### ISSUE TITLE
Tab completion broken when file names contain underscores.

### ISSUE THREAD

**Issue by z5h** [robbyrussell/oh-my-zsh#1398]
e.g.
```
mkdir test
touch a.z b.z c.z d.z a_.z b_.z c_.z
ls <tab>
```

on the first tab you see

```
ls .z
```

on the second, you see
```
a.z  b.z  c.z  d.z
```

files with underscores are not shown.

**Comment by Gravemind** [comment]
I took time to find (and understand) this bug, here is what I found:

The `r:|[._-]=*` matcher makes any completion with `.`, `_`, or `-` in file names useful when:

> to complete veryverylongfile.c rather than veryverylongheader.h [...] you can just type very.c before attempting completion. - http://zsh.sourceforge.net/Doc/Release/Completion-Widgets.html#Completion-Matching-Control

But really does not seem worth it: it makes any completion with `.`, `_`, or `-` in file names really annoying, and you already can type `very[TAB]c`.

So, here it fixes #1398, #4599, and #4063 (and keeps the other neat substring completion):
```diff
diff --git a/lib/completion.zsh b/lib/completion.zsh
index f5b2924712..85c892165d 100644
--- a/lib/completion.zsh
+++ b/lib/completion.zsh
@@ -12,14 +12,14 @@ zmodload -i zsh/complist
 
 ## case-insensitive (all),partial-word and then substring completion
 if [ "x$CASE_SENSITIVE" = "xtrue" ]; then
-  zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
+  zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'
   unset CASE_SENSITIVE
 else
   if [ "x$HYPHEN_INSENSITIVE" = "xtrue" ]; then
-    zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
+    zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
     unset HYPHEN_INSENSITIVE
   else
-    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
+    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
   fi
 fi
```

**Comment by khughitt** [comment]
:+1: Thanks for taking the time to look into that. This is still one of the biggest annoyances to date for me.

**Comment by protist** [comment]
I'm not sure why this has been closed? The changes haven't been committed, and this problem is still present three years after a fix was proposed. This also breaks completion for files with internal [hyphens](https://unix.stackexchange.com/questions/259287/how-can-i-get-zshs-completion-working-in-the-middle-of-the-filename).

FWIW I could put either fix's `zstyle…` line in `~/.zshrc` after sourcing OMZ, and this worked fine.

**Comment by paddor** [comment]
I have these files:

* `zproject.gsl`
* `zproject_ruby.gsl`
* `zproject_java.gsl`
* ...

When i type `zp<tab>`, it completes to `zproject.`, and another tab completes the whole argument to `zproject.gsl`, completely skipping the `zproject_*.gsl` files. I guess this is due to the same bug?

Please, please fix this.

**Comment by mcornella** [comment]
#5435 fixes this, I guess I can merge it immediately given that you've been running with that since January. Thanks guys!

**Comment by wks** [comment]
I have quite some files that look like `foo-bar-baz`, `foo-day-err`, `foo-day-ess`, etc. I could type `f-b-b<TAB>` to get `foo-bar-baz` and type `f-d-er<TAB>` to get `foo-day-err`. It is quite convenient. But it no longer works after this change has been merged.

I can workaround this by adding `zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'` into my `.zshrc`. But is `f-b-b` -> `foo-bar-baz` supposed to work at all, or is it just a side-effect of some other features? I find it quite handy in my use case.

**Comment by Gravemind** [comment]
@wks, look at https://github.com/robbyrussell/oh-my-zsh/issues/1398#issuecomment-169163149.

Yes, this fix intentionally broke `f-b-z` -> `foo-bar-baz`. It was the `r:|[._-]=*` basically saying that any `.`, `_`, or `-` should match any character in the completion, _I think_ it transforms `f-b-z` to `f*b*z` to match completion candidates.

So yes, `zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'` in your .zshrc (after `source $ZSH/oh-my-zsh.sh`) should re-enable it.

**Comment by mcornella** [comment]
@wks see this comment for a solution: https://github.com/robbyrussell/oh-my-zsh/issues/5470#issuecomment-250155435

**Comment by Gravemind** [comment]
I am looking to properly fix this issue, without breaking completion of https://github.com/robbyrussell/oh-my-zsh/issues/1398#issuecomment-249771828, #5435 , and #5560.

But now I think I better understand the issue and `matcher-list`, I cannot choose between 2 solutions, and **I need to ask you** (anyone):

For example, having the files `www`, `wine`, and `downloads`, if you did:
```
ls w<tab>
```
**Would you want to see `downloads` in the list or not ?**


For short, I cannot decide between the safest solution (does not hide any candidates):
```
 zstyle ':completion:*' matcher-list 'r:|=* r:|[._-]=* l:|=*'
```
Or, a "refinement" that suggests only "beginning with" candidates first (`downloads` comes back if `ls wn<tab>`):
```
zstyle ':completion:*' matcher-list 'r:|=*' '+ r:|[._-]=* l:|=*'
```

(I did not bring both full diff `lib/completion.zsh` to not pollute the post)

**Comment by paddor** [comment]
Me personally, I would not like to see `downloads` if I've only typed `ls w<tab>`. It just doesn't make sense. In case of `ls wn<tab>`, it would make more sense, being an actual, multi-character part of `downloads`.

**Comment by Gravemind** [comment]
Ok, after "real world" testing, I also find the "hide downloads" best.
And it is the current behavior of oh-my-zsh so it does not breaks the "omz completion experience".

So, here is my proposal: Properly fixes #1398, #4063, and #4599. Re-enables partial words (hyphen, underscore, and dot separated words) fixing https://github.com/robbyrussell/oh-my-zsh/issues/1398#issuecomment-249771828, #5560, and https://github.com/robbyrussell/oh-my-zsh/pull/5435#commitcomment-19315117. And fix insensitive completion (found no omz issues, but found some stackoverflow):

```diff
diff --git a/lib/completion.zsh b/lib/completion.zsh
index bbd0216565..2f274967c1 100644
--- a/lib/completion.zsh
+++ b/lib/completion.zsh
@@ -13,14 +13,15 @@ setopt always_to_end
 bindkey -M menuselect '^o' accept-and-infer-next-history
 zstyle ':completion:*:*:*:*:*' menu select
 
-# case insensitive (all), partial-word and substring completion
+# complete on the right side only, and if there are no candidates,
+# then also look for partial-word and left side completion
 if [[ "$CASE_SENSITIVE" = true ]]; then
-  zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'
+  zstyle ':completion:*' matcher-list 'r:|=*' '+ r:|[._-]=* l:|=*'
 else
   if [[ "$HYPHEN_INSENSITIVE" = true ]]; then
-    zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
+    zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-} r:|=*' '+ r:|[._-]=* l:|=*'
   else
-    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
+    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z} r:|=*' '+ r:|[._-]=* l:|=*'
   fi
 fi
 unset CASE_SENSITIVE HYPHEN_INSENSITIVE
```

Here is the explanation of the fix:
`matcher-list` matchers are evaluated in order one by one, and **stops at the first matcher having candidates**.
Pre-#5435 the partial words completion [1] was in the matcher list *before* the matcher for substring completion [2]. So, if a completion on the left-side added one of `._-`, then, the next `<tab>` would stop at the "magic dash" matcher (if matches) and suddenly would not look for left completion (showing less candidates than the first `<tab>`).

[1]: partial word is `r:|[._-]=*` for `ls ~/.o-m-z<tab>`
[2]: substring works with `l:|=*` that makes completion on the left side

The fix puts **"magic dash" and substring in the same matcher**, so all candidates from both are always shown, so no surprises where candidates disappear on the second tab.

**Fix bonus: makes insensitive completion insensitive all the way**: try `touch fooKbar` `ls k<tab>`. The fix adds `+` to make the second matcher include the previous one, so the "partial word dash+substring" matcher become also insensitive, it was not before.

**Comment by mcornella** [comment]
I'm also working on having a better default that works for everybody. So far, I found [this proposal from stackoverflow](http://stackoverflow.com/a/25556544/5798232) that enables fuzzy matching and it also works for the original files that had issues completing (https://github.com/robbyrussell/oh-my-zsh/issues/1398#issue-8184366).

For now you can use this (add it at the end of your zshrc file), until I have the proper time to test each candidate, read up on @Gravemind's proposal and present a viable PR.
Enjoy and report back any issues:

```zsh
zstyle ':completion:*' matcher-list 'r:[[:ascii:]]||[[:ascii:]]=** r:|=* m:{a-z\-}={A-Z\_}'
```

**Comment by mcornella** [comment]
Also, subscribe to #5560 for updates on this particular issue.
