### ISSUE TITLE
history-substring-search doesn't work after update to Ubuntu 12.10 [has workaround]

### ISSUE THREAD

**Issue by seriyps** [robbyrussell/oh-my-zsh#1433]
history-substring-search just doesn't work since I update my distro from 12.04 to 12.10.
I mean that when I type smth, eg `ls ` and press up-arrow button, it shows me last history item, not started from `ls `.

My .zshrc
```
$ cat .zshrc | grep -v -E "^# .*"
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="clean" # fletcherm
plugins=(git history-substring-search command-not-found)
source $ZSH/oh-my-zsh.sh
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
```
ZSH version
```
$ zsh --version
zsh 5.0.0 (i686-pc-linux-gnu)
```

**Comment by robbyrussell** [comment]
Going to close this one out... and hope that it's resolved for folks. (we can open up new issues as necessary)

**Comment by gravis** [comment]
I'm having this issue since a few days, on Debian, and Mac OS 10.10.3. None of the tips above is working.

**Comment by cchamberlain** [comment]
For me it appeared to be something I did corrupted the .zcompdump / .zcompdump.zwc files on Mac.  I trashed the files and restarted and my issue appears to be gone.

**Comment by billcarroll** [comment]
broken on OS X again for me after the last update

**Comment by akoo1010** [comment]
also running into the issue

**Comment by donnykurnia** [comment]
I'm running just fine in OSX under gnu screen inside iTerm. Try to close all screen and iTerm and start again after update zsh and oh-my-zsh.

**Comment by sgsvenkatesh** [comment]
This started happening again with zsh recent update. None of the above mentioned suggestions are working. No `.zshenv` file in my machine.

zsh 5.0.8 (x86_64-apple-darwin15.0)
OS X El Capital 10.11.6

Can someone please point me to the solution?

**Comment by sgsvenkatesh** [comment]
I think `_zsh_highlight` should be used carefully by checking if it is available. Here is the [line reference](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/history-substring-search/history-substring-search.zsh#L255).

Commenting out this line, works as a workaround for this problem. But I hope there will be a release will the fix.

**Comment by shadowhand** [comment]
Same error here.

**Comment by sgsvenkatesh** [comment]
@shadowhand The issue as resolved for me a few weeks back after updating zsh to the latest version. You should try it.

**Comment by shadowhand** [comment]
This happened after upgrading to current master. Appears to have gone away again.

**Comment by braindead** [comment]
Same issue on osx. Commenting out line (151)[https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/history-substring-search/history-substring-search.zsh#L255] worked for me!
