### ISSUE TITLE
OS X: Opening New Tab Doesn't Always Stay in the Same Directory

### ISSUE THREAD

**Issue by jprichardson** [robbyrussell/oh-my-zsh#1527]
This just started happening a few months ago. For some reason if I navigate to any directory or subdirectory in my `~/Dropbox/Projects` when I open a new tab in Terminal.app it doesn't stay in the same directory but goes back to my home directory. 

Now, if I do this switch to an old commit: https://github.com/robbyrussell/oh-my-zsh/commit/99468cb4ec38f11b78ac71cae0c9ac70ac0a516e (random old commit)

```
cd ~/.oh-my-zsh
git checkout -b old-branch 99468cb4ec38f11b78ac71cae0c9ac70ac0a516e
```
Close Terminal and reopen it, everything works as expected. If I checkout the `master` branch of `oh-my-zsh` again and close Terminal and reopen it, the problem occurs again.

This happens with or without the `osx` plugin. This only happens in some directories in my home directory. Maybe it has something to do with path length? I'm unsure now.

Oh ya, this happens on both Lion and Mountain Lion.

Any thoughts on the problem?

**Comment by mcornella** [comment]
Are you guys using iTerm2? Can you upgrade and check if it's solved? (we pushed a recent solution)

**Comment by jprichardson** [comment]
No, I was just using the Terminal.app. I can't remember how I fixed the
issue... either downloaded a new version or reverted to an old version.

On Tue, Feb 10, 2015 at 4:18 PM, Marc Cornellà <notifications@github.com>
wrote:

> Are you guys using iTerm2? Can you upgrade and check if it's solved? (we
> pushed a recent solution)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/1527#issuecomment-73796311>
> .
>



-- 
Simple & Secure Bitcoin Wallet: <https://www.coinbolt.com>
https://www.coinbolt.com
Bitcoin / JavaScript: <http://cryptocoinjs.com> http://cryptocoinjs.com
Follow JP Richardson: <https://twitter.com/jprichardson>
https://twitter.com/jprichardson

**Comment by mcornella** [comment]
Would you mind trying the newest release? You can backup your existing installation just in case.

**Comment by mcornella** [comment]
Hey! I mistook iTerm2 for Terminal.app. See https://github.com/robbyrussell/oh-my-zsh/issues/3570#issuecomment-73943556 for a working solution (you'll have to upgrade though).
