### ISSUE TITLE
git-flow plugin isn't working

### ISSUE THREAD

**Issue by phillipadsmith** [robbyrussell/oh-my-zsh#1717]
I've completely re-installed zsh, oh-my-zsh, and git-flow several times to no avail. After the last upgrade to git (using homebrew) the git-flow completion stopped working. Typing `git flow [tab]` doesn't offer any completions like `feature` or `release` or what-have-you. Totally banging my head against a wall on this one. :(

**Comment by wildjcrt** [comment]
@azu NICE! you save me, too.
@stevenjlho I think git-flow plugin isn't working because we installed git with completions and then git flow plugin can't override it.

**Comment by zx1986** [comment]
@azu You save my life!

**Comment by alinz** [comment]
@azu Thank you it worked for me.

**Comment by ikhoon** [comment]
@azu You save my fingers!

**Comment by jasperkennis** [comment]
This issue seemed to just start out of nowhere for me today. Fixed it by removing the brew version of git.

**Comment by cdekok** [comment]
not working for me with:

$ brew uninstall git
$ brew install git --without-completions

**Comment by Falkor** [comment]
as for @cdekok ;( 
no longer any git flow completion working once `git flow` is reached ;(

**Comment by cdekok** [comment]
The only thing that worked for me was to install: https://github.com/petervanderdoes/git-flow-completion

**Comment by codeHatcher** [comment]
@azu worked for me! Thanks!

**Comment by jwkicklighter** [comment]
Still an issue, and @azu's fix still works. Should this be added to the git-flow plugin readme?

**Comment by bensleveritt** [comment]
@jwkicklighter I think so. Same thing again.

**Comment by kodemaan** [comment]
@cdekok that worked for me, thanks
