### ISSUE TITLE
github plugin errors after updating

### ISSUE THREAD

**Issue by omares** [robbyrussell/oh-my-zsh#1727]
Hey,

after updating to the latest version of oh-my-zsh (git hash `85426a57a2561f675a6ad51754d6687c3ec571c2`) i get following erros when opening a new console when the `github` plugin is enabled:

```
(anon):6: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
```

**Comment by devinrhode2** [comment]
I wish I could use the `gitfast` plugin with `github` instead of `git`

git it

**Comment by bric3** [comment]
Hi I don't want to brag about my fork, but I gave up on the git utils of oh-my-zsh to use **oh-my-git**, unfortunately it wasn't integrating well with oh-my-zsh, and it has other issues, that's why I forked the project here https://github.com/bric3/oh-my-zsh-git

And use it on a daily basis, so far it's been around a year that I use on a big project it it's fairly stable and _imho_ fast.

https://camo.githubusercontent.com/62bdfd2e67c91fcaa4eee39be17c7de595ea5489/687474703a2f2f62726963332e6769746875622e696f2f6f682d6d792d7a73682d6769742f696d616765732f6f682d6d792d6769742e696e2e616374696f6e2e706e67

**Comment by djui** [comment]
Sorry for warming this one up, but the issue is back with OSX 10.11 _El Capitan_ but this time git doesn't currently compile:

```
(anon):6: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
```

```
$ brew install git --without-completions
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.4.3.tar.xz
Already downloaded: /Library/Caches/Homebrew/git-2.4.3.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.4.3 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1
1 error generated.
make: *** [levenshtein.o] Error 1
make: *** [list-objects.o] Error 1
1 error generated.
make: *** [line-log.o] Error 1
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Sandbox breaks Git compile (https://github.com/Homebrew/homebrew/issues/38978)
Install man / help page for git-subtree (https://github.com/Homebrew/homebrew/issues/40522)
heroku-toolbelt = heroku client + foreman + git (https://github.com/Homebrew/homebrew/issues/40379)
git-annex broken after latest update (https://github.com/Homebrew/homebrew/issues/40263)
git-big-picture: new formula v0.9.0 (https://github.com/Homebrew/homebrew/pull/36812)
when i update my homebrew use git clone ,i can't open my iterm2 (https://github.com/Homebrew/homebrew/issues/40748)
always gives error when search "Error: Failed to connect to: https://api.github.com/repos/Homebrew/homebrew-binary/git/trees/HEAD?recursive=1" (https://github.com/Homebrew/homebrew/issues/40805)
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

I guess we need to wait for a fix...

**Comment by peralmq** [comment]
Successfully solved this issue on Mac OSX by following the steps in https://github.com/robbyrussell/oh-my-zsh/issues/1727#issuecomment-112825937 but with the `brew install git --without-completions` now, so I'm guessing the previous compile issue has been fixed.

**Comment by vkravets** [comment]
Confirmed, solution with brew install git --without-completions resolve the issue on the release of 10.11

**Comment by cjwilburn** [comment]
I was able to solve the problem by removing the github plugin.

**Comment by apjanke** [comment]
There's a PR #4443 that I think will fix this issue. It looks like one of the underlying issues is that the `github` plugin is out of date with respect to the current version of `hub`. I think merging that, and making sure you're running a current version of `hub`, will clear a lot of this up.

**Comment by ziaulrehman40** [comment]
Reinstalling git fixed issue on ubuntu 18, I had upgraded zsh to 5.5.1 to fix some crashes on auto complete, than started getting this error. Hopefully no new error will pop up now.

**Comment by hntddt123** [comment]
For the solution I found that worked

Add this line
`setopt PROMPT_SUBST`

Remove this line
`source ~/git-completion.zsh`
