### ISSUE TITLE
git-extras plugin is not working when having gitfast plugin enabled

### ISSUE THREAD

**Issue by mbauhardt** [robbyrussell/oh-my-zsh#1746]
Hi.

* enable git plugin
* enable gitfast plugin
* enable git-extras plugin
* <code>git checkout [tab]</code> shows all branches, is working very fast (thx to gitfast)
* <code>git feature [tab]</code> do not show any branch or the completion to the <code>finish</code> parameter.

marko

**Comment by mcornella** [comment]
Can you tell me if this is still happening? It's been a long time since you last posted this...

**Comment by mbauhardt** [comment]
I never tried it out again. because the `git` plugin is now fast enough for me. No idea why the `git` plugin  is now very fast. Maybe someone pushed some improvements or my new macbook is responsible for this.
I also do not use the git extras plugin because we have another workflow.

Sorry, not really a helpful answer. ;)

**Comment by jpscharf** [comment]
If you enable both ```git-flow-avh``` and ```git-extras``` only one plugin will function with tab completion.

**Comment by mcornella** [comment]
@jpscharf can you look at #3408?
@mbauhardt please close this, then. We'll continue discussion in the linked above PR.
