### ISSUE TITLE
history-substring-search has a non-plugin-like README

### ISSUE THREAD

**Issue by zodiac** [robbyrussell/oh-my-zsh#1832]
The history-substring-search README contains this line

```
To activate this script, load it into an interactive ZSH session:
  % source history-substring-search.zsh
```

Which is confusing, because the proper way to activate it is to edit the ``~/.zshrc`` file's plugins variable

``plugins=(... history-substring-search)``

**Comment by mcornella** [comment]
Minor issue but easily solved. Care to provide a PR?

**Comment by mcornella** [comment]
:+1:
