### ISSUE TITLE
taskwarrior plugin autocompletion produces segfault

### ISSUE THREAD

**Issue by chmue** [robbyrussell/oh-my-zsh#2044]
When I use the autocompletion function from the taskwarrior plugin (`task [tabtab]`) zsh crashes with a segmentation fault.

I am using zsh 5.0.2 (archlinux) and an up to date version oh-my-zsh.

If you need additional debug info, I am happy to help.

**Comment by mcornella** [comment]
Obsolete? The segfault might not happen again but the first completion is not triggered. Adding a `_task` statement at the end of the `_task` file will make it work, as @pdvyas suggested.

**Comment by xtaran** [comment]
At least the segfault has been fixed in zsh in September 2013 in the commit zsh-users/zsh@844e569b632fc032576edc039f793be47fde724e.

**Comment by chmue** [comment]
@mcornella Yes, as far as I am concerned the issue is obsolete. I'm using the fix @pdvyas suggested  and it works very well for me. Sorry for never posting back.

**Comment by elliottw** [comment]
strange, i'm using ubuntu 14.4 zsh 5.0.2 and just installed oh-my-zsh and getting same error when tab completing.
