### ISSUE TITLE
System wide RVM and ZSH

### ISSUE THREAD

**Issue by raffone** [robbyrussell/oh-my-zsh#2051]
Hi, I've installed oh-my-zsh for a user on a server that have a system-wide rvm installation (/usr/local/rvm/..), everything works except the rvm rubyver@gemset text doesn't show up. I've tried cleaning the path= in .zshrc but doesn't work.  

Unfortunately is not possible to uninstall rvm and install it to the single user. Is there a way to make rvm and zsh to talk each other?

Thanks

**Comment by robbyrussell** [comment]
Closing for now. Someone can send a PR
