### ISSUE TITLE
(eval):1: command not found: _tmux

### ISSUE THREAD

**Issue by ganglio** [robbyrussell/oh-my-zsh#2092]
After installing the tmux plugin whenever I type tmux on the command line and then hit the tab button instead of showing the available commands it displays a pretty ugly:

> (eval):1: command not found: _tmux

Any clue how to fix this?

Ciao,
r-

**Comment by kumasento** [comment]
@ganglio Hey I have the same issue like you. I've fixed it by:

1. Delete the .oh-my-zsh folder
2. Delete the .zcomdump* files
3. Reinstall oh-my-zsh

And then tmux autocompletion works.

**Comment by Gisleburt** [comment]
For the sake of others, the original solution works, BUT, don't forget to restart your shell.
```
$ ~/.zcomdump*
$ upgrade_oh_my_zsh
```
quit shell, go back in, all is good.

I was suffering this problem with `kubectl`. No idea why, but glad it's fixed. 👍 Thanks to everyone above.

**Comment by aboqasem** [comment]
A oneliner that worked for me.

```shell
rm -rf ~/.zcompdump* && exec zsh
```
