### ISSUE TITLE
dircycle plugin works incorrect

### ISSUE THREAD

**Issue by vas7** [robbyrussell/oh-my-zsh#2101]
My problem is in pushd number arguments.
If I change dircycle commands from this:
```bash
pushd -q +1 # Left
pushd -q -0 # Right
```
to this:
```bash
pushd -q -1 # Left
pushd -q +0 # Right
```
then plugin works well.
Before I could use dircycle without any correction, so I think it is only my problem.

**Comment by mcornella** [comment]
Hi @vas7 check out my PR #3413

**Comment by vas7** [comment]
I switched to your branch and plugin now work sperfect. Thank you.
