### ISSUE TITLE
Vi mode

### ISSUE THREAD

**Issue by daGrevis** [robbyrussell/oh-my-zsh#2103]
1. How can I set normal mode as default mode?
2. How can I remap <C-c> (Ctrl - c) to go back to normal mode?

**Comment by mcornella** [comment]
Is this still relevant? Perhaps a vi-mode user could chime in...

**Comment by dragonxlwang** [comment]
any solution to this?

**Comment by mcornella** [comment]
If you want to be by default in normal mode (also known as emacs mode), you can append the following to your zshrc file:
```
bindkey -e
```

Remaping `CTRL`+`C` is not possible that I know of, but you can remap some other key sequence.
Here's an example:
```zsh
use-emacs-keymap() { bindkey -v }
zle -N use-emacs-keymap
bindkey ^G use-emacs-keymap # CTRL+G
```

You would put that on your zshrc file as well.
