### ISSUE TITLE
gpg-agent plugin should check existence of ssh-agent before sourcing from GPG_ENV file

### ISSUE THREAD

**Issue by eakret** [robbyrussell/oh-my-zsh#2121]
The gpg-agent plugin needs to check for the existence of an ssh-agent before sourcing the `GPG_ENV` file. The `GPG_ENV` file potentially contains `SSH_AUTH_SOCK` and `SSH_AGENT_PID` for an old gpg-agent started with `--enable-ssh-support`. In this case, sourcing the file and then checking for ssh-agent's existence results in a failure since the `ssh-add -l` check uses the stale environmental variables from `GPG_ENV` rather than the current values of the live ssh-agent.

**Comment by mcornella** [comment]
Triaged.
