### ISSUE TITLE
cd function screws with output

### ISSUE THREAD

**Issue by andsens** [robbyrussell/oh-my-zsh#2130]
The `cd` function in `lib/directories.zsh` outputs non visible characters, which can screw with a lot of things.
Try running:
```
echo -n $(cd /some/long/path) | wc -c
```

Expected result: 0
Actual result: A number higher than 0

This interferes with functions which execute things like:
```
local root=$(cd $file_dir; pwd)
local rel_path=${abs_path#$root}
```
`$root` will not be removed from `$abs_path` because of the non visible characters.

**Comment by mcornella** [comment]
It was merged! This can be closed now :)
