### ISSUE TITLE
Completion for git-flow doesn't work

### ISSUE THREAD

**Issue by ngocphamm** [robbyrussell/oh-my-zsh#2147]
I'm not so sure why but I put `git git-flow` into plugin list. The `git <tab>` trigger argument suggestions but `git-flow <tab>` just list files and folders.

Someone please help. Thanks!

**Comment by mcornella** [comment]
Did you figure it out?

**Comment by ngocphamm** [comment]
Errr. I kind of forgot about this. Don't use oh-my-zsh anymore. Sorry!

**Comment by mcornella** [comment]
Ok, please close the issue then. Thanks for trying it out!
