### ISSUE TITLE
Move wiki to sphinx

### ISSUE THREAD

**Issue by darayus** [robbyrussell/oh-my-zsh#2158]
Using sphinx for documentation would both be easier to browse and to maintain through pull requests. Pull requests that modify functionality or add features could also directly contain the updated documentation so that both get updated if the PR is merged.

I would be able to assist merging the wiki over to sphinx through an initial pull request. Sphinx can be found at http://sphinx-doc.org/.

**Comment by robbyrussell** [comment]
@darayus One of things that I'd like to see happen is have more documentation within the actual code base (in individual README.x files for each plugin).
