### ISSUE TITLE
Taskwarrior tab completion crashes the terminal

### ISSUE THREAD

**Issue by masterkorp** [robbyrussell/oh-my-zsh#2187]
Using rxvt-unicode 9.18-7
zsh 5.0.2-4
taskwarrior 2.2.0
lastest oh-my-zsh

As soon as TAB is pressed on task it just crashes, nothing on tty.

**Comment by mcornella** [comment]
Solved in the current oh-my-zsh. Please close

**Comment by nordam** [comment]
I also experience this issue. If I type "task " and press tab, the terminal crashes. If I type for example "task project:" and press tab, it lists my projects as expected.

Using zsh 5.4.1, taskwarrior 2.5.1 and newest oh-my-zsh.
