### ISSUE TITLE
vi-mode plugin makes zsh painfully slow in OSX Mavericks

### ISSUE THREAD

**Issue by sammynammari** [robbyrussell/oh-my-zsh#2189]
in `.zshrc`:

```
plugins=(vi-mode)
```
zsh is now extremely slow

```
plugins=()
```
zsh now behaves normally

**Comment by robbyrussell** [comment]
If you hit this...

`brew install git`

**Comment by mdentremont** [comment]
OMG, forgot about this and it was driving me nuts on a laptop I just configured :)

**Comment by Leland** [comment]
Switching to homebrew's Git resolved this for me as well, but I'm curious why. Anyone have an idea as to why Mac's pre-rolled version of Git is giving ZSH so much trouble?

**Comment by hugofcampos** [comment]
Tested in Yosemite (10.10.3), installing git 2.4.3 with brew, same great results :+1:

**Comment by crunk1** [comment]
+1 to installing git 2.4.3 homebrew.

**Comment by stuartcarnie** [comment]
Same problem in 10.11 too; don't use Apple's version of `git`

**Comment by dani-h** [comment]
Experienced the same issue in El Capitan 10.11. Installing git using brew solved the problem.

**Comment by adjohnson916** [comment]
+1 Fixed on OS X 10.9.5 Mavericks by replacing native Apple Git 1.9.3 with Git 2.5.1 from homebrew.

**Comment by dariuszlesniak** [comment]
+1 Fix for brew install git

**Comment by hank** [comment]
This also fixed my issue, but wouldn't it be better to add a command to zsh that would allow the functionality for vi-mode but not reset every plugin in the process (eg. git)?

**Comment by longlinht** [comment]
I also encounter same problem, I only use git and vi-mode plugin, I fixed it by comment a line in .oh-my-zsh/plugins/vi-mode/vi-mode.plugin.zsh

``zle reset-prompt``

**Comment by Adrian-Grimm** [comment]
> I also encounter same problem, my environment is
> 
> `Yosemite 10.10.5`
> `Git 2.3.2 (Apple Git-55)`
> 
> I only use git and vi-mode plugin, I fixed it by comment a line in .oh-my-zsh/plugins/vi-mode/vi-mode.plugin.zsh
> 
> `zle reset-prompt`

not perfect but 100% faster switch between the vi-modes...
(under WSL Ubuntu on Windows 10 1809)
