### ISSUE TITLE
Can't override git through custom/something.zsh

### ISSUE THREAD

**Issue by wildeyes** [robbyrussell/oh-my-zsh#2203]
This was posted here:  http://unix.stackexchange.com/questions/97938/oh-my-zsh-overriding-my-function

Copy:
I use ZSH with Oh My Zsh and I am trying to define a function called `git`, as such:

    function git() { echo "I'm happy because I am executed!" }

I have placed the function definition in `$ZSH/custom/general.zsh`.

Everything else in this file works (I have a bunch of aliases there) except this function.

Running `which git` outputs:

    git () {
        case $1 in
            (commit|blame|add|log|rebase|merge) exec_scmb_expand_args "$_git_cmd" "$@" ;;
            (checkout|diff|rm|reset) exec_scmb_expand_args --relative "$_git_cmd" "$@" ;;
            (branch) _scmb_git_branch_shortcuts "${@:2}" ;;
            (*) "$_git_cmd" "$@" ;;
        esac
    }

Removing `git` from `plugins=( ... )` didn't work. Trying to find this function in Oh My Zsh yielded no results. 

I read the source code of `oh-my-zsh.sh`, and it seems the `custom` directory is loaded after all of OMZ's files, so it didn't make any sense to me, that when I placed my function **at the bottom of** `.zshrc` it worked.

Any Ideas on how to keep the function in the `custom` folder? I would like to keep things organized.

**Comment by mcornella** [comment]
Do you still need help?
