### ISSUE TITLE
virtualenvwrapper does not activate env when changing into directory

### ISSUE THREAD

**Issue by noisufnoc** [robbyrussell/oh-my-zsh#2395]
Hello!

The virtualenvwrapper plugin does not seem to be activating the env when I change into the project directory, as expected.  The project directory name is the same as the environment, and I have tried disabling all other plugins to prevent any type of incompatibilities.

**Comment by mcornella** [comment]
As is, the plugin only works in the following conditions:
1. You're in a git repository
2. You have a `.venv` file indicating the name of the virtualenv or a `.venv` directory containing the virtualenv files.

If neither of these conditions are met, `$PROJECT_ROOT` is set to `.`, therefore `$ENV_NAME` won't be set. Do these conditions apply to you?
