### ISSUE TITLE
Copying code from zsh-completion and other projects

### ISSUE THREAD

**Issue by co-dan** [robbyrussell/oh-my-zsh#2439]
I was wondering if it's possible/allowed to copy code from https://github.com/zsh-users/zsh-completions to plugins? It seems easier than maintaining a separate version of plugins that provide completion?

zsh-completion files uses BSD3, while oh-my-zsh is licensed under MIT, I am not sure if that is a problem though

**Comment by mcornella** [comment]
Not the way we want to go. Please cllose this issue
