### ISSUE TITLE
Ubuntu/XFCE keyboard Layout being reset....

### ISSUE THREAD

**Issue by simoncruddas** [robbyrussell/oh-my-zsh#2447]
Ubuntu 12.04 LTS
zsh 4.3.17
XFCE 4.8
latest .oh-my-zsh

Seems if I enable .oh-my it resets my keyboard layout basically dropping most of the extended keyboard (insert, page up and down)

Only using the XFCE keyboard editor and changing the layout gets it back...

Any help? Any more info needed?

**Comment by mcornella** [comment]
Hi @simoncruddas, sorry for the delayed response. Can you upgrade oh-my-zsh and try it out again? Also, post the output of `infocmp` please
