### ISSUE TITLE
Git plugin conflicts with GNU coreutils on Mac

### ISSUE THREAD

**Issue by srinivasanv** [robbyrussell/oh-my-zsh#2463]
Not sure if this is the right place to say it - just wanted to point it out somewhere.

The git plugin (included) aliases strings starting with g to git commands. For example, gwc is aliased to 'git whatchanged'. However, on most Mac systems with GNU coreutils installed from a package manager such as Homebrew, gwc would refer to the GNU version of wc (http://linux.die.net/man/1/wc).  Installing oh-my-zsh results in gwc and some others to not work.

Figured I'd let you know, that's all.

**Comment by patkujawa-wf** [comment]
Ugh, I was pulling my hair out trying to figure out why `gwc` suddenly disappeared!

**Comment by ncanceill** [comment]
Sorry, the admitted policy is that aliases should not override commands.

We are working on a safe aliasing system in order to avoid those situations.

If you do not use GNU `wc`, you can still add `gwc` as a custom alias.
