### ISSUE TITLE
filename autocompletion doesn't work for make

### ISSUE THREAD

**Issue by paulhkulla** [robbyrussell/oh-my-zsh#2503]
When doing "make <tab>" filename completion is not triggered. Nothing happens.

When I remove line 53 from oh-my-zsh.sh
compinit -i -d "${ZSH_COMPDUMP}"

then the default zsh filename completion works when tabbing after "make ". This just goes to show that the problem is with oh-my-zsh overriding the completion. Can someone advise why it doesn't work at the moment (this issue might not only exist for make but other commands as well so worth looking into, I think).

**Comment by mcornella** [comment]
This can be closed, then. Thanks Nicolas
