### ISSUE TITLE
gradle plugin assumes alias

### ISSUE THREAD

**Issue by knagelbergsfdc** [robbyrussell/oh-my-zsh#2505]
At https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/gradle/gradle.plugin.zsh#L85

it attempts to execute 'gradlew'. I believe you need to execute './gradlew', as this plugin only works for me when I alias gradlew="./gradlew"

**Comment by mcornella** [comment]
If you put it in a directory included in `$PATH` you don't need to have the `./`, but I agree to what you imply that the alias should be included in the plugin.

**Comment by robbyrussell** [comment]
@knagelbergsfdc Want to submit a PR?
