### ISSUE TITLE
Display running time if command work more then $value sec.

### ISSUE THREAD

**Issue by korjavin** [robbyrussell/oh-my-zsh#2575]
Hello,

I am not sure, is it approtiate place for this feature request, but anyway

Is it possible to add some config value max_time into zsh.rc for controling max time of execution without show running time.

```
max_time=20

$ls
rw-r--r--  1 root root 3,0M aa
rw-r--r--  1 root root 3,0M ab
$
$dd if=.....
...
running time 1h 10m
$
```

**Comment by mcornella** [comment]
@korjavin, look at PR #3301 for a very well put proposal.
