### ISSUE TITLE
Arrow up symbol for for branch ahead Git repo 

### ISSUE THREAD

**Issue by galderz** [robbyrussell/oh-my-zsh#2666]
The default Git plugin for ZSH makes the prompt show when the branch is ahead. It uses an arrow up signal to indicate that. Would it be possible to have that in oh-my-zsh as well? 

Also if the branch is behind, it'd be great to have an arrow down symbol.

Cheesm

**Comment by mcornella** [comment]
There are some pull requests that provide that, for instance #2723. If you search some more I think you'll find more of them.

**Comment by apjanke** [comment]
This is supported now, and set on a per-theme basis. You can set its appearance by defining `$ZSH_THEME_GIT_PROMPT_AHEAD` and include it in the prompt using `$(git_prompt_ahead)` in the `$PROMPT` string. The themes `juanghurtado`, `sunrise`, and `wedisagree` do this. Or you can use them as examples to build your own theme that does so.

Same for `$ZSH_THEME_GIT_PROMPT_AHEAD` AND `$(git_prompt_ahead)`.
