### ISSUE TITLE
Conflict using 'dirhistory' and 'last-working-dir' plugin together

### ISSUE THREAD

**Issue by pablospe** [robbyrussell/oh-my-zsh#2675]
If you one plugin is active, the other one is not working properly. Actually, the last plugin in the plugin list will work ok but not the other (so, it depends in the order they are loaded).

One solution is to use only the 'last-working-dir' plugin and an alternative implementation of 'dirhistory' (I am not sure if this is equivalent, but it is working for me):

    # Alt+Left
    function insert-cycled-right () { zle push-line; pushd -q ~+0; zle accept-line }
    zle -N insert-cycled-right
    bindkey "^[[1;3C" insert-cycled-right

    # Alt+Right
    function insert-cycled-left () { zle push-line; pushd -q -1; zle accept-line }
    zle -N insert-cycled-left
    bindkey "^[[1;3D" insert-cycled-left

**Comment by mcornella** [comment]
Isn't it overkill having two plugins providing directory navigation? Also, I think you mean `dircycle` plugin instead of `dirhistory`. If by any chance that's true, try again because it was updated recently :wink:
