### ISSUE TITLE
Consider doing tagged releases using Semantic Versioning

### ISSUE THREAD

**Issue by psyrendust** [robbyrussell/oh-my-zsh#2678]
Automatic updates are great, but there really isn't a clean way to roll back to a specific version'd release other then checking out a hash tag. This project is big enough to consider using tagged releases, or at least creating release branches. This would make it more convenient to lock down a version of OMZ across machines.

**Comment by robbyrussell** [comment]
If you're aiming to lock down a version across machines, I would advocate that you fork it and install from your own managed repository. Then you can use tags to your hearts content... but I don't want to introduce extra steps into my own workflow for what I consider to be an edge case scenario. (
