### ISSUE TITLE
Git auto-complete not working on Zsh 5.0.5

### ISSUE THREAD

**Issue by chitsaou** [robbyrussell/oh-my-zsh#2683]
I installed zsh 5.0.5 via homebrew and found that git auto-complete is not working.

```
$ git add <tab>
```

It does not prompt any file, and cannot type anything anymore, until I press ^C.

If `chsh` to `/bin/zsh` (which is 5.0.2 on my OS X 10.9), it works normally.

**Comment by mcornella** [comment]
Please post the output of `print -l $fpath`, using both zsh 5.0.5 and 5.0.2. Also post the absolute path of the 5.0.5 binary.
