### ISSUE TITLE
xargs -r invalid on OSX

### ISSUE THREAD

**Issue by ryanwmarsh** [robbyrussell/oh-my-zsh#2692]
The alias in the git plugin uses the -r flag for xargs. This is invalid on OSX. 
`gwip='git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m "--wip--"'`

**Comment by mcornella** [comment]
Effectively solved and ready to close once #2790 is merged. Just leaving this comment to update the issue and get it out of the way to triage the rest...

**Comment by apjanke** [comment]
Looks like this was fixed by #2790. I don't see any remaining `xargs -r` uses in the repo. Could you confirm if this is fixed for you, and if so, close this issue?

**Comment by ncanceill** [comment]
Indeed this should be fixed now.
