### ISSUE TITLE
Number pad home key fails to function with gnome-terminal

### ISSUE THREAD

**Issue by Timesquare** [robbyrussell/oh-my-zsh#2698]
Gnome-terminal apparently uses different escape sequences for the normal home key and the home key located on the number pad. With the switch to using terminfo in 174c9177aa34b4c05bb5a1c6f637e6fa479a8e10 the number pad home key ceases to function.

**Comment by apjanke** [comment]
Still broken? What OS and gnome-terminal version are you folks running, and what's your `$TERM` value?

**Comment by Timesquare** [comment]
The number pad keys function as expected in gnome-terminal.

I'm not sure if it is a separate issue, the number pad function keys didn't and still don't work for urxvt.

**Comment by apjanke** [comment]
What OS and version are you running? (There's a lot of `urxvt`s out there.)

**Comment by apjanke** [comment]
Any chance this is on openSUSE? They have a nonstandard `rxvt-unicode` entry in their `terminfo` database. (See #2750.)

**Comment by mcornella** [comment]
I'm closing this because of a lack of a follow up. If this is still happening please reopen.
