### ISSUE TITLE
vundle plugin - commands soon to be deprecated

### ISSUE THREAD

**Issue by ajpaulson** [robbyrussell/oh-my-zsh#2794]
The current vundle plugin uses the original `BundleInstall` commands from the older version of vundle.

The vundle project is undergoing some updates and among these are extra commands and new commands to replace the old ones. 

At a minimum any commands already used in this plugin should be changed to their replacement commands.

**Comment by uberspot** [comment]
I added a commit that updates the vundle plugin in https://github.com/robbyrussell/oh-my-zsh/pull/3575 
Hope it's ok.

**Comment by ajpaulson** [comment]
Seems to be updated in a recent commit
