### ISSUE TITLE
command not found (hacluster, history and port_preexec)

### ISSUE THREAD

**Issue by jlvcm** [robbyrussell/oh-my-zsh#2823]
i was using ubuntu 12.04 and i've switched to ubuntu 14.04 and copied my old oh-my-zsh settings to it.. but now i'm getting this 3 errors when i start:

/home/jl/.oh-my-zsh/lib/completion.zsh:61: command not found: hacluster
/home/jl/.oh-my-zsh/lib/history.zsh:15: command not found: history
/home/jl/.oh-my-zsh/lib/termsupport.zsh:40: command not found: port_preexec

the hacluster and port_preexec command don't actually exist, and history is working just fine, i've tried to find something about hacluster and port-preexec with no luck.. am i missing something?

**Comment by robbyrussell** [comment]
Radio silence... closing
