### ISSUE TITLE
Options & Settings (variables/functions) Documentation

### ISSUE THREAD

**Issue by nfarrar** [robbyrussell/oh-my-zsh#2853]
I assume I'm just missing it - but I've been looking and cannot find documentation of the oh-my-zsh options (configurable variables, exported functions).

There are some variables referenced with some documentation in the zshrc.zsh-template file:

```
# CASE_SENSITIVE="true"
...
# ZSH_CUSTOM=/path/to/new-custom-folder
```

Is this a comprehensive list of the configurable variables? Are there oh-my-zsh "api" functions as well, documented somewhere else perhaps?

In the themes, I see lots of references to other configurable values as well - the most common seem to revolve around git, for example:

```
ZSH_THEME_GIT_PROMPT_PREFIX="${PR_RESET}${PR_RED}‹git:"
...
ZSH_THEME_GIT_PROMPT_UNTRACKED="${PR_RESET}${PR_YELLOW} ✭${PR_RESET}"
```

I checked the [git plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh) but I don't see any of these values referenced.

I then checked the [git lib](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh) and I see several git related functions defined and these variables are referenced. There appears to be some minimal documentation on the functions there.

I started hacking together my own prompt and started to add virtualenv support - there is no lib for virtualenv - but there is a plugin which contains:

```
function virtualenv_prompt_info(){
  if [[ -n $VIRTUAL_ENV ]]; then
    printf "%s[%s] " "%{${fg[yellow]}%}" ${${VIRTUAL_ENV}:t}
  fi
}

# disables prompt mangling in virtual_env/bin/activate
export VIRTUAL_ENV_DISABLE_PROMPT=1
```

I assume that I call virtualenv_prompt_info() to display the name of the virtualenv in my prompt, (haven't tried it yet), but I am unsure how it's being detected, or how I should be configuring the way in which it's displayed (colors, etc).

Is there a developer guide or similar documentation that provides information on how things in oh-my-zsh are done? A comprehensive list of variables/functions that can be used and how they should be used?

From the virtualenv & git examples above, XXXX_prompt_info seems to be a standard naming convention - is there some kind of oh-my-zsh magic that defines standard configurable values for these functions?

I apologize of these things should be self-evident and I'm just super dense. If documentation exists somewhere, can someone point me to it?

**Comment by apjanke** [comment]
There's now a [Design](https://github.com/robbyrussell/oh-my-zsh/wiki/Design) Wiki page which lists a lot of the relevant variables for the core OMZ stuff, which you can set in `.zshrc` to control its behavior. That and the other Wiki stuff, along with comments in individual plugins, is about as far as the documentation goes.

There's virtualenv support in OMZ now, from the `virtualenv`, `virtualenvwrapper`, and `autoenv` plugins. Have a look at those and add them to your plugin list.

**Comment by apjanke** [comment]
Have you had a chance to look at the Design wiki page? Does it cover what you're looking for here?
