### ISSUE TITLE
Themes not displaying ruby info in 10.10 Yosemite

### ISSUE THREAD

**Issue by jweaver60** [robbyrussell/oh-my-zsh#2858]
After upgrading to 10.10 Yosemite all of the themes which should display ruby info are leaving that prompt section blank. I'm using RVM and ruby 2.1.2.

**Comment by mcornella** [comment]
Hey @graf-abolmasov, do you remember what file you where pointing at? Github doesn't link anywhere now...

**Comment by mcornella** [comment]
Blast from the past... Ok, so the [change referred to is using `ruby_prompt_info`](https://github.com/robbyrussell/oh-my-zsh/compare/7f07fac...0222e77#diff-0dc1d11e542313c60edbb4f77d41bbafL14) which requires using one of the above mentioned plugins to have a working ruby prompt (`rvm`, `rbenv` or `chruby`). Closing.
