### ISSUE TITLE
Don't display Powerline icons after upgrading to OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by takahiro47** [robbyrussell/oh-my-zsh#2869]
After upgrading to OS X 10.10 Yosemite all of the themes which use "Powerline" don't display powerline icons.
Of cause, I tested to change iTerm2.app's font to 'Ricty Regular for Powerline', 'Inconsolata-dz for Powerline', 'Source Code Pro for Powerline', '' and so on.

※ on tmux, powerline icons has displayed that icons with no problems!

![2014-06-09 17 11 51](https://cloud.githubusercontent.com/assets/1147724/3214388/c9c17630-efad-11e3-9495-339ff996eecb.png)

**Comment by jonlambert** [comment]
Did this ever get resolved? I'm experiencing a similar issue at the moment on Yosemite 10.10.1 in Terminal. 

![w0t6k412lpgpup9zs5wlhm9gncruydobhcbq6ne79cw](https://cloud.githubusercontent.com/assets/856225/5795047/5a70721e-9f7e-11e4-861d-5c68f0490da7.png)

**Comment by schrepfler** [comment]
My zsh theme was actually corrupted, the special characters got encoded in something else (no idea why Yosemite would do that). Putting a new checkout of the theme solved the issue.

**Comment by jonlambert** [comment]
Hmm that's a good idea, but I just checked out the theme (and even re-cloned the .oh-my-zsh directory) to no avail! 
![screenshot 2015-01-19 12 35 07](https://cloud.githubusercontent.com/assets/856225/5800537/a9dc0594-9fd7-11e4-8a96-b8b5fb4b30c6.png)

**Comment by MartinRogalla** [comment]
Encountering the same problems with Iterm2 and default Terminal in Yosemite. Should be a Powerline/OSX specific problem since it also occurs when using vim-airline. Has anyone found a solution for this?

![screen shot 2015-01-23 at 14 59 19](https://cloud.githubusercontent.com/assets/1066157/5875716/73d57bec-a310-11e4-823f-ae2f6241b51a.png)

**Comment by seawatts** [comment]
Also seeing this same error

**Comment by jkenneydaniel** [comment]
Was this resolved? Having same problem - have tried reinstalling powerline fonts a million times... On Yosemite, with iTerm2.

**Comment by mclearc** [comment]
I've had similar problems. The only solution I've found is to use the unicode numbers. 

Symbol  |  powerline | vim-powerline
-----------|----------------|---------------|-
separator.left |  '' (\ue0b0) | '⮀' (\u2b80)
separator.right | '' (\ue0b2)  | '⮂' (\u2b82)
subseparator.left | '' (\ue0b1) | '⮁' (\u2b81)
subseparator.right | '' (\ue0b3) | '⮃' (\u2b83)
branch symbol | '' (\ue0a0) | '⭠' (\u2b60)
readonly symbol | '' (\ue0a2) | '⭤' (\u2b64)
linecolumn symbol | '' (\ue0a1) | '⭡' (\u2b81)

**Comment by jkenneydaniel** [comment]
I actually resolved this for myself after several frustrating hours of toying with Powerline and such. Essentially I had to go into Font Book and resolve "issues" with the powerline fonts I had installed (perhaps because I tried installing/reinstalling them several times? Either way - first install didn't work either). Inside Font Book I chose to allow it to repair the issue automatically for each font - the special characters now display correctly.

**Comment by jonlambert** [comment]
How come this has been closed? Has it been fixed?

**Comment by Aghassi** [comment]
I'm still having this issue on 10.10.2 and I just went through a fresh install process.

**Comment by mclearc** [comment]
I've continued to have this issue on 10.10.2, also after fresh install. jkenneydaniel's solution did not work for me (i'm also showing no sign in FontBook that there are unresolved issues.

**Comment by lgvalle** [comment]
Change the font on both ASCII and non-ASCII worked for me.

Seen here: https://github.com/powerline/fonts/issues/44

**Comment by Aghassi** [comment]
@lgvalle Thank you! This worked!

**Comment by jonlambert** [comment]
Can you explain further how you fixed it? What do you mean by "changing the font"?

**Comment by Aghassi** [comment]
@jonlambert go to preferences in iterm, go to profiles, then go to the fonts at the bottom and select a powerline font.

**Comment by georgesamy** [comment]
^ this worked for me, but for clarification, the steps on my version of iTerm were as follows:
) Go to preferences in iTerm
) Go to profiles
) Select Text then change the regular and non-ascii fonts to a powerline font

**Comment by iwrightcode** [comment]
^ Can confirm. I used 12pt Meslo LG L Regular for Powerline and it worked for me. Thanks all!

**Comment by zloban** [comment]
hi, I am using OS X 10.10 and iTerm2 to ssh and edit files on linux. still can't setup the fonts right.
Am I missing something in my configuration?
![screen shot 2015-05-28 at 16 06 30](https://cloud.githubusercontent.com/assets/164447/7860708/10a2e356-0554-11e5-8eb7-2607caa4d7c1.png)

**Comment by patbaker82** [comment]
@zloban Same for me - did you figure it out?

**Comment by juaprebo** [comment]
I found the solution: You must edit the theme file (i.e agnoster.zsh-heme) and change the original ones for these lines:

SEGMENT_SEPARATOR='\ue0b0'
and in prompt_git:

 echo -n "${ref/refs\/heads\//'\ue0a0' }$dirty"

That works for me.

**Comment by kaichih** [comment]
After choosing the powerline font, it works for me now. \o/

**Comment by Rafeh01** [comment]
# Got the powerline fonts to work. My agnoster theme is now working!
[![asciicast](https://asciinema.org/a/25402.png)](https://asciinema.org/a/25402)

@iwrightcode that worked for me thank you!
@lgvalle Thank you!
@georgesamy Thank you!

**Comment by Matthewspear** [comment]
Perfect, just changed the non-ascii and I've got mine working, thanks @georgesamy!!

**Comment by ivermac** [comment]
I cloned and installed the powerline fonts then changed my fonts in iterm2 and it worked for me. Thanks @georgesamy 
![image](https://cloud.githubusercontent.com/assets/1128227/9950693/c834c0ec-5dc5-11e5-92c1-a75d80f3d783.png)

**Comment by adeekshith** [comment]
@ivermac Woah!!! This worked. Thank you.

**Comment by mattjj** [comment]
Thanks @ivermac and @georgesamy (and everyone else)!

**Comment by Orthocenter** [comment]
@ivermac thx!

**Comment by satishd** [comment]
No need to change Regular font but Non-Ascii font should be changed to powerline font.

**Comment by bperucchi** [comment]
Sorry, but did try many resolution in this post but still not get icons correctly in prompt line.

![screen shot 2017-04-25 at 18 50 23](https://cloud.githubusercontent.com/assets/367967/25790991/9a9de74e-3393-11e7-8909-9d56e8e44c83.png)

**Comment by Willib** [comment]
iTerm2:
![dd4a7141-3be0-4e33-9181-d1f6e6e6e170](https://cloud.githubusercontent.com/assets/6252577/26089391/e9eb32f0-3a2f-11e7-9052-8b4b0612ee33.png)
![qq20170516-120604](https://cloud.githubusercontent.com/assets/6252577/26089425/3234d390-3a30-11e7-9822-303cde4ab6e1.png)

**Comment by mqliutie** [comment]
@georgesamy  Thank you, that works~

**Comment by gfilios** [comment]
Had the same issue. 
fixied it by setting POWERLEVEL9K_MODE="awesome-fontconfig" in .zshrc

**Comment by ewoks** [comment]
do I need to download Powerline fonts from somewhere?!

**Comment by snamoah** [comment]
@ewoks yeah... you can download it from here https://github.com/powerline/fonts

I got mine working also by changing to a powerline font

<img width="570" alt="Screen Shot 2019-03-12 at 9 12 49 am" src="https://user-images.githubusercontent.com/8088486/54188261-3ae7ae80-44a7-11e9-8b2f-68300d3f200f.png">

**Comment by big-hunter** [comment]
Sorry , I have no idea  about where the window is ? could you piont to way ?

> [snamoah](/snamoah)

**Comment by DanielPAdeCarvalho** [comment]
If anyone is having the same problem on another linux terminal, what solved for me was to change to a font that had powerline, like the ones in:
[https://github.com/powerline/fonts/tree/master](https://github.com/powerline/fonts/tree/master)
