### ISSUE TITLE
sub-project within a git repo cannot have custom .venv file

### ISSUE THREAD

**Issue by amontalenti** [robbyrussell/oh-my-zsh#2882]
Due to the way these lines of code are written:

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh#L13-L26

It's not possible to have a Git repo which contains a subfolder with a `.venv` file in that subfolder containing the virtualenv for that sub-project.

For example, I have a Git repo named "backend". It has two subfolders, "analytics" and "crawl". Each has a separate venv associated with it; by convention, I name them `backend+analytics` and `backend+crawl`. However, I can't put a separate `.venv` file in each subfolder because the zsh code will "walk up" to the project root directory and look for the file there.

**Comment by apjanke** [comment]
This is fixed by  #3918, which is now merged, and supersedes #2376. However, #3918 broke normal git repo venv detection, which is fixed by pending PR #4122. Could you test out #4122 and see if it works for you?

**Comment by mcornella** [comment]
This can be closed
