### ISSUE TITLE
fatal: Invalid gitfile format: .git

### ISSUE THREAD

**Issue by rhoml** [robbyrussell/oh-my-zsh#2883]
After upgrading to the latest version, I see the error `fatal: Invalid gitfile format: .git` whenever I get to a non-git repository directory.

![screenshot](https://cloud.githubusercontent.com/assets/369350/3285163/2d6d720a-f536-11e3-9cb2-f90a615ba977.png)

**Comment by mcornella** [comment]
Hey I know it's been a while but could you check out [this solution](https://github.com/robbyrussell/oh-my-zsh/pull/3091/files#diff-4ad2773a26526d0e361e66139c283099R128) to see if it works in your case?

**Comment by rhoml** [comment]
@mcornella actually I migrated away from that theme, and upgraded oh-my-zsh and it works great.

**Comment by mcornella** [comment]
Ok thanks for replying anyway. Remember to close the issue!
