### ISSUE TITLE
pathes.zsh, tmux -> new window not abbreviated

### ISSUE THREAD

**Issue by v76591wC** [robbyrussell/oh-my-zsh#2894]
I have some directory shortcuts in my custom/pathes.zsh.
When I use them the path is correctly abbreviated in my prompt. When i create a new tmux window the path is taken from the current path, but it is not abbreviated. I wonder if there is an option or a thing I can do to make it work as expected.

**Comment by v76591wC** [comment]
- Debian GNU/Linux stable
- tmux 1.6-2 (the -2 could be a debian patch level)
- zsh 4.3.17
- plugins=(gitfast zsh-syntax-highlighting)

the thing can be reproduced like in this comment: 
https://github.com/robbyrussell/oh-my-zsh/issues/2894#issuecomment-47418850

**Comment by mcornella** [comment]
If you can, I'd try upgrading zsh. I guess you're on stable, you can add the testing repository and install zsh5. Meanwhile, I'll try to downgrade to zsh4 and test your problem to see if it's due to that..

**Comment by mcornella** [comment]
Have you had a chance to test with zsh5?
