### ISSUE TITLE
zsh not support adb logcat *:E?!!!

### ISSUE THREAD

**Issue by rakkang** [robbyrussell/oh-my-zsh#2901]
when enter the command "adb logcat *:E", i got the error 'zsh: no matches found: *:E'....

**Comment by mcornella** [comment]
Hi! Did you got the chance to test my solution?

**Comment by weimuhua** [comment]
yeah. 
adb logcat '*:E' worked. 
thanks a lot.

**Comment by 1037975742** [comment]
因为zsh缺省情况下始终自己解释这个firefox*，而不会传递给adb logcat来解释。

open ~/.zshrc add line:
setopt no_nomatch
and perform source .zshrc command

**Comment by kmusham** [comment]
This worked

$: adb logcat '*:S' TSLocationManager:V
