### ISSUE TITLE
OS X Plugin - "tab" command bug in iTerm

### ISSUE THREAD

**Issue by manewitz** [robbyrussell/oh-my-zsh#2913]
With the osx plugin using iTerm, the `tab` command opens a new tab and I can see the command (`cd "/Users/mike"; clear;` for example) entered but I have to hit return to get it to run. Terminal.app appears to be working correctly.

It might be as easy as adding a newline or something to the command [on line 37](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/osx/osx.plugin.zsh#L37) in the iTerm section 

Thanks!

**Comment by sorin-ionescu** [comment]
Which iTerm version does this affect 2.0.0.20141103 or 2.9.20150221-nightly?

**Comment by sorin-ionescu** [comment]
In 2.0.0.20141103, it works without `keystroke return`.
In 2.9.20150221-nightly, the code doesn't work at all.

**Comment by sorin-ionescu** [comment]
With just the following:

```AppleScript
write text "Hello"
```

I get:

```
~ ❯❯❯ Hello
zsh: command not found: Hello
```
