### ISSUE TITLE
per-directory-history ignores HIST_IGNORE_SPACE

### ISSUE THREAD

**Issue by legovini** [robbyrussell/oh-my-zsh#2972]
I think the title says it all: the per-directory-history plugin records all history, while it should honor HIST_IGNORE_SPACE (and perhaps other history-related options).

**Comment by A-Manning** [comment]
This is now fixed in master with https://github.com/jimhester/per-directory-history/pull/26, can we merge it?

**Comment by mcornella** [comment]
Done, thanks!
