### ISSUE TITLE
The fishy theme is not showing colors

### ISSUE THREAD

**Issue by legovini** [robbyrussell/oh-my-zsh#2973]
The fishy theme should show some colors in the prompt, but it is not. I have to say that I tried with Antigen, I'm not sure if this matters.

I think it has to do with the color variables being local, and so not being set when zsh prints the prompt.

**Comment by mcornella** [comment]
Have you tried that?

**Comment by legovini** [comment]
Not really: I switched to fish...

**Comment by mcornella** [comment]
Ok please close this issue
