### ISSUE TITLE
Error returnned when attempting to autocomplete git commands while not in a git repository

### ISSUE THREAD

**Issue by nanenj** [robbyrussell/oh-my-zsh#3013]
Typing: git checkout [TAB] while not inside of a git repository results in the following:
```
[nanenj]% git checkout fatal: Not a git repository (or any of the parent directories): .git
HEAD
```

When not in a git repositiory, it should fail to autocomplete and should not suggest HEAD.  The failure to autocomplete is indication enough that it's not working and as is the error returned while hitting tab destroys the prompt and makes things difficult to read.

I don't think tab completion should be returning errors.  It should either default to how zsh itself behaves or just not autocomplete at all.  Even if this isn't an 'issue' that will get resolved.  If someone could point me in the right direction of where to look so I could at least fix it to my tastes locally, that'd be awesome. 

Currently I've explored large portions of the git.zsh functions in lib, and the git plugin, but, most if not all of the obvious calls in both of these places redirect stderr to /dev/null, indicating that the behavior I'm after is actually what's intended.

**Comment by mcornella** [comment]
Can you close?
