### ISSUE TITLE
PAGER environment variable blindly overwritten

### ISSUE THREAD

**Issue by Hibou57** [robbyrussell/oh-my-zsh#3016]
In `$ZSH/lib/misc.zsh` at line 12, `export PAGER="less"`, blindly overwrites the `PAGER` environment variable. This should be changed into `env_default PAGER "less"`.

**Comment by shreevatsa** [comment]
What is the resolution here? I saw #3359 and have that issue too -- I just installed OMZ and it just clobbered by SAVEHIST and HISTSIZE to the ridiculously low value of 10000. And it's also doing something strange with the pager, where it brings up the pager even for very short (or empty: e.g. "git diff" from a clean state) files.

**Comment by shreevatsa** [comment]
Nonsensical. This has been closed without even a reply, when the issue is very much still present. The resolution to "your software does a broken thing for no good reason" is not "here's a way you can undo the damage after you realise it has already happened". I'm giving up.

**Comment by mcornella** [comment]
Sorry @shreevatsa I wasn't clear enough. I was referring to this https://github.com/robbyrussell/oh-my-zsh/pull/3359#issuecomment-67022891, which says that these variables should be initialized *after* the `source oh-my-zsh...` line in `.zshrc`.

That way we avoid having bad defaults as it happened with the `SAVEHIST` and `HISTSIZE` variables on #3359. There could be a potentially better alternative, which is checking if those variables have really low variables (like zsh's default which puts it at 30), but the alternative of defining them after oh-my-zsh ensures we don't have to change it in the future.

And btw, sorry I didn't see your comment before. Do you have a better suggestion?

**Comment by shreevatsa** [comment]
@mcornella Thanks for your gracious comment.

I don't have the patience to try oh-my-zsh again now after many sour experiences like this (lots of my settings were screwed up, and even tentative attempts to improve things, e.g. pull request #3869, were ignored), but perhaps for future users, you ought to write in bold and at the top of the installation instructions that it is recommended that `source oh-my-zsh...` be the first line in `.zshrc` and all your personal settings come later.

Most users advanced enough to use zsh and further use oh-my-zsh probably have their preferences too, and it's frustrating that the default behaviour of oh-my-zsh is to ignore all those preferences. I see in hindsight that a lot would be improved if I had put `source oh-my-zsh` at the top rather than at the bottom (but still not everything), maybe if the next time I try OMZ, if the documentation has been updated to say it prominently, I'll remember to do so.

**Comment by Hibou57** [comment]
> but perhaps for future users, you ought to write in bold and at the top of the installation instructions that it is recommended that  source oh-my-zsh...  be the first line in  .zshrc  and all your personal settings come later.

And that would still be half solved: on many UNIX‑like (including Ubuntu, to name the most famous one), there is a `~/.profile` which always comes before anything else, is loaded with the session, and is intended to hold definitions for all cases, shell independent.


> I don't have the patience to try oh-my-zsh again

Alternatively, you may just avoid updating it (that's what I did, installed it, tweaked it, with no update to avoid issues like the one of this thread).

**Comment by MagiCrazy** [comment]
I agree with @Hibou57 as I use ~/.zshenv on GNU/linux to set my environment variables. Like ~/.profile, it's parsed before .zshrc, so the PAGER variable is overwritten. My PAGER is "most", as it looks far better than "less", so what if I propose a PR ?

**Comment by stardiviner** [comment]
I got issue on `env_default`, seems it the `misc.zsh` is loaded before `functions.zsh` (which define `env_default`).

![image](https://user-images.githubusercontent.com/378699/35545904-69ec5ab8-05ac-11e8-83e0-4622a89ce6b9.png)

**Comment by danballance** [comment]
This is still an issue for me. Worked around by placing this at the bottom of my `.zshrc`:
```
unset LESS
```

**Comment by darkn3rd** [comment]
This PAGER setting is disrupting automation, I have a loop for `aws` command that outputs json output, it hangs there, frozen until someone hits `:q`, very annoying.  I HATE THIS. :'(

**Comment by mcornella** [comment]
@darkn3rd as you can see the variable is no longer overwritten (#5231). These variables are supposed to be set and not cause issues like the one you have. In your case, it is a fault in the CLI tool that you use that it by default choose to use a pager.

For `aws` in particular, [the following document shows how to change this behavior](in https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside):

> In order of precedence, you can disable all use of an external paging program in the following ways:
> - Use the --no-cli-pager command line option to disable the pager for a single command use.
> - Set the cli_pager setting or AWS_PAGER variable to an empty string.
