### ISSUE TITLE
Custom $PATH for a specific machine

### ISSUE THREAD

**Issue by qiuwei** [robbyrussell/oh-my-zsh#3017]
Hi, I put the custom directory under VCS.
The problem is that I have several machines which are set up differently.
So I would like to custom the PATH on different machines. So I don't want to directly modify the .zshrc file.
But the customization of PATH I introduced under custom directory would be overwritten by .zshrc due to the order.
I can get around this issue by moving `PATH=blah blah ` before setting the path to the custom directory.
May I know whether this would introduce any side effects?
Thanks!

**Comment by mcornella** [comment]
Hey can you close this? Did I solve your doubts?

**Comment by qiuwei** [comment]
Yes, sure. Thanks!
