### ISSUE TITLE
ssh-agent Plugin on Mac OS X doesn’t work because launchd set the $SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by isqua** [robbyrussell/oh-my-zsh#3019]
As I see, [ssh-agent plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/ssh-agent/ssh-agent.plugin.zsh#L61) launches `ssh-agent` only if variable `$SSH_AUTH_SOCK` is empty. But on Mac OS X it is not empty:

```
$ echo $SSH_AUTH_SOCK
/tmp/launch-aY7Yo1/Listeners

$ lsof $SSH_AUTH_SOCK
COMMAND PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
launchd 244 isqua   11u  unix 0x2e8ad5a2c9398243      0t0      /tmp/launch-aY7Yo1/Listeners
```

When I launch `ssh-agent` it (as i understand) doesn’t connect to this socket:

```
$ ssh-agent
SSH_AUTH_SOCK=/var/folders/56/bq22bg3d4xz6w81jxj8c3b90msfw89/T//ssh-jd61LOgtorda/agent.2619; export SSH_AUTH_SOCK;
SSH_AGENT_PID=2620; export SSH_AGENT_PID;
echo Agent pid 2620;

$ lsof -c ssh-agent | grep unix
ssh-agent 2620 isqua    3u    unix 0x2e8ad5a2cd0617bb       0t0          /var/folders/56/bq22bg3d4xz6w81jxj8c3b90msfw89/T//ssh-jd61LOgtorda/agent.2619
```

Why does the launchd create the socket and set the variable? How ssh-agent should use it? How should I modify the plugin to make it work?

**Comment by mcornella** [comment]
Did you manage to find a solution?

**Comment by mcornella** [comment]
I've submitted #7174 to fix this.
