### ISSUE TITLE
Does not actually check whether ZSH is installed.

### ISSUE THREAD

**Issue by jrasanen** [robbyrussell/oh-my-zsh#3026]
Dies when chsh doesn't get an argument

    $ wget --no-check-certificate http://install.ohmyz.sh -O - | sh
    --2014-08-13 17:22:26--  http://install.ohmyz.sh/
    Resolving install.ohmyz.sh (install.ohmyz.sh)... 50.31.209.254
    Connecting to install.ohmyz.sh (install.ohmyz.sh)|50.31.209.254|:80... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh [following]
    --2014-08-13 17:22:26--  https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    Resolving raw.github.com (raw.github.com)... 185.31.17.133
    Connecting to raw.github.com (raw.github.com)|185.31.17.133|:443... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh [following]
    --2014-08-13 17:22:27--  https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.43.133
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.43.133|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 1779 (1.7K) [text/plain]
    Saving to: ‘STDOUT’

    100%[==============================================================================================>] 1,779       --.-K/s   in 0.005s  

    2014-08-13 17:22:28 (352 KB/s) - written to stdout [1779/1779]

    \033[0;34mCloning Oh My Zsh...\033[0m
    Cloning into '/home/jrasanen/.oh-my-zsh'...
    remote: Counting objects: 10530, done.
    remote: Total 10530 (delta 0), reused 0 (delta 0)
    Receiving objects: 100% (10530/10530), 1.93 MiB | 928.00 KiB/s, done.
    Resolving deltas: 100% (5672/5672), done.
    Checking connectivity... done.
    \033[0;34mLooking for an existing zsh config...\033[0m
    \033[0;34mUsing the Oh My Zsh template file and adding it to ~/.zshrc\033[0m
    \033[0;34mCopying your current PATH and adding it to the end of ~/.zshrc for you.\033[0m
    \033[0;34mTime to change your default shell to zsh!\033[0m
    which: no zsh in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin:/home/jrasanen/gopher/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/opt/bin:/usr/local/go/bin:/home/jrasanen/gopher/bin:/home/jrasanen/.local/bin:/home/jrasanen/bin:/opt/bin:/usr/local/go/bin:/home/jrasanen/gopher/bin)
    chsh: option requires an argument -- 's'

**Comment by apjanke** [comment]
I think #2836 will take care of this, because it positively locates `zsh` in the `/etc/shells` list.
