### ISSUE TITLE
Username completion when it shouldn't happen

### ISSUE THREAD

**Issue by yegle** [robbyrussell/oh-my-zsh#3035]
Just noticed that the username completion happened even when it doesn't make sense.

```
(.py3kvenv) ying@nike ~ $ whoami
ying
(.py3kvenv) ying@nike ~ $ yin<TAB>
yin       ying      yingfeng    <- these are the local usernames
```

**Comment by mcornella** [comment]
Hi @yegle can you close the issue?

**Comment by yegle** [comment]
Sorry I missed your comment at https://github.com/robbyrussell/oh-my-zsh/issues/3035#issuecomment-55508946
