### ISSUE TITLE
Virtualenv wrapper not working?

### ISSUE THREAD

**Issue by itsnauman** [robbyrussell/oh-my-zsh#3047]
Hey, I have installed `virtualenvwrapper` using `pip`.I am aware that there is a plugin for using it but it doesn't seem to work for me when I run `mkvirtualenv xyz`. So are there some configurations I need to do?

**Comment by mcornella** [comment]
How did this turn out? Was it solved?

**Comment by todkiry** [comment]
This worked for me

**Comment by chrisalcantara** [comment]
This worked for me :+1:

**Comment by bavly** [comment]
it works for me after typing this
source /usr/local/bin/virtualenvwrapper.sh
then mkvirtualenv

**Comment by ianchesal** [comment]
The plugin should be updated. The default location of this script changed. Opened a pull request.
