### ISSUE TITLE
Tab completion fails for global aliases

### ISSUE THREAD

**Issue by ikkath** [robbyrussell/oh-my-zsh#3062]
After re-installing my entire OSX machine today and now grabbing the latest oh-my-zsh it seems I can no longer complete _global_ aliases in any context.

Searching around the net I see lots of scripts for expanding the alias automatically (like ctrl-x a) and other little tweaks, but everyone seems to take it for granted that global aliases tab complete.

Anyone have any insight? This is a brand new install with no plugins, etc.

**Comment by mcornella** [comment]
You can use the globalias plugin which expands upon pressing space.
