### ISSUE TITLE
rbenv plugin not working with homebrew

### ISSUE THREAD

**Issue by jweaver60** [robbyrussell/oh-my-zsh#3093]
I can't get the rbenv plugin to work with homebrew installed rbenv. It looks to be setting `$RBENV_ROOT` to `/usr/local/opt/rbenv` instead of `~/.rbenv`. When I enable the rbenv plugin then rbenv reports only the system ruby as installed and available.

**Comment by bartdorsey** [comment]
Same problem here. If it's supposed to work with the brew installed rbenv then it should be /usr/local/var/rbenv or .rbenv.  It should never be /usr/local/opt/rbenv

**Comment by caesarsol** [comment]
same problem.

I have a solution, but I'm not sure if it works for everyone.

the problem is in rbenv.plugin.zsh, line 13.
the script selects the RBENV_HOME dir based on the presence of the `bin` directory, but my

**Comment by mcornella** [comment]
See #3808, +1 if it works for you.

**Comment by caesarsol** [comment]
@mcornella reversing the order doesn't work for me, since the bin directory doesn't exist in my `~/.rbenv`...

**Comment by caesarsol** [comment]
oops, sorry I haven't read the pull request from @mbologna which is exactly my patch.

**Comment by mbologna** [comment]
Hey @jweaver60 @bartdorsey @caesarsol @mcornella: please check with #4384 if it solves your problem

**Comment by tanelsuurhans** [comment]
Is there any hope for this getting merged in, I still see this issue present on OSX
