### ISSUE TITLE
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:87: command not found: compdef

### ISSUE THREAD

**Issue by qinf** [robbyrussell/oh-my-zsh#3129]
problem on my centos 7.0:
/etc/profile.d/colorls.sh:26: command not found: tty
/etc/profile.d/colorls.sh:35: command not found: mktemp
/etc/profile.d/colorls.sh:38: no such file or directory: 
/etc/profile.d/colorls.sh:42: command not found: rm
path/to/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
path/to/.oh-my-zsh/lib/completion.zsh:28: command not found: whoami
path/to/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
path/to/.oh-my-zsh/lib/theme-and-appearance.zsh:10: command not found: uname
path/to/.oh-my-zsh/lib/theme-and-appearance.zsh:14: command not found: uname
path/to/.oh-my-zsh/oh-my-zsh.sh:55: compinit: function definition file not found
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:3: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:5: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:7: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:9: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:11: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:13: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:15: command not found: compdef
path/to/.oh-my-zsh/plugins/git/git.plugin.zsh:17: command not found: compdef

**Comment by mcornella** [comment]
Please post the output of
```
echo $SHELL
zsh --version
```
Remember to paste it inside triple backquotes, like this:
\`\`\`
PASTE HERE
\`\`\`

**Comment by mcornella** [comment]
Any updates?

**Comment by atomic** [comment]
@mcornella I have the same issue with this zsh after installing it on a cloud box. 
my shell and version:
/bin/zsh
zsh 4.3.10 (x86_64-redhat-linux-gnu)
after uncomment the plugin section from .zshrc. I got 2 errors.
/home/linux/server/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/linux/server/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
On related note, vim also can't start on zsh, but it runs on bash, default shell.
vim: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory

**Comment by mcornella** [comment]
Hi @atomic, you're issue seems different enough to warrant a new one. Please open a new issue and I'll comment there.

**Comment by uri** [comment]
I have the same problem as @qinf zsh version: `zsh 5.4.2 (x86_64-apple-darwin16.7.0)`

**Comment by Gemma-mobu** [comment]
Guys. Is there anyone to solve this problem? I've got this problem, too

**Comment by mcornella** [comment]
Can you post your output?
