### ISSUE TITLE
yum install name.rpm can not auto complete

### ISSUE THREAD

**Issue by netroby** [robbyrussell/oh-my-zsh#3181]
yum install name.rpm can not auto complete.

there is a rpm package file in my home directory, 
i want install it using yum install,

but the auto complete does not working.

rpm -Uvh examp 
then type tab key, the auto complete working .

but when i type 

yum install examp
and type tab key, nothing works.

**Comment by mcornella** [comment]
`yum` completion is provided by zsh itself. Try a newer version.
