### ISSUE TITLE
ugly appearance in emacs shell on  Mac osx 

### ISSUE THREAD

**Issue by ChinaXing** [robbyrussell/oh-my-zsh#3190]
I use oh-my-zsh as default shell in Mac osX Terminal

when I start emacs in Terminal and run command : 

M-x: shell

in emacs, the shell opened in emacs is too ugly: 
![snip20141005_4](https://cloud.githubusercontent.com/assets/1628109/4516324/434a212a-4bf0-11e4-842d-3cbaec5bba5b.png)

**Comment by mcornella** [comment]
Has this been solved? Can you please close the issue?
