### ISSUE TITLE
Download the install script with a secured connection

### ISSUE THREAD

**Issue by netheril96** [robbyrussell/oh-my-zsh#3207]
The current documentation tells us to do this in order to install oh-my-zsh

```sh
curl -L http://install.ohmyz.sh | sh
```

But this is very dangerous. The content is transferred on a unsecured http channel, which means it can be modified by an attacker, or maybe it can get corrupted (TCP's checksum is very weak). Either way, there is a chance for arbitrary malicious/broken code to be executed.

It should be curled from a secured channel instead, like https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh

**Comment by mcornella** [comment]
Done. For the time being we've gone back to the old github URL. See #3459.
Please close
