### ISSUE TITLE
Warp point should not contain whitespace while is just  contains "s"

### ISSUE THREAD

**Issue by krisdante** [robbyrussell/oh-my-zsh#3208]
I don't know why but on one of my OSX I am not able to add any warp point with "s" letter in name.
Seems that \s matches not only space but also "s".
This happens only on one of my computers. What can be miss-configured?

```
git:(master) wd add ssite
 * Warp point should not contain whitespace
```

**Comment by mcornella** [comment]
Already solved in the current version, please close
