### ISSUE TITLE
compleat plugin not working

### ISSUE THREAD

**Issue by doomred** [robbyrussell/oh-my-zsh#3234]
hello, I am new to zsh,

compleat via github HEAD,
compiled successfully(conclusion from stdout),
and ofcuz add compleat to plugins=...

Anyone works on this plugin please help.

FYI:
zsh 5.0.2 (x86_64-slackware-linux-gnu)
OMZ via install.ohmyz.sh
added top.usage & tested **only** on top(is this nessary?? it's stupid to add all the commend *.usage file)
compleat also not working on my bash(using method on compleat/readme.md

**Comment by zeorin** [comment]
I had the same issue. I managed to fix this by adding

```
autoload -Uz compinit
compinit
```

Before loading the `compleat` plugin.

**Comment by mcornella** [comment]
This shouldn't be necessary. The only requirement of the compleat plugin to work is to find the `compleat` command, so it needs to be in `$PATH`. The `compinit` setup is already done by Oh My Zsh.
