### ISSUE TITLE
For the theme "ys"

### ISSUE THREAD

**Issue by zhanglongqi** [robbyrussell/oh-my-zsh#3266]
![3](https://cloud.githubusercontent.com/assets/956693/4804626/f105c0d0-5e6f-11e4-951f-46bc5f055da2.png)
Only If I 

**use my own kernel(I compile it myself)** , 

**the 'ys' theme** and 

**serial login**, 

then three spaces won't show up. it turn to be <2>. so strange.

**Comment by mcornella** [comment]
Did you find the answer? It's clear that it's not oh-my-zsh related though, can you please close this?

**Comment by zhanglongqi** [comment]
I did not. sorry.
