### ISSUE TITLE
New feature for update

### ISSUE THREAD

**Issue by zezadas** [robbyrussell/oh-my-zsh#3277]
I use zsh as my main shell, and I login via startx, so when I have the option to update day by day, when I boot the PC, I get a message prompting if I want to update oh-my-zsh, its really annoying, because I just want to startx and I don't have internet before login. Since I like to be updated, but dont like to be asked to update every time I start my computer, I asking if you could make an option to disable update message for example, the first time ZSH starts.

Thanks for this amazing framework, keep the good work :)

**Comment by apjanke** [comment]
A login shell isn't going to be a sufficient test. Most shells that users fire up are going to be login shells. (This is the default for most terminal emulators I'm familiar with.)

**Comment by mcornella** [comment]
Then maybe checking the value of tty (or `$TTY`). If it's not a pseudo-terminal don't prompt for update, or something like that.
