### ISSUE TITLE
Load custom configs from $ZSH_CUSTOM before loading plugins defined in ~/.zshrc?

### ISSUE THREAD

**Issue by rhbecker** [robbyrussell/oh-my-zsh#3282]
I'm new to oh-my-zsh. One of the first plugins I'm messing with is ssh-agent.

At first blush, my intuition is to keep the setting of zstyles - e.g. `zstyle :omz:plugins:ssh-agent identities example-key` - out of my main `~/.zshrc` file, rather putting them into `*.zsh` files in my `$ZSH_CUSTOM` directory.

However, for that to work, I need the `$ZSH/.oh-my-zsh.sh` file to load those custom configs before loading plugins.

Am I stupidly breaking something by doing that? Or would that be a good idea for everyone - i.e. something I should submit as a PR?

**Comment by mcornella** [comment]
Hey @rhbecker can you close this issue now that your use case is solved?

**Comment by rhbecker** [comment]
When you say "your use case is solved", are you referencing the workaround you suggested in your November 7th comment?

**Comment by mcornella** [comment]
Yeah exactly. It's conceptually an aberration but I think it might work... unless the init script calls it again after sourcing oh-my-zsh. I don't know...

I think we merged quite recently a PR to allow using custom lib files, so you could have a particular `$ZSH_CUSTOM/lib/something.zsh` sourced before the rest. Take a look at the init script for more info.

In the end, I think none of these solutions is good enough. Maybe we could standardise some file in the custom directory to run before everything else.. like a pre-init.zsh file. But I'm not a 100% on that either. You might want to reconsider putting it in the zshrc file.

BTW your applied solution of loading custom files first breaks the use case of overriding plugin or libs settings (I'm talking aliases and such).

Sorry for the big reply :grin:

**Comment by apjanke** [comment]
This was merged in #3617 / #3809. Custom configs are now loaded before plugins.

Could you close this issue?

**Comment by rhbecker** [comment]
Cool! I haven't confirmed this solves my issue yet, but I'll assume so and re-open if not. Thanks!
