### ISSUE TITLE
Disable git-prompt based on path?

### ISSUE THREAD

**Issue by bubba-h57** [robbyrussell/oh-my-zsh#3284]
I know that there is a way to set the git config so that the git-prompt plugin is disabled, but that will not work for me.

I need a way to to disable the git-prompt based on a root path (~/ignoreGit/*). Google search seems to indicate that there is a way for me to change the theme, based on what directory I'm in, but I can't seem to find an example of how that works.

Could someone point me toward an answer to my delima? Or could we just get git-prompt to accept a list of directory to ignore?

**Comment by ncanceill** [comment]
Hi, I am not sure that the `git-prompt` plugin offers a way to do what you want.

Both of you could work with @jtriley on implementing a solution.

**Comment by matthewbauer** [comment]
The settings "oh-my-zsh.hide-dirty" can be set in gitconfig to disable this.

So:

```
git config --global oh-my-zsh.hide-status 1
```

will hide it globally.

and:

```
git config oh-my-zsh.hide-status 1
```

will hide it for the current repo.

**Comment by bubba-h57** [comment]
That is perfect, thanks!

**Comment by AllanLRH** [comment]
Not working for me (using a freshly spawned tab) – or did I misunderstand something?
<img width="549" alt="screen shot 2018-01-05 at 14 43 04" src="https://user-images.githubusercontent.com/2641327/34611715-ea73bf94-f226-11e7-86b7-9e94813d0f56.png">
The directory in the screenshot is mounted through sshfs.

**Comment by AllanLRH** [comment]
Found a workaround, by disabling the git prompt for a specified folder in my .zshrc – works with the Refined theme (previously named Pure). [The fix](https://github.com/sindresorhus/pure/issues/189#issuecomment-173839487).

**Comment by username123231** [comment]
Note that `oh-my-zsh.hide-status` may not work with all themes
