### ISSUE TITLE
"apt-get download" won't complete

### ISSUE THREAD

**Issue by mhalano** [robbyrussell/oh-my-zsh#3285]
I use the comand "apt-get download <package name>" a lot, but i start to type "apt-get..." and "download" option is not available. How do I fix them?

**Comment by mcornella** [comment]
From [askubuntu.com](http://askubuntu.com/a/47877): 

> The command apt-get download wasn't added until version 0.8.11 of apt. It was first available in Ubuntu 11.04 (which uses apt 0.8.13.2).

Zsh completion of the `apt` commands is implemented over time, you can see that to this day it is not yet there: http://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Debian/Command/_apt

This is a `zsh` issue though. Please close
