### ISSUE TITLE
How to turn off git plugin

### ISSUE THREAD

**Issue by andyr** [robbyrussell/oh-my-zsh#3288]
I removed git from the plugins=() line, but still get the aliases it sets up which I don't want.  I can't find uninstall instructions anywhere and it didn't stop working the way I thought was intuitive.  Please advise.

**Comment by mcornella** [comment]
Any update?

**Comment by ffxsam** [comment]
What was the solution to this? I'm unable to disable this plugin.

**Comment by igl** [comment]
I hate the 1000 aliases it creates, yet i want the branch-name prefix displayed.
Is there an alternative plugin? Editing this file breaks zsh updates. :disappointed:

**Comment by TN1ck** [comment]
You are probably using a theme were the git-prompt is hard-coded, like the default one. If you are you using robby-russel, open ~/.oh-my-zsh/themes/robyrussel.zsh-theme and replace the `PROMPT`-line with `PROMPT='${ret_status}%{$fg_bold[green]%}%p %{$fg[cyan]%}%c%{$fg_bold[blue]%}%{$fg_bold[blue]%}%{$reset_color%}'`.

**Comment by divsmith** [comment]
I just removed git from the plugins=() line in my .zshrc, restarted my terminal, and it worked for me. I'm running the miloshadzic theme and left the theme file stock. I still get the branch name prefixed but none of the default aliases get loaded. Works great!

**Comment by mcornella** [comment]
This is probably a side effect of #4085. I'll merge #4420 in a bit to fix that.

**Comment by balkierode** [comment]
I needed a theme without git_promt as my network mounted drive was very slow. Here are the current list:

themes|master ⇒ grep --files-without-match "git_prom" *
agnoster.zsh-theme
apple.zsh-theme
cypher.zsh-theme
duellj.zsh-theme
eastwood.zsh-theme
emotty.zsh-theme
evan.zsh-theme
example.zsh-theme
funky.zsh-theme
gallois.zsh-theme
half-life.zsh-theme
imajes.zsh-theme
jnrowe.zsh-theme
josh.zsh-theme
kolo.zsh-theme
linuxonly.zsh-theme
mikeh.zsh-theme
nicoulaj.zsh-theme
pure.zsh-theme
rkj.zsh-theme
steeef.zsh-theme
trapd00r.zsh-theme
xiong-chiamiov.zsh-theme
zhann.zsh-theme

**Comment by waffletower** [comment]
I had been using antigen to load zsh modules and I didn't lose my git branch prompt either after commenting out the git module. Those aliases are decidedly user-hostile.

**Comment by f3z0** [comment]
For agnoster theme the solution is to remove (or comment out) prompt_git from build_prompt() function in ~/.oh-my-zsh/themes/agnoster.zsh-theme.

I like the git prompt when working with small repositories but it doesn't work well for large repositories where a git status can take several minutes for completion.

**Comment by niasand** [comment]
I just resolve is like this:
1. rm git plugin
```
cd ~/.oh-my-zsh/plugins
rm -rf  git*
```
2.  open my ~/.zshrc, and remove git from the plugins=() line

3. and then add these below to my ~/.zshrc. 
```
alias g='ls -la'
alias ga='ls -la'
alias gaa='ls -la'
alias gapa='ls -la'
alias gau='ls -la'
alias gap='ls -la'
alias gb='ls -la'
alias gba='ls -la'
alias gbd='ls -la'
alias gbda='ls -la'
alias gbl='ls -la'
alias gbnm='ls -la'
alias gbr='ls -la'
alias gbs='ls -la'
alias gbsb='ls -la'
alias gbsg='ls -la'
alias gbsr='ls -la'
alias gbss='ls -la'
alias gc='ls -la'
alias gc!='ls -la'
alias gcn!='ls -la'
alias gca='ls -la'
alias gca!='ls -la'
alias gcan!='ls -la'
alias gcans!='ls -la'
alias gcam='ls -la'
alias gcsm='ls -la'
alias gcb='ls -la'
alias gcf='ls -la'
alias gcl='ls -la'
alias gclean='ls -la'
alias gpristine='ls -la'
alias gcm='ls -la'
alias gcd='ls -la'
alias gcmsg='ls -la'
alias gco='ls -la'
alias gcount='ls -la'
alias gcp='ls -la'
alias gcpa='ls -la'
alias gcpc='ls -la'
alias gcs='ls -la'
alias gd='ls -la'
alias gdca='ls -la'
alias gdcw='ls -la'
alias gdct='ls -la'
alias gdt='ls -la'
alias gdw='ls -la'
```

**Comment by sefeng211** [comment]
Looks like the setting for `robbyrussell` has been changed. For me, I just removed `$(git_prompt_info)` from the `PROMPT+=`.

**Comment by sqren** [comment]
Disable Git integration for a single repository:
```
git config oh-my-zsh.hide-status 1
```

Disable Git integration for all repositories:
```
git config oh-my-zsh.hide-status 1 --global
```

**Comment by Navid61** [comment]
I **removed** only **$(git_prompt_info)** and replace that  with **%{$fg[yellow]%}✗**: 
PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} %{$fg[yellow]%}✗: '

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"

**Comment by gwendalp** [comment]
I use the theme **p10k**. 

I commented the line 37 in **~/.p10k.zsh**  : 

`#vcs `

It is not destructive and it works great !

**Comment by scobby** [comment]
> I use the theme **p10k**.
> 
> I commented the line 37 in **~/.p10k.zsh** :
> 
> `#vcs `
> 
> It is not destructive and it works great !

this solved it for me too. :-) thx!

**Comment by jonnyzzz** [comment]
It seems to be broken after the latest update today

**Comment by mcornella** [comment]
Can you specify what's broken? That commit doesn't change anything related to git

**Comment by sefeng211** [comment]
With the latest update, my prompt starts showing git branch names again. I think `git config oh-my-zsh.hide-status 1 --global` stopped working?

**Comment by mcornella** [comment]
2f39c68a changed the necessary config option to disable that. For `git_prompt_info` you now need to use
```
git config oh-my-zsh.hide-info 1
```

BTW, the real time-sink in that function is `parse_git_dirty`, maybe you only need
```
git config oh-my-zsh.hide-dirty 1
```
and you'll still get the branch name displayed.

PS. Didn't you get a changelog message notifying you of the breaking change? If not, how long has it been since the last update?

**Comment by jonnyzzz** [comment]
Thanks. The second option seems to work on my setup. Thanks to git reflog I was able to recover. 
I usually do updates once it suggests to, maybe 1-2 weeks only. 
It could be that I've missed any breaking changes notifications in the update log (could it probably be blocking to attract mode attention?)

**Comment by mcornella** [comment]
Hmm the changelog should be already in place in that timeframe. Anyway, you'll see the changelog on the next update.

**Comment by loligans** [comment]
Any way the git plugin can ignore specific directories? I run in WSL2 and don't want the git plugin to run for any directory under `/mnt`

**Comment by nimrodp-cye** [comment]
The git info is indeed often hardcoded into the theme. I used the `font` and I had to go into `~/.oh-my-bash/themes/font/font.theme.sh` and change the `PS1` from this:
```
PS1="$(clock_prompt)$python_venv${hostname} ${_omb_prompt_bold_teal}\W $(scm_prompt_char_info)${ret_status}→ ${_omb_prompt_normal}"
```
to this
```
PS1="$(clock_prompt)$python_venv${hostname} ${_omb_prompt_bold_teal}\W ${ret_status}→ ${_omb_prompt_normal}"
```
And it worked (and I got the speedup).

**Comment by sevk** [comment]
`[oh-my-zsh] Can't update: not a git repository.
`

how to hide this ?

**Comment by hack505** [comment]
This can be solve with git, only use this commands

```bash
sudo git config oh-my-zsh.hide-status 1 --global
```
Disables the Git status prompt in all Directory

```bash
sudo git config oh-my-zsh.hide-info 1
``` 
To apply changes
**Restart the termial and see the wonder**

**-For Linux based os**

**Comment by MKesenheimer** [comment]
> This can be solve with git, only use this commands
> 
> ```shell
> sudo git config oh-my-zsh.hide-status 1 --global
> ```

This was the command that made my shell a thousand times faster. Thanks.

**Comment by rwmitchell** [comment]
> > This can be solve with git, only use this commands
> > ```shell
> > sudo git config oh-my-zsh.hide-status 1 --global
> > ```
> 
> This was the command that made my shell a thousand times faster. Thanks.

Can you provide any metrics on the git repos you were in that provided that speed increase?

**Comment by MKesenheimer** [comment]
> Can you provide any metrics on the git repos you were in that provided that speed increase?

I had speed issues in a git repository with 1330 files (mostly text files) and approximately 20 commits.

**Comment by carlosala** [comment]
Hi! For everyone here, we're rolling out a new async way of showing git status in prompt, that should get rid of all kind of lag. You can activate it by:

```sh
zstyle ':omz:alpha:lib:git' async-prompt yes
```

We're quite proud of this one, and although it needs some work, we think it will get rid of all the "slow git prompt" issues, as it will now be rendered asynchronously.

Here's a recording of a before/after enabling on a shallow copy of the git repo https://github.com/torvalds/linux (which is a good test for slowness).

[![asciicast](https://asciinema.org/a/OBK9cA3Yc6kvU87BHm2jooL4v.svg)](https://asciinema.org/a/OBK9cA3Yc6kvU87BHm2jooL4v)

Please test and send in your feedback! Thanks!!
