### ISSUE TITLE
Check to see whether zsh is installed before "chsh -s `which zsh`"

### ISSUE THREAD

**Issue by amingilani** [robbyrussell/oh-my-zsh#3300]
Hi, i'm running elementary OS, i don't believe it ships with zsh since I installed with `sudo apt-get install zsh` but even after, here's what happens

```
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
chsh: option requires an argument -- 's'
Usage: chsh [options] [LOGIN]

Options:
  -h, --help                    display this help message and exit
  -s, --shell SHELL             new login shell for the user account

user@elementeryOS:~$ chsh -s 'which zsh'
Password: 
chsh: which zsh is an invalid shell
```

I used the following to resolve this issue:

```
user@elementeryOS:~$ sudo apt-get install zsh -y
user@elementeryOS:~$ which zsh
/usr/bin/zsh
user@elementeryOS:~$ chsh -s /usr/bin/zsh
```

Please add support to detect if zsh isn't already installed on the system, and a fix for `'which zsh'` is needed.

**Comment by amingilani** [comment]
I'm reopening this issue since I just did a fresh install and ran into the same problem again.. please close this when the issue is solved.

**Comment by dandv** [comment]
Just got the same `chsh: option requires an argument` error on Ubuntu:

```
$ sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
Cloning Oh My Zsh...
Cloning into '/home/dandv/.oh-my-zsh'...
remote: Counting objects: 671, done.
remote: Compressing objects: 100% (542/542), done.
remote: Total 671 (delta 15), reused 511 (delta 4), pack-reused 0
Receiving objects: 100% (671/671), 416.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (15/15), done.
Checking connectivity... done.
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
Time to change your default shell to zsh!
chsh: option requires an argument -- 's'
Usage: chsh [options] [LOGIN]

Options:
  -h, --help                    display this help message and exit
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             new login shell for the user account
```

**Comment by apjanke** [comment]
Portability note: Using `which zsh` with `chsh` isn't robust: the `zsh` that's first on the path may not be in `/etc/shells`. For example, if you're running Homebrew on Mac and have their `zsh` installed, and `/usr/local/bin` ahead of `/bin` (which most people do), `which zsh` will be `/usr/local/bin/zsh`, but that's not in `/etc/shells`, so trying to `chsh -s $(which zsh)` will error out. Same if a user has compiled their own `zsh` and installed in in their home directory or something.

You should `grep` `/etc/shells` for an appropriate `zsh` instead, and check for the case of no `zsh` being installed, as #4241 does. This should work more portably:

```
chsh -s $(grep /zsh$ /etc/shells | tail -1)
```
