### ISSUE TITLE
'e' command do not open emcas

### ISSUE THREAD

**Issue by dluksza** [robbyrussell/oh-my-zsh#3305]
I've installed emacs24 and enabled emacs plugin in or-my-zsh .zshrc file. Then when I tried open emacs using `e` command it is immedialty quiting (going back to promt). No error or any other messages are shown on command line.

My quick fix if to modify emacsclient.sh file:

``` diff
diff --git a/plugins/emacs/emacsclient.sh b/plugins/emacs/emacsclient.sh
index 625201a..636339d 100755
--- a/plugins/emacs/emacsclient.sh
+++ b/plugins/emacs/emacsclient.sh
@@ -1,7 +1,7 @@
 #!/bin/sh

 # get list of available X windows.
-x=`emacsclient --alternate-editor '' --eval '(x-display-list)' 2>/dev/null`
+x=`emacsclient -t --alternate-editor '' --eval '(x-display-list)' 2>/dev/null`

 if [ -z "$x" ] || [ "$x" = "nil" ] ;then
     # Create one if there is no X window yet.
```

Now, all emacs command will open emacs frame in current terminal. I'm not sure if this is the proper fix for this problem (eg. maybe one would prefer to have '-c' instead of '-t' there)

**Comment by mcornella** [comment]
Open a PR to discuss this solution

**Comment by zen0x90** [comment]
I tried the above quick fix and it works fine.

However, when I start "emacs" my theme gone and also "emacs -nw" is not working. I think more change must be done in order to make this script work for emacs24.

emacs 24.4
zsh 5.0.2

**Comment by Bounga** [comment]
I'd really like to see a full fix for emacs24. Maybe I can provide some help?

**Comment by shfx** [comment]
This `-e` flag fixed my problem when killing last Emacs frame using  `c-x c-c` (`save-buffers-kill-terminal`) and then trying to open something using oh-my-zsh emacs plugin.

Looking forward to see PR resolving this issue.

**Comment by shfx** [comment]
Any news on this issue?

**Comment by cmal** [comment]
I have this problem, too.

**Comment by tru2dagame** [comment]
On my Ubuntu server, I have this problem too.
It works for me with this [PR](https://github.com/robbyrussell/oh-my-zsh/pull/5714)
