### ISSUE TITLE
oh my zsh fresh install issue syntax error line 48 plugins=(git)

### ISSUE THREAD

**Issue by hrwebasst** [robbyrussell/oh-my-zsh#3317]
The following is what happens when I install zsh on my ubuntu systems, everything seems to work fine if I type zsh and press enter after install but otherwise you still have old shell:

curl -L http://install.ohmyz.sh | sh
Cloning Oh My Zsh...
Cloning into '/home/richard/.oh-my-zsh'...
remote: Counting objects: 11225, done.
remote: Total 11225 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (11225/11225), 2.05 MiB | 0 bytes/s, done.
Resolving deltas: 100% (6098/6098), done.
Checking connectivity... done.
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc
Copying your current PATH and adding it to the end of ~/.zshrc for you.
         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
                        /____/                       ....is now installed!

 Please look over the ~/.zshrc file to select plugins, themes, and options.

 p.s. Follow us at http://twitter.com/ohmyzsh.

 p.p.s. Get stickers and t-shirts at http://shop.planetargon.com.
sh: 48: /home/richard/.zshrc: Syntax error: "(" unexpected

**Comment by apjanke** [comment]
@hrwebasst, can you close this as a duplicate and just have you follow #3294 for updates?

BTW, when pasting terminal output, you can use the triple-backquote (```) Wiki markup to have them rendered in fixed-width font, making it more readable.

**Comment by mcornella** [comment]
Closing because it seems dead.
