### ISSUE TITLE
ZSH plugin, for Git repo folder switching, management and cloning

### ISSUE THREAD

**Issue by SamMorrowDrums** [robbyrussell/oh-my-zsh#3319]
I would love it if somebody from the team would take a look at this, and consider adding it as official.

I have tested my [zsh version of the gh cli tool](https://github.com/SamMorrowDrums/gh) and it works well!

It uses [Hub](https://hub.github.com/) to clone repositories if you haven't yet, and it changes to the correct folder straight away.

It uses the repo file system scheme supported by Golang: 
$HOME/src/github.com/$account/$repo

It's a handy little tool!

**Comment by ncanceill** [comment]
Since there does not appear to be any dependency between OMZ and you tool (which looks handy, by the way), why do you think it should become a part of OMZ?

People can simply install both OMZ and your tool, no need for it to become a plugin of OMZ, am I wrong?
