### ISSUE TITLE
Completion is repeated after sudo -s

### ISSUE THREAD

**Issue by amiorin** [robbyrussell/oh-my-zsh#3346]
Normal user
```
╭─alberto@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd[CURSOR]

# after TAB completion

╭─alberto@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd[CURSOR]
PWD       pwd       pwd_mkdb
```

Root user with ``sudo -s``
```
╭─root@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd[CURSOR]

# after TAB completion

╭─root@nareti  ~/.oh-my-zsh  ‹master›
╰─$ pwd pwd[CURSOR]
PWD       pwd       pwd_mkdb
```

It happens with iTerm
TERM = xterm-256color
theme = bira or flazz or pygmalion
zsh 5.0.6 (x86_64-apple-darwin13.3.0) installed with brew
osx mavericks

**Comment by Freyskeyd** [comment]
Same here:

In docker container running fresh ubuntu and/or debian

**Comment by Freyskeyd** [comment]
I've add `LANG=C.UTF-8` to env and it's working.

**Comment by amiorin** [comment]
@Freyskeyd You saved my day. Thx

**Comment by mcornella** [comment]
Hey upgrade oh-my-zsh and test if it works again, we solved a nasty bug with unicode support. You'll have to temporarily disable any workaround you made to test it though...
