### ISSUE TITLE
Large delay when running commands inside a git-svn directory

### ISSUE THREAD

**Issue by peterlauri** [robbyrussell/oh-my-zsh#3351]
Ubuntu 12.04 run inside VirtualBox from Mac host.

I have a medium sized svn repo that I have cloned with git-svn. Contains 78 branches and around 65000 commits. Whenever stepping into that directory, or executing any command, the command executes normally, but after that there is around a 5 second pause, before the prompt returns. By using "time <CMD>" I see that the command actually executes quickly, but that it looks to be zsh that it causing that delay.

If I disable zsh, this problem goes away.

**Comment by apjanke** [comment]
When you say you "disable zsh", do you mean disabling `oh-my-zsh`, or switching from `zsh` back to `bash` or another shell?

What theme and plugins are you using in oh-my-zsh?

Is this a public repo that we could also clone to try to reproduce the issue?

**Comment by peterlauri** [comment]
Disable zsh: just went back to bash

Unfortunally I cannot reproduce this now, I got a new very much powerful Macbook Pro, and I don't get the same behavior anymore. So for me this could be closed.

Thanks for oh-my-zsh, love it! :)

**Comment by apjanke** [comment]
Okay, cool. How about just close this, and we can reopen or make a new issue if someone else gets hit with the problem?

**Comment by peterlauri** [comment]
Sure.

**Comment by mcornella** [comment]
I believe this is related to svn-prompt and the pause is IO-related because the repo is so big. If this happens in the future, a good way to debug this is to enable XTRACE and VERBOSE (`set -xv`), which will print all zsh commands that are being executed, even prompt-related. 
Thanks for closing this.
