### ISSUE TITLE
About Ubuntu Linux Theme

### ISSUE THREAD

**Issue by SharkIng** [robbyrussell/oh-my-zsh#3355]
the sign ➜ is not working on Ubuntu Linux Right?? 
Is there any way to solve it?

**Comment by apjanke** [comment]
Probably a font or encoding issue. What font are you using in your terminal emulator, and what are your locale settings? That is, what is the output of `locale`? It should look something like this.

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by SharkIng** [comment]
Thank you for answering this question, it works fine on my Mac but not Ubuntu Linux, I just gave up since it's not a primary issue. Thanks again.
