### ISSUE TITLE
git plugin: allow to skip (possibly setup) git wrapper function (e.g. `hub`)

### ISSUE THREAD

**Issue by blueyed** [robbyrussell/oh-my-zsh#3363]
The git plugin should not use just `git` for most of its commands, but `command git` to avoid calling `hub` (a Ruby program setup to provide additional Github related features).

The following could be used to get the command that is also used by the Zsh's `vcs_info` backend:

    local git_cmd
    zstyle -s ":vcs_info:git:*:-all-" "command" git_cmd
    : ${git_cmd:=git}

Then the user would be able to configure this when they are using some `git` wrapper, like this:

    # use the git command for vcs_info, instead of hub!
    zstyle ':vcs_info:git:*:-all-' command $(whence -p git)

`$cmd_git` should then probably get used for anything that's not wrapped with extra functionality by `hub` (see https://github.com/github/hub).

/cc #2790 
/cc https://github.com/ncanceill/oh-my-zsh/commit/7f5f8c36f5935b8c3e8a53420d55d195e0ab0774#commitcomment-8782925

**Comment by ncanceill** [comment]
@blueyed, any update? I would like to get this into #2790.

**Comment by blueyed** [comment]
@ncanceill 
I am using this myself since a while without problems.

**Comment by apjanke** [comment]
This has [made it in to master](https://github.com/robbyrussell/oh-my-zsh/blob/57c2ac1e605c8cc3922c46109b8b65361e05acef/plugins/git/git.plugin.zsh#L1-L3). Work for you?

**Comment by blueyed** [comment]
Yes, thanks!
