### ISSUE TITLE
Order dependency between bundler and rails plugins

### ISSUE THREAD

**Issue by simonc** [robbyrussell/oh-my-zsh#3370]
Hi,

Using both the `bundler` and `rails` plugins, order between them matters.

Here is the observed behavior:
```
#.zshrc
plugins=(bundler rails)

$ type -a rake
rake is an alias for _rake_command
rake is /usr/bin/rake
```

```
#.zshrc
plugins=(rails bundler)

$ type -a rake
rake is an alias for bundled_rake
rake is /usr/bin/rake
```

Can this be considered a bug?

Thanks :)

**Comment by mcornella** [comment]
There's no way to know what the user wants. In this case, the plugin enabled last is the one with preference over the other. There's plenty of other similar situations between incompatible plugins. 

So, to answer your question... no, it's...a...feature? :grin: 
Please close the issue
