### ISSUE TITLE
Symfony2 plugin breaks path completions in arguments

### ISSUE THREAD

**Issue by stof** [robbyrussell/oh-my-zsh#3377]
Currently, the symfony2 plugin autocompletes symfony command names, which is awesome. However, once we have entered the command name, there is no autocompletion at all for command arguments. Several commands are expecting a path as argument, and the plugin prevents relying on the normal ZSH completion for paths when writing them. Could it fallback to normal ZSH completion for later args ?

**Comment by mcornella** [comment]
Closing for lack of viable solution.
