### ISSUE TITLE
Feature request: split plugins into submodules

### ISSUE THREAD

**Issue by adamwong246** [robbyrussell/oh-my-zsh#3379]
I really like oh-my-zsh but I feel that it's not right to have to download all the plugins, when I only use a few. 

I think the maintainer of each plugin should use the git subtree split technique to split plugins into separate repos and then add references to those repos as submodules. Oh-My-Zsh can continue to operate as usual while allowing those outside the oh-my-zsh ecosystem to use (and contribute to!) the project. 

I'm still working out the kinks but here's an example.
https://github.com/adamwong246/heck-yeah-zsh-colored-man - the colored-man plugin, split into a seperate repo. Ideally this would be maintained by the originator, in this case @moinakg. 

https://github.com/adamwong246/dotfiles - my dotfiles, which references the split repo as a submodule. 

Of course, this may introduce some extra cognitive overhead when merging and such but this approach allows for a more "federated" system of plugins.

**Comment by dritter** [comment]
:+1: The same applies to templates. I think it would unburden the OMZ-team from a lot of tasks and the vast amount of pull requests will decrease.. As a bonus: pull requests will be merged faster..

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

There is an ongoing discussion on project management and maintenance, but for now it has been temporarily chosen to keep everything in a single repository.

Besides, we do not have a dedicated maintainer for each plugin.

**Comment by dritter** [comment]
@ncanceill Can you say where the discussion is happening? Can't find anything in the wiki nor in the issues..

**Comment by ncanceill** [comment]
Some of it is in #2771.

**Comment by ncanceill** [comment]
Also some of it is in #1035.
