### ISSUE TITLE
encoding problem on OSX

### ISSUE THREAD

**Issue by flashpixx** [robbyrussell/oh-my-zsh#3384]
I use Oh-My-Zsh under OSX 10.9, but german chars e.g. ä,ü,ß are not displayed correctly in the command-line:

```
phil@imac ~/Documents/ » ls
Übung 1              Übung 3
Übung 2              Übung 4
phil@imac ~/Documents/ » cd U<0308>bung\ 4
```

**Comment by apjanke** [comment]
I assume that last command line is you doing autocompletion and hitting tab after the "U"?

This is normal ZSH behavior, not specific to oh-my-zsh. (See #3505.) By default, combining characters like umlauts and accents are displayed as their unicode values in the autocompletion process. To have them combine, enable the `combining_chars` shell option. You can put `setopt combining_chars` in your `~/.zshrc` to make it the default.
