### ISSUE TITLE
npm plugin slows terminal startup on osx

### ISSUE THREAD

**Issue by yekver** [robbyrussell/oh-my-zsh#3392]
If I just add a `npm` plugin in ~/.zshrc my terminal slows at startup.

After executing this command `/bin/zsh -i -x` I see that terminal freezes from 1 to 5 seconds at this line:
`+/Users/username/.oh-my-zsh/plugins/npm/npm.plugin.zsh:1> npm completion`

Everything becomes OK if I remove `npm` plugin from the ~/.zshrc file and directly execute one of this commands:
`npm completion >> ~/.zshrc`
`npm completion > /usr/local/etc/bash_completion.d/npm`

**Comment by mcornella** [comment]
We could probably cache the output of `npm completion` somewhere. You're right that it doesn't make much sense having that run every time.

**Comment by teddybradford** [comment]
:+1:
Ran into the same issue, so disabled the npm plugin for now.

**Comment by iamstarkov** [comment]
no pull-requests?

**Comment by apjanke** [comment]
This looks like the upstream issue: npm/npm#6671.

How would we determine cache freshness? The path and version of `npm` seem reasonable keys, but even getting the version of `npm` takes a quarter of a second on my MacBook Pro, about half as long as `npm completion` itself takes. Ouch.

```
$ time npm --version
3.3.9
npm --version  0.23s user 0.03s system 101% cpu 0.258 total
```

As a crude hack, we could just cache it on a per-machine basis, assume the version of `npm` stays the same, and require users to manually refresh the cache when the update `npm`. Or refresh the cache automatically every week or so (which I'm not a fan of; it'll catch up eventually, but then you get inconsistent behavior).

The `$ZSH_CACHE` dir is per OMZ install, so we could either subdivide that using a `npm/<host>` directory tree, at the cost of syncing every machine's cache everywhere (and assuming host names are reliable). Or we could make a new per-user-host cache location (like `~/.oh-my-zsh-cache`, call it `$ZSH_CACHE_LOCAL`).

A nicer solution might be to get a static completion definition as part of the npm installation. Then you'd just stick it on your `$fpath` as part of locating `npm`. But that's not something OMZ can do on its own.

**Comment by apjanke** [comment]
I suppose freshening the cache daily wouldn't be bad; you'd only have to pay that one startup per day. I guess it's a question of whether the different versions of `npm` have significant differences in completion behavior.

We could also write a lazy-loading shim for the completion function so it only gets invoked the first time you actually try to complete something with `npm`, so you only pay that 1/4 sec once in each session where you use `npm`. Not bad for occasional use and much better for correctness. Still ugly if you're going to use it often.

**Comment by apjanke** [comment]
(This is likely to be slow on all platforms; the "on OS X" can probably be removed.)

**Comment by fx3O2** [comment]
Yes confirmed, slow on archlinux as well. :turtle:
