### ISSUE TITLE
Explicitly document that customizing ZSH settings should come after loading oh-my-zsh

### ISSUE THREAD

**Issue by unixorn** [robbyrussell/oh-my-zsh#3418]
We should document more clearly that variable customization should always come after loading oh-my-zsh in `.zshrc`, otherwise some settings will be clobbered by oh-my-zsh. See #3359 for an example of why we shouldn't just skip setting those variables in oh-my-zsh if they're already set.

**Comment by apjanke** [comment]
I put together a draft for a design/architecture Wiki page that discusses configuration variables. Might be a decent place to document this.

https://github.com/apjanke/omz-scratch/wiki/OMZ-Design
