### ISSUE TITLE
Color themes

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#3439]
It would be nice to have some predefined color themes. This could be difficult to implement due to the fact that each terminal have its own way to customize but it is still a very good idea. Maybe someone could present a clever way to do that.

**Comment by mcornella** [comment]
I presume you meant color schemes. This one is a difficult, possibly impossible feature. For now we're requiring theme creators to specify their color scheme used in the screenshots they provide. 
That's all we can do I think.
Will close in #3651.

**Comment by Mayccoll** [comment]
i made this:
https://github.com/Mayccoll/Elementary-OS-Terminal-Colors
using http://ciembor.github.io/4bit/
suddenly could use a similar approach
