### ISSUE TITLE
Update Error!!!

### ISSUE THREAD

**Issue by chinxianjun** [robbyrussell/oh-my-zsh#3446]
.oh-my-zsh/oh-my-zsh.sh:30: parse error near `||'

**Comment by mcornella** [comment]
What's the status on this one?

**Comment by DuGuille** [comment]
Im getting the same error

**Comment by mcornella** [comment]
Have you tried @yachi's suggestion? Run `git config --get core.autoclrf` to find out

**Comment by samu** [comment]
had to use `dos2unix` to fix this problem:

`find . -type f -exec dos2unix {} \;`

**Comment by apjanke** [comment]
Sounds like a local Git configuration error on Cygwin. Can we close this?
