### ISSUE TITLE
oh-my-zsh uninstall.sh issues - switch back to bash is unsatisfactory

### ISSUE THREAD

**Issue by sr-murthy** [robbyrussell/oh-my-zsh#3447]
Hi

I recently installed `oh-my-zsh` on my system (running OS X Yosemite, v. 10.10.1, with `bash` (v. 3.2.53) as default, to test it out.  It was really interesting, but wanting to get back to `bash` I ran the uninstall script and noticed two minor problems with it (with easy fixes):
1. it does not make the change to the user visible in the _current_ shell window - this is because the although the relevant line `chsh -s /bin/bash` (line 24 in `uninstall.sh`) will certainly change the `UserShell` property in the user's record in the OS X Directory Services database (for the local domain node "`.`") from `bin/zsh` to `/bin/bash`, the change will not be applied to the user's current (presumably `bash`) shell window - they have to open a new window (after possibly closing the current one, or from the existing one).  Of course the user may know this, but also they may not, but it would seem a nice to idea to have this done cleanly so that the uninstallation appears painless.  I propose a simple fix - do `exec su - $USER`, which replaces the current shell instance with a new one, immediately after `chsh -s /bin/bash`.  Some prompting, pre- and post-execution checking may be required.
2. it sources `/etc/profile` (after doing `chsh -s /bin/bash`).  This seems unnecessary according to the [OS X bash man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/bash.1.html) `/etc/profile` is sourced first after `bash` is invoked as an interactive login shell (or a non-interactive login shell with the `--login` option).  So having done `chsh -s /bin/bash` the user would be expected to open either a new window from their terminal app or close and reopen their terminal app, which will start an interactive login `bash` shell that will source `/etc/profile` first.  Thus this is unnecessary in the uninstall script.

I have forked this repo, applied the changes and made a [pull request here](https://github.com/robbyrussell/oh-my-zsh/pull/3454).

**Comment by mcornella** [comment]
Hey @sr-murthy, #5169 deals with this and it's now ready to test. If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!
