### ISSUE TITLE
Old command not working

### ISSUE THREAD

**Issue by gizburdt** [robbyrussell/oh-my-zsh#3457]
Hi,

I installed oh-my-zsh. I really like the themes and plugins. But I have a problem, my old command aren't working anymore (npm, bower, yo).

This is my `.zshrc` file:
```
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="cloud"

# Plugins
plugins=(git)

# User configuration
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"
export PATH=/usr/local/share/npm/bin:$PATH
source $ZSH/oh-my-zsh.sh

# SSH
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Aliases
alias sudo='sudo '
```

Please help me

**Comment by apjanke** [comment]
What OS are you on? Was this `.zshrc` file created by the oh-my-zsh installer? If so, what was your .zshrc like before the installation? What happens when you try to run `npm` or `bower`?

**Comment by gizburdt** [comment]
I already fixed it :) Missed some PATHs.
