### ISSUE TITLE
How about setting HISTTIMEFORMAT by default 

### ISSUE THREAD

**Issue by tobegit3hub** [robbyrussell/oh-my-zsh#3466]
We always `export HISTTIMEFORMAT="%y/%m/%d T "` in ~/.zshrc after install oh-my-zsh. It's generally used so how about setting this by default?

**Comment by tobegit3hub** [comment]
It seems that zsh doesn't support HISTTIMEFORMAT yet.

I should close this with won't fix :smiley:

**Comment by MyChaOS87** [comment]
History time is stored in zsh by default you only need ativate the output for that in your .zshrc, there is even a commet telling what to do:

> # Uncomment the following line if you want to change the command execution time
> # stamp shown in the history command output.
> # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"

**Comment by tobegit3hub** [comment]
Thanks @MyChaOS87 for telling me about that :smiley:

**Comment by Gnodiah** [comment]
add one line `HIST_STAMPS="yyyy-mm-dd"` to file `.zshrc`, then `source ~/.zshrc`.

**Comment by tobegit3hub** [comment]
Sorry @Gnodiah it doesn't work for me :-(

**Comment by Gnodiah** [comment]
@tobegit3hub Sorry I forgot to tell you I use oh-my-zsh, maybe you can try `alias history='fc -il 1'`

**Comment by tobegit3hub** [comment]
It works like a charm. Thanks @Gnodiah very much :smile:

**Comment by ubuhuo** [comment]
@gnodiah Thanks for your advice, It works.
