### ISSUE TITLE
Syntax highlighting in less

### ISSUE THREAD

**Issue by pickfire** [robbyrussell/oh-my-zsh#3468]
I hope that there is a syntax highlighting in less although it is a bit different from the syntax highlighting in vim. Take a look at this:

https://linux-tips.org/article/78/syntax-highlighting-in-less

**Comment by pickfire** [comment]
And for using vim: 

http://vim.wikia.com/wiki/Using_vim_as_a_syntax-highlighting_pager

**Comment by linux-modder** [comment]
why not add a scripted alias in your ~/.zshrc?

**Comment by pickfire** [comment]
Thanks. I am just suggesting.
