### ISSUE TITLE
[Bower] install certain version not working

### ISSUE THREAD

**Issue by ImBobby** [robbyrussell/oh-my-zsh#3469]
Doing this
```Bash
bower i jquery#1.11.2 --save
```

returns **zsh: no matches found: jquery#1.11.2**. But when I switch to bash, it works as expected.

**Comment by mcornella** [comment]
It interprets the `#` as a globbing character, you have to wrap it between single commas (`'`) or put `noglob` before bower. You can also define an alias to use noglob by default: `alias bower='noglob bower'`

**Comment by ImBobby** [comment]
Ah I see, it does solve my problem. Thank you @mcornella.
