### ISSUE TITLE
didn't find any theme for full path + display git changes

### ISSUE THREAD

**Issue by ohadpartuck** [robbyrussell/oh-my-zsh#3484]
Hi, I'm looking for theme to display a full path + git (branch name + uncommitted changes + added files).
Didn't find any. 
would love a recommendation of one / a tip of how to edit an existing one (I am currently using Godzilla).

**Comment by apjanke** [comment]
In `gozilla.zsh-theme`, change the `%c` (trailing component of pwd) to `%d` (full path of pwd). The customized version should go in your `$ZSH_CUSTOM/themes` directory.

See [Prompt Expansion in the Zsh Reference Manual](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Prompt-Expansion) for details on how it works and other prompt stuff you can do.

**Comment by apjanke** [comment]
BTW, @Gozala, what's the `%p` expansion in gozilla's `$PROMPT` for? That's the time in `tcsh` prompt configuration, but AFAIK, `%p` isn't supported by ZSH. `%*` might be the zsh equivalent.

**Comment by ohadpartuck** [comment]
thanks, solved it by editing the 
`~/.oh-my-zsh/themes/gozilla.zsh-theme`
changed the PROMPT to 
`PROMPT='$(rvm-prompt) %{$fg_bold[red]%}➜ %{$fg_bold[green]%}%p %{$fg[cyan]%}%d %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_    bold[blue]%} % %{$reset_color%}'`
