### ISSUE TITLE
Theme disabled after installing powerline

### ISSUE THREAD

**Issue by ahmgeek** [robbyrussell/oh-my-zsh#3487]
here is my ```.zshrc``` file:

```
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="amuse" 

plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

. /usr/local/lib/python2.7/dist-packages/powerline/bindings/zsh/powerline.zsh 

```

the last line points to my powerline.zsh, and the  theme is "amuse", so instead of having something like this image 
![zsh](https://camo.githubusercontent.com/7b7e68d1c60dcc1874a2a069df842036821b7f77/68747470733a2f2f6769746875622d63616d6f2e676c6f62616c2e73736c2e666173746c792e6e65742f646265323865366430376637303061393631343961333666653438666639633036356161653134662f36383734373437303361326632663634363837323735373636313733363136373631373232653633366636643266373737303264363336663665373436353665373432663735373036633666363136343733326633323330333133333266333033333266343136643735373336353265373036653637) 

I got this instead

![img](https://imgur.com/oou2f63.jpg)

**Comment by Kriechi** [comment]
Thats the way powerline works. 
Why did you install powerline? What features did you expect to get?
