### ISSUE TITLE
Not autocompleting named directories

### ISSUE THREAD

**Issue by felipellrocha** [robbyrussell/oh-my-zsh#3492]
Hey guys!

I've recently upgraded OMZ to the latest version, but not it won't autocomplete any of my named directories.

Any thoughts on why that might be happening?

Felipe Rocha

**Comment by mcornella** [comment]
You need to reenable `autonamedirs` option (see #3252 on why it was removed). 
You can enable it by putting `setopt autonamedirs` at the end of your zshrc file

**Comment by felipellrocha** [comment]
Ah! Great! Yes! I've been missing that feature, and I couldn't find the documentation saying where things had changed! Thanks!

**Comment by ncanceill** [comment]
Hi @felipellrocha, since your problem seems solved can you close this Issue? Thanks.
