### ISSUE TITLE
Home and End keys aren't working

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#3495]
On Ubuntu 14.04 the Home|End keys work very well.
On Centos 5.10 these keys work on a bash but not in zsh.

Thus, sometimes the prompt lose its position:
![selection_011](https://cloud.githubusercontent.com/assets/1277920/5758066/f4174de4-9ca8-11e4-9b05-bda373b944d1.png)

**Comment by leoheck** [comment]
In Ubuntu is ok now but in Centos not.

**Comment by apjanke** [comment]
When you say they don't work in `zsh`, do you mean they do nothing at all? Or they move the cursor to the wrong place? Or something else?

**Comment by leoheck** [comment]
I think they were moving to wrong places, I don't remember. BUT, I was using zsh version ```4.*```, and it was working with the following workaround:
```
#Rebind HOME and END to do the decent thing:
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
case $TERM in (xterm*)
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
esac

#To discover what keycode is being sent, hit ^v
#and then the key you want to test.

#And DEL too, as well as PGDN and insert:
bindkey '\e[3~' delete-char
bindkey '\e[6~' end-of-history
bindkey '\e[2~' redisplay

#Now bind pgup to paste the last word of the last command,
bindkey '\e[5~' insert-last-word
```
last week I updated to ```5.0.2```, and It is working fine without the workaround!

**Comment by apjanke** [comment]
That sounds a lot like an issue related to `terminfo` definitions, bad key bindings, and/or the `smkx`/`rmkx` problem popping up in a couple plugins, like #3061 or #2735. In particular, I suspect that maybe this part where you're unconditionally binding these two sequences was letting Home and End work in a terminal that's stuck in "keypad local' (`rmkx`) mode.

```
#Rebind HOME and END to do the decent thing:
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
```

On the other hand, might have been something totally backward from that. Hard to know without knowing the details of your whole terminal stack setup; this stuff is complicated.

If it crops up again in 5.x for you, hop on one of those comment threads. I also just wrote [a little key binding diagnostic tool called `omz_bindkey_dump`](https://github.com/apjanke/oh-my-zsh-custom/blob/ef94f9f81c6a9f79a13a976a9c65a6d648af9506/diagnostics-extras.zsh) that can help you diagnose key binding problems like this.
