### ISSUE TITLE
Tab autocompletion of accented characters not working

### ISSUE THREAD

**Issue by nunoh** [robbyrussell/oh-my-zsh#3505]
When I use oh-my-zsh, doing `cat c<tab>` autocompletes to `cat ca<0303>o.txt`, instead of `touch cão.txt`. If I uninstall oh-my-zsh it works ok again and as expected. Also in every other kind of bash it works ok, only oh-my-zsh is breaking that. I've tried uninstalling and reinstalling again with vanilla configuration and the issue persisted.

I've posted before (12 days ago) [a question on unix.stackexchange.com] (http://unix.stackexchange.com/questions/178038/tab-autocompletion-of-accented-characters-with-oh-my-zsh-doesnt-work) about this, but I wasn't able to reach a fix for this problem. 

Could this actually be oh-my-zsh problem or any idea what I might be missing in my setup? Thanks!

**Comment by mcornella** [comment]
Maybe it has something to do to with your locale. Post the output of `locale`

**Comment by nunoh** [comment]
Here it is:
```
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
For the `LANG` variable I've tried empty, `"en_US.UTF-8"` and `"pt_PT.UTF-8"` and the issue still persists... Then I type `zsh` and it autocompletes ok. Can't really understand why...

Oh, and thanks for your time trying to help of course :)

**Comment by mcornella** [comment]
Ok that's not it then. `$LC_CTYPE` is the important one and it's already using UTF8. Maybe you should try setting your system to use portuguese by default (if you don't know how, you can set both `LC_ALL` and `LANG` to `pt_PT.UTF-8`).

**Comment by nunoh** [comment]
I've tried that and still doesn't work.. :frowning: Any other idea maybe?

**Comment by mcornella** [comment]
This exact same thing happened to a friend of mine. He's using Ubuntu 14.04 and Guake as Terminal Emulator. Maybe I can get him to let me troubleshoot his setup.

For the time being, you can try disabling oh-my-zsh and running clean zsh, and see if it happens the same. Follow this instructions:

1. Backup and remove zshrc file: `mv ~/.zshrc{,.bak}`
2. Restart terminal
3. A menu will appear, choose option that installs recommended zshrc default file (this should get autocompletion up and running)
4. Restart terminal if needed and test again your problem

**Comment by nunoh** [comment]
I've tried following your instructions, but at 3), no menu appear... If I remove the `.zshrc` file I still get problems with the autocomplete..

**Comment by apjanke** [comment]
I don't want to sound paranoid, but it seems like something strange is going on here. I'm on OS X 10.9, and when I removed `~/.zshrc` to try to reproduce this, I am also no longer getting the "new user" menu when launching zsh. And I can't run it manually by doing `zsh-newuser-install`. This is unexpected. And I'm pretty sure it's new; I've done the new-user menu on this machine many times before for testing. 

I just made a fresh 10.10 Yosemite install, and it also is not presenting a new-user menu, even when I open terminal and run `zsh` as the first thing after installing the OS.

I can get it to run if I explicitly autoload it before invoking it. But I remember the zsh startup sequence doing it for me automatically in the past.

```
autoload -U zsh-newuser-install
zsh-newuser-install -f
```

The ZSH INSTALL file says:
```
In the default configuration, the shell comes with a system based around
the zsh/newuser add-on module that detects when a user first starts the
shell interactively and has no initialisation files (.zshenv, .zshrc,
.zprofile or .zlogin).  The shell then executes code in the file
scripts/newuser in the shared library area (by default
/usr/local/share/zsh/<VERSION>/scripts/newuser).
```

But I don't see any files under scripts/ on my machine.
```
eilonwy% ls /usr/share/zsh/5.0.2/scripts 
eilonwy% 
```

Any ideas what's going on here?

**Comment by apjanke** [comment]
I checked 10.8, too. None of OS X 10.8, 10.9, or 10.10 have the scripts for automatic running of `zsh-newuser-install`. I must simply be misremembering having it happen on these machines.

@nunoh, if you're removing `~/.zshrc`, oh-my-zsh shouldn't be loading at all. Do the autocomplete problems still happen after you open a new terminal window with zsh running in it after removing `~/.zshrc`?

I think what's happening is that the `cat ca<0303>o.txt` behavior is actually `zsh`'s default behavior. U+0303 is the code point for the tilde character; it's being displayed as its Unicode equivalent instead of backing up and changing the `a` character. (This may be to make it easier to work with multiple-combining-chars compositions.) This beahvior is controlled by the `combining_chars` zsh option. Maybe something in `oh-my-zsh`, or the script you used to invoke or customize it, used to turn `combining_chars` on for you, and now it's not doing it any more.

At any rate, I can reproduce, in a bare zsh. Here's what happens when I do `ca<tab>` with and without the `combining_chars` option enabled.

```
eilonwy% ls ~/.zshrc
ls: /Users/janke/.zshrc: No such file or directory
eilonwy% ls -d c*
cão.txt
eilonwy% cat ca<0303>o.txt 
hello
eilonwy% setopt combining_chars
eilonwy% cat cão.txt 
hello
eilonwy% 
``

I don't see anything in oh-my-zsh's codebase that affects the `combining_chars` option. So I'm guessing something else was setting it for you, and the oh-my-zsh interaction is a red herring.

Try going back to using oh-my-zsh, and put this in your `~/.zshrc` file after the part that loads oh-my-zsh.

    setopt combining_chars

**Comment by apjanke** [comment]
Based on your SO question, maybe your `/etc/zshenv` is what was setting `combining_chars` for you, and something later is clobbering it. Can you post the output of `cat /etc/zshenv`?

**Comment by nunoh** [comment]
First off, thanks so much @apjanke, you're the man! :bow: 

That `setopt combining_chars` did the trick. I was starting to think I wasn't going to get a fix for this, which sucks quite a lot because some team members keep on insisting on using Portuguese file and folder names (which have a lot of accented characters). 

Here's the output for the `/etc/zshenv`:
```
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

I'm not sure whether to close or not the issue already, not sure if you are digging into the oh-my-zsh (or even zsh) code to fix this or something similar. From my part, feel free to do it or let me know if I should. Thanks again.

**Comment by apjanke** [comment]
You're welcome!

Go ahead and close ! please. This sounds like it was just a matter of getting your local config files right for your use case, and not a zsh or oh-my-zsh issue: if that's your `/etc/zhsrc`,zsh and omz are working as expected and there's no changes to be done.

**Comment by mcornella** [comment]
Thanks @apjanke for solving this bad boy! I guess we should add `setopt combining_characters` somewhere on our lib files.
