### ISSUE TITLE
zsh: command not found: brew

### ISSUE THREAD

**Issue by almogdesign** [robbyrussell/oh-my-zsh#3507]
I'm getting zsh: command not found: brew and for mongoDB both are installed and in .zshrc file I have the following

export PATH=$HOME/bin:/usr/local/bin:$PATH

I also tried

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"
export PATH="/bin /usr/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/bin /usr/local/git/bin"

**Comment by apjanke** [comment]
Hmm. Seems like it should work. `/usr/local/bin` is the usual install location for `brew`.

Can you post your entire `~/.zshrc` file as a gist, and your output for the following sequence of commands?

```
which brew
brew
ls -l /usr/local/bin/brew
set | grep -a PATH
```

**Comment by almogdesign** [comment]
Got it working had to uninstall and reinstall everything

**Comment by robbyrussell** [comment]
:+1:

**Comment by Zorigt** [comment]
Uninstalling and re-installing homebrew didn't work, but I did the following which worked for me. 

Open the text ~/.zshrc  file in text editor like vim or similar. Then, uncomment the export line for the below section. Source your file. 

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

**Comment by Hellowor1d** [comment]
If you use zsh in Debian

have a try:
```shell
#  ~/.zshrc
export PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
```

**Comment by amairi** [comment]
echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/$HOME/.zshrc

**Comment by tyirvine** [comment]
Don't forget to close and open a new zsh/bash session after installing HomeBrew. I forgot to do this wondering why it wasn't working lol
