### ISSUE TITLE
zsh: locking failed for [user]/.zsh_history: permission denied: reading anyway

### ISSUE THREAD

**Issue by RichardDooling** [robbyrussell/oh-my-zsh#3512]
I installed a new hard drive on Mac OS X (Yosemite) and after restoring from Time Machine backup I am getting this error whenever I start a new shell in iterm2? I see some references to it when I Google search but no solutions. Any ideas? THANK YOU

**Comment by robbyrussell** [comment]
@RichardDooling You might look at OS X's disk repair to check permissions (and repair)

http://osxdaily.com/2015/01/13/repair-disk-permissions-mac-os-x/

**Comment by netxixi** [comment]
try it
chmod 755 /usr/local/share/zsh
chmod 755 /usr/local/share/zsh/site-functions

**Comment by suside** [comment]
zsh is creating `.zsh_history.LOCK` in the same directory `.zsh_history` exists, so you have to be owner of that dir

**Comment by Brannua** [comment]
> @RichardDooling You might look at OS X's disk repair to check permissions (and repair)
> 
> http://osxdaily.com/2015/01/13/repair-disk-permissions-mac-os-x/

hi, on manjaro linux, i also find the same question, i would appreciate it if you can give me some solutions.

**Comment by mcornella** [comment]
Can you post the exact error you get, as well as an `ls -l` of the file the error mentions?

**Comment by lacostenycoder** [comment]
I'm now having this issue running Linux Mint 20.1  I tried @Brannua idea, and I get
```
➜  ~ sudo chmod 755 /usr/local/share/zsh/site-functions
[sudo] password for lance:          
chmod: changing permissions of '/usr/local/share/zsh/site-functions': Read-only file system
```

**Comment by steakknife** [comment]
Also encountered this message when macOS decided to effectively `chmod 550` my home directory after I only changed all *share permissions* to "Read Only". With that change, zsh running as the current user could no longer create `.zsh_history.LOCK` for synchronizing access to `.zsh_history`. `chmod 750 ~` fixed it.

**Comment by rootsiona** [comment]
[sudo] senha para hackerroot: 
zsh: locking failed for /root/.zsh_history: o ficheiro existe

**Comment by jd-apprentice** [comment]
I have this issue and I can't fixed yet, any one got an idea?

OS: Ubuntu 20.04
Zsh 5.8

**Comment by colby-ham** [comment]
Deletion worked for me https://unix.stackexchange.com/a/628065/346403

**Comment by rwmitchell** [comment]
Who owns the file?  What are the perms?

**Comment by Xmuluneh** [comment]
muluneh owns the file as well as the root user for the machine 

> Who owns the file? What are the perms?

muluneh owns the file as well as the root user for the machine

**Comment by mcornella** [comment]
Please post the full output of `ls -l ~/.zsh_history`

**Comment by Xmuluneh** [comment]
<img width="779" alt="Screen Shot 2023-02-01 at 8 32 34 PM" src="https://user-images.githubusercontent.com/71099880/216119185-45367a4f-2c24-4bf7-946b-a5e93d90c2c7.png">


>

**Comment by Xmuluneh** [comment]
> Please post the full output of `ls -l ~/.zsh_history`

Thanks man for ur help

**Comment by mcornella** [comment]
Check if this document helps: https://jdhao.github.io/2021/08/15/mac_operation_not_permitted/.

**Comment by svarup** [comment]
None of the above solution helped, after lot of searching find out below solution that worked for me

Got to Macintosh HD -> Users -> and then right click on "Your Username" folder and select "Get Info" then unchecked "Locked".

**Comment by stcaptain** [comment]
> Got to Macintosh HD -> Users -> and then right click on "Your Username" folder and select "Get Info" then unchecked "Locked".

That's right, just add permissions to the root directory

**Comment by HKirito** [comment]
Or you can Got to Macintosh HD -> Users -> and then right click on "Your Username" folder add you account，In the “Sharing and Permissions” section of the “Show Profile” column, click on the “+” at the bottom right to add your own username and give it read and write permissions, which works for me!

**Comment by HKirito** [comment]
Or you can Got to Macintosh HD -> Users -> and then right click on "Your Username" folder add you account，In the “Sharing and Permissions” section of the “Show Profile” column, click on the “+” at the bottom right to add your own username and give it read and write permissions, which works for me!

**Comment by NajimFS** [comment]
> Or you can Got to Macintosh HD -> Users -> and then right click on "Your Username" folder add you account，In the “Sharing and Permissions” section of the “Show Profile” column, click on the “+” at the bottom right to add your own username and give it read and write permissions, which works for me!

Thanks a lot, this did it for me!
