### ISSUE TITLE
lxc-docker support (docker.io error)

### ISSUE THREAD

**Issue by mishak87** [robbyrussell/oh-my-zsh#3520]
Upon completion for `docker` command I get
```
(eval):1: _docker.io: function definition file not found
(eval):1: _docker.io: function definition file not found
(eval):1: _docker.io: function definition file not found
```

lxc-docker replaces old docker.io

OS: Ubuntu 14.04 LTS 
Docker: version 1.4.1, build 5bc2ff8
lxc-docker: 1.4.1
docker.io: not installed

**Comment by mralbu** [comment]
Had the same error.
This solved it for me
http://stackoverflow.com/questions/10585002/zsh-complains-about-rvm-rvm-cleanse-variables-function-definition-file-not-fo

**Comment by mcornella** [comment]
@mishak87 the solution from @mralbu was to run `rm -f ~/.zcompdump*`. Can you try and test if it works (and if so, close this issue)?

**Comment by mishak87** [comment]
Closing now it works with lxc-docker 1.8.1 (same system). I have updated oh-my-zsh at least once since posting this issue.
