### ISSUE TITLE
git plugin uses '--ignore-submodules=dirty'

### ISSUE THREAD

**Issue by hansbogert** [robbyrussell/oh-my-zsh#3532]
When cwd is a git directory I get:

```
error: invalid option: --ignore-submodules=dirty
```

Git version is:

```
git --version
git version 1.7.1
error: invalid option: --ignore-submodules=dirty
```

**Comment by ncanceill** [comment]
This is not related to the `git` plugin but to the [`git` lib](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh). This should not happen because we specifically check for a `git` version of at least 1.7.2, which is the first one to support `--ignore-submodules=dirty` for `git status`.

This is likely because you have multiple `git` installations, one of those above 1.7.2, and one at 1.7.1 which gets added to your `$PATH` later on during init.

Can you `source` this [script](https://gist.github.com/ncanceill/e941de4b6a59646df457) and tell me what it prints?

**Comment by hansbogert** [comment]
````
$ source test.sh
git version 1.7.1
-1
nocando
error: invalid option: --ignore-submodules=dirty
````

Indeed on this cluster node there are multiple git versions, however just the typical /usr/bin/git is on the path in my case. Due to restrictions I cannot run zsh as the first shell, so I start zsh through bash. 

But I am not entirely sure in which sequence events (whether being on the PATH or not for a specific GIT) this occurs.

**Comment by ncanceill** [comment]
Oh wait, of course this will not work that way, can you copy that same script into `$ZSH_CUSTOM` and open a new shell?

**Comment by hansbogert** [comment]
So you mean in the initial bash login shell, set the $ZSH_CUSTOM with the contents of the scripts and then run zsh?

**Comment by ncanceill** [comment]
No, sorry I am not clear.

`$ZSH_CUSTOM` points to your custom OMZ directory, by default `$ZSH/custom`, where `$ZSH` points to your OMZ install directory, by default `~/.oh-my-zsh`.

So `$ZSH_CUSTOM` is a directory, copy the file in there. Then open a new Zsh from anywhere.

**Comment by hansbogert** [comment]
Can't seem to get that working
I use OMZ through antigen. I've added the script as test.zsh to, in my case:
````
/home/vdbogert/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh.git/custom/
````
But files inside this custom dir do not seem to work. I've even set $ZSH_CUSTOM in my login bash shell, pointing to the above path just to make sure, still nothing is run.

**Comment by mcornella** [comment]
Hi @hansbogert I'm not familiar with how antigen starts OMZ, can you post your `.zshrc` as well as the output of `echo $ZSH_CUSTOM`?

**Comment by hansbogert** [comment]
.zshrc:
````
source ~/antigen.zsh
antigen use oh-my-zsh
antigen theme agnoster
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle sharat87/autoenv

antigen apply

alias cds="cd /var/scratch/vdbogert"
````

````
echo $ZSH_CUSTOM
[empty]
````
Unless I set it manually to $ZSH/custom, but as described above that does not remedy the issue of being able to start the test script in the way @ncanceill wants

**Comment by mcornella** [comment]
Closing for being an old issue. Reopen if it still applies.
