### ISSUE TITLE
add `git add --all` alias

### ISSUE THREAD

**Issue by itsNikolay** [robbyrussell/oh-my-zsh#3535]
It would be great to have alias something like this:
`gaa` to `git add --all`

**Comment by tejasbubane** [comment]
:+1: I think this is handy.

**Comment by Newman101** [comment]
Done, please refer to #3556.

**Comment by MarcoSero** [comment]
Has this been removed? I just updated to the latest version and I don't see it anymore.

**Comment by tejasbubane** [comment]
Ya even I don't see it in the [file](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh).

**Comment by ncanceill** [comment]
It was removed in the latest update, but I will gladly bring it back for you if you really want it. In the meantime you can use `ga -A` which is only two characters longer.
