### ISSUE TITLE
Add git-open

### ISSUE THREAD

**Issue by tejasbubane** [robbyrussell/oh-my-zsh#3546]
I am using @paulirish's [git-open](https://github.com/paulirish/git-open) and I am loving it.
Can we integrate this in oh-my-zsh's git plugin?

**Comment by mcornella** [comment]
Adding binaries doesn't seem to be a good use of this repository: why not adding [`hub`](https://github.com/github/hub) too or other git related utilities? We would have to provide support for that, and we'd be splitting support requests between both repositories. Plus, we have enough trouble as it is to keep up with issues.
Instead, we should keep this project to the smallest possible size.

**Comment by tejasbubane** [comment]
@mcornella It is a single shell script https://github.com/paulirish/git-open/blob/master/git-open

**Comment by paulirish** [comment]
While I do love my own scripts, I do agree it should remain outside of this project.

**Comment by tejasbubane** [comment]
Ok then, closing this issue.

**Comment by mcornella** [comment]
Thanks Paul.
