### ISSUE TITLE
segfault with ubuntu 12.04

### ISSUE THREAD

**Issue by evandrojr** [robbyrussell/oh-my-zsh#3548]
Hi guys,

I get a segfault after 2 minutes I run any command at the shell. Even a 'ls' causes that.

Feb  4 10:20:35 venus1553624 kernel: [  268.932535] zsh[18525]: segfault at 0 ip b759d5e2 sp bfe9f490 error 6 in libc-2.15.so[b750f000+1a4000]

Any hint?

**Comment by mcornella** [comment]
What version of zsh are you running? What's your `.zshrc`, `.profile` files contain. Does it happen without oh-my-zsh enabled (using a blank zshrc file)?

**Comment by mcornella** [comment]
It may also be a bug in the `glibc` library provided by Ubuntu, see if you have any pending updates to install
