### ISSUE TITLE
ssh-agent replacing existing ssh identity with empty one when zsh is started.

### ISSUE THREAD

**Issue by Schabernack** [robbyrussell/oh-my-zsh#3562]
Using OSX with latest ohmyzsh and the ssh-agent plugin.

Keys get loaded locally, connecting to local tmux sessions works as well. I ssh into a remote box, get thrown into a bash shell: `ssh-add -l` shows the key being available.

starting zsh now results in this:

```
[nmn@xxx ~]$ zsh
(default)nmn@xxx ~ $ ssh-add-l                                                                                                                                                         
The agent has no identities.
```

When starting zsh after keys are loaded in bash, keys are not inherited. 

update:
checking env on remote:
in bash:
SSH_AUTH_SOCK=/tmp/ssh-MSzBEb3924/agent.3924

after starting zsh:
SSH_AUTH_SOCK=/tmp/ssh-CuFjA24566/agent.24566

**Comment by Schabernack** [comment]
@docwhat @nishigori @gwjo maybe one of you guys have any ideas since you already worked on the ssh-agent plugin?

**Comment by docwhat** [comment]
There are some really annoying edge cases for doing what this plugin tries to do. As well as some unobvious security concerns. 

I've switched to using `keychain` instead. Sorry.

**Comment by ncanceill** [comment]
May be related to #3019.

**Comment by mcornella** [comment]
The ssh-agent plugin needs to check for existing `$SSH_*` variables for alive ssh-agents and act accordingly.

**Comment by mcornella** [comment]
This should be fixed with the released updates to the ssh-agent plugin. Reopen if necessary.
