### ISSUE TITLE
Main $ZSH variable for OMZSH causes conflicts

### ISSUE THREAD

**Issue by ravenoak** [robbyrussell/oh-my-zsh#3565]
Does anyone know if there is a way to get around the issue that occurs when other things are using the $ZSH variable?  At work, they have it set up so that $ZSH contains the actual shell path for some things, and forking OMZSH just to change a variable name seems daunting.

Thanks!

**Comment by mcornella** [comment]
You should be fine by replacing all instances of `$ZSH` in the oh-my-zsh folder, there's really nothing else to it.
Remember to replace it in the zshrc file too.

**Comment by texastony** [comment]
`grep -rlZP '\$ZSH(!?(_|\w))' <path-to-omzsh> | xargs -0r perl -pi -e "s/\$ZSH(!?(_|\w))/\$OMZSH/g;"`
