### ISSUE TITLE
New Terminal tabs no longer default to the current working directory

### ISSUE THREAD

**Issue by jdsimcoe** [robbyrussell/oh-my-zsh#3570]
I just ran the update to `oh-my-zsh` and now when I open new tabs in Terminal they default to my home directory (`~`) instead of the current working directory. Do you know what might be causing this?

**Comment by mcornella** [comment]
Are you by any chance running iTerm2 and have the auto-title functionality disabled?

**Comment by jdsimcoe** [comment]
Nope. Running in Terminal on Yosemite 10.10.2. It was working splendidly until today.

**Comment by mcornella** [comment]
Oh yeah, sorry, I mistook iTerm2 for Terminal.app. Can you confirm my hypothesis by running `echo $TERM_PROGRAM $DISABLE_AUTO_TITLE` and posting the output?

**Comment by jdsimcoe** [comment]
`Apple_Terminal true`

**Comment by mcornella** [comment]
Ok, as I thought. This is a consequence of both #3525 and #3568 being merged (and my shortsight to not check out the changes in #3568). I've created PR #3571 to fix this problem. 
If you want to try it you can use [`hub`](https://github.com/github/hub) to `hub checkout URL-of-PR` to test the functionality. Or you can manually make the change.

**Comment by mcornella** [comment]
Could you test it?

**Comment by jdsimcoe** [comment]
@mcornella That fixes it.
