### ISSUE TITLE
termsupport Terminal.app stuff fails for dirs with special chars and remote hosts

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#3581]
Couple bugs in the `lib/termsupport.zsh` implementation of Apple Terminal.app cwd-update support.

It fails on directories with special characters in their name, because only spaces are being URL-escaped. For example, if I do this, Terminal.app ends up incorrectly showing `tmp` as the current directory.

    $ cd tmp
    $ mkdir '$#@%^&*%$'
    $ cd '$#@%^&*%$/'

There's an alternate implementation in the `terminalapp` plugin that URL-escapes all special characters, and works for directories like this.

Also, it's using $HOSTNAME instead of $HOST. $HOSTNAME is a bash-ism and isn't necessarily set under zsh. If $HOSTNAME is unset, it gets replaced with a blank, so the reported `file:` URL always looks like it's on the local host. Fine if you're running zsh locally, but if you're logged in to a remote machine, it'll think the dirs are on localhost instead, so they'll be displayed incorrectly.

Discovered this stuff during the discussion on #2932.

**Comment by apjanke** [comment]
Note that Apple's own `/etc/bashrc` implementation of this is subject to the same bug with special characters. I've filed a Radar bug on it with them, bug ID 19839079.

**Comment by mcornella** [comment]
Ok, so this one can be closed because it's been implemented in #3582. Please close to keep it tidy :wink:

**Comment by apjanke** [comment]
Do we actually want to close it before the pull request gets merged in? #3582 has a "fixes" reference to this, so it should auto-close upon merge.

**Comment by mcornella** [comment]
Just to tidy up, and make sure Robby doesn't merge the wrong one (it has happened) :wink:

**Comment by apjanke** [comment]
Okay, closed.
