### ISSUE TITLE
theme plugin side effects (cwd & variables) and inconsistency

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#3585]
There are a few related issues in the `themes` plugin. I'm listing them all in one Issue because they're interrelated and I plan on fixing them all in one PR.

* lstheme() changes the pwd as a side effect
* lstheme() does not include custom themes
* theme() leaks variables `$N`, `$themes`, and `$RANDOM_THEME` when setting random theme
* mixed tabs and spaces for indentation
* theme() reads custom themes from `$ZSH_CUSTOM` but not `$ZSH_CUSTOM/themes`.

### lstheme pwd side effect

If you call lstheme, it dumps you in to the themes dir. It shouldn't change the directory.

```
[@ in ~]
~ » pwd
/Users/janke
~ » lstheme > /dev/null
.oh-my-zsh/themes [master] » pwd
/Users/janke/.oh-my-zsh/themes
.oh-my-zsh/themes [master] »
```

### Custom theme locations

It seems like the dir structure of $ZSH_CUSTOM should mirror the directory structure of the main oh-my-zsh directory. Theme() looks under the themes/ subdir of the main dir, but the root dir under $ZSH_CUSTOM. This is also inconsistent with `oh-my-zsh.sh`, which looks in both `/` and `themes/` under $ZSH_CUSTOM.

Really, most of the theme plugin implementation is duplicated by the theme loading section in the `oh-my-zsh.zsh` script. The theme plugin should probably be moved in to `lib/theme-and-appearance.zsh` and `oh-my-zsh.zsh` should call it.

**Comment by apjanke** [comment]
Did a rewrite to fix all these.

Now that lstheme() is stably-ordered and includes custom themes, you can have a function that selects themes by index. This is to make it easy to cycle through all the themes for debugging purposes. Could be added to theme() as an alternate argument form (e.g. `theme #<N>`) but for now I'm just using a separate function. Here's an example in case other people want to use it.

```zsh
# Load theme by index
#
# Load a theme selected by index into list of defined themes, instead of by
# name. 
function themen() {
    # Numeric index argument: select theme by index 
    local themes n name
    n=$1
    themes=($(lstheme))
    name=${themes[$n]}
    echo "Loading theme: $name"
    theme $name
}
```

**Comment by mcornella** [comment]
@apjanke it's bad practice having both an issue and PR open in a short period of time. If you have working code, normally you would put the things it solves in the PR description. I realize you first created this issue, then worked on the code, but both are just 1.5 hours apart. 

I'd copy-paste this issue's description into your PR and close this one. BTW, if #3587 is more advanced than #3337, you can auto-close that too by adding `Close #3337` in the PR description.

**Comment by apjanke** [comment]
Noted. I'll stick to just a PR when I'm going to have code for something.

Closing in favor of #3585.
