### ISSUE TITLE
Everything broken after auto-update

### ISSUE THREAD

**Issue by kevinansfield** [robbyrussell/oh-my-zsh#3595]
Each time I open a new tab I see the following:

```
Last login: Mon Feb 16 10:36:55 on ttys014
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:setopt:2: no such option: auto_pushd^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:setopt:3: no such option: pushd_ignore_dups^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:setopt:4: no such option: pushdminus^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:5: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:10: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:20: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:24: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/directories.zsh:30: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/history.zsh:10: parse error near `in^M'
/Users/kevinansfield/.oh-my-zsh/lib/key-bindings.zsh:4: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/key-bindings.zsh:88: parse error near `\n'
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:4: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:setopt:6: no such option: long_list_jobs^M
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:7: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:11: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:15: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:18: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/misc.zsh:23: parse error near `\n'
/Users/kevinansfield/.oh-my-zsh/lib/termsupport.zsh:18: parse error near `elif'
/Users/kevinansfield/.oh-my-zsh/lib/theme-and-appearance.zsh:2: command not found: colors^M
/Users/kevinansfield/.oh-my-zsh/lib/theme-and-appearance.zsh:4: command not found: ^M
/Users/kevinansfield/.oh-my-zsh/lib/theme-and-appearance.zsh:13: parse error near `elif'
${ret_status}$fg_bold[green] $fg[cyan]~ $fg_bold[blue]$(git_prompt_info)$fg_bold[blue] $reset_color
```

Every time I type a character I get this:

```
-zsh:1: url-quote-magic^M: function definition file not found
${ret_status}$fg_bold[green] $fg[cyan]~ $fg_bold[blue]$(git_prompt_info)$fg_bold[blue] $reset_color
```

With a fresh install of .oh-my-zsh I see the following:

```
/Users/kevinansfield/.oh-my-zsh/oh-my-zsh.sh:37: parse error near `||'
```

This shows the same error as https://github.com/robbyrussell/oh-my-zsh/issues/3552 but a re-install of zsh through homebrew had no effect.

If I remove the `\` on line 37 of oh-my-zsh.sh so that the command is all on one line, I then get the following error:

```
/Users/kevinansfield/.oh-my-zsh/oh-my-zsh.sh:43: parse error near `elif'
```

Is there anything else I can try to get back to a working state?

---

OS X Yosemite 10.10.2
zsh 5.0.7 (installed through homebrew)
oh-my-zsh 5ee5403 (old version and fresh install, no known custom changes on the old version)

**Comment by mcornella** [comment]
There's a conflict with your git `core.autocrlf` value. Delete it with `git config --delete core.autocrlf` and re-clone the repository (delete the .oh-my-zsh folder first).

I'm working on a PR to force line endings, this is not the first time this happens. Let me know if you have any doubts.

**Comment by kevinansfield** [comment]
Thanks, that has fixed it.

FYI, `git config --delete core.autocrlf` didn't work, it gave me an `unknown option 'delete'` message so I removed the relevant line manually from ~/.gitconfig

**Comment by mcornella** [comment]
Right, the correct argument is `--unset`. Cheers!

**Comment by doomsbuster** [comment]
I got the issue `/home/ironman/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'`. I followed this post and just did a `git pull origin master` in the .oh-my-zsh directory and it worked. The error is gone.

**Comment by JeremyDwayne** [comment]
Thanks @doomsbuster, your timing is impeccable! I was having the same error as you, and doing the `git pull origin master` cleared out the errors in my misc.zsh file. For reference, I did not have the autocrlf line in my gitconfig and was still receiving this error.
