### ISSUE TITLE
The install needs to be as secure as possible!

### ISSUE THREAD

**Issue by nextgenthemes** [robbyrussell/oh-my-zsh#3600]
Someone criticized bootstrap about 2 years ago for having only two guys managing the repo. They hesitated and kept it that way for some time, now 2 years later bootstrap has a core team of awesome guys http://getbootstrap.com/about/#team pushing things forward closing and merging tons of pull requests every day.

Holy s this repo has almost 400 pull requests and seem to have only one guy handling this. Don't get me wrong, I do not want to handle this but I am sure they are tons of people out there who would happily help out. It just pains me to see something like this. I am also not saying @robbyrussell should do more but just let others do something!

Or maybe this repo should be forked or split up into a core repo and a community addon repo with most of the plugins.

While I am at it, I am by far not a security expert but I find it insulting how @robbyrussell seems to not care about risking everyones security.
https://github.com/robbyrussell/oh-my-zsh/issues/3459
https://github.com/robbyrussell/oh-my-zsh/pull/3461
there was another issue I cant find anymore where I first commented on this months ago.

And to the guys saying its just the script and the downloads are from Github so its no problem: You obviously have no clue. Its not that hard to do a men in the middle attack when someone requests something over HTTP, so it does not matter at all since that very small script can then be modified do some malicious stuff on the users machine silently and then go ahead and install oh-my-zsh from github via https and nobody would notice.

I think not even SSL is really secure, you should watch this https://www.youtube.com/watch?v=Z7Wl2FW2TcA and get your mind blown, its not even designed to do the stuff we do with it today. But not using it at all is like inviting hackers and screaming "hack me hack me now!"

The text says "Do you trust me?" Well yeah I trust you @robbyrussell but I do not trust this stupid HTTP connection that directly runs commands on my system without me even seeing them, not using any basic security whatsoever. And we all know most people are lazy and just copy paste this **totally insecure** commands into their command-line, not checking checksums or something, this needs to stop! For what for this "cool" .sh domain name you not willing to get handled by Github. This is possible or not? Or enabling a SSL Cert for it? Seriously? Actually the checking of checksum after download is more secure so you could leave the SSL be and just pull this: https://github.com/robbyrussell/oh-my-zsh/pull/3461 this is open since december last year!

Then on the other hand he seems to care about if a user may use sudo "by accident" by explicitly enabling a plugin called autosudo :smirk: ... https://github.com/robbyrussell/oh-my-zsh/pull/373#issuecomment-74612736. This two not fit together at all.

BTW, I myself not really miss anything here apart from security for others, i just use the debian and the autojump plugin thats it. Its just that I see all this people waiting to get pulled and nothing happens.

I hope it will not take 2 years until this gets a little more speed. I also hope I am not making to many enemies by speaking my mind in this. Thanks for reading. </rant>

// just saw this from a day ago lol https://github.com/robbyrussell/oh-my-zsh/wiki/Volunteers sorry. Looks like this one is on the way.

**Comment by mcornella** [comment]
Dude.

**Comment by robbyrussell** [comment]
The core team part is under consideration.
