### ISSUE TITLE
compinit:473: bad output format specification

### ISSUE THREAD

**Issue by vajapravin** [robbyrussell/oh-my-zsh#3602]
I am getting following error which comes before 3-4 days.. any guess??

compinit:473: bad output format specification

**Comment by apjanke** [comment]
Can you give us more information on this?

* When does it happen? Does it happen during `zsh` startup?
* What operating system are you running?
* Is anything else breaking?

**Comment by vajapravin** [comment]
Yes, it happens when zsh starts
OS: Linux Mint 14
oh-my-zsh not working properly. if i remove oh-my-zsh, zsh works well without error(compinit:473: bad output format specification).

**Comment by mcornella** [comment]
Try deleting `~/.zcompdump*` files and restarting the terminal.

**Comment by vajapravin** [comment]
mcornella, it's working.. Thank you.

**Comment by mcornella** [comment]
Great! Remember to close this issue.
