### ISSUE TITLE
Chuck norris plugin not working on os x

### ISSUE THREAD

**Issue by marcodejongh** [robbyrussell/oh-my-zsh#3604]
I used the brew version of fortune. For some reason it doesn't recognise the fortunes file.

Console output:

```
fortune: /Users/pablo/.oh-my-zsh/plugins/chucknorris/fortunes: No fortune files in directory.
fortune:/Users/pablo/.oh-my-zsh/plugins/chucknorris/fortunes not a fortune file or directory
```

**Comment by wachunei** [comment]
Having the same issue. 

The script is not generating the `.dat` file.

If you need a quickfix, run:
```
strfile $ZSH/plugins/chucknorris/fortunes/chucknorris
```

**Comment by apjanke** [comment]
Hmm. I'm on OS X 10.9, also using brew fortune, and it's working for me. I updated oh-my-zsh and enabled the chucknorris plugin. The next time I opened a terminal window, it automatically ran that strfile command to build the `.dat` file.

```
Last login: Thu Feb 19 11:37:37 on ttys000
"/Users/janke/.oh-my-zsh/plugins/chucknorris/fortunes/chucknorris.dat" created
There were 447 strings
Longest string: 374 bytes
Shortest string: 1 byte
➜  ~
```

Are you seeing any output - status or error - when you start a new zsh login shell?

**Comment by wachunei** [comment]
There isn't any output.

**Comment by apjanke** [comment]
Sounds like now that the file is built, it's bypassing that initialization code.

Want to help me reproduce it? Try this.

    rm $ZSH/plugins/chucknorris/fortunes/chucknorris.dat
    zsh -l

That will delete the fortune dat file, forcing it to rebuild it as if it was new. You should see an explicit confirmation of its creation.

```
➜  ~  rm $ZSH/plugins/chucknorris/fortunes/chucknorris.dat
➜  ~  zsh -l
"/Users/janke/.oh-my-zsh/plugins/chucknorris/fortunes/chucknorris.dat" created
There were 447 strings
Longest string: 374 bytes
Shortest string: 1 byte
➜  ~
```
