### ISSUE TITLE
vi-mode broken since last auto-update?

### ISSUE THREAD

**Issue by Cutuchiqueno** [robbyrussell/oh-my-zsh#3605]
Since last autoupdate I get the following message when I open a terminal: `TRAPWINCH:zle:2: widgets can only be called when ZLE is active`. I figured out that the TRAPWINCH function comes from the vi-mode plugin. To test I deactivated this plugin and the messages disappeared.

I haven't changed anything manually in in my .zshrc after the autoupdate. Before this update there was no error message.

**Comment by apjanke** [comment]
I'm not getting that error when I run `vi-mode`. (OS X 10.9, Terminal or iTerm, robbyrussell or custom theme.) But that TRAPWINCH was indeed added recently to vi-mode (Feb 4). Let's track this down. What OS, terminal program, oh-my-zsh theme, and plugins are you running? Mind posting your .zshrc as a gist?

**Comment by mcornella** [comment]
We're looking at this in https://github.com/robbyrussell/oh-my-zsh/issues/3537#issuecomment-75052757.

**Comment by scottkidder** [comment]
Same issue since upgrade. mcornella's fix in #3537 works for me.
```
TRAPWINCH() {
  [[ -o zle ]] && zle && zle reset-prompt && zle -R
}
```

**Comment by mcornella** [comment]
Can you try the same without the `[[ -o zle]]` part? (line should start
with `zle &&`)

**Comment by mcornella** [comment]
Everybody, please try PR #3610 so we can get it merged.
