### ISSUE TITLE
[TEST] placeholder for screenshot images

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#3619]
This issue is just a scratchpad for uploading screenshot images for use in the Themes section of the wiki. This is not an actual bug report.

![alanpeabody](https://cloud.githubusercontent.com/assets/2618447/6316714/5190b8ba-ba00-11e4-8fa9-9f22160be9e4.png)
![arrow](https://cloud.githubusercontent.com/assets/2618447/6316717/51a09e7e-ba00-11e4-8120-45ca128b9bf6.png)
![aussiegeek](https://cloud.githubusercontent.com/assets/2618447/6316719/51a34962-ba00-11e4-9577-882124c30b4e.png)
![avit](https://cloud.githubusercontent.com/assets/2618447/6316718/51a2fd9a-ba00-11e4-845a-24bed6ae9210.png)
![bira](https://cloud.githubusercontent.com/assets/2618447/6316716/51a0708e-ba00-11e4-8664-11a804f2fe3f.png)
![blinks](https://cloud.githubusercontent.com/assets/2618447/6316715/519c8e56-ba00-11e4-9792-a4b3d1d3775a.png)
![bureau](https://cloud.githubusercontent.com/assets/2618447/6316720/51a54ba4-ba00-11e4-82d2-f2af8cc18869.png)
![clean](https://cloud.githubusercontent.com/assets/2618447/6316721/51af13a0-ba00-11e4-87ea-cf83f32010f0.png)
![cloud](https://cloud.githubusercontent.com/assets/2618447/6316723/51b24944-ba00-11e4-8dcb-cb09a198523e.png)
![crunch](https://cloud.githubusercontent.com/assets/2618447/6316722/51b1f4b2-ba00-11e4-9ebf-1359aa272fbd.png)
![dallas](https://cloud.githubusercontent.com/assets/2618447/6316725/51b39b28-ba00-11e4-942e-600c704a8180.png)
![daveverwer](https://cloud.githubusercontent.com/assets/2618447/6316726/51b3fc8a-ba00-11e4-8378-a18d1be9cee3.png)
![dieter](https://cloud.githubusercontent.com/assets/2618447/6316724/51b2886e-ba00-11e4-805f-c622567608e3.png)
![dogenpunk](https://cloud.githubusercontent.com/assets/2618447/6316727/51b8067c-ba00-11e4-8e59-722a79ec60c2.png)
![dpoggi](https://cloud.githubusercontent.com/assets/2618447/6316730/51bca236-ba00-11e4-810d-ab3e9365c56b.png)
![eastwood](https://cloud.githubusercontent.com/assets/2618447/6316728/51ba0026-ba00-11e4-9d83-435c3c4513cf.png)
![flazz](https://cloud.githubusercontent.com/assets/2618447/6316729/51bc9fac-ba00-11e4-9e4b-cb0612d5f440.png)
![frisk](https://cloud.githubusercontent.com/assets/2618447/6316732/51bdd21e-ba00-11e4-97ac-0fdda49fe3c2.png)
![gallois](https://cloud.githubusercontent.com/assets/2618447/6316731/51bd3b88-ba00-11e4-9c58-e09a3965e0f0.png)
![gentoo](https://cloud.githubusercontent.com/assets/2618447/6316733/51c0f390-ba00-11e4-876d-70a95b5d629b.png)
![gianu](https://cloud.githubusercontent.com/assets/2618447/6316736/51c6a6c8-ba00-11e4-8b5f-b45795d98907.png)
![gnzh](https://cloud.githubusercontent.com/assets/2618447/6316735/51c62b1c-ba00-11e4-8107-fb532db89c7d.png)
![jnrowe](https://cloud.githubusercontent.com/assets/2618447/6316737/51c7104a-ba00-11e4-9875-ca6652e45fb5.png)
![jreese](https://cloud.githubusercontent.com/assets/2618447/6316734/51c54d82-ba00-11e4-882e-695dd5570528.png)
![jtriley](https://cloud.githubusercontent.com/assets/2618447/6316738/51c836c8-ba00-11e4-87a9-667ccbcbbd30.png)
![juanghurtado](https://cloud.githubusercontent.com/assets/2618447/6316739/51cc2814-ba00-11e4-9d4a-1dca9961d906.png)
![kafeitu](https://cloud.githubusercontent.com/assets/2618447/6316741/51cec254-ba00-11e4-8433-a3c2524086c1.png)
![kardan](https://cloud.githubusercontent.com/assets/2618447/6316740/51ce9356-ba00-11e4-80c1-79e0b489cd32.png)
![kennethreitz](https://cloud.githubusercontent.com/assets/2618447/6316742/51cfb3e4-ba00-11e4-8e8e-720bab641edd.png)
![kolo](https://cloud.githubusercontent.com/assets/2618447/6316743/51d066ea-ba00-11e4-850c-6527b01d8ef5.png)
![lambda](https://cloud.githubusercontent.com/assets/2618447/6316744/51d09ba6-ba00-11e4-9e41-e942ee626bae.png)
![linuxonly](https://cloud.githubusercontent.com/assets/2618447/6316745/51dab9ba-ba00-11e4-853b-7ea8ab5ced35.png)
![lukerandall](https://cloud.githubusercontent.com/assets/2618447/6316747/51db7bca-ba00-11e4-8018-6838f2bec7da.png)
![mh](https://cloud.githubusercontent.com/assets/2618447/6316746/51db6d92-ba00-11e4-988c-6c89eb581c8c.png)
![miloshadzic](https://cloud.githubusercontent.com/assets/2618447/6316748/51dc1eae-ba00-11e4-843d-379183044762.png)
![minimal](https://cloud.githubusercontent.com/assets/2618447/6316749/51de4ad0-ba00-11e4-8b4e-42e7000bad53.png)
![mortalscumbag](https://cloud.githubusercontent.com/assets/2618447/6316750/51dee102-ba00-11e4-8ede-27627cd495f9.png)
![muse](https://cloud.githubusercontent.com/assets/2618447/6316752/51e211a6-ba00-11e4-8f57-e82fcc4a453f.png)
![nanotech](https://cloud.githubusercontent.com/assets/2618447/6316751/51e187c2-ba00-11e4-8a7e-1a45e4df00bf.png)
![nebirhos](https://cloud.githubusercontent.com/assets/2618447/6316754/51e4a182-ba00-11e4-8cf1-65ff1511da34.png)
![nicoulaj](https://cloud.githubusercontent.com/assets/2618447/6316755/51e4b0c8-ba00-11e4-85ef-3e7faeeb0e0b.png)
![norm](https://cloud.githubusercontent.com/assets/2618447/6316753/51e440c0-ba00-11e4-87ed-400fe2b0dd39.png)
![pygmalion](https://cloud.githubusercontent.com/assets/2618447/6316756/51e859ee-ba00-11e4-8b58-2f086c491926.png)
![rixius](https://cloud.githubusercontent.com/assets/2618447/6316760/51efdeb2-ba00-11e4-8da6-a839f192a207.png)
![rkj-repos](https://cloud.githubusercontent.com/assets/2618447/6316757/51ee9e12-ba00-11e4-86d4-1d59a182f688.png)
![sammy](https://cloud.githubusercontent.com/assets/2618447/6316759/51ef7a44-ba00-11e4-9c76-e9bb6e75f5ce.png)
![simple](https://cloud.githubusercontent.com/assets/2618447/6316758/51ef3480-ba00-11e4-840c-a9ebec42f4b6.png)
![smt](https://cloud.githubusercontent.com/assets/2618447/6316761/51f0052c-ba00-11e4-990f-cdf7fc5610e6.png)
![sorin](https://cloud.githubusercontent.com/assets/2618447/6316762/51f34624-ba00-11e4-948a-6ac65a49f8c5.png)
![sporty_256](https://cloud.githubusercontent.com/assets/2618447/6316763/51f8f2e0-ba00-11e4-82fe-40c9a5a81569.png)
![steeef](https://cloud.githubusercontent.com/assets/2618447/6316764/51f98994-ba00-11e4-9083-ecec290a8dcb.png)
![sunrise](https://cloud.githubusercontent.com/assets/2618447/6316766/51fbf062-ba00-11e4-9b66-2b0da5a0dbbc.png)
![superjarin](https://cloud.githubusercontent.com/assets/2618447/6316765/51fac93a-ba00-11e4-95bc-e2eea4e98c8b.png)
![terminalparty](https://cloud.githubusercontent.com/assets/2618447/6316767/51fc28fc-ba00-11e4-9129-953048acce0a.png)
![tjkirch](https://cloud.githubusercontent.com/assets/2618447/6316768/520565e8-ba00-11e4-98ad-4665f72882ac.png)
![wedisagree](https://cloud.githubusercontent.com/assets/2618447/6316769/5205cc54-ba00-11e4-9d2b-e7b632f74997.png)
![wuffers](https://cloud.githubusercontent.com/assets/2618447/6316770/52071794-ba00-11e4-9122-c7194f5188f4.png)
![zhann](https://cloud.githubusercontent.com/assets/2618447/6316771/520a5170-ba00-11e4-9561-78f0c76e996c.png)

**Comment by apjanke** [comment]
Closing because it's just a test issue.

**Comment by apjanke** [comment]
More screenshots, covering the ones that weren't in that first archive.  

![af-magic](https://cloud.githubusercontent.com/assets/2618447/6316860/70f310d8-ba03-11e4-973c-eb5eb6b5b289.png)
![afowler](https://cloud.githubusercontent.com/assets/2618447/6316859/70f1cb06-ba03-11e4-865f-209473ddd5c8.png)
![agnoster](https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png)
![amuse](https://cloud.githubusercontent.com/assets/2618447/6316861/70f3c4ce-ba03-11e4-88a5-0b423dd5a2ce.png)
![candy](https://cloud.githubusercontent.com/assets/2618447/6316863/70f5b87e-ba03-11e4-8ee5-65345537e0bf.png)
![cypher](https://cloud.githubusercontent.com/assets/2618447/6316864/70f5c09e-ba03-11e4-90c3-c539e09c6cc9.jpg)
![darkblood](https://cloud.githubusercontent.com/assets/2618447/6316865/70fa9006-ba03-11e4-81c4-593d9ae34a9c.jpg)
![evan](https://cloud.githubusercontent.com/assets/2618447/6316867/70fc6e44-ba03-11e4-8537-9a77378e6c48.jpg)
![gallifrey](https://cloud.githubusercontent.com/assets/2618447/6316866/70fc3f8c-ba03-11e4-888a-baef9f609c56.jpg)
![garyblessington](https://cloud.githubusercontent.com/assets/2618447/6316868/7100520c-ba03-11e4-9357-07472942ad5e.jpg)
![imajes](https://cloud.githubusercontent.com/assets/2618447/6316870/710289f0-ba03-11e4-9482-25742645379d.jpg)
![junkfood](https://cloud.githubusercontent.com/assets/2618447/6316869/710182e4-ba03-11e4-84ec-b0e05eec8e4c.png)
![kphoen](https://cloud.githubusercontent.com/assets/2618447/6316871/7103ea8e-ba03-11e4-977d-255b34aabe53.png)
![macovsky](https://cloud.githubusercontent.com/assets/2618447/6316872/71047346-ba03-11e4-8a49-2d83c4437b81.png)
![mrtazz](https://cloud.githubusercontent.com/assets/2618447/6316873/71057cc8-ba03-11e4-911a-53d085b1894e.jpg)
![philips](https://cloud.githubusercontent.com/assets/2618447/6316874/710a1e22-ba03-11e4-91c4-30f195e3fa2f.jpg)
![rkj-repos-2](https://cloud.githubusercontent.com/assets/2618447/6316875/710b063e-ba03-11e4-9e22-ecb86da25f46.png)
![robbyrussell](https://cloud.githubusercontent.com/assets/2618447/6316876/710cbb8c-ba03-11e4-90b3-0315d72f270c.jpg)
![suvash](https://cloud.githubusercontent.com/assets/2618447/6316877/710d06be-ba03-11e4-8942-d6d28c54ff74.png)
![tonotdo](https://cloud.githubusercontent.com/assets/2618447/6316878/710deab6-ba03-11e4-8897-52154d993ad8.jpg)
![trapd00r](https://cloud.githubusercontent.com/assets/2618447/6316879/710ec8dc-ba03-11e4-923a-580d6682a3bf.png)
![ys](https://cloud.githubusercontent.com/assets/2618447/6316880/71133e4e-ba03-11e4-8913-08451551ab98.jpg)

**Comment by apjanke** [comment]
![daveverwer](https://cloud.githubusercontent.com/assets/2618447/6317506/faa0ca2a-ba24-11e4-9c34-ffa83f0cca23.png)

New daveverwer screenshot since text in the old one was a bit unreadable. On Debian Linux gnome-terminal, default color scheme.

**Comment by jgrar** [comment]
![simple-example](https://cloud.githubusercontent.com/assets/466092/6865307/377144a4-d4b8-11e4-956b-1cdbf8481a2e.png)

**Comment by mbologna** [comment]
[!michelebologna(https://cloud.githubusercontent.com/assets/530992/7785021/34c45cea-017d-11e5-964f-10f99d4a5d37.png)][https://cloud.githubusercontent.com/assets/530992/7785021/34c45cea-017d-11e5-964f-10f99d4a5d37.png]

**Comment by notpeter** [comment]
![image](https://user-images.githubusercontent.com/145113/73003386-8f500000-3dd3-11ea-8710-657fac00d4ad.png)
