### ISSUE TITLE
Cloud symbol not showing properly

### ISSUE THREAD

**Issue by faruh-narzullaev** [robbyrussell/oh-my-zsh#3621]
I am using Ubuntu 14.04
I set up cloud theme and it does not show properly:
![klioxyn](https://cloud.githubusercontent.com/assets/6521962/6319708/e088d9da-baf0-11e4-8434-b067891f698a.jpg)

Please, help to fix that!

**Comment by apjanke** [comment]
Looks like the theme is working fine. That's just what the cloud character - [Unicode U+2601](http://www.fileformat.info/info/unicode/char/2601/index.htm) - looks like in the font your terminal is using. OS X's fixed-width fonts have clouds that look similar, with flat bottoms. You may get better results if you switch to a different font.
