### ISSUE TITLE
How to make the git branch completion work?

### ISSUE THREAD

**Issue by mkoxio** [robbyrussell/oh-my-zsh#3628]
I found **_git-branch** function in the **git** plugin, but I don't know how to make it work.

I tried to type following in the terminal:

`_git-branch`

and hit the tab button, but only the files and folders appear, not branches. any idea?

**Comment by apjanke** [comment]
That's not how it's used. The `_git_branch` function is itself just the completion definition. It defines completions for the `git branch` subcommand and is sourced automatically. To use those completions, type `git branch ` in your terminal (not `_git-branch`) and press tab.

**Comment by mkoxio** [comment]
I found where the problem that lies
in my *.zshrc*, the line:

`alias git=hub`

which [hub](http://hub.github.com) suggested 

it makes my terminal painfully slow both for `ls` and 'git status' in my mac(macbook air 2010), and tab completion for branch doesn't work.

delete this line on my .zshrc file make the tab completion for branch works
