### ISSUE TITLE
Messed up prompt after last update

### ISSUE THREAD

**Issue by pjar** [robbyrussell/oh-my-zsh#3631]
I've just updated oh-my-zsh and this is what my prompt looks like:

    ${ret_status}$fg_bold[green] $fg[cyan].oh-my-zsh $fg_bold[blue]$(git_prompt_info)$fg_bold[blue] $reset_color

How can I fix it?

**Comment by apjanke** [comment]
This looks like the `prompt_subst` shell option is getting turned off for you somehow. I can reproduce a similarly messed-up prompt by turning it off manually.

```
 .oh-my-zsh git:(master) pwd
/Users/janke/.oh-my-zsh
 .oh-my-zsh git:(master) setopt nopromptsubst
${ret_status}$fg_bold[green] $fg[cyan].oh-my-zsh $fg_bold[blue]$(git_prompt_info)$fg_bold[blue] $reset_colorpwd
/Users/janke/.oh-my-zsh
${ret_status}$fg_bold[green] $fg[cyan].oh-my-zsh $fg_bold[blue]$(git_prompt_info)$fg_bold[blue] ${ret_status}$fg_bold[green] $fg[cyan].oh-my-zsh $fg_bold[blue]$(git_prompt_info)$fg_bold[blue] $reset_colorsetopt promptsubst
 .oh-my-zsh git:(master)
```

But unless I tweak that, my prompt looks fine. I'm up to date with the latest oh-my-zsh, at commit 6ddd44a341c77910ac64ec2f67ee762ecebcc82d. Maybe it's something specific to your setup.

Do you have any custom files in $ZSH_CUSTOM, particularly `lib/theme-and-appearance.zsh`? That's where `setopt prompt_subst` gets enabled for most themes. 
What theme are you running? Looks like `robbyrussell`, the default.
What do you get for the output of `echo $(setopt)`?

**Comment by pjar** [comment]
@apjanke thanks for quick reaction. It turned out I had some uncommited changes in .oh-my-zsh directory, but don't know why - there were lots of them. After stashing all and pulling fresh commits it came back to normal.
