### ISSUE TITLE
npmd alias is messing with the fantastic npmd module

### ISSUE THREAD

**Issue by binarykitchen** [robbyrussell/oh-my-zsh#3640]
Alias at https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/npm/npm.plugin.zsh#L7 should be removed or changed.

This in favor of this cool module https://github.com/dominictarr/npmd ...

**Comment by apjanke** [comment]
Hi @jameswomack, you added the npm aliases. What do you think of the conflict with `npmd`?

**Comment by jameswomack** [comment]
Hey folks. I'll look into it addressing it, possibly by checking for the existence of npmd on the user's system.

**Comment by jameswomack** [comment]
The following would work:
https://github.com/jameswomack/oh-my-zsh/commit/64d6597de033becac1676b0f3fabbf3ae02b8603

Thoughts?

**Comment by apjanke** [comment]
What do you think about using the alias `npmD` instead? That way it could still be used by users with `npmd` installed. And when reading people's scripts or shell sessions, there wouldn't be confusion between the two.

**Comment by jameswomack** [comment]
https://github.com/jameswomack/oh-my-zsh/commit/608d5f42e3a393e263da0bf5a8b1de4e78b0b406

**Comment by apjanke** [comment]
I like it!
