### ISSUE TITLE
Emacs Terminal Emulator completion / menu issues

### ISSUE THREAD

**Issue by peterhadlaw** [robbyrussell/oh-my-zsh#3645]
Attached is a screencast of the issues I'm experiencing with the GUI version of emacs terminal emulator. Basically when I hit tab to autocomplete some choices such as what directory to 'cd' into, some residue is left over. Also, I heard that this might be an incompatibility of Oh My ZSH with ansi terminals. https://www.dropbox.com/s/oo4tjagx8fnae1h/emacs_zsh.mov?dl=0

**Comment by apjanke** [comment]
Your screencast link is 404. Could you repost? If you could format it as an animated gif, or provide a few separate screenshots, you could post those directly in the bug report, so it's not dependent on an external Dropbox link.

**Comment by mcornella** [comment]
I think this could be closed because of lack of response. Perhaps it's not relevant anymore...
