### ISSUE TITLE
docker completion plugin error: permission denied

### ISSUE THREAD

**Issue by kxxoling** [robbyrussell/oh-my-zsh#3649]
Got this error while click tag to complete  command `sudo docker history`:

![docker zsh](https://cloud.githubusercontent.com/assets/1227139/6425593/563098ac-bf6b-11e4-825e-e050da03d4c3.png)

I just installed docker and oh-my-zsh as the tutorial says on a Xubuntu 14.04 in VirtualBox, have no idea why.

**Comment by chrw** [comment]
Maybe you don't have permissions to read `/var/run/docker.sock` with your current user.
```srw-rw---- 1 root docker 0 Mar 13 12:07 /var/run/docker.sock```

The completion does not use sudo to make the query for the history. Just add your user to the docker group and you're fine. It worked for me!

**Comment by kxxoling** [comment]
@chrw Yes, it works! But logout is usually needed. Thank you very much!

**Comment by chrw** [comment]
Nice! No problem!
Yes. You need to logout and login again. :-)
