### ISSUE TITLE
Add zsh-autosuggestions to available plugins

### ISSUE THREAD

**Issue by calebmeyer** [robbyrussell/oh-my-zsh#3662]
I love zsh. Everything is fast, and 90% of the scripts online work with it.

I then discovered fish. The completions are so good that I switched, even though it has been a real pain to get some things working (rvm, for example).

Today I discovered https://github.com/tarruda/zsh-autosuggestions . Is there any way we could get it included as part of oh-my-zsh, so that more people can enjoy the awesomeness that is commands completing as you type them?

![screen shot 2015-03-03 at 12 03 11 pm](https://cloud.githubusercontent.com/assets/3342777/6468802/4e1a49ea-c19d-11e4-8e0b-b13993873695.png)

**Comment by apjanke** [comment]
There's an open PR on zsh-autosuggestion's side to make this function as an oh-my-zsh plugin: tarruda/zsh-autosuggestions#32. I think with that merged, you'd just need to clone their repo in to a `zsh-autosuggestions` dir under your `$ZSH_CUSTOM/plugins`.

**Comment by ncanceill** [comment]
Can we close this until tarruda/zsh-autosuggestions#32 is merged then?

**Comment by calebmeyer** [comment]
That's fine by me

**Comment by ncanceill** [comment]
Well, you are the one to do that, I think.
