### ISSUE TITLE
Commit ce607d3fcb4c730c991563b4c62725cd89ce0ced breaks "tab" functionality

### ISSUE THREAD

**Issue by Marco-Lindsay** [robbyrussell/oh-my-zsh#3670]

**Comment by apjanke** [comment]
Can you be more specific? What tab functionality – autocompletion? What's broken about it?

What operating system are you on, and what oh-my-zsh plugins do you have enabled?

**Comment by apjanke** [comment]
Here's the commit: ce607d3fcb4c730c991563b4c62725cd89ce0ced
Doesn't look like it's part of a PR.

Sounds like you're talking about the `tab()` function inside the `osx` plugin. I don't know that this commit itself broke it. I undid the commit locally, and it still didn't work. New tabs opened with `tab` would have the `cd ...` command sitting there on the command line, but not executed. Is that what you're seeing?

![screen shot 2015-06-26 at 1 06 20 am](https://cloud.githubusercontent.com/assets/2618447/8371061/acf7102c-1b9f-11e5-8b27-90afe306ac0a.png)

When was the last time this actually worked for you?

I think the issue might be that the trailing semicolon in the `$command` string; it seems to cause iTerm to not execute it.

**Comment by apjanke** [comment]
I put in a fix for this, #4093. Could you give it a try?

**Comment by Marco-Lindsay** [comment]
That fixes the issue that I was referencing which was the "tab" functionality that is part of the OSX plugin stopped working on my system after the referenced commit.

**Comment by apjanke** [comment]
Cool. Do you mind giving a "+1" comment on the PR itself? That will help it get merged sooner.
