### ISSUE TITLE
[nvm] Add npm global binaries to PATH

### ISSUE THREAD

**Issue by RobLoach** [robbyrussell/oh-my-zsh#3674]
`npm` has the ability to install global binaries. For example, to install Grunt, you would use `npm install -g grunt-cli`.

This issue is to add `npm`'s globally installed binaries to `$PATH`, so that once they're installed globally, you can run them seamlessly.

You can retrieve the current node path by using:
```
npm config --global get prefix
```

So, the binaries would be available at:
```
$(npm config --global get prefix)/bin
```

Appending the following to the nvm plugin would allow such binaries to be run:
```
export PATH=$PATH:$(npm config --global get prefix)/bin
```

A requirement of this is to have a version of node installed, and set as the default, however:
```
nvm install stable
nvm alias default stable
```

PR to come. cc @paulmelnikow

**Comment by urosjarc** [comment]
I have this in my .zshrc .... and it works

        export NVM_DIR="/home/$USER/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
	nvm use 0.

**Comment by mcornella** [comment]
I'm not comfortable messing with people's PATH, let's not do this for now.
