### ISSUE TITLE
ZSH_TMUX_AUTOSTART in tmux plugin does not work

### ISSUE THREAD

**Issue by fsqcds** [robbyrussell/oh-my-zsh#3676]
I set ZSH_TMUX_AUTOSTART=true in my .zshrc on server but tmux is not starting when I ssh to server. ZSH_TMUX_AUTOSTARTED doesn't become true also.

**Comment by bwithem** [comment]
Hey @fsqcds I am unable to repro this issue. Can you verify you are running zsh at login?

**Comment by fsqcds** [comment]
Yes, zsh is my login shell and all other functionality is working.
```
 ~  finger ft3354
Login: ft3354         			Name: Fedor Nikolaev
Directory: /home/ft3354             	Shell: /usr/bin/zsh
On since Sat Mar  7 23:22 (EST) on pts/0 from 35.16.42.6
   4 seconds idle
No mail.
No Plan.
'''

**Comment by bwithem** [comment]
@fsqcds assuming you have the tmux plugin enabled in .zshrc? Are the tmux aliases working `ts test`?

**Comment by fsqcds** [comment]
Yes, plugin is enabled and aliases are working. Here is my .zshrc without commented out and empty lines.
```zsh
~  grep -v '^#' .zshrc | grep -v '^$'
export ZSH=/home/ft3354/.oh-my-zsh
ZSH_THEME="agnoster"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="mm/dd/yyyy"
plugins=(dircycle git gitignore python rsync tmux wd zsh_reload)
export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin"
source $ZSH/oh-my-zsh.sh
export EDITOR='emacs'
alias e=$EDITOR
REPORTTIME=10
DEFAULT_USER=fsqcds
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_ITERM2=true
'''

**Comment by bwithem** [comment]
Does a `echo $TMUX` after a fresh login return anything?

**Comment by fsqcds** [comment]
No, it is empty.

**Comment by bwithem** [comment]
Thanks for satisfying my curiosity!

**Comment by apjanke** [comment]
You need to put the `ZSH_TMUX_...=...` assignments before the `source $ZSH/oh-my-zsh.sh` line that fires up oh-my-zsh. In general, all the `ZSH_*` variables for controlling oh-my-zsh behavior need to be set before initializing oh-my-zsh.

**Comment by fsqcds** [comment]
Thank you, that helped.

**Comment by Ulysses-Odysseus** [comment]
The above solution was not working for me, It was giving me the following error: *Reason: %begin with empty command queue*

* ZSH_TMUX_AUTOSTART=true
* ZSH_TMUX_ITERM2=true

I had to remove **ZSH_TMUX_ITERM2=true** to make it work, just remember to close and open your terminal.

**Comment by Ulysses-Odysseus** [comment]
**Updated**

The last run tmux automatically but it did crash every time I typed any tmux command. I was able to execute tmux as follow:

if [ "$TMUX" = "" ]; then exec tmux; fi

**Comment by shaxbee** [comment]
Same here, setting **ZSH_TMUX_ITERM2=true** causes *Reason: %begin with empty command queue* error.

Running **tmux -CC** manually works fine.
