### ISSUE TITLE
Plugins wiki page is gone

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#3696]
The [Plugins wiki page](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins) is gone, and the reference to it from the [main wiki page](https://github.com/robbyrussell/oh-my-zsh/wiki) is broken.

Is this intentional? @jesshong, looks like you made the edit that removed it; can you comment?

**Comment by mcornella** [comment]
Yeah, and it looks like [there's no easy way to revert that without doing git stuff](http://stackoverflow.com/a/24797660). The [revisions page](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins/_history) doesn't show up for deleted pages.

I've just cloned

**Comment by apjanke** [comment]
Looks good. Thanks; closing.

For future reference:

I think the wiki revisions page is just the `git log <file>` history for the file(s) backing that page, but the wiki presentation layer only looks at the current set of files to determine whether to present it for a named node vs 404 it, and to choose which of the candidate files backing a given page to do the log for. E.g. depending on how you set the "editing mode" it might be backed by `Plugins.md`, `Plugins.mw`, `Plugins.rst`, etc.

You can also get at the revisions page for the overall wiki with a URL like https://github.com/robbyrussell/oh-my-zsh/wiki/_history  (with no page name in it). Commits that affected deleted pages still show up here. So if you can find the commit that removed a page, you can check it and the previous commit and do a "Compare Revisions" with the button on the upper right. Inside the comparison tool, you can either click "View" on the deleted file to get its contents for copy and pasting. There's also a "Revert Changes" button at the bottom of the Compare Revisions page, but it doesn't work for me; I get a `500 oops` page when I try to use it. (You can see the state for a wiki with a deleted page over at https://github.com/apjanke/omz-scratch/wiki/_history – there's a currently-deleted "Victim page" there.)

I'm not entirely sure this is a supported feature – I don't remember seeing it documented anywhere – but it does seem to work, for people who want to admin a wiki without dropping down to using `git` on it.

**Comment by mcornella** [comment]
Nice investigation! Thanks for the tip about the `wiki/_history` stuff, very useful.

Cheers!

**Comment by jesshong** [comment]
How
