### ISSUE TITLE
Improve plugins wiki

### ISSUE THREAD

**Issue by wernight** [robbyrussell/oh-my-zsh#3698]
The https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins-Overview page is a long listing with sometimes a description of the required package it may enhance, sometimes a description of enhancements.

Suggested format: Keep the grouping, but make a [table](https://help.github.com/articles/github-flavored-markdown/#tables) for each with columns:
- For (dependent package/name or the program is enhanced, for example mvn plugin enhances Maven)
- _Auto-complete_ (yes if it has adds auto-completion for that package)
- _Aliases_ (at least a check if it adds aliases, preferable a list of some aliases it adds
- _Functions_ (list of other functions that it adds to ZSH, like node plugin adds node-docs; for git plugin it also shows current branch name...)

**Comment by wernight** [comment]
Would be also very useful if people could favorite plugins, or the system automatically finds which plugins are mostly used by people.

**Comment by apjanke** [comment]
I like the idea of a extended summary table like this, though it might be hard to get all the plugin maintainers to fill it in. (IMHO it would be cool if the plugin code itself declared these things in the plugin code itself, like in formatted comments, and then you could programmatically generate the table from them, like generating Javadoc.) But I think one could fill in a lot of it with just clerical work summarizing the existing Plugins wiki sections or doco in the plugin files.

In particular, it would be nice (for me, anyway) to know which of the functions a plugin defines as part of its public API, and which are just internal-use helper functions. But this is starting to sound kind of bureaucracy-heavy; I don't know if that's in the oh-my-zsh spirit.

**Comment by wernight** [comment]
I like the README per plugin for details especially for complex plugins. Having a formatted manner to declare that overview and parsing it sounds overkill.

As you said it's hard to get it for all. First step could be to setup the presentation and leave `?` or `N/A` when the information hasn't been filled in. I prepared those info for some of my favorite plugins so I could edit the wiki and add the info. It's also by no mean supposed to be complete, but give an idea of why for example a user using Python `virtualenv` would like or even gain by enabling the plugin of same name. So it should remain very short.

**Comment by mcornella** [comment]
It looks good right now.
