### ISSUE TITLE
Installation on Lubuntu 14.10 failed

### ISSUE THREAD

**Issue by alex93ushakov** [robbyrussell/oh-my-zsh#3709]
After running default installation command
```
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
```
and rebooting - nothing changes.

```
chsh -s /bin/zsh
```
command cause error:
```
chsh: Warning: /bin/zsh does not exist
```

As I understand, oh-my-zsh installed by default in home directory - how to move it to /bin/zsh or by other way fix the problem?

**Comment by mcornella** [comment]
You need to install zsh before installing oh-my-zsh

**Comment by alex93ushakov** [comment]
You are right. After installing zsh by ```apt``` all is ok.
