### ISSUE TITLE
Linux Mint 17.1 64 bit auto installer failure

### ISSUE THREAD

**Issue by alex93ushakov** [robbyrussell/oh-my-zsh#3714]
For ending installation, ```chsh -s /bin/zsh``` command without admiin rights (it is not noted in manual) must be executed.

And, how to install correctly **omz** for all users, including admin? How to change color of default theme, when current user is root?

**Comment by apjanke** [comment]
I would recommend not installing OMZ for root, period. Root should have a minimal, security-conscious configuration. OMZ is both featureful and fast-and-loose, and probably not appropriate for use as root.

That said, can you tell us what behavior you're seeing during the installation? Are you getting error messages or other unexpected output? What is going wrong that makes you think `chsh` without admin rights is necessary?

In OMZ, generally, you don't change the color of a theme. If you want different colors, you either switch themes (which will use different colors) or change the color configuration of your terminal emulator, which will change the actual colors that your nominal terminal color palette will display as.

**Comment by alex93ushakov** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/9713207/6826249/1b1bb4d6-d311-11e4-8cba-6f0c75358905.png)

**Comment by apjanke** [comment]
That looks like #3516. Have a look at that bug. As a workaround, use this variant command to install oh-my-zsh, instead of the `curl ... | sh` command.

```
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```
