### ISSUE TITLE
add help to install zsh

### ISSUE THREAD

**Issue by MartinDelille** [robbyrussell/oh-my-zsh#3715]
I want to install ohmyzsh but I need to install zsh first. A brief paragraph to install zsh would be welcome. I'll be happy to add it but any help would be appreciated. Shall I do it in the README or the wiki?

**Comment by MartinDelille** [comment]
Here is the first command
## Install zsh

### Linux ###

    sudo apt-get install zsh

### OSX ###

    brew install zsh

Now I need to find the simplest way to make the terminal use zsh by default.

**Comment by MartinDelille** [comment]
Maybe this shall be part of the installation script? Checking zsh presence, install it if needed? and asking the user if he wants to make it the default shell in the terminal?

**Comment by tomauty** [comment]
`apt` is Debian/Ubuntu specific, so while this script is distribution agnostic, adding in a `zsh` installer would require maintaining support for most/all major package managers across distributions. 

I'm all for providing help with setting up zsh though. The most distribution-agnostic way to do it would be something like:

1. Install with your package manager of choice
2. Make sure it installed by running `zsh`
3. `chsh -s $(which zsh)`
4. Log out and back in.

**Comment by apjanke** [comment]
Note that the oh-my-zsh installer itself will call `chsh -s $(which zsh)` itself if you're not already running `zsh`.

**Comment by tomauty** [comment]
Ah okay, cool. Can't hurt to be thorough :smile:

**Comment by apjanke** [comment]
True enough. In fact, there's a couple open bugs related to the installer's use of `chsh` (#3588, #3516). And `chsh` doesn't exist on all systems. So it would make sense to have a "making `zsh` your default shell" section.

**Comment by tomauty** [comment]
Yeah, agreed. I would even support removing use of `chsh` entirely and replacing its use with that support section. Probably best to assume `zsh` isn't installed at all.

**Comment by jesshong** [comment]
W

**Comment by ncanceill** [comment]
Hi all,

I strongly disagree on one point (we already had this discussion somewhere, but it has been buried under the heap of open issues and is forever lost). It is **NOT** _"probably best to assume Zsh isn't installed at all"_.

This is **Oh-My-Zsh**. Why would anyone try to install it without having Zsh installed or even knowing what it is?

The `chsh` is only there to take care of the case where the user inadvertently launched the install from another shell than Zsh.

I still believe some help could be provided as to how Zsh can be installed, but for that a link in the README should be enough.

**Comment by tomauty** [comment]
Being that the issue opener came here not having fully set up Zsh (and that the discussion has happened in the past), I think there is a non-negligible number of people that see examples of various things using OMZ and aren't familiar with the setup, but want to be fully configured as quickly as possible.  

A link might actually be the best choice (as long as we can safely assume the link will remain alive), so that OMZ maintainers aren't being asked questions about non-OMZ-related Zsh issues. I imagine that's the most pressing issue with providing some help with the initial setup.

**Comment by MartinDelille** [comment]
Personnally I didn't knew ZSH before OMZ. As @tomauty said, I wanted to have OMZ set up as quickly as possible.

**Comment by MartinDelille** [comment]
As @ncanceill told it, let's assume ZSH is already installed on the system.

**Comment by mcornella** [comment]
I posted a response at https://github.com/robbyrussell/oh-my-zsh/pull/3736#issuecomment-91372856, can we reach an agreement there?
