### ISSUE TITLE
os x 10.10 can't build cache

### ISSUE THREAD

**Issue by beyondkmp** [robbyrussell/oh-my-zsh#3720]
```bash
~|⇒  cd .oh-my-zsh/cache
⇒  ls
```
There is no cache. And I use pip ,there is no cache.

```bash
beyond@birdcat:~/.oh-my-zsh/cache|master
⇒  pip install -
```

it complets - options first ,not the name of the software. 

The version of pip is
```bash
⇒  pip --version
pip 6.0.8 from /usr/local/lib/python2.7/site-packages/pip-6.0.8-py2.7.egg (python 2.7)
```

Could you help me???

**Comment by apjanke** [comment]
It's normal for the `.oh-my-zsh/cache` directory to be empty. Only some plugins use it.

It also seems normal for the pip completion to be completing option names, since you have a "-" as the last character in the command you've typed so far. What were you expecting to happen that isn't working for you?

**Comment by beyondkmp** [comment]
I expect it completes the software's name.
I have solved it! I install zsh-completions, and I write the following setting in .zshrc
```other
#fpath=(/usr/local/share/zsh-completions $fpath)
```
So I find it rum zsh-completions firstly. It  conflicts  with the plugins of oh-my-zsh. Understand? Thank you also!

**Comment by apjanke** [comment]
This sounds normal, too. Options start with a dash, so if you type in a dash and hit tab, the completion system thinks you are typing an option, so it completes option names for you. If you type in the first couple letters of a software or package name and hit tab, then it will complete package names.

For example, if you type `pip install foo` and hit tab, you'll get a list of package names starting with "foo".

```
$ pip install foo
foo             foobar2         foodstats       foolib          foorep
fooArjun        foocaptcha      foohid          foolscap        foot-fixtures
foobar          foodlist        fookebox        foonitidigital
```
