### ISSUE TITLE
"aptitude upgrade" not autocompleted

### ISSUE THREAD

**Issue by tpimh** [robbyrussell/oh-my-zsh#3722]
I don't know if it's oh-my-szh issue, but if I type "aptitude upg" and press <Tab>, it is autocompleted as "aptitude -upgrade", because "upgrade" is not in the autocompletion list, only "full-upgrade" and "safe-upgrade" are.
Could you please fix it?

**Comment by tpimh** [comment]
Found relevant issue: http://sourceforge.net/p/zsh/bugs/75/
Maybe, it would be usefull to add a fix for it in debian.plugin.zsh?

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

OMZ simply uses Zsh's built-in completion system, and it is not easy to customize — you are welcome to give it a try, though. We prefer that these issues get solved by Zsh. Moreover, you can see that Hong Xu [is waiting for](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=667578) Debian devs to act.

**Comment by tpimh** [comment]
Issue is closed, but does not seem to be fixed to me.
Is it really fixed or is it "WONTFIX"?

**Comment by mcornella** [comment]
Yeah this is a wontfix. As @ncanceill said, it's a matter of the `aptitude` command not printing the `upgrade` command on the `aptitude --help` list. Besides, the real commands are `safe-upgrade` (equivalent to `apt-get upgrade`) and `full-upgrade` (equivalent to `apt-get dist-upgrade`). The `upgrade` command works but is only there for compatibility with `apt-get`.
Just use `aptitude` with `safe-upgrade` and you'll be fine.

**Comment by tpimh** [comment]
I was planning to create an oh-my-zsh plugin which will be similar to yaourt in Arch. For example, if operation is not permitted (running `apt-get update` with non-root user), it will ask for password instead of printing errors. This may make someone's life easier.

**Comment by mcornella** [comment]
That's a lot of work, and if you're planning to change aptitude's completion to have the `upgrade` entry appear you may even go insane because of the weird syntax. 

It's really better if you grow accustomed to the `(safe|full)-upgrade` commands and just go with it. I did and I haven't looked back since (infomercial-mode off :wink: )
