### ISSUE TITLE
af-magic breaks line wrapping on ARM

### ISSUE THREAD

**Issue by 5paceToast** [robbyrussell/oh-my-zsh#3724]
Running on ARMv7, using af-magic breaks line wrapping.

Expected behavior: after the cursor reaches the end of the line, it passes a \n and continues on the next line.
Actual behavior: after the cursor reaches the end of the line, it seems to pass a \r (erasing the line from view) and reusing the existing line. If you backspace back unto the present line, the characters are still missing (though in-buffer).

This seems to be an af-magic specific issue, since after testing with a few other teams, that issue would not reproduce (but is 100% reproducible with it, in this environment).

Environment:
- Raspberry Pi 2
- Arch Linux ARM (up to date)
- Version: zsh 5.0.7 (armv7l-unknown-linux-gnueabi)

I might look into af-magic source and/or try compiling zsh manually to see if that changes anything, but for now submitting this (in case it's something obvious I'm missing).
What I do find strange is this only happens on my ARM system...

**Comment by jgrar** [comment]
@5paceToast I've seen similar behaviour but unrelated to ARM and zsh, usually being an issue with PS1, does changing it solve the issue?

Could you provide more information about your current configuration? There's a diagnostic script here: https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics.zsh

paste the output of  `source diagnostics.zsh; omz_diagnostic_dump` to a gist

**Comment by 5paceToast** [comment]
Output with af-magic (broken): http://sprunge.us/KJge
Output with gallois (works fine): http://sprunge.us/LEXH
(if you want it in gist specifically, I can do that, I'm just used to sprunge ( `command | sprunge` )

**Comment by apjanke** [comment]
That's a little odd. There's not a whole lot of difference between `af-magic` and `gallois`. Does it happen with other themes that have a multi-line `PS1`, like `amuse` or `adben`?

What terminal are you working in? Are you on toast-dpi locally or ssh'ed in to it?

I've also updated that diagnostic dump function to grab additional information, if you want to do a rerun of it.

**Comment by apjanke** [comment]
Oh, and I think we would prefer gists: that way all of the information is available on GitHub indefinitely for future reference. Sprunge eventually deletes its posts, so we'd lose that data and the bug reports would be less useful.

**Comment by 5paceToast** [comment]
I have since moved to Void Linux (partially for the sake of runit). Not sure if something changed with zsh, or OMZ, but af-magic no longer has the problematic behavior (neither does amuse, at  which point I think it's solved). I'll attach logs anyway.

Toast-rpi is my Raspberry Pi 2 (ARM 7hf), and I am accessing it through ssh (KiTTY and OpenSSH both had (and now that it appears fixed, have) the  same behavior).

Reran the logs, can be found [here](https://gist.github.com/5paceToast/a68f4dc0cdb8985acd94), the first (read: older) one is with af-magic, the other one is with gallois.

Maybe it's an issue with how Arch ARM compiles it?
