### ISSUE TITLE
Git Alias Commands

### ISSUE THREAD

**Issue by AndyF** [robbyrussell/oh-my-zsh#3730]
Oh-my-zsh currently ignores aliases in `~/.bash_profile`. Is there any way to add aliases to my `zshrc`?

Trying to add this:
```
function acp() {
    git add .
    git commit -a -m "$1"
    git push
}
```

**Comment by mcornella** [comment]
You can add this exact same thing to ~/.zshrc, at the end of it to prevent
it from being overridden by oh-my-zsh.
The same with any other aliases you need to add.
—
Marc

**Comment by AndyF** [comment]
![screen shot 2015-03-27 at 2 25 44 pm](https://cloud.githubusercontent.com/assets/5637822/6874380/317eb8d6-d48d-11e4-88c3-fc766b46b54c.png)

I get a `zsh: command not found: acp` adding the above alias to the end of `.zshrc`.

**Comment by mcornella** [comment]
Ok, have you restarted the terminal? You need to restart each time you make
a change to zshrc. Also check you didn't misspell the function name or
something.

I'm just trying to rule out basic problems, as you see 😁

**Comment by AndyF** [comment]
Thanks @mcornella , restarting the terminal did it. :+1:

**Comment by mcornella** [comment]
I figured 😊. A shortcut I use all the time is just running "exec zsh".
This will run zsh and put it as the main process, therefore zshrc will be
re-read.

Cheers
—
Marc
