### ISSUE TITLE
Home and End keys not working on CentOS

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#3733]
Avarus presented a solution that work great [here](https://www.linuxquestions.org/questions/linux-software-2/ins-end-delete-keys-are-mischevious-297024/)

```bash
#Rebind HOME and END to do the decent thing:
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
case $TERM in (xterm*)
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
esac

#To discover what keycode is being sent, hit ^v
#and then the key you want to test.

#And DEL too, as well as PGDN and insert:
bindkey '\e[3~' delete-char
bindkey '\e[6~' end-of-history
bindkey '\e[2~' redisplay

#Now bind pgup to paste the last word of the last command,
bindkey '\e[5~' insert-last-word
```

**Comment by jgrar** [comment]
I'm confused.

Isn't this completely zsh settings related? Or do these keys still not work after binding them and loading oh-my-zsh?

I don't believe I've ever had home/end keys behave like this with zsh out-of-the-box, it doesn't define them like this for a reason: some people don't have these keys and sometimes they aren't mapped properly to begin wtih.

I don't think this is oh-my-zsh or centOS related.

FYI: CTRL+A and CTRL+E are the default keybinds for beggining-of-line and end-of-line, respectively.

**Comment by leoheck** [comment]
You are right, the zsh does not have the home/end keys by default.
Thanks for the Ctrl+a and Ctrl+e tip. It will be very usefull.

**Comment by jgrar** [comment]
I was likely too hastey dismissing this as a non-issue. OMZ apparently _does_ bind home/end keys for this exact behaviour: https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh#L37

Could you please join the discussion in #3061 it would be helpful to coordinate some information gathering in one location.
