### ISSUE TITLE
Design or Architecture documentation page

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#3740]
It wold be nice to have a design or architecture documentation page to serve as a guide to the oh-my-zsh codebase and system for people who want to hack on it, provide plugins or themes, or just get more familiar with what it's doing.

I've put together a rough design documentation page at https://github.com/apjanke/omz-scratch/wiki/OMZ-Design, based on my reading of the oh-my-zsh source code. Anybody want to look at that and give some feedback before I add it to the main oh-my-zsh wiki? (Especially @mcornella, @ncanceill, or @robbyrussell?)

**Comment by ncanceill** [comment]
Very good work. I have a few changes I want to suggest, but I think this should be added to the main wiki right away, just indicate at the top that it is a work in progress.

**Comment by apjanke** [comment]
Thanks!

I've moved it to the main wiki at https://github.com/robbyrussell/oh-my-zsh/wiki/Design and added a work-in-progress note at the top.

**Comment by apjanke** [comment]
The Design page is fleshed out enough to consider this done. (Though it'll always be a work-in-progress as long as OMZ is evolving.) Closing this.
