### ISSUE TITLE
plugin command not recognized in shell script

### ISSUE THREAD

**Issue by yev** [robbyrussell/oh-my-zsh#3760]
Hi,

I didn't find any useful information with Google, so I ask here.

I'm writing a little shell script to automate the start of my dev env. For this I created  start.sh file:
```bash
#! /bin/zsh

echo "setting up environment for development"
tab
```

After execution, I have:
setting up environment for SF development
./start.sh:4: command not found: tab

I have enabled osx plugin in my zshrc config file and command tab works well while I type it in terminal.

Any idea how can I fix it?

**Comment by jgrar** [comment]
@yev this isn't the place for your question, but I'll answer it for you anyway. Startup files, such as ~/.zshrc won't be sourced if the running shell is non-interactive. The script you're writing is an example of a non-interactive instance of zsh. You can remedy this by sourcing your zsh startup scripts (and thus oh-my-zsh) with `source $HOME/.zshrc` or you can start an interactive instance with `#!/bin/zsh -i`.

**Comment by yev** [comment]
@jgrar thank you for your response. I close the ticket.
