### ISSUE TITLE
.bash_profile ignored on mac

### ISSUE THREAD

**Issue by danielgomezrico** [robbyrussell/oh-my-zsh#3765]
I had some aliases on my .bash_profile file and when I install zsh it looks like it dosen't use it, there are no aliases :(

**Comment by ncanceill** [comment]
I am not sure how to answer.

What makes you think that Zsh should use `~/.bash_profile`?

Do you realize that Bash and Zsh are two different shells?

Easiest way to get it working is
```zsh
cat ~/.bash_profile >> ~/.zshrc
```
or even simply
```zsh
echo "source ~/.bash_profile" >> ~/.zshrc
```

**Comment by danielgomezrico** [comment]
Opa, ok, thanks

**Comment by ncanceill** [comment]
Glad to help.

You should check out the various [plugins](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins-Overview) that oh-my-zsh has to offer, they already offer many useful aliases you could like.
