### ISSUE TITLE
Whether there is support freebsd?

### ISSUE THREAD

**Issue by chrom** [robbyrussell/oh-my-zsh#3769]

**Comment by mcornella** [comment]
It should work fine since it's also targeted at OSX, which is a version of BSD. Try it and tell us! :smile:

**Comment by ncanceill** [comment]
@mcornella I would say OS X is derived from BSD, not a version of it.

@chrom we already have BSD users, and yes, if you use OMZ under FreeBSD, you will get support. Please close this issue, and feel free to open a new one if you find a particular bug.

**Comment by mcornella** [comment]
> I would say OS X is derived from BSD

Fair enough :grin: 

Adding this to [closable-v3](https://github.com/robbyrussell/oh-my-zsh/pull/3651)

**Comment by apjanke** [comment]
I'm running oh-my-zsh on FreeBSD and PC-BSD myself. It'll mostly work there.

There's one big outstanding issue on FreeBSD, though: the installer's broken (#3367). Which might be why they're asking.

@chrom, Check out #3367. Once you get OMZ installed by manually cloning the repo and editing `~/.zshrc`, or by hacking the installer, it should work.

**Comment by gyaaniguy** [comment]
Getting the same behaviour in freebsd 12.0
