### ISSUE TITLE
Unicode errors on fresh install of Elementary Freya

### ISSUE THREAD

**Issue by amingilani** [robbyrussell/oh-my-zsh#3771]
Hi, I get this:
```
 gilani@ava  ~  echo "note the unicide error in the beginning?"
note the unicide error in the beginning?
 gilani@ava  ~  git init check-this-out
Initialized empty Git repository in /home/gilani/check-this-out/.git/
 gilani@ava  ~  cd check-this-out 
 gilani@ava  ~/check-this-out   master  echo "see?"
see?
 gilani@ava  ~/check-this-out   master ava  ~ 
```
Yes, i've seen #2645. I uncommented `export LANG=en_US.UTF-8` and even added `export LC_ALL=en_US.UTF-8` but no cigar. Help please?

**Comment by ncanceill** [comment]
Hi,

Just to be sure, please check that your terminal emulator is also configured to use UTF-8. You should be able to `echo 😸` if it is the case.

Anyway, even though UTF-8 is probably set up, you seem to be using the agnoster theme. In that case, you very likely need a Powerline-patched font. Please go [over there](https://github.com/powerline/fonts) and grab one you like.

**Comment by amingilani** [comment]
Ahhhh.. installing the font worked! Yes, i could echo out the kitty cat! :smile_cat: thank you!
