### ISSUE TITLE
Add IRC channel

### ISSUE THREAD

**Issue by MartinDelille** [robbyrussell/oh-my-zsh#3784]
Is there an IRC channel for the project?

**Comment by ncanceill** [comment]
Not that I am aware of. There is a [Twitter feed](https://twitter.com/ohmyzsh). To quote from [the Community page on ohmyz.sh](http://ohmyz.sh/community/):
> Have suggestions of what to display here? Send an email to [robby@planetargon.com](mailto:robby@planetargon.com).

**Comment by Dog** [comment]
I don't know if its official, but there is a channel on freenode. It seems very quiet though.

**Comment by jgrar** [comment]
@Dog and the name of that channel is?

**Comment by Dog** [comment]
#oh-my-zsh

**Comment by apjanke** [comment]
I'm on freenode #oh-my-zsh semi-regularly, but it is pretty quiet. If we make a semi-official one, we should probably start a new channel where the project maintainers can have ops rights.

**Comment by mcornella** [comment]
[Gitter](https://gitter.im) is a popular one amongst GitHub-hosted open source projects. I've created one in less than a minute: https://gitter.im/robbyrussell/oh-my-zsh
