### ISSUE TITLE
Error when opening new zsh session on Mac

### ISSUE THREAD

**Issue by Fabs** [robbyrussell/oh-my-zsh#3785]
I'm getting the following error, I think it has something to do with oh-my-zsh. It's been working for ages on my mac with no issue.  It's Yosemite the developer preview with the beta software update from apple.

zsh:12: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
zsh:12: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function

zsh 5.0.7 (x86_64-apple-darwin14.0.0)
plugins=(brew bundler catimg coffee common-aliases compleat dirhistory gem github last-working-dir meteor npm ruby rvm sudo node rails git ruby colorize cp git-extras git-flow github gnu-utils osx postgres rsync screen textmate zsh-syntax-highlighting)

I dunno how to get oh-my-zsh version, so i Have:
commit 75b9030f48a55a42849cc68b0fc5b92d66d236ac (origin/master, origin/HEAD)
Merge: 8301040 d4918ae
Author: Robby Russell <robby@planetargon.com>
Date:   Mon Mar 30 07:39:34 2015 -0700
Merge pull request #3731 from NHDaly/patch-1
Fixed Typo.

**Comment by Fabs** [comment]
Also I have the following change from the oh-my-zsh repo for agnoster. I think its not related, but who knows. 

![image](https://cloud.githubusercontent.com/assets/10524/7208415/00006b84-e517-11e4-8b37-08b7b129305f.png)

**Comment by apjanke** [comment]
Providing the oh-my-zsh git commit SHA like you did is the closest thing we have to a version. A `git status` output can also be useful to pick up any locally changed files.

When exactly does the error happen? Immediately when starting zsh? Does it happen every time?

I wonder if it something about these statements in the `git-fast` plugin, or somewhere similar, with an undefined `$service` collapsing to produce `___main`. Are you using git-fast, too?

```
[@ in ~/local/opp/omz/oh-my-zsh on ⇄ git-status-timebox]
$ grep -r '}_main' *
plugins/gitfast/_git:		emulate ksh -c __${service}_main
plugins/gitfast/git-completion.bash:		emulate ksh -c __${service}_main
```

It looks like it might be completion-related, so first `rm ~/.zcompdump*` and restart zsh to clear out old cached completion definitions.

**Comment by ncanceill** [comment]
Hi @Fabs, could you check out the [Completion section](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#completion-problems) of the Troubleshooting wiki page that I just wrote and see if it helps you?

**Comment by firedev** [comment]
That is github plugin, just enabled it and got a bunch of errors, without it everything worked fine:

```
Last login: Wed Apr 29 14:06:05 on ttys007
mux szsh:12: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
```

**Comment by Fabs** [comment]
Hey guys. Sorry it took me a while to get back here. I missed the notification. 

The ~/.zcompdump* fixed that for me. @ncanceill 

My git status only talks about that modification above @apjanke 

```
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
```

I have github plugin @firedev but do not have git-fast @apjanke 
`plugins=(brew bundler catimg coffee common-aliases compleat dirhistory gem github last-working-dir meteor npm ruby rvm sudo node rails git ruby colorize cp git-extras git-flow github gnu-utils osx postgres rsync screen textmate zsh-syntax-highlighting)
`

**Comment by apjanke** [comment]
Cool.

@ncanceill, this happens often enough, maybe we should pull the `rm ~/.zcompdump*` out of "Completion Problems" in the Troubleshooting page and tell everyone to do it regardless of what problem they're having.
