### ISSUE TITLE
[vi-mode plugin] The wiki entry says to read the plugin readme file - which isn't there

### ISSUE THREAD

**Issue by tofagerl** [robbyrussell/oh-my-zsh#3788]

**Comment by mcornella** [comment]
Which plugin are you talking about? -- plugin READMEs are a relatively young feature, only some of them have it already.

**Comment by tofagerl** [comment]
Oh, vi-mode. 
vi-mode

Maintainer: robbyrussell

** Read the plugin README file **

Increase zsh vi-like functionality

**Comment by mcornella** [comment]
Ok, please update the title to reflect that. Let's see if someone has written one and can submit a PR. 
In the meantime, do you have any specific question about the plugin that could be answered?

**Comment by tofagerl** [comment]
No, I read the file.

**Comment by apjanke** [comment]
There's a `vi-mode` plugin README.md now, since 0e35bd4001494782fb1956acaebadf2f81c25b42.

**Comment by mcornella** [comment]
I agree: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vi-mode/README.md. I'm closing this as solved.
