### ISSUE TITLE
is_dirty:cd:1: too many arguments

### ISSUE THREAD

**Issue by xinput** [robbyrussell/oh-my-zsh#3789]
hello guys,

since i'm using agnoster theme, i get the following error when i'm entering a cloned git repository. for example when i'm entering the .oh-my-zsh/ folder:
![bildschirmfoto 2015-04-18 um 23 56 39](https://cloud.githubusercontent.com/assets/11652924/7217368/157a617a-e627-11e4-884b-bc25261660e6.png)

someone knows how to fix this?

ok so after doing a git status i get the following:

![bildschirmfoto 2015-04-19 um 00 12 51](https://cloud.githubusercontent.com/assets/11652924/7217405/2fc82984-e629-11e4-9106-aa51a2354490.png)

cheers

**Comment by xinput** [comment]
i uninstalled oh-my-zsh and reinstalled it using curl.

now the error is_dirty:cd:1: too many arguments is gone. 
when i'm run the command "git status" in the .oh-my-zsh dir i get the "string not in pwd" as above.

upgrading oh-my-zsh works fine.
i couldn't find a solution for this error until now.. someone knows how to fix?

**Comment by mcornella** [comment]
Can you post the output of `which is_dirty` and `which cd`?

**Comment by xinput** [comment]
follwing output on the both commands:

![bildschirmfoto 2015-04-19 um 22 10 02](https://cloud.githubusercontent.com/assets/11652924/7221163/f4407ffc-e6e0-11e4-8a13-900d86a5cb9f.png)

**Comment by HeroCC** [comment]
What was the problem? It may help others

**Comment by xinput** [comment]
it was a typo in my .aliases dotfile.

i declared a alias with the name "git" which should be "dgit" instead.

so if i run git status it tried to  use the alias.

**Comment by apjanke** [comment]
@xinput: As the original issue poster, you (and the repo maintainer) have permissions to close it. Should be a "close" button down below.

**Comment by xinput** [comment]
@apjanke: thanks, i didn't noticed this button!

**Comment by samegel** [comment]
FTR I had a similar problem after making a similar goof. I got the error `is_plugin:cd:3: too many arguments` (or some such) after setting an alias to `test` (a built in command).

Helps to make sure syntax highlighting is on for vim (add `syntax on` to your .vimrc).
