### ISSUE TITLE
Can't Change Theme

### ISSUE THREAD

**Issue by realph** [robbyrussell/oh-my-zsh#3801]
I'm using iTerm on OS X, and I can't for the life of me work out how to change the theme. I'm going into my `.zshrc` file and changing the theme at the top to:

    ZSH_THEME="mh"

and hitting save. But for some reason, why I boot back up iTerm, I get the same dull black theme.

Any reason why it might be doing this?

Any help is appreciated. Thanks in advance!

**Comment by mcornella** [comment]
Are you sure you successfully changed the shell to `zsh`? Do `echo $SHELL` to confirm

**Comment by realph** [comment]
I hadn't changed the shell, silly me!
