### ISSUE TITLE
.bash_profile needs to be sourced after oh-my-zsh updates

### ISSUE THREAD

**Issue by nmartin867** [robbyrussell/oh-my-zsh#3807]
System Spec: OSx Yosemite 10.10.2

I noticed that after each oh-my-zsh update ENV vars set in ~/.bash_profile are no longer on my PATH. 
```bash
$ echo $JAVA_HOME
// it's gone
```
Simply sourcing .bash_profile fixes the issue:

```bash
$ source ~/.bash_profile
```
So it's a very minor inconvenience with a simple work around.I don't think oh-my-zsh update would require heightened privileges to source .bash_profile post update (I could be wrong).

**Comment by mcornella** [comment]
That's not how you should solve it. `.bash_profile` is a file read only by bash, which is not compatible with zsh. If we start sourcing `.bash_profile` bad things will start to happen. Instead, you should copy those ENV vars to the `.zshrc` file, preferably at the end of it.

Not an issue, please close.

**Comment by nmartin867** [comment]
It didn't occur to me to put env vars in `.zshrc`. Good enough. Thanks!

**Comment by teledirigido** [comment]
Just added "source ~/.bash_profile" to my .zshrc and everything is working fine now even when I open new tabs.

**Comment by zuhrasofyan** [comment]
@teledirigido: you save me hours of frustration and began considering using instant solution such as MAMP!

**Comment by preslavrachev** [comment]
@teledirigido @zuhrasofyan to save myself from managing variables and aliases here and there, I did the same. Perhaps, it is a only short-term solution. Eventually, I think that I will extract the harmless variable and alias statements into a third `.sh` file, which will then be sourced by `.bash_profile` and `.zshrc` respectively.

**Comment by sherlockhoatszx** [comment]
Yes, After i installed, i can't open python or  spyder in the terminal. and i use the command 
> source ~/.bash_profile
That solved my problem

**Comment by DuM4ll3** [comment]
@mcornella how is the best way to do it ? I had the same problems and I'm using the `source ~/.bash_profile` as a workaround.

> If we start sourcing .bash_profile bad things will start to happen
such as ? 

thanks

**Comment by dedalozzo** [comment]
The best way is `source ~/.bash_profile` at the end of your `.zshrc` file. Nothing bad will happen. Copying all the content of `.bash_profile` is not smart, because you have to maintain two file in synch in case you want remove zsh in the future.

**Comment by steelx** [comment]
you should update and add `➜  ~ nano .zshrc` with `export PATH=${PATH}:/usr/local/mysql/bin`

**Comment by lijiansong** [comment]
When I put `source ~/.bash_profile` into the .zshrc, every time I open the terminal, I will get a waring, that is very anoying!

**Comment by yayanbachtiar** [comment]
thanx

**Comment by mcornella** [comment]
The way to do it is having one file that is both compatible with bash and zsh, and sourcing it in `.bash_profile` / `.bashrc` and `.zshrc`. `.bash_profile` can have syntax that is only compatible with bash, so be careful.
