### ISSUE TITLE
frontend-search bug

### ISSUE THREAD

**Issue by Septembers** [robbyrussell/oh-my-zsh#3810]
```
➜  ~ jquery test
http://api.jquery.com/?s=test
➜  ~ Created new window in existing browser session.

➜  ~ 
```

[frontend-search.plugin.zsh#L116](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/frontend-search/frontend-search.plugin.zsh#L116) using replaced by:
```
  if [[ $(uname -s) == 'Darwin' ]]; then
    open "$url"
  else
    sh -c "xdg-open $url >/dev/null 2>&1 &" >/dev/null
  fi
```
the revised:
```
➜  ~ jquery test
http://api.jquery.com/?s=test
➜  ~ 
```
-----------------------------------------------------------
OS: Ubnutu 15.04 (x64)
Branch: `* master ff4663a Merge pull request #3802 from willmendesneto/patch-1`

**Comment by willmendesneto** [comment]
@Septembers, for ubuntu users you should install xdg-utils package via apt-get. This package has [xdg-open](http://manpages.ubuntu.com/manpages/hardy/man1/xdg-open.1.html), the plugin used for open search page. Are you already have this package installed in your OS?

**Comment by Septembers** [comment]
```
➜  ~ dpkg -S xdg-open 
xdg-utils: /usr/share/man/man1/xdg-open.1.gz
xdg-utils: /usr/bin/xdg-open
➜  ~ 
```

**Comment by willmendesneto** [comment]
@Septembers, please, check if `xdg-open http://api.jquery.com/?s=test` run without problem in your CLI and update here. 

![Imgur](http://i.imgur.com/1DRYBLl.png?1)

`xdg-open` isn't enabled by default for open your browser, so your search will be ocurring in your CLI environment via socket.

![Imgur](http://i.imgur.com/N3x6YyB.png?1)

Please try reinstall `xdg-utils` package and, if this doesn't works on, please pass more informations about your OS configuration.

**Comment by Septembers** [comment]
![1](https://cloud.githubusercontent.com/assets/3842474/7335974/4a3427fe-ec15-11e4-987a-1841855847df.gif)

**Comment by willmendesneto** [comment]
@Septembers, `xdg-open` is working ok. Could you try run `jquery test` or `frontend jquery test` command and show the result, please?

**Comment by Septembers** [comment]
![2](https://cloud.githubusercontent.com/assets/3842474/7336055/db8ada04-ec1a-11e4-9fdb-5552f3ca3e6b.gif)

**Comment by willmendesneto** [comment]
Now it's ok. Thanks for contribute and feedback @Septembers

**Comment by ncanceill** [comment]
Thanks @willmendesneto for being so reactive ;-)

**Comment by willmendesneto** [comment]
you are welcome! @ncanceill could you close this issue, please?

**Comment by septs** [comment]
@ncanceill `python -m webbrowser -t "http://www.python.org"`
see https://docs.python.org/3/library/webbrowser.html

**Comment by mcornella** [comment]
@setps we're now using a [dedicated `open_command` function](https://github.com/robbyrussell/oh-my-zsh/blob/3477ff2/lib/functions.zsh#L18) that runs the proper command for the platform. Note this is an old issue. Using python wouldn't be the most portable way to solve this as well, given that it's not installed by default in most systems.
