### ISSUE TITLE
Examples for tmux.plugin.zsh?

### ISSUE THREAD

**Issue by binarykitchen** [robbyrussell/oh-my-zsh#3824]
Are there any examples out there how to use tmux.plugin.zsh in conjunction with an SSH session?

Just the basic stuff, thanks!

**Comment by ncanceill** [comment]
Please see the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#tmux) on how to use the plugin.

Also note that, when you SSH to a remote machine, you open a shell on that machine, so Zsh, OMZ and the tmux plugin should be installed on that remote machine.

Maybe I did not understand what you were asking, can you try to be a bit clearer?

**Comment by binarykitchen** [comment]
yes, i saw that but there are no examples and i didn't know the plugin must be enabled on that remote machine.

all i need is some examples how you are using the plugin. i mean, how you ignite a ssh session from localhost to the remote machine that never dies by using that plugin?

**Comment by ncanceill** [comment]
As I explained above, when you open an SSH session, you are actually using a shell on the remote machine. Your local shell configuration is thus irrelevant. If you want Zsh and OMZ when you SSH to the remote machine, you need to install Zsh and OMZ on the remote machine.

A bit more about SSH: when you connect to a remote machine, it is acting as SSH server. With a default configuration, the server will automatically disconnect clients after a certain period of inactivity. When you get disconnected, the SSH session is closed, and programs you have launched from that shell session get interrupted.

***

Also, before we get to the plugin, you need to understand what the [`tmux`](http://tmux.sourceforge.net) program is: a terminal multiplexer, kind of like `screen`. When you launch it from a shell, it allows you to open multiple programs within the same terminal; also, the programs will not be interrupted when the shell session is closed, instead they will be detached and waiting to be re-attached to a `tmux` session.

So, technically, `tmux` will not _"ignite a ssh session_ [...] _that never dies"_. What it allows you to do is:
1. Use SSH to open a shell on the remote machine
2. From that shell, launch `tmux`
3. From that `tmux` session, launch your programs and do your stuff

Then, if you get disconnected, your programs are not interrupted. You can simply:
1. Use SSH to connect again
2. Use `tmux` to re-attach to your programs
3. Continue working like it never happened

Instead, if you really want to keep you SSH sessions from disconnecting entirely, you should use the [`*AliveInterval` config options](http://www.openssh.com/faq.html#2.12).

***

Anyway, the above is about SSH and the `tmux` _program_. Concerning the `tmux` _plugin_, its goal is simply to make it easier to use the `tmux` program.

**Comment by binarykitchen** [comment]
Ah, wonderful, this tmux tool is really very very handy. Wish I had known it earlier!

Now I can do this:
1. ssh into server
2. start `tmux` and get a session with the name '0'
3. do anything and do not exit
4. go to work, ssh into the server
5. do `tmux attach` and it automatically links me to that session

Very nice. Okay, now that I understand the basics, I assume, enabling that plugin and setting `ZSH_TMUX_AUTOSTART` to true, will save me from typing `tmux attach` when SSH-connecting to a server. Is that correct?

**Comment by ncanceill** [comment]
Not exactly.

Setting `ZSH_TMUX_AUTOSTART` (on the remote machine) will save you from typing `tmux` when you connect.

You should also set `ZSH_TMUX_AUTOCONNECT` if you want `tmux` to detect an existing session and save you from typing `tmux attach` when you connect and there is an existing `tmux` session.

Finally, you can enjoy the aliases provided by the plugin — issue `alias | grep tmux` to list them.

**Comment by binarykitchen** [comment]
Merci beaucoup! Your support is magnifique.

**Comment by ncanceill** [comment]
De rien ;-)

Please close this issue if it is solved.

**Comment by mcornella** [comment]
Hi @ncanceill, excellent support here. Perhaps we could a brief intro as a README file for the tmux plugin. I'm adding this to a list of pending READMEs.
Thanks!

**Comment by binarykitchen** [comment]
Hi @ncanceill - I have another question if you do not mind:

Just had a tmux session with two horizontal panes. One was running a command, dumping the output to a log file. The other pane outputs that log file with `tail -f ...` but I realized, that pane is not synced unless I switch to it.

Can I somehow reconfigure tmux so that all panes are in real-time? Have all panes on the screen work, output different logs and so on?

**Comment by ncanceill** [comment]
Sorry, I am much more familiar with `screen` than `tmux`, and I really have no idea how to do what you want.

**Comment by binarykitchen** [comment]
Pas de probleme. I ll ask on Stackoverflow then. Looks like the live output of a log file when using `tail -f test.log` does not work when you are in a tmux session.
