### ISSUE TITLE
Command not found...

### ISSUE THREAD

**Issue by siamakmokhtari** [robbyrussell/oh-my-zsh#3830]
Hi guy,
I hope that you have great fell. I need to help...
I installed ZSH on OSX and I set my iterm to ZSH. When I open iterm and Enter `gulp` ZSH return to me `zsh: command not found: gulp` like below photo:

![qu](https://cloud.githubusercontent.com/assets/3109082/7419420/2e847b4e-ef8a-11e4-93ad-ca6c5e7fbb3a.jpg)

Thanks for Watching ;)

**Comment by ncanceill** [comment]
Hi,

Your English is not very clear, so forgive me for making some assumptions here.

You can remark that `gulp` is found when you open Zsh by running `zsh` from your Bash. This tells me that your iTerm is not properly running Zsh.

Please check which Zsh was run in your example, by opening Bash and running `which zsh`. The output you get should be the exact command configured in iTerm. Use that output to correct your iTerm configuration.

**Comment by mcornella** [comment]
I'd assume this has to do with wrong PATH settings. In the situation above, he opens bash which reads `.bashrc` or `.bash_profile`. These contain an `export PATH` statement of some sort, and on subsequently opening zsh this one has the updated PATH.

@siamakmokhtari Look on your `~/.bashrc` or `~/.bash_profile` for a line that reads `export PATH=....` and add that to your zshrc file. If you don't find this, post the content of those files and we'll try to help you.

**Comment by mcornella** [comment]
Any updates?
