### ISSUE TITLE
Not an editor command: BundleInstall

### ISSUE THREAD

**Issue by binarykitchen** [robbyrussell/oh-my-zsh#3832]
Seeing this error after calling `vundle`, why?

```
Error detected while processing command line:
E492: Not an editor command: BundleInstall
```

**Comment by vikikamath** [comment]
- `git` must be installed and `Vundle` must be checked out.
- `Vundle` uses 'PluginInstall' instead of 'BundleInstall'. 

See the Vundle documentation  for sample .vimrc file [here](https://github.com/gmarik/Vundle.vim).

**Comment by binarykitchen** [comment]
Then there must be a bug. Because https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vundle/vundle.plugin.zsh executes with `BundleInstall`

**Comment by ajpaulson** [comment]
Vundle changed a while ago and I believe an issue was raised here to update the plugin to reflect vundle's changes.

**Comment by mcornella** [comment]
This is fixed in the current version. Please close
