### ISSUE TITLE
Can you support syntax highlight for Dart ?

### ISSUE THREAD

**Issue by LyndonChin** [robbyrussell/oh-my-zsh#3843]
As we know, The google project [sky](https://github.com/domokit/sky_sdk) is using Dart and it is being more popular, would you like to add the syntax highlight support ?

**Comment by ncanceill** [comment]
Hi,

What do you mean by _"the syntax highlight support"_? By convention your shell command-line is not highlighted, and you would not write in there with Dart anyway.

Maybe you want your favorite editor to highlight Dart code, in that case I suggest you should look that up in your editor's manual.
