### ISSUE TITLE
debian plugin 'ag' alias overrides silversearcher app

### ISSUE THREAD

**Issue by oryband** [robbyrussell/oh-my-zsh#3844]
Many people, including myself, are using [the silver searcher](http://geoff.greer.fm/ag/) as a better grep/ack. debian plugin overrides it. You should probably disable this alias if the application is installed, or just find a different alias.

Is there a way to turn this alias off instead?

**Comment by apjanke** [comment]
Duplicate of #3633.

**Comment by KhasMek** [comment]
Please test out that patch and let me know how it works for you @apjanke 
Maybe my implementation isn't the cleanest/best idea for the project, but it's working just fine on my end.

**Comment by oryband** [comment]
closing because duplicate of #3633 , @KhasMek i've replied on the original issue
