### ISSUE TITLE
Slowing down a Homestead-server on a Vagrant setup

### ISSUE THREAD

**Issue by simplenotezy** [robbyrussell/oh-my-zsh#3845]
I have experienced, that after installing oh-my-zsh on a Homestead vagrant server, it is slowed down incredibly.

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

This is a bit vague though. Were you able to track this slowness further down? (plugins, themes, startup files)

Homestead seems like a big box, so many things could be happening here.

**Comment by apjanke** [comment]
Betcha it's git status in the prompt again (like #3706). But yeah, can we get some details?

**Comment by xavierhb** [comment]
@apjanke Although vague, @canfiax could explain that better, it's simply very slow on doing simple operations as accessing a folder or listing a comment. I've notice that the problem only occurs on Git-repository folders, maybe some background checks?

**Comment by apjanke** [comment]
If the problem only occurs in Git-repository folders, it's probably the git status checks in the prompt again (like #3706). You can see more discussion in #3009.

**Comment by xavierhb** [comment]
Thanks @apjanke I solved adding this config to git: `git config --add oh-my-zsh.hide-status 1`

**Comment by mcornella** [comment]
@canfiax any updates on @xavierhb's solution?
