### ISSUE TITLE
Correct place to add additional paths

### ISSUE THREAD

**Issue by jamesla** [robbyrussell/oh-my-zsh#3847]
I want to add the folder ~/Applications to my path, what's the correct way to do this? I realise this is basic but I've checked the docs and couldn't find it (maybe I missed it).

**Comment by ncanceill** [comment]
I suppose you want this folder to be added to your `$PATH` at shell initialization. In this case, it would usually be in `~/.zshrc`, which is sourced at every interactive Zsh initialization. You can read more about Zsh startup files [there](http://zsh.sourceforge.net/Intro/intro_3.html).

When you have figured out where you want to add it, maybe you are also wondering how. The standard way is: `PATH=$PATH:~/Applications`
