### ISSUE TITLE
support zsh not in default directory

### ISSUE THREAD

**Issue by duffqiu** [robbyrussell/oh-my-zsh#3850]
if zsh is not install in default directory, oh-my-zsh will not work properly.

for exmaple, if I install zsh shell in /opt/zsh

the library is under /opt/zsh/lib64
the functions is under /opt/zsh/share/zsh/5.0.2

then oh-my-zsh will not work unless I add below lines in the .zshrc and .oh-my-zsh/tools/check_for_upgrade.sh at the beginning 

module_path=(/opt/zsh/lib64/zsh/5.0.2/)
fpath=(/opt/zsh/share/zsh/5.0.2/functions/ /opt/zsh/share/zsh/site-functions/ $fpath)

any way can default support zsh not in the standard directory?

(BTW, I do this because I want to use oh-my-zsh in coreos)

**Comment by apjanke** [comment]
This should be doable. In fact, I'm a little surprised it doesn't work as is.

It's a little surprising to me that you had to set up `module_path` and `fpath` to get zsh's own functions on there. Oh-my-zsh only adds entries to `fpath` for the custom oh-my-zsh functions. Maybe there's something odd about your `zsh` setup? What's your `$fpath` and `$module_path` when you first start `zsh` without oh-my-zsh loaded?

We also have a pending change for detecting the `zsh` location by parsing `/etc/shells` in #3780 which may be relevant.

**Comment by duffqiu** [comment]
If using centos to install zsh with `yum install zsh`, the default path for `module_path` is at `/usr/lib64/zsh/5.0.2/zsh`, and `fpath` is at `/usr/share/zsh/5.0.2/functions/`

Why I need this because I want to use it in `CoreOS` which doesn't support any installation tools like `yum`. So I have to install it manually. 
BTW, in CoreOS, the path of `/usr/` is read only.

**Comment by apjanke** [comment]
What version/channel of CoreOS are you running?

I assume you installed zsh from source?

**Comment by duffqiu** [comment]
I use coreos633.1
I copy the centos7's Python files from rpm to Coreos

I didn't compile Python from source code

**Comment by apjanke** [comment]
I assume you mean "zsh" instead of "Python".

That's not expected to work. You can't just move files from a package to a different location on the filesystem, or to a different distribution. The paths to the default installation location are already baked in to some of those files. You need to get a working installation of zsh for CoreOS.

Try installing zsh from source, or find a Dockerized package of it for CoreOS. The [zsh-users mailing list](http://zsh.sourceforge.net/Arc/mlist.html), [zsh IRC or wiki](http://zsh.sourceforge.net/), or a CoreOS forum would be a better place to ask about this.

This isn't an oh-my-zsh issue.

**Comment by duffqiu** [comment]
since there is impossible to build the zsh from source for zsh. that is why I copy them from centos rpm.

but I after define the below environment variables, it can work.
that is why i hope oh-my-zsh can support it if someone wants oh-my-zsh in coreos.

```
odule_path=(/opt/zsh/lib64/zsh/5.0.2/)
fpath=(/opt/zsh/share/zsh/5.0.2/functions/ /opt/zsh/share/zsh/site-functions/ $fpath)
```

**Comment by apjanke** [comment]
I'm sorry, this isn't what oh-my-zsh does. OMZ provides customizations and extensions to zsh. It is not a tool for porting zsh to other OSes. You should contact the zsh or CoreOS folks for this.

**Comment by duffqiu** [comment]
ok. got it.
