### ISSUE TITLE
Brew plugin needs minor update for alias bubu

### ISSUE THREAD

**Issue by cold-logic** [robbyrussell/oh-my-zsh#3855]
When running the bubu command Homebrew issues a warning that the behavior of the upgrade command will be changing soon:

Warning: brew upgrade with no arguments will change behaviour soon!
It currently upgrades all formula but this will soon change to require '--all'.
Please update any workflows, documentation and scripts!

**Comment by cold-logic** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/3856

**Comment by mcornella** [comment]
Hi! The homebrew team backtracked on the --all parameter decision: Homebrew/homebrew@a45a34d.
Please close this
