### ISSUE TITLE
Help with maintenance and PullRequests

### ISSUE THREAD

**Issue by diraol** [robbyrussell/oh-my-zsh#3873]
Hi @robbyrussell, first of all, congrats for this really nice work!

I saw that there is so much PullRequests to your repository and I wondered if you want/need some help with them. What do you think about creating a "task-force" to try to clean up some issues and Pull Requests?

Cheers!

**Comment by ncanceill** [comment]
Hi, and thanks for volunteering!

There actually is a [wiki page](https://github.com/robbyrussell/oh-my-zsh/wiki/Volunteers) for that, and we are working on contributing guidelines in #3770.

Also @mcornella and I are working on dwindling down the number of issues and PRs, _resp_ #3651 and #3809.
