### ISSUE TITLE
Don't autocomplete variables

### ISSUE THREAD

**Issue by ivancuric** [robbyrussell/oh-my-zsh#3885]
Using OSX here. How do I disable autocompletion for environment variables?
For instance, if I type `zsh` to get to `zshconfig` this is the result:

```
[~]$ zsh                                                                       
ZSH                            ZSH_THEME_GIT_PROMPT_SUFFIX  
ZSH_CACHE_DIR                  ZSH_THEME_RVM_PROMPT_PREFIX  
ZSH_COMPDUMP                   ZSH_THEME_RVM_PROMPT_SUFFIX  
ZSH_CUSTOM                     ZSH_THEME_TERM_TAB_TITLE_IDLE
ZSH_NAME                       ZSH_THEME_TERM_TITLE_IDLE    
ZSH_PATCHLEVEL                 ZSH_VERSION                  
ZSH_SPECTRUM_TEXT              zsh                          
ZSH_THEME                      zsh_scheduled_events         
ZSH_THEME_GIT_PROMPT_CLEAN     zsh_stats                    
ZSH_THEME_GIT_PROMPT_DIRTY     zshconfig                    
ZSH_THEME_GIT_PROMPT_PREFIX           
```

It's especially bad with the awesome case-insensitive option.
Another example: If I type `wo` to get to virtualenv's `workon` command, I instead get this:

```
[~]$ wor                                                                       
WORDCHARS         WORKON_HOME       work_in_progress  workon  
```

**Comment by mconigliaro** [comment]
:+1:

**Comment by webknjaz** [comment]
Someones work around this by disabling case-insensitive matching http://serverfault.com/a/438119/111608

Yet, I'm looking for opposite — how to make zsh completion suggest me exactly env var names..

**Comment by mcornella** [comment]
> Yet, I'm looking for opposite — how to make zsh completion suggest me exactly env var names..

You can put a dollar sign and it will suggest variables.

As per the original request, I don't think there is a method available to disable completion of variable names. Try asking in [zsh's mailing list](http://zsh.org/mla).
