### ISSUE TITLE
af-magic font

### ISSUE THREAD

**Issue by jrock2004** [robbyrussell/oh-my-zsh#3888]
In the screenshot for af-magic, what font and size is being used?

https://github.com/robbyrussell/oh-my-zsh/wiki/themes#af-magic

**Comment by ncanceill** [comment]
I have no idea, looks similar to [Secret Code](http://www.dafont.com/fr/secret-code.font) but that is not it.

@andyfleming do you remember which font you used for the preview?

**Comment by andyfleming** [comment]
The current preview is not a screenshot I generated, so I'm not sure what font is being used there.
