### ISSUE TITLE
ssh-agent is replaced when invoking a sudo shell

### ISSUE THREAD

**Issue by stucki** [robbyrussell/oh-my-zsh#3890]
When invoking a shell as root using `sudo -s`, the ssh-agent plugin starts a new agent although it already exists.

The problem boils down to a check if ssh-agent is running using `ps x`. If that is extended to `ps ax` for root, then the existing ssh-agent will still work.

**Comment by stucki** [comment]
Close here, use the pull-request #3891 instead.

**Comment by blueyed** [comment]
btw: you can convert issues to pull-requests: https://github.com/davidhalter/jedi/blob/master/CONTRIBUTING.md#changing-issues-to-pull-requests-github

**Comment by stucki** [comment]
Reopening until the pull request has been merged...

**Comment by mcornella** [comment]
This should be fixed now. Reopen if not.
