### ISSUE TITLE
virtualenvwrapper plugin fails on ubuntu with EQUALS option set

### ISSUE THREAD

**Issue by stuffy-the-dragon** [robbyrussell/oh-my-zsh#3893]
Refering to code from #2819.
On my system I got: <pre>"/etc/bash_completion.d/virtualenvwrapper:5: = not found" </pre> when the virtualenvwrapper plugin was loaded.

The problem is that /etc/bash_completion.d/virtualenvwrapper is bash script that is run by zsh with the EQUALS option set (default I think). 
When zsh hits the <pre>if [ "$USE_FULL" == "yes" ]; then</pre> line in /etc/bash_completion.d/virtualenvwrapper it tries to do '=' expansion as described in 14.7.3 [here](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Expansion)

I managed to fix the problem by adding <pre>unsetopt EQUALS</pre> to the top of the virtualenvwrapper.plugin.zsh file but there is probably a better way to do this.

**Comment by ncanceill** [comment]
CC: @mispy
