### ISSUE TITLE
Uninstaller leaves zsh as default shell

### ISSUE THREAD

**Issue by marceloboeira** [robbyrussell/oh-my-zsh#3894]
After uninstalling zsh I had to run:
`chsh -s /bin/bash`

http://osxdaily.com/2012/03/21/change-shell-mac-os-x/

**Comment by ncanceill** [comment]
Please see #3863. I am working on a wiki section dedicated to uninstalling.

**Comment by marceloboeira** [comment]
alright!

**Comment by ncanceill** [comment]
If it is alright could you please close this?

**Comment by marceloboeira** [comment]
@ncanceill of course!
