### ISSUE TITLE
source command completion

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#3895]
Using source [tab] does not see files inside the folder.
I think it is using /bin for suggestions

I need to use with ./ for the command completion

```bash
source [tab] <--- this return many commands
source ./[tab]
source ./setup-env.sh
```

**Comment by ncanceill** [comment]
This is the default Zsh behavior, and OMZ does not change it.

The [Zsh manual](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) entry for “`.` _file_” reads:
> If _file_ does not contain a slash, or if `PATH_DIRS` is set, the shell looks in the components of `$path` to find the directory containing _file_. Files in the current directory are not read unless ‘`.`’ appears somewhere in `$path`.

And the entry for “`source` _file_” reads:
> Same as ‘`.`’, except that the current directory is always searched and is always searched first, before directories in `$path`.

If you have an issue with that, I suggest you should reach out to zsh-users@zsh.org or to their [IRC channel](http://zsh.sourceforge.net/Arc/irc.html).

**Comment by mcornella** [comment]
Agree with the diagnostic. If you want to be able to source local files, put the local directory in the path:
`path+=.`. You can add this line to your zshrc file so you don't have to do it every time (note that this will also enable you to run commands located in your current working directory.

Please close this issue
