### ISSUE TITLE
vi-mode not setting a visual indicator of any kind

### ISSUE THREAD

**Issue by fardog** [robbyrussell/oh-my-zsh#3909]
With `vi-mode` added to my plugins and the `robbyrussell` theme, I'm not seeing any visual indication of the mode being set; the prompt looks identical whether in insert or command mode.

My [zshrc](https://github.com/fardog/dotfiles/blob/master/zshrc) can be found in my [dotfiles repo](https://github.com/fardog/dotfiles/), I've not done any additional configuration on it except for enabling that plugin. I wasn't able to find any docs that specify any other configuration being necessary.

For good measure, I tried the `sorin` theme but see exactly the same result; no visual difference. I can confirm the plugin is loaded as the `vi_mode_prompt_info` function it defines is present in my shell.

Thanks!

**Comment by apjanke** [comment]
Hmm. Your zshrc looks okay there.

Here's what the command-mode indicator should look like in the `robbyrussell` theme: three red carets on the right hand side. Works out of the box for me on OS X just by adding `vi-mode` to the plugins list.

![screen shot 2015-06-08 at 12 40 32 pm](https://cloud.githubusercontent.com/assets/2618447/8040079/bdcb9fca-0ddb-11e5-83d9-f71e045393af.png)

This is done by including `$(vi_mode_prompt_info)` in `$RPROMPT`. The `sorin` theme defines its own `$RPROMPT`, so the vi mode info is lost in that theme.

Could something else in your setup be setting `$RPROMPT`/`$RPS1`? Maybe that `~/.boxrc`? What's in your `$RPS1` when the mode indicator isn't displaying for you?

```
➜  ~  echo $RPS1
$(vi_mode_prompt_info)
➜  ~
```

**Comment by fardog** [comment]
Thanks @apjanke; I'm unsure what changed, but this started working for me recently across both my machines; I'm assuming it was some setting I had amiss, but unfortunately haven't been able to track down what it was.

I'm going to close this issue out, and will comment here if I figure out what the issue was.

Thanks again!

**Comment by habibalamin** [comment]
To anyone else who might run into this, I had the same issue on a fresh install. The plugin doesn't seem to enable the required option to get this working, but you need a `setopt prompt_subst` in your ZSH config somewhere.
