### ISSUE TITLE
Diagnostic dump function for bug reporting?

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#3915]
Hi, OMZ folks,

A lot of the issues we get are problem reports about OMZ on a particular user's machine, and since there's complex configuration for both the system and OMZ, we end up doing a lot of back and forth to elicit more info from the user. I think it would make bug reports easier if we had a function in OMZ that would just dump out all the relevant state and configuration for OMZ and ZSH, so the user could just submit that instead of answering a series of questions in comments.

I've put one together at [diagnostics.zsh](https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics.zsh) in my oh-my-zsh-custom tree. It dumps out information about the user's system and shells, zsh and environment state, OMZ installation, and grabs copies of all the relevant zsh configuration files.

Any interest in bringing this in to the main OMZ distribution, maybe as `lib/diagnostics.zsh`?

**Comment by mcornella** [comment]
:+1: I support this, but I would put it on `tools/diagnostics.zsh` and make it a function.

**Comment by KhasMek** [comment]
This sounds like a pretty fantastic idea. Adding it to the [Troubleshooting](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting) wiki page would be a good idea as well, IMO.

**Comment by apjanke** [comment]
@mcornella: Thanks!

My understanding is that `tools/` is for things intended to be run as commands or scripts. E.g. `check_for_upgrade.sh` is invoked as `zsh -f $ZSH/tools/check_for_upgrade.sh`, it in turn runs `upgrade.sh` as `env ZSH=$ZSH /bin/sh $ZSH/tools/upgrade.sh`, `theme_chooser.sh` is a shebang script, and so on. I think the diagnostic dump needs to be run as a function in the exact same `zsh` process as the user's trying to debug, in order to get the best view of its state. Parameters and shell options might not propagate to subshells.

What do you mean by "make it a function"? It's currently implemented as a function and some helper functions. Sourcing the file is only necessary to get the function definitions in to zsh, since most users don't have this as part of their zsh-custom definitions.

**Comment by apjanke** [comment]
@KhasMek: Thanks! Yeah, if we pull this in, my intention is to make this a normal part of the troubleshooting/bug-reporting process, and I'd add a description to Troubleshooting/Contributing (probably as part of a longer "How to Make Bug Reports" section like people are working on under #3770).

**Comment by KhasMek** [comment]
@apjanke That sounds perfect, and much needed in many cases.

**Comment by apjanke** [comment]
Okay, I think the `omz_diagnostic_dump` implementation is stable and defensive enough. I've added a PR #3940 to include it in the main OMZ distribution.
