### ISSUE TITLE
Opinions on a large wiki reformat before submission

### ISSUE THREAD

**Issue by KhasMek** [robbyrussell/oh-my-zsh#3928]
Hello there everyone,

First off, this isn't really an issue or anything like that, so I apologize for cluttering up this area more than it is. But, there aren't really any other areas on GH for project discussions.

 I had some time over the weekend and felt like giving the wiki pages some tlc with regards to formatting consistency and use of github flavored markdown support. However, before submitting such a large, bulk change to the wiki and risk doing something one of the maintainers/creators disapproves of, I was hoping to get some feedback.

The majority of what I did to the wiki is as follows:
 - add shell syntax highlighting where missing
 - switch zsh syntax highlighting to shell (some text editors don't highlight snippets marked as _zsh_)
 - cut lines at ~100-120 chars (for ease of editing)
 - convert *'s to -'s for non-numbered lists (cosmetic constancy)
 - use '_''s for italics across the wiki (cosmetic constancy)
 - use '**''s for bold across the wiki (cosmetic constancy)
 - use actual markdown language for images instead of html for images/tables
 - all files use unix line endings
 - remove unnecessary characters for github flavored markdown
 - use tables for aliases, functions and other commands for plugins/libs

You can view the gist containing the updates [here](https://gist.github.com/KhasMek/732374571c122a5d7a03).

Note: There have been a few modifications on the wiki over the weekend that I need to merge into my updates before final submission, but the gist is pretty much final(?).

**Comment by oshybystyi** [comment]
You said that you've cloned the wiki and did modifications. Maybe I am wrong but I don't think you will be able to push your modifications without access to repo, sorry to crush you like that :(

Seems like pretty good job though.

p.s. If any of the collaborators are reading this, I think it would be cool to add something like [gitter](http://gitter.im) to repo for better communication. But anyway I think for your question - creating issue is a better option.

**Comment by KhasMek** [comment]
I am fully aware I cannot push to the wiki branch unless I am an owner of that repo. If non owners were able to push to the wiki branch, we would also be able to open up pull requests on said branch, and I would have opened a PR apposed to opening up an issue to discuss the updates on. ;)

We (non owners of the omz repo) are able to manually edit the wiki pages through the edit tab though. So, if my modifications are liked and wanted to be brought in, I can manually update them that way (again, not via git or any non-web based method).

Thank you for your input on the update though, much appreciated.

**Comment by apjanke** [comment]
Looks promising imho, though it's a bit hard to determine the actual diffs from the gist.

Any chance you could post this as a wiki on GitHub so we could see how it renders, and view it side-by-side with the current wiki state, and read the changes as diffs to the underlying markup? You can't push to the main OMZ wiki, but you could post it by cloning and pushing to the Wiki part of your own oh-my-zsh fork, or a special-purpose wiki repo. (e.g. I have one at https://github.com/apjanke/omz-wiki/wiki; I added in a couple of your changes as an example.)  (and then if you really wanted to go crazy you could add folks as contributors to that (only advisable if you are doing a wiki-only repo))

It's too bad GitHub doesn't support forking the wiki repo too, or support viewing branches of the wiki repo in the web browser.

**Comment by KhasMek** [comment]
Most excellent idea @apjanke!

I have uploaded the repo [here](https://github.com/KhasMek/omz-wiki), added you, @mcornella and @ncanceill as contributors. Please let me know if there's anyone else I should add. You can view the updated wiki proposed [here](https://github.com/KhasMek/omz-wiki/wiki) (I'm wouldn't be surprised if there were some areas I've missed updating, but we can sort that out fairly quickly), and the overhaul commit can be found [here](https://github.com/KhasMek/omz-wiki/commit/da94830c93c9f32f428f3097e4d85e4bc4c858f2)

**Comment by apjanke** [comment]
Cool, looks good.

Looks like there are copies of all the wiki files in the main area of the repo. Maybe we should [remove them](https://github.com/KhasMek/omz-wiki/pull/1) to avoid ambiguity? Or did you want to keep the duplicates there for PRs or similar?

**Comment by KhasMek** [comment]
Removing the duplicates is fine with me, I initially pushed it there for an easy diff of my changes. However, all that can be done just as easily via CLI, so it's a tad redundant.

**Comment by apjanke** [comment]
Oh, I gotcha. I'm just viewing the diffs locally in a Git client, which I think is at least as useful. The changes are extensive enough that the Git diff display on GitHub mostly shows all the lines in the file being removed as one block, and then all the new lines as another block.

Here's my setup, which is working pretty well so far.

```shell
git clone https://github.com/khasmek/omz-wiki.wiki.git omz-wiki-khasmek
cd omz-wiki-khasmek
git remote add upstream https://github.com/robbyrussell/omz-wiki.wiki.git
# Assuming you've forked this omz-wiki yourself
git remote add me https://github.com/$my_github_username/omz-wiki.wiki.git
```

**Comment by apjanke** [comment]
I've merged in the upstream changes that happened since the fork.

**Comment by KhasMek** [comment]
Oh man, I feel terrible. I had just noticed that somehow my initial commit message was really butchered somehow and just re-pushed it seconds before getting the notification on your changes. Would you mind pulling and re-pushing it please? Otherwise I can do it in a bit.

**Comment by apjanke** [comment]
Not a problem. I've re-merged and pushed now. Do a pull to pick up the changes.

**Comment by apjanke** [comment]
Okay, I've had a chance to review your changes, and I think they're good. The table formatting for plugins and aliases is especially a nice improvement. Shell syntax highlighting is also nice, and I like the miscellaneous cosmetic cleanup to some of the wiki markup.

I'm not personally a fan of hard-wrapping the lines in paragraphs (cutting lines at 100 chars). If you work with them in a narrow editor window, they re-wrap poorly. And if you add or remove text in the middle of a line, then you have to reflow the paragraph or it ends up ragged. But to each their own.

![screen shot 2015-05-30 at 12 50 38 am](https://cloud.githubusercontent.com/assets/2618447/7895665/90286122-0668-11e5-89c7-d5d3fb4335cd.png)

I'd say go ahead and do the changes on the main wiki.

**Comment by KhasMek** [comment]
Thanks! That's a really good point regarding hard wrapping the lines. I'll go ahead and work on reverting those portions (and modify my sublime settings for the filetype like I should have in the first place) before moving it over to the main wiki.

**Comment by KhasMek** [comment]
Alright. I have removed the hard line wrapping in the latest revision, in addition to a few other small things I had noticed in going over it a couple more times (Plugins:git.md will show as one block change due to me switching the line endings from Windows to Unix). Give the latest revision a pull when you have a chance and I'll start updating the main wiki when I get your approval.
Thanks again for your time!

**Comment by apjanke** [comment]
👍 Looks good to me. I say go ahead and post it.

Thanks for your work on this!

**Comment by KhasMek** [comment]
Excellent! I've just finished posting the updated files in the main wiki, everything should be as it should. I will now close this "_issue_"

It was my pleasure, thanks for taking your time to review and help with it! Great talking with you! :)

**Comment by apjanke** [comment]
You too!

**Comment by oshybystyi** [comment]
I think it would be cool to create a separate page - like 'recommendations on wiki contribution' - that will help to unify style of future contributions.

**Comment by KhasMek** [comment]
I agree. In fact, I plan to write one out when I have some spare time with the guidelines I used for the overhaul. _Wiki Coding Style Guide_ or something along those lines.

**Comment by KhasMek** [comment]
Alright, I have added a markdown guide [here](https://github.com/robbyrussell/oh-my-zsh/wiki/Coding-Style-Guide:-Wiki). Hopefully it looks okay to everybody.

**Comment by apjanke** [comment]
👍

I made a couple edits for minor grammar things; nothing substantive.

**Comment by KhasMek** [comment]
Fantastic! Thanks for getting an extra pair of eyes on it and fixing those mistakes.
