### ISSUE TITLE
can not show username and computer name with zsh

### ISSUE THREAD

**Issue by zjhsdtc** [robbyrussell/oh-my-zsh#3930]
normally it should show username and computername at home or other places like this

![2015-05-26 11 37 49](https://cloud.githubusercontent.com/assets/3396524/7804907/45163cf0-039c-11e5-9844-ca4d4007581e.png)

but after i connect to the wifi in my office and my zsh went wrong there is no username and computername there it's really wired

![2015-05-26 11 38 21](https://cloud.githubusercontent.com/assets/3396524/7804913/5ba4895e-039c-11e5-9220-1fa92d589ed6.png)

so should i add some config in the .zshrc file or should i change some config with the wifi router?

**Comment by apjanke** [comment]
What theme are you using?

**Comment by zjhsdtc** [comment]
i use the "ys" zsh theme

**Comment by apjanke** [comment]
That's interesting. It looks like the entire line before the "in" is getting wiped out.

The `ys` theme uses a special `box_name()` function to determine the host name, and it's located in the `PROMPT` right before where your line seems to be getting reset. I wonder if that's related.

```shell
# The box_name function from ys
function box_name {
    [ -f ~/.box-name ] && cat ~/.box-name || echo $HOST
}
```

I wonder if your box-name file or something related is affecting this. Maybe there's a Windows-style `\r` in there that's causing the cursor to back up to the beginning of the line. Try this as a test: do `box_name | od -c`. What do you get as output? E.g. I get this.

```
# janke at eilonwy.local in ~ [13:20:29]
$ box_name | od -c
0000000    e   i   l   o   n   w   y   .   l   o   c   a   l  \n
0000016
```

And what operating system are you running? Are you ssh-ing in to other computers, or just using the shell locally?

**Comment by zjhsdtc** [comment]
thx!

i use osx 10.9.3 and i just use shell locally i'm not ssh-ing any other remote computers 

the output of box_name command

![2015-06-01 7 50 12](https://cloud.githubusercontent.com/assets/3396524/7912144/78701d32-0897-11e5-8e60-50b6b72adefa.png)

and zsh itself works fine now and i link to the same wifi in my office this is really wired  some times it goes perfect and sometimes it went wong...  really wired :sob:

**Comment by apjanke** [comment]
Okay. Grab that same output next time you connect to the office wifi and your prompt gets messed up. And get `box_name | od -x`, too. Maybe that connection is doing something to dynamically set your hostname and resulting in weird characters in it. Perhaps a locale issue, even?

**Comment by zjhsdtc** [comment]
ok thx you sooooo much!  but i don't think it's a locale issue maybe the router dynamically set my hostname or something like that thx again :)

**Comment by mcornella** [comment]
Please close this issue, and reopen it if you can reproduce the issue again.

**Comment by zjhsdtc** [comment]
ok :)
