### ISSUE TITLE
Sometimes is too slow

### ISSUE THREAD

**Issue by jiayouxjh** [robbyrussell/oh-my-zsh#3935]
My environment : 
mac os 10.10.3
zsh 5.0.7
tmux 1.9a
iTerm build2.1.1

when I use tmux with zsh after upgrade oh-my-zsh, sometimes is too slow especially cd a git dir or use ls command.

please let me know how to fix it ?

**Comment by apjanke** [comment]
Can you describe what exactly is too slow? Is it the prompt that's slow to display after issuing a command?

If you do `PROMPT='%n@%m %c%# '` to get a simpler prompt (with no git info) does the slowness go away?

**Comment by jiayouxjh** [comment]
My problem has been resolved, I upgrade the autojump with brew in my mac, and run 'autojump --purse' in the termenal. I think maybe autojump database is too huge to jump. And more, I remove some zsh plugin that not ofen use.
This issue can be closed.
