### ISSUE TITLE
[plugin] rails or rails3 for rails 3.2

### ISSUE THREAD

**Issue by abderrahmane-tj** [robbyrussell/oh-my-zsh#3936]
Hi,

Like the title says, should one use rails or `rails3` plugin for a rails 3.2 installation ?

the docs says  : `rails - rails 2.3 commands (mostly) for running scripts` and since there is a `rails3` plugin available. So I thought I should be using `rails3`.

but when I use it, OMZ states it has been deprecated in favor of a newly consolidated 'rails' plugin.

So the question is, logic should I follow ?

- the one that says use `rails3`
- or the one that says, don't use `rails3`

Thank you.

**Comment by Kriechi** [comment]
There should only be one rails plugin - is your OMZ up to date?

**Comment by mcornella** [comment]
I think he's referring to the deprecated statement you put there in #2240. FWIW, since that was 1.5 years ago we could make a PR to remove them. I assume nobody is still using those :smile: 
BTW, since you did such a good job, we only need a `git revert 1493d88e` for that.

@abderrahmane-tj use the `rails` plugin. The other 2 are just the remaining of what once were separate plugins.

**Comment by abderrahmane-tj** [comment]
Thanks a bunch ^^

**Comment by mcornella** [comment]
Thank you for bringing this old topic again :smile: 
Remember to close the issue please! (I can't do it)

**Comment by abderrahmane-tj** [comment]
Humm, I am not sure how to do that !

**Comment by mcornella** [comment]
The button to close is right beside the comment button:

![captura de pantalla de 2015-06-05 18 35 52](https://cloud.githubusercontent.com/assets/1441704/8010594/b9c2d988-0bb1-11e5-99e6-a9a16e5a9a19.png)

**Comment by abderrahmane-tj** [comment]
ah damn I need to go to sleep xD

**Comment by mcornella** [comment]
Hahaha (we all do! :wink:)

**Comment by abderrahmane-tj** [comment]
Actually my mistake, there is also this problem : https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins

Look at the section where there is rails and rails3, I was referring to the wiki not being up to date

![image](https://cloud.githubusercontent.com/assets/302837/8010665/f96eecbe-0ba9-11e5-914d-8bc447a6a173.png)

**Comment by mcornella** [comment]
Ooops, completely missed that (I told you, I also need to go to sleep haha). I'll change that in no time

**Comment by mcornella** [comment]
Done: https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#rails

**Comment by abderrahmane-tj** [comment]
Thanks a bunch ^^ (let's pretend this is the first time i posted this comment)

**Comment by mcornella** [comment]
Ok, I made PR #3955 to get rid of `rails3` and `rails4` plugins.
