### ISSUE TITLE
how can make ls command have rich colors when use agnoster.zsh-theme 

### ISSUE THREAD

**Issue by huguangju** [robbyrussell/oh-my-zsh#3938]
default, under agnoster.zsh-theme ```ls``` command no rich colors, how can i make it like this:
![image](https://cloud.githubusercontent.com/assets/6972433/7890071/24ca2a2e-0676-11e5-9561-01847b5b15b1.png)

> Mac OSX Yosemite

**Comment by KhasMek** [comment]
Do you have [this line](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template#L20) uncommented in your zshrc or being exported as true anywhere? Seems to be displaying rich colors fine for me with agnoster and other themes by default, unless I set that value to true. If that's not the case, maybe post your zshrc file in case there's something else in there that's causing the issue for you.

**Comment by huguangju** [comment]
Thank you for your reply. I did not modify other places, just changed here:
```
ZSH_THEME="agnoster"
```
then go to Preferences/Profiles / Colors,
import and select ```iterm2-colors-solarized/Solarized Dark.itermcolors``` theme

my iterm2
![image](https://cloud.githubusercontent.com/assets/6972433/7895289/39ddcb82-06b7-11e5-8f0b-067545d9f61f.png)

**Comment by diraol** [comment]
@huguangju, so can we close this issue?

**Comment by apjanke** [comment]
That last screen shot looks like it is using rich colors (see the lighter and darker grey for some items) but you just have it set to use a dull palette. What is the value of `$LSCOLORS` for you?

**Comment by huguangju** [comment]
thx. I didn't  set ```$LSCOLORS ```.

**Comment by eno812** [comment]
I know this is closed but I don't know how to set the $LSCOLORS

**Comment by abuzze** [comment]
I fixed that by installing the warhol plugin (https://github.com/unixorn/warhol.plugin.zsh) that set the color.

**Comment by eno812** [comment]
Thanks very much. Now my directories are a different colour which is heaps
easier to read :-)

**Comment by sel-fish** [comment]
I use [dircolors-solarized](https://github.com/seebi/dircolors-solarized).

```
git clone https://github.com/seebi/dircolors-solarized
eval `gdircolors -b dircolors-solarized/dircolors.ansi-light`
```

**Comment by zx1986** [comment]
Not work with my Prezto default theme :-p
