### ISSUE TITLE
dnf

### ISSUE THREAD

**Issue by sebastianbergmann** [robbyrussell/oh-my-zsh#3941]
Fedora 22 has been released and [replaces yum with dnf](https://fedoraproject.org/wiki/Changes/ReplaceYumWithDNF). Either the existing `yum` plugins needs to be updated to also support `dnf` or a new `dnf` plugin (based on the old `yum` one) needs to be created.

**Comment by KhasMek** [comment]
There are some PR's already open [here](https://github.com/robbyrussell/oh-my-zsh/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+dnf+is%3Atitle). Maybe you would test them and leave your recommendation on your preferred patch. Thanks!

**Comment by sebastianbergmann** [comment]
Done. For some reason the GitHub search I did for "dnf" did you yield these issues.
