### ISSUE TITLE
brew plugin: brew upgrade require --all

### ISSUE THREAD

**Issue by olbura** [robbyrussell/oh-my-zsh#3949]
`brew upgrade` will [require](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-update-my-local-packages) soon `--all`

> Warning: brew upgrade with no arguments will change behaviour soon!
> It currently upgrades all formula but this will soon change to require '--all'.
> Please update any workflows, documentation and scripts!

Should be the alias definition of the brew.plugin updated to?
`alias bubu="brew update && brew upgrade --all && brew cleanup"`

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh#L2

**Comment by KhasMek** [comment]
Hello,
Patch #3816 is the patch to fix this that will be merged.

**Comment by mcornella** [comment]
This will be fixed when #3809, which will be imminent. I'm adding it to #3651.

**Comment by mcornella** [comment]
Forget what I said, the homebrew team backtracked on the `--all` parameter decision: https://github.com/Homebrew/homebrew/commit/a45a34db0b2c66f626f3724ae9a52563b4aa94b5
