### ISSUE TITLE
ggpull and ggpush are no longer aliases?

### ISSUE THREAD

**Issue by kedarmhaswade** [robbyrussell/oh-my-zsh#3956]
I am running:
> commit 4224c2a1af2a1b99c14ef81012af321c39856cf5
> Merge: 51e366e 8cf04ed

and it appears that this version has removed those useful aliases, although I can't say for sure. Am I the only one missing these aliases with today's (5/6/2015) update?

**Comment by mcornella** [comment]
They are replaced by the ggl and ggp functions respectively.

**Comment by kedarmhaswade** [comment]
I see. Thanks!
