### ISSUE TITLE
Not working with rspec excluding tag option

### ISSUE THREAD

**Issue by stereodenis** [robbyrussell/oh-my-zsh#3957]
```
rspec -t ~slow
zsh: no such user or named directory: slow
```

**Comment by mcornella** [comment]
In zsh the `~name` syntax is expanded to `/folder/of/name/user`. You can bypass this behavior by adding `noglob` at the beginning of the command: `noglob rspec...`.
You can also alias the rspec command so that you don't have to put write that every time: `alias rspec='noglob rspec '`.

**Comment by stereodenis** [comment]
@mcornella :+1:
