### ISSUE TITLE
.oh-my-zsh/plugins/git/git.plugin.zsh:local:2: not valid in this context: git_cmd^M

### ISSUE THREAD

**Issue by shiduanguang** [robbyrussell/oh-my-zsh#3963]
After the latest upgrade_oh_my_zsh, I got this error and the git plugin didn't work.

**Comment by apjanke** [comment]
Can you be more specific about the errors you're seeing? When do you see that error message?

As an experiment, delete line 2 of `plugins/git/git.plugin.zsh`, where it says `local git_cmd`. Does that fix it?

**Comment by apjanke** [comment]
Also, check to make sure you don't have a DOS-mode file for `plugins/git/git.plugin.zsh` for some reason, if you're on a non-DOS system. I think `^M` is `\r`, and I can reproduce this error by running some bogus DOS-mode text on my OS X 10.9 system.

```
$ eval $(printf 'local git_cmd\r')
local: not valid in this context: git_cmd^M
```

**Comment by razor-x** [comment]
Not sure if this is related, but I just updated and now whenever I open a new shell I get `git_cmd=git` and then my normal prompt, e.g.,

```
git_cmd=git
$
```

**Comment by apjanke** [comment]
It's related; that top-level `local` was added in [a recent update to the `git` plugin](https://github.com/robbyrussell/oh-my-zsh/commit/5b75cc7880de1931a0507800d90eb77ed659fa46). There's an outstanding PR #3962 to fix it.

**Comment by shiduanguang** [comment]
This problem is solved now, the reason is that I set my git line endings incorrectly.
On Mac OS X 10.10.3:
```shell
$ git reset --hard cffeefde903149df8ef48224fedf5205cb2497c3
$ git config --global core.autocrlf input
$ git pull
```
