### ISSUE TITLE
Put the foreground color of the prompt segment as "default"

### ISSUE THREAD

**Issue by fniessen** [robbyrussell/oh-my-zsh#3968]
The prompt segment should be better in "default" foreground color than in "black": much more readable (at least, in my terminal emulator). And that seems more coherent.

Here is a diff:

    diff --git a/themes/agnoster.zsh-theme b/themes/agnoster.zsh-theme
    index 8c7be6e..c07fcca 100644
    --- a/themes/agnoster.zsh-theme
    +++ b/themes/agnoster.zsh-theme
    @@ -139,7 +139,7 @@ prompt_hg() {
     
     # Dir: current working directory
     prompt_dir() {
    -  prompt_segment blue black '%~'
    +  prompt_segment blue default '%~'
     }
     
     # Virtualenv: current working virtualenv

**Comment by apjanke** [comment]
That readability really depends on what the default color and the rest of the color scheme are, though, doesn't it? That black foreground was chosen to contrast against the light blue background. If the user's running a "dark" theme, their default foreground text is going to be light, and it will contrast poorly with the blue background.

Here's what this change looks like on a terminal using Solarized Dark, which is my default color scheme. Not good, IMHO. I have a hard time reading that.

![screen shot 2015-06-11 at 8 52 02 am](https://cloud.githubusercontent.com/assets/2618447/8107476/719cfb92-1017-11e5-8b24-105a78a3009f.png)

**Comment by fniessen** [comment]
Not good, right.  Then, there is no general solution?

Closing this.
