### ISSUE TITLE
What happened with ggpush, gap and others?

### ISSUE THREAD

**Issue by opsidao** [robbyrussell/oh-my-zsh#3972]
I can see [here](https://github.com/robbyrussell/oh-my-zsh/commit/5b75cc7880de1931a0507800d90eb77ed659fa46#diff-4ad2773a26526d0e361e66139c283099L145) a lot of aliases been removed... this breaks my workflow and I guess others too, could you explain the rationale behind those removals?

**Comment by MarioAraque** [comment]
+1

**Comment by NuclearCookie** [comment]
+1

**Comment by badmanski** [comment]
+1

**Comment by arroadie** [comment]
+1

**Comment by wess** [comment]
+1

**Comment by michaelghinrichs** [comment]
+11

**Comment by Tom-Sesselmann** [comment]
+1

**Comment by zachgraves** [comment]
+1

**Comment by kirillplatonov** [comment]
+1

**Comment by kirillplatonov** [comment]
I forked and reverted this commit as temp solution. Maybe it will be helpful for you:
```
cd ~/.oh-my-zsh
git remote add git_fix git@github.com:kirillplatonov/oh-my-zsh.git
git fetch --all
git checkout git_fix/master
```

**Comment by ncanceill** [comment]
Hi guys, and thanks for voicing your concerns.

I am the new maintainer of the Git plugin, and the one who (with help from many others contributors) put together this big update.

I have posted an answer in the PR thread, please [check it out](https://github.com/robbyrussell/oh-my-zsh/pull/2790#issuecomment-110689393) and discuss possible solutions over there.

In order to handle this, would you all be so kind as to make a list of all the aliases that you are missing. We know of `gap` (it was conflicting with a program) and the ones starting with `gg` (they were renamed), are there any other?

Once this is all dealt with, we can discuss how to improve the updating process so this does not happen again.

**Comment by opsidao** [comment]
Hey @ncanceill, 

I guess I will have to add that gap alias to my own aliases, besides that, if you bring the gg* bunch back I will be more than happy.

Thanks a lot!

**Comment by doomspork** [comment]
I may just be missing something but it seems that the functionality of `ggpush` changed when the alias was switched to `ggp`.  For example, `ggpush --force` has worked for me but now I _always_ get an error with `ggp --force`.  However, `git push origin a-branch-name --force` works just fine:

```shell
➜  SampleApp git:(sample-branch) ✗ ggp --force
To git@github.com:doomspork/SampleApp.git
 ! [rejected]        sample-branch -> sample-branch (non-fast-forward)
error: failed to push some refs to 'git@github.com:doomspork/SampleApp.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

➜  SampleApp git:(sample-branch) ✗ git push origin sample-branch --force
Counting objects: 13, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (13/13), 1.49 KiB | 0 bytes/s, done.
Total 13 (delta 9), reused 0 (delta 0)
To git@github.com:doomspork/SampleApp.git
 + 976defc...4ec7719 sample-branch -> sample-branch (forced update)
```

**Comment by ncanceill** [comment]
@doomspork this may be related to what @heliostatic [reported](https://github.com/robbyrussell/oh-my-zsh/pull/2790#issuecomment-110892169), can you check if the `current_branch` function works properly for you?

**Comment by iammichiel** [comment]
+1.

**Comment by ncanceill** [comment]
There was a long debate on the form the `gg*` aliases should take, and every OMZ user (actually, every interested human being, really) has been welcome to voice their suggestions and concerns. Please keep in mind that OMZ is an open-source, community-driven project: together, we all make it and improve it. My strongest advice is: get involved!

This being said, the Git plugin update only shows that our update process is not suiting many users, and I will be working hard with all contributors to improve it. We already have many ideas, like a safe aliasing framework, an official mailing list to announce coming changes and deprecations, clear contributing guidelines, and an improved wiki... coming soon once the Git plugin issues are solved.

Once again, all suggestions are welcome!

Also, please notify me ASAP of anything else in the Git plugin that may be broken or missing! I am making a list [here](https://github.com/robbyrussell/oh-my-zsh/pull/2790#issuecomment-110689393).

**Comment by ncanceill** [comment]
Everybody PLEASE report any trouble or missing alias to #3990, thank you!

**Comment by ncanceill** [comment]
@doomspork actually you issue is unrelated to all the rest, it is a side-effect of the rewrite from aliases to functions. I will work on a fix and add this to #3990.

**Comment by doomspork** [comment]
@ncanceill thanks for the heads up.  I really appreciate all the hard work you guys are doing :+1:

**Comment by ncanceill** [comment]
@doomspork thanks, really appreciate your support, also for forced push you now have [`ggf`](https://github.com/robbyrussell/oh-my-zsh/blob/5b75cc7880de1931a0507800d90eb77ed659fa46/plugins/git/git.plugin.zsh#L97-L101)

**Comment by doomspork** [comment]
@ncanceill That's awesome and very useful to me, thanks! :tada:

**Comment by blueyed** [comment]
> also for forced push you now have `ggf`

I recommend removing this alias, and allow for `ggp`/`ggpush` to accept/handle the `-f` (given its potentially destructive outcome).

**Comment by ncanceill** [comment]
@blueyed we know how you feel about destructive aliases, but given how much love this one is getting I do not think it should be removed. You can still `unalias ggf` in your `.zshrc` after sourcing OMZ if you really do not want it.

I will work on allowing options through `ggp` and `ggl` anyway.

**Comment by blueyed** [comment]
> `ggf` … given how much love this one is getting

I am not convinced this is the case.
And I just want to prevent someone accidentally force-pushing master because of some typo etc.
As for unaliasing this myself, I am using a fairly different `git.plugin.zsh` file myself anyway - so it's not a problem for myself.

**Comment by ncanceill** [comment]
Anyone want to weigh in on this debate?

**Comment by doomspork** [comment]
:+1: for `ggf`.  

The `f` and `p` are not near one another on the keyboard, no one should "accidentally" type `ggf` when they mean `ggp`, silly to suggest so.  If people are using aliases they don't understand then that is a problem the individual should resolve themselves.

**Comment by blueyed** [comment]
@doomspork 
It's not mainly about typing `p` instead of `f` (which are only two keys apart with Dvorak layout btw), but having some short alias for something that might happily cause problems.
I really think that `ggp -f` is good enough.

**Comment by zachgraves** [comment]
I agree with @blueyed on `ggp -f`

**Comment by orendon** [comment]
good to know, I wasn't aware of this change. 

keep the good work @ncanceill

**Comment by iammichiel** [comment]
And I agree on the `-f` option. Should not be part of the alias.

**Comment by ncanceill** [comment]
OK what would you guys think about an option, properly documented in the plugin's ReadMe and wiki, that would either enable or disable potentially destructive aliases like `ggf`?

For those who agree, what should the default be?

**Comment by blueyed** [comment]
> OK what would you guys think about an option, properly documented in the plugin's ReadMe and wiki, that would either enable or disable potentially destructive aliases like `ggf`

I think it's not worth the effort, especially for aliases that only add `-f`.
Instead of then enabling this option (which should be off by default), you could just add your own alias for it.  Maybe the wiki could just list some "recommended" aliases like this.
