### ISSUE TITLE
'gap' alias removed (accidentely) from git plugin

### ISSUE THREAD

**Issue by groolot** [robbyrussell/oh-my-zsh#3982]
the commit 5b75cc7880de1931a0507800d90eb77ed659fa46 removes `gap` alias on line 77

**Comment by doomspork** [comment]
See discussion here about `gg*` and `gap`: https://github.com/robbyrussell/oh-my-zsh/pull/2790#issuecomment-110689393

**Comment by ncanceill** [comment]
This was no accident! it was murder! cold-blooded murder I tell you!!!

More seriously though, `gap` is a program — see #3682.

Until we build a safe aliasing system for OMZ, you can set the `gap` alias in your personal config, or you are welcome to suggest a new alias for `git add --patch`.

**Comment by ncanceill** [comment]
Also please close #3983.
