### ISSUE TITLE
Strange `ggpnp` behaviour

### ISSUE THREAD

**Issue by shark0der** [robbyrussell/oh-my-zsh#3991]
As discussed with @ncanceill [in the comments](https://github.com/robbyrussell/oh-my-zsh/commit/5b75cc7880de1931a0507800d90eb77ed659fa46#commitcomment-11623364), `ggpnp` has a weird behaviour when being launched for the first time in a zsh session on a repository.
The first part runs (`ggl`) runs well but the second part (`ggp`) fails with a "fatal: remote part of refspec is not a valid name in" error. If I run `ggl` or `ggp` alone, then I run `ggpnp` - everything works fine.

See the comment thread in the code for more details and attempts to debug the issue.

**Comment by ncanceill** [comment]
OK I think I figured this out, would you be so kind as to fetch my fork and cherry-pick f513999 to see if it fixes your issue?

**Comment by shark0der** [comment]
It doesn't seems to fix the issue. Here's screenshot so you can confirm I did the cherry-pick correctly: http://i.imgur.com/qlYuVZS.png

**Comment by ncanceill** [comment]
I trust you can do a cherry-pick ;-)

Did you properly open a new shell after performing the cherry-pick?

Could you also cherry-pick 6c29041 and try again? this was proven to be related to issues with `current_branch`, which may in turn cause problems with `gg*` functions.

**Comment by shark0der** [comment]
Yes, I did properly open the new shell, the second screenshot confirms this: I ran `which ggl` and I've seen the keyword `local` in the code.

**Comment by ncanceill** [comment]
OK thanks for confirming. Ca

**Comment by shark0der** [comment]
Still failing: http://i.imgur.com/Di9D89i.png

**Comment by ncanceill** [comment]
OK let me look deeper into it and I will get back to you.

**Comment by ncanceill** [comment]
OK, I finally figured it out: I am a moron!

In `ggpnp` the two functions `ggl` and `ggp` are called with `"$1"`, which counts for an argument as far as `$#` is concerned, even when `$1` is empty.

I will fix this at the same time I fix the issue of passing options to `ggl` and `ggp`.

**Comment by shark0der** [comment]
Well, since you figured out what the problem is, you just proved you're not a moron :+1:
Thanks for taking your time to fix this!

**Comment by ncanceill** [comment]
OK this should now be fixed in #3990.

**Comment by shark0der** [comment]
Confirmed  - works :)
You're awesome!
