### ISSUE TITLE
_git:58: _git_commands: function definition file not found

### ISSUE THREAD

**Issue by Douglas-Su** [robbyrussell/oh-my-zsh#3996]
When I use `tab` key to auto complete git's subcommand, `_git:58: _git_commands: function definition file not found` is reported. 

I tried `status`, `push`, `commit` commands but all failed.

system: Debian 8.
git version: 2.1.4

**Comment by mcornella** [comment]
What plugins do you load? Do `echo $plugins` and post the output.

**Comment by Douglas-Su** [comment]
@mcornella, only `git` is loaded.

**Comment by mcornella** [comment]
Try deleting the completion cache files: `rm ~/.zcompdump*` and restarting the terminal. 
If that doesn't do it, please post contents of the file zsh-debug.log after running the following:
```
{ echo $fpath; echo; which -a _git; echo; which -a _git_commands } > zsh-debug.log
```

**Comment by Douglas-Su** [comment]
@mcornella 
I tried deleting `~/.zcompdump*`, it didn't work. 

After running the commands you gave me, it dumps:

~~~
_git () {
	# undefined
	builtin autoload -XUz
}

_git_commands () {
	# undefined
	builtin autoload -XUz
}
~~~

**Comment by apjanke** [comment]
@Douglas-Su Did you make sure to log out and log back in after deleting the zcompdump files? (Git completion is working for me, so this smells like a local completion/zcompdump issue to me, too.)

That's a little odd. The `_git_commands` function, from what I can tell, is supplied by `zsh` itself as part of its user-contributed functions [and not normally marked for autoloading](http://www.zsh.org/mla/users/2012/msg00734.html). Those "undefined" outputs look like Zsh's git completion is not getting loaded as normal.

Would you mind giving us a full diagnostic dump to help debug this? Download and `source` [this `diagnostics.zsh` file], run `omz_diagnostic_dump`, and post the output as a gist you can link us to. 

... and hey, wait a minute. Is `gitfast` intentionally masking Zsh's own supplied `_git` completion function? I know you don't have it loaded, but that's interesting.

```
[@ in ~/.oh-my-zsh on ⇄ master]
$ for f in $fpath; [[ -e $f/_git ]] && echo $f
/usr/share/zsh/5.0.2/functions
[@ in ~/.oh-my-zsh on ⇄ master]
$ find . -name _git
./plugins/gitfast/_git
```

Wonder if we're seeing some unintentional interaction between native Zsh git support and OMZ git support.

**Comment by Douglas-Su** [comment]
This problem has gone after I upgraded `oh-my-zsh`. Maybe, it just a occasional error, and anyhow it is fine now.

**Comment by apjanke** [comment]
Great.

Could you close this issue? Only you and the repo owner have permissions to close it.

**Comment by Douglas-Su** [comment]
OK. no problem

**Comment by icfantv** [comment]
Just a note for others, clearing the `~/.zcompdump*` files worked for me on my MBP.

**Comment by pomkine** [comment]
Had the same error. Clearing ```~/.zcompdump*``` helped

**Comment by Falkor** [comment]
Same error. Clearing `~/.zcompdump*` **didn't** helped ;(

```
$> echo $plugins                                                                                                         
git-flow git-extras git-remote-branch hub rvm ruby brew brew-cask colored-man-page cp extract gem marked2 osx rake taskwarrior falkor zsh-completions
```

**Comment by kunalpowar** [comment]
Yep. Same issue and solved by clearing `~/.zcompdump*`.

**Comment by kliu2333** [comment]
I also encounter this issue for a month. Now it is solved by clearing ~/.zcompdump* and restarting a terminal.

**Comment by cyrilleverrier** [comment]
Note that you may have the issue if you have multiple `git` in your zshrc plugin list.
Check with `echo $plugins`

**Comment by amitach** [comment]
The $plugins just gave one git. 
Clearing ~/.zcompdump* fixed the issue. You need to restart the terminal. Didn't work without it

**Comment by lyda** [comment]
Had this problem.  Fixed like so:

```sh
rm ~/.zcompdump
exec zsh -l
```

**Comment by sarnobat** [comment]
Perfect, lyda's solution worked for me too. Repeating what he wrote so people don't have to scroll up past my post.

```
rm ~/.zcompdump
exec zsh -l
```

**Comment by kostaz** [comment]
For me it helped somehow just to close and reopen "terminator" terminal.

**Comment by yutongz** [comment]
rm ~/.zcompdump helps, thanks!

**Comment by duduscript** [comment]
rm ~/.zcompdump
exec zsh -l

it works for me

**Comment by aflashyrhetoric** [comment]
Removing the zcompdump also fixed another issue I was having with an autocomplete issue. Thanks!

**Comment by ungrim97** [comment]
Hi,
I am seeing this same error and `rm ~/.zcompdump*` is not resolving. I have also tried resintalling both zsh and OMZ

Any help would be greatly appreciated as this is driving me nuts

Cheers

**Comment by Falkor** [comment]
Same for me...

**Comment by ungrim97** [comment]
@d0u9 can this ticket be reopened?

**Comment by samkhal** [comment]
Bashed my head against this for a bit before realizing that I had multiple `zcompdump` files: `~/.zcompdump`, `~/.antigen/.zcompdump`, `~/.antigen/.zcompdump.zwc`. Deleting _all_ of them fixed the issue for me. I recommend doing a `locate zcompdump` especially if you're running other managers for zsh.

**Comment by ungrim97** [comment]
@samkhal You're a star. That appeared to be exactly my issue. Thank you

**Comment by chlorochrule** [comment]
I am using zplung(https://github.com/zplug/zplug) and happened same problem. `rm ~/.zplug/zcompdump` resolve for me.

**Comment by erdong** [comment]
i have this problem 。commit is 6da59ff046d7a81483345d0e16333a69eb96ccc6 。CentOS Linux release 7.3.1611 (Core)

1、
rm ~/.zcompdump
2、
logout and login 

then  it work . git is ok.
