### ISSUE TITLE
__vte_urlencode errors while browsing directory ending in exclamation

### ISSUE THREAD

**Issue by danielkza** [robbyrussell/oh-my-zsh#3998]
```shell
⇒  ~ git:master ✗ cd /data/Music/Booka\ Shade/2010\ -\ More\!
__vte_urlencode:[:9: too many arguments                                 
__vte_urlencode:[:5: too many arguments
```

oh-my-zsh rev 140034605edd0, Fedora 22 x86_64 in GNOME terminal.

**Comment by mcornella** [comment]
I can reproduce  this in Debian with gnome-terminal as well. This looks like the culprit is  `echo $precmd_functions` and confirm you have `__vte_urlencode` in there. If it is, then you're probably sourcing the `/etc/profile.d/vte.sh` file, which sets up this `__vte_urlencode` function so as to [enable gnome-terminal to open a new tab on the current directory](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1132700):

```sh
__vte_urlencode () {
	(
		LC_ALL=C 
		str="$1" 
		while [ -n "$str" ]
		do
			safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}" 
			printf "%s" "$safe"
			str="${str#"$safe"}" 
			if [ -n "$str" ]
			then
				printf "%%%02X" "'$str"
				str="${str#?}" 
			fi
		done
	)
}
```

In any case, this is a bug in gnome-vte, so you should add it in their project bugtracker: https://bugzilla.gnome.org/page.cgi?id=browse.html&product=vte

**Comment by danielkza** [comment]
You're right, initially it seemed to be `__vte_urlencode` was the one being fed wrong arguments, but it is actually `test` *inside* that function. I'll see if I can set up a fixed version as a workaround if anyone is interested.

**Comment by mcornella** [comment]
Trying the version from [the github mirror](https://github.com/GNOME/vte/blob/master/src/vte.sh) I only get `__vte_urlencode:[:5: too many arguments`, so there's something fixed in there.

**Comment by danielkza** [comment]
It seems `[ -n '!' ]` works in Bash but not ZSH. I'm starting to think this might be a ZSH bug, or at least a misunderstanding from whoever wrote the script about what is compatible with a POSIX shell. I actually don't know the answer myself. I believe using `[[ ]]` instead should work though, since the script only targets Bash and ZSH.

**Comment by mcornella** [comment]
Yes, that solves the problem. I don't know whose fault it is though.

**Comment by danielkza** [comment]
I [reported it to Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1231552) as a VTE bug, but it still seems like weird behavior from ZSH to me. Having to guess whether a string you test is an exclamation or not seems iffy. But since it would be unwise from VTE to rely on any particular ZSH versions, it should be fixed there anyway.

**Comment by mcornella** [comment]
FWIW, this is [documented behavior](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Overview):
  
> The ‘!’ can be escaped with ‘\’ or can be enclosed between a pair of single quotes (’’) to suppress its special meaning. Double quotes will not work for this.

But I fail to understand why `[[` works correctly. Anyway, now it's their business dealing with that.

**Comment by danielkza** [comment]
I don't think this is the case. The exclamation is not parsed by the shell for expansion, since it is only produced *by the expansions themselves*. For that to happen you'd need to feed the string through `eval`, but it isn't the case. For example, the following works correctly for me on ZSH 5.0.7:

```shell
asd='!'
echo "$asd"
```

It seems to me it is actually a bug on how the test command parses it's arguments.

**Comment by mcornella** [comment]
You're absolutely right again. If I try with the binary `[` it works ok. So the command line is actually parsed correctly:
```
$ asd='!'
$ [ -n "$asd" ]                                                            
[: too many arguments
$ /usr/bin/\[ -n "$asd" ] && echo ok                                       
ok
```
