### ISSUE TITLE
.oh-my-zsh/lib/misc.zsh:3: parse error near `then'

### ISSUE THREAD

**Issue by xingheng** [robbyrussell/oh-my-zsh#4008]
I just install oh-my-zsh in my new mac and got the following warning, it occurs when I installed it at the first time **and every time when starting a new shell session**.

/Users/apple/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'
➜  ~  zsh --version
zsh 5.0.5 (x86_64-apple-darwin14.0)

Please check it, thanks!

**Comment by ncanceill** [comment]
This is reported in #3986 and fixed in #4002, thanks!

**Comment by xingheng** [comment]
:) Thanks for your quick reply!

I just saw the misc.zsh file before and didn't recognized that syntax error, stupid me~
