### ISSUE TITLE
 parse error near `then' after update

### ISSUE THREAD

**Issue by Javix** [robbyrussell/oh-my-zsh#4018]
Just updated to the latest version by taping in 'y' in my terminal and got the below error:
```
ast-forwarded master to 8921902388bf357ad0ab6ec198f4ba1f14b94fe4.

/Users/XXXXX/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'
```
It reappears when quitting and reopening the terminal.

OS: OS X 10.10.3

Regards

**Comment by Kevin-Lee** [comment]
I got the same issue and the pull request I've just created fixes it.

**Comment by Javix** [comment]
Perfect, waiting forward to get the merge.

**Comment by Javix** [comment]
Seems like the same has already been reported: https://github.com/robbyrussell/oh-my-zsh/issues/4037

**Comment by oshybystyi** [comment]
yeah, @Javix can you close this, #4002 is in the master already...

**Comment by Javix** [comment]
Great, no problem.
