### ISSUE TITLE
parse error near `then' after update

### ISSUE THREAD

**Issue by TonyWael** [robbyrussell/oh-my-zsh#4020]
Hey guys, 

first of all I would like to thank you for Oh-my-zsh it is awesome. 

I'm getting this error " /home/tony/.oh-my-zsh/lib/misc.zsh:3  " after i update to the newest version. 

Cheers

**Comment by ncanceill** [comment]
Yes, sorry, a typo was merged by mistake.

This will be fixed by #4002.
