### ISSUE TITLE
Parse error in lib/misc.zsh

### ISSUE THREAD

**Issue by arnlaugsson** [robbyrussell/oh-my-zsh#4023]
## Description
After updating Oh-My-ZSH this morning, I got the following error when trying to open a new shell:

```shell
Last login: Mon Jun 15 10:09:19 on ttys002
/Users/skuli/.dotfiles/lib/misc.zsh:3: parse error near `then'
```

By opening the file mentioned in the parse error, I noticed a space was missing.

Culprit: https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/misc.zsh#L3

## Problem
```shell
for d in $fpath; do
	if [[ -e "$d/url-quote-magic"]]; then
		autoload -U url-quote-magic
		zle -N self-insert url-quote-magic
	fi
done
```

## Fix
```shell
for d in $fpath; do
	if [[ -e "$d/url-quote-magic" ]]; then
		autoload -U url-quote-magic
		zle -N self-insert url-quote-magic
	fi
done
```

**Comment by Kevin-Lee** [comment]
#4002

**Comment by arnlaugsson** [comment]
And this is one of multiple duplicates. Closing.
