### ISSUE TITLE
New dependency (realpath) breaks when switching to a directory present with a virtualenv

### ISSUE THREAD

**Issue by santiagobasulto** [robbyrussell/oh-my-zsh#4030]
```bash
workon_cwd:6: command not found: realpath
The program «realpath» is not installed. You can install it typing:
sudo apt-get install realpath
```

Whenever I switch to something like: `~/my-python-project` and I have a virtualenv named `my-python-project`. It's like it gets into an infinite loop. I had to kill it and then install realpath. And now the error is gone, but it's not automatically activating the virtualenv:

![http://i.imgur.com/sbVRM4e.png](http://i.imgur.com/sbVRM4e.png)

**Comment by tklovett** [comment]
Please merge :)

**Comment by joeghodsi** [comment]
+1

**Comment by IanLee1521** [comment]
+1 on ``zsh 5.0.2 (x86_64-pc-linux-gnu)``

**Comment by PeerXu** [comment]
+1 zsh 5.0.5 (x86_64-apple-darwin14.0)

**Comment by ncanceill** [comment]
Hi, can you guys checkout #4025 and check if it solves your issue?

**Comment by crucialfelix** [comment]
Same issue on OS X: no realpath

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh#L42

quick fix is to install a realpath for OS X:
http://blog.ivansiu.com/blog/2014/05/01/os-x-get-full-path-of-file-using-realpath/

**Comment by wmayner** [comment]
@ncanceill Applying #4025 does seem to fix it.

**Comment by alicetragedy** [comment]
+1
this was super annoying, but the quick fix @crucialfelix posted worked for me.

**Comment by IanLee1521** [comment]
Agreed #4025 fixes this on `zsh 5.0.2 (x86_64-pc-linux-gnu)` on Linux Mint 17.1. I agree with the comment though that a better solution would (possibly) be to use `readlink -f ...`, however since that's not installed by default on OSX apparently, perhaps a custom `realpath` function should be defined in that script rather than relying on either `realpath` (the package) or `readlink -f`.

**Comment by Surgo** [comment]
+1

**Comment by crucialfelix** [comment]
crafty

**Comment by slackorama** [comment]
This was really annoying to hunt down after I upgraded yesterday.

**Comment by Gaffney** [comment]
+1

**Comment by philipz** [comment]
+1

**Comment by skhaz** [comment]
I've the same issue here

**Comment by drucci** [comment]
Another quick-fix;  If you have coreutils installed, it comes with `grealpath` which you can symlink to `realpath`. 

```
brew install coreutils
ln -s /usr/local/bin/grealpath /usr/local/bin/realpath
```

**Comment by apjanke** [comment]
None of this `realpath` or `readlink` stuff seems necessary. `zsh` has a native `:A` parameter expansion modifier that does the same thing, without relying on external programs.

I've put in a PR #4106 that removes the `realpath` dependency. If some of you having this issue could test it out, that would be great.

**Comment by oryband** [comment]
![](http://www.quickmeme.com/img/54/54504eb08de8bea51ecf9ccc75e21a07767a171264fdee210e3d22ad8cd334c9.jpg)

**Comment by guillaumevincent** [comment]
+1 annoying bug

**Comment by jononomo** [comment]
+1

**Comment by guillaumevincent** [comment]
the solution breaks virtualenvwrapper on mac os x

**Comment by singingwolfboy** [comment]
@guillaumevincent Please elaborate. *How* is it broken?

**Comment by oryband** [comment]
using arch here, virtualenvwrapper doesn't auto-activate virtualenvs when `cd`ing into directories who have the same virtualenv's name

**Comment by guillaumevincent** [comment]
@singingwolfboy +1 @oryband : virtualenvwrapper doesn't activate virtualenvs **automatically** when cd or jump in directory with the same virtualenv's name

**Comment by apjanke** [comment]
I believe that's the issue #4110. It was a regression caused by #3918. There's a PR #4122 open to fix it. Please give #4122 a try and +1 it if it fixes this issue for you.
