### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by levisbakalinsky** [robbyrussell/oh-my-zsh#4034]
Upgraded last night to the latest version, and received the following error:

/Users/levisbakalinsky/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'

zsh 5.0.8 (x86_64-apple-darwin14.3.0)

**Comment by alvincrespo** [comment]
:+1: Getting this as well

**Comment by oshybystyi** [comment]
the [pr for this](https://github.com/robbyrussell/oh-my-zsh/pull/4002), it will be merged soon.

**Comment by nick4fake** [comment]
Same here.

why there is no "stable" branch?

**Comment by ncanceill** [comment]
This was already reported multiple times and the fix should be merged ASAP.

@nick4fake currently our upgrade process is very poor but we will be working on it in the near future.

**Comment by tehmaspc** [comment]
duplicate of https://github.com/robbyrussell/oh-my-zsh/pull/4002

please close.

**Comment by ncanceill** [comment]
This should be fixed now, @levisbakalinsky please confirm and close.
