### ISSUE TITLE
`.oh-my-zsh/lib/misc.zsh:3: parse error near `then'` after update

### ISSUE THREAD

**Issue by leee** [robbyrussell/oh-my-zsh#4037]
Not a critical issue.

Upon updating oh-my-zsh, I get the pretty Hooray! message, with the appropriate twitter and swag links. Immediately thereafter, I get hit with a:

`/path/to/user/.oh-my-zsh/lib/misc.zsh:3: parse error near 'then'`

Here's that file - I don't see any immediate errors.

```
## Load smart urls if available
for d in $fpath; do
	if [[ -e "$d/url-quote-magic"]]; then
		autoload -U url-quote-magic
		zle -N self-insert url-quote-magic
	fi
done

## jobs
setopt long_list_jobs

## pager
export PAGER="less"
export LESS="-R"

## super user alias
alias _='sudo'
alias please='sudo'

## more intelligent acking for ubuntu users
alias afind='ack-grep -il'

# only define LC_CTYPE if undefined
if [[ -z "$LC_CTYPE" && -z "$LC_ALL" ]]; then
	export LC_CTYPE=${LANG%%:*} # pick the first entry from LANG
fi

# recognize comments
setopt interactivecomments
```

It should also be noted the error gives me a ` as opposed to a ' before the 'then'.

**Comment by edenzik** [comment]
Yep - having the same issue.

**Comment by omarowns** [comment]
On Line 3, `if [[ -e "$d/url-quote-magic"]]; then` there is a missing space between __"__ and __]__.
It should be like this `if [[ -e "$d/url-quote-magic" ]]; then`. This fixed it for me and my buddy.

**Comment by ncanceill** [comment]
Thanks for reporting.

This is fixed in #4002 and many other PRs, and originally reported in #3986.

**Comment by gabeio** [comment]
I have this issue on like 5 computers super annoying. :disappointed:

**Comment by tklovett** [comment]
+1

**Comment by stephen-puiszis** [comment]
+1 having the same issue

**Comment by jmagnusson** [comment]
Same here.

**Comment by tehmaspc** [comment]
duplicate of https://github.com/robbyrussell/oh-my-zsh/pull/4002

please close.

**Comment by oshybystyi** [comment]
@leee , can you close this issue? It should be fixed in the master already by #4002

**Comment by lucassch** [comment]
+1 having the same issue

**Comment by ncanceill** [comment]
If you are still experiencing the issue, please get the latest version using `upgrade_oh_my_zsh`.

**Comment by leee** [comment]
Sorry for the delay, I never have time to contribute nowadays. Appears to be good, closing.

**Comment by ncanceill** [comment]
Thanks!
