### ISSUE TITLE
Compass Doesn't Work

### ISSUE THREAD

**Issue by realph** [robbyrussell/oh-my-zsh#4044]
I'm installing Compass with `gem install compass` and it installs successfully, but for some reason when I run it, it returns this error:

```
zsh: command not found: compass
```

I feel it has something to do with my `$PATH`, but I've never fully understood the `$PATH` or the directories it's pointing to. My `$PATH in my`.zshrc` looks like this:

```
export PATH="$HOME/.node/bin:$HOME/.rbenv/shims:$PATH"
```

If anyone can help me out with this it would be much appreciated. Thanks in advance!

**Comment by Ricky54326** [comment]
Is `compass` somewhere in those two folders in your `$PATH` ? If not, that's likely your issue.

**Comment by apjanke** [comment]
Yep. Do `gem environment` to see where it installs to, and add those paths to your `$PATH` with another line in your `~/.zshrc`.
