### ISSUE TITLE
ggp does not handle --force flag correctly

### ISSUE THREAD

**Issue by chadhietala** [robbyrussell/oh-my-zsh#4045]
I used to be able to do `ggpush --force` or `ggpush -f` and everything worked well. Now when I `ggp --force` I see 

```
fatal: The current branch dep-export has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin some-branch
```

Running `git push origin some-branch  --force` does not cause the fatal error.

/cc @ncanceill

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

I am aware of this issue, it was reported in #3995. I have been looking for a fix, but since more people encounter this, the best course of actions is probably to revert the alias back to its original form. This will be done shortly.

**Comment by chadhietala** [comment]
Closing since https://github.com/robbyrussell/oh-my-zsh/pull/4058 seems to have fixed the issue.

**Comment by ncanceill** [comment]
Thanks!
