### ISSUE TITLE
Backspace doesn't work properly

### ISSUE THREAD

**Issue by hu6360567** [robbyrussell/oh-my-zsh#4046]
XShell (xterm) connect to Server

normally, backspace works fine in shell, but not in interactive prompt
```
touch add

rm add -i

rm: remove regular empty file ‘ass’? n^H^H
```

**Comment by hu6360567** [comment]
```
stty erase ^H
```
It works!

**Comment by ncanceill** [comment]
Hi, it seems you fixed your problem by yourself, congratulations. Can you please close this issue now?

**Comment by ncanceill** [comment]
Thanks! Do not hesitate to create a new issue if you have another problem — especially if you intend to solve it by yourself as well ;-)
