### ISSUE TITLE
Parse error after upgrade OhMyZsh

### ISSUE THREAD

**Issue by nntoan** [robbyrussell/oh-my-zsh#4047]
Hello there,
I got this error after upgrade oh-my-zsh to the lastest version

```bash
~/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'
```

What had happened?

**Comment by nicompte** [comment]
The bug is fixed here: https://github.com/robbyrussell/oh-my-zsh/commit/f66a54fb7862b396e3fc09e7041ca6fee4b42a4a.

**Comment by ncanceill** [comment]
Yes, please upgrade to the latest version, this should go away.
