### ISSUE TITLE
Errors after update to the lastest version

### ISSUE THREAD

**Issue by rchomat** [robbyrussell/oh-my-zsh#4049]
Hi there,

Since I did the update to the lastest version, I get a parsing error
    .oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'

And I also get a message "command not found: parse_git_dirty"

What happen ?

**Comment by benedfit** [comment]
I have an error too, but not the same one:

`/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'`

**Comment by vishnu667** [comment]
for the Second misc.zsh:3: 
just modify the file 

    /.oh-my-zsh/lib/misc.zsh

and replace the third line with 

    	if [[ -e "$d/url-quote-magic" ]]; then

The error there is there should be a space between ' gic" ' and the double quotes

**Comment by benedfit** [comment]
@vishnu667 thanks, problem solved

**Comment by vishnu667** [comment]
@rchomat  Can you update to the latest version again. To Upgrade run the below command 

        upgrade_oh_my_zsh

If the error Still exists can you list the plugins that your using.

**Comment by rchomat** [comment]
@vishnu667 Problem resolved. I still don't know why but I had a lot of "^M" in the different files.
Problem solved.
