### ISSUE TITLE
Git path tab completion broken with recent update

### ISSUE THREAD

**Issue by raddevon** [robbyrussell/oh-my-zsh#4051]
Git commands are completing properly (add, rm, etc), but trying to use tab completion for a path after the command seems to be broken. Attempting this locks up my shell and requires a SIGINT.

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

Please be clear about the steps to reproduce: is it simply `git add <TAB>` then freeze?

Can you also use `git bisect` to track down the offending commit?

**Comment by raddevon** [comment]
@ncanceill Yes, those are the exact steps to reproduce. if I type a partial path, this also triggers the freeze when pressing tab. I should also mentioned I'm running OS X Yosemite 10.10.3.

I'm happy to help find the commit, but I'm not familiar with `git bisect`.

**Comment by ncanceill** [comment]
I seem unable to reproduce. Can you check out the [wiki about completion problems](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#completion-problems)?

`git bisect` is simply a tool to help you back up history looking for a faulty commit, and it has [a manual](http://git-scm.com/docs/git-bisect).

**Comment by ncanceill** [comment]
Also OMZ does not provide completion for Git commands, but instead uses the default Zsh completion, so this is unlikely to be related to OMZ. Can you please use blank startup files and open a new shell to see if the issue occurs?

**Comment by raddevon** [comment]
I started a shell with a blank startup file, and I'm not observing the freeze. I also discovered some more context that is probably important.

Git completion works in most directories, but this one in particular causes a freeze. Here's the structure:

    cwd/
    | .git/
    | home/
    | | .tmux.conf
    | | .vimrc
    | | .zshrc

If I change into the `home` directory, completion works, but, from the root, it freezes.

**Comment by raddevon** [comment]
I ran through the completion troubleshooting, but that didn't seem to help.

**Comment by ncanceill** [comment]
Thanks for digging! I will look into this next week.

**Comment by raddevon** [comment]
Great. Thank you!

**Comment by mcornella** [comment]
Reopen if appropriate.
