### ISSUE TITLE
Hanging at startup with `virtualenvwrapper` and `last-working-dir` plugins

### ISSUE THREAD

**Issue by Gagaro** [robbyrussell/oh-my-zsh#4052]
I have to ^C at the start of zsh if I have both these plugins.

I found that 7b478d75a3a0db466e78b6e46a0e468d64354618 is the bad commit after bisecting.

**Comment by Gagaro** [comment]
Seems like the issue is that I don't have `realpath` (#4030 and #4025 related). It works fine with it installed.

**Comment by ncanceill** [comment]
Hi, and thinks for reporting.

Indeed either installing `realpath` or pulling #4025 should fix the issue.
