### ISSUE TITLE
After upgrade, ggpull breaks local git repo

### ISSUE THREAD

**Issue by anneveling** [robbyrussell/oh-my-zsh#4053]
After upgrading oh-my-zsh to latest version, my daily routine of doing "ggpull" on a branch tracked remotely, resulted in an additional output line like this:

`
➜  project-42 git:(master) ggpull
From github.com:gust/project-42
 * branch            master     -> FETCH_HEAD
 * branch            HEAD      -> FETCH_HEAD
`
This happens even on a clean folder, just after a clone.

Because of this double fetch-head (or whatever it is called), simple pulls will then result in complex merge conflicts.

We tracked this to https://github.com/robbyrussell/oh-my-zsh/issues/3991
and commit https://github.com/robbyrussell/oh-my-zsh/commit/f513999a4dbfea3a15287368848a718543fcaf7b

Reverting oh-my-zsh to version 6ff96dab36865ab208b08a004903338bfd405eac does not have the issue.

It seems that the latest changes to the git plugin making the current-branch variable local has broken this. Took me some time to figure this out, will stay on older version for now but it would be great if you could fix this? Do you need more info to reproduce? Simple enough: just clone any github repo into a clean folder and do a "ggpull".

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

This was already identified and I will send a fix today.

For your curiosity, the cause of this is a try to allow additional arguments to `ggpull` and the like; when called with `""` as an argument `git pull` will recognize it as an empty branch name, and default to the remote HEAD.

**Comment by anneveling** [comment]
Ooh that was quick. Thanks. Looked at the issue list but didn't see the duplicate there. Will upgrade again to latest version when you say it's fixed. Keep up the good work. oh-my-zsh makes my life so much easier
