### ISSUE TITLE
Completion doesn't work if there's an underscore in the file name

### ISSUE THREAD

**Issue by Cathret** [robbyrussell/oh-my-zsh#4063]
Hi,

I had problems when trying to use the completion in my prompt since the last update. I had 5 files in my directory, but I could see and choose only 3 of them.

I looked for the reason of it, and it appeared that when there was an underscore in the file name, the file didn't show in the list. So yet, even if it works if it's the only possibility left, it's quite annoying not beeing able to see all the files.

If the problem's just for me, I'll be gratefull to get a solution for this,

Thanks !

**Comment by apjanke** [comment]
I'm not seeing this. Files with underscores in them seem to work as normal for completion for me.

Can you include more details? The `ls -la` output of the directory showing those files, what system you're on, and the exact command you were trying to complete.

**Comment by Cathret** [comment]
Well, I'm I tryed it again today, and this issue is occuring only in a group of certain directories (and I don't have a clue "why"). I thought maybe it was because of the alias I was using, but when I tryed the "cat" command, I had the same issue.
![doesntappear](https://cloud.githubusercontent.com/assets/6931649/8261072/06c30fc0-16c8-11e5-9ee7-8d4ddc286a9d.png)

I have looked in the other topics, and a lot are talking about completion using git. I'm in a directory checked by git, if that's usefull.

Considering my system, I'm on an Opensuse x86_64 base, and I'm using XFCE and Terminator (don't think these two last info's are usefull, however, everything's good to take).

That's it ! I tryed a lot of commands to get the same issue happen in other directories (to be able to find what I may have done), but nothing's doing it.

**Comment by apjanke** [comment]
Sounds like this might be an interaction with partial-match "completers" in the zsh completion configuration that OMZ sets up.

Okay, I can reproduce this with the current OMZ and a a default completion setup for it.

```
➜  tmp  rm -rf repro-4063
➜  tmp  mkdir -p repro-4063/01
➜  tmp  cd repro-4063/01
➜  01  touch network.c param_fct.c param_set.c server.c test_fct.c
```

Then type `cat<space>` and hit `<tab>. The `.c` appears. Hit tab again and the menu of selections appears beneath it, but without the filenames with underscores.

```
➜  01  cat .c
network.c  server.c
```

But in [my own custom OMZ completion setup](https://github.com/apjanke/oh-my-zsh-custom), which overrides `lib/completion.zsh` with simplified completion settings, hitting `<tab>` to request autocompletion will show all the files as options.

```
$ cd tmp/repro-4063/01
[@ in ~/tmp/repro-4063/01]
$ cat
network.c    param_fct.c  param_set.c  server.c     test_fct.c
```

Take a look at the settings in `~/.oh-my-zsh/lib/completion.zsh`. Those are the things you'll need to tweak to get the behavior you want. (By putting stuff in your `~/.zshrc` after invoking OMZ, or by setting up stuff in `$OH_MY_ZSH_CUSTOM`.) The Zsh doco for this is in the ["Completion System" section of the Zsh Reference Manual](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Completion-System).

I'll bet it's that "`matcher-list`" `zstyle` setting and `setopt complete_in_word`. If I have some free time later, I'll fiddle with it and see if I can let you know exactly what it is.

**Comment by apjanke** [comment]
Yep, it's the `matcher-list` setting. Short answer: stick this line in your `~/.zshrc` after loading OMZ and you'll get more traditional behavior, where files with underscores are included in the completion list.

```
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
```

Even if this workaround fixes it for you, I would leave this issue open. This sounds like undesirable behavior to me, and may well be something that should be changed in the main OMZ files.

Looks like this behavior was introduced recently by #3838. @forivall, is this behavior expected?

**Comment by forivall** [comment]
No, that's not expected behaviour. I don't think it's from my change, unless @Cathret set  `HYPHEN_INSENSITIVE=true` in their zshrc. You can double check what your completion matchers are by running `zstyle -a ":completion:" matcher-list tmp && echo ${(F)tmp}`. if it's the default settings, it should look like
```
❯ zstyle -a ":completion:" matcher-list tmp && echo ${(F)tmp}
m:{a-zA-Z}={A-Za-z}
r:|[._-]=* r:|=*
l:|=* r:|=*
```
If hyphen insensitivity is turned on, it will look like
```
❯ zstyle -a ":completion:" matcher-list tmp && echo ${(F)tmp}
m:{a-zA-Z-_}={A-Za-z_-}
r:|[._-]=* r:|=*
l:|=* r:|=*
```
If it looks like something different, then something else has changed it.

**Comment by apjanke** [comment]
Gotcha. I think "git blame" just attributed this line to you because of the indentation change then.

I'll poke around at this later. I'm still learning the completion configuration stuff, and this is something I'd like to resolve for myself too.

**Comment by Cathret** [comment]
Thanks for the `zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'` line, it got the problem away, or at least I don't have it anymore.

Considering checking the completion matcher, I tryed to use `zstyle -a ":completion:" matcher-list tmp && echo ${(F)tmp}` before and after using the line above.

When using the new line, I got
`> zstyle -a ":completion:" matcher-list tmp && echo ${(F)tmp}`
`m:{[:lower:]}={[:upper:]}`
which I believe is the wanted result.

Using the old settings, the result was
`> zstyle -a ":completion:" matcher-list tmp && echo ${(F)tmp}`
`r:|[._-]=* r:|=*`
`l:|=* r:|=*`
which, I think, is missing the `m:` part.

I really don't know where it comes from, but I'm glad the problem is kind of resolved.

Many thanks !

**Comment by apjanke** [comment]
You know what; I can't even reproduce this behavior now. I don't know what's changed, or if there was some other overlooked setting that's necessary to induce it.

Want to just close this issue out, and we can re-open if it happens again in the future?

**Comment by Cathret** [comment]
Yes sure ! The issue has personnaly be "solved", and shouldn't happen again. Hopefully it won't appear for other people.

**Comment by apjanke** [comment]
Great.

Only you and the repo owner have rights to close the issue. Want to hit the "Comment and close" button which should be down below your "add comment" field" somewhere over there 	↘ ?

**Comment by Cathret** [comment]
Yes ! Sorry, not really used to topics on github haha.
