### ISSUE TITLE
Git clone errors if .gitconfig specifies autocrlf = true

### ISSUE THREAD

**Issue by miabrahams** [robbyrussell/oh-my-zsh#4069]
This pertains to issues #1730 #3294, #3304 and perhaps others.  Cloning the repository fails if `core.autocrlf = true`.  A workaround is OK but I don't understand why the issue is considered resolved; autocrlf is a standard Git setting and users should be able to clone the repository successfully whichever setting they choose.

---
### WORKAROUND:

Run the following:

``` sh
cd $ZSH
git config core.autocrlf false
git rm --cached -r .
git reset --hard
```

**Comment by apjanke** [comment]
What system are you on? Windows/cygwin?

**Comment by mcornella** [comment]
@miabrahams it's not considered solved. I implemented a solution but never got to posting it, sorry :joy: I'm submitting my PR now, please feel free to test it (I'll be posting test instructions as well soon): #4071.
