### ISSUE TITLE
virtualenvwrapper: realpath not available on Mac OS X

### ISSUE THREAD

**Issue by domibarton** [robbyrussell/oh-my-zsh#4073]
Hi

If you're activating the virtualenvwrapper in OS X, you'll get an endless loop of errors:

```
...
workon_cwd:6: command not found: realpath
workon_cwd:6: command not found: realpath
workon_cwd:6: command not found: realpath
workon_cwd:6: command not found: realpath
workon_cwd:6: command not found: realpath
...
```

It will be used in the `workon_cwd` function in `plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh`:

```bash
  function workon_cwd {
    if [ ! $WORKON_CWD ]; then
      WORKON_CWD=1
      # Check if this is a Git repo
      PROJECT_ROOT=`pwd`
      while [[ "$PROJECT_ROOT" != "/" && ! -e "$PROJECT_ROOT/.venv" ]]; do
        PROJECT_ROOT=`realpath $PROJECT_ROOT/..`
      done
```

**Comment by domibarton** [comment]
There's a workaround on OS X by disabling the feature:

```bash
export DISABLE_VENV_CD=1
```

**Comment by radome** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/4025 should fix the problem.

**Comment by mail6543210** [comment]
duplicate of #4030

**Comment by andrey-yantsen** [comment]
fixed by #4106

**Comment by apjanke** [comment]
Could you update your OMZ, and close this issue if #4106 fixed it for you?

**Comment by domibarton** [comment]
yay it works again :+1: 

awesome work mates, awesome! thanks!
