### ISSUE TITLE
Tab completion on mac os 10.10 keeps typed in characters at beginning of line

### ISSUE THREAD

**Issue by tilmans** [robbyrussell/oh-my-zsh#4075]
For example when I do the following:
```rm[tab]``` the result is ```rmrm```. I can delete the second rm but the first sticks around without having any effect - it's only being displayed but I can delete it with backspace and it's not getting executed. 

Versions: 
* zsh 5.0.8 (x86_64-apple-darwin14.3.0)
* newest omzsh (uninstalled, removed all .zsh*, re-installed)

**Comment by apjanke** [comment]
I'm afraid I can't reproduce. Tested on OS X 10.10.4 with zsh 5.0.8 from Homebrew, on Terminal.app and iTerm 2.1.1, with OMZ up to date as of today.

What terminal program are you using? And what's your `$TERM` value?

Please run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/). That will give us your configuration state and system information, which could help track this down.

**Comment by Nixpower** [comment]
See if issue https://github.com/robbyrussell/oh-my-zsh/issues/4107 helps you at all.

**Comment by tilmans** [comment]
Thanks, that helped me look in the right place. I found that "Set locale environment variables on startup" was not set in the Terminal Advanced settings. Turning it on fixed the issue.

**Comment by manthansharma** [comment]
Facing same problem with beaglebone connected as remote device.
