### ISSUE TITLE
Upgrade_oh_my_zsh returns "Command Not Found" when called from inside a bash script

### ISSUE THREAD

**Issue by JonathanWolfe** [robbyrussell/oh-my-zsh#4078]
I have a update/upgrade script for my mac and when I run `upgrade_oh_my_zsh` through the `.sh` I get a `command not found` error.

I worked around the issue by copying the `upgrade_oh_my_zsh` function contents into the file itself.
```bash
echo '=== update Oh-My-ZSH ==='
env ZSH=$ZSH /bin/sh $ZSH/tools/upgrade.sh
```

**Comment by apjanke** [comment]
Do you really mean a `bash` script instead of a `zsh` session or script? It's a `zsh` function that's part of oh-my-zsh, so it wouldn't be available in `bash`.

How exactly do you "run `upgrade_oh_my_zsh` through the .sh"? And are you getting an error that `upgrade_oh_my_zsh` is not found, or is it `upgrade_oh_my_zsh` complaining that something else is not found?

**Comment by JonathanWolfe** [comment]
I know it's a function, but I had assumed that running a `.sh` script inside a `zsh` session would let me access `zsh` functions too. What I'm suggesting is turning `upgrade_oh_my_zsh` into a bin so that it can always be accessed.

**Comment by apjanke** [comment]
`$ZSH/tools/upgrade.sh` is already a bin that can already be accessed from any shell. (Though it could probably use a shebang and a default value for `$ZSH`, for ease of use.) `upgrade_oh_my_zsh` is just a function that locates and calls it. If you turned `upgrade_oh_my_zsh` in to a command too, it would beg the question of how you would locate and call *it*, in turn.

I think what you're doing now is the right way to handle it.

**Comment by JonathanWolfe** [comment]
That's fine if it is, it just wasn't obvious to me how I should be calling it until I decided to look at the source.

**Comment by apjanke** [comment]
To be fair, I'm not sure you *should* be calling it – the `tools/` stuff isn't well-documented, and I don't know if it's considered part of a public interface. It may just be for OMZ's internal use and change underneath you at some point.

Comments, @robbyrussell, @ncanceill, or @mcornella? Are the `tools/*` scripts stable or supported for use outside OMZ?

**Comment by ncanceill** [comment]
Indeed ˋ$ZSH/tools/upgrade.shˋ is a generic script for ˋ/bin/shˋ, which you can call from Bash.

However ˋupgrade_oh_my_zshˋ is a Zsh function defined in ˋ$ZSH/lib/functions.zshˋ, thus only available in a Zsh session with OMZ properly loaded.

You guys are welcome to document this.

**Comment by apjanke** [comment]
I guess I'm wondering more whether we can expect the `tools/*.sh` scripts to stick around for the long run. Do you know if that's the plan?

**Comment by mcornella** [comment]
Yes, that's the right way to call it, and as far as I know there are no
plans to change those.
—
Marc

**Comment by JonathanWolfe** [comment]
Guess I'll close this then, since this is the preferred method of use.
