### ISSUE TITLE
workon_cwd:6: command not found: realpath

### ISSUE THREAD

**Issue by axiaoxin** [robbyrussell/oh-my-zsh#4079]
I always open the virtualenv plugin,but I upgrade oh-my-zsh today, when I cd to a project dir, it tell me `workon_cwd:6: command not found: realpath`

**Comment by wiltzius** [comment]
same. it is a bummer, i am going to try downgrading somehow.

**Comment by wiltzius** [comment]
I'll note that if I ctrl-c it seems to recover fine, though.

**Comment by axiaoxin** [comment]
it can not auto active the virtualenv

**Comment by diwu1989** [comment]
hitting this one too

**Comment by wolfg1969** [comment]
same. after upgrade.

**Comment by wernight** [comment]
+1

**Comment by levchik** [comment]
Same here

**Comment by gmeans** [comment]
I had the same issue. @wernight 's workaround worked as well.

**Comment by AlanAlbuquerque** [comment]
@wernight It worked for me, thanks.

**Comment by harrislapiroff** [comment]
+1

**Comment by apjanke** [comment]
Duplicate of #4030.
Fixed by #4025.
Caused by #3918.

Affects some non-OS X systems too, since `realpath` isn't standard everywhere.

**Comment by diwu1989** [comment]
can someone fix or revert the offending commit?

**Comment by oskargicast** [comment]
@axiaoxin You need to install realthpath requirement. If you are inside a devian based OS: sudo apt-get install realpath.

**Comment by wolfg1969** [comment]
For Mac OS X:
```
brew tap iveney/mocha
brew install realpath
```

**Comment by SanketDG** [comment]
@oskargicast It can't find `realpath` on Linux Mint 17.1.

**Comment by twz915** [comment]
@wolfg1969 fixed, thanks, Mac 10.10

**Comment by diwu1989** [comment]
installing realpath shouldn't be necessary, this used to work just fine before

**Comment by apjanke** [comment]
Agreed. We shouldn't introduce dependencies on programs that aren't widely available by default unless they're really necessary. And in this case, it isn't; `zsh`'s own `:A` modifier flag does the same thing as `realpath`. (Try it out yourself: `ln -s /usr/share/man dummy; cd dummy; d="."; echo ${d:A}`.)

I've put in a PR using `:A` at #4106 that cleans this up. If any of you who are having this problem could test it out and comment on #4106, I'd appreciate it, and that would help get it merged quickly.
