### ISSUE TITLE
Upgrade oh-my-zsh gives me "git_prompt_ahead:1: command not found: current_branch"

### ISSUE THREAD

**Issue by purohit** [robbyrussell/oh-my-zsh#4084]
With an upgrade today, now every command returns:

`git_prompt_ahead:1: command not found: current_branch`

Any ideas?

**Comment by purohit** [comment]
Fixed by changing my theme from "sunrise" to "norm."

**Comment by apjanke** [comment]
Uh-oh. Looks like some of the functions in the core `lib/git.zsh` use `current_branch()`, which is defined in the `git` plugin, not the core lib. So themes which use `git_prompt_ahead`, `git_prompt_behind`, or `git_prompt_remote` will break like this if you do not have the `git` plugin loaded.

➜  .oh-my-zsh git:(master) grep current_branch lib/git.zsh
  if [[ -n "$(command git rev-list origin/$(current_branch)..HEAD 2> /dev/null)" ]]; then
  if [[ -n "$(command git rev-list HEAD..origin/$(current_branch) 2> /dev/null)" ]]; then
  if [[ -n "$(command git show-ref origin/$(current_branch) 2> /dev/null)" ]]; then
➜  .oh-my-zsh git:(master) grep -r "function current_branch" *
plugins/git/git.plugin.zsh:function current_branch() {
➜  .oh-my-zsh git:(master)

If you add `git` to your plugins by adding it to `$plugins` in `~/.zshrc` before sourcing oh-my-zsh, that should fix it too, for all themes.

This is a bug, IMHO. Core stuff should not depend on plugins, or should at least declare their dependencies and help diagnose them.

Possible dupe of #2193.

**Comment by apjanke** [comment]
Looks like #2386 fixes this.

**Comment by purohit** [comment]
Thanks for the speedy reply. Yes, adding `plugins = (git)` before sourcing oh-my-zsh fixed the problem even with the "sunrise" theme. Thanks again.
