### ISSUE TITLE
zsh hangs indefinitely if git is unresponsive

### ISSUE THREAD

**Issue by atsepkov** [robbyrussell/oh-my-zsh#4092]
Somehow my git installation got corrupted such that running any git command would just hang there indefinitely without doing anything. The problem is that this issue effectively rendered all my shells useless since zsh would similarly hang indefinitely trying to load 'git.zsh' library. The shell kinda works, but not really, ctrl+c doesn't exit out of this loop, but keeps cycling between random window titles, when the window title says `zsh`, the terminal seems to accept some user input (vim, bash).

It took me several hours of poking around until I figured out the culprit, which was very frustrating - especially with a gimped shell. Disabling git plugin did not help, since the library git.zsh for git integration is still loaded. oh-my-zsh should have a timeout mechanism that gives up trying to run git for the duration of the terminal session if it's unresponsive (i.e. timeout after 10 seconds and set a environment variable skipping all git logic).

**Comment by apjanke** [comment]
There's an open PR #3914 for timeboxing some of the `git` calls done inside prompts, to avoid hanging if you're in a slow repo (like a very large one, or one on a network drive). It's possible this could be applied to the `git` calls in `lib/git.zsh` setup, too.

Was it hanging on `git --version`? That's the only call I see happening in the library loading phase.

**Comment by atsepkov** [comment]
Yep, it was hanging on `git --version` as well, I still have the old binary on my machine if that would be of any help. Doing a fresh install after renaming it fixed the issue.

**Comment by apjanke** [comment]
Ouch. Don't worry about the old binary: broken is broken and it doesn't matter exactly why. If we're going to do this we just need to defend against `git` hanging for whatever reason.

It's not really OMZ's job to guard against broken installations of standard utilities. And the timeboxing code is pretty finicky so it will ugly up the code. But in this case I think it's worthwhile doing to avoid a hang in the main shell initialization path; that is a real bad failure mode.

You'd need to make sure the prompt didn't hang either, once it got past initialization. PR #3914 takes care of that for the simpler git status stuff that most prompts use. So if you use the simpler fonts, you'd be okay in this case; the prompt would be a bit slow but wouldn't hang. The more complicated git prompt things like `git_prompt_status` are not covered by PR #3914, and would require extensive surgery to fix: doing correct asynchronous `git` calls with timeouts for multi-line outputs of unknown length is more complicated than I can figure out how to do with just native `zsh` and `git` facilities; it might even require a custom helper program in C or the like. I think that's a bit ambitious for either OMZ or myself.

I think I'll add the timeboxing for that first `git --version` to PR #3914. It's the same level of complexity so it makes sense to include, and it probably would've been enough to save your bacon in this case.

**Comment by atsepkov** [comment]
I see, the prompt config I'm using is `avit`, which does indeed include `git_prompt_status`. Didn't realize simpler schemes could bypass this issue. Appreciate the quick response and the fix.

**Comment by mcornella** [comment]
So the solution to this problem is fixing the git installation.
