### ISSUE TITLE
how do i put github api token into profile file? 

### ISSUE THREAD

**Issue by YANGZHEXUAN** [robbyrussell/oh-my-zsh#4096]
new to zsh.

**Comment by mcornella** [comment]
I don't understand your question, why do you want to do that? What's the end result you expect to see?

**Comment by apjanke** [comment]
Where do you want the API token to go? In an environment variable, or loaded in to a program, or somewhere else?

By "profile", are you referring to the [`profiles` plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/profiles)?

**Comment by YANGZHEXUAN** [comment]
Thanks guys. Already fixed it.
