### ISSUE TITLE
How do I get autocomplete of hosts to work for an alias or function?

### ISSUE THREAD

**Issue by devondragon** [robbyrussell/oh-my-zsh#4101]
I have a custom function which takes in a hostname argument.  I would like to be able to tab-complete the hostname just like I can with ssh/rsync/scp/etc...  I've tried adding the short alias to my function "wl" to the the line in the common-aliases.plugin.zsh:

zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync|wl):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

And tried doing the same in my .zshrc.  But neither seems to work.

How can I apply the hosts completion to an arbitrary function or alias?

**Comment by apjanke** [comment]
Could you stick that code sample in triple-backquotes so we can see the exact string and it doesn't get interpreted as Markdown formatting? Some stars in there are turning things in to italics.

```
Like this.
```

**Comment by devondragon** [comment]
\\\zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync|wl):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

**Comment by devondragon** [comment]
I just took the line from the common-aliases.plugin.zsh which I believe provides tab completion for ssh, and added my alias "wl" to the list of commands.  But that doesn't seem to actually work.

**Comment by apjanke** [comment]
Short answer: that `zstyle` line just customizes the manner in which `zsh` looks up hosts when it knows it needs them for completion. To tell `zsh` that your function takes hosts as an argument, do this.

```
compdef _hosts wl
```
If only one of your function's arguments takes hosts, then you may want to define your own `_wl()` completion widget function to go along with the main `wl()` function that can do more context-sensitive completing.

Long answer: see the [Completion System](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Completion-System) section of the Zsh Reference Manual for all the details of defining completion.

**Comment by devondragon** [comment]
Perfect!  Thank you very much!!!
