### ISSUE TITLE
Git Plugin Supporting git add commit push

### ISSUE THREAD

**Issue by sahin** [robbyrussell/oh-my-zsh#4108]
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L1

function g_add_commit_push {
  git add -A && git commit -m "$1" ; git push;
}
alias g_acp='g_add_commit_push'

We would love to smth like this

**Comment by mcornella** [comment]
Won't merge: harmful behavior.
