### ISSUE TITLE
virtualenvwrapper not activatin the venv according to directory

### ISSUE THREAD

**Issue by osleg** [robbyrussell/oh-my-zsh#4110]
After one of the updates virtualenvwrapper stopped to activate env via directory name.
Testcase:
Clean config from fresh install of oh my zsh from git
In plugins only virtualenvwrapper
```
cd Projects && mkdir new_proj && cd new_proj && git init && mkvirtualenv -p /usr/bin/python2 new_proj
cd ..
cd new_proj
```
Expecting:
Virtuale environment "new_proj" should be activated
Actual result - there is even no this tiny delay I used to had before when CDing into directories and no venv activated.

```
λ echo $chpwd_functions
autojump_chpwd workon_cwd steeef_chpwd
λ echo $ZSH_VERSION 
5.0.8
```

**Comment by osleg** [comment]
After some checking I found out that after this #3918 the PROJECT_ROOT variable is always set to "."

**Comment by apjanke** [comment]
PR #4122 fixes this. Would you mind testing it out and +1ing it if it works for you?

**Comment by osleg** [comment]
Works for me with both .venv and bare .git projects
