### ISSUE TITLE
chucknorris plugin depends on fortune

### ISSUE THREAD

**Issue by shubhamchaudhary** [robbyrussell/oh-my-zsh#4112]
chucknorris plugin should also have dependency on fortune.

 Story everytime I setup omz on a new Mac:
* I have to google "command not found: strfile", 
* Land on some page, 
* Realise I need *fortune* package

If not more, then at least issue might help somebody google the similar error :)

**Comment by apjanke** [comment]
It also depends on `cowsay`, for the `cowthink` call in `chuck_cow`.

There's no mechanism for declaring dependencies in oh-my-zsh, but we could add a test and informative error message to the chucknorris plugin.

**Comment by apjanke** [comment]
I put in a PR, #4121, that will give users a better error message, directing them to the "fortune" package.
