### ISSUE TITLE
upgrade_oh_my_zsh - Failing?

### ISSUE THREAD

**Issue by slempke** [robbyrussell/oh-my-zsh#4114]
Received an error this morning when I went to update oh-my-zsh...

*custom/example.zsh: needs update
custom/plugins/example/example.plugin.zsh: needs update
refusing to pull with rebase: your working tree is not up-to-date*

Is this because OS X 10.10.4 update? or Xcode 6.4 update? Maybe it's because I've been fiddling around with custom plugins... but I thought git ignores the custom directory.

$HOME
└── custom
&nbsp;&nbsp;&nbsp;&nbsp;└── example
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── example.plugin.zsh
&nbsp;&nbsp;&nbsp;&nbsp;└── example-custom
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── example-custom.plugin.zsh
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── README.md
&nbsp;&nbsp;&nbsp;&nbsp;└── example.zsh

Any ideas?

**Comment by apjanke** [comment]
That sounds like you've made changes to files in the oh-my-zsh repo that are tracked.

Git ignores the custom directory... *except* for those example files that are provided with the oh-my-zsh distribution. You can see this in the `.gitignore` at the project root.

```
custom
!custom/plugins/example
!custom/example.zsh
!custom/example.zshcache
```

Is that stuff under your `$HOME` dir, or under `~/.oh-my-zsh` (which is `$ZSH`'s default location).

Post the output of `git status` run from `~/.oh-my-zsh` and let's see what's going on.

**Comment by slempke** [comment]
I appreciate the the feedback APJ and thank you for such a quick reply. Bear with me because this is, however, my first post to github about an ongoing issue. 

Here's my output after running <code>git status</code> within <code>~/.oh-my-zsh</code>

<code>stephen-lempke in ~/.oh-my-zsh on master✘✘✘ using ‹› 15-07-07 - 9:22:42</code>
<code>» git status</code>
<code># On branch master</code>
<code># Your branch is ahead of 'origin/master' by 3186 commits.</code>
<code>#</code>
<code># Changed but not updated:</code>
<code>#   (use "git add <file>..." to update what will be committed)</code>
<code>#   (use "git checkout -- <file>..." to discard changes in working directory)</code>
<code>#</code>
<code>#	modified:   .gitignore</code>
<code>#	modified:   custom/example.zsh</code>
<code>#	modified:   custom/plugins/example/example.plugin.zsh</code>
<code>#</code>
<code># Untracked files:</code>
<code>#   (use "git add <file>..." to include in what will be committed)</code>
<code>#</code>
<code>#	themes/slempke.zsh-theme</code>
<code>no changes added to commit (use "git add" and/or "git commit -a")</code>

Updating oh-my-zsh has always been smooth, even with having a custom theme within the themes directory. Here's the output when running <code>upgrade_oh_my_zsh</code>

<code>stephen-lempke in ~ using ‹› 15-07-07 - 9:45:03</code>
<code>» upgrade_oh_my_zsh</code>
<code>Upgrading Oh My Zsh</code>
<code>.gitignore: needs update</code>
<code>custom/example.zsh: needs update</code>
<code>custom/plugins/example/example.plugin.zsh: needs update</code>
<code>refusing to pull with rebase: your working tree is not up-to-date</code>
<code>There was an error updating. Try again later?</code>

Thoughts?

**Comment by apjanke** [comment]
Yeah, it looks like the fact that those two OMZ-provided example files have been modified.

If you want to keep your changes, do this:

```
cd ~/.oh-my-zsh
cp custom/example.zsh custom/my-example.zsh
mkdir custom/plugins/my-example
cp  custom/plugins/example/example.plugin.zsh custom/plugins/example/my-example.plugin.zsh
```

And then do this to undo the changes on the main files.

```
git checkout -- .gitignore
git checkout --  custom/example.zsh 
git checkout -- custom/plugins/example/example.plugin.zsh
```

Then I think the update will work for you again; you can run it manually by doing `env ZSH=$ZSH zsh -f $ZSH/tools/check_for_upgrade.sh`.

It's a little odd that `git` says your branch is 3800 commits *ahead*. I guess we'll worry about that later if there's still a problem.

**Comment by slempke** [comment]
Well, that worked! Thank you.

Was the issue because I didn't create the directory and file for a custom plugin through terminal?

Still receiving:
<code>» git status</code>
<code>On branch master</code>
<code>Your branch is ahead of 'origin/master' by 3193 commits.</code>

Much appreciated!

**Comment by apjanke** [comment]
The issue was just that you modified existing files in the `~/.oh-my-zsh/custom` directory instead of creating new ones.

I don't think that limitation is documented anywhere, so it's not surprising that you hit it. We should document that or do something else about it.

**Comment by mcornella** [comment]
Yes, we should add a warning in those `example` files.

**Comment by mcornella** [comment]
Please close this issue.
