### ISSUE TITLE
michelebologna theme throwing error on every command

### ISSUE THREAD

**Issue by cFINNY** [robbyrussell/oh-my-zsh#4120]
Hey guys,
Not sure if it was an update to zsh, oh-my-zsh, or otherwise but something recently broke the michelebologna theme - it has to do with the git branch output on the right side, and also the colors are now off which is odd but that may have just been part of a theme update which is not an issue.

The error which pops after any command/opening terminal/etc is:
zsh: command not found: __git_ps1

Of course commenting out the following line in the theme file as shown
#PROMPT+='$(__git_ps1)'

...resolves the error but the issue then becomes missing the git branch when in a relevant dir. I haven't had time to run through the code at all to see what the relevant variable should be or if was recently changed so will check that out when I can, just wanted to report first - if any ideas beforehand would be appreciated, thanks!

PS forgot to include, running Arch Linux utilizing the oh-my-zsh-git aur package which simply builds from github (and I checked to be sure I had the latest commits).

**Comment by cFINNY** [comment]
My fault, looks like referenced https://github.com/robbyrussell/oh-my-zsh/pull/4014 and on the linked issue for some reason did not get pulled with the latest commits may not be merged yet but nomatter resolves the issue, thanks!

**Comment by PageVPetty** [comment]
Mine kept saying, " -bash: __git_ps1: command not found  " until I realized that the file " git-prompt.sh " was misspelled. It said " git-promt.sh ". As soon as I changed that everything worked fine.
