### ISSUE TITLE
missing command completion for  'vagrant box'

### ISSUE THREAD

**Issue by CptLausebaer** [robbyrussell/oh-my-zsh#4130]
the completion shows only:

```
add            -- NAME URI Add a box to the system
help           -- COMMAND Describe subcommands or one specific subcommand
list           -- Lists all installed boxes
remove         -- NAME Remove a box from the system
repackage      -- NAME Repackage an installed box into a `.box` file.
```

the output from `vagrant [command] --help` shows that there are more commands of the `vagrant box` subcommand:

```
➜  ~ vagrant box --help
Usage: vagrant box <subcommand> [<args>]

Available subcommands:
     add
     list
     outdated
     remove
     repackage
     update

For help on any individual subcommand run `vagrant box <subcommand> -h`
```

**Comment by hedgehog1029** [comment]
When executing `vagrant box --help` on my system (Ubuntu 14.04, fresh install of Vagrant + deps) I only get:
![screengrab](http://i.imgur.com/OEu08tR.jpg)

So I assume that the plugin reflects the default behaviour.

**Comment by CptLausebaer** [comment]
I use Ubuntu 14.04 and Vagrant 1.7.4 and my output is:
![bildschirmfoto vom 2015-08-21 12 48 50](https://cloud.githubusercontent.com/assets/2578782/9406695/25fc8602-4803-11e5-939f-6bf7c1589ea6.png)

**Comment by hedgehog1029** [comment]
Looks like I somehow have an outdated vagrant install, despite installing from apt-get just now.
I assume the plugin was written off the version I found.

**Comment by CptLausebaer** [comment]
I have installed the latest version from the homepage: https://www.vagrantup.com/downloads.html

The apt-get sources actually provides an older version of vagrant:
![bildschirmfoto vom 2015-08-21 13 05 32](https://cloud.githubusercontent.com/assets/2578782/9406996/aec223f0-4805-11e5-8fc9-b2f719e7ecc5.png)

**Comment by hedgehog1029** [comment]
Even then I have only the Trusty repos, hence the older version that I found (1.4.3). I'll PR the new commands, could you get a short description of what the missing commands do?

**Comment by CptLausebaer** [comment]
The short description of the missing commands could be:

    outdated  -- NAME Check if the box is outdated
    update    -- NAME Update box if outdated

More information can be found on the documentation: http://docs.vagrantup.com/v2/boxes/versioning.html sub-heading: "Viewing Versions and Updating"

**Comment by hedgehog1029** [comment]
Fixed in #4269.

**Comment by CptLausebaer** [comment]
Thanks for the fix.

I have discovered that there are more commands missing:
![bildschirmfoto vom 2015-08-21 13 53 07](https://cloud.githubusercontent.com/assets/2578782/9407700/0bdc4484-480c-11e5-9657-f869e3e075fd.png)

**Comment by hedgehog1029** [comment]
Could you list the missing commands with a short description? I'll update the PR.

**Comment by CptLausebaer** [comment]
The following commands are missing as `vagrant [command]`

    push            deploys code in this environment to a configured destination
    Usage: vagrant push [strategy] [options]

    rdp             connects to machine via RDP
    Usage: vagrant rdp [options] [name] [-- extra args]

    rsync           syncs rsync synced folders to remote machine
    Usage: vagrant rsync [vm-name]

    rsync-auto      syncs rsync synced folders automatically when files change
    Usage: vagrant rsync-auto [vm-name]
