### ISSUE TITLE
Commit a28dbc8 seems to have broken compdef usage in custom/*.zsh

### ISSUE THREAD

**Issue by digitaltoad** [robbyrussell/oh-my-zsh#4133]
I started getting `command not found: compdef` after this commit. I've removed `~/.zcompdump*` to no avail. I've also ran `compinit`. Am I missing something or is this actually a regression?

**Comment by apjanke** [comment]
I think this is a duplicate of #4072 and #4048. Yes, it's a change: custom code now runs before the plugins and before the completion system is initialized, so compdef calls will fail.

Could you check through those other two issues, and if it looks like your issue, chime in there and close this one?

**Comment by digitaltoad** [comment]
I'm sorry yes this is a dup. I guess I didn't look hard enough.
