### ISSUE TITLE
Resizing gnome-window has artifacts

### ISSUE THREAD

**Issue by mrquincle** [robbyrussell/oh-my-zsh#4138]
On resize (you have to resize to the level of the prompt) and after for example just `ls`, you will see that:
- in git folders, there are superfluous X's printed on new lines
- in any folder, the prompt is written halfway on previous lines
- in any folder, lines from the `ls` command are deleted

This is on stock Ubuntu, nothing special. First item seems only the git plugin, the other ones are general.

**Comment by apjanke** [comment]
Do you mean a "gnome-terminal window"?

Which version of Ubuntu are you running?
