### ISSUE TITLE
Add tmux-cssh in list of completion, like ssh

### ISSUE THREAD

**Issue by davizucon** [robbyrussell/oh-my-zsh#4162]
Hi !

Every day I need to do recurring tasks in more them one server at same time,I use some automation and for some specific tasks I use tmux-cssh.
Would be great if tmux-cssh have hosts completion from ~/.ssh/config.
I dunno where exactly I have to make changes to include tmux-cssh host completion, maybe someone can help to add this feature. 

What you think? 

Thanks.

**Comment by moul** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/3321

**Comment by davizucon** [comment]
@moul thank you!!

**Comment by apjanke** [comment]
3321 has been merged. Can this be closed?

**Comment by mcornella** [comment]
I guess it can. Reopen if necessary.
