### ISSUE TITLE
Script echoed to console and nothing works on cygwin / zsh

### ISSUE THREAD

**Issue by krisdante** [robbyrussell/oh-my-zsh#4165]
When I run zsh it echoes to console:

```
colors () {
        emulate -L zsh
        typeset -Ag color colour
        color=(00 none 01 bold 02 faint 22 normal 03 standout 23 no-standout 04 underline 24 no-underline 05 blink 25 no-blink 07 reverse 27 no-reverse 08 conceal 28 no-conceal 30 black 40 bg-black 31 red 41 bg-red 32 green 42 bg-green 33 yellow 43 bg-yellow 34 blue 44 bg-blue 35 magenta 45 bg-magenta 36 cyan 46 bg-cyan 37 white 47 bg-white 39 default 49 bg-default)
        local k
        for k in ${(k)color}
        do
                color[${color[$k]}]=$k
        done
        for k in ${color[(I)3?]}

/// 1000 lines removed here

url-quote-magic () {
        # undefined
        builtin autoload -XU
}
compdef: unknown command or service: git
compdef: unknown command or service: grep
compdef: unknown command or service: git
```

This was working fine before and after recent update - stopped.

Autocomplete do not work, reinstall oh-my-zsh does not help.

**Comment by apjanke** [comment]
Try removing the zcompdump files with `rm ~/.zcompdump*`, close all your sessions, and start a new one. Those files seem to break a lot, and when they do, it can look like this. (An update could have triggered it if it changed the set of `_xxx` completion files on the path.)

Also run `compaudit` to see if you have any insecure directories on the path; that could break completion too, as discussed in #3889.

Let us know of those work.

**Comment by krisdante** [comment]
Removing ~/.zcompdump* helps for 1 time.
compaudit returns a list of un insecure paths but this one line fix is not working anymore (permissions are not changed). I'll investigate why later on when I have time.

**Comment by krisdante** [comment]
chmod g-x was not working, but chmod to 550 directly (etc) solved the problem.
