### ISSUE TITLE
Error symbol not going away

### ISSUE THREAD

**Issue by FWoelffel** [robbyrussell/oh-my-zsh#4175]
Hi there,

I've just installed oh-my-zsh on my Ubuntu computer with the agnoster theme. When an error occurs, the error symbol is correctly prepended to the prompt but wont go away on the next lines.
Since my english might not be clear enough, here is a screenshot of the issue.
![Screenshot](http://i.imgur.com/GXjz7C9.png)
Has anybody faced this ? Could somebody help me to fix it ?

**Comment by apjanke** [comment]
This is normal, and how all themes will behave. It is not something special to oh-my-zsh. Instead, oh-my-zsh is just showing you how the shell works.

When an error happens, the "last command errored" stays in effect until another command is run. (In technical terms, the `$?` shell variable keeps the exit status of the last command run; nonzero `$?` values are considered errors.)

Pressing enter to get a new line just redraws the prompt. It doesn't run a new command, so `$?` does not change. When you run a new command like `cd`, then `$?` gets updated. 

If you really want the "✘" to go away without doing anything new, you can just run `true`, which is a command that does nothing and succeeds.

**Comment by FWoelffel** [comment]
I wasn't aware of that. Thanks for your answer!
