### ISSUE TITLE
Tab completion shifts characters, makes command unreadable

### ISSUE THREAD

**Issue by markogresak** [robbyrussell/oh-my-zsh#4176]
Referring to issue https://github.com/jeremyFreeAgent/oh-my-zsh-powerline-theme/issues/46, asking here if someone knows how to solve this.

Problem description:

A gif explaining what my problem is (sorry that it's a bit laggy, this happened after conversion from video):

![iterm-problem](https://cloud.githubusercontent.com/assets/6675751/8792668/78ed40e2-2f6a-11e5-9c4e-1109d973a963.gif)

As you can see I have set the correct font (Meslo LG M DZ Regular for Powerline), I also had set the `LANG` and `LANG_ALL` values to `en_US.UTF-8`.

[Here is my .zshrc](https://github.com/markogresak/dotfiles/blob/master/zsh/.zshrc), the theme config part is at the top, the code at bottom are mostly functions/aliases. The `LANG` setting is defined in [.globalsrc](https://github.com/markogresak/dotfiles/blob/master/zsh/.globalsrc) file.

I'm using:
  - OS X Yosemite 10.10.4 (freshly installed today, as is the rest)
  - iTerm2 Build 2.9.20150720-nightly -- also happening in Terminal.app
  - zsh 5.0.8 (x86_64-apple-darwin14.3.0)
  - this theme, configured with mentioned font and material design colors theme

I have been using this theme (same config) for almost a year before I decided to reinstall the OS and now I can't figure out what am I missing.

**Comment by markogresak** [comment]
I couldn't figure out what is wrong so I decided to use agnoster theme and added few modifications so it looks like the powerline one.

**Comment by steadystatic** [comment]
I'm having this exact same issue, too :( 

Latest oh-my-zsh and zsh 5.0.5 

![zsh-tab-issue](https://cloud.githubusercontent.com/assets/130587/10947436/28281c08-82e5-11e5-8eec-b171aebc5426.gif)

**Comment by dzcpy** [comment]
+1
