### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by infusion** [robbyrussell/oh-my-zsh#4177]
Hi,

I'm not sure if it should address OMZ or zsh itself. When I type "cd ..<tab>", I would expect to browse the upper directory, without typing a slash. Is this possibly configurable or patchable with OMZ?

Thanks

**Comment by apjanke** [comment]
I believe this is normal zsh behavior. The same thing happens with OMZ turned off. I suspect that `.`. and `..` are being handled specially, and not considered as candidates for completion when it's looking for a directory. (Probably to avoid ".." popping up where you usually wouldn't want it, e.g. as a completion candidate for a path element when you've already provided some leading path elements, or as a high-precedence exact match when you have more complicated completion options enabled, or in the presence of files which start with "..".)

You can look at the `_cd` function supplied with `zsh` to see exactly how it's doing the completion. (Though it can be pretty unreadable.) To find it, do `for i in $fpath; do ls $i/_cd; done`. The first one that's found is probably the one in effect for you.

I don't see an option to control it, so I think this is just normal `zsh` behavior.

**Comment by apjanke** [comment]
Looks like a duplicate of #3775.

**Comment by mcornella** [comment]
I found the solution: https://github.com/robbyrussell/oh-my-zsh/issues/3775#issuecomment-125536530
Please close the issue if it works

**Comment by infusion** [comment]
This works perfectly well, thanks!
