### ISSUE TITLE
oh-my-zsh is constantly hanging

### ISSUE THREAD

**Issue by mcurly** [robbyrussell/oh-my-zsh#4179]
Hello.

I love your project. But, is it me or this `zsh`ell just fails/hangs too many times. I mean, I can't even see any noticeable traces of it failing. The terminal just stays on unresponsive even to the `Ctrl-c` interrupt request issued.

Is this reported, already? I tried to get some signs in the logs but didn't find them on the `dmesg`, and `journalctl -b 0` doesn't show (apparently) any signs of these disruptions.

By the way, I am using your (otherwise) brilliant work on several of my boxes, and this behavior happens on all of them. I use an `ALArm` (Arch Linux Arm), and two pcs with the latest Arch Linux. One of the pc's is a laptop and the other is a server.

`4.0.8-3-ARCH #1 SMP PREEMPT Wed Jul 15 19:11:50 MDT 2015 armv7l GNU/Linux`
and the others are:
`4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux`

Thank you in advance for any interest you may have in this issue, and If there's any other info I should bring here, then, please give me some pointers, and I will gladly follow them to try to sort this out.

Yours,

**Comment by apjanke** [comment]
When does `zsh` tend to hang for you? Is it after a command runs and you'd expect to see a new prompt? Or is it while you're editing a command line or doing other things?

A common cause of `zsh` hanging at the prompt with OMZ installed is slow `git` calls done to get the git status info for the prompt while in a slow repo (e.g. a large repo, or one over a network connection). This is discussed in #3009 and #4092.

If that's your issue, you can work around it by switching to a theme which does not have git status info in the prompt. (I can't think of any offhand, but I think there are a couple.) You could also disable the git info by redefining the `git_prompt_info` (or whichever git function your theme uses) to be a do-nothing.

If that's not it, see if you can find more of a pattern. Do the hangs happen on both local terminal sessions and remote ssh sessions? Are they at prompt time, or other times? Etc etc. And if you get a hung zsh, see if you can open another session and use `ps` etc to find out if it's hung in `zsh` itself, or if it's spawned subprocesses and might be waiting on them.

**Comment by mcurly** [comment]
Hello.

Thank you @apjanke for your interest in the issue I've reported.

Well what I can say about the freezing is that if happens mostly on byobu wrapper, both locally and in ssh sessions.

When I try to find "defunct" processes (by issuing `ps -ef --forest | grep zsh` , for instance) I do actually find them and if I kill the parent (I think it's called that way) the defunct child process disappears. But then again, these workarounds are somehow annoying.

I can't yet confirm that this happens on git trees, and maybe it is so, which would only confirm the other tickets that you've mentioned.

Up until now I've used the default theme, and ys theme before trying the 'bureau' theme, and this one doesn't seem so much troublesome.

Lastly I am sorry for not answering previously, but I just couldn't up until now.

Hope this can be of some use.

Yours

**Comment by apjanke** [comment]
You're welcome. And no worries on the response speed. we've all got things to do, and OMZ debugging isn't your main job.

I don't think I can be any more help right now: I don't use Byobu, and the "bureau" theme doesn't seem to be very different from the other themes. So I've got no other leads, unless the Git thing pans out.

Let me know if you see any more patterns emerging.

**Comment by mcurly** [comment]
@apjanke  Hello again. Thank you again for what you do.

I must also add, that lately (at least for the past 24 hours) I did not experience any hangs on zsh. Although this might not help much as to solve/debug the issue, it surely is more reassuring as well as should alleviate the concerns on the developers' team.

If more disturbing signs should happen I surely will be glad to post them back here.

Thanks,

**Comment by mcornella** [comment]
Hi @mcurly, can you close this issue? In case something else comes up, you can reopen it again.

**Comment by dbalabka** [comment]
On large repositories, you can face that git "dirty" status check can take a lot of time. You should consider disabling getting "dirty" status by setting the git config as following:
```
git config --add oh-my-zsh.hide-dirty 1
```
https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/git.zsh#L16
