### ISSUE TITLE
Autocomplete isn't working as expected

### ISSUE THREAD

**Issue by limonte** [robbyrussell/oh-my-zsh#4183]
Here's the explaining gif:

![recorded](https://cloud.githubusercontent.com/assets/6059356/8874451/6dc4e1b2-3211-11e5-86ee-28b3700658f4.gif)

Actual behavior: I can select one of 4 files by pressing <kbd>Tab</kbd>
Expected behavior: I can select one of all available files in directory (in this case 13) by pressing <kbd>Tab</kbd>

**Comment by limonte** [comment]
It seems that `-` symbol is the source of this issue. All files without it are listed as expected. Files with `-` aren't listed by unknown reason.

**Comment by apjanke** [comment]
I can reproduce, using the default OMZ completion settings. Sounds similar to #4063, which had the same problem with underscores.

If it is something like that, it would probably be the `matcher-list` zstyle setting, [set up by `lib/completion.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/a207a38d634cc10441636bc4359cd8a18c502dea/lib/completion.zsh#L13-L24).

As a workaround, try adding line this to your `~/.zshrc` after OMZ is loaded. It will reset `matcher-list` to a simpler one. For me, this fixes the hyphen-matching problem.

```
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
```

And in the future, could you post bug descriptions using either written-out text, or a sequence of static image screenshots? There's no pause button on animated gifs, and that moved too fast to read closely, so I had to screencap it so I could read it and transcribe enough to reproduce.

**Comment by limonte** [comment]
That was it, @apjanke thank you for the explanation!

> And in the future, could you post bug descriptions using either written-out text, or a sequence of static image screenshots? There's no pause button on animated gifs, and that moved too fast to read closely, so I had to screencap it so I could read it and transcribe enough to reproduce.

Sure, sorry for that.

**Comment by apjanke** [comment]
Nevermind about the static screenshots - realized you can save the animated GIF out and open it in Preview or another image editor to view individual frames statically.
