### ISSUE TITLE
Prompt colors in ubuntu

### ISSUE THREAD

**Issue by manasthakur** [robbyrussell/oh-my-zsh#4188]
The prompt colors on ubuntu under robbyrussell theme are bold and different shades of grey, instead of green for the "arrow" and bluish for the directory.
When a command is erroneously executed, it changes to red successfully, though.
I have observed this problem in my shell on ubuntu; on Mac everything works fine.

P.S. I am using solarized-light theme.

**Comment by manasthakur** [comment]
Solved. LSCOLORS needed to be set explicitly in ubuntu.

**Comment by manasthakur** [comment]
Solved. LSCOLORS needed to be set explicitly in ubuntu.

**Comment by apjanke** [comment]
What terminal emulator are you using, and where did you get the solarized-light theme definition for it? What version of Ubuntu? It may be an issue with how "bold" vs "bright" fonts are being rendered.
