### ISSUE TITLE
`compdef` not found error on custom script

### ISSUE THREAD

**Issue by BrendanThompson** [robbyrussell/oh-my-zsh#4194]
I have a custom script that's in my `~/dotfiles/zsh/custom` directory which is loading, however I am getting the following error now after upgrading just before:

```
/Users/bthompson/dotfiles/zsh/custom/iTerm2-ssh.zsh:33: command not found: compdef
```

The script is based on this [gist](https://gist.github.com/wadey/1140259)

**Comment by apjanke** [comment]
Duplicate of #4133. See #4072 for the main discussion.

In short,  #3617 changed how custom files are loaded in the startup sequence. Custom files are now loaded before plugins are loaded or completion is initialized, and `compdef` will no longer work.

A workaround is to turn this custom file into a custom plugin, and add it to the *end* of your list of custom plugins. (So it runs after other plugins, which was the old location for user custom code to run.)

If this is causing you an issue, please add a comment on #4072, so maintainers discussing that change can take it in to consideration.

**Comment by BrendanThompson** [comment]
Seems as though when this is used as a `plugin` it breaks the functionality

**Comment by apjanke** [comment]
That code in the linked gist seems to work for me as a plugin. I saved it as `$ZSH_CUSTOM/plugins/iterm2-tabs.plugin.zsh` and added `iterm2-tabs` to my `$plugins` list. No error on startup, and I can call `tab-color 255 0 255` to make my tab purple. (For that matter, there's a PR #2805/#3790 to do an extended version of this in a plugin.)

What's not working for you? Maybe there's some other code or something it's interacting with?

**Comment by BrendanThompson** [comment]
For whatever reason it just wasn't changing the tab colour when i used it as a plugin. Not too sure why tbh. Have just changed it back to a script. What is the likelihood of #3617 being reverted, or changed as you suggested in #4072?

**Comment by apjanke** [comment]
Pretty low, I'd guess. OMZ development moves kind of slowly, and #4072 has been sitting there for over a month already.

If you want to post your exact code as a Gist, I'll try to help you get it working as a plugin. I don't see any reason it couldn't.

BTW, I misspoke earlier: the file I saved it to was `$ZSH_CUSTOM/plugins/iterm2-tabs/iterm2-tabs.plugin.zsh`, not `$ZSH_CUSTOM/plugins/iterm2-tabs.plugin.zsh`. Each plugin `foo` has its own `foo` dir, and a `foo/foo.plugin.zsh` file.

**Comment by BrendanThompson** [comment]
maybe that's why, I'll give that a go :)

**Comment by apjanke** [comment]
Oh yeah, that definitely would have broken it. Probably would have just silently failed to load your code at all.

**Comment by BrendanThompson** [comment]
Cool, that seemed to fix that issue. However now when it runs it crashes and closes the tab. But I fear that is more of an iTerm2 issue. Also, the code is basically the same just a few more `elif` statements :)

**Comment by apjanke** [comment]
Hmmm; that's not optimal behavior. If you want help debugging that too, post a gist and point us at it.

In the mean time, since we've got the compdef/OMZ part fixed, do you want to close this issue?

**Comment by BrendanThompson** [comment]
@apjanke I opened up a ticket with iTerm [here](https://gitlab.com/gnachman/iterm2/issues/3716) if you're interesting in having a look that would be awesome. But yes i will close this ticket off now.

Thanks heaps mate

**Comment by apjanke** [comment]
No prob!

Subscribing to that issue, but my 10.11 box is tied up with Homebrew test builds at the moment. Will try to reproduce when it's free. (Figure a couple days; it's a wimpy box.)

Andrew

**Comment by BrendanThompson** [comment]
Thanks mate, appreciate it :)
