### ISSUE TITLE
sftp autocomplete 

### ISSUE THREAD

**Issue by shahidash** [robbyrussell/oh-my-zsh#4196]
Unable to autocomple on yosemite again. It was previously resolved but happening again check issue #2223

**Comment by mcornella** [comment]
Ok, can you provide more information? System platform and version, terminal emulator and version, `echo $TERM`, `zsh --version`, `zshrc` file.

**Comment by shahidash** [comment]
xterm-256color, zsh 5.0.5 (x86_64-apple-darwin14.0)

**Comment by apjanke** [comment]
Works for me on Mavericks and Yosemite.

What about it isn't working for you? Is it not giving you any possible completions? Or is it giving you in appropriate values? Or something else?

**Comment by shahidash** [comment]
hi Andrew

when i use sftp , i try to use autocomplete (tab completion feature) its
not working , gives nothing as a result.

Thanks

P.S. Do share some resources, so i start helping you guys.

On Tue, Aug 18, 2015 at 9:57 AM, Andrew Janke <notifications@github.com>
wrote:

> Works for me on Mavericks and Yosemite.
>
> What about it isn't working for you? Is it not giving you any possible
> completions? Or is it giving you in appropriate values? Or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/4196#issuecomment-132069336>
> .
>



-- 
with Regards
Shahid Ashraf

**Comment by apjanke** [comment]
All right. We're going to need some additional debugging info.

Please run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/).

**Comment by mcornella** [comment]
Any updates @shahidash?
