### ISSUE TITLE
zshell path with Gems quick fix

### ISSUE THREAD

**Issue by YonasBerhe** [robbyrussell/oh-my-zsh#4211]
/home/sanoy/.gem/ruby/2.2.0/bin
I need help setting up my path in for Gems with shell. 

I have the line below in my .zshrc file but no cigar. 
export PATH=$PATH:/home/sanoy/.gem/ruby/2.2.0/bin

**Comment by mcornella** [comment]
You need to put that line at the top of the `zshrc` file

**Comment by mcornella** [comment]
Did that work?
