### ISSUE TITLE
vim show more dirs or files error

### ISSUE THREAD

**Issue by CKKing** [robbyrussell/oh-my-zsh#4219]
One day ago, when I type vim /etc/  ,the same time I type tab button, the error  is showing,eg:
_arguments:450: _vim_files: function definition file not found
_arguments:450: _vim_files: function definition file not found
_arguments:450: _vim_files: function definition file not found

**Comment by apjanke** [comment]
Sounds like an issue with your completion setup.

Try `rm ~/.zcompdump*` and restarting your session.

What do you get for the output of `compaudit`?

**Comment by CKKing** [comment]
Thanks,But the iterm color is not work, I sad

**Comment by CKKing** [comment]
Thank you very much,But rm this file, I need to install oh-my-zsh againt

**Comment by apjanke** [comment]
You should not need to do that. When that zcompdump file is deleted, oh-my-zsh will regenerate it as part of its startup sequence. If that's not happening, something else is wrong, possibly the permissions on directories in your `$FPATH`.

What do you get for the output of `compaudit`?

**Comment by CKKing** [comment]
Okay,but I havent to do it.The compaudit happend on commnd line  type <tab> button

**Comment by apjanke** [comment]
I'm sorry, I just don't understand what you're saying.

What language do you speak? Maybe another OMZ user can help out here.

**Comment by CKKing** [comment]
sorry, I not good at english,ver sorry.I speak chinese, another, the problem is resolved.Tanks againt.

**Comment by mcornella** [comment]
Ok, please close the issue then.

**Comment by CKKing** [comment]
Ok,thanks

**Comment by eggsbenjamin** [comment]
I had the exact same issue. 

It looks like `zsh` sets the path of the compdump file as an environment variable `ZSH_COMPDUMP`. The `~/.zcompdump` was also on my system which led to some confusion.

`rm $ZSH_COMPDUMP \
exec zsh` 

This worked for me :+1: .
