### ISSUE TITLE
plugin common-aliases will cause error

### ISSUE THREAD

**Issue by Arondight** [robbyrussell/oh-my-zsh#4223]
between line 24 and line 33 of file `plugins/common-aliases/common-aliases.plugin.zsh`, there is some code using alias:
```shell
# Command line head / tail shortcuts
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"
```
it will cause problem, for example, command
```shell
vim L
```
will explan to
```shell
vim | less
```
that's will make trouble.
suggest: **do not use any `alias -g`**, it won't always make things goes well.

**Comment by mcornella** [comment]
Frankly I think that's a desired feature of the common-aliases plugin, not a bug. You can work around those aliases by putting stuff inside quotation marks: `vim 'L'`. 

Otherwise you can:
- Disable **all** global aliases: `for alias in $(alias -g); do unalias $alias; done`.
- Disable the `common-aliases` plugin.
- Modify the plugin to make those global aliases optional.

**Comment by Arondight** [comment]
@mcornella 
finally i unalias all of global alias at the end of my `~/.zshrc`
```shell
for alias in $(alias -g | /usr/bin/env grep -oP '^.+?(?==)'); do
  unalias $alias
done
```
maybe it is a desired feature to use global alias, but sometimes it will make trouble. i dont think it is suitable. :stuck_out_tongue_closed_eyes:

**Comment by apjanke** [comment]
Ooh. I would just copy the aliases you *do* want from that plugin to a custom file, and then not load the plugin. Those global aliases could still interact with code in other plugins and stuff that runs before control returns to your `~/.zshrc` for unaliasing. Avoiding them in the first place would be cleaner than writing code to back them out later.

Also watch out for these aliases, which turn on interactive mode for some file-manipulation commands, which may make them unsuitable for use in scripts or pipelines which are intended to run headless, in background, or have stdin redirected.

```
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
```

And this `grep` alias, which will override the setup done in `lib/grep.zsh`, and will break `grep` on OS X and possibly other BSDs. On those systems, the `--color` option *must* take an argument (`never`, `always`, or `auto`) and using it without one causes an error.

```
alias grep='grep --color'
```

And this thing at the bottom which is not an alias, but instead modifies completion behavior for `ssh`.

```
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
```

**Comment by Billy-** [comment]
You might find this interesting... I'm using it, works like a charm :)

http://blog.patshead.com/2012/11/automatically-expaning-zsh-global-aliases---simplified.html
