### ISSUE TITLE
Problems installing ohmyzsh ("command not found: ^M")

### ISSUE THREAD

**Issue by lightningboss** [robbyrussell/oh-my-zsh#4227]
I have problems while installing Oh my zsh. The console is giving me the following errors (screenshot). How can I install oh my zsh properly without errors?

![screenshot](https://cloud.githubusercontent.com/assets/11751444/9145730/0fa246f0-3d57-11e5-9fba-9f617fcbe308.jpg)

**Comment by mcornella** [comment]
Please post what commands have you run to install oh-my-zsh and what's the output of `git config core.autocrlf`

**Comment by lightningboss** [comment]
Thank you for this note on git. I actually imported my git configuration from windows, which caused this problem. I now deleted the oh my zsh folder and its config, and the gitconfig file as well. I read while looking for a solution about the Windows-line endings, which are bad for oh my zsh.
