### ISSUE TITLE
How to Implement  The theme 'amuse' bottom of status？

### ISSUE THREAD

**Issue by netcan** [robbyrussell/oh-my-zsh#4231]
![so cool!](https://cloud.githubusercontent.com/assets/2618447/6316861/70f3c4ce-ba03-11e4-88a5-0b423dd5a2ce.png)
What the plugin is?

**Comment by bronzdoc** [comment]
@netcan in your .zshrc
<code>ZSH_THEME="amuse"</code>

The status bar is tmux with the powerline plugin.

**Comment by john156** [comment]
:+1:

**Comment by mcornella** [comment]
Updated the [wiki instructions to reflect that](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#amuse). Please @netcan close this issue.
