### ISSUE TITLE
copyfile and copydir are osx specific

### ISSUE THREAD

**Issue by jody-frankowski** [robbyrussell/oh-my-zsh#4232]
They both use the pbcopy command which is only available on osx.

**Comment by apjanke** [comment]
Affects plugins `cloudapp` and `coffee`, too.

```
$ grep -r pbcopy *
plugins/cloudapp/cloudapp.rb:`echo '#{url}' | tr -d "\n" | pbcopy`
plugins/coffee/coffee.plugin.zsh:  cf $1 | pbcopy
plugins/coffee/coffee.plugin.zsh:alias cfpc='cfp | pbcopy'
```

**Comment by apjanke** [comment]
Added a PR #4254 to make them portable. Tested on OS X and Windows; think it will work on Linux too. Would you mind giving it a test and see if it works for you too?
