### ISSUE TITLE
Why font color overlaps and changed in iTerm2 on Mac

### ISSUE THREAD

**Issue by FinalTheory** [robbyrussell/oh-my-zsh#4246]
![qq20150814-1](https://cloud.githubusercontent.com/assets/2818951/9275566/79908882-42d0-11e5-85fe-c30b07986331.png)
![qq20150814-2](https://cloud.githubusercontent.com/assets/2818951/9275656/31fcd5ba-42d1-11e5-9eb0-d44ec36285f7.png)
Just as shown in pictures above, the small triangle looks so uncomfortable, and similar problem also appears in Terminal.app, with just same configuration.
iTerm version: Build 2.1.1
Oh my zsh and the themes are latest.

**Comment by apjanke** [comment]
What version of OS X are you running? Is that the `agnoster` theme?

**Comment by FinalTheory** [comment]
Mac OS 10.10.5
The agnoster theme

**Comment by apjanke** [comment]
This looks like you're running in to the effects of "minimum contrast enforcement". This is a terminal emulator feature that ensures text is readable by adjusting foreground colors that are too similar to the background color of the window (in Terminal's case) or the character cell (in iTerm's case, I think). Powerline themes make that right-pointing segment shape by drawing a special right-pointing triangle character with a foreground color that is the same as the previous segment's background color.

You can see it in action by adjusting the background color. In Terminal, take a look at the "Window" tab under the Profile, select the Background Color & Effects, and adjust the color and opacity slider. You'll see the green triangle pop in and out of a brightened mode when you have a dark background that's like the green color.

In iTerm2, you can adjust this feature with the "Minimum contrast" slider in the Colors section of your profile. Terminal.app doesn't seem to have any way to turn it off or control it. You may just have to fiddle with your background color until you get one that doesn't trigger it.

**Comment by FinalTheory** [comment]
Wow, that just work fine!
I spent a lot of time trying to find which option controls this behavior, but got nothing.
So I recommend to add your notification to the wiki page to remind others about this thing.
And thanks very much for your reply.
