### ISSUE TITLE
common-aliases plugin has `zsh` host completion controls

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#4257]
The common-aliases plugin, in addition to defining a bunch of aliases, [changes settings](https://github.com/robbyrussell/oh-my-zsh/blob/9a5e1a055201409ebe9e1ab97cd8c3fe52b990f5/plugins/common-aliases/common-aliases.plugin.zsh#L84-L85) for how hosts completion is done for ssh-related programs.

```
# Make zsh know about hosts already accessed by SSH
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
```

That doesn't seem like it belongs on an alias-defining plugin. And it may conflict with other plugins that try to configure ssh-related completion.

**Comment by mcornella** [comment]
Not a bug, but a feature. I think some folks prefer it that way.
