### ISSUE TITLE
sbt multi project

### ISSUE THREAD

**Issue by MasseGuillaume** [robbyrussell/oh-my-zsh#4262]
When using https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/sbt/_sbt

Sbt allows multiple projects. You can specify a command against a specific project: `sbt projectA/compile`

currently the autocompletion plugin does not trigger after the slash `sbt projectA/c...`

**Comment by mcornella** [comment]
This is nearly impossible to implement using zsh's completion api.
