### ISSUE TITLE
Add `--follow-tags` to Git plugin

### ISSUE THREAD

**Issue by blakeembrey** [robbyrussell/oh-my-zsh#4264]
Not sure on the etiquette for plugins, so I'm going to start by making an issue. It would be great to push tags with the changes using the `--follow-tags` option on the alias `gp` and possibly others.

**Comment by mcornella** [comment]
[By the look of it](https://git-scm.com/docs/git-push#Documentation/git-push.txt---follow-tags) you can specify that option to be the default via git-config. It looks like a pretty useful option.
