### ISSUE TITLE
.oh-my-zsh/templates/zshrc.zsh-template': No such file or directory

### ISSUE THREAD

**Issue by kiemrong08** [robbyrussell/oh-my-zsh#4265]
When i install oh-my-zsh, i meet the error.
![image](https://cloud.githubusercontent.com/assets/3337033/9376536/925aa08e-4738-11e5-9d7b-896581bec614.png)

**Comment by hedgehog1029** [comment]
You're using Windows, rather than a POSIX-based OS. oh-my-zsh is designed for OSX and Linux.

**Comment by kiemrong08** [comment]
i use with cygwin

**Comment by hedgehog1029** [comment]
Doesn't matter, Cygwin does not magically make Windows fully POSIX compatible.

**Comment by mcornella** [comment]
It doesn't matter, we stlil support Cygwin (and babun) users. It should work ok with cygwin, the problem that you might be suffering from is one of permissions, since you're installing from the Administrator user.

Do me a favor and post the output of `umask`, `ls -Al /home/Administrator/.oh-my-zsh`, and `getacl /home/Administrator/.oh-my-zsh`.

**Comment by apjanke** [comment]
Could be an MSYS vs Cygwin `git` compatibility issue.

I've seen a [similar error trying to install on Cygwin when the native Windows Git is installed, but the Cygwin `git` is not](https://github.com/robbyrussell/oh-my-zsh/issues/3588). OMZ (and Cygwin in general) require the Cygwin Git, and do not play well with the native Windows (aka MSYS) Git. See #3588. (It crosses the Cygwin/Windows boundary without translating Unix style paths to Windows style paths, so Git downloads OMZ to the wrong location.)

To test and fix: Do a `which git` to see if it's the Cygwin or MSYS Git on your path. If it's not the Cygwin one (which will be `/usr/bin/git`), re-run the Cygwin `setup` program and use it to install `git` and then try installing OMZ again.

It's also a little weird that a couple of the lines of output are interleaved, almost like they were from parallel jobs. Anyone know what's up with that? I thought `git` was single-threaded. Maybe that's just another side effect of using MSYS `git` from Cygwin.

<img width="590" alt="screen shot 2015-08-20 at 4 59 24 pm" src="https://cloud.githubusercontent.com/assets/2618447/9395509/e3f0aff0-475c-11e5-9b23-663b90e8d9cc.png">

> rRemote: Total 671 (delta 15), reused 517 (delta 4), pack-reused 0eciving objec

**Comment by kiemrong08** [comment]
@apjanke Thank a lot !. After install git pakage for cygwin and reinstall OMZ it work like a charm.
But why it appear `chsh: command not found` when install.
![image](https://cloud.githubusercontent.com/assets/3337033/9542429/d827ebfe-4d9a-11e5-827a-83d76b36fa80.png)

**Comment by apjanke** [comment]
You're welcome.

That's just a limitation of Cygwin: `chsh` simply doesn't exist there. (#3646 should make OMZ handle that more gracefully.) 

To change your default shell on Cygwin, you need to manually edit `/etc/passwd`, creating it if necessary. See https://cygwin.com/cygwin-ug-net/ntsec.html.

**Comment by mcornella** [comment]
This can be closed now.
