### ISSUE TITLE
install.sh crashes while changing shell

### ISSUE THREAD

**Issue by ViKomprenas** [robbyrussell/oh-my-zsh#4274]
I have a Raspberry Pi and thought I'd give this a try. The install script crashes at "Time to change your default shell to zsh!" with "Password: chsh: PAM: Authentication failure".

**Comment by apjanke** [comment]
Sounds similar to #3516.

What method did you use to install it? Did you do `sh -c "$(curl -fsSL https://.../install.sh)"` (as described in the README in the repo) or `curl -L https://.../install.sh | sh` (as described on http://ohmyz.sh)? The first one is what you need to use. The second one can run in to the error you had on systems where `chsh` reads from `stdin` instead something like `/dev/tty`.

**Comment by ViKomprenas** [comment]
I used the one from the website. Thankfully, that's the last step and everything else worked fine. The website should probably be corrected, though.
