### ISSUE TITLE
alias 'gf' conflicted between plugin git & git-flow

### ISSUE THREAD

**Issue by cxbig** [robbyrussell/oh-my-zsh#4275]
`gf` in `.oh-my-zsh/plugins/git/git.plugin.zsh` L:90
```zsh
alias gf='git fetch'
```

`gf` in `.oh-my-zsh/plugins/git-flow/git-flow.plugin.zsh` L:24
```zsh
alias gf='git flow'
```

`gf` for `git fetch` now is overwritten by the one in `git flow`

**Comment by mcornella** [comment]
Which one do you want? That's normal, IMO. Those two plugins are related to git and it is expected that some aliases will clash. 

In that case, the plugin that's added later in the `$plugins` array will override the aliases from the former plugin. That means that if you want `git fetch`, you have to put the `git` plugin after the `git-flow` plugin. If you want the `git flow` one, you have to put the `git-flow` plugin after the `git` plugin.

**Comment by cxbig** [comment]
People will use both plugins & commands often.
I will suggest to update one of the alias. Then we have no conflict for git usage.

**Comment by mcornella** [comment]
Ok, that's fair. Do you know how to submit a PR?

**Comment by cxbig** [comment]
I will create one soon.

**Comment by mcornella** [comment]
This can be closed now, thank you!
