### ISSUE TITLE
vagrant plugin - completions not working

### ISSUE THREAD

**Issue by ascii-soup** [robbyrussell/oh-my-zsh#4277]
I have added vagrant to my plugins list

`plugins=(vagrant)`

I reload zsh and vagrant completions do not appear.

`$ vagrant [Ctrl+X, h]` yields the following:

```
tags in context :completion::complete:vagrant::
    all-files  (_files _default)
```

which confirms my suspicion that the completions are not loaded.

The output of `$ autoload` does not contain the _vagrant() function, yet $fpath contains the vagrant plugin directory (/home/[my-user]/.oh-my-zsh/plugins/vagrant)

If I type the following:
```
$ autoload _vagrant
$ compdef _vagrant vagrant
```
it all starts working again.

Having tried a few other plugins that only define a `_plugin` completions file,
it appears that none of them work for me. Plugins that contain a `plugin.plugin.zsh`
file which calls compdef appear to be work fine.

Is there something obviously wrong with my configuration that prevents these completions
from loading correctly?

**Comment by apjanke** [comment]
Works for me, for both vagrant and other plugins, by just adding them to my `$plugins` list. 
```
➜  ~  vagrant
tags in context :completion::complete:vagrant::
    argument-1  (_arguments _vagrant (eval))
tags in context :completion::complete:vagrant:argument-1:
    commands  (_describe _vagrant (eval))
```
Something may be off about your configuration or state on this machine. But I can't tell what it is without more info.

As a first step, try just `rm ~/.zcompdump*` and restarting your session. Might just be a corrupted zcompdump file.

Might also be that `compinit` is ignoring "insecure" directories. Try running `compaudit` and see if it produces any output. If it does, do `chmod o-w` on those insecure directories. (See #3889.)

If neither of those works, we can take a look at a diagnostic dump of your configuration to see what's up. Run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/).

**Comment by ascii-soup** [comment]
I had already tried removing the .zcompdump* files to no avail.

compaudit was telling me that the vagrant plugins directory was insecure, so I followed some advice on "correcting" the permissions. This didn't work. However, this marked all files in the OMZ repo as modified (which they weren't before, so permissions should have been the defaults...) so I did a checkout of everything and removed the .zcompdump* files again and success!

Not really sure what caused the issue, the permissions are now the same as they were before according to all checks I can do, but hey ho - I'm just glad to have it fixed!

Thanks!

**Comment by apjanke** [comment]
You might want to take another look at the permissions correction you did, and the state your OMZ repo is in. If `git` is still seeing the files in it as modified, that may prevent you from picking up future updates from OMZ, since the updater is implemented with a `git pull`.

**Comment by mcornella** [comment]
> so I did a checkout of everything and removed the .zcompdump* files again and success!

I assume he already fixed the state of the repo with a `git checkout` here.

**Comment by ascii-soup** [comment]
"I assume he already fixed the state of the repo with a git checkout here."

Bingo.
