### ISSUE TITLE
ohmyz.sh web site using old installer form which breaks on some systems

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#4278]
In #3872 / #3809, the README was updated to change the installation instructions from `wget .../installer.sh | sh` to `sh -c $(wget .../installer.sh)`, to avoid `chsh` errors like #3516.

The http://ohmyz.sh web site is still using the old installer form, so some users are still using it and getting `chsh` errors (like #4274).

Can the web site be updated?

**Comment by mcornella** [comment]
/cc @robbyrussell
—
Marc

**Comment by peterrus** [comment]
yeah just ran into this issue.

**Comment by mcornella** [comment]
Last time we had to update the web Robby called corinnekunze: https://github.com/robbyrussell/oh-my-zsh/pull/3461#issuecomment-75405658. 

So @corinnekunze (hi! :D) could you please update the links on the website with newer ones (from [the README file](https://github.com/robbyrussell/oh-my-zsh#via-curl)). Thanks!

**Comment by corinnekunze** [comment]
Hi @mcornella + @apjanke  ! 
This should be updated on the website now.

**Comment by apjanke** [comment]
I'm still seeing the old instructions. Could it be taking a while to propagate?

![screen shot 2015-08-26 at 7 41 16 pm](https://cloud.githubusercontent.com/assets/2618447/9509183/9716910e-4c2a-11e5-9c50-68615dac66fc.png)

**Comment by corinnekunze** [comment]
It's probably your cache, refresh a few times or open an incognito tab.

On Wed, Aug 26, 2015 at 4:44 PM, Andrew Janke <notifications@github.com>
wrote:

> I'm still seeing the old instructions. Could it be taking a while to
> propagate?
>
> [image: screen shot 2015-08-26 at 7 41 16 pm]
> <https://cloud.githubusercontent.com/assets/2618447/9509183/9716910e-4c2a-11e5-9c50-68615dac66fc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/4278#issuecomment-135206569>
> .
>



-- 
*Corinne Kunze*
Planet Argon -  Web Developer

**Comment by apjanke** [comment]
Okay, that fixed it. Thanks!

**Comment by mcornella** [comment]
Thanks Corinne

**Comment by peterrus** [comment]
thanks! :D
