### ISSUE TITLE
rompt_segment:5: character not in range

### ISSUE THREAD

**Issue by xiaozihan2011** [robbyrussell/oh-my-zsh#4279]
Hello , i am using agnoster theme in iterm2(Yosemite10.10.5/imac),but it have some problem with my text 
![qq20150825-1](https://cloud.githubusercontent.com/assets/6435613/9458662/9002762e-4b23-11e5-86f3-9bb1b2d1ed85.png)
![qq20150825-2](https://cloud.githubusercontent.com/assets/6435613/9458664/943d7072-4b23-11e5-8f90-39ad4214f830.png)

it can't have other characters , i use menlo for powerline fonts

**Comment by mcornella** [comment]
Please post the output of "locale", it may have something to do with not
having a utf8 locale.
—
Marc

**Comment by xiaozihan2011** [comment]
But it already having a utf8 locale
![qq20150825-3](https://cloud.githubusercontent.com/assets/6435613/9464446/79cc6ab2-4b56-11e5-8f1d-c0e831e1173b.png)
![Uploading QQ20150825-3.png…]()
![Uploading QQ20150825-3.png…]()

**Comment by mcornella** [comment]
This is a duplicate of #4065, please close this one and comment there. And post the output of running the command `locale`, even if the Terminal app is configured for that the locale variables can be messed up.

**Comment by xiaozihan2011** [comment]
ok
