### ISSUE TITLE
Already installed vundle is not detected by vundle plugin

### ISSUE THREAD

**Issue by matthiasvegh** [robbyrussell/oh-my-zsh#4281]
Currently the [vundle quickstart guide](https://github.com/VundleVim/Vundle.vim#quick-start) specifies `~/.vim/bundle/Vundle.vim` as the installation guide, and I suspect others like me installed it there.

The vundle plugin however assumes that vundle is _or is to be_ installed at [`~/.vim/bundle/vundle/`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vundle/vundle.plugin.zsh#L2). This means that even though vundle has been correctly installed, the plugin needlessly attempts to clone a second copy of vundle.

I think the plugin should either use the default installation location, or should detect whether vundle is installed by querying vim whether `:PluginUpdate` is available along the lines of:

    vim -c 'if exists(":PluginUpdate") | q | else | cq | endif'

**Comment by mcornella** [comment]
This is fixed in the current version, can you please check?

**Comment by matthiasvegh** [comment]
Looks good on my end, thanks for the update!
