### ISSUE TITLE
A way to disable git status segment 

### ISSUE THREAD

**Issue by Thermatix** [robbyrussell/oh-my-zsh#4288]
Hi, I've stared using this https://github.com/michaeldfallen/git-radar because it provides a lot of useful information about a git-repo the problem is however there's the git-status segment. 
Now I disabled that on the theme I'm using (agnoster) by commenting the segment out in the list at the very bottom. 

I think there should be a global variable that you can set in your `.zhrc` and all the themes listen to this variable and will not render the git status segment when this variable is set to false.

I'm not sure how much work this would be but I feel that something like that would be easier then simply editing a theme file and less update breaking potentially.

**Comment by hendrikstier** [comment]
My current way to achieve this is overwriting the `build_prompt` of the theme function like so:

```
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_end
}

export PROMPT="$PROMPT\$(git-radar --zsh --fetch) "
```

**Comment by hiberabyss** [comment]
You can run this command `git config --global oh-my-zsh.hide-status 1` to disable git status prompt

**Comment by Thermatix** [comment]
Tried the last one but it didn't seem to do anything, I restarted my terminal as well but no difference.
I think I'll use the method @hendrikstier suggested.

**Comment by mcornella** [comment]
@hendrikstier you can go further and put the `git-radar` call inside the `build_prompt` function as well:
```zsh
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_end
  git-radar --zsh --fetch
}
```

@hiberabyss the `agnoster` theme doesn't currently have that flag enabled. We're looking to standardise that, though.

**Comment by hendrikstier** [comment]
@mcornella Thanks for the hint, works just fine!
