### ISSUE TITLE
Syntax for "for" loops different when sourcing and executing a file

### ISSUE THREAD

**Issue by mulchy** [robbyrussell/oh-my-zsh#4295]
I don't know much about shell scripting so this might not be an actual issue, but I noticed this after upgrading to the latest version `zsh 5.0.5 (x86_64-apple-darwin14.0)`

```
λ Naboo ~ → cat hello.zsh
#!/bin/zsh
for x (1 2 3); do echo $x; done

λ Naboo ~ → chmod +x hello.zsh
λ Naboo ~ → ./hello.zsh
1
2
3
λ Naboo ~ → source ./hello.zsh
./hello.zsh:4: parse error near `\n'
```

**Comment by mcornella** [comment]
Which shell are you using to source? Run `echo $SHELL && $SHELL --version` to be sure.

**Comment by mcornella** [comment]
ping @mulchy

**Comment by apjanke** [comment]
Does that file maybe have DOS mode line endings? I wasn't able to reproduce that error message by running it under any shell; ksh, csh, and so on all gave different syntax errors. But converting it to DOS mode and sourcing it in zsh gives that exact error.

```
$ unix2dos hello.zsh 
unix2dos: converting file hello.zsh to DOS format...
[~/tmp]
$ source ./hello.zsh 
./hello.zsh:4: parse error near `\n'
```

**Comment by mcornella** [comment]
I'm closing this, @mulchy. If you see this and you're still having the same problem, feel free to reopen it or comment.

**Comment by mulchy** [comment]
@mcornella Sorry for not responding. I just tried to reproduce this on my other machine and was unable to. It must have been DOS line endings as @apjanke was suggesting. Thank you both for the help

**Comment by mcornella** [comment]
That's ok. Thanks for replying back!
