### ISSUE TITLE
atom plugin not working on ubuntu

### ISSUE THREAD

**Issue by luisrudge** [robbyrussell/oh-my-zsh#4297]
```bash
luis@luisrudge-ubuntu  ~/code/   master  att
zsh: command not found: at
```

**Comment by hacfi** [comment]
@luisrudge Did you install the shell commands in atom?

**Comment by luisrudge** [comment]
I only installed the .deb package. I have to install something else? Sorry, I'm a linux newbie :|

**Comment by mcornella** [comment]
You don't actually need the atom plugin. Just call `atom` and it should open fine.

**Comment by robobenklein** [comment]
Fixed in https://github.com/robbyrussell/oh-my-zsh/pull/4342

**Comment by mcornella** [comment]
Please close

**Comment by robobenklein** [comment]
Atom plugin removed in https://github.com/robbyrussell/oh-my-zsh/commit/0516a39dec64568f6db194d143a0ae2969c3cf9b
