### ISSUE TITLE
Incomplete Zsh installation instructions for Ubuntu

### ISSUE THREAD

**Issue by eyalev** [robbyrussell/oh-my-zsh#4298]
I followed the instructions here: https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH

But `echo $SHELL` kept outputting `/bin/bash`

I followed the instructions here: http://askubuntu.com/questions/195361/chsh-s-usr-bin-zsh-not-working

Logging out and in solved the problem.

Should the wiki get updated?

Thanks

**Comment by mcornella** [comment]
You're right, if there's change of the shell the user needs to log out. I'll update the wiki

**Comment by mcornella** [comment]
Done. How's that now?

**Comment by eyalev** [comment]
Looks good. Thanks!
