### ISSUE TITLE
The autoenv plugin doesn't seem to do anything

### ISSUE THREAD

**Issue by harrislapiroff** [robbyrussell/oh-my-zsh#4312]
I have `.env` files in a bunch of directories, but I always have to `source` them manually. Am I doing it wrong?

This is my `.zshrc`:

```zsh
# Path to your oh-my-zsh installation.
export ZSH=/Users/harris/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git, git-prompt, autoenv, virtualenvwrapper, thefuck)

# User configuration

export PATH=$HOME/bin:$PATH                # user scripts
export PATH=/usr/local/bin:$PATH           # homebrew
export PATH=/usr/local/sbin:$PATH          # more homebrew
export PATH=/usr/local/share/npm/bin:$PATH # npm
export PATH="$HOME/.rvm/bin:$PATH"         # rvm

source $ZSH/oh-my-zsh.sh

precmd () {
}

# Display status of last command as a traffic light.
RPROMPT="%(?.%F{green}.%F{red}%? )%{%G•%}%f"
```

**Comment by mcornella** [comment]
Do you get [this message](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/autoenv/autoenv.plugin.zsh#L3-L7)? If not, then there might be something wrong with your autoenv installation...

Or it may be since we removed the custom `cd` function, before it used `autoenv_cd` by default (see [commit](https://github.com/robbyrussell/oh-my-zsh/commit/4c91f6d13e32d7389cae299d96f6778451a45fc8#diff-f7d0a3ef1bc4893bc37a320a5c593e70R32). Since when does that happen?

**Comment by harrislapiroff** [comment]
I do not get that message! Hm.

**Comment by mcornella** [comment]
Can you check if running autoenv_cd <directory> works correctly?

**Comment by harrislapiroff** [comment]
hm: `zsh: command not found: autoenv_cd`

I'm going to try reinstalling autoenv with homebrew and see if that changes anything. Will report back.

**Comment by harrislapiroff** [comment]
That did not fix it, but it does seem to work if I manually run `source $HOME/.autoenv/activate.sh`.

**Comment by mcornella** [comment]
You mean `autoenv_cd` works right? I have no idea why sourcing manually would work but the plugin doesn't. Let me get back at you later

**Comment by harrislapiroff** [comment]
Actually if I run the source line manually, even `cd` seems to run autoenv.

**Comment by mcornella** [comment]
Ok, that is because [autoenv defines a custom `cd` function](https://github.com/kennethreitz/autoenv/blob/master/activate.sh#L143-L145). From your home directory, run a new zsh session with tracing enabled (`zsh -xv &> tracing.log`), then run `exit` and post the `tracing.log` file in a gist.

**Comment by harrislapiroff** [comment]
Here it is! https://gist.github.com/harrislapiroff/4962f5206466451d6ec0

**Comment by harrislapiroff** [comment]
OH

**Comment by mcornella** [comment]
Heh, the commas shouldn't be there :grin:

**Comment by harrislapiroff** [comment]
I think the problem was that I was including commas between plugin names. Seems to be solved now.

**Comment by harrislapiroff** [comment]
Ahahaha, yeah. Silly me.

**Comment by harrislapiroff** [comment]
Thanks for your help!

**Comment by mcornella** [comment]
:+1: Cool, you can delete the gist now. Relevant part:
```
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:67> plugin=git,
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:68> [ -f /Users/harris/.oh-my-zsh/custom/plugins/git,/git,.plugin.zsh ']'
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:70> [ -f /Users/harris/.oh-my-zsh/plugins/git,/git,.plugin.zsh ']'
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:67> plugin=git-prompt,
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:68> [ -f /Users/harris/.oh-my-zsh/custom/plugins/git-prompt,/git-prompt,.plugin.zsh ']'
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:70> [ -f /Users/harris/.oh-my-zsh/plugins/git-prompt,/git-prompt,.plugin.zsh ']'
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:67> plugin=autoenv,
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:68> [ -f /Users/harris/.oh-my-zsh/custom/plugins/autoenv,/autoenv,.plugin.zsh ']'
+/Users/harris/.oh-my-zsh/oh-my-zsh.sh:70> [ -f /Users/harris/.oh-my-zsh/plugins/autoenv,/autoenv,.plugin.zsh ']'
```
