### ISSUE TITLE
Should export PATH contain $PATH in .zshrc?

### ISSUE THREAD

**Issue by vassyz** [robbyrussell/oh-my-zsh#4317]
To make [RVM](https://rvm.io/) work, I had to add **:$PATH** at the end of PATH in .zshrc:

```
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
```

Shouldn't that be a default?

**Comment by apjanke** [comment]
There's an ongoing discussion about this in #1359 and #2589.

**Comment by mailinglists35** [comment]
Why does this requires an 'ongoing discussion'?

why is so difficult to restore default behaviour?

why do I have to manually restore PATH?

**Comment by mailinglists35** [comment]
@vassyz hah, looking at differences between distribution-shipped zshrc and OMZ zshrc, OMZ explicitely overrides PATH. I've only commented that line (line 97) and now I've got default good PATH as root.
`#export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"`

**Comment by mcornella** [comment]
This is fixed on the current version of the installer.
