### ISSUE TITLE
OS X - How to set up themes?

### ISSUE THREAD

**Issue by ffxsam** [robbyrussell/oh-my-zsh#4318]
I'm a little confused on how to set up zsh. I've got `agnoster.zsh-theme` and I've put it in ~/.oh-my-zsh/themes`. These are the contents of my `~/.zshrc` file:

```
ZSH_CUSTOM=~/.oh-my-zsh
ZSH_THEME=agnoster
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/samh/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
```

When I start a new zsh shell, the theme doesn't appear to be active. Am I missing something?

**Comment by apjanke** [comment]
Your `~/.zshrc` does not appear to be loading Oh My Zsh. And normally `$ZSH`, not `$ZSH_CUSTOM`, is pointed at `~/.oh-my-zsh`.

Have you installed Oh My Zsh? The whole thing needs to be installed for it to work.

**Comment by ffxsam** [comment]
Oops. Got it now, thanks!
