### ISSUE TITLE
Don't understand how to get Powerline fonts working

### ISSUE THREAD

**Issue by ffxsam** [robbyrussell/oh-my-zsh#4319]
I'm on Mac OS, and I've installed OMZ, and set my theme to agnoster. I've installed the Powerline fonts via the install script, but when I set iTerm's font to Source Code Pro for Powerline, I still see garbage characters in my prompt. Is there something I missed?

**Comment by apjanke** [comment]
You might be using an old version of the Powerline fonts. They made a breaking change a while back when they switched which private-use code points they used for the special characters (see #4001). You need the most recent version from [the official powerline/fonts repo](https://github.com/powerline/fonts). Did you download them recently?

**Comment by ffxsam** [comment]
Yes, I cloned that repo and ran `install.sh`.

**Comment by ffxsam** [comment]
Oops! I forgot to change iTerm's "font for non-ASCII." Works fine :) My mistake

**Comment by mcornella** [comment]
Hey don't forget to close this issue! Thanks!
