### ISSUE TITLE
Meteor plugin needs a reboot

### ISSUE THREAD

**Issue by ffxsam** [robbyrussell/oh-my-zsh#4321]
Not necessarily a request for someone else to fix, just putting the issue in so it's here as a to-do :) The Meteor plugin is out of date, and actually the package completion doesn't work as it should.

Could someone tell me how to make a plugin? What language is used?

**Comment by mcornella** [comment]
Hi @ffxsam, there are 3 open pull requests regarding the meteor plugin, see if any of them are correct at #4327.
