### ISSUE TITLE
golang path completions slightly broken

### ISSUE THREAD

**Issue by pizzaops** [robbyrussell/oh-my-zsh#4323]
Hey there. Golang's completions for ohmyzsh are awesome, but they seem to break path autocompletion.

E.g. if I try to `go run` and I'm one directory up from my go files, it won't autocomplete the subdirectory names at all. It will however autocomplete the `.go` files within the subdirectory once I type the directory manually.

E.g.

``` shell
LOLcalhost :: Learning/Go/golang-book ‹master*› % go run ch 
LOLcalhost :: Learning/Go/golang-book ‹master*› % # above won't tab complete dir names
LOLcalhost :: Learning/Go/golang-book ‹master*› % go run chapter4/
dynamic_vars.go  main.go          test_types.go
LOLcalhost :: Learning/Go/golang-book ‹master*› % # above WILL tab complete filenames, as seen
```

Anyway, keep up the good work in general! <3

**Comment by apjanke** [comment]
Where did you get the `golang-book` repo from? Is that something public I could use to reproduce this?

And is this still happening after #4331?

**Comment by pizzaops** [comment]
@apjanke pretty sure golang-book is just a directory tree I made.

Not doing much go work lately but I'll be coming back to this eventually.
