### ISSUE TITLE
_arguments:440: command not found: cache_stat_timeout=

### ISSUE THREAD

**Issue by twz915** [robbyrussell/oh-my-zsh#4325]
when I input:
sshfs -C -o reconnect user@host:MetaData ./Meta
At this time, press TAB

_arguments:440: command not found: cache_stat_timeout=
_arguments:440: command not found: cache_stat_timeout=
_arguments:440: command not found: cache_stat_timeout=

How could I fix this?
mac 10.10.5

**Comment by apjanke** [comment]
Same thing happens for me in zsh 5.0.2 and 5.0.8 on OS X 10.9.5 even when Oh My Zsh is not running. Looks like an issue with zsh's own completion for `sshfs`. (It's in `/usr/share/zsh/5.0.2/functions/_sshfs` on most systems.)

Looks like they're aware of it: the zsh ChangeLog [indicates a recent fix for `sshfs` completion](https://github.com/zsh-users/zsh/blob/45e67c35529a27c2d228c616e5bafad2164e9bd6/ChangeLog#L294-L298).
