### ISSUE TITLE
Oh My Zsh customisation strange issue?

### ISSUE THREAD

**Issue by nntoan** [robbyrussell/oh-my-zsh#4326]
Greeting world,

I have a strange problem with Oh My Zsh customisation. Here is my custom directory

```
.oh-my-zsh-custom
├── plugin
│   ├── example
│   │   └── example.plugin.zsh
│   └── example_script.zsh
├── themes
│   └── custom.zsh-theme
├── lib
│   ├── variables.zsh
│   ├── exporting.zsh
│   └── lovely_function.zsh
└── secret
    └── .gitignore
```

As far as I know every files in `$ZSH_CUSTOM/lib` will be source by `oh-my-zsh.sh` by default.

This is my `$ZSH_CUSTOM/lib/lovely_function.zsh`

```bash
export OSX_SUPERB="$ZSH_CUSTOM/plugins/osx-superb"
export SUPERB_ALIAS="$ZSH_CUSTOM/plugins/superb-aliases"

function upgrade_oh_my_zsh_custom() {
  env ZSH_CUSTOM=$ZSH_CUSTOM /bin/sh $ZSH_CUSTOM/tools/upgrade.sh
}
```

And now is the most fun part, the variable I exported in this file are good, but my function `upgrade_oh_my_zsh_custom` wasn't.

After I reload it by `source` command. That function will be able to use...

The question here is **WHY**?

**Comment by mcornella** [comment]
> As far as I know every files in `$ZSH_CUSTOM/lib` will be source by oh-my-zsh.sh by default.

That's actually not true. Files in `$ZSH_CUSTOM/lib` will only be sourced if they override a file in the normal lib folder. This means that files of other names won't be sourced (this includes your `variables.zsh`, `exporting.zsh` and `lovely_function.zsh` files).

If you want to have them actually sourced, you need to put them at the root of your `$ZSH_CUSTOM` directory, not inside the `lib` folder. But keep in mind that these files will be loaded *after* your plugins have been loaded.

**Comment by nntoan** [comment]
I saw these lines and thought it will auto sourced by default

```bash
for config_file ($ZSH/lib/*.zsh); do
  custom_config_file="${ZSH_CUSTOM}/lib/${config_file:t}"
  [ -f "${custom_config_file}" ] && config_file=${custom_config_file}
  source $config_file
done
```
After look back, then I know why.

Thanks for your response.
