### ISSUE TITLE
autojump plugin issues

### ISSUE THREAD

**Issue by xuanj** [robbyrussell/oh-my-zsh#4332]
/usr/local/Cellar/autojump/21.7.1/etc/autojump.bash:13: command not found: complete
/usr/local/Cellar/autojump/21.7.1/etc/autojump.bash:52: = not found
j doesn't work

**Comment by apjanke** [comment]
The "complete" error is probably happening because you're running the `bash` version of autojump's initialization inside `zsh`.

There's a newer version of `autojump` out; maybe it has better shell detection. Try doing a `brew update && brew upgrade` and see if that improves things.

**Comment by xuanj** [comment]
@apjanke  Thanks,problem solved by brew update && brew upgrade.

**Comment by apjanke** [comment]
Cool. Could you close out this issue then?
