### ISSUE TITLE
Chucknorris strfile

### ISSUE THREAD

**Issue by rogoit** [robbyrussell/oh-my-zsh#4334]
Hi,

when i add the chucknorris plugin i get this

/.oh-my-zsh/plugins/chucknorris/chucknorris.plugin.zsh:2: command not found: strfile

See you

**Comment by icholy** [comment]
My guess is that the `strfile` command is not found. In ubuntu, it comes in the `mod-fortune` package.

``` sh
sudo apt-get install mod-fortune
```

**Comment by apjanke** [comment]
Yeah, it's part of fortune. There's a PR #4121 out to produce a more helpful warning about this.

**Comment by jaycaetano** [comment]
> ```shell
> sudo apt-get install mod-fortune
> ```

sudo: apt-get: command not found using iTerm2 macOS Mojave

**Comment by apjanke** [comment]
Yep. `brew install fortune` will get you what you need. [Install Homebrew first](https://brew.sh/) if you don't already have it.

**Comment by snowoverride** [comment]
> sudo apt-get install mod-fortune

Correct command is ``sudo apt-get install fortune-mod``

**Comment by Roberto919** [comment]
After using the `brew install fortune` command and including the chuck norris plugin `plugins=(chucknorris)`, I'm trying the execute the command `chuck_cow` but I'm getting the following error message:
`zsh: command not found: cowthink`
I have the feeling that this a very basic question, but how can I surpass this error so I can finally see chuck norris jokes in my terminal? :'v

**Comment by apjanke** [comment]
> `zsh: command not found: cowthink`

Sounds like you need the `cowsay` package installed on your system. `cowthink` is a command provided by Cowsay; it doesn't come with zsh itself. `brew install cowsay` if you're on Mac; check your Linux distro provider's package repository if you're on Linux.

**Comment by ALara001** [comment]
Im trying to run the chuck_cow command but i get a error message saying chucknorris depends on strfile, which is not installed. strfile is often provided as part of the 'fortune' package. I have fortune installed and it works. any suggestions? running on macOS 13.0.1

**Comment by mcornella** [comment]
According to https://github.com/Homebrew/homebrew-command-not-found/blob/383b5067f49f913dfb11af7c5e930c9b795b80d5/executables.txt#L1582 the `strfile` command should be provided by Homebrew's `fortune` package. If you don't have it perhaps you can install it that way.

**Comment by ALara001** [comment]
> According to https://github.com/Homebrew/homebrew-command-not-found/blob/383b5067f49f913dfb11af7c5e930c9b795b80d5/executables.txt#L1582 the `strfile` command should be provided by Homebrew's `fortune` package. If you don't have it perhaps you can install it that way.

I've tried uninstalling fortune and reinstalling to make sure, but strfile is still not there and I'm not sure how install it. 
<img width="1128" alt="Screenshot 2022-11-13 at 2 01 54 PM" src="https://user-images.githubusercontent.com/117392033/201546781-f0caa29b-7627-4f4b-9666-32239e03511e.png">

**Comment by ALara001** [comment]
Also I have Tried on a separate computer running macOS 12.6.1 and it works just fine

**Comment by rwmitchell** [comment]
> According to https://github.com/Homebrew/homebrew-command-not-found/blob/383b5067f49f913dfb11af7c5e930c9b795b80d5/executables.txt#L1582 the `strfile` command should be provided by Homebrew's `fortune` package. If you don't have it perhaps you can install it that way.

Certainly there is a link to the source without having to use Homebrew ?

**Comment by mcornella** [comment]
It might be that the path to `strfile` is not found, but try to look for it in `/usr/local/bin/strfile`. If it is there and you can't find it, you should look at whether you have a correct `$PATH` variable.

If you still have issues, please create a new issue referencing this one and we'll track it there, as this one is very old.
