### ISSUE TITLE
After Update: omz fails to load

### ISSUE THREAD

**Issue by lightningboss** [robbyrussell/oh-my-zsh#4339]
After updating omz and after a restart of my mac the terminal says the following:

<img width="583" alt="screenshot 2015-09-10 07 47 23" src="https://cloud.githubusercontent.com/assets/11751444/9796134/ca908780-57f4-11e5-998c-fd9e2f9d8a52.png">

Everything worked fine before.

**Comment by apjanke** [comment]
Uh oh. I'm on Mac OS X 10.9.5 and OMZ is fully up to date. Working fine for me. Might be a local update error or configuration issue. Could you do a `cd ~/.oh-my-zsh; git status` check to make sure there are no local changes and the last update worked okay?

If something looks odd there, you could just reinstall it. (By doing a `git clone`, not running the `install.sh` script again; that would reset your `~/.zshrc` file.)

If that doesn't bring up anything interesting, try posting the output of `zsh -l -x 2>omz_debug.log` as a gist and we'll see if we can work through this.

**Comment by lightningboss** [comment]
The command did nothing, just opening a new instance of (the broken) zsh. I did the following: Deleting the .oh-my-zsh-Folder and reinstalled it completely (with curl). After that I restored my .zshrc-File.
