### ISSUE TITLE
Why change the update method like Vundle ？

### ISSUE THREAD

**Issue by wsdjeg** [robbyrussell/oh-my-zsh#4347]
Neobundle and vundle is a tool which is short for Vim bundle and is a Vim plugin manager!
then we only need to add this to zshrc
plugin 'username/pluginreso'
then will auto install the plugin

**Comment by mcornella** [comment]
Sorry if I did not understand correctly. You mean to ask if we can add a [`neobundle`](https://github.com/Shougo/neobundle.vim) plugin, which is a `vundle` alternative?

**Comment by wsdjeg** [comment]
I think i find what i was looked for

zsh-users / antigen
