### ISSUE TITLE
[Question/Feature Request] - Set Tab and/or Window Names Independently

### ISSUE THREAD

**Issue by BrendanThompson** [robbyrussell/oh-my-zsh#4358]
Hi there,

Basically, I want to be able to set my **tab** title to something specific when I SSH into a server, but i would like the whole window title to continue auto updating. Is this something that's currently possible? I can't see that it is. 

Thanks,

Brendan

**Comment by apjanke** [comment]
Not currently supported, but sounds useful and is something that could be looked in to. I've been wanting similar functionality myself for a while, and might tackle it if I find some spare time.

**Comment by BrendanThompson** [comment]
@apjanke awesome! Sounds good mate :)

**Comment by mcornella** [comment]
> i would like the whole window title to continue auto updating.

This is only possible if you have OMZ installed wherever you ssh.


> I want to be able to set my tab title to something specific when I SSH into a server

This is possible as it is now. You only have to disable the feature to set the title automatically with `DISABLE_AUTO_TITLE=true`, and then you can run `title [tab title] [window title]` to change the title of your tab or your terminal window.
