### ISSUE TITLE
Colors for Git in Agnoster failed

### ISSUE THREAD

**Issue by rogoit** [robbyrussell/oh-my-zsh#4363]
Hi, 

since the last update i do not get the right color for the git status.

Any idea?
Roland
![bildschirmfoto 2015-09-18 um 10 52 46](https://cloud.githubusercontent.com/assets/3101439/9955733/ab2b952e-5df3-11e5-8b75-3a481b8d7e19.png)

**Comment by mcornella** [comment]
Try running `parse_git_dirty` and let's see what you get. You can also show me what these outputs: `echo "$ZSH_THEME_GIT_PROMPT_DIRTY"; echo "$ZSH_THEME_GIT_PROMPT_CLEAN"`.

**Comment by rogoit** [comment]
parse_git_dirty
%{%}%{✔%G%}

echo "$ZSH_THEME_GIT_PROMPT_DIRTY";
*

echo "$ZSH_THEME_GIT_PROMPT_CLEAN".
%{%}%{✔%G%}.

**Comment by mcornella** [comment]
Ok here's the problem:
```
echo "$ZSH_THEME_GIT_PROMPT_CLEAN".
%{%}%{✔%G%}.
```

The agnoster theme expects (probably wrongly), that `parse_git_dirty` will return something if the repo is dirty (the default of `$ZSH_THEME_GIT_PROMPT_DIRTY` is `*`), or empty if the repo is clean (the default of `$ZSH_THEME_GIT_PROMPT_CLEAN` is `""`).

That is a shortsight of the agnoster theme, but it should be easy to fix if you put `ZSH_THEME_GIT_PROMPT_CLEAN=""` in your zshrc file (you may have it already there with a different value, which is what triggered your problem). But we should use a better logic as well in the repository.

**Comment by rogoit** [comment]
Fix thx ;)

**Comment by mcornella** [comment]
Yay!! :smile: Remember to close the issue though!
