### ISSUE TITLE
How to use docker-compose plugin

### ISSUE THREAD

**Issue by berdyshev** [robbyrussell/oh-my-zsh#4365]
Hi, I have enabled `docker` and `docker-compose` plugins. Here is the line in ~/.zshrc

```
plugins=(git github history symfony2 docker docker-compose)
```

`docker` completions works by tab, but `docker-compose` doesn't work. What I'm doing wrong?

**Comment by darkwinternight** [comment]
Funny enough, for me it's the other way round.

**Comment by evsign** [comment]
Not working too

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` and restarting the shell when enabling a plugin that provides completion.

**Comment by evsign** [comment]
Thats work! thanks!
