### ISSUE TITLE
Unexpected behavior with up arrow when newlines in history

### ISSUE THREAD

**Issue by bobwhitelock** [robbyrussell/oh-my-zsh#4374]
In a basic Zsh install with nothing in my `.zshrc`, if I enter commands like the following:

```
% ls                      
% ( 
subsh> ls
subsh> )
% cd
% 
```

and then push the up arrow repeatedly (with the prompt initially empty), I get shown `cd`, then the subshell with each line in turn, and then `ls`.

However if I do the same when using `oh-my-zsh` I get shown `cd`, then go through the subshell lines, and then when the `(` is reached further presses of the up arrow go through any previous lines containing just `(` (or does nothing if none of these exist).

To me at least this seems unexpected and I would expect it to work more like the `zsh` default. If I'm pressing up starting from an empty history I would expect to be shown each of my previous commands in turn rather than each up to a certain point and then not be able to view further.

I would guess this is to do with `oh-my-zsh` searching history based on the first input word but I'm not exactly sure what's causing it. I've also noticed the same thing in other situations where a command takes up multiple lines, which is why I think it's to do with the newlines in the history.

**Comment by apjanke** [comment]
That is unexpected, and probably not what' s intended. 

I can't reproduce this. On OS X 10.9/zsh 5.0.2 with OMZ loaded (with `plugins=( osx themes nyan sublime brew vagrant emoji ) `), if I do this:

```
➜  ~  ls
AT.postflight.11860  Downloads  Movies    Public    local    stats
Desktop              Dropbox    Music     archives  luggage  tmp
Documents            Library    Pictures  bin       misc     var
➜  ~  (
subsh> echo foo
subsh> echo bar
subsh> )
foo
bar
➜  ~  cd
```
then when I use the up arrow, repeated presses show me:
* `cd`
* The 
```
(
echo foo
echo bar
)
```
multi-line command, as a single history entry
* `ls`

Maybe it's some additional configuration you have, or a different plugin? Could you run `omz_diagnostic_dump` (available in the latest OMZ update), and post the output as a gist?

**Comment by BobWhitelock** [comment]
Hi, thanks for checking this out. I thought this was probably something to do with some atypical configuration of mine or similar; to try and avoid this I tried the same in a fresh VM, with the same result. Here's the result of `omz_diagnostic_dump` in that VM: https://gist.github.com/BobWhitelock/219dc5924cc1eae8372e.

**Comment by apjanke** [comment]
Okay, I can reproduce on an up-to-date non-Vagrant Ubuntu 14.04 VM (in VMware Fusion running on OS X 10.9). Works fine with normal zsh 5.1.1 and OMZ, but when I copied your `.zshrc` from that diagnostic dump over to mine, then I got the bad behavior. (Maybe I had custom settings that were avoiding it earlier.) Will look in to it more when I have a chance.

**Comment by erlendfh** [comment]
I recently ran into the same problem, what solved it for me was adding `export LANG='en_US.UTF-8'` at the beginning of `.zshrc`.

**Comment by mcornella** [comment]
Can reproduce and @erlendfh's solution doesn't work. With zsh 5.1.1 and these two key bindings:
```
bindkey ^[OA up-line-or-search
bindkey ^[OB down-line-or-search
```
where `^[OA` and `^[OB` are the character sequences for up and down arrow (YMMV).

Unfortunately I think that's the documented behavior, see [up-line-or-search](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#index-up_002dline_002dor_002dsearch):
> Move up a line in the buffer, or if already at the top line, search backward in the history for a line beginning with the first word in the buffer.

You can use `up-line-or-beginning-search` which does the same but puts the cursor in the first line, therefore not triggering your use case.
