### ISSUE TITLE
install.sh fails if tput isn't available

### ISSUE THREAD

**Issue by fcrozat** [robbyrussell/oh-my-zsh#4376]
on some reduced system (Synology NAS), tput isn't available, causing install.sh script to fail to run. Fix incoming

**Comment by mcornella** [comment]
@apjanke

**Comment by apjanke** [comment]
Wow, I didn't even know there were systems skinny enough to not have `tput`.

The fix looks good to me. I don't have a `tput`-less system to test on right now, but I tested it on OS X to at least verify that it doesn't interfere with the normal case.

We should do the same thing to `tools/upgrade.sh` so you don't get surprised by the same problem a week from now when OMZ updates itself.

**Comment by apjanke** [comment]
Can you close this if the PR worked?

**Comment by WhyEee** [comment]
@fcrozat's original fix assumes which not to output anything to STDOUT in case the command is not found. That is not necessarily true on all systems. A better solution is to check the return value instead.
