### ISSUE TITLE
command not found: compdef

### ISSUE THREAD

**Issue by 2Dou** [robbyrussell/oh-my-zsh#4378]
After update 9c08641 to 918d26e，I got this error:
```
.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
```

now versions:
```
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

```
9c08641: (Sat Sep 5 13:30:44 2015) <Robby Russell>    Merge pull request #4299 from mcornella/refactor-frontend-search-plugin
918d26e: (Sun Sep 20 05:17:15 2015) <Robby Russell>  Merge pull request #3664 from apjanke/installer-portable-colors
```

**Comment by DomT4** [comment]
Ran around screaming trying to fix this earlier. Can't find the other thread now, but answer seems to be:

Run `chmod g-w` on anything `compaudit` complains about & then run `compinit`.

**Comment by 2Dou** [comment]
@DomT4 Thank you. It did for me.

**Comment by serkanyersen** [comment]
for others that this solution did not work, `chmod 755` worked for me.
