### ISSUE TITLE
zsh:1: url-quote-magic: function definition file not found

### ISSUE THREAD

**Issue by schoeke** [robbyrussell/oh-my-zsh#4379]
Starting my terminal, every input is answered with `zsh:1: url-quote-magic: function definition file not found`. I deleted zcompdump, but can't do much more, as the required functions are not accessible to others shells.

I commented the line concerning url-quote-magic in lib/misc.zsh but now completion does not work even when a new shell is started and fails with `-zsh:5: _main_complete: function definition file not found`. I tried resetting the completion in accordance with https://github.com/robbyrussell/oh-my-zsh/issues/630#issuecomment-70291622 but I get a `zsh: compaudit: function definition file not found`.

zsh 5.1.1 (x86_64-apple-darwin14.5.0) on Mac OS X Yosemite with brew.

**Comment by mcornella** [comment]
Which zsh version do you have? Run `zsh --version`

**Comment by schoeke** [comment]
I was updating the initial post as you answered. Entered it there.

**Comment by mcornella** [comment]
Try the following PR: #4337

**Comment by schoeke** [comment]
I added the file, but I still get `-zsh:1: url-quote-magic: function definition file not found` with every keypress.

**Comment by schoeke** [comment]
I found the problem. $fpath contained a non-existent folder `/usr/local/Cellar/zsh/5.0.8/share/zsh/functions`. Instead, it should be 5.1.1. However, I do not know where this part gets added to $fpath. Quick fix for now was to copy the 5.1.1 to 5.0.8.

**Comment by schoeke** [comment]
The problem reoccured with the next zsh update to version 5.2. Can somebody point me to in which file the fpath should be updated?

**Comment by lsdriscoll** [comment]
anybody got a fix for this?

**Comment by xiaokunx** [comment]
This is a still a gem in late 2017. I've finally upgraded one of my mac to High Sierra. Previous I've only zsh 5.2 installed at /usr/local/bin/. Somehow after the grade, the zsh was also automatically upgraded to 5.3.1. Therefore the line hard-coded zsh5.2 in my ~/.zshrc was broken and throw the error shown above.

So the fix is to find out the version of your zsh. Then grep 'zsh/5.2' ~/.zshrc, and update it with your current version of zsh.

**Comment by mcornella** [comment]
You could just use `$ZSH_VERSION` to build the path: `/usr/local/Cellar/zsh/$ZSH_VERSION/share/zsh/functions`. To be clear though, is this something you get because of OMZ or is it a problem with your environment?

**Comment by schoeke** [comment]
Ah, didn't answer this yet. It is an environment problem, that occurs if the brew version of zsh on mac OS is used. But I only understood this after somebody pointed me towards the right direction here.

**Comment by schoeke** [comment]
`$ZSH_VERSION` is btw not working all the time as brew has some times other naming schemes. The best way to find the correct path is `brew info --json=v1 zsh | jq .[0].linked_keg`.

**Comment by DeepikaKaranji** [comment]
As mentioned before, the issue occurs when zsh is upgraded to a new version. 
Here is my fix for it:
1. Do `zsh --version` -- will result in say 5.8.1
2. `vim .zshrc`
3. search for `fpath`. Check if `/usr/share/zsh/<zsh version>/functions` is present. Most likely, you will not see the latest version of zsh, but some previous version number there. Change it to the version you got in step 1.
4. save changes
5. Open new terminal window and run `exec zsh`
6. Now try cd <tab> --> auto complete should work perfectly now.

Cheers.

**Comment by wdeshazer** [comment]
I encountered this issue and couldn't find  anywhere with an explicit reference to <zsh version>. After searching harder, I came arcross `carlosala' solution here [Response to 'Where should I load custom completions'](https://github.com/ohmyzsh/ohmyzsh/discussions/11342#discussioncomment-4167614), quoted here for convenience

> 
> You need to add a file named `_forc` with the completion inside in a directory that is present in `$fpath`. Then you need to delete `$ZSH_COMPDUMP` file and do `omz reload`. After that, you should be good to go.
> Seeing the documentation it would be `forc completions --shell=zsh > /path/that/is/in/fpath/_forc`
