### ISSUE TITLE
Make a theme repo and sort them by population!

### ISSUE THREAD

**Issue by lijunle** [robbyrussell/oh-my-zsh#4380]
I have a newbie to zsh and oh-my-zsh.  I find that there are [a lot of themes](https://github.com/robbyrussell/oh-my-zsh/wiki/themes). I don't know which one is good, which one is most popular.

Why not host a website to for themes and sort them by their download count (or :star: count)? Then, there resolve the [*Don’t Send us your theme!*](https://github.com/robbyrussell/oh-my-zsh/wiki/themes#dont-send-us-your-theme-for-now)" problem.

**Comment by apjanke** [comment]
This would be a lot of work: it would require re-designing OMZ to be modular with respect to themes, hosting the themes (to do download tracking), and/or building a dynamic website for tracking user stars, and then getting the community to go vote for themes on the website, which in most cases gives pretty lousy results. And getting a clean data set that actually indicated the usage levels of themes would be difficult, given the noise from re-downloads, multiple installations, people downloading a theme just to try it out, and so on.

Maybe making a new Wiki page for discussing themes would be an adequate alternative?

You could also look at Prezto and Antigen, which are OMZ alternatives that use modular designs, to see if they have any theme popularity info.

**Comment by pradyunsg** [comment]
How about allowing install from arbitrary places like Github repositories like antigen?

**Comment by mcornella** [comment]
We're in no shape to do such a thing. Right now there's the [External themes](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes), and as you said there is antigen. 

Perhaps we could build some kind of central repository for users' configurations and themes but that would require a joint effort not just from the Oh My Zsh community which, to be honest, is in a very bad shape in terms of maintenance.

So, right now, we cannot even consider such a thing. We have put in place the external themes wiki and let's leave it there for the moment.
