### ISSUE TITLE
New zsh pull, messed up my system :( please help. 

### ISSUE THREAD

**Issue by rjrobinson** [robbyrussell/oh-my-zsh#4382]
I updated to the latest version. And it messed me up a little... 

not sure what to do. I have oh-my-zsh in a .dotfile dir

here is my edited zshrc file 
```
echo "You is logged in.... "
export ZSH=$HOME/.dotfiles/oh-my-zsh

export ZSH_THEME="clean"

export CASE_SENSITIVE="false"
plugins=(brew cloudapp colorize compleat dirpersist gem git git-flow github osx mvn node npm nvm rv rails )

source $ZSH/oh-my-zsh.sh

export NVM_DIR=~/.nvm
source /usr/local/opt/nvm/nvm.sh

export PATH="$PATH:bin/subl"
export PATH="$PATH:/Users/rrobin008c/.nvm/versions/node/v0.12.7/bin/node"
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin"

#NVM
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

LUNCHY_DIR=$(dirname `gem which lunchy`)/../extras
  if [ -f $LUNCHY_DIR/lunchy-completion.zsh ]; then
    . $LUNCHY_DIR/lunchy-completion.zsh
  fi
nvm use stable

# export PATH="/usr/local/sbin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting```


Any help would be great. None of my aliases work, In fact, it had over ridden the file. idk what happened....

**Comment by mcornella** [comment]
Can you post the rest of your dotfiles directory?
And what do you mean that "it had overridden the file"? Which file?

**Comment by apjanke** [comment]
> export PATH="$PATH:bin/subl"

That `bin/subl` is a relative path so it won't work in most situations. Maybe it should be `~/bin/subl` instead? You can also omit the `export`s from those `$PATH` setting lines: `$PATH` is already marked for export, and it stays exported through changes to its value.

Can you give us a specific example of what's not working? Like, an alias that was working before, and how it's behaving now? When you say "my aliases", do you mean aliases that you have defined yourself, or aliases defined by OMZ that you use?

The final "```" for quoting code in GitHub markdown needs to be on a line by itself. Right now, the fixed-width formatting is leaking to the rest of your comment.

**Comment by rjrobinson** [comment]
I'll close this issue. Im not really sure what happened. But i reconfigured everything. 

It asked if I wanted to upgrade. I pressed `Y` , and just like that, all of my custom configurations were gone. painful 2 days. Its all backed up double redundantly now.

**Comment by apjanke** [comment]
Where are you putting your custom configurations? We wouldn't want this to happen to you again.

**Comment by rjrobinson** [comment]
In the `oh-my-zsh/lib` folder, i had a `alias.zsh` file , and a `my_functions.zsh` file.

**Comment by apjanke** [comment]
Hmmm. The OMZ upgrade should have left those alone; it uses a `git pull` mechanism that just I think ignores untracked files it doesn't recognize. (I tested it now to make sure, creating those files and running the upgrade a few times. They survived. But maybe there was something different about when you upgraded and picked up more live commits. I'll see if I can figure out how to set up a better test that can create a "stale" local repo.)

For extra safety and convenience, I like to keep my OMZ customizations in a separate `$ZSH_CUSTOM` directory at `~/.oh-my-zsh-custom`, which is itself a Git repo that I have [hosted on GitHub](https://github.com/apjanke/oh-my-zsh-custom) and Bitbucket. Makes it easy to get it on multiple machines and make sure my stuff isn't lost. OMZ really does expect user customizations to go in a different directory, either under `custom/` inside the main `.oh-my-zsh` directory, or a separate custom dir.

**Comment by rjrobinson** [comment]
Ok. Thanks so much!
