### ISSUE TITLE
Git syntax for `^..` and `..` does not work with zsh

### ISSUE THREAD

**Issue by ddelnano** [robbyrussell/oh-my-zsh#4398]
Lets say I have commits with hashes of A and B and I want to see the diff between the two.  I would issue a command like `git diff A^..B`.  However when I do this in zsh I get the following.

![screen shot 2015-09-24 at 8 49 45 am](https://cloud.githubusercontent.com/assets/5855593/10073789/5c9f83ac-6299-11e5-92b6-9426961e9b6a.png)

Running the same command with bash works however.

![screen shot 2015-09-24 at 8 51 29 am](https://cloud.githubusercontent.com/assets/5855593/10073809/8549b1a6-6299-11e5-9df1-cbf680c6e467.png)

Does anyone have any idea what the issue is here?

**Comment by apjanke** [comment]
The `^` is a special character in zsh [filename or history expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Expansion). Maybe you have a shell option enabled that's causing it to be treated as that, instead of a literal `^` to be passed to the command? (It works for me in my default `zsh` and OMZ configurations.)

Try sticking that argument in single quotes. If that fixes it, it's an expansion thing of some sort, and you can dig in to your options and shell parameters to see what could be causing it. Also check to see if `git` has been aliased or redefined.

**Comment by apjanke** [comment]
(BTW, when posting bug reports like this, it's helpful to include a text copy of your terminal session in addition to the screenshots, so people can copy and paste the commands to try to reproduce it.)

**Comment by mcornella** [comment]
You can use `noglob` to avoid treating `^`, `*` and other globbing characters as such. You can use an alias, and to make it permanent put it in your `zshrc` file:
```
$ alias git
git='noglob git'
```

**Comment by ddelnano** [comment]
Wrapping the A^..B in single quotes did the trick.  So as you said must be an expansion issue.  As for what you said about posting bug reports your right except no one else is gonna have the commit history I have so providing the commit hashes is useless that is why I chose not to do that.  Thanks for the help! @mcornella I will look into configuring that like you suggested.

**Comment by apjanke** [comment]
Good point; didn't know if this was a private repo.

Weird thing is, I don't have `git` aliased, and I don't need to enclose it in quotes in my `zsh` session. 

```
[~/.oh-my-zsh on ⇄ master]
$ git diff cbc1a0806e910f7b4eed07b992d3d88ff7cb1162^..76a26a2a59d8c6d0f65a4426cdb93920e255aea7 | cat | head
diff --git a/plugins/atom/README.md b/plugins/atom/README.md
index 75d77a0..6350c64 100644
--- a/plugins/atom/README.md
+++ b/plugins/atom/README.md
@@ -1,6 +1,8 @@
 ## atom

-Plugin for Atom, a cross platform text and code editor, available for Linux, Mac OS X, and Windows.
+This plugin makes "at" a useful function for invoking the Atom Editor.
+
```

Maybe it's a shell option or similar setting? Here's what I have.

```
$ setopt
alwaystoend
autocd
noautomenu
nobeep
cdablevars
extendedhistory
histexpiredupsfirst
histignoredups
histignorespace
histverify
ignoreeof
incappendhistory
interactive
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
shinstdin
zle
$ echo $histchars
!^#
```

**Comment by apjanke** [comment]
Aha! It's `EXTENDED_GLOB`, which enables `^` as a special pattern character for filename expansion.

```
[~/.oh-my-zsh on ⇄ master]
$ git diff cbc1a0806e910f7b4eed07b992d3d88ff7cb1162^..76a26a2a59d8c6d0f65a4426cdb93920e255aea7 | cat | head -1
diff --git a/plugins/atom/README.md b/plugins/atom/README.md
[~/.oh-my-zsh on ⇄ master]
$ setopt extended_glob
[~/.oh-my-zsh on ⇄ master]
$ git diff cbc1a0806e910f7b4eed07b992d3d88ff7cb1162^..76a26a2a59d8c6d0f65a4426cdb93920e255aea7 | cat | head -1
zsh: no matches found: cbc1a0806e910f7b4eed07b992d3d88ff7cb1162^..76a26a2a59d8c6d0f65a4426cdb93920e255aea7
[~/.oh-my-zsh on ⇄ master]
$
```

That's a totally valid thing to have on. I think @mcornella's right; a `noglob` may be the best way to handle this on a long term basis.

If you're using the `git` plugin aliases like `gco`, `gc`, and so on, I think you should do that `alias git=noglob git` *before* loading OMZ, so the alias affects the `git` calls inside all those other aliases, too: alias expansion is done at alias definition time, not evaluation time.

**Comment by mcornella** [comment]
Thanks for reminding me of `extended_glob`, it *is* set in my setup so that's why this issue didn't appear before...

> If you're using the git plugin aliases like gco, gc, and so on, I think you should do that alias git=noglob git before loading OMZ, so the alias affects the git calls inside all those other aliases, too: alias expansion is done at alias definition time, not evaluation time.

That's actually not my case, where have you seen this? Aliases are lazy loaded I think, you can try the following:
```
$ alias a='b'
$ alias b='echo'
$ a hello
hello
```

I have the alias right below the sourcing of OMZ, so I think it will be ok.

**Comment by apjanke** [comment]
> That's actually not my case, where have you seen this? Aliases are lazy loaded I think...

You're right; I'm just confused. I can't remember why I thought that.

**Comment by Aftab-111** [comment]
> alias git=noglob git

this shows "zsh: command not found: cherry-pick"

**Comment by mcornella** [comment]
Use quotes: `alias git="noglob git"`
