### ISSUE TITLE
Youtube-dl issue

### ISSUE THREAD

**Issue by elav** [robbyrussell/oh-my-zsh#4400]
I run on Linux Manjaro 64 Bits this command:

    $ youtube-dl https://www.youtube.com/watch?v=xu0VSKvfNEI
    zsh: no matches found: https://www.youtube.com/watch?v=xu0VSKvfNEI

What can be?

**Comment by apjanke** [comment]
The `?` is a file globbing special character like `*`. Put the URL in quotes.

**Comment by mcornella** [comment]
Additionally, if you paste the URL `url-magic-quotes` should automatically quote special characters, perhaps that's not working for you. 

Which `zsh --version` do you have?

**Comment by elav** [comment]
I have zsh 5.1.1. The rare is that before work without put \. I try this..

**Comment by mcornella** [comment]
Ok, so this must be the same problem as reported in #4337. Try the changes in that PR, see if it works correctly again.

**Comment by mcornella** [comment]
This should be working now if you update, please confirm and close.

**Comment by elav** [comment]
Nothing friends. I applied changes bug #4337, later using the command:
    upgrade_oh_my_zsh
and nothing.

**Comment by mcornella** [comment]
It should work, it did in my case. Make sure the upgrade finished correctly and restart the terminal afterwards.

**Comment by apjanke** [comment]
It's working for me too, on OS X 10.9 with iTerm2 and Terminal.app.

What terminal program are you using?

And check your `.oh-my-zsh` git status to make sure there are no local changes that might be interfering with the update.

```
[~/.oh-my-zsh on ⇄ master]
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by elav** [comment]
I use Konsole, Yakuake.. 

```
leniu510 :: ~/.oh-my-zsh » git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

Y try once again..

**Comment by apjanke** [comment]
Works for me in Konsole 2.14.2 and Yakuake 2.9.9 on Debian 8 with zsh 5.1.1: without changing my configuration, the `url-quote-magic` is getting loaded, and gets pasted in with escapes.

```
[~]
$ echo https://www.youtube.com/watch\?v\=v1K0e2Juvf0
https://www.youtube.com/watch?v=v1K0e2Juvf0
```

I don't know what's going on here. Perhaps the `nomatch` option was unset before?

Let's grab your entire configuration so we can diagnose it. Could you run `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/)?

**Comment by elav** [comment]
I use Konsole in its latest version.

```
konsole -v
QCoreApplication::arguments: Please instantiate the QApplication object first
Qt: 5.5.0
KDE Frameworks: 5.14.0
Konsole: 15.08.0
```

This is my dump » https://gist.github.com/elav/963917ce993b55d6329e

**Comment by apjanke** [comment]
Thanks.

That "core commands have been redefined" message looks scary, but it's actually fine: `omz_diagnostic_dump` just doesn't know about the new stuff in zsh 5.1.1; see #4436.

I don't recognize a lot of those `zstyle` settings.

You're also loading `zsh_syntax_highlighting`, which isn't part of OMZ. This extension also interacts a lot with ZLE, and may be having an effect here. Could you try disabling it by commenting out the following line in your `~/.zshrc`, and see if that makes a difference?
```
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

**Comment by elav** [comment]
'll try that solution you offer me. Really what I did was reinstall oh_my_zsh. I try and tell them.

Thanks guys

**Comment by mcornella** [comment]
Should be solved by #4337. We're still getting the hang of the new bracketed-paste mode so if it comes up again another issue should be opened.

**Comment by divyanshu013** [comment]
To anyone coming to this issue, a simple solution is to enclose your url inside single quotes like:

`youtube-dl 'your_video_url'`

**Comment by kodekrendel** [comment]
Got the same issue, manually adding quotes is stupid. 

How to use this fix? I can't download with `youtube-dl`

**Comment by pabloab** [comment]
FTR, other solutions are:

- [Disabling globing on zsh](https://superuser.com/a/982399/500826): `setopt NO_NOMATCH`
- Maybe better: [Use special](https://superuser.com/a/1237124/500826) [functions](http://zsh.sourceforge.net/Doc/Release/Functions.html) on [your `.zshrc`](https://coderwall.com/p/ktv3hq/zsh-autoloading-functions-i) like `url-quote-magic` to get special characters to be quotes automatically.

**Comment by gock-cpu** [comment]
> To anyone coming to this issue, a simple solution is to enclose your url inside single quotes like:
> 
> `youtube-dl 'your_video_url'`

single quotes solve my problem thx
