### ISSUE TITLE
.oh-my-zsh/oh-my-zsh.sh:40: parse error near `||'

### ISSUE THREAD

**Issue by lykhouzov** [robbyrussell/oh-my-zsh#4402]
After last git pull i got following error when open new terminal
```
/home/alykhouzov/.oh-my-zsh/oh-my-zsh.sh:40: parse error near `||'
alykhouzov@empire:~> 
alykhouzov@empire:~> echo $SHELL && $SHELL --version 
/usr/bin/zsh
zsh 5.1 (x86_64-suse-linux-gnu)
alykhouzov@empire:~/.oh-my-zsh> git branch 
* master

```
commit is 
```
commit 76a26a2a59d8c6d0f65a4426cdb93920e255aea7
```

```
alykhouzov@empire:~/.oh-my-zsh> uname -a && cat /etc/os-release 
Linux empire 4.1.6-3-desktop #1 SMP PREEMPT Fri Aug 28 10:59:34 UTC 2015 (d867e86) x86_64 x86_64 x86_64 GNU/Linux
NAME=openSUSE
VERSION="20150909 (Tumbleweed)"
VERSION_ID="20150909"
PRETTY_NAME="openSUSE 20150909 (Tumbleweed) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:20150909"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```

**Comment by mcornella** [comment]
Please post the result of `shasum $ZSH/oh-my-zsh.sh`

**Comment by ivanlemeshev** [comment]
I have the same error after upgrade.

```
lmshv% shasum $ZSH/oh-my-zsh.sh
059fc44fa5bccd75638849eac77c765dad2cb218  /Users/ivan/.oh-my-zsh/oh-my-zsh.sh
```

```
Last login: Mon Sep 28 15:35:04 on ttys003
/Users/ivan/.oh-my-zsh/oh-my-zsh.sh:40: parse error near `||'
lmshv% echo $SHELL && $SHELL --version
/bin/zsh
zsh 5.0.5 (x86_64-apple-darwin14.0)
lmshv% uname -a
Darwin lmshv.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
lmshv% git branch
* master
```

```
b05ef10 - (HEAD, origin/master, origin/HEAD, master) Merge pull request #4121 from apjanke/chucknorris-check-for-fortune (14 hours ago) <Robby Russell>
a51a916 - Merge pull request #4348 from andybateman/patch-1 (14 hours ago) <Robby Russell>
9e29103 - Merge pull request #4394 from PrestanceDesign/new-git-alias (14 hours ago) <Robby Russell>
156fa5f - Merge pull request #4396 from TylerCharlesworth/patch-1 (14 hours ago) <Robby Russell>
4b902d7 - Merge pull request #4410 from justVitalius/master (14 hours ago) <Robby Russell>
dc3413b - Fix print rvm version in amuse theme (18 hours ago) <justvitalius>
b75b0b8 - Merge pull request #4333 from mbologna/fedora_plugin (2 days ago) <Robby Russell>
935948c - Merge pull request #3646 from apjanke/installer-cygwin-support-3 (2 days ago) <Robby Russell>
b5a5bc9 - Merge pull request #4337 from iCross/master (2 days ago) <Robby Russell>
f186b62 - Merge pull request #4387 from mbologna/fix_git_equal_remote (2 days ago) <Robby Russell>
d47219f - Merge pull request #4397 from vidakovic/master (2 days ago) <Robby Russell>
c932eb3 - Merge pull request #4385 from Philosoft/patch-1 (2 days ago) <Robby Russell>
c076fc0 - Merge pull request #4392 from ag4ve/patch-1 (2 days ago) <Robby Russell>
4204cfd - Merge pull request #4408 from DoomHammer/fix-chruby-test-expression (2 days ago) <Robby Russell>
a97a308 - Merge pull request #4349 from FishingCactus/fix-atom_plugin_for_cygwin (2 days ago) <Robby Russell>
3b2d036 - Merge pull request #4377 from fcrozat/master (2 days ago) <Robby Russell>
ccc86da - Merge pull request #4375 from PrestanceDesign/capistrano-plugin-fix (2 days ago) <Robby Russell>
a861719 - Merge pull request #4340 from pahnev/master (2 days ago) <Robby Russell>
```

**Comment by mcornella** [comment]
Your init script is different than it should be. Do a `cat -v $ZSH/oh-my-zsh.sh` to see if there are any `^M` characters. If so, it might be your `git config core.autocrlf` setting that's messing with it.

**Comment by crsuarez** [comment]
@lykhouzov you could take this script  /home/alykhouzov/.oh-my-zsh/oh-my-zsh.sh and run it using -x -v flags. something like ```zsh -xv /home/alykhouzov/.oh-my-zsh/oh-my-zsh.sh``` this could give you more information for troubleshoot. Did you modify that file?

**Comment by leoleozhu** [comment]
same error after upgrade

**Comment by mcornella** [comment]
Can you guys check this https://github.com/robbyrussell/oh-my-zsh/issues/4402#issuecomment-143692774 ?

**Comment by ivanlemeshev** [comment]
I did cat -v $ZSH/oh-my-zsh.sh
And yes, there are many ^M characters in the end of lines.

**Comment by mcornella** [comment]
Ok, what's does `git config core.autocrlf` says?

**Comment by ivanlemeshev** [comment]
It says `true`.

**Comment by mcornella** [comment]
True is a reasonable setting for Windows, [but not for OSX](https://help.github.com/articles/dealing-with-line-endings/#global-settings-for-line-endings). Change that to `input` and then [refresh your files](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings) to get the line endings back to LF.

BTW there's a PR in the process of being tested that would eliminate the need of doing this again, check it out: https://github.com/robbyrussell/oh-my-zsh/pull/4071

**Comment by lykhouzov** [comment]
sorry for delay with answer
```
alykhouzov@empire:~/.oh-my-zsh> shasum $ZSH/oh-my-zsh.sh
059fc44fa5bccd75638849eac77c765dad2cb218  /home/alykhouzov/.oh-my-zsh/oh-my-zsh.sh
alykhouzov@empire:~/.oh-my-zsh> 
```

**Comment by mcornella** [comment]
It's probably the `core.autocrlf` git setting. See my comment above

**Comment by leoleozhu** [comment]
It works after resetting autocrlf. Thanks

**Comment by frizbee** [comment]
@mcornella Thank you, refreshing files helped after changed `core.autocrlf` to `input`

**Comment by mcornella** [comment]
@lykhouzov please check again your `core.autocrlf` setting (explained in https://github.com/robbyrussell/oh-my-zsh/issues/4402#issuecomment-143976458). Fixing that should fix your problems.

Feel free to reopen the issue if that doesn't solve it!

**Comment by adaofeliz** [comment]
Thanks @mcornella this https://github.com/robbyrussell/oh-my-zsh/issues/4402#issuecomment-143976458 finally solve my problem after the last update this week (Feb 2016)

**Comment by teamonn** [comment]
1. `.zshrc:3: command not found: ^M` The solution is as follows:

  `vim ~/.zshrc` then enter `:set ff=unix`

2. ```.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'  ``` The solution is as follows:
```
cd $ZSH
git config core.autocrlf input
git rm --cached -r .
git reset --hard
```

**Comment by xiaoppp** [comment]
@teamonn 
thanks, you save my day!!!
