### ISSUE TITLE
[git module] git checkout + tab bring commit hash instead of branches

### ISSUE THREAD

**Issue by behzadsh** [robbyrussell/oh-my-zsh#4403]
I have updated oh-my-zsh today, and now when I enter `git checkout` then press tab it will show me list of commits on current branch instead of branch name lists

**Comment by apjanke** [comment]
Probably related to #4395.

What `$plugins` are you loading?

**Comment by behzadsh** [comment]
Yes, It's related to that issue.

Sorry for creating duplicate issue

**Comment by apjanke** [comment]
No apology needed; we love bug reports. Chime in on the other thread if this doesn't get resolved for you.
