### ISSUE TITLE
how do I install in windows10 ?

### ISSUE THREAD

**Issue by ezekel** [robbyrussell/oh-my-zsh#4405]
Can I ask some help how can I install this in windows10 ?

Thank you in advance.

**Comment by apjanke** [comment]
Install Cygwin and run the installer from a Cygwin shell [following the normal installation instructions](https://github.com/robbyrussell/oh-my-zsh#basic-installation). Is that not working for you?

**Comment by NightRa** [comment]
Try Babun.

**Comment by mcornella** [comment]
@NightRa's suggestion: http://babun.github.io. I'm closing this one.
