### ISSUE TITLE
gco <tab> to not include remote branches

### ISSUE THREAD

**Issue by jchannon** [robbyrussell/oh-my-zsh#4406]
Is there a way for `gco <tab>` not to show remote branches?

I've done a `git fetch --all` and now when I type `gco <tab>` it shows me ALL the branches starting with XX. I would like it to only show me the local branches.

Thanks

**Comment by apjanke** [comment]
I don't think so, at least not with the current code.

The main completion logic for `git` is provided by either `zsh` itself or as part of a `git` installation, not by OMZ. You could submit this as an upstream request to either the Zsh or Git maintainers. (Zsh is more likely to do it, I'd bet.)

There is an OMZ `gitfast` plugin that provides a different implementation of `git` completion. It doesn't have an option for listing local branches only either. But if you use `gitfast`, that's something that could be added in OMZ itself. (Though it seems unlikely: it looks like that plugin is itself derived from the Git-supplied `git` bash completions.)
