### ISSUE TITLE
can not open dir!!!

### ISSUE THREAD

**Issue by wsdjeg** [robbyrussell/oh-my-zsh#4409]
with two dir named ./JavaWeb and ./javaweb
if i use cd javaweb ,return me the message
can not find the dir named javaweb

**Comment by mcornella** [comment]
Please post the output of `ls -l` in that directory, and the output of `which -a cd`.

**Comment by wsdjeg** [comment]
just now it exists!
but now it has gone!
i really do not why,maybe the issue should be closed,thank you all the same
