### ISSUE TITLE
git: pull rejected

### ISSUE THREAD

**Issue by krisnakumar** [robbyrussell/oh-my-zsh#4428]
when i take git pull, using command : " git pull origin master "  , then it shows the following message:

"cannot pull with rebase: you have unstaged changes.
Please commit or stash them." 

any one please help me to resolve this issue...
Thank you

**Comment by Mansuro** [comment]
If you made a little research you would find a solution: http://stackoverflow.com/a/23517643/612920

**Comment by mcornella** [comment]
Does this happen in the oh-my-zsh repository or somewhere else? If it's the first case, don't do anything yet, run a `git diff` and post the output here.
