### ISSUE TITLE
A plugin that make zsh search the Application to open the application?

### ISSUE THREAD

**Issue by yu-yuxuan** [robbyrussell/oh-my-zsh#4431]
Before using the zshell, in the terminal, I can type "anki" and it opens the gui of the anki. But when I do it in zshell. It shows `zsh: command not found: anki`. So is there a plugin that make zsh search the Application to open the application?

**Comment by apjanke** [comment]
This isn't normal default behavior for any shell that I know. Do you know what tool or mechanism you were using to do that? What shell were you using before Zsh? I assume this is on Mac OS X?

OS X has the `open -a` command to open an application by name. For example, `open -a anki`. And in `zsh`, I think you could use a [`command_not_found_handler()`] hook function to try translating commands to application names. #3278 has a proposal that would do that with Homebrew-controlled packages; you could do something similar with `open -a` and `/Applications`.

**Comment by mcornella** [comment]
That seems like a `$PATH`-related thing. If you were using bash before, post the output of `grep 'PATH' .bashrc .bash_profile .zshrc` to see what was your PATH before and what it is now.

**Comment by apjanke** [comment]
I don't know that it's a `$PATH` thing per se: their example program [Anki](http://ankisrs.net/) is a Mac GUI program, `Anki.app`. There's no `anki` command to run from the path (except the one contained inside the `Anki.app` bundle, which you don't want to do directly).

**Comment by yu-yuxuan** [comment]
Thank you, @apjanke . `open -a Anki`  is a good way.

**Comment by mcornella** [comment]
Closing as solved.
