### ISSUE TITLE
Wrong detection of bad folder permissions

### ISSUE THREAD

**Issue by lslinnet** [robbyrussell/oh-my-zsh#4432]
After running a ```sudo diskutil repairPermissions /``` I get the following error from oh-my-zsh, I believe this reporting to be wrong, unless by default mac os x is insecure?

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x+ 109 root admin 3706 Sep 29 11:33 /Applications/
lrwxr-xr-x    1 root wheel   49 Jul  4  2013 /User Information -> /Library/Documentation/User Information.localized/
drwxrwxrwt+   3 root admin  102 Sep 29 10:58 /Volumes/
drwxrwxr-t    2 root admin   68 Sep  9  2014 /cores/
lrwxr-xr-x    1 root wheel   11 Apr 18 11:59 /tmp -> private/tmp/
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.
```

**Comment by apjanke** [comment]
It's probably not the `repairPermissions` that made this start appearing, but the recent #3889, which added a `compaudit` to the startup sequence.

Those permissions are normal for those directories, and `zsh`'s simplistic `compaudit` will see them as insecure. But they're not normally on your `$fpath`; do you know why they're there? What's your `$fpath`?

```
[~]
$ echo "${(F)fpath}"
/Users/janke/.oh-my-zsh/plugins/debian
/Users/janke/.oh-my-zsh/plugins/brew
/Users/janke/.oh-my-zsh/plugins/nyan
/Users/janke/.oh-my-zsh/plugins/themes
/Users/janke/.oh-my-zsh/plugins/osx
/Users/janke/.oh-my-zsh/functions
/Users/janke/.oh-my-zsh/completions
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.2/functions
```

At any rate, this change was turned back off by #4426. Do another update of OMZ and those messages should go away.

**Comment by lslinnet** [comment]
My output of ${(F)fpath}
```
➜  ~  echo "${(F)fpath}"
/Users/myuser/.oh-my-zsh/plugins/nyan
/Users/myuser/.oh-my-zsh/plugins/sublime
/Users/myuser/.oh-my-zsh/plugins/capistrano
/Users/myuser/.oh-my-zsh/plugins/vagrant
/Users/myuser/.oh-my-zsh/plugins/extract
/Users/myuser/.oh-my-zsh/plugins/git
/Users/myuser/.oh-my-zsh/functions
/Users/myuser/.oh-my-zsh/completions
/var
/usr
/tmp
/sbin
/private
/opt
/net
/home
/etc
/dev
/cores
/bin
/Volumes
/Users
/User Information
/System
/Network
/Library
/Applications
/Users/myuser/.dotfiles/functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.5/functions
```

I might have some magic going on in the .zshrc file, I am also including some other scripts and functionality specifically for my work.

**Comment by apjanke** [comment]
Everything between `/var` and `/Applications` is rather strange to have in your fpath. That looks like everything at `/*`. Maybe there's an uninitialized variable somewhere in your startup files such that you're adding `$FOO/*` to the `$fpath`, but `$FOO` is blank, so it ends up adding `/*` instead?

The `/Users/myuser/.oh-my-zsh/functions` and `/Users/myuser/.oh-my-zsh/completions` are the first things Oh My Zsh prepends to $fpath, so it sounds like these are being added by your `~/.zshrc` before it's calling `oh-my-zsh.sh`.

**Comment by lslinnet** [comment]
Okay, seems like it is something happening due to some custom dotfiles i used that might need an update, thanks for the help & clarification.
