### ISSUE TITLE
Can't activate vi-mode?

### ISSUE THREAD

**Issue by grobmeier** [robbyrussell/oh-my-zsh#4433]
Hi, 

I guess I am doing something wrong with activating vi-mode.

First I run zsh_upgrade. Then I changed my plugins to:

```
plugins=(vi-mode git osx composer mvn sudo git-flow sublime)
```

I opened a new ZSH window (also tried to source .zshrc) und was typing ```v <enter>```

Result:

```
~  v
zsh: command not found: v
```

Anything I can check? Anything you see I did wrong?

Thanks!

**Comment by apjanke** [comment]
You're probably in vi mode. `v` doesn't do anything, as far as I know. If you type in some stuff at the command line, and then hit Escape, that will switch you in to vi command mode, where you can use `b` and `w` to move between words on the command line. If that works, it confirms you're in vi mode.

You can also run `bindkey -lL | grep main`. If you see `bindkey -A viins main`, that means you're in vi mode.

**Comment by grobmeier** [comment]
aaaaaah, thanks @apjanke You were right, hitting ESC brought me to VI mode. Awesome!! Thanks a lot!
