### ISSUE TITLE
autoenv plugin looking in wrong folder

### ISSUE THREAD

**Issue by mhuggins** [robbyrussell/oh-my-zsh#4438]
Hello,

I just installed [autoenv via homebrew](https://github.com/kennethreitz/autoenv#mac-os-x-using-homebrew):

```
$ brew install autoenv
$ echo 'source /usr/local/opt/autoenv/activate.sh' >> ~/.zshrc
```

Unfortunately, when I modify my plugins to include the autoenv plugin in my plugins list, I see the following error when I try to source .zshrc:

>     -------- AUTOENV ---------
>     Could not find ~/.autoenv/activate.sh.
>     Please check if autoenv is correctly installed.
>     In the meantime the autoenv plugin is DISABLED.
>     --------------------------

It looks like the plugin is looking for `~/.autoenv/activate.sh` instead of `/usr/local/opt/autoenv/activate.sh`.  What's the best approach for fixing this?

**Comment by apjanke** [comment]
We should update the plugin to look in both places. And pull in #4147 so it doesn't get loaded redundantly.

**Comment by apjanke** [comment]
Added #4440 to do this.

**Comment by mhuggins** [comment]
Awesome, thank you!

**Comment by monkeyxite** [comment]
Via pip install autoenv, the activate.sh path would be "/usr/local/bin/activate.sh" for brewed python in mac, so suggest to add /usr/local/bin.

**Comment by apjanke** [comment]
Good idea. Maybe along with the `~/.local` or `site.USER_BASE` location for `pip install --user`?

Any other possible install locations we should be considering? And what should be the precedence order?
