### ISSUE TITLE
taskwarrior plugin causes segmentation fault

### ISSUE THREAD

**Issue by Shir0kamii** [robbyrussell/oh-my-zsh#4441]
Hi,

When I try to use autocompletion from the taskwarrior plugin, a segmentation fault happens.

I saw #3796 and #4237 but it doesn't change anything, it still crash with the new update.

PS: thanks for the hard work

**Comment by apjanke** [comment]
Have you looked at #2044? Seems like there might be a version-dependent bug on some systems. What version of zsh are you running, and what operating system?

**Comment by Shir0kamii** [comment]
I just took a look. I no longer have segmentation fault with the 5.1.1 version of zsh.

Now, when I type `task [tab]`, I have the following error message : `_arguments:450: _task_default: function definition file not found`

**Comment by mcornella** [comment]
Please try deleting the cached completion files with `rm ~/.zcompdump*` and restarting the terminal.

**Comment by Shir0kamii** [comment]
I did it and strangely, the sementation fault is back.

**Comment by apjanke** [comment]
I can't reproduce on OS X 10.9 or 10.11.

Could you post the output of `omz_diagnostic_dump` as a gist so we can get some debugging info?

**Comment by Shir0kamii** [comment]
See : https://gist.github.com/Shir0kamii/64b67c4e1594a6fd0be5

**Comment by apjanke** [comment]
Thanks.

I've got an Ubuntu VM around here somewhere. I'll try to reproduce it there.

**Comment by Shir0kamii** [comment]
Thanks for your work, it's a bit annoying to not have autocompletion with a verbose tool like this one.

Let me know if there's anything I can try to solve the problem !

**Comment by Shir0kamii** [comment]
Hi !

Any news ?

**Comment by apjanke** [comment]
Sorry, been busy with work and other projects; haven't had a chance to test this yet.

**Comment by mcornella** [comment]
This was also reproduced by @xoyk at https://github.com/robbyrussell/oh-my-zsh/issues/3796#issuecomment-134982023. 
I could not reproduce that in my current system, I'm running task 2.4.4. Which version are you running (`task --version`)?

**Comment by Shir0kamii** [comment]
My version was 2.5.0-beta3. I upgraded it to 2.5.1 and the autocompletion is working fine. Thank you and sorry for the bother.

**Comment by Shir0kamii** [comment]
Well, I was wrong in closing the issue. When I'm in a nested zsh, the autocompletion indeed works fine, contrary to before. But if I open a terminal with zsh and type "task [TAB]", the terminal closes so I guess there's still a problem.

I tried with terminator 0.97 and Xterm(297) and the behaviour was the same. I also updated zsh and oh-my-zsh.

Yet, I have no idea what is going on.

One last thing (that doesn't seem related but I'm not sure), I have the following error when I launch zsh inside zsh, but not when I launch zsh alone : 

`/home/shir0kamii/.oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh:[:55: integer expression expected: 52-dev-0`

**Comment by apjanke** [comment]
> One last thing (that doesn't seem related but I'm not sure), I have the following error when I launch zsh inside zsh, but not when I launch zsh alone :
>
> /home/shir0kamii/.oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh:[:55: integer expression expected: 52-dev-0

Sounds like you have a beta version of `zsh` installed on your path (maybe from Homebrew or something), and its version number (something with a "-dev-0" on it) is not numeric, but your default shell is the system `zsh` which has a numeric-looking version number. When you launch a new terminal session, you get your default shell `zsh`, and when you run `zsh` from the command line you get the other version.

The test in `common-aliases` should probably be changed to handle this.

**Comment by Shir0kamii** [comment]
Indeed, it was two different versions of zsh. My system version was pointing to `/etc/alternatives/zsh-usrbin` while `zsh` is resolved as `/usr/local/bin/zsh`. I changed the symlink and now I have an error when I open a terminal but at least I have an autocompletion for taskwarrior, which is much more useful for me.

This issue's problem is solved and was just a bug in an old version so I'll close the issue and open a new one for the error I have.

Thank you for your help.

**Comment by apjanke** [comment]
Can you tell me what version of zsh is in `/usr/local/bin/zsh` so I can try to reproduce it?

**Comment by apjanke** [comment]
This should fix the error with the "dev" version: #4689. Give it a try?

**Comment by k1-hedayati** [comment]
Ok, I encountered this problem too.
```shell
-> cd ~/.oh-my-zsh && git pull
-> zsh
-> task --version
2.5.1
-> zsh --version
zsh 5.0.2 (x86_64-pc-linux-gnu)
-> task ......[1]    15398 segmentation fault (core dumped)  zsh
```

**Comment by in-in** [comment]
Same problem
```bash
➜  ~ which zsh
/usr/bin/zsh
➜  ~ zsh --version
zsh 5.0.2 (x86_64-pc-linux-gnu)
➜  ~ task --version
2.5.1
➜  ~ 

```

**Comment by robin9975** [comment]
I'm also encountering this as well;

outputs of version is exactly as  @in-in and oh-my-zsh has been updated. Running Ubuntu 14.04, having taskwarrior compiled using the release version.

Any clue what's causing this issue?
