### ISSUE TITLE
Get stuck on paste some non-ascii chars to terminal(auto escape)

### ISSUE THREAD

**Issue by kennel209** [robbyrussell/oh-my-zsh#4452]
iterm2 get stuck when paste some non ascii chars like chinese (maybe occur with auto escape?)
ctrl-c produce non-recognizable code

Occurs as well as OSX's terminal
with zsh 5.1.1

maybe some wrong in bracketed-paste-magic?
weird error when reproduce with some "\?\=" words with iterm2's Paste history
```
bracketed-paste-magic:zle:38: not enough arguments for -U
```

or just some bug in url-quote-magic?

HOW can i disable this auto paste escape function?

UPDATE:
NO PROBLEM with zsh 5.0.8

**Comment by apjanke** [comment]
This sounds like #4434.

For mitigation, you could copy `lib/misc.zsh` to your `$ZSH_CUSTOM` and comment out [this section](https://github.com/robbyrussell/oh-my-zsh/blob/19c0b185ad9b37b448a979fb6cc995cc648e76a4/lib/misc.zsh#L1-L11) to disable the url quoting and bracketed paste support. You'd lose safe pasting but it might keep things from locking up.
