### ISSUE TITLE
Annoying gap at the bottom

### ISSUE THREAD

**Issue by mostafahussein** [robbyrussell/oh-my-zsh#4457]
I have an annoying gap at the bottom , how can i get ride of it ?!

while using vim:
![screenshot from 2015-10-04 12-43-36](https://cloud.githubusercontent.com/assets/4104127/10267468/1a0d7ce2-6a96-11e5-945d-e3c6a6a762dc.png)

while using the commandline itself:
![screenshot from 2015-10-04 12-46-31](https://cloud.githubusercontent.com/assets/4104127/10267469/24c5ff6a-6a96-11e5-874d-37016cd20a17.png)

as you see there is a gap under vim or when i am on the commandline , how to fix it ?

**Comment by alocersade** [comment]
reduce your font size -_-

**Comment by mostafahussein** [comment]
thanks i made it 11 instead of 12 , i didn't know that it could be the problem.
