### ISSUE TITLE
Problems with git completion for branches

### ISSUE THREAD

**Issue by dkpalmer** [robbyrussell/oh-my-zsh#4461]
After updating ZSH to 5.0.5, git completion has broken for me when trying to complete branch names. It looks isolated to branches I have prefixed w/ "f/" or "b/", e.g. "f/feature1", "b/bug2". I am able to tab complete both 'master' and 'develop' fine.

I also noticed I can tab-complete some names that come after these prefixes, e.g. 'git checkout fea' + TAB does result in 'git checkout feature1', but that obviously doesn't work since my branch is 'f/feature1'.

One other observation.. tab complete does seem to hang a little bit on these branch names.

**Comment by apjanke** [comment]
What plugins do you have loaded? There are some problematic interactions between certain plugins and zsh's (or git's) internal completion functions.

**Comment by sirLisko** [comment]
I've the same problem since I've updated to el capitan.

**Comment by dkpalmer** [comment]
It looks like the problem is isolated to git-extras for me. When I limited my plugins to just 'git' and 'git-extras', I still experienced the issue. Removing git-extras tab-completion at least lists the possible branches, but doesn't attempt to autocomplete with a best match (which I assume was provided via 'git-extras').

Also, I am still on Yosemite.

**Comment by apjanke** [comment]
`git-extras` has known compatibility issues with the `_git` from some versions of `zsh`. That might be what you're hitting here. We recently put in a fix: #4444. Try updating oh-my-zsh and see if that fixes it.

**Comment by dkpalmer** [comment]
Things seem good now after a manual update.  Thanks.
