### ISSUE TITLE
Condition expected

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#4462]
Someone know how to solve this message?
```
/home/lheck/.oh-my-zsh/lib/functions.zsh:42: condition expected: =~
```

Some imformation about my system:
```
lheck@kriti:~ » lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 5.11 (Final)
Release:	5.11
Codename:	Final
```

**Comment by apjanke** [comment]
Can you post the output of `omz_diagnostic_dump` as a gist, so we have full debugging info? This shouldn't happen, and we'll get it fixed up.

**Comment by leoheck** [comment]
Sure, take a look:

```
oh-my-zsh diagnostic dump

omz_diagdump_20151006-094638.txt

Tue Oct  6 09:46:38 BRT 2015
Linux kriti 2.6.18-348.el5 #1 SMP Tue Jan 8 17:53:53 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
OSTYPE=linux-gnu
ZSH_VERSION=4.2.6
User: lheck
umask: 022

OS Release: "CentOS release 5.11 (Final)"
/etc/redhat-release:
CentOS release 5.11 (Final)


_omz_diag_dump_one_big_text:33: unrecognized modifier `A'
```

**Comment by apjanke** [comment]
zsh 4.2.6 is pretty old; it's from 2005. It doesn't have support for `[[ =~ ]]` or probably the `A` modifier. Any chance you could upgrade?

**Comment by leoheck** [comment]
I am using the latest version I can. The machine is a server with the old
5.11 CentOs. Is it possible to add a solution to avoid the feature that
gives the problem?

**Comment by apjanke** [comment]
I dunno. Restricting the core functions to only use features from zsh 4.2.6 or earlier is a pretty big ask: I don't even know what all we'd have to remove, and no active OMZ developers test on stuff that old, AFAIK. Getting plugins to support it would be even harder. That's a lot of work now and in the future, for a pretty small part of the user base.

You might be better off just turning off OMZ for zsh versions before 5.0 or so. If you're sharing config files between machines, [you can use `is-at-least`](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#index-is_002dat_002dleast) to do it automatically.

```zsh
# in your ~/.zshrc
autoload -U is-at-least
if is-at-least 5.0; then
  source ~/.oh-my-zsh/oh-my-zsh.sh
fi
```

**Comment by leoheck** [comment]
Ok, I understand. I will keep using the OMZ because it is still good for my use. Thank you @apjanke!

**Comment by mflash** [comment]
Alternatively, why don't you compile from source. It's quite easy.
Just installed zsh 5.1.1 (latest stable) on CentOS 5.8 (even older than yours).

Here's a set of instructions (just replace the URL from sourceforce with the latest version):

http://michaelheap.com/installing-zsh-5-0-on-centos-5-7/

**Comment by leoheck** [comment]
@mflash I had updated my server with 5.0.2 with yum and forgot this. But you give me a good idea and which worked well. Thank you :) 

My steps if someone wants to know.

```bash
# Donwload zsh (zsh-5.1.1.tar.gz)
tar -xvzf zsh-5.1.1.tar.gz
cd zsh-5.1.1
./configure
make && sudo make install
```

**Comment by apjanke** [comment]
Cool.

Can we close this issue out, since it looks like it was just a `zsh` version compatibility problem?

**Comment by mcornella** [comment]
Thank you guys

**Comment by leoheck** [comment]
Actually this problem persists even with version 5.1.1 :( 
I had moved to bash since some other problems... but now I realized that the problem persists.

**Comment by mcornella** [comment]
Can you post the error you get now?

**Comment by leoheck** [comment]
Sure, but it is the same:
```
/home/lheck/.oh-my-zsh/lib/functions.zsh:42: condition expected: =~
```

I tried [@apjanke's](https://github.com/robbyrussell/oh-my-zsh/issues/4462#issuecomment-146358673) workaround but with no luck. The same message is showing. I also tried changing `5.0` to `5.1.1`.

**Comment by mcornella** [comment]
That's weird, on [line 42](https://github.com/robbyrussell/oh-my-zsh/blob/bd6dbd1d9b1fc8a523aaf588492eb3ed4113b49d/lib/functions.zsh#L42) there's no such symbol.
Can you check that you have OMZ updated to the latest version?

**Comment by leoheck** [comment]
Sure, but this is very weird. I just created a new and clean user yesterday and have cloned oh-my-zsh yesterday from git too. The zsh is 5.1.1 and I ran the upgrade_oh_my_zsh which no changes nothing. The only problem I can think is something related to the ssh login. This setup is running on a remote machine.

**Comment by mcornella** [comment]
Please post your `.profile` file to see how you're calling that, and alos tell me what's the default `$SHELL`.

**Comment by leoheck** [comment]
Look, how this is strange.. 

I changed theme to blink.. then when I log into the host, I receive the ``condition expected` message then the prompt is messed like this:

```bash
/home2s/leco/.oh-my-zsh/lib/functions.zsh:42: condition expected: =~

{black}{green}leco{blue}@{cyan}kriti{green} {yellow}{black}~{green}
{black}{blue}±{black} %                                                                                                                           !zshan}366
```

Then, I type zsh again and the theme is applied correctly.

Something is happening during the login, then it is fixed in the next zsh openning.

**Comment by mcornella** [comment]
```
/home2s/leco/...
```
That's from another host, isn't it?

In any case, please follow [these instructions](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#other-problems) to generate a debug file and post it as a gist.

**Comment by mcornella** [comment]
Which zsh version are you using? And please follow the comment above to generate a debug file.

**Comment by thunderousNinja** [comment]
```bash
➜  zsh --version
zsh --version
zsh 5.2 (x86_64-unknown-linux-gnu)
```

---

Will follow the debug file logs later tonight. Just figured I would chime in on the commit this started happening at.

**Comment by mcornella** [comment]
Thanks for that!

**Comment by leoheck** [comment]
How can I share the gist? This [link](https://gist.github.com/leoheck/0a83391d1becbd2e6515) works for you @mcornella ?

**Comment by mcornella** [comment]
This dump doesn't contain the error... Try modifying your zshrc file in the following way:
```zsh
set -xv
source $ZSH/oh-my-zsh.sh &> ~/omz-debug.log
set +xv
```
then restarting your zsh and submitting the `omz-debug.log` file. You'll find the `source $ZSH/oh-my-zsh.sh` line after the `plugins=()` line.

**Comment by leoheck** [comment]
[file-omz-debug-2-log](https://gist.github.com/leoheck/0a83391d1becbd2e6515#file-omz-debug-2-log)

**Comment by mcornella** [comment]
I'm sorry, that doesn't contain the relevant part. Try this other version that uses `exec` plus clever redirections (taken from [this exec example](http://www.tldp.org/LDP/abs/html/x17974.html#UPPERCONV)):

```zsh
exec 7<&1 8<&2
exec 1> ~/omz-debug.log 2>&1

set -xv
source $ZSH/oh-my-zsh.sh
set +xv

exec 1>&7 7>&-
exec 2>&8 8>&-
```

**Comment by leoheck** [comment]
[file-omz-debug-3.log](https://gist.github.com/leoheck/3a8a823810e45622aaec)

**Comment by mcornella** [comment]
Ok, the problem is on lines [967 to 968](https://gist.github.com/leoheck/3a8a823810e45622aaec#file-omz-debug-3-log-L967-L968), coming from the omz_urlencode function:
```
    ...
    if [[ "$byte" =~ "$dont_escape" ]]; then
/home2/leco/.oh-my-zsh/lib/functions.zsh:42: condition expected: =~
```

If we go a little further we can find [the zsh version this is running on](https://gist.github.com/leoheck/3a8a823810e45622aaec#file-omz-debug-3-log-L1417), 4.2.6, which we already established didn't support such functionality. 

Please try the same on your 5.1.1 version as you stated in https://github.com/robbyrussell/oh-my-zsh/issues/4462#issuecomment-194922816.

**Comment by leoheck** [comment]
Good, that works. I had to put the code bellow on my .profile using ``/usr/local/bin/zsh`` instead of ``/bin/zsh`` which was an outdated version. 

```
# Using zsh instead of bash
export SHELL=/usr/local/bin/zsh
[ -z "$ZSH_VERSION" ] && exec /usr/local/bin/zsh -l
```

```
~ » /bin/zsh --version                                                                                                                                                               lheck@kriti
zsh 4.2.6 (x86_64-redhat-linux-gnu)
------------------------------------------------------------
~ » /usr/local/bin/zsh --version                                                                                                                                                     lheck@kriti
zsh 5.1.1 (x86_64-unknown-linux-gnu)
```

**Comment by hheedat** [comment]
Thanks for that!
