### ISSUE TITLE
Recover oh-my-zsh installation

### ISSUE THREAD

**Issue by vkyt** [robbyrussell/oh-my-zsh#4467]
Hi guys,

Is there anyway that I would be able to recover the installation on mac?  I was trying to run another command but accidently ran the uninstall-oh-my-zsh because it was the first item that came up when I tabbed.  

Please help!!!!! I have a lot of custom scripts under the .oh-my-zsh folder and it would be a disaster if I cannot recover it.

Thanks a lot!

**Comment by apjanke** [comment]
I'm afraid not. The uninstall just does an `rm -rf ~/.oh-my-zsh`.

We should add something to the uninstaller that detects user additions to the directory and either preserves them or balks, to avoid destroying user data.

**Comment by vkyt** [comment]
Oh no... I knew I should have done a backup of all of my setup files.  Now I gotta recreate them from my memory.  Thank god I still have the .zshrc file.  

But yeah, to your point, I think preserving the /custom folder and /theme would have been great.

**Comment by apjanke** [comment]
Bummer. I'm sorry. :(

This time around, stick all your custom code in a separate `~/.oh-my-zsh-custom` directory (point `$ZSH_CUSTOM` at it in your `~/.zshrc`), make it a Git repo, and upload it to GitHub or (if you want to keep your files private) Bitbucket. That way you have a backup, it'll be untouched by OMZ installs/reinstalls, and is easy to sync between machines or share with other developers if you want help with some code in it. For example, [mine's here](https://github.com/apjanke/oh-my-zsh-custom), and I keep it checked out to a local repo under my Dropbox, so it auto-syncs to all my desktop machines.

I will look in to adding preservation checks to the uninstaller.

**Comment by vkyt** [comment]
Will do!  Thanks a lot!!

**Comment by RHieger** [comment]
Hi, I am new to Oh My Zsh and definitely like what I see. Unfortunately, the moment I installed the framework, all global commands ceased working. Most notably, I had nvm installed and two different versions of node.js. I also had at least one version of Angular installed.

My system is a late 2018 Mac Book Pro with Touchbar and 32GB RAM, an i9 processor and 1TB SSD (nearly top of the line at the time).

I am running Mac OS Catalina, which automatically switched over to using the zsh shell. The problems actually began then. I was able to get nvm back up and running using another set of instructions in a Github Gist [install-nvm-zsh](https://gist.github.com/mike-casas/6d489bebf48d89f5109cd1395aabe150).

Once I installed Oh My Zsh, everything fiixed by the above gist ceased to work.

I've been reading around the net, and there seems to be much conflicting information, and my development studies are now at a standstill.

Any insights you can provide are greatly appreciated.

Thanks,

Robert Hieger
