### ISSUE TITLE
Uninstall impossible

### ISSUE THREAD

**Issue by roukmoute** [robbyrussell/oh-my-zsh#4483]
There was an error when we want uninstall:

    ➜  ~  uninstall_oh_my_zsh
    Are you sure you want to remove Oh My Zsh? [y/N] y
    /home/roukmoute/.oh-my-zsh/tools/uninstall.sh: 2: /home/roukmoute/.oh-my-zsh/tools/uninstall.sh: [[: not found
    Uninstall cancelled

**Comment by apjanke** [comment]
Looks like this is caused by #4464, which introduces a prompt for the uninstall, but uses non-portable syntax for it. The test needs to be done with single-bracket `[ ... ]`.

**Comment by superlbr** [comment]
can i uninstall manually?

**Comment by roukmoute** [comment]
@superlbr: Yes, just read uninstall.sh

```
rm -rf ~/.oh-my-zsh
chsh -s /bin/bash
```

It's actually almost the only thing to do.

**Comment by superlbr** [comment]
thanks

**Comment by mkoller** [comment]
@roukmoute This worked, but every time I open up Iterm2 I have to type

```
~$ zsh
```

In order to start OhMyZsh, any ideas on to have zsh start on default?

**Comment by apjanke** [comment]
Use `chsh -s` to change your default shell. (Unless you're on cygwin, in which case you have to manually generate and edit `/etc/passwd`.)

**Comment by roukmoute** [comment]
Thanks @apjanke.
But this question @mkoller has nothing to do here.
You're answer [written here](https://github.com/robbyrussell/oh-my-zsh#4-change-your-default-shell).
