### ISSUE TITLE
Found this error after updated El Capitan

### ISSUE THREAD

**Issue by macbaszii** [robbyrussell/oh-my-zsh#4485]
I couldn't use any auto-complete in git

![screen shot 2558-10-12 at 11 24 39 am](https://cloud.githubusercontent.com/assets/809559/10421527/e7f813f4-70d3-11e5-93c8-84e76d1a8a00.png)

**Comment by o-shabashov** [comment]
+1

Dirty hack is just turn off git from plugins

**Comment by apjanke** [comment]
Looks like a dupe of #4127.

**Comment by mcornella** [comment]
Duplicate of #4127. Follow discussion there please.
