### ISSUE TITLE
Bug when using themes with right prompt in iTerm2

### ISSUE THREAD

**Issue by JakubMatejka** [robbyrussell/oh-my-zsh#4488]
The prompt is shifted three places left (and so is rewriting last three characters of the prompt) when I use any theme having some info on the right. This happens with both stable and beta version of iTerm2 on Mac (with OS X El Capitan) but not in default Mac terminal. See the screenshot (with theunraveler theme):

![bug](https://cloud.githubusercontent.com/assets/215660/10427518/a973963c-70ea-11e5-91df-1056c4ebe390.png)

**Comment by apjanke** [comment]
It's not reproducing for me on OS X 10.9 or 10.11 in iTerm2, with either zsh 5.0.8 or 5.1.1. Maybe it's a character-width info issue? I'm using the Meslo LG font. What font are you using?

**Comment by JakubMatejka** [comment]
Hm, that's weird, I use Consolas but it is the same with Menlo and Courier. Zsh is 5.0.8 and iTerm2 2.1.4.

**Comment by JakubMatejka** [comment]
But interesting is that this is happening only when I work in my filesystem. When I ssh to a server where is the same setup of oh-my-zsh with the same theme, it is ok there.

**Comment by apjanke** [comment]
Hmm. What's your `locale` on the machine where it's going wrong?

**Comment by JakubMatejka** [comment]
Oh, right, that would be it. I had setting `Profiles -> Terminal -> Environment -> Set locale variables automatically` in iTerm Preferences switched off and `locale` command showed me `LC_CTYPE="C"`. When I switch it on, the problem disappears (and `locale` command shows `LC_CTYPE="UTF-8"`). 

I remember that I switched that iTerm setting off intentionally because of some problem with ssh on servers but I don't remember why anymore. ;o) Thanks.

**Comment by apjanke** [comment]
Cool.

If this fixed it, could you close the issue?

**Comment by JakubMatejka** [comment]
Right, thanks.
