### ISSUE TITLE
git icon still not display on El Capitan when use amuse theme

### ISSUE THREAD

**Issue by smaty1** [robbyrussell/oh-my-zsh#4494]
![318 pic](https://cloud.githubusercontent.com/assets/1223202/10510270/95665342-7364-11e5-88ab-5d67f8f0684a.jpg)

**Comment by apjanke** [comment]
Amuse uses custom Powerline characters, which require a special font. Make sure you have a current ["Powerline-patched font"](https://github.com/powerline/fonts) installed and selected as the font for your terminal, and if you're using iTerm2, that it's selected for the "non-ASCII" font, as well. Also make sure it's a recent copy of the font; Powerline changed which code points they use for their characters a while back, so older copies of their patched fonts no longer work with current Powerline code. See #4091 for more info.

**Comment by apjanke** [comment]
Any luck with trying new Powerline fonts on this?
