### ISSUE TITLE
El Capitan & Homebrew w/ iTerm2 

### ISSUE THREAD

**Issue by brianjking** [robbyrussell/oh-my-zsh#4497]
Whenever I open a new tab or window in iTerm 2 I'm seeing this notice:

```
Last login: Thu Oct 15 09:58:06 on ttys005
/Users/brianjking/.zshenv:1: command not found: brew
```
The contents are as follows:
```
cat /Users/brianjking/.zshenv
export PATH="$(brew --prefix)/bin:$PATH"
```

Any tips?

**Comment by apjanke** [comment]
`brew` is installed in `/usr/local/bin`, which is not on the path by default. `/usr/local/bin` is added by a `/usr/libexec/path_helper` invocation in the global startup files. In 10.9, this was done in `/etc/zshenv`. In El Capitan, Apple [moved it to `/etc/zprofile`](http://www.zsh.org/mla/users/2015/msg00727.html), which runs later in the startup file order, after `.zshenv`. So now, at the point your `.zshenv` runs on El Cap, `/usr/local/bin` isn't on the path yet.

You can fix it by moving that command from your `.zshenv` to your `.zprofile` or `.zshrc`, which run after `/etc/zprofile`, so `/usr/local/bin` will be in place. (You could also pull the `path_helper` invocation in to your `.zshenv`, but that zsh mailing list advises against it, so a caller's exported `$PATH` will be respected in subshells.) And maybe wrap it in a test for the existence of `brew`, so it doesn't break on machines that don't have Homebrew installed.

**Comment by brianjking** [comment]
@apjanke -- Just to make sure I understand.

It sounds like the best option is to paste the contents of ```.zshenv``` into my ```.zshrc```?

```export PATH="$(brew --prefix)/bin:$PATH"```

**Comment by apjanke** [comment]
@brtianjking: Yes, and then delete your `.zshenv`.

**Comment by brianjking** [comment]
@apjanke Does it matter where in the .zshrc I put it?

**Comment by apjanke** [comment]
It depends on exactly how you want your setup to behave. But in the typical case, you would want your Homebrew-installed stuff to take priority over system-installed commands, and you'd want the `$PATH` to be consistent for everything. If you had it in `.zshenv` before, that's the case for you. So put it at or near the top of `.zshrc`, before loading OMZ or anything else. Otherwise you might find that OMZ plugins or other things are complaining about not being able to find commands they need.

**Comment by brianjking** [comment]
@apjanke I think your suggestion worked! Thanks!

```
export PATH="$(brew --prefix)/bin:$PATH"


# Path to your oh-my-zsh installation.
export ZSH=/Users/brianjking/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"
```

**Comment by apjanke** [comment]
Great. You're welcome!

If that worked, could you close this issue out?

**Comment by brianjking** [comment]
Thanks again @apjanke. Everything seems to be working fine now. Closing issue as complete & fixed.
