### ISSUE TITLE
Add the first official collaborator

### ISSUE THREAD

**Issue by robbyrussell** [robbyrussell/oh-my-zsh#4503]
Confession: Over the years, I've hesitated to introduce new official collaborator to the project. There have been a number of folks who have invested a significant amount of time helping test, review, and organize pull-requests and issues... but I've never given anyone official commit access to the master branch.

Why did I hesitate? Some background..

When I started the project, outside of myself and a few friends/coworkers... I didn't know who my target audience was. I didn't have any grand plans on what would be bundled. Features like themes, plugins, an auto-update tool... didn't come until later. 

Ultimately, I never had a cohesive vision for the project. Without a vision, what would another collaborator be helping me accomplish? 

That isn't to say that I don't have rudimentary ideas of what my vision is.

For example, when [Prezto](https://github.com/sorin-ionescu/prezto) was created as a fork of oh-my-zsh, it was directly because of [a difference of opinion](https://github.com/robbyrussell/oh-my-zsh/issues/377) on how to move the project forward. When faced with a valid proposal on how to evolve the project, I found myself having to step back and think about who the target audience that the project should focus on. Given that I didn't have any vision shared with others, you couldn't fault folks for pushing in a different direction because it wasn't contrary to anything that had been shared. After some care consideration, I passed on the proposal and [said that I wanted to focus attention on folks who were new to terminal shells and git](https://github.com/robbyrussell/oh-my-zsh/issues/377#issuecomment-6311373). That isn't to say that more experienced folks wouldn't find joy in using oh-my-zsh, but they were not going to be who we optimized the project for. 

Through that process, hints of a project vision began to emerge (in my head). 

Back in May of 2011, I was interviewed on the Changelog podcast ( [episode 61](https://changelog.com/61/) ) about the project. I remember talking about how it was a goal to keep the open pull request count under 100. 

Under 100! hah

As of writing this post, there are 432 open pull-requests and I've personally merged cod from 876 different developers. 

It's becoming, increasingly, far too active of a project to maintain myself.

Over the past several months, it's become clear to me that I'm ready to take that first step of bringing in an additional official collaborator to help work through the backlog.

It's also really clear who that first person would be.

**Comment by DanielGGordon** [comment]
"It's also really clear who that first person would be."

Lol way to leave us hanging!

**Comment by robbyrussell** [comment]
Earlier this year, I started to get emails like this from @mcornella. 

![Alt text](https://monosnap.com/file/rHZIDebaAZpe13tb82rmUnPAr0xqoh.png)

Out of nowhere. They started appearing in my inbox every 3-4 weeks. A list of pull-requests that Marc believed were good to merge. It allowed me to focus my attention on those items, check the commits, and merge via the Github web interface. 

Marc realized that I wasn't able to focus that much attention on the day-to-day issues/requests coming in and created a workaround workflow for the project. It has worked pretty well.

Another example... Marc also helped organize #3809 with the help of a bunch of other folks... but he definitely orchestrated the whole thing. Another great example is #3651. 

This isn't to say that Marc is the only person who has helped the project move forward despite my limited availability, but he took a few extra steps to really foster a collaborative relationship with me. I've had many people write me and ask, _"how can I help?"_ ... but very few people approached me with, _"I'd like to help, I've organized the following for you."_   There are a handful of people who I believe would be great additions to this project... but I'm going to ease the project into this new era. Marc has accepted my invitation and we've agreed on the following:

* Keep the installation process as simple as possible for new folks. 
* Keep the auto-update process working as smooth as we can
* No new themes* (we'll make exceptions for really innovative ones)
* Don't break existing ~.zshrc configurations (i.e., when we add new options, let's avoid breaking things for existing users)
* Get a second opinion (from each other) on bigger changes to the core of the project

That isn't what I'd classify as a vision for the project, but it's something we can start working together with.


# Meet Marc.

![Alt text](https://monosnap.com/file/xj83jqzlTPuUlcNa4RwzS3zleabf5q.png)

Please join me in welcoming @mcornella as the first official collaborator to the project.

**Comment by apjanke** [comment]
A hearty :+1: to this!

**Comment by jinjorge** [comment]
very cool :100: :+1:

**Comment by mcornella** [comment]
I just published a correction to Robby's post which I spotted recently. A lot of the work was done by @ncanceill, so I'm just giving credit where it's due.
