### ISSUE TITLE
Upgrade should be avoided when git isn't available

### ISSUE THREAD

**Issue by cross** [robbyrussell/oh-my-zsh#4504]
I copy my .oh-my-zsh directory (and .zshrc) to multiple production servers without development tools, therefore no git installation.  The request to update is foolish, as it wouldn't work.

I propose a change to tools/check_for_upgrade.sh to look for git, and give up if it's not found.

**Comment by cross** [comment]
index 5afd83c..c3b376d 100644
--- a/tools/check_for_upgrade.sh
+++ b/tools/check_for_upgrade.sh
@@ -26,6 +26,9 @@ fi
 # oh-my-zsh directory.
 [[ -w "$ZSH" ]] || return 0
 
+# Cancel upgrade if no git command is available on this system.
+whence git >/dev/null || return 0
+
 if [ -f ~/.zsh-update ]
 then
   . ~/.zsh-update

**Comment by cross** [comment]
index 5afd83c..c3b376d 100644
--- a/tools/check_for_upgrade.sh
+++ b/tools/check_for_upgrade.sh
@@ -26,6 +26,9 @@ fi
 # oh-my-zsh directory.
 [[ -w "$ZSH" ]] || return 0
 
+# Cancel upgrade if no git command is available on this system.
+whence git >/dev/null || return 0
+
 if [ -f ~/.zsh-update ]
 then
   . ~/.zsh-update

**Comment by robbyrussell** [comment]
Can you submit a pull-request?

**Comment by robbyrussell** [comment]
For your production servers, I would recommend toggling the following in the .zshrc file to avoid this entirely

`DISABLE_AUTO_UPDATE="true"`

https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template#L18

**Comment by cross** [comment]
> On Oct 16, 2015, at 11:34 , Robby Russell <notifications@github.com> wrote:
> 
> Can you submit a pull-request?

  I tried, but the closest I could get was a pull request with other grot in it.  I’m only moderately skilled with git, and minimally skilled with git hub and pull requests.

  If you’d like me to, even after your alternate suggestion, let me know and I will do so.  (And if you know how to make the pull request be only the one commit I want, instead of the 4 commits it seems to try, including an add, remove, re-add and another file I don’t want  you to pull, that would be great too.  :-) )

  Thanks!

                - Chris

**Comment by cross** [comment]
I created a pull request, since I didn't notice that someone else also did.  Oh well.
And of course you're right that I can set that variable, but that would prevent me sharing a .zshrc between my personal machine, which I want to update, and the remote servers without git.  But it is a reasonable middle-ground, as I don't change my .zshrc often.

**Comment by robbyrussell** [comment]
Thanks, Cross. There is a pending pull-request awaiting testers on #4505
