### ISSUE TITLE
###bug report can not use adb logcat *:E

### ISSUE THREAD

**Issue by wsdjeg** [robbyrussell/oh-my-zsh#4511]
![2015-10-18 10-38-42](https://cloud.githubusercontent.com/assets/13142418/10562248/6cf3b0a4-7584-11e5-90ad-0d3401f1c20d.png)

but if i change to bash it works will

**Comment by wsdjeg** [comment]
i have find the answer here http://stackoverflow.com/questions/20037364/why-zsh-tries-to-expand-and-bash-does-not
but with my pool english
i really can not understand

**Comment by mcornella** [comment]
`*` is a globbing character, which means zsh will use it to find files. For example, `ls *.jpg` will list all files ending with `.jpg`. In your case, you want to escape the `*` so zsh doesn't interpret that. You have two alternatives:

1. Use `'` (single quotes): `adb logcat '*:E'`.
2. Use `noglob` and alias so you don't have to quote `*` every time: `alias adb='noglob adb'`. After that you can do `adb logcat *:E` without issues.

**Comment by wsdjeg** [comment]
thank you 
i have add setopt nonomatch to my zshrc
is there any potential problems?

**Comment by mcornella** [comment]
That only disables the `no matches found` error message, so as far as I know, you are ok :+1:

**Comment by wsdjeg** [comment]
it really works well,I just worry about potential problems
