### ISSUE TITLE
Upgrade_oh_my_zsh fails in OSX 10.10.5

### ISSUE THREAD

**Issue by senavis** [robbyrussell/oh-my-zsh#4512]
➜  ~  upgrade_oh_my_zsh
Upgrading Oh My Zsh
fatal: BUG: get_tempfile_fd() called for inactive object
There was an error updating. Try again later?

➜  .oh-my-zsh (master) gst
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

Please verify, not sure whats causing this issue.  Thanks!

**Comment by apjanke** [comment]
Yowza. Based on the error message, this looks like you are encountering a [bug in `git` itself](https://github.com/git/git/blob/99397152a345011c99497b93f8518c7981e811a5/tempfile.c#L204). What version of `git` are you running?

**Comment by senavis** [comment]
Hi there!

Thats unexpected, I am running git version 2.6.2.  Please recommend a working version and I can try with that. Thanks!

**Comment by apjanke** [comment]
Beats me, really. I don't know exactly what will trigger that bug; there's not much info in that error message. And I'm running 2.6.2 myself (on OS X 10.9.5, using Homebrew-installed git). What OS are you on?

Does it happen if you just do `git pull` inside your `.oh-my-zsh` directory? What if you re-clone it?

**Comment by senavis** [comment]
I was using OS X 10.10.5.  git pull didnt work as I encountered permission denied error.   Re-cloned it completely as new and it works now with the upgrade cmd. I'll wait until the next update rolls out and check back. 

Thanks!

**Comment by apjanke** [comment]
Cool. Sounds like a corrupt or mis-configured local repo, which ended up triggering that bug.

There's a small chance this was caused by OMZ's recent code for fixing `$fpath` permissions for "insecure" directories that `compaudit` complains about. This installation wasn't shared between multiple users, or created by a user who had changed their identity at some point, was it?

**Comment by senavis** [comment]
Nope, it was for a fresh OS X install and no users/identity changed.  I just another upgrade cmd and it works fine now.

**Comment by ramonamorim** [comment]
Hi,
I solved this isue unlocking the index so i tried to "git pull --rebase" again and it work, currently i'm using : https://git-for-windows.github.io/ version 2.6.1. I don't know the cause of the problem but it worked for me :D 

sorry for my english.

**Comment by guoxiao** [comment]
@ramonamorim @senavis I met the same problem and after removing `.git/index.lock` it works. 
I think the problem is that while you are doing some git actions the system restarted, and the temporary files no longer exist.

**Comment by kevlawrence** [comment]
@guoxiao thanks for posting your solution, it worked for me.

**Comment by watkinsmatthewp** [comment]
@guoxiao I owe you. Thanks!
