### ISSUE TITLE
when i paste Chinese ,the words changed

### ISSUE THREAD

**Issue by 0xbug** [robbyrussell/oh-my-zsh#4521]
![2015-10-19 21-44-06](https://cloud.githubusercontent.com/assets/12611275/10579964/bb98be1e-76ad-11e5-88c2-0428418b2db6.png)

**Comment by apjanke** [comment]
Looks like it might be an encoding or locale issue, where the encoding of the source text didn't match the encoding your shell is running under. Where did you copy that text from? What was it supposed to be? What's the output of `locale` in your terminal? And what system are you running on?

**Comment by nujabse** [comment]
确认了， zsh 5.1.1 的 bug ， bracketed-paste-magic 的问题，和 ohmyzsh 无关

**Comment by mcornella** [comment]
That may be the bracketed-paste-magic biting us again, that `^[[200~` [looks like the escape sequence](https://github.com/zsh-users/zsh/blob/a9df6aaa702abf761b155cd842a7f6917be44139/Functions/Zle/bracketed-paste-magic#L2) (I think that's what @nujabse is saying). 
If I'm correct, @0xbug update oh-my-zsh to the last version.

**Comment by 0xbug** [comment]
- 谢谢@nujabse 已解决
- Thanks @mcornella @apjanke 
- Everything seems to be working fine now. Closing issue as complete & fixed.
- I LOVE oh-my-zsh :)
