### ISSUE TITLE
Typo in git-extras plugin

### ISSUE THREAD

**Issue by qpautrat** [robbyrussell/oh-my-zsh#4525]
Hi,

I think there is a [typo](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git-extras/git-extras.plugin.zsh#L305) in git extras command to delete merged branches:
`delete-merged-brancees:'delete merged branches'\`

Best regards,

Quentin.

**Comment by sachin21** [comment]
I think that is typo. and it's fixed.
I found same command name [here](https://github.com/tj/git-extras/blob/cc488a035d205c340e533d15817fbdb43573f833/man/git-delete-merged-branches.md#examples)

**Comment by qpautrat** [comment]
Thanks @sachin21

**Comment by sachin21** [comment]
ur welcome :dancers:
