### ISSUE TITLE
some zsh themes did not work in tmux

### ISSUE THREAD

**Issue by majinjing3** [robbyrussell/oh-my-zsh#4530]
This issue appear on CentOS, and didn't on Mac OS X.
I use default config for **oh-my-zsh, tmux, powerline-status**, with some themes, such as"**agnoster**", "**terminalparty**". I just add "source /usr/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh" to the end of .zshrc.

when use tmux, zsh with some themes, such as"**agnoster**", "**terminalparty**", and powerline-status together, the command line's prompt didn't work. If I just use zsh and powerline-status, it works OK, or just use tmux and zsh, it also works OK.
when use zsh theme "**pygmalion**", all is OK. I guess there is something different in themes. or I loss some additional config.

I have *search around in google*, it has been long time, finally I given up.
I very like oh-my-zsh tmux and powerline-status. please help check it!

**Comment by apjanke** [comment]
Can you elaborate on "didn't work"? What's not working? Are some characters displayed incorrectly? Can you provide some example screenshots?

**Comment by majinjing3** [comment]
Firstly, it only exists in centos.
Normally, use zsh with theme "agnoster" and enable powerline, it work OK. see flow
![image 2](https://cloud.githubusercontent.com/assets/1567113/10682077/8d7053ae-7963-11e5-871f-472626e629e7.png)
but, when in tmux, the prompt seems not work correctlly.
![image 3](https://cloud.githubusercontent.com/assets/1567113/10682078/8d87da4c-7963-11e5-94e6-4ba4149bea38.png)
ps: some theme like terminalparty appears the same issue in tmux(same prompt)

**Comment by apjanke** [comment]
Hmmm. Looks kind of like it's running in only 8-color mode inside tmux there. Or some of the color-setting terminal escape sequences aren't getting propagated through tmux to your actual terminal, or some escape sequences are being issued wrong. The agnoster theme uses at least 16 colors, I think.

What's the value of `$TERM` normally, and when you're running inside `tmux`? And the result of `echoti colors` in both cases?

**Comment by majinjing3** [comment]
@apjanke Hi, I use Xshell to connect my vms. I have check the value of $TERM, default $TERM is screen-256colors, while using xshell, it changed. I think it is compatibility problem.
Thank you for you help!

**Comment by apjanke** [comment]
Cool. I'll give Xshell a try too; I hadn't heard of it before. Thanks for the pointer.
