### ISSUE TITLE
installs.sh didn't work

### ISSUE THREAD

**Issue by williamn** [robbyrussell/oh-my-zsh#4531]
I tried to install oh-my-zsh by running:

    sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

and I got this error:

    sh: 1: Syntax error: "(" unexpected

Previously I have a working oh-my-zsh for few months and then it stop working and when I try to reinstall I got the above error.

**Comment by LPMAXI** [comment]
Same problem with the CURL installation.

**Comment by iBreaker** [comment]
install.sh  error  
sh: 1: Syntax error: "(" unexpected

**Comment by danibram** [comment]
Same here

**Comment by FredrikAugust** [comment]
Same here on Xubuntu 15.04. Same error for both `wget` and `curl`.

**Comment by mcornella** [comment]
Hi guys, sorry for the confusion. This is due to a syntax error on #4515. All should be good again now.

**Comment by williamn** [comment]
It works now. Thanks @mcornella :beers:
