### ISSUE TITLE
Logic is backwards on uninstall_oh_my_zsh

### ISSUE THREAD

**Issue by clarkewd** [robbyrussell/oh-my-zsh#4533]
$ uninstall_oh_my_zsh

	Are you sure you want to remove Oh My Zsh? [y/N] n
	Removing ~/.oh-my-zsh
	Looking for original zsh config...
	Switching back to bash
	Changing shell for root.
	Shell changed.
	Thanks for trying out Oh My Zsh. It's been uninstalled.

**Comment by mcornella** [comment]
Sorry! :sweat_smile:
