### ISSUE TITLE
Colored-man plugin not 'always' working

### ISSUE THREAD

**Issue by etiennebatise** [robbyrussell/oh-my-zsh#4543]
Hi,

I'm having troubles with the *colored-man* plugin. I use **Konsole** and KDE,  I can remember the plugin worked fine until I decided to change the colorscheme and oh-my-zsh theme. 

I now use [Tomorrow](https://github.com/dram/konsole-tomorrow-theme) coloscheme and *steeef* theme, and I've noticed the man pages are not colored any more.

I just to a look, and it's the same with **xterm**. But when I log on a tty2 without running X server, I get to see colors in man pages. That being said I can't find what causes this behavior.

**Comment by etiennebatise** [comment]
Ok so my bad, it seems it is the Tomorrow colorscheme that is not well configured for colors in LESS.
By reading the issue again, it feels obvious now.

**Comment by systemovich** [comment]
@etiennebatise, which theme are you using? I have the same problem.

**Comment by systemovich** [comment]
Currently using OpenSUSE. Found out one has to set `export GROFF_NO_SGR=1`. This variable is used by the **grotty** program. From the grotty man page:

> If set, the old drawing scheme for bold and  underline  (using  the backspace character) is active. Colors are disabled.

**Comment by etiennebatise** [comment]
This is an old ticket.. I'm sorry I can't help you on that.

**Comment by systemovich** [comment]
@etiennebatise, I solved it. See my previous comment.
