### ISSUE TITLE
`ag` alias in debian plugin overrides the silver searcher

### ISSUE THREAD

**Issue by tejasbubane** [robbyrussell/oh-my-zsh#4548]
I am using [The silver searcher](https://github.com/ggreer/the_silver_searcher) to grep through the project. 

The debian plugin has an alias `ag` https://github.com/robbyrussell/oh-my-zsh/blob/b75b0b88823b6196fd18da8d9e7e16a1e014f14e/plugins/debian/debian.plugin.zsh#L53 which doesn't allow me to invoke the silver searcher. 
Is there a way to overcome this other than disabling the entire plugin?

**Comment by sachin21** [comment]
How about this?
```
alias ag='command ag'
```
In your zshrc or bashrc

**Comment by tejasbubane** [comment]
Fixed by adding

```
alias ag='command ag'
```

into my `.zshrc`.

**Comment by apjanke** [comment]
Duplicate of #3633.
