### ISSUE TITLE
Suggestion for better update checking

### ISSUE THREAD

**Issue by duchao0726** [robbyrussell/oh-my-zsh#4550]
Hi!
I am using oh-my-zsh across multiple servers. I put oh-my-zsh folder in some distributed file system (MooseFS) so that the servers can share a same copy of oh-my-zsh. However I notice that oh-my-zsh check for update by reading a "LAST_EPOCH" variable in ~/.zsh-update. This makes it ask me for checking update when I login a new server even it is just updated when I login another server before.

Is it possible to move .zsh-update file into the git repository?  I think this may be more reasonable :)

Sincerely,
Chao

**Comment by apjanke** [comment]
That makes sense. It could probably be moved to `$ZSH_CACHE`, which is `~/.oh-my-zsh/cache` by default.

**Comment by ncanceill** [comment]
Seconded. I agree that `$ZSH_CACHE` is the place for this. Who wants to make a PR?

**Comment by duchao0726** [comment]
Let me have a try, though I don't even know how to make a pull request. I am totally a novice at github :)

**Comment by apjanke** [comment]
Have a look at these to get started, and just ask if you have any questions. The main thing to note is to make sure to do your work on a separate branch that will be used just for this PR, not on `master`.

https://yangsu.github.io/pull-request-tutorial/
https://help.github.com/articles/using-pull-requests/

**Comment by duchao0726** [comment]
Thanks for your kind help! I've made a PR at [#4571](https://github.com/robbyrussell/oh-my-zsh/pull/4571).
