### ISSUE TITLE
Installer fails on windows if using Windows Git

### ISSUE THREAD

**Issue by amynbe** [robbyrussell/oh-my-zsh#4551]
Git clones the repo into C:/cygrive/c/... instead of /cygdrive/c/...

**Comment by apjanke** [comment]
Oh My Zsh is incompatible with the Windows (MSYS) git. You need to install the Cygwin git.

We added detection for this in the installer in #3646, but it looks like the ordering is messed up, so the check doesn't run in time. Opened PR #4557 to fix it.
