### ISSUE TITLE
Error: git clone of oh-my-zsh repo failed

### ISSUE THREAD

**Issue by Decontra** [robbyrussell/oh-my-zsh#4559]
I'm running OS X 10.11.1 and i'm using iTerm 2

I encountered two errors after attempting to install oh-my-zsh with curl using the following command: 

` sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" `

Output:

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: git clone of oh-my-zsh repo failed `

From my understanding, I have to change the active developer path? I don't know what to do about the git clone error. 

I would really appreciate some help, thanks.

**Comment by ncanceill** [comment]
Hi,

This is not an issue with OMZ, so please close — there are enough open, real issues already.

***

In order to fix your problem, you need to install the lastest Command Line Tools for XCode, and optionally run `xcode-select` accordingly.

See [details](http://lmgtfy.com/?q=xcrun%3A+error%3A+invalid+active+developer+path).

**Comment by Decontra** [comment]
Okay, thanks ncanceill.

**Comment by ncanceill** [comment]
My pleasure. I know all this XCode setup stuff can quickly become a pain in the A...

Please close this issue using the button at the bottom of the page ;-)

**Comment by hmaesta** [comment]
@jch-duran I already have **Command Line Tools** installed and I still receive `git clone of oh-my-zsh repo failed` from Terminal (El Capitan).

```
Cloning Oh My Zsh...
Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]
(...)
Error: git clone of oh-my-zsh repo failed
```
```
xcode-select: error: command line tools are already installed,
use "Software Update" to install updates
```

And everything is updated here. Can you help me?

**Comment by mcornella** [comment]
Can you post the full output you get when doing `git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh`?

**Comment by hmaesta** [comment]
@mcornella I already have done this, so the directory already existed. So I realized that I just had to set `oh-my-zsh` as default shell, like explained in [manual installation](https://github.com/robbyrussell/oh-my-zsh#manual-installation). 

Thank you for your help. Sorry for the unnecessary post.

**Comment by mcornella** [comment]
No problem :+1:
