### ISSUE TITLE
Mac OS El Capitan got "not valid in this context:" 

### ISSUE THREAD

**Issue by chrissom** [robbyrussell/oh-my-zsh#4565]
Hi,

On my Mac OS El Capitan I got "update_terminalapp_cwd:local:6: not valid in this context: -P" after the upgrade.

I'm the only one?

**Comment by apjanke** [comment]
Haven't seen that myself.

Looks like it's [this line](https://github.com/robbyrussell/oh-my-zsh/blob/e44aa50301cbdb9c713193263e6c0c5a9a5798c0/lib/termsupport.zsh#L77) it's complaining about. 

That looks like a quoting issue: normal `$FOO` expansion doesn't need to be protected, but I think `$(...)` might split if you have spaces in it. I wouldn't expect the output of `omz_urlencode` to have spaces or `-P`, but this might just mean there's an underlying bug, and the lack of `"$(...)"` protection is turning it into a syntax error.

Hold on, lemme whip up a patch for this.

**Comment by apjanke** [comment]
Try this and see if it fixes it. It's just a matter of slapping double-quotes around it.

https://github.com/apjanke/oh-my-zsh/tree/termsupport-protect-subshell

Before:
```
local URL_PATH=$(omz_urlencode -P $PWD)
```

After:
```
local URL_PATH="$(omz_urlencode -P $PWD)"
```

**Comment by apjanke** [comment]
And I think that's consistent with it showing up on El Capitan: El Cap has a newer version of `zsh`, and in newer `zsh`, `local` is now a reserved word and not a builtin, so its syntax is slightly different.

**Comment by chrissom** [comment]
the path is "/Users/chrissom". 

I tried your patch and it works perfectly. 

thanks @apjanke :+1:

**Comment by apjanke** [comment]
Weird. It really doesn't seem like that should require the quotes, and it's already protected with that `emulate -L zsh`.

Would you mind running `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/)? I'd like to see if I can reproduce it myself and figure out the reason the quotes are needed.

**Comment by chrissom** [comment]
Yes of course. Here is the [gist](https://gist.github.com/chrissom/40c56cc29198d66178b3).

**Comment by apjanke** [comment]
Thanks @chrissom.

Well, I honestly have no idea what's going on here. I can't reproduce using the config in your gist, I don't know why it was breaking, and I don't know why my proposed patch fixes it.

I think we should go ahead and do this patch: it fixes current user breakage, and extra (conservative) quoting mostly never breaks anything. But I'm concerned that we don't know why it's breaking. That's a bad sign.

**Comment by chrissom** [comment]
If i can help more, just ping me.

**Comment by mcornella** [comment]
I've merged your patch @apjanke.

**Comment by chrissom** [comment]
:+1:
