### ISSUE TITLE
ERROR: z.sh is meant to be sourced, not directly executed.

### ISSUE THREAD

**Issue by 0a-** [robbyrussell/oh-my-zsh#4570]
when I run `/bin/zsh -c "source ~/.zshrc"` I got the error: 

```
 z.sh is meant to be sourced, not directly executed.
```

After some searches it looked like that was an old behavior. I think we should update z to the latest version : https://github.com/rupa/z/blob/master/z.sh

**Comment by apjanke** [comment]
Yep, sounds like it. There's a similar issue in the z repo itself: rupa/z#107. Let's bump it to [version 1.9](https://github.com/rupa/z/releases/tag/v1.9).

There's already open PRs for this: #4181 and #3248.

Looks like the plugin file should be revised, too. This is the current implementation. This looks like it will try to load *both* the custom and main versions, and the main one will take precedence over the custom one, which isn't how OMZ customizations are supposed to work.

```
_load_z() {
  source $1/z.sh
}

[[ -f $ZSH_CUSTOM/plugins/z/z.plugin.zsh ]] && _load_z $ZSH_CUSTOM/plugins/z
[[ -f $ZSH/plugins/z/z.plugin.zsh ]] && _load_z $ZSH/plugins/z
```

**Comment by apjanke** [comment]
#4578 takes care of the problem with loading the custom version.

**Comment by 0a-** [comment]
Cool
