### ISSUE TITLE
eastwood theme should not depend on git plugin

### ISSUE THREAD

**Issue by clarkewd** [robbyrussell/oh-my-zsh#4581]
The eastwood theme gives an error if the `git` plugin is not enabled

    git_custom_status:1: command not found: current_branch

This appears to stem from [line 17](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/eastwood.zsh-theme#L17) where the current_branch function is called.

**Comment by apjanke** [comment]
PR #4420 moves `current_branch()` to the core and removes this plugin dependency.

**Comment by apjanke** [comment]
Want to do me a favor and test #4420 and give it a +1 if it works for you? Sooner we get it tested, the sooner it can be merged.

**Comment by clarkewd** [comment]
sure - but I'm not a git expert - how can I merge the PR into my local repo?

**Comment by apjanke** [comment]
Check out this tutorial on checking out PRs locally. https://help.github.com/articles/checking-out-pull-requests-locally/

I use that a lot. I even put together a little `zsh` function to do it. 

```
# Check out a PR locally
function _apj_print_and_do() {
  echo -E "==>" "$@"
  "$@"
}
function gh-local-pr() {
  emulate -L zsh
  local pr=$1
  local remote=${2:-upstream}
  _apj_print_and_do git fetch $remote pull/$pr/head:pr-$pr \
    || return
  _apj_print_and_do git checkout pr-$pr
}
```

With that, you'd cd into your `~/.oh-my-zsh` dir and do `gh-local-pr 4420 origin`. Test it out there, and then when you're done, `git checkout master`.
