### ISSUE TITLE
/etc/profile.d/quantum.sh:27: command not found: complete

### ISSUE THREAD

**Issue by alanwilter** [robbyrussell/oh-my-zsh#4586]
It started to happen when I login at my work cluster.

I am using 

commit e44aa50301cbdb9c713193263e6c0c5a9a5798c0
Merge: ba20b98 e9de366
Author: Marc Cornellà <marc.cornella@live.com>
Date:   Wed Oct 21 17:45:44 2015 +0200

**Comment by alanwilter** [comment]
I am accessing a "Red Hat Enterprise Linux Server release 6.6 (Santiago)"

**Comment by apjanke** [comment]
This doesn't sound like an Oh My Zsh issue. The file `/etc/profile.d/quantum.sh` is from a different program, and OMZ does not define a `complete` command. Sounds like that file is meant to be run under a different shell, like `bash`, not `zsh`. Maybe your `~/.zshrc` or other `zsh` startup files are over-aggressively pulling in files for other shells.

See [this bug](https://bugs.launchpad.net/neutron/+bug/1178037).

**Comment by alanwilter** [comment]
Thanks, indeed, I passed that to the sysadmin.
