### ISSUE TITLE
echo $SHELL prints /bin/bash

### ISSUE THREAD

**Issue by chirag7jain** [robbyrussell/oh-my-zsh#4596]
echo $SHELL prints /bin/bash

shouldn't it be printing /bin/zsh

**Comment by apjanke** [comment]
Probably. `$SHELL` is the path to your default shell, so it seems like your default shell didn't get changed to `zsh`. If this is the case, you can fix it yourself with `chsh -s /bin/zsh`.

**Comment by mixania** [comment]
I hope my problem is relevant to this issue. I am having problems making oh-my-zsh work in both Terminal an iTerm2. I tried everything from changing the default shell, to configuring the settings. Here is a screenshot of my attempt to apply the agnoster theme in iTerm: 
![iTerm](http://i.imgur.com/IE936dv.png)

Same attempt in Terminal:
 ![iTerminal](http://i.imgur.com/Hv03Sxq.png)

Regarding the issue, here is what $SHELL command gives me: 
![$SHELLr](http://i.imgur.com/0xrpJJH.png)

**Comment by apjanke** [comment]
Agnoster requires a special Powerline-patched font in order to display properly. See its README.

**Comment by mixania** [comment]
@apjanke So from what I understood, my *oh-my-sh* is running correctly my terminal. Like you said, I just need to read README files more often. Is that also might be why the background is in no way influenced by the themes?

**Comment by apjanke** [comment]
That's what it seems like. But in this case I think I misled you: there's no README for Agnoster in Oh My Zsh. (Only in the [upstream Agnoster repo](https://github.com/agnoster/agnoster-zsh-theme).) Sorry.

The `themes/agnoster.zsh-theme` has info about the fonts it needs in the comments of the file itself. So if a theme isn't working, taking a look at the theme's source code to see if there are notes on its requirements is also a good place to look.

**Comment by ncanceill** [comment]
@chirag7jain is your issue fixed?

**Comment by mcornella** [comment]
Closing for the time being. Reopen if it's not solved.

**Comment by chirag7jain** [comment]
i think some recent update has fixed the issue.

I am getting the correct output now
