### ISSUE TITLE
Autocompletion drives me up the wall

### ISSUE THREAD

**Issue by fiesh** [robbyrussell/oh-my-zsh#4599]
After installing oh-my-zsh, the new autocompletion has given me rise in blood pressure that is unsustainable.  Behold:

```
fiesh@wsbox ~ $ mkdir /tmp/arg && cd /tmp/arg
fiesh@wsbox /tmp/arg $ touch coin-download coin_i686-w64-mingw32.shared coin_x86_64-w64-mingw32.shared coin_x86_64-w64-mingw32.static
fiesh@wsbox /tmp/arg $ cat coin<TAB>
```

Now the following happens: `zsh` adds a hyphen, positions the cursor before the hyphen. After the first `<TAB>`, pressing tab again autocompletes to `coin-download`.  WTF. (Not as in cycling through the options, but autocompletes-and-moves-on wise.)

I suppose this is some very smart autocompletion that outsmarts me instantly.  I'd really appreciate it if there was some mentioning of it, how to use it properly, and especially how to get rid of it.

Thanks!

**Comment by apjanke** [comment]
This is from [the completion `zstyle` settings in `lib/completion.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/b42efeb87ebdcb89510b8ffbcf210494f194109e/lib/completion.zsh#L13-L24).

You can get simpler behavior by sticking this or something similar in your `~/.zshrc` after the point where it loads OMZ.

```
# Lowercase matches uppercase but not vice-versa
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
```

You can also completely replace OMZ's completion setup with your own by adding a `lib/completion.zsh` file to your `$ZSH_CUSTOM` dir (by default, `~/.oh-my-zsh/custom`), which will shadow the one in OMZ.

**Comment by fiesh** [comment]
Awesome, thank you so much!  I think it'd be great if this was somehow documented.
