### ISSUE TITLE
colors: function definition file not found

### ISSUE THREAD

**Issue by zhuhan1236** [robbyrussell/oh-my-zsh#4607]
After I've uncommented all the plugins and type command "source .zshrc", the following errors come out:

"""
/home/zhuhan/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/zhuhan/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
.zshrc:99: compinit: function definition file not found
"""

---

My system is "CentOS 7". zsh version is "zsh 5.0.2 (x86_64-redhat-linux-gnu)". oh-my-zsh is the master branch "135c376".

And if I enable git plugin, "source .zshrc" gives the following error:

"""
home/zhuhan/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/zhuhan/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:90: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:96: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:105: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:114: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:116: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:125: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:127: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:135: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:141: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:143: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:148: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:151: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:166: command not found: compdef
/home/zhuhan/.oh-my-zsh/plugins/git/git.plugin.zsh:177: command not found: compdef
.zshrc:99: compinit: function definition file not found
"""

line 99 of my .zshrc file is "autoload -U compinit && compinit -u"

---

With git plugin, if I cd to any dir managed by git, the following error will show up:

"""
prompt_git:37: vcs_info: function definition file not found
"""

**Comment by apjanke** [comment]
Could be a corrupted zcompdump file. Try `rm ~/.zcompdump*` and restarting your session.

These "missing" functions are provided by `zsh` itself. Check to make sure your `zsh` installation is okay, and that `$fpath` is being initialized.

**Comment by zhuhan1236** [comment]
Thanks a lot, export $FPATH works for me!

**Comment by apjanke** [comment]
Interesting... I thought `$FPATH` should be exported by default. Is this the default `zsh` installation for CentOS?

**Comment by zhuhan1236** [comment]
Yes, I used yum install to install zsh. Actually, $FPATH is exported by default. But after I use " echo 1 > /proc/sys/vm/drop_caches" to drop memory caches, it comes to be wrong and I don't know how to fix it

**Comment by apjanke** [comment]
Well, that's odd. Seems like that shouldn't happen, since `drop_caches` is supposed to be non-destructive. Perhaps this is a lower-level `zsh` or Linux issue.

**Comment by appleparan** [comment]
I have a same problem, but my problem doesn't related to "echo 1 > /proc/sys/vm/drop_caches". I'm using zsh without root permission, but set SHELL as my custom zsh location. is that a cause of problem?

**Comment by appleparan** [comment]
I installed my zsh as $HOME/usr, so I added $HOME/usr/share/zsh/'version of zsh'/functions then BOOM! it solved.

**Comment by apjanke** [comment]
You shouldn't need to add that `functions` dir manually; it should be compiled in by default if `zsh` was built correctly, with `$HOME/usr` as its `PREFIX`.

**Comment by croydondias** [comment]
@appleparan can you clarify exactly what you did please? as I'm seeing the same issue as you on my end.

zsh version = 5.0.5

**Comment by XStargate** [comment]
@croydondias 

Add ```export FPATH=$HOME/usr/share/zsh/'version of zsh'/functions:$FPATH``` in your .zshrc

**Comment by rguareschi** [comment]
The solution proposed by @XStargate worked like a charm!

**Comment by richaeell** [comment]
> Could be a corrupted zcompdump file. Try `rm ~/.zcompdump*` and restarting your session.
> 
> These "missing" functions are provided by `zsh` itself. Check to make sure your `zsh` installation is okay, and that `$fpath` is being initialized.

How do you check if its beenig initialized?

**Comment by eriknomitch** [comment]
> @croydondias
> 
> Add `export FPATH=$HOME/usr/share/zsh/'version of zsh'/functions:$FPATH` in your .zshrc

Thanks, this led me to some digging around.

For my system (`zsh` installed via `brew`) a cleaner fix was appending this to the top of my `~/.zshrc`:

```Shell
 export FPATH="/usr/local/share/zsh/functions:$FPATH"
```

This way it's version-agnostic.

**Comment by kurkutesa** [comment]
> > @croydondias
> > Add `export FPATH=$HOME/usr/share/zsh/'version of zsh'/functions:$FPATH` in your .zshrc
> 
> Thanks, this led me to some digging around.
> 
> For my system (`zsh` installed via `brew`) a cleaner fix was appending this to the top of my `~/.zshrc`:
> 
> ```shell
>  export FPATH="/usr/local/share/zsh/functions:$FPATH"
> ```
> 
> This way it's version-agnostic.

This works perfectly on my High Performance Computing Clusters.
```shell
/cvmfs/cluster_name/nix/var/nix/profiles/16.09/share/zsh/version/functions
``` 
I am using Canadian Supercomputer cluster and the zsh version is 5.2

**Comment by BenjiTheC** [comment]
> @croydondias
> 
> Add `export FPATH=$HOME/usr/share/zsh/'version of zsh'/functions:$FPATH` in your .zshrc

This lovely solution saved my day!

**Comment by fergalmoran** [comment]
None of the solutions here worked for me, I eventually figured it was caused by installing linuxbrew and adding

`export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin`

to the end of my ~/.zshrc file

**Comment by xZero707** [comment]
I know this issue is quite old, but I've recently encountered this issue on my Alpine server, and no solution worked for me. Not even a reinstall of omz. It seems to be related to omz update, but I'm not sure. 

The solution in my case was to remove omz, remove zsh package, exit, log in again and install omz and zsh again.

**Comment by rwmitchell** [comment]
zsh recently updated versions, which would have changed the path used in $FPATH for zsh defined functions.  other folks have also been having similar issues - wonder if there is a correlation?

**Comment by mcornella** [comment]
## All solutions saying to use `export FPATH` in this thread are wrong. `$FPATH` and it's equivalent `$fpath` variables should never be exported.

## If you encounter an issue and when you run `typeset -p FPATH` you see `export` in the output you should look in your .zshrc file for a line saying `export FPATH` and remove it.

## After that you'll need to log out of your user session and log back in.

## EXPLANATION:
## Zsh should be able to figure out the proper `$FPATH` value on startup, BUT IF `$FPATH` IS EXPORTED THE OLD VALUE GETS IN THE WAY AND THIS ISSUE WILL REAPPEAR EVERY TIME YOU UPDATE YOUR ZSH VERSION
