### ISSUE TITLE
Throwing PREFIX error nvm / node

### ISSUE THREAD

**Issue by jylinman** [robbyrussell/oh-my-zsh#4609]
I was getting this error when I started my terminal and when I would try to specify node versions with nvm: `nvm is not compatible with the npm config "prefix" option: currently set to "/Users/----/.nvm/versions/node/v0.12.7"
Run `nvm use --delete-prefix v0.12.7` to unset it.`

```
nvm deactivate ; nvm debug ; echo $PREFIX ; echo $NPM_CONFIG_PREFIX
Could not find /Users/albanda/.nvm/*/bin in $PATH
Could not find /Users/albanda/.nvm/*/share/man in $MANPATH
$SHELL: /usr/local/bin/zsh
$NVM_DIR: '$HOME/.nvm'
$PREFIX: '---'
$NPM_CONFIG_PREFIX: ''
nvm current: system
which node: /usr/local/bin/node
which iojs: iojs not found
which npm: /usr/local/bin/npm
npm config get prefix: /usr/local
npm root -g: /usr/local/lib/node_modules
---
```

Is there any objection to maybe adding `unset PREFIX` to the theme files like this? I added it to my theme file, and can now continue work... `https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/sunrise.zsh-theme`  

This issue was related to https://github.com/creationix/nvm/issues/855 but not quite the same issue.

**Comment by apjanke** [comment]
I think we already have a PR open for this: #4572. Looks like `sunrise` is the only theme to use `$PREFIX` like this. Does #4572 work for you?

**Comment by jylinman** [comment]
Hey @apjanke I must have missed that.  Yeah renaming it works-- I might personally prefer unsetting the variable for future things that may, for whatever reason, use the variable they changed it to-- but it works... So why not ;)
