### ISSUE TITLE
option to disable aliases

### ISSUE THREAD

**Issue by Konfekt** [robbyrussell/oh-my-zsh#4611]
To use aliases in the Vim editor  by `:!`, these have to be defined in `.zshenv`. However, `oh-my-zsh`, sourced after it, overrides common ones such as `o` or `l`. How to stop it doing that?

**Comment by apjanke** [comment]
There's a discussion on this in #4585.

**Comment by Konfekt** [comment]
Thanks, grepped consciously for it but didn't see it.
