### ISSUE TITLE
NixOS: Cannot "source .zshrc" (autoload: command not found)

### ISSUE THREAD

**Issue by adinapoli** [robbyrussell/oh-my-zsh#4613]
Hey folks,

On a pristine NixOS installation, when I try to source my `.zshrc` I get this:

```
[alfredo@unluckystar:~]$ source .zshrc
autoload: command not found
-bash: /home/alfredo/.oh-my-zsh/oh-my-zsh.sh: line 31: syntax error near unexpected token `('
-bash: /home/alfredo/.oh-my-zsh/oh-my-zsh.sh: line 31: `for config_file ($ZSH/lib/*.zsh); do'
```

~~The culprit is indeed the fact my NixOS installation does not seem to have the `autoload` command. Googling around doesn't seem to yield anything meaningful.~~

EDIT: I'm just being stupid, as `autoload` seems to be provided by zsh and not from the OS.
I did install zsh following the guide here:

https://nixos.org/wiki/Using_the_ZSH_SHELL

Perhaps my installation is screwed?

Do you guys have any clue on how to workaround this? I'm a relatively new NixOS user.

Thanks a ton!

A.

**Comment by adinapoli** [comment]
I was just being stupid (twice!). Apparently `zsh` was not being loaded by NixOS as my default shell. Duh.

**Comment by ale-batt** [comment]
Same error on osx

**Comment by mcornella** [comment]
@ale-batt check that you have zsh as the default shell. `echo $SHELL` will do that.
If zsh is not your default shell, a `chsh -s $(which zsh)` will do it. Then, log out of your user session and log back in to apply the setting.

**Comment by ale-batt** [comment]
Forget to wrote, i solve it :) 👍 (just change to a backup from my zshrc)

**Comment by carlosfh87** [comment]
i fixed, i just uninstall npm and reinstalled again, if you have yarn installed uninstall yarn first and then npm:
```
brew uninstall yarn
brew uninstall npm
brew install npm

```
then close your term and open it again
