### ISSUE TITLE
gulp doesn't work properly in zsh

### ISSUE THREAD

**Issue by benzid-wael** [robbyrussell/oh-my-zsh#4615]
I have defined a default Gulp task, so executing `gulp` should be the same as `gulp default`. However, with the default oh-my-zsh configuration when I type `gulp` the shell execute `cd gulp`. I like this feature but the shell should try to change directory when he didn't find a command not the opposite.

So if it's not a bug, how can I configure zsh to work as I expect ?

**Comment by apjanke** [comment]
I'm not certain, but that sounds like a bug to me. I thought the command should take precedence over the directory, too.

The thing that enables this behavior is `setopt auto_cd`, which is done [here in `lib/theme-and-appearance.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/135c3763ccfb07c4a5cde9a2529dfa8d6ba19b39/lib/theme-and-appearance.zsh#L26).

I tried doing the same test with `gulp` and a couple other commands - `brew`, `vim` - by making a dir with that name, enabling `auto_cd`, and running the command. The command still took precedence. I'm on OS X 10.9.5.

Maybe there's something different about our configurations. What do you get for `which gulp`?

**Comment by tomasdev** [comment]
I'm not having this issue.
Are you sure you're on the directory where your gulpfile.js is? Same question, what do you get for `which gulp` ? Did you recently `npm install -g gulp`? It will be necessary to close and open terminal again for zsh to realize you have that command now (or so it does, in my experience)

**Comment by mcornella** [comment]
Yes please, run `which gulp` and if it says `gulp not found` install with `npm install -g gulp` and then run `rehash` (no need to restart the terminal, @tomasdev) to pick up the new gulp binary. After that, you should be able to run `gulp` without any problems.

**Comment by mcornella** [comment]
Closing for the time being. Reopen if necessary.

**Comment by benzid-wael** [comment]
@mcornella the gulp was installed globally and after reopening the terminal, but it seems also to be an issue behind this, because if zsh don't realize that I have installed ``zsh`` he should notify me with an error message when I executed ``gulp some_task``

**Comment by apjanke** [comment]
Doing `gulp some_task` will throw an error if there is no `gulp` command installed. It's only plain `gulp` with no arguments which will `cd` in to the directory instead.

```
[~/tmp/test-gulp]
$ ls
[~/tmp/test-gulp]
$ mkdir gulp
[~/tmp/test-gulp]
$ which gulp
gulp not found
[✘ ~/tmp/test-gulp]
$ gulp default
zsh: command not found: gulp
[✘ ~/tmp/test-gulp]
$ gulp
[~/tmp/test-gulp/gulp]
$ pwd
/Users/janke/tmp/test-gulp/gulp
```

This is normal behavior for `zsh`, and aside from enabling `auto_cd`, Oh My Zsh doesn't affect this.

> It will be necessary to close and open terminal again for zsh to realize you have that command now (or so it does, in my experience)

You can also just run `rehash` in an existing `zsh` session to get it to re-scan for newly installed commands. I also like to set `zstyle ':completion:*' rehash true` so it will do this automatically when performing command completion.

**Comment by mcornella** [comment]
> But I think that there are an issue behind this case, because if zsh don't realize that I have installed zsh he should notify me with an error message when I executed gulp some_task

That is a very common complaint. You can set up automatic rehash in your zshrc but there is the potential to slow down the prompt [if you have NFS paths in your `$PATH` for example](http://unix.stackexchange.com/a/2180). What @apjanke said is exactly how you enable that:

> I also like to set `zstyle ':completion:*' rehash true` so it will do this automatically when performing command completion.

**Comment by mgol** [comment]
I have a similar (but even worse) issue, see #5735.
