### ISSUE TITLE
mercurial plugin readme file should be update

### ISSUE THREAD

**Issue by shellvon** [robbyrussell/oh-my-zsh#4616]
Sorry, I am not good at English.
In the readme file content

> e.g. plugins = (..., mercurial, ...) (that is pretty obvious).

should be update with
> e.g. plugins = (... mercurial ...) (that is pretty obvious).

en ,i means ..it should be replaced the `comma` into `backspace`.
because it will cause misunderstanding to some users

**Comment by apjanke** [comment]
Good catch. I've put in a PR to do so: #4619.
