### ISSUE TITLE
First characters of prompt are repeated after tab autocompletion (FreeBSD)

### ISSUE THREAD

**Issue by jSherz** [robbyrussell/oh-my-zsh#4632]
Apologies if this has been posted before - I can't seem to find it in the active issues. I'm experiencing this bug on FreeBSD running the latest oh-my-zsh.

It happens (seemingly at random) after typing a command, pressing space and then using tab to do a completion.

What I get is the following:

    ➜  ~  cdcd ~/projects/

Pressing enter will correctly perform the command (it's just a visual bug that doesn't affect the text).

Has anyone ever seen this?

    ➜  ~  zsh --version 
    zsh 5.1.1 (amd64-portbld-freebsd10.1)

**Comment by apjanke** [comment]
Sounds similar to #4529 or #3932. Could be an issue with the font and terminal not agreeing on the width of characters, or possibly non-printing characters being emitted in the prompt and not properly escaped. Strange that it only happens sometimes, though. Are there particular completion activities that will regularly reproduce it?

Does it happen with other themes?

**Comment by jSherz** [comment]
I'm using Solarized Light currently but will try with some others and see if the problem still occurs. Unfortunately, I've got no idea what causes it but I'll keep an eye out and look back at my history when it comes back.

Thanks!

**Comment by apjanke** [comment]
Solarized is a colorscheme (a set of particular color values for your terminal to display for the palette of ANSI colors), not an OMZ theme. The OMZ theme is set by `$ZSH_THEME` and controls how the prompt is displayed in terms of formatting and contents. Might also be affected by the font you're using. Looks like you're using the `robbyrussell` theme. That right-pointing arrow in the theme may be a wide character (two character "cells" for a monospaced font), and if the font and terminal don't agree on how wide it is, that could cause display issues.

**Comment by jSherz** [comment]
My mistake! As you pointed out, I'm using `robbyrussell`. I'll try a different theme over the next few days and see if the problem reappears.

**Comment by jSherz** [comment]
Confirmed it's specific to that theme so I'll investigate why the arrow is displayed incorrectly. Thanks for your help!

**Comment by barhom** [comment]
I'm also having this issue with the 'cloud' theme.
@jSherz did you manage to fix it ?

**Comment by xh3b4sd** [comment]
@barhom I had the same problem and found a solution working for me here: https://github.com/robbyrussell/oh-my-zsh/issues/5157#issuecomment-226031519.

**Comment by ajaychk** [comment]
same issue with robbyrussell theme

**Comment by DSLituiev** [comment]
same issue with `powerlevel9k/powerlevel9k` scheme

**Comment by stephane-archer** [comment]
> 
> 
> Confirmed it's specific to that theme so I'll investigate why the arrow is displayed incorrectly. Thanks for your help!

did you find a solution? I have the same problem...

**Comment by stephane-archer** [comment]
put export LC_ALL="en_US.UTF-8" at the end of your .zshrc and see if it fixes that.

**Comment by tsauvajon** [comment]
> put export LC_ALL="en_US.UTF-8" at the end of your .zshrc and see if it fixes that.

I would suggest using `export LC_ALL=$LANG` if your $LANG is not `en_US`

**Comment by 13-05** [comment]
i'm having this same issue, and none of the listed solutions worked (including the one on the faq).
`locale`:

![image](https://user-images.githubusercontent.com/64506392/196813830-e27bdfe0-12a8-4100-92f9-a1f270b9e873.png)

**Comment by mcornella** [comment]
Make sure you have installed that locale, it should appear in `locale -a`.

**Comment by 13-05** [comment]
> Make sure you have installed that locale, it should appear in `locale -a`.

hey, i think that's the issue, but i can't seem to install the locale!

![image](https://user-images.githubusercontent.com/64506392/197410067-7601c98a-55bb-46d9-b53a-8f21e74fc811.png)

i've tried a ton of things, and in `/etc/locale.gen` `en_US.UTF-8` IS uncommented, so i'm not sure what the issue is! every time i do `locale-gen`, it works as expected:

![image](https://user-images.githubusercontent.com/64506392/197410170-1da1c3f4-f43a-4e60-af70-5a5623303d41.png)

i'll keep troubleshooting, but if you know any ways i can fix it, please let me know :)

**Comment by mcornella** [comment]
Try using `en_US.utf8` exactly as it appears in the `locale -a` output.
```sh
export LANG=en_US.utf8
```

**Comment by 13-05** [comment]
still happens:

![image](https://user-images.githubusercontent.com/64506392/198001964-29bf420e-0c1b-4ebb-b27d-d140688dc44d.png)

**Comment by mcornella** [comment]
What theme are you using?
