### ISSUE TITLE
thefuck plugin causes zsh to hang

### ISSUE THREAD

**Issue by gAmUssA** [robbyrussell/oh-my-zsh#4656]
I activated `thefuck` plugin and zsh ever shows a promt.
To test the side effects of other plugins, I disabled everything except `thefuck` plugin.
Thank you

cc @kyleheyne @black-roland

**Comment by mcornella** [comment]
Please run zsh in debug mode to see where it got stuck: run `zsh -xv` and post the last lines of output that you can see.

**Comment by gAmUssA** [comment]
Hi @mcornella 

```
+/Users/apple/.oh-my-zsh/oh-my-zsh.sh:81> plugin=thefuck
+/Users/apple/.oh-my-zsh/oh-my-zsh.sh:82> [ -f /Users/apple/.oh-my-zsh/custom/plugins/thefuck/thefuck.plugin.zsh ']'
+/Users/apple/.oh-my-zsh/oh-my-zsh.sh:84> [ -f /Users/apple/.oh-my-zsh/plugins/thefuck/thefuck.plugin.zsh ']'
+/Users/apple/.oh-my-zsh/oh-my-zsh.sh:85> source /Users/apple/.oh-my-zsh/plugins/thefuck/thefuck.plugin.zsh
if [[ -z $commands[thefuck] ]]; then
    echo 'thefuck is not installed, you should "pip install thefuck" first'
    return -1
fi
+/Users/apple/.oh-my-zsh/plugins/thefuck/thefuck.plugin.zsh:1> [[ -z /usr/local/bin/thefuck ]]

# Register alias
eval "$(thefuck --alias)"
+/Users/apple/.oh-my-zsh/plugins/thefuck/thefuck.plugin.zsh:7> thefuck --alias
```

**Comment by mcornella** [comment]
So this gets stuck on the `thefuck --alias` call. Ok, try running that directly from bash. If that works, try running it from zsh without the `thefuck` plugin enabled, and let's see what's going on.

**Comment by gAmUssA** [comment]
```
$ thefuck --alias
No fuck given

```

same output in in bash and in zsh without thefuck plugin

**Comment by gAmUssA** [comment]
quick update.
Definitely it was something wrong with command itself so I reinstall `thefuck` from scratch.
Now it seems to work.

Thank for help @mcornella

**Comment by mcornella** [comment]
Great news thank you.
