### ISSUE TITLE
Command not found: __git_aliased_command

### ISSUE THREAD

**Issue by tdyer-aio** [robbyrussell/oh-my-zsh#4658]
This is probably a dupe of https://github.com/robbyrussell/oh-my-zsh/issues/4553 but it was closed... Here is a gist of my omz_diagdump: https://gist.github.com/tdyer-aio/b3e8d9f794b521f2fd81

That said... running `omz_diagnostic_dump` seems to fix the issue I was having. (specifically `git checkout top<tab>` was causing the tab completion to have issues in the above manner, than it would start a function i defined in my zshrc that had been named `test`

**Comment by apjanke** [comment]
Sounds similar to #4553 but this is new info since you're not running `gitfast`. Want to post this as a comment over there and we'll reopen it? No need to split in to separate issues.

**Comment by tdyer-aio** [comment]
will do

**Comment by apjanke** [comment]
> then it would start a function i defined in my zshrc that had been named `test`

Don't define a function called `test`. That's a standard shell command and redefining it will break things. I don't see it in your .zshrc, though.

> running omz_diagnostic_dump seems to fix the issue I was having

Beats me why that would happen. `omz_diagnostic_dump` is supposed to be minimally invasive and not change anything about your shell state.

Continuing the rest of the conversation over on #4553.
