### ISSUE TITLE
errors in zsh 4.3.10

### ISSUE THREAD

**Issue by wiggin15** [robbyrussell/oh-my-zsh#4664]
I'm using zsh 4.3.10 (the default on CentOS/RedHat 6.x), which should be supported according to the README.
When I open zsh and start typing, the text I type is discarded and an error appears:

    [root@host-ci023 ~]# zsh --version
    zsh 4.3.10 (i386-redhat-linux-gnu)
    [root@host-ci023 ~]# zsh
    root@host-ci023 (Redhat 6.1) ➜  ~  d
    _zsh_highlight_main_highlighter:95: error in flags
    root@host-ci023 (Redhat 6.1) ➜  ~  d
    root@host-ci023 (Redhat 6.1) ➜  ~  s
    _zsh_highlight_main_highlighter:95: error in flags
    root@host-ci023 (Redhat 6.1) ➜  ~  s
    root@host-ci023 (Redhat 6.1) ➜  ~  a
    _zsh_highlight_main_highlighter:95: error in flags
    root@host-ci023 (Redhat 6.1) ➜  ~  a
    root@host-ci023 (Redhat 6.1) ➜  ~

(in this case, I typed 'dsa' into zsh)

Using git bisect, I see that this is broken since 16535452829d36f5382b176216a9ad312b2be1e5 (added `setopt interactivecomments`) and that the line that causes the error is main-highlighter.zsh:101:

    local interactive_comments= # set to empty

Removing this line or reverting the commit fixes the issue.

Please help by fixing this or by updating the README with the minimum supported zsh version.

**Comment by apjanke** [comment]
There's no `main-highlighter.zsh` or `_zsh_highlight_main_highlighter` in Oh My Zsh. That looks like it's part of [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting/blob/73ee7c1f6c4a2bbb77029a93c79e0289e0ffef57/highlighters/main/main-highlighter.zsh#L101). According to [its README](https://github.com/zsh-users/zsh-syntax-highlighting/tree/73ee7c1f6c4a2bbb77029a93c79e0289e0ffef57#zsh-syntax-highlighting), it requires Zsh 4.3.17+.

**Comment by wiggin15** [comment]
Ah. My mistake. Thanks!

**Comment by donatj** [comment]
It would appear updating from zsh 4.3.10 -> 4.3.11 fixed the above issue for me.

**Comment by sagioto** [comment]
This still happens to me with `zsh 5.3.1 (x86_64-unknown-linux-gnu)` and a fresh install of `oh-my-zsh`
This is the error I'm seeing: `_zsh_highlight_highlighter_main_paint:130: error in flags`
I'm using a `tmux 2.3` session

**Comment by chenxinle** [comment]
can not do anything from the command line when seeing the problem, how can you "Removing this line or reverting the commit fixes the issue"
