### ISSUE TITLE
EOL errors in latest oh-my-zsh

### ISSUE THREAD

**Issue by dogrizz** [robbyrussell/oh-my-zsh#4665]
/home/login/.oh-my-zsh/tools/check_for_upgrade.sh:2: command not found: ^M
    /home/login/.oh-my-zsh/tools/check_for_upgrade.sh:3: invalid module name `zsh/datetime^M'
    /home/login/.oh-my-zsh/lib/functions.zsh:25: parse error near `in^M'
    /home/login/.oh-my-zsh/lib/termsupport.zsh:21: parse error near `elif'
dos2unix on those files seems to solve the issue.
I upgraded today.

**Comment by apjanke** [comment]
Are you on Cygwin/Windows? Check to see if you have your `git` configured to do autocrlf. That could cause this. The files in the repo are checked in with Unix mode line endings.

(There's a pending PR #4071 to keep that from happening, regardless of user configuration.)

**Comment by dogrizz** [comment]
I'm on ubuntu. Will check the autocrlf.

**Comment by maxmumford** [comment]
I had this problem on Mac after updating ZSH today. Fixed with:

```
cd ~/.oh-my-zsh/
find . -name "*.*" | xargs dos2unix
```
