### ISSUE TITLE
mysql-colorize plugin gives weird characters

### ISSUE THREAD

**Issue by linbynd** [robbyrussell/oh-my-zsh#4666]
I enabled the plugin mysql-colorize and this created below symlink for mysql command. But when I access the db and fire ```show database``` it shows up weird characters

```
➜  ~  which mysql                                                                                                                                                    
mysql: aliased to /usr/local/bin/mysql --pager=/Users/vinitkhandagle/.oh-my-zsh/custom/plugins/mysql-colorize/mycat --pager=/Users/vinitkhandagle/.oh-my-zsh/custom/plugins/mysql-colorize/mycat
```
The only way I found was to unalias the mysql command and disable the plugin.

**Comment by apjanke** [comment]
Where did you find the `mysql-colorize` plugin? That's not part of the main Oh My Zsh distribution.
