### ISSUE TITLE
Sudden launch problem

### ISSUE THREAD

**Issue by theoden8** [robbyrussell/oh-my-zsh#4669]
Hello,

Before an hour ago, after I updated my packages and, perhaps, `OMZ`, my configuration stopped working. I no longer have autocompletion, syntax highlighting and arrow. Please, help me!

When I launch **OMZ**, I get the following error:

		$ZSH/lib/completion.zsh:11: failed to load module `zsh/zle': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/zle.so, 9): image not found
	$ZSH/lib/completion.zsh:15: failed to load module `zsh/zle': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/zle.so, 9): image not found
	$ZSH/lib/completion.zsh:26: command not found: zstyle
	$ZSH/lib/completion.zsh:29: failed to load module `zsh/zle': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/zle.so, 9): image not found
	$ZSH/lib/completion.zsh:31: command not found: zstyle
	$ZSH/lib/completion.zsh:32: command not found: zstyle
	$ZSH/lib/completion.zsh:37: command not found: zstyle
	$ZSH/lib/completion.zsh:41: command not found: zstyle
	$ZSH/lib/completion.zsh:44: command not found: zstyle
	$ZSH/lib/completion.zsh:45: command not found: zstyle
	$ZSH/lib/completion.zsh:48: command not found: zstyle
	$ZSH/lib/completion.zsh:59: command not found: zstyle
	$ZSH/lib/completion.zsh:71: failed to load module `zsh/zle': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/zle.so, 9): image not found
	$ZSH/lib/completion.zsh:72: command not found: bindkey
	$ZSH/lib/functions.zsh:104: failed to load module `zsh/langinfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/langinfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:7: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:18: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:20: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:21: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:22: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:23: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:26: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:30: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:33: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:37: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:40: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:44: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:46: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:47: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:49: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:53: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:54: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/lib/key-bindings.zsh:57: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:58: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:59: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:64: command not found: zle
	$ZSH/lib/key-bindings.zsh:65: command not found: bindkey
	$ZSH/lib/key-bindings.zsh:68: command not found: bindkey
	$ZSH/lib/theme-and-appearance.zsh:2: colors: function definition file not found
	$ZSH/oh-my-zsh.sh:77: compinit: function definition file not found
	/usr/local/opt/pyenv/libexec/../completions/pyenv.zsh:5: failed to load module `zsh/zle': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/zle.so, 9): image not found
	$ZSH/plugins/git/git.plugin.zsh:2: command not found: zstyle
	$ZSH/plugins/gitfast/../git/git.plugin.zsh:2: command not found: zstyle
	$ZSH/plugins/git-flow/git-flow.plugin.zsh:355: command not found: zstyle
	$ZSH/plugins/git-flow-avh/git-flow-avh.plugin.zsh:419: command not found: zstyle
	$ZSH/plugins/git-hubflow/git-hubflow.plugin.zsh:355: command not found: zstyle
	$ZSH/plugins/github/github.plugin.zsh:2: failed to load module `zsh/parameter': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/parameter.so, 9): image not found
	$ZSH/plugins/sudo/sudo.plugin.zsh:23: command not found: zle
	$ZSH/plugins/sudo/sudo.plugin.zsh:25: command not found: bindkey
	$ZSH/plugins/fasd/fasd.plugin.zsh:1: failed to load module `zsh/parameter': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/parameter.so, 9): image not found
	$ZSH/plugins/history-substring-search/history-substring-search.zsh:72: command not found: zle
	$ZSH/plugins/history-substring-search/history-substring-search.zsh:73: command not found: zle
	$ZSH/plugins/history-substring-search/history-substring-search.zsh:79: failed to load module `zsh/parameter': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/parameter.so, 9): image not found
	$ZSH/plugins/history-substring-search/history-substring-search.zsh:87: failed to load module `zsh/parameter': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/parameter.so, 9): image not found
	zsh-syntax-highlighting: failed loading zsh/zleparameter.
	$ZSH/plugins/history-substring-search/history-substring-search.plugin.zsh:17: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/plugins/history-substring-search/history-substring-search.plugin.zsh:20: failed to load module `zsh/terminfo': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/terminfo.so, 9): image not found
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:7: command not found: bindkey
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:9: command not found: bindkey
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:13: command not found: bindkey
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:14: command not found: bindkey
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:16: command not found: bindkey
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:18: command not found: zle
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:19: command not found: zle
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:20: command not found: zle
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:21: command not found: zle
	$ZSH/plugins/safe-paste/safe-paste.plugin.zsh:22: command not found: zle
	$ZSH/plugins/common-aliases/common-aliases.plugin.zsh:85: command not found: zstyle
	zsh-syntax-highlighting: failed loading zsh/zleparameter.
	zsh-syntax-highlighting: failed binding ZLE widgets, exiting.

$ZSH stands for `path/to/oh-my-zsh` and has no spaces or special characters.

I am on **OS X** with `zsh` reinstalled via homebrew.

**Comment by apjanke** [comment]
```
failed to load module `zsh/zle': dlopen(/usr/local/Cellar/zsh/5.1.1/lib/zsh/zle.so, 9): image not found
```

That sounds like your `zsh` installation is broken, or something else is going wrong at a system level. Try uninstalling `zsh` and installing it again. And run `brew doctor` to see of anything is odd with your Homebrew setup.

**Comment by dannyperson** [comment]
If anyone cares, I think this happens when you upgrade system zsh. Just reload zsh with `exec zsh`.

**Comment by chrismejia** [comment]
> If anyone cares, I think this happens when you upgrade system zsh. Just reload zsh with `exec zsh`.

This worked like a charm!

**Comment by tstilz** [comment]
running `exec zsh` will fix the current terminal, but it doesn't fix the root problem.
>>  "default shell throwing errors on load" 

I hit this problem on MacOS 10.14.6   which has default zsh:5.2
You couldn't find how to edit the PATH or the zsh path before the terminal started, so I put a symlink to the new zsh version where the last one was.   
```
mv /bin/zsh /bin/zsh_5.2
ln -s /usr/local/bin/zsh .
```

**Comment by mishell-trickster** [comment]
I have problem with launch zsh. Same error:
`failed to load module `zsh/zle':  /usr/lib64/zsh/5.0.2/zsh/zle.so: file not found`
But I install zsh package into custom folder $HOME/centos/{bin,etc,usr} and I have all dependencies at path like this
`$HOME/centos/usr/lib64/zsh/5.0.2/zsh/zle.so`

How can I change default library dir for zsh? My LD_LIBRARY_PATH is empty. I change this variable, but doesnt work, zsh try look for libraries at root dir, not in my home dir.
