### ISSUE TITLE
Conflict between the pyenv and oh-my-zsh's pyenv-plugin

### ISSUE THREAD

**Issue by ccqpein** [robbyrussell/oh-my-zsh#4674]
Pyenv-plugin in oh-my-zsh did someting for pyenv, and make it has a very weird path. I add this problem in [pyenv 20151105 can't load "~/.pyenv"](https://github.com/yyuu/pyenv/issues/476).

**Comment by duyt1001** [comment]
Is there plan to fix this one? I encountered the same issue when I added pyenv to the plugins list.

**Comment by ccqpein** [comment]
My solution is "do not use pyenv plugin"....

**Comment by mcornella** [comment]
The new version should work as intended. Please try it again!

**Comment by ccqpein** [comment]
It looks like `which python` show right path to pyenv now. thanks!
