### ISSUE TITLE
nvm_prompt_info() printed wrong on Windows

### ISSUE THREAD

**Issue by Snack-X** [robbyrussell/oh-my-zsh#4677]
I'm using oh-my-zsh at everywhere, including my desktop in Windows with Cygwin and MinTTY, which is installed by [Babun](http://babun.github.io/). I use bureau theme, and it has nvm support.

As far as I checked, on Linux and OS X, `node -v` command returns `vX.Y.Z\n`. But on Windows, `node -v` command returns `vX.Y.Z\r\n`.
I don't know how does zsh or oh-my-zsh handle trailing newline characters, but I suppose it strips only last `\n`, so on Windows, [`$nvm_prompt`](https://github.com/robbyrussell/oh-my-zsh/blob/16d07683058719811a7871cbf7bed066ac8fc784/lib/nvm.zsh#L7) still has trailing `\r` character.

I managed to patched `lib/nvm.zsh` file by myself to strip `\r` character on Cygwin environment. It's working, but I think there would be a better way to handle this problem.

Sorry for not including my patch or making a PR. I can't use my desktop right now.

**Comment by mcornella** [comment]
I presume this is no longer relevant. Reopen if necessary.
