### ISSUE TITLE
OSX El Capitan issue with profile.d/z.sh

### ISSUE THREAD

**Issue by cksachdev** [robbyrussell/oh-my-zsh#4679]
I recently upgraded to osx El Capitan. I remember installing zsh using brew. 
Issue I am facing is:
```
/Users/Sachdev/.zshrc:1: command not found: o#
/Users/Sachdev/.zshrc:.:11: no such file or directory: /usr/local/etc/profile.d/z.sh
```
There are 2 different formula z and zsh. I am not familiar with zsh and brew. But there are few commands which are not working now. e.g. sublime

Please suggest what could have gone wrong and how it can be fixed.

**Comment by apjanke** [comment]
Are you running Oh My Zsh? This doesn't look OMZ-specific. Oh My Zsh is a configuration layer on top of [Zsh](http://zsh.sourceforge.net/), and is a separate project.

`z` is basically unrelated to `zsh`. `zsh` is the shell you're running, and `z` is a utility to make jumping between various directories easier. (There is an Oh My Zsh plugin to load `z`, as with many other tools, but that's a coincidence.) The file `z.sh` is part of `z`, not `zsh`. Unfortunate spelling there. :)

That `/usr/local/etc/profile.d/z.sh` file is provided by the `z` formula. It looks like maybe you installed it using Homebrew, followed the formula's directions to add code to run it from your `~/.zshrc`, and then either uninstalled it or used that same `~/.zshrc` file on another machine that doesn't have `z` installed.

```
$ brew install z
==> Using the sandbox
==> Downloading https://github.com/rupa/z/archive/v1.9.tar.gz
==> Downloading from https://codeload.github.com/rupa/z/tar.gz/v1.9
######################################################################## 100.0%
==> Caveats
For Bash or Zsh, put something like this in your $HOME/.bashrc or $HOME/.zshrc:
  . `brew --prefix`/etc/profile.d/z.sh
==> Summary
🍺  /usr/local/Cellar/z/1.9: 4 files, 32K, built in 2 seconds
[~]
```

Those instructions could be a bit better, maybe having something to only load `z` if it is found. How about posting this as a bug [over in Homebrew](https://github.com/homebrew/homebrew/issues)?

> /Users/Sachdev/.zshrc:1: command not found: o#

This sounds like maybe there's a comment in your `.zshrc` that's missing a leading space, so it's not being parsed correctly as a comment, or a typo got stuck in there. Especially on line one of the file. Take a look at it and see if there's a typo. If you can't figure it out, post your `.zshrc` [as a gist](https://gist.github.com/) and link to it here, and someone will help you out.
