### ISSUE TITLE
rbenv_prompt_info give empty string

### ISSUE THREAD

**Issue by hnchuong** [robbyrussell/oh-my-zsh#4688]
This cause the ruby version + gemset part in the prompt blank

**Comment by mcornella** [comment]
You need to add the `rbenv` plugin for rbenv prompt support.

**Comment by hnchuong** [comment]
Of course I did add the plugin rbenv.

I've tried to run the line in the plugin:

      echo "$(rbenv gemset active 2&>/dev/null | sed -e ":a" -e '$ s/\n/+/gp;N;b a' | head -n1)"

but it give nothing.
