### ISSUE TITLE
A sudo-autofill function maybe?

### ISSUE THREAD

**Issue by hanbang-wang** [robbyrussell/oh-my-zsh#4691]
After typing a command, you can press 'up' to get the previous sentence of this command. It is perfectly fine. But when it come to `sudo` command, the oh-my-zsh will pull the last `sudo`.
For example, I run the `sudo vi test`, and then run the `sudo rm -rf test`, when I type in `sudo vi` and press the up button, it will come back to `sudo rm -rf test`, which is not what I wanted.
I was thinking if you can add a function to detect whether this command a sudo or not, and if there is another parameter following sudo, get back to that last command.
Sorry for my bad English :P

**Comment by mcornella** [comment]
You can add the `history-substring-search` to complete the line with commands that start with what you wrote. So if you wrote `sudo vim` and you press UP, it will use the last command that started with `sudo vim`.

**Comment by hanbang-wang** [comment]
wow nice, thx
