### ISSUE TITLE
Parameter autocompletion with "du"

### ISSUE THREAD

**Issue by tomasnorre** [robbyrussell/oh-my-zsh#4694]
Hi,

I don't know if this is default behavior or from a plugin i've activated.. 

I really like the feature of autocompletion of ls -l (etc) but when doing it with du -sh Va[Tab] then my terminal don't auto complete to the Vagrant directory anymore.. ls -l Va[Tab] works still.. 

I feel like it a bug, but correct me if i'm wrong :) 

It's on OSX and these are the plugins i have activated:

plugins=(git-flow github colored-man colored-man-pages osx screen vagrant git flow)

**Comment by mcornella** [comment]
This was already reported. See https://github.com/robbyrussell/oh-my-zsh/issues/4573#issuecomment-153439901: you can either update your `zsh` or copy the `_du` file from a newer version.

**Comment by tomasnorre** [comment]
Thanks for fast feedback..
