### ISSUE TITLE
OS X: colored-man-pages.plugin.zsh:1: no matches found: solaris*

### ISSUE THREAD

**Issue by christian-titze** [robbyrussell/oh-my-zsh#4699]
Commit 09d2a597a588abd69647c37b082009125ae07b9a broke something, at least on OS X.

After each login I get:
`colored-man-pages.plugin.zsh:1: no matches found: solaris*`

I suspect it has to do with the missing quotes and *-wildcard. However, I could not find a quick fix.

It worked perfectly when `solaris*` was still `"solaris"`.

**Comment by mcornella** [comment]
Sorry, my bad

**Comment by mcornella** [comment]
That should do it
