### ISSUE TITLE
forklift have option to open in a new window

### ISSUE THREAD

**Issue by gajus** [robbyrussell/oh-my-zsh#4703]
It would be nice if https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/forklift had an option to open the target path in a new ForkLift window. Now it uses the most recent ForkLift window.

**Comment by gajus** [comment]
cc @bitboxer

**Comment by bitboxer** [comment]
Sadly I won't find time to do this before christmas, but it should not be too hard. Maybe you can try to do it? Look here https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/forklift/forklift.plugin.zsh#L58 for an example how to open a new window.

**Comment by gajus** [comment]
Looks simple, though I don't feel comfortable making contributions outside of my knowledge domain.

**Comment by bitboxer** [comment]
Try it. There is nothing bad that could happen if you do. You will learn things. And isn't that a great opportunity to learn?

**Comment by apjanke** [comment]
Yeah, go for it!

Here's a suggestion to get you started: https://github.com/apjanke/oh-my-zsh/commit/30230e27e32b64c0925c7379a286a6b22f45c01e. That "here doc" made with `<<END` can interpolate variables. So you can insert optional text just by sticking in variables which are empty by default but you fill them in when you see an option.

**Comment by mcornella** [comment]
Reopen if there is still an interest in this and someone willing to implement it.
