### ISSUE TITLE
rkj-repos theme unusable!

### ISSUE THREAD

**Issue by Sumith1896** [robbyrussell/oh-my-zsh#4706]
I really like this a lot but this is unusable. Everytime I fire the I get this

```
┌─[sumith@sumith-Lenovo-Z50-70] - [~] - [2015-12-16 07:35:26]
└─[0] <Mercurial Distributed SCM

basic commands:

 add           add the specified files on the next commit
 annotate      show changeset information by line for each file
 clone         make a copy of an existing repository
 commit        commit the specified files or all outstanding changes
 diff          diff repository (or selected files)
 export        dump the header and diffs for one or more changesets
 forget        forget the specified files on the next commit
 init          create a new repository in the given directory
 log           show revision history of entire repository or files
 merge         merge working directory with another revision
 pull          pull changes from the specified source
 push          push changes to the specified destination
 remove        remove the specified files on the next commit
 serve         start stand-alone webserver
 status        show changed files in the working directory
 summary       summarize working directory state
 update        update working directory (or switch revisions)

use "hg help" for the full list of commands or "hg -v" for details> 
```
and I am not able to get out of this. 
Thank you.

**Comment by mcornella** [comment]
Your hg command doesn't have an `hg prompt` argument. Now, I don't use Mercurial so I don't know what alternative command there is to display a prompt, but you could just disable the Mercurial prompt function and call it a day.

To disable it put the following in your zshrc file, at the end of it:

```zsh
hg_prompt_info(){} 
```

**Comment by mcornella** [comment]
Oh right, this theme uses the [`hg-prompt` extension](http://sjl.bitbucket.org/hg-prompt/installation/). You can either install that, or if you don't care about it disable the hg prompt as I said before.

Ultimately we're going to put in place a mercurial prompt that doesn't require hg-prompt, but as you can see [here](https://github.com/robbyrussell/oh-my-zsh/labels/mercurial), there is quite the backlog of issues to triage and put together in a coherent state, so this may take a while to fix. 

Thanks

**Comment by Sumith1896** [comment]
Thanks @mcornella :)
