### ISSUE TITLE
git_prompt_short_sha outputs BEFORE and AFTER variables when outside of a git repo

### ISSUE THREAD

**Issue by sethlopezme** [robbyrussell/oh-my-zsh#4708]
After updating today, I noticed that my prompt was outputting the `ZSH_THEME_GIT_PROMPT_SHA_BEFORE` and `ZSH_THEME_GIT_PROMPT_SHA_AFTER` variables when I was outside of a git repo.

Here is my theme:

```shell
USER_PROMPT_SYMBOL="%{%(?.$fg[yellow].$fg[red][$?] )%}λ%{$reset_color%} "
CWD="%3(c:../%2.:%2.) "

GIT_BASE_COLOR=$fg[green]

ZSH_THEME_GIT_PROMPT_PREFIX="%{$GIT_BASE_COLOR%}\ue822 "
ZSH_THEME_GIT_PROMPT_SUFFIX=" "
ZSH_THEME_GIT_PROMPT_DIRTY="*"
ZSH_THEME_GIT_PROMPT_CLEAN=""

ZSH_THEME_GIT_PROMPT_SHA_BEFORE="("
ZSH_THEME_GIT_PROMPT_SHA_AFTER=")
%{$reset_color%}" # newline

PROMPT='$(git_prompt_info)$(git_prompt_short_sha)$CWD$USER_PROMPT_SYMBOL'
```

What it should look like:

```
# inside a repo
 master* (c7195a4)
../zsh/omzsh-themes λ

# outside a repo
../zsh/omzsh-themes λ
```

What it actually looks like after updating today:

```
# inside a repo
 master* (c7195a4)
../zsh/omzsh-themes λ

# outside a repo
()
../zsh/omzsh-themes λ
```

Environment info:
Max OS X 10.10.5
zsh 5.0.5 (x86_64-apple-darwin14.0)

**Comment by mcornella** [comment]
I can reproduce, this is a side effect of turning `$SHA` variables to local in 9f552130b. The fact that it is being declared local in the same line that `$(command git ...)` is run make the exit code be true regardless of the exit code of the `git` command. Let me work on a quick PR

**Comment by mcornella** [comment]
#4709 should fix this, can you try it?

**Comment by mcornella** [comment]
ping @sethlopezme

**Comment by sethlopezme** [comment]
@mcornella Your PR works for me
