### ISSUE TITLE
[update] wiki screenshot for "norm" theme

### ISSUE THREAD

**Issue by KLVTZ** [robbyrussell/oh-my-zsh#4725]
Problem
------------
Current screenshot for norm theme is out-of-date:
![norm](https://cloud.githubusercontent.com/assets/2618447/6316753/51e440c0-ba00-11e4-87ed-400fe2b0dd39.png)

This is due to an addition of host to theme in commit https://github.com/robbyrussell/oh-my-zsh/commit/6c45d217af77552a4f0b09542985520a577af3d5

Solution
-----------
I would like to replace the screenshot with something that reflects the current setup:
![norm-updated](http://i.imgur.com/85yEwcK.png)

How would I setup a new image on the wiki to reference github user content and not from another third-party image site?

**Comment by mcornella** [comment]
You just paste the screenshot into a Github markdown textbox (i.e. a comment): ![norm theme](https://cloud.githubusercontent.com/assets/1441704/11986491/65c9c702-a9d0-11e5-8393-ce262988ab09.png)
and copy the resulting URL (`cloud.githubusercontent.com/...`). Then you can replace the original with the new URL. 

I just did that, so don't worry about it. Next time you know what to do :wink: It's a mess, I know, but it's the best way we came up with, until GitHub allows pasting images directly in the wiki...

**Comment by KLVTZ** [comment]
@mcornella thanks for verifying! I had a small suspicion that what you described above was the process. Thanks!
