### ISSUE TITLE
_update_zsh_update:1: permission denied

### ISSUE THREAD

**Issue by Zorgatone** [robbyrussell/oh-my-zsh#4744]
Whenever I open up my terminal I get prompted to update, and then I get this error (Both Y/N answers) `_update_zsh_update:1: permission denied: /Users/webdev1/.zsh-update`

```
[Oh My Zsh] Would you like to check for updates? [Y/n]:
Updating Oh My Zsh
From https://github.com/robbyrussell/oh-my-zsh
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at:  http://shop.planetargon.com/
_update_zsh_update:1: permission denied: /Users/webdev1/.zsh-update
 tommaso@TR ~
```

**Comment by wuhongbing** [comment]
sudo？
吴

**Comment by Zorgatone** [comment]
[**@wuhongbing**](https://github.com/wuhongbing) commented on [4 gen 2016, 10:05 CET](https://github.com/robbyrussell/oh-my-zsh/issues/4744#issuecomment-168616378 "2016-01-04T09:05:22Z - Replied by Github Comment Enhancer"):
> <div class="email-fragment">sudo？
> 吴</div>
> <span class="email-hidden-toggle">[…](#)</span><div class="email-hidden-reply" style="display:none">
> <div class="email-quoted-reply"> 在 2016年1月4日，17:03，Tommaso Ricci &lt;notifications@github.com&gt; 写道：
> 
>  Whenever I open up my terminal I get prompted to update, and then I get this error (Both Y/N answers) _update_zsh_update:1: permission denied: /Users/webdev1/.zsh-update
> 
>  [Oh My Zsh] Would you like to check for updates? [Y/n]:
>  Updating Oh My Zsh
>  From [https://github.com/robbyrussell/oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)
>   * branch            master     -&gt; FETCH_HEAD
>  Current branch master is up to date.
>           __                                     __
>    ____  / /_     ____ ___  __  __   ____  _____/ /_
>   / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
>  / /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
>  \____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
>                          /____/
>  Hooray! Oh My Zsh has been updated and/or is at the current version.
>  To keep up on the latest news and updates, follow us on twitter: [https://twitter.com/ohmyzsh](https://twitter.com/ohmyzsh)
>  Get your Oh My Zsh swag at:  [http://shop.planetargon.com/](http://shop.planetargon.com/)
>  _update_zsh_update:1: permission denied: /Users/webdev1/.zsh-update
>   tommaso@TR ~
>  —
>  Reply to this email directly or view it on GitHub &lt;[#4744](https://github.com/robbyrussell/oh-my-zsh/issues/4744)&gt;.
> </div>
> <div class="email-fragment"></div>
> </div>

Sudo what? I didn't run any command :laughing:

**Comment by mcornella** [comment]
sudo rm ~/.zsh-update

—
Marc

**Comment by Zorgatone** [comment]
@mcornella When I got that error I tried a `ls -ahf` and no such file was listed at all

**Comment by Zorgatone** [comment]
[**@Zorgatone**](https://github.com/Zorgatone) commented on [4 gen 2016, 13:30 CET](https://github.com/robbyrussell/oh-my-zsh/issues/4744#issuecomment-168667066 "2016-01-04T12:30:19Z - Replied by Github Comment Enhancer"):
> @mcornella When I got that error I tried a `ls -ahf` and no such file was listed at all

Nevermind.. The file was there. I just was trying to execute it `sudo ~/.zsh-update` and I was getting "Invalid command .zsh-update". Fixed with `~/.zs-update` thanks @mcornella

**Comment by mcornella** [comment]
:+1:
