### ISSUE TITLE
VCS_info broken in zsh 5.2, workaround?

### ISSUE THREAD

**Issue by abjugard** [robbyrussell/oh-my-zsh#4745]
Any theme using _nvcsformats_ (VCS_info) to display different information depending on if current working directory is a repository or not, such as the [pure theme](https://github.com/robbyrussell/oh-my-zsh/blob/c249c69/themes/pure.zsh-theme#L38), is broken in zsh 5.2.

It has been [noted upstream](http://www.zsh.org/mla/workers/2015/msg03259.html) already, but for those of us stuck at 5.2 (Arch users for example), is there any easy workaround for the time being?

**Comment by InspectorMustache** [comment]
Well, this is an old post but this still isn't fixed and I've figured something out and I thought it might help someone. Now, I don't use oh-my-zsh myself but I don't see why this shouldn't work with that as well.

You can use the start-up hook to specify the prompt (or whatever you use vcs_info for) you want in VCS directories and then use the no-vcs hook to overwrite that setting if you're in a non-vcs environment. Like this:

```
zstyle ':vcs_info:*+start-up:*' hooks vcs_prompt
zstyle ':vcs_info:*+no-vcs:*' hooks no_vcs_prompt
function +vi-vcs_prompt() {
    PROMPT='the-prompt-you-want-in-vcs-directories'
}
function +vi-no_vcs_prompt() {
    PROMPT='the-prompt-you-want-in-non-vcs-directories'
}
```

Of course, you can also put something completely different in those functions.

**Comment by dgallegos** [comment]
I fixed "refined" or "pure" using the following hack. If anyone has something more elegant, please provide it.

**refined.zsh-theme**
```
repo_information() {
    inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
    if [ "$inside_git_repo" ]; then
        echo "%F{blue}${vcs_info_msg_0_%%/.} %F{8}$vcs_info_msg_1_`git_dirty` $vcs_info_msg_2_%f"
    else
        echo "%F{blue}%~%f"
    fi
    # echo "%F{blue}%~%F{blue}${vcs_info_msg_0_%%/.} %F{8}$vcs_info_msg_1_`git_dirty` $vcs_info_msg_2_%f"
}
```
