### ISSUE TITLE
theme agnoster show "?"

### ISSUE THREAD

**Issue by lubeast** [robbyrussell/oh-my-zsh#4756]
![](http://7xphy5.com1.z0.glb.clouddn.com/48F1073C-2886-43AB-BDDD-DB80FB0D3F0C.png)

I know maybe a lot of people have asked this question before, and i searched a lot on the internet.
I've already install powerline-font but it still show this.

what should i do?

**Comment by apjanke** [comment]
You may have an outdated Powerline font. Download fresh ones from [the main Powerline fonts repo](https://github.com/powerline/fonts), and make sure your Oh My Zsh installation is also up to date.

If you are using iTerm2 or another terminal emulator that has separate selections for "non-ASCII" fonts, make sure the "Non-ASCII Font" in your terminal profile is also set to a Powerline font.

See #1906, #4091, #4083, #3713, #2869.

Somebody needs to write a FAQ on this. :)

**Comment by lubeast** [comment]
@apjanke Thank you for your answer :D  

I redownload `Powerline fonts repo` and reinstall `oh-my-zsh`.But it still doesn't work for me. So I change font from menlo to `Meslo LG M Regular for Powerline` and that work for me.

Once again, thank you for your professional answer. It's really need someone to write a FAQ about this.

**Comment by apjanke** [comment]
You're welcome!

>  So I change font from menlo to Meslo LG M Regular for Powerline and that work for me.

Yes, that is what you should do. "Menlo" is a classic font. "Meslo" is a derivative of "Menlo". And "Meslo XXX for Powerline" is a non-standard Powerline-patched derivative of "Meslo", which is what you need to make Agnostor and other Powerline-dependent themes work. 

Sorry for any confusion! (And this is not your fault; you just ran in to a compabibility/licensing/release-management/font-fallback/private-use-area mess.)

**Comment by audiebantzhan** [comment]
change font from menlo to Meslo LG M Regular for Powerline  ,it work for me.

**Comment by tolerious** [comment]
yes, we should change the terminal fonts.
