### ISSUE TITLE
installation problems with colors, compinit and git plugin

### ISSUE THREAD

**Issue by isidroc** [robbyrussell/oh-my-zsh#4757]
Hi All,
I have installed the latest version of oh-my-zsh. 
I am having the following errors:

/home/ic71/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/ic71/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:74: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:83: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:89: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:98: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:107: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:109: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:118: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:120: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:128: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:134: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:136: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:141: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:146: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/home/ic71/.oh-my-zsh/plugins/git/git.plugin.zsh:170: command not found: compdef
/home/ic71/.zshrc:107: compinit: function definition file not found

Any ideas on how to solve this?

echo $ZSH   gives  ~/.oh-my-zsh
zsh --version
zsh 4.3.10 (x86_64-redhat-linux-gnu)

**Comment by autumnlansing** [comment]
I had these exact same errors when I first set up zsh and oh-my-zsh, but only when I ran zsh through Guake. It worked fine in Gnome Terminal. The problem was solved in Guake by setting the default shell to /bin/zsh and checking "Run command as a login shell." In what terminal do you get your errors?

You might also check your $fpath to make sure the oh-my-zsh folders are included.

**Comment by OMGloom** [comment]
I got same issue on OS X, tried everything I could find, still nothing.

**Comment by beatorizu** [comment]
I got this error when update this week on CentOS 7

**Comment by beatorizu** [comment]
I believe I got a workaround for this problem. 
The first thing to do is verify your FPATH variable content: `echo $FPATH`. In a normal situation return something like that: `/home/charmander/.oh-my-zsh/plugins/git:/home/charmander/.oh-my-zsh/functions:/home/charmander/.oh-my-zsh/completions:/home/charmander/.oh-my-zsh/plugins/python:/home/charmander/.oh-my-zsh/plugins/pip:/home/charmander/.oh-my-zsh/plugins/git:/home/charmander/.oh-my-zsh/functions:/home/charmander/.oh-my-zsh/completions:/usr/share/zsh/site-functions:/usr/share/zsh/5.0.2/functions`.

In my case it returned: `/opt/intel/composer_xe_2011_sp1.7.256/mkl/include`. When I try to remove .oh-my-zsh and run only zsh returned this: `/usr/share/zsh/5.0.2/scripts/newuser:6: zsh-newuser-install: function definition file not found`. Search in web I found this bug report: [zsh: Many function definitions are missing zsh-newuser-install, compinit, etc](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=666168#47) that say it could have a variable overwrite made by intel compiler :/

So a workaround to this problem could be insert the following lines to your .bash_profile, if you can not run this command `chsh -s $(which zsh)`.
```bash
FPATH=/home/modelagem/beatriz.fonseca/.oh-my-zsh/plugins/python:/home/modelagem/beatriz.fonseca/.oh-my-zsh/plugins/pip:/home/modelagem/beatriz.fonseca/.oh-my-zsh/plugins/git:/home/modelagem/beatriz.fonseca/.oh-my-zsh/functions:/home/modelagem/beatriz.fonseca/.oh-my-zsh/completions:/usr/share/zsh/site-functions:/usr/share/zsh/5.0.2/functions

export FPATH
```

I hope it help

**Comment by anyint** [comment]
I got the similar  error these days. 
And I have fixed it by removing composer_xe_** .sh from /etc/profile.d
'''shell
sudo rm /etc/profile.d/compiler_intel-composer_xe*
```

**Comment by pawelniewie** [comment]
Got the same problem as @anyint today on Fedora 28, don't have compiler_intel-composer_xe* though.

Initial fpath includes /usr/share/Modules/init/zsh-functions only which is provided by environment-modules package. But this directory lacks zsh functions which are still in /usr/share/Modules/init/zsh-functions.

A quick workaround was to update my .zshrc with:

`fpath=(/usr/share/zsh/5.5.1/functions/ $fpath)`

**Comment by julianoes** [comment]
I had the same problem on Fedora 29 and fixed it by adding the line mentioned above at the beginning of `.zshrc`. I just added a check for the correct zsh version.
```
fpath=(/usr/share/zsh/`zsh --version | awk '{print $2}'`/functions/ $fpath)
```

**Comment by gavin971** [comment]
> I had the same problem on Fedora 29 and fixed it by adding the line mentioned above at the beginning of `.zshrc`. I just added a check for the correct zsh version.
> 
> ```
> fpath=(/usr/share/zsh/$ZSH_VERSION/functions/ $fpath)
> ```

nice job!

**Comment by travisneids** [comment]
I found myself in this situation. I used Homebrew to install zsh. Adding the following to my `.zshrc`:

`fpath=(/usr/local/Cellar/zsh/5.8/share/zsh/functions/ $fpath)`

and ensuring `/usr/local/bin/zsh` was added to the end of my `/etc/shells` file fixed it all.
