### ISSUE TITLE
gradle + gradlew autocompletion not working

### ISSUE THREAD

**Issue by kaushikgopal** [robbyrussell/oh-my-zsh#4758]
I'm almost positive this isn't something specific to my environment but the gradle + gradlew autocompletion never seems to works. Here's what i'm trying:

in my `.zshrc`:

```
 plugins=(brew git git-extras ruby rails gradle)
```

in my aliases.zsh:

```
alias gradlew="./gradlew"
alias gw="./gradlew"
alias gr="gradle"
```

on my console, as i type `gradlew <hit tab here>` nothing shows up. i've tried almost every combination with/without aliases etc.

I don't have this problem with git/brew/ruby or the other plugins shown above.

**Comment by evilnoxx** [comment]
I have this problem too. Extracted to ~/bin/gradle-2.12, set GRADLE_HOME and added the bin dir to my path.
The gradle command seems to work just fine, but no autocomplete...

**Comment by bes** [comment]
I have a similar issue, but instead of "nothing" I get this message (which prints out on the command line which is extra annoying)

`gradlew _gradle:80: command not found: gradlew`

Where the first gradlew is what I wrote and the rest is what is spewn out on my command line

**Comment by bes** [comment]
I managed to partially solve it, for me at least.

In the directory `~/.oh-my-zsh/plugins/gradle` do the following:
```
ln -s gradle.plugin.zsh _gradle
ln -s gradle.plugin.zsh _gradlew
```

Now I can do 
```
./gradlew <TAB>
==== Gradlew Tasks ====
buildEnvironment   dependencies       help               model              properties         wrapper
components         dependencyInsight  init               projects           tasks
```

I would still like my *actual* tasks to show up, but it's a start...

**Comment by bes** [comment]
I fixed so that I could list all tasks, and I created a pull request:

https://github.com/robbyrussell/oh-my-zsh/pull/5230

**Comment by ryanstull** [comment]
I'm having a similar issue except I don't have gradlew, and I'm using sdkman to manage my gradle install.

$GRADLE_HOME = /home/ryan/.sdkman/candidates/gradle/current

Whenever I hit tab after typing gradle, I don't see any suggestions.

**Comment by mcornella** [comment]
@ryanstull I assume you have the `gradle` plugin enabled. Run `functions -t _gradle_tasks` to debug the gradle completion function, trigger the gradle completion with `gradle [TAB]` then post the output that it spits.

**Comment by MercurieVV** [comment]
Using gradle on windows over babun (cygwin). Plugin not working even with #5230
If I execute `functions -t _gradle_tasks`
1) `gradlew <tab>` or `./gradlew <tab>` shows nothing
2) `gradle <tab>` show tons of logs, cant see actual gradle tasks there

**Comment by mcornella** [comment]
For ` gradlew` you have to do `functions -t _gradlew_tasks`. Can you do that and post the output of both?

**Comment by cliffred** [comment]
I have the same issue on my mac. Gradle is installed via homebrew. See attached logs.

[gradle.log.txt](https://github.com/robbyrussell/oh-my-zsh/files/531126/gradle.log.txt)
[gradlew.log.txt](https://github.com/robbyrussell/oh-my-zsh/files/531127/gradlew.log.txt)

**Comment by mcornella** [comment]
I didn't see anything wrong in those logs. Perhaps the cache file didn't contain anything?

Anyhow, reply if this still happens with the latest version. Make sure to delete the gradle cache file (`.gradletasknamecache`) to force reset the completion.

**Comment by trejkaz** [comment]
I have the same issue today and nothing above helped me. What do I do?
