### ISSUE TITLE
Add '^r' binding key to vi-mode plugin

### ISSUE THREAD

**Issue by khapota** [robbyrussell/oh-my-zsh#4760]
It is popular key binding and i think it should be added by default.

```
bindkey '^r' history-incremental-search-backward
```

**Comment by okapia** [comment]
Popular it may be but it is essentially and emacs binding. The vi mode equivalent is to use / from command mode.

**Comment by softmoth** [comment]
This is supported in the [vim-mode](https://github.com/softmoth/zsh-vim-mode) plugin add-on.

**Comment by mcornella** [comment]
Added in #4994
