### ISSUE TITLE
_history_fn:fc:14: event not found:

### ISSUE THREAD

**Issue by noscripter** [robbyrussell/oh-my-zsh#4761]
I know this is an old issue here, but since no specific solution is provided and the problem still exists, I'm wondering what could be done to fix this issue.

In zsh, the history commands is read from $HIST_FILE, so I can just edit $HIST_FILE to delete specific history commands, but that' not compliant with the default history command, and why fc is provided here to replace history?

**Comment by apjanke** [comment]
The default `history` is just the same as `fc -l`. OMZ aliases it to display a longer output by default. And it's `$HISTFILE`, not `$HIST_FILE`.

What are you trying to do, and what's not working?

There's no `_history_fn` in the main OMZ code base (yet). Are you running off of [mcornella's fork](https://github.com/mcornella/oh-my-zsh/commit/013d258dba88d2688945e74f23ae8194526f380d) or testing PR #3422?

**Comment by mcornella** [comment]
That looks like it. Please direct this issue over to #3422 and provide more information to reproduce your particular problem.

> why fc is provided here to replace history?

That's because zsh doesn't have a builtin `history` command, it's an alias of `fc -l`.

**Comment by apjanke** [comment]
> That's because zsh doesn't have a builtin history command, it's an alias of fc -l.

Well, strictly speaking it's a builtin that aliases `fc -l`, not a shell alias per se. ;)

```
$ which history
history: shell built-in command
```

**Comment by mcornella** [comment]
Nitpicking :grin: Updated!
