### ISSUE TITLE
Will your zsh cost a lot of cpu?

### ISSUE THREAD

**Issue by lubeast** [robbyrussell/oh-my-zsh#4766]
![](http://7xphy5.com1.z0.glb.clouddn.com/cpucost.png)

zsh cost 83.6% of the CPU when i typing in the Terminal just like the picture. What about yours? And does anyone know why?

**Comment by lubeast** [comment]
no-one answer this question.

**Comment by mcornella** [comment]
Sorry for the late reply, we're very few people managing the project. Yours is the first issue I encounter of having this problem, if you google `zsh high cpu usage` you'll find a few resources to check out. [This is one of the most similar I've found](https://github.com/sorin-ionescu/prezto/issues/879#issuecomment-103113750).

Another thing you can try is looking at the exact execution tree of zsh, by running `ps fax` which will output a tree of the running processes:
```
24473 tty2     Sl+    0:00 /usr/lib/gnome-terminal/gnome-terminal-server
24493 pts/0    Ss     0:00  \_ zsh
24929 pts/0    R+     0:00      \_ ps fax
```

**Comment by lubeast** [comment]
Thx for your reply.It will appear `zsh high cpu usage` only when i use `adb push`, but i can't figure out why.
