### ISSUE TITLE
Special characters showing as question marks in Linux

### ISSUE THREAD

**Issue by awan1** [robbyrussell/oh-my-zsh#4776]
- Not like #4065: not getting a "character not in range" error. Updated powerline font from repo and ran `install.sh`, and set terminal font to the powerlinef font. Also tried locale fix. 
- `echo $TERM` yields `xterm`.

Any ideas? Sorry if this is a simple fix. 

![screen shot 2016-01-14 at 2 39 24 pm](https://cloud.githubusercontent.com/assets/6291092/12340038/4fbcebf2-bacd-11e5-9835-3b9b66d2650a.png)

**Comment by mcornella** [comment]
I've never seen a prompt like that, can you post the `$PROMPT` variable? Also, could you try with a different powerline font?

**Comment by awan1** [comment]
... This automagically fixed itself, probably after a computer restart. No idea what happened. 

In case you're interested, the $PROMPT variable is 

    $(prompt_line_sep)%{%f%b%k%}$(build_prompt)$(prompt_line_sep)%{${fg_bold[default]}%}$(prompt_char) %{$reset_color%}

It's an adaptation of the bullet-train theme.

Thanks for responding!
