### ISSUE TITLE
Address space occupied and fork failing on Cygwin

### ISSUE THREAD

**Issue by ordonezalex** [robbyrussell/oh-my-zsh#4778]
I am using oh-my-zsh in Cygwin and just today it began to act unexpectedly.
I have ran `upgrade_oh_my_zsh`, and that did not fix the problem.

Messages almost all seem to either involve an address space being occupied or a fork failing.

Is there anything else I can post to help resolve this issue?

When opening Cygwin:

```
$fg_bold[green]${PWD/#$HOME/~}$reset_color$(git_prompt_info) ⌚ $fg_bold[red]15:18:48$reset_color
$ vim .zshrc
      0 [main] zsh 8416 child_info_fork::abort: address space needed by 'terminfo.dll' (0x3A0000) is already occupied
zsh: fork failed: resource temporarily unavailable
```

Instead of my expected prompt:

Expected

```
~ ⌚ 15:27:01
$
```

Actual

```
$fg_bold[green]${PWD/#$HOME/~}$reset_color$(git_prompt_info) ⌚ $fg_bold[red]15:23:33$reset_color
$ [cursor here]
```

Sometimes running simple commands such as `ls` will output this and not expected output at all:

```
      0 [main] zsh 2880 child_info_fork::abort: address space needed by 'terminfo.dll' (0x3B0000) is already occupied
git_prompt_info:3: fork failed: resource temporarily unavailable
```

**Comment by mcornella** [comment]
Are you using [babun](https://github.com/babun/babun)? This looks like a cygwin issue, ask over there...

**Comment by ordonezalex** [comment]
@mcornella I am not using babun as far as I know.

I only use [Cygwin](https://cygwin.com/) and I did not update Cygwin before this behavior, only ohmyzsh.

**Comment by apjanke** [comment]
This doesn't sound like an Oh My Zsh specific issue. Your `zsh` is messed up. Sounds like something is injecting code in to your `zsh` process and it's not working out. [Googling for this](https://www.google.com/search?q=terminfo.dll&ie=utf-8&oe=utf-8#q=address+space+terminfo.dll) comes up with people talking about various antivirus programs causing this on Cygwin, which sounds plausible.

Have a look at your antivirus software & settings, and check whether your computer has been owned by malware.

**Comment by ordonezalex** [comment]
@apjanke, it looks like my issue stemmed from Windows Defender. However, after not doing anything else, everything seems to be working as expected.

I guess that's Windows.
