### ISSUE TITLE
alias conflict with fasd

### ISSUE THREAD

**Issue by ikhthiandor** [robbyrussell/oh-my-zsh#4780]
alias d='dirs -v | head -10' 
which is defined in $ZSH_HOME/lib/directories.zsh
conflicts with alias d='fasd -d'

I never use the one defined in OMZ but always use the fasd one. So, I had to trace through a bit to figure out what was overwriting that. Just a heads up to anyone else facing this issue.

Finally, I think it would be nice if the OMZ alias was changed to something else.

**Comment by mcornella** [comment]
The `fasd` alias should be the preferred one since plugins are loaded after lib files, which makes them override any alias previously set up. 

I'm not familiar with `fasd` so I'm not sure at what point the `alias d='fasd -d'` is set up, but perhaps you can clarify that. If that's an alias you set up, you should put that after the `source $ZSH...` line in the zshrc file.

**Comment by apjanke** [comment]
The `fasd` plugin [calls `fasd --init`](https://github.com/robbyrussell/oh-my-zsh/blob/5464fe3e4ad02a33243f42bcd8c91a287bc26185/plugins/fasd/fasd.plugin.zsh#L4), which [defines the `d` alias](https://github.com/clvv/fasd/blob/90b531a5daaa545c74c7d98974b54cbdb92659fc/fasd#L86). So yeah, it should take precedence over the one in `lib`.

There's also a `d` alias [in the `singlechar` plugin](https://github.com/robbyrussell/oh-my-zsh/blob/5464fe3e4ad02a33243f42bcd8c91a287bc26185/plugins/singlechar/singlechar.plugin.zsh#L47) (found with `grep -r 'alias d='`).

**Comment by mcornella** [comment]
Ok, then that should work regardless. @ikhthiandor please post your zshrc file so we can take a closer look at your setup.

**Comment by ikhthiandor** [comment]
Sorry, I got busy with other things. I've figured it out. The issue was caused by moving `eval "$(fasd --init auto)"` from .zshrc to .zshenv. Apparently, I still have to learn the purpose of different zsh config files. Moving fasd initilization snippet to .zshrc fixed things again. I think this issue can be closed now.

**Comment by mcornella** [comment]
Oh, ok that makes sense. Notice that you can also add the fasd plugin, which does the same thing within OMZ. Have a nice one!
