### ISSUE TITLE
Parse error after upgrade

### ISSUE THREAD

**Issue by uptownhr** [robbyrussell/oh-my-zsh#4783]
```
/Users/uptown/.oh-my-zsh/lib/git.zsh:42: parse error near `elif'
zsh: command not found: git_prompt_info  
```

**Comment by otoniel-isidoro** [comment]
same error here

**Comment by otoniel-isidoro** [comment]
I fixed that by changing the config "git config --global core.autocrlf false" and restarted zsh.

**Comment by uptownhr** [comment]
yup, that worked. thank you!

Wouldn't adding in a .gitattributes file fix this issue for people that have autocrlf enabled?

**Comment by mcornella** [comment]
There's #4071 but it's not ready yet, needs thorough testing.
