### ISSUE TITLE
Home and End not working in PhpStorm terminal in Mac OS/X

### ISSUE THREAD

**Issue by hkirsman** [robbyrussell/oh-my-zsh#4784]
If i go to bash, it works. In Oh My Zsh I only get system sound when pressing the home and/or end keys.

**Comment by apjanke** [comment]
Sounds like a key binding issue, maybe related to the `[sr]mkx` stuff; see #3061, #4540, #2735, #2511.

Check the value of `$TERM` inside your PhpStorm session, and make sure it matches what the PhpStorm Terminal is emulating, including the `smkx/rmkx` numeric keypad application/local behavior. (You can probably use Ctrl-V to get a literal echo of the character sequences your terminal is sending for Home and End.)

If this isn't just a `$TERM` mismatch, this might be a reason to consider ditching `[sr]mkx` in the OMZ code.

**Comment by apjanke** [comment]
Ping. Any update on this? What's your `$TERM` value, and what are Home and End emitting inside the PhpStorm terminal?

**Comment by hkirsman** [comment]
Thank you for getting back to this issue!
I was a bit overwhelmed by the information. Like "If this isn't just a $TERM mismatch, this might be a reason to consider ditching [sr]mkx in the OMZ code." Although I'm not computer noobie it's hard to understand what you mean by this. .)

So one way to print the $TERM is through printenv in Mac?
In that output it shows:
TERM=xterm-256color
It's the same both in [PhpStorm](https://www.jetbrains.com/phpstorm/) and normal shell.

**Comment by apjanke** [comment]
Sorry: the `smkx`/`rmkx` stuff is kind of advanced low level terminal stuff that you shouldn't have to worry so much about. In particular, the "consider ditching [sr]mkx in the OMZ code" part was just for the OMZ developers' benefit. It has to do with [how OMZ controls the terminal keypad behavior](https://github.com/robbyrussell/oh-my-zsh/blob/5464fe3e4ad02a33243f42bcd8c91a287bc26185/lib/key-bindings.zsh#L7-L16) through control sequences when it displays the prompt.

Let's have a look at your `bindkey` setup and all that. Could you run `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/)? That will include a bunch of info about your shell setup that will help us figure out what's going wrong.

I'll download a copy of PhpStorm and have a look at its terminal behavior. How do you start a shell session in it?

**Comment by apjanke** [comment]
Looks like PhpStorm's terminal is not changing the character sequences issued by Home and End in response to `smkx`. [Here's](https://docs.google.com/spreadsheets/d/1Ue5gb2hLjz058QEtEXwaw8YR7QoVZpSYzbXQKrRcGKk/edit?usp=sharing) what I observed.

As a workaround, you could hardcode bindings for `^[[H` and `^[[F` (xterm's local-keypad-mode sequences for Home and End) in your `~/.zshrc`, after loading OMZ. Will probably get Home/End working for you, and is unlikely to break anything.

```
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
```

**Comment by hkirsman** [comment]
Wow, it's working!!! You can't imagine how frustrating it was to 'emulate' home and end with arrow keys. Pretty time consuming. Thank you very much, Apjanke!

**Comment by mcornella** [comment]
> [Here's](https://docs.google.com/spreadsheets/d/1Ue5gb2hLjz058QEtEXwaw8YR7QoVZpSYzbXQKrRcGKk/edit?usp=sharing) what I observed.

That's an impressive file you got there. That should make key binding issues easier to fix, hopefully. This particular one should be fixed by PhpStorm, from what I understand. In the meantime, we have this issue for future reference. 

@hkirsman I'm closing this issue.

**Comment by apjanke** [comment]
@hkirsman You're welcome! Hope we can make this easier for you and other users in the future.

@mcornella Thank you! Yeah, I think this seems like it might be an issue with PhpStorm's terminal. I don't have time for another week or so, but I wouldn't mind filing a bug report with them and seeing what they say. This is a terminal-emulation edge case I'm still learning about, and would be interested in their response. Or of you or @hkirsman or someone else has time, please CC me in on it.

Something to think about for the longer term—this is one more case that makes me think OMZ might be better off ditching the `smkx`/`rmkx` stuff entirely, and just using hardcoded local-mode sequences for the cursor keypad keys, since most current popular emulators and corresponding terminfo definitions seem to match xterm or urxvt in local mode, but have a bit more variance in application mode. And they vary in whether & how they respond to the local/application mode sequences. Lately I'm leaning toward "`smkx` is a failed experiment and shells should avoid it".

**Comment by hkirsman** [comment]
There's an issue in PhpStorm issue queue and I've added a followup - https://youtrack.jetbrains.com/issue/IDEA-118848 Hope I've communicated it properly.

**Comment by apjanke** [comment]
Thanks @hkirsman! I commented there too; let's see how the discussion there goes and follow up here if necessary.

**Comment by hkirsman** [comment]
Nice! Very thorough (y)

**Comment by maalicki** [comment]
@apjanke Thanks!
Xubuntu 14.04 here

**Comment by rubiconTwist** [comment]
@apjanke Thank you!!

**Comment by hkirsman** [comment]
Seems they fixed it today! Celebration! Not sure in what version it will be available.
