### ISSUE TITLE
Agnoster theme doesn't work

### ISSUE THREAD

**Issue by FlareHAX0R** [robbyrussell/oh-my-zsh#4786]
When I launch zsh, I get
```
(anon):12: character not in range
```

I've installed powerline fonts, help plz!

I'm using konsole for kde plasma 5 to launch zsh, but I get the same error with Terminator, too. My OS is arch linux if that helps any

**Comment by mcornella** [comment]
This could be a locale issue. Please post the output of both `locale` and `locale -a`.

**Comment by FlareHAX0R** [comment]
locale:
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

locale -a:
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
```

**Comment by mcornella** [comment]
You need to install a locale that supports `UTF-8`. Notice you only have `C` and `POSIX` available which are, I suppose, the default locales shipped with archlinux. See [generating locales](https://wiki.archlinux.org/index.php/locale#Generating_locales).

**Comment by FlareHAX0R** [comment]
Oh. Sorry! I uncommented the UTF-8 en_US locale, but didn't know I had to locale-gen again! Sorry!

**Comment by mcornella** [comment]
Glad to help :+1:

**Comment by FlareHAX0R** [comment]
but how do I change that color from that hard-to-see dark blue?

**Comment by mcornella** [comment]
It cannot be done currently, but if you search for `light agnoster` in this repository's pull requests you'll find some that can work for you.

**Comment by ocboogie** [comment]
I have this problem too, and it turns out it is a problem with WSL. So for anyone using WSL I recommend you look at https://github.com/Microsoft/WSL/issues/1878. If you're not using WSL I can't help you.

**Comment by ixez** [comment]
I encounter this problem with my Docker.
It needs to set `locale` in advance. I run the following code to solve the problem.
```sh
apt-get install -y locales
locale-gen en_US.UTF-8
```

**Comment by pmonty** [comment]
Running arch linux and I get this problem in Konsole.

Not sure what to do. 

output of `locale` and `locale -a`
```
pmonty@archPC:~% locale
LANG=C
LC_CTYPE=C
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
pmonty@archPC:~% locale -a
C
POSIX
en_AU.utf8
```

**Comment by nijkah** [comment]
I faced the same issue.
I am using nvidia-docker for cuda setting.
Locale setting in my container seems no problem

`LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8`

`C
C.UTF-8
en_US.utf8
POSIX`

but it still displays
(anon):12: character not in range

How can I solve it?

**Comment by mcornella** [comment]
Try with `export LANG=en_US.utf8`

**Comment by nijkah** [comment]
After I `export LANG=C.UTF-8`, and i switched again as `export LANG=en_US.UTF-8`. 
Now, it works fine.
I cannot find what the exact problem was.

**Comment by puzzle9** [comment]
> After I `export LANG=C.UTF-8`, and i switched again as `export LANG=en_US.UTF-8`.
> Now, it works fine.
> I cannot find what the exact problem was.

maybe reboot

**Comment by jadia** [comment]
The following works for me everytime:

```bash
sudo apt-get install -y language-pack-en
sudo update-locale
```

Source: https://gist.github.com/jadia/1f4c2190730ef646d41823b6a6c30926

**Comment by JavonneM** [comment]
Seems like it requires `en_US-UTF-8` as a locale.
Locale configuration when it breaks
```
% locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_ZA-UTF-8
LC_CTYPE="en_ZA-UTF-8"
LC_NUMERIC="en_ZA-UTF-8"
LC_TIME="en_ZA-UTF-8"
LC_COLLATE="en_ZA-UTF-8"
LC_MONETARY="en_ZA-UTF-8"
LC_MESSAGES="en_ZA-UTF-8"
LC_PAPER="en_ZA-UTF-8"
LC_NAME="en_ZA-UTF-8"
LC_ADDRESS="en_ZA-UTF-8"
LC_TELEPHONE="en_ZA-UTF-8"
LC_MEASUREMENT="en_ZA-UTF-8"
LC_IDENTIFICATION="en_ZA-UTF-8"
LC_ALL=
```

```
% locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
en_ZA.utf8
```
Locale configuration with agnoster working
```
% locale                  
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_ZA-UTF-8
LC_CTYPE="en_ZA-UTF-8"
LC_NUMERIC="en_ZA-UTF-8"
LC_TIME="en_ZA-UTF-8"
LC_COLLATE="en_ZA-UTF-8"
LC_MONETARY="en_ZA-UTF-8"
LC_MESSAGES="en_ZA-UTF-8"
LC_PAPER="en_ZA-UTF-8"
LC_NAME="en_ZA-UTF-8"
LC_ADDRESS="en_ZA-UTF-8"
LC_TELEPHONE="en_ZA-UTF-8"
LC_MEASUREMENT="en_ZA-UTF-8"
LC_IDENTIFICATION="en_ZA-UTF-8"
LC_ALL=
```

```
locale -a               
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
en_US.utf8
en_ZA.utf8
```

**Comment by mcornella** [comment]
The value separator is a dot, not a dash: `en_ZA.UTF-8`.

**Comment by JavonneM** [comment]
oh my didn't notice that thank you. After changing to locale.conf `LANG=en_ZA.UTF-8` had to manually set it in KDE as well, I think it has its own configuration.

**Comment by SupinePandora43** [comment]
had to add `LC_ALL=C.UTF-8` to `/etc/locale.conf`

**Comment by KyLeggiero** [comment]
I'm getting this issue right now, but I've tried everything in this thread.

```zsh
% locale   
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.utf8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```
```zsh
% locale -a             
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.utf8
POSIX
```


`/etc/locale.conf`:
```
LC_ALL=C.UTF-8
```
`/etc/locale.gen`:
```
en_US.UTF-8 UTF-8
```


Couldn't even use @mcornella's advice of [generating locales](https://wiki.archlinux.org/index.php/locale#Generating_locales) because I'm using Debian and get this:
```zsh
% sudo apt-get install language-pack-en
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package language-pack-en
```


And I rebooted plenty of times throughout & after this process.


Currently running:
```zsh
% uname all
Linux rpi3-20231109 6.1.0-13-arm64 #1 SMP Debian 6.1.55-1 (2023-09-29) aarch64 GNU/Linux
```
