### ISSUE TITLE
chsh returns user does not exist

### ISSUE THREAD

**Issue by aacalfa** [robbyrussell/oh-my-zsh#4789]
Hello,

I have been using oh-my-zsh on my own computer for a while without problems. I was wanting to install it for my account at my university's system, but I cannot change the shell to zsh. This is what I get:

    chsh -s /bin/zsh
    Changing shell for xxx.
    Password:
    chsh: user "xxx" does not exist.

Any ideas?

**Comment by mcornella** [comment]
It's probable that your university restricts the ability to change the shell. 

You should contact your own uni tech support for instructions, or construct a dedicated shell rc file that runs zsh directly, depending on the `$SHELL` you have by default. Here's a sample file [I had to use in my university](https://github.com/mcornella/dotfiles/blob/86a5c87fd10cf6f1752e2cc197e80ae6075eb5f3/tcshrc).

**Comment by mcornella** [comment]
Also, that error you see is because your university uses LDAP, so normal `chsh` cannot be used.

**Comment by aacalfa** [comment]
Thanks a lot! Your shell rc file worked for me :)

**Comment by mcornella** [comment]
Cool, you're welcome :wink:

**Comment by derrickzhuyz** [comment]
Think you for your very useful advice! To record details on how I solve the problem based on advice above:
1. use `echo $SHELL` to check default shell, for example it is `csh` or `tcsh` in your sever;
2. Create or edit the file of `.cshrc` or `.tcshrc` use the script [link](https://github.com/mcornella/dotfiles/blob/86a5c87fd10cf6f1752e2cc197e80ae6075eb5f3/tcshrc):
```
if($?prompt) then
  exec /usr/bin/zsh -l
  export SHELL=/usr/bin/zsh
endif
```
3. Before adding code, make sure the path to your `zsh` is correct. You can find the path to zsh by `which zsh` . If the output path is not `/usr/bin/zsh`, then you need to use the actual path in script.
4. activate: `source ~/.bashrc`
