### ISSUE TITLE
Need an undo of tab completion

### ISSUE THREAD

**Issue by codysherman** [robbyrussell/oh-my-zsh#4791]
If in a terminal I do a tab completion of 'cd ~/Projects/very-long-project-name-but-not-the-right-project', hitting the Tab button to autofill that very long folder name is frankly super awesome, but sometimes I accidentally go into the wrong project out of habit or whatever. It would be super-er awesome to be able to do something similar to a Shift+Tab command to do the opposite of a tab completion, which would undo the last folder added and revert that line in the terminal to just 'cd ~/Projects/'.

That would save me a lot of backspacing! :D

**Comment by aacalfa** [comment]
Does ctrl+w help?

**Comment by codysherman** [comment]
Thanks for the suggestion! ctrl+w does obviously help over just holding the delete key, however I'm still suggesting an essentially "undo" command for tab completion rather than still having to delete by word. It would just jump back to the previous forward slash.

**Comment by mcornella** [comment]
You can use the `undo` zle widget, which is by default bound to `CTRL`+`_`. See [this answer on stackoverflow](http://stackoverflow.com/a/12267181/5798232).

**Comment by codysherman** [comment]
Awesome thanks! Please at least consider for future versions having the command be something more similar to the inverse of Tab, such as Shift+Tab, as is the standard for most programs. Glad to have a working solution now though!
