### ISSUE TITLE
pj plugin tab completion error

### ISSUE THREAD

**Issue by jxpx777** [robbyrussell/oh-my-zsh#4793]
Whenever I try to use tab completion with the `pj` plugin, I get this error printed three times to my console:

```
(eval):1: unmatched '
```

I tried a clean install of oh-my-zsh with the default zshrc and simply adding in the pj plugin and still get this error.

I did recently move to a new machine, so I'm absolutely open to the idea that maybe something is hinky in my configuration, so if that's the case, I'd love a pointer for how to identify where this unmatched ' is coming from.

**Comment by apjanke** [comment]
I turned on the `pj` plugin and can't reproduce. (OS X 10.9.) Might be something specific to your configuration.

Check the definition of `$PROJECT_PATHS` in your `~/.zshrc` or wherever it's defined. Looks like [that's pulled in and evaluated at completion time](https://github.com/robbyrussell/oh-my-zsh/blob/5464fe3e4ad02a33243f42bcd8c91a287bc26185/plugins/pj/pj.plugin.zsh#L8-L9) by `pj`, so it could be where that syntax issue is coming from.

If that's not it, you can debug it by doing `set +x` and then trying tab completion again. That's a shell option which will dump an execution trace to your console, so you can see what it's running and what broke.

If that doesn't give you enough info to spot the issue, you can run `omz_diagnost_dump` and post the output as a gist. That will give us a bunch of debugging info about your zsh and OMZ setup, which could help find the problem.

**Comment by jxpx777** [comment]
Looks like something happened in migrating my dot files to a new user account. I got things working after a fresh clone and resetting all my symlinks and such. Thanks for the tips on diagnosing though. Those will come in handy in the future.
