### ISSUE TITLE
red dots appear in vi mode

### ISSUE THREAD

**Issue by Leandros** [robbyrussell/oh-my-zsh#4808]
If I turn on Vi mode through `bindkey -v`, and I use the tab completion, red dot's appear (indicating loading, I guess).
How can I get rid of these? Or is this zsh related, and not oh-my-zsh related?

I found `COMPLETION_WAITING_DOTS`, but even setting that to `false` doesn't seem to work.

**Comment by Leandros** [comment]
Setting `bindkey "^I" expand-or-complete` overwrites the current binding, and let the dots disappear.
Thanks to #2482

**Comment by mcornella** [comment]
You might have `COMPLETION_WAITING_DOTS=true` uncommented in your zshrc. Commenting or deleting that line will give you back the normal behavior, no need for the additional `bindkey` line.
