### ISSUE TITLE
Code completion does not work paths starting with /

### ISSUE THREAD

**Issue by tdi** [robbyrussell/oh-my-zsh#4810]
I use zsh 5.2-3 on Debian and omz git tag=5464fe3. 

Path completion does not work and completely hangs the console, when I try these completions (different commands not only ls of course):

- I want to do completion a'la `ls /*/.*<TAB>`, e.g. `ls /etc/i<TAB>`
- Completion a'la `ls /home/myuser/*`

I suspect that completion does not work when path starts with `/`. 

What works:
- `ls <TAB>`
- `ls ../<TAB>`
- in `/etc/` `ls -l init<TAB>`

From zsh debug, the last lines:
...
```
+_path_files:243> [[ automenu-unambiguous == (*menu|[0-9]*) || -n '' || -n '' ]]
+_path_files:246> [[ -n '' ]]
+_path_files:250> Mopts=( -M 'r:|/=* r:|=*' ) 
+_path_files:255> [[ /etc/i == [^][*?#^\|\<\>\\]#(`[^`]#`|\$)*/* ]]
+_path_files:276> [[ / == \~ ]]
+_path_files:326> linepath='' 
+_path_files:327> realpath='' 
+_path_files:329> zstyle -s :completion::complete:ls:argument-rest: preserve-prefix tmp1
+_path_files:337> [[ / == / ]]
+_path_files:342> pre=etc/i 
+_path_files:343> orig=etc/i 
+_path_files:344> donepath=/ 
+_path_files:345> prepaths=( '' ) 
+_path_files:358> prepath=
+_path_files:364> skipped='' 
+_path_files:365> cpre='' 
+_path_files:367> [[ -n '' || -z 1 ]]
+_path_files:407> tpre=etc/i 
+_path_files:408> tsuf='' 
+_path_files:416> testpath=/ 
+_path_files:418> tmp2='' 
+_path_files:419> tpre=etc/i 
+_path_files:421> tmp1=( / ) 
+_path_files:424> ((  npathcheck = 0  ))
+_path_files:425> true
+_path_files:427> origtmp1=( / ) 
+_path_files:430> [[ etc/i == */* ]]
+_path_files:431> PREFIX=etc 
+_path_files:432> SUFFIX='' 
+_path_files:447> tmp2=( / ) 
+_path_files:449> [[ etc/i == (#b)*/(*) ]]
+_path_files:457> [[ -n i ]]
+_path_files:458> compfiles -P tmp1 accex '' 'm:{a-zA-Z}={A-Za-z} m:{a-zA-Z}={A-Za-z}' '' fake
```

**Comment by mcornella** [comment]
`_path_files` is bundled by default within zsh. You can check if [the case insensitive option of Oh My Zsh](https://github.com/robbyrussell/oh-my-zsh/blob/5464fe3e4ad02a33243f42bcd8c91a287bc26185/templates/zshrc.zsh-template#L10-L11) is the source of the problem, but I lean on the side of this being an issue with your installed zsh version.

If the above doesn't work, try changing you zshrc file for one that doesn't load Oh My Zsh but still enables completion with `compinit -i ~/.zcompdump`.

**Comment by tdi** [comment]
You are right. I downgraded to 5.2-2 and it works again. I will file Debian bug.

**Comment by mcornella** [comment]
Nice! Feel free to reopen the issue if it's confirmed that Oh My Zsh has something to do with it.
