### ISSUE TITLE
Red prompt on terminal startup, using default robbyrussell theme

### ISSUE THREAD

**Issue by kixarinum** [robbyrussell/oh-my-zsh#4812]
Hi all, I am using default `robbyrussel` theme and I'm getting the red arrow on startup. After any successful command it turns green, after any other error it goes red again. But, I can't understand why it's an error (thus a red string) on startup. Looks like this part of [code](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme#L1) is responsible for this.

**Comment by mcornella** [comment]
The last command you run on startup returns an error, which is the last one on your zshrc. Please post that

**Comment by qaisjp** [comment]
Close?

**Comment by harenj** [comment]
I noticed I get a red arrow after running `git log` and then pressing `q` to exit. The arrow will remain red until I run another successful command. I am not sure the intended purpose of this?

**Comment by duttaditya18** [comment]
@harenj If you press `q`, git returns an error code other than `0`. So, you see a red arrow.

**Comment by qaisjp** [comment]
Close???
