### ISSUE TITLE
java -jar <myname> does not autocomplete

### ISSUE THREAD

**Issue by AAverin** [robbyrussell/oh-my-zsh#4817]
I get a very strange behaviour.
Attempting to run my custom file using some java.jar program fails to autocomplete filename even if I provide full path.

I was trying to unpack an .apk file using apktool (http://ibotpeaches.github.io/Apktool/), but autocomplete simply doesn't work

**Comment by mcornella** [comment]
Hi! How did you figure this out?

**Comment by AAverin** [comment]
I forgot to add a parameter to the call.
I was writing `java -jar apkTool.jar my.apk` instead of `java -jar apkTool.jar d my.apk`.

**Comment by mcornella** [comment]
Oh nice, thanks for the info :+1:
