### ISSUE TITLE
shell '/usr/bin/zsh' does not exist

### ISSUE THREAD

**Issue by nickdesaulniers** [robbyrussell/oh-my-zsh#4818]
Hi there, I'm setting a new machine and probably missed something.

I installed homebrew, git, zsh, then this.  During the installation I saw the warning:

```
chsh: WARNING: shell '/usr/bin/zsh' does not exist
```

and when I try to open a new session I see:

```
login: /usr/bin/zsh: No such file or directory
```

but it does look like I have zsh installed:

```sh
➜  ~  which zsh
/usr/local/bin/zsh
```

Why is the install script trying to `chsh` to `/usr/bin/zsh` as opposed to `/usr/local/bin/zsh`?

**Comment by nickdesaulniers** [comment]
ah, after running `brew reinstall zsh` I just saw: 

```
==> Caveats
In order to use this build of zsh as your login shell,
it must be added to /etc/shells.
Add the following to your zshrc to access the online help:
  unalias run-help
  autoload run-help
  HELPDIR=/usr/local/share/zsh/help
```

**Comment by mcornella** [comment]
[The current installer looks at `/etc/shells`](https://github.com/robbyrussell/oh-my-zsh/blob/5464fe3e4ad02a33243f42bcd8c91a287bc26185/tools/install.sh#L95) for the most recent zsh (i.e. the last one in `/etc/shells`). For some reason you have `/usr/bin/zsh` there even though you don't have it installed.

As the brew notice you posted says, you need to add to `/etc/shells` the zsh you installed with brew (`which -a zsh` might tell you where it is). Then a simple `chsh -s path_to_zsh` will change your default shell (note that you'll have to log out).

**Comment by nickdesaulniers** [comment]
> For some reason you have /usr/bin/zsh there even though you don't have it installed.

Indeed. Maybe this is new for the latest version of Zsh, homebrew, or OSX.

**Comment by nickdesaulniers** [comment]
I had to remove `/usr/bin/zsh` from `/etc/shells`, then rerun the installer.

**Comment by mcornella** [comment]
Ok, thanks for reporting that. Possibly in a subsequent version of the installer we have a smarter way to change the shell by checking if it exists or not.

**Comment by nickdesaulniers** [comment]
Thanks for the help.  oh my zsh is a fantastic utility, and I appreciate the help!

**Comment by mcornella** [comment]
Hi @nickdesaulniers! It's been so long but now the installer in #5169 has a better way to get the zsh path. I've tested it in a few systems and it seems to work, so hopefully it does so for you.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!
