### ISSUE TITLE
virtualenwrapper_setup_tab_completion:1x: command not found.

### ISSUE THREAD

**Issue by texastony** [robbyrussell/oh-my-zsh#4819]
I just installed zhs, and then oh-my-zsh. Now, every time I start a shell, I get this:

`virtualenvwrapper_setup_tab_completion:14: command not found: complete
virtualenvwrapper_setup_tab_completion:15: command not found: complete
virtualenvwrapper_setup_tab_completion:16: command not found: complete
virtualenvwrapper_setup_tab_completion:17: command not found: complete
virtualenvwrapper_setup_tab_completion:18: command not found: complete
virtualenvwrapper_setup_tab_completion:19: command not found: complete`

I have looked around on Google, stack over flow, and here, but have not seen this issue. I did not install the vitualenvwrapper plugin, and the only plugin callled in my .zshrc is:
`plugins=(git)`

Since git tab completion is why I am trying zsh, I am loathe to get rid of that. I did have some virtual environments installed on my system prior to installing zsh, so maybe that is why these are being called. Does anyone have any pointers on are where this command is being generated from? 

My OS is Scientific Linux 7, I use gnome as my desktop environment. 

I uploaded my .zshrc as zshrc.txt. It is not called that on my file system, I just needed to appease github.
[zshrc.txt](https://github.com/robbyrussell/oh-my-zsh/files/113712/zshrc.txt)

-------
EDITED by moderators

zshrc without comments:
```zsh
export SHELL=/bin/zsh
export EDITOR='emacs'

[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh

export ZSH=/afs/inf.ed.ac.uk/user/s15/s1567890/.oh-my-zsh

ZSH_THEME="af-magic"

COMPLETION_WAITING_DOTS="true"

plugins=(git)

export PATH="/usr/lib64/qt-3.3/bin:/usr/local/bin/:/usr/libexec/lightdm:/opt/matlab-R2015a/bin/:/usr/local/sbin:/usr/bin:/sbin:/opt/sicstus-4.0.1/bin"

source $ZSH/oh-my-zsh.sh

. /etc/profile.d/vte.sh
```

**Comment by mcornella** [comment]
First of all, there's nothing in your zshrc to suggest that the virtualenvwrapper stuff comes from there. So I would think that you're actually not using zsh, which is reinforced by the fact that you have a university account and normally administrators of such networks don't allow users to change their shell. Please confirm that by posting the result of `echo $SHELL`.

Second of all, the `vte.sh` file is sourced twice. That has nothing to do with your issue though, it's just tidying up. Put the `[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh` line at the bottom and get rid of the `. /etc/profile.d/vte.sh` line.

**Comment by texastony** [comment]
You are, of course, spot on that I am a student using a university account.  However, I can set my preferences to my desires for most attributes. In particular, I can set my shell:
`------------------------------------------------------------
~ » echo $SHELL                                                s1567890@marsala
/bin/zsh
`
I corrected my .zshrc as indicated. Maybe this has nothing to do with oh-my-zsh and is an artefact  of something else. But if I launch bash, I do not get the above messages. Is there a way to launch .zsh with out oh-my-zsh, to help me debug where this all is coming from?

**Comment by mcornella** [comment]
> Answer to my own, very unintelligent, question: Of course there is, I can just comment out everything in the .zshrc file related to oh-my-zsh and launch that. And if I do that, I see that I still have the same errors, so it is an artefact of my zsh installation, not of my oh-my-zsh files. Thank you very much mcornella.

You could also run zsh without loading user files by running [`zsh -f`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-NO_005fRCS). If you run that, I'm confident you won't see the virtualenvwrapper error anymore. That means that there must be some other resource file that loads `virtualenvwrapper`. Have a look at any of the files listed [in this page](http://zsh.sourceforge.net/Doc/Release/Files.html#Files-2).

**Comment by texastony** [comment]
I found it was a global file that was set by my administrator system, though I am still not certain which file was causing the problem. I fixed it by setting so the zsh always starts with `-d` option, and therefore only loads my startup files, as compared to startup files set elsewhere.
