### ISSUE TITLE
zsh shows wrong directory path when directory is changed using uppercase letters

### ISSUE THREAD

**Issue by ajitsing** [robbyrussell/oh-my-zsh#4820]
when I switch the directory by typing uppercase letters, after switching when I run ```pwd``` zsh shows me the path with directory name in caps. which is wrong. It should show me the right path to current directory.

<img width="316" alt="dir_path_issue" src="https://cloud.githubusercontent.com/assets/3875127/12752005/51d38a0e-c9e6-11e5-90b0-bda3b07c7726.png">

**Comment by mcornella** [comment]
You have two directories named the same, but one is uppercase and the other is lowercase. You can see that with a simple `ls`. When you switch to the uppercase directory zsh shows the uppercase directory, and viceversa.

**Comment by ajitsing** [comment]
I am sure there is only one directory with this name, here is another example with ```ls```

<img width="502" alt="dir_issue_zsh" src="https://cloud.githubusercontent.com/assets/3875127/12752388/57fcfb66-c9e8-11e5-97b7-79fb242014d6.png">

I hope this will clear the doubt.

**Comment by mcornella** [comment]
Ok that is indeed weird, it's the first time I've seen it. Are you using OSX or some sort of cygwin on Windows?

**Comment by ajitsing** [comment]
Yes I am using OSX.

**Comment by mcornella** [comment]
Ok you might be using a case insensitive filesystem. If that's the case, that's standard behavior. Check here: http://apple.stackexchange.com/a/71360

**Comment by ajitsing** [comment]
Yes you are right, My filesystem is case insensitive. I can see the save behaviour even in bash.

**Comment by 5tefan** [comment]
Sorry for digging this up, I'm experiencing something similar with autocomplete and can't find a solution: I'm in a very similar situation, and once upon a time, I accidentally typed `cd teST`, now every time I tab complete `cd te<tab>` I get `cd teST`. Is there anything I can do about that? I would like it to just autocomplete to `cd test`.

**Comment by mystredesign** [comment]
I am getting this too. Completely inaccurate casing even appears on the PWD location path for the terminal. For me, It auto-completes to something that has a .egg with the capitalization, and then a similar-named folder with out a .egg extension is given the capitalization. Right now I'm really annoyed that OSX switched to zsh because the only reasonable fix was to use ohmyzsh and there is still some crazy behavior.
