### ISSUE TITLE
Why `gcan!` has `-s` option?

### ISSUE THREAD

**Issue by wanbok** [robbyrussell/oh-my-zsh#4827]
It makes unnecessary text like:
```
Signed-off-by: Git Author <my@email.com>
```

I think that `-s` should be removed.

**Comment by mcornella** [comment]
The `gca!` alias is what you want then, which is the same as `gcan!` without the `-s´.  The `n` of the alias refers to *naming* the commit, i.e. the signed-off thing.

**Comment by wanbok** [comment]
@mcornella Actually, I want `gca! --no-edit`. but `gcan!` is `gca! -s --no-edit`

**Comment by mcornella** [comment]
I see that now, sorry.

I assume this had to do with the git workflow of the author of the alias, which was taken from the [`git2` plugin](https://github.com/Stibbons/oh-my-zsh/blob/master/plugins/git2/git2.plugin.zsh#L97).

From my perspective, @Stibbons probably uses this when rebasing and fixing some commits from another author, which then needs to be signed off but there's no reason to edit the commit message.

Removing the `-s` from the `gcan!` alias might break people's workflow, so the best solution is to add a separate alias with the `--no-edit` flag. I'm not exactly sure about the naming though. What do you suggest?

**Comment by Stibbons** [comment]
Hello

Adding signature is a pretty good habbit, the alias ``gcan!`` does pretty much everything. I agree with you this breaks the rule "shortened git command", ie, g = 'git', c = "commit", a = "all", n = "not edit", ! = "amend" (could have been A). to have s it would be in an alias such as gcans!

I also agree, this would break user workflow, and adding this signature is a good practice to set up (signature might be different from the user that push the commit).

**Comment by wanbok** [comment]
Hi

I'm glad that you agree.
I changed my commit that make `gcane!` to `gcan!` and the old `gcan!` to `gcans!`.
