### ISSUE TITLE
xcrun: error: invalid active developer path

### ISSUE THREAD

**Issue by Jcasselman** [robbyrussell/oh-my-zsh#4829]
Full error message:

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools),
       missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

**Comment by mcornella** [comment]
This doesn't look like an Oh My Zsh issue. 

Here are possible solutions: https://github.com/Homebrew/homebrew/issues/23500#issuecomment-26992756 (the whole thread has more suggestions), [part 3, _Fix developer tools_ of this post](https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/) and [this stackexchange thread](http://apple.stackexchange.com/questions/209624/how-to-fix-homebrew-error-invalid-active-developer-path-after-upgrade-to-os-x).

**Comment by lmery** [comment]
sudo xcode-select --install

**Comment by ragurney** [comment]
@mcornella 

This just happened to me when I accidentally typed `git status <enter>` when a random 'Do you want to update ZSH' popped up :/

**Comment by mcornella** [comment]
That's just because you ran git, see the comment previous to yours.

**Comment by ragurney** [comment]
That does indeed fix the problem, but I run into this for example by accidentally typing a command when ZSH tries to auto-update. For example, here you can see I accidentally typed 'ls <enter>' when opening the terminal:
```
Last login: Thu Feb  3 13:12:05 on console
[oh-my-zsh] Would you like to update? [Y/n] l
[oh-my-zsh] You can update manually by running `omz update`
 rgurney >~ > ls
```

which results in 
```
 git status
xcrun: error: active developer path ("/Library/Developer/CommandLineTools") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
```

and i have to run `xcode-select --install` _again_ to fix this. Very annoying.

**Comment by mcornella** [comment]
It should be enough to run the command once. It's not relevant whether you mistakenly run a command when OMZ tries to auto-update. This message will still appear when you run git. See https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa for more things to try.
