### ISSUE TITLE
Globalias

### ISSUE THREAD

**Issue by slavaGanzin** [robbyrussell/oh-my-zsh#4834]
Can't find any mentions of global alias expand plugin 
http://blog.patshead.com/2012/11/automatically-expaning-zsh-global-aliases---simplified.html

May I add it to plugins?

**Comment by mcornella** [comment]
I wanted to adapt that to fix #4000, see https://github.com/robbyrussell/oh-my-zsh/pull/4000#issuecomment-120507697. You could work on adapting it yourself and put it on some `lib/` file as well, instead of creating a plugin. Thanks!
