### ISSUE TITLE
alias .='pwd'

### ISSUE THREAD

**Issue by nitrocode** [robbyrussell/oh-my-zsh#4835]
Thought this alias might be useful enough to add since it's not being used for anything else

**Comment by sachin21** [comment]
`.` is shell built-in command. so we cannot use `alias .='pwd'`.
`.` is `source` command.

**Comment by nitrocode** [comment]
Oh wow I didn't know [this](http://ss64.com/bash/source.html). Thanks.

**Comment by sachin21** [comment]
np :smile:
