### ISSUE TITLE
Most-used History Cleanup

### ISSUE THREAD

**Issue by hickscorp** [robbyrussell/oh-my-zsh#4843]
Good morning,

This is a feature request. Maybe it already exists, but I would have no idea in the world about how it would be called.

Basically, I find myself opening my `.zsh_history` from times to times and do some cleanup. I noticed some patterns:
- I usually remove commands that had a non-zero exit status, but not **always**.
- I remove commands that I don't use often (Eg `apt-get install` with one specific package etc), but **not always**.
- Ha! `find ./ -name .DS_Store -exec rm {} \;` all over the place... I'll remove that, but **not always**.

As the factorization of the **not always** part is obvious, it probably means we need machine learning, so here is the idea. It would be quite nice to have some kind of scoring options:
- When a command is issued, it is being scored with 100.
- A zero exit status immediately decreases that score.
- When opening a new shell, all commands that are older than `N` days have their score decreased by 25.
- When an existing command is selected using up / down / completion, increase it's score.
- Whenever a command's score reaches zero, it gets removed.

On top of that, a slightly configurable user callback would be nice, here would be the flow:
- Whenever a command score would change, the user callback is called.
- The user callback has access to the command itself, the current score, the increment / decrement and a reason ("non-zero-status", "history-selected", etc).
- The user callback method is free to return a new value that would replace the increment / decrement.

I hope you will understand what I mean. Do you guys think it would be nice to have this maybe?  It's very unfortunate that I have no idea how to create such plugin.

Keep up the good work! I just looooove my `oh-my`.

**Comment by mcornella** [comment]
[This](https://superuser.com/a/902508/545959) could be of use to remove failed commands. I can't say the same for the rest of the specs. I don't think you could do that without reintroducing a completely new history file format and history command.

**Comment by mcornella** [comment]
I'm closing it because I see nothing like this being coded in the near- or mid-term.
