### ISSUE TITLE
Error _omz_git_git_cmd on startup 

### ISSUE THREAD

**Issue by rands0n** [robbyrussell/oh-my-zsh#4851]
Everytime I open my iterm with zsh I got this error. Updated last day with improvements.

```
/Users/orandson/.oh-my-zsh/plugins/git/git.plugin.zsh:2: not an identifier: _omz_git_git_cmd
```

I open the file and see that function to get the current directory:

```
# The list of remotes
function current_repository() {
  if ! $_omz_git_git_cmd rev-parse --is-inside-work-tree &> /dev/null; then
    return
  fi
  echo $($_omz_git_git_cmd remote -v | cut -d':' -f 2)
}
```

In first line we have this too:

```
zstyle -s ":vcs_info:git:*:-all-" "command" _omz_git_git_cmd
: ${_omz_git_git_cmd:=git}
```

My iterm is working right now, but is boring see this everytime i opened him. What do you guys think is?

**Comment by rands0n** [comment]
Solved by downloading version of plugins directory!

**Comment by CafeLiang** [comment]
Hi @rands0n, I have the same problem, could you please explain how you solve this problem by "downloading version of plugins directory"? Thanks a lot!
