### ISSUE TITLE
No indication of which virtualenv using workon

### ISSUE THREAD

**Issue by vinamelody** [robbyrussell/oh-my-zsh#4853]
Hi, strange behavior experienced yesterday, I'm getting `deactivate:unset:1: no such hash table element: pydoc`, yet this morning it's gone.

However when using `workon saleor` there is no usual indicator of (saleor) before the arrow.

Thank you for your help.

**Comment by Marcholio** [comment]
Is this still an issue with the current version? If not, this could be closed.
