### ISSUE TITLE
input disabled after paste (bracketed-paste-magic and zsh 5.2)

### ISSUE THREAD

**Issue by argshook** [robbyrussell/oh-my-zsh#4854]
Hi,

pasting any text, even without any special characters, freezes prompt and i have to ctrl+c to be able to use it again. Error i get after hitting `ctrl` + `shift` + `v`:

```bracketed-paste-magic:zle:41: not enough arguments for -U```

happens even if my clipboard has just `a` 

Looks similar to #4434 except i'm using zsh 5.2 on arch linux.

To prevent error i'm bypassing the loading of smart urls in `~/.oh-my-zsh/lib/misc.zsh` like so:

```zsh
#if [[ $ZSH_VERSION != 5.1.1 ]]; then
if false; then
  for d in $fpath; do
  	if [[ -e "$d/url-quote-magic" ]]; then
  		if is-at-least 5.1; then
  			autoload -Uz bracketed-paste-magic
  			zle -N bracketed-paste bracketed-paste-magic
  		fi
  		autoload -Uz url-quote-magic
  		zle -N self-insert url-quote-magic
      break
  	fi
  done
fi
```

looks like checking for zsh version is not enough.

Let me know if any additional info is required.

**Comment by mickaelperrin** [comment]
I can confirm the problem on Mac OS X 10.11.3 and zsh 5.2 (x86_64-apple-darwin15.0.0).

The workaround works also.

Thanks

**Comment by roshannaik** [comment]
Thank you for providing this workaround!

**Comment by rakshit-jain** [comment]
Thanks for the work around

**Comment by Roscoe69** [comment]
Dont bother me again slut

**Comment by mcornella** [comment]
If this is still happening to you please provide the following:
- What system you're using
- What zsh version you're using

**Comment by smiller171** [comment]
Pixelbook running Crostini
zsh 5.3.1 (x86_64-debian-linux-gnu)
