### ISSUE TITLE
z.sh:243: bad math expression: operator expected at `precmd_fun...'

### ISSUE THREAD

**Issue by smironescu** [robbyrussell/oh-my-zsh#4860]
Hi folks,
I'm getting this error on iTerm after updating to OSX El Capitan.
`z.sh:243: bad math expression: operator expected at precmd_fun...`
Anyone has the same problem? Any solutions are welcomed!
Many thanks.

**Comment by mcornella** [comment]
What `zsh --version` do you have?

**Comment by smironescu** [comment]
I have 4.8 version. The error still keeps appearing even after the updates.

**Comment by mcornella** [comment]
[There's no such version of zsh](https://github.com/zsh-users/zsh/releases?after=zsh-5.0.0) (?)

Anyway, try running `precmd_functions[$(($#precmd_functions+1))]=_z_precmd` and tell me if you get the same error.

**Comment by TheKinrar** [comment]
I'm having the same error on zsh 5.4.2.
`precmd_functions[$(($#precmd_functions+1))]=_z_precmd` produces the error too.

**Comment by TheKinrar** [comment]
Well, my mistake, not the same error.

`printSizeHumanReadable:2: bad math expression: operator expected at `3311280947...'`

Should I open an other issue?

**Comment by mcornella** [comment]
@TheKinrar you would need to open another issue, but it looks like that's an error within [the powerlevel9k theme](https://github.com/bhilburn/powerlevel9k/blob/13b0e383a066c9c37d5cf71d4af521f9b73a173e/functions/utilities.zsh#L33).

**Comment by Dmitryi** [comment]
When starting xterm, a message appears.
/etc/profile.d/z.sh:223: bad math expression: operator expected at `precmd_fun...'

zsh 5.7.1 (x86_64-redhat-linux-gnu) 
Xterm + tmux

How do you get rid of this message?

**Comment by mcornella** [comment]
Look at line 223 of `/etc/profile.d/z.sh` to figure out what the bad math expression is. Also we don't ship things in `/etc/profile.d`, that must be installed by a package, not Oh My Zsh.

**Comment by Dmitryi** [comment]
I thought I'd put out a piece of code.
Perhaps he will clarify the situation somehow.

```
if type compctl >/dev/null 2>&1; then
    # zsh
    [ "$_Z_NO_PROMPT_COMMAND" ] || {
        # populate directory list, avoid clobbering any other precmds.
        if [ "$_Z_NO_RESOLVE_SYMLINKS" ]; then
            _z_precmd() {
                _z --add "${PWD:a}"
            }
        else
            _z_precmd() {
                _z --add "${PWD:A}"
            }
        fi
        [[ -n "${precmd_functions[(r)_z_precmd]}" ]] || {
223 ->  precmd_functions[$(($#precmd_functions+1))]=_z_precmd
        }
    }
    _z_zsh_tab_completion() {
        # tab completion
        local compl
        read -l compl
        reply=(${(f)"$(_z --complete "$compl")"})
    }
    compctl -U -K _z_zsh_tab_completion _z
```

**Comment by mcornella** [comment]
Looks like `$#precmd_functions` needs braces: `${#precmd_functions}`. A better syntax is `precmd_functions+=_z_precmd`, as long as it's compatible with bash.

This needs to be reported to the rupa/z github repository.

**Comment by Dmitryi** [comment]
I understand what you're saying.
I just deleted z. And the error does not appear anymore.
Thank you.
