### ISSUE TITLE
ssh-agent plugin does not work on mac os El Capitan

### ISSUE THREAD

**Issue by MRezaNasirloo** [robbyrussell/oh-my-zsh#4862]
I have added ssh-agent to plugin list, but it doesn't add any identities to `ssh-add`
It doesn't even produce some error or logging text.

**Comment by bzhtux** [comment]
Hi, I have a pretty similar issue but I have only one key loaded and always the same whatever the order in the .zshrc file.

**Comment by jotum** [comment]
Same here in OSX and ubuntu 16.04

**Comment by anandpathaksharma** [comment]
I just experienced the same problem. I checked in my `~/.ssh` directory and found existing `environment-*` files. Deleting these then logging out and back in resolved the issue.

**Comment by mcornella** [comment]
You have to specify which identites you want to load using the [command found in the README](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ssh-agent#instructions).
For example:
```zsh
zstyle :omz:plugins:ssh-agent identities id_rsa id_bob
```

Put it on your zshrc file, **before** OMZ is sourced.
