### ISSUE TITLE
Incorrect autocomplete for `cd` command with `whoopsie`

### ISSUE THREAD

**Issue by tejasbubane** [robbyrussell/oh-my-zsh#4864]
I just upgraded to 0d0042a and started getting this little issue.

In any directory if I start typing `cd wh` and hit a tab, I get autocompletion of `wh` to `whoopsie`. This happens even when I don't have any directory named `whoopsie`.

```shell
tejas@tejas-Presario-CQ62-Notebook-PC:~/.oh-my-zsh|master 
⇒  ls
cache  custom  lib  log  MIT-LICENSE.txt  oh-my-zsh.sh  plugins  README.markdown  templates  themes  tools
tejas@tejas-Presario-CQ62-Notebook-PC:~/.oh-my-zsh|master 
⇒  cd whoopsie 
cd: no such file or directory: whoopsie
```

This is really weird. Closing and restarting the terminal did not help. Searched through the code and  issues list for the word `whoopsie` but found no results. Can anyone else confirm this?

**Comment by apjanke** [comment]
Doesn't reproduce for me on OS X 10.9.

Do you have a user named `whoopsie`? Or have `$cdpath` set?

You can turn on `set -x` and do a completion to see a trace of what the completion code is doing. A lot to read through, but that should tell you where it's coming from.

**Comment by mcornella** [comment]
That's [the `cdablevars` setopt doing it's "magic"](http://superuser.com/questions/833812/zsh-autocompleting-cd-with-other-peoples-home-directories#comment1095949_833812). We should probably get rid of it unless there's some really good use of it.

**Comment by mcornella** [comment]
I forgot, you can disable that by appending `unsetopt cdablevars` to your zshrc file.

**Comment by tejasbubane** [comment]
Too much magic :smile: `unsetopt` works. :+1:
