### ISSUE TITLE
... Where is the ZSH_CUSTOM folder located?

### ISSUE THREAD

**Issue by koesherbacon** [robbyrussell/oh-my-zsh#4865]
This is probably me just being a bonehead, but where can I find the ZSH_CUSTOM folder so I can put my custom aliases in there as instructed in the .zshrc file?

Thanks a lot!  I love your shell!!

**Comment by apjanke** [comment]
By default, [it is at `$ZSH/custom`](https://github.com/robbyrussell/oh-my-zsh/blob/0d0042aad33562877dffd12baa6fe86e40642241/oh-my-zsh.sh#L16-L20); that is, the `custom` directory under your oh-my-zsh installation, which is at `~/.oh-my-zsh` by default. 

If you want to use a different location, you can set `$ZSH_CUSTOM` to a different path in your `~/.zshrc` before loading oh-my-zsh.

**Comment by JohnMaguire** [comment]
`echo $ZSH_CUSTOM`

**Comment by ndeoligence** [comment]
One more thing...
What must I name my aliases file within $ZSH_CUSTOM/ ?

**Comment by mcornella** [comment]
Any file ending in `.zsh` immediately under `$ZSH_CUSTOM` (that is, not inside a folder) will be sourced, so you can name it anything. For example:
```
# works
$ZSH_CUSTOM/aliases.zsh
# doesn't work
$ZSH_CUSTOM/aliases/git.zsh
```

**Comment by ferrao** [comment]
> Any file ending in `.zsh` immediately under `$ZSH_CUSTOM` (that is, not inside a folder) will be sourced, so you can name it anything. For example:

Would be great to have this documented somewhere, it took me a while to find this issue, was naming it `.zshrc` and `zshrc`, but nothing was working ;)

**Comment by tya99** [comment]
> Any file ending in `.zsh` immediately under `$ZSH_CUSTOM` (that is, not inside a folder) will be sourced, so you can name it anything. For example:
> 
> ```
> # works
> $ZSH_CUSTOM/aliases.zsh
> # doesn't work
> $ZSH_CUSTOM/aliases/git.zsh
> ```

That's kind of inconvenient and a depart from the way that `$HOME/.oh-my-zsh/plugins` is with individual directories per plugin

I want to put mine in `$HOME/.config/ohmyzsh/custom/plugins`

The particular plugin I'm wanting to add is [solarized-man](https://github.com/zlsun/solarized-man). The thing is it's a git submodule so the '.zsh' file needs to actually be in a "solarized-man" directory inside the plugins directory.

If there's some way to do this can you tell me how thanks.

Inside "plugins" there I have a directory, "solarized-man"

**Comment by mcornella** [comment]
The `$ZSH_CUSTOM` variable should point at the root of the custom folder, not the plugins folder. So: 
```zsh
ZSH_CUSTOM=$HOME/.config/ohmyzsh/custom
```

**Comment by tya99** [comment]
Okay, if I have this in my zshrc:

```sh
# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.config/ohmyzsh/custom
```
ie:
```
$ echo $ZSH_CUSTOM
/home/tya99/.config/ohmyzsh/custom
```

The issue is my plugin isn't being detected in:
```
/home/tya99/.config/ohmyzsh
└── custom
    └── plugins
        └── solarized-man
            ├── .git
            ├── LICENSE
            ├── README.md
            └── solarized-man.plugin.zsh

3 directories, 4 files
```

How might I go about allowing detection of this?

**Comment by tya99** [comment]
> The `$ZSH_CUSTOM` variable should point at the root of the custom folder, not the plugins folder. So:
> 
> ```shell
> ZSH_CUSTOM=$HOME/.config/ohmyzsh/custom
> ```

Hmm. that didn't work for me, it seemed if I didn't specify the `plugins` directory, the plugin wasn't detected, even when i symlinked it to the current directory ie;

```
/home/tya99/.config/ohmyzsh
└── custom
    └── plugins
        ├── solarized-man
        │   ├── .git
        │   ├── LICENSE
        │   ├── README.md
        │   └── solarized-man.plugin.zsh
        └── solarized-man.plugin.zsh -> solarized-man/solarized-man.plugin.zsh

3 directories, 5 files
```

**Comment by mcornella** [comment]
The init script looks at `$ZSH_CUSTOM/plugins/$plugin/$plugin.plugin.zsh`, so `ZSH_CUSTOM` should be pointed at the custom directory. The symlink isn't necessary. If that doesn't work, maybe there are some changes to the OMZ repository or you don't have the latest update, but I guess that's not the case if you're getting a `warning: plugin not found` error. 

Run `zsh -xvic 'exit' &> ~/omz-debug.log` and post the generated file so I can take a look.

**Comment by tya99** [comment]
The plugin not found error was resolved when I removed it from `plugins=(git svn)`, i think it was probably looking in `~/.oh-my-zsh/plugins/`

The plugin is only found if I have the symlink not in the plugins directory ie:

```
lrwxrwxrwx 1 tya99 tya99 81 Mar 25 05:03 /home/tya99/.config/ohmyzsh/custom/solarized-man.plugin.zsh -> /home/tya99/.config/ohmyzsh/custom/plugins/solarized-man/solarized-man.plugin.zsh
```

I've put the omz-debug.log up here https://gist.github.com/tya99/61dc786e18f30bbebeabd24c59789ebb

**Comment by mcornella** [comment]
The debug log doesn't show the problem because you took out `solarized-man` from the plugins array. Try again with it this time, and also redefine `ZSH_CUSTOM` so that it doesn't end with a trailing slash. In my system the trailing slash wasn't a problem, but maybe in Solaris is? Just to check.

**Comment by tya99** [comment]
Seems to be working now. I did just update ohmyzsh.

```diff
@@ -43,13 +43,13 @@ ZSH_THEME="risto"
 # HIST_STAMPS="mm/dd/yyyy"
 
 # Would you like to use another custom folder than $ZSH/custom?
-ZSH_CUSTOM=$HOME/.config/ohmyzsh/custom/
+ZSH_CUSTOM=$HOME/.config/ohmyzsh/custom
 
 # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
 # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(git svn)
+plugins=(git svn solarized-man)
```

I could have sworn I tried this earlier and it didn't.

```
/home/tya99/.config/ohmyzsh
└── custom
    └── plugins
        └── solarized-man
            ├── .git
            ├── LICENSE
            ├── README.md
            └── solarized-man.plugin.zsh

3 directories, 4 files
```

Thanks!

**Comment by mcornella** [comment]
Oh I saw something about Solaris in the log, I guess I confused it with the OMZ code. Glad it's working now!

**Comment by lucawrabetz** [comment]
New to oh-my-zsh and zsh. I added an alias to a file $ZSH_CUSTOM/aliases.zsh i created, restarted my terminal, and the alias was not working. Alias was added as: 
alias python = "python3" 

Does anything need to be sourced manually, I thought this would work as a permanent alias?

**Comment by mcornella** [comment]
The equal sign needs to not have spaces around it. So:
```zsh
alias python="python3"
```

**Comment by lucawrabetz** [comment]
> The equal sign needs to not have spaces around it. So:
> 
> ```shell
> alias python="python3"
> ```

Thank you! Problem solved.
