### ISSUE TITLE
How do I remove directory yellow highlighting from robbyrussell's theme?

### ISSUE THREAD

**Issue by diegodesouza** [robbyrussell/oh-my-zsh#4867]
After running `ls` depending on the file/directory type, i get a yellow highlighting that i dislike much. I wanted to remove that but haven't found where it's being set. Could anyone point me to it? 
<img width="401" alt="screen shot 2016-02-21 at 2 54 15 pm" src="https://cloud.githubusercontent.com/assets/7575914/13205013/66517616-d8ab-11e5-89f4-8de5d62e95d9.png">

**Comment by diegodesouza** [comment]
After exploring other themes I found one that doesn't add this yellow highlighting, and they use `export LSCOLORS=""` is this the best way of changing the color of the `ls`ing? thanks for the help

**Comment by colepanike** [comment]
Could also be this: https://superuser.com/questions/1242321/oh-my-zsh-why-did-my-ls-colors-for-directories-change-after-copying-to-usb
