### ISSUE TITLE
Parse errors due to ^M end of line

### ISSUE THREAD

**Issue by sinlov** [robbyrussell/oh-my-zsh#4870]
```
.zshrc:3: command not found: ^M
.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'

38 is_plugin() {
39   local base_dir=$1
40   local name=$2
41   test -f $base_dir/plugins/$name/$name.plugin.zsh \
42     || test -f $base_dir/plugins/$name/_$name
43 }
```

All files change to windows file style: each file endline is `^M`.

zsh 5.2 (x86_64-apple-darwin14.5.0)

**Comment by mcornella** [comment]
The temporary solution to that is changing your `core.autocrlf` git config setting to use `input`, given that you are on OSX. See https://github.com/robbyrussell/oh-my-zsh/issues/4402#issuecomment-143976458.

To sum up, you need to run the following:
```zsh
cd $ZSH
git config core.autocrlf input
git rm --cached -r .
git reset --hard
```

**Comment by sinlov** [comment]
thinks ~ 

I'm setting
`git config --global core.autocrlf true`
so that。。

**Comment by mcornella** [comment]
Don't set it to true, set it to `input`. That's a better default for OSX.

**Comment by sinlov** [comment]
Thanks For Sharing~

**Comment by teamonn** [comment]
1. `.zshrc:3: command not found: ^M`  The solution is as follows:

&ensp; `vim ~/.zshrc`  then enter `:set ff=unix`

2. ```.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'  ```   The solution is as follows:
```
cd $ZSH
git config core.autocrlf input
git rm --cached -r .
git reset --hard
```

Who can explain the reason, I will be grateful. Most of them appear on the OSX system.

**Comment by nickwebcouk** [comment]
I'm still having this issue after following the troubleshooting steps above. 

Last login: Mon Aug 24 09:52:54 on ttys000
/Users/nick/.oh-my-zsh/oh-my-zsh.sh:20: parse error near `<<<'

sw_vers:
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73

uname -a
Darwin Mac-mini.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

Can this be reopened? Thanks, Nick

**Comment by mcornella** [comment]
You must not have the latest OMZ update, there's no `<<<` in the oh-my-zsh.sh file at the moment. Try `omz update`.

**Comment by nickwebcouk** [comment]
Looks like I've hijacked this unnecessarily - manually went and edit the file and removed all non confirming characters, but now all I get is a '''[oh-my-zsh] plugin 'git,zsh-autosuggestions' not found'''. Shall I raise a fresh issue? Thanks,

**Comment by mcornella** [comment]
Oh you probably had a git conflict pending to resolve, that's probably the source of the `<<<` characters.

Re: the not found error, the `plugins` variable is an array, and in zsh array entries are separated by whitespace, not commas. So that's why you see that error, OMZ is looking for a plugin literally named `git,zsh-autosuggestions`. Plus, make sure to have `zsh-autosuggestions` installed as an OMZ plugin, otherwise you'll get another not found error for that one.
