### ISSUE TITLE
.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'

### ISSUE THREAD

**Issue by sinlov** [robbyrussell/oh-my-zsh#4871]
38 is_plugin() {
 39   local base_dir=$1
 40   local name=$2
 41   test -f $base_dir/plugins/$name/$name.plugin.zsh \
 42     || test -f $base_dir/plugins/$name/_$name
 43 }

zsh 5.2 (x86_64-apple-darwin14.5.0)

**Comment by mcornella** [comment]
Duplicate of #4870

**Comment by sinlov** [comment]
Thanks
