### ISSUE TITLE
per-directory-history plugin permissions problems when using sudo

### ISSUE THREAD

**Issue by vip9** [robbyrussell/oh-my-zsh#4883]
When using per-directory-history plugin, it creates dirs/files in ~/.directory_history/. 
When used with sudo -s, plugin creates its files with permissions are root:root.
After end sudo session, shell is unusable due to:
_per-directory-history-addhistory:2: can't read history file /home/vip/.directory_history/**/history
Commands are not being executed (even exit)

Will simple SUDO_UID/GID check and chown be sufficient?
e.g. here: [(https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/per-directory-history/per-directory-history.zsh#L97)]

**Comment by mcornella** [comment]
Maybe #5493 solves your problem. If not, try asking @jimhester in [the official repo](https://github.com/jimhester/per-directory-history/issues/).
