### ISSUE TITLE
Autocomplete broken for 'du' command

### ISSUE THREAD

**Issue by ffxsam** [robbyrussell/oh-my-zsh#4885]
How do we modify the autocomplete files? The one for the "du" command is quite broken. It only wants to autocomplete the options, never files or folder names.

**Comment by varCharlie** [comment]
It seems to be working fine for me? 
Previously, I did notice issues, but not anymore.

If you type `-` it should give you options for arguments. If you leave out the `-` it gives you options for files and folders.

This must have been fixed recently.

What are your specs? Can you verify this is still an issue?

**Comment by mcornella** [comment]
Please post the output of the following:

```zsh
which -a du
which _du # after triggering du completion
zsh --version
```

**Comment by xlbruce** [comment]
I am having same trouble

**Comment by mcornella** [comment]
@xlbruce please follow the above instructions.
