### ISSUE TITLE
vim-mode seems to not working in my system

### ISSUE THREAD

**Issue by yangdaweihit** [robbyrussell/oh-my-zsh#4888]
after installing oh-my-zsh, I edited .zshrc line 52:

         plugins=(git vim-mode)

but it seems to not working. How can I enable it?

**Comment by varCharlie** [comment]
@yangdaweihit 
The plugin is not called vim-mode, it's called `vi-mode`.

You should close this issue.

**Comment by mcornella** [comment]
Thanks @varCharlie, that's exactly it.
