### ISSUE TITLE
Plugin zsh-syntax-highlighting stopped working

### ISSUE THREAD

**Issue by jazen** [robbyrussell/oh-my-zsh#4894]
I left comments at an issue there but the omz glue code seems to be the culprit — https://github.com/zsh-users/zsh-syntax-highlighting/issues/270#issuecomment-191179960

**Comment by apjanke** [comment]
Might be because their installation instructions ignore `$ZSH_CUSTOM`. See discussion on [the issue over there](https://github.com/zsh-users/zsh-syntax-highlighting/issues/270).

**Comment by jazen** [comment]
@apjanke You're right. Thanks — [this has been resolved](https://github.com/zsh-users/zsh-syntax-highlighting/commit/e635f766bef9ffe1c0d646d8fd256e9134e94468).
