### ISSUE TITLE
Bundler plugin without a gem, show wrong message

### ISSUE THREAD

**Issue by renanoronfle** [robbyrussell/oh-my-zsh#4896]
Hi, i have a wrong message error when i execute bi command without a gem bundler installed 

I got this message: 
Can't 'bundle install' outside a bundled project
i'm inside the project path.
The error message should be something as:
Bundler gem is not installed.

**Comment by mcornella** [comment]
If there is no Gemfile then it isn't a bundled project. I think that's what the error means.
