### ISSUE TITLE
git.plugin.zsh interferes with Graphics Magick

### ISSUE THREAD

**Issue by thebodzio** [robbyrussell/oh-my-zsh#4900]
One of the aliases in git.plugin.zsh, namely “gm” (git merge), interferes with “gm” (Graphics Magick) program. Perhaps it would be good to change the name of this alias?

**Comment by mcornella** [comment]
This is not the first time it's mentioned. We are working on a safer aliasing system that accounts for such things. For the time being, you can delete the gm alias by appending `unalias gm` to your zshrc file. 
Thank you for your understanding.

**Comment by mcornella** [comment]
Related: #1432

**Comment by thebodzio** [comment]
Thank you for taking care of it!
