### ISSUE TITLE
agnoster theme not showing up properly in pantheon-terminal "Elementary OS Freya 0.3.2"

### ISSUE THREAD

**Issue by rezk2ll** [robbyrussell/oh-my-zsh#4901]
hello, i've noticed after installing oh-my-zh that the agnoster theme is not working properly on pantheon-terminal , precisely the character  "\ue0b0" , i tried installing the power-line fonts , but that didn't fix it.
i'm on Elementary OS Freya 0.3.2 64bits , and here is a screenshot to explain more the issue.
![screenshot from 2016-03-05 21 01 25](https://cloud.githubusercontent.com/assets/6764881/13550147/29371bb6-e317-11e5-953e-78ab6d8df263.png)

**Comment by rezk2ll** [comment]
rezk2ll@X554LA:~$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

rezk2ll@X554LA:~$ locale -a
ar_TN.utf8
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

**Comment by pradyunsg** [comment]
You're most likely installing old powerline fonts. If the following command doesn't show a right pointing triangle on your terminal, get a powerline compatible font (like [Hasklig]).

```
echo "\ue0b0"
```
![separator example](https://cloud.githubusercontent.com/assets/3275593/13915116/b17c2bde-ef78-11e5-9f5c-5426896e035b.png)
(the black character)

[Hasklig]: https://github.com/i-tu/Hasklig

**Comment by jabbink** [comment]
Somehow I have the same problem since yesterday (randomly, I did not update any package).

I tried reinstalling the powerline fonts from git@github.com:powerline/fonts.git but that didn't seem to fix it :/

**Comment by mcornella** [comment]
What is your `locale` output? Are you sure your terminal emulator is using the right font?

**Comment by jabbink** [comment]
```zsh
 ✘ jasper@jasper-ThinkPad-T530  ~  locale
LANG=en_US.utf8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Seems like you were correct: somehow my `org.pantheon.terminal.settings font` setting reset itself to an empty string. Sorry.

**Comment by mcornella** [comment]
Ok thanks. @rezk2ll did you solve your problem? Make sure the terminal emulator is set up to use one of the Powerline fonts.

**Comment by tulsyan** [comment]
Having the same problem, anyone found a solution?

**Comment by jabbink** [comment]
did you see my comment?

**Comment by Luceafarul** [comment]
Try set Hack 10 via dconf
![terminal-conf](https://user-images.githubusercontent.com/5311913/29770944-0ead5e3a-8bfa-11e7-81e8-cf48ea6facbd.png)

**Comment by rezk2ll** [comment]
yeah, last year I changed the font in dconf and it worked

![image](https://user-images.githubusercontent.com/6764881/29771384-5a4515fe-8beb-11e7-938e-8f6710b6cbf9.png)

**Comment by tulsyan** [comment]
For me, it was a silly mistake. Although I did install the powerline fonts, I didn't change the terminal font settings to switch to them. Once I changed that, It was working perfectly.

**Comment by mtsmfca** [comment]
Thanks a million! I looked all over the world for this solution. Man, oh, it helped!

**Comment by danmtripp** [comment]
Thanks this helped immensely.  It was working yesterday.  Not working this morning.  The only thing I can think of was that I installed gnome-terminal.  I didn't have to configure pantheon-terminal to use powerline with oh-my-zsh, it just worked, then stopped,  powerline fonts displayed correctly in gnome-terminal.  Checked dconf-editor - and the font string is empty for pantheon terminal!  Ran "fc-list" to see my fonts, set pantheon-terminal to "Roboto Mono" and voila it's all working again!

**Comment by SevanMelemedjian** [comment]
I had the problem using tilix terminal and the default gnome terminal on Ubuntu 19.04, with oh-my-zsh and zsh installed, and playing with the locales did not help. Powerline was not installed, so I installed it with :
`apt install powerline`
I then rebooted and it solved the problem ! Hope this helps.

**Comment by Matthias29483** [comment]
This same problem happened to me after I updated my OS. 
Neither locales nor the "apt install" did anything so I was pretty bummed.

After about a hour of trying various things I finally managed to fix it:
First you can verify which font your Terminal currently uses:
`gsettings get org.gnome.desktop.interface monospace-font-name`
For me this returned: `'Roboto Mono 10'`
So I just set it to the appropriate Powerline Font:
`gsettings set org.gnome.desktop.interface monospace-font-name 'Roboto Mono for Powerline 10'`
Which ultimately fixed the problem.

Hope this helps anyone dealing with similar problems!
