### ISSUE TITLE
consider using xdg base home path for composer

### ISSUE THREAD

**Issue by glumanda99** [robbyrussell/oh-my-zsh#4910]
According to https://getcomposer.org/doc/03-cli.md#composer-home:

> By default it points to C:\Users<user>\AppData\Roaming\Composer on Windows and /Users/\<user\>/.composer on OSX. On nix systems that follow the XDG Base Directory Specifications, it points to $XDG_CONFIG_HOME/composer. On other nix systems, it points to /home/\<user\>/.composer.

The `php-composer` package on Arch is pointing to the former than the latter.

**Comment by mcornella** [comment]
The composer plugin doesn't concern itself with any installation path, it uses the output of `composer global config bin-dir`, which depends on how the user installed composer.
