### ISSUE TITLE
Gnu screen + Oh my zsh + French Accents not getting along

### ISSUE THREAD

**Issue by rubalo** [robbyrussell/oh-my-zsh#4911]
Hi,

We I launch screen and I'm in a folder with accents i.e ~/Téléchargement, screen tab that displays the $(pwd) cannot refresh as it doesn't process the accents correctly. 

I address it by modifying the following file : oh-my-zsh/lib/termsupport.zsh
`title $ZSH_THEME_TERM_TAB_TITLE_IDLE $ZSH_THEME_TERM_TITLE_IDLE`
with
`title $ZSH_THEME_TERM_TAB_TITLE_IDLE $ZSH_THEME_TERM_TITLE_IDLE | iconv -f utf8 -t ascii//TRANSLIT`

I not sure it's an issue and there should be definitly a better way to do it. 

Just wanted to let you know...

Cheers...

**Comment by mcornella** [comment]
I know this is old but I can't reproduce this. Which terminal emulator are you using?

**Comment by rubalo** [comment]
Ah ah ah hello, I can't remember as it was quite a long time. But I believe it was Gnome terminal. I can surely be closed if there were no other report of this bug ever since.

**Comment by mcornella** [comment]
I did try it with GNOME Terminal. If you can reproduce this again reopen it.
