### ISSUE TITLE
change URLencoding method to use %20 instead of + for spaces?

### ISSUE THREAD

**Issue by p0fi** [robbyrussell/oh-my-zsh#4915]
Is there a way to change the behavior of urltools to use %20 instead of + for spaces?

**Comment by mcornella** [comment]
You can use the bundled [`omz_urlencode` function](https://github.com/robbyrussell/oh-my-zsh/blob/83cf8dc16f51babbb0193c5b97e568739c1f40de/lib/functions.zsh#L122-L129) which provides the `-P` option to encode spaces as '%20'.

Perhaps we should combine the `urltools` plugin with the core functions?
