### ISSUE TITLE
I want record history only once，how to achieve this?

### ISSUE THREAD

**Issue by ufosky** [robbyrussell/oh-my-zsh#4922]
The case,assume this is the history list:
```sh
a
b
c
```
Now I enter `b`, the list should be:
```sh
a
c
b
```
It just swipe out many repeated items in the history list.

**Comment by mcornella** [comment]
You want to use the [`hist_ignore_all_dups` option](http://zsh.sourceforge.net/Doc/Release/Options.html#index-HISTIGNOREALLDUPS).
Just put `setopt hist_ignore_all_dups` in your zshrc file and you're all set!

Note that this can be confusing if you're trying to understand the sequence of commands you ran by the commands in your history.
