### ISSUE TITLE
Github plugin causes "(eval):1: parse error near `then'" on startup

### ISSUE THREAD

**Issue by amcameron** [robbyrussell/oh-my-zsh#4927]
Using this as my .zshrc:
```zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="robbyrussell"
plugins=(github)
source $ZSH/oh-my-zsh.sh
```

I receive the following error message each time I start zsh:
```
(eval):1: parse error near `then'
```

Using the following .zshrc instead results in no error message:
```zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="robbyrussell"
plugins=()
source $ZSH/oh-my-zsh.sh
```

My current checkout of Oh My Zsh is 83cf8dc (currently the most recent available).

**Comment by mcornella** [comment]
That's probably coming from the [`_hub` completion file](https://github.com/robbyrussell/oh-my-zsh/blob/83cf8dc16f51babbb0193c5b97e568739c1f40de/plugins/github/_hub#L105). This is the same version over at [github/hub](https://github.com/github/hub), so the bug may not be coming from OMZ itself. 

Please follow [these instructions](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#other-problems) to generate a debug file (with the github plugin enabled) so I can better diagnose where the error comes from.

**Comment by amcameron** [comment]
[Done.](https://gist.github.com/anonymous/209439587591ef48a42a)

[Direct link to parse error.](https://gist.github.com/anonymous/209439587591ef48a42a#file-omz-debug-log-L4361)

**Comment by mcornella** [comment]
Relevant part:
```zsh
if [ "$commands[(I)hub]" ]; then
  if hub --version &>/dev/null; then
    eval $(hub alias -s zsh)
  fi
fi
+/home/andrew/.oh-my-zsh/plugins/github/github.plugin.zsh:2> [ hub ']'
+/home/andrew/.oh-my-zsh/plugins/github/github.plugin.zsh:3> hub --version
+/home/andrew/.oh-my-zsh/plugins/github/github.plugin.zsh:4> hub alias -s zsh
+/home/andrew/.oh-my-zsh/plugins/github/github.plugin.zsh:4> eval alias 'git=hub' if type compdef '>/dev/null;' then compdef 'hub=git' fi
(eval):1: parse error near `then'
```

That is coming from the `hub` command itself, then. On my system, `hub alias -s zsh` just outputs `alias git=hub`. What `hub --version` are you using?
