### ISSUE TITLE
Load additional plugins specified in another file

### ISSUE THREAD

**Issue by tamasgal** [robbyrussell/oh-my-zsh#4929]
The standard way to load plugins is of course setting `plugins=(...)` in the `.zshrc`. However, since I work with many different kind of systems (from Mac, over NetBSD to Linux), and some of the plugins are system specific, I'd like to have some additional plugin definitions in a separate file. I use `.zshrc` for the common stuff, which is of course in my "dot files" repository, and there is a `.zshrc_local` which holds machine specific configuration (environment settings, custom aliases etc.), so I can simply modify that for each system without interfering with the common rc file.

Now my question: what would be the easiest way to have some additional plugins activated in that second file?
Adding another `plugins=(osx brew)` for course will not trigger the load of the plugins. But sourcing `source $ZSH/oh-my-zsh.sh` seems also an overkill (that's what I do now)?

**Comment by mcornella** [comment]
This is a difficult one. I suggest sourcing the `.zshrc_local` file from within your main `.zshrc` file, and modifying the `plugins` array in your `.zshrc_local` file. 

That would require that you source the local file before sourcing `oh-my-zsh.sh`, so if you have custom aliases and stuff in there they might get overwritten by OMZ. If you post a sample `.zshrc_local` file I can give you more specific instructions.
