### ISSUE TITLE
no autocompletion for --autosquash on git rebase

### ISSUE THREAD

**Issue by Shir0kamii** [robbyrussell/oh-my-zsh#4930]
Hi,

I noticed that when I type `git rebase --auto[TAB]`, OMZ only suggests me `autostash` while I was searching for `autosquash`.

I tried on two different installations so I think it's just missing but I didn't found where the autocompletion code is located.

I really want to improve this oh-my-zsh since I use it everyday, so I can help fix it if needed.

**Comment by mcornella** [comment]
It seems that's only available if the `--interactive` flag is already there. See the [default git completion shipped within zsh](https://github.com/zsh-users/zsh/blob/5deb57714fc799918552b22f077cc4b1daf1f68f/Completion/Unix/Command/_git#L1318-L1322) and the [man page for the `git-rebase` command](https://www.kernel.org/pub/software/scm/git/docs/git-rebase.html), that says on the `--autosquash` flag description (a quick `CTRL`+`F` to find it):

> This option is only valid when the `--interactive` option is used.

So you have to have either `-i` or `--interactive` on that command line before autocompletion of `autosquash` is available. Hope this helps!

**Comment by Shir0kamii** [comment]
Thank you for the fast reply.

I was putting the `--interactive` flag later on the command line, that's why I couldn't see it.

**Comment by smmoosavi** [comment]
but only with `--interactive` option work.
`git rebase -i --auto[TAB]` not working
`git rebase --interactive --auto[TAB]` wokring

also I have some other problem with autocompletion. eg. `git commit --amend --no-[TAB]` never say `--no-edit`
