### ISSUE TITLE
Gallois theme: git_custol_status:3

### ISSUE THREAD

**Issue by AClavijo** [robbyrussell/oh-my-zsh#4931]
Hi,

In a git project, with the "gallois" theme, i've got always the same sentence:

`git_custom_status:3: command not found: work_in_progress `
When i changed the theme, i don't have this error anymore

**Comment by mcornella** [comment]
The gallois theme [depends on the git plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/gallois.zsh-theme#L1) for the `work_in_progress()` function. Do you have it enabled?

**Comment by AClavijo** [comment]
Hi, 
Yes, with the git plugin enabled.

**Comment by mcornella** [comment]
Then there's something weird going on, because the `work_in_progress()` function [is properly defined](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L30).

Please post your zshrc file so I can take a look.

**Comment by AClavijo** [comment]
I changed the theme to avoid this. But in attachment my file.
[zshrc.txt](https://github.com/robbyrussell/oh-my-zsh/files/179992/zshrc.txt)

**Comment by mcornella** [comment]
Ok, the fault is in the syntax you use. zsh array values are separated by a space. The commas make it look for the `git,` plugin, `symfony2,` plugin, etc. 

```
plugins=(git, symfony2, docker)
```

It should be:

```
plugins=(git symfony2 docker)
```

**Comment by AClavijo** [comment]
Ok it's my fault it's working now. Thank's @mcornella =)

**Comment by mcornella** [comment]
No problem, nobody is born knowing 😉
—
Marc
