### ISSUE TITLE
Certificate error when installing via wget

### ISSUE THREAD

**Issue by MichaelBaydoun** [robbyrussell/oh-my-zsh#4933]
Difference between raw.github.com and www.github.com

➜  gitrepos git:(master) ✗ sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
--2016-03-19 11:04:27--  https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
Resolving raw.github.com... 23.235.44.133
Connecting to raw.github.com|23.235.44.133|:443... connected.
ERROR: cannot verify raw.github.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `www.github.com' doesn't match requested host name `raw.github.com'.
To connect to raw.github.com insecurely, use `--no-check-certificate'.

**Comment by mcornella** [comment]
Try `sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"` instead. I've updated the README file.
