### ISSUE TITLE
Wrong `bundle install` alias in Bundler plugin

### ISSUE THREAD

**Issue by matiasgagliano** [robbyrussell/oh-my-zsh#4936]
The [`bundle_install`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/bundler/bundler.plugin.zsh#L55) function checks Bundler's version to determine if parallel workers are available or not but the condition used doesn't work well with [semantic versioning](http://semver.org).

The condition in question is `[[ $bundler_version > '1.4.0' || $bundler_version = '1.4.0' ]]` and it will treat '1.11.0' as being before '1.4.0' for example.

Also, it will be better to check workers support just once and set the alias accordingly instead of making the alias check Bundler's version in each call. Something like:

``` sh
if [[ $workers_supported ]]; then
  alias bi="bundle install --jobs=$(get_number_of_available_processing_units)"
else 
  alias bi="bundle install"
fi
```

**Comment by robbyrussell** [comment]
@matiasgagliano is this something you can submit a PR for?
