### ISSUE TITLE
asdf: Extendable version manager

### ISSUE THREAD

**Issue by RobLoach** [robbyrussell/oh-my-zsh#4942]
Add a plugin for https://github.com/asdf-vm/asdf . Allows handling installations of node, ruby, lua, and more.

**Comment by mcornella** [comment]
First things first, we should have a basic need for a plugin. Right now the only thing I can see is a pretty slim completion file. Do you have some other functionality in mind?

Secondly, we should get a few users wanting that. If not, it's not really worth it dedicating another plugin in the core repo. You can always put the completion file in a custom plugin and use it yourself. If you later find there's something to add to the OMZ repository I'll gladly consider adding the plugin.

Thanks!
