### ISSUE TITLE
extract plugin: deb fails if content is xz compressed

### ISSUE THREAD

**Issue by rck** [robbyrussell/oh-my-zsh#4946]
Recent deb files contain archives xz compressed (e.g., data.tar.xz instead of data.tar.gz). extract always tries to extract a tar.gz and fails. Some fallback code for tar.xz would be needed.

**Comment by mcornella** [comment]
Can you provide a sample deb file so I can test it out?

**Comment by rck** [comment]
http://ftp.us.debian.org/debian/pool/main/c/cowsay/cowsay_3.03+dfsg1-10_all.deb

**Comment by mcornella** [comment]
Fixed in #5476. Please test and +1 that if it works.
