### ISSUE TITLE
Strange characters in some themes (Linux OS)

### ISSUE THREAD

**Issue by mauricioklein** [robbyrussell/oh-my-zsh#4947]
I'm facing some problems with some themes.
Some characters can't be displayed and, so, a strange char appears in every new section.

The SS below shows the problem with _af-magic_ theme, but the same occurs with many other themes.

![issue](https://cloud.githubusercontent.com/assets/11538662/14062911/9fa62624-f38f-11e5-827e-0d1844f67b2c.png)

LANG was already set to UTF-8 at _~/.zshrc_

It seems to be a problem at PROMPT, as you can see in the image above, but I couldn't figure out where this character is coming from.

Thanks in advance for the attention so far, and feel free to ask for further information.

**Comment by mauricioklein** [comment]
Just to give more information:

It seems that this character are coming directly from theme file, as show below:

![af-magic](https://cloud.githubusercontent.com/assets/11538662/14062956/8d1f1450-f391-11e5-9fe5-c032de2a7a48.png)

Here are the last commits to this theme:

![af-magic-commits](https://cloud.githubusercontent.com/assets/11538662/14062958/b0434564-f391-11e5-96fd-8bd7dce86880.png)

However, since this kind of problem occurs in many themes, I suspect the theme is OK, the problem is in my host.

Thanks!

**Comment by atilacamurca** [comment]
I have a similar issue and it's because I was using a Font that hasn't some characters used by themes. I install a Font compatible with Powerline and now it works great.

You can install one (or more if you like) of those Fonts <https://github.com/powerline/fonts>

**Comment by jscappini** [comment]
You should also check the Private Use Area for the font you are using, with an application like Character Map (run "gucharmap" and then search for the character "E000"). There you can see if the font you are using is causing a conflict with another font (that is what used to happen to me).
