### ISSUE TITLE
Git plugin auto-complete errors

### ISSUE THREAD

**Issue by piraveen** [robbyrussell/oh-my-zsh#4950]
Git auto completion causes error:

gco
```
_call_function:22: _git-checkout: function definition file not found
```

gba
```
_call_function:22: _git-branch: function definition file not found
```

any git commands with auto complete fails with `function definition file not found`

**Comment by piraveen** [comment]
Seems to fixed now.

**Comment by jorgeorpinel** [comment]
I'm having this same problem with any `git` alias after I updated OMZ with `upgrade_oh_my_zsh`. Other plugins seem to be OK

**Comment by mcfullard** [comment]
This issue has started happening for me after the latest update
