### ISSUE TITLE
scp autocomplete feature not working with zsh on the remote system

### ISSUE THREAD

**Issue by kunal394** [robbyrussell/oh-my-zsh#4952]
I tried to use autocomplete feature of scp, but its not working if I have zsh on the remote system as well. When I change the remote system to bash again, it works. All of the above observations are when I have zsh on my system and yes I have password-less ssh setup with the remote server. 
Please mention any screenshot or any other system info if required.

**Comment by mcornella** [comment]
What does `scp` autocomplete exactly, remote files and directories? You can use [`asciinema`](https://asciinema.org/) to make a screencast of both the working completion with bash and the non-working completion with zsh. 

Either way, this is probably not an Oh My Zsh issue but an issue with the zsh completion of scp.
