### ISSUE TITLE
Installer assumes zsh is not installed if it's not in /etc/shells

### ISSUE THREAD

**Issue by ulf-f** [robbyrussell/oh-my-zsh#4955]
Hi,

I have zsh installed and used it already some time, but without oh-my-zsh. I would like to give it a try but ran into the error that the install.sh didn't recognize my already installed zsh?

```
[userX@hostX1]~% zsh --version
zsh 5.1.1 (x86_64-redhat-linux-gnu
[userX@hostX1]~% rpm -qa | grep zsh
zsh-5.1.1-4.fc23.x86_64
[userX@hostX1]~% echo $SHELL
/bin/zsh
[userX@hostX1]~% cat /etc/redhat-release
Fedora release 23 (Twenty Three)
[userX@hostX1]~% sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
**Zsh is not installed! Please install zsh first!**
[userX@hostX1]~% 
```

Could you give me a hint what's wrong? It's nothing special on my zsh or on my Fedora 23 setup.

Thanks,

regards,
ulf

**Comment by jncornett** [comment]
If you do `cat /etc/shells`, do you see the path to zsh?

**Comment by mcornella** [comment]
@ulf-f as @jncornett indicates, the installer checks the `/etc/shells` file to see if zsh is in there. If not, the installer erroneously says that it is not installed. What is weird though is that `$SHELL` is zsh...

Please run the following and paste the output so I can get a sense of your system:
```zsh
# This will output the default shell of your user
getent passwd $USER | cut -d ':' -f 7
# This will show what shells are available to be used
cat /etc/shells
```

**Comment by ulf-f** [comment]
Hi, thanks for fast reply.

my user has as default shell zsh:
[userX@hostX1]~% getent passwd $USER | cut -d ':' -f 7
/bin/zsh
[userX@hostX1]~% cat /etc/shells
/bin/sh
/bin/bash
/sbin/nologin
/usr/bin/sh
/usr/bin/bash
/usr/sbin/nologin
/bin/dash
[userX@hostX1]~% 

but zsh is not in /etc/shells? I did not remove it. Strange?

regards,
ulf

**Comment by mcornella** [comment]
That is indeed weird. But the installer should be smarter than that, I'm currently working on a better version that takes into account all these possibilites. In the meantime, you can edit the `/etc/shells` file as root, add a new line with `/bin/zsh` and rerun the installer.

**Comment by ulf-f** [comment]
Hi,
thanks, adding /bin/zsh and /usr/bin/zsh to /etc/shells works.
Maybe you could approve the check but issue "zsh --version" and parse the output and add a nice error message if that's not working or version dosen't fit. That would remove the manual check for zsh and the correct version from the install manual https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH.
Again, thanks for help, I'm a happy oh-my-zsh user now.
regards,
ulf

**Comment by mcornella** [comment]
> Maybe you could approve the check but issue "zsh --version" and parse the output and add a nice error message if that's not working or version dosen't fit.

My intention is to check if the `zsh` command exists to see if zsh is installed, instead of how it's done now that it checks the `/etc/shells` file. Thanks

**Comment by bobbypriambodo** [comment]
@mcornella May I ask how is the progress on this? I'm having this issue on a machine where I have no root access (had to build zsh from source), hence modifying /etc/shells is out of the question. Would be great if it only detects via the `zsh` command.

**Comment by SimpleJian** [comment]
if "zsh --version" works properly, but you still get "Zsh not installed", you can download the install.sh file and change the zsh check condition in it, then it should work.

**Comment by alarsyo** [comment]
Just to add another reason to not use this `/etc/shells` check, distros with stateless defaults will not have a `/etc/shells` file.

(I'm using Solus which doesn't have one, and Clear Linux doesn't either)

The Solus developer Ikey proposed `which zsh` or `grep -E ^"${USER}:" /etc/passwd|cut -d : -f 7` as a replacement, but I guess just checking the output of `zsh` works as well.

**Comment by v0idst4r** [comment]
#6398 should fix this

**Comment by rey-grschel** [comment]
It appears to still be unresolved on the latest Solus version, and the latest ZSH version.

**Comment by JoshStrobl** [comment]
@rey-grschel Because @v0idst4r's PR hasn't landed yet.

**Comment by harryjubb** [comment]
Any movement on this? I am on a machine where I'm not permitted root access, can't edit `/etc/shells`. Have installed zsh with linuxbrew and added to `PATH`, but get `Zsh is not installed! Please install zsh first!`.

The default shell on this system is tcsh, I've set konsole to run `/bin/bash` instead, happy to then add running `zsh` in `.profile` to get from bash into zsh, which [AFAICT is the solution when you can't be root](https://unix.stackexchange.com/questions/136423/making-zsh-default-shell-without-root-access).

Noticed that #5931 in addition to #6398 are trying to fix this.

**Comment by v0idst4r** [comment]
Yeah I don't think they're ever going to get merged. You can in fact however use the raw version of my changes instead (or download the script yourself and modify it) at https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/283252158563af52f87fd52b15aaaffe029191e5/tools/install.sh

**Comment by harryjubb** [comment]
Thanks @v0idst4r, in the end I modified `install.sh` to remove the check and the `chsh` attempt.

Is this project now quite inactive? A bit worrying as a user: I know I really can't complain given it's free and open, and always thankful for everybody's work (loving OMZ!) but it's a shame if it languishes.

**Comment by iMichka** [comment]
> Thanks @v0idst4r, in the end I modified install.sh to remove the check and the chsh attempt.

Same here, had to edit the install script to get it working. I am one of the Linuxbrew core maintainers, and am interested to get this fixed, as the zsh we install will not allow to install oh-my-zsh.

If there is anything I can do to move this forward, please tell me. But it looks like there are already two pull requests open to fix this; so not sure I will be of any help, 90% of the work is already done :)

**Comment by Fibrasek** [comment]
Thanks @v0idst4r, your modifications works great!

(I am running Solus OS)

**Comment by mcornella** [comment]
This is fixed in the latest version (finally!).

**Comment by v0idst4r** [comment]
@ahangarha What's the output of "command -v zsh" and "which zsh"? Also I just wouldn't really use zsh on WSL at all, it has an annoying lag spike before printing the current directory. (I'm not sure if this was fixed in SCU)

**Comment by ahangarha** [comment]
@v0idst4r These are the results:
```
➜  ~ which zsh
/usr/bin/zsh
➜  ~ command -v zsh
/usr/bin/zsh
```
And also:
```
➜  ~ cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/dash
/bin/bash
/bin/rbash
/usr/bin/tmux
/usr/bin/screen
/bin/zsh
/usr/bin/zsh
```
I don't usually use Windows. But sometimes I am forced to and I don't want it stops me from doing things in right way. Yet, I had this problem on a CentOS machine as well. I will check it asap and will update you with that.

**Comment by PepRoll** [comment]
I have this problem on a Ubuntu 16.04

```
cat /etc/shells

/bin/sh
/bin/dash
/bin/bash
/bin/rbash
/bin/zsh
/usr/bin/zsh
/usr/bin/tmux
```

**Comment by mcornella** [comment]
The condition was wrong.

**Comment by agrublev** [comment]
So once I did 
```
sudo apt install zsh
```
then the install script worked :)
