### ISSUE TITLE
Small padding to window

### ISSUE THREAD

**Issue by silencesys** [robbyrussell/oh-my-zsh#4958]
Hi, I would like to ask you if there is any option how to add a padding to the window, so the text is not attacking the border?

**Comment by mcornella** [comment]
That is a feature that should be implemented by your terminal emulator. For instance, here's the instructions for adding padding in [Gnome Terminal 3.6.2](http://askubuntu.com/a/563190).
This will vary depending on the terminal emulator you're using.

Not directly related to OMZ so I'm closing this. Thanks!

**Comment by silencesys** [comment]
Ok, I'll look at my terminal settings. Thank you
