### ISSUE TITLE
problem updating Oh My Zsh

### ISSUE THREAD

**Issue by borrougagnou** [robbyrussell/oh-my-zsh#4974]
Hello,

I have a problem... in Root, I have no problem for install update oh my zsh but...
with non root mode oh my zsh not functionnal...

```
$ > upgrade_oh_my_zsh
Updating Oh My Zsh
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
There was an error updating. Try again later?
```
I use Agnoster theme.
What should I do?

**Comment by johnrazeur** [comment]
Did you modify any file except your .zshrc ?

**Comment by mcornella** [comment]
You must have modified some file in oh-my-zsh. Go to your oh-my-zsh folder and run:
```
git status
git diff 
```

**Comment by jondeaton** [comment]
Quick fix is to go `cd ~/.oh-my-zsh` and `git stash`, then retry `upgrade_oh_my_zsh`

**Comment by xargr** [comment]
@jondeaton it works for me thanks!!

**Comment by Eksapsy** [comment]
It was a change in the folder indeed.
If anyone wants **the changes to be back after the upgrade**, like in my case where I stored a Theme, all you have to do is:
```bash
cd ./.oh-my-zsh     # zsh Source Folder
git stash                # Stores all the changes you've made and reverses to the previous commit
upgrade_oh_my_zsh    # Updates the zsh client
git pop                   # Pops in the folder the previous changes you've made 
```

----------------
Although, I would suggest the themes to not be changed in the `zsh` folder. If not everyone, most people use a theme and it's somewhat impractical to do this process every time.
