### ISSUE TITLE
Git plugin auto-complete errors continue

### ISSUE THREAD

**Issue by jorgeorpinel** [robbyrussell/oh-my-zsh#4975]
Exactly the same as https://github.com/robbyrussell/oh-my-zsh/issues/4950 which @piraveen closed himself. In my case this is still happening even with the newest version of oh-my-zsh (just updated with `upgrade_oh_my_zsh`).

Any git alias e.g. `gco` or `gm` reports 
```sh
_call_function:22: _git-checkout: function definition file not found
_call_function:22: _git-checkout: function definition file not found
_call_function:22: _git-checkout: function definition file not found
```
(`_git-checkout` changing to which ever specific command is in use).

---

My env:
```sh
echo $ZSH_VERSION
5.0.8
```

**Comment by peterlupu** [comment]
I just ran `upgrade_oh_my_zsh`, running `5.0.8`:

```
zsh: command not found: parse_git_dirty
zsh: command not found: git_prompt_ahead
zsh: command not found: git_current_branch
zsh: command not found: git_prompt_short_sha
zsh: command not found: git_prompt_status
```

**Comment by mcornella** [comment]
@jorgeorpinel @peterlupu try deleting the completion cache file: `rm ~/.zcompdump*`

**Comment by peterlupu** [comment]
@mcornella 
```
> rm ~/.zcompdump*
zsh: command not found: parse_git_dirty
zsh: command not found: git_prompt_ahead
zsh: command not found: git_current_branch
zsh: command not found: git_prompt_short_sha
zsh: command not found: git_prompt_status
```

**Comment by mcornella** [comment]
(and restarting the terminal)

**Comment by peterlupu** [comment]
@mcornella that solved the issue, thank you; but now I'm getting:
`~/.oh-my-zsh/lib/git.zsh:42: parse error near `elif'`

```~/.oh-my-zsh $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean```

**Comment by mcornella** [comment]
That's a separate issue, probably caused by you having git's `core.autocrlf` set to something. See https://github.com/robbyrussell/oh-my-zsh/issues/4783#issuecomment-172520209 for a solution.

**Comment by peterlupu** [comment]
@mcornella  You were right!
I ran `git config --global core.autocrlf false` and it fixed the issue.
Thanks a bunch!

**Comment by jake-work** [comment]
Hi, am having the same issue however `git config --global core.autocrlf false` does not fix.
Also tried clearing ~/.gitconfig file also to no avail :(

**Comment by peterlupu** [comment]
@jake-work I ran these commands:
```
 git config --global core.autocrlf false
 mv ~/.oh-my-zsh ~/.oh-my-zsh-bak
 git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
 rm ~/.zcompdump*
```

Then restart your terminal. Hope it helps.

**Comment by jake-work** [comment]
re-clone worked a treat, thanks.
- fixed error "zsh: command not found: git_prompt_info"

**Comment by mmhan** [comment]
I believe this had something to do with `upgrade_oh_my_zsh` process. 

Even though it clone the latest update of .oh_my_zsh, it somehow didn't remove/overwrite some old files.

I went to `~/.oh_my_zsh` check dirty files and ran the following

```
git checkout lib/git.zsh
git checkout plugins/git/git.plugin.zsh
```

It solved the problem for me.

**Comment by jorgeorpinel** [comment]
@mcornella thanks, that fixed it for me so I'm closing this issue. Solution:

> ...deleting the completion cache file with `rm ~/.zcompdump*` (and restarting the terminal)
