### ISSUE TITLE
Auto-complete includes commands and directories

### ISSUE THREAD

**Issue by standingdreams** [robbyrussell/oh-my-zsh#4978]
Previously, when I would try to auto-complete to a directory, it would only list directories with the matching letters. Currently, it has been including commands that I'm not certain of. I haven't added any plugins or anything. 

Example: I type "pa" and hit tab. I'm trying to get to "patriot-capital-website". It will include the following:
![screen shot 2016-04-06 at 9 45 50 am](https://cloud.githubusercontent.com/assets/942959/14318753/6204f886-fbdc-11e5-8d76-8fcd41e9d0a1.png)

**Comment by mcornella** [comment]
I don't really know how to disable completion of variable names, but of directories can be disabled running `unsetopt cdablevars`.

**Comment by standingdreams** [comment]
The goal here is so that it only includes directories. Or at least have a flag so that commands can be hidden.

**Comment by mcornella** [comment]
That has never been possible, I think. If you're writing in a position where a command might be written, zsh will offer commands to complete. If you want to only have directories I'm afraid you're going to need to write `cd` before it.
