### ISSUE TITLE
How does it differ from ZIM?

### ISSUE THREAD

**Issue by elmerehbi** [robbyrussell/oh-my-zsh#4979]
I had installed ZIM a while ago and just discovered oh my zsh and installed it too.

How do they relate? They both seem to improve ZSH and Oh My ZSH seems more advanced.

**Comment by mcornella** [comment]
It seems zim is a derived version of zprezto, with a bigger focus on speed. Compared to OMZ is a faster framework but with less plugins. Take a look at both to see what's available on each one.

To be honest, I hadn't heard of zim before.
