### ISSUE TITLE
git-extras completion does not work [probably a documentation issue]

### ISSUE THREAD

**Issue by AlexCzar** [robbyrussell/oh-my-zsh#4982]
I have git-extras installed and the commands work, e.g. `git summary` prints the summary. `git-extras` plugin is enabled on oh-my-zsh but `git summ<TAB>` does not autocomplete, neither do other commands from `git-extras`. In the plugin notes there is a phrase:

> If you have both `zsh` and `git` installed, you need to make sure that the `zsh`-provided `_git` takes precedence.

I believe this is exactly my problem, unfortunately I could not find any way of ensuring the precedence. So I do not believe this is a bug on OMZ part, but instead—a documentation issue. The docs should either say how to _make sure_ or link to the relevant docs.

What I tried (without success):

```
$ rpm -q --filesbypkg git-core| grep comp

---
git-core                  /etc/bash_completion.d/git-prompt.sh
git-core                  /etc/bash_completion.d/git.sh
git-core                  /etc/zsh_completion.d
git-core                  /etc/zsh_completion.d/_git
git-core                  /usr/lib/git/mergetools/codecompare
git-core                  /usr/share/tcsh/git.complete

---
$ sudo rm  /etc/bash_completion.d/git-prompt.sh /etc/bash_completion.d/git.sh /etc/zsh_completion.d/_git
```

**Comment by mcornella** [comment]
Fixed in be65adc6c364e842307c7b4e8da30f0162b629f0
