### ISSUE TITLE
Last update completely broke oh-my-zsh

### ISSUE THREAD

**Issue by squarerootfury** [robbyrussell/oh-my-zsh#4987]
I've updated my oh-my-zsh installation today. Now it's completely broken.

I get `command not found: ^M` and `parse errors`. At least the first looks like a Line-Ending Issue?

Even a clean installation does not fixed the problem. Let me know if you need further informations!

I'm using zsh 5.1.1 (x86_64-ubuntu-linux-gnu).

**Comment by mcornella** [comment]
That's a known issue, see a temporary workaround at #4069.
