### ISSUE TITLE
Only default theme works

### ISSUE THREAD

**Issue by zhouhao27** [robbyrussell/oh-my-zsh#4996]
All themes don't work. Even the color of default theme seems not the same as your screenshot.

<img width="553" alt="2016-04-12 10 20 22" src="https://cloud.githubusercontent.com/assets/8099731/14463233/d5d9e2ba-00fc-11e6-94f2-d70701ff72cb.png">

I tried to install the fonts. Still not working. Any idea? Thanks.

**Comment by mcornella** [comment]
The colors of the theme can't be changed from OMZ, you have to apply whatever color scheme the theme uses to your terminal emulator. For example, `agnoster` uses [solarized dark](https://www.google.es/search?q=solarized+dark+terminal&hl=en)

**Comment by zhouhao27** [comment]
Not only the color. Here is my screenshot:

![screen shot 2016-04-13 at 4 27 29 pm](https://cloud.githubusercontent.com/assets/8099731/14487358/b107cd7e-0194-11e6-9101-a57cb6b3867f.png)

I installed the Powerline patched fonts.

**Comment by mcornella** [comment]
You have to also tell the terminal emulator to use one of the Powerline fonts. Anyhow, the powerline font issue is a recurring theme on OMZ, you might find the solution on one of the several issues posted here about this.
