### ISSUE TITLE
rbenv.plugin.zsh not working

### ISSUE THREAD

**Issue by ifyouseewendy** [robbyrussell/oh-my-zsh#4998]
I'm using homebrew to install rbenv (1.0.0), and want to use rbenv.plugin.zsh to enable ruby version display in zsh.

While fixing my issues, I've found two places to modify the current [rbenv.plugin.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/rbenv/rbenv.plugin.zsh).

_Issue 1_

``` zsh
rbenvdirs=("$HOME/.rbenv" "/usr/local/rbenv" "/opt/rbenv" "/usr/local/opt/rbenv")
if _homebrew-installed && rbenv_homebrew_path=$(brew --prefix rbenv 2>/dev/null); then
    rbenvdirs=($rbenv_homebrew_path "${rbenvdirs[@]}")
    unset rbenv_homebrew_path
fi
```

This section puts `rbenv_homebrew_path` in front of `$HOME/.rbenv`. It may work in previous version, but I've used homebrew to install rbenv, and rubies are installed under `$HOME/.rbenv`. So to make it work, I've comment out code in if section.

_Issue 2_

``` zsh
for rbenvdir in "${rbenvdirs[@]}" ; do
  if [ -d $rbenvdir/bin -a $FOUND_RBENV -eq 0 ] ; then
    FOUND_RBENV=1
    if [[ $RBENV_ROOT = '' ]]; then
      RBENV_ROOT=$rbenvdir
    fi
    export RBENV_ROOT
    export PATH=${rbenvdir}/bin:$PATH
    eval "$(rbenv init --no-rehash - zsh)"

    ...
```

This section is finding rubies under `${rbenvdir}/bin` path, but rbenv has put all bins into `shims`. So to make it work, I've changed to `${rbenvdir}/shims`.

**Comment by brendon** [comment]
Yes definitely confusing. I ended up just removing it again.

**Comment by brendon** [comment]
Also See: https://github.com/robbyrussell/oh-my-zsh/issues/3093
