### ISSUE TITLE
Bug with cd command

### ISSUE THREAD

**Issue by VitorVRS** [robbyrussell/oh-my-zsh#5001]
Evertime i use "cd" command and the autocomplete feature, i got an wrong autocompletion.

**Actual behaviour:** (on Ubuntu 14.04)
$ cd /var
$ cd c<TAB>  (will show *cache* and *crash* suggestion)
$ cd co<TAB> (will suggest nothing)
$ cd colord<ENTER> (cd: file ou directory not found: colord)

**Actual behaviour:** 
$ cd /var
$ cd c<TAB>  (will show *cache* and *crash* suggestion)
$ cd co<TAB> (will autocomplete with *colord*)
$ cd colord<ENTER>
$ pwd (/var/lib/colord)

-- 
This is annoying :angry: 

Thanks.

**Comment by mcornella** [comment]
Can you try running `unsetopt cdablevars` to see if that fixes it?

**Comment by VitorVRS** [comment]
Thank you, this solve my problem.
Searching by cdablevar i found the same issue #2560.
Sorry for redundancy and thanks for your time.
