### ISSUE TITLE
In the installer, add a way to "not" launch zsh after finishing

### ISSUE THREAD

**Issue by luislobo** [robbyrussell/oh-my-zsh#5002]
In the installer, add a way to "not" launch zsh after finishing.

It could be an environment variable that is being checked or whatever way you find appropriate.

I have my own "install_ubuntu.sh" that, in the middle, invokes OMZ installer, and I have to type exit everytime I want my installer to continue.

One way would be to leave it to the end.. but the installer should not just "nest" a shell call if you don't want to...

**Comment by mcornella** [comment]
That's a very good use case, I think we can add a check to see if we're running interactively or not.

**Comment by luislobo** [comment]
that would be great, I guess that will benefit some other people using it the same way

**Comment by loket** [comment]
Does #5893 solve your problem?

**Comment by luislobo** [comment]
It should, but it didn't so far:

![virtualbox_u1704_24_04_2017_16_20_45](https://cloud.githubusercontent.com/assets/453120/25359276/2b844f76-290a-11e7-97e3-da688a3ce0b4.png)

The script is here https://raw.githubusercontent.com/luislobo/ubuntu-install-scripts/master/test.sh
Just tried it in a VirtualBox with Ubuntu 17.04.

**Comment by loket** [comment]
Ah, I see the problem.

Since the pull request hasn't been merged yet, the `--batch` argument won't be processed in the upstream installer. I updated by PR with better instructions.

Simply replace this line in your script:
`oh_my_zsh_url="https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"`
with
`oh_my_zsh_url="https://raw.githubusercontent.com/loket/oh-my-zsh/feature/batch-mode/tools/install.sh"`

This will use the installer from my pull request instead of the upstream one. The upstream oh-my-zsh will be installed as before (not my fork), so you should be able to safely use this script until the pull request has been merged.

Hope that works! 😄

**Comment by mcornella** [comment]
#5169 has added the option to disable that, either by setting the environment variable `RUNZSH=no` or passing the flag `--unattended`, which also skips the change of default shell. It has a bunch of other fixes, and it's now ready to test.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by mcornella** [comment]
Closed by #5169.

**Comment by vincentmader** [comment]
> #5169 has added the option to disable that, either by setting the environment variable `RUNZSH=no` or passing the flag `--unattended`, which also skips the change of default shell. It has a bunch of other fixes, and it's now ready to test.
> 
> If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.
> 
> Thanks!

Passing the flag "--unattended" to which command?

**Comment by mcornella** [comment]
To the installer command, see:
- https://github.com/ohmyzsh/ohmyzsh#unattended-install
- https://github.com/ohmyzsh/ohmyzsh/blob/ce9104c4f3d9ea424346d711f0653cd9e5d81303/tools/install.sh#L14-L36
