### ISSUE TITLE
Colorize plugin not working

### ISSUE THREAD

**Issue by JiffsMaverick** [robbyrussell/oh-my-zsh#5005]
I installed [Colorize plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/colorize).

`cat oh-my-zsh.sh` - not working

But

`pygmentize oh-my-zsh.sh` - working fine

Additional information:

```
% which pygmentize
/usr/bin/pygmentize
```

```
% dpkg -l G python-pygments
ii  python-pygments                               2.0.1+dfsg-1.1svn1.1                       all          syntax highlighting package written in Python
```

```
% dpkg -l G python
ii  python                                        2.7.9-1                                    amd64        interactive high-level object-oriented language (default version)
```

```
cat .zshrc G plugins=
plugins=(colorize)
```

**Comment by MT--** [comment]
+1 exact same issue

**Comment by ArtemMedvedev** [comment]
faced with the same problem

**Comment by ArtemMedvedev** [comment]
I've solved it with similar python package.

Install [Pygments](http://pygments.org/) with `easy_install Pygments` or `pip install Pygments`

Then add alias to your ~/.zshrc, `alias cat="pygmentize -g"`

And after `source ~/.zshrc` you can colorize output with `cat gulpfile.babel.js`

**Comment by hkalia** [comment]
Use the command `colorize` instead.

For Example:
Instead of `cat oh-my-zsh.sh`
try `colorize oh-my-zsh.sh`

**Comment by blurm** [comment]
same here

@hkalia Could't found the `colorize` command, does it need to install seperatlly?

**Comment by mcornella** [comment]
You have to add `colorize` to the plugins array in your zshrc file.

**Comment by E3D3** [comment]
Same problem here.
I activated the colorize plugin in my .zshrc and installed the (not documented) requirements python-pygments (for python2 & -3) and pigmentize. The colorize-command still kept complaining about a missing 'pigmentize', although 'which pigmentize' showed an installed executable.
I solved it by, like suggested by **artdevjs**, adding an alias to my .zshrc
`alias cat="pygmentize -g"`
and deactivated the now not needed colorize-plugin.

**Comment by arechta911** [comment]
I left the solution that I found here, its simple fix:
Open `$ nano ~/.oh-my-zsh/plugins/colorize/colorize.plugin.zsh`

find and replace below script (line 6):
` if ! (( $+commands[pygmentize] )); then`
`⠀echo "package 'Pygments' is not installed!"`
`⠀return 1`
`fi`

to this:
` command -v pygmentize >/dev/null 2>&1 || { echo >&2 "package 'Pygments' is not installed!"; return 1; }`

it should works, here the screenshot:
![Tangkapan Layar Deepin_urxvt_20190918220339](https://user-images.githubusercontent.com/36139976/65161143-3a852d00-da61-11e9-901a-3254174a4d2a.png)
