### ISSUE TITLE
Add plugin expand-aliases

### ISSUE THREAD

**Issue by jarmo** [robbyrussell/oh-my-zsh#5007]
I've created a plugin **expand-aliases**, which does what it says :) More information in the [README](https://github.com/jarmo/expand-aliases-oh-my-zsh/blob/master/README.md).

Since I'm not sure how should I do a pull request for a plugin, then I've made a separate repo here:
https://github.com/jarmo/expand-aliases-oh-my-zsh

**Comment by sontags** [comment]
Yes Please!

**Comment by mcornella** [comment]
Closing as per https://github.com/robbyrussell/oh-my-zsh/pull/5597#issuecomment-257819411.
