### ISSUE TITLE
zsh-navigation-tool shadows script arguments

### ISSUE THREAD

**Issue by doubleloop** [robbyrussell/oh-my-zsh#5014]
@psprint 
I love zsh-navigation-tool plugin. Still one problem I found is that when I enable it, there is problem with scripts witch are testing input arguments. For example we are using script to setup env variables witch starts for example like this:
```bash
if [ -z "$1" ]; then tenant="admin" ; else tenant=$1 ; fi
if [ -z "$2" ]; then user="admin" ; else user=$2 ; fi
export OS_USERNAME=$user
export OS_TENANT_NAME=$tenant
```
And it does not work as expected as when I execute it with no arguments OS_USERNAME is not equal to admin as expected. When I run a file:
```bash
# test.sh
echo $1 $2 $3 $4 $5 $6 $7 $8 $9
```
with:
```
$ . test.sh
```
i get:
```
n-aliases.conf n-env.conf n-history.conf n-list.conf n-panelize.conf n-cd.conf n-functions.conf n-kill.conf n-options.conf
```
Witch I guess are some internals of this plugin. Can you not use $1 $2 $3 $4 $5 $6 $7 $8 $9 for the plugin internals?

**Comment by psprint** [comment]
Hello. Thanks for the report. I've created fixing PR:

https://github.com/robbyrussell/oh-my-zsh/pull/5023

**Comment by mcornella** [comment]
@doubleloop when you have a moment test #5023 and I'll merge it if it works. Thanks!

**Comment by doubleloop** [comment]
@mcornella just tested, works for me. Thanks
