### ISSUE TITLE
Open File Error with the Sublime Plugin in tmux

### ISSUE THREAD

**Issue by greenchapter** [robbyrussell/oh-my-zsh#5015]
I would like to open a file with sublime-oh-my-zsh-plugin 'st' from a tmux shell.
Sublime opens but without the file and no content.

**Comment by apjanke** [comment]
Does this happen consistently? This might just be a Sublime Text issue: about 20% of the time, when I use the `subl` command to open a file in Sublime Text from the command line, it switches to Sublime Text, but no file is actually opened. Seems to happen particularly often when first opening Sublime Text.

Just try doing it again a few times and see if it works some of the time. If it does, it's probably a Sublime Text issue, and not the OMZ plugin for it.

**Comment by greenchapter** [comment]
I have the problem on two machines, every time when I will open an file with sublime the file complete empty.
So the problem still exists...

**Comment by mcornella** [comment]
Continuing thread on #5885
