### ISSUE TITLE
Don't use `which` during load

### ISSUE THREAD

**Issue by CyberShadow** [robbyrussell/oh-my-zsh#5024]
#3165 introduced an unconditional `which` invocation during startup. Unfortunately, under CygWin and with a long `PATH`, `which` can take a long time to execute (takes two seconds here), which slows down startup enough to be annoying.

Would it be possible to make it lazy / autoloaded somehow instead?

**Comment by mcornella** [comment]
You can try using the `$commands` variable which is built in into zsh. Here's an example of the necessary change, try it and let me know if it's better:

```diff
-if which ack-grep > /dev/null;
-then
+if (( $+commands[ack-grep] )); then
    alias afind='ack-grep -il'
```

If this works I'll make a PR.

**Comment by CyberShadow** [comment]
For no explainable reason I can no longer reproduce this.

Windows ¯\_(ツ)_/¯

Will reopen and test your patch if it happens again.

**Comment by mcornella** [comment]
Haha okay. It's a good practice using the `$commands` form, so I'll probably change it anyway.
