### ISSUE TITLE
Has the prompt in avit theme gone pink for anyone else?

### ISSUE THREAD

**Issue by sohrab-** [robbyrussell/oh-my-zsh#5030]
The prompt colour has changed from blue to pink since the latest update but I cannot see anything in the theme's source code that would have caused that.

![image](https://cloud.githubusercontent.com/assets/4444588/14699853/e7ee92dc-07de-11e6-8bea-dda7f90dd073.png)

Anyone else is having this issue? Any clues?

_This is not really threat to my masculinity but I liked the blue._

**Comment by wulfgarpro** [comment]
Roll back amongst these commits: https://github.com/robbyrussell/oh-my-zsh/commits/master/themes/avit.zsh-theme

**Comment by mcornella** [comment]
This might be due to the change to `$fg_bold[blue]` instead of `$fg[blue]`, see [diff](https://github.com/robbyrussell/oh-my-zsh/pull/4790/files#diff-312232e5a738e51aa9eee453a017fc89R11).
Try running `print -P "${fg[blue]}blue ${fg_bold[blue]}pink?"` to confirm.

**Comment by sohrab-** [comment]
Oh yes, that's the culprit:

![image](https://cloud.githubusercontent.com/assets/4444588/14816075/461e849a-0bf2-11e6-93aa-cd0cc2179a4a.png)

Pinkest blue I've ever seen.

**Comment by mcornella** [comment]
In my case I see it gray and I have the Solarized Dark color scheme. 
![captura de pantalla de 2016-04-26 13-06-58](https://cloud.githubusercontent.com/assets/1441704/14816220/da3d6d1e-0baf-11e6-85ed-886d3043870c.png)

You might want to look at yours, but anyways, that change shouldn't have gone through the merging process. I'll see if I can get it back to what it was before.

**Comment by sohrab-** [comment]
Thanks. I reverted that bit locally for now.

It's curious because I am running Solarized Dark as well. I do turn off bold fonts setting though because the kerning on the bold font is all over the place.

**Comment by mcornella** [comment]
> It's curious because I am running Solarized Dark as well

It's also dependent on the termcap database entry used (which depends on `$TERM`) and possibly the terminal emulator.
