### ISSUE TITLE
Terminal title misbehaves with putty and tmux

### ISSUE THREAD

**Issue by enko** [robbyrussell/oh-my-zsh#5034]
Hi folks,

I dont know who is exactly the culprit here, but when running oh-my-zsh inside a tmux inside a putty, the terminal title displays some dubious characters, have a look at the screenshot:

![2016-04-22 09_31_51-0_9_ - _ _zsh_](https://cloud.githubusercontent.com/assets/19407/14734855/8bf69bfc-086d-11e6-9e43-8545ab1eb084.png)

If I run the zsh session with tmux the title is displayed without the additional characters.

I'm activating the titles in tmux with „set -g set-titles on“.

**Comment by sparr** [comment]
Can you elaborate on which of the characters are dubious vs expected?

**Comment by enko** [comment]
![2016-04-25 09_32_55-0_11_ - _ _zsh_](https://cloud.githubusercontent.com/assets/19407/14776815/25e3f644-0ac9-11e6-868d-72991948be28.png)

Upper is without tmux and bottom is within a tmux session. I would expect the same inside the tmux session as it is outside of tmux.

**Comment by fcrozat** [comment]
By default, tmux doesn't set the title to the pane title. You need to configure that with `set -g set-titles-string "#{pane_title}"`
More about this on #3579
