### ISSUE TITLE
Create file with '>' freeze terminal

### ISSUE THREAD

**Issue by danilopinotti** [robbyrussell/oh-my-zsh#5046]
Hello,
when i try to create a file using '>', the command freeze and need to press Ctrl C.

Example:
```bash
$ > file.txt
```

In a native terminal emulator works.
">" is faster to create files that use the touch command

**Comment by moore3071** [comment]
It looks like to me that this is a problem with zsh itself, and not oh-my-zsh.

**Comment by moore3071** [comment]
From a zsh-contributor,

> What you see is not a bug, it is a feature. Configurable feature:
> 
>     $ zsh -f
>     % emulate bash
>     % > file
> 
> does exactly what you request. See `man zshmisc`, section REDIRECTIONS WITH NO COMMAND.

**Comment by mcornella** [comment]
A faster solution is setting up the `sh_nullcmd` option using `setopt sh_nullcmd`. You can find more info about it at [Redirections with no command](http://zsh.sourceforge.net/Doc/Release/Redirection.html#Redirections-with-no-command).
