### ISSUE TITLE
mvn-color seems to swallow prompts for input

### ISSUE THREAD

**Issue by cmsimike** [robbyrussell/oh-my-zsh#5052]
Hi,

When using mvn-color vs just regular mvn, any prompts by maven end up getting swallowed, making it seem like mvn locked up.  For example:

mvn-color archetype:generate should have as the las line:
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): 771:

mvn archetype:generate 
correctly shows the prompt.

This is not limited to just generating an archetype, but in any instance where maven asks for input.

**Comment by mcornella** [comment]
I'll add this to the plugin's README, but I don't think we'll fix it (unless someone wants to get a shot at it) because Maven 3.5.0 was released with color support in April 2017.
