### ISSUE TITLE
install.sh tries to git clone outisde of my home dir.

### ISSUE THREAD

**Issue by bibek22** [robbyrussell/oh-my-zsh#5059]
So, i am the user 'bibek' on my machine but '/home/bibek/' is not mine. But '/home/bibek22' is. When i try to install oh-my-zsh with the install script, it tries to create dir in /home/bibek and fails as I don't have permission there.

tried to look into the script, couldn't find anything. $USER is "bibek" $HOME is "/home/bibek22"

**Comment by mcornella** [comment]
I can't reproduce this. The installer script uses `~` to refer to `$HOME`, perhaps there's some edge case where it doesn't work correctly. What does `print -P ~` output?

**Comment by bibek22** [comment]
hey, i forgot to update this sooner. so, the issue was due most likely due to the config files I copied over from other machine where i owned '/home/bibek/' and had omz installed. It set some variables that installer script uses. i removed the configs entirely and relogin, and then was able to install omz.  
Thanks. closing.
