### ISSUE TITLE
zsh-navigation-tools: configuration in zshrc

### ISSUE THREAD

**Issue by doubleloop** [robbyrussell/oh-my-zsh#5064]
zsh-navigation-tools is using internal config files copied to ~/.config/znt/, and I do not see the way to propagate configuration from zshrc.. It would be awesome if such flags like NLIST_INSTANT_SELECT (https://github.com/psprint/zsh-navigation-tools/issues/14#issuecomment-213288800) could be set in zshrc (so all custom configuration is in one place and easy to deploy/share).

**Comment by mcornella** [comment]
You have to file that on [psprint/zsh-navigation-tools](https://github.com/psprint/zsh-navigation-tools).
