### ISSUE TITLE
XCode plugin delete derived data bug

### ISSUE THREAD

**Issue by maxandron** [robbyrussell/oh-my-zsh#5065]
The function does not work because rm is supplied the option -r instead of -R.
The way it works now, directories are not deleted from inside the folder.

Would like to fix it with permission

**Comment by mcornella** [comment]
You mean this?
```
alias xcdd='rm -rf ~/Library/Developer/Xcode/DerivedData/*'
```

`rm -rf` deletes everything, `-R` is the same as `-r`. From the manpage:
```
       -r, -R, --recursive
              remove directories and their contents recursively
```

You should double-check that there's nothing else going on. Perhaps Xcode is open when doing this so it is recreated? I don't use MacOS so I can't know for sure.
