### ISSUE TITLE
Allow removing binding to Alt-L

### ISSUE THREAD

**Issue by sumitsahrawat** [robbyrussell/oh-my-zsh#5071]
I'm very fond of using the Alt-L keys to lowercase a word, like it works by default. I couldn't find a way to get the old behaviour.

**Comment by moore3071** [comment]
Where does this work by default? It does not seem to work by default in a clean zsh, but it does however work in bash (which I assume is what shell it worked in for you beforehand).

**Comment by mcornella** [comment]
This is due to `ESC`+`L` bindkey at [`lib/key-bindings.zsh@L21`](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh#L21), which is─accidentally─the same keyboard sequence as `ALT`+`L`.

On a clean zsh (`zsh -f`) the key binding runs `down-case-word`, here's the command you can run to use that by default:
```
bindkey '^[l' down-case-word
```

**Comment by mcornella** [comment]
@moore3071 here's a demo of how this works: https://asciinema.org/a/6oz7ljc51uc9l1jwwjvws1k80

**Comment by sumitsahrawat** [comment]
Cool :+1:

**Comment by sumitsahrawat** [comment]
@mcornella I came up with this, which runs `zle down-case-word` when run on a non-empty line, and `ls` otherwise.

```zsh
#! /usr/bin/env zsh

function _magic-alt-l () {
    if [[ -z "$BUFFER" ]]; then
        echo ls
        ls
        zle send-break
    else
        zle down-case-word
    fi
}
zle -N _magic-alt-l

bindkey '\el' _magic-alt-l
```

The only minor issue I have with this is that it outputs an empty line after the `ls` output.

**Comment by mcornella** [comment]
The way I've found that works well is modifying `$BUFFER` and then running `zle accept-line`:
```zsh
if [[ -z "$BUFFER" ]]; then
    BUFFER="ls"
    zle accept-line
else
```

Though I'm trying to find one where it just runs `ls` below the prompt without cluttering the prompt. I'll see what I find.

**Comment by sumitsahrawat** [comment]
That's great, just what I was looking for. It even gives highlighting for the `ls` that ends up in the prompt.

Previously, I tried this, which didn't work.

```zsh
if [[ -z "$BUFFER" ]]; then
    BUFFER="ls" zle accept-line      # This doesn't work
else
```
