### ISSUE TITLE
temperature and cpu information

### ISSUE THREAD

**Issue by wiso** [robbyrussell/oh-my-zsh#5078]
I am a [liquidprompt](https://github.com/nojhan/liquidprompt) user. 

One feature I am missing in oh-my-sh is

 * temperature of the cpu 
 * cpu load

These quantities are displayed in the prompt when above a threshold

**Comment by mcornella** [comment]
You can use both ohmyzsh and that prompt theme using `antigen`. See https://github.com/nojhan/liquidprompt#installation-via-antigen
