### ISSUE TITLE
gunwip throws "error: -n requires an argument"

### ISSUE THREAD

**Issue by LM450N** [robbyrussell/oh-my-zsh#5079]
![image](https://cloud.githubusercontent.com/assets/2325091/15175791/4a9c069c-1768-11e6-801c-7d5f6e027eef.png)

The current alias is `gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'`

It should be `gunwip='git log -n1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'`

**Comment by mcornella** [comment]
What version of `git` do you have? In my setup both versions work correctly.

**Comment by LM450N** [comment]
I was using git 2.7.4. This morning I upgraded to git 2.8.2 and the issue is still here. I also use [scm_breeze](https://github.com/ndbroadbent/scm_breeze) and a colleague with a similar configuration has the same error.

_OSX EC 10.11.4, zsh 5.2 (x86_64-apple-darwin15.0.0)_

**Comment by mcornella** [comment]
Closing for duplicity. Discussion over at #5080.
