### ISSUE TITLE
"alias -g" not working

### ISSUE THREAD

**Issue by yeKcim** [robbyrussell/oh-my-zsh#5082]
I've added a custom/file.zsh everything works except:

alias -g G='| grep -vi '
alias -g L='| less'

the other aliases (without -g option) work fine.

```
$ grep ' -g' *.zsh 
file.zsh:alias -g G='| grep -vi '
file.zsh:alias -g L='| less'
```

```
$ alias | grep 'grep'
G='| grep -vi '
```

**Comment by mcornella** [comment]
The alias command returns both normal aliases and globals. If you do `alias -g` do you still see them?

**Comment by yeKcim** [comment]
Yes :
```
$ alias -g
...=../..
....=../../..
.....=../../../..
......=../../../../..
CA='2>&1 | cat -A'
G='| grep -vi '
H='| head'
L='| less'
LL='2>&1 | less'
M='| most'
NE='2> /dev/null'
NUL='> /dev/null 2>&1'
P='2>&1| pygmentize -l pytb'
T='| tail'
```

**Comment by mcornella** [comment]
Ok, so it *does* work. How are you using them?

**Comment by yeKcim** [comment]
```
$ alias | grep pol
Apol='apt-cache policy '
```

`$ alias G pol`
must return same line but return every aliases

**Comment by mcornella** [comment]
`alias G pol` is not the same as `alias | grep pol`, but `alias | grep -vi pol`. It's different. The `G` alias you defined inverts the match, so it only shows what doesn't match `pol`.

**Comment by yeKcim** [comment]
thank, sorry, my mistake.

**Comment by mcornella** [comment]
No harm no foul :wink:
