### ISSUE TITLE
Git add, git commit and git push in one command

### ISSUE THREAD

**Issue by christoga** [robbyrussell/oh-my-zsh#5086]
I'm thinking about a command that will easily add, commit and push.

**Comment by mcornella** [comment]
`git add -A && git commit && git push`

**Comment by christoga** [comment]
I mean one command dude, not tons of command.
I already know that command

**Comment by mcornella** [comment]
There's no single command on git that does this. You can either make it into a git alias (for example, git post), or make it into a zsh alias or function.
