### ISSUE TITLE
some hash commands are broken in latest upgrade

### ISSUE THREAD

**Issue by madwed** [robbyrussell/oh-my-zsh#5096]
I have zsh 5.0.8 from the latest update, which broke all of my hash commands.

Example:
`hash -d oz=~/.oh-my-zsh` does not work.

**Comment by mcornella** [comment]
This is a result of removing `setopt cdablevars` from the default ohmyzsh settings on ed484dfaf63c6d8789b2bd2e952a07bbbb9ad330, which was causing completion issues for lots of users. You can reenable it by setting it on your zshrc file.

**Comment by mcornella** [comment]
You can also use it putting the tilde (`~`) character before the variable, _i.e._ `cd ~oz`, without having to enable `cdablevars`.

**Comment by madwed** [comment]
ah thank you so much
