### ISSUE TITLE
ubuntu oh-my-zsh login remote ubuntu server via ssh cause encoding error

### ISSUE THREAD

**Issue by iampkuhz** [robbyrussell/oh-my-zsh#5102]
hi, i'm using zsh in my ubuntu laptop,
when i login to remote ubuntu server via ssh, the encoding seems not utf8
if i open a file via vim ,and exec `:set encoding` in vim, it shows `laten1`
if i exec `mvn --version` in remote server terminal , it does not show `UTF8` in platform encoding

however, if i switch to bash and login remote server, the encoding works well.

What's wrong with my zsh configure and how can i fix this?

**Comment by kapsh** [comment]
Can you post output of `locale` command from your server and client?

**Comment by iampkuhz** [comment]
`locale` in zsh:

    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE=en_US.UTF-8
    LC_NUMERIC=zh_CN.UTF-8
    LC_TIME=zh_CN.UTF-8
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY=zh_CN.UTF-8
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER=zh_CN.UTF-8
    LC_NAME=zh_CN.UTF-8
    LC_ADDRESS=zh_CN.UTF-8
    LC_TELEPHONE=zh_CN.UTF-8
    LC_MEASUREMENT=zh_CN.UTF-8
    LC_IDENTIFICATION=zh_CN.UTF-8
    LC_ALL=
    
`locale` in bash:

    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=en_US.UTF-8
    
`locale` in server (login through `bash`):

    LANG=en_US.UTF-8
    LANGUAGE=en_US:
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=en_US.UTF-8
    

`locale` in server (login through `zsh`):

    locale: Cannot set LC_ALL to default locale: No such file or directory
    LANG=en_US.UTF-8
    LANGUAGE=en_US:
    LC_CTYPE=en_US.UTF-8
    LC_NUMERIC=zh_CN.UTF-8
    LC_TIME=zh_CN.UTF-8
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY=zh_CN.UTF-8
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER=zh_CN.UTF-8
    LC_NAME=zh_CN.UTF-8
    LC_ADDRESS=zh_CN.UTF-8
    LC_TELEPHONE=zh_CN.UTF-8
    LC_MEASUREMENT=zh_CN.UTF-8
    LC_IDENTIFICATION=zh_CN.UTF-8
    LC_ALL=
    

encoding seems error. how can I solve this?

**Comment by kapsh** [comment]
Um, it seems like you have some locale settings for China on your laptop (ssh session uses client environment). If you didn't set up this by yourself, try this:

1. Run `locale -a | grep en_US`. 
2. (If you have `en_US.UTF-8` in output — skip this step):
Run `sudo locale-gen en_US.UTF-8`.  
3. Run `sudo dpkg-reconfigure locales` and choose en_US.UTF-8. 

Relogin or reboot may be required.

**Comment by iampkuhz** [comment]
this helps me fix the problem.
just add two line in `~/.zshrc` file.

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8

https://github.com/mobile-shell/mosh/issues/98
