### ISSUE TITLE
Jump to slash, Delete to slash

### ISSUE THREAD

**Issue by imShara** [robbyrussell/oh-my-zsh#5108]
How to make this:

> ~/hello/sick-sad-world

E.g I want to remove 'sick-sad-world' until slash after hello.

> ~/hello/

 But `^W` and `Alt + Backspace` removes by words until minus.

> ~/hello/sick-sad-

And if I want to remove or change 'sick-', I need to jump to slash, but Ctrl + ← jumps to minus too.

`WORDCHARS='*?.[]~-_=&;!#$%^(){}<>'` in `~/.zshrc` does not help

**Comment by mcornella** [comment]
I think this is what you're looking for: http://zshwiki.org/home/zle/bindkeys#most_wanted.

> One of the things I most missed about bash when first switching to Zsh was that M-b and M-f (backward-word and forward-word) would jump over an entire /path/location, rather than to each word separated by a '/'. To make the behavior more like bash, you can evaluate this command:
```
export WORDCHARS=''
```
> If you prefer, you can make WORDCHARS local to the definition of say, backword-word, so that kill-word still deletes an entire path. To do this, you need to define a widget function. For example, for backward-word, I use this:
```
tcsh-backward-word() {
  local WORDCHARS="${WORDCHARS:s@/@}"
  zle backward-word
}
zle -N tcsh-backward-word
```
> PiyoPiyo: This is what I use in my own setup:
```
# by default: export WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'
# we take out the slash, period, angle brackets, dash here.
export WORDCHARS='*?_[]~=&;!#$%^(){}'
```
