### ISSUE TITLE
Environment specific customization 

### ISSUE THREAD

**Issue by ulejon** [robbyrussell/oh-my-zsh#5109]
I would find it extremely handy if I could have different custom scripts for different environments. For example in the custom directory I could have one directory called Darwin and one called Linux. 

Is there support for something similar already?

**Comment by mcornella** [comment]
Not that I know of, but you could design a specific custom script, say at `$ZSH_CUSTOM/env-loader.zsh` that would use `$OSTYPE` or whatever variable you need (like `$HOSTNAME`) to load scripts from a custom folder, say `$ZSH_CUSTOM/env-loader/` with scripts named `linux.zsh`, `darwin.zsh`, etc.

Let me know if that helps.
