### ISSUE TITLE
vi-mode plugin - normal mode indicator is missing.

### ISSUE THREAD

**Issue by Granitas** [robbyrussell/oh-my-zsh#5118]
Hello, I've tried several themes and even terminals but I can't seem to find any that displays an indicator for vi-mode plugin's normal mode.

Am I misunderstanding here something?

Edit: after going through several random themes I finally found one that actually works, it's `avit`, so it seem to be theme issue.

**Comment by apjanke** [comment]
Yeah, this is normal. Most themes do not include a vi mode indicator. You can get a partial listing of those that do by looking for themes that use `vi_mode_prompt_info`.

```
[~/.oh-my-zsh/themes on ⇄ master]
$ grep -l vi_mode_prompt_info *
avit.zsh-theme
flazz.zsh-theme
[~/.oh-my-zsh/themes on ⇄ master]
$
```

You can add a vi mode indicator to other themes by making a custom variant of them.

**Comment by bderrly** [comment]
vi-mode sets an indicator with $RPS1 if it is not set by a theme. In other words, as long as you have the vi-mode plugin enabled and a theme that doesn't do something with RPS1 or RPROMPT you should get the setting from vi-mode which is a set of three red left chevrons.
