### ISSUE TITLE
[zsh-navigation-tools] n-kill freezes whole shell on second page

### ISSUE THREAD

**Issue by kapsh** [robbyrussell/oh-my-zsh#5120]
I've just enabled zsh-navigation-tools plugin and soon I figured out that `n-kill` command can cause 100% CPU and up to 14 GB RAM usage of currently running zsh process.
To reproduce it, one can launch `n-kill` and try to scroll down to second page with arrow key or page down.

**Comment by mcornella** [comment]
The plugin on Oh My Zsh is just a mirror of the official repository, please post the issue there: https://github.com/psprint/zsh-navigation-tools.

**Comment by kapsh** [comment]
k, thanks for pointing out.
