### ISSUE TITLE
Cordial theme does not exist anymore in the last release

### ISSUE THREAD

**Issue by zanot** [robbyrussell/oh-my-zsh#5121]
I recently upgraded to the latest release, and wanted to set my theme to [Cordial](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#cordial) but I get the warning :
```no such file or directory: /Users/_X_/.oh-my-zsh/themes/cordial.zsh-theme```

It seems this theme does not exist anymore, or may have been renamed?

**Comment by mcornella** [comment]
This theme was never bundled with OMZ, it seems the author misplaced the theme information in the Themes wiki page instead of the `External themes` one. You can find more information over at the repository web: https://github.com/stevelacy/cordial-zsh-theme.
