### ISSUE TITLE
Plugin to Mark/Umark a directory on the fly.

### ISSUE THREAD

**Issue by hasanein** [robbyrussell/oh-my-zsh#5125]
I've previously written a shell script that allows the automatic bookmarking a directory or a path to a name and navigating to that by simply typing the bookmark name.

More info on the project are in: https://github.com/hasanein/BookmarkerScript

If people think that this might be useful, I can adapt that to a plugin to use within Oh-My-Zsh as I am using it locally at the moment.

**Comment by mcornella** [comment]
No demand (and we have quite a few of these types of plugins already).
