### ISSUE TITLE
When I run the command line “adb”  it shows that "command not found"，but at the time I use the terminal ,it works properly

### ISSUE THREAD

**Issue by xinghedazhan** [robbyrussell/oh-my-zsh#5131]
When I run the command line “adb”  it shows that "command not found"，but at the time I use the terminal ,it works properly

**Comment by GospelYe** [comment]
did u config android tool path in .zshrc?

**Comment by xinghedazhan** [comment]
I have solved the problem,thank you

**Comment by aziz-boudi4** [comment]
@GospelYe how can I config tool path in .zshrc?

**Comment by sgallese** [comment]
@aziz-boudi4 if you're a mac user, you probably have you Android config here by default: `~/.bash_profile`
I modified ~/.zshrc to use those same credentials.

There are many posts on how to configure Android adb in the shell of your choice, including here: https://stackoverflow.com/questions/17901692/set-up-adb-on-mac-os-x

**Comment by oscargallegoglobant** [comment]
> I have solved the problem,thank you

You Should put your solution here to other people

**Comment by mcornella** [comment]
The folder where the adb command is located needs to be in `$PATH`.

**Comment by alisen** [comment]
[oh-my-zsh config](https://stackoverflow.com/a/48117074/1108911)
