### ISSUE TITLE
Fabric autocomplete plugin errors

### ISSUE THREAD

**Issue by unklphil** [robbyrussell/oh-my-zsh#5134]
The autocomplete for Fabric throws errors when trying to autocomplete.

**Steps to reproduce:**

Add the fabric plugin to the plugins to load:

```zsh
# ~/.zshrc
plugins=(fabric)
```

Install Fabric:

```
$ pip install fabric
```

Try to use autocomplete:

```
$ fab <press tab>
_arguments:comparguments:312: invalid argument:
_fab:61: command not found: (--hide=-)--hide=-[comma-separated list of output levels to hide]: :->levels
_arguments:comparguments:312: invalid argument:
_fab:61: command not found: (--hide=-)--hide=-[comma-separated list of output levels to hide]: :->levels
_arguments:comparguments:312: invalid argument:
_fab:61: command not found: (--hide=-)--hide=-[comma-separated list of output levels to hide]: :->levels
```

**System details:**

- Mac OS X v10.11.5
- Fabric v1.11.1
- zsh v5.0.8

**Comment by svenXY** [comment]
I have the same problem on Arch Linux

Fabric 1.10.2
zsh 5.2 (x86_64-unknown-linux-gnu)

**Comment by unklphil** [comment]
fixed by https://github.com/zsh-users/zsh-completions/issues/437
