### ISSUE TITLE
iTerm2 v3.0.0: syntax error: Expected “,” but found identifier

### ISSUE THREAD

**Issue by daniula** [robbyrussell/oh-my-zsh#5142]
After updating iTerm2 to version 3.0.0 I've noticed this issue:
Every time after I press `Ctrl+C` there is a message: `55:62: syntax error: Expected “,” but found identifier. (-2741)` It happens on all themes in zsh. Issue disappears when I switch to bash or default OSX Terminal.

**Comment by mcornella** [comment]
This seems to be an AppleScript error. What plugins are you using?

**Comment by daniula** [comment]
In `.zshrc` I have only: `plugins=(git)`

**Comment by mcornella** [comment]
Ok. Please run `omz_diagnostic_dump`, post the resulting `.txt` file in a private gist and copy the link here.

**Comment by daniula** [comment]
https://gist.github.com/daniula/f426f4b3630be9ebc9d095ca74843a3e

**Comment by mcornella** [comment]
I couldn't find anything of relevance. Perhaps you have something else in your `.docker_aliases` file that you could post? Grep for an `osascript` function and you'll hopefully find it.

BTW, there was a github API token in your zshrc file that I saw, I strongly recommend you to regenerate that.

**Comment by daniula** [comment]
An issue was with `marzocchi/zsh-notify` plugin, which it seems they know about. Switching to branch `next-iterm` solved an issue.

Thank you for noticing github token, I was removing bunch of those and missed that one.

**Comment by mcornella** [comment]
Thanks for the heads up. And about that token, we should have a better system to gather diagnostic dumps in a safer way.

**Comment by daniula** [comment]
Simple tool recognising long hashes and obfuscating them should do a job.
