### ISSUE TITLE
no matches found: _vagrant[Conflict]

### ISSUE THREAD

**Issue by welly** [robbyrussell/oh-my-zsh#5146]
Vagrant plugin appears to be broken on my system somehow. I'm not sure what has changed but enabling it in .zshrc and opening a new terminal window reports:

> /Users/alastair/.zcompdump-Alastair’s MacBook Pro-5.0.8:1408: no matches found: _vagrant[Conflict]

Any suggestions?

Thanks!

**Comment by mcornella** [comment]
You could try `rm ~/.zcompdump*` and restarting the shell.
