### ISSUE TITLE
Ubuntu 15.10 Problem: Changes to the directory after pressing the command.

### ISSUE THREAD

**Issue by sadhakbj** [robbyrussell/oh-my-zsh#5147]
I am getting a issue with Ubuntu 15.10.
For example I want to run gulp inside my php application and i have gulp directory also. If i type 
```
gulp
```
it rather than running the gulp it takes me inside the gulp directory. It is doing same for every directory. I no longer need to type cd to change to directory.

**Comment by mcornella** [comment]
Are you sure you have a `gulp` command? Do `which gulp` to confirm. If it doesn't appear, it must be that you don't have it added in your `$PATH`.

**Comment by sadhakbj** [comment]
I faced the problem. I completely uninstalled oh-my-zsh and again i installed it how the problem has been fixed.
