### ISSUE TITLE
Completions on zsh repeat a command

### ISSUE THREAD

**Issue by alvesadrian** [robbyrussell/oh-my-zsh#5157]
Double tab completions on zsh repeat a first command at the beggining of the line:

```
$ vivi Downloads/archwall
# for that ^^^ i just typed "vi" and hit tab twice
```

**Comment by mcornella** [comment]
This is a known bug that we haven't fully understood. It could be a UTF8 problem or a theme problem.
Please post what theme you're using, the output of `locale` and whether you're using tmux, screen, putty, etc.

Related: #3346 #3368 #3932 #4176 #4529 #4632

**Comment by adrian-gluu** [comment]
locale=en_UTF8
default theme robbyrusell i think just the default
terminal termite 
no tmux no screen no putty

**Comment by mcornella** [comment]
Please post the full output of running the `locale` command, it's important.

**Comment by alvesadrian** [comment]
locale
LANG=en_US.UTF-8
LC_CTYPE=C
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by mcornella** [comment]
`LC_CTYPE=C` is probably the culprit. Check your `~/.zshrc` file or `~/.profile` for a line setting `LC_CTYPE` and delete it. If you don't find one, you can also override that by setting `export LC_CTYPE=en_US.UTF-8` in your zshrc file.

**Comment by alvesadrian** [comment]
yup that sorted the issue! thanks!

**Comment by turkeyphant** [comment]
> `LC_CTYPE=C` is probably the culprit. Check your `~/.zshrc` file or `~/.profile` for a line setting `LC_CTYPE` and delete it. If you don't find one, you can also override that by setting `export LC_CTYPE=en_US.UTF-8` in your zshrc file.

Unfortunately I am still getting this error:

```
root@fs  ~
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=en_US.UTF-8
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by mcornella** [comment]
What locales do you have installed? Run `locale -a`

**Comment by turkeyphant** [comment]
` root@fs  🖿  ~ ▓▒░ locale -a                                                                                  ░▒▓ ✔  2m 2s  4.77  3%  16:07 🕓  
C
POSIX
en_US.utf8`

**Comment by mcornella** [comment]
Hmm you're prompt looks complex, perhaps it's the emojis. What terminal emulator are you using?

**Comment by turkeyphant** [comment]
How do I find what terminal editor I'm using?

This was exactly the same behaviour with a default zsh prompt long before any eomji or anything.

**Comment by mcornella** [comment]
The terminal emulator is the GUI program you use to run the console.

I don't think that's it but try `export LANG=en_US.utf8` instead of `en_US.UTF-8`.

**Comment by turkeyphant** [comment]
Hi, I know that but I'm using unraid webterminal so I don't know what emulator is running beneath that.

Unfortunately that doesn't fix the issue.

**Comment by mcornella** [comment]
> I'm using unraid webterminal so I don't know what emulator is running beneath that.

That's precisely the terminal emulator. Do you have `COMPLETION_WAITING_DOTS=true` set up in your zshrc file, by any chance?

**Comment by ofersabo** [comment]
I'm also having this issue, what zsh version to you use?

**Comment by dzcpy** [comment]
Tried all suggestions above and it didn't work

**Comment by mcornella** [comment]
Please see [the full instructions in the FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command).
