### ISSUE TITLE
Emacs plugin wrong keybinding

### ISSUE THREAD

**Issue by shinderohitt** [robbyrussell/oh-my-zsh#5160]
M-w cuts the selected text (selected using C-space), whereas it should just be copying the text. C-w cuts the selected text as expected.

**Comment by mcornella** [comment]
I don't see in the plugin code where that key binding is modified. Can you check if using `command emacs` instead of `emacs` the same key binding is there? That would confirm that it's not an OMZ thing.

**Comment by shinderohitt** [comment]
Hey @mcornella, sorry about this. I looked up and OMZ has nothing to do with it. I think it's zsh configuration. I am actually using a default set-up of OMZ (hence only `git` plugin).

Thanks for responding!
