### ISSUE TITLE
After upgrade everything has broken up

### ISSUE THREAD

**Issue by rootical** [robbyrussell/oh-my-zsh#5161]
![image](https://cloud.githubusercontent.com/assets/1233196/16078495/93527e68-32ff-11e6-85ec-8a66bfcdb719.png)

After upgrade today I have these weird errors. I've upgraded using zsh proposal on update.
Could anyone please advise?

``` bash
zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

I was using agnoster theme, tried others and get pretty similar errors and no actual theme.

**Comment by mcornella** [comment]
See #4870 for a solution.

**Comment by rootical** [comment]
Thanks, it helped.
