### ISSUE TITLE
The git repo is corrupt

### ISSUE THREAD

**Issue by stephanecollot** [robbyrussell/oh-my-zsh#5168]
Hi,

I'm trying to mirror your github repository but it is not possible because it is corrupt:

> ^[[0;32mCreating mirror from https://github.com/robbyrussell/oh-my-zsh
> ^[[0;39mCloning into bare repository 'oh-my-zsh'...
> ^[[0;32mAdding gitlab remote to project.
> ^[[0;39m^[[0;32mChecking the mirror into gitlab.
> remote: error: object 2b7227859263b6aabcc28355b0b994995b7148b6:contains zero-padded file modes
> remote: fatal: Error in object
> error: unpack failed: index-pack abnormal exit
> To git@localhost:gitlab-mirrors/oh-my-zsh.git
>  ! [remote rejected] master -> master (unpacker error)
> error: failed to push some refs to 'git@localhost:gitlab-mirrors/oh-my-zsh.git'

**Comment by mcornella** [comment]
This is a known issue that doesn't have any significant impact on the git repository other than this annoying error. Solving it would involve rebasing over 5 years of commits, which is not a sensible option. See https://github.com/robbyrussell/oh-my-zsh/issues/4963#issuecomment-210263233 for the solution.
