### ISSUE TITLE
Taskwarrior completion fails due to regex arguments

### ISSUE THREAD

**Issue by aranw** [robbyrussell/oh-my-zsh#5170]
Just added taskwarrior and plugin for it and when I do `task [tab]` I get the following output.

```
aran on Arans-MacBook-Pro in ~
○  task
_task_attributes:zregexparse:4: not enough regex arguments

aran on Arans-MacBook-Pro in ~
○  task
zsh: do you wish to see all 100 possibilities (98 lines)?
```

**Comment by mcornella** [comment]
I've submitted #5171 which should fix it. Please try it out and tell me if it works.

**Comment by aranw** [comment]
Oh that looks to be working!

**Comment by mcornella** [comment]
Thanks for confirming!

**Comment by dein0s** [comment]
is this plugin version-dependent?
getting the same error as above:
```
 ~  task
_task_attributes:zregexparse:4: not enough regex arguments
 ~  task
zsh: do you wish to see all 101 possibilities (100 lines)? 
```
task 2.5.0 (latest available from linuxmint repos)
zsh 5.1.1
