### ISSUE TITLE
`hash` for directory shortcuts broken after updating

### ISSUE THREAD

**Issue by rodri042** [robbyrussell/oh-my-zsh#5173]
In my `.zshrc` I have, for example:
```
hash -d soft=~data/soft
hash -d scripts=~data/scripts
hash -d work=~data/work
hash -d mus=~data/music
```

After updating ohmyzsh, this doesn't work anymore.
```
╭─rodri042@rodri042  ~halu  ‹master*› 
╰─$ cd soft
cd: no such file or directory: s
```

I'm using Terminator in Fedora 23.

**Comment by mcornella** [comment]
This is happening because we removed `setopt cdablevars` from the main codebase. If you want that to work again you have to add that to your zshrc file. The reason we removed it was because lots of users where complaining of having user names in their cd completion.
Thanks!
