### ISSUE TITLE
pj with two projects having the same name

### ISSUE THREAD

**Issue by kopparam** [robbyrussell/oh-my-zsh#5184]
I have two projects with the same name. I am trying to navigate to the second one.
When I tab-complete, I always end up in the first one. I don't see the second one in the list when I am trying to tab-complete. 

Is there anything I can do to have two projects with the same directory name?

**Comment by Oscarteg** [comment]
How can you have same directory name?

**Comment by mcornella** [comment]
I don't think I understand correctly the reproducing instructions. Maybe you can try https://asciinema.org to record what your issue is, and post the link here?

**Comment by mcornella** [comment]
Ok, after looking better at the pj plugin, it seems there is no way to allow same project names in different `$PROJECT_PATHS`. It's a [known pitfall](https://github.com/mcornella/oh-my-zsh/blob/f30ecfb980c18a49a7f8913785896488204130ee/plugins/pj/README.md#pj-my-project).

It doesn't seem to be fixable in the short term so I'm closing this. If you want this to work put whatever directory you want first in the `$PROJECT_PATHS` array, or use a different directory-jumping plugin like `z` or `fasd`.

Thanks for your understanding.
