### ISSUE TITLE
Don't drop into ZSH in the installer

### ISSUE THREAD

**Issue by Industrial** [robbyrussell/oh-my-zsh#5187]
Hi!

Is it possible for the installer to not drop me into a ZSH session at the end of the script when oh-my-zsh has finished installing?

I have this installed as part of my Dockerfile and there are several steps I want to take after installing oh my zsh liky making symlinks etc. These all get skipped if I get dropped into zsh.

How do I solve this issue?

**Comment by Industrial** [comment]
Nevermind.

I'm just doing a git clone now, with my own .zshrc :-)

**Comment by mcornella** [comment]
This will be fixed on #5123; but yes, for the moment a `git clone` is enough. The installer is also more directed to end users instead of to non-interactive installations, so we check if zsh is installed and if it's the default `$SHELL`.
