### ISSUE TITLE
ys.zsh-theme virtualenv 

### ISSUE THREAD

**Issue by elchinot7** [robbyrussell/oh-my-zsh#5192]
Hi there, 

I'm just wondering if there is some way to show the `python virtualenv` prompt  in `ys.zsh-theme`. 
After activating the `virtualenv` plugin the venv prompt is shown in other themes but not in `ys`.

Now I'm temporally using `agnoster-theme` but I really prefer the simplicity of `ys`, so I hope someone here knows how to fix this issue.

Cheers

**Comment by madhat2r** [comment]
This might give you what you want. Unzip the attached file and copy it to `~/.oh-my-zsh/custom/themes`, then set your theme to `ZSH_THEME="ys-modified"`
[ys-modified.zsh-theme.zip](https://github.com/robbyrussell/oh-my-zsh/files/339189/ys-modified.zsh-theme.zip)

**Comment by elchinot7** [comment]
Thanks @madhat2r
This is just what I need, I appreciate your time and help.
I'm back to `ys` (modified).

**Comment by mcornella** [comment]
Closing this since you seem to have what you need.
