### ISSUE TITLE
Plugin, alias, function search engine

### ISSUE THREAD

**Issue by fabianmoronzirfas** [robbyrussell/oh-my-zsh#5193]
Hi oh-my-zsh team,

I have a feature request/suggestion for you. Wouldn't it be great if oh-my-zsh had a build in search engine for enabled plugins, aliases and functions. The problem I always have with oh-my-zsh is that I forget which plugins are enabled and what the aliases it has. There is this project called [bash-it](https://github.com/Bash-it/bash-it) (inspired by oh-my-zsh) that has that.

**Comment by mcornella** [comment]
This is covered by the wiki page of plugins and each one of the plugins' READMEs (we still lack some of them, feel free to contribute to the documentation!).
