### ISSUE TITLE
nocorrect mv

### ISSUE THREAD

**Issue by sygi** [robbyrussell/oh-my-zsh#5196]
When I'm using `mv`, I'd prefer correction to be turned off, to prevent this:

```
mv ~/Downloads/index.mp4 2.5.mp4
zsh: correct '2.5.mp4' to '1.5.mp4' [nyae]? 
```

It seems that the authors thought about this and made aliases for that kind of commands in [lib/correction.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/correction.zsh), but, as one can see above, it is not executed in my case.

Did I do something wrong? What can I do to make zsh correction work as expected with `mv`? Do I have to turn something on?
I have:

```
ENABLE_CORRECTION="true"
plugins=(command-not-found common-aliases fasd git python)
```

in my `~/.zshrc`.

**Comment by mcornella** [comment]
The `common-aliases` [overrides the `mv` alias](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/common-aliases/common-aliases.plugin.zsh#L51). You can manually do the `alias mv='nocorrect mv'` a the end of your zshrc file.

**Comment by sygi** [comment]
Thanks, now it works. Do you think it deserves a pull request like that:

[compare](https://github.com/robbyrussell/oh-my-zsh/compare/master...sygi:mv-clash?expand=1)

**Comment by mcornella** [comment]
I don't think that's a great way to solve this and it's not immediately obvious to me what the best approach is. For the time being I'll leave this hanging but I'll come back to it right away if someone else has this problem.
