### ISSUE TITLE
How to integrate oh-my-zsh with other git tool - posh-git-bash to show git prompts?

### ISSUE THREAD

**Issue by alexya** [robbyrussell/oh-my-zsh#5197]
I can use the posh-git-bash in normal bash shell, but I can't use it under oh-my-zsh.

First of all, I follow github project [posh-git-sh](https://github.com/lyze/posh-git-sh) to create ~/git-prompt.sh, and add the following scripts to the bottom of file ~/.bashrc

```
source ~/git-prompt.sh
PROMPT_COMMAND='__posh_git_ps1 "\u@\h:\w" "\\\$ ";'$PROMPT_COMMAND
```

reopen the terminal, and go to a git project folder, all the git prompts are correct and as I expected. e.g.

```
Orion@Orions-machine-1:~/Source/MyProjects/deploy_tools [master ≡ +0 ~1 -0 | +1 ~0 -0]$
```

Then, I follow the oh-my-zsh to install zsh and oh-my-zsh. I choose the 'crcandy' theme, and add the scripts to the bottom of file ~/.zshrc.

But it always uses the format defined in theme 'crcandy', just show a '*' in prompt.

```
Orion@Orions-machine-1 [10:25:57] [~/Source/MyProjects/deploy_tools] [master *]
```

The file ~/.oh-my-zsh/themes/crcandy.zsh-theme content:

```
PROMPT=$'
%{$fg_bold[green]%}%n@%m %{$fg[blue]%}%D{[%I:%M:%S]} %{$reset_color%}%{$fg[white]%}[%~]%{$reset_color%} $(git_prompt_info)\
%{$fg[blue]%}->%{$fg_bold[blue]%} %#%{$reset_color%} '

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[green]%}["
ZSH_THEME_GIT_PROMPT_SUFFIX="]%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[red]%}*%{$fg[green]%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""
```

Do you guys know how to integrate other git tool into oh-my-zsh? thx.

[thread in stackoverflow](https://stackoverflow.com/questions/38136266/how-to-use-posh-git-bash-in-oh-my-zsh)

**Comment by jamesboswell** [comment]
@alexya  looks like this might be something you're looking for https://github.com/elboletaire/zsh-theme-racotecnic
