### ISSUE TITLE
Hashbang for zsh?

### ISSUE THREAD

**Issue by ramswaroop** [robbyrussell/oh-my-zsh#5199]
I have a shell script which has `#!/bin/bash` as the first line and so whenever I execute the script(by `source script`), it changes my shell from `zsh` to `bash`. How do I prevent this from happening? I tried replacing it with `#!/bin/env zsh` and `#!/bin/zsh` but no luck.

**Comment by jamesboswell** [comment]
Did you restart your terminal session or switch back to zsh before editing your file? `#!/bin/env zsh` should work

**Comment by ramswaroop** [comment]
Yes @jamesboswell . Is it like the interpreter sees something in the script which isn't supported by zsh and so it switches back to bash?

**Comment by mcornella** [comment]
I think the path to env is `/usr/bin/env`. Check with `which env`. If that's not it post the script and how you're running it.

**Comment by mcornella** [comment]
Oh, nevermind. I misunderstood the original question. Can you post the script? Perhaps there's an `exec bash` in there.

**Comment by apjanke** [comment]
When you execute a script using `source`, it is read and executed in your current shell session, and the `#!` shebang line is ignored. The fact that it has a shebang suggests that it's intended to be run as an external command, with `./script.sh` instead of `source script.sh`. Maybe try that instead.

**Comment by ramswaroop** [comment]
@apjanke Actually it's a bash script without the extension `.sh` and when I do `./script` it says `./script: command not found`

**Comment by ramswaroop** [comment]
@mcornella There is no `exec` but there is `eval` in the script.

**Comment by mcornella** [comment]
I feel like the fastest way for us to solve this is if you post the script and the terminal contents of when you're running.

**Comment by apjanke** [comment]
> Actually it's a bash script without the extension `.sh` and when I do `./script` it says `./script: command not found`

That sounds even more like something that's intended to be run as an external command (i.e. in its own process) instead of being `source`d.

That error message sounds like it might be something inside the script calling a nonexistent command.

Yeah, post the script (maybe as a Gist - https://gist.github.com/) and we can help debug it. Doesn't sound like an OMZ issue.

**Comment by mcornella** [comment]
> That error message sounds like it might be something inside the script calling a nonexistent command.

That's probably the result of not having executable permission on the script file.

**Comment by apjanke** [comment]
> That's probably the result of not having executable permission on the script file.

That'd probably produce a "permission denied" error. Assuming OP copied the error message correctly, it better matches a bad command invocation inside the script. The error message form "foo: whatever" means that "foo" (in this case, `./script`, not `zsh` or `bash`) is running and producing the error.

```

$ ls -l script
-rw-r--r-- 1 janke staff 37 Jul 14 12:59 script
[~]
$ ./script
zsh: permission denied: ./script
[✘ ~]
$ chmod a+x script
[~]
$ ./script
Hello world
./script: line 4: blah: command not found
[✘ ~]
$ cat script
#!/bin/bash

echo "Hello world"
blah
[~]
$
```

**Comment by mcornella** [comment]
Actually this is what I get:
```
$ ls -l script
-rw-r--r-- 1 marc marc 0 Jul 14 19:16 script
$ ./script
./script: command not found
```
.
.
.
.
.
.
.
.
.
.
.
.
Not really though, I just made that up. You win this time, Janke.

![](http://i.giphy.com/l46CtynlAiRNzfsA0.gif)

**Comment by ramswaroop** [comment]
Here is the script guys: https://gist.github.com/ramswaroop/efe163f635d27b9a98b2adce7c3ced44

Sorry for the late reply.

**Comment by mcornella** [comment]
[Line 41](https://gist.github.com/ramswaroop/efe163f635d27b9a98b2adce7c3ced44#file-script-L41) already shows that this is intended to be used for bash:
```bash
export PS1="\n\[\e[33m\]\w\[\e[0m\]\n\$ "
```

I think this is what you mean by changing to bash: the prompt changes to `\u:\w$ `, and you interpret that as being in bash, but it's still zsh:

```
source script.txt 
Warning: location WORKSPACE=/home/marc/workspace does not exist on disk
Warning: location GITSPACE=/home/marc/git does not exist on disk
Warning: location KIT_REPO=/home/marc/kits_for_validation does not exist on disk
Warning: location INSTALL_HOME=/home/marc/installs does not exist on disk
Warning: location RUN_CONF=/home/marc/run.conf does not exist on disk
Warning: location ANT_HOME not defined
Warning: location ANTINSTALLER_HOME not defined
Warning: location JBOSS_HOME=/opt/jbosses/jboss-6.1.0.Final does not exist on disk
\u:\w$
```

```
\u:\w$ echo $ZSH_VERSION
5.2
```

Basically you can remove that line from the script and you won't have the prompt changed.

If that is not it feel free to reopen the issue.

**Comment by ramswaroop** [comment]
@mcornella Thanks for the help but before removing the line I have to make sure what's the purpose of `PS1`. There is another one in [line 91](https://gist.github.com/ramswaroop/efe163f635d27b9a98b2adce7c3ced44#file-script-L91) as well.

**Comment by mcornella** [comment]
[`$PS1` (or `$PROMPT` also in zsh)](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-PS1) is just the variable that holds the prompt string. So if you run `PS1='prompt-here$ ` you would get a prompt like this:
```
prompt-here$ [CURSOR]
```

Bash prompt sequences are different from [zsh prompt sequences](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html)─bash uses backslash instead of `%`─, that's why it looks weird.

**Comment by ramswaroop** [comment]
Sorry, but by purpose I meant why the author of the script has written that. Why is it needed?

Anyways, thanks very much for the help. I know the cause now.

**Comment by mcornella** [comment]
I have no idea 😁

**Comment by gaurav5430** [comment]
> Actually this is what I get:
> 
> ```
> $ ls -l script
> -rw-r--r-- 1 marc marc 0 Jul 14 19:16 script
> $ ./script
> ./script: command not found
> ```
> 
> .
> .
> .
> .
> .
> .
> .
> .
> .
> .
> .
> .
> Not really though, I just made that up. You win this time, Janke.
> ![](https://camo.githubusercontent.com/5142965f21634a1a190ed4d5d3e15d7484466171/687474703a2f2f692e696d6775722e636f6d2f695557443863782e676966)

did you understand the reason for the 'command not found' ?

**Comment by sighbaby** [comment]
Please I am wake me think I changed your source that I go to you and I’m so in love with him as it was when we was in here what do you need

Sent from Yahoo Mail for iPhone


On Monday, June 15, 2020, 12:30 PM, Gaurav Gupta <notifications@github.com> wrote:





Actually this is what I get:
$ ls -l script
-rw-r--r-- 1 marc marc 0 Jul 14 19:16 script
$ ./script
./script: command not found

.
.
.
.
.
.
.
.
.
.
.
.
Not really though, I just made that up. You win this time, Janke.



did you understand the reason for the 'command not found' ?
