### ISSUE TITLE
Alias on separet file

### ISSUE THREAD

**Issue by The33Coder** [robbyrussell/oh-my-zsh#5200]
Hello,

I want to transfer my alias and function on separate file but I don't know how to do.

Actually all function and alias is in the .zshrc

thank you

**Comment by mcornella** [comment]
Hi there, you have two options:

- Put them on a separate file anywhere you want, for example, `~/.aliases`, and put `source PATH_TO_YOUR_FILE` at the bottom of your zshrc file.

- The other option is putting that in `$ZSH_CUSTOM/YOUR_FILE_NAME.zsh` and OMZ will automatically load when loading it.
