### ISSUE TITLE
Git plugin crashes after upgrading to El Capitan

### ISSUE THREAD

**Issue by azer** [robbyrussell/oh-my-zsh#5203]
I've just upgraded my system to El Capitan, and my terminal began crashing once I press `tab` while typing a Git command. No idea how to get an error output, any ideas ?

**Comment by mcornella** [comment]
You can run `functions -T _git` which will toggle debugging of the git completion function and hopefully get you a helpful error message.

**Comment by mcornella** [comment]
You have to run that and _then_ try tab-completing a git command if it wasn't clear.

**Comment by azer** [comment]
@mcornella here is the output; ![](https://cldup.com/QlgPRLUBE7.png)

**Comment by azer** [comment]
@mcornella thanks for the tip about showing the error.

**Comment by mcornella** [comment]
What was the problem?

**Comment by azer** [comment]
@mcornella dunno, just disabled the git-completion plugin
