### ISSUE TITLE
_zsh_autosuggest_invoke_original_widget:7: maximum nested function level reached

### ISSUE THREAD

**Issue by crazy-canux** [robbyrussell/oh-my-zsh#5204]
when I run " source ~/.zshrc"  got this error.
Any ideas why?

**Comment by mcornella** [comment]
First of all you shouldn't `source ~/.zshrc` for almost anything. If you want to reload the zshrc file you can restart the terminal or just run `exec zsh` to restart the zsh session.

That said, if you post the contents of your zshrc file I'll may be able to help you.

**Comment by crazy-canux** [comment]
It looks a zsh5 issue. 
thanks.
