### ISSUE TITLE
Add a refreshing clock segment.

### ISSUE THREAD

**Issue by Thermatix** [robbyrussell/oh-my-zsh#5206]
A colleague has mentioned about having a clock that updates in realtime in the terminal. I thought that this was a cool thing to have but when I tried to add the clock, it didn't seem to work very well with the agnoster theme so I was wondering could some one help integrate this?

The clock update comes from[ this answer](http://askubuntu.com/a/360172/284992) to an ask ubuntu question.

I also have the following code which I use to add a git-radar segment to my terminal instead of the standard git-hub segment the agnoster theme normally has:

```bash
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_end
  git-radar --zsh --fetch
}
```

I thought I'd ask here as I want to ad this without breaking the agnoster theme, if I figure it out my self then I will of course post it here.

I also thought to ask here becuase like the git-radar segment thing I thought it would be useful to other people that might want to know how to add a clock in the same circumstances.

**Comment by mcornella** [comment]
What has been your work so far with the clock thing? If you can provide code and screenshots we'll be able to help you better.

**Comment by Thermatix** [comment]
Well so far I've added the code below to my current `.zshrc`:

```bash
add_date() {
  date +%r
}

build_prompt() {
  RETVAL=$?
  prompt_status
  add_date
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_end
  git-radar --zsh --fetch
}

setopt PROMPT_SUBST
TMOUT=1

TRAPALRM() {
    zle reset-prompt
}
```

and it results in somthing like this (with auto-updating clock):

![](https://ibin.co/2mzgxYJNi4Nc.png)

I'd much rather it resemble how looks in answer previously mentioned but I'm not quit sure how to do it, as I whilst I do kind of understand this:

```bash
PROMPT='%B%F{red}%n@%m%f%F{yellow}[%D{%L:%M:%S}]%f:%F{blue}${${(%):-%~}}%f$ %b'
```

I'm not sure how to integrate it into the `build_prompt` method so it looks right with the current theme 'agnoster'.

**Comment by mcornella** [comment]
What you want is to use `prompt_segment` which sets the color and doesn't output a new line. Based on your `$PROMPT` above, you'd want something like this:
```zsh
prompt_date() {
    # prompt_segment bgcolor fgcolor text
    prompt_segment black yellow '[%D{%L:%M:%S}]'
}
```

If you thing the prompt gets too crowded, you can also put the date on `$RPROMPT` which is the right prompt. For agnoster there isn't a `build_rprompt` function, so you would something like this:
```zsh
RPROMPT='%{%F{yellow}%}[%D{%L:%M:%S}]%{%f%}'
```

**Comment by mcornella** [comment]
Here's a demo of the last option: https://asciinema.org/a/10qj1bqcxx8iuq6dt6mismnoo

**Comment by Thermatix** [comment]
Ok, almost perfect, my `.zshrc` currently looks like (the relevant part):

```bash
time_segment() {
   prompt_segment black blue '[%D{%L:%M:%S}]'
}

TMOUT=1

TRAPALRM() {
    zle reset-prompt
}

build_prompt() {
  RETVAL=$?
  prompt_status
  time_segment
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_end
  git-radar --zsh --fetch
}
```

and it looks like:

![](https://cdn.pbrd.co/images/7O8eQg1Ur.png)

Last thing is How to make it 24hour clock?

**Comment by Thermatix** [comment]
Ok, thanks for your help.
