### ISSUE TITLE
I already add the ZSH_THEME="agnoster" in the zshrc but nothing happened why 

### ISSUE THREAD

**Issue by woshichuanqilz** [robbyrussell/oh-my-zsh#5212]
I use the command `sudo apt-get install zsh` to install the zsh. 
And I add the `ZSH_THEME="agnoster"`(or `ZSH_THEME=agnoster both tried`) to the `.zshrc` file but nothing happened. Even I logout and the relogin. 

And I search in the system use the command `find / | grep -e "zsh-theme"  and get nothing. So it means I haven't install the theme on my pc?  

So I git the `theme` from this repository and put them in the `.oh-my-zsh` directory. And then add the line 
`ZSH_CUSTOM="~/.oh-my-zsh"`in the .zshrc file, 

still nothing happens. 

What's wrong with it ? 

Where is the theme file ?

My system is `Ubuntu kylin` 16

**Comment by stevenspasbo** [comment]
After you installed zsh, did you change your shell?

    chsh -s zsh

**Comment by woshichuanqilz** [comment]
@stevenspasbo yeah, I changed. the symbol of the command line promote change to `%`

**Comment by stevenspasbo** [comment]
What do you get when you run `echo $ZSH`?

**Comment by woshichuanqilz** [comment]
echo $ZSH get nothing 
but echo $SHELL get /usr/bin/zsh

**Comment by stevenspasbo** [comment]
The `ZSH` environment variable needs to be set to where you cloned the oh-my-zsh repository to.

**Comment by stevenspasbo** [comment]
So actually you just need to remove the `CUSTOM` from `ZSH_CUSTOM`

**Comment by woshichuanqilz** [comment]
@stevenspasbo I use the sudo apt-get to install the zsh.

And just now I clone the zsh in my $HOME directory, 

And I set the $ZSH in the zshrc file. 
Now the `echo $ZSH` is `~/oh-my-zsh` the theme folder is under the `~/oh-my-zsh` which is `~/oh-my-zsh/themes`
And the `ZSH_THEME="3den"`
but nothing happened still.

**Comment by stevenspasbo** [comment]
You shouldn't need to reinstall zsh, just make sure you have

    # Path to your oh-my-zsh installation.
    export ZSH=$HOME/.oh-my-zsh
    # then source the script
    source $ZSH/oh-my-zsh.sh

**Comment by PascalPixel** [comment]
In my case, it was because I used TextEdit to set the theme, which replaces `"` with `”`

**Comment by NoSkillGuy** [comment]
In `ubuntu` i had similar issues. Manual installation fixed all of them.
