### ISSUE TITLE
`ctrl-r` stopped working after enabling `vi-mode`

### ISSUE THREAD

**Issue by iamrahulroy** [robbyrussell/oh-my-zsh#5213]
After enabling `vi-mode` plugin `ctrl-r` stopped working in both insert & normal mode.

**Comment by apjanke** [comment]
Do you mean that it no longer did a backward incremental search?

Enabling `vi-mode` changes the keymap, so many of the default oh-my-zsh key bindings are no longer there. You can restore it by adding the binding in your `~/.zshrc` after sourcing OMZ.

```
bindkey '^r' history-incremental-search-backward
```

**Comment by apjanke** [comment]
See also #4994, which adds the binding under `vi-mode`.

**Comment by mcornella** [comment]
+1. Also, this will be fixed once we implement the keymap managing on `omz_bindkey`, which will be the next step after #5113.

**Comment by iamrahulroy** [comment]
@apjanke Thanks! Your solutions works. I was expecting vi-mode to not change anything in insert mode. Is there a setting which disables vi-mode in insert mode?

**Comment by apjanke** [comment]
No. Insert mode (`viins`) is sort of a sub-mode of vi mode, and is unrelated to emacs mode.

You can add key bindings to the `viins` key map, though, using the `bindkey -M` option.
