### ISSUE TITLE
gfa alias present both in go and git plugins

### ISSUE THREAD

**Issue by pmalek** [robbyrussell/oh-my-zsh#5214]
I have noticed that `gfa` alias present both in go https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/golang/golang.plugin.zsh#L183

```
alias gfa='go fmt . ./...'
```

and git plugins https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L89

```
alias gfa='git fetch --all --prune'
```

Can we somehow change either of them so that they don't collide/overwrite themselves?

**Comment by bderrly** [comment]
Changing alias behaviors may be tricky, see https://xkcd.com/1172/.

**Comment by mcornella** [comment]
This is fixed in #5259, if you agree with it +1 that PR.

**Comment by blackmirroxx** [comment]
+1

**Comment by pmalek** [comment]
@mcornella #5259 looks good, as soon as it is merged we can close this one here

**Comment by mcornella** [comment]
Thanks!
