### ISSUE TITLE
why I lost my zsh-autosuggestions and my oh-my-zsh is faiure

### ISSUE THREAD

**Issue by zhangwei900808** [robbyrussell/oh-my-zsh#5216]
I used zsh-autosuggestions and it is success , but when I set oh-my-zsh is faiure , how to solove this problem???
![qq20160710-2 2x](https://cloud.githubusercontent.com/assets/4385154/16711042/a4f49f1e-467a-11e6-9c4d-a994388a1f6f.png)

**Comment by mcornella** [comment]
I can't quite understand what your problem is. If you've followed the instructions exactly, then the problem might be that you only have `zsh-autosuggestions` in your `plugins` array, therefore all the other plugins you had before aren't enabled now.

If that's not it please explain further.
