### ISSUE TITLE
Zsh is not installed! message is coming

### ISSUE THREAD

**Issue by flik** [robbyrussell/oh-my-zsh#5223]
When I try to install by below command

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

I am getting this error: Zsh is not installed! Please install zsh first!

**Comment by rogeriofonseca** [comment]
You must firt install the ZSH through..
instruction here: [Installing ZSH](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH)

**Comment by flik** [comment]
fixed thanks
