### ISSUE TITLE
accidentally typed gsr with git plugin

### ISSUE THREAD

**Issue by kentor** [robbyrussell/oh-my-zsh#5226]
Apparently `gsr` is an alias for `git svn rebase`.

I'm using the `pure` theme. Now my prompt says `git-svn/branch_name` instead of just `git/branch_name`. How do I revert this?

Kinda sucks that there's a command that can change your prompt like this.

**Comment by mcornella** [comment]
I can't reproduce this from several git repositories that I have flying around. What remote are you pulling from, Bitbucket?

**Comment by kentor** [comment]
Okay I figured it out. For some reason running `git svn rebase` created an `svn` directory under `.git`. I just had to delete `.git/svn/`
