### ISSUE TITLE
Why can't I see the emojis properly?

### ISSUE THREAD

**Issue by maldad** [robbyrussell/oh-my-zsh#5234]
I installed [wild-cherry](https://github.com/mashaal/wild-cherry) theme, it uses emojis, also

* [x] downloaded and installed a [powerline-font](https://github.com/powerline/fonts/tree/master/Monofur)
* [x] enable the emoji plugin

But I still get this

![image](https://cloud.githubusercontent.com/assets/11675538/16891978/1f3937e6-4aca-11e6-9e4e-eb812e4b51cb.png)

**Comment by mcornella** [comment]
What terminal emulator are you using? Have you enabled your powerline font in the terminal emulator? Finally, I feel that you should ask this over to the [wild-cherry repository](https://github.com/mashaal/wild-cherry) instead.

**Comment by maldad** [comment]
Hi, it's konsole, I've asked already in wild-cherry repository, and by a little search on google I noticed that it was a problem from my system, i needed this:  [https://github.com/eosrei/emojione-color-font#install-on-linux](url)
So now, my terminal looks like this, anyway thanks for taking your time to answer me :)
![term](https://cloud.githubusercontent.com/assets/11675538/16975004/14524d54-4e08-11e6-85af-4f954b6faa8c.png)
