### ISSUE TITLE
Error with git.zsh:42

### ISSUE THREAD

**Issue by cbou** [robbyrussell/oh-my-zsh#5241]
Since the last update I get this error on my Mac (10.11.5).

```
~/.oh-my-zsh/lib/git.zsh:42: parse error near `elif'
zsh: command not found: git_prompt_info
```

**Comment by adrianhj** [comment]
I was able to resolve this by changing the line endings from CRLF to LF for lib/git.zsh.

e.g. in vim -> :set ff=unix

**Comment by cbou** [comment]
Yeah Thanks! It works!

**Comment by mcornella** [comment]
For the next time, here's the solution: https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351
