### ISSUE TITLE
Strange display problem when inside git repos

### ISSUE THREAD

**Issue by ghost** [robbyrussell/oh-my-zsh#5248]
I have been using oh-my-zsh with the kardan theme for quite some time now. Recently, after an update I seem to be having a problem with the way the display works.

Earlier it used to be

`> <cursor_here>                                                                                        path(git-branch)@host`

However, now it seems to be the case that the cursor overlaps onto the ">" and the "path@host" has moved one space to its left whenever inside a git repository with files that have not been committed.
1. Is this a known problem?
2. I tried reverting to an earlier version of oh-my-zsh but it did not fix the problem. Does oh-my-zsh internally pull any other git repos that I need to revert as well?

Thanks,

**Comment by apjanke** [comment]
Can you post a screenshot of the bad display?
