### ISSUE TITLE
issue with git :cry:

### ISSUE THREAD

**Issue by zakariaGatter** [robbyrussell/oh-my-zsh#5250]
when im inside a Git repo, git command act weird when i use `tab` to auto complete the command jump to middle of screen   

**EX :**
``` sh
$USER@HOST $ git p
```

after i click TAB git command jub 

``` sh
$USER@$HOST $ git                                    git pull
```
thats happen only inside Git repo 

can any one help me please

**Comment by franklinyu** [comment]
With default configuration? More details?

**Comment by zakariaGatter** [comment]
is ok i found the problem and is done it was a zsh_prompt-git color problem 
thnx for care no one those here oh-my-zsh help is f********

**Comment by franklinyu** [comment]
Good to hear that. You may want to close this issue if your issue is solved.
