### ISSUE TITLE
zsh: command not found: git_prompt_info

### ISSUE THREAD

**Issue by miniyuuzhan** [robbyrussell/oh-my-zsh#5256]
I got this error since this morning after updating oh my zsh when prompted.
After googling it it appears to have happened a few time already, caused my a faulty merge.

So I'm just posting this to let you know.

**Comment by victor-domain** [comment]
run zsh and fix those files on vim setting ":set ff=unix".

**Comment by miniyuuzhan** [comment]
I already have this line in my .vimrc
set ff=unix

but I tried to write it in the vim command panel at the bottom.

It didn't fix.

**Comment by victor-domain** [comment]
edit the file with vim, set ff=unix, save your changes and run zsh again. it should work :)

**Comment by qujian** [comment]
that :set ff=unix  does not take any effect

**Comment by mcornella** [comment]
Follow these instructions: https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351
