### ISSUE TITLE
pj <tab> causes (eval):1: parse error near `&'

### ISSUE THREAD

**Issue by JayyWalker** [robbyrussell/oh-my-zsh#5266]
```
❯ pj ...... 
(eval):1: parse error near `&'
(eval):1: parse error near `&'
```

**Comment by niderhoff** [comment]
Can you state more details for your configuration? installed plugins/dotfiles/os?
For me this error doesn't happen.

**Comment by mcornella** [comment]
You probably have something wrong with your `$PROJECT_PATHS` variable because the pj completion function is really basic:
```zsh
function _pj () {
    typeset -a projects
    projects=($PROJECT_PATHS/*)
    projects=$projects:t
    _arguments "*:file:($projects)"
}
```

**Comment by mcornella** [comment]
Nevermind, I find the problem. This happens if there are directories or files under `$PROJECT_PATHS` containing `&`. A patch is on the way.

**Comment by mcornella** [comment]
PR #5296 should fix this. Please test.

**Comment by JayyWalker** [comment]
I've tested it and my issue is fixed. However we have lost the ability to go to the folder I set as `$PROJECT_PATHS`

**Comment by mcornella** [comment]
That was a side effect of a bug when no project was specified. What should the behavior be if `$PROJECT_PATHS` has more than one directory? The bug made it go always to the first one, so it doesn't seem to be worth it having the old behavior. What do you think?

**Comment by mcornella** [comment]
As far as I know there was never any intention of having that ability. The `pj` plugin is very limited in that sense.

**Comment by mcornella** [comment]
Anyhow, I'm merging that. Thanks.
