### ISSUE TITLE
pj doesn't support project directories with spaces in them

### ISSUE THREAD

**Issue by niderhoff** [robbyrussell/oh-my-zsh#5267]
pj will just truncate at the space and then be unable to open the directory.

Example directory: $HOME/Projects/sample directory/
.zshrc content: $PROJECT_HOMES = ( $HOME/Projects )

``` 
$~:
$~: pj <TAB>
sample
$~: pj sample
No such project sample
$~: pj sample\ diretory
$~/Projects/sample directory/:
```

Also it has problems with special characters (they are displayed as escaped by "\" in the auto-completion display).

Any ideas how to fix those?

**Comment by mcornella** [comment]
PR #5296 should fix this. Please test.
