### ISSUE TITLE
zsh: command not found --- zsh cannot find any global packages

### ISSUE THREAD

**Issue by brucebrophy** [robbyrussell/oh-my-zsh#5269]
I installed oh-my-zsh today and now zsh cannot find any npm packages I have installed globally. I currently have my npm config path set to /Users/brucebrophy/.npm-global

I tried adding an export path for npm to .zshrc but with no luck!

**Comment by Jahhein** [comment]
Remember that the variable's at shell start are what they stay unless you re-source the file after changing it via "export ZSH=whereever" or by editor. Change the ZSH variable, then resource the oh-my-zsh.sh inside  ~/.oh-my-zsh.
