### ISSUE TITLE
oh-my-zsh.sh:42: parse error near `||'

### ISSUE THREAD

**Issue by qujian** [robbyrussell/oh-my-zsh#5272]
i have new-installed on my mac, but got following:
.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'

**Comment by lubeast** [comment]
@qujian duplicate with [issues-4610](https://github.com/robbyrussell/oh-my-zsh/issues/4610)

**Comment by franklinyu** [comment]
Try in your shell:

```shell
test 'a' = 'b' \
|| test 'a' = 'a'
```

Does it returns 1 as expected?

**Comment by mcornella** [comment]
Solution: https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351
