### ISSUE TITLE
Feature request: RSpec plugin

### ISSUE THREAD

**Issue by bquorning** [robbyrussell/oh-my-zsh#5273]
When using [RSpec](http://rspec.info/), I find myself trying to autocomplete command line arguments like `--bisect`, `--only-failures` and `--next-failure`. I would be grateful if someone were to make a zsh plugin for this.

**Comment by mcornella** [comment]
You can use the one [at zsh-completions](https://github.com/zsh-users/zsh-completions/blob/master/src/_rspec).
