### ISSUE TITLE
oh-my-zsh cost 3-5 seconds to login

### ISSUE THREAD

**Issue by gaozp** [robbyrussell/oh-my-zsh#5279]
Every time I open a new terminal , It will cost about 3-5 second to login ,and during that moment , I couldn't do anything about this terminal .
I can't post my screenshot..

**Comment by gaozp** [comment]
https://gist.github.com/gaozp/75bef1078841c64314c863821b47f3e4

**Comment by gaozp** [comment]
After I uninstall omz, it also reduces, so it seems nothing concerned with omz, Close this issue.

**Comment by devondragon** [comment]
I am having the same issue... started within the last couple of weeks.  @gaozp were you able to figure out what it was?

**Comment by gaozp** [comment]
@devondragon I use mac OS , I don't know which platform you use. here is my solution 
 `sudo rm /private/var/log/asl/*.asl`
when I deleted the asl files , really reduce the login time.

**Comment by devondragon** [comment]
Yes, that solved it for me as well.  Thanks!
