### ISSUE TITLE
pj will report files as projects for autocomplete

### ISSUE THREAD

**Issue by niderhoff** [robbyrussell/oh-my-zsh#5284]
If you do

    $ pj <TAB>

it will show you an autocomplete-list of projects. However, it also includes files in the base of your Project-directory-tree, i.e.

    $ pj <TAB>
    Directory1/ Directory2/ file1.ext file2.ext

Of course, autocompleting to a file leads to an error:

    No such project file1.ext

possibly related to #5267

**Comment by mcornella** [comment]
PR #5296 should fix this. Please test.
