### ISSUE TITLE
golang and git plugin alias conflict

### ISSUE THREAD

**Issue by hjpotter92** [robbyrussell/oh-my-zsh#5288]
We have the line#183 in [`golang.plugin.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/golang/golang.plugin.zsh#L183):

    alias gfa='go fmt . ./...'

And, in the [`git.plugin.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L90), line#90:

    alias gfa='git fetch --all --prune'
One of those should be modified to avoid conflicts.

**Comment by hjpotter92** [comment]
This issue is a duplicate of #5214

**Comment by mcornella** [comment]
Please +1 #5259 if you like that.
