### ISSUE TITLE
How ssh autocomplete hosts list is being generated?

### ISSUE THREAD

**Issue by syabro** [robbyrussell/oh-my-zsh#5293]
I see a bunch of hosts that I don't want to see there. How to remove em?

**Comment by ykl7** [comment]
@syabro editing `.ssh/known_hosts` and restarting the shell should do the job

**Comment by ruchern** [comment]
@ykl7 That method did not work.

**Comment by mcornella** [comment]
I think it also uses `/etc/hosts` and `.ssh/config`.
