### ISSUE TITLE
zsh update gave me a parse_git_dirty error

### ISSUE THREAD

**Issue by wendyl2017** [robbyrussell/oh-my-zsh#5295]
prompt_git:4: command not found: parse_git_dirty

The recent update to oh my zsh has created the above error whenever I run any command now in iTerm2. I've only been able to find outdated (2012) information on this error and it's been pretty vague. Any ideas on how I can either roll back zsh or eliminate this error? Thanks!

**Comment by mcornella** [comment]
I'd recommend two possible solutions:

1. `rm ~/.zcompdump*` and restart the shell.

2. `cd $ZSH; git reset --hard origin/master` after updating (this will delete any local modifications you had on the repository).

If you're not comfortable doing (2), perhaps you can paste the output of `cd $ZSH; git status` and `git rev-parse HEAD`.

**Comment by wendyl2017** [comment]
I appreciate the feedback, although the solutions didn't work for me. One of my coworkers had a solution, but unfortunately while it did get rid of the error, it kind of ripped my system apart. He suggested we run git config --global core.autocrlf false and delete .zshrc and .oh-my-zsh. It took a lot of restoration to get everything back the way I had it. Just wanted to post this here as a what not to do, or to do as a last resort, just in case anyone else thought of doing the same.

**Comment by mcornella** [comment]
Thanks for the update.

**Comment by Pramodmahali** [comment]
I faced same issue, I have been changed the path "# export PATH=$HOME/bin:/usr/local/bin:$PATH". After changed zsh config file (.zshrc) I was unable to access my terminal. I tried to fix the file whatever I changed by sed command in **New Command** line but not success.

Then finally I changed my zsh shell to bash shell by manually.

![image](https://user-images.githubusercontent.com/51443973/81242168-0e3b1280-902a-11ea-982f-883904451bfa.png)

![image](https://user-images.githubusercontent.com/51443973/81242210-2743c380-902a-11ea-9716-e3fadbfa695d.png)
