### ISSUE TITLE
how to Remove random theme loaded text?

### ISSUE THREAD

**Issue by himanshurajkandel** [robbyrussell/oh-my-zsh#5297]
[oh-my-zsh] Random theme '/home/user/.oh-my-zsh/themes/flazz.zsh-theme' loaded... it's kinda look irritating, any possiblity to remove this,,,,

**Comment by himanshurajkandel** [comment]
Answer to myself :P 
$ gedit ~/.oh-my-zsh/oh-my-zsh.sh Goto , Line 102 and edit that with your desired text :)

**Comment by mcornella** [comment]
What would you like there to be?

**Comment by himanshurajkandel** [comment]
nothing, i just used figlet command , to make mine terminal better

**Comment by maxiqboy** [comment]
Now, it looks like it changed to this file:
```bash
edit ~/.oh-my-zsh/themes/random.zsh-theme
```

In this time I'm writing this, it located in line 38, and I change to : `echo "Theme '${RANDOM_THEME}' loaded"` for shorter display.

**Comment by thinh105** [comment]
Look like after update, it lost that and I have to come back this very topic to do it again :D
