### ISSUE TITLE
Bash for Windows and wrong home/end/del

### ISSUE THREAD

**Issue by monkeysuffrage** [robbyrussell/oh-my-zsh#5301]
The home/end/del keys aren't working properly with Bash for Windows.
How about an option to map them to ^A, ^E, ^D like you have for ^H ??

**Comment by mcornella** [comment]
Maybe. What character codes do they send? Press <key>CTRL</key>+<key>V</key> and then the key to see the character code.

**Comment by apjanke** [comment]
What do you want to bet that the Home and End behaviors are related to `smkx`/`rmkx`?

**Comment by mcornella** [comment]
On latest version of OMZ:
```
Home: ^[OH
End: ^[OF
Del: ^[[3~
```

With #5113 merged:
```
Home: ^[[H
End: ^[[F
Del: ^[[3~
```

In both these cases the keys do their job well. 

Here's the bindkey setup:
```
$ bindkey '^[OH'
"^[OH" beginning-of-line
$ bindkey '^[OF'
"^[OF" end-of-line
$ bindkey '^[[3~'
"^[[3~" delete-char
```

I'm using Windows 10 Anniversary Update btw. You can find those character codes with `CTRL`+`V` followed by the key; follow [this screencast if you're unsure about that](https://asciinema.org/a/ejxdamcgxew2qlmyb8gdnrxeh).

**Comment by mcornella** [comment]
Closing because it seems to work fine on my end and there's no response. You would better direct your inquiries to [BashOnWindows](official repository).
