### ISSUE TITLE
Completion feature hides the content

### ISSUE THREAD

**Issue by VSRahul** [robbyrussell/oh-my-zsh#5302]
I am using the latest version of Oh my ZSH (v5.0.8) on Mac OS X El Capitan (v10.11.6).

When I try to use the tab completion feature with `g++ -`, I get all the options available but the content (with width beyond the window) overflows and gets hidden. It would be great if the text wraps to show the content in the next line. I've attached 2 images for showing the problem:

![sample-1](https://cloud.githubusercontent.com/assets/6072276/17647417/77817518-620c-11e6-8ccf-85e8b363a568.jpg)
![sample-2](https://cloud.githubusercontent.com/assets/6072276/17647418/782da9e6-620c-11e6-9218-8cff5a06e6de.jpg)

And it's not just with `g++`, but the same thing happens with other plugins like `git`, `wget`, etc.

**Comment by mcornella** [comment]
It should paginate over the completion results in a `less`-like manner. See:
 
![screenshot  2016-08-14 16-25-35](https://cloud.githubusercontent.com/assets/1441704/17649723/f96276ca-623b-11e6-84c3-a14d5f500b5e.png)

Please post the output of `setopt` and `zstyle`.

**Comment by mcornella** [comment]
Nevermind, I understood the problem now. Let me have a look at the completion docs.

**Comment by VSRahul** [comment]
> Please post the output of `setopt` and `zstyle`.

Here's the output

```bash
➜  ~ setopt     
alwaystoend
autocd
autopushd
combiningchars
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
```

```bash
➜  ~ zstyle
cache-path
        :completion::complete:* /Users/rahul/.oh-my-zsh/cache/
command
        :completion:*:*:*:*:processes 'ps -u rahul -o pid,user,comm -w -w'
ignored-patterns
        :completion:*:*:*:users adm amanda apache at avahi avahi-autoipd beaglidx bin cacti canna clamav daemon dbus distcache dnsmasq dovecot fax ftp games gdm gkrellmd gopher hacluster haldaemon halt hsqldb ident junkbust kdm ldap lp mail mailman mailnull man messagebus mldonkey mysql nagios named netdump news nfsnobody nobody nscd ntp nut nx obsrun openvpn operator pcap polkitd postfix postgres privoxy pulse pvm quagga radvd rpc rpcuser rpm rtkit scard shutdown squid sshd statd svn sync tftp usbmux uucp vcsa wwwrun xfs '_*'
list-colors
        :completion:*:*:kill:*:processes '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
        :completion:* ''
matcher-list
        :completion:* 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
menu
        :completion:*:*:*:*:* select
single-ignored
        * show
tag-order
        :completion:*:cd:* local-directories directory-stack path-directories
url-globbers
(eval)  :url-quote-magic 'zmodload -i zsh/parameter;
	 reply=( noglob
		 ${(k)galiases[(R)(* |)(noglob|urlglobber|globurl) *]:-}
		 ${(k)aliases[(R)(* |)(noglob|urlglobber|globurl) *]:-} )'
url-local-schema
        :urlglobber ftp file
url-metas
        :url-quote-magic:* '*?[]^(|)~#{}='
url-other-schema
        :urlglobber http https ftp
url-seps
(eval)  :url-quote-magic:* 'reply=(";&<>${histchars[1]}")'
use-cache
        :completion::complete:* 1
```

**Comment by mcornella** [comment]
I didn't find anything after weeks of searching. Sorry this took so long. You'll have better luck asking directly to the [zsh-users mailing list](http://www.zsh.org/mla/).
