### ISSUE TITLE
^ symbol not recognized with zsh shell.-

### ISSUE THREAD

**Issue by jimsrc** [robbyrussell/oh-my-zsh#5305]
Hi,
I use `git diff HEAD^` commands-like very often.
But since some "days" ago, I have to use `git diff HEAD\^` now.

Don't know what happened exactly in these "days"; for sure, I installed `bundle`, `ruby` and `jekyll`.
That's the only funny thing that happened in these "days" (I checked my `~/.zsh_history`).
I really don't know exactly where to report this, since I didn't find similar cases in the web (I already googled "jekyll, ruby, zsh, arrow up, etc").

This persists even if I delete my `~/.zshrc`. 
However in bash, `git diff HEAD^` works normal.

Any pointers is very appreciated!
Thank you!!

**Comment by mcornella** [comment]
`^` (caret symbol) is a globbing character, used to indicate `except` (so `ls ^.git` would list files and directories except `.git`). This only works if `setopt extended_glob` is enabled.

I don't know what "happened" but if you want to not care about that you can alias git like so: `alias git='noglob git'`. That way there is no globbing enabled for the git command and you can do `git diff HEAD^` however you like.

**Comment by jimsrc** [comment]
Thank you very much mcornella!

**Comment by januszm** [comment]
I'd like to turn this option off permanently for ZSH but unfortunately setting:

```sh
unsetopt extended_glob
```
in `~/.zshrc` doesn't help. Probably it's overridden by some oh-my-zsh functions .

**Comment by mcornella** [comment]
See https://github.com/ohmyzsh/ohmyzsh/issues/8588#issuecomment-580907415
