### ISSUE TITLE
Agnoster theme doesn't work on konsole

### ISSUE THREAD

**Issue by abhigenie92** [robbyrussell/oh-my-zsh#5309]
I am using kde 5.6 plasma with kubuntu 16.04.
![image](https://cloud.githubusercontent.com/assets/12474640/17680971/9c199784-6360-11e6-9b87-9a05d330d778.png)
In the above screenshot the below konsole shows the prompt incorrectly while Yakuake above shows it fine.

Here's what my zshrc ~~and bashrc~~ (not necessary).
I also want to remove the username@computername somehow from the prompt.

~/.zshrc
```
export ZSH=/home/abhishek/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git rvm rails laravel5 laravel4)

source $ZSH/oh-my-zsh.sh
```

**Comment by BenoitAverty** [comment]
To remove the context segment (username@computername) you have to set the DEFAULT_USER variable in your zshrc. This segment will disappear if the user is equal to the content of that variable.

For the prompt, it's probably a font issue. You need to use a powerline-patched font in the terminal (note that the terminal is not the shell. zsh is the shell, konsole is the terminal emulator). Go in the konsole settings and choose an appropriate font, for example the one that's probably set in your other terminal emulator.

**Comment by mcornella** [comment]
@abhigenie92 are both windows from Konsole? If so, are they from the same computer or is one on ssh?

**Comment by mcornella** [comment]
Did you figure this out?

**Comment by abhigenie92** [comment]
@mcornella Hi! Thanks for asking. The directions in the earlier comment (https://github.com/robbyrussell/oh-my-zsh/issues/5309#issuecomment-240333061) made it work.

**Comment by mcornella** [comment]
Ok thanks!
