### ISSUE TITLE
go tool pprof autocomplete plugin errors

### ISSUE THREAD

**Issue by syslot** [robbyrussell/oh-my-zsh#5310]
The autocomplete for **go tool pprof** throws errors when trying to autocomplete.

**Steps to reproduce**:
```
- install golang
- console  type : go tool pprof -
```

Then zsh throws errors like below:
>_arguments:comparguments:312: invalid option definition: -functions[report at function level [default]]
_arguments:comparguments:312: invalid option definition: -functions[report at function level [default]]
_arguments:comparguments:312: invalid option definition: -functions[report at function level [default]]

**System details**:
- Mac OS X v10.11.6
- go1.7.darwin-amd64
- zsh 5.2 (x86_64-apple-darwin15.0.0)

**Comment by mcornella** [comment]
Do you have the `go`/`golang` plugin enabled? If not, this must be an issue with official completion itself.

**Comment by syslot** [comment]
Well, @mcornella , I have tried add **go** in to zshrc and now it works. Thank you very much!
