### ISSUE TITLE
Dual prompt

### ISSUE THREAD

**Issue by adriandeveloper** [robbyrussell/oh-my-zsh#5312]
![screen shot 2016-08-16 at 1 06 05 pm](https://cloud.githubusercontent.com/assets/3031275/17710308/46c140d2-63b2-11e6-8ac6-4ad524e4a673.png)

When I switch themes other than the default that loads with .oh-my-zsh, I get two prompts.  Doubt this is so much a bug but a config setting.  How do I hide the top most prompt in .oh-my-zsh?  

I'm using iTerm 2 as my terminal.

**Comment by adriandeveloper** [comment]
Can be closed. Figured out what the issue was.  Thanks. :)

**Comment by mcornella** [comment]
For another occasion, you can close the issue as well. Thanks!
