### ISSUE TITLE
gh alias is used by NodeGH tool

### ISSUE THREAD

**Issue by fernandosouza** [robbyrussell/oh-my-zsh#5313]
Hello guys. The gh alias used by *git plugin* is overwriting the CLI command of NodeGH http://nodegh.io

**Comment by leoj3n** [comment]
Same problem for gitsome: https://github.com/zsh-users/zsh-completions/issues/438

**Comment by mcornella** [comment]
Fixed in 76821f50. Sorry for the inconvenience!

**Comment by fernandosouza** [comment]
Thanks @mcornella.

Cc. @henvic
