### ISSUE TITLE
pj plugin improvement

### ISSUE THREAD

**Issue by Trevor-L** [robbyrussell/oh-my-zsh#5323]
@mcornella 
`pj` was recently updated to force the user to specify a project directory.  Previously just by typing `pj` on the command line you would get the first directory in the `PROJECT_PATHS` list e.g.

```sh
export PROJECT_PATHS=(~/Projects ~/Projects/java)
-> pj
# cd ~/Projects
```

Could this check be removed by default leave and an optional export for a `PJ_STRICT` env variable that would enforce the project being specified?

**Comment by mcornella** [comment]
This was also complained about in https://github.com/robbyrussell/oh-my-zsh/issues/5266#issuecomment-239676037. I've reverted the change in 774c4ec.
