### ISSUE TITLE
REPORTTIME

### ISSUE THREAD

**Issue by Im3lo0sh** [robbyrussell/oh-my-zsh#5331]
Hi,
I am using Arch linux
I use REPORTTIME feature my zshrc using export REPORTTIME=0 ( want every command to get reported ) 
using zsh 5.2-1 and oh-my-zsh-git from aur
my zshrc 
>ZSH=/usr/share/oh-my-zsh/
>REPORTTIME=0
>ZSH_THEME="agnoster"
>DISABLE_AUTO_UPDATE="true"
>ENABLE_CORRECTION="true"
>COMPLETION_WAITING_DOTS="true"
>HIST_STAMPS="yyyy-mm-dd"
>plugins=(git command-not-found)
>export LANG=en_US.UTF-8
>export EDITOR="vim"
>export ARCHFLAGS="-arch x86_64"
>ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
>if [[ ! -d $ZSH_CACHE_DIR ]]; then
>  mkdir $ZSH_CACHE_DIR
>fi
>source $ZSH/oh-my-zsh.sh
>source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

but everytime I execute command get reported with

> ali@Dell  ~   echo Hi
>Hi   
> 0.00s user 0.00s system 0% cpu 0.003 total                                    
> 0.00s user 0.00s system 0% cpu 0.002 total

after using the default zshrc I dont get reported with 2 outputs
using the method from [http://superuser.com/questions/735660/whats-the-zsh-equivalent-of-bashs-prompt-command](url) to execute time before every command I got
> ali@Dell  ~  echo Hi
>Hi
>shell  0.60s user 0.09s system 0% cpu 9:58.11 total                             
>children  0.20s user 0.03s system 0% cpu 9:58.11 total

How do I remove the shell reported time `shell  0.60s user 0.09s system 0% cpu 9:58.11 total ` or in the first example `0.00s user 0.00s system 0% cpu 0.003 total`
thank you .

**Comment by bderrly** [comment]
This is likely because you're seeing literally every command run on the shell, including the pre-/post-commands that are run behind the scenes by oh-my-zsh. For example, in a git directory you'll possibly end up with six reports (as I did) as it tries to figure out which branch I'm in and what the commit is. In other words, you probably do not want it set to zero.

**Comment by Im3lo0sh** [comment]
thank you
after setting REPORTTIME=5 problem solved

**Comment by Im3lo0sh** [comment]
thank you
after setting REPORTTIME=7 problem solved
