### ISSUE TITLE
npm.plugin.zsh:4: command not found: npm

### ISSUE THREAD

**Issue by termosa** [robbyrussell/oh-my-zsh#5332]
I've just updated my oh-my-zsh:

```bash
/Users/username/.oh-my-zsh/plugins/npm/npm.plugin.zsh:4: command not found: npm
/Users/username/.oh-my-zsh/plugins/npm/npm.plugin.zsh:source:7: no such file or directory: /Users/username/.oh-my-zsh/cache//npm_completion
```

**npm** is available in my shell.
I don't know which information to provide for you to help to fix it. 😞

**Comment by Kevin-Lee** [comment]
I'm having the same problem.

**Comment by mcornella** [comment]
You probably have the `export PATH` statement to far down the zshrc file (at one point in time we had it below the `source oh-my-zsh.sh` line). Have [a look at the current zshrc template](https://github.com/robbyrussell/oh-my-zsh/blob/9e81b79/templates/zshrc.zsh-template#L1-L2), I'd advise you put the `export PATH` line there.

Also, I've updated the npm plugin to check if `npm` exists before attempting to load its completion (commit 136a8343), please update OMZ.

**Comment by termosa** [comment]
@mcornella thank you!
@Kevin-Lee cut this row in `.zshrc`:
```bash
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"
```
and moved it above
```bash
source $ZSH/oh-my-zsh.sh
```

**Comment by mcornella** [comment]
Hey guys, my previous fix had an error, I've pushed the new fix at 4f15bd1. You should update OMZ again. Sorry for the inconvenience!

**Comment by termosa** [comment]
Wow, it was fast.
So, for those who has this problem now, run:
``` bash
zsh .oh-my-zsh/tools/upgrade.sh
```
Thank you @mcornella !

**Comment by neemah** [comment]
> zsh .oh-my-zsh/tools/upgrade.sh

didn't help :(

**Comment by mcornella** [comment]
There's a dedicated function for updating called `upgrade_oh_my_zsh`. That should be enough.

**Comment by neemah** [comment]
<img width="827" alt="screenshot 2016-09-09 22 34 44" src="https://cloud.githubusercontent.com/assets/212695/18400247/0b9e30d6-76e6-11e6-88b8-81ba628e88e0.png">
<img width="879" alt="screenshot 2016-09-09 22 34 52" src="https://cloud.githubusercontent.com/assets/212695/18400249/0cbcc126-76e6-11e6-92dd-9d6732141eee.png">

**Comment by mcornella** [comment]
What do you get running `npm completion`?

**Comment by mcornella** [comment]
I've fixed what seemed to be your problem. You have a broken `npm` (see the error _env: node: No such file or directory_). Try to fix your npm command and you'll have this working again.
