### ISSUE TITLE
Autocomplete the last word still here

### ISSUE THREAD

**Issue by C1tas** [robbyrussell/oh-my-zsh#5340]
when i click tab the last word still here

![](https://camo.githubusercontent.com/e4329790b66bef72aaf1dee1ad212804299ed05a/687474703a2f2f37786f6d72752e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f73686f742d323031362d30382d32355f30382d35362d31382e706e67)

as you can see the word `so` can't delete

![](https://camo.githubusercontent.com/c32cfa19702bce8bdcd7ff0db2db25b2d2003b4b/687474703a2f2f37786f6d72752e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f73686f742d323031362d30382d32355f30382d35392d34322e706e67)

how can i fix it ? thanks plz

**Comment by mcornella** [comment]
Post your zshrc file please.

**Comment by C1tas** [comment]
I haven't change the default config file , I only change the theme, but the problem in every theme, my system is `archlinux` and `zsh` version is `5.2.1`

**Comment by C1tas** [comment]
@mcornella .And I only use zsh ,there isn't any problem .I think oh-my-zsh case that problem
how can I fix it? close the autocomplete?

**Comment by C1tas** [comment]
there is something amazing, the theme `alanpeabody` works well, but how does the problem show up?

**Comment by C1tas** [comment]
`alanpeabody`,also has some problem when i make a mistake ,the cursor can cover the mark `$` like 
![](http://7xomru.com1.z0.glb.clouddn.com/shot-2016-08-26_09-30-39.png)

**Comment by mcornella** [comment]
That's weird. Please post the output of running `locale`.

**Comment by MiteshShah** [comment]
@mcornella Facing the same issue

```
╭ neo at Matrix in ~ using 16-10-13 - 15:56:58 
╰ ○ localocale 
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
![screen shot 2016-10-13 at 3 55 25 pm](https://cloud.githubusercontent.com/assets/1223371/19345763/9a09af12-915d-11e6-89c6-5b2697018c2a.png)

**Comment by MiteshShah** [comment]
@C1tas @mcornella Issue fixed by uncomment following line on ~/.zshrc

```
# You may need to manually set your language environment
 export LANG=en_US.UTF-8
```
