### ISSUE TITLE
display problem when I type more than one line

### ISSUE THREAD

**Issue by HParis** [robbyrussell/oh-my-zsh#5345]
1. There is something can't display when I type more than one line. In fact the image below hide the last two letters(FG) what I type.
![img](https://gitlab.com/gnachman/iterm2/uploads/2c704f24fd6c837da53a16811daf8ba5/image.png)

2. It shows the full content when I type return like the following image blow.
![img](https://gitlab.com/gnachman/iterm2/uploads/985c8a358ffdd44242b439d469edc2c4/image.png)

3. echo $PS1 | hexdump -C.
```
00000000  25 7b 25 66 25 62 25 6b  25 7d 24 28 62 75 69 6c  |%{%f%b%k%}$(buil|
00000010  64 5f 70 72 6f 6d 70 74  29 20 0a                 |d_prompt) .|
0000001b
```

**Comment by mcornella** [comment]
It seems you have a modified agnoster theme, can you post the content of `$ZSH/themes/agnoster.zsh-theme`?

**Comment by mcornella** [comment]
ping @HParis

**Comment by mcornella** [comment]
I don't know this looks like more of a customization problem and not an OMZ one. I can't reproduce. Feel free to reopen if you have more information.
