### ISSUE TITLE
ls colors not displayed

### ISSUE THREAD

**Issue by shaktigoap** [robbyrussell/oh-my-zsh#5349]
I've tried to figure out if I've missed something but the 'ls' command doesn't show up colorful output. Tried different methods but no results. Can somebody help me with this ?

PS - Screenshot added!

<img width="1064" alt="screen shot 2016-08-27 at 6 14 21 am" src="https://cloud.githubusercontent.com/assets/1829208/18023948/d50c8f54-6c1d-11e6-8b98-4c5b90914fa6.png">

**Comment by mcornella** [comment]
Try `ls --color=auto`, probably your `ls` is not aliased (do `which ls` to confirm).

**Comment by shaktigoap** [comment]
@mcornella I tried doing `ls --color=auto` but displays it as the illegal option. `ls` is aliased to `ls -G`. Here are the screenshots of `.zshrc` file as well.

<img width="962" alt="screen shot 2016-08-27 at 7 17 24 pm" src="https://cloud.githubusercontent.com/assets/1829208/18027933/63c6bed4-6c8e-11e6-888e-a54e302a24a5.png">
<img width="1280" alt="screen shot 2016-08-27 at 7 17 36 pm" src="https://cloud.githubusercontent.com/assets/1829208/18027934/63f70314-6c8e-11e6-886f-7547f362e4f0.png">
<img width="1053" alt="screen shot 2016-08-27 at 7 36 39 pm" src="https://cloud.githubusercontent.com/assets/1829208/18027935/640fac52-6c8e-11e6-9480-b039a32fde66.png">
<img width="1050" alt="screen shot 2016-08-27 at 7 38 32 pm" src="https://cloud.githubusercontent.com/assets/1829208/18027936/644b1062-6c8e-11e6-89c7-c9d68b76eb1c.png">

**Comment by samangh** [comment]
I see that the `ls` results are actually colored, but the colors are washed out becuase of the combination of your theme and the pale `LSCOLORS` chosen by oh-my-zsh.

You can revery back to the Oognal colors from OS X (which is a bit more colorful by running):
```
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1
````
That way the folders, symliks, etc will be colored. But to get coloring based on file extensions, you might want to look at [dircolors-solarized](https://github.com/seebi/dircolors-solarized).

**Comment by mcornella** [comment]
Oh yeah, you can see there are some colors, for instance directories appear bold. So the issue is with LSCOLORS.

**Comment by brando90** [comment]
I am confused. So does it matter where:

```
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1
```

does in the `.zshrc` script?

**Comment by brando90** [comment]
> I also had this problem and what was causing problems for me was using the GNU flavored utils that comes with `brew install coreutils`.
> 
> **This line was causing the problem**
> 
> ```shell
> export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
> ```
> 
> By commenting it out my colors came back. The `gnubin` folder contains replacements for a lot of the shell commands, such as `ls`, `cat`, `mkdir` etc.
> 
> So I was running `gls` instead of `ls`, and to use `gls` with colors I added this alias:
> 
> ```shell
> alias ls="gls --color=always"
> ```

how do you install that for mac/apple? seems brew install doesn't work

**Comment by brando90** [comment]
the problem remains to me. I cannot set my manual colors. The colors that come by default are to dark to read for me. How do I make the manual ones work?
```
LS_COLORS='di=1:fi=96:*.m=31:*.py=32:*.txt=36:*.out=35'
```

**Comment by yahkun** [comment]
> I see that the `ls` results are actually colored, but the colors are washed out becuase of the combination of your theme and the pale `LSCOLORS` chosen by oh-my-zsh.
> 
> You can revert back to the original colors from OS X (which is are bit more colorful by running):
> 
> ```
> unset LSCOLORS
> export CLICOLOR=1
> export CLICOLOR_FORCE=1
> ```
> 
> That way the folders, symlinks, etc will be colored. But to get coloring based on file extensions, you might want to look at [dircolors-solarized](https://github.com/seebi/dircolors-solarized).

This works for me. Thanks :)

**Comment by codeman101** [comment]
> I see that the `ls` results are actually colored, but the colors are washed out becuase of the combination of your theme and the pale `LSCOLORS` chosen by oh-my-zsh.
> 
> You can revert back to the original colors from OS X (which is are bit more colorful by running):
> 
> ```
> unset LSCOLORS
> export CLICOLOR=1
> export CLICOLOR_FORCE=1
> ```
> 
> That way the folders, symlinks, etc will be colored. But to get coloring based on file extensions, you might want to look at [dircolors-solarized](https://github.com/seebi/dircolors-solarized).

This worked for me as well. I don't knOw why it's hard set to the ls color scheme of the default theme. Adding those three lines to the end of the zshrc file did the trick.

**Comment by russell-shizhen** [comment]
> I also had this problem and what was causing problems for me was using the GNU flavored utils that comes with `brew install coreutils`.
> 
> **This line was causing the problem**
> 
> ```shell
> export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
> ```
> 
> By commenting it out my colors came back. The `gnubin` folder contains replacements for a lot of the shell commands, such as `ls`, `cat`, `mkdir` etc.
> 
> So I was running `gls` instead of `ls`, and to use `gls` with colors I added this alias:
> 
> ```shell
> alias ls="gls --color=always"
> ```

You are genius!

**Comment by RyanTippsTX** [comment]
> I am confused. So does it matter where:
> 
> ```
> unset LSCOLORS
> export CLICOLOR=1
> export CLICOLOR_FORCE=1
> ```
> 
> does in the `.zshrc` script?

Yes - it has to be placed anywhere _after_ the `source $ZSH/oh-my-zsh.sh` in the .zshrc file, otherwise it will be overwritten by oh-my-zsh.

**Comment by RyanTippsTX** [comment]
> the problem remains to me. I cannot set my manual colors. The colors that come by default are to dark to read for me. How do I make the manual ones work?
> 
> ```
> LS_COLORS='di=1:fi=96:*.m=31:*.py=32:*.txt=36:*.out=35'
> ```

Full explanation:

First, understand that oh-my-zsh includes a bunch of default aliasing, so when you run `ls` that is actually an alias for `ls -G`, which you could manually enter (or alias) in zsh without oh-my-zsh. 

Also, understand that the `ls` command is not actually part of zsh at all. When you run `ls` you are actually telling your shell to run an external executable which is located at `/bin/ls` on your Mac. 

You are on MacOS, which uses the [BSD implementation](https://www.freebsd.org/cgi/man.cgi?ls) of `ls`. There's also a GNU implementation of `ls` that MacOS does not come with. The BSD version and the GNU version have different ls colorization features and they are specified differently. The BSD ls colorization feature is more basic, whereas the GNU version allows you to specify different colors by file extension.

LSCOLORS is for the BSD version, 
LS_COLORS is for the GNU version, 
see the respective man pages for each.

If you want to use the GNU version on your mac, it looks like there's an option to install it via homebrew. 

Regardless of which version you decide to use, you need to make sure that your aliases & environment variables are set up properly so that the intended implementation of `ls` is called, that the correct flags / options are passed, and that the correct environment variables & their values are specified properly in your .zshrc file. See man pages for the respective version you want to use.

**Comment by philCryoport** [comment]
Q: is oh-my-zsh by default inserting `export CLICOLOR_FORCE=1` into the `.zshrc` file?

If so, why?  

I just lost nearly a day's worth of work time chasing down why I couldn't install an ocaml tool (see mention https://github.com/ocaml/ocamlfind/issues/40 ) -- and it turned out the cause was that `export CLICOLOR_FORCE=1` was in my `.zshrc`.  Once I commented that out and opened a completely new session, I had no issues installing that ocaml tool.

**Comment by mcornella** [comment]
> Q: is oh-my-zsh by default inserting `export CLICOLOR_FORCE=1` into the `.zshrc` file?

No

**Comment by philCryoport** [comment]
> > Q: is oh-my-zsh by default inserting `export CLICOLOR_FORCE=1` into the `.zshrc` file?
> 
> No

Weird.  I wonder where it came from?
```
# Colors.
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1
```

I know for certain I didn't put it in there by hand.  Perhaps the `spaceship` theme?  It's between my `rbenv` lines and before 
```
# Don't require escaping globbing characters in zsh.
unsetopt nomatch

# Nicer prompt.
# export PS1=$'\n'"%F{green} %*%F %3~ %F{white}"$'\n'"$ "
```

**Comment by philCryoport** [comment]
Ugh.  I found where it might have come from.

**Comment by rwmitchell** [comment]
Share?

**Comment by mcornella** [comment]
Looks like [this person's dotfiles](https://github.com/geerlingguy/dotfiles/blob/8489a049a4205fb4b20d2702f4e182cb5afe7214/.zshrc#L7-L16).

**Comment by philCryoport** [comment]
Correct.  [I opened a PR yesterday](https://github.com/geerlingguy/dotfiles/pull/10)

**Comment by philCryoport** [comment]
> Looks like [this person's dotfiles](https://github.com/geerlingguy/dotfiles/blob/8489a049a4205fb4b20d2702f4e182cb5afe7214/.zshrc#L7-L16).
> 
> EDIT: [sourcegraph.com is badass](https://sourcegraph.com/search?q=context:global+%23+Colors.%5Cnunset+LSCOLORS%5Cnexport+CLICOLOR%3D1%5Cnexport+CLICOLOR_FORCE%3D1&patternType=regexp).

That's awesome.  I will definitely be using that in the future

**Comment by simonliu009** [comment]
I finally found a solution.
In my case, I'm using `Solarized Dark` theme for `iTerm2` and built-in `terminal` . 
I just deselect the `Bold` option in `File->Preferences->Profiles->Colors->Basic Colors` in iTerm2.
And deselect `Use bright colors for bold text`.
![iterm2](https://user-images.githubusercontent.com/9347580/168763282-234504d0-890f-45ac-a5b6-de0d50f56bba.gif)
![terminal](https://user-images.githubusercontent.com/9347580/168763383-007428c1-d9b4-46d4-8b7d-142e9357cf08.gif)

**Comment by thsno02** [comment]
> ```shell
> alias ls="gls --color=always"
> ```

just run `alias ls="ls --color=always"`, it works for me
