### ISSUE TITLE
Windows subsystem for Linux: .oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'

### ISSUE THREAD

**Issue by ralekna** [robbyrussell/oh-my-zsh#5366]
Hi,

 I'm using WSL (Ubuntu emulation on windows) and after last oh-my-zsh update I get this error on terminal load:
`.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'`

Last commit in my oh-my-zsh is `3c8a33364f64975970839eeded921c3ed85ad507`.

**Comment by mcornella** [comment]
Solution: https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351
