### ISSUE TITLE
Django plugin is not listed in Plugins wiki

### ISSUE THREAD

**Issue by ShalbafZadeh** [robbyrussell/oh-my-zsh#5370]
there is [Django plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/django/django.plugin.zsh) for oh-my-zsh but is not listed in [plugins wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins)

**Comment by mcornella** [comment]
[Added](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#django). In the future, know that you can add it yourself, the wiki is publicly writable.

**Comment by ShalbafZadeh** [comment]
@mcornella sure , thanks marc :)
