### ISSUE TITLE
cat {file1,file2} > file3

### ISSUE THREAD

**Issue by mylamour** [robbyrussell/oh-my-zsh#5371]
cat {file1,file2} > file3
It's not support in zsh, but can be used with bash.

**Comment by mcornella** [comment]
It does work, at least on my end:
```
$ cat file1 
file1
$ cat file2
file2
$ cat {file1,file2}
file1
file2
$ cat {file1,file2} > file3
$ cat file3
file1
file2
```

That said, if this was a feature missing from zsh it wouldn't be an Oh My Zsh issue but a zsh one, therefore this wouldn't be the place to post that.

**Comment by mcornella** [comment]
If this doesn't work on your end, try starting zsh with `zsh -f` and run the above test.

**Comment by mylamour** [comment]
I know what's wrong with my zsh,  it was my problem. beacuse i always to type a  space. 
I am sorry about that and thank you very much.

**Comment by mcornella** [comment]
Oh right! There can be no space around the comma. Glad you solved it :smile:
