### ISSUE TITLE
Support pycharm embedded terminal - osx plugin

### ISSUE THREAD

**Issue by CrazyPython** [robbyrussell/oh-my-zsh#5375]
```
❯ tab
tab: unsupported terminal app: pycharm
```

**Comment by mcornella** [comment]
I don't think you can control the `pycharm` terminal with osascript. You should try [opening a new tab](https://www.jetbrains.com/help/pycharm/2016.1/working-with-embedded-local-terminal.html#d432323e252) with `CTRL`+`SHIFT`+`T` and see if that opens it in the same directory.
