### ISSUE TITLE
display not normal!

### ISSUE THREAD

**Issue by zhenglu1989** [robbyrussell/oh-my-zsh#5378]
![image](https://cloud.githubusercontent.com/assets/3859671/18269275/0d2054d6-745a-11e6-9307-f02546d8b8f4.png)

**Comment by mcornella** [comment]
This is a very frequent question, if you search the issues you'll find several answers. The summary is that you need to use a [Powerline font](https://github.com/powerline/fonts) for it to display these characters correctly.
