### ISSUE TITLE
how can I remove " master ●" label

### ISSUE THREAD

**Issue by sinmaystar** [robbyrussell/oh-my-zsh#5379]
How can I remove "master" label, in my computer I use "agnoster" theme

 ⚡ root@illsuionsMBP  ~   master ● 

**Comment by chancellorr** [comment]
Hey, I recently edited this theme to do exactly what you are asking. You can find it here. https://github.com/chancellorr/Random-stuff

I wish it would only show up if I was actually using Git because I do like having it.

**Comment by mcornella** [comment]
I imagine you're using the `agnoster` theme. If that's the case, you can delete the git prompt part by adding this to your zshrc file:
```
prompt_git() {}
```
