### ISSUE TITLE
themes not displayed properly when becoming root

### ISSUE THREAD

**Issue by MatrixCW** [robbyrussell/oh-my-zsh#5387]
When I issue the command sudo su, the theme (bira) cannot be displayed properly.
May I knwo how to fix that? I am using OSX 10.11.6.

<img width="644" alt="screen shot 2016-09-07 at 1 41 22 pm" src="https://cloud.githubusercontent.com/assets/3275948/18322550/3b23a66a-7501-11e6-8eda-d6f9aded4714.png">

**Comment by MatrixCW** [comment]
I also notice that some of the functionalities are not available as well, such as tab-complete, when I become root.

**Comment by Ellaylone** [comment]
Try installing oh-my-zsh with root account and then create symlink to .zshrc in your home directory aka
`ln -s /Users/user/.zshrc /var/root/.zshrc`
This fixed issue for me.

**Comment by mcornella** [comment]
You should either log in as root with `sudo -s -E`, or install ohmyzsh with your root user as well.
