### ISSUE TITLE
plugin:"last-working-dir" conflict with "open babun here" context menu

### ISSUE THREAD

**Issue by saccohuo** [robbyrussell/oh-my-zsh#5392]
When I add plugin `last-working-dir` to my plugin list, I find the context menu `Open Babun Here` does not work anymore.

Finally, I find the problem caused by `last-working-dir` as described `Jump to last working directory (automatically called for new shells)`.

So I want to know if there is a setting to disable the function to automatically jump to last working directory for new shells but keep the command `lwd` after new shell is established.

@op

**Comment by mcornella** [comment]
This is a known issue with the `last-working-dir` plugin: https://github.com/robbyrussell/oh-my-zsh/issues/3999#issuecomment-112233045. I'll leave this open until we patch that.

**Comment by mcornella** [comment]
Check out #5471, +1 it if it fixes your problem.

**Comment by saccohuo** [comment]
It does work.
