### ISSUE TITLE
/Users/ssteiner/.zshrc:15: command not found: antigen

### ISSUE THREAD

**Issue by ssteinerx** [robbyrussell/oh-my-zsh#5393]
Just started just now, maybe oh-my-zsh update went by without my noticing, but it's now very broken.

**Comment by mcornella** [comment]
That seems like you uninstalled `antigen` or you modified the `$PATH` variable and now it doesn't find the `antigen` binary. Please post your zshrc file.

**Comment by ssteinerx** [comment]
I reinstalled antigen from homebrew and am sourcing it from there.  I hadn't looked at it in a long while and spent quite a bit of time rearranging and organizing,  so whatever originally caused the issue is long gone.  I just wanted to make sure it wasn't a widespread issue that I should just pull an older version off github 'till it was fixed.
