### ISSUE TITLE
Error displayed when coreutils is in the path 

### ISSUE THREAD

**Issue by cscetbon** [robbyrussell/oh-my-zsh#5400]
Hey,

If my path is prepended with coreutils binaries path I get an error whenever I enter a command :
```
$ grep ^path ~/.zshrc                                                                                                                                
path=($(brew --prefix coreutils)/libexec/gnubin /usr/local/bin $path)

$ zsh                                                                                                                                                    
date: 10560: No such file or directory
```

**Comment by mcornella** [comment]
What do you get running `brew --prefix coreutils`?

**Comment by cscetbon** [comment]
I get the right path :

**Comment by mcornella** [comment]
Show me `print -l $path`. Are there any spaces in those directories?

**Comment by cscetbon** [comment]
```
$ print -l $path
/usr/local/opt/coreutils/libexec/gnubin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
date: 5760: No such file or directory
```

**Comment by mcornella** [comment]
That has to be something else unrelated to `$path`. What does `which -a date` throw? And post your zshrc file as well.

**Comment by mcornella** [comment]
*Or* perhaps there's a `date` command inside the coreutils folder that is all messed up.

**Comment by cscetbon** [comment]
I just tried to clean my zshrc and it really comes from coreutils. A small version of my zshrc http://pastebin.com/SJNQPmRv

```
$ which -a date
/usr/local/opt/coreutils/libexec/gnubin/date
/bin/date
date: 5640: No such file or directory
```

**Comment by mcornella** [comment]
You probably have an uncompatible `date` with [the powerlevel9k theme](https://github.com/bhilburn/powerlevel9k/blob/cef8c65/powerlevel9k.zsh-theme#L362). Run the following:

```zsh
raw_data="$(ioreg -n AppleSmartBattery | grep -E "MaxCapacity|TimeRemaining|CurrentCapacity|ExternalConnected|IsCharging")"
time_remaining=$(echo $raw_data | grep TimeRemaining | awk '{ print $5 }')
date -u -r $(($time_remaining * 60)) +%k:%M
```

**Comment by mcornella** [comment]
Edited the command to:
```zsh
date -u -r 5640 +%k:%M
/bin/date -u -r 5640 +%k:%M
```

**Comment by cscetbon** [comment]
yeah it's definitely the issue : 
```
$ date -u -r 5640 +%k:%M
1:34
$ /usr/local/opt/coreutils/libexec/gnubin/date -u -r 5640 +%k:%M
/usr/local/opt/coreutils/libexec/gnubin/date: 5640: No such file or directory
```

**Comment by mcornella** [comment]
It seems there's already a PR and a patch in progress: https://github.com/bhilburn/powerlevel9k/pull/279. Cheers!

**Comment by cscetbon** [comment]
oh, @mcornella I'm so sorry to have taken your time when there is already one opened ticket ... i wasn't aware of it

**Comment by mcornella** [comment]
No problem :wink:
