### ISSUE TITLE
zsh as default shell

### ISSUE THREAD

**Issue by ykl7** [robbyrussell/oh-my-zsh#5401]
Operating System : Ubuntu 16.04.1
Even after running :
```
sudo apt-get install zsh
sudo apt-get update
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```
and rebooting, zsh does not become default shell.

This has been the case on many machines with same OS configuration.

**Comment by rjrobinson** [comment]
`chsh -s $(which zsh)` should work.

**Comment by atk91** [comment]
Why do you `apt-get update` after `apt-get install zsh`?

**Comment by ykl7** [comment]
@rjrobinson tried that as well. Does not work on all systems though
@atk91 force of habit doing that, which is why i typed it out here as well

**Comment by mcornella** [comment]
Regarding `apt-get`, the appropriate pattern is update, then install.

About zsh, post the output of `which -a zsh` and `cat /etc/shells`.

**Comment by ykl7** [comment]
@mcornella about the `apt-get update` part, like I told @atk91 it's just a bad habit that I have, I update first, install a package, update again and then get to work. Trying to shrug it off though

Output of commands are-

`which -a zsh` : 
`/usr/bin/zsh`
`/bin/bash`

`cat /etc/shells` : 
`/bin/sh`
`/bin/dash`
`/bin/bash`
`/bin/rbash`
`/usr/bin/tmux`
`/usr/bin/screen`
`/bin/zsh`
`/usr/bin/zsh`

Sorry for the delay. Hope this is enough.

**Comment by mcornella** [comment]
> I update first, install a package, update again and then get to work

Oh I didn't get the `update first` part.

Based on your shell output `chsh -s $(which zsh)` should work always. If there's some system where that doesn't work post the result of the same commands on that system. Some systems don't have `/etc/shells` (like [the Termux Android app](https://github.com/robbyrussell/oh-my-zsh/pull/4564)) or `chsh` doesn't work because of lack of permission or zsh is not in `/etc/shells` (like in [college computers](https://github.com/robbyrussell/oh-my-zsh/issues/4131#issuecomment-149938314)).

I'll wait for the information of those systems where the shell change doesn't work. Cheers!

**Comment by ykl7** [comment]
@mcornella It is actually a college system I'm talking about. But I do have complete root access over on these systems/ The reason I opened this issue is that zsh changed into default shell on one such system but the same didn't happen on 2 other systems by following the same command.

What information do you want about the systems? I'll try to get them as soon as possible. Thanks!

**Comment by mcornella** [comment]
The same, `which -a zsh` and `/etc/shells` content.

**Comment by ykl7** [comment]
@mcornalla sorry it took so long but here is the output i obtained on 3 different systems, none of which had zsh as the default shell even though i followed the correct steps.

`which -a zsh` :
`/usr/bin/zsh`
`/bin/zsh`

`cat /etc/shells` :
`/bin/sh`
`/bin/dash`
`/bin/bash`
`/bin/rbash`
`/bin/zsh`
`/usr/bin/zsh`

**Comment by mcornella** [comment]
All looks good, it should work without problem. How did you run the installer? Was it `curl http... | sh` or `sh -c $(curl http...)`?

**Comment by ykl7** [comment]
@mcornella I used `sh -c $(curl ...)` like [ohmyzsh](ohmyz.sh) suggests.
It works without any problems on some computers. On other computers with the same configuration, it doesn't.

**Comment by mcornella** [comment]
What's the output you get for `chsh -s $(which zsh)` in those computers were it fails?

**Comment by ykl7** [comment]
Hey @mcornella sorry for the late reply. I get access to my college systems only once a week.
`chsh -s $(which zsh)` results in no output in the shell prompt. By rebooting, bash shell is still the default shell, not zsh.

**Comment by mcornella** [comment]
It is very possible that you can't use chsh in your college. You should instead add code to your `.bashrc` file (or `.bash_profile`) to automatically start zsh:

```bash
if [[ $- == *i* ]]; then
    export SHELL=zsh
    zsh -l
fi
```

The if checks that you're running in interactive mode. 

As per chsh not outputting anything, it's possible that it just exits with an error code (`echo $?` shows that).

You can also contact your college tech support to be sure that you can't use chsh.

I hope this settles it. Reopen if necessary.

**Comment by mcornella** [comment]
UPDATE: the proper script is the following:

```bash
if [[ $- == *i* ]]; then
    export SHELL=zsh
    exec zsh -l
fi
```

**Comment by ykl7** [comment]
@mcornella I'll look into adding the script you mentioned into my `.bash_profile`. Thanks for the help

**Comment by Renrhaf** [comment]
+1 for the script above, it's working properly

**Comment by gbdsantos** [comment]
thanks of a lot @mcornella :rocket: :tada:
