### ISSUE TITLE
ssh-agent not forwarded on OS X

### ISSUE THREAD

**Issue by webOS101** [robbyrussell/oh-my-zsh#5406]
I recently upgraded oh-my-zsh and now I am prompted to enter my ssh key passphrase each time.  ssh-agent is running on the mac, but the environment variable pointing to the ssh-agent is not set on zsh anymore.  I see in the recent commit history work on ssh-agent.  Is this related?

System is OS X 10.10.5.

**Comment by sollie** [comment]
I've also had this issue lately. Can't remember exactly when it started, but it's driving me slowly insane.

**Comment by sollie** [comment]
This seems to have been fixed by 5bd9500.

**Comment by webOS101** [comment]
Fixed a long time ago so closing this out.
