### ISSUE TITLE
Autocomplete doesn't recognize filename with number after dot

### ISSUE THREAD

**Issue by kiquetal** [robbyrussell/oh-my-zsh#5407]
#[/home/Documents]/ tree                   
.├── file.2016jar
 └── file.jar
When type java -jar file <THEN TAB> only file.jar is listed

Please remove if this is not an issue,best regards!

**Comment by mcornella** [comment]
You lack an extra dot. The extension should be `.jar`, that's why `java -jar` is not recognising it.
