### ISSUE TITLE
zsh: can't open input file: /tools/check_for_upgrade.sh

### ISSUE THREAD

**Issue by extink** [robbyrussell/oh-my-zsh#5409]
Every time when I try to open an zsh shell I get this error
```zsh: can't open input file: /tools/check_for_upgrade.sh```

**Comment by nicolaifsf** [comment]
I get something similar
```
/tools/check_for_upgrade.sh:3: failed to load module `zsh/datetime': dlopen(/usr/lib/zsh/5.0.8/zsh/datetime.so, 9): image not found
_current_epoch:1: bad math expression: operand expected at `/ 60 / 60 ...'
```

**Comment by extink** [comment]
This issue I described has resolved itself, do not know how and when. But after one of the updates it did not happen again.

@nicolaifsf: if you still have the issue you described, please open an new issue, as my issue is different than the one you are having.
