### ISSUE TITLE
bindkey -v breaks arrows

### ISSUE THREAD

**Issue by TxHawks** [robbyrussell/oh-my-zsh#5410]
When I set `bindkey -v`, either from the cli itself, directly in `.zshrc` or using the `vi-mode` plugin, the arrow keys print what seems to be `back` <char> `newline`, white char being `A` for the `up arrow`, `B` for the `down arrow`, `D` for the `left arrow` and `C` for the `right arrow`. This doesn't happen in emacs mode.

If examined with `ctrl-v`, the `left`, `top`, `right` and `down` arrows produce `^[OD`, `^[OA`, `^[OC` and `^[OA`, respectively, which means, vi-mode interprets them a `esc`, `O` (open line above), <letter>.

Any ideas on how to get around this would be greatly appreciated.

**Comment by TxHawks** [comment]
I just noticed that this only happens when I log in through ssh from a windows machine.

**Comment by okapia** [comment]
What have you got $KEYTIMEOUT set to? Perhaps it is set to something too low.

**Comment by softmoth** [comment]
I assume this issue can be closed?
