### ISSUE TITLE
docker completion arguments for a command

### ISSUE THREAD

**Issue by ivanovaleksey** [robbyrussell/oh-my-zsh#5411]
Hi guys.
I started to learn Docker and decided to enable docker plugin to see all commands and options.
But I noticed that completion for arguments of a particular command works very strange.
So my steps (and steps to reproduce ) are:

- write `docker[space]` or select it from completion and press `tab`
- the output would be a list of all commands 👍 

- select a command (e.g. `image`), so it would be `docker images[space]`

- press `tab` to see arguments for the command. It complete command with only one dash so it would be `docker images -`
- press `tab` again  and here comes strange things like
![image](https://cloud.githubusercontent.com/assets/11523473/18503685/ffce054a-7a66-11e6-839a-cfb02ff97dc9.png)

So the output is not formatted. But I noticed that if it would be two dashes at the end i.e. `docker images --` and press `tab` the output would be pretty and clear (as expected).

I don't know much how zsh completion works so I don't know how to fix it (or should be fixed whether). But if you give some advice I would try to do my best.

Thanks.

**Comment by ivanovaleksey** [comment]
It seems like with `docker ps` command everything is fine (no matter one or two dashes at the end).
Maybe it is because `images` completion call `__docker_images` at the end and `ps` doesn't? 
It is the only difference I can see.

**Comment by mcornella** [comment]
The docker completion in OMZ was outdated. #5354 should solve this problem.

Also, please check if you have docker zsh completion installed by posting the output of running the following:
```
for d ($fpath); do [[ -f "$d/_docker" ]] && print -l "$d/_docker"; done
```

**Comment by ivanovaleksey** [comment]
Thanks Marc. I also noticed that it was outdated because some arguments was deprecated and now are not supported.

Tha command gives 
`/Users/aivanov/.oh-my-zsh/plugins/docker/_docker`

**Comment by mcornella** [comment]
Ok, I see your docker completion wasn't automatically installed with docker. I won't delete the docker completion from OMZ because some of you won't have an alternative. How did you install docker, if I may ask?

**Comment by ivanovaleksey** [comment]
On this particular machine is running on MacOS so I install docker with dmg package from [here](https://www.docker.com/products/docker#/mac).
I could easily remove it and install with the way you provide because I didn't do anything yet.

**Comment by mcornella** [comment]
I was asking because in the Debian and Ubuntu installers the official docker completion is installed in `/usr/share/zsh/vendor-completions/_docker`.

I see the official installer for Mac doesn't install a completion, so it's better I don't delete the completion from OMZ even if it may become outdated. I'll see if I can find a better solution because OMZ forces to use the plugins completion, regardless of whether there is a more updated completion...

Thanks for your information!

**Comment by ivanovaleksey** [comment]
Not at all Marc.
Thanks for the explanation and help!
