### ISSUE TITLE
Blinks theme: Add time above current history event number

### ISSUE THREAD

**Issue by rbjorklin** [robbyrussell/oh-my-zsh#5414]
Would it be possible to have the time added above the current history event number for the [blinks theme?](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#blinks).

**Comment by mcornella** [comment]
You can modify the `PROMPT` variable yourself with [prompt expansion sequences](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Date-and-time) to show the time. You can look at the bureau or candy themes to get a general sense of how they do it.
