### ISSUE TITLE
where should i put my aliases

### ISSUE THREAD

**Issue by YUFENGWANG** [robbyrussell/oh-my-zsh#5419]
I am just wondering it's too bad to put all my aliases in the .zshrc. where can i put  them instead?

**Comment by cosmosgenius** [comment]
You can always create a separate aliases file and source it inside your .zshrc file. For ref check https://github.com/thoughtbot/dotfiles/blob/master/zshrc

**Comment by mcornella** [comment]
If you don't have many aliases there's no need to separate them. But if you want to separate them you can put them at `$ZSH/custom/aliases.zsh` and ohmyzsh will source them automatically (the `.zsh` extension is important).
