### ISSUE TITLE
Tab autocompletion for files breaks with some extensions

### ISSUE THREAD

**Issue by foxx** [robbyrussell/oh-my-zsh#5436]
Tab autocompletion seems to break for some file extensions, but I'm not sure why. Normally when hitting tab you'd be given a list of files that match which you can select through, but when using `.coffee` files this seems to break.

I've recorded this here;
https://asciinema.org/a/dltligujkuo5do1jcnuwuiopl

**Comment by mcornella** [comment]
This looks like the until recent bug regarding hyphens and underscores in files. Update your OMZ with `upgrade_oh_my_zsh` and it should work well.

**Comment by foxx** [comment]
Ah yeah, that fixed it, thank you :)
