### ISSUE TITLE
Tab auto-completion hangs the terminal (macOS Sierra)

### ISSUE THREAD

**Issue by alextegelid** [robbyrussell/oh-my-zsh#5437]
Since upgrading to macOS Sierra earlier today I can't use the tab completion in zsh while running Oh My Zsh or it will hang that terminal session. Running zsh without Oh My Zsh works fine.

I've upgraded o the latest release of Oh My Zsh and I'm running the pre-builtin Z shell in macOS Sierra: `zsh 5.2 (x86_64-apple-darwin16.0)`.

Let me know if you need any additional information.

**Comment by alextegelid** [comment]
Actually it seems to hang the zsh process so hard I can't normally reboot my laptop, but instead I have to kill it by holding the power switch down for a couple of seconds.

**Comment by alextegelid** [comment]
Having reinstalled Antigen (forgot to mention I'm using that package manager) and updated oh-my-zsh via `antigen update` it seems to work. I'm not sure where in that process it started working...

**Comment by alextegelid** [comment]
I'm not sure how that is meant to be used. I tried `functions -t cd` but that immediately froze that session.

Anyway, it works for the moment. I'll let you know if something comes up.

**Comment by mcornella** [comment]
The underscore before command is important, that's the conventional name of completion functions; `_cd` in your case.

**Comment by alextegelid** [comment]
Oooh, I see! Thank you, I'll give that a try.
