### ISSUE TITLE
Themes do not work on "Bash on Ubuntu on Windows"

### ISSUE THREAD

**Issue by JakeCooper** [robbyrussell/oh-my-zsh#5444]
It is still in beta, so it's understandable that things aren't 100% compatible yet. However, it would be awesome if there was support for this.

**Comment by brianjking** [comment]
@JakeCooper Themes do work, I've used Agnoster as well as PowerLevel 9K. What errors are you seeing?

**Comment by giacomoalonzi** [comment]
@brianjking when I activate theme Agonoster is showed like this: http://i.imgur.com/ORhvQz1.png
is the same with other themes, any help?

**Comment by brianjking** [comment]
@giacomoalonzi @JakeCooper Likely need to install Powerline fonts. See my posts [here](https://github.com/Microsoft/BashOnWindows/issues/91#issuecomment-220369715).

**Comment by JakeCooper** [comment]
@giacomoalonzi Yea that's a powerline font issue. My issue is that zsh simply looks like the normal terminal, except with a blue highlight on the location portion. I'll update this response with a screenshot when I get home.

**Comment by CosimoZi** [comment]
I have this problem too. Looking forward to solutions.

**Comment by brianjking** [comment]
Have you tried using [ConEmu](http://conemu.github.io/)?

**Comment by auscompgeek** [comment]
@JakeCooper You're not using an oh-my-zsh theme then. Are you sure you have oh-my-zsh installed and set up correctly?

**Comment by santoshbs** [comment]
Can one change the theme of icons and fonts of pcmanfm that opens in vcxsrv?

**Comment by karanrajpal14** [comment]
@JakeCooper did you find a fix for the issue? I'm facing it now and I can't seem to find anything.

**Comment by vstrides** [comment]
I just installed Powerline Fonts from [here](https://github.com/powerline/fonts) in Windows not on bash file system, everything works fine, I've tried few themes not all of them but the ones I tried worked fine.

**Comment by phun-ky** [comment]
Anyone got a fix on this? I've got the powerline font and oh-my-szh installed with agnoster theme activated, but I get this:

![image](https://user-images.githubusercontent.com/1714029/27577222-2a4c3612-5b20-11e7-9f7c-47a2d7ec85f4.png)

**Comment by dekubi** [comment]
@phun-ky how did you do it, i mean the steps

**Comment by krnlde** [comment]
1. Install [Linux Subsystem for Windows](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)
2. Install [Ubuntu from Store](https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/)
3. Install [oh-my-zsh](http://ohmyz.sh/)
4. Install [Agnoster Theme](https://github.com/robbyrussell/oh-my-zsh#themes)
5. Restart console
6. See the above result

**Comment by AngryYogurt** [comment]
Same problem, anyone got a fix？

**Comment by yakzan** [comment]
ConEmu is definitely  the way to go for now, looks much better than Windows bash. Detailed instructions here: [ConEmu with Windows Bash](https://github.com/bootstraponline/meta/wiki/Windows_10_Bash)

**Comment by coffeepy** [comment]
https://medium.com/@danielgodigna/how-to-install-zsh-oh-my-zsh-and-themes-in-ubuntu-on-windows-933489b6d6e0

**Comment by cpereiraweb** [comment]
> This worked for me
> 
> 1. Install [Menlo for Powerline](https://github.com/abertsch/Menlo-for-Powerline/raw/master/Menlo%20for%20Powerline.ttf) and set it as your font for the Ubuntu Sub System
> 2. Right Click Ubuntu Terminal Window
> 3. Click Properties
> 4. Click the Font Tab
> 5. Set Font to Menlo for PowerLine
> 6. Click Ok
> 7. Restart the Ubuntu App
> 
> [Credit where its due ](https://medium.com/@danielgodigna/how-to-install-zsh-oh-my-zsh-and-themes-in-ubuntu-on-windows-933489b6d6e0)

Thank you! It worked perfectly for me!

**Comment by aravindaytha12** [comment]
> @brianjking when I activate theme Agonoster is showed like this: http://i.imgur.com/ORhvQz1.png
> is the same with other themes, any help?

Hi,
I am facing the same issue, can please let me know if you find the solution
I have installed Powerline fonts in my winwos admin powershell also, but still facing this "?" issue

**Comment by yanpaingkyaw** [comment]
> > This worked for me
> > 
> > 1. Install [Menlo for Powerline](https://github.com/abertsch/Menlo-for-Powerline/raw/master/Menlo%20for%20Powerline.ttf) and set it as your font for the Ubuntu Sub System
> > 2. Right Click Ubuntu Terminal Window
> > 3. Click Properties
> > 4. Click the Font Tab
> > 5. Set Font to Menlo for PowerLine
> > 6. Click Ok
> > 7. Restart the Ubuntu App
> > 
> > [Credit where its due ](https://medium.com/@danielgodigna/how-to-install-zsh-oh-my-zsh-and-themes-in-ubuntu-on-windows-933489b6d6e0)
> 
> Thank you! It worked perfectly for me!

It is work for me. Thanks.
