### ISSUE TITLE
Current path is not displayed with Sierra

### ISSUE THREAD

**Issue by Gray-Wind** [robbyrussell/oh-my-zsh#5445]
Hello, I've updated to Sierra recently and my zsh stopped to show my current path. Path is showing only when in a repo (relative).

iTerm2 3.0.5
Freshly updated oh-my-zsh
zsh 5.2.0
I'm using ```nicoulaj``` theme.

**Comment by mcornella** [comment]
That's just how the `nicoulaj` theme works ¯\\\_(ツ)\_/¯

**Comment by Gray-Wind** [comment]
Nope, before Sierra it worked well. Outside of any repo it showed path relative to home directory. And it still work properly on El Capitan.

**Comment by mcornella** [comment]
That's not what I see on debian. Which zsh version did you use before?

**Comment by Gray-Wind** [comment]
```
#elcapitan
~❯ cd Downloads
~/Downloads❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

#sierra
❯ cd Downloads
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323
```

**Comment by Gray-Wind** [comment]
I used zsh installed in system:

```
# from El Capitan:
zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

**Comment by mcornella** [comment]
It seems the `VCS_INFO` API changed on 5.2.0. Let me see how to proceed.

**Comment by mcornella** [comment]
There is a bug in the `VCS_INFO_nvcsformats` where the `msgs` variable is made local. This commit fixes it, but the 5.2 release was made 6 days before: https://github.com/zsh-users/zsh/commit/4105f79a3a9b5a85c4ce167865e5ac661be160dc. I'll let the core team know, see if they push a revision.

In the meantime, you can delete that line yourself and it'll work again. To find the location of the file, run:
```zsh
for d ($fpath); do
    [[ -f "$d/VCS_INFO_nvcsformats" ]] && print "$d/VCS_INFO_nvcsformats"
done
```

**Comment by Gray-Wind** [comment]
Thank you, all works now.

**Comment by alejandroiglesias** [comment]
This is also happening to me using the `pure` theme after upgrading to macOS Sierra.

**Comment by mcornella** [comment]
Have a look at this issue as well: https://github.com/robbyrussell/oh-my-zsh/issues/4745#issuecomment-258717241.

**Comment by krs013** [comment]
@alejandroiglesias That is because you are trying to change macOS's native copy of `zsh`, which it does not allow under the "rootless" system integrity protection. The solution is to install an updated copy of `zsh` from a different source (I use `homebrew`) and use that as your shell instead.

Changing your default shell is a little risky; any change that deletes or breaks your installation will make all terminals unusable until you change it back. Still, it's possible to change it from System Preference (details [here](https://superuser.com/a/363555/222671)), so it's not really that bad. My default shell is not `/usr/local/bin/zsh` and everything works great. 👍

A potentially safer solution would be to have `bash` as your default shell and have a bashrc that looks something like `/usr/local/bin/zsh; exit`, so `zsh` would run immediately and the terminal would still exit when it returns. But... eh.

**Comment by alejandroiglesias** [comment]
@krs013 I'm already using the zsh from Homebrew. On my macOS user account preferences, I see `/bin/zsh` which is the default macOS one. But on terminal, I run `zsh --version` and I get the version from Homebrew. I'm a bit puzzled...

**Comment by krs013** [comment]
@alejandroiglesias That's not quite the same. `zsh --version` runs whatever zsh is on your path and returns the version, but that does not mean that the shell currently running is the same. If you want to check which shell is running, use `echo $SHELL`.

**Comment by dgallegos** [comment]
Upgrading zsh to 5.3.1 didn't fix the issue for me.

I fixed "refined" or "pure" using the following hack. If anyone has something more elegant, please provide it.

refined.zsh-theme

repo_information() {
    inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
    if [ "$inside_git_repo" ]; then
        echo "%F{blue}${vcs_info_msg_0_%%/.} %F{8}$vcs_info_msg_1_`git_dirty` $vcs_info_msg_2_%f"
    else
        echo "%F{blue}%~%f"
    fi
    # echo "%F{blue}%~%F{blue}${vcs_info_msg_0_%%/.} %F{8}$vcs_info_msg_1_`git_dirty` $vcs_info_msg_2_%f"
}

**Comment by alejandroiglesias** [comment]
I was also missing the current path while using the Pure theme. I fixed this by: 

1. Changing my shell in the System Preferences > Users & Groups > advanced settings for my user account. 
2. Installing Pure from npm: `npm install --global pure-prompt`.
3. Replacing in my `.zshrc`:
```sh
ZSH_THEME="pure"
```
with:
```sh
autoload -U promptinit; promptinit
prompt pure
```
