### ISSUE TITLE
Uninstall instructions don't work out of the box

### ISSUE THREAD

**Issue by dandv** [robbyrussell/oh-my-zsh#5446]
I've installed oh-my-zsh but it messed up Perl's `@INC` and scripts that used to run fine, now can't find their modules.

The [instructions](https://github.com/robbyrussell/oh-my-zsh#uninstalling-oh-my-zsh) to uninstall just say "just run `uninstall_oh_my_zsh` from the command-line". That doesn't work.

One needs to `chmod +x ~/.oh-my-zsh/tools/uninstall.sh`, then run that. (It did fix the Perl INC problem.)

**Comment by joelmheim** [comment]
I think this could be fixed very easily by adding the execute bit to the scripts in the tools directory. Is there any reason why this should not be done?

**Comment by joelmheim** [comment]
If the answer is "NO" then I have a pull request ready to go :-)

**Comment by TheSeventhLion** [comment]
None of this worked for me. Ive noticed many people complaining about not being able to uninstall ZSH. 

Whats the correct answer?

**Comment by mcornella** [comment]
This is not necessary, the function `uninstall_oh_my_zsh` runs that file with `sh`.
