### ISSUE TITLE
last-working-dir plug-in causes unexpected behavior in Emacs

### ISSUE THREAD

**Issue by patbl** [robbyrussell/oh-my-zsh#5450]
If you enable `last-working-dir`, shell commands in Emacs are executed in the directory stored in `$cache_file` rather than in the directory of the current file. So if you run `(shell-command "pwd")` in Emacs, it'll return the directory stored in `$cache_file` regardless of what file is open in Emacs.

This breaks packages that rely on shell commands' being run in the same directory as the current file. For example, an Emacs package called Projectile has a command for searching for files by filename in the current Git project. If you run this command with `last-working-dir` enabled, it will search the Git project associated with whatever path is in `$cache-file`. (It will produce an error if there's no associated project.) More details [here](http://emacs.stackexchange.com/questions/27296/why-is-the-projectile-git-repository-being-set-to-the-most-recently-cdd-directo)

There might not be any easy way of fixing this issue, but I think it would be helpful to include a warning, either in a new README or a source-code comment.

This is similar to #3999.

**Comment by mcornella** [comment]
Check out #5471, +1 it if it fixes your problem.

**Comment by patbl** [comment]
My understanding is that it would fix the problem unless I'm using a file in the root of the home directory. Is this correct? If so, it would probably make the plug-in usable again, though it could still cause unexpected behavior among unsuspecting users.

**Comment by mcornella** [comment]
That's exactly the behavior. I've documented that as a README so hopefully users will understand that. I'm not aware of any other heuristic we can use, so for now this should fix most of the problems.
