### ISSUE TITLE
nvm plugin reloads existing nvm

### ISSUE THREAD

**Issue by saschabratton** [robbyrussell/oh-my-zsh#5453]
If nvm has already been loaded, the nvm plugin will load it again.

See: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/nvm/nvm.plugin.zsh#L4-L5

Some people may want to load nvm on their own, but still utilize the completions from nvm plugin. For example, executing `nvm use default` on shell initializing can result in a significant slowdown.

See: https://github.com/creationix/nvm/issues/860

So if you want to load nvm with `--no-use` parameter, or implement other workarounds to this issue, you would lose all gains when loading nvm plugin through omz for the completions.

**Comment by saschabratton** [comment]
Proposed solution: #5454

**Comment by brandon-swu** [comment]
I would love to see this merged, I too have noticed a significant slowdown when using nvm "auto use" when entering a directory, and on shell init.

**Comment by brandonb927** [comment]
I would love to see this merged, I too have noticed a significant slowdown when using nvm "auto use" when entering a directory, and on shell init.
