### ISSUE TITLE
[Documentation] ZSH without Oh-My-Zsh

### ISSUE THREAD

**Issue by mcordingley** [robbyrussell/oh-my-zsh#5455]
A co-worker introduced me to Oh-My-Zsh several months back, and it has since migrated to be on a number of my own personal systems. It's going to stay on these, so I stay up to date with the latest and greatest from Oh-My-Zsh. :+1:

However, I'd also like to extend some of the goodness to more restricted environments, like servers, in a more light-weight and controlled manner. How would I go about understanding how Oh-My-Zsh hooks into Zsh and then extracting specific pieces of Oh-My-Zsh into a flat .zshrc file?

**Comment by slavaGanzin** [comment]
You can just copy plugins you want to use into git repo. Then clone them into server home and add to .zshrc

``` source plugins/name/name.plugin.zsh ````

for all plugins you want to use.

And it would be nearly the same you get with oh-my-zsh

**Comment by mcordingley** [comment]
It depends. I'd like a flat .zshrc file that I could throw at a server and have done. It won't really change over time. I'm not going power-user on ZSH. Just something a bit more palatable than bash.

Nice to know that the plug-ins can be more or less sourced right in.

I tried just sourcing in a theme and had a bad time of it. It seems that there's at least one other file that I need to source in for colors before the themes will source properly. I _think_ that's all that I'd need to pull in a theme.

That just leaves more general ZSH options. There's a dizzying number of them! I presume that Oh-My-Zsh has a place where these are all set in one big list, but don't know where to even begin looking.

**Comment by raxod502** [comment]
You may be interested in [Antigen](https://github.com/zsh-users/antigen), a cleaner and more lightweight approach to Zsh plugin management. Your `.zshrc` would look something like:

```
if [[ ! -e ~/.antigen-repo ]]; then
    git clone https://github.com/zsh-users/antigen.git ~/.antigen-repo
fi

source ~/.antigen-repo/antigen.zsh

antigen bundle autojump
antigen bundle sudo
...
antigen theme mgutz

antigen apply
```

Required plugins will be downloaded automatically, if necessary.

**Comment by mcornella** [comment]
I agree with @raxod502. Apart from [antigen](https://github.com/zsh-users/antigen), you can also try [zgen](https://github.com/tarjoilija/zgen) or [antibody](https://github.com/getantibody/antibody).

**Comment by mcornella** [comment]
I realize this is not the original question. If you want to understand the code, take a look at the files inside `lib/` and the `oh-my-zsh.sh` which is the initalizer and loads lib files, the enabled plugins and the theme if there is one.

If you need more information you can use the commit history and `git blame`.
