### ISSUE TITLE
keybindings change when exiting zsh (ssh session) via ctrl-d, but not via "exit"

### ISSUE THREAD

**Issue by michaeltraxler** [robbyrussell/oh-my-zsh#5458]
When I log on to a remote machine via ssh (with the same .oh-my-zsh settings) I can use exit and the keybinding for ALT-LEFT stay `^[^[[D` and my keybind to `backward-word` still works as before.

When I exit the remote session via ctrl-d, the keybinding changes to `^[^[OD` and `backward-word` doesn't work anymore.

I use the newest git version on both computers and the same .zshrc.
zsh is the same version on both computers: zsh 5.2 (x86_64-suse-linux-gnu), on OpenSuSE Tumbleweed.

Any idea what could be the reason?

**Comment by mcornella** [comment]
What's the output of `infocmp` on both systems? Do they use the same OMZ version?

Finally, could you try this PR #5113 to see if it solves the problem?

**Comment by michaeltraxler** [comment]
Thank you so much for the hint with infocmp! I'm so much intimidated by this terminfo issues.... I don't understand why this is so hard and so complicated and so hard to agree on...

The diff between the infocmp of the main machine shows the difference:
<code>
 % diff -w infocmp_system1 infocmp_system2
3c3
<       am, bce, bw, ccc, eo, hs, km, mc5i, mir, msgr, npc, xenl, xon,
---
>       am, bce, bw, ccc, eo, hs, mc5i, mir, msgr, npc, xenl, xon,
8c8
<       clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
---
>       clear=\E[H\E[2J, cnorm=\E[?25h, cr=^M,
12,16c12,16
<       cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
<       dl1=\E[M, dsl=\E]2;\007, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
<       el1=\E[1K, enacs=, flash=\E[?5h$<20/>\E[?5l, fsl=^G,
<       home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
<       ich1=\E[@, il=\E[%p1%dL, il1=\E[L, ind=^J, indn=\E[%p1%dS,
---
>       cvvis=\E[?25h, dl=\E[%p1%dM, dl1=\E[M, dsl=\E]2;\007,
>       ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K, enacs=,
>       flash=\E[?5h$<20/>\E[?5l, fsl=^G, home=\E[H, ht=^I,
>       hts=\EH, ich=\E[%p1%d@, ich1=\E[@, il=\E[%p1%dL, il1=\E[L,
>       ind=^J, indn=\E[%p1%dS,
20,23c20,23
<       kDC=\E[3$, kEND=\E[8$, kFND=\E[1$, kHOM=\E[7$, kIC=\E[2$,
<       kLFT=\E[d, kNXT=\E[6$, kPRV=\E[5$, kRIT=\E[c, ka1=\EOw,
<       ka3=\EOy, kb2=\EOu, kbs=\177, kc1=\EOq, kc3=\EOs, kcbt=\E[Z,
<       kcub1=\E[D, kcud1=\E[B, kcuf1=\E[C, kcuu1=\E[A,
---
>       kDC=\E[3$, kEND=\E[8$, kHOM=\E[7$, kIC=\E2$, kLFT=\E[d,
>       kNXT=\E[6$, kPRV=\E[5$, kRIT=\E[c, ka1=\EOw, ka3=\EOy,
>       kb2=\EOu, kbs=\177, kc1=\EOq, kc3=\EOs, kcbt=\E[Z,
>       kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
28,33c28,40
<       kf3=\E[13~, kf4=\E[14~, kf5=\E[15~, kf6=\E[17~, kf7=\E[18~,
<       kf8=\E[19~, kf9=\E[20~, kfnd=\E[1~, khome=\E[7~,
<       kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~, kslt=\E[4~,
<       mc0=\E[i, mc4=\E[4i, mc5=\E[5i, op=\E[39;49m, rc=\E8,
<       rev=\E[7m, ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
<       rmam=\E[?7l, rmcup=\E[r\E[?1049l, rmir=\E[4l, rmkx=\E>,
---
>       kf21=\E[23$, kf22=\E[24$, kf23=\E[11\^, kf24=\E[12\^,
>       kf25=\E[13\^, kf26=\E[14\^, kf27=\E[15\^, kf28=\E[17\^,
>       kf29=\E[18\^, kf3=\E[13~, kf30=\E[19\^, kf31=\E[20\^,
>       kf32=\E[21\^, kf33=\E[23\^, kf34=\E[24\^, kf35=\E[25\^,
>       kf36=\E[26\^, kf37=\E[28\^, kf38=\E[29\^, kf39=\E[31\^,
>       kf4=\E[14~, kf40=\E[32\^, kf41=\E[33\^, kf42=\E[34\^,
>       kf43=\E[23@, kf44=\E[24@, kf5=\E[15~, kf6=\E[17~,
>       kf7=\E[18~, kf8=\E[19~, kf9=\E[20~, kfnd=\E[1~,
>       khome=\E[7~, kich1=\E[2~, kind=\E[a, kmous=\E[M, knp=\E[6~,
>       kpp=\E[5~, kri=\E[b, kslt=\E[4~, mc0=\E[i, mc4=\E[4i,
>       mc5=\E[5i, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
>       rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
>       rmcup=\E[r\E[?1049l, rmir=\E[4l, rmkx=\E[?1l\E>,
40c47
<       sgr=\E[%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m%?%p9%t\E(0%e\E(B%;,
---
>       sgr=\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m%?%p9%t\E(0%e\E(B%;,
42c49
<       smcup=\E[?1049h, smir=\E[4h, smkx=\E=, smso=\E[7m,
---
>       smcup=\E[?1049h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
44c51
<       u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
---
>       u8=\E[?1;2c, u9=\E[c,

</code>
 
even though both systems are OpenSuSE tumbleweed and have the same terminfo package:
terminfo-base-6.0-12.2.x86_64

But then I remembered the unfortunate issue that the SuSE-maintainer could not agree with the urxvt maintainers about the "correct" terminfo.
I installed urxvt from source some weeks ago, as some bugfix came along. This overwrote the file:
/usr/share/terminfo/r/rxvt-unicode-256color

When I force reinstall the terminfo-base, everything is fine again....

So, this is a terminfo <-> urxvt issue, not related to zsh. Sorry for bothering you!
Why this only happens with ctrl-d and not with exit also puzzles me :-)
But I'm really happy now! Thanks again!

**Comment by mcornella** [comment]
That's probably that CTRL+D outputs that key binding which messes up the terminal in some way. The exit command doesn't output key bindings, it just exits.

Glad you found your problem!

**Comment by matrixagent** [comment]
@mcornella Sorry to just randomly pop in here. I'm rather desperate… I'm having the same issue, CTRL+D is breaking a keybinding of mine, while exit does not. I've also compared the infocmp output and it differs, but I don't quite know how to proceed know, as I don't have any other terminfo-related problems like @michaeltraxler did. Is there any way to find out what exactly CTRL+D is emitting that is causing this problem?

**Comment by gdh1995** [comment]
Hello everyone, I once found a way to fix the affect Ctrl-D:
``` bash
echo -n -e '\e[?1l\e>' # $(tput rmkx)
```

I have forgotten what it means, though it does works on my "bash of Git for Windows" and "bash of WSL 1".
