### ISSUE TITLE
How to disable auto selected mode after paste

### ISSUE THREAD

**Issue by ykswang** [robbyrussell/oh-my-zsh#5459]
I only used default settings with theme pygmalion

![dingtalk20160927113550](https://cloud.githubusercontent.com/assets/13538862/18859456/c12f7414-84a6-11e6-8c54-b3fd9768b6bf.png)

**Comment by ykswang** [comment]
It's worked fine in bash

![dingtalk20160927114855](https://cloud.githubusercontent.com/assets/13538862/18859637/70b64f24-84a8-11e6-9cc0-d6b1334e7ecf.png)

**Comment by mcornella** [comment]
You can set `zle_bracketed_paste=()` in your zshrc file and it will stop highlighting your pasted text.

**Comment by lisonge** [comment]
nice work
