### ISSUE TITLE
Backticks and $() evaluated twice

### ISSUE THREAD

**Issue by fth86** [robbyrussell/oh-my-zsh#5466]
Issue  #2234 is un-fixed with the most recent oh-my-zsh version:

```
$ echo `echo doh >> doh`
$ cat doh
doh
doh
```

I checked for the fix from #2234 in lib/termsupport.zsh, and it's there but apparently something else is un-fixing it.
 
Interestingly, the problem now also occurs with `$()`:
```
$ rm doh
$ $(echo doh >> doh)
$ cat doh
doh
doh
```

**Comment by mcornella** [comment]
That's just not the behavior I see. Please post the output of `setopt`.

**Comment by fth86** [comment]
▲ ~ setopt
alwaystoend
autocd
autopushd
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle

**Comment by mcornella** [comment]
I see nothing suspicious there. Run `functions -t omz_termsupport_preexec` (enables function tracing) and then your tests like above and post the whole output.

**Comment by fth86** [comment]
sure! 

 ▲ ~ echo `echo doh >> doh`
+omz_termsupport_preexec:1> emulate -L zsh
+omz_termsupport_preexec:2> setopt extended_glob
+omz_termsupport_preexec:4> [[ '' == true ]]
+omz_termsupport_preexec:9> local CMD=echo
+omz_termsupport_preexec:10> local LINE='echo `echo doh >> doh`'
+omz_termsupport_preexec:12> title '$CMD' '%100>...>$LINE%<<'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case screen-256color (cygwin | xterm* | putty* | rxvt* | ansi)
+title:10> case screen-256color (screen*)
+title:16> print -Pn '\ek\$CMD\e\'

 ▲ ~ cat doh
+omz_termsupport_preexec:1> emulate -L zsh
+omz_termsupport_preexec:2> setopt extended_glob
+omz_termsupport_preexec:4> [[ '' == true ]]
+omz_termsupport_preexec:9> local CMD=cat
+omz_termsupport_preexec:10> local LINE='cat doh'
+omz_termsupport_preexec:12> title '$CMD' '%100>...>$LINE%<<'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case screen-256color (cygwin | xterm* | putty* | rxvt* | ansi)
+title:10> case screen-256color (screen*)
+title:16> print -Pn '\ek\$CMD\e\'
doh
doh

 ▲ ~ $(echo doh >> doh)
+omz_termsupport_preexec:1> emulate -L zsh
+omz_termsupport_preexec:2> setopt extended_glob
+omz_termsupport_preexec:4> [[ '' == true ]]
+omz_termsupport_preexec:9> local CMD='$(echo'
+omz_termsupport_preexec:10> local LINE='$(echo doh >> doh)'
+omz_termsupport_preexec:12> title '$CMD' '%100>...>$LINE%<<'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case screen-256color (cygwin | xterm* | putty* | rxvt* | ansi)
+title:10> case screen-256color (screen*)
+title:16> print -Pn '\ek\$CMD\e\'

I was able to reproduce this on another system, by the way. Both with 
my (heavily customized) .zshrc and the default one.

Thanks alot for the help - would love to see this fixed!

**Comment by mcornella** [comment]
No problems there. It might be possible that you have another automatic function that has this problem. Run this and post the output:
```zsh
for f ($precmd_functions $preexec_functions); do which $f; done
```

**Comment by fth86** [comment]
▲ ~ for f ($precmd_functions $preexec_functions); do which $f; done
omz_termsupport_precmd () {
        emulate -L zsh
        if [[ "$DISABLE_AUTO_TITLE" = true ]]
        then
                return
        fi
        title $ZSH_THEME_TERM_TAB_TITLE_IDLE $ZSH_THEME_TERM_TITLE_IDLE
}
_zsh_highlight_main__precmd_hook () {
        _zsh_highlight_main__command_type_cache=() 
}
prompt_geometry_set_title () {
        prompt_geometry_print_title '%~'
}
prompt_geometry_render () {
        if [ $? -eq 0 ]
        then
                PROMPT_SYMBOL=$GEOMETRY_SYMBOL_PROMPT 
        else
                PROMPT_SYMBOL=$GEOMETRY_SYMBOL_EXIT_VALUE 
        fi
        PROMPT="
 %${#PROMPT_SYMBOL}{%(?.$GEOMETRY_PROMPT.$GEOMETRY_EXIT_VALUE)%} %F{$GEOMETRY_COLOR_DIR}%3~%f " 
        PROMPT2=" $GEOMETRY_SYMBOL_RPROMPT " 
        RPROMPT="$(prompt_geometry_git_info)%f" 
}
omz_termsupport_preexec () {
        emulate -L zsh
        setopt extended_glob
        if [[ "$DISABLE_AUTO_TITLE" = true ]]
        then
                return
        fi
        local CMD=${1[(wr)^(*=*|sudo|ssh|mosh|rake|-*)]:gs/%/%%} 
        local LINE="${2:gs/%/%%}" 
        title '$CMD' '%100>...>$LINE%<<'
}
_zsh_highlight_preexec_hook () {
        typeset -g _ZSH_HIGHLIGHT_PRIOR_BUFFER= 
        typeset -gi _ZSH_HIGHLIGHT_PRIOR_CURSOR= 
}
prompt_geometry_set_cmd_title () {
        prompt_geometry_print_title "${2} @ %m"
}
_fasd_preexec () {
        {
                eval "fasd --proc $(fasd --sanitize $2)"
        } >> "/dev/null" 2>&1
}

**Comment by mcornella** [comment]
```
prompt_geometry_set_cmd_title () {
        prompt_geometry_print_title "${2} @ %m"
}
```

This is the culprit function. If you try running `prompt_geometry_set_cmd_title() {}` you'll see it works again.

**Comment by fth86** [comment]
Yes, that was it, thanks!

**Comment by mcornella** [comment]
You should report the bug here: [frmendes/geometry](https://github.com/frmendes/geometry).

**Comment by fth86** [comment]
did so, bye!
