### ISSUE TITLE
trapd00r theme has external dependency

### ISSUE THREAD

**Issue by smk291** [robbyrussell/oh-my-zsh#5468]
When I use the trapd00r theme I see the following error:

`prompt_jnrowe_precmd:3: command not found: zsh_path`

**Comment by mcornella** [comment]
This [comment](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/trapd00r.zsh-theme#L3-L5) says it needs [this script](https://github.com/trapd00r/utils/blob/master/zsh_path) to work.

I don't think that's a satisfactory way of working so it would be good to have it integrated.

**Comment by smk291** [comment]
Right, and when I installed zsh_path, the command prompt threw a much more verbose error, asking for a perl script named Term-ExtendedColor (https://github.com/trapd00r/Term-ExtendedColor and https://github.com/trapd00r/Term-ExtendedColor). I couldn't get it to work, but I also didn't spend much time on it.

**Comment by miia** [comment]
I submitted a PR (#5579) with a fix that might or might not make you cringe. It still requires you to have the Term::ExtendedColor module installed, but that could definitely be avoided too, if someone is willing to devise a workaround for the perl code.

**Comment by memoselyk** [comment]
I followed this instructions to get the problem fixed:
https://luxing.im/zsh-trapd00r-theme-fix/

Even after installing `Term-ExtendedColor`, I was getting the error. That is because my system is using `/usr/local/bin/perl` instead of `/usr/bin/perl`. I solved the issue by changing the shebang in `zsh_path` to `#!/usr/bin/env perl`.

**Comment by mcornella** [comment]
I've pulled @miia's "fix". If any of you can think of a better solution feel free to open a new PR. Thanks!
