### ISSUE TITLE
Completion no longer works for directories containing hyphens

### ISSUE THREAD

**Issue by owst** [robbyrussell/oh-my-zsh#5470]
As a consequence of #5435, a common short cut I use has stopped working:

Assume the following (simplified) directory structure:
```
> tree
.
├── common
├── companyname-backend
├── companyname-boilerplate
├── companyname-frontend
└── companyname-gateway
```
I used to be able to quickly `cd` around using unique "name-parts" (sorry not sure what the correct terminology is here), e.g.:
1. `cd c-f<TAB>` would autocomplete to `cd companyname-frontend`
2. `cd c-b<TAB>` would autocomplete to `cd companyname-b` and show the completion options `companyname-backend/      companyname-boilerplate/`
3. `cd c-ba<TAB>` would autocomplete to `cd  companyname-backend/`

This was very useful and saved me a lot of TAB-time :-)

Now my examples 1. and 3. above require several more steps:
1. `cd c<TAB>`
2. `cd comp<TAB>`
3. `cd companyname-f<TAB>`
and
1. `cd c<TAB>`
2. `cd comp<TAB>`
3. `cd companyname-ba<TAB>`

(example 2. isn't really affected in "total number of `<TAB>`s", but I guess it shows how I tend to use the old-style completion)

Is there a way to implement the fixes of #5435 without breaking this use case? Or, is there a better way to `cd` around with minimal `<TAB>`ing, using the new completion?

**Comment by mcornella** [comment]
You can directly use the last part of the filename, _i.e._ `cd back<TAB>` will expand to `cd companyname-backend`. The same with the rest of names (`cd mon<TAB>`, `cd front<TAB>`, `cd gate<TAB>`).

I'm sorry #5435 was an inconvenience but it was a common complaint for a long time and we had to do something about it. I hope this new way of completing is satisfactory :wink:

**Comment by owst** [comment]
Perfect that works fine for my usecase, now to retrain my muscle memory :smile: - thanks @mcornella!
