### ISSUE TITLE
tmux plugin causes hanging tmux sessions

### ISSUE THREAD

**Issue by raxod502** [robbyrussell/oh-my-zsh#5473]
Steps to reproduce:
- Attach to a tmux session.
- Close the graphical Terminal.app or iTerm2 window that contains the tmux session (running inside zsh).
- In a new window, attach to the same session.

If and only if the tmux plugin is enabled, then the following symptoms are observed:
- Whatever is inside tmux appears to be frozen, because the displayed text only updates when switching windows. However, tmux still works as expected—it's just programs running inside tmux that suffer from the problem.
- Pressing `prefix + D` lists both the current session as well as the last session, which is somehow **prevented from being killed when the terminal window is closed**.
- Detaching the "ghost" session from inside tmux or using `kill` returns the behavior of the tmux session to normal.

See also:
- https://gitlab.com/gnachman/iterm2/issues/3995
- https://gitlab.com/gnachman/iterm2/issues/2706

where the same symptoms are observed but for different reasons.

**Comment by mcornella** [comment]
The tmux plugin has had a number of changes in the last few years, reopen if the issue still persists with the latest version.
