### ISSUE TITLE
Default theme [robbyrussell] broken after updating to OS Sierra

### ISSUE THREAD

**Issue by Javix** [robbyrussell/oh-my-zsh#5478]
It seems like I have no more colours after updating to OS Sierra. Tried to switch to `agnostic` - the same problem. Tried to manually update by running `upgrade_oh_my_zsh`, - got the message that I already had the latest version. Any ideas on how t fix that ? Thank you.

**Comment by mutantkeyboard** [comment]
I have updated to Sierra, and I have no problems. 
<img width="1280" alt="screen shot 2016-10-01 at 10 16 25" src="https://cloud.githubusercontent.com/assets/1167494/19012813/1ed8a0e2-87c0-11e6-9703-f8e17a1750ef.png">

Are you sure your shell is set to ZSH?
Try opening your terminal and typing zsh then enter. Did it change shell?
If it's not a default shell, you can change it. 

Go to System Preferences -> Users & Groups -> Unlock the seal to allow changes -> Right click on your username -> Advanced options -> Make sure that login shell is /bin/zsh

Return to your terminal and type source ~/.zshrc

Let me know if it fixed the problem or not.

**Comment by Javix** [comment]
Here is hat my terminal looks like: https://www.dropbox.com/s/6chvdfqz26eld5v/Screenshot%202016-10-01%2012.40.03.png?dl=0
Here is what my terminal settings look like: https://www.dropbox.com/s/o1aixf5ml9ygord/Screenshot%202016-10-01%2012.41.27.png?dl=0

I checked user & Groups settings as well. Login shell is set to `/bin.zsh`.
Running `zsh`from the terminal changed nothing :(.

**Comment by mutantkeyboard** [comment]
Aha. 
You're using the built-in Terminal. Might be that the colour scheme doesn't play well with it. 
Try installing the iTerm2 -> https://www.iterm2.com and see if the problem persists.

**Comment by Javix** [comment]
I used Oh My Zsh and liked it, so I do not want to use iTerm. I'll try to uninstall it and try again. Thank you for your help.

**Comment by Javix** [comment]
It worked as needed after I changed the default terminal profile settings:

My terminal looks like [that](https://www.dropbox.com/s/w11zepbe5tfsnxf/Screenshot%202016-10-01%2022.04.30.png?dl=0) after I changed the Terminal settings as [follows](https://www.dropbox.com/s/q715cbk34oly11a/Screenshot%202016-10-01%2022.08.12.png?dl=0). AS you see, I had to change default background and text color.
