### ISSUE TITLE
agnoster theme - only show ~ as working directory

### ISSUE THREAD

**Issue by quang-ha** [robbyrussell/oh-my-zsh#5479]
Is there a way to only show `~` instead of the full directory in the `agnoster` theme? I kind of love the blue rectangle strip but again don't want to show the full working path.

**Comment by brianjking** [comment]
@quang-ha I'm not sure about the Agnoster theme, however, you definitely can in [Powerlevel9k](https://github.com/bhilburn/powerlevel9k).

**Comment by mcornella** [comment]
You can redefine the `prompt_dir` function like so:
```zsh
prompt_dir () {
	prompt_segment blue black '~'
}
```

Paste that at the end of your zshrc file and you should be good to go.

**Comment by betogrun** [comment]
@quang-ha you can also show only the current folder without the full path:
```sh
prompt_dir() {
  prompt_segment blue black "${PWD##*/}"
}
```

**Comment by hck94829** [comment]
@betogrun r u sure? What I am getting is this
 ${PWD##*/} showing on the screen

**Comment by betogrun** [comment]
@hck94829  I'm not sure why it is no longer working.
I've customized this theme locally and now I'm using an alternative approach:
```
prompt_dir() {
  prompt_segment blue $PRIMARY_FG " `basename ${PWD/#$HOME/'~'}` "
}
```
More info: https://github.com/betogrun/agnoster-zsh-theme/commit/3c57a1de7d4d73a4f0cba6fd92e4dbdd592f4099

**Comment by fabrobocom** [comment]
@hck94829 Make sure you put in double quotes like this `"${PWD##*/}"`

**Comment by fepegar** [comment]
I do just:
```shell
prompt_dir() {
  prompt_segment blue black '%c'
}
```

**Comment by georgealegre** [comment]
Technically '%c' is deprecated. [Documentation](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) recommends '%.' or '~1/'.

**Comment by RenuxRenardi94** [comment]
What @georgealegre says, I tried '%.' and it does just that. Instead of the full path, it shows the current directory. Which I'd say it's good, because sometimes the full path would be so wide that there's almost no space left for commands...

**Comment by TerminatorP** [comment]
for me '%' or '~1' didn't work but as @fepegar said '%c' worked...

**Comment by RenuxRenardi94** [comment]
Actually, I got that problem too, first. It's kind of embarrassing to say it, but I got the characters wrong. '%' and '~1' do nothing. It's '%.' and '~1/'. The dot and the slash, kind of easy not to see them.

**Comment by aaophilip** [comment]
Here's what worked for me:
``` 
prompt_dir() {
    prompt_segment blue black "`basename ${PWD##*/}`"
} 
```

**Comment by SarKurd** [comment]
@betogrun comment works for but how to show parent too? i want to show parent and current directory

**Comment by mcornella** [comment]
@SarKurd you can do
```
prompt_dir() {
  prompt_segment blue black '%2/'
}
```
You can see more [prompt expansion characters in the documentation](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html).
