### ISSUE TITLE
my vim setting files are removed after auto update.

### ISSUE THREAD

**Issue by hanwong** [robbyrussell/oh-my-zsh#5485]
<img width="477" alt="2016-10-01 12 24 14" src="https://cloud.githubusercontent.com/assets/5924403/19011495/2e2d6f48-87d2-11e6-8bac-1c83a24be00b.png">

Every setting files are removed in vim73 directory after oh-my-zsh auto update.
And autocomplete tab key is not work.
I think it is about removed files...

How can I fix it???
I am mac user.

**Comment by mcornella** [comment]
OMZ doesn't remove any files, that looks like a vim installation issue. Try reinstalling it.
