### ISSUE TITLE
docker-machine autocomplete causes error

### ISSUE THREAD

**Issue by ghost** [robbyrussell/oh-my-zsh#5495]
Hi,

Just find that docker-machine start `<tab>` causes error:
`_arguments:comparguments:312: invalid argument: (- :){-h,--help}[Print usage]`

**System info:**
- MacOS 10.11.5
- Homebrew 1.0.6
- Homebrew/homebrew-core (git revision 016d; last commit 2016-10-04)
- zsh 5.1.1 (x86_64-apple-darwin14.5.0)
- docker-machine installed via `brew install docker-machine`

**Comment by mcornella** [comment]
Upstream issue.
