### ISSUE TITLE
Auto git fetch when cd into a git repo

### ISSUE THREAD

**Issue by fazlearefin** [robbyrussell/oh-my-zsh#5507]
This is a question rather than an issue. Maybe it can be a feature request if the feature I will be talking about isn't already in `oh-my-zsh`.

I moved to `oh-my-zsh` from `magicmonty/bash-git-prompt`. In that `magicmonty/bash-git-prompt` repo there was a very nice feature _where when I `cd` into a direcotry which was a git repo, it would automatically do a `git fetch` and thus saving me the hassle of manually doing a `git fetch` (or `gf` in `oh-my-zsh`)_. Is there something similar in `oh-my-zsh`?

**Comment by vharsh** [comment]
Hi, it's in the process of getting merged. 
See #5477

**Comment by slavaGanzin** [comment]
@fazlearefin It would be great if you can test this feature and add your comments to #5477

**Comment by fazlearefin** [comment]
Hi @slavaGanzin ,

Thanks for writing this plugin. I've left a detailed feedback on #5477
