### ISSUE TITLE
info: how I can hide the pc name and full actual directory route

### ISSUE THREAD

**Issue by rafaelleru** [robbyrussell/oh-my-zsh#5512]
I want that my prompt only shows my user and actual directory, not the full path. But I cand find a way.

**Comment by mcornella** [comment]
What theme are you using?

**Comment by rafaelleru** [comment]
agnoster

**Comment by mcornella** [comment]
If you don't want to see `user@hostname` you can set `DEFAULT_USER=$USER` in your zshrc file. 

Regarding the directory, you should be more specific as to what you want exactly:
- You can just show tilde `~`: #5479
- You can modify the `prompt_dir` function similarly to what is in #5479 to use the [`shrink-path` plugin](https://github.com/robbyrussell/oh-my-zsh/pull/5262#issue-168178807).

**Comment by rafaelleru** [comment]
I only wants to show the current directory. An example:
If I am working on ~/folder1/folder2/directory_working I want to show in prompt directort_working

**Comment by mcornella** [comment]
You can modify the `prompt_dir` function like this:
```
prompt_dir () {
    prompt_segment blue black '%1~'
}
```
