### ISSUE TITLE
Can add some autocomplete respect the project podfile for the zsh plugin?

### ISSUE THREAD

**Issue by CodeLife2012** [robbyrussell/oh-my-zsh#5513]
For example when use `pod update`  then tap can prompt pods in  `podfile`.

**Comment by CodeLife2012** [comment]
Hi @ajmccall, do you have time to look about this?

**Comment by ajmccall** [comment]
Hi, do you know if this functionality exists elsewhere?

I'm no expert, but generally (and in particular cocoapods's) tab completion uses a predefined list of commands/options to give values. For `pod update` this would have to be generated at run time.

**Comment by CodeLife2012** [comment]
I see a similar function in plugin `gem`.
