### ISSUE TITLE
alias (caching) question

### ISSUE THREAD

**Issue by michahell** [robbyrussell/oh-my-zsh#5515]
I have this (very ugly) alias to just quickly show my local IP adresses:

```bash
alias localip="
printf '%s\n' '========================';
printf '%s\n' 'en0: \"$(ipconfig getifaddr en0)\"';;
printf '%s\n' 'en4: \"$(ipconfig getifaddr en4)\"';
printf '%s\n' '========================';
"
```

which is just an alias for executing the commands:

```bash
➔ ipconfig getifaddr en0
➔ ipconfig getifaddr en4
```

Somehow, the alias does not update correctly when my IP address changes. It does report the correct IP addresses when I reload my shell. This leads me to think that there is some alias caching going on, somewhere? is it just regular terminal logic to do this, or is this something (oh-my-)ZSH does?

**Comment by mcornella** [comment]
When you use double quotes, whatever subcommands (`$()` or \`\`) or variables inside it are expanded to contain the actual value when the string is defined. If you don't want that to happen you have to use single quotes. This behavior happens across most shells, including zsh and bash.

That said, your alias is complex enough that you're better off with a function. You can also use `echo` or `print` for an easier syntax:

```zsh
localip() {
    echo ========================
    echo en0: \"$(ipconfig getifaddr en0)\"
    echo en4: \"$(ipconfig getifaddr en4)\"
    echo ========================
}
```

or using [`cat <<-EOF`](http://zsh.sourceforge.net/Doc/Release/Redirection.html) with tabs:
```zsh
localip() {
	cat <<-EOF
		========================
		en0: "$(ipconfig getifaddr en0)"
		en4: "$(ipconfig getifaddr en4)"
		========================
	EOF
}
```

**Comment by michahell** [comment]
ah, thanks for the feedback!
