### ISSUE TITLE
folder and files colour issue

### ISSUE THREAD

**Issue by MrKiven** [robbyrussell/oh-my-zsh#5520]
Hi:

I upgrade oh-my-zsh today, after update, folder and file do not display colour. It's ok before update.

**Comment by MrKiven** [comment]
I've checkout to https://github.com/robbyrussell/oh-my-zsh/commit/d69f2850afc189310b40141c839480b42f71775c, is ok now.

**Comment by MrKiven** [comment]
@mcornella

**Comment by s7evinz** [comment]
I'm having the same issue. ls doesn't have colour highlight for directories, symlinks, executables etc.

**Comment by MrKiven** [comment]
@s7evinz yeah, I've checkout to https://github.com/robbyrussell/oh-my-zsh/commit/d69f2850afc189310b40141c839480b42f71775c this commit, it's ok

**Comment by jannylund** [comment]
Looks like the problem is that there is no test for `gls` before testing `$OSTYPE`. https://github.com/robbyrussell/oh-my-zsh/blob/628d0bb10664453fe55c1e725ab89fa42dc4ab0a/lib/theme-and-appearance.zsh#L9 makes os x skip the `else`  settings for colors if `gls` is missing.

**Comment by mcornella** [comment]
Is it `ls -G` the one that works?

**Comment by MrKiven** [comment]
`ls -G` works.

**Comment by mcornella** [comment]
To update run `upgrade_oh_my_zsh`. Apologies for the mistake!
