### ISSUE TITLE
Why some zsh related projects isn't incorporated into oh-my-zsh

### ISSUE THREAD

**Issue by slavaGanzin** [robbyrussell/oh-my-zsh#5521]
Hello.
There is no easy way or documented one (or I missed something) to install and update this projects (just to name a few) with oh-my-zsh:
https://github.com/zsh-users/zsh-completions#oh-my-zsh
https://github.com/zsh-users/zsh-syntax-highlighting

Would it be acceptable to add them as submodules to oh-my-zsh?

**Comment by masoncodes** [comment]
Can that not be done with Git, or am I not understanding this right?

**Comment by slavaGanzin** [comment]
It can be done with git submodules. 

I'm talking about policy of oh-my-zsh:  some plugins are part of this project, but
 some are just "friendly" (using oh-my-zsh plugin interface) maintained as other github project. 

Would it be acceptable to add that plugins(via submodules or other way) into standard oh-my-zsh setup? (so everybody shouldn't run bunch of git clones, on every remote host setup, for example)

**Comment by slavaGanzin** [comment]
Here is my proposition:
I'll create plugins for zsh-completions and others which on first run will clone that repo and substitute my code

**Comment by mcornella** [comment]
This is a frequent request and fortunately there is a plugin manager from zsh creators and a couple other projects that do the same: [antigen](https://github.com/zsh-users/antigen), [zgen](https://github.com/tarjoilija/zgen) and [antibody](https://github.com/getantibody/antibody).

Have a look at them and you'll see it's actually pretty easy to use.
