### ISSUE TITLE
(venv) upon activating virtualenv doesn't show up in "robbyrussell" theme

### ISSUE THREAD

**Issue by sourabhtk37** [robbyrussell/oh-my-zsh#5532]
After creating a virtualenv for a project.I tried activating it and it's supposed to show (venv) before the path. But it's not showing in "robbyrussell" theme:

![screenshot from 2016-10-14 09 37 29](https://cloud.githubusercontent.com/assets/8580742/19375471/0c72e386-91f2-11e6-8490-11633cff9369.png)

I replaced theme in ~/.zshrc to "agnoster" ,the issue seems to have gone:

![screenshot from 2016-10-14 09 37 58](https://cloud.githubusercontent.com/assets/8580742/19375473/16206944-91f2-11e6-9caf-fe435ce3bf2f.png)

@robbyrussell I love the default theme,don't want to use that long "agnoster" path.

**Comment by brianjking** [comment]
@sourabhtk37 I'm not sure if the default theme `robbyrussell` has support for `venv`. However, I could be wrong and personally use the Powerlevel9k theme (which does have venv support).

I checked the `agnoster` theme and found the [venv](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme#L193-L199) support in these lines.

````
# Virtualenv: current working virtualenv
prompt_virtualenv() {
  local virtualenv_path="$VIRTUAL_ENV"
  if [[ -n $virtualenv_path && -n $VIRTUAL_ENV_DISABLE_PROMPT ]]; then
    prompt_segment blue black "(`basename $virtualenv_path`)"
  fi
}
````

However, when I look at the `robbyrussell` [theme](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme) it doesn't seem to mention anything about `venv` support based on my understanding.

````
local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})
````

**Comment by brianjking** [comment]
Oh, looks like you may want to check out https://github.com/robbyrussell/oh-my-zsh/issues/5186 as well.

**Comment by sourabhtk37** [comment]
Closing this as it's duplicate (#5186)
