### ISSUE TITLE
Many plug-ins can not be used after .zshrc addition, various methods will not work.

### ISSUE THREAD

**Issue by niaiwomattt** [robbyrussell/oh-my-zsh#5534]
Examples  catimg

**Comment by mcornella** [comment]
It's possible you're using commas to separate plugins in your plugins array, you should only use spaces. You also have to restart your zsh session after changing it, for example with `exec zsh`.

If that's not it, it's possible that some plugins silently fail if they're missing a dependency.

**Comment by mcornella** [comment]
In the case of catimg though, it just defines a catimg function which you can use to output images: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/catimg/catimg.plugin.zsh.

It would be nice having a README for it.

**Comment by niaiwomattt** [comment]
Resolved, brew install imagemagick
