### ISSUE TITLE
New Feature : add a simple command to check which are not merged to current git branch

### ISSUE THREAD

**Issue by dinesh707** [robbyrussell/oh-my-zsh#5535]
Here is what I use when I want to check whats not merged to develop branch. It gives a nice overview. (this query is not made up by me, i got it from stackoverflow or somewhere). But i think its a nice feature to have in oh.my-zsh

```zsh
for k in`git branch --no-merged develop | perl -pe s/^..//`; do echo -e`git show --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" $k -- | head -n 1`\\t$k; done | sort -r
```

**Comment by mcornella** [comment]
This looks nice but we already have many aliases in the git plugin. You can make it into a function or an alias in your zshrc file.
