### ISSUE TITLE
Completion knife data bag from file doesn't complete path

### ISSUE THREAD

**Issue by jsirex** [robbyrussell/oh-my-zsh#5539]
Syntax: knife data bag from file BAGNAME PATH|DIRECTORY
`knife data bag from file BAG <tab>`

After pressing tab nothing happens.
Expect path completion.

Same for `knife environment from file`

**Comment by mcornella** [comment]
I think this was fixed with https://github.com/robbyrussell/oh-my-zsh/pull/4240. Reopen if not.
