### ISSUE TITLE
Odd display bug with Agnoster theme, user root only

### ISSUE THREAD

**Issue by module0x90** [robbyrussell/oh-my-zsh#5546]
Hi,

I am using OMZ now for quite some time, I am very happy with it.
I am using the Agnoster theme.

I noticed since a few days I have the following problem with the prompt, anywhere (Arch Linux, Debian and Raspbian), but only as user root:
(please see pic https://s10.postimg.org/p7af57qid/aomz_nospace.jpg)

If I don't enter anything at the root prompt, the cursor is set straight after the > powerline character, there is no space before that.

My non-privileged user prompt looks like this https://s10.postimg.org/ntis9wr91/aomz_space.jpg
there is a space between the prompt and the cursor.

This problem with the root prompt is a bit annoying as it messes up tab-completion (it moves everything further right after pressing tab, then looses a character and just absolutely confuses you - and your prompt.

I tried the following to fix it:
- "git log themes/agnoster.zsh-theme" and then did a "git checkout XXX themes/agnoster.zsh-theme" for the last 5 commits or so. Logged out and re-opened a root-shell.
- Reinstalled .oh-my-zsh completely, even with a fresh .zshrc.
- Disabled all plugins (I used git and some others).
- The directory doesn't matter, git or no git doesn't matter. That space is missing always on the root-prompt independent of the directory.

It appears that that space is displayed _after_ the "⚡" of the prompt. I tried editing ".oh-my-zsh/themes/agnoster.zsh-theme" but my vim is getting confused by that UTF char. It is highlighting 2 characters and I cannot edit it. I am getting this with hexdump:

I replaced the ⚡ with "Y", reset my session and then it's ok again...
Not necessarily a bug with OMZ/Agnoster, where should I report this? I have this problem on Arch Linux, Debian Jessie, Raspbian Jessie.

**Comment by bluec0re** [comment]
Same here with dpoggi2 theme. It's definitely the lighting utf8 char which is responsible for this. Zsh is version 5.2. Oh-my-zsh most current git clone.

**Comment by module0x90** [comment]
Sorry, same versions for me, zsh 5.2 and latest omz clone, updated daily.

**Comment by module0x90** [comment]
@bluec0re Which terminal are you using?

I noticed I have this problem only with Sakura, when I use gnome-terminal (3.22.1) and the same font (Hack Regular) as with Sakura it is working ok. I did some digging on "UTF-8 character widths" using https://sourceware.org/bugzilla/show_bug.cgi?id=4335 and it shows me always "1".
Other UTF8 chars like u2620 (skull) are ok.
My setup is mostly the same, I use everywhere ... Sakura.

**Comment by bluec0re** [comment]
I'm using terminator, but the issue exists also with GNOME terminal 3.22.1 on my system.

**Comment by egmontkob** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=772812 for explanation of what's going on.

**Comment by mcornella** [comment]
Closing since this is not and OMZ issue, but a gnome-terminal/terminator. As that buzilla link shows, the latest libc version should fix it (2.26 and after).
