### ISSUE TITLE
Wrong indentation because "high voltage sign"  began to have a size of two signs

### ISSUE THREAD

**Issue by BjornMelgaard** [robbyrussell/oh-my-zsh#5549]
![18-22 11 05](https://cloud.githubusercontent.com/assets/7573215/19492555/cd9936d8-957f-11e6-93fc-3ba3bfd2ce87.png)

In non git directories all fine

P.S. Archlinux, oh-my-zsh-git r4227.f94d4e6-1

**Comment by BjornMelgaard** [comment]
![18-22 17 13](https://cloud.githubusercontent.com/assets/7573215/19492770/bd51c53c-9580-11e6-8e79-1ed6401da78e.png)
Also, lightning sign  was always size of two signs?

**Comment by BjornMelgaard** [comment]
Just noticed that this problem persists and on other themes and occurs after system update, maybe it was zsh update, dunno, please help

**Comment by apjanke** [comment]
This is probably a terminal issue. It is the terminal emulator that decides how many columns to render characters as. There's nothing OMZ can do about it. If it happened after a system update, your update may have picked up a new version of your terminal that uses different heuristics for determining character width.

**Comment by BjornMelgaard** [comment]
Yes, it is, I have reported that issue about gnome-terminal
