### ISSUE TITLE
Color ls broken after update

### ISSUE THREAD

**Issue by ButchAnton** [robbyrussell/oh-my-zsh#5552]
I just updated to the latest oh-my-zsh (commit f94d4e6a4019ed7fcc5470655b1154b3d1f67913) and color ls is now broken on my Mac running El Capitan.  Two recent log messages indicate fixes were checked in for just that (fixing 5520 and 5516), but it seems that has broken things for me:

```
% ls
/bin/ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
% which ls
ls: aliased to gls --color=tty
% which gls
gls () {
    /bin/ls -FC -lh $@
}
% /bin/ls
foo
% /bin/ls -FC -lh
total 0
-rw-r--r--  1 i831533  staff     0B Oct 19 12:06 foo
% gls --color=tty
/bin/ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
% /bin/ls -FC -lh --color=tty
/bin/ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
% /bin/ls -FC -lh -G
total 0
-rw-r--r--  1 i831533  staff     0B Oct 19 12:06 foo
```

It seems that the `--color=tty` option for Linux is being incorrectly passed to the Mac version of ls, which doesn't support it (instead supporting -G).

This all was working fine before this morning's update to oh-my-zsh.

**Comment by jGRUBBS** [comment]
I ran into this same issue as well. I have narrowed it down to this line:
https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/theme-and-appearance.zsh#L21

I see the error was introduced by this commit: https://github.com/robbyrussell/oh-my-zsh/commit/c24dfa1ab4abb1f28fad7666f3bc24f3abced801

I haven't had time to figure out what this line should be, but I know commenting it out resolves the issue for me.

**cc** @mcornella

**Comment by techthumb** [comment]
I'm having this issue as well. However, it appears that this only happens when https://github.com/scmbreeze/scm_breeze is activated.

I changed the `gls` alias to `glsa` to avoid the conflict.

https://github.com/scmbreeze/scm_breeze/blob/ac6a7808b703d4fc14bb5df55aabeef9b9981582/git.scmbrc.example#L92

**Comment by ButchAnton** [comment]
@techthumb: I don't have scm_breeze installed, so it's not an alias conflict.  Good catch on that one, though.

@jGRUBBS: I see what you mean by that commit.  I'm really not sure why there's even an attempt to use "--color=tty" on a darwin system.  Me thinks this is just plain wrong.

I've changed both sides of the or to use "-G" (so gls and ls both use the same arguments) for now until somebody with a bigger brain than me (and more time) can ponder out the right solution.

Thanks for your help, guys!

**Comment by mcornella** [comment]
@ButchAnton @techthumb @jGRUBBS check out #5570 and please tell me there if it fixes it.

**Comment by ButchAnton** [comment]
@mcornella:
It seems to have fixed the problem for me.  It falls back to using the system ls -G.

Here is my current configuration:

Environment has $LSCOLORS set.
I do NOT have a ~/.dircolors file.
I have installed coreutils, so gls is a valid executable:  /usr/local/bin/gls, and it responds correctly to --color=tty.

I just tested setting the LS_COLORS environment variable to the same string as LSCOLORS.  This resulted in ls continuing to be aliased to ls -G.
I then unset this environment variable and touched ~/.dircolors.  This resulted in breakage, and ls being aliased to gls, which, in turn, is a function aliased back to /bin/ls -FC -lh $@, which picks up the --color=tty argument.  Hmmmmm, not good.  Having both the environment variable set and the .dircolors file also had the same breakage.

What I fail to understand is why gls is being defined as a function for me instead of using the installed executable from coreutils in /usr/local/bin.

Then there's a further problem.  Some people share the same directory structure (AFS or NFS users, for example) across multiple computers, some of which may be Darwin based and others of which may be Linux based.  Therefore, the check for the environment variable and/or .dircolors could erroneously succeed.

To say that this is a ball of spaghetti would be an extreme understatement.  :-)

I hope some part of this was useful.

**Comment by nickolayrusev** [comment]
I have the exactly same problem. For now I just hardcode it like @ButchAnton said both side of the if to use "ls -G" argument. I'm using MacOS El Capitan. 

@ButchAnton thanks for solution :)

**Comment by jGRUBBS** [comment]
@mcornella #5570 works for me as well. Thanks for looking into it. 👍

**Comment by vmoutoussamy** [comment]
as of today, I had "ls: aliased to ls -G" because I used the following theme .oh-my-zsh/themes/tonotdo.zsh-theme which had an exported LS_COLORS in it...
To fix the issue (use the custom LS_COLORS of tonotdo), I had to put the export LS_COLORS command into my .zshrc.
This is because the actual code check for a LS_COLORS before applying the theme... This is clearly not the ideal solution.

**Comment by mcornella** [comment]
@vmoutoussamy that's interesting I'll see if there's a possible way to make all that work. It won't be in the near term though.
