### ISSUE TITLE
trying to modify bureau theme to include IP, but it puts time on new line.

### ISSUE THREAD

**Issue by mikedevita** [robbyrussell/oh-my-zsh#5553]
i modified the bureau theme to include an ip like so... however its putting the clock on a new line, im assuming this comes down to the spaces function.. not sure how else to troubleshoot it so it goes back to the right prompt.

![image](https://cloud.githubusercontent.com/assets/2991640/19535800/0f2ef6c2-95fe-11e6-8f4a-411d75e9aabd.png)

the edits i made are
```
ipv4_local () {
  local _result=""
  _result=$(getent hosts NBWK4UF75V1M  | awk '{ printf "%s", $1 } END {print ""}')
  echo $_result
}

_IPV4="%{$fg[green]$(ipv4_local)%}%{$reset_color%}"


_PATH="%{$fg_bold[white]%}%~%{$reset_color%}"

if [[ $EUID -eq 0 ]]; then
  _USERNAME="%{$fg_bold[red]%}%n"
  _LIBERTY="%{$fg[red]%}#"
else
  _USERNAME="%{$fg_bold[cyan]%}%n"
  _LIBERTY="%{$fg[green]%}$"
fi

_USERNAME="$_USERNAME%{$reset_color%}@%m(${_IPV4})"
_LIBERTY="$_LIBERTY%{$reset_color%}"
```
if i take the $_IPV4 out it works like the theme ships with. can anyone help me troubleshoot?

**Comment by stark** [comment]
Try adding a '-n' parameter to the echo in the ipv4_local function.

So `echo $_result` becomes:
```sh
echo -n $_result
```

**Comment by stark** [comment]
Try adding a '-n' parameter to the echo in ipv4_local function:

Example:

```sh
echo $_result
```

**Comment by mcornella** [comment]
@stark's this may be something rerlated to the `get_spaces` function, which will take me some time to understand. In the mean time, try what @stark suggests, `echo -n` doesn't output a newline so this might be the real culprit.
