### ISSUE TITLE
My custom oh-my-zsh theme

### ISSUE THREAD

**Issue by gpaixao** [robbyrussell/oh-my-zsh#5556]
Can I fork this project and include my [personal theme](https://github.com/gpaixao/aterminal-oh-my-zsh-theme) ?

**Comment by mikedevita** [comment]
there is a custom folder under `.oh-my-zsh` that lets you add plugins and themes without affecting the core oh-my-zsh... any theme placed in there overrides the duplicate named theme.

**Comment by gpaixao** [comment]
Nice! :sake:

**Comment by mcornella** [comment]
Have a look at [customization](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization) and feel free to add your theme to the [external themes](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) page.
