### ISSUE TITLE
git diff completion if not in a git directory

### ISSUE THREAD

**Issue by j16180339887** [robbyrussell/oh-my-zsh#5559]
Since `git diff` can compare two files or two folders.

Is there a way do this 

`git diff <tab> <tab>`

first `<tab>` shows folders/files, same as second `<tab>`

If I am NOT in a git directory, thanks ：）

**Comment by mcornella** [comment]
git's diff only works in a git repository, there is no going around it. You can use `diff -u` which is similar but doesn't have the color, or you can use [colordiff](https://github.com/daveewart/colordiff).

**Comment by j16180339887** [comment]
> git's diff only works in a git repository

Nope, git diff can be used even it is not in a git repository.
```
git diff 1.txt 2.txt
git diff folder1/ folder2/
```
Am I misunderstood your answer ?

**Comment by mcornella** [comment]
Last time I checked I got a `not a git repository` error. I'll check again but, if it works, Oh My Zsh doesn't ship a custom git completion so the issue will be with the official one.

**Comment by j16180339887** [comment]
Thank you for taking your time !

**Comment by j16180339887** [comment]
See #5075

**Comment by mcornella** [comment]
Ok, in any case that has to be solved upstream, in zsh's official `git-diff` completion. Thanks for the heads up!

**Comment by j16180339887** [comment]
[https://github.com/git/git/tree/master/contrib/completion](https://github.com/git/git/tree/master/contrib/completion)

Hope someone updates the scripts here! :)
