### ISSUE TITLE
rkj-repos: wrong color after git short sha1

### ISSUE THREAD

**Issue by D0tty** [robbyrussell/oh-my-zsh#5567]
Hi,

When you are in a git directory, the git short sha1 and status is printed in bue, normal.
But the end of the prompt is white and it should be bleu as well.
I tried to fix it by myself but failed, can you fix it ?

Thank you.

**Comment by apjanke** [comment]
What theme are you using?

**Comment by D0tty** [comment]
Hi,

ZSH_THEME="rkj-repos"

that was said in the title
