### ISSUE TITLE
How to disable magic plugins

### ISSUE THREAD

**Issue by Zert** [robbyrussell/oh-my-zsh#5569]
How to disable bracketed-paste-magic, url-quote-magic and whatever-magic plugins?

**Comment by apjanke** [comment]
Just don't include them from the `$plugins` list in in your `~/.zshrc`. Only plugins explicitly requested are loaded.

**Comment by Zert** [comment]
This is not oh-my-zsh plugin, it's code from `lib/misc.zsh`, and I don't know how to exclude this file from loading.

**Comment by apjanke** [comment]
Ah, sorry.

OMZ doesn't provide a setting to turn those off. But you can override the provided `lib/misc.zsh` with a customized one by copying it to your `$ZSH_CUSTOM/lib` directory (creating one if necessary) and editing it.

**Comment by Zert** [comment]
May be it worth to move this code to `plugin/` and enable it explicitly?

**Comment by mlibbey** [comment]
Perhaps similar to 5499?

**Comment by tasmo** [comment]
According to the [Wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Design#customization) it is possible to overwrite internal `lib/*.zsh` files through creating a corresponding `$ZSH_CUSTOM/lib/*.zsh`:

> It's not documented in the _Customization_ page, but `$ZSH_CUSTOM/lib/*.zsh` do override the corresponding internals lib files. If a custom one is present, it is sourced instead of the one in the distribution.

**Comment by untoreh** [comment]
`zle -N bracketed-paste bracketed-paste-magic` causes some serious delays copy-pasting ...an easier option to turn it off might be useful...

**Comment by AaronFlower** [comment]
First, edit the `misc.zsh` file.
```bash
vim $ZSH/lib/misc.zsh
```
Second,  Comment the following code.
```diff
--- a/lib/misc.zsh
+++ b/lib/misc.zsh
@@ -5,11 +5,11 @@ if [[ $ZSH_VERSION != 5.1.1 ]]; then
   for d in $fpath; do
        if [[ -e "$d/url-quote-magic" ]]; then
                if is-at-least 5.1; then
-                       autoload -Uz bracketed-paste-magic
-                       zle -N bracketed-paste bracketed-paste-magic
+                       # autoload -Uz bracketed-paste-magic
+                       # zle -N bracketed-paste bracketed-paste-magic
                fi
-               autoload -Uz url-quote-magic
-               zle -N self-insert url-quote-magic
+               # autoload -Uz url-quote-magic
+               # zle -N self-insert url-quote-magic
       break
        fi
   done
```

It works for me!

**Comment by mcornella** [comment]
After the latest update (run `upgrade_oh_my_zsh`), you can add `DISABLE_MAGIC_FUNCTIONS=true` to your zshrc (before OMZ is sourced) to bypass the loading of these functions.

**Comment by dimisjim** [comment]
@AaronFlower Is there a way to do this in the `custom` folder? (have zsh master in line with remote master, without stashing each time you do an `upgrade_oh_my_zsh`)

**Comment by mcornella** [comment]
Look at the latest comment, it's one setting away.

**Comment by RainMoonShy** [comment]
> This is not oh-my-zsh plugin, it's code from `lib/misc.zsh`, and I don't know how to exclude this file from loading.

DISABLE_MAGIC_FUNCTIONS=true
add this to ~./zshrc before source $ZSH/oh-my-zsh.sh
