### ISSUE TITLE
`ls` command outputs some directory names surrounded by ''

### ISSUE THREAD

**Issue by jottr** [robbyrussell/oh-my-zsh#5574]
On latest oh-my-zsh:
````
$ pwd
/Users/jonas/.oh-my-zsh

$ git rev-parse HEAD
0ee89d965ecaa4f32cf2d1039e9d84a73eb206cf

$ which ls
ls: aliased to gls --color=tty
```

Some directories are suddenly surrounded by `''`: 

<img width="703" alt="bildschirmfoto 2016-10-25 um 19 02 41" src="https://cloud.githubusercontent.com/assets/2744198/19696023/b668c6b6-9ae5-11e6-87b6-76cdc3580dc3.png">

Permission and ownership are identical for files with `''` and without.
`/bin/ls/` works as expected.

**Comment by stark** [comment]
This is actually a feature that has been added to `ls` provided by [GNU coreutils](https://www.gnu.org/software/coreutils/coreutils.html) few months ago.

You can alias `ls` to the following if you don't want quotes:
```sh
alias ls='ls -N'
```
See '[Formatting the file names](https://www.gnu.org/software/coreutils/manual/html_node/Formatting-the-file-names.html)' for more details.

**Comment by jottr** [comment]
The weird thing is, that this issue just showed up a few days for me.

**Comment by mcornella** [comment]
This should be fixed now on master.
