### ISSUE TITLE
how to remove username@computer name from prompt?

### ISSUE THREAD

**Issue by dariushazimi** [robbyrussell/oh-my-zsh#5581]
Using agnoster theme on osx iterm.
How can I modify the prompt to NOT display the username@computername /dir/dirname

It is too long.
Ideally I like to just display full directory path on line (plus all the features of the powerline, which works fine) and on the next line just have the prompt

Many thanks.

**Comment by grawlinson** [comment]
I found a [possible solution](https://gist.github.com/logicmd/4015090#gistcomment-1881695). Can you see if it works?

**Comment by brianjking** [comment]
@dariushazimi You could check out https://github.com/bhilburn/powerlevel9k if you really want to get custom.

**Comment by dariushazimi** [comment]
hi @grawlinson 
thanks for the tip. I used USER=`` and it did the trick. Now where would I have to place this to take effect everytime I start the iterm2. 
Many thanks again.

**Comment by dariushazimi** [comment]
Hi @brianjking 
Your suggestion looks amazing. But I am afraid of taking any risk with the prompt right now. I just managed to get the powerline to work (after a few containers of coffee :))

But I am really tempted. Thanks again for your suggestion.

**Comment by grawlinson** [comment]
Hey @dariushazimi, glad to hear it worked.

In order for the changes to persist, you should probably add that one line (USER=``) to your .zshrc.

**Comment by mcornella** [comment]
Please don't use that workaround (`USER=""`), it could mess up certain commands or functions. Better are using either of these:
```
DEFAULT_USER=$USER

# or

prompt_context() {}
```

[agnoster wiki section](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster).

**Comment by dariushazimi** [comment]
@mcornella thanks for the tip. I added the prompt_context() {} to the end of .zshrc file and it did the job. clean prompt finally. Thank you all.

**Comment by djacobus** [comment]
@mcornella Perfect fix for a clean prompt!
prompt_context() {}

**Comment by ishanSrt** [comment]
this doesn't seem to work with most themes other than agnoster

**Comment by chaouimar1** [comment]
this worked for me.
https://github.com/agnoster/agnoster-zsh-theme/issues/39#issuecomment-307338817
