### ISSUE TITLE
have _brew in my fpath but it does not work unless calling compinit

### ISSUE THREAD

**Issue by quinoa42** [robbyrussell/oh-my-zsh#5583]
Environment: homebrew-installed zsh

And in the output of `echo $fpath`, `/usr/local/share/zsh/site-functions` does show up, where I symlinked _brew and _brew_cask into this directory.

And if I call `rm -f ~/.zcompdump; compinit`, although it's a little bit slow but when I press tab it works.

However, after restarting my terminal, it stop working again unless I use the same command above.

**Comment by apjanke** [comment]
Are you sure you're running the Homebrew-installed zsh in all cases? If your default shell is still pointing at `/usr/bin/zsh`, then you'll be running the system `zsh` in new terminal sessions, even if `which zsh` reports the Homebrew-installed zsh. This behavior sounds consistent with running a system `zsh` which gets `/usr/local/share/zsh/site-functions` placed on `$fpath` after OMZ initialization/compinit is run.

Could you post the output of `omz_diagnostic_dump` as a gist so we can take a look at your config files and help you debug this?

**Comment by techtomas** [comment]
I just started using OMZ (it's great BTW) and ran into this issue tonight after updating Homebrew. The completions were working before so I remove the group write bit from the two directories listed by compaudit.

`chmod g-w /usr/local/share/zsh`
`chmod g-w /usr/local/share/zsh/site-functions`

**Comment by quinoa42** [comment]
Sorry about the late and here's my output:

<script src="https://gist.github.com/quinoa42/84f9476975ebf93d5e0689ff7e25ba37.js"></script>
