### ISSUE TITLE
ls: illegal option

### ISSUE THREAD

**Issue by mtawil** [robbyrussell/oh-my-zsh#5589]
Hello,

Suddenly, I got this error when I tried to list my files:
```
➜  ~ ls
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

I don't know how, why and when this happened.
Does anyone of you have the same issue? And how can I fix it?

Thanks.

**Comment by manojpandey** [comment]
@mtawil Probably check this
https://github.com/sorin-ionescu/prezto/issues/966

**Comment by mtawil** [comment]
Thanks, man.

I did follow these steps, and it works!
https://github.com/sorin-ionescu/prezto/issues/966#issuecomment-172003005

Really appreciated.
