### ISSUE TITLE
Why add the line alias, failure

### ISSUE THREAD

**Issue by penhauer-xiao** [robbyrussell/oh-my-zsh#5595]
Why add the following line alias:
`Alias -g rm = 'rm -i'`
It will affect the docker, because when running docker rm, on-my-zsh will resolve into docker rm -i, resulting in the implementation of failure.

```
$ docker rm 5afb994baf78
unknown shorthand flag: 'i' in -i
See 'docker rm --help'.
```

**Comment by mcornella** [comment]
I can't find that anywhere in the code. You must have an external dependency that does that.

**Comment by penhauer-xiao** [comment]
Do it dependency on zsh, non-oh-my-zsh?

**Comment by mcornella** [comment]
You must have some non-standard commands in your zshrc file. Please post it so that I can advise you on a solution.

**Comment by penhauer-xiao** [comment]
My zshrc as following:

`
export UPDATE_ZSH_DAYS=30

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# export ZSH_THEME="xiong-chiamiov-plus"
export ZSH_THEME="anwar"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git autojump sudo last-working-dir docker docker-compose encode64 urltools  extract)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#***********************************
export GOROOT="/mnt/shared/go"
export GOARCH="amd64"
export GOOS="linux"
export GOBIN="$GOROOT/bin"
export GOTOOLS=$GOROOT/pkg/tool/linux_amd64

export GOPATH="/mnt/shared/go-T"
export GOPKGBIN="$GOPATH/bin"
export PATH=$GOBIN:$GOPKGBIN:$GOTOOLS:$PATH
#***********************************

setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt APPEND_HISTORY   # If this is set, zsh sessions will append their history list to the history file, rather than overwrite it.
unsetopt BG_NICE            # Run all background jobs at a lower priority. This option is set by default.
setopt MENUCOMPLETE   # Very good to select option for commands,etc. ls -

# Set/unset  shell options
setopt   autoresume histignoredups pushdsilent 
setopt   autopushd pushdminus extendedglob rcquotes mailwarning
unsetopt bgnice autoparamslash

# Autoload zsh modules when they are referenced
zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile

alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias lla='ls -al --color=auto'
alias f=finger
alias -g cp='cp -i'
alias -g mv='mv -i'
alias -g rm='rm -i'
alias -g grep='grep --color=auto'
alias -g tmc='source $ZSH/themes/simple.zsh-theme'
alias -g tmn='tmux new -d -s'
alias -g tml='tmux ls'
alias -g tma='tmux attach -t'
alias -g tmk='tmux kill-session -t'
alias -g rtm='retmux '
alias -g py='bpython'
alias -g uterm='/usr/bin/rxvt-unicode'
alias -g mterm='/usr/local/bin/mlterm'
alias man="pinfo -m"
alias -g gt='gnome-terminal'
alias -g pcz='proxychains'
#alias go=colorgo

sudo-command-line() {
    [[ -z $BUFFER ]] && zle up-history
    [[ $BUFFER != sudo\ * ]] && BUFFER="sudo $BUFFER"
    zle end-of-line           
}
zle -N sudo-command-line

bindkey "\e\e" sudo-command-line
#}}}

setopt HIST_IGNORE_DUPS

zstyle ':completion:*:ping:*' hosts 192.168.128.1{38,} www.g.cn \
       192.168.{1,0}.1{{7..9},}

my_accounts=(
{r00t,root}@{192.168.1.1,192.168.0.1}
kardinal@linuxtoy.org
123@211.148.131.7
)
zstyle ':completion:*:my-accounts' users-hosts $my_accounts
#}}}

eval "`dircolors ~/.dircolors`"
ulimit -c unlimited

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8`

**Comment by penhauer-xiao** [comment]
For example,  I look forward to prompt before every removal, So I add alias ```alias -g rm='rm -i'```,  but this s alias conflicts with the ```docker rm```,  On My input ```docker rm```, on-my-zsh is interpreted as ```docker rm -i```; The resulting in the ```docker rm`` command can not be used, but I do not want to give up this alias.

**Comment by mcornella** [comment]
You have these aliases defined in your zshrc file: 
```
alias -g cp='cp -i'
alias -g mv='mv -i'
alias -g rm='rm -i'
```

My guess is that you mistakenly added the `-g` part which makes it global. Delete the `-g` part and you'll be fine.

**Comment by penhauer-xiao** [comment]
Nice, very good,  It is ok for your method.    @mcornella
