### ISSUE TITLE
No DIR ( directory )  colors => LS LL

### ISSUE THREAD

**Issue by duard** [robbyrussell/oh-my-zsh#5604]
I just install ubuntu 16.10
then install ZSH following this link https://gist.github.com/tsabat/1498393

commands LS, LL, etc 

![screenshot from 2016-11-02 16-24-22](https://cloud.githubusercontent.com/assets/36894/19941864/e4b260a2-a118-11e6-8e42-99b354262dff.png)

**Comment by nykh** [comment]
Just updated and affected by this as well.

**Comment by nykh** [comment]
Read through the git log. Can it be because of some change to `lib/theme-and-appearance.zsh`?

**Comment by duard** [comment]
I'm using default settings, nothing changed

**Comment by nykh** [comment]
It's strange. The environment variable `LS_COLORS` looks normal. And when I switch to bash the colors show up normally. I wonder what change happened.

**Comment by nykh** [comment]
A temporary fix is add the line

```bash
alias ls='ls -G --color
```

__after__ the `source $ZSH/oh-my-zsh.sh` line in the `.zshrc` file...

**Comment by duard** [comment]
Yes, this work, but I go back to bash until ZSH has an oficial fix to this problem.

**Comment by ozen** [comment]
Affects me as well on Ubuntu 16.04. I'm using default settings, and it broke after the last update.

**Comment by vunhan** [comment]
ok, tks for workaround solution. :))

**Comment by dustinliu** [comment]
ls --color -d . &>/dev/null && alias ls='ls --color=tty' || ls -G . &>/dev/null && alias ls='ls -G'
-> ls='ls -G'

ls -G . &>/dev/null && alias ls='ls -G' ||  ls --color -d . &>/dev/null && alias ls='ls --color=tty'
->ls='ls --color=tty'

zsh execute the command in wrong order?

**Comment by red15** [comment]
blame 2d96408

**Comment by M4GNV5** [comment]
```sh
cd ~/.oh-my-zsh
git checkout 1b799e9762067f912c0eb807cd5a55d8f122adfd
```
-> restart terminal

(temporary fix) working for me
ty to @red15 for poiting out the commit that broke the colors

**Comment by duard** [comment]
@red15 

`➜  .oh-my-zsh git:(master) git checkout 1b799e9762067f912c0eb807cd5a55d8f122adfd

fatal: reference is not a tree: 1b799e9762067f912c0eb807cd5a55d8f122adfd
`

**Comment by HGrzywacz** [comment]
`git revert 40544a1d`

works for me.

**Comment by arvidbjorkstrom** [comment]
`git revert 40544a1d`
Worked for me on one machine, but not another. Since it was installed a short while ago it didn't have the history locally. To fetch the history to be able to do a revert you can run
`git fetch --depth=5 origin` before running the revert, and everything will be fine. =)
