### ISSUE TITLE
request support: brew plugin add $PATH settings

### ISSUE THREAD

**Issue by septs** [robbyrussell/oh-my-zsh#5610]
```
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

add this code:
```bash
if [ -d "$(brew --prefix)/bin" ]; then export PATH="$(brew --prefix)/bin:$PATH"; fi
if [ -d "$(brew --prefix)/sbin" ]; then export PATH="$(brew --prefix)/sbin:$PATH"; fi
```

see
1.  [brew --prefix source](https://github.com/Homebrew/brew/blob/b35134239a22710acd680c1893fc2ad0dd9268a5/Library/Homebrew/cmd/--prefix.rb)
2. [brew diagnostic source](https://github.com/Homebrew/brew/blob/b35134239a22710acd680c1893fc2ad0dd9268a5/Library/Homebrew/diagnostic.rb#L400-L464)
3. [brew.plugin.zsh source](https://github.com/robbyrussell/oh-my-zsh/blob/0ee89d965ecaa4f32cf2d1039e9d84a73eb206cf/plugins/brew/brew.plugin.zsh)

**Comment by mcornella** [comment]
As a general rule we don't want to mess with people's `$PATH`s.
