### ISSUE TITLE
zsh cask plugin: cask command not found - Cask Plugin 

### ISSUE THREAD

**Issue by kevinmamaqi** [robbyrussell/oh-my-zsh#5611]
After adding cask to the plugin list (at the end) I receive the following message:

> zsh cask plugin: cask command not found

In the plugin page is the following message: _Make sure you have the cask directory in your $PATH before loading Oh My Zsh, otherwise you'll get the "command not found" error._

But I don't know what does it mean.

**Comment by mcornella** [comment]
Cask is the [project management tool for emacs](https://github.com/cask/cask). I assume you've installed it with `brew install cask`?

**Comment by kevinmamaqi** [comment]
Yes it is that tool, and yes. I've installed it via brew.

**Comment by mcornella** [comment]
Try `brew doctor`.

**Comment by mcornella** [comment]
ping @kevinmamaqi

**Comment by kevinmamaqi** [comment]
Done, but still the same. @mcornella

**Comment by mcornella** [comment]
Huh, you don't get any error? What's your `$PATH`?

**Comment by kevinmamaqi** [comment]
The only error that I get is the message _zsh cask plugin: cask command not found_ everytime that I start iTerm2.

Plugin $PATH = ~/.oh-my-zsh/plugins/cask
Source $PATH = ~/.zshrc

**Comment by mcornella** [comment]
Add `echo $PATH` at the beginning and end of your zshrc file, and post the results.

**Comment by kevinmamaqi** [comment]
I get the following messages:

`/Users/myuser/.rvm/gems/ruby-2.3.3/bin:/Users/myuser/.rvm/gems/ruby-2.3.3@global/bin:/Users/myuser/.rvm/rubies/ruby-2.3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/myuser/.rvm/bin:/Users/myuser/.rvm/bin`

`zsh cask plugin: cask command not found`

`/Users/myuser/.rvm/gems/ruby-2.3.3/bin:/Users/myuser/.rvm/gems/ruby-2.3.3@global/bin:/Users/myuser/.rvm/rubies/ruby-2.3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/myuser/.rvm/bin:/Users/myuser/.rvm/bin:/Users/myuser/.rvm/bin`

**Comment by mcornella** [comment]
You don't seem to have homebrew's Cellar directory in your `$PATH`. `brew doctor` should've given you some kind of error.

**Comment by mcornella** [comment]
Nevermind my previous message. Your problem is that you miss the `/usr/local/sbin` directory. If you add it you should be good to go.

**Comment by kevinmamaqi** [comment]
Hello @mcornella 

I've added it and the problem persist. Sorry for the delayed replies.

**Comment by kevinmamaqi** [comment]
Hello again @mcornella the problem persist and the directory is there.
