### ISSUE TITLE
rails plugin alias doesn't work with "bundle exec"

### ISSUE THREAD

**Issue by taylorthurlow** [robbyrussell/oh-my-zsh#5618]
Using the `rs` alias for `rails server` does't work when you append it to another command. As far as I can tell, it only works when it's used by itself. My end goal here is to be able to use it in combination with the `bundler` plugin and use `be rs` to execute `bundle exec rails server`.

Using no aliases:

```
$> bundle exec rails server
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
_
```

Using `rs` by itself:

```
$> rs
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
_
```

Using `rs = rails server` alias:

```
$> bundle exec rs
_
```

Using `be = bundle exec` alias from `bundler` plugin:

```
$> be rs
_
```

**Comment by mcornella** [comment]
Zsh only looks for an alias in the first position of a command. To make it expand rs as an alias anywhere in the command you would have to turn it into a global alias with `alias -g rs=...`.

**Comment by shinenelson** [comment]
In that case, I'd suggest almost all of the aliases in the rails plugin should be defined as global aliases.

I could open a pull request with that change, but what I'd like to know is whether there would be any other unintended consequences of defining global aliases?

For example, I wouldn't want `vim $HOME/.bashrc` to be expanded as `vim $HOME/.bashrails console` :confused: 

Forgive my lack of knowledge about how zsh / oh-my-zsh handles global aliases.

Is the above example a possibility @mcornella? If that is the case, I'll refrain from making all the aliases global.

**Comment by mcornella** [comment]
Adding global aliases is a dangerous path, but your example wouldn't happen. Only fully-fledged parameters that coincide with a global alias are expanded. That means **they have to be separated by spaces**, so `bashrc` wouldn't be expanded to `bashrails console`; `bash rc` would be expanded to `bash rails console`.

That being said, I won't merge the change to global aliases because of the added confusion. Using aliases in itself is frequently complained about, imagine if we use global aliases.

**Comment by shinenelson** [comment]
It makes sense. I wouldn't put that in the project for users to consume either.

That said, looking at the aliases though, I can't think of words that can be parameters for anything except for a few aliases like `rdb`, `rdms`, `rds`, `rt` and `rmd`. I think the other aliases are all safe to be made global.

Of course, there is the minute possibility that someone could make random shell variables (like naming a bash script `rc` and trying to execute it with `bash rc`) and then mess up to conflict with the global aliases; but that's going to be a rare occurrence.

I'm going to manually make a few of them (that I use) global in my local copy and see whether it affects any of my flows.
