### ISSUE TITLE
ps1 problem

### ISSUE THREAD

**Issue by yhshen** [robbyrussell/oh-my-zsh#5620]
why after i input a linux command, then next line will show the command.

And why always shows ~%

**Comment by lian4187** [comment]
i have this problem too，any one help?

**Comment by mcornella** [comment]
Please provide an example. You can copy and paste your terminal output or install [asciinema](https://asciinema.org/) and record your problem.

**Comment by robbyrussell** [comment]
Closing as we didn't get more details
