### ISSUE TITLE
DISABLE_UPDATE_PROMPT=true, still prompting

### ISSUE THREAD

**Issue by jwhipp** [robbyrussell/oh-my-zsh#5621]
I've set this value in my ~/.zshrc, but I still get prompted to update.   What behavior should I be seeing with this var set to true?

**Comment by mcornella** [comment]
Be sure to set that above the `source $ZSH/oh-my-zsh.sh` line. It is already written somewhere above that, you only have to uncomment it.

**Comment by donmccurdy** [comment]
My `.zshrc` looks like this:

```
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
export ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="agnoster"

# Update automatically.
DISABLE_UPDATE_PROMPT=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git git-flow github svn osx)

source $ZSH/oh-my-zsh.sh

...
```

...But i'm still being prompted regardless. Is this working correctly?

**Comment by C0rn3j** [comment]
@donmccurdy works on my Arch and Ubuntu 16.04 machines.

You can debug this by editing .zsh-update and setting the LAST_EPOCH to something like 17000, which will make it prompt for updates next time.

**Comment by donmccurdy** [comment]
Thanks, yeah I can reproduce the issue after changing LAST_EPOCH. This is on macOS 10.13.2. I have another Mac with similar setup that isn't having any problem..

**Comment by mcornella** [comment]
I can't reproduce. Can you run (from your $HOME directory)
```
echo LAST_EPOCH=17000 > .zsh-update
zsh -xvic 'exit' 2>omz-debug.log
```
and post the generated file (as a private gist)

**Comment by donmccurdy** [comment]
Fill output here: https://gist.github.com/donmccurdy/b174b0c439800ac3c60572e0c02b54bb

The snippet also immediately prompts me to check for updates. 😅

**Comment by mcornella** [comment]
It looks like you're not on the latest version of OMZ since the origin remote is git://github.com/sjl/oh-my-zsh, not robbyrussell's. If you change that and upgrade you'll find that the prompt should work properly.
