### ISSUE TITLE
'Oh My Zsh brew plugin' message showing all the time

### ISSUE THREAD

**Issue by adrianbrink** [robbyrussell/oh-my-zsh#5623]
The message about the bundling of the zsh completion with brew with their 1.0 release keeps showing up.
It says at the end that this message will only appear once, however I have now seen it for the last week or so.

Any idea why that happens?

OSX 10.12
iTerm2
Homebrew 1.0.9
Homebrew/homebrew-core (git revision 3927; last commit 2016-11-06)

<img width="590" alt="screen shot 2016-11-10 at 08 25 18" src="https://cloud.githubusercontent.com/assets/11320251/20167956/46a8bfc0-a71f-11e6-846c-62297d06e5b5.png">

**Comment by mcornella** [comment]
That code [creates a hidden directory in `$ZSH_CACHE_DIR`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh#L6), so that if it's already there it fails and doesn't display the message. Can you check if it is there by running `ls -lA $ZSH_CACHE_DIR`?

**Comment by ambaxter** [comment]
I have the same issue. Here's my results:

```
ls -lA $ZSH_CACHE_DIR
total 0
drwxr-xr-x 2 abaxter staff 68 Nov  8 10:04 .brew-completion-message
-rw-r--r-- 1 abaxter staff  0 Jun  1 11:20 .gitkeep

```

**Comment by mcornella** [comment]
Well I don't know what to say. What does `which mkdir` return? And running the following gives the same result?
```
$ mkdir "$ZSH_CACHE_DIR/.brew-completion-message" 2>/dev/null && echo show || echo "don't show"
$ command mkdir "$ZSH_CACHE_DIR/.brew-completion-message" 2>/dev/null && echo show || echo "don't show"
```

**Comment by ambaxter** [comment]
```
which mkdir
mkdir: aliased to nocorrect mkdir -p
```

**Comment by ambaxter** [comment]
and

```
 abaxter@abaxter-OSX  ~  mkdir "$ZSH_CACHE_DIR/.brew-completion-message" 2>/dev/null && echo show || echo "don't show"
show
 abaxter@abaxter-OSX  ~  command mkdir "$ZSH_CACHE_DIR/.brew-completion-message" 2>/dev/null && echo show || echo "don't show"
don't show
```

**Comment by mcornella** [comment]
Thanks for the prompt response, if you update with `upgrade_oh_my_zsh` that should be fixed.

**Comment by ambaxter** [comment]
Confirmed fixed. thank you!
