### ISSUE TITLE
zsh: command not found: npm

### ISSUE THREAD

**Issue by Skhoshhal** [robbyrussell/oh-my-zsh#5625]
After I installed and start to use theme for Iterm2, cant't work with npm and show me every time this message. So please can you help me to solve this problem.
here is my .zshrc file : 

```
export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gnzh"

plugins=(git)

source $ZSH/oh-my-zsh.sh
```

**Comment by bradykeeling** [comment]
Have you tried adding npm to your $PATH?  

export PATH=$HOME/bin:/usr/local/bin:/usr/local/share/npm/bin:$PATH

**Comment by GavBaros** [comment]
This also works assuming you used `nvm` to install node, just paste this in your `.zshrc` and close then re-open your terminal:
`export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"`

**Comment by ar4sdoteth** [comment]
> This also works assuming you used `nvm` to install node, just paste this in your `.zshrc` and close then re-open your terminal: `export NVM_DIR=~/.nvm [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"`

I'm getting `not an identifier: [`

**Comment by mcornella** [comment]
> I'm getting `not an identifier: [`

Formatting error, see now. Open a new issue if you have other problems.
