### ISSUE TITLE
Zsh installer defaults to main repo even if installed from fork sync

### ISSUE THREAD

**Issue by DwordPtr** [robbyrussell/oh-my-zsh#5628]
I bought a new laptop and stumbled on this when setting it up. 
I made a Pr to pull from origin master when [-d .git] is true which should fix this.

**Comment by mcornella** [comment]
#5169 now pulls in the ability to install from forked by setting these variables:

> The installer respects the following environment variables, that can be set up when calling it with `VAR=value sh install.sh`.
> 
> * `REPO`: value in the form of `owner/project`. Useful for forks in GitHub (defaults to `robbyrussell/oh-my-zsh).
> * `BRANCH`: default branch to check out once the clone has finished (defaults to master).
> * `REMOTE`: full remote URL (supersedes `REPO` if set). You could for example choose an ssh remote URL, like `git@github.com:user/oh-my-zsh`, or another fork from GitLab or Bitbucket.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by mcornella** [comment]
Closed by #5169.
