### ISSUE TITLE
docker exec autocomplete fails when flags used

### ISSUE THREAD

**Issue by jsirex** [robbyrussell/oh-my-zsh#5636]
```bash
docker exec -it <TAB>
zsh: do you wish to see all 4151 possibilities (831 lines)?
```

**Comment by jelohe** [comment]
Doesn't work with 'grouped' flags, but it works well if the flags are separated:
`docker exec -i -t <TAB>`

**Comment by jsirex** [comment]
Thank you. It is acceptable for me.

**Comment by mcornella** [comment]
See https://github.com/docker/docker/issues/27744.
