### ISSUE TITLE
How about supporting apm?

### ISSUE THREAD

**Issue by lk-geimfari** [robbyrussell/oh-my-zsh#5640]
So, how about autocomplete for [apm](https://github.com/atom/apm)? I think that it's can be useful. What do you think about it?

**Comment by DwordPtr** [comment]
I think this would be pretty cool. I also really wish vim had something like apm.

**Comment by lk-geimfari** [comment]
@DwordPtr As I know `apm` based on `npm` . And so, if this is true, it will be fairly easy to do.

**Comment by DwordPtr** [comment]
That would be so awesome, I wonder if it'd be easier/harder to do on neovim?
I just hate installing plugins by hand in vim >.<.

**Comment by lk-geimfari** [comment]
@DwordPtr I'm sorry, but I have not worked with `vim/neovim` so I can not answer. Actually, quite strange that no one else did it for Vim.
