### ISSUE TITLE
How about removing 'r' command ?

### ISSUE THREAD

**Issue by elieteyssedou** [robbyrussell/oh-my-zsh#5642]
Hi,

I just typed `r` and my zsh re-played the last command I typed - I use oh-my-zsh ofc. I didn't knew that command and my last command was a critical one. *I find this very dangerous*.

What do you think about removing that alias/command ? I think that the up-arrow is sufficient, don't you ?

Cheers

**Comment by DwordPtr** [comment]
theres also `!!` I think this alias might be a little overkill myself.

**Comment by elieteyssedou** [comment]
`!!` is not that dangerous, it's two chars and it needs you to press return. Then it replace your `!!` by your last command. But yeah it's the same idea.

**Comment by snood1205** [comment]
If you don't like it you can just alias it to something in `.zshrc`. Try `alias r="ruby"` or `alias r="irb"` so it's not as dangerous.

**Comment by mcornella** [comment]
I can't find that alias anywhere. What plugins are you using?

**Comment by snood1205** [comment]
@mcornella For me at least, when I run `alias` I don't get `r` being an alias for repeating the last command, but it works nonetheless. It seems to be part of zsh itself.

**Comment by mcornella** [comment]
Oh yes, you're right. That's a [zsh builtin](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-r). We could disable that using `disable r`. Put that in your zshrc file in the meantime and I'll put together a PR to disable that in a more user-friendly way.

**Comment by elieteyssedou** [comment]
Then I'll use `disable r` until the feature releases. Thank you !

**Comment by sergiosalfer** [comment]
I often use `r` for recompile my code several times, I liked it.

**Comment by elieteyssedou** [comment]
I think that having the ability to enable it if needed/requested is better than have it by default. Then you could enable it in your `.zshrc`, @sergiosalfer. Don't you think ?

**Comment by snood1205** [comment]
On the whole, I'd err to the side of keeping a feature of zsh standard with the option to disable it rather than the opposite. Oh-my-zsh is intended to compliment zsh, and I think that disabling a core command would, at least in some way, go against the ideology of oh-my-zsh.

**Comment by elieteyssedou** [comment]
I understand your point @snood1205.
I view `Oh-my-zsh` as a better `zsh`. A more secure `zsh` is an improvement, in my opinion.

**Comment by sounak98** [comment]
@mcornella you don't need to find plugins for aliases. You can make aliases of your own. Open and .zshrc file. It can be either opened by `vim ~/.zshrc` or `zshrc` if you have the correct plugin. Append the file with this line `alias r='echo Hello'`. This will work and whenever you enter the command `r` it will echo Hello which is pretty harmless I guess.

**Comment by robbyrussell** [comment]
Similar to what @mcornella said, this can be a personal preference. We're not here to combat Zsh's defaults. Only to expand on them.

**Comment by josue** [comment]
This was so annoying to fix after I installed the **R** language and trying to execute it. Running "r" will never load the R binary, so the only fix I could think of:

1. Load ZSH config file via editor
```bash
zshconfig
```

2. Append the following comment + command to the end of file:
```bash
# disable "r" command (which runs previous executed command) 
# so that it doesnt interfere with the binary for "r" language.
disable r
```

**Comment by aaron-goshine** [comment]
If you use the 'R' programming language like my self this will quickly become a problem.
