### ISSUE TITLE
tab completion not working

### ISSUE THREAD

**Issue by DarthPestilane** [robbyrussell/oh-my-zsh#5651]
I have two accounts on my Macbook, both are installed oh-my-zsh. But one account cannot use the tab completion. When I uninstalled oh-my-zsh, tab completion  worked well.

**Comment by snood1205** [comment]
This seems like a non-reproducible error.

**Comment by matheusazzi** [comment]
It is happening to me too, even after updating to last version the tab completion isn't working. Not sure what happened, it suddenly stopped.

**Comment by jubeater** [comment]
it happened to me too, i update the brew, zsh,  oh my zsh, still not working. I have tried to remove the dump file, but not work.

**Comment by 1nv3rse** [comment]
it happened to me too,tab working on zsh without ohmyzsh,but can not work with ohmyzsh,

**Comment by 1nv3rse** [comment]
I have solved it!  in .oh-my-zsh/oh-my-zsh.sh, look at 14th line:
**:${ZSH_DISABLE_COMPFIX:=true}**
turn true to false,  save it,then execute  **source ~/.zshrc** ,restart your terminal,you will know some directory which are insecure,then execute **chmod 755 \<insecure-directory\>**,
at last，back to .oh-my-zsh/oh-my-zsh.sh,the 14th line,turn false to true, and **source ~/.zshrc** 
it will be solved!!!

**Comment by matheusazzi** [comment]
@1nv3rse Awesome, it worked for me, thank you.

**Comment by jubeater** [comment]
@1nv3rse  U are really awesome, it's really useful!!! Thanks very much!!

**Comment by ilhamdoanggg** [comment]
its not work on me -_-

**Comment by DarthPestilane** [comment]
I removed the account which I used to install oh-my-zsh,  and also remove oh-my-zsh, then rebuild an account and reinstall oh-my-zsh, finally everything back to normal.

**Comment by matticala** [comment]
I started having the same problem but I could find no solution. I have two users and I need oh-my-sh to work for both, applying @1nv3rse solution has shown it is complaining about Cellar being gropu writable or writable on by another user. Is there a way to disable that group check?

**Comment by jfmercer** [comment]
I, too, have this problem, but, as @snood1205 mentioned, it appears to be a non-reproducible error. At the time of this writing, I'm on the up-to-date version of omz: `b908feeb`.

**Comment by macgyver** [comment]
I had a similar problem but it seems like it's specific to iTerm2 - tab completion fails in zsh or bash using iTerm.app, but succeeds in either shell using Terminal.app (maybe your problem is different, or maybe the issue is not with zsh)

**Comment by enthurohini** [comment]
@1nv3rse, You are awesome!

**Comment by imajinyun** [comment]
@1nv3rse You are awesome!

**Comment by musicalshore** [comment]
@1nv3rse For me, simply setting ZSH_DISABLE_COMPFIX to false, executing ,.zshrc and opening a new tab was sufficient. I don't get any warnings about any insecure directory. 

I suspect that installing an OSX update my cause tab completion to break, as it was working shortly before I applied the latest Sierra update.

**Comment by DYelamos** [comment]
guys it ain't working for me, It works fine with the normal terminal, but not with this one.. Halp?

**Comment by pksheldon4** [comment]
I just started having this issue after my Mac login was moved to a network login. When I tried to uninstall/re-install zsh, I found I no longer had permissions to several of the directories. Once I updated the permissions for my current user, tab-completion began working again.

**Comment by DarthPestilane** [comment]
I happened to solve this a few time ago, been too busy too reply, sorry. I delete the account and recreate the same one, then everything works fine. Don't know why. Maybe it's the problem of my macbook.

**Comment by AnthonyWC** [comment]
Interesting I have to source ~/.zshrc in a zsh shell to get various auto bash completion to work (e.g aws zsh autocomplete) while a new session in tmux didn't work, regardless of setting true/false on ZSH_DISABLE_COMPFIX.

I really have no explanation for this behavior, I don't really have any file that should load after .zshrc (according to https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/)

**Comment by fortyMiles** [comment]
thx a lot!

**Comment by fortyMiles** [comment]
It works for me. thanks a lot! @1nv3rse

**Comment by Abuyousuf** [comment]
Tab complete not issue

**Comment by hylaride** [comment]
@AnthonyWC I had the exact same issue as you.  When new terminal windows opened, I'd have to then re-source my `~/.zshrc` before my aws autocompletion would work.  For me, the issue ended up that I was installing pip within a pyenv that was sourced/activated later in the file after the oh-my-zsh invocation.  I guess it inherited the path to the `aws_zsh_completer.sh` script from that later activation when I sourced the file again manually.

Moving up the pyenv activation to before ZSH fixed it for me!

**Comment by mcornella** [comment]
If you're seeing this, I've just updated OMZ to ignore permission issues with your completion scripts and load them anyway, but you have to set this in your zshrc file:
```
# this goes before oh-my-zsh.sh is sourced
ZSH_DISABLE_COMPFIX=true
```

**Comment by claymcleod** [comment]
For me, there were no permission issues on my completion scripts so the above didn't fix my issue. Since this the top thread for tab completion not working in oh-my-zsh, I figured I'd post my solution for anyone in the same boat.

If the above doesn't work for you, try removing any `.zcompdump` files in your home directory. Credit: https://unix.stackexchange.com/a/210931.

```bash
rm ~/.zcompdump*
```

**Comment by 2inqui** [comment]
> For me, there were no permission issues on my completion scripts so the above didn't fix my issue. Since this the top thread for tab completion not working in oh-my-zsh, I figured I'd post my solution for anyone in the same boat.
> 
> If the above doesn't work for you, try removing any `.zcompdump` files in your home directory. Credit: https://unix.stackexchange.com/a/210931.
> 
> ```shell
> rm ~/.zcompdump*
> ```

This was to fix for me after trying all the other options. I would like to know what could cause that problem though so if posible we can add a fix to prevent this from happening again in the future.

**Comment by balalaXD** [comment]
I have tried all the solutions above and **NONE** of them work, and test under `iTerm2` and `Terminal`. 😭 😭 😭

**Comment by Kuangcp** [comment]
> I have tried all the solutions above and **NONE** of them work, and test under `iTerm2` and `Terminal`. sob sob sob

meet the same problem, tried too many way 
emmm , apt remove --purge zsh then install zsh 
it work

**Comment by lucasvinals** [comment]
Guys! It's more simple than that. 
Just add a single space in front of the opening/closing parenthesis, execute a **source ˜/.zshrc** and all plugins start working!

**Comment by Sp0rTB4cK** [comment]
> For me, there were no permission issues on my completion scripts so the above didn't fix my issue. Since this the top thread for tab completion not working in oh-my-zsh, I figured I'd post my solution for anyone in the same boat.
> 
> If the above doesn't work for you, try removing any `.zcompdump` files in your home directory. Credit: https://unix.stackexchange.com/a/210931.
> 
> ```shell
> rm ~/.zcompdump*
> ```

This fixed my problem. Thank you!

**Comment by expelledboy** [comment]
@claymcleod Give That Man a Bells! Thanks `rm ~/.zcompdump*` solved my problem!
