### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Devinsuit** [robbyrussell/oh-my-zsh#5652]
Page http://ohmyz.sh/community.  http://blog.secondplanetanimation.com/2011/05/31/zsh & http://thechangelog.com/episode-0-6-1-oh-my-zsh-with-robby-russell/  are broken.

**Comment by mcornella** [comment]
Thanks, reported.

**Comment by robbyrussell** [comment]
Thanks @Devinsuit !

http://ohmyz.sh/community/

Updated!
