### ISSUE TITLE
Rename Pure theme?

### ISSUE THREAD

**Issue by sindresorhus** [robbyrussell/oh-my-zsh#5657]
Hi. I'm the author of the original [Pure](https://github.com/sindresorhus/pure) theme.

While the [Pure theme in this repo](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/pure.zsh-theme) share the same name, they no longer share any code. People constantly get confused by thinking the Pure theme here is the same as mine and complain about missing and non-working things.

Would you be willing to rename the theme to something else to end confusion?

Suggestions:

- pristine
- refined
- purest

**Comment by mcornella** [comment]
I'll see what I can do.

**Comment by thiagotalma** [comment]
And why not add the "real" Pure theme to make our life easier??

Please do this and get the fuss over.

**Comment by sindresorhus** [comment]
@thiagotalma I don't want to see Pure bundled here. It will just get out of date. I much rather have one canonical place for it.

**Comment by mcornella** [comment]
Yes, as is now Oh My Zsh doesn't have a proper way to use external themes and plugins. I could set up a way to add it as a git submodule but there's no good way to auto-update it yet. But it is a very requested feature.

**Comment by mcornella** [comment]
I won't just use the current Pure theme because people might be using the current one and be happy with it. But I will give information to either use Sindre's one or the current OMZ one. I've renamed it to refined for now, will submit a PR today or tomorrow!

**Comment by GuillaumeAmat** [comment]
@mcornella Did you submit your PR?

**Comment by mcornella** [comment]
Fixed in 66bae5a5
