### ISSUE TITLE
wrong symbols in Agnoster Theme

### ISSUE THREAD

**Issue by CDitzel** [robbyrussell/oh-my-zsh#5665]
I installed oh-my-zsh and on top of that solarized as well as menlo. However, if I pick  under "Profile preferences" in the terminal the menlo font, the extra characters are displayed wrong.

Does anyone know why?

thanks in advance

**Comment by jemshit** [comment]
You have to install the theme i think: https://github.com/agnoster/agnoster-zsh-theme

I have background color problem, it is always black, not changing damnit

**Comment by mcornella** [comment]
Menlo is not a Powerline font if I recall correctly. You have to install one of [these Powerline fonts](https://github.com/powerline/fonts). This is [documented in agnoster's setup guide](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster).
