### ISSUE TITLE
Mention that the install blows away .zshrc

### ISSUE THREAD

**Issue by daveyostcom** [robbyrussell/oh-my-zsh#5678]
The **Basic Installation** section should mention that your .zshrc file will be completely overwritten.

**Comment by dpatou** [comment]
Isn't any existing .zshrc backed up to ~/.zshrc-pre-oh-my-zsh (as per https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/install.sh#L73) ?

**Comment by daveyostcom** [comment]
That would make a nice comment at the top. :)

**Comment by dpatou** [comment]
Maybe, the install script feedbacks about it tho (line above the one I linked) so that might be unnecessary. Launching a "quick install script" without reading neither the script nor its output is kinda careless.

**Comment by mcornella** [comment]
It does not, and the installer actually prints where it leaves the backup.
