### ISSUE TITLE
Please rethink the experience for new users.

### ISSUE THREAD

**Issue by daveyostcom** [robbyrussell/oh-my-zsh#5687]
I installed OhMyZsh so that when I relaunch the macOS Terminal app, windows will reopen in the same dir where they were at Quit.

Maybe I will want some of the other OhMyZsh features eventually, but OhMyZsh should let me phase them in as I understand them and decide to try them.

I suggest:
1. The install should not replace .zshrc. It should insert one line at the beginning of .zshrc:
  `source ~/.zsh-ohmyzshrc`

2. ~/.zsh-ohmyzshrc should not enable anything. Every feature or feature set should be controlled by a line in the file. Every one of these lines should be designed for opt-in, not opt-out, either by uncommenting or by some other convention that is clear by inspection whether it is currently set to enable or to disable some feature.

3. Consider splitting ~/.zsh-ohmyzshrc into sections, each enabled by a
  `source ~/.zsh-ohmyzshrc`
line the various zsh startup files, .zshrc, .zlogin, etc.

If you do this you will get a lot more adoption. As it is now, who would want to turn on a giant ball of stuff in their shell and just see what happens? Silly me. I did that. Now I have to back it all out.

**Comment by mastrauckas** [comment]
I just installed OhMyZsh for the first time too and don't like how it just completely replaces the `.zshrc` file. Like @daveyostcom said it would be better if it put a line in my own .`.zshrc` file and `source ~/.zsh-ohmyzsrc` instead of replacing it.

**Comment by mcornella** [comment]
As per a better zshrc replacement, there are other issues that ask for this and we're working on it.

As per the rest, I don't think opt-in is the Oh My Zsh approach. What we aim for is setting up a baseline configuration that we've come to expect from a clean zsh setup. There are though a number of settings that are documented in the zshrc template, but having an Oh My Zsh setting for every zsh setting is implausible.
