### ISSUE TITLE
Agnoster doesn't work even after using Meslo For Powerline

### ISSUE THREAD

**Issue by chris-fa** [robbyrussell/oh-my-zsh#5689]
I followed the original Agnoster repository instructions, and I also tried [this link](https://gist.github.com/kevin-smets/8568070) try and make Agnoster work. I tried using [Meslo for Powerline](https://github.com/powerline/fonts/blob/master/Meslo/Meslo%20LG%20M%20DZ%20Regular%20for%20Powerline.otf)

This is what happens:
<img width="465" alt="screen shot 2016-12-03 at 4 32 30 pm" src="https://cloud.githubusercontent.com/assets/22173137/20862352/262a37ce-b976-11e6-97de-87f9f458a383.png">

I'd like to try some ideas before uninstalling iTerm2 and reinstalling

**Comment by chris-fa** [comment]
Nvm, I had to put `Non-ASCII` font section too... my bad

**Comment by mcornella** [comment]
Yeah we should make a dedicated wiki section just for properly setting up Powerline fonts 😂

What terminal were you using, for the docs?

**Comment by chris-fa** [comment]
`iTerm2`, it has option for `fonts` and `non-ASCII fonts`. I had assumed (because I'm dumb :joy:) that I was only supposed to change the first one, but it's both 😂

**Comment by mcornella** [comment]
Nice. I think that's so you can use the same font you were using except one that supports symbols for non-ascii chars. You're not dumb :wink:

**Comment by aneesh-joshi** [comment]
For those still trying to figure it out:
https://gist.github.com/renshuki/3cf3de6e7f00fa7e744a
