### ISSUE TITLE
Backdoors possibilities reduction

### ISSUE THREAD

**Issue by KOLANICH** [robbyrussell/oh-my-zsh#5697]
Shell augmentations is a nice way to introduce backdoors. Especially popular augmentations like oh-my-zsh. It consist of tonns of addons, it is nearly impossible to audit them all. Especially in such a language as a shell where there are plenty of ways to shot your leg with ok-looking code. So I think we should pick the most popular zsh addons for most popular software like ```git``` and ```dd``` and move everything else into a separate repos. This will reduce attack ~~surface~~volume by reducing presence of unneeded and unaudited code in user's system.

**Comment by mcornella** [comment]
I agree with the diagnostic but the solution is worse. I'd rather have the code bundled within OMZ than having it be outside the repository and outside our control.

This is a complex topic though. Closing until there's a better solution.
