### ISSUE TITLE
setting terminal tab title

### ISSUE THREAD

**Issue by shiyuangu** [robbyrussell/oh-my-zsh#5700]
Hi, 
On Ubuntu 16.04(Xenial Xerius): I try to set the terminal tab title following [this post](http://blog.pengyifan.com/how-to-set-terminal-title-dynamically-to-the-current-working-directory/):
```
print -Pn "\e]1;test_title\a"
```
which has actually no effect. I wonder whether this problem is caused by interference with oh-my-zsh. I notice that `lib/termsupport.zsh` does define a title() function which has no effect either: 
```
title short_tab
```
Any help/suggestion on this is appreciated.

**Comment by heruan** [comment]
Any news on this? I'm experiencing it too.

**Comment by saurfangg** [comment]
@shiyuangu You probably need to edit your `~/.zshrc` file and uncomment the following line:

`DISABLE_AUTO_TITLE="true"`

After that you can change a tab's title with something like:
`echo -e "\033];this is the title\007"`

**Comment by tareqalam** [comment]
@shiyuangu solution works, just added a method inside .zshrc like this:
```
function set-title(){
  TITLE="\[\e]2;$*\a\]"
  echo -e ${TITLE}
}
```
then I can call the method in terminal like this:
set-title 'whatever i want'

**Comment by cameck** [comment]
You can put right underneath the `DISABLE_AUTO_TITLE="true"` (as stated by @saurfangg) this:

```zsh
function precmd () {
  window_title="\033]0;${PWD##*/}\007"
  echo -ne "$window_title"
}
```
That will set the tab to have the title of the current file directory and using the `precmd` will enable it to [execute before each prompt](http://zsh.sourceforge.net/Doc/Release/Functions.html).

Better yet, you should put this code in your own custom profile to keep things neat.

**Comment by llinfeng** [comment]
Managed to put hostname + emoji in the tab title as well (using Windows Terminal and WSL). My tab title looks like: `Hostname😎Foldername`.
```
HOSTNAME=$(hostname)
DISABLE_AUTO_TITLE="true"
function precmd () {
  window_title="\033]0;$HOSTNAME😎${PWD##*/}\007"
  # HOSTNAME="i510"
  # echo -ne "$HOSTNAME"
  echo -ne "$window_title"
}
```
@cameck @saurfangg One more question though: how to further let the tab-title rename itself when I enter the command-line Vim? The terminal does not opt to display Vim's own `titlestring` setting. Of course, I prefer to have the tab-title resume its `Hostname😎Foldername` format when I exit Vim.

**Comment by M-Younus** [comment]
add this in `~/.zshrc`
```
function set-title() {
  echo -en "\e]2;$@\a"
}
```

ref : [https://stackoverflow.com/a/59626071/5398403](url)

**Comment by cafink** [comment]
@jacobpierce1 I believe the additional information is being set by the OSX terminal application, not by zsh.  You can disable some of all of it via the terminal preferences, under "Profiles."  There's a "tab" section that lets you choose what information to display in the tab title.

**Comment by Justsoos** [comment]
actually, it is a function of oh my zsh, here:
https://github.com/ohmyzsh/ohmyzsh/blob/2eb3e9d57cf69f3c2fa557f9047e0a648d80b235/lib/termsupport.zsh#L52
```
# Runs before showing the prompt
function omz_termsupport_precmd {
  [[ "$DISABLE_AUTO_TITLE" == true ]] && return
  title $ZSH_THEME_TERM_TAB_TITLE_IDLE $ZSH_THEME_TERM_TITLE_IDLE
}
```
@llinfeng the best way to auto-change the title and same time containing your custom titles is to change this function here.

so, have people release some open API for it and avoid modifying the source code ?
for example, adding some Sign-Title for user custom proxy running/quit mode ? like appending some custom code on string $ZSH_THEME_TERM_TAB_TITLE_IDLE ?

**Comment by jonsmithers** [comment]
I'd like to customize the title used for an idle zsh shell, but I _don't_ want to disable the "auto title" feature.

Examples of why "auto title" is nice: when I run `vim`, the title auto changes to `vim`. If I run `sleep 1000`, the title auto changes to `sleep 1000`. When I "DISABLE_AUTO_TITLE" and do it all myself, I lose this behavior.

**Comment by mcornella** [comment]
@jonsmithers I've now documented the automatic title settings in the wiki, [have a look](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#automatic-title).
