### ISSUE TITLE
Python anaconda

### ISSUE THREAD

**Issue by beatorizu** [robbyrussell/oh-my-zsh#5703]
This packages and environment manager is powerful and useful python tool and its could be a great idea if oh-my-zsh framework had a plugin for that

**Comment by mcornella** [comment]
Reopen if there is still interest in this. FWIW, there exists [this one](https://github.com/dougalsutherland/anaconda.zsh) which you could clone in your custom folder, see [customization](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#adding-a-new-plugin).
