### ISSUE TITLE
showing weird characters

### ISSUE THREAD

**Issue by underscore-ex** [robbyrussell/oh-my-zsh#5709]
I followed the tutorial and installed oh-my-zsh with agnoster theme but i guess it didn't get installed properly. How can i fix it 

[console screenshot](https://www.dropbox.com/s/8lexeekved9gq4x/Screenshot%202016-12-12%2023.13.13.jpg?dl=0)

**Comment by mcornella** [comment]
You need to install a [Powerline font](https://github.com/powerline/fonts). This is all outlined in the [wiki section of agnoster](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster).
