### ISSUE TITLE
Question: How to edit my ZSH Git plugin alias?

### ISSUE THREAD

**Issue by zulhfreelancer** [robbyrussell/oh-my-zsh#5713]
I want to change my `gm` alias from `git merge` to `git merge --no-ff`. I came across this [file](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh) but I've no idea how to get into it from my local machine.

Please help.

**Comment by stevenspasbo** [comment]
You load the plugins by adding them to the `plugin` variable in your `.zshrc`.

    # For example
    # If only loading the git plugin, set it with
    plugins=(git)
    # Load omz
    source "$ZSH/oh-my-zsh.sh"
    # Here is where you would override any omz defaults
    alias gm=git merge --no-ff

**Comment by zulhfreelancer** [comment]
Thank you @stevenspasbo for your kind help.

**Comment by stevenspasbo** [comment]
No problem, that's how you can load any plugins that are in the plugin directory. Here's what I have in my zshrc:

    # Plugins I want loaded for all environments
    plugins=(common-aliases)
    [[ -s $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ]] && plugins+=(zsh-syntax-highlighting)
    # Check for executables
    # Plugins I only want loaded when application is installed
    for p (git tmux vagrant grunt composer); do
      if type $p > /dev/null; then
        plugins+=($p)
      fi
    done

[Link to plugins wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins)

[Link to plugins overview that has descriptions of all available plugins](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins-Overview)

**Comment by mcornella** [comment]
Thanks @stevenspasbo!

**Comment by lizzmo** [comment]
> You load the plugins by adding them to the `plugin` variable in your `.zshrc`.
> 
> ```
> # For example, if only loading the git plugin, set it with
> plugins=(git)
> # Load omz
> source "$ZSH/oh-my-zsh.sh"
> # Here is where you would override any omz defaults
> alias gm=git merge --no-ff
> ```

Just in case anyone else has this issue, I needed to add single quotes around the new definition to get it working `alias gm='git merge --no-ff'`

**Comment by mcornella** [comment]
Fixed in the original comment, thanks.

**Comment by xuwhite** [comment]
How do I change the an alias that contains "$(current_branch)"?
