### ISSUE TITLE
themes / prompt not working

### ISSUE THREAD

**Issue by benklett** [robbyrussell/oh-my-zsh#5719]
On my Linux PC the oh-my-zsh themes are not working correctly.

I always have the following prompt:
`ben@Ben-PC-Arch ~ % `

I recorded a short clip demonstrating the problem:
[https://asciinema.org/a/0daf3p2uuvwwysk912ix2fo8g](https://asciinema.org/a/0daf3p2uuvwwysk912ix2fo8g)

My zsh version is 5.3.

**Comment by mcornella** [comment]
That's interesting, this is what I get:
![captura de pantalla de 2016-12-21 13-58-41](https://cloud.githubusercontent.com/assets/1441704/21390139/9e944692-c785-11e6-8e1b-25db67d3bcfd.png)

I assume `zsh -f` gets you a different thing altogether. Is it possible that you're setting a different `$PROMPT`/`$PS1` at the end of you zshrc file? If not, post the full contents of it, maybe some plugin is messing up your theme.

**Comment by benklett** [comment]
Yeah, `zsh -f` prints:
`Ben-PC-Arch%`

I already tried completely reinstalling zsh but that did not help either. My current .zshrc is: [https://gist.github.com/benklett/db8d51f894e4796339b336cac991c192](https://gist.github.com/benklett/db8d51f894e4796339b336cac991c192)

**Comment by mcornella** [comment]
Hmm interesting... Do you have a `.zshenv` file? If not, try the big guns by running zsh in debug mode and posting the resulting file:
```zsh
zsh -ixv -c 'exit' &> >(tee ~/omz-debug.log 2>/dev/null)
```

**Comment by benklett** [comment]
I do not have a `.zshenv` file.

I uploaded the log file:
[https://gist.github.com/benklett/25201ad85673b44a7fa4c93963a246a4](https://gist.github.com/benklett/25201ad85673b44a7fa4c93963a246a4)

**Comment by benklett** [comment]
Ahh, now I know. The package `grml-zsh-config` on arch adds a system-wide `zshrc`, which messes with oh-my-zsh.
I removed the package and that resolved the issue.

**Comment by benklett** [comment]
Thank you for your advice.

**Comment by mcornella** [comment]
Awesome, thank *you* for posting the solution!

**Comment by bertabus** [comment]
Removing grml-zsh-config worked for me as well. THX :thumbsup:
