### ISSUE TITLE
Can't Install, Connection Refused

### ISSUE THREAD

**Issue by Alirezaies** [robbyrussell/oh-my-zsh#5727]
I used to install `oh-my-zsh` with different ways, but I get `443, Connection Refused`.

**Comment by mcornella** [comment]
This has to be a momentarily github issue. I bet if you try now it'll work!

**Comment by Alirezaies** [comment]
Still fails xD

I've found the problem, because the server rejects connection from Iran, 
I tried to download the script using Tor, worked.
Thanks any way :+1:

**Comment by mcornella** [comment]
That's interesting info. It's more probable that Iran has some sort of firewall that rejects it though.

Thanks!
