### ISSUE TITLE
Problem with zsh version 5.3.1

### ISSUE THREAD

**Issue by Cabbagec** [robbyrussell/oh-my-zsh#5728]
Arch Linux has upgraded zsh to version 5.3.1 recently.
A directory problem:
```
_systemctl_startable_units:4: failed to load module `zsh/regex': /usr/lib/zsh/5.3/zsh/regex.so: cannot open shared object file: No such file or directory
_systemctl_startable_units:4: -regex-match not available for regex
```
`ln -s /usr/lib/zsh/5.3.1 /usr/lib/zsh/5.3` is my temporary fix.

**Comment by bes** [comment]
I have this problem too, but on OSX. 

Recently upgraded to 5.3.1 using `brew` and this error started popping up.

```
zsh --version
zsh 5.3.1 (x86_64-apple-darwin15.6.0)
```

When trying to use the `diff` command and pressing <tab>, this happens:

```
(eval):1: _diff: function definition file not found
```

**Comment by bes** [comment]
Problem solved on OSX by doing this:

```
rm -f ~/.zcompdump*
```

Then restarting the terminal.

For the gradle autocompletion to work again, I had to delete the .gradletasknamecache file in the respective gradle directories.

Solution [found on stackoverflow](http://stackoverflow.com/a/10585017/816017), instant upvote ;)

**Comment by MaxMatti** [comment]
The solution provided by bes worked for me after the upgrade to zsh 5.4.2 on archlinux.
