### ISSUE TITLE
Bwana plugin blocks access to standard man

### ISSUE THREAD

**Issue by michalpiekarski** [robbyrussell/oh-my-zsh#5732]
[Bwana plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/bwana/bwana.plugin.zsh) should have a different name for the function. Currently it's `man` which (after enabling the plugin) make using standard `man` impossible.
I would suggest changing it to `bwana`.
/cc @avit

**Comment by mcornella** [comment]
You could run `command man` instead, but I guess we could change it to `bwana`. This is an easy change, would you consider opening a PR?

**Comment by BogdanRon7** [comment]
@mcornella I'd like to do that.
