### ISSUE TITLE
Short alias for `git grep`

### ISSUE THREAD

**Issue by elazarl** [robbyrussell/oh-my-zsh#5734]
`git grep` is a useful idiom, searching only for relevant source files in the repository.

Yet, there's no short alias for it in the git plugin.

Wouldn't it be useful to add one?

**Comment by mcornella** [comment]
You can set one up in your zshrc file. It doesn't seem to have much interest.

**Comment by elazar-lb** [comment]
I think it goes without saying that a standard alias available by default is more useful than per-user config.

But I'm not sure how to measure actual usage of aliases.
