### ISSUE TITLE
gulp doesn't work if a gulp directory exists

### ISSUE THREAD

**Issue by mgol** [robbyrussell/oh-my-zsh#5735]
I have a similar issue to the now-closed #4615; when I have the `gulp` directory in the current working directory, running the `gulp` command cds to that directory instead of invoking gulp. The difference, though, is that neither rehashing nor opening a separate terminal tab helps; it always cds.

The difference in the setup is that I generally don't use global packages; I have:
```sh
export PATH="$PATH:./node_modules/.bin"
```
in my `.zshrc` so when I'm in the main directory of the project I can run `gulp` without a global `gulp-cli` installation.

I can also verify that it **does** see the command:
```
$ which gulp
./node_modules/.bin/gulp
```

**Comment by LandonSchropp** [comment]
@mgol Did you ever find a solution to this? I'm experiencing the same problem with Prezto.

**Comment by mgol** [comment]
@LandonSchropp I just renamed the `gulp` directory 🤷‍♂️

**Comment by ArmandoAmador** [comment]
I know this is an old issue, but I was able to fix this issue by running `rehash`

**Comment by mcornella** [comment]
@mgol can you look into what `echo $commands[gulp]` throws?
