### ISSUE TITLE
Issue using zsh after iterm2

### ISSUE THREAD

**Issue by modqhx** [robbyrussell/oh-my-zsh#5749]
Hi, I couldn't find answer to this online, but a rather basic question. So I installed zsh. Seems to work fine except the profiles. I installed it on terminal. For example:
In iterm2, if you do `pip --version` --> you get, `pip 9.0.1 from //anaconda/lib/python2.7/site-packages (python 2.7)`
But in zsh, when I run the same command, I get: 
```
pip 8.1.1 from /Library/Python/2.7/site-packages (python 2.7)
```
I tried appending the entire contents from `.bash_profile` to `.zshrc` but still no luck..
Any idea on how to solve this? 

**## ** UPDATE: NEVERMIND, THE PROBLEM WAS SOLVED ** This issue can be closed. Sorry.**

**Comment by mcornella** [comment]
Hi! Thanks for closing, but another way you can help more is posting the solution after closing the issue. What did you do to solve this?

**Comment by modqhx** [comment]
@mcornella Agree! So I thought on installing zsh it automatically import all env/exports variables from `.bash_profile` or `.bashrc` since I was using iTerm2 before this.. But it does not. You have to manually copy paste all contents from `.bash_profile` to `.zshrc`. After that it worked..
