### ISSUE TITLE
git stash apply/pop autocomplete works wrong

### ISSUE THREAD

**Issue by neworld** [robbyrussell/oh-my-zsh#5754]
If I write:
```
git stash pop
```
and press `TAB`, zsh fills correctly:
```
git stash pop stash@{
```
If I press TAB again, instead of go through list of stashes, it adds `{`
```
git stash pop stash@{{
```

Used latest version

**Solution:** if you are using mac with installed git via brew, [this fix](https://github.com/robbyrussell/oh-my-zsh/issues/5754#issuecomment-278968514) could help you

**Comment by okapia** [comment]
What version of zsh. And what does `git stash list` output?

I would have expected the `{` to be quoted from the first TAB: `stash@\{`

**Comment by slavaGanzin** [comment]
Works as expected on:
zsh 5.2 (x86_64-unknown-linux-gnu)

**Comment by neworld** [comment]
Terrible sorry for forgotten issue. I am using `zsh 5.3.1 (x86_64-apple-darwin16.3.0)` and it doesn't work as expected (at least for me):

![zsh_git_stash_bug](https://cloud.githubusercontent.com/assets/38703/22751210/4b6c5d64-ee3c-11e6-930b-2f377f4a9c05.gif)

I expect that `<tab>` should go through all stashes

**Comment by okapia** [comment]
neworld: the output of `git stash list` could be crucial to solving this. I can't reproduce it either with a minimal plain zsh setup or a minimal oh-my-zsh setup. Could you also try cutting your setup down, Absolute minimum would be no oh-my-zsh and just `autoload -U compinit; compinit` (any less and there's no git completion at all).

**Comment by neworld** [comment]
No problem. List:
```
➜  android git:(master) ✗ git stash list
stash@{0}: WIP on master: f424dadd0 Unify my items (#7861)
stash@{1}: On master: proguard-for-cleaning
stash@{2}: WIP on master: 5490edada Feature switch to set newsfeed tab position (#7836)
stash@{3}: On master: Version checked
stash@{4}: On master: Chage fonts
stash@{5}: On master: custom fonts
stash@{6}: On master: monkey
stash@{7}: On master: Move models to native build
stash@{8}: On feature/block_appmsg: GCM test
```

I am not sure, what to test with minimal setup, but `<tab>` shows list of the files (as expected without ozh), and `git stash list` is:
```
Andriuss-MacBook-Pro-3% git stash list
stash@{0}: WIP on master: f424dadd0 Unify my items (#7861)
stash@{1}: On master: proguard-for-cleaning
stash@{2}: WIP on master: 5490edada Feature switch to set newsfeed tab position (#7836)
stash@{3}: On master: Version checked
stash@{4}: On master: Chage fonts
stash@{5}: On master: custom fonts
stash@{6}: On master: monkey
stash@{7}: On master: Move models to native build
stash@{8}: On feature/block_appmsg: GCM test
```

But git autocomplete works after I run `autoload -U compinit; compinit`, but without completion of stashes. I have something installed in `/usr/local/share/zsh/site-functions/`:
```
Andriuss-MacBook-Pro-3% ls /usr/local/share/zsh/site-functions/
_brew			_brew_cask		_docker-compose		_git			_lein			_tig			git-completion.bash	tig-completion.bash
```

BTW, git version 2.11.0 and ozh git log:
```
➜  .oh-my-zsh git:(master) git log --oneline
d2725d4 Add goodreads search provider (#5778)
0b4bba4 Change af-magic theme's branch color (#5730)
cae540f Adding new path to look for activate.sh (#5654)
4608231 Improved gradle options (arguments) completion (#5743)
```

**Comment by okapia** [comment]
Where does the `_git` in `/usr/local/share/zsh/site-functions` come from?!

That is more than likely overriding the `_git` that comes with zsh - run `print -l $fpath` to see the order in which directories are searched for functions such as _git. Has it come from homebrew or did you potentially copy it there yourself? And what are bash completions doing in that directory?

**Comment by neworld** [comment]
@okapia, thank you for an effort. Here the problem was. I removed that `_git` and problem fixed. 

I solved problem by reinstalling git without completions:
```
brew unlink git
brew install git --without-completions
```

BTW `$fpath` is:
```
➜  android git:(master) ✗ print -l $fpath
/Users/neworld/.oh-my-zsh/plugins/osx
/Users/neworld/.oh-my-zsh/plugins/gradle
/Users/neworld/.oh-my-zsh/plugins/docker
/Users/neworld/.oh-my-zsh/plugins/brew
/Users/neworld/.oh-my-zsh/plugins/adb
/Users/neworld/.oh-my-zsh/plugins/git
/Users/neworld/.oh-my-zsh/functions
/Users/neworld/.oh-my-zsh/completions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/5.2/functions
```

Is there any way to prevent other users face the same issue? Or simply close an issue?

**Comment by okapia** [comment]
I'd regard it as an issue with home brew or wherever it is that the broken _git completion comes with. They should just delete it.
