### ISSUE TITLE
An error in python code execution takes me to home folder on zsh

### ISSUE THREAD

**Issue by keyurgolani** [robbyrussell/oh-my-zsh#5761]
I've been working on Python codes on MacOS Sierra Platform.

I've noticed that sometimes when the Python code fails and exits with an exception, the zsh automatically gets out of the directory and goes to the home directory.

I assume that zsh crashes along with the Python code and reinitializes.

**Comment by mcornella** [comment]
Try to make a screencast of such behavior. You can use asciinema.

El dom., 8 ene. 2017 2:48, Keyur Golani <notifications@github.com<mailto:notifications@github.com>> escribió:

I've been working on Python codes on MacOS Sierra Platform.

I've noticed that sometimes when the Python code fails and exits with an exception, the zsh automatically gets out of the directory and goes to the home directory.

I assume that zsh crashes along with the Python code and reinitializes.

**Comment by keyurgolani** [comment]
Have an asciinema link.
Please check.
https://asciinema.org/a/dp7075tgl4ngrzxckr8wstou9
Thank you

**Comment by mcornella** [comment]
I'm not aware of any functionality that would make zsh behave like this. It seems to me that whatever that code is running, when your script breaks it cannot process the rest of the input and that gets swallowed by the zsh session. 

However, it doesn't seem there's neither a zsh fault or an ohmyzsh fault behind it. You can post the script and I'll take a look, but I'm closing this until new information makes it clear it is our problem. 

Thanks and good luck on the Qualification Round!
