### ISSUE TITLE
Don't alter the output format of the `time` command

### ISSUE THREAD

**Issue by dandv** [robbyrussell/oh-my-zsh#5763]
This must've been reported before, but searching didn't yield any issue:

Under zsh:

```
~ time uname
Linux
uname  0.00s user 0.00s system 0% cpu 0.001 total
```

I want the output of `time` to keep its original format, as when launched from bash:

```
~ bash
dandv:~$ time uname
Linux

real	0m0.001s
user	0m0.000s
sys	0m0.000s
```

I use the default `robbyrussell` theme and haven't found anything in it that seems to configure the output of `time`.

**Comment by apjanke** [comment]
OMZ doesn't change the output of `time`. That's just the normal behavior of the `zsh` `time` command.
