### ISSUE TITLE
Cannot disable the alias ...

### ISSUE THREAD

**Issue by hongkai-dai** [robbyrussell/oh-my-zsh#5766]
I am trying to temporarily disable the alias "...", which is defined as `alias -g ...=../..`. I tried to disable this alias by
```
disable -a ...
```
but I received the error 
```
disable : no such hash table element: ../..
```

On the other hand, I am very sure that `...` is aliased in `~/.oh-my-zsh/lib/directory.zsh`, and can be verified in the zsh terminal by
```
$ echo ...
../..
```

**Comment by apjanke** [comment]
Use a `\` to escape it and prevent the global alias expansion in your `disable` command.

```
$ disable -a ...
disable: no such hash table element: ../..
$ disable -a \...
$ which ...
... not found
```

**Comment by hongkai-dai** [comment]
Thanks for the help! That solves the problem
