### ISSUE TITLE
Add completion for nmcli

### ISSUE THREAD

**Issue by sidahmed-malaoui** [robbyrussell/oh-my-zsh#5768]
Can you add completion for `nmcli` (Network Manager Command Line Interface). This command allows to control the `network-manager` from the terminal.

The default completion that is in zsh is obsolete (here is [file](https://github.com/zsh-users/zsh/blob/master/Completion/Linux/Command/_nmcli) in github) and gives wrong completions.

**Comment by mcornella** [comment]
The current version is up-to-date: https://github.com/zsh-users/zsh/blob/eada7e1138a3fca90f085dd764ad86098e58c9ac/Completion/Linux/Command/_networkmanager
