### ISSUE TITLE
support regular expression

### ISSUE THREAD

**Issue by MetaiR** [robbyrussell/oh-my-zsh#5770]
Hello,
in the normal bash we can use something like this:
`sudo apt remove nvidia-*`
but it's not working in zsh.
it will be very good if it's going to be support it

**Comment by okapia** [comment]
To get bash behaviour, use `setopt nonomatch`
However, it is better to get in the habit of quoting special characters like `*` if you don't want shell filename generation: `nvidia-\*`. It's better to get error messages if a file glob fails than have it passed on to the command.
