### ISSUE TITLE
rails test autocompletion not working

### ISSUE THREAD

**Issue by Geesu** [robbyrussell/oh-my-zsh#5772]
Similar to how you can execute `rake test <tab>` and it will list directories/options, `rails test <tab>` doesn't have autocompletion.

Plugins in `~/.zshrc`:

`(brew git git-extras osx ruby rails rbenv rand-quote capistrano pow screen terminalapp textmate bundler)`

This does work properly in bash.

**Comment by kieraneglin** [comment]
To all those who follow, here is the fix:

1. Open `~/.oh-my-zsh/plugins/rails/_rails`
2. Change
```bash
if (( CURRENT == 1 )); then
  _describe -t commands "rails subcommand" _1st_arguments
  return
fi
``` 
to

```bash
if (( CURRENT == 1 )); then
  _describe -t commands "rails subcommand" _1st_arguments
  return
else
  _files
  return
fi
```
3. `source` (or open a new terminal window)

___

If this helped, please consider 👍'ing #5881.  Thanks for the PR, @oooooooo
