### ISSUE TITLE
Update breaks oh-my-zsh -- dumps script to screen

### ISSUE THREAD

**Issue by lah435** [robbyrussell/oh-my-zsh#5775]
I just updated oh-my-zsh to the newest version on two Macs, one 10.12 and one 10.11
Now when I open a new terminal on either machine, zsh dumps the contents of a script to the screen. I restored my backed up oh-my-zsh config but it doesn't help. Only removing oh-my-zsh completely restores a normal prompt without all the junk.

Here are first few lines (see attached file):

```
Last login: Thu Jan 12 23:50:40 on ttys014
bracketed-paste-magic () {
	# undefined
	builtin autoload -XUz
}
colors () {
	emulate -L zsh
	typeset -Ag color colour
	color=(00 none 01 bold 02 faint 22 normal 03 standout 23 no-standout 04 underline 24 no-underline 05 blink 25 no-blink 07 reverse 27 no-reverse 08 conceal 28 no-conceal 30 black 40 bg-black 31 red 41 bg-red 32 green 42 bg-green 33
```

[oh-my-zsh-terminal-dump.txt](https://github.com/robbyrussell/oh-my-zsh/files/703552/oh-my-zsh-terminal-dump.txt)

**Comment by SjorsSchijff** [comment]
Running `handle_completion_insecurities` fixed the problem for me

**Comment by p-s-** [comment]
I have the same problem, but only on one of my two user accounts on my Mac.
I think this might be the issue - is it not possible to run oh-my-zsh on two user accounts?

**Comment by lah435** [comment]
I tried running `handle_completion_insecurities` as suggested by SjorsSchijff, but it did not work in my case.

`➜  lib git:(master) source compfix.zsh`
`➜  lib git:(master) handle_completion_insecurities`
`[oh-my-zsh] No insecure completion-dependent directories detected.`

**Comment by Ramiashqar** [comment]
Hi after updating oh-my-zsh I have the same problem now, every time I open my terminal it shows the same text above , have you found a solution for this ??

**Comment by mcornella** [comment]
Your `.zcompdump` file must have become corrupt. Try `rm ~/.zcompdump*` and restart the shell.
