### ISSUE TITLE
emacs plugin doesn't work correctly on mac

### ISSUE THREAD

**Issue by seagle0128** [robbyrussell/oh-my-zsh#5779]
On my macOS Sierra with zsh 5.2/5.3, emacs and e always create a new frame.

in emacsclient.sh 
```shell
 if [ "$(echo "$frameslist" | sed -n '$=')" -ge 2 ] ;then
        # prevent creating another X frame if there is at least one present.
        emacsclient --alternate-editor "" "$@"
    else
        # Create one if there is no X window yet.
        emacsclient --alternate-editor "" --create-frame "$@"
    fi
```

I think the first condition is incorrect. `>=1` is better. Is it as designed or an issue?
```shell
if [ "$(echo "$frameslist" | sed -n '$=')" -ge 1 ] ;then
```

**Comment by seagle0128** [comment]
Anyone can merge this request?

**Comment by mcornella** [comment]
This is a simple change, can you submit a PR?

**Comment by akinnane** [comment]
@seagle0128 are you able to run `emacsclient --eval '(frame-list)'` with no emacs frames created and then with a frame created. Can you add the output of those commands to this ticket, please?

**Comment by seagle0128** [comment]
- no frame created
```shell
$ emacsclient --eval '(frame-list)'
emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
emacsclient: No socket or alternate editor.  Please use:

	--socket-name
	--server-file      (or environment variable EMACS_SERVER_FILE)
	--alternate-editor (or environment variable ALTERNATE_EDITOR)
```

- With a frame created

```shell
$ emacsclient --eval '(frame-list)'
(#<frame Centaur Emacs - ~/.emacs.d/custom.el 0x10106f5b0>)
```

**Comment by mcornella** [comment]
Hey, I've been revisiting this trying to find a working solution across all platforms, could you tell me what the code below outputs both for:
1. `emacs --daemon` not running
2. daemon running but no frames visible
3. one visible frame

```
emacsclient -n -e '(frame-list-z-order)'
```

**Comment by mcornella** [comment]
I've submitted a PR which theoretically fixes this problem for both situations (one residual frame or none are available). Please test #10227 by running `omz pr test 10227`. It should work when requiring a graphical frame (`--no-wait`) or a tty frame (`-t`/`-nw`/`--tty`).
Whether it works or it doesn't, please comment in #10227.
