### ISSUE TITLE
Function definition file not found

### ISSUE THREAD

**Issue by ilievv** [robbyrussell/oh-my-zsh#5794]
Not a long time Linux user here. I looked up for similar issues but unfortunately, none helped me resolve this. I get these errors after a fresh install:

![image](https://cloud.githubusercontent.com/assets/13287035/22117537/123a36d4-de7d-11e6-9afa-eb5ad0693f05.png)

**Comment by Iambecomeroot** [comment]
Check your `$FPATH` variable.

**Comment by mcornella** [comment]
Try running `rm ~/.zcompdump*` and restarting the terminal.

**Comment by Iambecomeroot** [comment]
I would leave this open just in case. For me, I googled for days (literraly) and kept finding this one piece of advice. Finally, the solution was in my FPATH.

**Comment by Singwai** [comment]
I had a similar issue with AWS and my reason was that I didn't install AWS cli.

**Comment by ktavabi** [comment]
What exactly is the `fpath` solution? BC, I am getting this error after a macOS update, which persists even when the plugin, e.g., `spaceship` prompt, is removed.

**Comment by danicunhac** [comment]
Same here
