### ISSUE TITLE
scp tab autocompletion stopped working

### ISSUE THREAD

**Issue by sandrodz** [robbyrussell/oh-my-zsh#5801]
I'm pretty sure it used to work, but it doesn't anymore, I've most recent oh-my-zsh.

scp initiated from: macOS 10.12.2
to server: centos7

Both have oh-my-zsh installed. Keys are working fine.

**Comment by mcornella** [comment]
If this is still relevant:
Type `scp ` (note the space), then press `CTRL`+`?`, and post the resulting file as a private gist.
