### ISSUE TITLE
How to complete file paths like native Zsh and Bash?

### ISSUE THREAD

**Issue by Frederick888** [robbyrussell/oh-my-zsh#5805]
The path completion for general commands is disabled with oh-my-zsh. For example, when I type `grep -rn ` and hit TAB, it doesn't give me any hints. I've tried to disable all themes and plugins but didn't work. Any suggestions?

**Comment by GreatBahram** [comment]
@Frederick888  it's right , because after `grep -rn ` you have to put your string after that press tab and zsh show path and files for like , for example write `grep -rn "show me path" `  then press tab button

**Comment by kapsh** [comment]
After `grep -rn` you should enter search template and only then path completion will work.

**Comment by Frederick888** [comment]
@kapsh Sorry but what is "search template"?

**Comment by kapsh** [comment]
@Frederick888 I mean, `grep` is usually used as 
`grep 'some text to find aka template' filename(s)`
ZSH completion is kinda smart and tries do not complete 'text to find' with filenames.

**Comment by Frederick888** [comment]
@kapsh Ah yea, you were right. I'm used to `grep -rn . -ie "pattern"` and I just need to swap them.
