### ISSUE TITLE
Running install script when `su` to another user finds wrong home dir

### ISSUE THREAD

**Issue by codecat** [robbyrussell/oh-my-zsh#5806]
From an existing zsh shell, I do: `su testuser` which brings me into a bash shell for the user `testuser`.

I then run the install script from that user. It then tells me oh-my-zsh is already installed because it is found in *my* home dir (the user logged in before switching user):

```
You already have Oh My Zsh installed.
You'll need to remove /home/angelog/.oh-my-zsh if you want to re-install.
```

**Edit**: It seems like I have to `unset ZSH` and then run the install script for this to work. Should this be closed?

**Comment by mcornella** [comment]
That's an interesting side effect we hadn't considered, thanks for reporting it.
