### ISSUE TITLE
Make adb pull complete filenames from device

### ISSUE THREAD

**Issue by dov** [robbyrussell/oh-my-zsh#5808]
Currently filename completion after `adb pull ` is done on local files instead of on files on the android device. Similarly for completion of the second parameter when doing `adb push localfile remote`. It would be nice to have the same kind of remote behavior as with ssh when doing `scp local remote`.

**Comment by dov** [comment]
For what it is worth the following code does a reasonable completion through the `compctl` command. I'm still too much at loss with zsh to merge it with the adb plugin.

```
function -K adblist { 
  read -l cmdline; 
  args=("${(@s/ /)cmdline}")

  if [[ ( $args[2] == "pull" && $#args -eq 3 )
        || ( $args[2] == "push" && $#args -eq 4) ]]; then
    reply=(`adb shell ls -a1d $1\* 2&>/dev/null`)
  else
    reply=(`ls -a1d $1*`)
  fi  
} 
compctl -K adblist adb

```

**Comment by mcornella** [comment]
Make a PR, it looks nice.

**Comment by dov** [comment]
I'm confused, as I realized that `adb pull` is being completed in my shell, even though I'm not using the above code.  So who *is* doing the completion? And if completion works, then m code seems redundant.

**Comment by mcornella** [comment]
Oh I see, [the official zsh distribution](https://github.com/zsh-users/zsh/blob/03b2cd1bb013212d1f6c2b897156ac87b455c2ee/Completion/Unix/Command/_adb#L463-L477) already has completion for that use case. Closing then.
