### ISSUE TITLE
simultaneous alias usage expands only the first alias

### ISSUE THREAD

**Issue by shinenelson** [robbyrussell/oh-my-zsh#5818]
I'm trying to use 2 different aliases from 2 different plugins (viz : `bundler` and `rails`). The first alias is expanded and then throws an error at the second alias instead of expanding the alias and executing it.

Here's an example : 
* `be` is the alias for `bundle exec` in the `bundler` plugin
* `rc` is the alias for `rails console` in the `rails` plugin

If I try to run `be rc`, I get the following error : 
`bundler: command not found: rc`

**Comment by msempere** [comment]
@shinenelson  do you have the same error running `be && rc` ?

**Comment by shinenelson** [comment]
@msempere It wouldn't make any sense to run `be && rc` because the command I'm trying to run is `bundle exec rails console`.

From my previous comment : 
> * `be` is the alias for `bundle exec` in the `bundler` plugin
> * `rc` is the alias for `rails console` in the `rails` plugin

But to answer your question, I tried running the command anyway (though I knew what would happen). Here's the output : 
`bundler: exec needs a command to run`

Just to clear out the confusion, `be rails console` works fine. It's just that `be rc` doesn't.

**Comment by msempere** [comment]
@shinenelson thank you for the clarification. I thought you wanted to run two different commands (I'm not a rails user) and there was a missing `&&`.

**Comment by slavaGanzin** [comment]
@shinenelson Here you can read about global aliases:
http://zsh.sourceforge.net/Intro/intro_8.html

but if you create global alias for rc, it would definitely substitute it when it would be unexpected, like:
```
vim .config.rc -> vim .config.rails console
```

So it's a bit tricky. And of course, you can use it. But you shouldn't push it publicly used software.

**Comment by shinenelson** [comment]
@slavaGanzin Thanks for your clarification, but I don't think that's really the problem. `rc` expands when used on it's own. But `bundler` fails to recognize the expansion of `rc` as `rails console`. I have a feeling that this is due to the way the `be` alias (`bundle exec`) is implemented.

I just tried `RED` (alias for `RAILS_ENV=development`) `be rails console` and it worked fine.

So, maybe either `zsh` isn't correctly expanding `rc` when used in conjunction with `be` or it's just that `bundler` is getting `rc` as input rather than the expanded `rails console` command.

**Comment by mcornella** [comment]
Aliases in the position of a parameter are not expanded, they are treated as parameters only. You would need to turn them into global aliases in order for them to be expanded anywhere in the command. See https://github.com/robbyrussell/oh-my-zsh/issues/5618#issuecomment-398903710

**Comment by mcornella** [comment]
Actually on further thought, you can chain aliases if you end the alias definition with a space. So if you have `alias be='bundle exec '` (note the trailing space), you can have `be rs` expand to `bundle exec rails server`.

That may be suitable for this use case so I'd be willing to change the current aliases to include the space. Is `be` the only useful alias to be modified or are there others?

**Comment by shinenelson** [comment]
> Is be the only useful alias to be modified or are there others?
I remember coming across something else as well, but I don't remember it now since at that point this issue was kind of lost in the heap. If I do come across it again, I'll remember to bring it to your attention here (or elsewhere, if you so wish; as a new issue perhaps?).

I didn't know about `BUNDLED_COMMANDS` before. For some reason, the documentation for that has escaped me. Can you please point me in the direction of the documentation for the variable? What other options does it take?

**Comment by mcornella** [comment]
> I didn't know about BUNDLED_COMMANDS before. For some reason, the documentation for that has escaped me. Can you please point me in the direction of the documentation for the variable? What other options does it take?

It's just an array of commands to be bundled, [here's the doco](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/bundler/README.md#add-additional-gems-to-be-wrapped).

I've pushed the alias change at 2991f23. Now you should be good to go

**Comment by RKushnir** [comment]
@mcornella For some reason it's now failing with
```
bundler: command not found: bundled_rspec
Install missing gem executables with `bundle install`
```
when I try to run `be rspec`, but works without alias(`bundle exec rspec`).

I tried removing the whitespace in the `be` alias and it started working again. Do you know why this could be happening?

**Comment by mcornella** [comment]
Because rspec is an alias to `bundled_rspec`, meaning it's already called with `bundle exec`. I guess the error is a bit confusing. I've updated the README with a list of the gems which are already wrapped: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/bundler

**Comment by RKushnir** [comment]
@mcornella Thanks! Works fine without `be`.

**Comment by mcornella** [comment]
**Update:** I had to revert this change because `be rails` failed when using the `rails` plugin (see #7065). If you still want this behavior and accept the pitfalls you can add the alias in your zshrc file.
