### ISSUE TITLE
aws plugin slow to load

### ISSUE THREAD

**Issue by elerch** [robbyrussell/oh-my-zsh#5823]
I was looking at why my terminal took so long to load and tracked down a nearly 1 second delay on my machine to the way the aws plugin loads it's completer.

I don't know that it's an appropriate fix for oh-my-zsh, but for me I overrode the plugin by adding a hard-coded path check (in the homebrew-installed location) prior to checking for homebrew. The brew list command (and brew --prefix) is pretty slow. My zsh load timing is shown here.

```
~ /usr/bin/time /usr/local/bin/zsh -i -c exit
        1.19 real         0.77 user         0.44 sys
~ /usr/bin/time /usr/local/bin/zsh -i -c exit
        0.17 real         0.08 user         0.08 sys
```

And the change to the if statement:

```
# This is the default install location for homebrew. brew and
# brew list are very slow, so we'll check the default path first
if [ -f "/usr/local/opt/awscli/libexec/bin/aws_zsh_completer.sh" ]; then
  _aws_zsh_completer_path="/usr/local/opt/awscli/libexec/bin/aws_zsh_completer.sh"
elif _homebrew-installed && _awscli-homebrew-installed ; then
  _aws_zsh_completer_path=$(brew --prefix awscli)/libexec/bin/aws_zsh_completer.sh
else
  _aws_zsh_completer_path=$(which aws_zsh_completer.sh)
fi
```

My full customized file is here: https://gist.github.com/elerch/d76c8f5935da13ec5a7889417e35b84f

**Comment by cscetbon** [comment]
mine is really faster with it. `oh-my-zsh` shouldn't depend on `brew` performances

**Comment by CraigMason** [comment]
Thanks for this @elerch . It's vastly improved the performance when I launch a new session.

**Comment by haidaraM** [comment]
If we installed awscli with pip, do we really need to check brew ?

**Comment by mcornella** [comment]
Fixed in master.
