### ISSUE TITLE
cd autocomplete doesn't work as expected

### ISSUE THREAD

**Issue by hatakekakashi2999** [robbyrussell/oh-my-zsh#5865]
Steps to reproduce:
1. Create two directories under a common directory, week 2 and Week 3
2. From within the common directory type cd (press tab to autocomplete)
3. Observe.

What happens:
zsh autocompletes the command to cd "week\ " Notice the w is lowercase

What is expected:
since there are two folders, "week 2" with a lower case w and "Week 3" with an uppercase w, autocomplete should show both alternatives instead of going for the lower case "week 2"

**Comment by kapsh** [comment]
Cannot confirm this: 
![2017-06-28_12-03-03](https://user-images.githubusercontent.com/144717/27629082-cc158faa-5bf9-11e7-8774-5d840fcf1f15.png)

Did you enable `CASE_SENSITIVE` in `.zshrc`?
