### ISSUE TITLE
npm plugin can attempt to write completion to root of filesytem

### ISSUE THREAD

**Issue by lukechilds** [robbyrussell/oh-my-zsh#5874]
Where the npm plugin [set's the path to the completion file](https://github.com/robbyrussell/oh-my-zsh/blob/b70842bae4346c793e4932d467dd566baeee7d64/plugins/npm/npm.plugin.zsh#L2) the `ZSH_CACHE_DIR` env var is used as the parent folder:

```shell
__NPM_COMPLETION_FILE="${ZSH_CACHE_DIR}/npm_completion"
```

if `ZSH_CACHE_DIR` isn't set it will fall back to using `/npm_completion` as the full path for the completion file. This will most likely throw a permission error on every new session, e.g:

```
npm.plugin.zsh:5: permission denied: /npm_completion
```

It would be better to fall back to something else (possibly `/tmp`) if `ZSH_CACHE_DIR` isn't set.

**Comment by drawcard** [comment]
Running into this issue as well

**Comment by rterbush** [comment]
I'm running into this as well. Not sure if this is due to ZSH_CACHE_DIR not getting set for some reason or if this is new change with npm plugin.

It seems this could fall back to `~/.zsh/` since that is where other plugins like `git` look for completion code.

**Comment by jonathantneal** [comment]
I get this too. Anyone know a temporary workaround? Please share.

**Comment by rterbush** [comment]
I added the following to my `.zshrc`

```
export ZSH_CACHE_DIR=$HOME/.zsh
```
