### ISSUE TITLE
Yarn plugin out of date

### ISSUE THREAD

**Issue by arb** [robbyrussell/oh-my-zsh#5878]
As yarn is changing at pretty rapid pace, the status of the autocomplete is behind. Not a huge deal, but I wanted to point start an issue. For example, it's `yarn list` but `yarn ls` is what is autocompleted.

**Comment by alaycock** [comment]
It also might be worth trying to make a zsh completion from this bash completion script. https://github.com/dsifford/yarn-completion

It pull in the script names from package.json and adds them as commands.

**Comment by calvin620707** [comment]
https://github.com/zsh-users/zsh-completions support up-to-date yarn completions. FYI.
