### ISSUE TITLE
sourcing .zprofile is too delayed

### ISSUE THREAD

**Issue by kaldown** [robbyrussell/oh-my-zsh#5879]
added this to `.zprofile`
```
if type setxkbmap >/dev/null 2>&1; then
        setxkbmap -layout us,ru -option ctrl:nocaps 2>/dev/null
fi
```
After successful authentication, there is a long delay, after my `caps` becomes `ctrl`.
What should I do to run script right after log in ?

**Comment by mcornella** [comment]
Put it in your `.profile` file.
