### ISSUE TITLE
Problems with SublimeText Plugin and tmux

### ISSUE THREAD

**Issue by greenchapter** [robbyrussell/oh-my-zsh#5885]
Hello,

I work a lot of with **SublimeText**, **oh-my-zsh** and **tmux**. I think this combination is really nice, but I discovered a little problem. I hope I can explain the problem in all details...

Lets go
I start an tmux session on my oh-my-zsh shell. So all would be fine. After that I will open the file index.js with a direct command in my shell. So I type in `st index.js`. Sublime opens but not the file. I got an empty sublime.

I think this a bug or something else. Have anydody also this problem?

**Comment by olbura** [comment]
This should fix the problem under macos https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

**Comment by greenchapter** [comment]
@olbura Hero!

**Comment by mcornella** [comment]
Is this still happening? If so, run `typeset -f -t subl` to trace the `subl` function and post what `st file` generates.

**Comment by mcornella** [comment]
Cool, thanks
