### ISSUE TITLE
Is it possible to display the command behind the alias that is being run?

### ISSUE THREAD

**Issue by sreenadhx** [robbyrussell/oh-my-zsh#5900]
An alias I am using:
alias subl="open -a 'Sublime Text'"

Is it possible that when I type "subl", the cmd shows "open -a 'Sublime Text'"? I have created too many alias and sometimes even I get confused on what exactly the alias does and I have to open ~/.zshrc to see whats happening under the hood.

**Comment by Mashi** [comment]
This is what I'm doing, maybe it is close enough?

alias | grep subl

**Comment by sreenadhx** [comment]
No, I am actually looking for something like text replacer. But I dont want to install an extra application.
Basically when I type "subl", the cmd show "open -a 'Sublime Text'" and runs it.

**Comment by Mashi** [comment]
I just now stumbled over the [globalias plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/globalias).  Press space to expand aliases.

**Comment by sreenadhx** [comment]
Thanks. This is exactly what I am looking for.

**Comment by belak** [comment]
If you've found what you're looking for, would you be willing to close the issue?
