### ISSUE TITLE
How to make  ZSH_THEME= as a function of the hostname?

### ISSUE THREAD

**Issue by korjavin** [robbyrussell/oh-my-zsh#5901]
I want to have different themes for different servers.
I want it almost in random but fixed order.

I mean I don't care what exact theme is set for exact host, but I want the same for each connect.

**Comment by pradzikowski** [comment]
Try 
`myfunc()
{
    echo "value"
}

ZSH_THEME=$(myfunc)`

OR 

`
makeName() {
    _tempval="value"
}

makeName ; name1=${_tempval}
`

**Comment by korjavin** [comment]
I probably explained bad.
I want that "value" set automatically based on hostname.

**Comment by belak** [comment]
It seems like you should be able to use the `hostname` command to determine what host you're on. So, in your .zshrc, you could have something like this:

```
case `hostname` in
host1) ZSH_THEME=pure ;;
host2) ZSH_THEME=gentoo ;;
*) ZSH_THEME=default ;;
esac
```

**Comment by korjavin** [comment]
I need a list of hostnames in that case, but it's better to have some fucntion for that.
getTheme(hostname) 

which return the random but deterministic existing theme for that particular host.

**Comment by mcornella** [comment]
You could compute a number from the hostname and use that to get the entry of an array of available themes. How you'd compute that number is up to you, but you can try different techniques and redesign them if you get the same number for different hostnames.
