### ISSUE TITLE
git-flow-avh: add bugfix (like feature) completion

### ISSUE THREAD

**Issue by AndydeCleyre** [robbyrussell/oh-my-zsh#5903]
gitflow-avh supports the notion of a `bugfix`, which works essentially like a differently named `feature`. It would be nice to have matching completion.

```
usage: git flow bugfix [list]
   or: git flow bugfix start
   or: git flow bugfix finish
   or: git flow bugfix publish
   or: git flow bugfix track
   or: git flow bugfix diff
   or: git flow bugfix rebase
   or: git flow bugfix checkout
   or: git flow bugfix pull
   or: git flow bugfix delete

    Manage your bugfix branches.
```

**Comment by jkaving** [comment]
I have just created a pull request (#6498) for this which updates the completion script to the latest official version from https://github.com/petervanderdoes/git-flow-completion

**Comment by zx1986** [comment]
git-flow-avh completion totally not work for me now :-(

zsh 5.6.2 (x86_64-apple-darwin18.0.0)
git flow version  1.11.0 (AVH Edition)
oh-my-zsh latest
macOS 10.14.2 (18C54)
