### ISSUE TITLE
Theme Documentation

### ISSUE THREAD

**Issue by jamesrobb** [robbyrussell/oh-my-zsh#5904]
Hello,

I was wondering if there was any documentation available for those looking to create their own theme. From looking at some tutorials online, I see that there are a number of different variables that can be set which allow for all sorts of customization.

Are the variables/options enumerated anywhere with a description of what they do?

**Comment by belak** [comment]
You probably want this: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html

That's a good place to start with some form of basic prompt. I'd honestly just recommend looking at the other themes as the next point for what you want to do.

**Comment by jamesrobb** [comment]
Great, Thanks!
