### ISSUE TITLE
Scripting installing on my zsh stops the script

### ISSUE THREAD

**Issue by BurningSmile** [robbyrussell/oh-my-zsh#5907]
So i'm trying to do some scripting to install oh my zsh. the problem is after the command to install it runs it enters zsh then kills the script. This results in anything after it not running. 

See [here](https://github.com/BurningSmile/LinuxScripts/blob/master/Arch/installburningpackages.sh) for the script in question.

I use this script to setup my vm's with everything I need to get work done. currently I have to manually copy over .zshrc after oh my zsh installs and I would like to be able to script this.

Output from the script install test.

Cloning Oh My Zsh...
Cloning into '/home/david/.oh-my-zsh'...
remote: Counting objects: 829, done.
remote: Compressing objects: 100% (699/699), done.
remote: Total 829 (delta 14), reused 741 (delta 9), pack-reused 0
Receiving objects: 100% (829/829), 565.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to ~/.zshrc
Time to change your default shell to zsh!
Changing shell for david.
Password: 
Shell changed.
         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
                        /____/                       ....is now installed!

Please look over the ~/.zshrc file to select plugins, themes, and options.

p.s. Follow us at https://twitter.com/ohmyzsh.

p.p.s. Get stickers and t-shirts at http://shop.planetargon.com.

➜  ~ exit
[david@vbox ~]$ 

If this is a simple bug fix then great. If its something more complicated then don't bother as it's only a mirror complaint not many users are going to have.

EDIT

Pull request ##5893 fixes the issue. Under testing it works without any issues.

**Comment by mcornella** [comment]
Closing as there are already many issues open complaining about this.

**Comment by mixn** [comment]
@mcornella That’s great — please link us to at least one with (ideally) a solution. Thank you. 😄

**Comment by mcornella** [comment]
#5002 #5853 #5893 #6547
