### ISSUE TITLE
Random theme from list

### ISSUE THREAD

**Issue by brandonsturgeon** [robbyrussell/oh-my-zsh#5918]
Hi there,

I'm suggesting that one should be able to put a comma-delimited list of theme names into the `ZSH_THEME` environment variable, and zsh will randomly select one of them on startup.

Minorly related to https://github.com/robbyrussell/oh-my-zsh/issues/3704
 
Edit: PR created. https://github.com/robbyrussell/oh-my-zsh/pull/5919
@robbyrussell this is a quick one!

**Comment by krysal** [comment]
This feature is already  available, see #4711
