### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by Vm900** [robbyrussell/oh-my-zsh#5929]
Hi folks,
Tried installing it and i keep getting this error:

zsh: can't open input file: /tools/check_for_upgrade.sh
./oh-my-zsh.sh: line 12: autoload: command not found
./oh-my-zsh.sh: line 31: syntax error near unexpected token `('
./oh-my-zsh.sh: line 31: `for config_file ($ZSH/lib/*.zsh); do'

Thanks in advance.

**Comment by belak** [comment]
Is this during the install process or after?

**Comment by Vm900** [comment]
During the installation process.Sorry for the late response.
Thanks

**Comment by belak** [comment]
What command did you use to install and do you have any of the other logs from the install? I'm guessing this is happening after the install when zsh starts up (the installer tries to start zsh when it's done), because I'm fairly certain the installer doesn't call check_for_updates.sh

**Comment by mcornella** [comment]
It looks like you installed it and the ZSH variable wasn't set correctly. Can you post your zshrc file?

**Comment by Vm900** [comment]
@mcornella Yea,you were right.Sorted now.Thanx
