### ISSUE TITLE
Can't get dir colors to work

### ISSUE THREAD

**Issue by luco** [robbyrussell/oh-my-zsh#5934]
Hey,
I'm new on zsh.
I just installed solarized theme in my iTerm. And I've set the proper fonts to work:

![image](https://cloud.githubusercontent.com/assets/246373/23565025/c5eb833a-002a-11e7-850c-23616395b98c.png)

However,  I can't apply colors to files/folder. I'm trying to set this repo: 
https://github.com/seebi/dircolors-solarized 

Any tip? Thanks.

**Comment by belak** [comment]
This seems like more of a question for the developer of the other repo... but I'll still try to see if I can help.

Can you post what you changed in your zshrc to get it to work?

**Comment by mcornella** [comment]
You would have to call dircolors before OMZ is sourced: `
```
eval `dircolors /path/to/dircolorsdb`
```
