### ISSUE TITLE
.zshrc file is missing & uninstall not working

### ISSUE THREAD

**Issue by bgb0923** [robbyrussell/oh-my-zsh#5939]
I received a successful completion message for the installation of oh my zsh and saw all the text like you were supposed to, however I don't have a .zshrc file.  People online said to just create one, so I did, but adding themes didn't do anything.  

I thought maybe I'd try to uninstall and reinstall, but the uninstall command provided in the wiki doesn't work either. 

Any help you could provide would be greatly appreciated.

**Comment by belak** [comment]
What are the contents of the .zshrc file you created?

**Comment by bgb0923** [comment]
All I did was put in 

 

ZSH_THEME="robbyrussell"

 

I was just trying to test to see if it was working or not.  I saw that it looked like the default file had more in it, however the online community seemed to think as long as you just have that in there it will change the theme.  If I’m supposed to copy and paste a block of text in please just provide the text file and I’ll do so.  I also wanted to create some aliases but those weren’t working either.
