### ISSUE TITLE
/Users/nicdford/.zshrc:source:59: no such file or directory: /Users/nicdford/.oh-my-zsh/oh-my-zsh.sh

### ISSUE THREAD

**Issue by TimHerbert** [robbyrussell/oh-my-zsh#5945]
A previous developer had oh-my-zsh installed and I found it annoying how long it took to load the script every time I loaded terminal. So I uninstalled it using your command to uninstall. However, now I am getting this error and I can't seem to figure out where the hook is causing this error every time I load terminal.

**Comment by TimHerbert** [comment]
I would think it would be loading from .bash_profile or in $PATH but don't see anything calling it in either.

**Comment by TimHerbert** [comment]
I managed to fix it somehow. I reset everything for it to factory defaults.

**Comment by paulmelnikow** [comment]
Just a suggestion that you might want to look at a couple other zsh frameworks: [Prezto](https://github.com/zsh-users/prezto), which I work on, or [Zim](https://github.com/Eriner/zim). Both pride themselves on snappy startup time.
