### ISSUE TITLE
apt autocomplete not working, displaying folders

### ISSUE THREAD

**Issue by mitap94** [robbyrussell/oh-my-zsh#5949]
Using Ubuntu 14.04 and `apt` autocomplete doesn't work.

`sudo apt upd...`
`sudo apt upg...`
`sudo apt install ter...`
None of these commands return anything when I press tab.

If I for example type:
`sudo apt install tem` and press tab it will resolve to:
`sudo apt install Templates/` if I am currently in the home folder. So it is behaving as if I am using `cd` or something like that.

The `apt-get` command works normally, and both commands work like they should in bash.

**Comment by DevJac** [comment]
This sounds like an issue I'm having. I have a git alias called `git graph` and I will type `git gra` and then hit tab (which would normally autocomplete the alias), and what happens instead is that one of my Python scripts runs. Fortunately it didn't run one of the scripts that launches nukes.

**Comment by diogo-gomes** [comment]
In Ubuntu Mate 16.04.2 are avaliable:

- edit-sources
- full-upgrade
- install
- list
- remove
- search
- show
- update
- upgrade

It's missing:
- purge

**Comment by mitap94** [comment]
I should add that everything works great on Linux Mint Cinnamon 18.1

**Comment by zephirefaith** [comment]
Same here. Ubuntu 14.04 + oh-my-zsh messes up apt autocomplete. Shows files inside the folder instead. Did not notice this happening in Ubuntu 16.04, if that helps.

**Comment by CadeBrown** [comment]
I am having this issue as well, anybody have any fixes?

**Comment by Freedzone** [comment]
Ubuntu 14.04 + oh-my-zsh + SSH - same problem. Instead of apt <command> i am getting list of folders and files

**Comment by M4lik** [comment]
apt completion does not work on Ubuntu 17.10 either.

**Comment by mcornella** [comment]
Can you verify if it works after upgrading with `upgrade_oh_my_zsh`? Perhaps you have some kind of permission problem with completion folders. If that doesn't do it, please post your `zsh --version` and what plugins you're using.

**Comment by mitap94** [comment]
Sorry, I'm not using Ubuntu 14.04 anymore on any PCs.

**Comment by Freedzone** [comment]
Not working for me, sorry. 
zsh 5.0.2 (x86_64-pc-linux-gnu)
plugins=(git zsh-completions)

**Comment by mcornella** [comment]
If this is still happening, run `echo $_comps[apt]` and `which $_comps[apt]` and post the output.

**Comment by rubenanapu** [comment]
# How I solved it

I had auto completion problems trying to autocomplete `wget` with `apt-get install wg[TAB][TAB]` and I managed to solve it by removing the `--no-generate` parameter from the flies below:

```
/usr/share/bash-completion/completions/apt-cache
/usr/share/bash-completion/completions/apt-get
```

It is worth mentioning that these files are available only after you install `bash-completion`.

The `--no-generate` parameter I'm referring to can be seen in the line below, but I removed ALL  `--no-generate`, not only from this line: 
https://github.com/scop/bash-completion/blob/master/completions/apt-get#L28

# How did I come to this point?

I got to this point after running `set -v` previous to `apt-get install wg[TAB][TAB]`, which showed that the command executed was:
```
apt-cache --no-generate pkgnames wg
```
and the output was an error:
```
E: Could not open file  - open (2: No such file or directory)
```
When I executed `apt-cache pkgnames wg` without the `--no-generate` I correctly got the list for autocompletion:
```
root@484f5c8f56ba:/# apt-cache pkgnames wg
wgalician-minimos
wget2
wgaelic
wget
wgerman-medical
wget2-dev
```
Hope this helps.
