### ISSUE TITLE
History not working as expected

### ISSUE THREAD

**Issue by pokkie** [robbyrussell/oh-my-zsh#5952]
The following options doesn't have the desired effect:

>HISTSIZE=50000
>SAVEHIST=$HISTSIZE

>wc -l ~/.zsh_history                                                                                                                                                          
>10286 /home/war/.zsh_history

In the past my history was up to 11220, yet after a reboot it is back down. 

>setopt hist_ignore_dups

>10032  l
>10034  l
>10036  l
>10038  l
>10041  l
>10044  l
>10046  l
>10048  l
>10054  l
>10056  l
>10058  l
>10060  l

I can confirm that the hist_ignore_space option does work. 

From reading the documentation: http://zsh.sourceforge.net/Doc/Release/Options.html#index-APPEND_005fHISTORY 

SHARE_HISTORY <K>

This option both imports new commands from the history file, and also causes your typed commands to be appended to the history file (the latter is like specifying INC_APPEND_HISTORY, **which should be turned off if this option is in effect**). The history lines are also output with timestamps ala EXTENDED_HISTORY (which makes it easier to find the spot where we left off reading the file after it gets re-written).

This suggests that the history configuration in oh-my-zsh doesn't take this into account.

**Comment by saveman71** [comment]
My guess is that you load oh-my-zsh after setting `HISTSIZE`, because oh-my-zsh will overwrite them in https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh
I had the same issue.

**Comment by pokkie** [comment]
Where would I check if I am loading the oh-my-zsh after setting the `HISTSIZE`?

**Comment by kreedz** [comment]
~/.zshrc:
`source $ZSH/oh-my-zsh.sh
`

**Comment by saveman71** [comment]
If you have your `HISTSIZE` defined in ~/..zshenv it will be defined before anything in the .zshrc as well

**Comment by pokkie** [comment]
my `HISTSIZE` variables are defined in `~/.oh-my-zsh/lib/history.zsh`

I haven't defined any other history settings outside of that. 

Are you saying that a potential solution is to copy the contents of that file and make sure that it executes after the `source $ZSH/oh-my-zsh.sh`?

I don't have a `~/.zshenv` file.

**Comment by mcornella** [comment]
I can't reproduce your issue.
