### ISSUE TITLE
Tab-Completion not working with normal user

### ISSUE THREAD

**Issue by Thubo** [robbyrussell/oh-my-zsh#5957]
I have two users on my MacOSX (Sierra): One with admin privileges and one without.

I used the privileged user to install brew & zsh (`su <AdminUser>`). My (oh-my-)zsh configuration was cloned directly into my home directory (I did not use the install script).

Not I'm facing the issue described in #3356 and #5651.

I've already had a look at [this comment](https://github.com/robbyrussell/oh-my-zsh/issues/5651#issuecomment-264617862), but I fear that this is at best fightings symptoms and changing permissions manually in my brew installation does not sound like a good idea.

Also [this comment](https://github.com/robbyrussell/oh-my-zsh/issues/3356#issuecomment-272265700) states that it will most likely not work in a admin/non-admin user scenario.

Is there any way to fix the issue (for now i've set `:${ZSH_DISABLE_COMPFIX:=false}` which makes tab-completion work again, but gives ugly error messages and does not seem to be the right approach)?

For reference:

```
# brew --version
Homebrew 1.1.11
Homebrew/homebrew-core (git revision b191; last commit 2017-03-12)
# zsh --version
zsh 5.3.1 (x86_64-apple-darwin16.3.0)
```

**Comment by Andersmholmgren** [comment]
+1. I have same issue

**Comment by Shea690901** [comment]
@Thubo:
What do you mean by (which commands did you use as which user?):
> My (oh-my-)zsh configuration was cloned directly into my home directory

**Comment by Thubo** [comment]
@Shea690901 

Here is more or less what I do (I use myrepos and vcsh to manage my dotconfigs):

```
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
```

(In other words: I do not check out any special tag/branch/revision, but I use master from this repository. I added this information, because I'm not sure if the install script does anything different.)

**Comment by Shea690901** [comment]
Beside settingup a .zshrc (and changing the login shell to zsh)?
not that I´ve seen anything....
you did change your .zshrc according the template from oh-my-zsh?

**Comment by Thubo** [comment]
@Shea690901 my zsh config is available here: https://github.com/Thubo/dotconfig-zsh

**Comment by Shea690901** [comment]
My mistake, one should realy read **all** of a complain before one tries to help....

You wrote something about error messages, something along the lines of
```
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.
```

**Comment by mcornella** [comment]
If you're seeing this, I've just updated OMZ to ignore permission issues with your completion scripts and load them anyway, but you have to set this in your zshrc file:
```zsh
# this goes before oh-my-zsh.sh is sourced
ZSH_DISABLE_COMPFIX=true
```

**Comment by jbowns10** [comment]
for mac users:

nano ~/.zshrc
one line up from where you define you source path ```export ZSH="path/to/.oh-my-zsh"
enter ```ZSH_DISABLE_COMPFIX=true```

save and exit, fixed it for me
