### ISSUE TITLE
robbyrussell: command prompt missing last character 

### ISSUE THREAD

**Issue by andrewcaulfield** [robbyrussell/oh-my-zsh#5958]
I'm having an issue whereby the command prompt is missing the last character.

![screen shot 2017-03-13 at 10 41 43](https://cloud.githubusercontent.com/assets/3205699/23851143/44540cf4-07da-11e7-8cd5-a99c9a5a9113.png)

Running the robbyrussell theme.

**Comment by mcornella** [comment]
Reopen if this still happens.
