### ISSUE TITLE
trapd00r theme has dependency

### ISSUE THREAD

**Issue by sparr** [robbyrussell/oh-my-zsh#5966]
https://github.com/robbyrussell/oh-my-zsh/blob/9dab3c6718d627bc3ea5beb79bfbf0a7f74a7648/themes/trapd00r.zsh-theme#L3-L5

This theme should not be included in the random theme selection until that functionality is included rather than depending on an external script that may not be installed.

**Comment by mcornella** [comment]
Fixed in #7079.
