### ISSUE TITLE
previous shell text still showing when view files with vim

### ISSUE THREAD

**Issue by MartinP7r** [robbyrussell/oh-my-zsh#5974]
somehow the view inside hyper doesn't get reset when opening files in vim (or nano),
the characters just get replaced where there is no whitespace on the textfile and stay as they are where there is whitespace.

![image](https://cloud.githubusercontent.com/assets/2669027/24067599/3c12bd7e-0bc2-11e7-9b74-dd0659e9784f.png)

**Comment by mcornella** [comment]
This is probably an issue with Hyper, and old enough to be probably solved. Reopen if this still happens and without OMZ it doesn't.
