### ISSUE TITLE
Autocomplete throwing errors with dnf

### ISSUE THREAD

**Issue by tusing** [robbyrussell/oh-my-zsh#5975]
So I'm having issues with autocomplete. Here's an example, where I type in ```dnf install anc[TAB HERE]```:

```
➜  ~ dnf install ancTraceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dnf'
horman-0.0.1-9.fc24.x86_64 
```

where the expected package is ```anchorman-0.0.1-9.fc24.x86_64```.

It throws the error right after the tab, but completes just fine after the error is thrown.

This error only seems to happen after I've put a space after the ```dnf```: for example, 

* typing ```dn[TAB]``` will show a working completion list:

```
➜  ~ dn
dnf                  dnssec-coverage      dnssec-revoke      
dnf-3                dnssec-dsfromkey     dnssec-settime     
dnsdomainname        dnssec-importkey     dnssec-signzone    
dnsmasq              dnssec-keyfromlabel  dnssec-verify      
dnssec-checkds       dnssec-keygen  
```

* typing ```dnf [TAB]``` will throw the ```ModuleNotFoundError```:

```
➜  ~ dnf Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dnf'
     dnf
autoremove           -- automatically remove no longer required packages
check-update         -- check for available package upgrades
[...etc...]
```
Strangely enough, commands like ```cd``` or ```git``` or ```gcc``` autocomplete just fine. I've only seen this happen with ```dnf```.

**Edit:** Finally, I should note that this doesn't happen when running as root/admin, and autocomplete works as expected.

**Comment by galenlynch** [comment]
I have the same problem with prezto.

**Comment by matuskropuch** [comment]
I didn't build any custom python nor do I have a custom python in path but I have the same problem. Is there some kind of general solution to this problem?

**Comment by amodig** [comment]
I have the same problem and I have Anaconda Python on my path.

**Comment by vladoxNCL** [comment]
Found the solution to the problem at Anaconda's Github:

To fix in the system installed zsh change the instances of python2 and python3 in /usr/share/zsh/5.3.1/functions/_dnf to /usr/bin/python2 and /usr/bin/python3 respectively.

Hope this helps!

**Comment by mcornella** [comment]
You can also try updating to zsh 5.5 or later since it is updated on those versions: https://github.com/zsh-users/zsh/commit/d8e3218938381901e5adbc48059fb54a7f12a23b.

**Comment by didli** [comment]
Sorry to dig this issue, but I have these errors on Rocky 8.5, with python 3.9.6 and ohmyzsh 5.5.1. I'm not sure if I can do anything to functions/_dnf since it's supposed to use python3 if dnf is dnf-3. So it's supposed to work but ... it's not. 
Any help please ^^' ?

**Comment by mcornella** [comment]
> Sorry to dig this issue, but I have these errors on Rocky 8.5, with python 3.9.6 and ohmyzsh 5.5.1. I'm not sure if I can do anything to functions/_dnf since it's supposed to use python3 if dnf is dnf-3. So it's supposed to work but ... it's not. Any help please ^^' ?

What do you head with `head -1 $(readlink -f /usr/bin/dnf)`?

**Comment by mcornella** [comment]
> Sorry to dig this issue, but I have these errors on Rocky 8.5, with python 3.9.6 and ohmyzsh 5.5.1. I'm not sure if I can do anything to functions/_dnf since it's supposed to use python3 if dnf is dnf-3. So it's supposed to work but ... it's not. Any help please ^^' ?

What do you get with `readlink /usr/bin/dnf`?

**Comment by didli** [comment]
Hi mcornella, thank you for your help
I read : dnf-3

**Comment by didli** [comment]
Oups. A weird thing just happened : I've checked again if I could get the error mentioned previously and right now ... the problem is ... gone. Voilà. I have no idea what changes I made (if any) that solves this. Awfully sorry for the noise.

**Comment by alexyin1** [comment]
`sudo dnf install python3`
fixed this for me on rhel 8, not sure why.
