### ISSUE TITLE
How to display only the folder name instead of the whole path in terminal?

### ISSUE THREAD

**Issue by bythckr** [robbyrussell/oh-my-zsh#5976]
I don't want to see the whole path of where I am, instead, I only want to see the folder that I am in currently.

The solution that I got was to modify the code from:
[`prompt_segment blue black '%~'`](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme#L190)
to:
`prompt_segment blue black '%1~'`.

Now with each update, I have stash the change.

Is there a better way of doing it by adding a setting to the zshrc file?

**Comment by Michael-Thibault** [comment]
See [Overriding and adding themes.](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes)

**Comment by bythckr** [comment]
I did see that method. But I did not like that method as I was trying for a portable set up.

In terms of portability, isn't it better if I can customize this via .zshrc? So, when I am in a new machine, all I have to do is update the .zshrc & I am good to go.

**Comment by Michael-Thibault** [comment]
If it's portability you're after, you could consider just tweaking the .zshrc file to set $ZSH and/or $ZSH_CUSTOM to point to a copy of omz on whatever storage you're carrying around. Unless I'm misunderstanding your use-case. (Forgive me, it's late; I haven't played with porting omz around much.)

**Comment by mcornella** [comment]
You can redefine the `prompt_dir` function in your zshrc, after OMZ has loaded:
```
prompt_dir() {
  prompt_segment blue $CURRENT_FG '%1~'
}
```
