### ISSUE TITLE
enable restarting the script

### ISSUE THREAD

**Issue by 927589452** [robbyrussell/oh-my-zsh#5978]
I would suggest (and maybe if it is liked code) having the install script try chsh again after a failed installation,
or retry chsh 3 times like sudo does,
to prevent a password typo from having to remove the folder and start over

**Comment by mcornella** [comment]
If `chsh` fails you don't have to restart the installation, just run `chsh` afterwards. The OMZ installation will be alright nonetheless. In fact, that's what the installer tells you: https://github.com/robbyrussell/oh-my-zsh/blob/09fbc163663cd814488cb4be474f034525a8cca0/tools/install.sh#L90-L91
