### ISSUE TITLE
why not showing python virtualenv ?

### ISSUE THREAD

**Issue by toplinuxsir** [robbyrussell/oh-my-zsh#5984]
why not showing python virtualenv ?

**Comment by osvalr** [comment]
I think  it's happening the same for me.

```bash
[21:56:50] ~/build/project master✘➦
 $ source ~/build/my_virtualenv/python3.4/bin/activate
(python3.4) cc3443025087%
```

it loses the theme and some behavior, @toplinuxsir is the same that you meant?

**Comment by osvalr** [comment]
@toplinuxsir try enabling `virtualenv` plugin, it worked for me.
```bash
# plugins list, originally having only git enabled
plugins=(
  git
  virtualenv
)
```

**Comment by gakkit** [comment]
I tried add virtualenv in the plugins. It's still not working. This is driving me nuts. I don't wanna ditch zsh for this, I guess I‘ll have to.

**Comment by 26huitailang** [comment]
add `virtualenv` plugin worked for me.
```
 ~ workon django
 (django) ~ 
```

**Comment by jatinw21** [comment]
It stopped showing me env after an update but adding virtualenv plugin in .zshrc file worked like a charm

**Comment by fabge** [comment]
This issue still persists, did anyone figure it out?

**Comment by mcornella** [comment]
This depends on the theme you're using.
