### ISSUE TITLE
Plz,Here is something wrong with uninstall zsh

### ISSUE THREAD

**Issue by leov1** [robbyrussell/oh-my-zsh#5987]
when i uninstalled the zsh and reset the terminal to bash ,but when i start use "sudo su" command returned "su: /usr/local/bin/zsh: No such file or directory".

**Comment by trauta** [comment]
What is the standard login shell for your account/root? Make sure to replace ../zsh with .../bash in /etc/passwd.

**Comment by leov1** [comment]
@trauta  i'm using the /bin/bash currently,there is no any zsh config  in /etc/passwd,my System is Mac OS-X-EI-Capitan
