### ISSUE TITLE
Graphics with Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by Ugarz** [robbyrussell/oh-my-zsh#5989]
Hi there !

I found an akward situation.
I've done a fresh reboot of my windows recently and decided to give a shot at [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) and of course oh-my-zsh is the first thing I've installed with :
```
apt-get update && apt-get install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```
I've seen an error with the so called `rzsh`, looked like he were missing in a `shared` folder but I decided to ignore it. Once this installed I started a new terminal but readability and icones weres missing.
Any Idea ?

![oospy](https://cloud.githubusercontent.com/assets/6050079/24284332/1d0ff27c-106b-11e7-934f-f65e3bdb5a7f.JPG)

**Comment by exwizzard** [comment]
You need to install a compatible font, the default windows fonts don't have the characters needed.

**Comment by Ugarz** [comment]
For those who want a compatible font check this repo : https://github.com/powerline/fonts I finally manage to do what I wanted.
Cheers !
