### ISSUE TITLE
External themes wiki page is gone

### ISSUE THREAD

**Issue by denysdovhan** [robbyrussell/oh-my-zsh#5993]
Recently, I've tried to update the description of my spaceship-zsh-theme on External themes wiki page, but this page is gone:

![image](https://cloud.githubusercontent.com/assets/3459374/24320667/71b0cf86-1142-11e7-9c8a-208152dcfcc8.png)

Can anyone check this? Maybe it was accidental deleted and might be restored?

**Comment by mcornella** [comment]
Fixed.

**Comment by denysdovhan** [comment]
Thanks!
