### ISSUE TITLE
Can't use .. to go up a directory as any other user than the root, permission denied

### ISSUE THREAD

**Issue by akashaggarwal7** [robbyrussell/oh-my-zsh#5997]
Title explains it all.

**Comment by xiaobai** [comment]
I'm unable to reproduce this. More information would be helpful: things like your .zshrc, any changes you might have made to any oh-my-zsh files, etc.

**Comment by akashaggarwal7** [comment]
@xiaobai Thanks for replying, here's my .zshrc file in non-root user. i don't think I changed anything in my oh-my-zsh files:

`# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'`

**Comment by mcornella** [comment]
Your zshrc file should load Oh My Zsh, [have a look at our zshrc template](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template).

**Comment by akashaggarwal7** [comment]
I actually tried to link my non-root account to zsh's installation on the root account following the steps mentioned [here](http://askubuntu.com/questions/521469/oh-my-zsh-for-the-root-and-for-all-user), didn't work as expected. Is it even possible to do this?

**Comment by LillyRigoli** [comment]
I'm currently experiencing this issue, where '..' isnt allowing me to go up a directory. Did you ever figure out what was causing your issue?

**Comment by mcornella** [comment]
You need `setopt autocd`, which is automatically enabled when using OMZ.
