### ISSUE TITLE
colored-man-pages: parse error when an alias exists called man

### ISSUE THREAD

**Issue by tremby** [robbyrussell/oh-my-zsh#6001]
When using the following I'm getting the following on shell startup:

```
~/.oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh:19: parse error near `()'
```

The line in question is `man() {`.

If I change this line to `function man() {` then it works.

From what I'm reading, it's preferred to *not* have the `function` keyword.

I narrowed down my zshrc until I found the offending line, and the issue is that I have an alias called `man`. In particular, `alias man='LC_ALL=C LANG=C man'`.

Is there a way for the plugin to coexist with such an alias?

**Comment by mcornella** [comment]
Fixed in master.
