### ISSUE TITLE
I'm looking build artifact that (cheaply) signals if oh-my-zsh is installed

### ISSUE THREAD

**Issue by AndrewSB** [robbyrussell/oh-my-zsh#6002]
Hey! Thank you so much for all of your work 👍 

I'm working on a script in my dotfiles, and I want to switch on whether or not the terminal I'm in has oh-my-zsh installed already. Usually I solve this by sending a command into `/dev/null` to test if the command line tool is installed.
I was having trouble coming up with a cheap (i.e. doesn't hit the network) test to see if oh-my-zsh is installed. `upgrade_oh_my_zsh` was what I came up with, but its too expensive for my taste. Any ideas?

Thank you 😄

**Comment by Tspoon** [comment]
Uninstalling oh-my-zsh just deletes the `~/.oh-my-zsh` directory.
I would have thought that checking for that directory would work:
```
if [ -d ~/.oh-my-zsh ]; then
    echo "oh-my-zsh installed"
fi
```

Or check for existence of the uninstall script (or indeed any of the other oh-my-zsh scripts) itself:
```
if [ -f $ZSH/tools/uninstall.h ]; then
    echo "oh-my-zsh installed"
fi
```

**Comment by AndrewSB** [comment]
Awesome! I ended up using the first one @Tspoon. Thanks 😄
