### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Polhp** [robbyrussell/oh-my-zsh#6003]
Hello everyone,
I get an error when I execute a command in my zsh shell, returns that:
```
zsh: no such file or directory: /home/paul/.rvm/bin/rvm-prompt                  
```

![Shell Screenshot](https://cloud.githubusercontent.com/assets/19956842/24518219/84b29f40-1581-11e7-9505-0801e5afc931.png)

This only appears when I use the 3den theme.

**Comment by robbyrussell** [comment]
@Polhp You may need to edit ~/.zshrc and remove that from your PROMPT config

**Comment by Polhp** [comment]
I don't declared this path in the ``.zshrc`` file.

**Comment by Polhp** [comment]
Closed, only I needed to install RVM.
