### ISSUE TITLE
strange ? mark

### ISSUE THREAD

**Issue by ja-heller** [robbyrussell/oh-my-zsh#6005]
Is this strange ? mark symbol normal or is there any way how to change this?
Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1441704/24520892/58002f7c-158a-11e7-98f3-b22aae863970.png)

**Comment by trauta** [comment]
Which theme are use using?  
This error may appears due to an incompatible font, since some themes require patched fonts like the Powerline theme.

Check what theme you are using and if there are any special fonts required to use it properly​.

**Comment by ja-heller** [comment]
Hi trauta,

I'm using agnoster as theme.

**Comment by trauta** [comment]
@ja-heller As I previously mentioned, you need patched fonts to use this theme. 

Clone this [repo](https://github.com/powerline/fonts) and run the install script. After changing your terminal font to one of the new patched ones, the theme should look as intended.

**Comment by ja-heller** [comment]
@trauta 

Thanks, any idea where to get the font "Menlo" working? Seems like just these icons are needed, because the font itself is working fine in iterm2.

**Comment by ja-heller** [comment]
Solved 👍 

Menlo can be found here:
https://github.com/abertsch/Menlo-for-Powerline

**Comment by naaano** [comment]
i ran https://github.com/powerline/fonts install.sh script and also installed Menlo-for-Powerline above, but the symbols are still there. I tried all powerline fonts in iterm2 profile config. I see the font aspect changes between fonts, but that [?] is still there. 

Any other ideas?
