### ISSUE TITLE
Which plugin does completion of last similar command

### ISSUE THREAD

**Issue by srccon** [robbyrussell/oh-my-zsh#6008]
I had a plugin enabled that I loved, then I lost the config file, and now I'm trying to find it again. It would auto-fill the last similar command from shell when up was pressed. 

Say my zsh history from newest to oldest was: 

```bash
cd $HOME
ssh host@example.com
rsync -avz files/ otherfiles/
ssh host@secondexample.com
```

If I just executed the `cd $HOME` command and had a blank prompt, if I typed `ssh` then `up-key`, it would, instead of filling with `cd $HOME`, would jump to `ssh host@example.com`. Pressing `up-key` again would fill with `ssh host@secondexample.com`. 

Which plugin does this? I loved it and can't find it.

Sorry this is not an issue but a support need.

**Comment by arizzubair** [comment]
https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/history-substring-search
This is the plugin. You can enable it by adding   history-substring-search in the plugin section of your .zshrc .
