### ISSUE TITLE
When use shell  have preblem

### ISSUE THREAD

**Issue by bzd111** [robbyrussell/oh-my-zsh#6010]
echo $SHELL
/usr/bin/zsh
zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)
os is Centos7.0 3.10.0-514.10.2.el7.x86_64

error info
/root/.autojump/share/autojump/autojump.zsh:22: command not found: uname
/usr/libexec/grepconf.sh: line 5: grep: command not found
/root/.autojump/share/autojump/autojump.zsh:22: command not found: uname
/root/.zshrc:57: compinit: function definition file not found
/root/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
env_default:1: command not found: env
env_default:1: command not found: grep
env_default:1: command not found: env
env_default:1: command not found: grep
/root/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/root/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:80: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:93: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:100: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:109: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:119: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:129: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:163: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:166: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:168: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:182: command not found: compdef
/root/.oh-my-zsh/plugins/git/git.plugin.zsh:193: command not found: compdef
/root/.autojump/share/autojump/autojump.zsh:22: command not found: uname

**help **

**Comment by bzd111** [comment]
Now, any command are not find in zsh 

root@root:~ # ls                                                                                                                                                                        zsh: command not found: ls
root@root:~ # cat /root/.oh-my-zsh/plugins/git/git.plugin.zsh                                                                                                                           
zsh: command not found: cat
root@root:~ # cat /etc/shell                                                                                                                                                            
zsh: command not found: cat
root@root:~ # chsh -s /usr/bin/shell                                                                                                                                                    zsh: command not found: chsh

**Comment by eremit** [comment]
@bzd111 do you have an other user than root configured? does that user also suffer from this issue?

**Comment by cyberplant** [comment]
Check that your PATH contains at least /bin and /usr/bin

you can do this:
```
export PATH=$PATH:/bin:/usr/bin
```
and try again.

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/issues/4607

**Comment by hipolitotata** [comment]
> Check that your PATH contains at least /bin and /usr/bin
> 
> you can do this:
> 
> ```
> export PATH=$PATH:/bin:/usr/bin
> ```
> 
> and try again.

its works for me, thannks
