### ISSUE TITLE
pyenv plugin is slow on startup

### ISSUE THREAD

**Issue by JensRantil** [robbyrussell/oh-my-zsh#6017]
I had issues with slow start of zsh. I looked into #5327. Specifically I found https://github.com/robbyrussell/oh-my-zsh/issues/5327#issuecomment-241226195 and tried `zsh -xv` and discovered that

    +_pyenv-from-homebrew-installed:1> brew --prefix pyenv

was very slow. Disabling `pyenv` plugin made starting my terminal much faster.

Expected: That `pyenv` is faster to start.

**Comment by xbeta** [comment]
👍 

this is a terrible performance

```
/usr/bin/time brew --prefix pyenv
/usr/local/Cellar/pyenv/1.0.10
        0.61 real         0.38 user         0.15 sys
```

**Comment by mcornella** [comment]
The new version doesn't call brew anymore. Hope you like it! :sparkles:
