### ISSUE TITLE
Composer plugin causes output on load

### ISSUE THREAD

**Issue by SunMar** [robbyrussell/oh-my-zsh#6022]
Hi,

The composer plugin causes output "Changed current directory to [...]". This seems to be introduced by #5886. I think the "2> /dev/null" is misplaced.

`export PATH=$PATH:$(composer global config bin-dir --absolute) 2>/dev/null`

should be

`export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)`

https://github.com/robbyrussell/oh-my-zsh/blob/4fba92e/plugins/composer/composer.plugin.zsh#L55

Putting the 2> /dev/null inside the $() call to composer removes the output and still adds the composer bin-dir to the path.

**Comment by HJGreen** [comment]
Duplicate of #5953.

There is a PR (#5935) open which I hope will be merged soon.

**Comment by SunMar** [comment]
Closing this issue since the PR was merged a while ago.
