### ISSUE TITLE
Some Commands Not Working

### ISSUE THREAD

**Issue by vishKurama** [robbyrussell/oh-my-zsh#6026]
I tried to remove a package known as tilix, it had two things
1. tilix
2. tilix-common, by running
 `sudo apt remove tilix*`
it didn't run as it would have in bash shell.
It shows: **zsh: no matches found: tilix***
however, `sudo apt remove tilix` ran but it removed only tilix not tilix-common

**Comment by sharan-cs2000** [comment]
its working with tilix*, did u attempted again ?

**Comment by mcornella** [comment]
You have to quote the argument, otherwise zsh thinks you want to use files beginning with `tilix`. If you use quotes the asterisk won't be expanded. It's called globbing, if you want to look it up further. 
TLDR: use `sudo apt remove "tilix*"`
