### ISSUE TITLE
Git prompt is very slow for remote FS.

### ISSUE THREAD

**Issue by benbor** [robbyrussell/oh-my-zsh#6029]
`zsh -xv` show 2 slow query:
```
git status --porcelain '--ignore-submodules=dirty' '--untracked-files=no'
git diff --no-ext-diff --ignore-submodules --quiet --exit-code
```

Does it possible make they faster or turn off totally?

**Comment by johnzeng** [comment]
Refer to #3725 this is an issue of git status. The problem is, is it possible to turn it off ?? I don't really need this feature.

**Comment by mcornella** [comment]
You can set the git-config value `oh-my-zsh.hide-status` to `1` to disable the git prompt on certain repositories.
