### ISSUE TITLE
Is any possibilities to marked and get actions from filepath in omz stdout?

### ISSUE THREAD

**Issue by nickmetal** [robbyrussell/oh-my-zsh#6042]
On Mac zsh I can click on the file path in the terminal (when i retrieved some prints in stdout ) and file will be opened on the linked application.For example clicking on the web-link (ctrl+mouse left button) is working fine. How can I get the same behavior with file path on Linux? Maybe some plugins I should to use?

Linux Mint 18.1
zsh --version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by mcornella** [comment]
This is a feature of your terminal emulator. I'm not aware of any that does this (links are highlighted in most programs though).
