### ISSUE TITLE
oh-my-zsh for bash on windows

### ISSUE THREAD

**Issue by batousik** [robbyrussell/oh-my-zsh#6044]
Could you test out such configuration?

**Comment by wumo** [comment]
With the help of ConEmu, oh-my-zsh works great in bash on windows.

**Comment by barbalex** [comment]
what is ConEmu?

**Comment by barbalex** [comment]
Probably this: https://conemu.github.io

**Comment by barbalex** [comment]
And how would ConEmu help?

**Comment by 7dir** [comment]
1) install cmder
2) install MSYS2
3) pacman -S zsh
4) install oh-my-zsh
