### ISSUE TITLE
What's the best way to backup zsh config? 

### ISSUE THREAD

**Issue by mrdulin** [robbyrussell/oh-my-zsh#6045]
system: OSX 

what zsh config files should be backup?
And, is there a best and simple way to backup zsh config?

I really need this, thanks.

**Comment by meain** [comment]
You have to back it up only if there is something that you have to back up, ie if you have customized it previously which from the question you ask I understand that you haven't. So don't worry about it.

Also when we say `backup` we just me keep a copy of the file somewhere else and nothing fancy. Just `backup` your file at `~/.zshrc`

**Comment by mrdulin** [comment]
@meain thanks. I set some http/https and socks5 proxy config, so I want to backup it.
