### ISSUE TITLE
multiple lines issue in OSX

### ISSUE THREAD

**Issue by juancrescente** [robbyrussell/oh-my-zsh#6047]
When having a long command in a ssh session (more than one line in the terminal) and start to write or delete part of the command, the cursor gets crazy and jumps to different locations, so I'm not able to see where am I modifying the script. This happens in default terminal, iTerm as well. 

<img width="581" alt="screen shot 2017-04-25 at 11 39 41 am" src="https://cloud.githubusercontent.com/assets/2141907/25391151/f49db360-29ab-11e7-9aea-ecfedd7396d4.png">

**Comment by kyreeves** [comment]
+1

**Comment by kyreeves** [comment]
I'm having the same issue using macOS Sierra. Can anyone help?

**Comment by guy-kdm** [comment]
Hi, this issue makes OH-my-zsh unusable. Will provide any information requested. Happens mostly with line-wrapping, word operations (move-delete) and tab-completion.

**Comment by juanmas07** [comment]
Also mess up while copy and pasting long lines. We need some workaround for this

**Comment by juanmas07** [comment]
Any updates on this?

**Comment by guy-kdm** [comment]
@juanmas07 this ended up being a problem with my prompt config (specifically with coloring). try to use the vanilla prompt, removing any of your customization

**Comment by Roscoe69** [comment]
Not interested
