### ISSUE TITLE
How to fix error them agnoster on ubuntu ? 

### ISSUE THREAD

**Issue by nhlinhCS** [robbyrussell/oh-my-zsh#6053]
I have this problem, could some one help me fix it, please !

![screenshot from 2017-04-27 10 25 54](https://cloud.githubusercontent.com/assets/12539363/25466619/fd679982-2b33-11e7-80e5-e73c0f730f4b.png)

i would like oh-my-zsh show like this: 
![screenshot from 2017-04-27 10 27 36](https://cloud.githubusercontent.com/assets/12539363/25466664/293cd220-2b34-11e7-8369-5432cb080f31.png)

**Comment by Joezc** [comment]
Hi, may I ask how did you fix it? Now I have the same question.

**Comment by phun-ky** [comment]
You have to install a power line font, I recommend the Menlo variant :)

**Comment by Joezc** [comment]
I encountered this problem and `sudo apt-get install fonts-powerline` solved the problem.
