### ISSUE TITLE
speed up loading 

### ISSUE THREAD

**Issue by gasparch** [robbyrussell/oh-my-zsh#6056]
is is feasible to make user-configurable [confinit](https://github.com/robbyrussell/oh-my-zsh/blob/master/oh-my-zsh.sh#L77) invocation?

If I use later in `.zshrc` additional settings for completion and re-run `compinit` again - it would be nice to avoid extra costs of security check on that line (by using `compinit -C`). Otherwise compinit is called several times during zsh startup and that makes startup slower. 

Stripping confiration down to 2 invocations of compinit allowed me to have shell start in 100ms, which is totally acceptable. 250ms feels already as a lag while opening terminal.

**Comment by mcornella** [comment]
The current setup runs `compinit` with `-C`.
