### ISSUE TITLE
'gmt' comflict

### ISSUE THREAD

**Issue by elmerehbi** [robbyrussell/oh-my-zsh#6062]
Hello,

I am running into problems using GMT ([Generic Mapping Tools](gmt.soest.hawaii.edu)) because `gmt` is being used as an alias for [git mergetools](https://github.com/robbyrussell/oh-my-zsh/issues/2513).

How can I disable the alias for git merge tools so I can access GMT?

**Comment by nuimk** [comment]
If you want to disable alias, then `unalias gmt`. Otherwise, You could also call `\gmt` to call actual program not an alias.

**Comment by elmerehbi** [comment]
@nuimk Thanks. I've added that to my configuration. Before your reply I had aliased gmt. This simplifies a script I've written.
