### ISSUE TITLE
how can i update zsh?

### ISSUE THREAD

**Issue by Mikey2008** [robbyrussell/oh-my-zsh#6065]
sometime when i open the Terminal on my Mac, it show me like this:

[Oh My Zsh] Would you like to check for updates? [Y/n]: 

and i type"y"

```
Updating Oh My Zsh
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
```

There was an error updating. Try again later?

**Comment by Shea690901** [comment]
The error message says all:
- you´ve made chamges within the repository without commiting them
- you need to either commit your changes or stashing them

**Comment by Mikey2008** [comment]
thanks man
i will try it again later
