### ISSUE TITLE
dotenv plugin does not properly escape values

### ISSUE THREAD

**Issue by hackel** [robbyrussell/oh-my-zsh#6075]
Using the dotenv plugin, when a backtick (`) is used in the key value, it does not get escaped, and it actually tries to run the contents as a shell command.  Pretty huge security vulnerability here.
e.g. .env file:
```
KEY=asdf`ls /`fdsa
```
echo $KEY
```
asdfbackup/
bin/
boot/
...etc.
vmlinuz.old@fdsa
```

The plugin is just sourcing the file, but .env files are not shell scripts!

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dotenv/README.md#disclaimer. The user is responsible for what content is in `.env` files.
