### ISSUE TITLE
I got this for every command I typed when I enabled theme.  Is this a bug ? 

### ISSUE THREAD

**Issue by lamproae** [robbyrussell/oh-my-zsh#6081]
┌[leeweop☮localhost.localdomain]-(~)
└> zsh --version
**zsh**zsh 5.3.1-dev-0 (x86_64-unknown-linux-gnu)
┌[leeweop☮localhost.localdomain]-(~)
└> uname -a
**uname**Linux localhost.localdomain 4.10.10-200.fc25.x86_64 #1 SMP Thu Apr 13 01:11:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
┌[leeweop☮localhost.localdomain]-(~)
└> ps
**ps**   PID TTY          TIME CMD
 79584 pts/1    00:00:00 bash
 86705 pts/1    00:00:00 zsh
 87085 pts/1    00:00:00 ps
┌[leeweop☮localhost.localdomain]-(~)
└> pwd
**pwd**/home/leeweop
┌[leeweop☮localhost.localdomain]-(~)
└> 
┌[leeweop☮localhost.localdomain]-(~)
└>

**Comment by lamproae** [comment]
every command echoed back.

**Comment by lamproae** [comment]
I use ssh to connect to the server. After I installed oh-my-zsh, every command I executed will be echoed back. 
When I remove the preexec and precmd in lib/termsupport.zsh， this problem is fixed.

**Comment by whuailin** [comment]
I have the save problem, thanks, fixed too
