### ISSUE TITLE
No file or directory found in .oh-my-zsh/themes/

### ISSUE THREAD

**Issue by xlsmile** [robbyrussell/oh-my-zsh#6090]
I've just installed V5.2 on MacOS (10.12.4), but not able to activate any of the "oh-my-zsh themes", because of this error popping in iTerm window:

/Users/Username/.oh-my-zsh/oh-my-zsh.sh:source:110: no such file or directory: /Users/Username/.oh-my-zsh/themes/“agnoster”.zsh-theme

The "oh-my-zsh.sh" "Load the Theme" configuration seems to be ok:

> if [ "$ZSH_THEME" = "random" ]; then
  themes=($ZSH/themes/*zsh-theme)
  N=${#themes[@]}
  ((N=(RANDOM%N)+1))
  RANDOM_THEME=${themes[$N]}
  source "$RANDOM_THEME"
  echo "[oh-my-zsh] Random theme '$RANDOM_THEME' loaded..."
else
  if [ ! "$ZSH_THEME" = ""  ]; then
    if [ -f "$ZSH_CUSTOM/$ZSH_THEME.zsh-theme" ]; then
      source "$ZSH_CUSTOM/$ZSH_THEME.zsh-theme"
    elif [ -f "$ZSH_CUSTOM/themes/$ZSH_THEME.zsh-theme" ]; then
      source "$ZSH_CUSTOM/themes/$ZSH_THEME.zsh-theme"
    else
      source "$ZSH/themes/$ZSH_THEME.zsh-theme"
    fi
  fi
fi

Where is the problem then?

Cheers!

**Comment by xshotD** [comment]
Can you check the directory and see if the file exists?

**Comment by xlsmile** [comment]
Yes, "agnoster.zsh-theme", as well as other themes, exists under ".oh-my-zsh" folder. Thanks!

**Comment by xshotD** [comment]
Did you put extra quotes in `ZSH_THEME` in .zshrc?

**Comment by xlsmile** [comment]
Nope, definitely not. However, after I removed them from  .zshrc (ZSH_THEME=agnoster), all seems to be working fine. Thanks for your help!

**Comment by xshotD** [comment]
No problem!

**Comment by mohdazharkhan** [comment]
Just put ZSH_THEME="random" and reload your .zshrc profile.

**Comment by evantaurusta** [comment]
just remove the quotation marks from the (ZSH_THEME=) line

**Comment by mcornella** [comment]
Thanks @tilda!
