### ISSUE TITLE
use fishy theme can not hide default_user

### ISSUE THREAD

**Issue by bravist** [robbyrussell/oh-my-zsh#6091]
I use the fishy theme for my omz

~/.zshrc

```bash
ZSH_THEME = "fishy"
```

i use all like this 

```bash

DEFAULT_USER=`whoami`

```

```bash

export DEFAULT_USER=`whoami`

```

```bash

USER=``

```

but don't sovle my problem.

**Comment by mcornella** [comment]
The fishy theme doesn't have that capability. You're trying to use a configuration for the agnoster theme.
