### ISSUE TITLE
Errors while executing zshrc

### ISSUE THREAD

**Issue by viveksachdeva** [robbyrussell/oh-my-zsh#6092]
Installed it... Made a change to zshrc.. on executing, getting 
/Users/xx/.oh-my-zsh/oh-my-zsh.sh: line 12: autoload: command not found
/Users/xx/.oh-my-zsh/oh-my-zsh.sh: line 31: syntax error near unexpected token `('

/Users/xx/.oh-my-zsh/oh-my-zsh.sh: line 31: `for config_file ($ZSH/lib/*.zsh); do'

Note:
echo $SHELL
/bin/zsh

Do I need to configure something>

**Comment by xshotD** [comment]
Provide your config? Otherwise we can't track down the problem.

**Comment by viveksachdeva** [comment]
# Check for updates on initial load...
if [ "$DISABLE_AUTO_UPDATE" != "true" ]; then
  env ZSH=$ZSH DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh
fi

# Initializes Oh My Zsh

# add a function path
fpath=($ZSH/functions $ZSH/completions $fpath)

# Load all stock functions (from $fpath files) called below.
autoload -U compaudit compinit

: ${ZSH_DISABLE_COMPFIX:=true}

# Set ZSH_CUSTOM to the path where your custom config files
# and plugins exists, or else we will use the default custom/
if [[ -z "$ZSH_CUSTOM" ]]; then
    ZSH_CUSTOM="$ZSH/custom"
fi

# Set ZSH_CACHE_DIR to the path where cache files should be created
# or else we will use the default cache/
if [[ -z "$ZSH_CACHE_DIR" ]]; then
  ZSH_CACHE_DIR="$ZSH/cache"
fi


# Load all of the config files in ~/oh-my-zsh that end in .zsh
# TIP: Add files you don't want in git to .gitignore
for config_file ($ZSH/lib/*.zsh); do
  custom_config_file="${ZSH_CUSTOM}/lib/${config_file:t}"
  [ -f "${custom_config_file}" ] && config_file=${custom_config_file}
  source $config_file
done


is_plugin() {
  local base_dir=$1
  local name=$2
  test -f $base_dir/plugins/$name/$name.plugin.zsh \
    || test -f $base_dir/plugins/$name/_$name
}
# Add all defined plugins to fpath. This must be done
# before running compinit.
for plugin ($plugins); do
  if is_plugin $ZSH_CUSTOM $plugin; then
    fpath=($ZSH_CUSTOM/plugins/$plugin $fpath)
  elif is_plugin $ZSH $plugin; then
    fpath=($ZSH/plugins/$plugin $fpath)
  fi
done

# Figure out the SHORT hostname
if [[ "$OSTYPE" = darwin* ]]; then
  # macOS's $HOST changes with dhcp, etc. Use ComputerName if possible.
  SHORT_HOST=$(scutil --get ComputerName 2>/dev/null) || SHORT_HOST=${HOST/.*/}
else
  SHORT_HOST=${HOST/.*/}
fi

# Save the location of the current completion dump file.
if [ -z "$ZSH_COMPDUMP" ]; then
  ZSH_COMPDUMP="${ZDOTDIR:-${HOME}}/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"
fi

if [[ $ZSH_DISABLE_COMPFIX != true ]]; then
  # If completion insecurities exist, warn the user without enabling completions.
  if ! compaudit &>/dev/null; then
    # This function resides in the "lib/compfix.zsh" script sourced above.
    handle_completion_insecurities
  # Else, enable and cache completions to the desired file.
  else
    compinit -d "${ZSH_COMPDUMP}"
  fi
else
  compinit -i -d "${ZSH_COMPDUMP}"
fi

# Load all of the plugins that were defined in ~/.zshrc
for plugin ($plugins); do
  if [ -f $ZSH_CUSTOM/plugins/$plugin/$plugin.plugin.zsh ]; then
    source $ZSH_CUSTOM/plugins/$plugin/$plugin.plugin.zsh
  elif [ -f $ZSH/plugins/$plugin/$plugin.plugin.zsh ]; then
    source $ZSH/plugins/$plugin/$plugin.plugin.zsh
  fi
done

# Load all of your custom configurations from custom/
for config_file ($ZSH_CUSTOM/*.zsh(N)); do
  source $config_file
done
unset config_file

# Load the theme
if [ "$ZSH_THEME" = "random" ]; then
  themes=($ZSH/themes/*zsh-theme)
  N=${#themes[@]}
  ((N=(RANDOM%N)+1))
  RANDOM_THEME=${themes[$N]}
  source "$RANDOM_THEME"
  echo "[oh-my-zsh] Random theme '$RANDOM_THEME' loaded..."
else
  if [ ! "$ZSH_THEME" = ""  ]; then
    if [ -f "$ZSH_CUSTOM/$ZSH_THEME.zsh-theme" ]; then
      source "$ZSH_CUSTOM/$ZSH_THEME.zsh-theme"
    elif [ -f "$ZSH_CUSTOM/themes/$ZSH_THEME.zsh-theme" ]; then
      source "$ZSH_CUSTOM/themes/$ZSH_THEME.zsh-theme"
    else
      source "$ZSH/themes/$ZSH_THEME.zsh-theme"
    fi
  fi
fi

**Comment by eremit** [comment]
@viveksachdeva can you attach the *.zshrc* instead of *oh-my-zsh.txt*?

**Comment by viveksachdeva** [comment]
Attached
[zshrc.txt](https://github.com/robbyrussell/oh-my-zsh/files/1050096/zshrc.txt)

**Comment by Jahhein** [comment]
What version of zsh are you running? You can check by running the command 'zsh --version'.

so long as:
1) zshrc is located at $HOME/.zshrc
and
2) Your .oh-my-zsh clone is located at $HOME/.oh-my-zsh

You shouldn't have a problem. Unless your zsh version, or you have a .zlogin or .zshenv config messing something up. Those two files a read before .zshrc

**Comment by Jahhein** [comment]
To save yourself troubleshooting time you could just delete your configurations files if you haven't put time into configuring them.

**Comment by viveksachdeva** [comment]
version : zsh 5.2 (x86_64-apple-darwin16.0)

File location is correct.. I removed .oh-my-zsh dir and cloned again.. still same issue

**Comment by Jahhein** [comment]
Then it's a configuration profile more than likely. Backup and remove your configuration files for zsh.
Go into the .oh-my-zsh directory and re-copy the template zshrc and replace your current zshrc located at $HOME/.zshrc

If that doesn't work...

The following command will move all configuration files for zsh to your desktop as a backup, and again, copy the OMZ zshrc template to your $HOME/.zshrc

' mv $HOME/{.zshrc,.zshenv,.zprofile.,.zlogin,.zlogout '

This would rule out that other ZSH configuration files in your $HOME directory could be conflicting.

**Comment by alexandredantas** [comment]
Besides checking files permissions, check if EDITOR environment variable is set. If it's not set, some scripts may fail

**Comment by mcornella** [comment]
Run `zsh -xvic 'exit' &> ~/omz-debug.log` and post the `omz-debug.log` file as a private gist. This is a weird issue... 

Check that you're really running zsh with `echo $0` (should say zsh).

**Comment by Bransonlee0426** [comment]
Same here!
When i run ~/.zshrc

/Users/x/.oh-my-zsh/oh-my-zsh.sh: line 23: autoload: command not found
/Users/x/.oh-my-zsh/oh-my-zsh.sh: line 34: syntax error near unexpected token `('
/Users/x/.oh-my-zsh/oh-my-zsh.sh: line 34: `for config_file ($ZSH/lib/*.zsh); do'

**Comment by mcornella** [comment]
Are you running it from bash? You should just run `zsh` and it will load the zshrc file itself.

**Comment by Bransonlee0426** [comment]
> Are you running it from bash? You should just run `zsh` and it will load the zshrc file itself.
I solved it.
Just delete the ~/.zshrc file but i got a issuse when i use  ~/.zshrc 
zsh: permission denied: /Users/bransonlee/.zshrc
Any idea for it?

**Comment by eremit** [comment]
@Bransonlee0426 what do you mean by "when I use ~/.zshrc".
```.zshrc``` is not an executable.
Simply start zsh by ```/bin/zsh``` or change your login shell via ```chsh -s /bin/bash```.
