### ISSUE TITLE
iTerm issues with Powerline font rendering

### ISSUE THREAD

**Issue by tobsn** [robbyrussell/oh-my-zsh#6094]
Tried to file an issue with iTerm but their gitlab is broken ;)

So this happened out of nowhere, no changes on zsh, no changes on the theme, no changes on the selected font:

![2017-05-19 at 1 11 pm](https://cloud.githubusercontent.com/assets/109529/26245681/83af36c2-3c95-11e7-8e92-2ed7d275d9c2.png)

Top Terminal.app, bottom iTerm.app

Maybe someone here has a similar experience?

Thank you!

**Comment by xshotD** [comment]
Not sure what you're talking about with GitLab being broken to be honest.

Works here.
