### ISSUE TITLE
"sudo" and "golang" plugins not working simultaneously

### ISSUE THREAD

**Issue by folixg** [robbyrussell/oh-my-zsh#6095]
Somehow the [sudo](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sudo) and [golang](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/golang) plugins don't work together. Only the one that is specified last in ```plugins``` in ```.zshrc``` is working.
So with ```plugins = (sudo, golang)``` I get a working golang plugin and with ```plugins = (golang, sudo)``` I get a working sudo plugin.

Debug log of a failed attempt to use golang completion: https://gist.github.com/folixg/9e95f0d91b210fb605dcd04981d2cd92#file-omz-debug_golang_fail-log

Debug log of a failed attempt to insert sudo by pressing ESC-ESC: https://gist.github.com/folixg/9e95f0d91b210fb605dcd04981d2cd92#file-omz-debug_sudo_fail-log

Any hint on what could cause this behavior is much appreciated.

**Comment by eremit** [comment]
Remove the **comma** in the plugin list so that it reads:
```
plugins = (sudo golang)
```

**Comment by folixg** [comment]
Oh my god, wouldn't have guessed that in a million years. Thanks!
