### ISSUE TITLE
Debian plugin does not support apt

### ISSUE THREAD

**Issue by kronos29296** [robbyrussell/oh-my-zsh#6098]
I use **apt** instead of apt-get or aptitude for package management as it uses a single command and options type of usage and the progress bar for installation. It is recommended for end users according to its man page. [apt man page](http://manpages.ubuntu.com/manpages/zesty/man8/apt.8.html)

But the debian plugin aliases point to aptitude or apt based on if aptitude is installed or not.

**Comment by xshotD** [comment]
Can confirm via a quick glance at the code of debian plugin:

```zsh
if [[ -e $( which -p aptitude 2>&1 ) ]]; then
    apt_pref='aptitude'
    apt_upgr='safe-upgrade'
else
    apt_pref='apt-get'
    apt_upgr='upgrade'
fi
```
