### ISSUE TITLE
No matches found

### ISSUE THREAD

**Issue by gabrownx** [robbyrussell/oh-my-zsh#6099]
Hello! When I try to install the retroarch with this command:
_sudo apt-get install retroarch retroarch-* libretro-* -y_
appears a message: **zsh: no matches found: retroarch-*** but when i uninstall the zsh doesn't appears any errors.

**Comment by vaporwavie** [comment]
Zsh considers the "*" as a wildcard. Try to do your command again but using single or double quotes:
<code>sudo apt install 'retroarch retroarch-* libretro-* -y'</code>

**Comment by xiaokesheng** [comment]
When I want to add some files with * using git, such as "git add *.java *.xml", it doesn't work either, and gives the same message: no matches found.
But I really don't want to add "'" in every git command.

**Comment by Shea690901** [comment]
That´s especially true since you **want** the shell to expand those wildcards....
But are you sure that the files you want to add are there to be matched? Or are they in some subdir you´re forgetting to provide?
`*.xml` matches other files then `subdir/*.xml`!

**Comment by Shea690901** [comment]
Especially since you **want** the shell to expand your patterns...
But are you sure that those files reside in your current directory?
The patterns `*.xml`, `dir1/*.xml`, `dir2/*.xml`, `*/*.xml`, `**/*.xml` and `***/*.xml` might all look for some xml files but (depnding on which files reside in which location) will either fail to match anything, have different or (partielly) the same matches...

**Comment by surajmandalcell** [comment]
Can this be fixed?

**Comment by mcornella** [comment]
This is zsh's intended behavior. If you want to disable all globbing you can use `unsetopt glob`, or if you want to disable it for a specific command you can alias it with `noglob` (i.e. `alias git='noglob git').

**Comment by Marek-Zientek** [comment]
> Zsh uważa gwiazdkę za symbol wieloznaczny. Spróbuj ponownie wykonać polecenie, używając pojedynczych lub podwójnych cudzysłowów:
> `sudo apt install 'retroarch retroarch-* libretro-* -y'`

thanks
