### ISSUE TITLE
gpg-agent plugin uses unsupported (deprecated) options

### ISSUE THREAD

**Issue by Czocher** [robbyrussell/oh-my-zsh#6106]
Since gpg 2.1 the `--write-env-file` option doesn't do anything:

```
$ gpg-agent --write-env-file
gpg-agent[6532]: WARNING: "--write-env-file" is an obsolete option - it has no effect
```

This causes the gpg-agent plugin to malfunction. It may be better to start the agent as it is defined in the gpg-agent documentation [here](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html) and [here](https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart), which means we'd have to:

1. Call `gpg-connect-agent /bye`
2. Set up the `GPG_TTY` variable: `export GPG_TTY=$(tty)`
3. If `enable-ssh-support` is in the `gpg-agent.conf` config file then set up the `SSH_AUTH_SOCK` variable: `export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"`

This would probably simplify the plugin and allow it to work with new versions of gpg-agent, but it would also mean loosing backward compatibility.

I can create a patch for this issue and fix the plugin but I need to know if backward compatibility is a requirement or not?

What do you think @robbyrussell ?

**Comment by felixsanz** [comment]
It doesn't malfunction, it just doesn't work :/

**Comment by Czocher** [comment]
It works for the people who have older versions of gpg installed ;).

**Comment by felixsanz** [comment]
Well, afaik he was talking about gpg 2.1, so i did.

**Comment by simplycycling** [comment]
I'm not sure if my issue is related or not, but gpg-agent simply wasn't working at all for me, with the current gpg-agent plugin in oh-my-zsh, so I put the following into my .zshrc, below the plugins line, and now it works as I would expect (meaning ssh-add -L shows my ssh key, and if I need to swap out for a different Yubikey, I'm able to bounce gpg-agent without the "a gpg-agent is already running" message):

    # Set SSH to use gpg-agent
    unset SSH_AGENT_PID
    if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
      export SSH_AUTH_SOCK="/run/user/$UID/gnupg/S.gpg-agent.ssh"
    fi

Obviously, change the UID to whatever you need it to be.

I am hoping a fix comes along, as this feels a little hacky. @Czocher - did you submit a PR?

**Comment by Czocher** [comment]
@simplycycling thanks for your input. Here's what I came up with after some tests:

```
# Enable gpg-agent if it is not running
GPG_AGENT_SOCKET="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
if [ ! -S $GPG_AGENT_SOCKET ]; then
  gpg-agent --daemon >/dev/null 2>&1
  export GPG_TTY=$(tty)
fi

# Set SSH to use gpg-agent if it is configured to do so 
GNUPGCONFIG=${GNUPGHOME:-"$HOME/.gnupg/gpg-agent.conf"}
if grep -q enable-ssh-support "$GNUPGCONFIG"; then
  unset SSH_AGENT_PID
  export SSH_AUTH_SOCK=$GPG_AGENT_SOCKET
fi
```

Here's the PR I created for it: #6140

**Comment by mzanibelli** [comment]
Unfortunately this throws errors if the `$GNUPGHOME` is manually set.

See https://github.com/robbyrussell/oh-my-zsh/pull/6140#issuecomment-342565054

**Comment by Phill93** [comment]
XDG_RUNTIME_DIR is not set on macOS.
And the GPG directory is named ".gnupg"

**Comment by Czocher** [comment]
@Phill93 Thanks for your input, that's something new. Can you provide information on where does gnupg create the `S.gpg-agent.ssh` socket? I'd create a fix to take your situation into account.

**Comment by Phill93** [comment]
@Czocher gnupg creates the socket in the `~/.gnupg/` Directory on macOS

[folder-content.txt](https://github.com/robbyrussell/oh-my-zsh/files/1600267/folder-content.txt)

**Comment by Czocher** [comment]
New PR ready, @Phill93 test if you can please.

**Comment by Phill93** [comment]
@Czocher test successful, now the agent starts correctly
Thank you

**Comment by mcornella** [comment]
Fixed on latest versions.
