### ISSUE TITLE
How do you display seconds in time?

### ISSUE THREAD

**Issue by ancon** [robbyrussell/oh-my-zsh#6109]
please help me 
How do you display seconds in time?
like the bash cmd
histtimeformat="%F %T"

**Comment by eremit** [comment]
%*
Current time of day in 24-hour format, with seconds.

**Comment by ancon** [comment]
@eremit 
# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"
how to set it? please help me , 3q~

**Comment by eremit** [comment]
@ancon okay, probably I was not really paying attention to your report..

see the following issue as reference:

https://github.com/robbyrussell/oh-my-zsh/issues/3466

In a nutsell:
* add one line HIST_STAMPS="yyyy-mm-dd"
* add one alias: alias history='fc -il 1'

**Comment by ancon** [comment]
@eremit thanks~
but it didn't work...
it can display the minute, but it display the seconds~
![2017-06-01 16 16 48](https://cloud.githubusercontent.com/assets/6762451/26670832/ce87cb6e-46e5-11e7-973a-411b21315a23.png)

**Comment by eremit** [comment]
@ancon use this one:

```
alias history="history -t'%F %T'
```

**Comment by eremit** [comment]
Hiya @ancon 
is your issue now resolved by the alias that I provided?

**Comment by ancon** [comment]
@eremit thanks a lot.
it work, but did not perfect.
I just think that display the second is unnecessary.

**Comment by ancon** [comment]
@CristianCantoro it work perfect! thanks a lot!

**Comment by tjharman** [comment]
I just had no idea why I wasn't seeing timestamps in my history either after setting this.

**Comment by CristianCantoro** [comment]
@tjharman said:
> I just had no idea why I wasn't seeing timestamps in my history either after setting this.

If you are interested in this feature you can support this pull request: PR https://github.com/robbyrussell/oh-my-zsh/pull/6770

**Comment by mcornella** [comment]
I've merged #6770 to include this feature. Now setting `HIST_STAMPS` to a custom format will automatically update the history alias to show the custom timestamp, no need to re-alias `history`.

**Comment by tjharman** [comment]
I find that it works if it's set to mm/dd/yyyy
But in New Zealand we use dd/mm/yyyy and if I set that, my output looks as follows:

```
   21  dd/mm/yyyy  vi .zsh
   22  dd/mm/yyyy  vim
   23  dd/mm/yyyy  vim .zshrc
   24  dd/mm/yyyy  history
   25  dd/mm/yyyy  vim .zshrc
```

**Comment by mcornella** [comment]
That's not a supported format. It has to be either one of these: `mm/dd/yyy`, `dd.mm.yyyy`, `yyyy-mm-dd`. If your desired format is not one of these, you have to specify your custom format using [strftime strings](http://man7.org/linux/man-pages/man3/strftime.3.html). Your specific case would be: `%d/%m/%Y`.
