### ISSUE TITLE
zsh: command not found: XXXX

### ISSUE THREAD

**Issue by Elaniobro** [robbyrussell/oh-my-zsh#6110]
I have been all over looking for info about how to resolve this. I am unsure of what to do.

`export PATH=$HOME/bin:/usr/local/bin:/usr/local/share/npm/bin:$PATH`

```
➜  git:(dev) ✗ lesshint com/css/styles.less 
zsh: command not found: lesshint
```

here is the actual node module installed:

```
➜  lesshint ls
CHANGELOG.md    LICENSE.md      appveyor.yml    docs            lib             package.json
CONTRIBUTING.md README.md       bin             gulpfile.js     node_modules    test
➜  lesshint pwd
/Users/elaniobro/.npm-packages/lib/node_modules/lesshint
```

Same thing happens over and over with any `node_module` installed. Please help.

**Comment by eremit** [comment]
@Elaniobro I noticed this as well, especially for node_modules. Seems that a new binary is not available in the same session right way. Usually spawning of a new session helped (at least in my case).

**Comment by exp-anoop** [comment]
I do have the same issue.

**Comment by Elaniobro** [comment]
@eremit yea, that did not work. I have ran `source ~/.zshrc` no matter what I do I get:
`zsh: command not found: [Name a package]`

Even when I try to run the `.oh-my-zsh.sh` script I get command not found:
```~/.oh-my-zsh/oh-my-zsh.sh  
zsh: permission denied: /Users/elaniobro/.oh-my-zsh/oh-my-zsh.sh
``` 

And same with sudo:
```
➜  ~ sudo  ~/.oh-my-zsh/oh-my-zsh.sh 
Password:
sudo: /Users/elaniobro/.oh-my-zsh/oh-my-zsh.sh: command not found
```

**Comment by Elaniobro** [comment]
bump.

**Comment by achere** [comment]
I have the same issue, does anyone have any suggestions?

**Comment by mcornella** [comment]
You have to add the directory where the binary is located to your `$PATH`, then run rehash to update the available commands.

For example, if you installed them globally, you could do:
```
export PATH=$PATH:$(npm prefix -g)/bin
```
