### ISSUE TITLE
ZSH Doesn't Start at New Terminal Creation

### ISSUE THREAD

**Issue by Astrades** [robbyrussell/oh-my-zsh#6112]
I installed oh-my-zsh and it was able to start automatically whenever I start a new terminal. I updated and rebooted my system and now, it doesn't work. I can still start zsh, but I can't make it auto-start. How can I fix this?

**Comment by brandon-m-skinner** [comment]
Hi.

[Try installing ZSH and setting it as your default shell](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH).

**Comment by pachonk** [comment]
Try this:
`chsh -s /bin/zsh`

**Comment by boyanbonev** [comment]
> Try this:
> chsh -s /bin/zsh

Thanks. This worked for me.

**Comment by mvanaltvorst** [comment]
In case this doesn't work for someone, try `chsh -s $(which zsh)`

**Comment by silentwarrior** [comment]
None of this is working for me. On Ubuntu (latest LTS) when I open a new shell it doesnt get `oh my zsh`ed. But if i delete ~/.oh-my-zsh and reinstall I do get it activated for my currently opened window.

**Comment by mcornella** [comment]
You need to do [this](https://github.com/robbyrussell/oh-my-zsh/issues/6112#issuecomment-463644808) and restart the user session (the whole desktop one).

**Comment by sagarr** [comment]
It worked after restarting my machine.

**Comment by flads** [comment]
> It worked after restarting my machine.

simply this!
