### ISSUE TITLE
Hyper terminal on MacOS - OSX plugin - "tab" command not working

### ISSUE THREAD

**Issue by rjwestman** [robbyrussell/oh-my-zsh#6115]
**Prerequisites:**
OS: macOS Sierra 10.12.5
Terminal: Hyper | Version 1.3.3 (1.3.3.1754)

**Steps to reproduce:**
- Activate osx plugin
- Restart terminal to have the setting change be applied
- enter "tab"

**Expected:**
- Current directory is opened in a new tab
- Expected behaviour can be checked by using the macOS default terminal

**Observed:**
Error message "tab: unsupported terminal app: Hyper"

**Assumed Priority:** low

**Comment by mcornella** [comment]
@rjwestman @tibuurcio @strivetobelazy @a-ast @nathandalal can you test #7494?
