### ISSUE TITLE
OSX Plugin Spotify Search Broken

### ISSUE THREAD

**Issue by robertTechJocks** [robbyrussell/oh-my-zsh#6118]
**How to reproduce the problem:**
Search for any artist/album/song using the plugin

**What the correct behavior should be**
Spotify will find a match and start playing the match

**What the actual behavior is**
Spotify returns with "No results when searching for X"

**Comment by xshotD** [comment]
This problem is most likely due to Spotify's breaking change of access. Any requests to their API now require a access token.

**Comment by hnarayanan** [comment]
There is is an updated version of the project from where the original spotify plugin was derived from: https://github.com/hnarayanan/shpotify

This now has proper support for access tokens. It can be ported over to this project if there is interest.
