### ISSUE TITLE
uninstall zsh didn't revert shell back to bash on OSX

### ISSUE THREAD

**Issue by rob-watts** [robbyrussell/oh-my-zsh#6119]
After running the uninstall command for zsh and restarting the terminal, I noted the zsh shell was still in use afterward. 

I had to use:

`chsh -s /bin/bash`

and restart the terminal to get the bash shell back.

I didn't think this was the expected result from the uninstall so I thought I would log an issue.

OSX Sierra 10.12.5

**Comment by donutmonger** [comment]
Looking at https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/uninstall.sh it looks like the uninstall script reverts your shell back to bash only if you didn't have a .zshrc before you installed oh-my-zsh.

**Comment by tysun** [comment]
@rob-watts You saved me there 👍

**Comment by johanroug** [comment]
thanks

**Comment by omatheus015** [comment]
@rob-watts your solution worked from me. Thank you very much... You saved me!!!

**Comment by mcornella** [comment]
Hi there, the behavior introduced in #5169 is to save the previous shell and restore it when uninstalling (but default to bash if no previous shell was saved). It also adds a few helpful comments to know what to do if things don't work.

**Comment by mcornella** [comment]
Closed by #5169.
