### ISSUE TITLE
Press TAB show directory as command!?

### ISSUE THREAD

**Issue by gino2010** [robbyrussell/oh-my-zsh#6120]
System: Mac OS X Sierra
I just install oh my zsh, and edit .zshrc file, append 
`source .bash_profile`

In .bash_profile, key lines:
```
export ORACLE_CLIENT=/Users/xxx/Library/instantclient
export PATH=$PATH:$ORACLE_CLIENT
```
There is '_sdk_' directory in /Users/xxx/Library/instantclient
Open Terminal, I find zsh identify '_sdk_' directory as a command, when I input sdk and press TAB, I can find '_sdk_' in hint with other commands.

More experiments:
If I create a new directory in $PATH, whatever name of directory, for example test1, I can also find this name in command hint.

So, zsh identify directory in $PATH as command? Or What I did wrong?
How can I fix it? Thanks

**Comment by folixg** [comment]
From my understanding this is how $PATH works. Everything in your $PATH is considered an executable.

[https://en.wikipedia.org/wiki/PATH_(variable)](https://en.wikipedia.org/wiki/PATH_(variable))

**Comment by mcornella** [comment]
This can be disabled if you run [`setopt hashexecutablesonly`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-HASHEXECUTABLESONLY), then `rehash`.
