### ISSUE TITLE
allow inverting behaviour of globalias plugin

### ISSUE THREAD

**Issue by nonchip** [robbyrussell/oh-my-zsh#6123]
I like the idea of the `globalias` plugin, but defaulting to replace aliases/subcommands is rather annoying, especially for people who like to draft oneliners or large pipes in a shell before copying them into a script etc.

therefore I want to propose a `~/.zshrc` config variable like `GLOBALIAS_INVERT_KEYS` or `zstyle :omz:plugins:globalias invert_keys` or similar that does nothing on space but replaces the aliases on ctrl+space.

**Comment by mavam** [comment]
I'm encountering the same. The function `globalias` is defined as follows:

```sh
globalias() {
   zle _expand_alias
   zle expand-word
   zle self-insert
}
```

Maybe all we need is make `expand-word` optional or configurable?

**Comment by nonchip** [comment]
@mavam maybe a stupid question, but: what does removing `expand-word` actually do then?

**Comment by mavam** [comment]
From the man page:

>        expand-word (^X*) (unbound) (unbound)
>              Attempt shell expansion on the current word.

So it does what it says: if there's a way to expand the current word, then this widget does it.

**Comment by nonchip** [comment]
so your patch doesn't really invert the behaviour, just remove it?

**Comment by mavam** [comment]
Yeah, it's just a workaround for the behavior that I find most useful. I do like the alias expansion (especially for git commands), but I don't need it to happen *automatically* for command arguments. There, it's still possible to trigger it with <kbd>Tab</kbd>, .e.g., `ls *.txt` + <kbd>Tab</kbd> expands text files on demand.

**Comment by nonchip** [comment]
aaah i see, nice.

**Comment by mcornella** [comment]
You can change the bindkey commands:
```
# space expands all aliases, including global
bindkey -M emacs "^ " globalias
bindkey -M viins "^ " globalias

# control-space to make a normal space
bindkey -M emacs " " magic-space
bindkey -M viins " " magic-space
```

**Comment by pyxelr** [comment]
@mcornell: Thank you, I have applied your suggestion on macOS, but to make it work, I also had to apply [this suggestion](https://mattkirwancom.wordpress.com/2020/04/30/use-ctrl-space-tmux-prefix-keybind-macos/#:~:text=To%20fix%20all%20you%20need%20to%20do%20is%20navigate%20to%20the%20%E2%80%9CInput%20Sources%E2%80%9D%20section%20of%20the%20%E2%80%9CShortcuts%E2%80%9D%20Keyboard%20preferences%20and%20uncheck%20(or%20change!)%20that%20shortcut.) (disable the default `^Space` macOS shortcut).

However, now when I use `Ctrl` + `Space`, the `^@` part is being added at the end of an expansion. For example:
1. I have an alias for `h` to be `history`
2. After typing `h` and pressing `Ctrl` + `Space`, it gets expanded into `history^@`
3. It is possible to remove `^@` with a single press of a `backspace` key, but it is still annoying.  Do you know if there is a fix for that? If I do not load `globalias` plugin, hitting `Ctrl` + `Space` does not produce `^@` in my iTerm.
