### ISSUE TITLE
Can not copy/paste on centos7.2

### ISSUE THREAD

**Issue by crazy-canux** [robbyrussell/oh-my-zsh#6125]
hi,

I got a problem when I changed from ubuntu to centos.

When I use mouse double click to copy and use middle button to paste, Just part of it paste on the terminal and the last char become upper. Even  shift+ctrl+v/c doesn't work.

OS:  centos7.2.1511
zsh:  5.0.2

After investigate really don't know what's going on.

I use this configuration on ubuntu14.04 and it's works well.

Here is the plugins i enabled:

![capture](https://cloud.githubusercontent.com/assets/14313415/26814844/1d2eb6be-4abb-11e7-9aa4-a3f0c7299506.PNG)

**Comment by folixg** [comment]
This sounds more like a problem with your terminal emulator, than with the shell. 
Are you using the same terminal emulator with centos and ubuntu?

**Comment by crazy-canux** [comment]
Yes, all the same.
But, different result.
