### ISSUE TITLE
aws plugin - (feat) add a way to clear the asp command

### ISSUE THREAD

**Issue by angelosarto** [robbyrussell/oh-my-zsh#6127]
The aws set profile command is great, but there isn't a way to clear it and have no profile set.

**Comment by geekmuse** [comment]
just type `asp<ENTER>` - you can echo out `$AWS_PROFILE` and verify that no profile is set

**Comment by angelosarto** [comment]
That definitely clears the profile but it does leave the console decoration "<aws:>"
