### ISSUE TITLE
Update lock may not be relinquished

### ISSUE THREAD

**Issue by nickswalker** [robbyrussell/oh-my-zsh#6138]
If the upgrade script loads the epoch dotfile and discovers that it is empty, it will create and populate it, then return without relinquishing the update lock. I don't know the full lifecycle of this lock, but it appears that this would cause the user to never be prompted to update again.

https://github.com/robbyrussell/oh-my-zsh/blob/1f64fa92f524d47a87320a4baf9d9883fd23ab5e/tools/check_for_upgrade.sh#L37

**Comment by mcornella** [comment]
Thanks for noticing this! Hopefully this only happened when LAST_EPOCH wasn't defined, meaning only on the very first upgrade check after a user has installed OMZ. 

I've pushed a very rough patch that should solve this, but we might have to instruct users whose automatic updates don't trigger how to manually remove the lock and upgrade to the latest version with `upgrade_oh_my_zsh`.

Thanks again!
