### ISSUE TITLE
ZSH completion functions broken

### ISSUE THREAD

**Issue by Iambecomeroot** [robbyrussell/oh-my-zsh#6145]
My oh-my-zsh install which has been working for almost a year has just broken. When I open a terminal, I get:
```
/home/marcel/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/marcel/.oh-my-zsh/oh-my-zsh.sh:78: compinit: function definition file not found
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:80: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:93: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:100: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:109: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:119: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:129: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:163: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:166: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:168: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:182: command not found: compdef
/home/marcel/.oh-my-zsh/plugins/git/git.plugin.zsh:193: command not found: compdef
$SPACESHIP_PROMPT_TRUNC is deprecated. Use $SPACESHIP_DIR_TRUNC instead.
spaceship_setup:3: add-zsh-hook: function definition file not found
spaceship_setup:4: add-zsh-hook: function definition file not found
$SPACESHIP_PROMPT_TRUNC is deprecated. Use $SPACESHIP_DIR_TRUNC instead.
spaceship_setup:3: add-zsh-hook: function definition file not found
spaceship_setup:4: add-zsh-hook: function definition file not found
```
A lot of other answers involve running `compaudit`. Running this gives me `zsh: compaudit: function definition file not found`.

### What I have tried:
1. `rm ~/.zcompdump*`
1. Reinstalling oh-my-zsh
1. Reinstalling zsh from source
1. Adding `/usr/share/zsh/functions` to `$fpath`
1. `chown -R 755 /usr/share/zsh/functions`

### My environment:
* `uname -a`: `Linux Hermes 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 08:19:42 CEST 2017 x86_64 GNU/Linux`
* `zsh --version`: `zsh 5.3.1 (x86_64-unknown-linux-gnu)`
* `which zsh`: `/usr/local/bin/zsh`

Sorry if this is the wrong place to post this. I don't know if it's a zsh issue or an omzsh issue but I couldn't find where to post zsh issues so here I am.

**Comment by m99coder** [comment]
I have a similar problem since yesterday as ZSH was updated to `5.3.1`. For every folder within a git repository I get the message `prompt_git:37: vcs_info: function definition file not found` as I’m using the plugins `git`, `warhol` and `wd`.

```
$ uname -a
Darwin ZALANDO-20181 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
$ zsh --version
zsh 5.3.1 (x86_64-apple-darwin16.6.0)
```

**Comment by Iambecomeroot** [comment]
I am still getting this issue with `zsh-5.2-2`. It's not a zsh update for me I guess.

**Comment by Iambecomeroot** [comment]
I have confirmed that it is a permissions problem. If I do

    sudo zsh -f
    autoload -U compaudit
    compaudit

The command works as expected. I then did

    sudo chmod 777 /usr/share/zsh/ -R # Just for testing I promise

and I still got `zsh: compaudit: function definition file not found` when running `compaudit`.

I also tried

    sudo chown user:users /usr/share/zsh/ -R

and it's still not working. If all these files are owned by my user AND are 777 how does zsh work as root and not as my user?

**Comment by Iambecomeroot** [comment]
# Solution:

It was my `$FPATH`. Since root was working, I copied over the `$FPATH`. I knew it was something like this but I just added the wrong directories to it I guess.

**Comment by jshardy** [comment]
@Iambecomeroot it would be so kind of you to tell how you solved it. Sure would save me a lot of time..........................................................................................................................................................................................................................................................................................................................................................................

**Comment by Iambecomeroot** [comment]
@jshardy As I said, I copied the `$FPATH` from the root user. I logged in as root (`sudo su`), then I copied the value of the variable (`echo $FPATH`), and finally I added that for my own user by putting `export FPATH=<copied value>` in my `~/.zshrc`.

**Comment by jshardy** [comment]
Ah I'm sorry, I didn't pay attention to "root".

I ended up commenting out $FPATH and debugging it from there. Not really sure what happened. I was adding zsh-completions to FPATH. Not sure why it went wrong, after uncommenting it again, it works...

My apologies.

**Comment by FlickerSoul** [comment]
Worked. Thank you so much!

**Comment by 0618** [comment]
I went back to my root and quit tmux. Then it worked again for me.
