### ISSUE TITLE
Shirt sales site

### ISSUE THREAD

**Issue by edasaki** [robbyrussell/oh-my-zsh#6149]
I'm not sure that this is the right place for this kind of feedback, but I feel the [shirt sales page](https://shop.planetargon.com/products/ohmyzsh-t-shirts) *really* needs like, a proper shirt-only front and back image. It's great that we can see what it looks like when worn, but there's not a single short that's an unobstructed front view of the shirt itself.

**Comment by mcornella** [comment]
I relayed your message. Thanks!
