### ISSUE TITLE
no such file or directory: /Users/tador/.oh-my-zsh/themes/“random”.zsh-theme

### ISSUE THREAD

**Issue by TadorHead** [robbyrussell/oh-my-zsh#6151]
I've just installed Oh My Zsh on my mac with iTerm2 and I wanted to try out one of the themes. I followed the direction for changing the theme but I keep getting this error in my terminal : `/Users/tador-vault/.oh-my-zsh/oh-my-zsh.sh:source:110: no such file or directory: /Users/tador-vault/.oh-my-zsh/themes/“random”.zsh-theme`. I get this error for every theme I've tried, including the default theme. 

![screen shot 2017-06-25 at 16 19 58](https://user-images.githubusercontent.com/9774563/27519490-b52215a4-59c2-11e7-81db-e7a66a06d709.png)

Any help would be appreciated.

**Comment by folixg** [comment]
Maybe try editing the file with another editor. It seems like you are using the wrong quotation marks to enclose the string. It should be ```"robbyrussel"```, not ```“robbyrussel”```. But maybe that is just because of the font you use for your terminal.

**Comment by folixg** [comment]
Check out #6090

**Comment by TadorHead** [comment]
Thank you @folixg for responding, it worked. I never thought about the editor, I knew it would be something simple. Thanks again!
