### ISSUE TITLE
can not autocomplete my makefile compile command when press "TAB"

### ISSUE THREAD

**Issue by zwxf** [robbyrussell/oh-my-zsh#6153]
this problem willl not happen in other shell like bash,when i press TAB and can not find the makefile command in the list.
this is my system version
"Linux zwxf 4.9.0-deepin5-amd64 #1 SMP PREEMPT Deepin 4.9.8-5 (2017-05-02) x86_64 GNU/Linux"
please check it out.

**Comment by mcornella** [comment]
The completion for the make command is provided by zsh, not Oh My Zsh. Nevertheless, if this still happens reply with more information, such as the exact command you're trying to complete and your Makefile contents.
