### ISSUE TITLE
Enter key not working

### ISSUE THREAD

**Issue by ghost** [robbyrussell/oh-my-zsh#6159]
When running zsh the enter key is not working, i can't do any command and i haven't changed any config files, i'm running on Arch.

**Comment by kapsh** [comment]
`^J` / `^M` doesn't work too? 
Linux distro is less important, it's better to name used terminal.

**Comment by Thedocz** [comment]
yes both ^J  and  ^M works, but not the return key. I tried terminator and gnome-terminal

**Comment by WaYdotNET** [comment]
ubuntu 17.04, some issue (^J and ^M work well)

**Comment by dalu** [comment]
keypad enter key doesn't work here (beep beep, warning tone)
the big regular enter key works

**Comment by captainkirkoff** [comment]
Same here with mintty under cygwin: no new line, only beep when hitting the enter key.  ^M and  ^J just work. The enter key works fine if the shell is started outside mintty, with cygwin.bat.

**Comment by dalu** [comment]
It was something about.. changing some settings.
oh-my-zsh seems to be abandoned. or rob is overoccupied.

**Comment by mcornella** [comment]
@dalu glad you solved it, did you narrow down the offending config?

And no, OMZ is not abandoned, we're just in need of more part- or full-time contributors.

**Comment by dalu** [comment]
in .zshrc
for linux, I googled and found that, there's a solution somewhere else
I don't have a mac so that's all I've got
```
# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"
```

**Comment by mcornella** [comment]
Oh you're talking about keypad enter. Yeah so the relevant part was `bindkey -s "^[OM" "^M"`.

For the rest of you that have issues with the enter key, try running a clean zsh (`zsh -f`) to see if it works there.

**Comment by lc-stevenzhang** [comment]
Can't believe still need this hack to make keypad work, today.

**Comment by Syphdias** [comment]
Maybe a stupid question, but why is this necessary? It works in vanilla `zsh`! (type `zsh -df`, disable num lock and press num lock enter/return.)

So if I understand it correctly this is only happening if num lock is not active (at least in my case). So why does omz break this standard behavior? If this is intended, what is the reasoning behind it?

**Comment by quchunguang** [comment]
same issues appeared on ubuntu 18.04 / Kali 19.3.
Is there any suggestion except for add `bindkey`s to .zshrc?

**Comment by OmegaNalphA** [comment]
I'm still getting this issue and zsh -f isn't working for me. I've tried uninstalling iterm to no avail, is there any other way to fix this?

**Comment by surak** [comment]
This happens on all oh-my-zsh configurations - I don't understand why this was closed. `zsh -f` performs as expected.

**Comment by mboehm21** [comment]
Same issue here. I also needed the hack mentioned by @mcornella in my `.zshrc` to make my ENTER-key work. This should be default behaviour.

**Comment by codelerk** [comment]
Still here in 2022 put this at the bottom of your zshrc.      bindkey -s "^[OM" "^M"

**Comment by KwisatzJim** [comment]
same for me.  on Manjaro linux with MATE in the MATE Terminal.

**Comment by linaori** [comment]
I know this issue is closed, but it's still not working by default.

**Comment by codertjay** [comment]
i turned off NumLK  and mine started working
