### ISSUE TITLE
Not working with youtube-dl command

### ISSUE THREAD

**Issue by ArtemBernatskyy** [robbyrussell/oh-my-zsh#6162]
Hello  
I am trying to execute  
`youtube-dl --ignore-errors --yes-playlist  --extract-audio --audio-format mp3 --audio-quality 0 http://www.youtube.com/playlist?someurl` command in oh-my-zsh  
but it says  
`zsh: no matches found: http://www.youtube.com/playlist?someurl`  

BUT when i switch back to `/bin/bash` it works flawlessly

**Comment by GreenJoey** [comment]
This is something to do with how zsh handles the input to itself. In the zsh shell you use the command as:

`youtube-dl --ignore-errors --yes-playlist --extract-audio --audio-format mp3 --audio-quality 0 "http://www.youtube.com/playlist?someurl"`

Use double quotes for the url

**Comment by ArtemBernatskyy** [comment]
@GreenJoey So should i file an issue to zsh itself, or it's a feature not a bug ?

**Comment by eremit** [comment]
@ArtemBernatskyy alternatively you can simply mask the "?" with a "\".

**Comment by ohjames** [comment]
@ArtemBenatskyy There is no bug here, you have failed to understand how zsh pattern matching works. Please close.

**Comment by ohjames** [comment]
@ArtemBernatskyy There is no bug here, you have failed to understand how zsh pattern matching works. Please close.

**Comment by ArtemBernatskyy** [comment]
@ohjames but this wrong matching pattern causes user displeasure, doesn't it ?

**Comment by eremit** [comment]
@ArtemBernatskyy it's not wrong pattern matching at all, though *you* might be displeased by it.

Anyhow, as @ohjames already pointed out, there is no bug and the least a bug in oh-my-zsh.

**Comment by ohjames** [comment]
Yes, mistakes cause you grief, so learn from them. `?` like `*` is a global operator and must be escaped. Globbing operators are not blogs. Now close this.

**Comment by ArtemBernatskyy** [comment]
ok, closing this for now, but i thought that open source were made for better products not for explaining why some bugs could be features )

**Comment by ohjames** [comment]
@ArtemBernatsky You should realise that when your criticism comes from a lack of understanding that your concerns are invalid, you should see this as a chance to educate yourself. By levying out criticism without taking the time to understand you just come across as ignorant.

`echo b*` echoes all of the files beginning with a `b`. This is a really useful globbing pattern. When you do `echo *.b??` it matches all files with an extension beginning with a `b`. This is useful for many.

So you can't have things both ways, both have access to globbing operators and not need to escape those globbing operators.

**Comment by ArtemBernatskyy** [comment]
Omg @ohjames , i am just trying to tell that in ordinary terminal that command works, in zsh it doesn't, is it bug or feature this decision i will leave to the creators

**Comment by MikeDrones** [comment]
can we add a line to the .zshrc to make it play nice with youtube-dl ?

**Comment by ohjames** [comment]
`alias youtube-dl noglob youtube-dl`

**Comment by MikeDrones** [comment]
awesome thanks

**Comment by josh-works** [comment]
If anyone ends up here w/a similar problem with github issues because of the `#` command:

eg:

```shell
$ git co maintain_aspect_ratio_#30
> zsh: no matches found: maintain_aspect_ratio_#30
```
update `~/.zshrc` with:
`alias git="noglob git"`
