### ISSUE TITLE
complete:13: command not found: compdef (Still exists)

### ISSUE THREAD

**Issue by leongaban** [robbyrussell/oh-my-zsh#6163]
Hi I recently installed NVM and now I keep getting this error.

> complete:13: command not found: compdef

I've done all the steps mentioned by [@mcornella](https://github.com/mcornella) here: https://github.com/robbyrussell/oh-my-zsh/issues/3356

- Removing my `zcompdump` files via the cli or manually did not work
- `exec zsh` did not work
- The following lines did not work

```
compaudit | xargs -I '%' chmod g-w '%'
compaudit | xargs -I '%' chown $USER:$USER '%'
rm ~/.zcompdump*
exec zsh
```

This is my current version of ZSH `zsh 5.0.8 (x86_64-apple-darwin15.0)`
My NVM version is `0.33.2`
Node `v7.10.0`

What new steps should I take? What files do you need to see here?

btw when I delete the dump file, it comes back everytime I open the terminal with zsh, or a new tab in zsh

`.zcompdump-Leon's MacBook Pro-5.0.8`

**Comment by leongaban** [comment]
Actually I finally found out where those NVM lines where, they were in my .zshrc file.

https://github.com/denysdovhan/dotfiles/commit/e13cbda0ff05e32b0ab81c82040fb12cac92f9eb

I didn't have a .zsh file, but in my main .zshrc file these lines where added.
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

I commented out the last line and no more annoying warning message.
There is still that tiny slight delay however when opening a new tab or terminal.

**Comment by cooperka** [comment]
@leongaban commenting out the line that loads `bash_completion` is not the best solution, because then you don't have bash completion!

I solved it by moving that whole block of code to the **bottom** of my `~/.zshrc` file:

```bash
# ... Lots of other code

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by N3oTraX** [comment]
Hi,

My issue was solved when removing wrong plugin in my ~/.zshrc 
This issue come with my migration from gentoo to archlinux

I replaced "gentoo" plugin by archlinux at the end of the following line :

`plugins=(rails ruby git brew python zsh_reload systemadmin torrent themes rbenv adb bundler colorize command-not-found common-aliases github git-extras gem extract cp copydir copyfile history-substring-search mix nanoc git-prompt archlinux)`

To be sure that zcompdump was not corrupted I deleted it and re-source my .zshrc

Issue was gone.

**Comment by picturedesk** [comment]
I had to update NVM, than "complete:13 command not found..." disappeared.
https://github.com/creationix/nvm#install--update-script
