### ISSUE TITLE
How to run custom commands after zsh launches

### ISSUE THREAD

**Issue by mukteshkrmishra** [robbyrussell/oh-my-zsh#6164]
Hi, 

I am using zsh in iTerm.  On startup I put following commands in General to launch : 

zsh (launches zsh). 

However I want once the zsh launches then 2 commands execute (as we can do in terminal or iterm2)  ie: ls && nvm use 4.2.3 (these must be executing inside zsh)

How to do this.

**Comment by folixg** [comment]
Simply put the commands in your .zshrc, then they will be executed everytime zsh starts.

**Comment by GreatBahram** [comment]
@mukteshkrmishra  you can put your script or command in ~/.zshenv and whenever zsh runs it will execute that piece of code.
if find your answer please close this issue
thanks

**Comment by mukteshkrmishra** [comment]
Thanks!! Let me check the same.

**Comment by Aestial** [comment]
I found that using ~/.zshenv as @GreatBahram suggested made my commands run twice, at least with my configuration. You can use other configuration files if you are facing the same problem as explained here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/23#issuecomment-31034789
