### ISSUE TITLE
plugins not working?

### ISSUE THREAD

**Issue by javixeneize** [robbyrussell/oh-my-zsh#6171]
Hi

I have edited .zshrc to modify the plugins, adding docker and python, but those dont seem to work

In fact, i have removed the plugins that come by default, as git, and those are still working

Should i reload anything to change the plugins?

Thanks

**Comment by AdrienHorgnies** [comment]
Your .zshrc is read only and you open a new shell by opening a new terminal or a shell with `env zsh` or directly sourcing the file `source .zshrc`. 

However certain changes may survive such operations, if you persist to have problems, log out and log in back.

And you're **NOT** at the right place to ask such a question. You should have tried 2 minutes more or researched a bit on the internet and you would have obtained your answer. And if you didn't you should have ask your question on stackoverflow.

**Comment by javixeneize** [comment]
I have done that. Most of the plugins work but not python

So, this is not the right place to report an issue, right? I might have misunderstood the "issues" label. Apologies

**Comment by eremit** [comment]
@javixeneize can you post your .zshrc?

**Comment by AdrienHorgnies** [comment]
@javixeneize Well, after reading `Should i reload anything to change the plugins?`, I concluded that your problem was very trivial, you didn't do your part of research and were using this channel as 'get help' forum. If that's not the case, I'm sorry.

So, after log in out and log back and opening a new terminal session, you still can use removed plugin such as git ? Are you using a plugin manager ?

**Comment by javixeneize** [comment]
No problem :)

Regarding git, i saw that .zshrc contains two plugins sections, and git
plugin was in both sections. I only removed from one, so it kept working

I have managed to make all the plugins i need (docker, colourize etc...)
but not python.

My config is nothing special. I have a plugin section where i have git
docker python and colourize. All of them work but python...

I am using opensuse if it helps

PS: I am experiencing the same problem with awesomepanda plugin

Thanks

**Comment by folixg** [comment]
Why do you have two plugins declarations? I am not sure if this is supported by oh-my-zsh. Try writing everythin in one statement.

**Comment by javixeneize** [comment]
I changed it as soon as i saw it. I added the plugin line at the end of the file without noticing it was already defined...

Anyway, i have only one plugin declaration now and the issue is still there

Thanks

**Comment by Gr1N** [comment]
Stuck with same issue, maybe anyone know what is wrong?
My list of plugins: git, extract, pip, python, tmux, tmuxinator, virtualenv, zsh-navigation-tools, zsh_reload, zsh-syntax-highlighting.

**Comment by eremit** [comment]
@javixeneize can you post your plugin line?

**Comment by AdrienHorgnies** [comment]
@javixeneize I would suggest you to post your whole `.zshrc`, just delete sensitive information if any.

**Comment by Yannleost** [comment]
> Your .zshrc is read only when you open a new shell by opening a new terminal or a shell with `env zsh` or when you source the file `source .zshrc`.
> 
> However certain changes may survive such operations, if you persist to have problems, log out and log in back from your unix session.
> 
> And you're **NOT** at the right place to ask such a question. You should have tried 2 minutes more or researched a bit on the internet and you would have obtained your answer. And if you didn't you should have ask your question on stackoverflow.
You're a dick
