### ISSUE TITLE
globalias messing up with some aliases depending their values

### ISSUE THREAD

**Issue by AdrienHorgnies** [robbyrussell/oh-my-zsh#6172]
```shell 
 ~  alias  | grep apm                                                           16:38:01 
apm='comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n "s/^Package: //p" | sort -u)'
 ~  apmsed: -e expression #1, char 11: unterminated `s' command                 16:38:36 
comm -23 <(apt-mark showmanual | sort -u) /proc/self/fd/13 
```
I pressed ' ' (space) after typing 'apm' and it outputted what you can see above, an invalid command.
I suppose it didn't like some of the characters from my alias because it didn't escape them or something like that.

I have tested with bash and expended the alias using `<ctrl><left alt><e>` and it worked fine.

It also messes up with the alias **gdct** from the plugin **git**.

**Comment by mcornella** [comment]
The thing is that the expansion also expanded 
```
<(gzip -dc /var/log/installer/initial-status.gz | sed -n "s/^Package: //p" | sort -u)
```
Turning it into a temporary file or `/proc/self/fd/13`. The command would've run equally ok, it just is a bit confusing.
