### ISSUE TITLE
External Themes page eating up RAM

### ISSUE THREAD

**Issue by iamsubhranil** [robbyrussell/oh-my-zsh#6173]
Whenever https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes is opened in a tab, RAM usage cramping up, and finally whole RAM gets eaten by Firefox(by the Web Content process). My 4GB RAM is filling up at a rate of almost 100MBps. This has not happened before. Is something wrong with the page?

Tested on Ubuntu 16.04(4.4.0-83-generic x86_64) and Arch(4.11.7-ARCH) on Firefox 54.0(multiprocess enabled).

**Comment by folixg** [comment]
I am not able to reproduce this behavior with Firefox 54.0 on Ubuntu 16.04 (4.4.0-81-generic x86_64).

**Comment by eremit** [comment]
I can reproduce the behavior with Firefox 54.0 on Fedora 25.

Seems that this only occurs when firefox is running with multiprocess windows enabled (which could be disabled because of extensions).

**Comment by tobske** [comment]
I can confirm this issue with Firefox 54.0.1 and enabled multiprocess.

**Comment by mcornella** [comment]
This seems to be a Firefox 54 issue then.
