### ISSUE TITLE
Sierra OSx Autocomplete issues

### ISSUE THREAD

**Issue by gotama** [robbyrussell/oh-my-zsh#6175]
Hey guys,

For the most part autocomplete works wonderfully.  But i have one issue so far.

When using this command:
>open -a "Microsoft Word" Filename.docx  

the autocomplete on Filename.docx doesnt work.  Am I missing something or maybe can be directed to the right solution?

Or is this a missing feature maybe a bug?

Regards.

**Comment by mcornella** [comment]
This should be provided by [zsh's completion for `open`](https://github.com/zsh-users/zsh/blob/master/Completion/Darwin/Command/_open). Maybe that completion doesn't support it, or maybe you don't have the latest zsh version.
