### ISSUE TITLE
Git plugin not working; all others do

### ISSUE THREAD

**Issue by nothingrandom** [robbyrussell/oh-my-zsh#6178]
All other plugins work fine, common-alias, zsh-syntax-highlighting, npm, etc. However, for some reason the git plugin is not working.

I'm sorry that's not much info, can you tell me how I can generate a useful log file so someone can advise me?

**Comment by robbyrussell** [comment]
@nothingrandom I know this might sound like a silly question...but do you have git installed? 

`git --version`

**Comment by folixg** [comment]
@nothingrandom check the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting) for instructions on how to produce a debug log.
@robbyrussell can you even install oh-my-zsh without git?

**Comment by nothingrandom** [comment]
@robbyrussell Hey, yes I do this is the output `git version 2.11.0 (Apple Git-81)` Would you like a log?

**Comment by nntoan** [comment]
I meet the same issue too. The git completion still working, but it unable to show auto-complete for branches anymore. If I revert the oh-my-zsh, it can (!!?)

**Comment by mcornella** [comment]
@nntoan the git completion is a concern of the git plugin, it is provided by zsh itself.

@nothingrandom what do you have in the plugins array of your zshrc file? The git plugin should provide aliases, I understand you're not getting them?

**Comment by mcornella** [comment]
@nntoan it is also possible that you're using the `gitfast` plugin which ships its own completion, which I believe is quite outdated.

I'm closing this issue since there was no response.
