### ISSUE TITLE
Does oh-my-zsh's theme conflict with terminal's theme? 

### ISSUE THREAD

**Issue by alexya** [robbyrussell/oh-my-zsh#6181]
I am using 2 terminals. see the following 2 screenshots. 
Left is MacOSX default terminal app, and right is iTerm2. 

In the following 1st screenshot, both terminal app and iTerm2 are using `Solarized Dark theme` in theirs settings, and I used oh-my-zsh theme `crcandy` too. You can see the results of them are different. It seems that the MacOSX default terminal can show the color defined in crcandy.zsh-theme, but iTerm2 failed.

![image](https://user-images.githubusercontent.com/2831220/28058768-51f289e8-6654-11e7-8465-c40cafe361e2.png)

In the following 2nd screenshot, I removed `Solarized Dark theme` for both terminal apps. But crcandy.zsh-theme was still in use. You can see that both terminals can show the color correctly. 

![image](https://user-images.githubusercontent.com/2831220/28112530-ed5fb806-672b-11e7-9024-b51dde84319a.png)

So, I am not sure if it is a bug of oh-my-zsh. It seems that it can't apply terminal app's theme and zsh theme at the same time to iTerm2 app.

**Comment by mcornella** [comment]
This is the terminal's color scheme. On both comparisons I see a difference between the colors, and it's probably a difference in the color scheme applied to Terminal.app and iTerm2. They may both be using a color scheme called `Solarized Dark`, but the actual colors are different.
