### ISSUE TITLE
Git plugin has unknown flag --recursive on clone (gcl)

### ISSUE THREAD

**Issue by Billy-** [robbyrussell/oh-my-zsh#6182]
[This line](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L72) - Can't see the `--recursive` flag in [the manpage](https://git-scm.com/docs/git-clone); any idea what it's supposed to be there for?

**Comment by eremit** [comment]
`--recursive` is used during cloning and will clone the specified repository including all submodules

**Comment by Billy-** [comment]
Should it not be `--recurse-submodules` (according to the man page)?

**Comment by eremit** [comment]
Right, but (from the manpage):  This is equivalent to running `git submodule update --init --recursive` immediately after the clone is finished.

**Comment by folixg** [comment]
@Billy- you're right, it's not in the man page. However when running ```git help clone``` you get the following information about the ```--recursive``` switch:
```       
--recursive, --recurse-submodules
     After the clone is created, initialize all submodules within, using their default settings.
     This is equivalent to running git submodule update --init --recursive immediately after the
     clone is finished. This option is ignored if the cloned repository does not have a
     worktree/checkout (i.e. if any of --no-checkout/-n, --bare, or --mirror is given)
```

**Comment by Billy-** [comment]
@eremit Yeah, `--recurse-submodules` is mentioned in the manpage and is equivalent to running `git submodule update --init --recursive` but that doesn't say anything about the `--recursive` flag being available on `git clone`. It's not that I didn't believe that it worked, just confused by the lack of documentation - I would have thought git would be pretty complete. Thanks for clearing that up @folixg.
