### ISSUE TITLE
command line-theme changed when bad command is typed

### ISSUE THREAD

**Issue by miklasz** [robbyrussell/oh-my-zsh#6183]
hi, i have experiencing small isuue, its not a big deal but i was thinking maybe someone could help me with this, basically when use bad command (example in the picture below) my command line breaks in to different line with missing hostname, then when i use right command its back on again, any one had this issue before ?
Many thanks

Bartosz

p.s. i might do something wrong with the theme but hope someone here may know the answer

![screen shot 2017-07-12 at 11 49 19](https://user-images.githubusercontent.com/12444755/28114450-d8dfe82a-66f8-11e7-90f4-22c3fa56f38c.png)

this is my theme code

`local ret_status="%(?:%{$fg_bold[green]bartron %}%{$FG[141]ツ %}%{$fg_bold[green]➜ :)"`
`PROMPT='%{$fg[red]%T%} ${ret_status} %{$fg[cyan]%}%~%{$reset_color%} $(git_prompt_info)'`

`ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[yellow]%}"`
`ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "`
`ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[red]%}✗"`
`ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"`

**Comment by mcornella** [comment]
You need to fix the `ret_status` line. If all you want is to change the color from green to red, all you have to do is:
```
local ret_status="%{%(?:$fg_bold[green]:$fg[red])%}"
PROMPT='%{$fg[red]%T%} ${ret_status}bartron ➜ %{$fg[cyan]%}...'
```
In other words, just change the color in `ret_status` and put the rest in `PROMPT`.
