### ISSUE TITLE
Issue Management

### ISSUE THREAD

**Issue by sils** [robbyrussell/oh-my-zsh#6200]
Hi,

I'm looking to investigate how other OS projects handle issues "at scale". At [coala](https://coala.io) we have a couple of issues as well in the main repo at a similar scale to yours and we're wondering on how we can manage them as an OS community efficiently.

Is there someone specifically responsible within your team to handle this? How do you approach this problem?

CC @latacz-io

**Comment by mcornella** [comment]
Sorry for the late response. At the moment I'm the only maintainer in charge of triaging issues. We're using [ZenHub](https://zenhub.com) to sort issues into pipelines and have some sort of coherent classification. Email me if you want to discuss further.
