### ISSUE TITLE
How to let history ignore the wrong command

### ISSUE THREAD

**Issue by niubaoshu** [robbyrussell/oh-my-zsh#6201]
➜ src sssssssssssssssssssssss

zsh: command not found: sssssssssssssssssssssss

➜ src history|tail -n 1

1633 sssssssssssssssssssssss
not history ssssssssssssssss

**Comment by eremit** [comment]
[Quick Answer](http://lmgtfy.com/?q=zsh+history+ignore+wrong+commands)
