### ISSUE TITLE
gitfast doesn't have to load the git plugin

### ISSUE THREAD

**Issue by 12425** [robbyrussell/oh-my-zsh#6206]
The gitfast plugin does not depend on the [git plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git), which defines a set of shell aliases. I don't like that many aliases, but I need gitfast. Could you help to prevent gitfast from loading the git plugin? One can always enable it by adding it in `.zshrc`.

**Comment by mcornella** [comment]
#7152 gets rid of it. Try it out and +1 if it works.
