### ISSUE TITLE
Help /.oh-my-zsh/lib/diagnostics.zsh:autoload:56: invalid option(s)

### ISSUE THREAD

**Issue by qichaotang** [robbyrussell/oh-my-zsh#6212]
![image](https://user-images.githubusercontent.com/12878507/28744941-23e3f204-749f-11e7-9ba6-28bfa11668ea.png)

My remote computer can't connect,
computer is centos
This is oh-my-zsh 's question
I should help！！！

**Comment by eremit** [comment]
What ZSH version are you using?
