### ISSUE TITLE
Italic escape codes in theme file not working

### ISSUE THREAD

**Issue by LindseyB** [robbyrussell/oh-my-zsh#6214]
What I have right now in my theme is the following: 

```
PROMPT=$'%{$fg[cyan]%}%1~%{$reset_color%}%{$fg[red]%}|%{$reset_color%}\e[3m$(git_prompt_info)\e[0m%{$fg[cyan]%}⇒%{$reset_color%} '
```
however when I look at the prompt in a repo it looks like: 

![screen shot 2017-07-29 at 10 54 53 pm](https://user-images.githubusercontent.com/33750/28750189-f8204cdc-74b0-11e7-959b-fdc9d1acb18d.png)

Which I would expect if my terminal didn't support italics however: 

![screen shot 2017-07-29 at 10 55 48 pm](https://user-images.githubusercontent.com/33750/28750195-1e9f6ea6-74b1-11e7-90ef-49ac2f486a82.png)

I'm not sure if this is a bug or if I need to adjust something in my .zshrc, but the behavior is definitely not what I expected. 

Any help is greatly appreciated. ❤️

**Comment by Shea690901** [comment]
Have you taken a look at your git_prompt_info?
Not that it resets your italic setting ;)

**Comment by LindseyB** [comment]
Closing this that was my problem @Shea690901 so I moved the italic stuff into ZSH_THEME_GIT_PROMPT_PREFIX
