### ISSUE TITLE
ssh-color

### ISSUE THREAD

**Issue by jakdept** [robbyrussell/oh-my-zsh#6216]
I've written a ssh wrapper that sets a random background color whenever you ssh to a server.

More specifically, it should:

* determines the host and IP that SSH is connecting to
* md5sum that combo
* uses the first 6 places as a hex color code
* change your terminal's title to that host and IP
* change your terminal's background color to that color
* change your terminal's color back to black and title back to "localhost" after SSH is done/on ctrl-c.

It's along the lines of [this guide for macos](http://www.drinchev.com/blog/ssh-and-terminal-background/) or [this one for linux](http://bryangilbert.com/post/etc/term/dynamic-ssh-terminal-background-colors/) - however rather than using a limited number of hosts and picking colors, the colors are picked randomly.

[I've written this in my dotfiles](https://github.com/jakdept/dotfiles/blob/master/zshrc.d/ssh_color.zsh) and I feel like this could be helpful - but:

* I've never submitted to oh-my-zsh and I might need help with guidelines to make sure I don't step on toes. :-)
* I've used sed (regex) and openssl (for md5'ing) directly, and IDK how friendly the community is on using those in a plugin.
* I don't know that I really understand how plugins work... at all.
* I'll need testers anyway.

Should I open a pull request to try to get this submitted? Is there interest in having this in oh-my-zsh?

**Comment by lumbric** [comment]
This is great, thank you! I can't really help you with oh-my-zsh unfortunately. I just was about building something like this for myself and stumbled upon this issue here when googling for existing solutions.

It does not work with xfce4-terminal, but it works great with roxterm.

Three suggestions for additonal options:
- changing color of the prompt instead of background color
- limit color range (e.g. to dark colors only)
- set colors for specific hosts

**Comment by lumbric** [comment]
Replacing `${SSH_BINARY} $*` by `ssh $*` seems to work fine for  me. When/why is this necessary?

**Comment by johndpope** [comment]
not sure this helps - but fyi was running into horror colors and it's possible to fix using iterm. https://github.com/ogham/exa/issues/412

**Comment by mcornella** [comment]
> * I am calling `${SSH_BINARY}` because elsewhere in the script, I should be populating that variable when the functions are first loaded - with:
> 
> ```
> SSH_BINARY=$(type -a ssh|awk '!/alias/ && !/function/ {print $NF}'|head -n1)
> ```

You can use `$commands[ssh]` in zsh, or `type -P ssh` in bash.

To create a plugin you must:
1. Add a folder in `plugins/` with the plugin name (`ssh-color` is a good option).
2. Add a file named `ssh-color.plugin.zsh` inside that function with the code (that would be your `ssh_color.zsh` file.
3. Add a README with a description of what the plugin does and how to enable it.

See the description written in the first message of https://github.com/robbyrussell/oh-my-zsh/issues/7175.

It looks like there is interest in this, so get to it!

**Comment by babbahotep** [comment]
This is awesome, was looking for this for 2 weeks. 
created a folder /custom/plugins/ssh-color/ssh-color.plugin.zsh
the plugins (ssh-color) in .zshrc
works like a charm.
