### ISSUE TITLE
How to make my terminal theme according to the screenshot provided in README.md file

### ISSUE THREAD

**Issue by arifmahmudrana** [robbyrussell/oh-my-zsh#6221]
My problem is straight forward I was looking to make my terminal exactly look like this image https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png provided I have plenty googled & searched & I think this should be documented in README.md file as well.

I am using Ubuntu 16.04 & theme is agnoster but can't make the theme like the screenshot provided in README.md. So a step by step guide would be helpful for the new users.

**Comment by folixg** [comment]
In the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster) you can find the prerequisites.

**Comment by arifmahmudrana** [comment]
Thanks @folixg I got the solution to some extent Here is the solution I am using Ubuntu 16.04

- Install https://github.com/Anthony25/gnome-terminal-colors-solarized
- Install Powerline-patched Menlo https://github.com/abertsch/Menlo-for-Powerline
- set terminal font 
![image](https://user-images.githubusercontent.com/2046796/28919482-86dbeee2-786f-11e7-9a7f-791ff2011714.png)
- then add this lines to your `.zshrc` file
```bash
DEFAULT_USER=$USER
prompt_context() {}
```
& my terminal is like now this 
![image](https://user-images.githubusercontent.com/2046796/28919623-13eb445e-7870-11e7-9b5a-60af4caf5b23.png)
