### ISSUE TITLE
Refined theme removes current directory display

### ISSUE THREAD

**Issue by mscottnelson** [robbyrussell/oh-my-zsh#6222]
@mcornella , when I set my theme to refined, I lose display of the current directory, but there is still a line break for one. Is this intended behavior?

**Comment by BayesZou** [comment]
me too!

**Comment by mcornella** [comment]
I can't reproduce this, maybe you're in the home directory and there's a very faint tilde in its place? I get a very dark blue color over black background, maybe it has something to do with that.
