### ISSUE TITLE
oh-my-zsh is eating newline in prompt on autocomplete with zsh 5.3.x

### ISSUE THREAD

**Issue by luitzifa** [robbyrussell/oh-my-zsh#6226]
Since i upgraded to Fedora 26 i got this strange behavior when pushing TAB for directory completion.
```
[dkraemer@witchhouse:~]
% cd /var/
```
push TAB and the newline disappears
```
[dcd /var/
account/   cache/     db/        ftp/       gopher/    lib/       lock@      mail@      opt/       run@       tmp/                                           
adm/       crash/     empty/     games/     kerberos/  local/     log/       nis/       preserve/  spool/     yp/  
```
If i push ctrl-c in this state even the previous line will be overwritten.

I would expect it to look like this:
```
[dkraemer@witchhouse:~]
% cd /var/
account/   cache/     db/        ftp/       gopher/    lib/       lock@      mail@      opt/       run@       tmp/                                           
adm/       crash/     empty/     games/     kerberos/  local/     log/       nis/       preserve/  spool/     yp/  
```

I use:

- zsh version: 5.3.1
- Theme: kphoen (but all multiline based Themes i tested are affected e.g. aussiegeek)

"Workarounds":

- I compiled zsh 5.1 from source and the bug was gone.
- Surprisingly when i start the same zsh-5.3.1 within zsh-5.3.1 in the same Terminal the bug is gone too.
- I also moved my .zshrc to .zshrc.org and started a clean zsh. I exported a pretty stupid multiline prompt and did not faced the bug.

I also tried to figure out if some different code is executed. To do so i wrote "exec 2>/tmp/x-$$.stderr; set -x" into the first line of my .zshrc and use vimdiff for comparison. But got bloated by different stuff and gave up this approach.

**Comment by eremit** [comment]
I have tried this on a Fedora 26 with the two themes you were mentioning but was not able to reproduce your issue.

**Comment by luitzifa** [comment]
Thank you for your response @eremit 
I'll try a fedora-live with clean ohmyzsh and my config later the day and post my results

**Comment by luitzifa** [comment]
Hey there, i found the Problem. I had `COMPLETION_WAITING_DOTS="true"` in my .zshrc, after comenting it again the strange behavior was gone. I didn't commented it before, because it's was shipped by ohmyzsh-zshrc and uncommenting was suggested. Maybe you should remove the Option?

**Comment by eremit** [comment]
@luitzifa you're right, I can confirm that there is an issue with the ```COMPLETION_WAITING_DOTS``` and combination with multi line based themes.

**Comment by exah** [comment]
Same issue

**Comment by benzrf** [comment]
I am also experiencing this problem. I'm on zsh 5.4.2 and e273cf00.

**Comment by skuxy** [comment]
Hey, I've got the same issue, using zsh 5.3.1 and c3b072e 

Solution that @luitzifa provided has worked for me, so perhaps it really makes sense for that option to be removed?

**Comment by benzrf** [comment]
I should mention: I found that the issue only happens when the first line of the prompt fully fills the width of the terminal; I changed my theme to only go up to the second-to-last column and the problem went away.

**Comment by aniforprez** [comment]
Can confirm this is a problem on my system, not just with multiline themes but all themes. Disabling it and restarting my session fixed the problem

**Comment by krupenja** [comment]
Having this issue with multiline themes only on macOS 10.14.2 (both in iTerm and Terminal) with zsh 5.6.2. Have not seen this on Linux machines.

**Comment by Seminioni** [comment]
Yeah same behaviour on the same specs as @krupenja

**Comment by romkatv** [comment]
There is a bug in zsh that causes completion menu disappear when prompt is redrawn. Anything that calls `zle reset-prompt` will trigger it. See https://www.zsh.org/mla/workers//2019/msg00161.html.

To make matters worse, vi-mode plugin [traps SIGWINCH](https://github.com/robbyrussell/oh-my-zsh/blob/a628b552c47be4e571dcba751ac12d0bf1d14133/plugins/vi-mode/vi-mode.plugin.zsh#L8) and calls `zle reset-prompt` from it. This is useless under normal circumstances and harmful when `reset-prompt` triggers a bug in zsh. vi-mode plugin does this as a bonus of sorts. This trap is unrelated to the plugin's functionality.

**Comment by mcornella** [comment]
Same underlying issue as #5765 and #5767.

**Comment by negebauer** [comment]
I'm having the issue with the prompt eating a line and also with the line being overwritten when going over the width of the terminal. Right before it happens:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/11860880/78415384-c292e480-75f7-11ea-8a07-38f111cdb64a.png">

And after I keep writing

<img width="437" alt="image" src="https://user-images.githubusercontent.com/11860880/78415392-cf173d00-75f7-11ea-8003-f4b5efefa3ce.png">

The line gets replaced visually, but it's a new line, since if a press enter the echo is done correctly

**Comment by negebauer** [comment]
Changing the locale fixed it for me https://github.com/ohmyzsh/ohmyzsh/issues/7558#issuecomment-460812339
