### ISSUE TITLE
Can't find osx plugins

### ISSUE THREAD

**Issue by JamesHopbourn** [robbyrussell/oh-my-zsh#6229]
![screen shot 2017-08-06 at 10 06 48](https://user-images.githubusercontent.com/18232831/28999990-3e6ae86c-7a8f-11e7-80dc-080b3316a786.png)
I try to source .zshrc,but zsh told me:/Users/spark/.oh-my-zsh/plugins/osx/osx.plugin.zsh:178: command not found: compdef.How to solve the problem?

**Comment by eremit** [comment]
Is this you're entire ```.zshrc```?
If so, is there a specific reason why you did not source ```$ZSH/oh-my-zsh.sh```?
Futhermore, if using ZSH you do not have to source the plugins explicitly, but use the ```plugins``` list.

On that note, ```zsh-syntax-highlighting``` must be listed as the last item in your plugins list, or if you explicitly source it the last script to source in your .zshrc.

**Comment by mcornella** [comment]
As @eremit says, your zshrc file is wrong. You don't need to manually source plugins, you just define the `plugins` array and then source `$ZSH/oh-my-zsh.sh`.

**Comment by ShaohanTian** [comment]
I met this question too, how did you deal with it?

<img width="458" alt="image" src="https://user-images.githubusercontent.com/58108746/204139713-0de19d97-bde1-45d7-a443-a96f96da90cf.png">

**Comment by ShaohanTian** [comment]
@JamesHopbourn

**Comment by mcornella** [comment]
`osx` plugin was renamed to `macos` long ago. See the wiki or `omz plugin list` for the list of valid plugin names.
