### ISSUE TITLE
Some parse error?!

### ISSUE THREAD

**Issue by kaymio** [robbyrussell/oh-my-zsh#6237]
It doesn't matter which (virtual) TTY I'm opening I always get these as the first lines:

/home/X/.oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh:19: defining function based on alias `man'
/home/X/.oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh:19: parse error near `()'
/home/X/.oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh:19: defining function based on alias `man'
/home/X/.oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh:19: parse error near `()'

but everything is working.

**Comment by terencode** [comment]
Having the same problem on Arch Linux after upgrading to zsh 5.4.1

**Comment by toto-42** [comment]
Wouldn't it be better to change "man ()" to "function man()" in 'colored-man-pages.plugin.zsh'?

IHMO this is better than to force users to change back globally to an old, non default behavior considered error prone by the zsh development team.

**Comment by marcelsiegert** [comment]
@toto-42 Yep, you're probably right. I updated my pull request.

**Comment by kaymio** [comment]
When can we expect a fix for this? Or could you provide a quick fix?

**Comment by terencode** [comment]
@kaymio: navigate to *usr/share/oh-my-zsh/plugins/colored-man-pages* then edit *colored-man-pages.plugin.zsh* by adding "function" before "man()" and you're done.
Credits to @marcelsiegert .

**Comment by kaymio** [comment]
Thank you very much @marcelsiegert !

**Comment by Zerophase** [comment]
Shouldn't the `()` be removed from the function. According to this it's only supported syntax from a bug. https://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo
