### ISSUE TITLE
code completion can't work when i input sudo

### ISSUE THREAD

**Issue by LynnShaw** [robbyrussell/oh-my-zsh#6248]
![image](https://user-images.githubusercontent.com/11351097/29367477-9c1d630c-82cf-11e7-8ded-13185119ec62.png)

I use Ubuntu17.04

**Comment by NanerLee** [comment]
+1, it like this issue #5949

**Comment by mcornella** [comment]
Reopen if this still happens and post the output of `which -a sudo $_comps[sudo] $_comps[apt]`.
