### ISSUE TITLE
Python upgrade breaks pip plugin alias

### ISSUE THREAD

**Issue by Dru89** [robbyrussell/oh-my-zsh#6254]
So with the recent upgrade of python on Homebrew, I'm now running into an issue where `pip` doesn't exist anymore.  Only `pip2`, `pip2.7`, `pip3`, and `pip3.6`.

I'm thinking that we should probably change this alias, but I'm not sure to what:
https://github.com/robbyrussell/oh-my-zsh/blob/d848c94804918138375041a9f800f401bec12068/plugins/pip/pip.plugin.zsh#L80

Easiest thing to do here would be to just make this an alias like `alias pip="noglob pip2"`.  But maybe we should have `pip2` and `pip3` plugins instead?

**Comment by Shea690901** [comment]
how about either using a vatiable `alias pip="noglob pip${SOME_VARIABLE}"` or just creating a symlink for the prefered version?

**Comment by mcornella** [comment]
That seems to be an installation error since [the documentation](https://docs.brew.sh/Homebrew-and-Python#python-3x-or-python-2x) and [this issue](https://github.com/Homebrew/homebrew-core/issues/4174) indicate that `pip` should be defined.
