### ISSUE TITLE
Pasting into terminal emulator results in dumped core

### ISSUE THREAD

**Issue by bin101** [robbyrussell/oh-my-zsh#6255]
zsh version: 5.4.1-1 (archlinux package)
oh-my-zsh commit: d848c94
terminal emulator: termite v12

If I want to paste something into my terminal emulator I get a dumped core.
Without oh-my-zsh I have no problems and the template "zshrc.zsh-template" also generates a dumped core.

systemd-coredump[17617]: Process 17391 (zsh) of user 1000 dumped core.
                                              
                                              Stack trace of thread 17391:
                                              #0  0x00007f5d0354fe74 zle_setline (zle.so)
                                              #1  0x00007f5d03570baf n/a (zle.so)
                                              #2  0x00007f5d035719d9 undo (zle.so)
                                              #3  0x00007f5d03557e30 execzlefunc (zle.so)
                                              #4  0x00007f5d03567f89 n/a (zle.so)
                                              #5  0x000000a61cd48b3f execbuiltin (zsh)
                                              #6  0x000000a61cd57c1a n/a (zsh)
                                              #7  0x000000a61cd5865a n/a (zsh)
                                              #8  0x000000a61cd58a42 n/a (zsh)
                                              #9  0x000000a61cd5a2c8 execlist (zsh)
                                              #10 0x000000a61cd801e8 execif (zsh)
                                              #11 0x000000a61cd56fa0 n/a (zsh)
                                              #12 0x000000a61cd5865a n/a (zsh)
                                              #13 0x000000a61cd58a42 n/a (zsh)
                                              #14 0x000000a61cd5a2c8 execlist (zsh)
                                              #15 0x000000a61cd5a85b execode (zsh)
                                              #16 0x000000a61cd5b5ec runshfunc (zsh)
                                              #17 0x000000a61cd5c086 doshfunc (zsh)
                                              #18 0x000000a61cd5c470 n/a (zsh)
                                              #19 0x000000a61cd57c8f n/a (zsh)
                                              #20 0x000000a61cd5865a n/a (zsh)
                                              #21 0x000000a61cd58a42 n/a (zsh)
                                              #22 0x000000a61cd5a2c8 execlist (zsh)
                                              #23 0x000000a61cd801e8 execif (zsh)
                                              #24 0x000000a61cd56fa0 n/a (zsh)
                                              #25 0x000000a61cd5865a n/a (zsh)
                                              #26 0x000000a61cd58a42 n/a (zsh)
                                              #27 0x000000a61cd5a2c8 execlist (zsh)
                                              #28 0x000000a61cd5a85b execode (zsh)
                                              #29 0x000000a61cd5a9f1 n/a (zsh)
                                              #30 0x000000a61cd57a43 n/a (zsh)
                                              #31 0x000000a61cd5865a n/a (zsh)
                                              #32 0x000000a61cd58a42 n/a (zsh)
                                              #33 0x000000a61cd5a2c8 execlist (zsh)
                                              #34 0x000000a61cd5a85b execode (zsh)
                                              #35 0x000000a61cd5b5ec runshfunc (zsh)
                                              #36 0x000000a61cd5c086 doshfunc (zsh)
                                              #37 0x00007f5d03557b3e execzlefunc (zle.so)
                                              #38 0x00007f5d0355852f zlecore (zle.so)
                                              #39 0x00007f5d03559409 zleread (zle.so)
                                              #40 0x000000a61cd72bf4 zleentry (zsh)
                                              #41 0x000000a61cd741b8 n/a (zsh)
                                              #42 0x000000a61cd6bc5c n/a (zsh)
                                              #43 0x000000a61cd7d9cc n/a (zsh)
                                              #44 0x000000a61cd9cb77 parse_event (zsh)
                                              #45 0x000000a61cd6f4b5 loop (zsh)
                                              #46 0x000000a61cd732d6 zsh_main (zsh)
                                              #47 0x00007f5d042fe4ca __libc_start_main (libc.so.6)
                                              #48 0x000000a61cd398ba _start (zsh)

**Comment by AndreFlakowski** [comment]
Have the same Issue zsh 5.4.1 x86_64 on arch.
I narrowed it down to a block where i source my environment from my .zsrhc e.g.:

```
.zshrc:
[...]
source /opt/env/path
```

```
#! /bin/zsh
setopt allexport
PATH=$PATH:$LOCALENV/bin
```
If i disable `setopt allexport` it works. But it is unrelated to oh-my-zsh. i reproduced it with a clean .zshrc as well.

**Comment by bin101** [comment]
I think this is OMZ related, because if I use setopt allexport with a pure zsh installation I dont get this Issue.

**Comment by shosca** [comment]
The issue is here https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/misc.zsh#L3-L16

I can get around this by setting `ZSH_CUSTOM` with a custom `lib/misc.zsh` that doesn't have that code.

**Comment by mcornella** [comment]
What zsh version are you using? @shosca are you using `setopt allexport` as well?

**Comment by shosca** [comment]
Tried it on a out of the box setup and i was able to get it running with overriding `misc.zsh`

My actual config is here: https://github.com/shosca/dotfiles/blob/master/zshrc

**Comment by mcornella** [comment]
After the latest update (run `upgrade_oh_my_zsh`), you can add `DISABLE_MAGIC_FUNCTIONS=true` to your zshrc (before OMZ is sourced) to bypass the loading of the magic functions.
