### ISSUE TITLE
Additional Output in command prompt

### ISSUE THREAD

**Issue by rafee** [robbyrussell/oh-my-zsh#6256]
In zsh shell, I am having the following issue. After I press a command in command prompt, it is repeated in second line and also there's an ineligible character as well.
![screenshot from 2017-08-18 13-17-46](https://user-images.githubusercontent.com/3380056/29462498-66a62848-8451-11e7-9d41-2bce32d614d1.png)
I am using Guake, if that helps. Although the issue persists in other terminals as well

**Comment by mcornella** [comment]
Reopen if this still happens and provide your zshrc file.
