### ISSUE TITLE
Add new git Alias

### ISSUE THREAD

**Issue by greenchapter** [robbyrussell/oh-my-zsh#6266]
Is it possible to add a new git alias to the git plugin?

It want to add this alias

`alias gdh='git diff HEAD'`

**Comment by abbyfleming** [comment]
Sure! Aliases can be added to the bottom of your .zshrc file. 

<img width="615" alt="bottom of .zshrc file" src="https://user-images.githubusercontent.com/22598014/29737561-98672c90-89d5-11e7-84ad-07244498eadf.png">

**Comment by greenchapter** [comment]
Yes, I know that but I think it is for everyone a good alias.
For a couple of days a opened a pull request with this new alias https://github.com/robbyrussell/oh-my-zsh/pull/6267 maybe someone will merge this improvement.

**Comment by mcornella** [comment]
`git diff` already defaults to using HEAD.
