### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by ieee8023** [robbyrussell/oh-my-zsh#6278]
Hello, Can this project be added to Homebrew (http://brew.sh)?

I want to use this project but I don't like to run code that has not been reviewed by the brew community.

**Comment by nitrocode** [comment]
Yes. I'd love to see this added to home brew. I work on a lot of different machines and adding this to my [Brewfile](https://github.com/nitrocode/dotfiles/blob/master/macos/Brewfile) would save me a lot of time.

**Comment by Jens0512** [comment]
Came here to open an issue on this

+1

**Comment by mcornella** [comment]
I don't think Homebrew can bundle OMZ since we don't do releases. And the project is self-updating, so the code will always be changing. Nevertheless, this is not the place to petition that.
