### ISSUE TITLE
Is there a way to install ZSH 5.0.5 on Ubuntu 14.04?

### ISSUE THREAD

**Issue by ilyador** [robbyrussell/oh-my-zsh#6294]
The latest version available is 5.0.2
(I am using Bash on Windows)

**Comment by folixg** [comment]
ZSH 5.0.5 is available in the [trusty-backports repository](https://packages.ubuntu.com/trusty-backports/zsh).
By the way, your question is not related to oh-my-zsh, therefore [askubuntu.com](https://askubuntu.com/) would have been the better place to ask it.
