### ISSUE TITLE
Uninstalling oh my zsh does NOT restore previous default shell

### ISSUE THREAD

**Issue by olleharstedt** [robbyrussell/oh-my-zsh#6299]
As title. Please fix your $#@!@#$ uninstall script, and excuse my language.

Running Xubuntu 14.10.

**Comment by itkasumy** [comment]
zsh is a shit

**Comment by mcornella** [comment]
Hi there, #5169 introduces changes from #6356 and #6608 that fix this. It should now work correctly after it has been installed with the newer version, or show a better error message when it doesn't.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by mcornella** [comment]
Closed by #5169.
