### ISSUE TITLE
oh-my-zsh

### ISSUE THREAD

**Issue by Abinayasandhiya** [robbyrussell/oh-my-zsh#6306]
Hi,

while running ./install.sh script on my home its not creating any .oh-my-zsh folder.
Please let me know then, to install oh-my-zsh on our host is that need any sudo permission.

Regards,
Abinaya

**Comment by robbyrussell** [comment]
@Abinayasandhiya  you shouldn't need sudo access to install Oh My Zsh.

**Comment by Abinayasandhiya** [comment]
Hi Robby, Thanks for the update:)
