### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gigi206** [robbyrussell/oh-my-zsh#6307]
Hello,

I have installed oh-my-zsh and I wonder how to change this behaviour :
- Ctrl-w (^W) don't erase option  **--** or **-**. Exemple **_ls --human-readable -l_** erase just letter **l**or **human-readable** without **-** and **--**.
- up arrow must always rewind the previous history (not the case if I have already put something on the sreen). Only true if the prompt is empty.

By advance thank for your help :)

**Comment by gigi206** [comment]
I have found :

- Ctrl-w :
```
autoload -U select-word-style
select-word-style bash
bindkey '^W' backward-kill-word
autoload -U backward-kill-word-match
zle -N backward-kill-word backward-kill-word-match
zstyle ':zle:backward-kill-word' word-style whitespace-subword
```
- up/down arrow : (https://github.com/zsh-users/zsh-history-substring-search)
```
bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down
```

- Ctrl-u : 
`bindkey '^u' backward-kill-line`

**Comment by hieu-van** [comment]
Here's my another solution (based on that of @gigi206):
```
autoload -U select-word-style
select-word-style whitespace
autoload -U backward-kill-word-match
zle -N backward-kill-word backward-kill-word-match

bindkey \^U backward-kill-line
```
