### ISSUE TITLE
If $EDITOR is defined as GVIM the vi-mode doesn't work properly

### ISSUE THREAD

**Issue by MaikoID** [robbyrussell/oh-my-zsh#6312]
Hi guys, I'm having this problem where if my $EDITOR variable is defined as GVIM the vi-mode doesn't work properly, it does fire GVIM but without any previous text and any text entered in GVIM is not returned back to ZSH command line.

If I change $EDITOR back to vim, it works just fine. Any thoughts?

BR

**Comment by Marcholio** [comment]
Hi, is this still an issue with the current version?

**Comment by mcornella** [comment]
This is probably the same issue as #5210. Look at your zsh version, and if not, reopen the issue.
