### ISSUE TITLE
Serious question: Is oh-my-zsh development dead?

### ISSUE THREAD

**Issue by mbgearhead** [robbyrussell/oh-my-zsh#6313]
I religiously upgrade my oh-my-zsh using the "upgrade_oh_my_zsh" command. Having now noticed that no updates have been pushed in quite some time, I decided to drop by here to see what's going on. Indeed there has not been a commit in three months. Just wanted to check in to see if the community needs to pitch in time or money to jump-start this project again (I'm a huge fan!!).

**Comment by robbyrussell** [comment]
This is a good question. I'm, personally, taking a bit of a break while I focus on a few other projects (i.e., my business and band). Unless there are any critical bugs that need to be squashed, I'm planning to hold off on many updates until our autumn/winter really sit in and I can spend some nice indoor time helping moving things forward.

...at least...that's the plan. :-)

**Comment by mbgearhead** [comment]
Good luck with ramping up your business and your band! Looking forward to the next round of updates this winter :)
