### ISSUE TITLE
fasd plugin: 'open_command: not found'

### ISSUE THREAD

**Issue by ricpelo** [robbyrussell/oh-my-zsh#6314]
Using the fasd plugin I get the following:

```sh
$ o
6       12         /home/ricardo/.oh-my-zsh/cache/fasd-init-cache
5       15         /home/ricardo/.oh-my-zsh
4       15         /home/ricardo/.oh-my-zsh/plugins/fasd/fasd.plugin.zsh
3       17.4       /home/ricardo/.oh-my-zsh/plugins
2       21.3181    /home/ricardo/conf
1       23.0068    /home/ricardo/.oh-my-zsh/plugins/fasd
$ o conf  
/usr/bin/fasd: 619: /usr/bin/fasd: open_command: not found
$ o fasd
/usr/bin/fasd: 619: /usr/bin/fasd: open_command: not found
$ o plugin
/usr/bin/fasd: 619: /usr/bin/fasd: open_command: not found
$ o plugin.zsh
/usr/bin/fasd: 619: /usr/bin/fasd: open_command: not found
```

**Comment by folixg** [comment]
It seems that `fasd` is running in a subshell, where it cannot access the function `open_command`, which is defined in [functions.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/functions.zsh). 
While I don't know, how to fix this, I can provide a workaround:
1. Copy the folder `$ZSH/plugins/fasd` to `$ZSH/custom/plugins/fasd` 
2. Open `$ZSH/custom/plugins/fasd/fasd.plugin.zsh`
3. Change the alias for `o` to `alias o='a -e xdg-open'`
