### ISSUE TITLE
Shrink_path fails when opening a directory that contains $HOME

### ISSUE THREAD

**Issue by abarisain** [robbyrussell/oh-my-zsh#6317]
When tilde is enabled, shrink_path will throw a lot of `shrink_path:cd:88: no such file or directory` if part of your path contains $HOME (such as mounting your old home in another folder)

It will also show a tilde right in the middle of the path.  

I believe that this could be fixed by tweaking this regexp to only match the beginning of the screen: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/shrink-path/shrink-path.plugin.zsh#L94

**Comment by mcornella** [comment]
Thanks for the thorough bug report, I've pushed a fix.
