### ISSUE TITLE
On Mac OS 10.13, there is a bug with zsh theme "agnoster"

### ISSUE THREAD

**Issue by wangxiaodong1021** [robbyrussell/oh-my-zsh#6319]
On Mac OS 10.13, there is a bug with zsh theme "agnoster".
When using this theme, My iTerm2 become very slow.

**Comment by tomasnorre** [comment]
@wangxiaodong1021 I think more information is needed, to be able to help you out here. 

Have you any measurements?
In which cases are the iTerm2 slower? 
Which plugins do you have loaded? 
Is it also slow will all plugins disabled ?

Etc.

Please provide more information.

**Comment by wangxiaodong1021** [comment]
Well, I solved this problem by modifying the theme for `ZSH_THEME = "robbyrussell"`.
Each time iTerm2 or Terminal opens and executes each command, the entire console waits for a few minutes to continue. In this process, I can monitor a background of the Python process takes up a lot of computing resources.

**Comment by tomasnorre** [comment]
Hmm. That sounds strange.. I have issues with time, when switching from cabled network to wifi or other way around, but that's due to DNS-Lookup issue on Terminal Start, I don't think that has anything to do with the Theme.

**Comment by wangxiaodong1021** [comment]
@tomasnorre  Perhaps because this zsh theme  **"agnoster"** calls the complex library, and then these calls are not compatible in the new version of the system.

**Comment by tomasnorre** [comment]
Can be, cannot answer that, I use that theme too, but rarely have any problems.

**Comment by mcornella** [comment]
You could be in a git or hg repository. If you run `set -xv` you will see a trace of the commands being run when printing the prompt; the last command where it hangs could be the key to solving it. Post the output you get and where it hangs. To disable this debug mode run `set +xv`.

**Comment by wangxiaodong1021** [comment]
I have solved this bug by upgrade Python.

**Comment by tomasnorre** [comment]
@wangxiaodong1021 From which version to which version did you update ?
