### ISSUE TITLE
Ridiculously slow pasting with bracketed-paste-magic

### ISSUE THREAD

**Issue by samphilipd** [robbyrussell/oh-my-zsh#6338]
It takes two minutes to paste 100kb of text with bracketed-paste-magic enabled.

Without it, it takes two seconds.

There is no way to disable this in oh-my-zsh by default, can it be made optional?

**Comment by Margular** [comment]
I can't use this magic in zsh 5.4.2!!! I have to disable it.It seems have a same bug at old version of zsh?but now it comes out again!

**Comment by ronjouch** [comment]
@samphilipd @Margular see discussion and disabling workaround at https://github.com/robbyrussell/oh-my-zsh/issues/5569

**Comment by mcornella** [comment]
After the latest update (run `upgrade_oh_my_zsh`), you can add `DISABLE_MAGIC_FUNCTIONS=true` to your zshrc (before OMZ is sourced) to bypass the loading of these functions.
