### ISSUE TITLE
Which Laravel plugin(s) do we use?

### ISSUE THREAD

**Issue by WadeShuler** [robbyrussell/oh-my-zsh#6343]
There isn't a README in the Laravel plugin dirs. I am using Laravel 5 (latest), so I have no need for older versions. I only need Laravel 5 support.

Do we install only the `laravel5` plugin? Or is the `laravel` plugin the main plugin and `laravel5` is an addon to that plugin to give the version 5 support to it (ie: install both)?

**Comment by WadeShuler** [comment]
Wow, over 400 issues... Is this repo dead? Is Oh-My-ZSH still the one to use, or is there a new bash shell everyone jumped to?

**Comment by cdarken** [comment]
@WadeShuler I use laravel5 plugin. It's been updated recently, but I think there's an issue with the autocompletions. The compdef function is called before the alias is defined and it's not working, I fixed it by moving `compdef _laravel5 la5` line just after the line where the alias is defined

**Comment by mcornella** [comment]
The laravel plugin only adds aliases, while the other ones add completion specific to the Laravel version. In the future we should merge them and have a single one, but in the meantime use whichever you prefer, knowing what they provide. We have READMEs for all of them now.
