### ISSUE TITLE
pass autocompletion: append slash when applicable

### ISSUE THREAD

**Issue by woutgg** [robbyrussell/oh-my-zsh#6347]
When autocompleting file system paths in Zsh, a slash (`/`) is appended automatically so you can immediately continue typing the next path component.

When using `pass edit` with hierarchically stored items in pass, the slash has to be added manually. This reduces the amount of time/effort saved by the autocompletion feature.

It would be nice if this feature could be added. (If time permits I'll look into this myself.)

(If I understand correctly, I should also mention the plugin maintainer, @sanbor here.)

**Comment by mcornella** [comment]
Try [`setopt AUTO_PARAM_SLASH`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-AUTOPARAMSLASH)? If that doesn't work try asking in the [password-store mailing list](https://lists.zx2c4.com/mailman/listinfo/password-store).
