### ISSUE TITLE
Oh my zsh is getting stuck

### ISSUE THREAD

**Issue by kadnan** [robbyrussell/oh-my-zsh#6349]
Since I am having issue that it's taking time to return command response. I am using Mac and this is the screenshot of the process it is running:

<img width="265" alt="screen shot 2017-10-10 at 4 30 49 pm" src="https://user-images.githubusercontent.com/273196/31388639-14971b3c-ade8-11e7-9997-334a586998d3.png">

**Comment by mcornella** [comment]
Reopen if this issue persists, and run `zsh -xv` to enable debug mode so as to see the exact instruction where zsh hangs.
