### ISSUE TITLE
Complex statements tend to lose characters

### ISSUE THREAD

**Issue by freysteinn** [robbyrussell/oh-my-zsh#6358]
Hi all.

Sometimes when I am working on complex one liners that I need to change, then they lose part of the statement.
I am able to reproduce the problem on some, but not all computers that I have running zsh with oh-my-zsh.

Here is an example, but don't think about what the one liner is doing, nor how you can improve it:

> echo pdfjam $(ls ../pdfs | sort -t t -k 2 -h) $(ls ../ivan | sort -t t -k 2 -h) --nup 2x1 --landscape --outfile out.pdf

Now if you move the cursor to the end of the first -h of the later sort, and add a space, pipe, space, then we end up with this:
> echo pdfjam $(ls ../pdfs | sort -t t -k 2 -h) $(ls ../ivan | sort -t t -k 2 -h | )
Notice how the "--nup 2x1 --landscape --outfile" has now disappeared, just like the hair on my head.

Best wishes
Frey Alfredsson

**Comment by Shea690901** [comment]
Have you by chance executed the first command, then called it back from history and started editing **that** line?
If that´s the casse you should check **all** options and variables concerning history handling and that´s beside those concerning line editing,,,

**Comment by freysteinn** [comment]
Hi Shea690901.

No, I just copy paste the line into my command line and edit it to reproduce it.
This often happens while I am writing commands.

I'm running oh-my-zsh on zsh 5.3.1 (x86_64-redhat-linux-gnu) on Fedora 26.

**Comment by Shea690901** [comment]
Hmm....
What happens when from the described situation you **jump** to the end of line and then **move** a few characters back? Delete a few characzers (either backward or forward)?
Are you where you **expect** to be (read: nothing vanished from eol) or are you where you **see** to be?
I seem to remember that I once had a few problems with my termcap/terminfo which resulted in similar symptoms, although in truth the only change to the line was my editing and not what I got to see...

**Comment by freysteinn** [comment]
Hi Shea690901.
I've had that happen to me too, and that's easily fixable by running the "reset" command. Here the command loses the characters. I'm not able to see them, nor are they available when I try to run the command by pressing enter.

**Comment by Shea690901** [comment]
OK (or not...)
While in my case it wasn´t resolved via `reset` but was a problem with my termcap database, I´m sadly out of ideas :(

**Comment by wrecklass** [comment]
What terminal software? rxvt? Seems to be something not wrapping lines perhaps when they go past the end of the terminal columns value.

**Comment by freysteinn** [comment]
I was using Gnome-Terminal on Fedora 25, 26, and 27. This behavior happens locally, but not when I ssh into a Ubuntu server with the same oh-my-zsh, but it does happen RHEL 7.2 and 7.3 servers with same same copy.

**Comment by mcornella** [comment]
This looks to me like an issue within zsh's line editor (zle). Try to compile a list of zsh versions in which this happens to see if there's a pattern.

**Comment by freysteinn** [comment]
This is not an issue in 5.5.1 (x86_64-redhat-linux-gnu) on Fedora 28.
