### ISSUE TITLE
systemctl enable  complete very slow

### ISSUE THREAD

**Issue by heelsleeh** [robbyrussell/oh-my-zsh#6380]
**issue**
when i type "systemctl enable/staus/disable/start"  then i type such as "ma"(mariadb should show)
but when i input 'm' or 'ma' or 'mari" and hit TAB twice zsh not respond over serveral seconds,
**ENV**
zsh 5.2
.zshrc is ohmyzsh default configure.

**Comment by mcornella** [comment]
OMZ doesn't provide systemd completion, that's a zsh issue. Try asking in the [zsh mailing list](http://zsh.org/mla).
