### ISSUE TITLE
Update to wd causing shell problems

### ISSUE THREAD

**Issue by runofthemill** [robbyrussell/oh-my-zsh#6382]
I believe related to #6371 - after updating Oh My Zsh this morning, running `wd <warppoint>` produces output similar to the following:

```
preexec:1: command not found: date
/Users/<username>/.oh-my-zsh/plugins/wd/wd.sh:382: command not found: getopt
wd_print_usage:2: command not found: cat
prompt_status:10: command not found: wc
context:1: command not found: whoami
```

Here's the output of some generic commands after the error, in the same shell session:

```
$ echo $?
preexec:1: command not found: date
0
prompt_status:10: command not found: wc
context:1: command not found: whoami

$ cd /home
preexec:1: command not found: date
_per-directory-history-change-directory:2: command not found: mkdir
_per-directory-history-change-directory:8: command not found: mkdir
prompt_status:10: command not found: wc
context:1: command not found: whoami

$ ls -al
preexec:1: command not found: date
zsh: command not found: ls
prompt_status:10: command not found: wc
context:1: command not found: whoami
```

Starting a new session eliminates the errors until running `wd <warppoint>` again. I isolated by updating Oh My Zsh to `head` and running `git revert 2102d10896fe14e912ed6ed8075bb0ddd3a5bc6a`, after which opening a new shell session allowed me to use `wd` without trouble.

**Comment by hhxsv5** [comment]
Me, too

`git revert 2102d10896fe14e912ed6ed8075bb0ddd3a5bc6a` fixed temporarily

**Comment by nasser-embedded** [comment]
Me, too!

**Comment by kikeonline** [comment]
Same here. revert fixed temporarily.

**Comment by nntoan** [comment]
Hello guys, I found the solution. Just simply remove everything insdie `~/.oh-my.zsh/cache/`. Then run `src` (command from plugin `zsh_reload`)

And we allow to use the lastest version of .oh-my-zsh :)

**Comment by rennerDa** [comment]
I updated oh-my-zsh manually and it seems to work again (master branch). Maybe they fixed it allready.
