### ISSUE TITLE
Rails rg alias conflicts with ripgrep

### ISSUE THREAD

**Issue by aselder** [robbyrussell/oh-my-zsh#6385]
Perhaps we might want to change the `rails generate` alias in the rails plugin to something other than `rg`, since that conflicts with the executable for ripgrep

**Comment by hvenables** [comment]
Ripgrep offers various solutions here [#638](https://github.com/BurntSushi/ripgrep/pull/638/files)

**Comment by mcornella** [comment]
As I said in #6972, you can use `unalias rg` and put it in your zshrc file for the moment. If there is more user demand we'll rename the alias.

**Comment by mbologna** [comment]
Please change the alias from the rails plugin to something that not clashes with ripgrep

**Comment by dimensi0n** [comment]
What do you want for alias @mbologna ?

**Comment by mbologna** [comment]
Anything that does not clashes with ‘rg’.
“rgen” sounds like a good alternative.

**Comment by mertingen** [comment]
Hey, I did take it up. According to the demand, I've changed that alias.
