### ISSUE TITLE
Opening iTerm with zsh is troublesome always !

### ISSUE THREAD

**Issue by nimmoadam** [robbyrussell/oh-my-zsh#6386]
Whenever I open up iTerm (+zsh), I see this error. I have been facing this issue for a long time now & unable to find the root cause to resolve this completely. 

```
/Users/Nirmal/.oh-my-zsh/oh-my-zsh.sh:3: command not found: env
env_default:1: command not found: env
env_default:1: command not found: grep
env_default:1: command not found: env
env_default:1: command not found: grep
compdump:136: command not found: mv
/usr/local/Bluemix/bx/zsh_autocomplete:7: command not found: dirname
/usr/local/Bluemix/bx/zsh_autocomplete:source:8: no such file or directory: /bash_autocomplete
prompt_status:10: command not found: wc
context:1: command not found: whoami
```

After I open my terminal, I export bin.

```
$ export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"
preexec:1: command not found: date

```

but it again shows some command not found.

Can someone help in resolving this issue? 

Basically, when I open up the terminal, I should be able to continue to work without exporting any Path.
Thanks

**Comment by chrsjhnsn** [comment]
Hey, did you resolve this? I'm also getting `compdump:136: command not found: mv` when using zsh and iterm.

**Comment by mcornella** [comment]
You probably have a wrong `$PATH` definition in your zshrc file. What are the contents?

**Comment by chrsjhnsn** [comment]
Fixed it pretty quickly after commenting by adding this near the top of my
.zshrc

`export
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"`

**Comment by chrsjhnsn** [comment]
Fixed it pretty quickly after commenting by adding this near the top of my
.zshrc

```
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
```

**Comment by mcornella** [comment]
Thanks for the confirmation.
