### ISSUE TITLE
parse error near `||'

### ISSUE THREAD

**Issue by ducreuxr** [robbyrussell/oh-my-zsh#6387]
After last zsh update on Ubuntu, I got the following error message:
`parse error near ||`
This was caused by the presence of ^M characters in ~/.oh-my-zsh/oh-my-zsh.sh script.
This is how i fixed it:
`sed -i -e 's/\r$//' ~/.oh-my-zsh/oh-my-zsh.sh`

**Comment by wederer** [comment]
I had additional errors in other files after running your command.
To fix all issues just run: `find ~/.oh-my-zsh/ -type f -print0 | xargs -0 sed -i -e 's/\r$//'`

**Comment by mcornella** [comment]
Be sure to deactivate git-config's `core.autocrlf` on Windows, at least at a repository level, so that when git does a checkout it uses LF endings.
