### ISSUE TITLE
closing zsh with oh my zsh kills all child processes created with `&`

### ISSUE THREAD

**Issue by fxfactorial** [robbyrussell/oh-my-zsh#6389]
I just switched from zpresto to oh-my-zsh, now when I start a child process, say: `$ emacs &` and then `^D`, I get the message: `zsh: you have running jobs.`, if I do it again then zsh will close and emacs stops. 

I didn't have this before. 

`zsh 5.3 (x86_64-apple-darwin17.0)`

**Comment by ramaganapa** [comment]
If i am not wrong it is functionality of nohung up to make application ignore the HUP signal.
So try `nohup emacs &`

**Comment by mcornella** [comment]
You can also `disown` a started job with `disown %n` where n is the job number shown in `jobs`. This is zsh behavior though, I can't see how or why prezto would behave differently.
