### ISSUE TITLE
apt autocomplete does not show all options

### ISSUE THREAD

**Issue by luator** [robbyrussell/oh-my-zsh#6392]
Tab-completion for the `apt` command is in general working for me (i.e. I do not have the problem reported in #5949), but not for all options. That is there are several options which can be tab-completed in bash but not in zsh:

**zsh:**

    % apt <tab>
    edit-sources  install       remove        show          upgrade                                           
    full-upgrade  list          search        update  

**bash:**

    $ apt <tab>
    autoclean     changelog     dist-upgrade  full-upgrade  list          purge         search        source
    autoremove    clean         download      help          moo           rdepends      show          update
    build-dep     depends       edit-sources  install       policy        remove        showsrc       upgrade

In case it is relevant: I am using Ubuntu 16.04

**Comment by mbgearhead** [comment]
Also on 16.04. I can confirm that this is correct. The (now deprecated) apt-get has complete completions. I may work on this and post a gist to this issue for review.

**Comment by luigiwerzowa** [comment]
I am having the same issue on 16.04. Any news?

**Comment by djelenc** [comment]
Same here :/

**Comment by linkp** [comment]
Just discovered this issue because I can no longer tab complete 'apt list --upgradeable' after switching from bash to zsh with oh-my-zsh. 'apt list' will tab complete, but the '--upgradeable' portion no longer works. I use this almost every day, so it's a bit disruptive to say the least.

I'm also on Ubuntu 16.04.

**Comment by yn4v4s** [comment]
I use 'apt list --upgradeable' a lot every day. I have the same issue :/

**Comment by Jamie-505** [comment]
+1

**Comment by luator** [comment]
When someone can give me a hint on where the responsible code is located, I can try to fix it. I was already searching a bit but did not find anything that seemed to be related to `apt` completion.

**Comment by mcornella** [comment]
The completion for the `apt` command is provided by the official zsh setup. You can try asking for better completions at the [zsh-users mailing list](https://www.zsh.org/mla/).
