### ISSUE TITLE
complete:97: command not found: compdef -- issue with nvm + zsh? 

### ISSUE THREAD

**Issue by jcollum** [robbyrussell/oh-my-zsh#6394]
Related thread https://github.com/robbyrussell/oh-my-zsh/issues/3356 -- solutions did not solve the issue. 

```
Loading ~./profile
complete:97: command not found: compdef
➜  ~ git:(master) zsh --version
zsh 5.4.1 (x86_64-apple-darwin15.6.0)
➜  ~ git:(master) compaudit | xargs -I '%' chmod g-w '%'
➜  ~ git:(master) compaudit | xargs -I '%' chown $USER:$USER '%'
➜  ~ git:(master) rm ~/.zcompdump*
➜  ~ git:(master) exec zsh

Loading ~./profile
bashcompinit:75: parse error near `('
/Users/r631947/.nvm/bash_completion:97: command not found: complete
➜  ~ git:(master) reload
Reloading...
Loading ~./profile
bashcompinit:75: parse error near `('
➜  ~ git:(master) zsh --version
zsh 5.4.1 (x86_64-apple-darwin15.6.0)
➜  ~ git:(master) 
```

OK `parse error near ``('` made me concerned so I killed the window and started over. Result: 

```
Loading ~./profile
complete:97: command not found: compdef

```

I am using `nvm` -- is there some conflict with that?

**Comment by myw** [comment]
i am also having this issue on MacOS; seems like completion is broken with oh-my-zsh and zsh 5.4.1

**Comment by ScottyFillups** [comment]
@jcollum It seems nvm is indeed the culprit, depending on how you installed it. Installing nvm from the Arch AUR requires you to add the following snippet to your `.zshrc`:

`source /usr/share/nvm/init-nvm.sh`

Looking at `init-nvm.sh`:

```bash
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec
```

Reading other issues reveals that loading `bash_completion` seems to be the line causing all the trouble: https://github.com/robbyrussell/oh-my-zsh/issues/6163

To fix this, remove your nvm installation and follow the instructions on the official repository: https://github.com/creationix/nvm

At the time this was posted, this one-liner did the trick:

```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
```

**Comment by mcornella** [comment]
The found solution was to [delay the sourcing of nvm completions](https://github.com/robbyrussell/oh-my-zsh/issues/6163#issuecomment-315836297). Reopen the issue if that didn't fix it.

**Comment by jcollum** [comment]
Thanks! Will check it out. Sometime :)
