### ISSUE TITLE
_arguments:451: _vim_files: function definition file not found

### ISSUE THREAD

**Issue by wireddude** [robbyrussell/oh-my-zsh#6399]
Whenever I try to tab-autocomplete a filename after vi or vim, I get the following error:

_arguments:451: _vim_files: function definition file not found

just upgraded to latest and have only enabled jira and git plugins. My path includes /usr/bin , /usr/local/bin and /bin

**Comment by redbrickone** [comment]
I'm having the same issue. Please let me know if you find anything.

**Comment by wireddude** [comment]
it seems to have fixed itself. perhaps a previous release addressed, however I don't remember upgrading between the time it was failing and it being fixed.

**Comment by redbrickone** [comment]
I got it fixed by removing the `.zcompdump` file from my root directory and running `exec zsh`.

**Comment by wireddude** [comment]
good to know, thanks!

**Comment by DwordPtr** [comment]
Thanks @redbrickone was starting to get anxious!

**Comment by sjcalamia** [comment]
👎 This does not fix it for me. Same error. I did fix it once... but now it's not working. :(

**Comment by hlecuanda** [comment]
removing `.zcompdump` is not a good solution, negating the startup speed-up that a **compiled completion digest** provides. just add a file `_vim_files` somewhere on your `$fpath` here is my [ `_vim_files` ](https://github.com/hlecuanda/zconf/blob/master/UserFunctions/_vim_files).

 enjoy :smiley:

**Comment by nitrocode** [comment]
@hlecuanda how come you removed [_vim_files](https://github.com/hlecuanda/zconf/commit/63ba8ac6705ee08bdca620ba4ee48515eebc86cc) ? How did you fix it?

**Comment by mcornella** [comment]
Run `rm ~/.zcompdump*` and restart the shell with `exec zsh`. The zcompdump files will be recreated with the right completions.

**Comment by nitrocode** [comment]
@mcornella I have to do this every time I open a new zsh prompt or split my panes. There must be a better solution for this.

**Comment by mcornella** [comment]
What `zsh --version` are you running and what does `echo $fpath` print?

**Comment by nitrocode** [comment]
>    $ zsh --version
>    zsh 5.5.1 (x86_64-unknown-linux-gnu)

>    $ echo $fpath
>    /home/user/.zplug/autoload /home/user/.zplug/misc/completions /home/user/.zplug/base/sources /home/user/.zplug/base/utils /home/user/.zplug/base/job /home/user/.zplug/base/log /home/user/.zplug/base/io /home/user/.zplug/base/core /home/user/.zplug/base/base /home/user/.zplug/autoload /home/user/.zplug/autoload/commands /home/user/.zplug/autoload/options /home/user/.zplug/autoload/tags /home/user/.oh-my-zsh/plugins/zsh-syntax-highlighting /home/user/.oh-my-zsh/custom/plugins/zsh-256color /home/user/.oh-my-zsh/custom/plugins/zsh-autosuggestions /home/user/.oh-my-zsh/plugins/z /home/user/.oh-my-zsh/plugins/extract /home/user/.oh-my-zsh/plugins/osx /home/user/.oh-my-zsh/plugins/brew /home/user/.oh-my-zsh/plugins/npm /home/user/.oh-my-zsh/plugins/node /home/user/.oh-my-zsh/custom/plugins/alias-tips /home/user/.oh-my-zsh/plugins/git /home/user/.oh-my-zsh/functions /home/user/.oh-my-zsh/completions /usr/local/share/zsh/site-functions /usr/local/share/zsh/5.5.1/functions

**Comment by LewisMojica** [comment]
This worked for me: 
`rm ~/.zcompdump*`
then
 `exec zsh`

**Comment by mcornella** [comment]
If this is happening to you, run 
```
print -l $^fpath/_vim_files(N)
```
and post the results.

**Comment by nitrocode** [comment]
@mcornella it returns nothing

```
✗ print -l $^fpath/_vim_files(N)
```
