### ISSUE TITLE
[vi-mode] Mode indicator disappears when resizing window

### ISSUE THREAD

**Issue by b4tg5s** [robbyrussell/oh-my-zsh#6404]
@robbyrussell 
#### Problem
The vi-mode plugin indicator disappears when the window (of the terminal emulator) is resized. I was hoping to find a zsh widget hook which lets me reset the prompt when resizing, but I got nothing so far. This only happens when `$ZSH_THEME` does not touch the `$RPS1` or `$PROMPT` (in this case the theme handles these variables instead of `plugins/vi-mode`).

#### Reproduce
- activate `vi-mode` plugin
- use theme `robbyrussel` (or any other that does not touch `$RPS1` or `$PROMPT`)
- start zsh in gnome-terminal
- press <kbd>ESC</kbd> to enter normal mode (`vicmd`), red indicator appears on the right side
- resize the terminal window

#### Desired Behavior
- red indicator should stay until I leave normal mode

#### Actual Behavior
- red indicator disappears altough I  am still in normal mode

At this point I don't know in which direction I should be looking.

**Comment by henrebotha** [comment]
Same issue here! Been driving me insane the last few days. I tried `zle-line-pre-redraw`, but no dice.

I suspect this has nothing to do with the vi mode plugin, because I'm not using it; I'm just using Zsh's built-in vi mode.

### Environment

I'm using a custom theme, and I can reproduce the issue with just this:

```zsh
# ~/.oh-my-zsh/themes/custom-theme.zsh-theme
function zle-line-init zle-keymap-select {
  local return_status="»"
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

PROMPT='${return_status}'

# ~/.zshrc
export ZSH=/Users/henrebotha/.oh-my-zsh
ZSH_THEME="custom-theme"
source $ZSH/oh-my-zsh.sh

bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward

# ~/.zshenv
export SHELL="zsh"
```

I'm running inside tmux.

### Reproduction

1. Start the shell.
2. Resize the window.

### Expected behaviour

The prompt character is visible after resize.

### Observed behaviour

The prompt character is deleted.

**Comment by b4tg5s** [comment]
@henrebotha 

I just found something :) There is a function in `vi-mode.plugin.zsh` that ensures the redrawing of the prompt after the terminal size changes. The function of interest is `TRAPWINCH()`. I just included the `zle reset-promt` hook. This is how it looks like:

```
# Ensure that the prompt is redrawn when the terminal size changes.
TRAPWINCH() {
  zle reset-prompt  
  zle &&  zle -R
}
```

Maybe you can include this somewhere in your zshrc where your prompt is formatted and try if it works for you.

**Comment by henrebotha** [comment]
In my case it was much sillier than that - the issue was the `local return_status`. Because the variable is local to the function, whenever `reset-prompt` was called from another source - e.g. from a window resize - the variable would be empty.
