### ISSUE TITLE
bash: autoload: command not found

### ISSUE THREAD

**Issue by eromoe** [robbyrussell/oh-my-zsh#6405]
Hi, today update got below error:

```
$ source ~/.zshrc
bash: autoload: command not found
bash: /c/Users/ODF/.oh-my-zsh/oh-my-zsh.sh: line 31: syntax error near unexpected token `('
bash: /c/Users/ODF/.oh-my-zsh/oh-my-zsh.sh: line 31: `for config_file ($ZSH/lib/*.zsh); do'

```

env:
win 7 ,  msys2

**Comment by sw-yx** [comment]
what did you find, eromoe??? what did you find???

**Comment by ckurban** [comment]
@eromoe What was the solution for you as I have the same issue ?

**Comment by eromoe** [comment]
Sorry， I forgot .  You can see my post time and close time, they are very close.  As I remmenber, it was not an issue related to oh-my-zsh ,  must be some mistake by myself. So I close this issue without comment.

**Comment by bsed** [comment]
kelvin@gnux ~$ source ~/.zshrc

autoload: command not found
-bash: /home/kelvin/.oh-my-zsh/oh-my-zsh.sh: line 31: syntax error near unexpected token `('
-bash: /home/kelvin/.oh-my-zsh/oh-my-zsh.sh: line 31: `for config_file ($ZSH/lib/*.zsh); do'

**Comment by cppddz** [comment]
also got this error.
i just do 
```
pacman -S zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
```
oh-my-zsh  work only when it install .
when I open a new terminal ，the oh-my-zsh don't work .
I source .zshrc  :
```
[zb@zb-Manjaro ~]$ source .zshrc
bash: autoload: 未找到命令
bash: /home/zb/.oh-my-zsh/oh-my-zsh.sh:行29: 未预期的符号 `(' 附近有语法错误
bash: /home/zb/.oh-my-zsh/oh-my-zsh.sh:行29: `for config_file ($ZSH/lib/*.zsh); do'

```

**Comment by mcornella** [comment]
You need to change your default shell to zsh.

**Comment by robinwkurtz** [comment]
I've ran into the same issue after changing my .zshrc... but only the theme. My default shell is zsh. Any ideas?

**Comment by mcornella** [comment]
Are you running zsh? `echo $ZSH_VERSION` should print something.

**Comment by robinwkurtz** [comment]
Sorry @mcornella, I should have posted earlier.

I was in fact running ZSH and was able to see a version but the problem continued so I reinstalled it and now it's working as expected.

Thanks!

**Comment by ylCodelab** [comment]
change your default shell to zsh
chsh -s /bin/zsh

**Comment by ptlCoder** [comment]
终端执行：chsh -s /bin/zsh

**Comment by gjjcommon** [comment]
I got this error just now  
first  run this command: chsh -s /bin/zsh
then logout from this terminal
login again
then rerun this command: source .zshrc


this works for me 

hope this can help others

**Comment by code33** [comment]
`echo "zsh" >> ~/.bashrc` 

`source ~/.bashrc`

FIXED  HAPPY ~~~

**Comment by Kikyouapp** [comment]
> `echo "zsh" >> ~/.bashrc`
> 
> `source ~/.bashrc`
> 
> FIXED HAPPY ~~~

oh my god   your my super star  why you konw that

**Comment by rwmitchell** [comment]
I fail to see the value of what is going on there.  Instead of changing the default shell to be zsh (the proper thing to do), bash is left as the default, the entirety of the old .bashrc file is loaded AND THEN zsh is invoked?  If zsh is loading to fast for you, just put a 'sleep 60' at the top of .zshrc.
