### ISSUE TITLE
Please can you use releases or branches.

### ISSUE THREAD

**Issue by GokhanPolat** [robbyrussell/oh-my-zsh#6406]
I have two computers and synced my dotfiles repo. 
When I was commit my repo one of my computers always behind each other bc this repo's master branch always progressing. Because this repo commits always pushing master branch.

If I follow your strategy I must push and pull process same time in two machines.

I forgot the mentioned about **upgrade_oh_my_zsh** command in terminal. Auto upgrade also break my repo.

For system wide consistency please consider git release or branches strategy.

If you suggest another way to solve my problem, I am happy to hear...

I am sorry for my English.
Best regards.

**Comment by mcornella** [comment]
This is being considered.
