### ISSUE TITLE
kubectl alias conflicts with "supercrabtree/k" plugin

### ISSUE THREAD

**Issue by aserrallerios** [robbyrussell/oh-my-zsh#6408]
It conflicts with:

https://github.com/supercrabtree/k

Could it be changed to `ku` or the likes?

**Comment by brokenmass** [comment]
:+1: bump

**Comment by mcornella** [comment]
If they're both plugins, whichever is sourced last will be the one with control over the `k` name. After af1709c, there is no need to rename the alias. Thanks

**Comment by mcornella** [comment]
Wait no, k is a function so the kubectl alias will have preference over it no matter what.

**Comment by mcornella** [comment]
#7749 should fix it for you, check that it works please.

**Comment by renatomefi** [comment]
I think many of us will find out (like me) that my `k` shortcut is broken! I think this change could be somewhat smarter in the sense of only doing this if people actually want to use both plugins, something like an alias collision detection.

For now:

```shell
# ~/.zshrc

alias k=kubectl
```

```

**Comment by aserrallerios** [comment]
Alias collision detection in #7749 didn't work for me. The conceptual problem was also that you needed to load them in an specific order.

There's really no easy solution that pleases everyone, I'm afraid.

**Comment by corneliusweig** [comment]
Am I the only one who prefers `k` for kubectl? I find it quite inconvenient to type `ku`, because I really use kubectl a lot.

**Comment by mcornella** [comment]
Don't revert the commit, use `alias k=kubectl` in your zshrc instead which is more future-proof.

**Comment by corneliusweig** [comment]
@mcornella but will that also give me command completion for `k`? I checked that the upgrade mechanism uses `pull --rebase`, so upgrading won't hurt.

**Comment by renatomefi** [comment]
@mcornella with all the respect, future proof had to be thought when changing a 2 years old alias.

**Comment by l13t** [comment]
You changed an alias for the officially built-in plugin because someone who uses third-party plugin complained about same name alias? Just wonder how many users of this plugin there are. And how many users use `k` as an alias for `kubectl`.

**Comment by mcornella** [comment]
I've reverted the change. Use `unalias k` if there's a conflict.

**Comment by aserrallerios** [comment]
No, I cannot `unalias k` but _you_ could `alias k`, that's the big difference.

> You changed an alias for the officially built-in plugin

Officially built-in plugin? This is a community plugin for kubectl or I'm missing something?

> because someone who uses third-party plugin complained about same name alias

First of all, it being a plugin is just a distribution detail, for the sake of discussion it's just a cli command.

Second, look at the date of this issue. The aliases got added to this plugin on Nov 7, 2017 https://github.com/robbyrussell/oh-my-zsh/commit/790712f6f2cae48e8e57239b9ca9e7ab01254253#diff-fb0dd043a2fbb10f3c81ce6b545bf82f

Anyway, fair enough, I'll just ping the `k` author, maybe he'll be willing to change something on his side.

**Comment by corneliusweig** [comment]
@aserrallerios AFAIK `k` already _is_ an alias. And with all due respect, supercrabtree/k has 1.1k stars, whereas kubernetes has 18k _forks_. To me this looks very much like kubernetes should have precedence here.

It's not oh-my's fault that the k author picked a dangerously short name for his command.

**Comment by aserrallerios** [comment]
I meant that even removing the alias here, you can add it later with another plugin or in your own `zshrc` with no disruption, just composition. Unalias is just not an option under all circumstances.
