### ISSUE TITLE
Emacs doesn't play nicely with oh-my-zsh anymore (termsupport.zsh)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [robbyrussell/oh-my-zsh#6411]
I recently noticed my **zsh terminals in emacs** started printing junk/strange characters whenever I issue a command. See the screenshot below:

![screen shot 2017-11-10 at 2 29 15 pm](https://user-images.githubusercontent.com/1993919/32678800-e8a1026a-c631-11e7-9af6-0c5d488689d2.png)

After careful investigation, I noticed the problem comes from sourcing `ZSH/oh-my-zsh.sh`.

If I don't load `oh-my-zsh` everything works like a charm, but as soon as I source it (even without any plugins, options theme selection, etc), I get the problem again.

Moreover, I localized the problem to the loading of [`termsupport.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/termsupport.zsh). If I force `oh-my-zsh `to *not* load this file (e.g. if I remove it), everything seems to works fine.

In case it helps I am using:
* `zsh 5.4.2 (x86_64-apple-darwin16.7.0)`
* The latest oh-my-zsh (I just run upgrade_oh_my_zsh)

What could be going on? If it helps I believe I started noticing the problem a few days/weeks ago.

**Comment by amelio-vazquez-reina** [comment]
I found the problem. I was setting the variable `EMACS` myself in `.zshenv` to help setup `PATH` and [`termsupport.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/termsupport.zsh) [uses this variable](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/termsupport.zsh#L13) internally. All I had to do is rename my own variable to something else, and it all now works.

**Comment by haishengwu-okta** [comment]
FYI: 
add `export EMACS="*term*"` ot `.zshenv` works for me.

**Comment by felker** [comment]
I had a similar issue, but I was **not** setting `EMACS` environment variable anywhere in my dotfiles. Still, @haishengwu-okta's suggestion fixed my problems.

Trying to understand why...

**Comment by mcornella** [comment]
The workaround was merged in https://github.com/ohmyzsh/ohmyzsh/pull/999. According to that PR, Emacs prints those characters when in term mode. It might be nice to figure out a way to disable or change the way OMZ sets the title when in Emacs, but I don't have the time or expertise in Emacs to figure it out right now. If anybody knows where to start I'd appreciate it.

**Comment by felker** [comment]
I figured out the problem, somewhat. The environment variable `EMACS` is no longer set by Emacs in terminal emulation modes. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html. Instead, `INSIDE_EMACS` is used. E.g. in `term-mode` for me:
```
zsh$ echo $INSIDE_EMACS
27.1,term:0.96
zsh$ echo $EMACS

```

Not sure how the current OMZ switch had been working at all for most users, since most people arent setting `EMACS` in their dotfiles, and the environment variable has not been set by Emacs terminal emulation mode in a long time. 

I have submitted #9577 to fix the OMZ switch so that it should work automatically with Emacs, no shell workaround needed.

**Comment by AnselmC** [comment]
I'm not sure whether this is part of the same problem but I'm experiencing weird whitespace and these "%" characters...

```shell
%                                                                                                                                                                 ➜  ocr_tools git:(master) ✗ echo $TERM
eterm-color
%                                                                                                                                                                 ➜  ocr_tools git:(master) ✗ echo $EMACS
27.2 (term:0.96)
%                                                                                                                                                                 ➜  ocr_tools git:(master) ✗ echo $INSIDE_EMACS
27.2,term:0.96
%                                                                                                                                                                 ➜  ocr_tools git:(master) ✗ 
```
