### ISSUE TITLE
Load custom zsh files at the end

### ISSUE THREAD

**Issue by deimosfr** [robbyrussell/oh-my-zsh#6412]
Hi,

I'd like to know if it's possible to load files in custom folders only at the end of ohmyzsh load. Why? Because for example I'm using ag instead of grep, I have an alias grep='ag' and my theme is requiring some grep specific options not available in ag. The theme is not fully loaded.

As I'd like to keep my custom aliases, I'd like to know how it is possible to load some specific (or all custome files) only at the end.

Thanks in advance

**Comment by MenkeTechnologies** [comment]
```source ~/myconfig.zsh``` at the end of ~/.zshrc

**Comment by mcornella** [comment]
You can bypass an alias using `command` or `\`: `command grep` will run grep regardless of aliases named grep; the same for `\grep`. So I'd advise you to use that instead of relying on the order of sourcing of files.
