### ISSUE TITLE
(Cross post) Missing symbols in patched Ubuntu Mono on Windows 10

### ISSUE THREAD

**Issue by wulfgarpro** [robbyrussell/oh-my-zsh#6413]
I'm cross posting here since [my ticket](https://github.com/powerline/fonts/issues/258) on the powerline-fonts project is affecting my use of the sheeef theme.

**Comment by victormongi** [comment]
Same issue...

**Comment by mcornella** [comment]
Sorry, this is not something we're able to fix.
