### ISSUE TITLE
docker stack rm autocomplite

### ISSUE THREAD

**Issue by krocos** [robbyrussell/oh-my-zsh#6415]
![image](https://user-images.githubusercontent.com/4757342/32702939-22911ff2-c810-11e7-8ca5-59e359cc0ca1.png)

When press Tab there are no options or stacks shown

Ubuntu 16.04
oh my zsh dcb8101fdeded9aa4310d867f9c809c976a0f1cb
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` and restarting the shell.
