### ISSUE TITLE
Separate code of each plugin into separated repositories

### ISSUE THREAD

**Issue by bruno-delfino1995** [robbyrussell/oh-my-zsh#6420]
Hi @robbyrussell,

I would like to propose to put the code of each plugin inside separated repositories. By doing so we can have a more fine issue reporting and make it clear where to find them. Also, the main reason for me is that some tools like [Antibody](https://github.com/getantibody/antibody/) don't support importing plugins from this repo, so by splitting the plugin's code into repositories we start to support Antibody.

I gave it a try by splitting each plugin into a single repository, keeping the history, and it worked. Now I just want to align with your expectations and if I can do such thing, if yes, I'm planning to contact either @nicoulaj (@zsh-users) or @desyncr (@zsh-plugins) to use their organizations as a place for the plugins.

What do you think about that?

**Comment by YoshiMan** [comment]
I think it is a great idea, because you can easily create pull requests/issues for each plugin, but on the other hand I can imagine its kind of hard to get this working all together.

**Comment by bruno-delfino1995** [comment]
I don't think it gonna be hard because what *oh-my-zsh* does is reading the $plugins array and loading each one of them from the plugins folder. With the current approach, we get all the plugins and load only what we want. In this new approach, you just need to clone the plugin's repo and load it by adding to the plugins array as before, making each plugin optional.

One possible difficulty maybe comes when trying to have the same setup as now by installing all the plugins with the latest code, but for that, we can create a script for that. Do you think is really necessary to install all of them in a new setup?

**Comment by YoshiMan** [comment]
Yeah sounds good an easy. And for the Plugins you need some kind of mapping table like pluginA="git@github.com:username/pluginA.git"
So zsh knows which plugins to clone and how to update.
So the initial setup will take some time, but the updates, will be easy and faster.

**Comment by YoshiMan** [comment]
Maybe the use of submodules is even a better approach. I'm not so familiar with these submodules, but it sounds like it is quite suitable.

**Comment by bruno-delfino1995** [comment]
AFAIK submodules are used to keep subprojects in a manner more towards customization. I've played with them and one limitation is that it will lock the module at a specific commit, making the updating process a little bit more bureaucratic. We would have to update the submodule and push it to the upstream, on the other hand, this makes the updates management more controllable because we could release updates with fixed versions of the plugins.

Although I don't think this would bring many advantages since *oh-my-zsh*  is mainly a configuration management tool and not a preset of plugins. To overcome the difficulties of updating, we could assume the folders in `plugins` are git repositories, so for updating it, we pull and for checking we fetch. This way we don't have the need to create a mapping table since all of them are repositories, the mapping would only be needed if we pretend to have the current plugins for a raw installation. That is the simplest approach that I can think of.

**Comment by 2m** [comment]
Just a note that it is now possible to load a built-in oh-my-zsh plugin with antibody by using `folder` annotation. For example:

```
robbyrussell/oh-my-zsh folder:plugins/sudo
```

**Comment by mcornella** [comment]
This is not something we're going to be working on in the near future.
