### ISSUE TITLE
I have some question

### ISSUE THREAD

**Issue by kamontat** [robbyrussell/oh-my-zsh#6430]
And I don't know where I can ask.. It about zsh.

you have set 
`setopt COMBINING_CHARS` in `.zshrc` file to avoid Thai Language error. 
But when I open new terminal this command somehow it didn't load for me, so I need to run `exec zsh` to activate it.

**Comment by NieDzejkob** [comment]
If you open a new terminal, are you dropped into zsh or bash?

**Comment by kamontat** [comment]
Zsh

**Comment by mcornella** [comment]
Can you post your zshrc file for reference? And how do you know it didn't load, what signs are you able to see?
