### ISSUE TITLE
yarn plugin alias yo confict with yeoman

### ISSUE THREAD

**Issue by justnewbee** [robbyrussell/oh-my-zsh#6435]
it took me quite a while to locate this issue,
please do NOT use `yo` as an alias, i see the aliases were added only 2 weeks ago

**Comment by xgarrett** [comment]
Hi @justnewbee, I had the same problem yesterday and I've just created PR immediately as it was really easy to fix. I didn't even realised that you've created this issue 😅 

So FYI here's PR with fix: #6453

**Comment by joonhocho** [comment]
I didn't know yarn aliases were auto added, and this caused me to waste some time. :(
Adding aliases without knowing doesn't seem like a good idea to me.

**Comment by joeycozza** [comment]
One solution that you can do even if the maintainers never update the yarn plugin to remove the yo alias, is "make" your own plugin and put it in the ZSH_CUSTOM folder.

You can follow the instructions here, but I'll even tell you exactly what you'd want to do. https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

On mac, this is all you'd have to do.

1.cp -r $ZSH/plugins/yarn $ZSH_CUSTOM/plugins/
2. Go edit the $ZSH_CUSTOM/plugins/yarn/yarn.plugin.zsh file. You can edit or remove the alias on line 7 and be good to go.

Hope this helps.
