### ISSUE TITLE
Can I improve the laravel plugin?

### ISSUE THREAD

**Issue by llbbl** [robbyrussell/oh-my-zsh#6437]
I would like to drop the 5 on the laravel plugin? Anyone opposed to this?

At the very least I would like to integrate some of the laravel news bash aliases. The consensus seems too be artisan and art as the main aliases. I think adding some of the "pa" aliases makes sense too. 

https://laravel-news.com/bash-aliases

**Comment by mdurao** [comment]
I'm using 'art' as an alias of 'php artisan'.

Would love to have file autocompletion in the plugin too for custom commands:

`php artisan import:csv myfile.csv`

Currently, you cant tab the custom commands, but after that, i'm unable to autocomplete the file or or directories...

**Comment by llbbl** [comment]
Guess i'll submit a PR and see what happens.

**Comment by mcornella** [comment]
You can!
