### ISSUE TITLE
"firewall-cmd "command con't autocomplete in CentOS

### ISSUE THREAD

**Issue by yaro97** [robbyrussell/oh-my-zsh#6438]
While the other commands autocomplete rightly, "firewall-cmd "command con't autocomplete in CentOS.
could anybody tell me why?

**Comment by smalleyes** [comment]
[root@dev xmc ]$ firewall-cmd --

env   in fedora.
so am i...

**Comment by mcornella** [comment]
This is because there is no completion for firewall-cmd in zsh. You could use the [bash completion](https://github.com/firewalld/firewalld/blob/master/shell-completion/bash/firewall-cmd) and [load it within zsh](https://stackoverflow.com/a/8492043).
