### ISSUE TITLE
something seriously changed lately?

### ISSUE THREAD

**Issue by pjhalsli** [robbyrussell/oh-my-zsh#6439]
I have installed zsh approx 100 times and never had problems. yesterdaty for a friend it looked like it was ok . it said shellc hanged. opened a new term and it still was bash. Today I innstallled Antergos on a machine and experienced the exact same issue. it says the shell have changed but on the next term you're still in bash. so now I had to type zsh to get into zsh.

I loked over my .zshrc but cant seee anything ifferent from what I've seen befor

So was just wondering if something important have changed  - say the last 2 weeks - thats about the time since I last installed it for a frined

edit:
when I speak of zsh I mean zsh AND oh-my-zsh
Linux user ofc

**Comment by rand0m86** [comment]
Same thing for me. After last update for git plugin I had an issue for line 42 (around 'elif' statement to be precise). Today I tried to reinstall it completely and I cannot even install it. VIM shows that there are bunch of `^M` chars at the end of each line in `.zshrc` and I cannot proceed because of:
```
/Users/myuser/.zshrc:3: command not found: ^M
.....
and many more
```

**Comment by andrewnsk** [comment]
Same thing for me. 
After update 
`zsh: command not found: git_prompt_info`

then i reinstall zsh and oh-my-zsh:
`/home/user/.zshrc:source:65: no such file or directory: /home/user/.oh-my-zsh/oh-my-zsh.sh^M
/home/user/.zshrc:66: command not found: ^M
`

**Comment by pjhalsli** [comment]
I usually install manually but this have made me try both curl and wget but it's the same result no matter what i do. I do have zsh and omz though but have to start it every time i open a terminal. Using a browser and only terminals for everything else i think zsh is the command typed most the last 2 days.   😁  feel real sorry for those who don't even have it.  It must be hard to live without a computer -  as using bash is unthinkable

**Comment by phumpal** [comment]
I've not looked into implementing a fix but reverting and disabling auto-updates seems to be a temporary workaround until this is patched.

```
cd $ZSH
git checkout 41eedd37005f6b3668fcebe2a5f5a26324753519
```

YMMV but in `~/.zshrc`
```
DISABLE_AUTO_UPDATE="true"
```

**Comment by phumpal** [comment]
Oddly, I just double checked and master seems to be working again.

**Comment by eugenpirogoff** [comment]
```^M``` is a CR setting in git config. This [here](https://github.com/robbyrussell/oh-my-zsh/issues/6417) may be helpful.

**Comment by rand0m86** [comment]
Thanks @eugenpirogoff ! Disabling `autocrlf` option helped

**Comment by pjhalsli** [comment]
Works fine for me now it seems.   Bsh is gone and I open a teminal and the old familiar jnrowe theme is already there,

Obviously een fixed. Thank You and closing
