### ISSUE TITLE
Plugin enabled even though not in .zshrc

### ISSUE THREAD

**Issue by carlos-sarmiento** [robbyrussell/oh-my-zsh#6443]
I'm having a weird issue in MacOS 10.12 with a just installed oh-my-zsh.

I work with extremely large mercurial and git repos and so wanted to test those plugins. I enabled them, but performance was way to slow (expected, the repos are huge) so I removed them from .zshrc. 

Now I'm facing this weird issue that the plugins are still loading. I'm printing the plugins var after the script is done (as the last line in .zshrc) and neither git nor mercurial is there. Any idea what might be happening?

EDIT: I've closed the terminal window, done a `source .zshrc`, and restarted the machine several times

**Comment by wrecklass** [comment]
Can you tell us how it is you know the Plugins are loaded? Are they in the FPATH? There are a bunch of git functions added automatically as part of oh-my-zsh/lib/git.zsh standard library.

**Comment by mcornella** [comment]
You might be facing slowness from some other part of the codebase. Reopen if necessary.

**Comment by carlos-sarmiento** [comment]
So I figured this out a while ago but forgot to post. The slowness came from the Agnoster theme, which has some logic to read the status of a mercurial repo. I don't know if this would be the right place to report this, but it would be great if there were a way to disable that on the theme without changing the actual code (which is what I had to do)

**Comment by mcornella** [comment]
I'm not very experienced with mercurial, but I see that it makes quite a lot of calls and it could probably be optimised in some way. If you want to try it out, you can just redefine the `prompt_hg` function and test what gives the best performance results. Unfortunately I can't actually put in any effort at the moment.
