### ISSUE TITLE
When i try to cd dir I get an error 'cd: string not in pwd: foo'

### ISSUE THREAD

**Issue by keevvinc** [robbyrussell/oh-my-zsh#6452]
I know this is almost the same issue as  #4513 , however I do not have set an alias for 'cp' ..
Any solutions? Until recently I could cd directories that contain space without escaping them, nor putting  the path into " " ..

**Comment by dalibran** [comment]
I'm encountering the same error. The directory I'm trying to cd into is labeled '2018.02 Spring.' I don't have an alias set up in my .zshrc file. The specific error I'm getting is...

<img width="236" alt="screenshot 2018-04-11 12 52 03" src="https://user-images.githubusercontent.com/2665651/38639783-28adc894-3d87-11e8-9e04-330d9203e98e.png">

**Comment by mcornella** [comment]
You have to escape the spaces in an argument, otherwise `cd` will see it as two arguments, which runs the second version of the `cd` command: [`cd old new`](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-cd), which is probably not what you intend.
Not an issue.

**Comment by dalibran** [comment]
thanks! @mcornella

**Comment by didimedina** [comment]
@mcornella thanks!

**Comment by redoz94** [comment]
So what if there's spaces in the name of a directory?

**Comment by mcornella** [comment]
Escape the argument, i.e. `cd "name of directory"`.

**Comment by UsmanButt93** [comment]
how we can access the directory which has spaces in name?
it would take too long every time to write for each directory in order to access it. 
does it have any shortcut?

**Comment by mcornella** [comment]
Use tab completion, i.e. start to type the directory, then press TAB to complete the name.

**Comment by Amir-mirgeloybayat** [comment]
@UsmanButt93 If you're using a mac os:
you can go to preferences > keyboard > shortcuts > go to the Files and folders drop-down menu and check "new terminal at folder"
Now if you go to a specific path/ folder and right-click on it, you can choose "new terminal at folder" and you can verify that you're in the right place by pwd command

happy coding!

**Comment by asaalim** [comment]
> Use tab completion, i.e. start to type the directory, then press TAB to complete the name.

this worked for me. thank you

**Comment by car21** [comment]
> Escape the argument, i.e. `cd "name of directory"`.

Thank u a lot!

**Comment by IdrissTheCat** [comment]
=) Tks

**Comment by Ankit-Yaduwanshi** [comment]
> > Escape the argument, i.e. `cd "name of directory"`.
> 
> Thank u a lot!

Thanks!!!
