### ISSUE TITLE
vim - read from stdin returns error

### ISSUE THREAD

**Issue by coot** [robbyrussell/oh-my-zsh#6458]
When `oh-my-zsh` is enabled (no plugins, default theme) the following command gives an error:
```
echo "OK" | vim -
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 19 2017 20:19:52)
Too many edit arguments: "-"
More info with: "vim -h"
```
While this should just load `ok` string into `vim`.

**Comment by wrecklass** [comment]
Do you have an alias or function for vim? What does 'which vim' say?

**Comment by coot** [comment]
I do have an alias to `vim --servername V`.

**Comment by mcornella** [comment]
This is not a problem of OMZ.
