### ISSUE TITLE
Terminal transparency not working ?

### ISSUE THREAD

**Issue by CodeGanesha** [robbyrussell/oh-my-zsh#6459]
I installed oh-my-zsh and installed one of transparent terminal looking theme, but the terminal window is not appearing transparent, I would like to know, Is there any way/scripts to make terminal window look transparent. I'm using bash on window or window subsystem for linux's bash, and installed oh-my-zsh in it.
Any help will be heartly appreciated. Thankyou all.

**Comment by x4018** [comment]
https://github.com/settings/emails

**Comment by 0508327755y** [comment]
Gncgjn

**Comment by mcornella** [comment]
The transparency is a setting you have to activate in whatever terminal application you're using.
