### ISSUE TITLE
Solution: autojump_chpwd: nice(5) failed: operation not permitted (WSL)

### ISSUE THREAD

**Issue by hua03** [robbyrussell/oh-my-zsh#6460]
- OS Version: Ubantu16.04 （Windows Subsystem for linux）
- Zsh Version: 5.1.1

Steps to Reproduce:

1. Check if autojump was installed correctly.I used this command `sudo apt install autojump` to install autojump, but it did not generate this folder `~/.autojump`. If you are the same as mine, you can install it by Git.[Here](https://github.com/wting/autojump#manual) to install.

2. Check if autojump.zsh was installed correctly.if not, you can use the command:

```bash
wget https://raw.githubusercontent.com/joelthelion/autojump/master/bin/autojump.zsh -O /etc/profile.d/autojump.zsh
```

3. Check the file `~/.zshrc`:

You must configure the .zshrc file correctly.The first configuration is when autojump is installed, it's recommended by oneself.The second does not need me to explain.

And you can get the third configuration information from this [issue](https://github.com/Microsoft/WSL/issues/1887), look at @daiconrad reply.

![image](https://user-images.githubusercontent.com/19561959/33417079-d2719adc-d5da-11e7-9ef9-fe7ae361fe5e.png)

**Comment by WozniakMac** [comment]
Thanks 👍

**Comment by mcornella** [comment]
I'd suggest you follow https://github.com/wting/autojump/issues/474 instead, this is not an OMZ-related issue.

**Comment by hua03** [comment]
OK 👌
