### ISSUE TITLE
termsupport.zsh: window title is not set when TERM=='screen*' (only window name is set)

### ISSUE THREAD

**Issue by thugcee** [robbyrussell/oh-my-zsh#6463]
In xterm there is the concept of _window icon_ and _window title_ and when we run tmux there is additionally _window name_. oh-my-zsh has logic to handle all of this, but finally for TERM 'screen' it sets only _window name_. 

It can be fixed by adding 1 lines to the title function like this:
```
    screen*)
      print -Pn "\e]2;$2:q\a" # set window title
      print -Pn "\ek$1:q\e\\" # set window name
      ;;
```

Now one can manipulate _ZSH_THEME_TERM_TITLE_IDLE_ and _ZSH_THEME_TERM_TAB_TITLE_IDLE_ to set variables '#T' and '#W' expanded in a tmux's status line.

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/issues/3579#issuecomment-480535129
