### ISSUE TITLE
ERROR: Cannot Verify github.com's certificate, issued by

### ISSUE THREAD

**Issue by CrAsHOvErRiDe34** [robbyrussell/oh-my-zsh#6464]
I am having issues when trying to down load git-cinnabar.macos.x86_64.zip on a CentOS 7 vm.  Regardless if I run the VM on Windows or MAC OS, I get the same error that it cannot verify github.com's certificate.

Do you know what could cause this?

**Comment by CrAsHOvErRiDe34** [comment]
(https://user-images.githubusercontent.com/9059118/33738609-553ee580-db5f-11e7-88ca-23746cea7e10.PNG)

**Comment by CrAsHOvErRiDe34** [comment]
See from the image I uploaded this is the issue we are getting, can someone help out.

**Comment by wrecklass** [comment]
Probably get more help from a GitHub support person than ZSH as it is not likely anything to do with this. As a guess I'd say you have a proxy between you and GitHub which is inserting it's own certificates into the stream. Talk to your network admin.
