### ISSUE TITLE
zsh: no matches found: [:digit:]

### ISSUE THREAD

**Issue by mrvilla** [robbyrussell/oh-my-zsh#6471]
### this works for bash!
echo “1this1to1test” | tr -d [:digit:] 

### (but in zsh) i get this error
zsh: no matches found: [:digit:]

any help? thanks

**Comment by folixg** [comment]
According to the zsh [release notes](http://zsh.sourceforge.net/releases.html) support for classes like :digit: was added with version 3.1, so I have no idea, why it doesn't work.
As a workaround you can specify digits as a range like this:
``` 
> echo “1this1to1test” | tr -d 0-9      
“thistotest”
```

**Comment by mrvilla** [comment]
the workaround works, thank you 👍 

I still would want to know why it doesn't work though. 
although, you do write less with the workaround 😄

**Comment by mrvilla** [comment]
this works btw

echo “This1is1for1testing” | tr -d '[:digit:]'
“Thisisfortesting”

**Comment by mcornella** [comment]
Yes, you have to quote parameters containing `[]`.
