### ISSUE TITLE
Unrendered character and unwanted echo of last command

### ISSUE THREAD

**Issue by khipukamayuq** [robbyrussell/oh-my-zsh#6476]
Still pretty new at all this linux and terminal stuff. I've swiched from Linux Mint (Cinnamon) 17.3 to UbuntuStudio 16.04 with Xfce DE. Using zsh as my default shell and had previously been using zprezto for my configuration. Set up oh-my-zsh with agnoster and did nothing else. Liking oh-my-zsh a lot, but noticed after setting up my .vimrc a minor annoyance. After each command I enter into terminal I get something like �kcd% preceding any output to terminal. It should be something in .zshrc, I'd think, only I never actually touched that except to add `export TERM = 'screen-256color'` for my vim configuration. I checked out the agnoster theme README.md and made sure to update my fonts. No effect. Any ideas on where to look? Nothing seemed obvious to me. I've attached a screenshot of this annoyance. Any help is greatly appreciated. ![screenshot_2017-12-07_10-44-55](https://user-images.githubusercontent.com/16020142/33724382-50ad006e-db3d-11e7-822b-5a677a4c8180.png)

**Comment by khipukamayuq** [comment]
So... commenting out my export for 256 colors fixes the issue. But then my vim isn't configured as nicely. For reference my vim config comes from [https://github.com/Integralist/ProVim](url). Now that I'm using oh-my-zsh I did not use any of the above link's recommended .zshrc config except for the now commented out export for 256 colors. Any ideas on why this could be? Or how to get my 256 colors back without this ugly echo?

**Comment by khipukamayuq** [comment]
I figured it out. Verbiage is slightly different in my case. export TERM=xterm-256color worked without causing the strange echo that export TERM="screen-256color" did.

**Comment by ktaragorn** [comment]
Cool, that worked for me too, thanks

**Comment by dmgolembiowski** [comment]
> I figured it out. Verbiage is slightly different in my case. export TERM=xterm-256color worked without causing the strange echo that export TERM="screen-256color" did.

Hello from 2022; this fix is still helpful
