### ISSUE TITLE
Can't use any themes

### ISSUE THREAD

**Issue by sdctm** [robbyrussell/oh-my-zsh#6478]
I have installed `oh-my-zsh` and `Iterm2` but when I change my theme to `Agnoster` nothing changes. Here's my `.zshrc` file:

```export ZSH=/Users/{username}/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh
```

But my Iterm2 terminal still looks the same

`echo $SHELL` outputs `/bin/zsh`

**Comment by wrecklass** [comment]
Did you try restarting iTerm2? I found that sometimes where I change the fonts and or themes iTerm2 must be shutdown and restarted (Quit app and re-Launch).

**Comment by VGamezz19** [comment]
Have the same error...

**Comment by girol** [comment]
Guys, I had an issue weeks ago similar to this and solved declaring plugins in a single line:

`plugins=(git composer laravel)`

Worth a shot. :)

**Comment by girol** [comment]
And what's the content of your env var `$ZSH`?

**Comment by sdctm** [comment]
@girol - Just tried to add the plugins on one line, restarted everything but the issue still exists. 

`$ZSH` returns `/Users/me/.oh-my-zsh`

**Comment by mcornella** [comment]
Please run `zsh -xvic 'exit' &> ~/omz-debug.log` and post the resulting file as a private gist.
