### ISSUE TITLE
Redirecting output to the wrong file

### ISSUE THREAD

**Issue by josanabr** [robbyrussell/oh-my-zsh#6479]
Hi,

I'm using zsh (zsh 5.3 (x86_64-apple-darwin17.0)) and I found that it utterly wrong overwrites the file that I did not indicate to do it. Here is the scenario, I have a file named 'otro.xml'. I run a command which redirects the output to other file named 'Otro.xml' (note the capitalized 'O'). However, zsh ignores the capitalized 'O' instead overwrites the original 'otro.xml'. 

Zsh has a lot of good features but autocompletion is not one of them, it should be removed.

Regards,

**Comment by mcornella** [comment]
If you don't want case-insensitive completion you can set `CASE_SENSITIVE` to true in your zshrc file, before sourcing OMZ.
