### ISSUE TITLE
NPM and YARN global packages won't work after closing Terminal

### ISSUE THREAD

**Issue by cassianomon** [robbyrussell/oh-my-zsh#6481]
Hello, my problem is that after I install a global package (Ex: yarn add global react-native-cli) and I try to run it, I get:
``zsh: command not found: react-native``

If I run the command:
export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"

It will work, but if I close the terminal, it stop working again...

If I uninstall ohmyzsh it will work just fine.

How to make my global npm/yarn packages work with ohmyzsh without having to export to path session?

Running macOS High Sierra Version 10.13.1

**Comment by folixg** [comment]
Just add the export command to your .zshrc, then it should be executed every time you start a terminal session.

**Comment by cassianomon** [comment]
Gonna try that, thanks

**Comment by cassianomon** [comment]
Worked!
