### ISSUE TITLE
Seeing some weird icons after git branch using agnoster theme

### ISSUE THREAD

**Issue by monsonjeremy** [robbyrussell/oh-my-zsh#6486]
I just installed and set the theme to agnoster and am seeing a weird circle icon and a question mark icon following my git branch. Does anyone know what these are or how i can remove them?
![screen shot 2017-12-11 at 11 58 27](https://user-images.githubusercontent.com/8846086/33855383-9e96b3e4-de79-11e7-9a04-ee3a7464fa3a.png)

**Comment by folixg** [comment]
I am not familiar with the agnoster theme, but my guess is, that these icons indicate the status of your repository (i.e. unstaged changes, untracked files, etc.).

**Comment by wrecklass** [comment]
Agree with folixg. Can you do a 'git status' to show us what is changed in the repo? The circle icon means means you have unstaged changes.

**Comment by cdarken** [comment]
Indeed, the icons should indicate the status of your repo, but because you don't have the proper font in your console what it's displayed may be not what's intended. What font are you using? Try and install Hack, I think it has already all the glyphs that are needed without patching you existing font.

**Comment by joeycozza** [comment]
You can follow the instructions here to customize a theme for yourself, but I'll even tell you exactly what you'd want to do. https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

On mac, this is all you'd have to do.

1. ```cp -r $ZSH/themes/agnoster.zsh-theme $ZSH_CUSTOM/agnoster.zsh-theme```
2. Go edit the $ZSH_CUSTOM/agnoster.zsh-theme file. 

You'll have to mess around a bit to find where the the symbols you want to remove are being set.
I'd start by looking around line 215 where they build the prompt from individual variables that they've made throughout the file.

Hope this helps.

**Comment by mcornella** [comment]
The circle means you have unstaged changes, the yellow segment means you have a dirty working directory (you have changes), and the question mark might be that you have staged changes, but it should show a plus sign (`✚`).
If you run `git status -sb` and post the output we could know more about it.
