### ISSUE TITLE
ZSH_THEME not working

### ISSUE THREAD

**Issue by Yakoot** [robbyrussell/oh-my-zsh#6488]
Hi. I've installed archlabs with zsh and oh-my-zhh out of box, but I can't change theme, what could be the problem?

**Comment by wrecklass** [comment]
Perhaps more information? I assume from what you've written you change the ZSH_THEME variable in .zshrc to a new theme, but when you start a new zsh shell the theme is not being used?

**Comment by Yakoot** [comment]
Yes

**Comment by Yakoot** [comment]
yakoot@yakoot-pc ~ % ls -lah | grep zsh
drwxr-xr-x 11 yakoot yakoot 4,0K дек 13 03:17 .oh-my-zsh
-rw-------  1 yakoot yakoot 6,2K дек 18 10:31 .zsh_history
-rw-r--r--  1 yakoot yakoot   21 дек 13 03:05 .zsh.local
-rw-r--r--  1 yakoot yakoot 3,1K дек 13 03:02 .zshrc
-rw-r--r--  1 yakoot yakoot 3,1K дек 13 02:48 .zshrc.pre-oh-my-zsh
-rw-r--r--  1 yakoot yakoot   17 дек 13 02:47 .zsh-update

**Comment by wrecklass** [comment]
What terminal are you using? Also, try this:

`cd ~
source ./.oh-my-zsh/themes/agnoster.zsh-theme`

That should also load the theme immediately. If that doesn't work I'm assuming you may have a terminal problem.

**Comment by Yakoot** [comment]
Guake
that doesn't work =(
I found the same issue, but I want to found problem without removing zsh
https://webcache.googleusercontent.com/search?q=cache:-63qr6R7njIJ:https://github.com/erikdubois/ArchLabs/issues/2+&cd=1&hl=ru&ct=clnk&gl=ru

**Comment by Yakoot** [comment]
I will try to ask a question in the archlabs forum

**Comment by wrecklass** [comment]
Ya, check /etc/zsh* and see if they have something in the defaults that are overriding your setup.

**Comment by jonas-meyer** [comment]
Hi Yakoot, If you still have the problem I was able to fix it by removing the package: "grml-zsh-config". Hope it helps you too

**Comment by Yakoot** [comment]
Thanks! It works!

**Comment by jonas-meyer** [comment]
@Yakoot Nice that it's working. Would be great if you could close the issue!
