### ISSUE TITLE
When not in git directory: "fatal: --local can only be used inside a git repository"

### ISSUE THREAD

**Issue by stationstops** [robbyrussell/oh-my-zsh#6491]
Whenever I press enter in a non-repo directory, I get the error:
"fatal: --local can only be used inside a git repository"

Teammates with same setup also have the issue:

oh-my-git: latest as of posting fd13327094d0ff2db3d713f21942f0419acb1dfb
oh-my-zsh: latest as of posting  a7fb55cf13bd5956a183e42916cf160a962b6370
OS: MacOS Sierra 10.12.6 
git version 2.15.1
zsh 5.2 (x86_64-apple-darwin16.0)

https://github.com/arialdomartini/oh-my-git/pull/109#issuecomment-311462105

This issue fix was merged in oh-my-git (Im not sure how that dependency works for oh-my-zsh), but didn't solve the problem for me. Couldn't find equally relevant code in oh-my-zsh.

**Comment by adambene** [comment]
same here

**Comment by albertplaya** [comment]
same here!

**Comment by Shea690901** [comment]
Look at all your plugins and look which one is calling ```git config --local ...```, than look which one doesn't send it's stderr into nirvana (```2> /dev/null``` or even ```> /dev/null 2>&1```) and then you know were your error comes from...

**Comment by twodiefor** [comment]
Still there. But, based on @Shea690901's comment, in file '~/.oh-my-git/base.sh' change the line `local enabled='git config --local --get oh-my-git.enabled'` to `local enabled='git config --local --get oh-my-git.enabled 2> /dev/null'`

**Comment by stationstops** [comment]
thx - but didnt work for me twodiefor

**Comment by mcornella** [comment]
There is no code in OMZ that runs `git config --local`. If you have oh-my-git updated make sure that your zshrc file reflects that. I can't tell you anything else.

**Comment by stationstops** [comment]
I literally just fixed this by simply running:
'antigen update arialdomartini/oh-my-git'

...not sure when the fix was actually pushed, as this didn't fix the issue previously....

**Comment by adambene** [comment]
@stationstops miracle happened for me as well...

**Comment by jpchavat** [comment]
Here is the commit that fixed the issue: https://github.com/arialdomartini/oh-my-git/commit/a9fefe33b026b738bd6dfdf6072923c9750733b8

**Comment by jessicatrettin** [comment]
@
