### ISSUE TITLE
Why git autocomplete get so many options? 

### ISSUE THREAD

**Issue by betorobson** [robbyrussell/oh-my-zsh#6495]
When I type:
```bash
$ git pull or
```
Followed by tab, I get a lot of options which is not related to my repository. There is a way to just get my repo options.
The example above I have expected to get just `origin` but I got the following screenshot:
<img width="1177" alt="screen shot 2017-12-19 at 12 47 07 am" src="https://user-images.githubusercontent.com/13212208/34138482-e0653916-e456-11e7-84ca-06878155bf8b.png">

**Comment by wrecklass** [comment]
Those are all FQDN's. I suspect you have a large /etc/hosts file with lots of such domains configured. So git completion offers them all as alternatives.

**Comment by betorobson** [comment]
Indeed my host has a lot of domains such as ads hosts to prevent any of them display on websites. There is a way to keep them without installing any adblock in my browser and not get any side effect on git autocomplete?

**Comment by wrecklass** [comment]
Well, one way would be to put these into your DNS resolver. I usually have my own dnsmasq server that acts as a local caching server for my network. Put any specific domains you wish into the configuration file for that.  Otherwise use an ad-blocker on your browser.
