### ISSUE TITLE
Installer: spaces in $HOME make the git clone fail

### ISSUE THREAD

**Issue by kingalione** [robbyrussell/oh-my-zsh#6500]
When I follow the instructions for installing zsh on my mac, I get this error after I try to run the install script via curl:

Error: git clone of oh-my-zsh repo failed

But in fact I can clone the repo so its not an git issue.

**Comment by wrecklass** [comment]
the installer uses the line:

`env git clone...`

If your environment doesn't have git installed in the usual places, this might fail. From the command line try doing: `env git` and see what happens.

**Comment by NicolJiang** [comment]
Same problem... It‘s terrible.

**Comment by freddydumont** [comment]
If there is a space in your $HOME path, this could cause the issue. I fixed it by following the procedure detailed here:

https://github.com/nodejs/node-gyp/issues/65#issuecomment-179159383

**Comment by mcornella** [comment]
This is fixed in the [current version of the installer](https://github.com/robbyrussell/oh-my-zsh/blob/bb908495deae22314c3355235133063087698796/tools/install.sh#L62).
