### ISSUE TITLE
Yarn plugin 'yo' alias colides with Yeoman's 'yo' command

### ISSUE THREAD

**Issue by Shuky** [robbyrussell/oh-my-zsh#6502]
When trying to call a Yeoman generator I was getting a yarn outdated message, and I couldn't find anything about it on the web.
It took some time till the chips fell and I remembered that I enabled the yarn plugin for zsh, and found out that it uses the same alias (yo) as the yeoman executable for 'yarn outdated'. 

Should consider changing this alias as Yeoman is extremely popular.

**Comment by joeycozza** [comment]
One solution that you can do even if the maintainers never update the yarn plugin to remove the yo alias, is "make" your own plugin and put it in the ZSH_CUSTOM folder.  

You can follow the instructions here, but I'll even tell you exactly what you'd want to do. https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

On mac, this is all you'd have to do.

1.```cp -r $ZSH/plugins/yarn $ZSH_CUSTOM/plugins/```
2. Go edit the $ZSH_CUSTOM/plugins/yarn/yarn.plugin.zsh file. You can edit or remove the alias on line 7 and be good to go.

Hope this helps.
