### ISSUE TITLE
scp dosen't work!

### ISSUE THREAD

**Issue by yanwii** [robbyrussell/oh-my-zsh#6504]
```
scp ubuntu@192.168.31.31:/xxxx/* ~/xxx
zsh: no matches found: ubuntu@192.168.31.31:/xxxx
```
but it works in bash

**Comment by Alwaysc0d3** [comment]
Hi yanwii,

It works here, so if you think this is an bug or error, please provide us with more information. Otherwise, i suggest checking the ~/.zshrc configuration or try a reinstallation of zsh (check the readme for this procedure).

**Comment by NieDzejkob** [comment]
Since `ubuntu@192.168.31.31:/xxxx/*` is a remove path, I believe you should either quote it or configure zsh to pass unmatched wildcards to programs verbatim instead of raising an error.

**Comment by mcornella** [comment]
You have to quote arguments that contain an asterisk or zsh will interpret it as trying to expand the argument to a file: `scp "ubuntu@192.168.31.31:/xxxx/*" ~/xxx`

**Comment by Amelius258** [comment]
In my case, zsh continue complaining my file 'not a regular file', as it recongnize my file location as a path to a folder. Strange issue, perhaps a unfixed bug.

**Comment by Amelius258** [comment]
Similarly, my scp command ,which downloads file from remote server, works well on Ubuntu 22.04:
[scp myname@myip:/path/to/my/file .]
However, zsh reports error as
[ "  '/path/to/my/file/' is not a regular file"]
I am definitely sure that my file is a tar file, not a path to folder (an commonly found error if you search "not a regular file" error on stackexchange).
