### ISSUE TITLE
Fresh install of Mac OS 10.13.2 High Sierra + zsh, zsh hangs

### ISSUE THREAD

**Issue by marklabrecque** [robbyrussell/oh-my-zsh#6505]
ON a fresh machine (completely wiped HD and re-installed OS), I am having trouble getting zshell to work. When run the install, everything seems to work like it used to, but when I run `echo $SHELL` it outputs `/bin/bash` and it was pretty clear post-install that zsh was not running, or at least not set to be my default shell (which used to be a part of the installation).

After trying to force the shell by running `zsh` in terminal, it hangs there until cancelled. when I try to source `~/.zshrc` it also hangs in the same way.

It looks like my `$HOME/.oh-my-zsh` folder is correctly installed and all the files do appear. When troubleshooting, I attempted to uninstall and re-install oh-my-zsh but had the same problem occur.

Is anyone else running this on High Sierra, and if so, did you run into something similar? Any workarounds?

THanks!

**Comment by wrecklass** [comment]
Did you try removing .oh-my-zsh and the .zshrc file and starting zsh to see if it would run without the scripts?

**Comment by marklabrecque** [comment]
yes I did. Same issue. I am very interested to know if this related to my recent upgrade to High Sierra or not.

**Comment by ChadTaljaardt** [comment]
I'm running high sierra and not experiencing this issue and i did a fresh install a week ago.

**Comment by marklabrecque** [comment]
Just to follow up on this one, I believe that this installation is actually working on High Sierra, but for some reason my $SHELL env variable is still being set to the default of `/bin/bash`, even though it is clear on using it that it is using zsh (and does in fact load the .zshrc file on a new process). This might just be a case of the env variable not being updated, which is not a huge deal but can be misleading for users.

I will also add that on certain High Sierra machines I've updated (at various time intervals since it's release) this problem does not exhibit at all and works exactly as expected, even reporting the correct $SHELL. Doesn't seem to be a rhyme or reason as to why it does or doesn't install the same way each time.

Anyways, I will close this issue for now and people with similar issues can source this in the future.

Thanks!
