### ISSUE TITLE
Issues with open_command

### ISSUE THREAD

**Issue by shivarajagopal** [robbyrussell/oh-my-zsh#6511]
I'm trying to use the jira plugin, but every time I do, I get this:
`jira:73: command not found: open_command`

The only way I've figured out to fix it is sourcing `oh-my-zsh/lib/functions.zsh` explicitly. Is there a better way of doing this? I feel like I shouldn't have to explicitly source things in the functions file, but even if I do, I figured there's a better way than explicitly sourcing it. 

Pardon my n00b levels. Thanks in advance, and happy holidays.

**Comment by mcornella** [comment]
You must have a broken OMZ installation. Try `upgrade_oh_my_zsh` or look at the file permissions in the `$ZSH/lib` directory.
