### ISSUE TITLE
when pressing tab to auto-complete, font colour changes, ... why??

### ISSUE THREAD

**Issue by silky** [robbyrussell/oh-my-zsh#6521]
so i'm struggling with some frustrating behaviour i can't find any information on.

if i have some files with a common prefix, then i autocomplete some command on them, like "cat ..." i get my font changing colour:

![image](https://user-images.githubusercontent.com/129525/34459346-fda3de70-ee41-11e7-9659-f030329f630c.png)

why?  and how can i change this?

it isn't a colour defined by my terminal, nor is it in my .zshrc or in my particular colour theme

i'm using zgen, so i have this:

```
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"

# load zgen
source "$HOME/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/command-not-found
  # zgen load silky/noon.zsh-theme noon.zsh-theme
  zgen load /home/noon/dev/noon.zsh-theme/noon.zsh-theme
  
  # generate the init script from plugins above
  zgen save
fi
```

where the colour scheme is exactly this one: https://github.com/silky/noon.zsh-theme/blob/master/noon-light.zsh-theme

any tips would be really appreciated!

**Comment by mcornella** [comment]
I substituted the last `$reset_color` in the `PROMPT` for `%f` which does basically the same thing and it started working again. I don't know, some weird variable scope issue or something like that.
