### ISSUE TITLE
gradle plugin should support kotlin gradle build files

### ISSUE THREAD

**Issue by dharrigan** [robbyrussell/oh-my-zsh#6528]
Currently it doesn't, so it can't generate the autocomplete for task names.

PR coming shortly.

**Comment by Xerus2000** [comment]
actually, this is not sufficient. it should work the same as gradle does - base itself on the settings.gradle file. That one is the only requirement for Gradle to recognise the directory as a place where Gradle is installed. Within the settings.gradle, a whole other buildfile name may actually be specified, which is not that unlikely for bigger projects.

**Comment by dharrigan** [comment]
PR's welcome :-)

**Comment by mcornella** [comment]
For the time being @dharrigan's solution is OK.
