### ISSUE TITLE
How to change on-my-zsh; the color of the background when switching directories

### ISSUE THREAD

**Issue by penhauer-xiao** [robbyrussell/oh-my-zsh#6535]
When you press tab to select the directory, the directory background is not clear, I do not know where to modify the configuration.

![image](https://user-images.githubusercontent.com/6280121/34646318-d4ffd9d4-f39f-11e7-888e-146b96116d5d.png)

The theme is as follows
```
PROMPT='%{$fg_bold[yellow]%}$%{$fg_bold[blue]%}$(git_prompt_info)%{$reset_color%} '
RPROMPT='%{$fg_bold[cyan]%}[%{$fg_bold[yellow]%}%~%{$fg_bold[cyan]%}]%{$fg_bold[cyan]%}[%{$fg[red]%}%*%{$fg_bold[cyan]%}]%{$reset_color%}'
```

**Comment by joeycozza** [comment]
You can either choose different prebuild theme https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

or you can customize an existing theme by following the steps here. https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

As for your specific question though, I'm not sure which variable to edit for the background of a suggested or proposed input. Sorry.

**Comment by mcornella** [comment]
This is configured via variable `LS_COLOR` or `LSCOLOR`, depending on the version of ls you're using (GNU version uses the first one). Look it up to see how to change directory background colors.
