### ISSUE TITLE
Opening existing issue doesn't work as expected

### ISSUE THREAD

**Issue by Zoniso** [robbyrussell/oh-my-zsh#6538]
When I try to open an existing issue I have to use:
jira -XXXX (issue number)
then it seems like it opens it for a sec and replaced by a blank search page ...
any idea how to fix?
http://prntscr.com/hxwp1r

**Comment by head1328** [comment]
try with JIRA_RAPID_BOARD=false (default setting)

**Comment by Zoniso** [comment]
Thanks, it worked
