### ISSUE TITLE
cd .. completion not working

### ISSUE THREAD

**Issue by paweloque** [robbyrussell/oh-my-zsh#6543]
I just installed oh my zsh on a new machine and the 'cd ..' completion is not working. All the other directory and filename completions work properly, but when I type 'cd ..' no proposals for directories in the upper directory are provided. Before installin ohmyzsh, on bash the completion worked properly. 

I'm on a Macbook Pro 13'' touchbar with High Sierra 10.13.2 .

**Comment by evberrypi** [comment]
That is interesting that it is not working with the `cd `prefix. 
Is it still failing when you type in just `..` ?

**Comment by paweloque** [comment]
It doesn't work neither with the '..' shortcut.. Do you have any ideas how to analyse the problem?

**Comment by rene-demonsters** [comment]
Use `../`, it will suggest from the upper level

**Comment by joeycozza** [comment]
My only insight is that it does give you proposals if you type ```cd ../```. Maybe it has to do with the fact that there is an alias for ```...``` and ```....``` so it can't expand or give suggestions? Not really sure.

**Comment by paweloque** [comment]
In deed, the cd ../ works like expected. Funny though, that it used to work.. But it's okay now.

**Comment by joeycozza** [comment]
Looks like it is here . https://github.com/robbyrussell/oh-my-zsh/blob/3705d47bb3f3229234cba992320eadc97a221caf/lib/directories.zsh

You could delete those lines from your .oh-my-zsh/lib/directories.zsh file for testing. If removing them does help ```cd ..``` to give completion, then you could follow the steps here https://github.com/robbyrussell/oh-my-zsh/wiki/Customization to more fully remove the alias for your use case. If that doesn't make sense, let me know and I can explain it further.

**Comment by paweloque** [comment]
I've uncommented the '...' '....' etc aliases, but the completion still doesn't work like before. Interestingly there is no '..' alias in this file. Do you have the '..' alias in your lib/directories.zsh file?
Is it something built in?

**Comment by joeycozza** [comment]
Dang. Bummer that didn't work.  
Also, when I just run ```alias``` to get a list of all aliases that are set, it doesn't even have ".." as an alias. So the double period must be some built in behavior somewhere else, but I couldn't find it. Sorry man.

**Comment by paweloque** [comment]
No Problem @joeycozza . You helped me already a lot by telling to try '../'
Thanks!

**Comment by mathewmeconry** [comment]
same issue with Fedora 27 and the latest version of oh my zsh

**Comment by mcornella** [comment]
This will fix it: `zstyle ':completion:*' special-dirs true`. We could have that pulled in OMZ though.

**Comment by mcornella** [comment]
As a matter of fact, this was asked already in https://github.com/robbyrussell/oh-my-zsh/issues/3775. I'll make a quick PR.
