### ISSUE TITLE
If the directory permissions is 777, CD command is optional, the color is not friendly, too ugly, is there any way?

### ISSUE THREAD

**Issue by penhauer-xiao** [robbyrussell/oh-my-zsh#6544]
If the directory permissions is 777, CD command is optional, the color is not friendly, too ugly, is there any way?

![image](https://user-images.githubusercontent.com/6280121/34867822-83fa561a-f7bc-11e7-9ed7-468a27b38843.png)

**Comment by joeycozza** [comment]
You can choose a different/better theme with instructions here. https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

If you want to do some deeper customization, you can follow the link for instructions how. https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

**Comment by mcornella** [comment]
You need to change the `dircolors` file.

**Comment by inselberg** [comment]
LS_COLORS+=':ow=01;37;40'
or
 LS_COLORS+=':di=01;37;40'
