### ISSUE TITLE
Slow command execution

### ISSUE THREAD

**Issue by lukaszog** [robbyrussell/oh-my-zsh#6545]
Hi,
I'm using Windows 10 with WSL VcxServer and Gnome Terminal. Yesterday I installed oh my zsh and fonts. Everything working good and fast, next I add powerlevel9k as a theme to my .zshrc after this execution of commands has slowed down, the prompt is loading for a long time. Why? Can I fix it?
![longloading](https://user-images.githubusercontent.com/5604018/34872754-807d2f8c-f792-11e7-9e66-8c3e878b4204.gif)

**Comment by lukaszog** [comment]
Anyone can help me?

**Comment by saishsali** [comment]
I'm too facing the same issue. Any fix on this?

**Comment by mcornella** [comment]
powerlevel9k is not supported by OMZ.
