### ISSUE TITLE
Break powerline on context prompt

### ISSUE THREAD

**Issue by myugan** [robbyrussell/oh-my-zsh#6549]
![image](https://user-images.githubusercontent.com/20453528/34907640-5b1fd6c2-f8b4-11e7-9638-01f4472854be.png)

I only change the context with add following lines to .zshrc: 
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='background'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='foreground'

**Comment by mcornella** [comment]
We don't support [Powerlevel9k](https://github.com/bhilburn/powerlevel9k).
