### ISSUE TITLE
Setting window title to remote hostname and not to "ssh"

### ISSUE THREAD

**Issue by antenore** [robbyrussell/oh-my-zsh#6553]
I've the latest version of oh-my-zsh with zsh 5.3.1 (x86_64-redhat-linux-gnu) and the same behaviour on Arch Linux. I only use tmux with suckles simple terminal (st).

When I connect to a remote host the window title is renamed to ssh, I'd like to set it the remote hostname. I've tried some different things, like:

```sh
printf "\033k$(hostname)\033\\"
```
In the remote bashrc (have to use bash in the remote server, sorry)

But than when I logout the window title is not updated, so it keeps using the remote hostname as title (I didn't disable the automatic title).

I'm sure it's not a bug this, but I cannot find out how to workaround this...

I've tried also to set an ssh function like this one

```sh
ssh() {
    if [ "$(ps -p $(ps -p $$ -o ppid=) -o comm=)" = "tmux" ]; then
        tmux rename-window "$(echo $* | awk '{print $NF}')"
        command ssh "$@"
        tmux set-window-option automatic-rename "on" 1>/dev/null
    else
        command ssh "$@"
    fi
}
```
But it doesn't work at all.

Thanks a lot!!!!

**Comment by LuD1161** [comment]
@antenore 
Either I've misunderstood your issue or I'm unable to reproduce it on my terminal. 
Please check this.

![image](https://user-images.githubusercontent.com/17861054/35038059-83990676-fb9f-11e7-8df5-1f35ed5a1dd1.png)
Perhaps this is what you aren't getting on your terminal ?

**Comment by rkmax** [comment]
I also unable to reproduce, asap I did enter into some ssh host the title changes and restore when exit

**Comment by antenore** [comment]
Weird... I'll check later or Monday.
Thanks for answering

**Comment by antenore** [comment]
It looks like a problem of my configuration in tmux and not with oh-my-zsh

Do you prefer to close this or do you want I'll update this as soon as I'll have a fix?
