### ISSUE TITLE
remove the prompt `date/time` on the right

### ISSUE THREAD

**Issue by hongliang5316** [robbyrussell/oh-my-zsh#6557]
Hello

Can i remove the prompt `date/time` on the right?
Anyone can help me? Thanks

**Comment by joeycozza** [comment]
It is definitely possible.
You can choose your theme from a HUGE list of custom themes. https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

Or if you are already using one that you like and you only want to take away the date/time in the right side, you can follow the instructions here to copy the theme you like, and tweak it a little and make oh-my-zsh use your newly tweaked theme. https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

**Comment by hongliang5316** [comment]
@joeycozza 
Thanks for you answer! oh-my-zsh is a very nice job 👍
