### ISSUE TITLE
Fonts are not displayed correctly

### ISSUE THREAD

**Issue by i-panov** [robbyrussell/oh-my-zsh#6561]
I tried the avit and agnoster themes, but the fonts everywhere are displayed incorrectly. Powerline fonts installed. 

![img-2018-01-19-17-24-02](https://user-images.githubusercontent.com/16288735/35155113-b3c5565c-fd3d-11e7-8132-65db88f5451f.png)
![img-2018-01-19-17-23-08](https://user-images.githubusercontent.com/16288735/35155112-b39d3d20-fd3d-11e7-9dfd-53d1269182f9.png)

Help me correct this please!

P.S. Windows 7, Putty terminal emulator (SSH to remote server with CentOS 6.9 and oh-my-zsh).

**Comment by guneemwelloeux** [comment]
Is your putty correctly configured to receive UTF-8 (in the Window > Translation option panel)?
Also, the font in the screenshots awfully looks like Courier New to me. Are you sure you changed the font in Putty to the one that handles Powerline symbols? (Window > Appearance)

**Comment by i-panov** [comment]
@guneemwelloeux 
![img-2018-01-22-13-09-49](https://user-images.githubusercontent.com/16288735/35215581-bf1bba98-ff75-11e7-901d-ece526f29984.png)
![img-2018-01-22-13-10-16](https://user-images.githubusercontent.com/16288735/35215583-bf3f1358-ff75-11e7-891a-ef59f9824b30.png)

**Comment by guneemwelloeux** [comment]
Indeed, your font setting says: `Courier New, 10-point`. Changing that to the Powerline-compatible font that you have installed should help.

**Comment by i-panov** [comment]
@guneemwelloeux But which fonts are compatible with powerline fonts? In general, it seems to me that the problem is not on the client, but on the server where oh-my-zsh is installed.

**Comment by guneemwelloeux** [comment]
Since you said "Powerline fonts installed", I imagined that you knew which ones.
I chose to use `Incolsolata 12-point`, which you can download from here: https://github.com/powerline/fonts/tree/master/Inconsolata. But any of the fonts in that repo should do the trick.

**Comment by i-panov** [comment]
@guneemwelloeux I installed it, but unfortunately I can not select this font in Putty. Writes that it is not found. :(

**Comment by i-panov** [comment]
Apparently oh-my-zsh is not intended for Windows users. Unfortunately, deleted it.

**Comment by guneemwelloeux** [comment]
I use OhMyZsh very happily from within Putty on Windows.

To get Inconsolata to show up in the Fonts menu however, you need to tell windows that the font is "terminal compatible". (Now that I think of it, I remember doing something similar)

I found this gist that could help:
https://gist.github.com/fearthecowboy/ff05b744df1916349d04

**Comment by i-panov** [comment]
FUUUUUUUUUUUUCK!!!!!!! I tried to reinstall oh-my-zsh and it overwrote my .zshrc... You should warn about this on the page where the installation process is described!!! I had very important lines there, which I now simply can not remember...

**Comment by i-panov** [comment]
And all the same the command resulted or brought under the link a problem has not solved. And now I have to remember what happened in .zshrc. :(

**Comment by i-panov** [comment]
Fuh... After the repeated deletion of oh-my-zsh, my .zshrc was restored ... Hallelujah!

**Comment by kelvin-273** [comment]
That was rollercoaster haha, gg good save though
