### ISSUE TITLE
Plugin: Forklift gets an error while executing, because of new version of Forklift?

### ISSUE THREAD

**Issue by sreher** [robbyrussell/oh-my-zsh#6565]
@bitboxer I use Forklift in the Version 3. Maybe that is the reason, why I get this error, when I try to use Forklift in the command shell with this Plugin (https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/forklift):

`227:231: execution error: „Finder“ hat einen Fehler erhalten: Parameterfehler. (-50)`

**Comment by bitboxer** [comment]
You can find a PR that fixes it here: https://github.com/robbyrussell/oh-my-zsh/pull/6490 .
