### ISSUE TITLE
new Feature :- One must be able to change the line spacing in the terminal using ohzmyzsh for better readability.

### ISSUE THREAD

**Issue by nadeem09wani** [robbyrussell/oh-my-zsh#6573]
i am great fan since i a have used ohmyzsh, i am using terminator as my terminal emulator on debian, ti would love to have a feature to change / edit line spacing to improve better readability of the terminal.  @mcornella @robbyrussell @apjanke @ncanceill

**Comment by apjanke** [comment]
As far as I know, line spacing is just a terminal emulator setting; there's nothing the shell running inside it can do about it. So this seems out of scope for oh-my-zsh.

**Comment by nadeem09wani** [comment]
okay , thanks for replying.. i need some advices on pull requests , as i am begineer to oss(open source software).. what resources to look for ..

**Comment by nadeem09wani** [comment]
i am leaving issue open for discussion, for time being, as i feel i am in good place to learn from mentors like you, hope u dont mind , if u want me to remove the issue i will .
