### ISSUE TITLE
command not found env_default

### ISSUE THREAD

**Issue by stardiviner** [robbyrussell/oh-my-zsh#6582]
I got issue on `env_default`, seems it the `misc.zsh` is loaded before `functions.zsh` (which define `env_default`).

![image](https://user-images.githubusercontent.com/378699/35545904-69ec5ab8-05ac-11e8-83e0-4622a89ce6b9.png)

**Comment by stardiviner** [comment]
It's been a long time of this issue. Anybody knows how to solve this problem.

**Comment by mcornella** [comment]
What do you get running `print -l $ZSH/lib/*.zsh`? Also, what does `locale` print?

**Comment by stardiviner** [comment]
```
print -l $ZSH/lib/*.zsh
/home/stardiviner/.oh-my-zsh/lib/bzr.zsh
/home/stardiviner/.oh-my-zsh/lib/clipboard.zsh
/home/stardiviner/.oh-my-zsh/lib/compfix.zsh
/home/stardiviner/.oh-my-zsh/lib/completion.zsh
/home/stardiviner/.oh-my-zsh/lib/correction.zsh
/home/stardiviner/.oh-my-zsh/lib/diagnostics.zsh
/home/stardiviner/.oh-my-zsh/lib/directories.zsh
/home/stardiviner/.oh-my-zsh/lib/functions.zsh
/home/stardiviner/.oh-my-zsh/lib/git.zsh
/home/stardiviner/.oh-my-zsh/lib/grep.zsh
/home/stardiviner/.oh-my-zsh/lib/history.zsh
/home/stardiviner/.oh-my-zsh/lib/key-bindings.zsh
/home/stardiviner/.oh-my-zsh/lib/misc.zsh
/home/stardiviner/.oh-my-zsh/lib/nvm.zsh
/home/stardiviner/.oh-my-zsh/lib/prompt_info_functions.zsh
/home/stardiviner/.oh-my-zsh/lib/spectrum.zsh
/home/stardiviner/.oh-my-zsh/lib/termsupport.zsh
/home/stardiviner/.oh-my-zsh/lib/theme-and-appearance.zsh
```

```
locale
LANG=zh_CN.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by mcornella** [comment]
The order of print seems to work. Is it possible that you have a file at `$ZSH_CUSTOM/lib`?

**Comment by stardiviner** [comment]
Yes I have two files `aliases.zsh` and `functions.zsh` under `$ZSH_CUSTOM/lib/`.

**Comment by mcornella** [comment]
Then the functions.zsh file in your custom folder is overriding the functions.zsh file in lib, therefore it is not being sourced.

Either delete the custom one or source the functions file in lib to get the env_default function.

**Comment by stardiviner** [comment]
@mcornella Thanks for your help!

**Comment by wlarch** [comment]
Greetings, I am having the exact same problem. I have no custom functions.zsh or script in the $ZSH_CUSTOM/lib folder. 

```print -l $ZSH/lib/*.zsh
/home/will/.oh-my-zsh/lib/bzr.zsh
/home/will/.oh-my-zsh/lib/clipboard.zsh
/home/will/.oh-my-zsh/lib/cli.zsh
/home/will/.oh-my-zsh/lib/compfix.zsh
/home/will/.oh-my-zsh/lib/completion.zsh
/home/will/.oh-my-zsh/lib/correction.zsh
/home/will/.oh-my-zsh/lib/diagnostics.zsh
/home/will/.oh-my-zsh/lib/directories.zsh
/home/will/.oh-my-zsh/lib/functions.zsh
/home/will/.oh-my-zsh/lib/git.zsh
/home/will/.oh-my-zsh/lib/grep.zsh
/home/will/.oh-my-zsh/lib/history.zsh
/home/will/.oh-my-zsh/lib/key-bindings.zsh
/home/will/.oh-my-zsh/lib/misc.zsh
/home/will/.oh-my-zsh/lib/nvm.zsh
/home/will/.oh-my-zsh/lib/prompt_info_functions.zsh
/home/will/.oh-my-zsh/lib/spectrum.zsh
/home/will/.oh-my-zsh/lib/termsupport.zsh
/home/will/.oh-my-zsh/lib/theme-and-appearance.zsh
❯ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

Any insight on this ?

**Comment by mcornella** [comment]
Run `zsh -xvic exit &>~/omz-debug.log` and post the `omz-debug.log` file.

**Comment by wlarch** [comment]
Thanks for your message. Here is the result :
[omz-debug.log](https://github.com/ohmyzsh/ohmyzsh/files/5227231/omz-debug.log)

**Comment by mcornella** [comment]
It looks like both `cli.zsh` and `functions.zsh` are empty. Go into the ohmyzsh folder and run a git status to see if the modification appears there. If you haven't made any modifications to the folder, you can safely run `git reset --hard master` to go back to a working state.

**Comment by wlarch** [comment]
Thanks @mcornella. It seems I had corrupt files / loose objects in .git/objects/. I simply pulled the master branch and everything is back to normal.

**Comment by Thomas-wagon** [comment]
Hi guys,

**Comment by mcornella** [comment]
Did you run the git reset command as root?

**Comment by Thomas-wagon** [comment]
I did this :

**Comment by mcornella** [comment]
I'd advise you to reinstall OMZ instead of trying to fix the repository folder. You'll have an easier time.

**Comment by Thomas-wagon** [comment]
that what I thought too. thank you @mcornella.
