### ISSUE TITLE
Indiscernible color for directories in `ls` output under Agnoster theme

### ISSUE THREAD

**Issue by x-ji** [robbyrussell/oh-my-zsh#6583]
I thought this would be a common issue faced by many users but after a quick search I don't seem to have found any previous posts on this. Basically, the directories in `ls` outputs under Agnoster theme would have a green-yellowish highlight background, which is very similar to the blue font color used. The result is that the directory names are hardly discernible. This screenshots demonstrate the issue:

<img width="403" alt="screenshot_20180130_100901" src="https://user-images.githubusercontent.com/2999209/35557742-49c07fe0-05a6-11e8-8dbc-1864d2b5b1be.png">

<img width="403" alt="screenshot_20180130_101530" src="https://user-images.githubusercontent.com/2999209/35557806-867e3eae-05a6-11e8-9b6a-000d87e3a2c5.png">

Weirdly I never encountered this issue before. Only after installing `oh-my-zsh` in two new systems did this problem start to occur.

It happened on both `Terminator` and `Konsole`, using the `Solarized` color scheme.

**Comment by mrGexogen** [comment]
same for me

**Comment by mrGexogen** [comment]
I listed all terminal's colors using script from https://askubuntu.com/a/17300 and found problem.
This is LS_COLORS'es OTHER_WRITABLE (ow) variable.
`echo $LS_COLORS` said that `ow=34;42`

Greping on .oh-my-zsh said nothing, that means LS_COLORS has default values.
Fast google brought me `dircolors` utility - OMZ use it in `~/.zshrc.pre-oh-my-zsh`.
dircolors gets default values from a precompiled database which contains (ta-dam!) 
`OTHER_WRITABLE 34;42 # dir that is other-writable (o+w) and not sticky`
This color which what we see on your screenshot: blue font on green background.

Fast fix for me (white font on green background):
`echo "LS_COLORS=$LS_COLORS:'ow=37;42:'"  >> ~/.zshrc`

**Comment by mcornella** [comment]
Try running without OMZ with `zsh -f`, check the coloring there and run `echo $LS_COLORS` to see the values you get. If these are good you can put them in your zshrc file.

OMZ uses the default `dircolors -b` values if `$LS_COLORS` is undefined, so that ls always shows colored output. I'm afraid we can't do more to fix these kinds of problems.
