### ISSUE TITLE
[bug] builtin command

### ISSUE THREAD

**Issue by Flayor** [robbyrussell/oh-my-zsh#6588]
Hi

They're a bug with this command : 
`which which`
I got this error `which: shell built-in command`

Thanks

**Comment by folixg** [comment]
That is not an error. As you can see in the [zsh docs](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html), `which` is a built-in command in zsh.

**Comment by Flayor** [comment]
Oh ok by bad
