### ISSUE TITLE
Why my terminal so slow `cd` in a huge git repository

### ISSUE THREAD

**Issue by 10cl** [robbyrussell/oh-my-zsh#6591]
When I entered an old Android project, it was a huge git repository. I just enter `cd xxx` , It will take me a long time to go in. I want to know how to reconfigure it make it fast. thanks.

**Comment by nguymin4** [comment]
I agree it's very slow.

**Comment by developer-jason** [comment]
also same here..

**Comment by mcornella** [comment]
Duplicate of #3009.
