### ISSUE TITLE
ZSH git clone and curl issues

### ISSUE THREAD

**Issue by Akilsrin** [robbyrussell/oh-my-zsh#6596]
Whenever I try to use curl with zsh aliases, it doesn't do what it's intended to. Instead of getting an attachment it downloads an add.zip file. When I open add.zip it creates an add.zip.cpgz file. And this goes on continuously. The alias I created is: 
getdata(){curl -s -O --negotiate -u : -H "X-Download-All: true" "thesiteineedtopulldatafrom.com/"$1"/attachments/"$1".zip"}

The same issue happens when I try to use git with zsh. Whenever I try to git clone and gitlab/github repo -> it creates a clone.zip with no content and recursively recreates clone.zip1, clone.zip2 when i try to open the zip.

Has anyone else seen this error and what could i do to resolve this?
It's extremely inconvenient since I need to keep switching back to bashrc every time I want to work with git or curl. I've tried uninstalling and reinstalling zsh but this persists across multiple machines.

thanks

**Comment by mcornella** [comment]
That is super weird. You can enable trace mode to see what zsh is actually running, with `set -xv`. Then reproduce your issue and post the output. You can disable trace mode with `set +xv`.
