### ISSUE TITLE
A few issues, including failed attempts at changing theme

### ISSUE THREAD

**Issue by rvergnau** [robbyrussell/oh-my-zsh#6597]
A few items:

When I open my terminal, I get the following line read to me before the input line:
/Users/rafaelvergnaud/.zshrc:export:96: not valid in this context: -w

Relevant history history:
   30 export ZSH=/Users/rafaelvergnaud/.oh-my-zsh
   34  mkdir ~/bin
   35  ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" ~/bin/subl
   36  echo 'export PATH=$PATH:$HOME/bin' >> ~/.zshrc
   37  echo "export EDITOR='subl' -w" >> ~/.zshrc
   46  ls -l oh.my.zsh
   47  /usr/local/bin
   48  ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" subl\n
   82  echo 'export PATH=$PATH:$HOME/bin' >> ~/.zshrc
   83  echo "export EDITOR='subl' -w" >> ~/.zshrc
   86  export PATH=$PATH:$HOME/bin

I am new to all this and I'm not sure what I did or how to fix it.

--------------------

Moreover, I do not actually find ~./zshrc in my home directory.
I do get
                   **-rw-r--r--  1 rafaelvergnaud  staff  3236 Feb  2 21:53 .zshrc**
when I type in the command
                **ls -l .zshrc**

If I type subl .zshrc, an empty files comes up.
Moreover, if I use nano, the theme does seem to change, but not to the right one (at least it doesn't match the themes pictured in the github  page).

I have the following written in the nano file:
export ZSH=/Users/rafaelvergnaud/.oh-my-zsh
ZSH_THEME="mh"

**Comment by mcornella** [comment]
This error
```
/Users/rafaelvergnaud/.zshrc:export:96: not valid in this context: -w
```
is due to the fact that you defined your `$EDITOR` wrong:
```
export EDITOR='subl' -w # this is wrong, it should be
export EDITOR='subl -w' # this works
```

* * *

> Moreover, I do not actually find ~./zshrc in my home directory.
It might be because you typed `~./zshrc` instead of `~/.zshrc` (notice where the period is).

* * *

> If I type subl .zshrc, an empty files comes up.
Make sure you're in your home directory

* * *
> Moreover, if I use nano, the theme does seem to change, but not to the right one (at least it doesn't match the themes pictured in the github page).
Some theme screenshots aren't up to date with the current source code. You may also find that you need to change your terminal emulator's color scheme and font to match that one in the screenshot. These aren't automatically changed by OMZ themes.
