### ISSUE TITLE
After cd to other directory than $HOME and back to $HOME, prompt don't show tilde but $HOME full path.

### ISSUE THREAD

**Issue by efade** [robbyrussell/oh-my-zsh#6599]
Pardon me if this seem trivial. But I am not really a power user, just really like zsh and the aesthetic of oh-my-zsh. 
I use Arch Linux, and installed oh-my-zsh with antigen. The title says it all, and I couldn't find any solution through Google.

![2018-02-04-093514_445x86_scrot](https://user-images.githubusercontent.com/22839979/35773785-d42085ea-098e-11e8-828c-2717b99fcd65.png)

**Comment by mcornella** [comment]
What theme are you using?
