### ISSUE TITLE
How to add the docker plugin ?

### ISSUE THREAD

**Issue by Aarbel** [robbyrussell/oh-my-zsh#6602]
https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#docker

There's not git repository to clone in `$ZSH_CUSTOM/plugins/`, how to install it ? Is that still included with oh-my-zsh dependencies ? 

Thanks a lot !

**Comment by Jahhein** [comment]
This zsh plugin comes with plugins with it already. Look through the directories in the plugins folder. There you will find a docker folder with the plugin script. [Link to docker plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/docker)

To add it, in your zshrc file located at `~/.zshrc` , add docker to the plugins variable like below.

`plugins=(git ruby osx docker)`

I added a few extras in that example, you don't need git, ruby, or osx. Just docker.

**Comment by Aarbel** [comment]
thanks @Jahhein, here is why i was confused : (there are two plugins folders)

![image](https://user-images.githubusercontent.com/25119847/35780758-6612c4f8-09e0-11e8-950a-cfab9d9bfa10.png)

![image](https://user-images.githubusercontent.com/25119847/35780773-a9d2de4e-09e0-11e8-9789-d900b02ec7ec.png)

**Comment by Jahhein** [comment]
The `.oh-my-zsh/plugins` directory is the plugins that come with OMZ. The `.oh-my-zsh/custom/plugins` directory is for plugins you might make or find somewhere that you want to add.

The repository has so many people wanting to add themes and plugins, but maintainers can't keep up. So the Custom folder is for your own plugin and theme additions.
