### ISSUE TITLE
Please help, lost .zshrc

### ISSUE THREAD

**Issue by andylaci** [robbyrussell/oh-my-zsh#6604]
Hello, I lost .zshrc file, still have opened one relation in window with old config. Can I somehow `cat config` in memory loaded config? It would really help

**Comment by Jahhein** [comment]
If I understand you correctly, you deleted your zshrc file located in your $HOME directory. 

The below commands can be copy and pasted into the terminal to replace your zshrc to default config and move your previous one (if it exists) as `.zshrc.prev`. Backslashes before commands are to ensure no aliases or functions are used instead.

```shell
\cp $HOME/.zshrc $HOME/.zshrc.prev
\curl https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/templates/zshrc.zsh-template > $HOME/.zshrc
```

**Comment by andylaci** [comment]
thank you for reply 😉
nah, I was really precise in deleting every piece of backup 😄 But thank you, first time it saved me so I was like what can happen, finally rewritten the config in 10 minutes... I realised I don't need those things any more

**Comment by Jahhein** [comment]
Good to hear you got it resolved @andylaci
