### ISSUE TITLE
Option-Left-Arrow and Option-Right-Arrow broken with the new update on Mac OSX

### ISSUE THREAD

**Issue by vchouhan** [robbyrussell/oh-my-zsh#6609]
The last update broke the Options-Left-Arrow and Options-Right-Arrow key on Mac OSX (17E139j). The current action just toggles between previous and last directories and if its a new session it jumps to the new line in whichever director you are in.

<img width="429" alt="screen shot 2018-02-06 at 12 48 53 pm" src="https://user-images.githubusercontent.com/1222739/35875759-47ebd654-0b3e-11e8-8072-460f0c9fffb5.png">
<img width="521" alt="screen shot 2018-02-06 at 12 48 25 pm" src="https://user-images.githubusercontent.com/1222739/35875760-47f65430-0b3e-11e8-9bbd-8005d7aa1d17.png">

**Comment by kobytg17** [comment]
Are you using the dirhistory plugin? I removed it, and it seems to solve the issue

**Comment by vchouhan** [comment]
@kobytg17 Yes. I might have to raise this issue with the Plugin developer. Thanks :)
