### ISSUE TITLE
Missing fonts with powerline fonts installed

### ISSUE THREAD

**Issue by sdrammis** [robbyrussell/oh-my-zsh#6610]
![missing-fonts](https://user-images.githubusercontent.com/5007863/35940109-1f3c2fe0-0c1c-11e8-9a6d-b01aa96be541.png)

For some reason I am missing symbols. I have installed powerline, but when i search for the symbols in the font selector they show up incorrectly as shown on the terminal in the image. I have tried other terminal emulators, such as xfce, and the result is the same.

**Comment by mcornella** [comment]
What does `locale -a` show?

**Comment by sdrammis** [comment]
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
