### ISSUE TITLE
Command shared history but remember last command

### ISSUE THREAD

**Issue by pabloriera** [robbyrussell/oh-my-zsh#6612]
Shared history is great, you won't miss a command. But usually, I need to cancel a process and execute it back again immediately so I would press the up key, half of the time that command is no longer there. I don't know if this could be easily accomplished or is a pain. Thanks

**Comment by mcornella** [comment]
I get the same only if I haven't executed the command yet and I `CTRL`+`C`; if I have pressed enter I can then access it with the up key.

What command is executed when you press up arrow? Look it up by running `bindkey 'UPARROW'`, where `UPARROW` is the sequence displayed when you press `CTRL`+`V`, then the up arrow.
