### ISSUE TITLE
File complete docker-compose to yaml files as well as yml files

### ISSUE THREAD

**Issue by drichards-levtech** [robbyrussell/oh-my-zsh#6614]
Current file completion for `docker-compose` is limited to `.yml` files
Is it possible to get it to match `.yaml` files as well?

`plugins/docker-compose/_docker-compose` line 390 change `-g "*.yml"'` to `-g "*.{yml,yaml}"'`

**Comment by mcornella** [comment]
You need to submit a PR to [the upstream project](https://github.com/docker/compose).
