### ISSUE TITLE
Problem with colorize plugin

### ISSUE THREAD

**Issue by Makishima** [robbyrussell/oh-my-zsh#6616]
Hello
What's wrong with my colorize plugin?
```
> ccat client-configs/make_config.sh
package \'Pygments\' is not installed!
> pip list
pip (8.1.1)
Pygments (2.2.0)
> python --version
Python 2.7.12
```

**Comment by phalanx8** [comment]
maybe pygmentize isnt in your path variable

The Colorize script 
.oh-my-zsh/plugins/colorize.plugin.zsh
colorize_via_pygmentize() {
    if [ ! -x "$(which pygmentize)" ]; then
        echo "package \'pygmentize\' is not installed!"   # IT CHECKS WITH WHICH WHERE IT IS
        return -1
    fi

mine is under /usr/local/bin/

**Comment by Makishima** [comment]
Yes, my bad --- `pip install Pygments` dont put it in path, I should use `apt install python-pygments` or manually add it to path.
