### ISSUE TITLE
ifconfig missing

### ISSUE THREAD

**Issue by msongz** [robbyrussell/oh-my-zsh#6619]
after install oh my zsh, the command 'ifconfig' not found

**Comment by phalanx8** [comment]
by installing oh-my-zsh it replace your old .zshrc with a new one 
so if you set a path in your old .zshrc it removed it 

however ifconfig is in /sbin/ifconfig

**Comment by mcornella** [comment]
Check that you have a valid `$PATH`.

**Comment by AmmarKothari** [comment]
There could be a more helpful message maybe:

in zsh:
```
❯ ifconfig                                                              09:43:19
zsh: command not found: ifconfig
```

in bash:
```
$ ifconfig

Command 'ifconfig' not found, but can be installed with:

sudo apt install net-tools

```

**Comment by mcornella** [comment]
That's a feature provided by the `command-not-found` package. If you have it installed, enable the `command-not-found` plugin.
