### ISSUE TITLE
gulp autocompletion broken

### ISSUE THREAD

**Issue by brianmay** [robbyrussell/oh-my-zsh#6620]
```
function $$gulp_completion {
    compls=$(gulp --tasks-simple 2>/dev/null)

    completions=(${=compls})
    compadd -- $completions
}

compdef $$gulp_completion gulp
```

If I I manually type in ``compdef $$gulp_completion gulp`` then it works.

I added the following lines at the end:

```
echo g: $_comps[gulp]
which compdef
```

This gives me:

```
g:
compdef () {
	
}
```

Which was a little bit surprising.

I am using antigen.

I am wondering if the gulp plugin is using a legacy mechanism for enabling completions?

**Comment by arsham** [comment]
Sadly, I have the same problem with golang plugin.

**Comment by mcornella** [comment]
The function name used `$$` which expands to the process ID of the shell. I've pushed a fix that should work for you. The golang plugin is a separate thing, open a new issue for it.
