### ISSUE TITLE
Git fast autocomplete

### ISSUE THREAD

**Issue by jakub-gonet** [robbyrussell/oh-my-zsh#6623]
How can I force zsh to use unstaged files in `git add` autocompletion? Now I have to write start of filename or `.` for every file in directory. It's quite annoying TBH.

**Comment by steliyan** [comment]
This is especially annoying if you've edited files in different depths and you need to quickly stage a file.

**Comment by mcornella** [comment]
Try with the latest version of the completion, I've merged #7152.
