### ISSUE TITLE
zsh shows verbose debugging information without -xv

### ISSUE THREAD

**Issue by imolorhe** [robbyrussell/oh-my-zsh#6629]
Hello, so I restarted my system after a while. I updated zsh just before that. Now each time I start a zsh shell, I see a whole lot of debugging information, and I'm not using `-xv`. When I used `-xv`, I get even more info but in a different color highlight. I can't see the result of the commands I enter because it gets lost in the logs.

![screen shot 2018-02-16 at 10 39 55 am](https://user-images.githubusercontent.com/4608143/36301754-3ff2f732-1306-11e8-91f1-8c4c90b76015.png)

Any idea how to fix this issue?

**Comment by mcornella** [comment]
It looks like you have tracing enabled for a single function. Look for lines saying
`typeset -f -t something` in your zshrc file and remove them.
