### ISSUE TITLE
Separate instance for different terminal emulators?

### ISSUE THREAD

**Issue by ratskin** [robbyrussell/oh-my-zsh#6633]
Hey there!

I'm currently running with [iTerm](https://www.iterm2.com/) as my terminal emulator and ZSH as my shell. I'm testing out [hyper](https://hyper.is/) as a replacement. Hyper has an option `shell`, which is described as "A path to a custom shell to run when Hyper starts a new session".

I'd love to be able to use a separate instance of ZSH and Oh My Zsh for hyper. Is this functionality implemented and if so how can I use it? I've been looking, but I can't find anything about this.

**Comment by mcornella** [comment]
You would have to make a custom setup for this, either using a separate user or loading a separate zshrc file based on how hyper calls the shell.

Maybe you can run zsh with a custom parameter in Hyper and detect that parameter? Or you could use a symlinked zsh and detect that with `$0`. I don't actually know any solid solutions.
