### ISSUE TITLE
mvn plugin does not show colorized

### ISSUE THREAD

**Issue by andreypp** [robbyrussell/oh-my-zsh#6638]
Hello,
I have been using the mvn plugin but my terminal screen does not get colorized by mvn output (error, success, etc are all grayed and not red/green)

Any ideas?

**Comment by belph** [comment]
Are you running `mvn-color`? By default, the plugin doesn't run `alias mvn="mvn-color"`, but you can do so if you would like it to always run.

**Comment by andreypp** [comment]
@belph thanks for your tip! It's working now.
