### ISSUE TITLE
Updating instead check for update

### ISSUE THREAD

**Issue by Makishima** [robbyrussell/oh-my-zsh#6643]
Hello.
After login oh-my-zsh _asked_ check for updates
`[Oh My Zsh] Would you like to check for updates? [Y/n]: Y`
But if I answer Yes it is goes to download and install them. 

> Updating Oh My Zsh
> remote: Counting objects: 3, done.
> remote: Compressing objects: 100% (1/1), done.
> remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
> Unpacking objects: 100% (3/3), done.
> From https://github.com/robbyrussell/oh-my-zsh
>  * branch            master     -> FETCH_HEAD
>    37c2d0d..2ff9560  master     -> origin/master
>  README.md | 2 +-
>  1 file changed, 1 insertion(+), 1 deletion(-)
> First, rewinding head to replay your work on top of it...
> Fast-forwarded master to 2ff9560ad3fc6a3da256d34d0ba804b01d222293

That's quite unexpected behavior. 

I suggest to divide this into 2 operations - checking for updates AND applying them. Or you can just change prompt text for more accurate its behavior.

**Comment by alexanderwallin** [comment]
I agree with @Makishima. Also, this prompt only appears (correct me if I'm wrong) when there is an update available, so obviously `zsh` has already checked.

Besides that, the features is super useful!
