### ISSUE TITLE
Cannot auto complete apt command

### ISSUE THREAD

**Issue by yn4v4s** [robbyrussell/oh-my-zsh#6659]
When I type `sudo apt remove --` I do not get `--purge` or other options, the same happens with `apt list` and others...

**Comment by mortenscheel** [comment]
+1

**Comment by Jamie-505** [comment]
+1

**Comment by vanushwashere** [comment]
+1

**Comment by dimensi0n** [comment]
I'll take a look at it

**Comment by Jamie-505** [comment]
> I'll take a look at it

nice! good luck!

**Comment by dimensi0n** [comment]
Ok, I took a look at the ubuntu plugin and obviously, there is no flags autocompletion.

**Comment by mcornella** [comment]
apt completion is provided by zsh itself, no need to enable a plugin. What zsh version are you using?

**Comment by delarocka** [comment]
Got the same problem, zsh 5.4.2 (x86_64-ubuntu-linux-gnu). apt autocompletion works for commands, but not for options.

**Comment by mcornella** [comment]
If you run `zsh -f`, then `autoload -U compinit && compinit -i`, does the apt command complete correctly?

**Comment by delarocka** [comment]
Tried `autoload -U compinit && compinit -i`, still no options autocomplete.

**Comment by xPride** [comment]
Same trouble:

```
➜  .oh-my-zsh git:(master) zsh --version
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)

➜  .oh-my-zsh git:(master) LANG=C git pull
Already up to date.

➜  .oh-my-zsh git:(master) git remote -v
origin	https://github.com/robbyrussell/oh-my-zsh.git (fetch)
origin	https://github.com/robbyrussell/oh-my-zsh.git (push)

➜  .oh-my-zsh git:(master) cat /etc/os-release
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

➜  .oh-my-zsh git:(master) uname -a
Linux home-ws 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
.vimrc
```
plugins=(
  git
  zsh-competitions
  docker
)
autoload -U compinit && compinit
```

**Comment by mcornella** [comment]
Ok, this happens across all zsh versions just because zsh doesn't support it. You can ask for it on the [zsh-users mailing list](https://www.zsh.org/mla/).

**Comment by dualscyther** [comment]
@mcornella Fair enough, but isn't providing plugins for completion support one of the goals of this project? Although I admit I have no idea how trivial/non-trivial this particular feature request would be.
