### ISSUE TITLE
Zsh icons broke

### ISSUE THREAD

**Issue by KnownAsDon** [robbyrussell/oh-my-zsh#6663]
I have used arch for so long and I am using manjaro for a while now. It had urxvt customized and eveyrthing looked so good. The terminal the was so great rxvt is a terminal I love so I had neovim I had tmux and so I decided to download zsh. 

Now I am new to zsh, I have only used for 2-3 months and I completly love it but I have encountered a problem: recently I upgraded my packages and I currently am using manjaro i3 and so I have set up a dropdown terminal that auto starts each time I refresh i3. And the update finished I restarted i3 and I saw that my dropdown or scratchpad terminal was not showing the symbols of oh-my-zsh theme, I thought this was just a temporary problem so I did a restart and actually the theme broke on all my terminals. I made a thread in the manjaro forums and they couldn't help me. So I hope that you guys can. 

I am using robbyrussell theme just because It comes by deafult I like it the most and this is the robbyrussell github page. But I want to mention that this error only occurrs with rxvt when I try it with something like sterminal everything is fine. 

Now I haven't changed my Xresources config, I've left like when it came by deafult which looks pretty good to me and I havent even added extra stuff to zshrc because I havent decided to configure it yet it just has the deafult oh-my-zsh config file. Now please if you could help me I'd find it really useful I've searched everywhere but nothing seems to help me.

If you need additional information just reply me and sorry for extra details and again sorry if i made this kinda informal question and last apologise is for my english. 

Rxvt version - 9.22
Zsh version - 5.4.2
Oh-my-zsh version - (Latest that is avaible in aur package oh-my-zsh-git)

**Comment by Antharia** [comment]
Same here.

I installed powerline2 package but it didn't change anything. 
I tried agnoster theme but I still missed symbols.

Manjaro i3 17.1.6
Zsh 5.4.2

**Comment by mcornella** [comment]
What symbols do you mean? Posting a screenshot would help a lot.

**Comment by Antharia** [comment]
@mcornella Since , I tried termite. I've got icons and symbols on termite but not on urxvt. So I guess it's not a zsh issue anymore. (I would like to keep urxvt because of Xresources colors configuration).

**Comment by mcornella** [comment]
You have to make sure to use a Powerline font. There's a [section in the Powerline documentation](http://powerline.readthedocs.io/en/master/tips-and-tricks.html#rxvt-unicode) dedicated to urxvt. Hope this helps!
