### ISSUE TITLE
cd into folders breaks/hangs zsh for minutes using Windows cmd, Powershell, Hyper, and Bash (Ubuntu)

### ISSUE THREAD

**Issue by mortenmoulder** [robbyrussell/oh-my-zsh#6666]
I'm copying this complete issue, which I posted on Stackoverflow almost 24 hours ago, but which I've gotten no answers on, unfortunately. Bear with me:

To clarify which I've tried:

 - Ubuntu bash
 - Hyper
 - Powershell
 - Git bash
 - cmd

I have installed Ubuntu bash on my Windows 10 PC. When I open `ubuntu.exe` up and I type `zsh` after the shell has started, my zsh shell starts up instead, as expected. This is perfectly fine and it does exactly what I want.

The problem: When I do the following sequences:

 1. `cd`
 2. `[TAB]` 
 3. `[ARROW KEYS]` (select an item)
 4. `ENTER`

It should `cd` into that folder. And it does that, but it literally takes over a minute to do so. CTRL+C to cancel does not work.

Now that I'm in that folder, I can clear the console by typing `clear`, so that's what I do:

    user@user-pc > /mnt/c/folder/otherfolder > GIT-REPO > clear

When I type `clear` and hit enter, it takes probably 30+ seconds before it clears the window.

I have tried a bunch of themes and a bunch of terminals/command prompts, but none of them work, not even the default one.

I've installed zsh and oh-my-zsh by doing these commands inside the Ubuntu bash shell:

    sudo apt-get install zsh
    curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

Any idea why this odd behavior happens? It looks like it's zsh, because I can easily `cd` into other folders using all of the above terminals. The problem also happens if I simply `cd /mnt/c/folder/otherfolder/` with and without the trailing slash.

**Comment by deathjest3r** [comment]
If the directory you're ``cd``'ing into contains a git repository it takes a while for the ZSH to figure out the local branch. Especially if you have a big project (e.g. Linux kernel)...

**Comment by mcornella** [comment]
You can `set -xv` to enable verbose zsh and tracing, so that when you press enter you'll see an output of all the commands being run, especially useful to see in which command the shell hangs.

**Comment by lucidvisionlabs** [comment]
is there a way to disable zsh from figuring out the local branch?

**Comment by hamaney** [comment]
is there a way to disable zsh from figuring out the local branch?
