### ISSUE TITLE
There should be a clear option to NOT change my default shell

### ISSUE THREAD

**Issue by mrbig033** [robbyrussell/oh-my-zsh#6672]
I wished to keep bash as default, so I had to press <c-c> to abort the install in the prompt and now I don't know if I skipped some important setting.

**Comment by Bepsii** [comment]
First reinstall, then you could just run `chsh`

**Comment by mrbig033** [comment]
That's cool, thanks. If it's not, may suggest this information is put in the documentation?

**Comment by Bepsii** [comment]
would you mine closing the issue?
