### ISSUE TITLE
plugin for pipenv

### ISSUE THREAD

**Issue by gangleri** [robbyrussell/oh-my-zsh#6679]
[pipenv][1] has command completion for zsh, having a plugin would make it easy and clean to include this in a zshrc file. I've made an attempt to create the plugin at https://github.com/gangleri/oh-my-zsh/tree/pipenv_plugin/plugins/pipenv would this be useful to anyone else?

[1]: https://github.com/pypa/pipenv

**Comment by sergekir** [comment]
It would be great if you add auto `shell` command if `Pipfile` in the current folder and pipenv not activated. Like pipenv plugin for fish.

**Comment by gangleri** [comment]
Ok I'll give that a go

**Comment by gangleri** [comment]
I have updated my plugin to auto-activate when cd into a directory containing a Pipfile

However, when leaving the directory, I have to call `exit` to quit the pipenv shell. Although this deactivates the pipenv shell, it does not change to the new target. I installed fish and its pipenv plugin, and it behaves the same.

My code is at https://github.com/gangleri/oh-my-zsh/blob/pipenv_plugin/plugins/pipenv/pipenv.plugin.zsh should I submit a PR so we can continue the discussion there?

**Comment by metakermit** [comment]
Hoping this gets merged soon. Also, it would be great if there was a more humanly-readable flag indicating the activated pipenv. So e.g. instead of:

```
(pipenv-test-O4-aMSd-) ➜  pipenv-test
```

to skip the hash part and have e.g.

```
(pipenv-test) ➜  pipenv-test
```

**Comment by metakermit** [comment]
Actually after looking at the source, some `-`-splitting just to get rid of the hash suffix in the virtualenv prompt info would probably be a bit too fragile. Maybe if pipenv itself was updated to not include hyphens in the suffix it would be possible…

**Comment by mcornella** [comment]
Closing this one. Let's continue the discussion in the PR.

**Comment by tschaub** [comment]
> However, when leaving the directory, I have to call `exit` to quit the pipenv shell. Although this deactivates the pipenv shell, it does not change to the new target

I have proposed #9206 as a way to exit the shell when changing directories.

**Comment by wbmcdonald4** [comment]
I'm having issues with pipenv activating when I open a new terminal instance which is already in a directory containing a Pipfile. If I cd into the folder it works fine. When I open the directory containing the Pipfile directly with terminal, I am getting the following error:
...
```
.pyenv/versions/3.7.5/lib/python3.7/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 788, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (19, 'Operation not supported by device')

```
Not sure if this is because I am using pyenv or something, went pretty deep into the source code and was unable to resolve it.

**Comment by chmod77** [comment]
> I'm having issues with pipenv activating when I open a new terminal instance which is already in a directory containing a Pipfile. If I cd into the folder it works fine. When I open the directory containing the Pipfile directly with terminal, I am getting the following error:
> ...
> 
> ```
> .pyenv/versions/3.7.5/lib/python3.7/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 788, in interact
>     mode = tty.tcgetattr(self.STDIN_FILENO)
> termios.error: (19, 'Operation not supported by device')
> ```
> 
> Not sure if this is because I am using pyenv or something, went pretty deep into the source code and was unable to resolve it.

I am having the same issue on Mac OS + iTerm2
<img width="689" alt="Screenshot 2021-07-03 at 14 49 19" src="https://user-images.githubusercontent.com/44134607/124353211-dae41b80-dc0d-11eb-825c-ad0b64383d80.png">

**Comment by bodgerbarnett** [comment]
I'm seeing the same error. Oddly, it's only happening on my new M1 Mac, not my old one.

**Comment by mcornella** [comment]
Please open a new issue with reproduction steps (preferably with a sample project).
