### ISSUE TITLE
Zsh 5.4 twice as fast, did anyone notice?

### ISSUE THREAD

**Issue by psprint** [robbyrussell/oh-my-zsh#6682]
Not sure if Zsh startup time is a problem with Oh-My-Zsh. However frameworks want to grow and increase their feature-set, so gradual slow down may occur. I have good news: Zsh 5.4 includes optimizations that divide Zsh startup time by 2. I wonder if any Oh-My-Zsh user noticed this?

[Here](https://www.zsh.org/mla/workers/2017/msg01796.html) is link to Zsh mailing list discussion that resulted in the optimization.

**Comment by AnthonyWC** [comment]
Not sure if already implemented but I think async prompt would make a much more noticeable difference to user.

**Comment by mcornella** [comment]
Closing because it's not an issue. The conversation can continue though 😉
