### ISSUE TITLE
Two Yarn Aliases

### ISSUE THREAD

**Issue by gearmobile** [robbyrussell/oh-my-zsh#6686]
yarn install => yi
yarn start => ys

**Comment by ckartchner** [comment]
The suggested yarn aliases would conflict with existing yum aliases.
yi - sudo yum install
ys - yum search

**Comment by bean5** [comment]
@ckartchner I don't know if the yum module runs by default. I think conflicts are okay. Annoying for those who use both, but they could always set up their own aliases to override, right? But then again, @gearmobile probably has these as overrides in `.bash_aliases`.
