### ISSUE TITLE
can't install: destination path already exists and is not  an empty directory.

### ISSUE THREAD

**Issue by cevhyruz** [robbyrussell/oh-my-zsh#6693]
OS: windows 8.1 64bit

I accidentaly killed the terminal process while currently cloning oh-my-zsh with this command
```
git clone git@github.com:robbyrussell/oh-my-zsh.git
```
so I decided to delete the directory and start over again 
```
rm -rf ~/.oh-my-zsh
```
I succesfully deleted the directory  but when I tried cloning this was the output
```
Cloning Oh My Zsh...
fatal: destination path '/home/johnfred/.oh-my-zsh' already exists and is not
an empty directory.
Error: git clone of oh-my-zsh repo failed
```
already checked with with the file explorer and with `ls -a` on the home directory but I can't see any `.oh-my-zsh` directory.  when I try to rename the installation directory it works but for some reason i can't clone it with the default installation directory, any ideas why? btw I'm using bash on cygwin

**Comment by mcornella** [comment]
Is it possible that there is a directory/file named `.oh-my-zsh` in the Windows path?

**Comment by colinli** [comment]
It’s wired the folder doesn’t exist.


________________________________

**Comment by mcornella** [comment]
Make sure to enable seeing hidden files and system files: https://www.laptopmag.com/articles/show-hidden-files-windows

**Comment by chromeragnarok** [comment]
@colinli This happened to me as well. I found out that I have a git installed on my Windows and cygwin was pointing to that git instead of the one that's installed through cygwin.

Make sure the git that's installed on your Windows is uninstalled, restart cygwin and run ```which git``` and verify that it should be pointing to ```/usr/bin/git```. Once confirmed rerun oh-my-zsh installation script again.

**Comment by junyzheng** [comment]
@chromeragnarok Life Saver

**Comment by Karsap268** [comment]
> [@colinli](https://github.com/colinli) This happened to me as well. I found out that I have a git installed on my Windows and cygwin was pointing to that git instead of the one that's installed through cygwin.
> 
> Make sure the git that's installed on your Windows is uninstalled, restart cygwin and run `which git` and verify that it should be pointing to `/usr/bin/git`. Once confirmed rerun oh-my-zsh installation script again.

Didn't work.
