### ISSUE TITLE
sudo bash returning an "zsh compinit" error

### ISSUE THREAD

**Issue by azharizkita** [robbyrussell/oh-my-zsh#6695]
so, like the tittle, im trying to do a `sudo bash` command and it gives me this error message

`zsh compinit: insecure directories and files, run compaudit for list.           
Ignore insecure directories and files and continue [y] or abort compinit [n]?`

and i pressed (n), gives me this error message

`compinit: initialization aborted
_antigen_compinit:1: command not found: compdef`

am i doing something wrong with the installation?
(i am pretty new to Linux command line things)

**Comment by mcornella** [comment]
Can you post the full output of your console when you run that?

**Comment by azharizkita** [comment]
Hi @mcornella , thank you for responding. I just realized that I clearly missed a step on installing git bundles. I'm a fool, but finally everything works :relaxed:
