### ISSUE TITLE
complete:13: command not found: compdef

### ISSUE THREAD

**Issue by dt-rush** [robbyrussell/oh-my-zsh#6700]
I am locked from commenting on the prior issue for this, but I wanted to note that for me, it was due to attempting to initialize nvm at the top of my .zshrc, before sourcing `source $ZSH/oh-my-zsh.sh`.

Here are the lines I used to initialize nvm:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

This issue can be closed or merged somehow into the older one.

**Comment by mcornella** [comment]
Have a look at the solution found in this thread: https://github.com/robbyrussell/oh-my-zsh/issues/6163#issuecomment-315836297.
