### ISSUE TITLE
Golang plugin version printing newline 

### ISSUE THREAD

**Issue by alanpadillachua** [robbyrussell/oh-my-zsh#6705]
Seems that the golang plugin that prints the version of golang is outputting a new line forcing the rest of the prompt to be on the line under. 
As seen in this output. 
![image](https://user-images.githubusercontent.com/22553942/38148382-ebd42978-341b-11e8-82fc-98da122e57a3.png)

**Comment by mcornella** [comment]
The golang plugin only contains completion code and aliases, there is no function showing the go version. Are you sure that's not a custom theme?

**Comment by alanpadillachua** [comment]
No, that could be it. I'll look into that. Thanks!

**Comment by Klein-Hu** [comment]
You could try to check the "code" in the theme file. What I have is something like this:
```
prompt_go() {
  setopt extended_glob
  if [[ (-f *.go(#qN) || -d Godeps || -f glide.yaml) ]]; then
    if command -v go > /dev/null 2>&1; then
      prompt_segment $BULLETTRAIN_GO_BG $BULLETTRAIN_GO_FG $BULLETTRAIN_GO_PREFIX" $(go version | grep --colour=never -oE '[[:digit:]].[[:digit:]]')"
    fi
  fi
}
```
Apparently the problem is in `[[:digit:]].[[:digit:]]`. Change it to `[[:digit:]].[[:digit:]][[:digit:]].[[:digit:]]` for now and you problem will be solved after restart the shell.
