### ISSUE TITLE
Wrong formatting when pasting URLs with parameters

### ISSUE THREAD

**Issue by terencode** [robbyrussell/oh-my-zsh#6706]
1. Copy the following: https://test?test=1?test2=2
2. Paste it in your zsh with oh-my-zsh framework 
3. URL becomes: https://test\?test\=1\?test2\=2

**Comment by mcornella** [comment]
That's the correct format so that you don't need to put the URL in quotes because of the `?` question mark character. If you use it in a command you will notice that it works correctly. If you paste it within quotes you will see the URL is displayed correctly.

**Comment by terencode** [comment]
@mcornella Ah ok, I was putting quotes to use it as a parameter (youtube-dl) and I never bothered trying it without them... Glad to know it's like that for making life easier :smile:
