### ISSUE TITLE
How to install on Tails? 

### ISSUE THREAD

**Issue by alexTitakoff** [robbyrussell/oh-my-zsh#6707]
Hello guys!

It is possible install oh-my-zsh on tails?

thanks

**Comment by mcornella** [comment]
I don't know of anyone who tried it, and I'm not familiar with it. The best way to figure it out is trying 😉

**Comment by mcornella** [comment]
Feel free to reopen if you try it and encounter and issue.

**Comment by cyanlink** [comment]
Google led me here, sorry it's been 2 years. My solution would be: copy _~/.oh-my-zsh_ (to dotfile if you want persistence, btw zsh and some other add-ons are inside Debian repo thus can be persisted as "additional software") and _.zshrc_ from another linux machine, and don't forget to disable update checker (It won't be able to connect to clearnet without Tor anyway)
