### ISSUE TITLE
docker completion breaks when arguments are combined ("-i -t" -> "-it")

### ISSUE THREAD

**Issue by RafalSkolasinski** [robbyrussell/oh-my-zsh#6710]
Normally
```bash
docker run <TAB>
```
lists all available images. 
When more arguments are added like
```bash
docker run --rm -i -t <TAB>
```
it still works properly.

However when one has
```bash
docker run --rm -it <TAB>
``` 
it wants to complete something that definitely is not right:
```bash
➜  ~ docker run --rm -it <TAB>
zsh: do you wish to see all 3866 possibilities (967 lines)? 
 ```

**Comment by kenden** [comment]
@RafalSkolasinski thanks for reporting. 

Combining optional arguments is disabled at the moment, as it has side-effects. See this comment:
https://github.com/moby/moby/pull/17124#issuecomment-150518700

See this issue in the docker repo for more info about this.
https://github.com/docker/cli/issues/993

**Comment by mcornella** [comment]
Closing then, as this is an upstream issue.

**Comment by Daniel451** [comment]
> Combining optional arguments is disabled at the moment, as it has side-effects. See this comment:
> [moby/moby#17124 (comment)](https://github.com/moby/moby/pull/17124#issuecomment-150518700)

It has been over a year now. Did anything change about the side-effects? Combined arguments are still not processed correctly.
