### ISSUE TITLE
$PATH outside the terminal... command not found

### ISSUE THREAD

**Issue by RaitaroH** [robbyrussell/oh-my-zsh#6712]
System: Kde Neon 5.12.4
```
bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```
Oh-my-zsh just installed from github on april 6, 2018.

I have installed zsh, then oh-my-zsh then powerlevel9k.

I `cat ~/.bashrc >> ~/.zshrc` in order to get my aliases and such. Obviously certain things from my .bashrc I had to remove because they had no place in the zshrc. I also have my export path uncommented 'export PATH=$HOME/bin:/usr/local/bin:$PATH'

Now, if I issue a command I have in /home/raitaro/bin it is found and it works alright, because the $PATH is set nicely:
```
echo $PATH
/home/raitaro/torch/install/bin:/home/raitaro/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
Ok, I thought, look it up. I did end up on the arch wiki so I made this .zshprofile
```                                                          
typeset -U path
path=(~/.local/bin $HOME/bin $path[@])
```
I also tried with the .zshenv, tried to just copy the export path from .zshrc... yet again, my path seems fine in the terminal but not outside of it. Login out or restart did not have any improvements at all.

So for example let's take my `waterfox` script that opens waterfox from the home dir. It is found, autocompleted and it works. But outside of the terminal I MUST reference it as `~/bin/waterfox` or otherwise it does not work. I have `waterfox -p PROFILE` as custom entries in my menu... I had to change all of them to the absolute path; creating a new keyboard shurtcut with `waterfox` does nothing, I have to reference it in full.

I also have custom kservice menu entries. They are basically right click menu option. Anything that is in my bin simply shows "Command not found" or doesn't even do anything. Obviously before trying out zsh everything went fine.

**Comment by RaitaroH** [comment]
https://github.com/RaitaroH/Random-Code/blob/master/dot/zshrc

**Comment by RaitaroH** [comment]
Doing:
```
sudo usermod raitaro -s $(which zsh)
```

Then restarting:
```
$PATH
zsh: no such file or directory: /home/raitaro/torch/install/bin:/home/raitaro/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
Those folders exist and besides the last 3 have files in them.

**Comment by mcornella** [comment]
I think `.zshrc` is not loaded on the desktop, you have to set the PATH in `.profile` for it to work outside the terminal. In my case, I have it set up in `.zshenv`, but that is a pure shell script (_i.e._ it works on any shell) and I source it in `.profile`.

**Comment by RaitaroH** [comment]
@mcornella Actually this is my .profile:
```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
if [ -n "$ZSH_VERSION" ]; then
    # include .zshrc if it exists
    if [ -f "$HOME/.zshrc" ]; then
        . "$HOME/.zshrc"
    fi
fi

# set PATH so it includes user's private bin directories
# PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/raitaro/.oh-my-zsh

. /home/raitaro/github/torch/install/bin/torch-activate
```
I also don't have those bash_profile and bash_login files:
```
ls -a | grep zsh
.fzf.zsh
.oh-my-zsh
.zsh_history
.zshrc
.zsh-update

ls -a | grep bash
.bash_history
.bash_logout
.bashrc
.bashrc.save
.fzf.bash
```
