### ISSUE TITLE
Cannot autocomplete

### ISSUE THREAD

**Issue by gongchuncheng** [robbyrussell/oh-my-zsh#6714]
I update my macos to High Sierra, but i can't autocomplete the path by the tap key.

This is the error.

_get_comp_words_by_ref:16: bad substitution

thanks!

**Comment by odusseys** [comment]
I am having the same error, but it only happens when I activate a python virtualenv and try to autocomplete

**Comment by gongchuncheng** [comment]
I have solved this problem.
I update my zsh and Restart my terminal.
I hope i can help you!

**Comment by mcornella** [comment]
Thanks for posting an update. Closing.

**Comment by stevematdavies** [comment]
This should not ba closed, this is still an issue with High Sierra and the latest version of zsh

**Comment by ashwinvidiyala** [comment]
@gongchuncheng That worked for me too. Thanks!
