### ISSUE TITLE
Space after tab completion gone

### ISSUE THREAD

**Issue by mattdavenport** [robbyrussell/oh-my-zsh#6717]
I'm not exactly sure which update this occurred on, or if it was an activated plugin (or perhaps a misconfiguration on my end), but I seem to have lost the great zsh feature of space-on-autocompletion.

Normally, when tab-completing a command (e.g. `docker-com<TAB>`), I would get an extra space for flags/args after the tab-completed command. However I'm no longer getting that. I have noticed this is only on one of my machines, but I can't seem to find where else my prompt or autocomps are altered. Are there any envvars I could check for, or anyone else having this issue?

Thanks!

**Comment by mcornella** [comment]
If I understood correctly, you would have, for instance `docker-com<TAB>` and it would autocomplete to `docker-compose` leaving the cursor right after the final e, instead of leaving a space so you can then enter arguments. Is that it?

**Comment by mcornella** [comment]
Ok, let's see... What `zsh --version` are you using and what's the output of `bindkey '^I'`?

**Comment by mattdavenport** [comment]
```sh
➜  ~ zsh --version && bindkey '^I'
zsh 5.3.1 (x86_64-apple-darwin16.3.0)
"^I" expand-or-complete
```

Thanks!

**Comment by mattdavenport** [comment]
I found the issue. I must have not <TAB>'d once more to find that there is a `docker-compose.backup` command on my dev machine. This is expected behavior, and not an issue anymore. Thanks so much for helping debug @mcornella!

**Comment by mcornella** [comment]
That was easier than expected, I was already starting to pour over the zsh docs looking for clues 😂
