### ISSUE TITLE
zsh 5.5 support

### ISSUE THREAD

**Issue by mbaldessari** [robbyrussell/oh-my-zsh#6718]
Mostly a heads-up for folks.

On F28 zsh just got updated to 5.5 and I get the following errors:
/home/michele/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/michele/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
zsh: compdef: command not found...
...repeated a few more times
zsh: compdef: command not found...
zsh: compdef: command not found...
╭─michele@palahniuk ~   10:10:57
╰─$ 

Downgrading to 5.4.2 makes things dandy again.

**Comment by kruegsch** [comment]
@mbaldessari A restart fixed the issue for me on F28. Directly after the update the FPATH variable was still pointing  to the the 5.4.2 functions directory.

**Comment by batisteo** [comment]
Thanks @kruegsch, I confirm it worked after a reboot. (I haven’t tested with a simple log out).

@mbaldessari Do you think this issue could be closed?

**Comment by mcornella** [comment]
Apparent solution: restart your terminal. Thanks folks.
