### ISSUE TITLE
Powerline font symbols not displayed correctly

### ISSUE THREAD

**Issue by FloLaco** [robbyrussell/oh-my-zsh#6722]
Hello,
I'm connecting on the server by SSH only. There's no GUI or X server available.

I've just installed zsh in my HOME because I've no root access on the server.
Then, I've installed the oh-my-zsh ans set the THEME to `ZSH_THEME="agnoster"`
I've also installed powerline-font : 
```
wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.local/share/fonts/
fc-cache -vf ~/.local/share/fonts/
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
```

Here's the output of my prompt. It seems that I've a problem of symbols.
![image](https://user-images.githubusercontent.com/1486562/38626434-ded8c8a6-3dac-11e8-98ff-8d296b1813c3.png)

```
echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"
zsh: character not in range
```

**Comment by GUiHKX** [comment]
https://github.com/powerline/fonts/issues/242#issuecomment-313530229

**Comment by mcornella** [comment]
@FloLaco what do you get when running `locale`?

**Comment by lazehang** [comment]
https://github.com/powerline/fonts/issues/44#issuecomment-300685004
