### ISSUE TITLE
Not able to choose tab completion options with arrow keys

### ISSUE THREAD

**Issue by frankpeng7** [robbyrussell/oh-my-zsh#6724]
When I enter `cd` and hit `tab` twice, I can see a list of tab completion options and I can select with arrow keys (up/down/left/right). The item I choose will be highlighted. Here is a screenshot of it on my Mac/iTerm
![screen shot 2018-04-11 at 4 48 02 pm](https://user-images.githubusercontent.com/16726609/38648969-effbf6f2-3da8-11e8-8697-e6b499bf25ac.png)
but when I ssh into my server (which is an Amazon EC2 machine and have oh-my-zsh installed), I can still go through the options by pressing `tab` but am not able to see them as a list and choose with arrow keys. The chosen item is not highlighted either.
![screen shot 2018-04-11 at 4 49 06 pm](https://user-images.githubusercontent.com/16726609/38649019-301261f4-3da9-11e8-960b-4978d82dfc2f.png)

I've tried solutions in related issues and they're not working. Any thoughts on this?

**Comment by mcornella** [comment]
You probably don't have OMZ installed on your server, but there's no need anyway: the relevant command that enables that is `zstyle ':completion:*' menu select`.
