### ISSUE TITLE
install duplication messages and antigen compatibility 

### ISSUE THREAD

**Issue by tysun** [robbyrussell/oh-my-zsh#6727]
I have some issues between antigen and zsh and have also posted this same question in the antigen repo since I don't know which one is causing what issues. Thanks. 

1. In order for my spaceship theme to load I need to put it in `.antigen -> themes`. That's fine but there is also an `.antigen -> custom -> themes` folder. For me that doesn't work. I have to copy my custom theme into `.antigen -> themes`. Is there a reason why it doesn't load from the `custom` folder?

2. When I `source ~/.zshrc` Terminal/zsh console returns these errors. So somewhere it's loading them again.

>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!
>Seems zsh-users/zsh-syntax-highlighting is already installed!
>Seems zsh-users/zsh-history-substring-search is already installed!
>Seems zsh-users/zsh-autosuggestions is already installed!
>Seems seebi/dircolors-solarized is already installed!
>Seems robbyrussell/oh-my-zsh is already installed!

I noticed that I have two instances of zsh located in `/usr/local/bin`.  Both a `zsh` and a `zsh-5.5`. Seems to be a system default version and Homebrew version. When I do `zsh --version` it says 1.22.1 which is very old. When I do `brew info zsh` it says `zsh: stable 5.5 (bottled)`. 

3. When I open a new Terminal window it is using the default bash and not defaulting to antigen/zsh. Do the Terminal preference settings matter? i.e. `Shells open with: Default login shell or Command (complete path /bin/zsh)`

==============================================

**.zshrc**
#PATH
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

#Anaconda
export PATH="$HOME/anaconda3/bin:$PATH"

#Homebrew
export PATH=/usr/local/bin:$PATH

#Java
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

#To activate zsh completions from Homebrew installation
fpath=(/usr/local/share/zsh-completions $fpath)

#Activate Antigen
source /usr/local/share/antigen/antigen.zsh

#Load oh-my-zsh's library.
antigen use oh-my-zsh

#Bundles from default repo
antigen bundle pod
antigen bundle pip
antigen bundle git
antigen bundle brew
antigen bundle git-extras
antigen bundle jsontools
antigen bundle last-working-dir
antigen bundle mysql-macports
antigen bundle npm
antigen bundle pyenv
antigen bundle python
antigen bundle pylint
antigen bundle sudo
antigen bundle virtualenvwrapper
antigen bundle virtualenv
antigen bundle web-search
antigen bundle heroku
antigen bundle command-not-found

#Other bundles
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle seebi/dircolors-solarized

#Load theme.
antigen theme spaceship

#Antigen done.
antigen apply

============================================

<img width="467" alt="screen shot 2018-04-14 at 11 49 56 am" src="https://user-images.githubusercontent.com/11150198/38763670-4bd8509a-3fdb-11e8-8d07-0ec52b82811a.png">

<img width="538" alt="screen shot 2018-04-14 at 11 50 52 am" src="https://user-images.githubusercontent.com/11150198/38763934-0ef0dc1e-3fe1-11e8-8f0a-de995ba630f6.png">

**Comment by tysun** [comment]
It seems to be fixed. I had to add these lines at the top of my .zshrc file. Does anyone know why? Because other users have not had to add these lines.  Even when you look at the repo .md install example it doesn't have these lines. 

```
# Path to oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
```

**Comment by ssteinerx** [comment]
@tysun I have been getting the same thing and have tried your suggestion above.  Didn't change anything, hoping to track this down today.

**Comment by ssteinerx** [comment]
Sure would be nice to get a line number or some sort of debugging information to help track this down.

**Comment by mcornella** [comment]
To reload the shell you should use `exec zsh` instead of `source ~/.zshrc`. I'm looking into the rest...

**Comment by mcornella** [comment]
You shouldn't need to add manual sourcing of OMZ to your zshrc file in order for it to work. 

Try setting `ANTIGEN_LOG=~/antigen.log` at the top of your zshrc file and restarting the shell. Then, a log file will be created at $HOME/antigen.log which you can post as a private [gist](https://gist.github.com).

**Comment by mrcsporto** [comment]
I've recently installed node and everytime I open mi zsh terminal it happens:

Last login: Sun May  1 19:57:23 on ttys000
Seems robbyrussell/oh-my-zsh is already installed!
Seems lukechilds/zsh-nvm is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems zsh-users/zsh-syntax-highlighting is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems lukechilds/zsh-nvm is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems zsh-users/zsh-syntax-highlighting is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems lukechilds/zsh-nvm is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems robbyrussell/oh-my-zsh is already installed!
Seems zsh-users/zsh-syntax-highlighting is already installed!
Seems robbyrussell/oh-my-zsh is already installed!

**Comment by mcornella** [comment]
This is an antigen issue. Look for existing issues in https://github.com/zsh-users/antigen/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc and if none is created do [this](https://github.com/ohmyzsh/ohmyzsh/issues/6727#issuecomment-383251122) and post the log in a new issue there.
