### ISSUE TITLE
chsh: PAM: Authentication failure

### ISSUE THREAD

**Issue by enumag** [robbyrussell/oh-my-zsh#6736]
When I try to install oh-my-zsh I get this error. I found [this article](https://medium.com/development-enviroment-setup/how-to-install-oh-my-zsh-on-ubuntu-98b82304e7b) but could not solve it. My `/etc/shells` contains `/usr/bin/zsh` which is also what `which zsh` returns. How am I supposed to install this?

**Comment by mcornella** [comment]
What command are you using to install it? It should be
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```
instead of `curl | sh`.

**Comment by enumag** [comment]
I was using `sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`.

It failed with the error in title on my old PC with Ubuntu 16.04. On new PC with Ubuntu 18.04 it works fine.
