### ISSUE TITLE
zsh: no matches found: issue#354

### ISSUE THREAD

**Issue by qq645381995** [robbyrussell/oh-my-zsh#6738]
![image](https://user-images.githubusercontent.com/7971419/38921185-afca7fb6-4327-11e8-96f1-b038811d88cc.png)

**Comment by mcornella** [comment]
The `#` (hash) character is used in [extended globbing to match filenames](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Operators). You need to put the file in quotes so that zsh doesn't interpret it as a globbing character: `git merge "issue#354"`.
