### ISSUE TITLE
date command return unexpected result

### ISSUE THREAD

**Issue by ReikyZ** [robbyrussell/oh-my-zsh#6742]
~ ➤ zsh --version                                                                                     
zsh 5.3 (x86_64-apple-darwin17.0)
~ ➤ date +%s%N                                                                                        
1524113639N

expected :
date +%s%N
1524113698007063000

**Comment by mcornella** [comment]
`%N` is not a [builtin date format character](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Date-and-time) so its validity depends on the call to strftime, which is system dependent. In the online docs there isn't a valid specification for it: http://man7.org/linux/man-pages/man3/strftime.3.html

What do you expect it to be? I can't figure it out based on your expected output.

**Comment by mcornella** [comment]
Nevermind, I see you were looking for [nanoseconds](https://linux.die.net/man/1/date). It seems your version of `date` doesn't support that: https://apple.stackexchange.com/a/135749.

Not an OMZ issue though, make sure to sort that out before posting an issue here. Thanks!
