### ISSUE TITLE
rkj-repos theme now depends on mercurial / hg prompt to be installed to work

### ISSUE THREAD

**Issue by Lavoaster** [robbyrussell/oh-my-zsh#6743]
As per #6655, the theme was updated to show information on how to enable hg prompt support. However, this has now meant that users that don't have mercurial installed (👋Hii) can no longer use this theme without installing both mercurial and hg prompt.

There are few possible solutions to this:
- Exit, only if mercurial is installed and hg prompt is not found.
- Return an empty string in the `hg_prompt_info` if `hg prompt` is not found.

**Comment by mcornella** [comment]
Good point. I'll push the patch as soon as it's done.
