### ISSUE TITLE
purge nvidia: no matches found

### ISSUE THREAD

**Issue by elmerehbi** [robbyrussell/oh-my-zsh#6748]
I was trying to purge nvidia with: `sudo apt-get purge nvidia*` however I was getting  the following error: `zsh: no matches found: nvidia-*`

The same command works in bash.

**Comment by mcornella** [comment]
Zsh interprets that as trying to search for files that start with nvidia. It's a bit misleading, but you'd have to quote it so that it gets passed as is to the apt-get command: `sudo apt-get purge "nvidia*"`.

**Comment by elmerehbi** [comment]
Thanks
