### ISSUE TITLE
omz_history:fc:15: event not found: -l

### ISSUE THREAD

**Issue by dikiaap** [robbyrussell/oh-my-zsh#6754]
I have a problem here after PR #3422 has been merged. When I type any command in Terminal, it says `omz_history:fc:15: event not found: -l`. I also added `unsetopt hist_verify` to `.zshrc`

**Comment by mcornella** [comment]
That's weird... Can you run `functions -ft omz_history` and post the output when running a command?

**Comment by mcornella** [comment]
#6359 solved your issue. Please update and all will be ok.

**Comment by hacfi** [comment]
@mcornella I updated (on `45a9f284641a23baa142743d8a6136d4e300c465`) but still get this error. Any ideas?

**Comment by mlsimpson** [comment]
I'm having the same issue. I just updated today. I'm using a modification of the half-life theme.

```
+omz_history:3> zparseopts -E 'c=clear' 'l=list'
+omz_history:5> [[ -n '' ]]
+omz_history:9> [[ -n '' ]]
+omz_history:15> fc 9930 -l 1
omz_history:fc:15: event not found: -l
```

**Comment by mlsimpson** [comment]
I found the culprit. It looks like the supplied half-life.theme replaced line 65:

`case "$(history $HISTCMD)" in`
to
`case "$2" in`

Changing the former to the latter in my theme solved the issue.

**Comment by hacfi** [comment]
Thanks..that fixed it for me (thanks as well to @flip111 for the PR to my dotfiles)!
