### ISSUE TITLE
Can you guys remove the po alias for popd?

### ISSUE THREAD

**Issue by nrobinson2000** [robbyrussell/oh-my-zsh#6761]
I am the lead maintainer for [po](https://github.com/nrobinson2000/po), a tool that provides a great command line experience for [Particle](https://www.particle.io/) users.

Many po users are oh-my-zsh users. Those who are oh-my-zsh users annoyed when they are unable to use po because of the `popd` conflict. Several users are not savvy enough with the command line to disable the `po` alias to resolve the conflict, and it pains me to hear from a user that oh-my-zsh is interfering with their Particle workflow.

All I ask is that you no longer make `po` be an alias for `popd`. It conflicts with [po](https://github.com/nrobinson2000/po), and `popd` is a pretty uncommon command. I don't see why it is necessary to make a two letter alias for a four letter command.

Thanks

**Comment by nrobinson2000** [comment]
Ping @mcornella

**Comment by nrobinson2000** [comment]
Bump

**Comment by dimensi0n** [comment]
You can do it 😉 and make a pr

**Comment by nrobinson2000** [comment]
So where are the aliases for oh-my-zsh located in the repo then?

**Comment by dimensi0n** [comment]
Great ;)

**Comment by webknjaz** [comment]
I used `po` for `popd` all the time. It's sad that it has been removed :(

**Comment by nrobinson2000** [comment]
You could make your own alias then.

**Comment by webknjaz** [comment]
Yep. It's just that it wasn't documented and collapsed with adding a third-party plugin, which I thought has broken things for me.
A better way to do removal would be to provide and/or document alternative for the removed feature, at least in changelog. I've spent more time than normally affordable to find this.
