### ISSUE TITLE
Remove git(master) from prompt

### ISSUE THREAD

**Issue by push32** [robbyrussell/oh-my-zsh#6771]
from zsh i'm goes into git 

then my zsh become 
 ~ git:(master) ✗ 

how back to ~ 
anyone please help me

**Comment by mcornella** [comment]
You're running a theme that displays a prompt when it finds itself within a git repository. You could use a different theme that doesn't (see [themes](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes)), or modify your existing theme to remove that part of the prompt. What theme are you using? (run `echo $ZSH_THEME`).

**Comment by push32** [comment]
i'm using the default theme robbyrussell

**Comment by mcornella** [comment]
You can modify the robbyrussell theme and put it in the [custom folder](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes), or just modify the `$PROMPT` variable to remove the `git_prompt_status` variable:
```zsh
# put this in your zshrc file, at the bottom
PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} '
```

**Comment by 0xprashant** [comment]
Hey @mcornella I m facing the same issue but i added 

PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} '
 as you said it will remove the git(master) prompt ,and it really did
But it changed the theme completely.....

#before the changes in ~/.zshrc file
![image](https://user-images.githubusercontent.com/40650455/78903953-d25a6f00-7ab6-11ea-8ca4-8e825de2a0e0.png)

#After the changes in ~/.zshrc file
![image](https://user-images.githubusercontent.com/40650455/78904029-f0c06a80-7ab6-11ea-9d13-9029c250556b.png)

You can see that ➜  and ✗ have been removed 
But i also want to kept them.....
Waiting for your solution

**Comment by mcornella** [comment]
Edited the comment to match the robbyrussell theme, see above.
