### ISSUE TITLE
Unexpected zsh-syntax-highlighting warning when running sudo

### ISSUE THREAD

**Issue by NearAutomata** [robbyrussell/oh-my-zsh#6780]
As described in [this issue](https://github.com/zsh-users/zsh-syntax-highlighting/issues/506#issuecomment-385102737) I am reporting an issue with zsh-syntax-highlighting. When I run `sudo -s` I get the following warning and I have no clue on how to fix it properly:

> zsh-syntax-highlighting: 'README.md' highlighter should define both required functions '_zsh_highlight_highlighter_README.md_paint' and '_zsh_highlight_highlighter_README.md_predicate' in '/Users/near/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/README.md//README.md-highlighter.zsh'.

**Comment by mcornella** [comment]
There is no zsh-syntax-highlighting code in our repository, you're probably bundling it as a custom plugin. But you're probably having a `$ZSH_HIGHLIGHT_HIGHLIGHTERS` setup in your zshrc file that causes this problem, as they said in the other issue. What is your zshrc file?

**Comment by NearAutomata** [comment]
My current zshrc is as follows:

```
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=/Users/near/.oh-my-zsh
ZSH_THEME="agnoster"
DISABLE_AUTO_TITLE="true"
plugins=(zsh-syntax-highlighting gulp)
source $ZSH/oh-my-zsh.sh
export DEFAULT_USER="near"

# Override auto-title when static titles are desired ($ title My new title)
title() { export TITLE_OVERRIDDEN=1; echo -en "\e]0;$*\a"}
# Turn off static titles ($ autotitle)
autotitle() { export TITLE_OVERRIDDEN=0 }; autotitle
# Condition checking if title is overridden
overridden() { [[ $TITLE_OVERRIDDEN == 1 ]]; }
# Echo asterisk if git state is dirty
gitDirty() { [[ $(git status 2> /dev/null | grep -o '\w\+' | tail -n1) != ("clean"|"") ]] && echo "*" }

# Show cwd when shell prompts for input.
tabtitle_precmd() {
   if overridden; then return; fi
   pwd=$(pwd) # Store full path as variable
   cwd=${pwd##*/} # Extract current working dir only
   print -Pn "\e]0;${cwd//$DEFAULT_USER/~}$(gitDirty)\a" # Replace with $pwd to show full path
}
[[ -z $precmd_functions ]] && precmd_functions=()
precmd_functions=($precmd_functions tabtitle_precmd)

# Prepend command (w/o arguments) to cwd while waiting for command to complete.
tabtitle_preexec() {
   if overridden; then return; fi
   printf "\033]0;%s\a" "${1%% *} | ${cwd//$DEFAULT_USER/~}$(gitDirty)" # Omit construct from $1 to show args
}
[[ -z $preexec_functions ]] && preexec_functions=()
preexec_functions=($preexec_functions tabtitle_preexec)
```

**Comment by mcornella** [comment]
Do you have it installed as root? It might be in your root zshrc file...

**Comment by NearAutomata** [comment]
No, since there are no root config files under macOS - at least none that I can find.

**Comment by mcornella** [comment]
Run this: `sudo -s exec zsh -xv 2>~/zsh.log`, then type `exit` and post the resulting `zsh.log` file as a private gist.

**Comment by NearAutomata** [comment]
Here is the dump: https://gist.github.com/NearAutomata/d8a34e0cdb3b1a6b2f2791e3186381b3

**Comment by mcornella** [comment]
Ok you can delete the gist now.

**Comment by mcornella** [comment]
The culprit is this part of zsh-syntax-highlighting:
```zsh
_zsh_highlight_load_highlighters() {
  # ...

  # Load highlighters from highlighters directory and check they define required functions.
  for highlighter_dir ($1/*/); do
    # ...
  done
```
where the `_zsh_highlight_load_highlighters` looks for highlighters (_i.e._ directories) in the passed folder. For some reason that I haven't yet found, zsh sees `highlighters/README.md` as a directory, and tries to load "its highlighters" therefore giving you the error:

```
+/Users/near/.oh-my-zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:374> _zsh_highlight_load_highlighters /Users/near/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters
+_zsh_highlight_load_highlighters:2> setopt localoptions noksharrays
+_zsh_highlight_load_highlighters:5> [[ -d /Users/near/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters ]]
+_zsh_highlight_load_highlighters:11> local highlighter highlighter_dir
+_zsh_highlight_load_highlighters:12> highlighter_dir=/Users/near/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/README.md/
+...
zsh-syntax-highlighting: 'README.md' highlighter should define both required functions '_zsh_highlight_highlighter_README.md_paint' and '_zsh_highlight_highlighter_README.md_predicate' in '/Users/near/.oh-my-zsh/plugins/zsh-syntax-highlighting/highlighters/README.md//README.md-highlighter.zsh'.
```

You don't see that error under your normal user, but you do under root, which is strange. A couple of tests you can run to try to narrow down the issue further:
```
$ print -l $ZSH/plugins/zsh-syntax-highlighting/highlighters/*/
$ print -l $ZSH/plugins/zsh-syntax-highlighting/highlighters/*(/)
$ for f ($ZSH/plugins/zsh-syntax-highlighting/highlighters/*/); do echo $f; done
```
all ran both with your normal user and under sudo.

**Comment by mcornella** [comment]
What about another directory, say `print -l $ZSH/*/` (with root).

**Comment by NearAutomata** [comment]
```
 ~  print -l $ZSH/*/
/Users/near/.oh-my-zsh/cache/
/Users/near/.oh-my-zsh/custom/
/Users/near/.oh-my-zsh/lib/
/Users/near/.oh-my-zsh/log/
/Users/near/.oh-my-zsh/plugins/
/Users/near/.oh-my-zsh/templates/
/Users/near/.oh-my-zsh/themes/
/Users/near/.oh-my-zsh/tools/
 ⚡ root@MBP  ~  print -l $ZSH/*/
/Users/near/.oh-my-zsh/CONTRIBUTING.md/
/Users/near/.oh-my-zsh/LICENSE.txt/
/Users/near/.oh-my-zsh/README.md/
/Users/near/.oh-my-zsh/cache/
/Users/near/.oh-my-zsh/custom/
/Users/near/.oh-my-zsh/lib/
/Users/near/.oh-my-zsh/log/
/Users/near/.oh-my-zsh/oh-my-zsh.sh/
/Users/near/.oh-my-zsh/plugins/
/Users/near/.oh-my-zsh/templates/
/Users/near/.oh-my-zsh/themes/
/Users/near/.oh-my-zsh/tools/
```

**Comment by mcornella** [comment]
I haven't been able to find why your zsh binary (version 5.3) behaves this way. I'm currently looking if there is a bug in that version, but I'd suggest updating to a newer version in the meantime.

**Comment by mcornella** [comment]
I haven't been able to reproduce your problem with zsh 5.3, so it must be a system bug. I've seen that `echo */` runs `access()`, while `echo *(/)` runs `lstat()`. In my system, the call to `access()` returns an `ENOTDIR` error on files which aren't directories, so in your case it must not work like that. 

Make a test suite by running the following:
```
mkdir -p test/{a..d}
touch test/{e..g}
cd test
```

Then run `strace zsh -fic 'echo */'` both with your normal user and with root. This is what I get with both:
```
...
open(".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
brk(0x56297e6d7000)                     = 0x56297e6d7000
getdents(3, /* 9 entries */, 32768)     = 216
getdents(3, /* 0 entries */, 32768)     = 0
brk(0x56297e6cf000)                     = 0x56297e6cf000
close(3)                                = 0
access("f/.", F_OK)                     = -1 ENOTDIR (Not a directory)
access("b/.", F_OK)                     = 0
access("g/.", F_OK)                     = -1 ENOTDIR (Not a directory)
access("e/.", F_OK)                     = -1 ENOTDIR (Not a directory)
access("c/.", F_OK)                     = 0
access("d/.", F_OK)                     = 0
access("a/.", F_OK)                     = 0
write(1, "a/ b/ c/ d/\n", 12a/ b/ c/ d/
)           = 12
...
```

So zsh discards the filenames of those that returned `ENOTDIR`, and then outputs the rest. Let me know what you get.
