### ISSUE TITLE
Do we need a documentation for npm plugin

### ISSUE THREAD

**Issue by dimensi0n** [robbyrussell/oh-my-zsh#6785]
I saw git plugin documentation and I wanted to ask if it is possible to have a documentation for npm plugin... If you want I can do it 😏.

**Comment by mcornella** [comment]
That would be great, yes!

**Comment by dimensi0n** [comment]
I'll do it

**Comment by dimensi0n** [comment]
It's here : https://github.com/dimensi0n/oh-my-zsh/wiki You can't make a PR for a wiki on github so you'll have to add it maanually.

**Comment by dimensi0n** [comment]
@mcornella

**Comment by mcornella** [comment]
Actually it's better as a README.md in the plugin folder. There are documented plugins on the wiki but we will transfer them to a plugin README in the near future. 

Also, can you add a description to the aliases? You can use the [comments in the plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/npm/npm.plugin.zsh). Thanks for your work!

**Comment by dimensi0n** [comment]
Ok i'll make a README.md ;)
What type of description do you wan't for plugins ?
```bash
# The action
# The equivalent
```
It looks like this : 
```bash
# Init a project with npm
# npm init
```

**Comment by dimensi0n** [comment]
here is my PR @mcornella ;) #6864
