### ISSUE TITLE
Zsh is not installed! Please install zsh first!

### ISSUE THREAD

**Issue by DDifDEVzero** [robbyrussell/oh-my-zsh#6796]
hello robbyrusell !

after install like your description on debian 9.4 i got this error:

Zsh is not installed! Please install zsh first!

zsh is install

```
# /etc/shells: valid login shells
/bin/sh
/bin/dash
/bin/bash
/bin/rbash
/bin/zsh
/usr/bin/zsh
```

two hours ago i install it on a another debian 9.4 computer and it works and i see you make changes one hour ago

please fix

**Comment by diegorm90** [comment]
There is a bug in a condition in this commit:
https://github.com/robbyrussell/oh-my-zsh/commit/c4981bae0a91ce6d4b0717558342584cc6491199

**Comment by daguttierrez** [comment]
I'm getting the same error, I have checked the zsh installation and unfortunately, the message `Zsh is not installed! Please install zsh first!` pops up.

**Comment by kinglabrador23** [comment]
ffs

**Comment by inheinsight** [comment]
I'm also getting this error. 
Installed via homebrew on macOS 10.13.4 in iTerm.

**Comment by daguttierrez** [comment]
Thanks @JimFung

**Comment by Robaire** [comment]
Getting the same error, fresh install of Ubuntu 18.04.

**Comment by Lumbaz** [comment]
Getting the error too on Kubuntu 18.04.0 LTS

**Comment by xqitong** [comment]
@JimFung thanks ~

**Comment by xnobodyx** [comment]
gentoo zsh 5.5 same problem

**Comment by ouniti** [comment]
Performed a fresh install of macOs, installed Homebrew, performed `brew install zsh zsh-completions`, followed by `curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh`, throws `Zsh not installed.`

I read through a different issue and adding `/usr/local/bin/zsh` to `/etc/shells` changed nothing.

**Comment by shovon** [comment]
Ditto on @ouniti.

Changed the contents of `/etc/shells`, and the installer still can't install.

**Comment by mattbdean** [comment]
I'm having the same issue on a fresh install of Ubuntu 18.04. See [here](https://github.com/robbyrussell/oh-my-zsh/commit/c4981bae0a91ce6d4b0717558342584cc6491199#r28869821) for a temporary workaround.

**Comment by nveselinov** [comment]
Today I made a fresh reinstall of my macOS. 

1. Installed Brew
2. Ran brew install zsh zsh-completions
3. Ran sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

I'm always getting "Zsh is not installed! Please install zsh first!". I've been also tried to change the shell to zsh and then to execute the setup script for Oh my zsh but no luck on that as well.

**Comment by Jobayer-Ahmed** [comment]
Ubuntu 16.04 same problem

**Comment by tiannian** [comment]
I got same problem on Arch Linux. Please fix it as soon as possible. tks.

**Comment by ShreyasAiyar** [comment]
Tried on 3 different Mac's all running macOS Hgh Sierra. Both the homebrew and native zsh are giving this error.

**Comment by Lasiar** [comment]
ubuntu 18.04 same problem

**Comment by maheshinder19** [comment]
same problem. cannot change the default shell. Wasted my 2 days in this.

**Comment by Dishendramishra** [comment]
Yes i am also getting the same error.

**Comment by JJMin** [comment]
I am getting the same problem, I thought I was the only one as well.

I used JimFung's comment to install: 
`$ curl -L https://raw.githubusercontent.com/mriedmann/oh-my-zsh/master/tools/install.sh | sh`

**Comment by saadbinsaeed** [comment]
Getting the same error

**Comment by dannyalfonzo** [comment]
hi guys, with this repo https://raw.githubusercontent.com/mriedmann/oh-my-zsh/master/tools/install.sh

the clone work!
so, you may use: sh -c "$(wget https://raw.githubusercontent.com/mriedmann/oh-my-zsh/master/tools/install.sh -O -)"

**Comment by CostGranda** [comment]
I solve it just downloading manually the `install.sh` file and commented out the lines 27 to 30, where the validation exists.
 Before
``` bash
  if command -v zsh >/dev/null 2>&1; then
    printf "${YELLOW}Zsh is not installed!${NORMAL} Please install zsh first!\n"
    exit
  fi
```
After
``` bash
#  if command -v zsh >/dev/null 2>&1; then
#   printf "${YELLOW}Zsh is not installed!${NORMAL} Please install zsh first!\n"
#    exit
#  fi
```

then execute de file `sh install.sh` 

Cheers.

**Comment by mcornella** [comment]
I'm a fucking moron. Fixed on master

**Comment by Dogkanos** [comment]
Ubuntu 18.04 and i get this error for fresh install

**Comment by trandaison** [comment]
This bug still appears on Unbuntu 16.04

**Comment by mcornella** [comment]
There weren't any changes recently, are you sure you have zsh installed?

**Comment by tyleroket** [comment]
Im still seeing this too on aws linux.

**Comment by mcornella** [comment]
Do you have zsh in your Path when running sh?

**Comment by ShangxuanWu** [comment]
Still seeing this on 14.04 :)

**Comment by Ava-O** [comment]
Still seeing this on macOS 10.13

**Comment by mcornella** [comment]
If this is happening to you answer the following:

- What does `which -a zsh; echo $PATH` print?
- What does `sh -c 'which -a zsh; echo $PATH` print?

**Comment by lsr** [comment]
New install of Ubuntu 18.04 here.
Getting the error "Zsh is not installed! Please install zsh first!"

which -a zsh; echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

sh -c 'which -a zsh; echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by skaunited** [comment]
that was exactly an error that I got when I tried to install ZSH on VPS, OS Ubuntu 18.04 and the solution that figured out with it is 
💯  apt install ZSH

**Comment by tayyebi** [comment]
Based on @skaunited,
here we have a simple method for offline installation

```
mkdir zsh-installer
cd zsh-installer
sudo apt-get --print-uris --yes install zsh | grep ^\' | cut -d\' -f2 > zsh.txt
wget -i zsh.txt
sudo dpkg -i *.deb
```

**Comment by jrbytes** [comment]
> Well, zsh is not there so it must not be installed. `sudo apt install zsh` will do.

It worked!

**Comment by robertocandido** [comment]
I had this problem, in my case git was not installed.
I installed git and it worked.

**Comment by viniciusbsneto** [comment]
**Solved** that problem running **these first**:

```
sudo apt update
sudo apt install git zsh -y
```

**Then** the **curl**:

`sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

**Comment by nathan-gratitudeindia** [comment]
> **Solved** that problem running **these first**:
> 
> ```
> sudo apt update
> sudo apt install git zsh -y
> ```
> 
> **Then** the **curl**:
> 
> `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

**Comment by mjedrasiak** [comment]
Thank you @nathan-gratitude , you are a wonderful human being.

**Comment by LuizNsIT** [comment]
> > **Solved** that problem running **these first**:
> > ```
> > sudo apt update
> > sudo apt install git zsh -y
> > ```
> > 
> > 
> > **Then** the **curl**:
> > `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

Thx, nathan. I'm really grateful.

**Comment by imadmi** [comment]
$sudo apt install zsh
Then enter your sudo password ,  type 'y' and press ok .

**Comment by PauloSantos1109** [comment]
Hey guys, I have a solution for this.
In the distribution Pop_os! I did the installation using apt and then I used wget to install the files.

1 - sudo apt-get install zsh
2 - sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

**Comment by XingYuan55** [comment]
[@CostGranda ](https://github.com/CostGranda) commented [on May 7, 2018](https://github.com/ohmyzsh/ohmyzsh/issues/6796#issuecomment-386918452)'s comment is true and it's very helpful.
Thank you.

For me, the lines for verifying existence are Line510 to Line513. Perhaps these lines are different on everyone's computer. How to find it? Just search (Ctrl+F) for `Zsh is`.
Thank you again, CostGranda, for your help!
In the end, I succeeded:
![image](https://github.com/user-attachments/assets/b5a21a4a-2967-48eb-92ce-5bfd98726c7b)

By the way, I'm a Chinese. Plz use Chinese when reply me if you can.
顺便说一句，我是中国人。如果可以的话，请用中文回复我。
