### ISSUE TITLE
sudo plugin stopped working

### ISSUE THREAD

**Issue by eyal0803** [robbyrussell/oh-my-zsh#6808]
In the past 2 weeks (I think), I noticed that the `sudo` plugin (pressing `Esc` twice prepends the previous command with `sudo `) stopped working.

I'm using oh-my-zsh with the same `.zshrc` on two machines, so I'm pretty sure it's not a local issue.

**Comment by mcornella** [comment]
Have you changed your plugins? I can't reproduce that... What does `bindkey '\e\e'` return?

**Comment by eyal0803** [comment]
I didn't change my plugins.

```
$ bindkey '\e\e'
"^[^[" undefined-key

**Comment by mcornella** [comment]
That's weird, the sudo plugin hasn't been updated in years... What's your zshrc file?

**Comment by eyal0803** [comment]
https://pastebin.com/FNqERWmi

**Comment by mcornella** [comment]
You can't use commas in your plugins array, just spaces.
