### ISSUE TITLE
pyenv plugin stopped working 

### ISSUE THREAD

**Issue by yuvalek** [robbyrussell/oh-my-zsh#6810]
after it's last update something went wrong and it is not working any more.
reverting to the old version of the plugin fixed the problem.

**Comment by mcornella** [comment]
In what ways does it not work? Does it find the pyenv command? If you have installed versions somewhere not in `$HOME/.pyenv` you should move them there.

**Comment by mcornella** [comment]
I've pushed the fix. Try updating OMZ (`upgrade_oh_my_zsh`). If it still doesn't work, feel free to reopen the issue.
