### ISSUE TITLE
rbenv plugin stops virtualenvwrapper plugin from functioning

### ISSUE THREAD

**Issue by stuaxo** [robbyrussell/oh-my-zsh#6816]
the "workon" alias is no longer available if rbenv is enabled.

**Comment by mcornella** [comment]
I can't find anything in the code that would make it clash with the virtualenvwrapper plugin. What do you have in your `plugins` array of your zshrc file?

**Comment by stuaxo** [comment]
```
plugins=(
  git,
  rbenv,
  virtualenvwrapper
)
```

**Comment by stuaxo** [comment]
Weirdly, I just found they both (```rbenv``` and ```workon```) work when I set 
```
plugins=(
  git,
  rbenv 
  virtualenvwrapper
)
```
(no comma between rbenv and virtualenvwrapper)


I had previously setup rbenv and virtualenvwrapper up in bash, not sure if this matters

**Comment by mcornella** [comment]
Yeah, you can't use commas in zsh arrays. That one `git,` also goes without comma. This is a problem that I see a lot here even though [there's an example just above the `plugins=()` line](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template#L59).
