### ISSUE TITLE
Ctrl+C during tab completion hides prompt

### ISSUE THREAD

**Issue by orlp** [robbyrussell/oh-my-zsh#6818]
Using oh-my-zsh with absolutely default settings, the following happens:

https://asciinema.org/a/w5gDwZS2xjZpxoKGLAz8JP5tV

The way to reproduce is:

1. Enter the start of a command that's ambiguous.
2. Press TAB to show options.
3. Press TAB again to move selection to first option.
4. Press Ctrl+C to cancel selection.

Now your prompt is hidden.

**Comment by orlp** [comment]
@mcornella Sorry, I should've been more explicit. This is not with the `robbyrussell` theme. The above example is made with only two lines in my `zshrc`:

```
export ZSH="/home/orlp/dotfiles/zsh/oh-my-zsh"
source $ZSH/oh-my-zsh.sh
```

Which uses no theme. That being said, if I add the line `ZSH_THEME="robbyrussell"`, the same issue occurs. The issue does not occur without using oh-my-zsh. My `zsh --version` is `zsh 5.2 (x86_64-ubuntu-linux-gnu)`.

**Comment by mcornella** [comment]
Please run `zsh xvic 'exit' &>~/omz-debug.log` and post the generated file as a private gist.

**Comment by orlp** [comment]
I assume you meant `zsh -xvic`? Either way, that results in a 7000+ lines file which is too large for me to manually verify it does not contain personal information about me or my system to publish in an online forum here, so I am not comfortable with sharing it.

I am more than willing to help to answer and debug specific questions.

Quick question: are you able or unable to reproduce the issue from my 4 step instructions above?

**Comment by mcornella** [comment]
I can't reproduce, no. You can try to narrow down which lib file causes it: instead of sourcing the init script, source each of the files in the lib folder, one by one, until you can reproduce your bug.

**Comment by orlp** [comment]
@mcornella Instead, I initialized a fresh install of oh-my-zsh, and deleted files from the `lib` folder until I narrowed it down. And once I found it was in `completion.zsh` (unsurprisingly), I narrowed it down further to the line:

    zstyle ':completion:*:*:*:*:*' menu select

This isn't standalone yet, it requires the initialization from the main `oh-my-zsh` script. From here I extracted the following parts to make a fully standalone reproduction inside a fresh `zsh -f`, without relying on oh-my-zsh:

```
autoload -U compinit
compinit -i -D
zstyle ':completion:*:*:*:*:*' menu select
```

**Comment by mcornella** [comment]
I can reproduce on zsh-5.2 on debian. I'll try to narrow it down to a specific commit, but for the time being you could disable that specific setting with `zstyle -d ':completion:*:*:*:*:*'` in your zshrc file.

**Comment by mcornella** [comment]
I've narrowed it down to versions between https://github.com/zsh-users/zsh/commit/32f5d3d8c16b4f3a11fa39c0ee378d72336ba853 (which introduces the bug) and https://github.com/zsh-users/zsh/commit/1d8b5285226afba4f1ef9030cf862c14b975c284 (which fixes it). 

That means that versions 5.1.1 and 5.2 have this bug.

**Comment by orlp** [comment]
I apologize for wasting your time - it was a `zsh` bug after all. I could only repro the bug with OMZ active, which led me to assume it was in OMZ. Thanks for your help in narrowing it down.

**Comment by mcornella** [comment]
Not wasted at all, I think we'd need to check for those versions before setting the menu select setting. I'll make a quick PR this evening.
