### ISSUE TITLE
Don't store history in my initial script

### ISSUE THREAD

**Issue by glebmikulko** [robbyrussell/oh-my-zsh#6821]
Don't know if I'm writing in proper place for my issue.
I tried to set my custom layout with several tabs and initial commands for every tab. I followed instruction as described here https://amir.rachum.com/blog/2015/11/28/terminator-multiple-custom-commands/
Main part there is this script
```
echo $INIT_CMD
if [ ! -z "$INIT_CMD" ]; then
    OLD_IFS=$IFS
    setopt shwordsplit
    IFS=';'
    for cmd in $INIT_CMD; do
        print -s "$cmd"  # add to history
        eval $cmd
    done
    unset INIT_CMD
    IFS=$OLD_IFS
fi
```
Everything works fine except commands from initial script are not stored in my zsh history. If I execute commands directly in zsh it works properly as well. My guess is that history file loaded after my command is executed.

**Comment by mcornella** [comment]
This is not an OMZ feature. You might want to look for help on that same blog post or on stackoverflow.

**Comment by glebmikulko** [comment]
thanks
