### ISSUE TITLE
Instalation Problem

### ISSUE THREAD

**Issue by Spikuriax** [robbyrussell/oh-my-zsh#6823]
Hi,

I have a problem, I would install oh-my-zsh in my professional computer (given by my company), but I can't install that.

When I do:
$ ./oh-my-zsh.sh
That puts me:
zsh: can't open input file: /tools/check_for_upgrade.sh
./oh-my-zsh.sh: 9: ./oh-my-zsh.sh: Syntax error: "(" unexpected

After I try to install with:
$ sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
That puts me:
Cloning Oh My Zsh...
Cloning in '/home/Spiku.oh-my-zsh'...
fatal: unable to access 'https://github.com/robbyrussell/oh-my-zsh.git/': SSL: certificate subject name (192.30.253.113) does not match target host name 'github.com'
Error: git clone of oh-my-zsh repo failed

I tried to find a solution but I did not find anything, please help :'(

My OS is Debian
I have Git installed
and Zsh is my default shell

**Comment by mcornella** [comment]
Try to run again the installer (`sh -c wget`...). It looks like a temporary glitch with the github git interface.
