### ISSUE TITLE
Plugins stop working when adding further plugins on OSX 10.13.4

### ISSUE THREAD

**Issue by nick-lehmann** [robbyrussell/oh-my-zsh#6824]
## Setup

- Computer: iMac, late 2013 with macOS High Sierra (10.13.4)
- Zsh version: zsh 5.3 (x86_64-apple-darwin17.0)
- Current OMZ as of today (May 14th 2018, latest commit: 6876d9c5438b0e0e950fc85f736458ba55f8d65c)
- iTerm2 build: 3.1.6 
- followed instructions under the `Completion problems` section on the [troubleshooting page](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting), without success

## Problem

After adding further plugins to `plugins=(...)` line in `.zshrc`, plugins who have already worked stop working. The issue is probably caused because the directories where some plugins are located are not added to the `fpath` environment variable.

## How to reproduce the problem

Start with two plugins, in my case:

```
plugins=(git, zsh-autosuggestions)
```

Restart iTerm2. Notice that `git` and `zsh-autosuggestions` plugins are working. Current `fpath` is:

```
echo $fpath
/Users/nicklehmann/.oh-my-zsh/custom/plugins/zsh-autosuggestions /Users/nicklehmann/.oh-my-zsh/functions /Users/nicklehmann/.oh-my-zsh/completions /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.3/functions
```

As shown by the output, the directory of `zsh-autosuggestions` is included in the variable.

Now add another plugin at the end of the line e.g. `docker`. The `plugins` line in `.zshrc` now looks like this:

```
plugins=(git, zsh-autosuggestions, docker)
```

After restarting iTerm, notice that the `git` plugin is still working, as well as the `docker` plugin. However, `zsh-autosuggestions` stopped working. The `fpath` environment variable now looks like this:

```
echo $fpath
/Users/nicklehmann/.oh-my-zsh/plugins/docker /Users/nicklehmann/.oh-my-zsh/functions /Users/nicklehmann/.oh-my-zsh/completions /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.3/functions
```

The directory where the `docker` plugin is located is now included in the variable, but the `zsh-autosuggestions` directory has disappeared. When switching the order of the plugin names in the `plugins=(...)` line so that `zsh-autosuggestions` is last, the `docker` plugin stops working and it's directory has disappeared from the `$fpath` variable. In this case, the workaround found the answer to [this SO question](https://stackoverflow.com/questions/37428133/zsh-docker-plugin-not-working) helps:

```
fpath+=($ZSH/plugins/docker)
autoload -U compinit && compinit
``` 

## What the correct behavior should be

While I'm not sure about the correct function of the `$fpath` variable, the correct behaviour would be that both plugins are working. Eventually, the following plugins should all work:

```
plugins=(git, zsh-autosuggestions, pip, brew, osx, django, docker)
```

### Little note
Not sure if it's connected to this issue, but my `.zshrc` is not located in my directory but under `~/.term-config` and symlinked into my home directory. I have done this to so I can have all my configuration files in a git repo without seeing the `vcs` indicator when I'm working in my home directory.

**Comment by mcornella** [comment]
The problem is that zsh arrays are separated by spaces, not commas.
