### ISSUE TITLE
Remove support for nyan

### ISSUE THREAD

**Issue by dgisser** [robbyrussell/oh-my-zsh#6826]
Nyan is no longer supported by the developer. We should consider deleting the plugin. When the command is run, the user sees 

> Due to increased bandwith costs, nyancat.dakko.us is no longer operating.
> We encourage you to build the Nyancat CLI source package:
>  https://github.com/klange/nyancat
> ... or install it from your distribution package manager.
> Thank you for nearly a decade of terminal nyaning!
>                              - K. Lange

@klange

**Comment by robbyrussell** [comment]
:-(
