### ISSUE TITLE
git branch response be like bash

### ISSUE THREAD

**Issue by naderdl** [robbyrussell/oh-my-zsh#6828]
Hi, I have a problem with `git brach` and `git diff` commands their responses are printed in a vim prompt and I should press q to exit instead of printing it under them.
<img width="496" alt="screen shot 2018-05-16 at 1 43 06 am" src="https://user-images.githubusercontent.com/20730929/40083809-86512e08-58aa-11e8-9bfe-6ae7d49443ef.png">
is there any way to change this ?
I want to git commands response like bash.

**Comment by mcornella** [comment]
There was a change made on git 2.13
6, see https://stackoverflow.com/a/48370253/5798232 for how to disable it.
