### ISSUE TITLE
Error after uninstall_oh_my_zsh

### ISSUE THREAD

**Issue by MeboGit** [robbyrussell/oh-my-zsh#6831]
Hi,

tried to run uninstall_oh_my_zsh on macbook pro high sierra.

When restarting terminal starts as follows:

Last login: Wed May 16 22:19:29 on ttys000
/Users/mebomac/.zshrc:source:66: no such file or directory: /Users/mebomac/.oh-my-zsh/oh-my-zsh.sh
Michaels-MBP-WLAN% 

That looked very different before?! What went wrong with uninstall? What does WLAN% means here?

Thanks and Regards

Michael

**Comment by ikhere** [comment]
Remove line 66 from your `.zshrc` file as it no longer points to `.oh-my-zsh`.

**Comment by mcornella** [comment]
It looks like the uninstaller didn't remove the zshrc file. `Michaels-MBP-WLAN%` is the prompt, where I presume `Michaels-MBP-WLAN` is the hostname and % is just the separator between the prompt and the command line. You're still running zsh here.

**Comment by MeboGit** [comment]
Thanks for the replies.
But how exactly can I uninstall zsh then?

**Comment by dsteinbach** [comment]
My original shell is not restored and when trying to get it to look like it used to I get this error:

```
REFWSnbachMPB% source .bash_profile   
WARNING: this script is deprecated, please see git-completion.zsh
\u@\h \W\[\033[32m\]$(parse_git_branch)\[\033[00m\] $
```

**Comment by fredden** [comment]
It looks like you'd like to [change your shell on Mac OS X](http://osxdaily.com/2012/03/21/change-shell-mac-os-x/) from zsh to bash. To do that on the command line, run `chsh -s /bin/bash`. The link above suggests there's a way to do this in the Terminal preferences too.

**Comment by mcornella** [comment]
Using `chsh` and login out and back in of your user session is the way to go.
