### ISSUE TITLE
alias conflict - agp

### ISSUE THREAD

**Issue by shinenelson** [robbyrussell/oh-my-zsh#6832]
The alias `agp` conflicts with 2 packages - `ubuntu` (maintainer unknown) and the `aws` plugin (maintained by @cristim).

For `ubuntu`, the alias points to `apt-get purge`, while for `aws`, it is supposed to print the current aws profile.

Can we please get to a consensus as to renaming one of these aliases?

**Comment by shinenelson** [comment]
`acp` would still conflict with the alias for `apt-cache policy` from the `ubuntu` plugin. It'd probably be too hard to get an alias combination that starts with `a` since most of the combinations would be reserved by the `debian` and `ubuntu` plugins :stuck_out_tongue_winking_eye:

**Comment by mcornella** [comment]
I'm afraid we can't rename one or the other since that would conflict with people's expectations of what that alias would run. On those users that load both plugins, the way to fix it is to load their preferred plugin last, so as to override the other plugin's alias.
