### ISSUE TITLE
Folder permission "Insecure completion-dependent directories detected"

### ISSUE THREAD

**Issue by rafaelstz** [robbyrussell/oh-my-zsh#6835]
I'm receiving this message below, I've use the command `sudo chmod -R 755 /usr/local/share/zsh` but didn't fix all folders, this message continue showing.
```
[oh-my-zsh] Insecure completion-dependent directories detected:
lrwxr-xr-x  1 rafael  admin  88 Apr 28 15:51 /usr/local/share/zsh/site-functions/_brew_services -> ../../../Homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.
```

How could I fix that?
Thanks

**Comment by jhullse** [comment]
I updated oh-my-zsh today and I am receiving the same message but in a different location after executing `sudo su`.

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x  11 jhonatan jhonatan 4096 May 17 21:26 /home/jhonatan/.oh-my-zsh
drwxr-xr-x 243 jhonatan jhonatan 4096 May 17 21:26 /home/jhonatan/.oh-my-zsh/plugins
drwxr-xr-x   2 jhonatan jhonatan 4096 May 17 21:26 /home/jhonatan/.oh-my-zsh/plugins/git
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:95: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:102: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:125: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:135: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:169: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:172: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:174: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:188: command not found: compdef
/home/jhonatan/.oh-my-zsh/plugins/git/git.plugin.zsh:200: command not found: compdef
```

**Comment by simplegadget512** [comment]
Same here. I purposely have group rwx permissions on directories in my homebrew setup so that multiple users (all me, btw) can access and perform updates as necessary from any login.

**Comment by AkdM** [comment]
Same here, I've updated zsh yesterday and I have the same errors.

**Comment by peanutgao** [comment]
I update this afternoon, has same problem. Please tell me How to solve it ?

Last login: Fri May 18 17:38:26 on ttys009
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  6 Joseph  staff  192  7 31  2017 /usr/local/share/zsh
drwxrwxr-x  8 Joseph  staff  256  3  5 15:42 /usr/local/share/zsh/site-functions
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:95: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:102: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:125: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:135: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:169: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:172: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:174: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:188: command not found: compdef
/Users/Joseph/.oh-my-zsh/plugins/git/git.plugin.zsh:200: command not found: compdef

**Comment by AkdM** [comment]
Disabling the git extension in the .zshrc file obviously hides the `command not found: compdef` error. But I still have the following:

```
Last login: Fri May 18 11:47:06 on ttys004
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 myusername  admin  102 Sep  4  2017 /usr/local/share/zsh
drwxrwxr-x  7 myusername  admin  238 Apr  3 11:34 /usr/local/share/zsh/site-functions
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.
```

**Comment by sourabh-goyal** [comment]
facing the same issue
`[oh-my-zsh] Insecure completion-dependent directories detected:
lrwxr-xr-x  1 root  wheel  55 Jul  8  2016 /usr/local/share/zsh/site-functions/_git -> ../../../Cellar/git/2.8.3/share/zsh/site-functions/_git
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:95: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:102: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:125: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:135: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:169: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:172: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:174: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:188: command not found: compdef
/Users/sourabhgoyal/.oh-my-zsh/plugins/git/git.plugin.zsh:200: command not found: compdef`

**Comment by dawoonchung** [comment]
Facing the same issue here after the update.

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  56 da-woon.chung  admin  1792 May 18 09:50 /usr/local/share
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:95: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:102: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:125: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:135: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:169: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:172: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:174: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:188: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/git/git.plugin.zsh:200: command not found: compdef
/Users/da-woon.chung/.oh-my-zsh/plugins/yarn/yarn.plugin.zsh:88: command not found: compdef
```

**Comment by ericchuawc** [comment]
I did this and it solved the issue

```
chmod 755 /usr/local/share/zsh
chmod 755 /usr/local/share/zsh/site-functions
```

Then close and open my iterm, it works.

**Comment by sourabh-goyal** [comment]
@ericchuawc your solution didnt help.

**Comment by sourabh-goyal** [comment]
ISSUE SOLVED!! by :
Set ZSH_DISABLE_COMPFIX=true in your zshrc file, before oh-my-zsh.sh is sourced, and update OMZ to the latest version. It should ignore these permission issues and load the completion system normally.

thanks to @mcornella  for the solution @ https://github.com/robbyrussell/oh-my-zsh/issues/6461

**Comment by oyoun** [comment]
Having the same issue! Same messages

**Comment by dompl** [comment]
Same here. Any help much appreciated.

**Comment by serdardalgic** [comment]
I have the latest master `a600ab4`

My OS is OSX El Capitan, Version 10.11.6 (15G20015). 

When I added  `ZSH_DISABLE_COMPFIX=true` to my zshrc, tab completion started to work again, but I experienced those issues.

* Updated completions are not used. E.g. when I write docker<TAB> it shows the old completions, not the ones that are introduced with, let's say, [919f0a42](https://github.com/robbyrussell/oh-my-zsh/commit/919f0a42a09371c948d89c2d63593c23658811cc). To be more precise, docker ins<TAB> autocompletes to inspect, doesn't give the option to select between ìnspect` and ìnstall`.

* `git add`command autocompletes the files that are suitable to be staged, but `git add -i` command doesn't autocomplete the files. 

I guess I need to recreate the hash for the autocompletion but I don't know how I can do it. 
I tried `rehash` command, it didn't work. 
`unfunction _docker && autoload -U _docker`didn't help either.

How can I debug the issue further?

**Comment by serdardalgic** [comment]
Sorry for the confusion, Those two issues still exist in the commit `cafa657` from which I updated to current master. I'll check those in the issues and if necessary, create new tickets.

**Comment by leeeunlim** [comment]
Same here.
```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxrwx 0 eunlim eunlim 512 Mar 22 18:31 /home/eunlim/.oh-my-zsh/custom/plugins/zsh-autosuggestions
drwxrwxrwx 0 eunlim eunlim 512 Mar 22 18:31 /home/eunlim/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] Insecure completion caches also detected:
-rw-rw-rw- 1 eunlim eunlim 39206 May 21 10:58 /home/eunlim/.zcompdump
[oh-my-zsh] Moving to "/home/eunlim/.oh-my-zsh/cache/zcompdump-bad/"...
```

**Comment by dompl** [comment]
This worked for me

`sudo chown -R $USER:staff /usr/local/*`

**Comment by mcornella** [comment]
The appropriate solution is https://github.com/robbyrussell/oh-my-zsh/issues/6835#issuecomment-390216875. The way zsh completions are loaded, you will get the message even if there is no *real* security risk. So just enable that flag to ignore it.

**Comment by stickperson** [comment]
Running `compaudit | xargs chmod g-w` worked for me.

**Comment by simplegadget512** [comment]
[6835](https://github.com/robbyrussell/oh-my-zsh/issues/6835#issuecomment-390216875 ) provides a workaround for the issue, but is that really a fix?

Why is oh-my-zsh doing a security audit on things that are pretty clearly not it's responsibility?

**Comment by reijin90** [comment]
you just have to change the ownership of the omz user folder:
`chmod a-wx /home/USER/.oh-my-zsh/custom/plugins/zsh-completions`

**Comment by pandaa880** [comment]
It says set 
`ZSH_DISABLE_COMPFIX=true` in **.zshrc** before you source **.oh-my-zsh** in your **.zshrc** file.

So, put
`ZSH_DISABLE_COMPFIX=true` at the first line of your **.zshrc** file. It worked for me.🔥

**Comment by rassouldev** [comment]
Last login: Sun Jul 22 12:40:09 on ttys000
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x  3 502  admin   96 Jul 11 10:57 /usr/local/share/zsh
drwxr-xr-x  4 502  admin  128 Jul 11 11:00 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
