### ISSUE TITLE
Powerline integration is broken

### ISSUE THREAD

**Issue by oliveiraev** [robbyrussell/oh-my-zsh#6836]
fbcda4d5a92e023388259652652d154558e49ef3 broke my powerline integration.

I've made a recording to display behaviors: https://asciinema.org/a/uvFsGhrnWQ14p9VWY9z5IboDn

With 3dab7e46e8815838c8099040e11a7ae9a30ba03d everything works ok (prompt INPUT  green, my name in blue and CWD in grey).

Today, I've made an update and my prompt broke. (airline fallback).

I have no clue about what could happened.

More info about my environment:

```.profile``` finds $POWERLINE location with...

```sh
export POWERLINE=$(python3 -c"print(__import__('powerline').__file__)" 2>/dev/null)
```

then, my ```.zshrc``` invoke powerline with
```sh
source $(dirname $POWERLINE)/bindings/zsh/powerline.zsh
```

Powerline was installed via pip as of:

```pip3 install --user poweline-config```

**Comment by mcornella** [comment]
I don't understand, if your theme is powerline why are you using agnoster? You should set your `ZSH_THEME` to nothing.

**Comment by JasonGiedymin** [comment]
@mcornella, believe @oliveiraev mentions `powerline` because agnoster is `A Powerline-inspired theme for ZSH`.

**Comment by oliveiraev** [comment]
> I don't understand, if your theme is powerline why are you using agnoster? You should set your ZSH_THEME to nothing.

I use as a fallback for machines that doesn't have powerline installed. In fact, setting ```ZSH_THEME``` to empty string did the trick.

I've updated my ```.zshrc``` as follows

```sh
ZSH_THEME=$(test -n "$POWERLINE" || echo "agnoster")
```

Thank you very much.



> @mcornella, believe @oliveiraev mentions powerline because agnoster is A Powerline-inspired theme for ZSH.

No. I **in fact** use _oh-my-zsh_, _agnoster theme_ **and** _powerline_.

**Comment by JasonGiedymin** [comment]
@oliveiraev same here, only trying to help you out. Personally it was obvious you were using powerline and a powerline leaning theme.

**Comment by mcornella** [comment]
FWIW, I pushed a change that should make it compatible again.

**Comment by oliveiraev** [comment]
> FWIW, I pushed a change that should make it compatible again.

Confirmed! Thank you very much!
