### ISSUE TITLE
Conda environment name no longer appears in prompt

### ISSUE THREAD

**Issue by drdavella** [robbyrussell/oh-my-zsh#6837]
Previously when activating a [conda](https://conda.io/docs/) environment, the name of the environment would be prepended to my command prompt. However, that no longer happens. There are no errors and the environment is still activated: it just doesn't appear in the prompt.

A git bisect led me to this commit: https://github.com/robbyrussell/oh-my-zsh/commit/fbcda4d5a92e023388259652652d154558e49ef3

**Comment by rootsmith** [comment]
I concur. The changes made to how `PROMPT` is built in commit [fbcda4d](https://github.com/robbyrussell/oh-my-zsh/commit/fbcda4d5a92e023388259652652d154558e49ef3) have broken the showing of $VIRTUAL_ENV basename in the prompt.

**Comment by mcornella** [comment]
I've reverted the change. Upgrade with `upgrade_oh_my_zsh`.
