### ISSUE TITLE
Agnoster theme has execute permissions

### ISSUE THREAD

**Issue by simplegadget512** [robbyrussell/oh-my-zsh#6838]
The agnoster theme file has executable permissions on OS X Sierra. I just did a refresh from repo and it's the only theme with `a+x`.

Is this normal?

Edit: misspelled 'agnoster'

**Comment by JasonGiedymin** [comment]
I found the same. Should be able to `chmod -x` to bring back to normal.

**Comment by mcornella** [comment]
Fixed in 8f3737f.
