### ISSUE TITLE
Prefer virtualenvwrapper_lazy to speed up loading

### ISSUE THREAD

**Issue by lbolla** [robbyrussell/oh-my-zsh#6839]
`virtualenvwrapper` plugin is quite slow (it takes 200ms to load on my machine).
Would it be possible to prefer using `virtualenvwrapper_lazy.sh` when available, which lazily sources what's needed?

**Comment by lbolla** [comment]
Any comments on this PR?

**Comment by mcornella** [comment]
Discussion happening on #6842.
