### ISSUE TITLE
Todays update broke powerline shell

### ISSUE THREAD

**Issue by hooba91** [robbyrussell/oh-my-zsh#6851]
As the title says. Disabling oh-my-zsh fixes the problem.
I m running Mac 10.13.14 and the issue happens with iTerm and Default Terminal.

**Comment by phun-ky** [comment]
Something similar happened to the oh my zsh (solarized dark/agnoster) on ubuntu bash for windows 10..

**Comment by jskitz** [comment]
I'm also having this same issue.  I was wondering if anyone knows of a way to go back to the previous version of oh-my-zsh?  Basically what it broke for me is the ability to know what python virtual environment I'm in, which is tough when switching around projects.

**Comment by mcornella** [comment]
Fixed in 8f3737f.
