### ISSUE TITLE
Repo has a corruption

### ISSUE THREAD

**Issue by blackcobra1973** [robbyrussell/oh-my-zsh#6852]
Hello, 

I noticed today that there is a corruption inside this git repo.  

Easy to reproduce:  

   root  /  var  repo  Home  date
Wed May 23 08:38:42 CEST 2018
   root  /  var  repo  Home  git clone  https://github.com/robbyrussell/oh-my-zsh.git
Cloning into 'oh-my-zsh'...
remote: Counting objects: 18285, done.
remote: Total 18285 (delta 0), reused 0 (delta 0), pack-reused 18285
Receiving objects: 100% (18285/18285), 4.44 MiB | 3.07 MiB/s, done.
Resolving deltas: 100% (9692/9692), done.
    root  /  var  repo  Home  cd oh-my-zsh/
    root   master  …  repo  Home  oh-my-zsh  git fsck 
Checking object directories: 100% (256/256), done.
warning in tree 2b7227859263b6aabcc28355b0b994995b7148b6: zeroPaddedFilemode: contains zero-padded file modes
warning in tree a18c4d13c2a5fa2d4ecd5346c50e119b999b807d: zeroPaddedFilemode: contains zero-padded file modes
warning in tree 84df066176c8da3fd59b13731a86d90f4f1e5c9d: zeroPaddedFilemode: contains zero-padded file modes
Checking objects: 100% (18285/18285), done.
    root   master  …  repo  Home  oh-my-zsh  date
Wed May 23 08:39:08 CEST 2018
    root   master  …  repo  Home  oh-my-zsh  

This corruption is transferred also to the forks that are made.  Can you please  fix this ? 

Thanks in advance. 

Kurt Dillen

**Comment by mcornella** [comment]
This is a known issue discussed in #4963. The solution is to disable `transfer.fsckobjects` when doing the cloning. See https://github.com/robbyrussell/oh-my-zsh/issues/4963#issuecomment-210263233 and below.
