### ISSUE TITLE
Plugin SSH-Agent does not load multiple keys

### ISSUE THREAD

**Issue by TheEbolaDoc** [robbyrussell/oh-my-zsh#6854]
## The Problem:
The documentation suggests that you, if you want to load multiple keys, add a line to your `$HOME/.zshrc` with the following style:
```
zstyle :omz:plugins:ssh-agent identities id_rsa second_key
```
But there is no prompt for unlocking the key!

## How to reproduce the issue: 
1. install zsh + oh-my-zsh and add `ssh-agent` to the active plugins
```
plugins=(  
  ssh-agent
)
```
2. have multiple ssh keys
3. add the zstyle line from the above example

## What should be the correct behavior?

all the keys specified after `zstyle ...` are prompted for their specific password

## What is the actual behavior
it doesn't :disappointed:

**Comment by mcornella** [comment]
Works on my end, are you sure you're setting the zstyle before loading OMZ?

**Comment by TheEbolaDoc** [comment]
Well i put it at the begin of the config and it works beautifully :P 
Then this is a thing that would be nice to have in the manual at `https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/ssh-agent/README.md`
Then it would be a nice RTFM :blush: Thanks for your help :1st_place_medal:
