### ISSUE TITLE
virsh - no matches found

### ISSUE THREAD

**Issue by rajula96reddy** [robbyrussell/oh-my-zsh#6859]
The *virsh* command of *libvirtd* is returning no matches found. The command looks like this ``` virsh -c qemu+ssh://ABC@xxx.xxx.xxx.xxx/system?keyfile=/xxx.pem list``` The output is ```zsh: no matches found:  qemu+ssh://ABC@xxx.xxx.xxx.xxx/system?keyfile=/xxx.pem```   The same was working with other shells. Tried installing virsh auto completion too, but the error is still not resolved

**Comment by mcornella** [comment]
You have to quote arguments that contain a star `*` or a question mark `?` because they will be interpreted as globbing characters so zsh will try to expand it to a filename.

Searching for `zsh no matches found` gives you this same solution.
