### ISSUE TITLE
virtualenvwrapper plugin stop working with default $WORKON_HOME after #6842

### ISSUE THREAD

**Issue by icmpecho** [robbyrussell/oh-my-zsh#6882]
After the [#6842](https://github.com/robbyrussell/oh-my-zsh/pull/6842) update. If we haven't set `$WORKON_HOME` manually, Plugin will run into this code block and `return` without adding `workon_cwd` function to the `chpwd_functions` array

```bash
if [[ "$WORKON_HOME" == "" ]]; then
  print "[oh-my-zsh] \$WORKON_HOME is not defined so plugin virtualenvwrapper will not work" >&2
  return
fi
```

Even when we remove the code block above. It still does not work since `workon_cwd` is relying on `$WORKON_HOME` which hasn't been set yet if we're using the `virtualenvwrapper_lazy`

**Comment by mcornella** [comment]
It will work next time `workon` is called, no? See #6870

**Comment by icmpecho** [comment]
If the code block above is reached. It wouldn't work even the next time workon is called since it's returned before workon_cwd is registered.

If we remove the code block above it will work after the next time workon is manually called but I think one of the reason people (me for one) using this plugin is to be able to automatically switch between venv when we change the dir. Requiring a manual workon every time we open a new shell would kill that purpose.

**Comment by mcornella** [comment]
Ok, I understand. So if `$WORKON_HOME` is not defined, we use the default set up by `virtualenvwrapper.sh`, which is `$HOME/.virtualenvs`. But since the lazy version is loaded, `$WORKON_HOME` will not be defined until a virtualenvwrapper command is called by the user.

So my suggestion is: let's just define `$WORKON_HOME` to `$HOME/.virtualenvs`, if it's undefined, and we can get rid of the error message. I think that solves all use cases, but I may be wrong.

**Comment by icmpecho** [comment]
Well afaik I also think that would solves all use cases.

My only concern with this approach is we duplicate knowledge about default venv location into our plugin. If one day (although it's unlikely to happen) people who maintain virtualenv/virtualenvwrapper design to change that default location, knowledge that we defined in our plugin will conflict with the actual source of truth

**Comment by timfeirg** [comment]
IMHO a oh-my-zsh plugin shouldn't include any logic from the underlying scripts or software.

I think we can totally remove the warning message, and let the plugin be a mere quick access to `virtualenvwrapper.sh`, and assume that users have good knowledge on how to actually use `virtualenvwrapper`. That's what I think plugins should do, they provide quick access, but not that users can skip learning all the stuff that the plugins had wrapped for you.

But really , any approach that doesn't break existing user space configurations, and will continue to set the default `$WORKON_HOME`, is fine. This shouldn't require too much discussion, if something like `virtualenvsrapper` changing its default `$WORKON_HOME` location really ever happened, I'm sure there's an easy fix to that, we shouldn't be worrying about it.

**Comment by icmpecho** [comment]
Please look at my change in [#6883](https://github.com/robbyrussell/oh-my-zsh/pull/6883). I think it's a reasonable fix. If user has already manually set `$WORKON_HOME` they can still enjoy the fast loading time of `virtualenvwrapper_lazy` but if it's not set then full `virtualenvwrapper` is loaded and nothing is break.

**Comment by mcornella** [comment]
If gone ahead with my proposal because it provides the better experience for the user. The virtualenvwrapper plugin will load faster, and the functionality will be the same as if the full virtualenvwrapper.sh script was loaded. Thanks for your input.
