### ISSUE TITLE
Git tab completion for parent/sibling directory doesn't work [git add ../dir<tab>]

### ISSUE THREAD

**Issue by mortona42** [robbyrussell/oh-my-zsh#6884]
This might be a newbie question, but when I try to add a sibling directory via [git add ../dir/<tab>], tab completion doesn't work. Am I doing something wrong?

**Comment by zyy199807** [comment]
same here with Debian sid and zsh 5.5.1

**Comment by mcornella** [comment]
There is a bug in the current official completion introduced in https://github.com/zsh-users/zsh/commit/aa160fc8e962c2f6df62c62d67e366644457966c. See  https://github.com/zsh-users/zsh/commit/aa160fc8e962c2f6df62c62d67e366644457966c#r29988033

**Comment by mcornella** [comment]
I've submitted a fix at https://github.com/zsh-users/zsh/pull/26. Follow that thread to get the latest information. Closing this issue since it's not OMZ-related.

**Comment by mcornella** [comment]
The patch is now merged, I guess it should be in the next version of zsh. You can also copy the _git completion file and put it in some directory in your `$fpath`.

**Comment by varunagrawal** [comment]
For those of you coming here later on and the ZSH update not helping, your solution might be to pass in the `-z` flag to `autoload`.

Check out this answer for more details: https://stackoverflow.com/a/58517668/1236990
