### ISSUE TITLE
agnoster too long path in terminal

### ISSUE THREAD

**Issue by palemoky** [robbyrussell/oh-my-zsh#6885]
Before
![image](https://user-images.githubusercontent.com/21208635/40870266-6ee2b27a-665e-11e8-885d-007239fe0df1.png)

Now
![image](https://user-images.githubusercontent.com/21208635/40870267-7894017a-665e-11e8-8b0d-99e2bd5f7013.png)

I compare commit [7e5483d](https://github.com/robbyrussell/oh-my-zsh/commit/7e5483d672aab9764231d9a569b6c7451474eecb#diff-dd732f1edd4402189b1f0f7869e4c307) and [8f3737f](https://github.com/robbyrussell/oh-my-zsh/commit/8f3737f45b4c3c05e1488a28f79c6bc29ad8fb32#diff-dd732f1edd4402189b1f0f7869e4c307), found file last line led to termial show difference, but I can't modify it right.
![image](https://user-images.githubusercontent.com/21208635/40870289-13ef2c44-665f-11e8-9791-4cf95cea64cd.png)

So, how to modify the file, let path look like before.
@mcornella @Dawnflash @0xabu 

英语太渣了，用中文说明一下吧
图一是我升级前的终端显示样式，图二是我现在显示的样式（我做了部分修改，去掉了主机名和git 分支的显示），我经过比较该文件的历史提交，发现文件的最后两行是导致路径显示过长的主要原因，但我在经过多次尝试后仍无法让路径像之前那样显示，所以需要怎么修改才能让很长路径显示为`...`的形式？

其中，我找到过一下方法，目前都无法达到我的需求
1. https://blog.csdn.net/z3512498/article/details/51245853
2. https://github.com/wesbos/Cobalt2-iterm/issues/15

**Comment by mcornella** [comment]
Upgrade to the latest version (`upgrade_oh_my_zsh`). The changes you refer to where reverted.
