### ISSUE TITLE
How do I create a zsh theme?

### ISSUE THREAD

**Issue by Bepsii** [robbyrussell/oh-my-zsh#6887]
Title says it all

**Comment by mcornella** [comment]
You can also check out zsh's [Prompt Expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) to know about special characters and their meaning. You can quickly prototype them using `print -P <special-character>`. Example: `print -P '%n'` will print the username.

**Comment by Slowly** [comment]
nooo...those links are not guides to creating one's own themes. What Bepsii are looking for is an *advanced*, non-noob, extensively detailed technical guide on how to create a custom theme.
Thanx :)

**Comment by mcornella** [comment]
This blog post is still relevant https://code.tutsplus.com/tutorials/how-to-customize-your-command-prompt--net-24083
