### ISSUE TITLE
Bottom bar not displayed (powerline + tmux) on Amuse

### ISSUE THREAD

**Issue by nathan30** [robbyrussell/oh-my-zsh#6894]
Hi,
I would like to user the "amuse" theme but I didn't have the PowerLine bar at the bottom. Is there any settings to update in order to have it ? (I follow the powerline git to install it on my computer with all the python dependencies and also install tmux package). Or could someone give the tmux/powerline conf needed to have similar screen that the one display in the themes list ?

![capture d ecran de 2018-06-06 09-32-36](https://user-images.githubusercontent.com/7926051/41023841-d76238f4-696d-11e8-926b-d4bbcdee86ce.png)

**Comment by mcornella** [comment]
I think you have to be running tmux for the bar to appear, provided you've configured everything properly. You may find better support in the [powerline repo](https://github.com/powerline/powerline).
