### ISSUE TITLE
Virtual Environment still not showing on robbyrussell

### ISSUE THREAD

**Issue by agrwlakshay** [robbyrussell/oh-my-zsh#6899]
Virtual Environment still not showing on robbyrussell theme. It shows perfectly on other themes like agnoster.

**Comment by agrwlakshay** [comment]
I have updated oh-my-zsh to the latest version, I have installed virtualenvwrapper perfectly and enabled its plugin in .zshrc . If i switch to agnoster it shows me my virtualenv fine.

**Comment by mcornella** [comment]
You can use the `virtualenv` plugin and add `virtualenv_prompt_info` to your `$PROMPT`, like so:
```
PROMPT+=' $(virtualenv_prompt_info)'`
```
You can also add it to `$RPROMPT`.
