### ISSUE TITLE
Unable to update after removing unused plugins and themes

### ISSUE THREAD

**Issue by simplegadget512** [robbyrussell/oh-my-zsh#6904]
I am unable to update oh-my-zsh by hook or by crook after I deleted a bunch of unused plugins and themes. Auto-update fails and a manual update with upgrade_oh_my_zsh fails with the following:

`Updating Oh My Zsh
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
There was an error updating. Try again later?`

I know space is cheap, but so am I ...

**Comment by mcornella** [comment]
Did you delete them from the OMZ folder? Because that's not a supported setup. You can either commit your changes or stash, then unstash, as @v0idst4r said. You will probably run into conflicts each time you update though.
