### ISSUE TITLE
Tab-completion makes sudo ask for password

### ISSUE THREAD

**Issue by sheafitzek** [robbyrussell/oh-my-zsh#6906]
I have been through these related issues, but they are closed and nothing in them is working for me.
[#2413](https://github.com/robbyrussell/oh-my-zsh/issues/2413) [#5651](https://github.com/robbyrussell/oh-my-zsh/issues/5651) [#5957](https://github.com/robbyrussell/oh-my-zsh/issues/5957) [#6461](https://github.com/robbyrussell/oh-my-zsh/issues/6461)

When I try to tab complete, a box pops up asking for my password. The completion actually works after I either enter my password or hit cancel on the popup.

When I cancel the auth window, /var/log/auth.log prints:
```
polkitd(authority=local): Operator of unix-session:c8 FAILED to authenticate to gain authorization for action org.freedesktop.systemd1.manage-unit-files for system-bus-name::1.134 [systemctl enable -p | ~ ( ? * [ < ^ #] (owned by unix-user:shea)
```
When I input my password, /var/log/auth.log prints:
```
polkitd(authority=local): Operator of unix-session:c8 successfully authenticated as unix-user:shea to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-unit-files for system-bus-name::1.135 [systemctl enable -p | ~ ( ? * [ < ^ #] (owned by unix-user:shea)
```
I tried 1nv3rse's [fix](https://github.com/robbyrussell/oh-my-zsh/issues/5651#issuecomment-264617862), but never got any warnings about an insecure directory.

I just updated zsh to `zsh 5.1.1 (x86_64-ubuntu-linux-gnu)` and oh-my-zsh to `f461d21`.

last 2 lines of .zshrc:
```
ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh
```

Any ideas how I might debug this?

**Comment by mcornella** [comment]
What command are you trying to complete? Or is it all of them? Can you check what `which -a enable` returns?

**Comment by sheafitzek** [comment]
Output of `which -a enable`:
```
enable: aliased to systemctl enable 
command which: 
builtin which: enable: aliased to systemctl enable
type -w: enable: alias
whence -v: enable is an alias for systemctl enable
whereis: enable:
whatis: 
```

**Comment by mcornella** [comment]
This was fixed renaming the `enable` alias to `sc-enable` some time ago. If you run `upgrade_oh_my_zsh` you'll get the latest version of the systemd plugin.

**Comment by sheafitzek** [comment]
I saw that mentioned in [#2413](https://github.com/robbyrussell/oh-my-zsh/issues/2413) from 2014. I last updated oh-my-zsh 3 days ago to commit #`f461d21` (6/6/18). There has only been one commit since, which was fixing a typo in plugins/archlinux/README.md. I will try to update again when I get home this evening, but something isn't adding up.

**Comment by mcornella** [comment]
Then somewhere else you must have the enable alias defined.
