### ISSUE TITLE
git plugin not working

### ISSUE THREAD

**Issue by dschinkel** [robbyrussell/oh-my-zsh#6907]
not sure what I'm doing wrong but I installed zsh with homebrew using `brew install zsh`

I'm running this in **OS X Sierra**
I'm trying these commends in **iTerm2**

`echo $SHELL` returns `/bin/bash`

`zsh --version` returns: **zsh 5.2 (x86_64-apple-darwin16.0)**
`$SHELL --version` gives me **zsh 5.2 (x86_64-apple-darwin16.0)**
**curl** is installed

Here's my ~/.zshrc file:

```
# Created by newuser for 5.5.1
ZSH_THEME="avit"
plugins=(git)
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/coffeegrinds/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
```

Tried a command such as gco and got `zsh: command not found: gco
`

**Comment by v0idst4r** [comment]
What's the output of `alias gco`, `echo $plugins`, and `ls $ZSH/plugins`?

**Comment by dschinkel** [comment]
Ah, it's not set to `bin/zsh`

**Comment by v0idst4r** [comment]
That's weird because it says `zsh: command not found: gco`

**Comment by dschinkel** [comment]
I guess since I used homebrew to install zsh I had to run `sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh`

no idea but at least my shell has changed to zsh

https://rick.cogley.info/post/use-homebrew-zsh-instead-of-the-osx-default

**Comment by v0idst4r** [comment]
Is the plugin problem fixed? If not can you post the output of the commands mentioned in my first comment?

**Comment by dschinkel** [comment]
Not yet. 

`alias gco` does nothing, just takes me to the command prompt again
`echo $plugins` gives me `git brew`
ls $ZSH/plugins gives me `ls: /plugins: No such file or directory`

**Comment by dschinkel** [comment]
I'm an idiot I forgot to run `sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

it's been a long, long night.

**Comment by 17720743491** [comment]
![img_20180222_121059](https://user-images.githubusercontent.com/38480801/41200051-0b61b7fa-6cd0-11e8-88d4-2a539c638a8d.jpg)
![Uploading IMG_20180222_121123.jpg…]()
