### ISSUE TITLE
Double bang commands require extra return key press

### ISSUE THREAD

**Issue by v0idst4r** [robbyrussell/oh-my-zsh#6908]
Is this expected behavior or a bug? For example normally `echo !!`  will instantly print out the last command but instead it just types it out and requires an extra key press.

**Comment by mcornella** [comment]
This is the result of [`histverify`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-HISTVERIFY). You can disable that behavior with `unsetopt histverify`.

**Comment by fakefarm** [comment]
Make sure it's at the bottom of the file too. I originally put it in the `DISABLE_` section which didn't work.

**Comment by mcornella** [comment]
FYI, you can also press tab to perform history expansion on your bang sequence.
