### ISSUE TITLE
INC_APPEND_HISTORY and SHARE_HISTORY are mutually exclusive options

### ISSUE THREAD

**Issue by nooproblem** [robbyrussell/oh-my-zsh#6909]
From closed [2537](https://github.com/robbyrussell/oh-my-zsh/issues/2537), referencing [history.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh), quoting @dualscyther:

> I notice from the docs that it says:
> 
> INC_APPEND_HISTORY_TIME
> 
> This option is a variant of INC_APPEND_HISTORY in which, where possible, the history entry is written out to the file after the command is finished, so that the time taken by the command is recorded correctly in the history file in EXTENDED_HISTORY format. This means that the history entry will not be available immediately from other instances of the shell that are using the same history file.
> 
> This option is only useful if INC_APPEND_HISTORY and SHARE_HISTORY are turned off. The three options should be considered mutually exclusive.
> 
> ...
> 
> SHARE_HISTORY
> 
> This option both imports new commands from the history file, and also causes your typed commands to be appended to the history file (the latter is like specifying INC_APPEND_HISTORY, which should be turned off if this option is in effect). The history lines are also output with timestamps ala EXTENDED_HISTORY (which makes it easier to find the spot where we left off reading the file after it gets re-written).
> 
> Is it intentional that INC_APPEND_HISTORY and SHARE_HISTORY are both set in oh-my-zsh?

**Comment by nooproblem** [comment]
> use
> unsetopt SHARE_HISTORY
> 
> in your .zshrc file

**Comment by curusarn** [comment]
I'm reopening this issue because it should be solved in oh-my-zsh itself imho.
