### ISSUE TITLE
Is it possible to use `cd .../some_dir` (more than 2 dots)?

### ISSUE THREAD

**Issue by raulchen** [robbyrussell/oh-my-zsh#6912]
I expected `cd .../some_dir` could work the same as `cd ../../some_dir`, but it doesn't.
Does anyone know how to make this work, as well as make tab completion work for `cd .../<tab>`?
Thanks in advance. 
BTW, I think it makes sense to have them by default.

**Comment by mcornella** [comment]
Related issue #3062

**Comment by mcornella** [comment]
You could use the [globalias plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/globalias).

**Comment by raulchen** [comment]
Thank you, @mcornella.
I noticed the globalias plugin as well. 
But I was hoping it could work without expanding (at least only expand `...`, not every global alias).
I'll look into how to do that. 
Thanks again.

**Comment by raulchen** [comment]
I ended up doing this
```sh
function expand-dots {
   if [[ $LBUFFER =~ ".*\.\.\.$" ]]; then
	 zle _expand_alias
	 zle expand-word
   fi
   zle self-insert
}
zle -N expand-dots
bindkey -M viins "/" expand-dots
```
