### ISSUE TITLE
Question: Expanding ssh tab completion

### ISSUE THREAD

**Issue by thenoid** [robbyrussell/oh-my-zsh#6913]
I utilize different know_hosts files for different environments at work, EG `known_hosts_prod` for production via a configuration line like this in my `~/.ssh/config`
```
Host production_hosts.example.com
    UserKnownHostsFile ~/.ssh/known_hosts_prod
```
This however seems to break the ssh known hosts tab completion.  This appears to come from `plugins/common-aliases/common-aliases.plugin.zsh` with this line:
```
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
```
I've tried including a modified version of this line in my `.zshrc`, updating the `plugins/common-aliases/common-aliases.plugin.zsh` directly to the following:
```
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts{,_*}(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
```
and it hasn't worked. What am I missing?

**Comment by mcornella** [comment]
The known_hosts in my setup doesn't contain hosts, but if yours does you can test step by step the output of the string inside the array until you get what you want:
```
echo ${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts{,_*}(|2)(N) /dev/null)"}%%[# ]*}//,/ }
```

I've already tested that your modification to file globbing works as intended.

**Comment by thenoid** [comment]
the globbing works outside of the .zshrc, but when it's in it it doesn't.  even just executing the the zstyle command on the cli doesn't work.

**Comment by thenoid** [comment]
rolsen@stealthstar  ~  cat .ssh/known_hosts
regular_know_hosts.example.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNo]0ekQ+QUzQy57PHy7FdnD8= regular-default
 rolsen@stealthstar  ~  cat .ssh/known_hosts_prod
prod_know_hosts.example.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTIt\+ayHy7FdnD8= prod-default
 rolsen@stealthstar  ~  egrep zstyle ~/.zshrc
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts{,_*}(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
 rolsen@stealthstar  ~  ssh                       broadcasthost                   localhost                       regular_know_hosts.example.com  user                          root

**Comment by mcornella** [comment]
Nevermind, I managed to get it working:
```
zstyle ':completion:*:(ssh|scp|sftp|rsh|rsync):*' hosts ${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts{,_*}(|2)(N) /dev/null)"}%%[# ]*}//,/ }
```

**Comment by thenoid** [comment]
thanks!
