### ISSUE TITLE
My plugins won`t load until i re source my zshrc file

### ISSUE THREAD

**Issue by vongohren** [robbyrussell/oh-my-zsh#6923]
So i have this .zshrc file: https://github.com/vongohren/.dotfiles/blob/master/.zshrc.
And for some reason, if I dont have the plugins before the oh-my-zsh sourcing, they wont be loaded. I have to source in the .zshrc file after started the terminal.

Is this documented anywhere, i like to understand why :)

**Comment by mcornella** [comment]
The `$plugins` variable is read when starting OMZ, which is done when sourcing `oh-my-zsh.sh`. It cannot be done any other way.
