### ISSUE TITLE
Two strange things about 'ls' result ... 

### ISSUE THREAD

**Issue by dmaj7** [robbyrussell/oh-my-zsh#6927]
From 2 days ago, when I enter 'ls', the result is somewhat strange. 

1. The directory I personally created was wrapped with quotation mark 
2. Color is gone when I hit 'ls' 

I manually set LS_COLORS on my .zshrc and make alias for ls as "gls --color=always". 
then now I have color when I hit 'LS' but 'ls' still doesn't work. 

![1](https://user-images.githubusercontent.com/284085/41556857-dfd2605a-7376-11e8-899b-b9febc2541d2.png)

I think all color value and settings are configured in theme file and ~/.oh-my-zsh/lib/theme-and-appearance.zsh. Now I cannot find any clue to this symptom. 

If anybody knows the reason, please let me know. 

Thanks.

**Comment by dmaj7** [comment]
in .zshrc, 'ls' was aliased to "/opt/local/bin/gls"
I'm still don't know why but when I delete above alias then set alias ls="ls --color=always" then 
delete all CLICOLOR & LS_COLORS settings from .zshrc. 
then .. the result is like this 
![2](https://user-images.githubusercontent.com/284085/41564461-cdc47616-738d-11e8-9bbf-a0d039b73053.png)

I'm not sure if it is fixed or not. I still don't understand why quotation mark set to the folder I created. 
2 days ago, all folders are just bold and color. 

I close this issue now. and If I find more about 'ls' related things, then I will share. 

Thanks.

**Comment by mcornella** [comment]
That's weird. What does `which -a ls` show, vs `which -a LS`?

**Comment by dmaj7** [comment]
mcornella: Thank you for your comment. 
the which results are like these. 

dmaj7@Dmaj7 % which -a ls                                                   ~
ls: aliased to ls --color=always
/opt/local/libexec/gnubin/ls
/bin/ls

dmaj7@Dmaj7 % which -a LS                                                   ~
/opt/local/libexec/gnubin/LS
/bin/LS

**Comment by mcornella** [comment]
Ok, so based on these results, it seems that if you delete the ls alias you would get the same behavior as `LS`. You can do that with `unalias ls`.
