### ISSUE TITLE
Is a bug when rm a symlink?

### ISSUE THREAD

**Issue by visoeclipse** [robbyrussell/oh-my-zsh#6931]
the uploads is a symlink,  eg:
lrwxrwxrwx  1 root   root     17 Jun 11 17:14 uploads -> /data/uploads

when i rm this symlink, 
➜  ~www rm uploads/
rm: cannot remove ‘uploads/’: Is a directory
➜  ~www rm -r uploads/
rm: cannot remove ‘uploads/’: Not a directory

**Comment by mcornella** [comment]
https://superuser.com/a/9191/545959
Not OMZ related.
