### ISSUE TITLE
my shell script said that command not found

### ISSUE THREAD

**Issue by hyunsooda** [robbyrussell/oh-my-zsh#6933]
my shell script

`#!/bin/bash`
`cat study.txt | `
`while read line`
`do`
`    echo "$line"`
`    $line`
`done`

my study.txt
cd mydir

Hello I'm korean student.
 When I changed "cd mydir" to "ls", it was working. and "cd mydir" is also working in my shell script file. but I'm not sure why is not working when I read sentence from file.

**Comment by mcornella** [comment]
You have to expand the contents of the variable `$line`, otherwise the behavior you get is trying to run `cd mydir` as if it's all the name of a command (i.e. it would look for a command named "cd mydir"). Use `${=line}` instead.
