### ISSUE TITLE
Not able to install for a user as a root

### ISSUE THREAD

**Issue by starx** [robbyrussell/oh-my-zsh#6936]
I was trying to configure Oh My Zsh for a user using root from chef and the install script apparently does not support this.

The install script heavily depends on "~" for the `.zshrc` path. If that part is configurable, this issue can be resolved.

**Comment by starx** [comment]
I have created a PR for this. https://github.com/robbyrussell/oh-my-zsh/pull/6937

**Comment by mcornella** [comment]
You can run the installer as another user using su: https://askubuntu.com/a/294748
