### ISSUE TITLE
Insecure completion-dependent directories messages won't go away

### ISSUE THREAD

**Issue by brightball** [robbyrussell/oh-my-zsh#6939]
For some reason whenever I switch from my user to root I get this message:

```
➜  ~ sudo -s                                                            
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x  11 barry barry 4096 Jun 13 20:41 /home/barry/.oh-my-zsh
drwxr-xr-x 244 barry barry 4096 Jun 13 20:41 /home/barry/.oh-my-zsh/plugins
drwxr-xr-x   2 barry barry 4096 Jun 13 20:41 /home/barry/.oh-my-zsh/plugins/asdf
drwxr-xr-x   2 barry barry 4096 Jun 13 20:41 /home/barry/.oh-my-zsh/plugins/git

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```

If run the compaudit command and it doesn't fix the issue. If I try manually fixing the permissions, it doesn't fix it. I'm not sure what I need to do to get this message correct. I saw a closed ticket that seemed to suggest just disabling the message, but I'd rather find out how to fix the actual problem if possible.

**Comment by mcornella** [comment]
Unfortunately, the way `compaudit` works is it looks for files and folders that have users and groups different from the current user and root.

When running as root, that comparison means that any user or group that isn't root will trigger a security warning. There is no alternative to disabling the message, other than not running root with your user's OMZ setup.

My choice: to put the following in `.zshenv` to disable the warning
```zsh
[[ $UID = 0 ]] && ZSH_DISABLE_COMPFIX=true
```

**Comment by Alsan** [comment]
I don't think the compaudit is necessary for me, therefore, I just place a "return 0" at the start of the compaudit. A better way should be provide an option to disable the compaudit completely, warning is acceptable, but not wait there for the input.

**Comment by mcornella** [comment]
`ZSH_DISABLE_COMPFIX=true` is the option to disable compaudit completely.

**Comment by BobbyWibowo** [comment]
Hmm, I still keep on getting on the compaudit thing even with this `ZSH_DISABLE_COMPFIX=true` at the very top of my `.zshrc` file.
```shell
➜  ~ sudo -s
[sudo] password for bobby: 
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y#
➜  ~ compaudit
There are insecure directories:
/home/bobby/.oh-my-zsh
/home/bobby/.oh-my-zsh
```

**Comment by benwoodward** [comment]
Also experiencing the same as Bobby. I have set up Homebrew to work with multiple users, which means /usr/local is owned by root, and I have a custom permissions group called 'brew', and that group has rwx permissions on /usr/local. 

If I remove the write permissions from these directories Homebrew starts throwing errors, and if I leave them on then zsh starts spitting out complaints. 

I've tried adding the `ZSH_DISABLE_COMPFIX=true` setting and get the exact same output as Bobby:

```bash
Last login: Fri Apr 19 12:33:56 on ttys008
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y

~/.oh-my-zsh
❯

~/.oh-my-zsh master
❯
```

**Comment by mcornella** [comment]
Can you verify you have the latest OMZ version with `upgrade_oh_my_zsh`, then trying again? Also double check that `ZSH_DISABLE_COMPFIX` is true with an `echo`.

**Comment by Kappyh** [comment]
I solved with ZSH_DISABLE_COMPFIX=true in the begin of the file ~/.zshrc

**Comment by benwoodward** [comment]
Unfortunately adding `ZSH_DISABLE_COMPFIX=true` to the top of my `~/.zshrc` doesn't completely make this problem go away. 

You should be able to reproduce this by adding group write permissions to the following directories:

```bash
sudo chmod g+w /usr/local/share/zsh /usr/local/share/zsh/site-functions
```

```bash
❯ echo $ZSH_DISABLE_COMPFIX
true

❯ upgrade_oh_my_zsh
Updating Oh My Zsh
From https://github.com/robbyrussell/oh-my-zsh
 * branch              master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at:  https://shop.planetargon.com/collections/oh-my-zsh
```

**Comment by LearningChanging** [comment]
`sudo chmod g-w /usr/local/share/zsh /usr/local/share/zsh/site-functions`
`sudo chmod o-w /usr/local/share/zsh /usr/local/share/zsh/site-functions`

**Comment by zhishaofei3** [comment]
chmod 755 /usr/local/share/zsh
chmod 755 /usr/local/share/zsh/site-functions
