### ISSUE TITLE
weird message from nyan plugin.

### ISSUE THREAD

**Issue by smeagolthellama** [robbyrussell/oh-my-zsh#6943]
I was browsing through the list of plugins, and came across the nyan plugin. Looking at its code and description I decided to try it. I added it, started a new session, and typed `nyan`. This is what I got:
```
DNS fwd/rev mismatch: nyancat.dakko.us != tsundere.me
nyancat.dakko.us [107.170.207.248] 23 (telnet) : Connection refused
```
My guess is that this is not what is supposed to happen, since this doesn't really match the description. What is the problem? Do I need to tweak my environmental variables? Or is it that the website has moved or something like that?

Output of `uname`: `Linux COMPUTER_NAME 4.16.0-2-686-pae #1 SMP Debian 4.16.12-1 (2018-05-27) i686 GNU/Linux`
oh-my-zsh is up to date, zsh version `zsh 5.5.1 (i686-debian-linux-gnu)`

**Comment by mcornella** [comment]
Extension of #6826. We should disable the plugin.

**Comment by smeagolthellama** [comment]
pity.
