### ISSUE TITLE
Copy pasted text appears in block/highlighted?

### ISSUE THREAD

**Issue by maxjowett** [robbyrussell/oh-my-zsh#6945]
I am hoping I am missing something obvious, once I have pasted a link inside of Hyper (e.g. a GitHub repo link to clone down), the text appears like so:

![screen shot 2018-06-24 at 4 31 53 pm](https://user-images.githubusercontent.com/33435443/41824848-284b1526-77cc-11e8-8c14-a8403815f19f.png)

I am using Hyper along with oh-my-zh and the default 'robbyrussell' theme. I had not touched my .zshrc file prior to experiencing this problem. However, I have since tried other themes but this issue still occurs.

Any help is appreciated!

**Comment by mcornella** [comment]
Reopen if this still happens, and try running zsh without rc files with `zsh -f`.

**Comment by digitaljhelms** [comment]
This is still happening and was also reported in the Hyper repo: https://github.com/zeit/hyper/issues/2588

**Comment by mcornella** [comment]
Is it confirmed to be an issue with Oh My Zsh? i.e. does it still happen when running  `zsh -f`?
