### ISSUE TITLE
Why you set WORDCHARS='' in lib/completion.zsh?

### ISSUE THREAD

**Issue by qoomon** [robbyrussell/oh-my-zsh#6948]
Why you set WORDCHARS='' in lib/completion.zsh?

**Comment by mcornella** [comment]
This was [added at the very beginning of OMZ](https://github.com/robbyrussell/oh-my-zsh/commit/5da20b9dddb1f7a9110675ded5df59c4c3ed1b83#diff-1cf34d3b138a6c8f242856c85478a390R7), possibly copied from [zshwiki.org](http://zshwiki.org/home/zle/bindkeys#most_wanted):
> One of the things I most missed about bash when first switching to Zsh was that M-b and M-f (backward-word and forward-word) would jump over an entire /path/location, rather than to each word separated by a '/'. To make the behavior more like bash, you can evaluate this command:
> 
> ```
> export WORDCHARS=''
> ```

I think we could refine that to only delete slashes from it, depending on what the user expects. There is already issue #5108 complaining about the current behavior. What characters do you expect to be treated as part of a word?

**Comment by zhanwenchen** [comment]
zsh should match bash in deleting an entire argument, including slashes and dots. For example,

```console
python -m module.method
```

Should delete to `python -m`, not `python -m module.`
