### ISSUE TITLE
rand-quote plugin URL must be updated

### ISSUE THREAD

**Issue by msafadieh** [robbyrussell/oh-my-zsh#6949]
I was trying out the plugin today and I ran into an error. @posva 

The URL being used in the plugin (http://www.quotationspage.com/random.php3) returns a 404 error. Removing the "3" at the end of the URL fixed it (both on the web and in the plugin).

Cheers!

**Comment by posva** [comment]
Indeed! You should fire a PR to fix it since you are the one who found out 😄
