### ISSUE TITLE
It seems like zsh relies directly on libgdbm.4.dylib

### ISSUE THREAD

**Issue by thillerson** [robbyrussell/oh-my-zsh#6956]
I recently upgraded *something*, at least MacVim, and it broke zsh. When I started a new zsh session it dies saying /usr/local/lib/libgdbm.4.dylib isn't found, which makes zsh broken.

I'm pretty sure this issue doesn't belong in oh-my-zsh's issues, but I'm not sure where it does belong. Any advice?

**Comment by mcornella** [comment]
Look at this thread https://github.com/Homebrew/legacy-homebrew/issues/27106

**Comment by thillerson** [comment]
@mcornella that thread did not help. Updating gdbm was the original problem for me, because it produced /usr/local/lib/libgdbm.6.dylib, while zsh seems to point explicitly to libgdbm.4.dylib.

**Comment by mcornella** [comment]
Is your zsh installed via brew?

**Comment by thillerson** [comment]
No, through oh-my-zsh. I realize this may not be a problem with oh-my-zsh, but I'm not sure where to take it next.

**Comment by thillerson** [comment]
Yes, my zsh is installed through brew, I guess. Looks like I should figure out what's going on there instead. Thanks - I didn't dig deep enough into where the root cause was.

**Comment by mcornella** [comment]
I'd advise you to seek help in the homebrew repository. Perhaps a reinstall of zsh will suffice though. Good luck!

**Comment by thillerson** [comment]
Sounds right. I just lumped together oh-by-zsh and zsh. In fact a brew
upgrade of zsh fixed my issue.

**Comment by Rishats** [comment]
Just reinstall my zsh help me on Mojave. 
```brew reinstall zsh```

**Comment by BSandipan** [comment]
I tried **brew upgrade zsh** and the problem got resolved.

**Comment by philipperemy** [comment]
`brew reinstall zsh` worked for me
