### ISSUE TITLE
zsh 5.3 colors: function definition file not found and command not found: compdef

### ISSUE THREAD

**Issue by Wkevin8** [robbyrussell/oh-my-zsh#6957]
```
/Users/pekon/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/Users/pekon/.oh-my-zsh/oh-my-zsh.sh:76: compinit: function definition file not found
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:95: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:102: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:125: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:135: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:169: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:172: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:174: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:190: command not found: compdef
/Users/pekon/.oh-my-zsh/plugins/git/git.plugin.zsh:202: command not found: compdef
➜  ~ zsh --version
zsh 5.3 (x86_64-apple-darwin17.0)
➜  ~ echo $FPATH
/Users/pekon/.oh-my-zsh/plugins/git:/Users/pekon/.oh-my-zsh/functions:/Users/pekon/.oh-my-zsh/completions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.3/functions
```
![image](https://user-images.githubusercontent.com/13580778/42080481-64da21ca-7bb5-11e8-8b6b-9010419e5471.png)

**Comment by mcornella** [comment]
What does `which -a zsh` return? Does it still happen if you run `zsh` after opening the terminal?

**Comment by Wkevin8** [comment]
@mcornella 
this is `which -a zsh` return
![image](https://user-images.githubusercontent.com/13580778/42141646-eec1b8b6-7ddc-11e8-912f-5c0739f30fe2.png)

this is `zsh` return
![image](https://user-images.githubusercontent.com/13580778/42141688-29d27a08-7ddd-11e8-8dcc-8b17d2d19eee.png)

**Comment by kitsuneflame** [comment]
I am having this same problem on zsh 5.5.1(x86_64-redhat-linux-gnu), Fedora 28.

**Comment by deeptechs** [comment]
I am having also same problem on zsh 5.5.1 on Ubuntu 16.04.

**which zsh** --> /bin/zsh
**zsh --version** --> zsh 5.5.1 (x86_64-unknown-linux-gnu)

**Comment by mcornella** [comment]
Please try the following:
```
echo $fpath

zsh -f
autoload colors && echo found || echo not found
echo $fpath
```

**Comment by ProbonoBonobo** [comment]
This issue isn't fixed, can you reopen?

![](https://i.imgur.com/hy1ZI96.png)

**Comment by mcornella** [comment]
Run `zsh -f` first, then type `echo $fpath; echo $FPATH`. If it comes empty, then you need to either reinstall zsh or patch it so that `$fpath` points to the functions directory of zsh. You can look it up, it should be `/usr/share/zsh/functions`, or `/usr/share/zsh/$ZSH_VERSION/functions`.

**Comment by Olivina** [comment]
maybe it's Lmod that cause the problem. See this article:
[Lmod FAQ](https://lmod.readthedocs.io/en/latest/040_FAQ.html)

> **If my startup shell is bash or tcsh and I start zsh, why do I get a message that is like: “/etc/zsh/zshrc:48: compinit: function definition file not found”**
Lmod supports both zsh and ksh. Both these shell use shell var. FPATH but in very different ways. The issue is that some bash or tcsh users run ksh scripts and need access to the module command. In the K-shell, the env. var. FPATH is exported and is the path to where the module shell function is found. Z-shell also uses FPATH to point to tool like compinit and others. By exporting FPATH, Z-shell does not change the value of FPATH which means that the zsh user can not find all the functions that make it work.
The solution is to add “unset FPATH” in your startup files before “exec zsh”.

In my case I have to uninstall the Lmod to ensure that both direct ssh and VSCode terminal run zsh completion correctly.
