### ISSUE TITLE
Rename rg alias from rails plugin (conflict with ripgrep)

### ISSUE THREAD

**Issue by stevensonmt** [robbyrussell/oh-my-zsh#6972]
In the rails plugin please remove or rename the "rg" alias for rails generate as it overrides the CLI command for [rip-grep](https://github.com/BurntSushi/ripgrep).

**Comment by hjpotter92** [comment]
Yes. Although I've now gotten used to using `\rg` for rip-grep...

**Comment by mcornella** [comment]
You can `unalias rg` to delete the alias. If more people have this problem I'll consider renaming it to `rge`.

**Comment by stevensonmt** [comment]
Yes that's what I've been doing. It's just mildly annoying to have to do it every new session.

**Comment by mcornella** [comment]
You can just put it in your zshrc file.

**Comment by jounathaen** [comment]
Probably a duplicate of #6385

**Comment by mcornella** [comment]
Follow the discussion there, thanks.
