### ISSUE TITLE
Themes update permission denied

### ISSUE THREAD

**Issue by GeVic** [robbyrussell/oh-my-zsh#6977]
When I try to update themes I get **permission denied** error in the terminal. To be exact that is:
```
permission denied: /home/gevic/.oh-my-zsh/themes/gnzh.zsh-theme
gevic@GeVic:/mnt/c/Users/GeVic%
```

**Comment by mcornella** [comment]
What do you mean by "update themes"?

**Comment by GeVic** [comment]
@mcornella  I was customizing some theme files within ```ohmyzsh``` folder but as soon as I  made changes and ran the terminal the above warning is displayed.

**Comment by mcornella** [comment]
You must have used a Windows app to edit it, so the permissions of the file might be broken. Try running `chmod 644 theme-file` and verifying the user and group of the file.

Using Windows apps to edit files internal to the WSL is strongly recommended against. See https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/
