### ISSUE TITLE
[BUG] Git double autocomplete

### ISSUE THREAD

**Issue by webknjaz** [robbyrussell/oh-my-zsh#6978]
Hi, 

I get the same branch autosuggested twice on `<Tab>`:
```zsh
$ git checkout feature/re
feature/refactor-systemd-module  -- Fix missing var
feature/refactor-systemd-module
```
even without `git` plugin.

**Comment by mcornella** [comment]
This is a bug in zsh which was fixed in zsh 5.7. See https://github.com/robbyrussell/oh-my-zsh/issues/7133#issuecomment-459517875
