### ISSUE TITLE
ssh-agent plugin doesn't load multiple identities

### ISSUE THREAD

**Issue by vielktus** [robbyrussell/oh-my-zsh#6979]
Hi,
I'm using `ssh-add` plugin https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ssh-agent. In the README.md, it says this:
```
To load multiple identities use the identities style, For example:
zstyle :omz:plugins:ssh-agent identities id_rsa id_rsa2 id_github
```

I already added this in my `~/.zshrc` before the line that sources oh-my-zsh like this:
```
zstyle :omz:plugins:ssh-agent identities id_rsa prd-key stg-key
source $ZSH/oh-my-zsh.sh
```
My `.ssh/` folder is having these keys:
```
 ll .ssh
-rw-------@ 1 122462    1.6K Feb 27 11:20 id_rsa
-rw-------@ 1 122462    1.7K Mar 28 14:54 prd-key
-rw-------@ 1 122462    1.6K Feb 27 11:26 stg-key
```

But when I executed `ssh-add -l`, only `id-rsa` was shown instead of all 3 keys:
```
ssh-add -l
2048 .ssh/id_rsa (RSA)
```

I'm expecting something like this:
```
ssh-add -l
2048 .ssh/id_rsa (RSA)
2048 .ssh/prd-key (RSA)
2048 .ssh/stg-key (RSA)
```
How can I solve this ? Did I miss anything ?

**Comment by mcornella** [comment]
You might have to kill the current ssh-agent processes and restart the zsh session.

**Comment by Shini31** [comment]
Same issue despite killing the ssh-agent process and launching a new zsh session

**Comment by mcornella** [comment]
Could you post a trace of the ssh-agent plugin? Run the following (after killing all ssh-agent processes):
```zsh
zsh -xvic 'exit' &> ~/omz-debug.log
```
And post the generated file as a private gist.

**Comment by riccardoerra** [comment]
I'm also having a similar problem.
In my case the `ssh-agent` plugin doesn't even start ssh-agent.

This is what I have in the `.zshrc` file:
```
plugins=(
  git
  ssh-agent
  zsh-nvm
)

# ssh-agent plugin setting
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities keyone_id_rsa keytwo_id_rsa
zstyle :omz:plugins:ssh-agent lifetime

source $ZSH/oh-my-zsh.sh
```

reloaded but no ssh-agent"
```
source ~/.zshrc

ps x | grep ssh-agent
 9536 s005  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ssh-agent
```

**Comment by mcornella** [comment]
@riccardoerra please follow https://github.com/robbyrussell/oh-my-zsh/issues/6979#issuecomment-407526192

**Comment by riccardoerra** [comment]
@mcornella First of all thanks for the help. Here it is the link to the log: https://gist.github.com/riccardoerra/8152b6cd5b54f1943410988c13240ba7

**Comment by mcornella** [comment]
@riccardoerra it looks like you're using agent forwarding and have an agent already executing (on path `/private/tmp/com.apple.launchd.8BlU11raP7/Listeners`), which seems to be launchd. Your issue is the exact same as #3019.

Relevant part of the log:
```
if [[ $_agent_forwarding == "yes" && -n "$SSH_AUTH_SOCK" ]]; then
	# Add a nifty symlink for screen/tmux if agent forwarding
	[[ -L $SSH_AUTH_SOCK ]] || ln -sf "$SSH_AUTH_SOCK" /tmp/ssh-agent-$USER-screen
elif [[ -f "$_ssh_env_cache" ]]; then
	# Source SSH settings, if applicable
	. $_ssh_env_cache > /dev/null
	if [[ $USER == "root" ]]; then
		FILTER="ax"
	else
		FILTER="x"
	fi
	ps $FILTER | grep ssh-agent | grep -q $SSH_AGENT_PID || {
		_start_agent
	}
else
	_start_agent
fi
+/Users/rerra/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:27> [[ yes == yes && -n /private/tmp/com.apple.launchd.8BlU11raP7/Listeners ]]
+/Users/rerra/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:29> [[ -L /private/tmp/com.apple.launchd.8BlU11raP7/Listeners ]]
+/Users/rerra/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:29> ln -sf /private/tmp/com.apple.launchd.8BlU11raP7/Listeners /tmp/ssh-agent-rerra-screen
```

**Comment by mcornella** [comment]
The rest of you check what `$SSH_AUTH_SOCK` returns, you might have the same issue.

**Comment by riccardoerra** [comment]
@mcornella, so how I should proceed to make the plugin work? I don't have `ForwardAgent` in my config file. Should I kill `$SSH_AUTH_SOCK` and try to launch `ssh-agent` plugin again?

**Comment by mcornella** [comment]
I'm not sure how to proceed. Maybe you could disable launchd's running ssh-agent?

**Comment by mcornella** [comment]
We could also test if a running ssh-agent has no identities loaded. `ssh-add -l` quits with an exit code of 1 if there are no identities, or 2 if there is no agent running.

**Comment by riccardoerra** [comment]
Update from my side. Restarted Mac and now `ssh-agent` starts but as other mentioned only loads one key.

If try to run command in the repo connected with second key I got this:
```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'rerra@rerra-mbp.(none)')
```

**Comment by Shini31** [comment]
Sorry for the delay.
I move to keychain instead of ssh-agent and now there is no more problem.

**Comment by mcornella** [comment]
@riccardoerra can you follow again https://github.com/robbyrussell/oh-my-zsh/issues/6979#issuecomment-407526192 now that it at least loads something (make sure to kill all ssh-agent process before)?

You're my only hope to debugging this 😄

**Comment by mcornella** [comment]
Hmm... that's the same situation as days ago, you're having ssh-agent started by Launchd so the plugin doesn't try to start it nor add the identities. I'll try to work on a better plugin that adds identities regardless of if the ssh-agent has already started.

**Comment by riccardoerra** [comment]
@mcornella I really not sure why last time I restarted my computer at least one key got added and this time we are back to square one... Thanks for your hard work on this!

**Comment by mcornella** [comment]
@riccardoerra I submitted #7174 to fix your use case.
