### ISSUE TITLE
pip plugin does not create cache

### ISSUE THREAD

**Issue by van51** [robbyrussell/oh-my-zsh#6981]
#### Problem 
Pip plugin with default pip index url "https://pypi.python.org/simple/" produces an empty cache.

#### Reproduce
```zsh
$ zsh-pip-clear-cache
$ zsh-pip-cache-packages
$ cat ~/.pip/zsh-cache # nothing here
```
#### Reason
Manually calling
```zsh
$ curl https://pypi.python.org/simple/
```
produces a 301 response "Moved permanently". This curl command does not follow redirects, so the *pip.plugin.zsh* script does not receive the index of the packages.

#### Suggested fixes
- Make command: "curl -L https://pypi.python.org/simple/" in the *pip.plugin.zsh* script, to follow redirects.
- Change the pip index url to "https://pypi.org/simple/", which seems to be the final url.

Both fixes work in my setup. Kindly let me know which one is preferred and if you 'd like me to submit a PR.

**Comment by mcornella** [comment]
Thanks, there's a PR in place at #6986.
