### ISSUE TITLE
[bug] zsh:no matches found: qrcode[pil]

### ISSUE THREAD

**Issue by jcjackchen** [robbyrussell/oh-my-zsh#6982]
➜  Project  pip install qrcode[pil]
zsh: no matches found: qrcode[pil]
➜  Project  exec bash
bash-3.2$ pip install qrcode[pil]
Requirement already satisfied: qrcode[pil] in /Library/Python/2.7/site-packages (6.0)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from qrcode[pil]) (1.4.1)
Requirement already satisfied: pillow; extra == "pil" in /Library/Python/2.7/site-packages (from qrcode[pil]) (5.2.0)

A bug that I found: 
when I am trying to install qrcode module which include pillow(pil) module, zsh told me that no matches found, but when I switch to bash, it worked just fine.

**Comment by mcornella** [comment]
You need to quote parameters that use square brackets or zsh will interpret it as you trying to expand it to an existing filename.
