### ISSUE TITLE
Where would I put the NPM_CHECK_INSTALLER environment variable?

### ISSUE THREAD

**Issue by matt3224** [robbyrussell/oh-my-zsh#6983]
Hi,

I need to add this as an env var but if i add it to .zshrc it runs it whenever i open the terminal. What should I do differently?

`NPM_CHECK_INSTALLER=pnpm npm-check -u`

Thanks!

**Comment by kleinjm** [comment]
Is that an env var or a function? If it's a function then you can define a function with whatever shorthand name you'd like. If it's an env var then add `export` in front and quotes around everything on the right side of the `=`

**Comment by matt3224** [comment]
Yes so if i do:
`export NPM_CHECK_INSTALLER='pnpm npm-check -u'` to set an environment variable as you say i get `spawn pnpm npm-check -u ENOENT`

Any ideas?

**Comment by mcornella** [comment]
Can you explain what you need to happen or some context? 

Closing as it is not OMZ-related.
