### ISSUE TITLE
Perplexing `COMP_POINT` value on bashcompinit tab completion

### ISSUE THREAD

**Issue by saveriomiroddi** [robbyrussell/oh-my-zsh#6992]
I use the OMZ/`bashcompinit` combination in order to write my tab completion scripts.

The tab completion itself works, however, I'm writing more complex scripts, and I find the `COMP_POINT` value perplexing, since it doesn't match the intuitive value (the position of the cursor in the string, which is what Bash returns).

Let's suppose you have a script named `/home/oooh_my_tab/scr`, whose autocompletion is defined via `complete -C "/path/to/myscript_completion" -o default scr`.

When typing:

```sh
$ scr <tab>
```

Bash sends to the completion script the env vars `COMP_LINE=scr ` and `COMP_POINT=4`. The number `4` is, intuitively, the position of the cursor (and the size of the `COMP_LINE` string).

Zsh sends `COMP_LINE=/home/oooh_my_tab/scr `, which is different but perfectly fine, but sends `COMP_POINT=23`, which is perplexing, since the position of the cursor is `22`.

When typing:

```sh
$ scr a<tab>
```

Bash sends `COMP_LINE=scr a` and `COMP_POINT=5`, which, again, has intuitive values.

Zsh sends `COMP_LINE=/home/oooh_my_tab/scr a`, and the now more perplexing `COMP_POINT=25`, which adds an unexpected extra unit to what was, in the previous example, an already apparently off-by-one value.

Is this a bug? Am I missing something? With such behavior, `COMP_POINT` breaks compatibility with Bash tab completion scripts.

**Comment by mcornella** [comment]
I have no idea about this, you might have better support in [zsh-users/zsh-completions](https://github.com/zsh-users/zsh-completions), or in the mailing list at [zsh.org/mla](https://zsh.org/mla).

I'm closing since this is not OMZ-related per se.

**Comment by saveriomiroddi** [comment]
Thanks and sorry. I thought bashcompinit was part of oh my zsh, but it actually is https://github.com/zsh-users/zsh (coincidentally, the last change to the file `Completion/bashcompinit` was a fix for `COMP_POINT`.

**Comment by mcornella** [comment]
Good to know!
