### ISSUE TITLE
Offline install 

### ISSUE THREAD

**Issue by cyrus104** [robbyrussell/oh-my-zsh#7001]
I would like to see if install can be updated to install from a local folder. I would like to download a copy of the master or release and then copy it to a couple of machines and then install it while they are offline.

Great project! 
Thanks

**Comment by mcornella** [comment]
You just need to extract it to a location (by default, we copy it to `$HOME/.oh-my-zsh`), then copy the file in `templates/zshrc.zsh-template` to `$HOME/.zshrc` and update [the ZSH variable of that file](https://github.com/robbyrussell/oh-my-zsh/blob/d3e3b2dd0d7c7574d2a47c0d3a0d79583c58b2b8/templates/zshrc.zsh-template#L5) to match the location where you've extracted Oh My Zsh.
