### ISSUE TITLE
installing did not work

### ISSUE THREAD

**Issue by SHADOWELITE7** [robbyrussell/oh-my-zsh#7004]
So I was watching this video about [Enhance your Web Development environment](https://www.youtube.com/watch?v=bBjg8t_2jN4&t=363s) using the [Hyper Terminal](https://hyper.is/). I typed in what I needed to install ``oh my zsh`` since it would not let me paste it into the terminal. the is what I got for the outcome.
![image](https://user-images.githubusercontent.com/33847580/42946101-17bd25e4-8b38-11e8-84a9-59878bee2e17.png)
Have I done something wrong or do I need to edit ``hyper.js``?

I am fairly new to using terminals

**Comment by mcornella** [comment]
You need to install WSL or use cygwin. We do not support Windows's cmd, which is what you're running in that screenshot.
