### ISSUE TITLE
Would like to package( make .deb) this module for Debian

### ISSUE THREAD

**Issue by Manas-kashyap** [robbyrussell/oh-my-zsh#7005]
I would like to package this module for Debian , so that apt install oh-my-zsh will work . 
So i need your permission to do it.

[Manas kashyap](wiki.debian.org/ManasKashyap)

**Comment by bwildenhain** [comment]
@Manas-kashyap oh-my-zsh is licensed under the MIT license, which is open source/free software, so anyone is allowed to package it without any special permission.
