### ISSUE TITLE
Example theme broken after upgrade

### ISSUE THREAD

**Issue by mlg-mentch** [robbyrussell/oh-my-zsh#7006]
I have been using the example theme for a long time, i recently got a new machine and tried to use it and it doesnt work.

ZSH version on my old machine = 5.0.5
ZSH version on new machine = 5.5.1

I also just updated oh-my-zsh on my old machine and it broke the example theme that machine too.

**Comment by mcornella** [comment]
Fixed in master. Please run `upgrade_oh_my_zsh`
