### ISSUE TITLE
error: unable to find utility "git", not a developer tool or in PATH

### ISSUE THREAD

**Issue by GuoZhiQiang** [robbyrussell/oh-my-zsh#7009]
When I open a new terminal  and use git in one of my projects.
It may say :`error: unable to find utility "git", not a developer tool or in PATH`.

If that happened , **quit the terminal and open it again** , the error will gone

**Comment by mcornella** [comment]
Try this https://stackoverflow.com/a/48738523/5798232
Not OMZ-related
