### ISSUE TITLE
No error message when adding comma separated plugin names.

### ISSUE THREAD

**Issue by Mortuie** [robbyrussell/oh-my-zsh#7013]
```sh
plugins=(
  git,
  docker,
  kubectl,
)
```
There is an extra comma.... So kubectl plugin doesn't work.
This should throw an error and say plugin "kubectl" or "" could not be found?

**Comment by mcornella** [comment]
On further thought, I won't label this issue as a bug since there is an example right above the `$plugins` definition which shows there shouldn't be any commas. Not a bug.
