### ISSUE TITLE
git branch display as file 

### ISSUE THREAD

**Issue by tianyuningmou** [robbyrussell/oh-my-zsh#7015]
I wish first photo, how can I do？
![2018-07-24 4 14 58](https://user-images.githubusercontent.com/15888216/43125538-ea0bdde2-8f5c-11e8-93e1-de215b29182b.png)
![2018-07-24 4 14 38](https://user-images.githubusercontent.com/15888216/43125553-f5cfeca4-8f5c-11e8-9301-d080f9a95df4.png)

**Comment by mcornella** [comment]
You can set your `core.pager` setting to a better default: `git config --global core.pager 'less -FX'`.

**Comment by ShowHandAce** [comment]
@tianyuningmou

**Comment by ShowHandAce** [comment]
@tianyuningmou 
https://stackoverflow.com/questions/48341920/git-branch-command-behaves-like-less
In case someone got the same issue.
