### ISSUE TITLE
dotenv plugin doesn't load .env when opening zsh from visual studio code

### ISSUE THREAD

**Issue by ple16** [robbyrussell/oh-my-zsh#7017]
Opening a project in visual studio code which uses zsh as it's integrated terminal doesn't load the project's .env file
It works when I manually cd out and back in to the project directory

**Comment by mcornella** [comment]
This must be because the chpwd hook is not called when the shell starts. I'll make a quick PR.

**Comment by AndrewKovalenko** [comment]
I have the same problem with latest installation of oh-my-zsh.

I've checked with `omz plugin list` that plugin is in the list of built-in plugins and `plugin enable dotenv` returns "omz::plugin::enable" however when I cd into directory with .env file - plugin doesn't load the file:

I even put specified explicitly 
```
ZSH_DOTENV_PROMPT=false
ZSH_DOTENV_FILE=.env
``` 
but still nothing. Could you please help to troubleshoot?
