### ISSUE TITLE
Bundler plugin stopped working

### ISSUE THREAD

**Issue by burlesona** [robbyrussell/oh-my-zsh#7019]
Sorry to open an issue here but this is a bit weird and I'm not even sure how to debug.

I've had oh-my-zsh installed for years with the bundler plugin and it has always worked perfectly. Recently it stopped working, that is, commands like `rails` and `rake` that should be `bundle exec` are not getting bundle exec'd anymore. I didn't make any changes to my shell, load paths, etc.

The weird thing is the plugin is installed and all the aliases work, I can run `be rails c` for example and the `be` alias for `bundle exec` IS defined and working. But the commands are not automatically bundled.

Any hint as to what might have gone wrong and how I can debug / fix this?

**Comment by mcornella** [comment]
What does `which -a rails rake` show?

**Comment by burlesona** [comment]
Hey @mcornella sorry for the delay, didn't see the notification for your comment.

```
code/project » which -a rails rake
/Users/me/.rbenv/shims/rails
/usr/bin/rails
rake: aliased to bundled_rake
/Users/me/.rbenv/shims/rake
/usr/bin/rake
```

Which now I'm realizing has never bundled rails. So now, side question, how do I add rails to the bundled commands list?

But also, rake seems not to be doing the right thing because I get different behavior when I run `rake` versus `bundle exec rake`.

For example in one project it complains about a require_relative not loading the correct version of a gem if I run `rake` but if I run `bundle exec rake` it's fine.

Any other suggestions?

**Comment by mcornella** [comment]
So `rake` is correctly bundled. `rails` can also be made to be bundled if you add it to `$BUNDLED_COMMANDS`, like so: `BUNDLED_COMMANDS=(rails)` (make sure to put it before sourcing OMZ).

The thing is that's always been the behavior, I'm not sure why you think the bundler plugin stopped working.
