### ISSUE TITLE
agnoster displays incorrectly

### ISSUE THREAD

**Issue by Nano-Sec** [robbyrussell/oh-my-zsh#7029]
![2018-08-02-104451_1201x345_scrot](https://user-images.githubusercontent.com/20042758/43564143-07cb0712-9643-11e8-9841-671c2508a70c.png)
There seem to be gaps with the badge that's displayed. Also the colors seem a bit dull. I'm not sure what's wrong here. I'm using powerline fonts.

**Comment by mcornella** [comment]
That's concerning your chosen powerline font and the font size setting in your terminal emulator. Play a bit with font sizes and powerline fonts until you have one that looks good.

As per the colors, look at the color scheme of your terminal emulator.

This is not OMZ related.

**Comment by Nano-Sec** [comment]
Yeah i realized that. Found this thread :
https://github.com/powerline/fonts/issues/176
It was an issue with urxvt. Switching the terminal fixed it. Thanks
