### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.4.dylib

### ISSUE THREAD

**Issue by panw3i** [robbyrussell/oh-my-zsh#7033]
mac version : 10.13.6 (17G65)

![image](https://user-images.githubusercontent.com/16938611/43618958-05392874-96fe-11e8-95a0-0398bb6d013c.png)

**Comment by mcornella** [comment]
Try a `brew upgrade zsh`.

**Comment by davidfells** [comment]
Hard to do a brew upgrade zsh when you can't run a terminal session at all...

Last login: Sun Aug 26 15:50:28 on ttys001
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.4.dylib
  Referenced from: /usr/local/bin/zsh
  Reason: image not found

[Process completed]

**Comment by tobegit3hub** [comment]
Works like a charm 👍

**Comment by teq0** [comment]
How can I run `brew upgrade zsh` when I can't open a terminal sessions because my shell is set to zsh?

**Comment by sergio-silva** [comment]
Thanks!

**Comment by yAoOw** [comment]
good ,sovled
