### ISSUE TITLE
how to set prompt colour to depend on hostname

### ISSUE THREAD

**Issue by RafalSkolasinski** [robbyrussell/oh-my-zsh#7035]
I recently came across https://github.com/robbyrussell/oh-my-zsh/issues/5686 that explains how to add username and/or hostname to default theme's prompt.

I wonder if there is an easy way to set different colours depending on the hostname, e.g.
hostname_name_1 -> red
hostname_name_2 -> blue
etc...

I would like to have it in form of some if / case way to be able to share same config across different computers.

**Comment by mcornella** [comment]
You could make a custom function `host_color` like:
```
case $HOST in
  host1) echo $fg[red] ;;
  host2) echo $fg[blue] ;;
  *) echo $fg[default] ;;
esac
```
or an associative alias that associates hostnames to a color:
```
local -a host_color
host_color=(
  host1  $fg[red]
  host2  $fg[blue]
  ...
)
```
then use `$host_color[$HOSTNAME]`.
