### ISSUE TITLE
check_for_upgrade does not work on shell init

### ISSUE THREAD

**Issue by ccqpein** [robbyrussell/oh-my-zsh#7036]
Hi guys, I just noticed my shell do not notify me `[Oh My Zsh] Would you like to update? [Y/n]:` for a long while.

I check shell code of `check_for_upgrade.sh` and search where this script running. I find in `oh-my-zsh.sh` line 14. There is not any information show in my terminal when I run manually `env ZSH=$ZSH ZSH_CACHE_DIR=$ZSH_CACHE_DIR DISABLE_UPDATE_PROMPT=$DISABLE_UPDATE_PROMPT zsh -f $ZSH/tools/check_for_upgrade.sh`

I have changed `${ZSH_CACHE_DIR}/.zsh-update` to `LAST_EPOCH=0`. Also, when I run `check_for_upgrade.sh` line 41 to 53 in shell (I have set $epoch_diff and $epoch_target), it works fine.

At endding, I figure out the problem. For some reason, `$ZSH/log/update.lock` already exist then `if` in 32 line of `check_for_upgrade.sh` return directly without running body of code. 

I thought it might be nice if we rmdir once before we enter if expression.

**Comment by ccqpein** [comment]
I add two lines to check `update.lock ` status and I sent pull request. 

[pull request 7037](
https://github.com/robbyrussell/oh-my-zsh/pull/7037)

**Comment by mcornella** [comment]
Remove the lock manually and `upgrade_oh_my_zsh`, there is now a fix in place.
