### ISSUE TITLE
Tab autocomplete: failed to load module `zsh/complist'

### ISSUE THREAD

**Issue by MacWeber** [robbyrussell/oh-my-zsh#7039]
After the latest upgrade, I while using `tab` to autocomplete I get some errors as the following lines:

```
_setup:8: failed to load module `zsh/complist': /usr/lib/x86_64-linux-gnu/zsh/5.0.7/zsh/complist.so: undefined symbol: brand
_setup:8: failed to load module `zsh/complist': /usr/lib/x86_64-linux-gnu/zsh/5.0.7/zsh/complist.so: undefined symbol: brand
_setup:8: failed to load module `zsh/complist': /usr/lib/x86_64-linux-gnu/zsh/5.0.7/zsh/complist.so: undefined symbol: brand
_main_complete:294: failed to load module `zsh/complist': /usr/lib/x86_64-linux-gnu/zsh/5.0.7/zsh/complist.so: undefined symbol: brand
```

I tried changing the theme, but it did not help.

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` and restarting the terminal.

**Comment by MacWeber** [comment]
I already had tried reinstalling ohmyzsh and it helped. Next time I will try your solution. Thanks!

**Comment by yiakwy** [comment]
@mcornella once you delete ~/.zcomdump*, `ubuntu zsh compinit: function definition file not found` prompted. The answer cannot be more silly. And I never use zsh again. I am in Ubuntu recovery mode.
