### ISSUE TITLE
alias grs="git reset"

### ISSUE THREAD

**Issue by jimbo1qaz** [robbyrussell/oh-my-zsh#7040]
CUrrently there is no alias for generalized `git reset`. Is it possible to add `alias grs="git reset"`, so users can tack on `--soft` and branch/file names?

**Comment by mcornella** [comment]
It's now `grh`: https://github.com/robbyrussell/oh-my-zsh/blob/91b771914bc7c43dd7c7a43b586c5de2c225ceb7/plugins/git/git.plugin.zsh#L215

**Comment by jimbo1qaz** [comment]
I assume this is for consistency with `grhh='git reset --hard'`, but I can't help but wonder where the `h` is located in the word `reset`.

**Comment by mcornella** [comment]
Because the previous versions used `HEAD` but we removed it because it was implicit.
