### ISSUE TITLE
tmux doesn't start

### ISSUE THREAD

**Issue by dawikur** [robbyrussell/oh-my-zsh#7041]
This is a regression after f584de5930467fd53e8b7d2e51f5227bc405e4b2.
In scenario when we have:
```bash
export ZSH_TMUX_AUTOCONNECT=false
```
tmux will not start:
```
63. [[ false == true ]] -> skip 'tmux_cmd attach' (correct)
68. [[ 0 -ne 0 ]] -> skip 'tmux_cmd new-session' (incorrect)
```

It should rather be something like (pseudocode) :
```bash
if [[ autoconnect == true ]]
  tmux attach
else
  tmux new-session
fi
```

Plus handling of  `$? -ne 0`

**Comment by Tolsto** [comment]
This is especially nasty when `ZSH_TMUX_AUTOSTART` is set to `true`. I couldn't open a terminal after the ZSH upgrade and had to edit the `.zshrc` in a graphical editor.

**Comment by mcornella** [comment]
Fixed. Thanks guys!
