### ISSUE TITLE
Issues on Install from AUR

### ISSUE THREAD

**Issue by DanitiKain** [robbyrussell/oh-my-zsh#7048]
I installed from AUR repo.  I then copied zshrc.zsh-template from /usr/share/oh-my-zsh/templates to ~/.zshrc.  I made a few changes to the directory where oh-my zsh is installed and I get the following error when running source ~/.zshrc

bash: autoload: command not found
bash: /usr/share/oh-my-zsh/oh-my-zsh.sh: line 34: syntax error near unexpected token `('
bash: /usr/share/oh-my-zsh/oh-my-zsh.sh: line 34: `for config_file ($ZSH/lib/*.zsh); do'

Here is the paste of my oh-my.zsh.sh
https://hastebin.com/icazasopes.bash

Here is my .zshrc file
https://hastebin.com/meduwiluju.bash

**Comment by mcornella** [comment]
You have to change your shell to zsh. You're running that with bash.
