### ISSUE TITLE
Got stuck when installing oh-my-zsh by using install.sh

### ISSUE THREAD

**Issue by eastera** [robbyrussell/oh-my-zsh#7055]
Got stuck when cloning from Github, it caused by using --depth=1 option, remove this, the script works.

**Comment by mcornella** [comment]
What `git --version` do you have?

**Comment by mcornella** [comment]
Can you try changing the parameter to `--depth 1` (without the equal sign)?

**Comment by eastera** [comment]
➜  ~ git --version
git version 2.15.2 (Apple Git-101.1)

This is my git version, and I haven't tried it without the equal sign.

**Comment by mcornella** [comment]
Please run this command: `git clone --depth 1 https://github.com/robbyrussell/oh-my-zsh.git` and report if it successfully clones the repository.

**Comment by eastera** [comment]
git clone --depth 1
This works fine for me.

**Comment by mcornella** [comment]
I can't reproduce this behavior in git 2.17.1, can you try the above command with `--depth=1`?

**Comment by eastera** [comment]
I have tried --depth=1 and --depth 1, the same behavior. But I used another laptop with git 2.15.2. Both all them works, so I think it could be my system problem~~~ Thanks for your help.

**Comment by mcornella** [comment]
Cool, it must've been a temporary glitch.
