### ISSUE TITLE
oh-my-zsh plugin using older version of git-flow-avh

### ISSUE THREAD

**Issue by istrasci** [robbyrussell/oh-my-zsh#7056]
https://github.com/robbyrussell/oh-my-zsh/blob/f2f078a1bbbce1631a99150029541544e621b6be/plugins/git-flow-avh/git-flow-avh.plugin.zsh

Why does my oh-my-zsh plugin use an older version of `git-flow-avh` than I have installed?

```zsh
» which git-flow
/usr/local/bin/git-flow

» /usr/local/bin/git-flow version
1.11.0 (AVH Edition)

» git flow version
1.9.1 (AVH Edition)
```
I'm not even sure how this is happening.

@petervanderdoes @rumpelsepp @YoshiMan @jkaving

**Comment by mcornella** [comment]
The `git-flow-avh` plugin only provides completion for git-flow. What you're seeing is the outcome of how git looks for the commands to be run. Look at this [example comment from git 2.7.4](https://github.com/git/git/blob/937978e0f3e750d917768c77665d5f8cfbd802b6/git.c#L681-L686):
```c
	/*
	 * We use PATH to find git commands, but we prepend some higher
	 * precedence paths: the "--exec-path" option, the GIT_EXEC_PATH
	 * environment, and the $(gitexecdir) from the Makefile at build
	 * time.
	 */
	setup_path();
```
In other words, what's probably happening is that you have a `git-flow` command inside `git --exec-path`, and that one is of an older version than the one found in your `$PATH`. If you're on Linux you can do `dpkg -S file` to know if and what package is responsible for putting it there.

**Comment by zx1986** [comment]
git-flow-avh completion totally not work for me now :-(

zsh 5.6.2 (x86_64-apple-darwin18.0.0)
git flow version  1.11.0 (AVH Edition)
oh-my-zsh latest
macOS 10.14.2 (18C54)
