### ISSUE TITLE
zsh: no matches found on curl URL

### ISSUE THREAD

**Issue by ourfor** [robbyrussell/oh-my-zsh#7058]
> here is the screenshot.
![screenshot_2018-08-12-21-44-13-313_com termux](https://user-images.githubusercontent.com/33711476/44002660-0b93407e-9e79-11e8-97d0-fcfded12a666.png)

I also run this command in my macOS. It also has this problem.

**Comment by mcornella** [comment]
You need to escape the question mark, otherwise zsh thinks it is a globbing or wildcard character and tries to find files that match it (that's why it says `no matches found`). Using double or single quotes is enough: `curl "wttr.in/Changsha?lang=zh"`.

**Comment by commadelimited** [comment]
I just came across this issue in my ZSH as well.

This seems like a bug that it should require escaping a valid URL character. My worker is able to run the same cURL command on his Mac without having to escape.

**Comment by rhowk** [comment]
if you are using basic auth as in " curl -u user:pass " just put the user in if it gives you errors and it will prompt you for the pass, which is good anyway since you shouldn't put pass on the cl anyway.
