### ISSUE TITLE
Change the value of HISTSIZE

### ISSUE THREAD

**Issue by sttyru** [robbyrussell/oh-my-zsh#7060]
Hello!

At the one server I need to store of all history. I found that history have the limit of 10000 records. How I can to change of the value of `HISTSIZE` (or need to change of value for `SAVEHIST` , or both)?
_I tryied to edit of `.zshrc` by adding of `HISTSIZE` by the end of file but after of shell was been restarted I've been no found of some changes._

Thanks.

**Comment by mcornella** [comment]
Adding your changes at the end of zshrc should be enough. Modify both `HISTSIZE` and `SAVEHIST`.

**Comment by faxotherapy** [comment]
Unfortunaly, it does no longer work anymore.
