### ISSUE TITLE
Display two batteries status?

### ISSUE THREAD

**Issue by DanitiKain** [robbyrussell/oh-my-zsh#7066]
I have a lenovo t450 which has an internal and a external battery.  It use the internal battery first then it uses the external battery.  Is there a way with zsh to show the battery status of both batteries via zsh?

**Comment by mcornella** [comment]
If there is a way in your system to access the charge levels of both, then you can adapt the battery plugin to use them. See https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/battery/battery.plugin.zsh
