### ISSUE TITLE
some lines in a few files is end with ^M

### ISSUE THREAD

**Issue by hellyguo** [robbyrussell/oh-my-zsh#7069]
After last auto update by oh-my-zsh self, my shell hit some error.
 ![screenshot](https://user-images.githubusercontent.com/1480942/44251187-07eb7e00-a22a-11e8-8b7e-0725fb07be91.png)
I found some lines in a few files was end with ^M. So I use dos2unix to convert them in correct format. It works.
```shell
dos2unix lib/functions.zsh
dos2unix -f lib/spectrum.zsh
dos2unix lib/termsupport.zsh
dos2unix plugins/git/git.plugin.zsh
dos2unix theme/philips.zsh-theme
```
And .oh-my-zsh's git version: `a52a5fb1f4a5ca4bacc67e117872cfc4eb1d6417`
And my os: `Fedora 28`
And my termial: `XTerm`

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351
