### ISSUE TITLE
Can't source bash_autocompletion: 

### ISSUE THREAD

**Issue by patrickvonplaten** [robbyrussell/oh-my-zsh#7070]
I have the zsh version on Ubuntu 18.04.1 LTS:
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

when trying to source the bash_autocompletion doing the following:
**autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
source /usr/share/bash-completion/bash_completion**

I get the following error message:
**/usr/share/bash-completion/bash_completion:1461: parse error near `|'**

Even when going into bash_completion and changing line 1461 from:
**if ! [[ "$i" =~ ^\~.*|^\/.* ]]; then**
to 
**if ! [[ "$i" =~ '^\~.*|^\/.*' ]]; then**

the following error comes: 
**/usr/share/bash-completion/bash_completion:2114: parse error near `\n'**

This error does not occur when sourcing the file being in bash terminal without having activated zsh

**Comment by mcornella** [comment]
This looks to me like differences in syntax. `bashcompinit` only defines the proper functions to enable interpreting bash completion files, but if there are syntax differences zsh will choke on them regardless. 

I suggest you go fixing them one by one until you find no errors, like you did with line 1461. If you do fix them and it still works in bash, I think you could even submit your changes upstream.

**Comment by bkarakashev** [comment]
Did u manage to resolve this I have the same issue?

**Comment by bkarakashev** [comment]
@patrickvonplaten ?

**Comment by mcornella** [comment]
You will get more problems down the line. Bash scripts are not made with zsh compatibility in mind, don't source them. If you still want to do this, look at the lines that the error complains about and try to fix them. I wouldn't do that though.
