### ISSUE TITLE
upgrade_oh_my_zsh fails with `cannot open .git/FETCH_HEAD: Permission denied`

### ISSUE THREAD

**Issue by mparada** [robbyrussell/oh-my-zsh#7071]
I'm on Mac OSX 10.13.6 and running zsh (5.5.1) in iterm2 (3.2.0).
This is what I get:
```
~> upgrade_oh_my_zsh
Updating Oh My Zsh
error: cannot open .git/FETCH_HEAD: Permission denied
There was an error updating. Try again later?
```

It is a clean install. I don't have any tracked file modified:
```
master ~/.oh-my-zsh> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
With `sudo` I get the same error.

I have ownership of the directory `.oh-my-zsh` and of the files `.zshrc` and `.zsh-history`. I also have ownership of my own home folder.

Any ideas?

**Comment by mparada** [comment]
Found a solution. Although I did have ownership for `.oh-my-zsh` I did not have ownership to all its sub-directories. `sudo chown -R username:admin .oh-my-zsh` solved the issue.

**Comment by bradwood** [comment]
I have the same problem when my `.oh-my-zsh` is symlinked to another folder. `chown` didn't help as all ownerships are me anyway. Any ideas?

**Comment by mcornella** [comment]
Check that the file it complains about is at least readable (if it is, and the error appears anyway, check that it is writable).

**Comment by hesto2** [comment]
@mcornella 's solution resolved the issue for me.
