### ISSUE TITLE
Probem with launching new terminal

### ISSUE THREAD

**Issue by imagnma** [robbyrussell/oh-my-zsh#7075]
Hello there, 
Everytime I luanch or open new terminal it greats me with this message 

```
Users/mo/.zshrc:source:2: no such file or directory: /oh-my-zsh.sh
``` 
and i have to source my zshrc file every time so i can have my normal shell back, 

I guess that problem happend back when I orgnized my dot files

**Comment by mcornella** [comment]
It seems like you don't have `$ZSH` defined when you source OMZ.
