### ISSUE TITLE
apt-get install of zsh on Ubuntu 18.04 not working at all

### ISSUE THREAD

**Issue by Pezzab** [robbyrussell/oh-my-zsh#7076]
I've been using zsh for a few years and have installed it on earlier versions of Ubuntu without issue, this is the first time I've installed it with apt-get.

After install, changing from bash and logging back in I follow the set of setup options offered (including the recommended ones) but once zsh is active nothing seems to work.

If I open .zshrc there are barely any settings (apart from HISTFILE etc), and not even the theme setting adding a theme and sourcing .zshrc has no effect.

I'd imagine on install there would at least be a populated default .zshrc with all the environmental settings as I've been used to with previous installs - at which point I usually start customising.

What is going wrong with my set up?

**Comment by mcornella** [comment]
You mean there is no OMZ? You have to install that as well, look at the README.

**Comment by Pezzab** [comment]
OK well that was weird - had no recollection of that part of the process - I assumed the apt-get replaced it altogether too. It's working now.

Thanks
