### ISSUE TITLE
Cannot uninstall oh-my-zsh 

### ISSUE THREAD

**Issue by marinakr** [robbyrussell/oh-my-zsh#7081]
➜  workspace uninstall_oh_my_zsh
Removing ~/.oh-my-zsh
Looking for original zsh config...
Found ~/.zshrc.pre-oh-my-zsh -- Restoring to ~/.zshrc
Found ~/.zshrc -- Renaming to ~/.zshrc.omz-uninstalled-20180821214458
Your original zsh config was restored. Please restart your session.
Thanks for trying out Oh My Zsh. It's been uninstalled.

Seem to be good, but when I open new tab in terminal, I get this:
Last login: Tue Aug 21 21:45:01 on ttys004
/Users/edenlab/.zshrc:source:68: no such file or directory: /Users/edenlab/.oh-my-zsh/oh-my-zsh.sh

And cannot use my custom bash profile

**Comment by D-sha** [comment]
Are you trying to go back to bash or stay with zsh?
What os?

**Comment by marinakr** [comment]
OS X 
I did not returned to bash and stay in tab where I run curl install script
That day I founded script uninstall, download in manually, chmod +x, run and that script  removed oh-my-zsh

**Comment by robbyrussell** [comment]
@marinakr Out of curiosity, what terminal app are/were you using? (i've seen some weird behavior with Hyper terminal, which is why I'm curious)

**Comment by marinakr** [comment]
MacOS default terminal
@jounathaen suggesting to close issue as it seems to be related  to another issue. I am not going to install it again and check so  I'll close it

**Comment by itkasumy** [comment]
zsh is a shit
