### ISSUE TITLE
zsh: command not found: wget

### ISSUE THREAD

**Issue by chaevnicher** [robbyrussell/oh-my-zsh#7085]
$ wget
zsh: command not found: wget
lol wtf?

**Comment by mcornella** [comment]
This is not a very helpful issue, have you done any effort to solve it by yourself? If it works in bash, the most probable cause is that your `$PATH` doesn't have the right directories in it. If that's so, you can compare with the value you see in bash and rectify it in your zshrc file accordingly.

**Comment by chaevnicher** [comment]
heh, this trouble arose after installation oh-my-zsh.
a reasonable question - why?

**Comment by D-sha** [comment]
I think @mcornella is asking you to do some basic troubleshooting. Comment back with the result of the following and i think i can help you:
`echo $PATH`
then change back to bash: `chsh /bin/bash`
`which wget`
`echo $PATH`
Cheers

**Comment by mcornella** [comment]
You don't really need to `chsh` to bash. Just run `bash`, see if wget works, then check what `echo $PATH` outputs.

> heh, this trouble arose after installation oh-my-zsh.
> a reasonable question - why?

It could be for many reasons. In a normal setup this doesn't happen, but perhaps you have a redefined `$PATH` somewhere in your zshrc file, or a custom `$PATH` in your ~/.bashrc or ~/.bash_profile files...

Maybe it's your installation of zsh: try running `zsh -f`, see if wget works now.

There are a million possibilities.

**Comment by nimsilvestre** [comment]
you should use `curl -O`

**Comment by BlaineOmega** [comment]
I had this same issue. Turns out that I didn't install wget on my Mac. I just did `brew install wget`. Works great now.

**Comment by carlos-ssh** [comment]
Very useful  @BlaineOmega Thanks.

**Comment by dlemm** [comment]
Thanks @BlaineOmega that was it.

**Comment by Canopix** [comment]
Thanks @BlaineOmega
