### ISSUE TITLE
Is there a way to let the prompt only show the first letter of each directory?

### ISSUE THREAD

**Issue by Fengzi21** [robbyrussell/oh-my-zsh#7089]
Is there a way to let the prompt only show the first letter of each directory?
e.g. `/c/r/g/b/y/b/white`if the working directory ls `/color/red/green/blue/yellow/black/white`,

**Comment by mcornella** [comment]
You can use the shrink_path plugin and adapt your theme with it. See the README for details: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/shrink-path/README.md .
