### ISSUE TITLE
Centos7, when i install zsh, it's look like this

### ISSUE THREAD

**Issue by PeterPuffer** [robbyrussell/oh-my-zsh#7091]
![image](https://user-images.githubusercontent.com/28674080/44629747-105c5b00-a986-11e8-8bae-191643fde077.png)
it looks like some commands of setting colors. how can i solve this problem?

**Comment by mcornella** [comment]
Have you installed ohmyzsh?

**Comment by PeterPuffer** [comment]
No，i dont install ohmyzsh in my linux machine, i installed it on my mac, but even if i didn't connect from iterm2, it will still like this.
![image](https://user-images.githubusercontent.com/28674080/44826421-8213fd80-ac41-11e8-9a5f-720d5f09f632.png)

**Comment by mcornella** [comment]
That looks like the sequence to define a bash prompt. Are you using a bash file inside zsh? Perhaps you've sourced a .bashrc or .profile in zsh.

Closing since this is not OMZ related.
