### ISSUE TITLE
Git plugin to: Rename Branch

### ISSUE THREAD

**Issue by InTheCloudDan** [robbyrussell/oh-my-zsh#7101]
Is the plugin open to have an alias like `rename_branch` or `git_rename_branch` with autocompletion it should still be quick to type and all of the git aliases in the current plugin are really only useful if you know what exactly that command does already.

So I was think `alias rename_branch="git branch -m"` or some semi-close variation to that. I just didn't want to open a PR without knowing if it's too far out there compared to existing.

**Comment by mcornella** [comment]
This is a thing that git users will know or be able to find easily without there being a dedicated alias with a descriptive name. Thanks for the suggestion though.
