### ISSUE TITLE
Some plugins can't work as it should be.

### ISSUE THREAD

**Issue by CodeLife2012** [robbyrussell/oh-my-zsh#7103]
I add `git brew osx gem` as plugins in `zshrc`, but it seems `osx gem` are not loaded as expected. If I manually source the `osx.plugin.zsh`, it just work.

Why and how can I fix this.

**Comment by CodeLife2012** [comment]
Use zsh 5.3 (x86_64-apple-darwin17.0) as the default shell.

**Comment by mcornella** [comment]
Please post your zshrc file.

**Comment by CodeLife2012** [comment]
```
# Path to your oh-my-zsh installation.
export ZSH=/Users/Karl/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="pygmalion"
#CDPATH="~/Code:$CDPATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh


# plugin
plugins=(git brew osx)

setopt +o nomatch

# custom config
source ~/.customrc.sh

fpath=(/usr/local/share/zsh/site-functions $fpath)

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

```

**Comment by D-sha** [comment]
Do plugins have to be loaded before source $ZSH/oh-my-zsh.sh?

**Comment by mcornella** [comment]
That's the thing precisely, they should be defined before sourcing. Closing

**Comment by CodeLife2012** [comment]
Great，it works now.

**Comment by D-sha** [comment]
@mcornella I cant see this documented anywhere. Would your like me to submit a PR?

**Comment by mcornella** [comment]
No need, it's already written the correct way in the zshrc template.
