### ISSUE TITLE
I want to delete all history command, but it does not work

### ISSUE THREAD

**Issue by shijiebei2009** [robbyrussell/oh-my-zsh#7106]
I also delete history files, such as
```
history -c
rm ~/.zsh_history
rm ~/.bash_history
```
and restart my iterm2, but when I press tab after`ssh admin@`, the history command come again, amazing, I want to delete all command history, but it appears always when I press tab

![111](https://user-images.githubusercontent.com/4994697/44942836-1e2e3800-aded-11e8-9a68-139766c53059.gif)

**Comment by mcornella** [comment]
That is not history, it's normal autocompletion. After you've deleted your history and reloading the session, you should see that if you run `history` there are no commands logged.

**Comment by shijiebei2009** [comment]
@mcornella the autocompletion is based on the history command, and if I delete all history command, why the autocompletion can load the history command, and what should I do can completely delete autocompletion history command?

**Comment by shijiebei2009** [comment]
Is there a way that I can delete autocompletion history command from oh-my-zsh?

**Comment by shijiebei2009** [comment]
this is my plugins
```
plugins=(
  git extract autojump zsh-autosuggestions
)
```

**Comment by mcornella** [comment]
It seems that zsh-autosuggestions is the culprit, but [they use the command history](https://github.com/zsh-users/zsh-autosuggestions/issues/179#issuecomment-233473237), so `history -c` should get rid of the suggestions. Make sure to have all terminal windows closed except one before running `history -c`, then close it and on the next session you shouldn't see any suggestions.
