### ISSUE TITLE
[fzf plugin] Wrong key-bindings.zsh folder

### ISSUE THREAD

**Issue by EtienneM** [robbyrussell/oh-my-zsh#7110]
I installed fzf using Arch Linux package manager. 
I just activated the fzf plugin.
Now, when I open a new shell, I get the following error message:

```
/home/XXXX/.oh-my-zsh/plugins/fzf/fzf.plugin.zsh:source:42: no such file or directory: /usr/share/fzf/shell/key-bindings.zsh
```

Indeed, my default `fzf_base` is `/usr/share/fzf`. But [here](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/fzf/fzf.plugin.zsh#L42), you try to `source "$fzf_base/shell/key-bindings.zsh"`. But my `fzf_base` folder contains: `completion.bash  completion.zsh  key-bindings.bash  key-bindings.zsh`

Ping @maxbrunet

**Comment by maxbrunet** [comment]
Hey @EtienneM, I opened a PR to fix this (#7119), let me know if it works for you.
I hadn't noticed the Archlinux package misses the `shell` directory, I wonder why the packagers didn't keep it (guidelines?).

Fedora kept it:
https://src.fedoraproject.org/cgit/rpms/fzf.git/tree/fzf.spec#n66

**Comment by EtienneM** [comment]
Your condition here (https://github.com/robbyrussell/oh-my-zsh/blob/16d6394e91b8592c8a5e63636f681d0b3f274f17/plugins/fzf/fzf.plugin.zsh#L28) does not really work as `uname -n` outputs my laptop name.

Maybe using `lsb_release` is a better fit here. On my laptop I can use:

```
$ lsb_release --id
Distributor ID:	Arch
```

**Comment by maxbrunet** [comment]
Oh I went too fast, `-n` is obviously the node, my VM was named archlinux. 🤦‍♂️
I pushed another commit, I use the `/etc/arch-release` file now.
I'm not sure `lsb_release` is always present.

**Comment by kronikpillow** [comment]
em... even after this pull on Arch it doesn't load the keybindings ... not sure why .. i set
EXPORT FZF_BASE=/usr/share/fzf in my .zshrc initialized the plugin, and it's not working
