### ISSUE TITLE
autojump: error: argument -i/--increase: invalid int value: 'work'

### ISSUE THREAD

**Issue by DL-85** [robbyrussell/oh-my-zsh#7111]
OS: macOS High Sierra
zsh: 5.5.1 and the latest master oh-my-zsh code (Add fzf plugin (#6910))
I found that when I write autojump after fasd in .zshrc file (like plugins=(fasd autojump))
The command j return error like "autojump: error: argument -i/--increase: invalid int value: 'work'"
When writing autojump before fasd, the command j working fine.
Before I git pull my oh-my-zsh config to the latest, plugins=(fasd autojump) working well.

**Comment by DL-85** [comment]
I finally found that is "alias j='zz'" which in fasd.plugin.zsh overrided the command j defined by autojum.zsh.
Delete fasd in plugins would solve the problem, but I have no idea how to use them both yet. (Although delete alias j='zz' which added by https://github.com/robbyrussell/oh-my-zsh/pull/3860 would work, but it may not be a good idea). Perhaps the author of https://github.com/robbyrussell/oh-my-zsh/pull/3860 may give some solutions

**Comment by mcornella** [comment]
You can run `unalias j` or put it in your zshrc file. I don't understand how that crashes autojump though...
