### ISSUE TITLE
Updating a plugin with local preferences

### ISSUE THREAD

**Issue by nevetS** [robbyrussell/oh-my-zsh#7115]
I wanted to change the prompt provided by the mercurial plugin (display the currently active bookmark rather than the branch).

I went into plugins/mercurial and made the change to the shell script.  I'm not seeing changes - even after logging out and logging in.

Is the file cached somewhere?  What is the proper way to update plugins with your own locally desired updates?

**Comment by nevetS** [comment]
I did find the section of the readme that talks about placing override code in custom/plugins/ which I also have tried.  (I copied plugins/mercurial/mercurial.plugin.zsh to custom/plugins/mercurial/mercurial.plugin.zsh and changed
```bash
function hg_get_branch_name() {
    if [ $(in_hg) ]; then
    echo $(hg branch)
  fi
}
```
to 
``` bash
function hg_get_branch_name() {
    if [ $(in_hg) ]; then
        echo "Why no work"
  fi
}

**Comment by nevetS** [comment]
It turned out that the theme I was using - agnoster - included it's own prompting code.

**Comment by mcornella** [comment]
Glad you found your answer. You can also customise themes in pretty much the same way or, in the case of agnoster, you can just redefine the `prompt_hg` function in your zshrc file.
