### ISSUE TITLE
Sdkman stopped working after oh-my-zsh update

### ISSUE THREAD

**Issue by lokeshh** [robbyrussell/oh-my-zsh#7120]
`mvn` used to work fine for me before I updated `oh-my-zsh` today. I installed `mvn` using sdkman and have this appended at the end of my `~/.zshrc`:

```export SDKMAN_DIR="/home/lokesh/.sdkman"```

When I do `which mvn` I get `mvn: aliased to mvn-or-mvnw` but I should be getting `/home/lokesh/.sdkman/candidates/maven/current/bin/mvn` which I get when I do `which mvn` in bash. Please help.

**Comment by lokeshh** [comment]
I managed to fixed the issue temporarily by appending `unalias mvn` in `~/.zshrc`.

**Comment by mcornella** [comment]
`mvn-or-mvnw` defaults to mvn when it can't find `mvnw`, so it shouldn't matter. The completion part has been added recently, so run `upgrade_oh_my_zsh` to get the latest changes.
