### ISSUE TITLE
I accidentally deleted the upgrade_oh_my_zsh

### ISSUE THREAD

**Issue by rdbox** [robbyrussell/oh-my-zsh#7121]
I had a desire to update I accidentally deleted the  ```upgrade_oh_my_zsh```
I decided to use the advice of the participants and typed this team ``` cd $ ZSH && git stash && cd -```

Then I lost the upgrade_oh_my_zsh file
What should I do to safely update?

**Comment by mcornella** [comment]
If you haven't made any modifications to the oh-my-zsh folder (`$ZSH`) that you wish to keep, you can just cd into it (`cd $ZSH`) and then type `git reset --hard origin/master`.
