### ISSUE TITLE
Contribute to cheatsheet

### ISSUE THREAD

**Issue by naquiroz** [robbyrussell/oh-my-zsh#7123]
Hi! I'm trying to make my first contribution, I would like to add some aliases missing to the cheatsheet. Can someone guide me to the steps on contributing. Please baby steps, its my first time :smile:

**Comment by grikomsn** [comment]
Do check #7175. You can make some documentations or update some plugins. 😄

**Comment by mcornella** [comment]
As @grikomsn said, the cheatsheet is no longer needed to be more documented, we're currently in need to add READMEs to plugins that don't have them. See https://github.com/robbyrussell/oh-my-zsh/issues/7175.
