### ISSUE TITLE
Automatic tab completion when filenames have a similar name

### ISSUE THREAD

**Issue by gitsnappy** [robbyrussell/oh-my-zsh#7124]
Say I have two files in the same folder, index.html and index.js.
I type in "ed ind", then hit tab.

Desired behavior: "ed index.html' populates. 
Then if I don't like that filename I can just keep tabbing through all files that start with 'ind'
Actual behavior:"ed index" populates

Reasoning: As it currently operates I have to hit the TAB button 4 times and it feels really clunky. Having "index" populate doesn't really save me any time as no "index" file exists and i have to keep mashing TAB a million times to get it what I want it to do.

**Comment by mcornella** [comment]
You can get that behavior with `setopt menucomplete`.
