### ISSUE TITLE
enhancement - include imagecat script out of the box

### ISSUE THREAD

**Issue by johndpope** [robbyrussell/oh-my-zsh#7129]
https://www.iterm2.com/documentation-images.html
https://www.iterm2.com/utilities/imgcat

<img width="989" alt="screen shot 2018-09-11 at 11 46 33 am" src="https://user-images.githubusercontent.com/289994/45371346-5f2a0780-b5b8-11e8-9017-0912c7f0aed5.png">

**Comment by mcornella** [comment]
It doesn't make sense to do that, imagecat is a separate program that should be installed separately.
