### ISSUE TITLE
Add plugin suggestion

### ISSUE THREAD

**Issue by lucarin91** [robbyrussell/oh-my-zsh#7131]
I do not have found information on how the plugin selection process works here, so sorry if I do something wrong.

Anyway, I want to suggest the inclusion of [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) and [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) plugins inside oh-my-zsh. These are very useful plugins that bring some fish-like features on zsh.

Let me know if I can do something to help.

**Comment by mcornella** [comment]
These plugins already have instructions on how to install them in Oh My Zsh, and bundling them in would suppose getting them up to date frequently. Thanks for the suggestion though
