### ISSUE TITLE
history-substring-search plugin doesn't set keybindings

### ISSUE THREAD

**Issue by gege251** [robbyrussell/oh-my-zsh#7137]
history-substring-search plugin used to work without setting anything, but now I had to set it in the .zshrc with:
```
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
```

**Comment by WildfootW** [comment]
Seems like happened after `* 285b540 - vi-mode show indicator on zle-line-init and SIGWINCH (#6449)<Balint Gyapjas>`

**Comment by irmowan** [comment]
I use `git revert 285b540` and fix this issue.

**Comment by hschne** [comment]
Different problem but same cause here.  After `285b540` `vi-mode` interferes with fzf on Antergos. 
Pressing `ESC` while using fzf keybindings (e.g. `Ctrl+R`) results in 

```
No such widget `zle-line-init'
```
Works fine on Ubuntu Mate for some reason. @irmowan's fix works for me on Antergos.
