### ISSUE TITLE
How to customize root user agnoster theme

### ISSUE THREAD

**Issue by RicoSpm** [robbyrussell/oh-my-zsh#7139]
Hi everyone,
I'm starting to use zsh shell. I noticed that when I switch to root user an arrow + the current directory are shown. How can I set a colored label (ex: root (in red)) instead of an arrow as root user?

Thank you guys!

**Comment by mcornella** [comment]
You should take a look at the code: https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme.

To delete the high voltage sign (⚡), which I assume is what you meant by arrow, you should delete the following line: https://github.com/robbyrussell/oh-my-zsh/blob/918a78cfdb92b9301168cb9d62d8ddbbdfd907f6/themes/agnoster.zsh-theme#L218

Then, you should modify the `prompt_context` function to print out root and the color red when the `$UID` is 0: https://github.com/robbyrussell/oh-my-zsh/blob/918a78cfdb92b9301168cb9d62d8ddbbdfd907f6/themes/agnoster.zsh-theme#L90-L94
