### ISSUE TITLE
Can't login to distant SSH server when using oh-my-zsh

### ISSUE THREAD

**Issue by Makaronelle** [robbyrussell/oh-my-zsh#7141]
I've recently wanted to try Oh My Zsh out, but I've bump into a frustrating issue. Whatever I do, I can't log into my Debian server using ssh when using zsh. Tried in verbose mode, it just ignores all my ssh keys, then asks for my password. Fine, I put in my password, make sure my password was all correct, but it just always says password wrong.

I'm using symbols in my password, and I'm also using french locales, that my lead to my issue, but I'm not sure what's causing it precisely.

**Comment by mcornella** [comment]
> I'm using symbols in my password, and I'm also using french locales, that my lead to my issue, but I'm not sure what's causing it precisely.

If you're using a different locale and symbols in your password your best bet is trying if typing out your password in the terminal gets you the correct one. Also make sure that you're ssh-ing to the right user.

Closing since this isn't an Oh My Zsh issue.
