### ISSUE TITLE
Messy code in the display 

### ISSUE THREAD

**Issue by xindzju** [robbyrussell/oh-my-zsh#7142]
![image](https://user-images.githubusercontent.com/42408511/45725325-f3195600-bbec-11e8-887b-106fa118da37.png)

the screen will display the "?" when I use the default scheme, does anyone know how to fix it?

**Comment by mcornella** [comment]
These are the representations of the arrow and x mark characters (➜ and ✗) respectively. You need to use a font and terminal emulator that supports them (look for unicode support) or change the theme.

**Comment by xindzju** [comment]
Thanks a lot.
