### ISSUE TITLE
git plugin aliases for `git checkout` not uniform

### ISSUE THREAD

**Issue by akwilliamson** [robbyrussell/oh-my-zsh#7147]
## Background

Git aliases seem to follow a pattern of a specific prefix for a specific command, followed by varying suffixes for various additional options. below are examples of other `gc` prefix commands to illustrate this pattern:

**`gc` == `git commit -v`**

- Any additional options passed to this command are suffixed onto the base **`gc`** alias

`gc!='git commit -v --amend'`
`gca='git commit -v -a'`
`gca!='git commit -v -a --amend'`
`gcam='git commit -a -m'`
`gcan!='git commit -v -a --no-edit --amend'`
`gcans!='git commit -v -a -s --no-edit --amend'`
`gcmsg='git commit -m'`
`gcn!='git commit -v --no-edit --amend'`
`gcs='git commit -S'`
`gcsm='git commit -s -m'`

**`gcp` == `git cherry-pick`**

`gcp='git cherry-pick'`

- Any additional options passed to this command are suffixed onto the base **`gcp`** alias

`gcpa='git cherry-pick --abort'`
`gcpc='git cherry-pick --continue'`

## Issue

The alias for `git checkout` does not continue this pattern of:
**`{uniform-alias-prefix}{option suffixes}`**

See below:

**`gco` == `git checkout`**

- Any additional options passed to this command **ARE NOT** suffixed onto the base **`gco`** alias. Instead, the **`o`** is omitted, mirroring instead the prefix pattern of **`gc`** which _should_ (IMO) be mapped to `git commit` commands.

`gcb='git checkout -b'`
`gcd='git checkout develop'`
`gcm='git checkout master'`

## Proposal 

`git checkout` aliases should be uniform to **`gco{option suffixes}`**. with the **`o`** always included in the prefix e.g:

`gcob='git checkout -b'`
`gcod='git checkout develop'`
`gcom='git checkout master'`

`git checkout` is one of the most common git commands, hence why I believe adhering to this uniform pattern is important enough to open this issue. What is the community's thoughts on this? There is a [PR](https://github.com/robbyrussell/oh-my-zsh/pull/7148) ready if the community agrees that this is an issue.

**Comment by akwilliamson** [comment]
What is the communities thoughts on this? I open the floor

**Comment by mcornella** [comment]
This is not really an issue: `gco` ends with an o because `gc` was already taken. Also, `gcb`, `gcm` and `gcd` are frequently used and an extra o would be noticed. Finally, changing aliases is a hard problem because people are already used to them.

Thanks for your contribution though.

**Comment by akwilliamson** [comment]
@robbyrussell Just want to confirm that you agree with @mcornella that this pattern shouldn't change with the reason being that people are already used to it being the way that it is.
