### ISSUE TITLE
precmd does not redraw when using dircycle

### ISSUE THREAD

**Issue by Jerry-Ma** [robbyrussell/oh-my-zsh#7149]
Hi,

I am using the "refine" (previously known as "pure") theme, which features a double-line style prompt, namely, `precmd()` and `PROMPT`.

However, this is incompatible with the plugin `dircycle`, which only do a `reset-prompt`. The effect of this is that the directory got changed, but the path text, which belongs to the `precmd()` part, does not update.

Any fix on this?

**Comment by mcornella** [comment]
Try these modifications:
```zsh
insert-cycledleft () {
        setopt localoptions nopushdminus
        switch-to-dir +1

        local fn
        for fn ($precmd_functions); do $fn; done
        zle reset-prompt
}
insert-cycledright () {
        setopt localoptions nopushdminus
        switch-to-dir -0

        local fn
        for fn ($precmd_functions); do $fn; done
        zle reset-prompt
}
```

**Comment by Jerry-Ma** [comment]
Thanks for the prompt investigation and quick fix.

The fix alone did not solve the issue, which is due to the fact that the refine theme code did not register its `precmd` function to the `precmd_functions` list. I had to make the change in the theme as follows:
```
diff --git a/themes/refined.zsh-theme b/themes/refined.zsh-theme
index 0e5681cc..4fe88c25 100644
--- a/themes/refined.zsh-theme
+++ b/themes/refined.zsh-theme
@@ -69,7 +69,7 @@ preexec() {

 # Output additional information about paths, repos and exec time
 #
-precmd() {
+theme_precmd() {
     vcs_info # Get version control info before we start outputting stuff
     print -P "\n$(repo_information) %F{yellow}$(cmd_exec_time)%f"
 }
@@ -79,6 +79,9 @@ precmd() {
 PROMPT="%(?.%F{magenta}.%F{red})❯%f " # Display a red prompt char on failure
 RPROMPT="%F{8}${SSH_TTY:+%n@%m}%f"    # Display username if connected via SSH

+autoload -U add-zsh-hook
+add-zsh-hook precmd theme_precmd
+
 # ------------------------------------------------------------------------------
 #
 # List of vcs_info format strings:
```

Anyways, thank you for the fantastic work. And feel free to cherry pick the above code.

**Comment by mcornella** [comment]
Ok, I've changed it to also try precmd if it exists:
```
insert-cycledleft () {
	setopt localoptions nopushdminus
	switch-to-dir +1

	local fn
	for fn (precmd $precmd_functions); do
		(( $+functions[$fn] )) && $fn
	done
	zle reset-prompt
}

insert-cycledright () {
	setopt localoptions nopushdminus
	switch-to-dir -0

	local fn
	for fn (precmd $precmd_functions); do
		(( $+functions[$fn] )) && $fn
	done
	zle reset-prompt
}
```

But the refine theme should probably be updated to use `$precmd_functions` as well.

**Comment by mcornella** [comment]
I've submitted #7161 with the fix

**Comment by mcornella** [comment]
I've verified that the PR fixes the issue. It prints the prompt in a newline but I don't think we can get it better than it is unless we change the precmd function to be a multiline prompt. But that's another topic anyhow.
