### ISSUE TITLE
Buggy characters at the beginning of each line

### ISSUE THREAD

**Issue by juancrescente** [robbyrussell/oh-my-zsh#7155]
I'm not sure how to reproduce this. The line does not begin in the first char as shown in the screenshot, but after the third one

![screenshot from 2018-09-24 16-23-03](https://user-images.githubusercontent.com/2141907/45973955-4ee14600-c016-11e8-9f82-0db5f1e30944.png)

**Comment by mcornella** [comment]
See #6985: it might be your `locale` configuration.
