### ISSUE TITLE
oh-my-zsh.sh:5: parse error near 'fi'

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [robbyrussell/oh-my-zsh#7156]
Hi, long time fan, first time bug filer

For whatever reason, I cannot get oh-my-zsh to install on OSX. This is happening on my work machine (Mid-2015 MBP, running High Sierra).

<img width="349" alt="screenshot 2018-09-24 17 46 24" src="https://user-images.githubusercontent.com/1289344/45983597-d634b680-c022-11e8-8615-edb91eefab93.png">

I've followed [the popular suggestion](https://github.com/robbyrussell/oh-my-zsh/issues/4402#issuecomment-290599606) for fixing this issue, but it doesn't resolve anything for me. 

Additional steps I have taken: I tried to automate installing oh-my-zsh and applying the aforementioned modifications. This manifested itself as this script:

```bash
#! /usr/local/bin/zsh

echo "\n removing ZSH \n"
rm -rf ~/.oh-my-zsh
echo "\n cloning ZSH \n"
git clone git@github.com:robbyrussell/oh-my-zsh ~/.whatever
echo "\n applying changes to ZSH \n"
(cd ~/.whatever && git config core.autocrlf input && git rm --cached -r . && git reset --hard)
echo "\n replacing ZSH \n"
cp -rf ~/.whatever ~/.oh-my-zsh
echo "\n copying ~/.zshrc \n"
cp ~/config_files/bash_profiles/zshrc.sh ~/.zshrc
echo "\n sourcing ~/.zshrc \n"
source ~/.zshrc
```

Without fail, the final line of output is `/Users/jeffrey.dorrycott/.oh-my-zsh/oh-my-zsh.sh:5: parse error near 'fi'`

I'm 100% open to the notion that I have done goofed here, but I'm also 100% unsure of how, given I seem to be doing everything I can find as a suggested solution. In case it's helpful [here](https://github.com/robbyrussell/oh-my-zsh/blob/14fead09641c17eb87e573e13b3c750bb98ea8cf/oh-my-zsh.sh#L5) is the line of code that my machine is complaining about.

**Comment by verygoodsoftwarenotvirus** [comment]
I'm more convinced than ever that this issue is tied to me and myself alone, sorry to take up time and space.

**Comment by mcornella** [comment]
Try changing your global git-config core.autocrlf to something other than true before making the git clone. Or post your solution if you've found one!
