### ISSUE TITLE
Path display error

### ISSUE THREAD

**Issue by Akemi-Homura** [robbyrussell/oh-my-zsh#7160]
There is an error in path displaying on Archlinux.
![image](https://user-images.githubusercontent.com/16780053/46024684-e8455080-c119-11e8-8c40-c4ef0d888c2b.png)
missing `"/"` after `"~"`
![image](https://user-images.githubusercontent.com/16780053/46024751-07dc7900-c11a-11e8-8304-e844908d550f.png)
display absolute path instead of `"~"`

**Comment by mcornella** [comment]
What theme are you using?

**Comment by Akemi-Homura** [comment]
@mcornella `fino`

**Comment by Akemi-Homura** [comment]
@mcornella other themes also has this problem

**Comment by Akemi-Homura** [comment]
@mcornella 
![image](https://user-images.githubusercontent.com/16780053/46122660-83d6de00-c24c-11e8-9b28-3c7aeab50cee.png)

**Comment by mcornella** [comment]
I can't reproduce your issue. Is it possible that you have a modified theme? What does `echo $PROMPT` show? (copy and paste the output)

**Comment by Akemi-Homura** [comment]
@mcornella 
```shell
╭─%{%{%}%}%n%{%} %{%{%}%}at%{%} %{%{%}%}archlinux%{%} %{%{%}%}in%{%} %{%{%}%}${PWD/#$HOME/~}%{%}$(git_prompt_info) %{%{%}%}
╰─$(prompt_char)%{%}
```
![image](https://user-images.githubusercontent.com/16780053/46182613-847c7c80-c2ff-11e8-9baa-36f71160fe69.png)

**Comment by mcornella** [comment]
Your `$PROMPT` looks fine. I don't actually know what's going on... What `zsh --version` do you have?

**Comment by Akemi-Homura** [comment]
```shell
zsh 5.6.2 (x86_64-pc-linux-gnu)
```
![image](https://user-images.githubusercontent.com/16780053/46276550-059f7200-c593-11e8-9ea4-143200786ae9.png)

**Comment by mcornella** [comment]
What about `echo $HOME`?

**Comment by Akemi-Homura** [comment]
@mcornella 
```shell
/home/quals
```
![image](https://user-images.githubusercontent.com/16780053/46577351-0bc0a300-ca18-11e8-8c5c-1136f7864b06.png)

**Comment by mcornella** [comment]
Yeah, see the problem is that `$HOME` has an extra trailing slash, that's why `${PWD/#$HOME/~}` doesn't work. Are you setting `$HOME` somewhere in your zshrc file?

Most probably though, the home field in `/etc/passwd` for your user has a trailing slash, when it should be just `/home/quals`. Please check that out.

**Comment by mcornella** [comment]
https://github.com/robbyrussell/oh-my-zsh/commit/3a6fa9149b7a3db89d22f40ae371ad636f5ed527 fixes this edge case.

**Comment by Akemi-Homura** [comment]
@mcornella Thank you! It's so kind of you!
