### ISSUE TITLE
`source` points to the wrong directory in MSYS2 when Cygwin is installed

### ISSUE THREAD

**Issue by wayne-chen** [robbyrussell/oh-my-zsh#7164]
I have both Cygwin and MSYS2 installed on my PC.  I'm unable to launch `oh-my-zsh` after it has been installed successfully on one versus the other.

```
wayne@0620-DESKTOP-PC MSYS ~/development/hifi-fork
$ zsh
/c/Users/wayne/.zshrc:source:69: no such file or directory: /cygdrive/c/Users/wayne/.oh-my-zsh/oh-my-zsh.sh
\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$
\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$ exit
```
If I perform these steps I can get it working.

![image](https://user-images.githubusercontent.com/10539521/46095416-5406d800-c171-11e8-9234-188a208a6abc.png)

Is it because there can only be one or the other linked to `oh-my-zsh`?

**Comment by mcornella** [comment]
It's possible the `$ZSH` variable wasn't set correctly, you should see its value at the top of the .zshrc file.
