### ISSUE TITLE
complete:13: command not found: compdef #3356

### ISSUE THREAD

**Issue by Nicole1991** [robbyrussell/oh-my-zsh#7171]
hi.
I am getting this error when I launch a new terminal window.[#3356](https://github.com/robbyrussell/oh-my-zsh/issues/3356#issuecomment-94344463)

`complete:13: command not found: compdef`
 my zsh version is 
"zsh 5.4.1 (x86_64-apple-darwin16.7.0)"

I have tried two way in issue #3356 like below, but they are useless.
```
rm ~/.zcompdump*
➜  ~ exec zsh
complete:13: command not found: compdef
```
```
compaudit | xargs -I '%' chmod g-w,o-w '%'
➜  ~ rm ~/.zcompdump*
➜  ~ exec zsh
complete:13: command not found: compdef
```

@mcornella 
anySuggestion? I will appreciate it if anyone can help.

**Comment by mcornella** [comment]
What does `compaudit` return?

And also, if you run `zsh -f`, then execute `autoload compinit && compinit`, what does `which compdef` print?

**Comment by mcornella** [comment]
Also post your zshrc file in case you're doing something out of the ordinary.

**Comment by letpeter** [comment]
I got the same error.  Here is the output of my compdef.

MacBook-Pro% autoload compinit && compinit
MacBook-Pro% which compdef
compdef () {
	local opt autol type func delete eval new i ret=0 cmd svc
	local -a match mbegin mend
	emulate -L zsh
	setopt extendedglob
	if (( ! $# ))
	then
		print -u2 "$0: I need arguments"
		return 1
	fi
	while getopts "anpPkKde" opt
	do
		case "$opt" in
			(a) autol=yes  ;;
			(n) new=yes  ;;
			([pPkK]) if [[ -n "$type" ]]
				then
					print -u2 "$0: type already set to $type"
					return 1
				fi
				if [[ "$opt" = p ]]
				then
					type=pattern
				elif [[ "$opt" = P ]]
				then
					type=postpattern
				elif [[ "$opt" = K ]]
				then
					type=widgetkey
				else
					type=key
				fi ;;
			(d) delete=yes  ;;
			(e) eval=yes  ;;
		esac
	done
	shift OPTIND-1
	if (( ! $# ))
	then
		print -u2 "$0: I need arguments"
		return 1
	fi
	if [[ -z "$delete" ]]
	then
		if [[ -z "$eval" ]] && [[ "$1" = *\=* ]]
		then
			while (( $# ))
			do
				if [[ "$1" = *\=* ]]
				then
					cmd="${1%%\=*}"
					svc="${1#*\=}"
					func="$_comps[${_services[(r)$svc]:-$svc}]"
					[[ -n ${_services[$svc]} ]] && svc=${_services[$svc]}
					[[ -z "$func" ]] && func="${${_patcomps[(K)$svc][1]}:-${_postpatcomps[(K)$svc][1]}}"
					if [[ -n "$func" ]]
					then
						_comps[$cmd]="$func"
						_services[$cmd]="$svc"
					else
						print -u2 "$0: unknown command or service: $svc"
						ret=1
					fi
				else
					print -u2 "$0: invalid argument: $1"
					ret=1
				fi
				shift
			done
			return ret
		fi
		func="$1"
		[[ -n "$autol" ]] && autoload -Uz "$func"
		shift
		case "$type" in
			(widgetkey) while [[ -n $1 ]]
				do
					if [[ $# -lt 3 ]]
					then
						print -u2 "$0: compdef -K requires <widget> <comp-widget> <key>"
						return 1
					fi
					[[ $1 = _* ]] || 1="_$1"
					[[ $2 = .* ]] || 2=".$2"
					[[ $2 = .menu-select ]] && zmodload -i zsh/complist
					zle -C "$1" "$2" "$func"
					if [[ -n $new ]]
					then
						bindkey "$3" | IFS=$' \t' read -A opt
						[[ $opt[-1] = undefined-key ]] && bindkey "$3" "$1"
					else
						bindkey "$3" "$1"
					fi
					shift 3
				done ;;
			(key) if [[ $# -lt 2 ]]
				then
					print -u2 "$0: missing keys"
					return 1
				fi
				if [[ $1 = .* ]]
				then
					[[ $1 = .menu-select ]] && zmodload -i zsh/complist
					zle -C "$func" "$1" "$func"
				else
					[[ $1 = menu-select ]] && zmodload -i zsh/complist
					zle -C "$func" ".$1" "$func"
				fi
				shift
				for i
				do
					if [[ -n $new ]]
					then
						bindkey "$i" | IFS=$' \t' read -A opt
						[[ $opt[-1] = undefined-key ]] || continue
					fi
					bindkey "$i" "$func"
				done ;;
			(*) while (( $# ))
				do
					if [[ "$1" = -N ]]
					then
						type=normal
					elif [[ "$1" = -p ]]
					then
						type=pattern
					elif [[ "$1" = -P ]]
					then
						type=postpattern
					else
						case "$type" in
							(pattern) if [[ $1 = (#b)(*)=(*) ]]
								then
									_patcomps[$match[1]]="=$match[2]=$func"
								else
									_patcomps[$1]="$func"
								fi ;;
							(postpattern) if [[ $1 = (#b)(*)=(*) ]]
								then
									_postpatcomps[$match[1]]="=$match[2]=$func"
								else
									_postpatcomps[$1]="$func"
								fi ;;
							(*) if [[ "$1" = *\=* ]]
								then
									cmd="${1%%\=*}"
									svc=yes
								else
									cmd="$1"
									svc=
								fi
								if [[ -z "$new" || -z "${_comps[$1]}" ]]
								then
									_comps[$cmd]="$func"
									[[ -n "$svc" ]] && _services[$cmd]="${1#*\=}"
								fi ;;
						esac
					fi
					shift
				done ;;
		esac
	else
		case "$type" in
			(pattern) unset "_patcomps[$^@]" ;;
			(postpattern) unset "_postpatcomps[$^@]" ;;
			(key) print -u2 "$0: cannot restore key bindings"
				return 1 ;;
			(*) unset "_comps[$^@]" ;;
		esac
	fi
}
MacBook-Pro%

**Comment by letpeter** [comment]
`test`

**Comment by Nicole1991** [comment]
when run compaudit， there didn‘t return anything in my terminal，
and also，there are which compdef print as below：
zsh -f 
CNqyzhao% autoload compinit && compinit
CNqyzhao% which compdef
compdef () {
	local opt autol type func delete eval new i ret=0 cmd svc
	local -a match mbegin mend
	emulate -L zsh
	setopt extendedglob
	if (( ! $# ))
	then
		print -u2 "$0: I need arguments"
		return 1
	fi
	while getopts "anpPkKde" opt
	do
		case "$opt" in
			(a) autol=yes  ;;
			(n) new=yes  ;;
			([pPkK]) if [[ -n "$type" ]]
				then
					print -u2 "$0: type already set to $type"
					return 1
				fi
				if [[ "$opt" = p ]]
				then
					type=pattern
				elif [[ "$opt" = P ]]
				then
					type=postpattern
				elif [[ "$opt" = K ]]
				then
					type=widgetkey
				else
					type=key
				fi ;;
			(d) delete=yes  ;;
			(e) eval=yes  ;;
		esac
	done
	shift OPTIND-1
	if (( ! $# ))
	then
		print -u2 "$0: I need arguments"
		return 1
	fi
	if [[ -z "$delete" ]]
	then
		if [[ -z "$eval" ]] && [[ "$1" = *\=* ]]
		then
			while (( $# ))
			do
				if [[ "$1" = *\=* ]]
				then
					cmd="${1%%\=*}"
					svc="${1#*\=}"
					func="$_comps[${_services[(r)$svc]:-$svc}]"
					[[ -n ${_services[$svc]} ]] && svc=${_services[$svc]}
					[[ -z "$func" ]] && func="${${_patcomps[(K)$svc][1]}:-${_postpatcomps[(K)$svc][1]}}"
					if [[ -n "$func" ]]
					then
						_comps[$cmd]="$func"
						_services[$cmd]="$svc"
					else
						print -u2 "$0: unknown command or service: $svc"
						ret=1
					fi
				else
					print -u2 "$0: invalid argument: $1"
					ret=1
				fi
				shift
			done
			return ret
		fi
		func="$1"
		[[ -n "$autol" ]] && autoload -Uz "$func"
		shift
		case "$type" in
			(widgetkey) while [[ -n $1 ]]
				do
					if [[ $# -lt 3 ]]
					then
						print -u2 "$0: compdef -K requires <widget> <comp-widget> <key>"
						return 1
					fi
					[[ $1 = _* ]] || 1="_$1"
					[[ $2 = .* ]] || 2=".$2"
					[[ $2 = .menu-select ]] && zmodload -i zsh/complist
					zle -C "$1" "$2" "$func"
					if [[ -n $new ]]
					then
						bindkey "$3" | IFS=$' \t' read -A opt
						[[ $opt[-1] = undefined-key ]] && bindkey "$3" "$1"
					else
						bindkey "$3" "$1"
					fi
					shift 3
				done ;;
			(key) if [[ $# -lt 2 ]]
				then
					print -u2 "$0: missing keys"
					return 1
				fi
				if [[ $1 = .* ]]
				then
					[[ $1 = .menu-select ]] && zmodload -i zsh/complist
					zle -C "$func" "$1" "$func"
				else
					[[ $1 = menu-select ]] && zmodload -i zsh/complist
					zle -C "$func" ".$1" "$func"
				fi
				shift
				for i
				do
					if [[ -n $new ]]
					then
						bindkey "$i" | IFS=$' \t' read -A opt
						[[ $opt[-1] = undefined-key ]] || continue
					fi
					bindkey "$i" "$func"
				done ;;
			(*) while (( $# ))
				do
					if [[ "$1" = -N ]]
					then
						type=normal
					elif [[ "$1" = -p ]]
					then
						type=pattern
					elif [[ "$1" = -P ]]
					then
						type=postpattern
					else
						case "$type" in
							(pattern) if [[ $1 = (#b)(*)=(*) ]]
								then
									_patcomps[$match[1]]="=$match[2]=$func"
								else
									_patcomps[$1]="$func"
								fi ;;
							(postpattern) if [[ $1 = (#b)(*)=(*) ]]
								then
									_postpatcomps[$match[1]]="=$match[2]=$func"
								else
									_postpatcomps[$1]="$func"
								fi ;;
							(*) if [[ "$1" = *\=* ]]
								then
									cmd="${1%%\=*}"
									svc=yes
								else
									cmd="$1"
									svc=
								fi
								if [[ -z "$new" || -z "${_comps[$1]}" ]]
								then
									_comps[$cmd]="$func"
									[[ -n "$svc" ]] && _services[$cmd]="${1#*\=}"
								fi ;;
						esac
					fi
					shift
				done ;;
		esac
	else
		case "$type" in
			(pattern) unset "_patcomps[$^@]" ;;
			(postpattern) unset "_postpatcomps[$^@]" ;;
			(key) print -u2 "$0: cannot restore key bindings"
				return 1 ;;
			(*) unset "_comps[$^@]" ;;
		esac
	fi
}

**Comment by mcornella** [comment]
The culprit are these lines:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
which are run before OMZ has had a chance to run compinit, which is what defines `compdef`. That's why you get the error.

To solve it, put these lines after OMZ has been sourced and you'll be good to go.

**Comment by Nicole1991** [comment]
That‘s works，thank you so much！ @mcornella

**Comment by samspycher** [comment]
You may have the same issue with 
```
source <(kubectl completion zsh)
```
which was in my `~/.zprofile`. Change to something like the following, and add it after sourcing `$ZSH/oh-my-zsh.sh` in `~/.zshrc`:
```
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)
```
