### ISSUE TITLE
permission denied: /root/.oh-my-zsh/oh-my-zsh.sh

### ISSUE THREAD

**Issue by dmatija** [robbyrussell/oh-my-zsh#7182]
At my home-lab setup, I run RedHat, and only **root** user has ALL privileges.
Regular user "**skeleto**" and he can't run any of yum install or any root privileges 
So, I install "**zsh**" and "**oh-my-zsh**" as **root** and setup all. All work fine as root.

Then i run next
> [skeleto@olimp ~]$ chsh -s /bin/zsh 
> Changing shell for skeleto.
> Password: 
> Shell changed.

and when i relog to be sure for apply all, i got this
`/home/skeleto/.zshrc:source:68: permission denied: /root/.oh-my-zsh/oh-my-zsh.sh`

Any words of wisdom ?

**Comment by mcornella** [comment]
Make sure you have read permissions set for others

**Comment by dmatija** [comment]
> Looks to me like $ZSH is being set to /root/ instead of /home/skeleto
> Does this persist logout / reboot?

skeleto user .zshrc file look's like this:   export ZSH="/root/.oh-my-zsh"
however skeleto user don't have .oh-my-zsh folder. he only hawe .zshrc file that point as is say in export

> Make sure you have read permissions set for others

as root i set:
`chmod -R 755 /root/.oh-my-zsh/`

i try 777 but no help at all

**Comment by mcornella** [comment]
I think the /root folder doesn't have read permissions by default.

**Comment by dmatija** [comment]
> I think the /root folder doesn't have read permissions by default.

worked =)
Thing is that I have done a few changes in the kernel and not sure what exactly caused this if that change was the source of problems.

thanks...

**Comment by WuG978** [comment]
> > I think the /root folder doesn't have read permissions by default.
> 
> worked =)
> Thing is that I have done a few changes in the kernel and not sure what exactly caused this if that change was the source of problems.
> 
> thanks...

I have the same problem that I cant deal with, would you like to give me some direction?

**Comment by mcornella** [comment]
Look at `/root` permissions (`ls -d /root`), the read permissions are probably disabled. You would have to enable them (`chmod +r /root`), **but I recommend instead** that, if you want to follow @dmatija's setup, that you install OMZ someplace other than `/root` (some users choose `/usr/share`, `/opt` would also work).
