### ISSUE TITLE
plugin colorize "false not detecting pygments"

### ISSUE THREAD

**Issue by g-uru** [robbyrussell/oh-my-zsh#7240]
In the plugin, the function to detect if pygments is installed does not work on WSL or MSYS2 on Windows 10 Prof, it will always return ` Pygments is not installed!` If commented out the plugin works as intended though. Oddly `which pygmentize` prints `pygmentize: aliased to pygmentize -O style=monokai`. Im not sure whats wrong.

```zsh
colorize_via_pygmentize() {  
#    if [ ! -x "$(which pygmentize)" ]; then  
#       echo "package \'Pygments\' is not installed!"  
#        return -1  
#    fi  

    if [ $# -eq 0 ]; then  
        pygmentize -g $@  
    fi  

    for FNAME in $@  
    do  
        filename=$(basename "$FNAME")  
        lexer=pygmentize -N \"$filename\"  
        if [ "Z$lexer" != "Ztext" ]; then  
            pygmentize -l $lexer "$FNAME"  
        else  
            pygmentize -g "$FNAME"  
        fi  
    done  
}
```

**Comment by mcornella** [comment]
I've submitted #7242 to fix this case. Please test it and report if it works (it should work).

**Comment by mcornella** [comment]
Correction: the PR is now #7250.

**Comment by g-uru** [comment]
manually pasted [#7250](https://github.com/robbyrussell/oh-my-zsh/pull/7250/commits/8de2644cd1567c667598913f0f7497d14b54fe35), works for me, thanks
