### ISSUE TITLE
when type 'd' command, maybe It's better to show number after path

### ISSUE THREAD

**Issue by Yanhao** [robbyrussell/oh-my-zsh#7257]
This is what i get when I type 'd' now
![image](https://user-images.githubusercontent.com/10085564/46644674-ed8faa00-cbb3-11e8-8651-45f6460d199b.png)

As you can see,  the leading parts of these paths are very similar.  So it's difficult to distinguish between them because the identify number is near the common parts. Thus I think maybe it's better to show number after paths. Or just provide an config item to modify this behavior.

**Comment by mcornella** [comment]
Unfortunately that's just the output of `dirs -v`, we can't change it because it would make the command more complex.
