### ISSUE TITLE
Plugin: kube-ps1: Do not auto-add to PROMPT

### ISSUE THREAD

**Issue by pmoranga** [robbyrussell/oh-my-zsh#7261]
The plugin kube-ps1 do not auto add itself to the PROMPT.

It requires that we add the new prompt format after sourcing the oh-zsh code: as follow:

      kube-ps1
    )
    
    source $ZSH/oh-my-zsh.sh
    PROMPT=$PROMPT'$(kube_ps1) '

Is this expected ? How can we inject the new argument into the PROMPT automatically and in the proper position ?

**Comment by ndeslandes** [comment]
i got the same issue

**Comment by Gabitchov** [comment]
Without this PR, the plugin is unusable. How can I help?

**Comment by pmoranga** [comment]
@Gabitchov not much to be done here, we need to wait the maintainer to approve https://github.com/robbyrussell/oh-my-zsh/pull/7269
