### ISSUE TITLE
zsh 5.6.2 tmux 2.7 gentoo theme 'cmdand cursh' prompt

### ISSUE THREAD

**Issue by zapme** [robbyrussell/oh-my-zsh#7262]
When reconnecting to a tmux session after a time away the prompt changes to:
`nyx ~ cmdand cursh#`
After a simple return the prompt is correct.
`nyx ~ #`

using plugins:
`plugins=(git svn vi-mode tmux)`

Any ideas what might cause this?

**Comment by fusion809** [comment]
I get this too on Arch, Fedora and Gentoo with:

```bash
plugins=(vi-mode git zsh-syntax-highlighting safe-paste zsh-completions)
```

and my own Zsh theme, [hfulldate](https://github.com/fusion809/zsh-theme/tree/master/hfulldate).

**Comment by e-ddie** [comment]
This is caused by && and {} on the following line:
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vi-mode/vi-mode.plugin.zsh#L9

**Comment by robbyrussell** [comment]
Anyone up for contributing a PR to resolve?

**Comment by mcornella** [comment]
If @e-ddie is right, a possible fix would be
```
TRAPWINCH() {
  if zle; then
    zle -R
    zle reset-prompt
  fi
}
```

Paste that in your zshrc file (after OMZ is sourced) and try again.

**Comment by mwiens91** [comment]
@mcornella that's not working for me. Now instead of getting  `~ cmdand cursh$` I'm getting `~ then$`.

**Comment by zapme** [comment]
@mcornella I have the same result, the prompt changes from ` ~ cmdand cursh$` to `~ then$`

**Comment by mwiens91** [comment]
Thanks @mcornella!
