### ISSUE TITLE
Composer autocomplete doesn't work

### ISSUE THREAD

**Issue by JRCrawford** [robbyrussell/oh-my-zsh#7271]
It appears that the autocomplete for composer doesn't work.  I've got the following in my zshrc file:
`
plugins=(git, composer, symfony2)
`
But as seen below, the autocomplete doesn't kick in.
![image](https://user-images.githubusercontent.com/16747994/46874901-36549680-ce32-11e8-8d1d-9830a778f71a.png)

**Comment by circa10a** [comment]
@JRCrawford What happens if you don't comma separate the plugins?
`plugins=(git composer symfony2)`

**Comment by mcornella** [comment]
Arrays in zsh are separated by spaces, not commas.
