### ISSUE TITLE
Tab autocomplete on ssh uses Hostname instead of Host

### ISSUE THREAD

**Issue by sandrodz** [robbyrussell/oh-my-zsh#7284]
Lets say I've:

```
Host fujin
User sandro
Port 999
Hostname fujin.domain.com
```
In `.ssh/config` file.

when I type `$ ssh fu` in terminal and hit tab, autocomplete makes it `$ ssh fujin.domain.com`

I'm pretty sure it did not work this way few month back, it would just autocomplete to `$ ssh fujin`.

**Comment by respencer** [comment]
Weird, for me it does exactly what you want. Do you perhaps have 2 instances of fujin.domain.com in your ~/.ssh/config?

I'm guessing it's using the other one, or your ~/.ssh/known_hosts, before it even gets to that entry in your ~/.ssh/config.

**Comment by mcornella** [comment]
This might happen when there is another entry in `/etc/hosts` that also begins with `fu`, can you check that?

**Comment by bryango** [comment]
This happens to me as well. There is no similar entry in `/etc/hosts`, but there is indeed an entry in `~/.ssh/known_hosts` (naturally).

**Comment by TiboC** [comment]
I experience the same issue here.
My /etc/hosts doesn't contain an entry with the autocompleted value.

**Comment by sandrodz** [comment]
@bryango it is indeed entry in `~/.ssh/known_hosts` interfering.

**Comment by mcornella** [comment]
This is a zsh completion issue, perhaps a [newer `_ssh_hosts` file](https://github.com/zsh-users/zsh/blame/master/Completion/Unix/Type/_ssh_hosts) would work. To try it, put it in a folder that's first in `$fpath`, `rm ~/.zcompdump*` and restart the shell.

If that doesn't work this is a bug and should be reported in the [zsh mailing list](http://zsh.org/mla).

**Comment by woitee** [comment]
This bugs still persists (zsh 5.7.1), and it is one thing that makes me leave zsh back to bash, where I had these things worked out - I can't really be spending time here. A shame, zsh.

**Comment by jaltek** [comment]
Hi,

`zstyle ':completion:*:ssh:*' hosts off` 

should help here.

**Comment by Aesku** [comment]
Thank you jaltek! It worked!
