### ISSUE TITLE
zsh: command not found: mysqladmin5

### ISSUE THREAD

**Issue by Fabriceli** [robbyrussell/oh-my-zsh#7290]
In my .zshrc `plugins=(
  git
  mysql-macports
  node
  npm
  python
  pip
  django
  docker
  zsh-autosuggestions
  extract
  z
  zsh-syntax-highlighting
)`

I enter `# mysqlstatus`,
i got `zsh: command not found: mysqladmin5`

**Comment by mcornella** [comment]
The `mysqlstatus` is an alias for `mysqladmin5 -u root -p ping`. Do you have `mysqladmin5` installed?

**Comment by Fabriceli** [comment]
how to install `mysqladmin5`? Can i run `brew install mysqladmin5` ?

**Comment by mcornella** [comment]
The plugin is supposed to be used with macports' mysql5.
