### ISSUE TITLE
Enable command-not-found by default

### ISSUE THREAD

**Issue by swapneeldatta** [robbyrussell/oh-my-zsh#7301]
Enable command-not-found by default. This can enable zsh to smartly suggest packages if not found.
Something like, rather than: 
`zsh: command not found: to`
Changes to 
```
Command 'plo' not found, did you mean:

  command 'plio' from deb gnustep-base-runtime
  command 'plot' from deb plotutils
  command 'palo' from deb palo
  command 'plog' from deb ppp
  command 'plm' from deb plm

Try: sudo apt install <deb name>
```

**Comment by mcornella** [comment]
We're going to keep it as an optional plugin. This way we don't mess with people's workflows and if anybody wants it they can just enable the plugin. Thanks
