### ISSUE TITLE
Some themes not working

### ISSUE THREAD

**Issue by martinchristov** [robbyrussell/oh-my-zsh#7302]
I'm changing the ZSH_THEME at /~.zshrc and I'm normally seeing the updated theme upon opening a new terminal tab.
However, there are a few themes which simply do not work and default to robbyrussell.
Those themes are:

- awesomepanda
- ys

Those happen to be precisely the themes which I want because they have keyword highlighting :-(

I'm running zsh 5.3 (x86_64-apple-darwin17.0)

**Comment by dimensi0n** [comment]
Doesn't work for me too, I'm investigating.

**Comment by dimensi0n** [comment]
Ok, I found, the `awesomepanda` theme is exactly like the `robbyrussell` default theme. 
The `ys` theme worked for me.
Did you type `source ~/.zshrc` ?

**Comment by mcornella** [comment]
Can't reproduce.

**Comment by mcornella** [comment]
Keyword highlighting is a plugin in itself, look up [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting).

**Comment by EricWiener** [comment]
I also have this issue with `ys`
