### ISSUE TITLE
 [per-directory-history] Multiple shells in the same folder do not share history

### ISSUE THREAD

**Issue by piegamesde** [robbyrussell/oh-my-zsh#7331]
# How to reproduce the problem

1. Open a shell in a folder, and type `echo hello`.
2. Open a second shell in that same folder and type `echo world`.
3. In both shells, use the arrow keys to view their respective history.

# What happens

Each shell does not contain the history of the other, albeit them being in the same folder. Sometimes, toggling to global and back makes the entries appear in the history, but a little in the wrong order.

# What should happen

All shells in the same folder have a shared history.

**Comment by mcornella** [comment]
Please submit this issue in the [upstream project](https://github.com/jimhester/per-directory-history).
