### ISSUE TITLE
history-substring-search plugin doesn't works

### ISSUE THREAD

**Issue by juan-moreno** [robbyrussell/oh-my-zsh#7347]
I try to add history-substring-search plugin in my linux installation but doesn't work. To avoid misconfiguration in my Linux, I install oh-my-zsh in a fresh Ubuntu Bionic installation with the same result 
history-substring-search plugin doesn't works.

#### New fresh Linux installation

    $ vagrant init ubuntu/bionic64
    $ vagrant up
    $ vagrant ssh

#### Install zsh

    $ sudo apt-get update && sudo apt-get install zsh

#### Install oh-my-zsh

    $ sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

Note: password "vagrant"

#### modify ~/.zshrc to add history-substring-search

plugins=(
  git
  history-substring-search
)

#### Load new config to enable history-substring-search plugin 

    $ source ~/.zshrc

And both, in this fresh installation and in my machine the plugin doesn't work

**Comment by michaelroevievictoria** [comment]
Same here any feedbacks ?

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/issues/7255#issuecomment-481190209.
