### ISSUE TITLE
ssh-agent plugin: identities not loaded

### ISSUE THREAD

**Issue by tomaswalander** [robbyrussell/oh-my-zsh#7352]
I have the following in my zsh config (other than the below I have very little config; only some aliases and theme settings that I don't think is relevant)
```
plugins=(git ssh-agent)

zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa
zstyle :omz:plugins:ssh-agent lifetime 4h

source $ZSH/oh-my-zsh.sh
```

It used to work fine, prompting me for the ssh key passphrase when necessary. But recently just stopped to working and I don't get any error messages add all. 

The ssh-agent seems to work fine. Because if I manually run ssh-add once it adds the identity and keeps it throughout the terminal session. 

Any ideas on how to fix this? Or just search further for the error...?

Thanks in advance!

**Comment by norilt** [comment]
got the issue myself. Solution for me was: `upgrade_oh_my_zsh`

**Comment by mcornella** [comment]
I'll mark this as closed then, since it works after the latest changes. Reopen if necessary.

**Comment by tomaswalander** [comment]
Worked like a charm! Thanks!
