### ISSUE TITLE
Deprecate transfer plugin

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#7371]
_Register at [Hacktoberfest](https://hacktoberfest.digitalocean.com/) before submitting a Pull Request_

----

Since [transfer.sh](https://transfer.sh) is shutting down on November 30th we should deprecate the plugin that uses it. The reasoning is that we should encourage users to use a different service, since their files will presumably be gone after it shuts down.

To do this, we should both:

- Add a deprecation warning in the README (explaining the reason)

- Add a deprecation warning in the `.plugin.zsh` file to run when the plugin is loaded. Extra points for printing the warning with a warning-like color, like yellow or orange.

After November 30th we should give a week or so before completely removing the plugin.

**Comment by steaward** [comment]
I can handle this for you

**Comment by steaward** [comment]
Or not... lol @a7r3

**Comment by mcornella** [comment]
Closing because it's been implemented. Thanks guys!
