### ISSUE TITLE
SSH Autocomplete on WSL is very slow

### ISSUE THREAD

**Issue by jwhipp** [robbyrussell/oh-my-zsh#7380]
On Windows 1803 with Ubuntu 18.04, SSH auto-completion is super slow.   I am guessing this has something to do with the slow I/O.    Is there a way we can optimize it?  I've seen various suggestions that have helped with bash_completion.    

I've also tested with bash_completion and it is way faster.  Rough estimate is 2X faster than oh-my-zsh's ssh completion.

**Comment by ilazycat** [comment]
Same problem here. Windows 1809 with ubuntu 18.04
In 16.04 everything works fine. SSH completion is slower than native linux but acceptable. When upgrade to  18.04 it becomes extremely slow. In the meanwhile ssh completion on bash is very fast.

**Comment by mcornella** [comment]
We don't bundle ssh completion, this is a zsh issue. See the [zsh mailing list](http://www.zsh.org/mla/).

**Comment by xqliang** [comment]
When ZSH completion completes hosts, it will call `_ssh_hosts` to parse `~/.ssh/config` multiply times (See  `/usr/share/zsh/functions/Completion/Unix/_ssh`). And unfortunately, `_ssh_hosts` on WSL is very slow when  `~/.ssh/config` file is large (for example, 1000 lines).

A workaround is to disable ZSH SSH hosts completion (just add the following code in ~/.zshrc):
```zsh
_ssh_hosts () {}
```

**Comment by mcandre** [comment]
:( But I specifically want ssh host completion. Disabling it is not an option.
