### ISSUE TITLE
Self-update fails if start folder is repository

### ISSUE THREAD

**Issue by michaeljohansen** [robbyrussell/oh-my-zsh#7381]
If a shell defaults to a git repository folder instead of the home folder, and the git repository has unstaged changes, then self-update fails.

```
[Oh My Zsh] Would you like to update? [Y/n]:
Updating Oh My Zsh
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
There was an error updating. Try again later?
```

I suggest storing current working directory, then moving to a safe location for doing the update, then moving back to user's preferred "start folder" after update.

**Comment by mcornella** [comment]
I'm not sure I follow. The upgrade process always cds into the ohmyzsh folder to do the pull rebase. The error you're seeing is that you have unstaged changes, but on the ohmyzsh folder.

**Comment by michaeljohansen** [comment]
I can confirm that this is not the case. There are no unstaged changes in `~/.oh-my-zsh`. However, I do `cd` around in my `.zshrc`. Maybe that's what causes the problem.

**Comment by mcornella** [comment]
As I said, the upgrade script cds into the ohmyzsh folder right before the pull rebase: https://github.com/robbyrussell/oh-my-zsh/blob/05b617066ba5a37ef0c533385efd6e232a387b8f/tools/upgrade.sh#L24-L25

I don't know how cds in your zshrc file could affect the process... Can you tell me what ohmyzsh commit you have checked out?

**Comment by michaeljohansen** [comment]
Hmm. Hope this isn't just some error I've caused myself. I'm at commit `16bfd6f`(git log below).

![image](https://user-images.githubusercontent.com/582580/48038119-87288800-e16f-11e8-8696-7a50ce230e13.png)

**Comment by mcornella** [comment]
What does `cd $ZSH; git status -s` show?

**Comment by michaeljohansen** [comment]
`cd $ZSH; git status -s`:
![image](https://user-images.githubusercontent.com/582580/48099167-045f0600-e21f-11e8-9bb8-94cf41479d03.png)
