### ISSUE TITLE
The prompt is missing in Midnight Commander

### ISSUE THREAD

**Issue by jabbalaci** [robbyrussell/oh-my-zsh#7383]
I have a problem with oh-my-zsh + Midnight Commander (mc). In mc, at the bottom there is a mini shell, just one line. When using oh-my-zsh, there's no prompt in this shell. I tried to set PS1 and PROMPT too, but that didn't help. When I deactivated oh-my-zsh (used an empty .zshrc file) and changed PROMPT (with `export PROMPT=">>> "` for instance), it was visible in mc. So it must be an oh-my-zsh setting that conflicts with mc.

**Comment by jabbalaci** [comment]
I think it's a Midnight Commander issue. I tried some custom settings without oh-my-zsh and I had the same problem. I have the impression that mc doesn't work well with zsh.

**Comment by quicktrick** [comment]
> I think it's a Midnight Commander issue. I tried some custom settings without oh-my-zsh and I had the same problem. I have the impression that mc doesn't work well with zsh.

That's not true. Try not using any theme at all (comment out `#ZSH_THEME="robbyrussell"` in .zshrc) and add to the end of .zshrc something like:
```
export PS1="%{$fg_bold[green]%}➜ %{$fg[cyan]%}%~ # %{$reset_color%}"
```
It works fine with MC, except MC removes any colors from the prompt (see [here](https://midnight-commander.org/ticket/2027#comment:21)). Though in a subshell (ctrl+o) the colors appear again after you just press Enter.

**Comment by maver1ck** [comment]
@jabbalaci 
I have the same problem 2 years later. 
Any solution for that ?

**Comment by cadmi** [comment]
> I have the same problem 2 years later.
> Any solution for that ?

+1, the same

**Comment by quicktrick** [comment]
There is no problem with MC, you just don't read carefully the messages in this thread.

Add your own theme to `ohmyzsh`.  Add some file like `~/.oh-my-zsh/custom/themes/myawesome.zsh-theme` with the contents like:
```
PROMPT="%{$fg_bold[green]%}➜ %{$fg[cyan]%}%~ # %{$reset_color%}"
```
and change the theme in `~/.zshrc` to:
```
ZSH_THEME="myawesome"
```
Everything works just fine!

**Comment by cadmi** [comment]
it's great that it works in its own theme, but the point is that does not work command prompt in mc subshell with agnoster theme, for example :)

**Comment by quicktrick** [comment]
Correct agnoster theme as you like an it will work with it too.

**Comment by mcornella** [comment]
After a few tests, it seems that Midnight Commander doesn't support calling functions inside the `$PROMPT` variable, and using `precmd` functions doesn't work either, so I suggest you do as @quicktrick says and modify the themes to remove any `$()` calls in `$PROMPT`.

**Comment by quicktrick** [comment]
> After a few tests, it seems that Midnight Commander doesn't support calling functions inside the $PROMPT variable, and using precmd functions doesn't work either

As I already wrote above, the explanation is [here](https://midnight-commander.org/ticket/2027#comment:21):

>> Is there a way to get the prompt colors show up also in MC?
> Unfortunately no. It is not supported, аll control sequences in the prompt are ignored.

**Comment by cadmi** [comment]
@quicktrick, let the command line prompt be black and white, but show the current directory, repository branch, etc. nope, instead, with default settings, the command prompt is completely empty. and @mcornella fully explained why.

So I had to remove all the useful stuff from the ohmyzsh and bring the command line prompt inside the mc to the standard view, adding a few lines to the end of the ~/.zshrc

```zsh
if ps $PPID | grep mc; then
    # this removes git_prompt_string cool stuff but I have no other solution for now
    PROMPT='%n@%m %1~ %# '
fi
```

**Comment by TimaGribanov** [comment]
So, I've enhanced what @cadmi suggested to make it look more the way it is in the `agonster` theme.
```
if ps $PPID | grep mc; then
    PROMPT="%n@%m %d > "
fi
```
So, it ends up looking something like this:
![image](https://user-images.githubusercontent.com/48593815/206660741-c734f322-9185-41ec-9135-d5285055e962.png)

Moreover, you can create your own PROMPTs [here](https://zsh-prompt-generator.site/).

**Comment by cognivore** [comment]
For starship users!

I added an alias `mc` to  be `bash -c "SHELL=bash mc" or, on Nix:

```nix
shellAliases = {
  mc = ''
       bash -c "SHELL=/home/sweater/.nix-profile/bin/bash mc"
  '';
};
```

and disabled support of  starship for bash.

Workaround, but it punches through starship PROMPT override!
