### ISSUE TITLE
git plugin latency

### ISSUE THREAD

**Issue by Hyuntae-91** [robbyrussell/oh-my-zsh#7384]
Hello.

Recently, I cloned Unreal Engine to review the code.
When I change to Unreal Engine directory, there are 1-4 seconds before terminal "responds".

I tried both of my Mac and laptop. And both of them have same issue.

User software 1
 - Mac OS Sierra
 - Zsh 5.6.2
 - Oh-my-zsh latest version

User software 2
 - Ubuntu 18.04
 - Zsh 5.6.2
 - Oh-my-zsh latest version

I used debug mode using this command "zsh -xv"
And I found the moment what the responds happen.

    +prompt_git:13> repo_path=+prompt_git:13> git rev-parse --git-dir
    +prompt_git:13> repo_path=.git
    +prompt_git:14> dirty=+prompt_git:14> parse_git_dirty
    +parse_git_dirty:1> local STATUS=''
    +parse_git_dirty:2> local -a FLAGS
    +parse_git_dirty:3> FLAGS=( --porcelain )
    +parse_git_dirty:4> [[+parse_git_dirty:4> git config --get oh-my-zsh.hide-dirty
    +parse_git_dirty:4> [[ '' != 1 ]]
    +parse_git_dirty:5> [[ 1 -gt 0 ]]
    +parse_git_dirty:6> FLAGS+='--ignore-submodules=dirty'
    +parse_git_dirty:8> [[ '' == true ]]
    +parse_git_dirty:11> STATUS=+parse_git_dirty:11> git status --porcelain '--ignore-submodules=dirty'
    +parse_git_dirty:11> STATUS=+parse_git_dirty:11> tail -n1
         <On this moment, stopped 1-4 seconds delay>

I think so many commits(Unreal Engine has 63,000 commits) make latency to open directory.
When I deleted the ".git" folder, the issue was gone.
Does we improve this latency?

**Comment by Hyuntae-91** [comment]
I reviewed the issue, and the git plugin has issue. 
There are so many commits(almost 63,000 commits) and I think this is why. 
Does we improve this latency?

**Comment by Hyuntae-91** [comment]
I reviewed the issue, and the I found git plugin Make latency.
There are so many commits(almost 63,000 commits) and I think this is why.
Does we improve this latency?

**Comment by mcornella** [comment]
As you found out, the culprit of this latency is reading the state of the git repository you're in. In big repositories there is the ability to disable this check by running `git config oh-my-zsh.hide-status 1`.
