### ISSUE TITLE
source error

### ISSUE THREAD

**Issue by XxYyKk** [robbyrussell/oh-my-zsh#7387]
ubuntu 18.*
 first install zsh, 'source .zshrc' Meeting this problem

source .zshrc 
autoload：未找到命令
bash: /home/***/.oh-my-zsh/oh-my-zsh.sh: 行 34: 未预期的符号 `(' 附近有语法错误
bash: /home/***/.oh-my-zsh/oh-my-zsh.sh: 行 34: `for config_file ($ZSH/lib/*.zsh); do'

**Comment by 527147280** [comment]
- 下载zip压缩包， 然后解压 `unzip oh-my-zsh-master.zip `

- 复制到家目录 `mv oh-my-zsh-master  ~/.oh-my-zsh`

- 复制配置文件 `cp templates/zshrc.zsh-template ~/.zshrc`

- 修改默认终端 `chsh -s /bin/zsh `

- 生效配置 `source  ~/.zshrc `

然后就报错了， 解决方法， 终端输入 `zsh`， 然后退出， 重新打开终端就显示正常了
