### ISSUE TITLE
prepend conda to PATH on macOS High Sierra version 10.13.6 

### ISSUE THREAD

**Issue by crazyhottommy** [robbyrussell/oh-my-zsh#7389]
Hi there,
If I prepend 
```
export PATH="/anaconda3/bin":$PATH
```
my zsh terminal will not show the folder/file colors.

If I append it to my PATH, everything works fine.
Any hint why?

Thanks,
Tommy

**Comment by mcornella** [comment]
When you say folder/file colors, you mean when doing `ls`? If so, what does `which -a ls` print when conda is first in the `$PATH`?

Closing this since it is not OMZ related.
