### ISSUE TITLE
plugin dev question - check for local files 

### ISSUE THREAD

**Issue by brettswift** [robbyrussell/oh-my-zsh#7391]
My iterm2 is loading really slow.  I had some pyenv init commands that add 1 second to my load time.  Without those (not via the pyenv plugin) my shell loads quick.

with out pyenv plugin or pyenv init hard coded
```
machine-d 福 ~
10022 ◯ : /usr/bin/time zsh -i -c exit
        0.38 real         0.17 user         0.12 sys
```
with the pyenv -init scripts in my .zshrc, it takes about 1.5 seconds.

with the pyenv plugin, it's even worse! 
```
machine-id 福 ~
10018 ◯ : /usr/bin/time zsh -i -c exit
        4.99 real         1.54 user         0.95 sys
```

So I want to write my own pyenv plugin, and just make it very quick.  

1) check for .python-version file
2) if that exists, run the init scripts

I've looked at a few plugins but not sure how in a plugin to check to see if a specific file exists in the current working directory.   Is there a plugin I could look at to figure this out?

**Comment by mcornella** [comment]
> * check for .python-version file
> * if that exists, run the init scripts

You want to check if the `.python-version` exists in current working directory **on zsh start**? If so, you just use a conditional:
```
if [[ -f .python-version ]]; then
```

See [zsh conditional expressions](http://zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html).
