### ISSUE TITLE
after update to macOs Mojave zsh broken

### ISSUE THREAD

**Issue by fabiobarboza7** [robbyrussell/oh-my-zsh#7395]
Some shortcuts isnt working more, like stt (sublime)... also special words like git, rails, ruby are not colored.

**Comment by thearabbit** [comment]
the same for me +1

**Comment by mcornella** [comment]
What does `which subl` output? What's your zshrc file?

**Comment by thearabbit** [comment]
My output `subl not found`

**Comment by thearabbit** [comment]
oh sorry, I base on `VS Code`

**Comment by mcornella** [comment]
Can you make a list of everything that's broken and what are the contents of your zshrc file?
