### ISSUE TITLE
Ignore blocked DNS hostnames in /etc/hosts in autocompletion 

### ISSUE THREAD

**Issue by febs** [robbyrussell/oh-my-zsh#7397]
I use a hostname-based antispam: 
https://github.com/StevenBlack/hosts

in oh-my-zsh though, when autocompleting the hostname, the whole /etc/hosts file is parsed and used as potential candidates.
So that I find myself trying to ssh'ing into:
` ssh slutmachine.net`
Which I don't want. :sweat_smile: 
That also slows down completion.
Would it be possible to configure the ssh completion so to ignore /etc/hosts entirely, or even better, to ignore the blocked hosts (i.e, those translated to 0.0.0.0)?

**Comment by msafadieh** [comment]
Is the solution in this [thread](https://unix.stackexchange.com/questions/375814/zsh-completion-rules-for-ssh) useful in your situation?

**Comment by febs** [comment]
I'm afraid not, since that is asking for a different thing (actually, getting _more_ names from /etc/hosts resolved) but maybe I'll find inspiration there. Thanks.

**Comment by mcornella** [comment]
According to the latest completion: https://github.com/zsh-users/zsh/blob/6f35d6c0d0eeb80c0145e5226285a8a45ffb5f25/Completion/Unix/Type/_hosts#L7-L8

You could set a variable `$_cache_hosts` or a `zstyle ':completion:*:hosts hosts` to bypass the [read of `/etc/hosts`](https://github.com/zsh-users/zsh/blob/6f35d6c0d0eeb80c0145e5226285a8a45ffb5f25/Completion/Unix/Type/_hosts#L24) or [call to `getent hosts`](https://github.com/zsh-users/zsh/blob/6f35d6c0d0eeb80c0145e5226285a8a45ffb5f25/Completion/Unix/Type/_hosts#L22).

Your best option though is to ask [the zsh mailing list](http://zsh.org/mla) for a fix that ignores blocked hosts.
