### ISSUE TITLE
Files of .oh-my-zsh, .zshrc are not created

### ISSUE THREAD

**Issue by xlsmile** [robbyrussell/oh-my-zsh#7399]
Just installed zsh 5.6.2. (Mojave 10.14.1). However, files like .oh-my-zsh, .zshrc are not created neither in root directory, nor in the /bin. The only file installed is zsh in the /bin. Cannot figure out how to install themes after 3 hours of fiddling with diff. solutions found in the web. Nothing helps.

What am I doing wrong?

**Comment by dimensi0n** [comment]
Try with `locate` to find this files.

**Comment by xlsmile** [comment]
> Try with `locate` to find this files.

Nope, doesn't find .oh-my-zsh.

**Comment by LiuYanpin** [comment]
try to use `vim ~/.zshrc`

**Comment by xlsmile** [comment]
> try to use `vim ~/.zshrc`

Thank you, Liu. I've done a couple of reinstalls and finally got it working.
