### ISSUE TITLE
Fabric completion broken after latest update

### ISSUE THREAD

**Issue by amrishparmar** [robbyrussell/oh-my-zsh#7405]
Pressing tab to autocomplete on a `fab` command gives the following output instead of correctly autocompleting it.

```
(base) ➜  folder git:(master)  fab   
(eval):1: _fab: function definition file not found
(eval):1: _fab: function definition file not found
(eval):1: _fab: function definition file not found
```

It seems to have been caused by the following commit https://github.com/robbyrussell/oh-my-zsh/commit/fa9d93008b2c9d42f26320c92752f4f019c47404

Renaming the _fabric file back to _fab as it was originally resolves the issue.

**Comment by shawn-bluce** [comment]
yes i think so. but when i reinstall the oh-my-zsh, it work.
