### ISSUE TITLE
when install oh-my-zsh oh aliyun ecs  debian other user can not access file at root user home 

### ISSUE THREAD

**Issue by guider** [robbyrussell/oh-my-zsh#7408]
env：debian9.2

testfilepath  : :+1: /root/www/test.txt
-rw-r--r-- 1 root root    5 Nov 14 15:12 test.txt

root@iZuf64664y88ugan2c0iebZ:~/www# groups test
test : test

but test can not access test.txt after install oh-my-zsh 
result:

![image](https://user-images.githubusercontent.com/15050634/48466832-ee0a0900-e821-11e8-92a2-d41b01a370b0.png)

**Comment by guider** [comment]
full image : 
![image](https://user-images.githubusercontent.com/15050634/48466864-02e69c80-e822-11e8-875b-edfeb1bc69c2.png)

**Comment by guider** [comment]
add test user in root group

**Comment by guider** [comment]
![image](https://user-images.githubusercontent.com/15050634/48471791-b5712c00-e82f-11e8-96ed-c14c322f5882.png)
 
I found that absoulte  path access fail relative path access success

**Comment by mcornella** [comment]
You need to have execution permission on each of the parent folders to view a file inside. `/root` normally has no `x` permissions on group or others. That explains why a relative path works and an absolute path doesn't.

This is not OMZ related though.

**Comment by mcornella** [comment]
I should add that you **shouldn't** add execution permission on `/root` because that's a security vulnerability. Find another way to do what you want.

**Comment by guider** [comment]
thank you.
