### ISSUE TITLE
Unable to type non-ASCII chars on Mac <ffffffff>

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [robbyrussell/oh-my-zsh#7412]
When I try to type or paste some text that contains non-ASCII chars, `<ffffffff>` is shown instead of the proper char.

For example, when I try to type `á`, that happens:

<img width="682" alt="screen shot 2018-11-16 at 12 02 03 pm" src="https://user-images.githubusercontent.com/7753096/48629272-f3895f80-e997-11e8-8a59-d4ee68401e77.png">

While I expect that to happen:

<img width="682" alt="screen shot 2018-11-16 at 12 02 05 pm" src="https://user-images.githubusercontent.com/7753096/48629273-f421f600-e997-11e8-975a-e4a13be0f709.png">

**Comment by t0rr3sp3dr0** [comment]
I actually sove that by disabling **Escape non-ASCII Input with Control-V** in *Advanced* tab of *Profiles* section on *Preferences*.

**Comment by smstotti** [comment]
danke

**Comment by dmitrybukhonov** [comment]
Or as solution
Profile --> Terminal --> Terminal Emulation : Caracter encoding : Unicode (UTF - 8)

**Comment by davideluque** [comment]
Terminal -> Settings -> Profiles -> Keyboard

Disable "Use Option as Meta key" 

Fixed it for me. I suspect is related to using Termius.
