### ISSUE TITLE
Error installing oh my zsh with .gitconfig on current directory

### ISSUE THREAD

**Issue by marioanloru** [robbyrussell/oh-my-zsh#7413]
I had upstream and origin defined on .gitconfig at ~ because of an old project, and oh my zsh installation script (from `sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh`)")
`install.sh` cloned the repository defined on my upstream instead of https://github.com/robbyrussell/oh-my-zsh.git, so when it tries to copy /.oh-my-zsh/templates/zshrc.zsh-template fails as it does not exist.

Deleting .giticonfig solves the problem, but this issue should be contemplated

**Comment by respencer** [comment]
I contemplated it -- I have no idea why you would do that. You should be adding settings like that to each individual project, not your global gitconfig.

Can you please close this issue? That's an issue with your git configuration and not specific to oh-my-zsh.

**Comment by mcornella** [comment]
Yeah there is no way we'll overcomplicate the install script looking for this exact setting when there is no reason to have it in the first place.
