### ISSUE TITLE
How to get 'git help log' colored as 'man ls'?

### ISSUE THREAD

**Issue by fniessen** [robbyrussell/oh-my-zsh#7415]
This is more a question for which I did not find the answer, and I'm sure I could get a yes-or-no type of answer here.

I do use colored-man-pages pluging, but this does not impact 'git help log' for example. Is it possible to do so, or not?

Thanks for this amazing piece of art!

**Comment by mcornella** [comment]
After #7173 is merged you could use `colored git help log`. So +1 that if you want it.

Another option would be to export the LESS_TERMCAP_* variables in that function, and that would automatically color any command with man-like output, including `git help`:
```
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;32m'
```
