### ISSUE TITLE
Git no indication when new untracked files are being added

### ISSUE THREAD

**Issue by VinayakBagaria** [robbyrussell/oh-my-zsh#7419]
While using git with zsh, there is no indication to show when new untracked files are being added, although there is indication when tracked files are changed.
Without seeing the `git status`, developer can't know if any untracked files exist.

**Comment by mcornella** [comment]
The robbyrussell or the agnoster theme show when there are untracked files, for example. Whatever theme you're using must not support that, but it can be added.
