### ISSUE TITLE
Garbled command line in IntelliJ + Tmux

### ISSUE THREAD

**Issue by katafractari** [robbyrussell/oh-my-zsh#7420]
I'm experiencing a strange problem with most of oh-my-zsh themes in combination with tmux and Intellij terminal. The current command is one line above the prompt until the prompt is not at the bottom of the terminal window. Then the current command jumps to the same line as the prompt.

Tried solution from https://github.com/robbyrussell/oh-my-zsh/issues/4775 but didn't work.

This is happening on latest Arch Linux and latest macOS.

![image](https://user-images.githubusercontent.com/1299228/48742826-e4890280-ec60-11e8-8588-a3de533d1f7a.png)

**Comment by katafractari** [comment]
To answer my own question, I had to set the terminal font in IntelliJ to something that supports Powerline characters. (in my case inconsolata-powerline)

**Comment by stephanoparaskeva** [comment]
Having same issue, tried many different powerline enabled fonts with no success
<img width="898" alt="Screenshot 2020-04-04 at 13 50 33" src="https://user-images.githubusercontent.com/40718272/78451090-480ba880-767b-11ea-929b-e705bdb228b8.png">

**Comment by katafractari** [comment]
@stephanoparaskeva Does this happen to you with all oh-my-zsh themes?

**Comment by stephanoparaskeva** [comment]
@katafractari  it occurs with an empty .zshrc so issue is probably the intellij terminal itself

**Comment by AlessandroVol23** [comment]
> To answer my own question, I had to set the terminal font in IntelliJ to something that supports Powerline characters. (in my case inconsolata-powerline)

How did you install powerline fonts inside of IntelliJ? I have the same issue but I don't see the installed powerline fonts. Ubuntu 18.04

**Comment by eliecharra** [comment]
@katafractari As a workaround I've wrapped tmux directives in a `if` directive in my `.zshrc` to avoid launching tmux when zsh spawn in IntelliJ terminal. 

```bash
if [ "$TERMINAL_EMULATOR" != "JetBrains-JediTerm" ]; then 
    ZSH_TMUX_AUTOSTART=true 
    ZSH_TMUX_AUTOCONNECT=false 
fi
```

It disable tmux only inside your IDE, and seems to be working for me using my custom oh my zsh theme

![image](https://user-images.githubusercontent.com/6154987/96118516-e65ead80-0eeb-11eb-8aca-e2b57fe7a56f.png)
