### ISSUE TITLE
First characters of prompt are repeated after tab autocompletion (in a docker container)

### ISSUE THREAD

**Issue by amjltc295** [robbyrussell/oh-my-zsh#7426]
Similar to  #4632  #3505 #3368  #4341 #5157 (...). Should we document this somewhere?

I could reproduce the problem inside a Docker container with almost all themes.  It could not be solved by setting proper `locale` (suggested in #5157). It does not work if I add `%{...%}` as well (from #3932 and https://unix.stackexchange.com/questions/90772/first-characters-of-the-command-repeated-in-the-display-when-completing ).
Instead, I fixed it by replacing all special characters with normal ones.
Take `robbyrussell.zsh-theme` for example, replace the `➜` with `>` and `✗` with `X`:
```
 local ret_status="%(?:%{$fg_bold[green]%}> :%{$fg_bold[red]%}> )"
 PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
 
 ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
 ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
 ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}X"
 ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```
and the annoying problem is solved.

Just a workaround but may help if for people who could not solve it by `export LC_CTYPE=en_US.UTF-8`. I would be glad to know if there is any other solution without replacing these characters inside a Docker container.

**Comment by jason-oliveira** [comment]
There is a good chance you have an **export LC_ALL=C** sitting somewhere in your environment. put **export LC_ALL="en_US.UTF-8"** at the end of your .zshrc and see if it fixes that.

**Comment by sago2k8** [comment]
Thanks @jason-oliveira you where right, after locale update it's working perfectly

**Comment by mcornella** [comment]
Better yet, use your preferred locale ending in `UTF-8` from the list of `locale -a`. In docker containers most probably that will be `C.UTF-8` since there aren't any other locales.

**Comment by mcornella** [comment]
> Similar to #4632 #3505 #3368 #4341 #5157 (...). Should we document this somewhere?

This could be a good moment to add a FAQ section in the wiki :wink:

**Comment by turkeyphant** [comment]
> There is a good chance you have an **export LC_ALL=C** sitting somewhere in your environment. put **export LC_ALL="en_US.UTF-8"** at the end of your .zshrc and see if it fixes that.

Still getting this even after fixing `LC_ALL` and `LC_COLLATE`

Interestingly, regardless of whether I enclose it in double quotes in `.zshrc`,"en_US.UTF-8" is always outside of quotes in `locale`

![image](https://user-images.githubusercontent.com/8129583/80353842-de438080-886d-11ea-8e34-5a693425cfe1.png)

![image](https://user-images.githubusercontent.com/8129583/80353953-fe733f80-886d-11ea-9683-3f818e8e63c0.png)

**Comment by mcornella** [comment]
Does this locale exist (run `locale -a` for available ones). Also, which theme are you using, perhaps it's bleeding some UTF-8 characters and guessing a wrong char width for them.

**Comment by turkeyphant** [comment]
> Does this locale exist? (run `locale -a` for available ones). Also, which theme are you using, perhaps it's bleeding some UTF-8 characters and guessing a wrong char width for them.

Hmm

```# locale -a                                                                                
C
POSIX
en_US.utf8```

**Comment by mcornella** [comment]
What's the minimal zshrc file with which you can reproduce this bug, and also, are you using a particular Docker image that I can use to reproduce this?

**Comment by NishanthSpShetty** [comment]
having this issue with ubuntu docker image after installing ohmyzsh, setting locale dint help either.
`docker exec -it run ubuntu` install zsh, ohmyzsh. Should be able to reproduce the issue.

**Comment by mcornella** [comment]
I could reproduce it, but it is solved by setting locale in my case. Here I used `export LANG=C.UTF-8`:
![image](https://user-images.githubusercontent.com/1441704/87563657-c71f6c80-c6bf-11ea-8564-2de8a2279029.png)
![image](https://user-images.githubusercontent.com/1441704/87563773-e918ef00-c6bf-11ea-9a67-a65722257d9b.png)

**Comment by NishanthSpShetty** [comment]
@mcornella thank you 🙏 , that worked.
