### ISSUE TITLE
Piping to non-existant command fails silently

### ISSUE THREAD

**Issue by ukch** [robbyrussell/oh-my-zsh#7428]
When using `oh-my-zsh` (actual):
```
$ echo hello | notrealcommand
$
```

When using `zsh --norcs` (expected):
```
$ echo hello | notrealcommand
zsh: command not found: notrealcommand
$
```

When using bash (for comparison):
```
$ echo hello | notrealcommand
notrealcommand: command not found
```
I am using `oh-my-zsh` with a number of aliases defined. I am also using the `command-not-found` library.

Please let me know if you need to see some of my config in order to debug this.

**Comment by ukch** [comment]
Here's an [omz-debug.log](https://github.com/robbyrussell/oh-my-zsh/files/2605089/omz-debug.log) of the issue, in case that helps.

**Comment by mcornella** [comment]
Try without the command-not-found plugin, I recall there was a bug when it couldn't find an appropriate package where it didn't show any error.

**Comment by ukch** [comment]
> Try without the command-not-found plugin, I recall there was a bug when it couldn't find an appropriate package where it didn't show any error.

I have removed `command-not-found` from my `.zshrc` but am still encountering the same issue.

**Comment by mcornella** [comment]
You have a custom `command_not_found_handler` function in your zshrc file:
```zsh
command_not_found_handler() {
  if [[ $1 =~ ^ar+$ ]]; then
    ar ${@:2}
    return $?
  else
    return 127
  fi
}
```

~~There's probably something wrong with it but I can't see what.~~

From the [documentation](http://zsh.sourceforge.net/Doc/Release/Command-Execution.html):
> If the function wishes to mimic the behaviour of the shell when the command is not found, **it should print the message ‘command not found: cmd’ to standard error** and return status 127.

It's not enough to just return 127, the function is also in charge of printing the error.

**Comment by ukch** [comment]
Thanks @mcornella. I'm not sure how that function got in there (I definitely didn't define it) but I can confirm that removing it solves the problem.
