### ISSUE TITLE
Add stackoverflow

### ISSUE THREAD

**Issue by iamantu93** [robbyrussell/oh-my-zsh#7430]
Please add an option to search stackoverflow

**Comment by rkmax** [comment]
there's a plugin called "web-search" look at [$ ZSH / plugins / web-search / web-search.plugin.zsh] (https://github.com/robbyrussell/oh-my-zsh/blob/ master / plugins / web-search / web-search.plugin.zsh)

you only need to add the entry `stackoverflow 'https://stackoverflow.com/search?q=" `to urls and the alias that you want at the end of the file` aka help_so = "web_search stackoverflow" `and last just add the plugin` web-search` to your `$ HOME / .zshrc` and voilà! you can now type `help_so oh my zsh plugin` and you'll have the results on your browser

I invite you to create a fork add this feature and create a PR in that way you can help the community :)

cheers!

**Comment by mcornella** [comment]
The `frontend-search` plugin provides that: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/frontend-search/README.md
