### ISSUE TITLE
Using vi-mode plugin conflicts with sudo plugin's EscEsc sequence

### ISSUE THREAD

**Issue by pentago** [robbyrussell/oh-my-zsh#7431]
Any chance any of these plugins can be modified so they do not conflict with each other's functionality? 
For instance, configurable binding for **sudo** plugin's **Esc Esc** sequence would be a decent solution I guess.

**Comment by abuchanan920** [comment]
Same

**Comment by mcornella** [comment]
The fix for now is to load `vi-mode` before the `sudo` plugin.

**Comment by SomeDer** [comment]
@mcornella maybe this should be mentioned in the README

**Comment by pentago** [comment]
@mcornella this doesn't work on my end, just tried it. Anything changed in the meantime?
