### ISSUE TITLE
PhPStorm terminal UI Bug

### ISSUE THREAD

**Issue by menjilx** [robbyrussell/oh-my-zsh#7434]
hi, anyone encountered the same issue for PHPStorm Terminal UI.
Check the screenshot below, if you can see the "check" icon were not shown properly and the arrow as well.

PHPStorm screenshot
![image](https://user-images.githubusercontent.com/14908836/48963406-7039c080-efcc-11e8-9cd8-a5aa90c63836.png)

iTerm screenshot
![image](https://user-images.githubusercontent.com/14908836/48963410-82b3fa00-efcc-11e8-93d5-9e1f08bc6e94.png)

Thanks!

**Comment by sptndc** [comment]
I think this is bug on PHPStorm not on this repo.
