### ISSUE TITLE
Linuxbrew ZSH

### ISSUE THREAD

**Issue by Mario253** [robbyrussell/oh-my-zsh#7436]
I installed zsh using linuxbrew, and when I tried to install oh-my-zsh, it just said "Zsh is not installed! Please install Zsh first!" and quit. I installed an older version of zsh and still ran the linuxbrew version, and it ran ok.

**Comment by Vertana** [comment]
@Mario253 I know I'm catching this super late, but can you confirm if this is still an issue? In the install script it just looks like it tries to find zsh via $PATH: https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/install.sh#L27

If this is still happening maybe Homebrew isn't setting the binary in $PATH correctly?

**Comment by Mario253** [comment]
It seems like it is resolved. I recently had to reinstall the container I was working in, and I didn’t hit any problems.

**Comment by Vertana** [comment]
Sounds good! Glad it worked out.
