### ISSUE TITLE
Dotenv plugin breaks my prompt

### ISSUE THREAD

**Issue by batisteo** [robbyrussell/oh-my-zsh#7444]
Using dotenv plugin and doing `cd .` breaks the prompt.

Removing the following lines seems to fix the problem. But I have no idea what’s the use of it.

```bash
autoload -U add-zsh-hook
add-zsh-hook chpwd source_env
```

Maybe @mcornella have an idea?

**Comment by mcornella** [comment]
Do you have a `.env` file in your current working directory? If so, what are the contents?

**Comment by dalmirog** [comment]
> Do you have a `.env` file in your current working directory? If so, what are the contents?

I had an empty `.env` file and that seemsed to be causing the issue. I was going crazy with this. Thanks a lot.

**Comment by mcornella** [comment]
Can you let me know which theme you are using?
