### ISSUE TITLE
update error in KDE NEON 

### ISSUE THREAD

**Issue by acharjyanisankh** [robbyrussell/oh-my-zsh#7449]
![screenshot_20181208_093751](https://user-images.githubusercontent.com/36255122/49681751-fd9d0a80-facc-11e8-9d76-23a2f33ca9a2.png)
oh-my-zsh is unable to update automatically in KDE NEON distribution . it can only be updated by changing directory to `~/.oh-my-zsh` than executing `git pull`

can you look into this ...

**Comment by respencer** [comment]
Where you in another git repository when you did that update or do you have another git repository specified in your ~/.gitconfig ?

**Comment by mcornella** [comment]
You have unstaged changes made to the OMZ folder. Run `git status` to see the changes and either discard them or commit them.
