### ISSUE TITLE
when press ctrl+c or run any command which is not in mac, promt breaks

### ISSUE THREAD

**Issue by miklasz** [robbyrussell/oh-my-zsh#7450]
Hi,

i have prompt:

17:49 bartron @ mik ツ ➜  ~

when run normal command it works fine

however when i run command which does not exisit in mac, or if i press ctrl+c it changes prompt to:

17:49  ~

when i use command again one exist in system it comes back to my original prompt, for example:

17:53  ~ time
shell  0.27s user 0.29s system 0% cpu 23:24:35.59 total
children  1.49s user 2.87s system 0% cpu 23:24:35.59 total
17:53 bartron @ mik ツ ➜  ~

any idea how to fix this ? :)

**Comment by mcornella** [comment]
Duplicate of #6183
