### ISSUE TITLE
alias folder navigation

### ISSUE THREAD

**Issue by mett96** [robbyrussell/oh-my-zsh#7453]
There is a view to allow zsh to view folders that are created as alias when I use for example CD or any other command?

**Comment by mett96** [comment]
OK. I make an example in order to be more clear. 

On my desktop I have different directory that are alias (linked folder) as my university's folder
![image](https://user-images.githubusercontent.com/16799929/52220860-2ad52180-28a0-11e9-9f8b-f8e08d165205.png)

When I perform the command `ls` these type of folder are showed.
![image](https://user-images.githubusercontent.com/16799929/52220951-5b1cc000-28a0-11e9-8565-75ba22c208fe.png)

Instead when I try to go in this folder with `cd` it doesn't appear. 

![image](https://user-images.githubusercontent.com/16799929/52220977-67a11880-28a0-11e9-8628-41dc5d8db710.png)

But in order to go to this folder, I have to insert the complete path.

**Comment by respencer** [comment]
Unfortunately I no longer have a working Mac, so I can't test that on my side.

I'm curious though, that Universita alias is showing up as a file (white). That makes me think it is indeed a text file (or binary) that opens up a connection to your [remote?] University folder.

cd only knows how to work with local directories and symlinks. You need to use bridging software to mount remote directories locally, so you can cd into them. And that's not something I'm in a position to advise you on.

**Comment by mett96** [comment]
Ok I resolve momently the problem, because if I create the symlinks programmatically with `ln` it works well.
But if I use the Finder, as in the photo, it doesn't work

<img width="350" alt="image" src="https://user-images.githubusercontent.com/16799929/52336663-c502aa00-2a05-11e9-8dc9-2fc08eb619e0.png">

**Comment by respencer** [comment]
I'm glad you found a work around.

Since this doesn't appear to be an oh-my-zsh issue, can you please close this issue?

**Comment by mcornella** [comment]
There's [this option](https://superuser.com/a/254005) but it looks to be too much of a hassle when there's the option of just creating a symbolic link.
