### ISSUE TITLE
parse error near `\n'

### ISSUE THREAD

**Issue by labike** [robbyrussell/oh-my-zsh#7462]
i find long time, don't know the error is where.
<img width="440" alt="2018-12-06 4 30 09" src="https://user-images.githubusercontent.com/15871933/49571481-615ff000-f974-11e8-8f67-99051b289b08.png">
<img width="559" alt="2018-12-06 4 33 57" src="https://user-images.githubusercontent.com/15871933/49571608-bf8cd300-f974-11e8-8ede-a6e924672117.png">

the last line is 107

**Comment by MenkeTechnologies** [comment]
error could be above line 107.
you ought to quote "$PATH:/usr/local/mysql/bin"
post line 1-107

**Comment by mcornella** [comment]
Stale issue

**Comment by touchmii** [comment]
The problem is rather bone-headed, in Vim set ff=mac

**Comment by touchmii** [comment]
The problem is rather bone-headed, in Vim set ff=mac
