### ISSUE TITLE
yarn workspaces support

### ISSUE THREAD

**Issue by chrisands** [robbyrussell/oh-my-zsh#7464]
@robbyrussell hi! 
I thought yarn plugin missing workspaces support 
alias yw='yarn workspace'
alias ywi='yarn workspaces info'

and autocompletion of packages names possible to add?
 
Workspaces folders indicated in package.json `  "workspaces": [ "packages/*" ]` and workspace name is in `package/somepackage/package.json` with property `name`

Also nice to autocomplete commands like after `yarn` and tab, but after `yarn workspace @pg/somepackage`. But not sure if it should be in yarn plugin.

Here's bash autocompletion that support workspaces. https://github.com/dsifford/yarn-completion

**Comment by dimensi0n** [comment]
I could create the alias if you want

**Comment by mcornella** [comment]
We're using [zsh-completions completion](https://github.com/zsh-users/zsh-completions/blob/master/src/_yarn), so ask for completion features there.
