### ISSUE TITLE
how can i change git branch listing?

### ISSUE THREAD

**Issue by deadlylaid** [robbyrussell/oh-my-zsh#7466]
HI when i run `git branch`

![2018-12-11 11 52 09](https://user-images.githubusercontent.com/16588261/49775343-380bdf00-fd3b-11e8-87a4-ccc2f861c48c.png)

oh-my-zsh is expose branches 
and when i was press `q` key i can exit this editor(is it a editor??)
it is difficult when i `delete branch`
![2018-12-11 11 57 56](https://user-images.githubusercontent.com/16588261/49775595-05aeb180-fd3c-11e8-847a-b75ae5a3f390.png)

but i want see branch listing like `bash`(just expose in command line not editor)

![2018-12-11 11 56 37](https://user-images.githubusercontent.com/16588261/49775540-de57e480-fd3b-11e8-9d19-c60f92153a61.png)

can i change this configuration??

**Comment by tassianoalencar** [comment]
> HI when i run `git branch`
> 
> ![2018-12-11 11 52 09](https://user-images.githubusercontent.com/16588261/49775343-380bdf00-fd3b-11e8-87a4-ccc2f861c48c.png)
> 
> oh-my-zsh is expose branches
> and when i was press `q` key i can exit this editor(is it a editor??)
> it is difficult when i `delete branch`
> ![2018-12-11 11 57 56](https://user-images.githubusercontent.com/16588261/49775595-05aeb180-fd3c-11e8-847a-b75ae5a3f390.png)
> 
> but i want see branch listing like `bash`(just expose in command line not editor)
> 
> ![2018-12-11 11 56 37](https://user-images.githubusercontent.com/16588261/49775540-de57e480-fd3b-11e8-9d19-c60f92153a61.png)
> 
> can i change this configuration??

Just add it to your git configuration file (~/.gitconfig)

```shell
[pager]
	branch = false
```

or

git config --global pager.branch false

**Comment by deadlylaid** [comment]
thank you ! :)

**Comment by GreatDefector** [comment]
Thank you! Found this from google in 2022, branches in oh my bash are behaving better now
