### ISSUE TITLE
auto-suggest is always stop my type

### ISSUE THREAD

**Issue by chenyuncai** [robbyrussell/oh-my-zsh#7467]
1. type some commands a few times before like tmxall, tmxall/somedir, tmxall/somedir2
1. then type tmx command

It shows a popup a history list about tmx related and set the first default selected, thus stopping me to hit enter.

I always have to hit ESC firstly to let it disappear.

I think it is a better way to set anything default. we can use up/down to select only if we want the suggested.

Or we can put the exact command that user typed in the first place.

Thanks.

**Comment by mcornella** [comment]
I think you're referring to https://github.com/zsh-users/zsh-autosuggestions, am I right? If so, that's a separate project.

**Comment by mcornella** [comment]
From email:

> Thanks for helping me about the issue https://github.com/robbyrussell/oh-my-zsh/issues/7467, but the link you suggested is not the issue described.
> 
> ![屏幕快照 2019-07-05 13 53 52](https://user-images.githubusercontent.com/1441704/60706712-5a00c500-9f0a-11e9-9787-3d1133e7143e.png)
> 
> I typed "cd tmxmall" When I type some commands before like “cd tmxmall/test, cd tmxmall/demo”, the terminal shows up a popup about the history records.
> 
> And I cannot use “tab" key to list the subitems because of the popup, but there are lots of files in the tmxmall directory indeed.
> 
> In this case, I have to use “esc” key to hide the popup and then enter “tab” to list all the sub files.
> 
> So is there anyway to optimize the interaction?  I wish it can allow me type any key.

------

That looks like it's a feature of your terminal emulator, in this case [iTerm2](https://www.iterm2.com/documentation-shell-integration.html). Look up how to disable that in the preferences.
