### ISSUE TITLE
Git plugin stash alias should use push instead of save

### ISSUE THREAD

**Issue by InfinitySamurai** [robbyrussell/oh-my-zsh#7474]
According to git-stash man page:

git stash save: `This option is deprecated in favour of git stash push`

Currently the git plugin has an alias `gsta='git stash save'`
Should this be changed to `gsta='git stash push'`

**Comment by p-himik** [comment]
Here's the relevant line from `man git-stash` (Git version 2.19.1):
```
git stash [push [-p|--patch] [-k|--[no-]keep-index] [-q|--quiet]
             [-u|--include-untracked] [-a|--all] [-m|--message <message>]
             [--] [<pathspec>...]]
```
As you can see, `git stash` and `git stash push` are not equivalent if you want to add any parameters to the command.
I guess a good way to solve it would be to add a function `_git_stash_push` that would try `git stash push` and if that fails, `git stash save`. And then alias it to `gsta`.
