### ISSUE TITLE
fzf-history-widget: fc:3: history events are in wrong order, aborted

### ISSUE THREAD

**Issue by manfredlotz** [robbyrussell/oh-my-zsh#7478]
I'm often working on an older Debian system where I get

fzf-history-widget: fc:3: history events are in wrong order, aborted

when searching history.

I'm not sure if this is an oh-my-zsh issue or if it is related to zsh being pretty old. zsh is zsh 4.3.17 (x86_64-unknown-linux-gnu)

Things work fine on my laptop which is Fedora 29.

**Comment by manfredlotz** [comment]
I'm often working on an older Debian system where I get 

  fzf-history-widget: fc:3: history events are in wrong order, aborted

when searching history.

I'm not sure if this is an oh-my-zsh issue or if it is related to zsh being pretty old. zsh is zsh 4.3.17 (x86_64-unknown-linux-gnu)

Things work fine on my laptop which is Fedora 29.

**Comment by mcornella** [comment]
This is probably an issue with fzf, ask there.
