### ISSUE TITLE
what is the name of this theme

### ISSUE THREAD

**Issue by kerolloz** [robbyrussell/oh-my-zsh#7485]
![image](https://user-images.githubusercontent.com/36763164/50540601-65f77d00-0b9d-11e9-807d-f3c911b49f03.png)

**Comment by robbyrussell** [comment]
I'm not familiar with that specific one. I don't believe it's bundled into OMZ (at least, I searched for a '¶' and didn't see anything in here). You might ask on twitter and/or add a comment to the youtube video creator. Best of luck!

**Comment by kerolloz** [comment]
I found it here: 
https://github.com/johndbritton/dotfiles/blob/master/dot/oh-my-zsh/custom/themes/johndbritton.zsh-theme :heart:
