### ISSUE TITLE
oh-my-zsh inxi issue

### ISSUE THREAD

**Issue by sandikata** [robbyrussell/oh-my-zsh#7487]
with oh-my-zsh no matter what theme, inxi just not rendered with colors but only showing color codes.
what could be the problem?

12CPU~8 core AMD FX-8320 Eight-Core (-MCP-) 12speed/max~4514/4500 MHz 12Kernel~4.20.0-funtoo x86_64 12Up~1 day 12Mem~3882.1/24062.3MB 12HDD~1620.3GB(48.2% used) 12Procs~410 12Client~Unknown : zsh 12inxi~2.3.56

it shouldn't show color codes, but to render them..

**Comment by smxi** [comment]
File an issue on this where it belongs, https://github.com/smxi/inxi

This is an issue with the start client not presenting inxi with a recognizable shell environment, making it assume it's in IRC.

With the right debugger data, that can sometimes be corrected for some start clients, like MOTD, Ansible, Chef. Depends.

I'll take a look at it once you file the issue in the right place, inxi issues.

**Comment by sandikata** [comment]
problem seems to be fixed by closing terminal and relogin.

**Comment by respencer** [comment]
Since this doesn't appear to be an oh-my-zsh issue, can you please close this issue?
