### ISSUE TITLE
When you insert the command appears white fill

### ISSUE THREAD

**Issue by euppi98** [robbyrussell/oh-my-zsh#7490]
When you insert a command, a white fill appears. How to remove it?
<img width="152" alt="screen shot 2019-01-01 at 23 57 05" src="https://user-images.githubusercontent.com/23306157/50576343-1e812300-0e21-11e9-9b23-3b8e46f6ca44.png">

**Comment by respencer** [comment]
That just means the text is highlighted. Press the right arrow key, type something more on the command line, or press Enter and the highlighting will disappear.
