### ISSUE TITLE
How do i use default commands mac?

### ISSUE THREAD

**Issue by cuexit** [robbyrussell/oh-my-zsh#7493]
Hey,

This might have been asked already but couldn't find the issue. When i try to run the default commands of mac before i had this installed it doesn't work anymore. How can i use the default commands again with oh my zsh?

Kind regards,

cuexit

**Comment by mcornella** [comment]
Your `$PATH` might be different. See if you had it defined somewhere in the rc files of your previous shell (if bash, that is in `.bashrc` or `.bash_profile`).
