### ISSUE TITLE
Random emoji for each line 

### ISSUE THREAD

**Issue by kerolloz** [robbyrussell/oh-my-zsh#7500]
I want to make my prompt to print a random emoji for each command I write. I can make it print a random emoji for each new terminal but I have no idea how to make it print a random emoji for each new command.

**Comment by mcornella** [comment]
If you're using the [emoji plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/emoji) you would put a call to the `random_emoji` function in your `PROMPT` or `RPROMPT`. Something like
```
PROMPT='......$(random_emoji) '
```
