### ISSUE TITLE
ZSH keeps on asking for passphrase

### ISSUE THREAD

**Issue by iamdevlinph** [robbyrussell/oh-my-zsh#7509]
I noticed that with the latest update zsh always asks me for the passphrase.

Before it would ask me one time on start-up of the ssh-agent but now it doesn't appear anymore.

I already have the `ssh-agent` on my plugins
```
plugins=(
    git ssh-agent zsh-autosuggestions
)
```

```
zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
```

**Comment by iamdevlinph** [comment]
It just shows `starting ssh-agent...` but doesn't ask for my passphrase 🤔 

![image](https://user-images.githubusercontent.com/19337229/51099699-47d08480-180d-11e9-8df7-4654dfcb06a8.png)

**Comment by iamdevlinph** [comment]
Fixed it by following this: https://github.com/robbyrussell/oh-my-zsh/issues/4862#issuecomment-392551701

**Comment by iamdevlinph** [comment]
It's really this update that broke ssh-agent

![image](https://user-images.githubusercontent.com/19337229/51222263-ec6ed580-1977-11e9-93a1-431391f3b1df.png)

Look how after "starting ssh-agent" it does't ask for my passphrase.

**Comment by mcornella** [comment]
It's possible this is the same as https://github.com/robbyrussell/oh-my-zsh/pull/7174#issuecomment-454741290. See if #7520 fixes it.

**Comment by iamdevlinph** [comment]
I guess it is. I'll be closing this one.

**Comment by mcornella** [comment]
Can you check if applying the change at #7520 fixes your problem?

**Comment by iamdevlinph** [comment]
Hi. Sorry I didn't try any more solutions since mine was fixed by https://github.com/robbyrussell/oh-my-zsh/issues/4862#issuecomment-392551701

**Comment by iamdevlinph** [comment]
Just to update. The issue does not exist any more as of version `zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`.
I also removed the code snippet I used from here: https://github.com/robbyrussell/oh-my-zsh/issues/4862#issuecomment-392551701
```
zstyle :omz:plugins:ssh-agent identities id_rsa id_bob
```
