### ISSUE TITLE
Theme astm Missing

### ISSUE THREAD

**Issue by Gerst20051** [robbyrussell/oh-my-zsh#7510]
`.oh-my-zsh/themes/astm.zsh-theme` doesn't exist in the repo but is in the list of available themes.

**Comment by BusyHe** [comment]
+1

**Comment by lhorace** [comment]
Was that '+1' to let us know he changed the title?

**Comment by mcornella** [comment]
Change reverted. [It looks like a user's mistake](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes/_compare/36761cf8a20a8338efcb65d424ded1d99554cceb)
