### ISSUE TITLE
function definition not found 

### ISSUE THREAD

**Issue by richaeell** [robbyrussell/oh-my-zsh#7513]
Ive been looking in all issues and no answer has solved my problem. 
when I run zsh I get the followeing errors:
`/etc/zsh/zshrc:111: compinit: function definition file not found
/home/richard/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/richard/.oh-my-zsh/oh-my-zsh.sh:76: compinit: function definition file not found
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:83: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:98: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:105: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:118: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:128: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:153: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:162: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:172: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:175: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:177: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:194: command not found: compdef
/home/richard/.oh-my-zsh/plugins/git/git.plugin.zsh:208: command not found: compdef`

zsh version:
`zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`

My $FPATH is the following: 
`/home/richard/.oh-my-zsh/plugins/git /home/richard/.oh-my-zsh/functions /home/richard/.oh-my-zsh/completions /home/richard/.oh-my-zsh/plugins/git /home/richard/.oh-my-zsh/functions /home/richard/.oh-my-zsh/completions /usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/Zftp /usr/share/zsh/functions/Zle` 

And if I export it by typing export FPATH it SEEMS to work fine. 
I have no Idea where else to look, any help is well apreciated!

**Comment by MenkeTechnologies** [comment]
autoload compinit?

**Comment by MenkeTechnologies** [comment]
colors is at /usr/share/zsh/functions/Misc not sure why this is not in your FPATH

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/issues/4607

**Comment by natema** [comment]
Similar issue, solved by updating the line 
```zsh
export FPATH="/usr/share/zsh/5.8/functions:$FPATH"
```
to 
```zsh
export FPATH="/usr/share/zsh/5.8.1/functions:$FPATH"
```
in my `.zshrc`.

**Comment by carlosala** [comment]
You shouldn't export FPATH. Just rebooting the computer solves the issue!

**Comment by natema** [comment]
> You shouldn't export FPATH. Just rebooting the computer solves the issue!

I tried that, but `zsh` continued to be missing the correct `FPATH`, since the line I had in `.zshrc` remained wrong. Perhaps you had a different problem, or is a reboot supposed to get for the correct `FPATH` from somewhere else?

**Comment by carlosala** [comment]
You should delete the line exporting and changing FPATH. Then reboot and everything should work.

**Comment by natema** [comment]
I see, thank you!
