### ISSUE TITLE
ssh-add always prompts for password

### ISSUE THREAD

**Issue by ulrichSchreiner** [robbyrussell/oh-my-zsh#7516]
hi,

since the last change in `ssh-add` i always have to enter the password for one of my keys. the problem is, that now `ssh-keygen -lf <mykey>` is used to extract the signatures of keys. but one of my keys is reported as **not a key file**.

i can reproduce the whole thing with a fresh key:
~~~
openssl genrsa -aes256 -out example.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
.........................+++++
............+++++
e is 65537 (0x010001)
Enter pass phrase for example.key:
Verifying - Enter pass phrase for example.key:
~~~
but now:
~~~
$ ssh-keygen -l -f example.key 
example.key is not a key file.
~~~
but the key can be loaded with `ssh-add`:
~~~
$ ssh-add example.key 
Enter passphrase for example.key: 
Identity added: example.key (example.key)
$ ssh-add -l
2048 SHA256:PBYUzy+OyFzmRg1hPNBEdv6uuwQf8rRAyVmNLL6lfr8 example.key (RSA)
~~~

the `ssh-add` plugin always tries to load the signatures with `ssh-keygen` but with this new key this fails. and so i always have to enter the passphrase for this one key althoug it is loaded in the agent.

i do not know why `ssh-keygen` thinks this is an illegal key, but since the last changes to the `ssh-add` plugin every new shell asks for the passphrase.

**Comment by mcornella** [comment]
I've submitted a fix at #7521, hopefully it works. Please try it and report back

**Comment by ulrichSchreiner** [comment]
hi,

this one works with all of my keys, including the one reported as **not a key file**.

thanks for the patch, the bug seems to be fixed (although i think is more a bug from `ssh-keygen`).

**Comment by mcornella** [comment]
Thanks for the confirmation, it is now merged!

**Comment by thorian93** [comment]
I have the very same issue now.

4096 bit key on Debian 10.

`ssh-keygen -lf /path/to/key.file` throws: `key.file is not a key file.`

Can anyone point me in the right direction to fix this?
