### ISSUE TITLE
request support: rebar3 plugin

### ISSUE THREAD

**Issue by hmgle** [robbyrussell/oh-my-zsh#7519]
The erlang build tool `rebar` is deprecated now. The successor to `rebar` is [rebar3](https://github.com/erlang/rebar3), could somebody add the rebar3 plugin? It's very usefull tool which will replace rebar in further.

**Comment by hmgle** [comment]
`rebar3` already includes the [completion shell](https://github.com/erlang/rebar3/blob/master/priv/shell-completion/zsh/_rebar3), just copy it to a fpath (e.g.:/usr/local/share/zsh/site-functions).

**Comment by mdbrnowski** [comment]
updated link for anyone looking for it: [completion shell](https://github.com/erlang/rebar3/blob/main/apps/rebar/priv/shell-completion/zsh/_rebar3)
