### ISSUE TITLE
/etc/passwd file permissions changed after execution of install.sh

### ISSUE THREAD

**Issue by sandrohuber** [robbyrussell/oh-my-zsh#7530]
Hey all,

Some days ago, the issue #7492 was fixed by commit #7514. Now after installing it, the /etc/passwd actually is setup with the correct shell:

old: `root:x:0:0:root:/root:/bin/bash`
new: `root:x:0:0:root:/root:/usr/bin/zsh`

It might be possible, that the call `expr "$SHELL" : '.*/\(.*\)'`did fail for quite some time, but I suspect, almost everybody tailored the install.sh with `|| true`? 

Since the install script sets `umask g-w,o-w`, I will loose previously set permissions on edited files in the install script, e.g /etc/passwd.

Run `docker build .`on this Dockerfile:

```
FROM ubuntu:16.04

RUN set -ex \
  && apt-get update \
  && apt-get install curl -y \
  && apt-get install zsh -y \
  && apt-get install git -y

RUN chmod 666 /etc/passwd

RUN ls -l /etc/passwd

# this now also works without `|| true`
RUN curl https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh || true

RUN ls -l /etc/passwd
```

The permissions change from (not sure why only other looses write permissions, while group keeps it)
`-rw-rw-rw- 1 root root 1239 Dec 18 05:44 /etc/passwd` to
`-rw-rw-r-- 1 root root 1242 Jan 18 12:29 /etc/passwd`.

If you run the Dockerfile instead with the old version of the script: `RUN curl https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/8f95637e6772a1156a29d9c6a9c21ea8d7316a12/tools/install.sh | sh || true` the command will fail, the /etc/passwd will not be updated, thus keeping the permissions previously set.

To fix this in the meantime simply run `RUN chmod 666 /etc/passwd` after running install.sh, but this is quite ugly.

**Comment by mcornella** [comment]
That's actually `chsh` doing it, here's an strace of just the command, with no umask or the OMZ installer having been called previously:
```
umask(0777)                             = 077
open("/etc/passwd+", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4
umask(077)                              = 0777
fchown(4, 0, 0)                         = 0
fchmod(4, 0660)                         = 0
fstat(4, {st_mode=S_IFREG|0660, st_size=0, ...}) = 0
write(4, "root:x:0:0:root:/root:/bin/zsh\nd"..., 1238) = 1238
fsync(4)                                = 0
close(4)                                = 0
lstat("/etc/passwd", {st_mode=S_IFREG|0772, st_size=1239, ...}) = 0
rename("/etc/passwd+", "/etc/passwd")   = 0
```

If you're able to follow the output, you can see that chsh creates a file called `/etc/passwd+`, changes its permissions to 600 (rw-rw-r--), then renames it to `/etc/passwd`. 

That was after running `chmod 772` on it. After a couple more tests, I saw that what chsh does is setting the permissions such that it removes all-executable and other-writable. So if the permissions were set at 777, it would end up at 664. If it was set at 644, it would keep it that way.

I haven't found documentation on why it does that, but in my opinion it just seems common sense. You don't want to let any user change what the login shell of root is  for example

So not only is this not the fault of the installer, it's behavior is also appropriate for the user's security.

**Comment by sandrohuber** [comment]
Ah I see; I also doubted that this is directly related to OMZ. Thanks!
