### ISSUE TITLE
Clear git Prompt

### ISSUE THREAD

**Issue by aritro6** [robbyrussell/oh-my-zsh#7537]
Hello!

I am using iTerm for my terminal, powerlevel9k as my theme and I am on a Mac. I am having an issue (maybe it's a git thing) but one day while I was using git, I accidentally committed code outside of the directory the project was on and since zsh has a git prompt on it, this shows up.

<img width="404" alt="zsh-problem" src="https://user-images.githubusercontent.com/11360056/51445472-945f0880-1cc2-11e9-9371-708aaf14b543.png">

It comes up no matter what project I am on. In the image, I am in my main directory.

How do I get clear this so I can start fresh?

Thank you.

**Comment by respencer** [comment]
You can't commit code outside the directory your project is in unless that directory is also a git repository.

I would guess that cleaning up that git repo would resolve the issue.

**Comment by mcornella** [comment]
You need to find the root directory of the git repo you're in. `git rev-parse --show-toplevel` will help you. Then you can run `git status` to figure out what to do. You'll probably have to end up deleting the `.git` folder in that root directory.
