### ISSUE TITLE
misc.zsh (`\n') git.plugin.zsh (_omz_git_git_cmd^M)

### ISSUE THREAD

**Issue by sahlouls** [robbyrussell/oh-my-zsh#7542]
Hi,

two errors after upgrade

* OS: Ubuntu 18.04
There is a problem with end of line characters 

```
$ source .zshrc

.../.oh-my-zsh/lib/misc.zsh:41: parse error near `\n'
.../.oh-my-zsh/plugins/git/git.plugin.zsh:2: not an identifier: _omz_git_git_cmd^M
```

I re-saved the files using `LF` and no more warnings.

Thanks

**Comment by Roguyt** [comment]
For those having this issue, you can easily fix it with 2 commands
```
dos2unix -b ~/.oh-my-zsh/lib/misc.zsh
dos2unix -b ~/.oh-my-zsh/plugins/git/git.plugin.zsh
```

But yeah something broke after last upgrade :c

**Comment by mcornella** [comment]
Has your git config `core.autocrlf` value changed? We didn't change anything...

**Comment by synbit** [comment]
I had the same issue and basically it was me setting `autocrlf` to `true` which is wrong as it will convert line endings to `CRLF` thus causing this issue. I changed my Git config globally, saved the files with new line endings (`LF`), problem solved. But that's what happened in my case.

**Comment by tameemkhan** [comment]
> 
> 
> For those having this issue, you can easily fix it with 2 commands
> 
> ```
> dos2unix -b ~/.oh-my-zsh/lib/misc.zsh
> dos2unix -b ~/.oh-my-zsh/plugins/git/git.plugin.zsh
> ```
> 
> But yeah something broke after last upgrade :c

Was facing same issue and this solved the issue for me.
