### ISSUE TITLE
.zshrc custom installation : how to source it?

### ISSUE THREAD

**Issue by politicus** [robbyrussell/oh-my-zsh#7543]
I want to install oh-my-zsh and its settings (i.e. zshrc file) in a subfolder of my Dropbox.

Found how to modify the path to my oh-my-zsh installation. 

I also wants to add my .zshrc file in my Dropbox so I do not have to modify the settings on any of my macs. 

My settings only loads when .zshrc is located in ~/  When located in one of my Dropbox sub-folder they don't. 

How can I source my .zshrc file so I do do have to source it manually every time I launch zsh?

Thank you !

**Comment by mcornella** [comment]
You can move the zshrc file to your Dropbox folder and make a symlink to it in your home directory (named `.zshrc`).

**Comment by politicus** [comment]
Thank you for your answer. This is what I ended doing 10 minutes ago after reading this on [SO](https://stackoverflow.com/questions/27659100/how-to-specify-a-custom-path-for-my-zshrc-file). It is a fast solution but is it the only solution?
