### ISSUE TITLE
zsh mistakenly thinks unterminated quote

### ISSUE THREAD

**Issue by ahmetb** [robbyrussell/oh-my-zsh#7557]
(not sure if zsh bug or by-design or oh-my-zsh bug)

When I type `echo --message="foo!"` to my oh-my-zsh (up-to-date) with zsh 5.3, I get a "dquote" prompt for an unterminated quote:

```
$ echo --message="foo!"
dquote>
```

This does not happen in bash.

Weird enough, when I drop the `!` from `foo!` it works fine:

```
echo --message="foo"
--message=foo
```

(I'm sorry for reporting here if this is not a zsh issue.)

**Comment by schrer** [comment]
It seems you already got your answer on stackexchange. 

For me it works to just escape the exclamtion mark with a backslash, like so "\!".

For those interested, the accepted answer on stackexchange says that "that's the history expansion at work", so it's a feature of zsh.
Link to the question on stackexchange:
[ZSH thinks unterminated quote if preceded by exclamation mark (!)](https://unix.stackexchange.com/questions/497328/zsh-thinks-unterminated-quote-if-preceded-by-exclamation-mark)

**Comment by mcornella** [comment]
Using single quotes also works.
