### ISSUE TITLE
oh-my-zsh default ~/.zshrc will cause locale to be unset

### ISSUE THREAD

**Issue by eatradish** [robbyrussell/oh-my-zsh#7558]
When loading omz default zshrc file:
```
 🌝👍 ~ echo $LANG

```
and bash:
```
 🌝👍 v bash
sakiiily@eat-x220i [ v ] $ echo $LANG
en_US.UTF-8
```
The solution is to add `source /etc/profile` to your zshrc

**Comment by ston1x** [comment]
I experience this too, especially when trying to install some packages like neovim via pip. It says there’s no environment variables for locale so I set it manually in my .zshrc

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by respencer** [comment]
Odd, that's not the default behavior on my system. I get "en_ZA.UTF-8" under both my zsh config and the default for oh-my-zsh, which is correct for my system.

**Comment by krupenja** [comment]
Have come across this problem. After installing oh-my-zsh, I had no locale-related exports in .zshrc and the output of `locale` command was:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Had to manually add these:

```
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```

Otherwise installation of some software (gcalcli, php) was failing.

**Comment by respencer** [comment]
On my system (Kubuntu 18.10) locales are set outside the shell and then inherited by each shell.

All my shells also read /etc/profile, and ~/.profile, so I find it odd that the OP had an issue with that. All login shells should be reading those files. Unless he's not using it as a login shell.

I have noticed one reference that says zsh uses /etc/zprofile, and ~/.zprofile, but I haven't seen that myself.

Looking through the code in my oh-my-zsh installation I can only find an external theme (powerlevel9k.zsh-theme), that harmfully fiddles with locales their justification being: "Set the right locale to protect special characters".

So maybe it's a theme that's screwing you over.

**Comment by mcornella** [comment]
If you run `zsh -f` (which doesn't read user rc files), is this issue still there? If yes (probably) then it's not a problem of OMZ but of the way your profile files are loaded. Most zsh setups don't load `/etc/profile`, see [Startup/Shutdown_files](https://wiki.archlinux.org/index.php/zsh#Startup/Shutdown_files). As Arch Linux does, you could add a line in `/etc/zsh/zprofile` to `source /etc/profile`.
