### ISSUE TITLE
Does it support Windows?

### ISSUE THREAD

**Issue by abcplex** [robbyrussell/oh-my-zsh#7560]
I have used this terminal in Mac but now I am using Windows. Does it support windows? If not do you have any idea what is close to this on windows?

**Comment by shmcgough** [comment]
You might want to look into babun. It has integrated oh my zsh http://babun.github.io/

**Comment by mcornella** [comment]
You can also use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10), or cygwin.

**Comment by abcplex** [comment]
I wanna use it just for GIT and multi tab. I don't wanna add Linux in Windows.

**Comment by mcornella** [comment]
If you don't want to add Linux you can use cygwin, or [Git for Windows](https://gitforwindows.org/). This last one comes with bash, but I believe it also has git completion. Otherwise, you might be able to install zsh on it too.
