### ISSUE TITLE
Arrow and cross symbols disappeared from the prompt for Mac OS 10.14.4 beta

### ISSUE THREAD

**Issue by maksimf** [robbyrussell/oh-my-zsh#7563]
On my Mac OS 10.14.4 Beta prompt looks like this:

<img width="577" alt="screenshot 2019-01-30 at 16 38 06" src="https://user-images.githubusercontent.com/860283/51984945-b3714d80-24ad-11e9-9c3e-7141e78722b6.png">

Note green and yellow underscore in the beginning and the end of the line, it should look like this:

![710cbb8c-ba03-11e4-90b3-0315d72f270c](https://user-images.githubusercontent.com/860283/51985021-e582af80-24ad-11e9-8a28-508ed141e02b.jpg)

Everything was fine until I've upgraded Mac OS to 10.14.4 Beta

**Comment by mcornella** [comment]
Has the font changed?

**Comment by maksimf** [comment]
This has nothing to do with oh-my-zsh, since it works in iTerm just fine, but doesn't work when I'm launching tmux
