### ISSUE TITLE
Colored "ls" output in FreeBSD

### ISSUE THREAD

**Issue by ymitsos** [robbyrussell/oh-my-zsh#7565]
Colored ls output in FreeBSD might be enabled using the same approach as OpenBSD, darwin using   the following simple diff. Shall I send a PR?
```
diff --git a/lib/theme-and-appearance.zsh b/lib/theme-and-appearance.zsh
index 96f34aa8..d5907cc5 100644
--- a/lib/theme-and-appearance.zsh
+++ b/lib/theme-and-appearance.zsh
@@ -22,6 +22,9 @@ if [[ "$DISABLE_LS_COLORS" != "true" ]]; then
   elif [[ "$OSTYPE" == darwin* ]]; then
     # this is a good alias, it works by default just using $LSCOLORS
     ls -G . &>/dev/null && alias ls='ls -G'
+  elif [[ "$OSTYPE" == freebsd* ]]; then
+    # this is a good alias, it works by default just using $LSCOLORS
+    ls -G . &>/dev/null && alias ls='ls -G'
```

**Comment by mcornella** [comment]
OpenBSD is supported in the lines above darwin:
https://github.com/robbyrussell/oh-my-zsh/blob/8fba503667a477b544bfd1fa33e75430874e228a/lib/theme-and-appearance.zsh#L15-L21

Any reason to change it?

**Comment by ymitsos** [comment]
@mcornella I refer to FreeBSD not to OpenBSD. 
For instance the OSTYPE variable in FreeBSD holds values like: "freebsd12.0", so your quoted snippet is not sourced because the if statement fails. There has to be another elif statement to support FreeBSD. 

On top of that, FreeBSD's ls command supports natively, nowadays, colored output using the -G flag, so no need to install the gnuls package (as per the OpenBSD statement).

**Comment by mcornella** [comment]
Ok, then we could just patch the darwin conditional to support freebsd as well:
```diff
diff --git a/lib/theme-and-appearance.zsh b/lib/theme-and-appearance.zsh
index 96f34aa8..d5907cc5 100644
--- a/lib/theme-and-appearance.zsh
+++ b/lib/theme-and-appearance.zsh
@@ -22,6 +22,9 @@ if [[ "$DISABLE_LS_COLORS" != "true" ]]; then
-   elif [[ "$OSTYPE" == darwin* ]]; then
+   elif [[ "$OSTYPE" == (darwin|freebsd)* ]]; then
     # this is a good alias, it works by default just using $LSCOLORS
     ls -G . &>/dev/null && alias ls='ls -G'
```

You can send a PR, yes please.
