### ISSUE TITLE
Sublime plugin inconsistent readme and platform support

### ISSUE THREAD

**Issue by winkelsdorf** [robbyrussell/oh-my-zsh#7570]
I stumbled about a platform inconsistency with the current sublime plugin.

In 2015 @ckesc introduced the `sst` command which sudos sublime (commit 5b90092). Readme was later updated to reflect this change (commit c28b226).

This is misleading now. Having a look at the plugin source `sst` is only available for Linux, no alias were introduced for macOS and cygwin. The latter may not provide `sudo` but macOS indeed does.

**Comment by mcornella** [comment]
#7715 will fix this.

**Comment by winkelsdorf** [comment]
@mcornella Thanks for taking care of!
