### ISSUE TITLE
ggl giving error, temporarily fixed by commenting lines

### ISSUE THREAD

**Issue by abdullahkhilji** [robbyrussell/oh-my-zsh#7572]
/Users/abdullahkhilji/.oh-my-zsh/plugins/git/git.plugin.zsh:120: defining function based on alias `ggl'
/Users/abdullahkhilji/.oh-my-zsh/plugins/git/git.plugin.zsh:120: parse error near `()'

**Comment by respencer** [comment]
Did you change it before you got that error?

And can you paste line 120 from that file here.

**Comment by abdullahkhilji** [comment]
```
ggl() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git pull origin "${*}"
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git pull origin "${b:=$1}"
  fi
}
compdef _git ggl=git-checkout
```

**Comment by mcornella** [comment]
Do you have an alias named `ggl`? It's possible that's triggering the error. Look it up by running `alias ggl`.

**Comment by abdullahkhilji** [comment]
~ 
➜ alias ggl
ggl='git grep --files-with-matches'

**Comment by mcornella** [comment]
It must be in your `.zshrc` file, before sourcing OMZ. If it's not there, check out `.zshenv` or `.zprofile`, all in your home directory. Closing this issue then.
