### ISSUE TITLE
When using iTerm, the colours don't get applied unless new tab is opened.

### ISSUE THREAD

**Issue by marbuser** [robbyrussell/oh-my-zsh#7573]
So I'm using ZSH with iTerm, and it “sort of” works. I have a theme loaded ('dracula' to be specific but this also happens with default fonts), and I also setup some colour options in iTerm for background colour and such.

However, when launching iTerm, I always get this Black background;
![image](https://user-images.githubusercontent.com/34422459/52160969-536ee700-26f9-11e9-9e9b-6cf80b71e4fc.png)

However, if I then make a new tab, it works fine?
![image](https://user-images.githubusercontent.com/34422459/52160983-7b5e4a80-26f9-11e9-9d5e-3d6cd25ad3a6.png)

However, if I use the new tab, I still get basic ZSH functionality but it's almost as if the theme isn't loaded properly. The theme by default strips computer name and such (and it does in the first tab), but in the second window it doesn't.

This exact thing happens with every single theme I've tried (including around 10 of the default ones.)

Can someone explain why this is happening? Since as much as I like ZSH, I'm not willing to sacrifice my eyes for the added functionality of it with this dreaded solid black background.

**Comment by respencer** [comment]
I don't have a working Mac any longer unfortunately, so I can't even try to replicate that on my end.

That being said, do you get the same result if you do the following?

mv -i ~/.zshrc ~/_zshrc
Close iTerm
Open new iTerm session
Open new tab

That should result in you testing on a naked (default) zsh setup without any theme getting involved except your setting in iTerm.

**Comment by marbuser** [comment]
Hey @respencer ,

Completely forgot I opened this. I actually managed to fix it by just completely uninstalling iTerm and reinstalling it from scratch with default config files and everything. Seemed to fix it so much have been an iTerm issue.

Thanks anyway! :)
