### ISSUE TITLE
ssh-agent plugin not working after update

### ISSUE THREAD

**Issue by frankfuu** [robbyrussell/oh-my-zsh#7575]
Eversince `oh-my-zsh` prompted me to upgrade and pressing `y` I've been receiving this error. I'm currently using Windows 10's WSL on Ubuntu 18.04

**The error I get**
```
/home/frank/.oh-my-zsh/lib/misc.zsh:41: parse error near `\n'
/home/frank/.oh-my-zsh/plugins/git/git.plugin.zsh:2: not an identifier: _omz_git_git_cmd^M
/home/frank/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:typeset:1: not valid in this context: _ssh_env_cache^M
```

**.zshrc**
```
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="ys"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(
  git
  ssh-agent
  colored-man-pages
)

source $ZSH/oh-my-zsh.sh

# Aliases
alias dkr="docker-compose"
alias dc="docker-compose"
alias reload="source .zshrc"
```

Any idea what's going on? Is it line endings?

**Comment by respencer** [comment]
See the comment by @Roguyt for issue #7542

**Comment by frankfuu** [comment]
Thanks @respencer. I had to install `dos2unix` and run it against the problematic files

```
sudo apt install dos2unix -y
```

```
dos2unix /home/frank/.oh-my-zsh/lib/misc.zsh
dos2unix  /home/frank/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh
ddos2unix /home/frank/.oh-my-zsh/plugins/git/git.plugin.zsh
```

It's strange though, I don't have my `core.autocrlf` changed because I have my dotfiles under source control and symlinked.

I'm suspecting my setting of `core.autocrlf=true` might be the culprit.

**Comment by frankfuu** [comment]
@respencer, can be be closed. Thanks again.

**Comment by mcornella** [comment]
This is due to the git-config's `core.autocrlf` setting. See https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351

**Comment by frankfuu** [comment]
@mcornella thanks for confirming.
