### ISSUE TITLE
dotenv: make it possible to define the file you would like to use

### ISSUE THREAD

**Issue by NotSoShaby** [robbyrussell/oh-my-zsh#7579]
It would be good to have the ability to set the file's name  you would like to use for the env (I for example have a problem with .env file because it is not recognized by my pycharm EnvFle plugin)

**Comment by mcornella** [comment]
Are you referring to the `dotenv` file? If so, this would be a simple change, just define a `ZSH_DOTENV_FILE` variable that defaults to `.env` and use that in the `source_env` function wherever it says `.env`:
https://github.com/robbyrussell/oh-my-zsh/blob/bb64446ebf51ef9ab8c6cf9f2569a0900529861e/plugins/dotenv/dotenv.plugin.zsh#L1-L14

Then add it to the README and it's done. Care to submit a PR?

**Comment by arshadkazmi42** [comment]
I would like to take this up, if its still available

**Comment by mcornella** [comment]
Absolutely, go ahead thanks!

**Comment by arshadkazmi42** [comment]
> Are you referring to the `dotenv` file? If so, this would be a simple change, just define a `ZSH_DOTENV_FILE` variable that defaults to `.env` and use that in the `source_env` function wherever it says `.env`:
> 
> https://github.com/robbyrussell/oh-my-zsh/blob/bb64446ebf51ef9ab8c6cf9f2569a0900529861e/plugins/dotenv/dotenv.plugin.zsh#L1-L14
> 
> Then add it to the README and it's done. Care to submit a PR?

I would need some more help. So as per my understanding, I have to create a temporary variable `ZSH_DOTENV_FILE = .env`
and then replace `.env` with `ZSH_DOTENV_FILE` in the function.
This should be defined inside the function above, or somewhere else.
What and where exactly this needs to be added in README.
This is my first contribution to oh-my-zsh, so might need help understanding the codebase

**Comment by mcornella** [comment]
Ok let me run down the list of steps:

The plugin should:
1. Check if `ZSH_DOTENV_FILE` is defined, and set it to `.env` if it's not defined. This should go outside the `source_env` function, preferrably before it. You can do this two ways:

	1. Check [if $ZSH_DOTENV_FILE is empty](http://zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html), then set it. This is done with `[[ -z $variable ]]`.

	2. Use [parameter expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion) to set it to the default value `.env`. This would look like:
		```zsh
		: ${ZSH_DOTENV_FILE:=.env}
		```

2. Replace where it says `.env` with `$ZSH_DOTENV_FILE` in the `source_env` file.
3. In the `echo dotenv error` line you'll have to use double quotes (as well as using `$ZSH_DOTENV_FILE` instead of `.env`), and substitute the backticks (<code>`</code>) with single quotes (this last part is because backticks are interpreted as wanting to run a command):
	```zsh
	echo "dotenv: error when sourcing '$ZSH_DOTENV_FILE' file" >&2
	```
4. In the README, add a section called Settings or Configuration and document that there is this setting available, describe it and what its default value is. There is a [GitHub Markdown guide available](https://guides.github.com/features/mastering-markdown/) if you need it.

**Comment by arshadkazmi42** [comment]
@mcornella I gave it a first try. Diff looks something like below

```diff
diff --git a/plugins/dotenv/dotenv.plugin.zsh b/plugins/dotenv/dotenv.plugin.zsh
index b701b559..abd26e5c 100644
--- a/plugins/dotenv/dotenv.plugin.zsh
+++ b/plugins/dotenv/dotenv.plugin.zsh
@@ -1,13 +1,13 @@
 source_env() {
-  if [[ -f .env ]]; then
+  if [[ -f $ZSH_DOTENV_FILE ]]; then
     # test .env syntax
-    zsh -fn .env || echo 'dotenv: error when sourcing `.env` file' >&2
+    zsh -fn $ZSH_DOTENV_FILE || echo `dotenv: error when sourcing '$ZSH_DOTENV_FILE' file` >&2

     if [[ -o a ]]; then
-      source .env
+      source $ZSH_DOTENV_FILE
     else
       set -a
-      source .env
+      source $ZSH_DOTENV_FILE
       set +a
     fi
   fi
@@ -16,4 +16,9 @@ source_env() {
 autoload -U add-zsh-hook
 add-zsh-hook chpwd source_env

+if $ZSH_DOTENV_FILE is empty; then
+  [[ -z $variable ]]
+else
+  : ${ZSH_DOTENV_FILE:=.env}
+
 source_env
```

I can't find `Settings` or `Configuration` in the main readme.
Is it in some other readme.

**Comment by mcornella** [comment]
> ```diff
> +    zsh -fn $ZSH_DOTENV_FILE || echo `dotenv: error when sourcing '$ZSH_DOTENV_FILE' file` >&2
> ```

Here the backticks (<code>\`</code>) should be substituted with double quotes (`"`). Backticks are interpreted by the shell as "run whatever is inside it as a command". For example,
```
$ ls `echo /`
```
will run `echo /`, and pass that as an argument to `ls`, meaning it will eventually run `ls /`. See [this stackoverflow question](https://unix.stackexchange.com/questions/27428/what-does-backquote-backtick-mean-in-commands) for more information.

----
As per
> ```diff
> +if $ZSH_DOTENV_FILE is empty; then
> +  [[ -z $variable ]]
> +else
> +  : ${ZSH_DOTENV_FILE:=.env}
> ```
I think I didn't make myself clear. You should use either one method or the other, not both in an if-else expression. Also, `[[ -z $variable ]]` is the construct to check if `$variable` is empty, so
```zsh
if $ZSH_DOTENV_FILE is empty; then
    [[ -z $variable ]]
```
isn't correct. It should be `[[ -z $ZSH_DOTENV_FILE ]]`:
```zsh
if [[ -z $ZSH_DOTENV_FILE ]]; then
    ZSH_DOTENV_FILE=.env
fi
```

----
Lastly,

> I can't find `Settings` or `Configuration` in the main readme.
> Is it in some other readme.

The section doesn't exist yet, you should create it yourself.

**Comment by arshadkazmi42** [comment]
@mcornella I have sent a PR for this.
Can you also check my changes and README content, whether it makes sense.
