### ISSUE TITLE
no output after bad command when command-not-found plugin is enabled

### ISSUE THREAD

**Issue by lmichelin** [robbyrussell/oh-my-zsh#7583]
Hello !

When the _command-not-found_ plugin is enabled, there is no output after a bad command when no suggestion is available from the plugin.

The screenshot below shows this incorrect behavior: on the left the plugin is disabled and the output is correct, on the right the plugin is enabled and there is no output to inform the user that the command is not found.

![](https://user-images.githubusercontent.com/33673240/52412584-7b868d80-2adf-11e9-82bf-eaccf8ff3a26.png)

Thanks for your feedback!

**Comment by mcornella** [comment]
If you're using Ubuntu, there's an issue with the `command-not-found` package which makes this fail on newer versions of zsh. See https://github.com/robbyrussell/oh-my-zsh/issues/7130 and https://bugs.launchpad.net/ubuntu/+source/command-not-found/+bug/1766068.

**Comment by lmichelin** [comment]
Thanks for your help! I found a temporary fix at #7130.
