### ISSUE TITLE
Virtualenvwrapper conplains unnecesarily

### ISSUE THREAD

**Issue by beruic** [robbyrussell/oh-my-zsh#7588]
I get this error message when I start zsh

    [oh-my-zsh] $WORKON_HOME is not defined so plugin virtualenvwrapper will not work

, but the last commit f461d21de1bd0c1394e57a2e3af69778692e4ba4 made the plugin behave like virtualenvwrapper on Bash, and default to `$HOME/.virtualenvs`.

Am I correct in that this warning should just be removed?
The plugin seems to works just fine.

**Comment by mcornella** [comment]
This only happens if virtualenvwrapper_lazy.sh is found in the path. Make sure you can find it with `which virtualenvwrapper_lazy.sh`.

**Comment by beruic** [comment]
I'm not sure I quite understand what you mean. Do yo mean that it only happens if `virtualenvwrapper_lazy.sh` is _not_ found?

Running `which virtualenvwrapper_lazy.sh` tells me that virtualenvwrapper_lazy.sh not found.

**Comment by mcornella** [comment]
> but the last commit [f461d21](https://github.com/robbyrussell/oh-my-zsh/commit/f461d21de1bd0c1394e57a2e3af69778692e4ba4) made the plugin behave like virtualenvwrapper on Bash, and default to `$HOME/.virtualenvs`.

This behavior only applies if `virtualenvwrapper_lazy` is found in the path. That means that if it isn't found, you have to define `WORKON_HOME` yourself. See #6882 for the reasoning behind that.

**Comment by mcornella** [comment]
Addendum: `WORKON_HOME` is defined only in the case of sourcing the lazy script because it is a requirement. Only in the [full init script](https://bitbucket.org/dhellmann/virtualenvwrapper/src/master/virtualenvwrapper.sh) there is a [fallback if `WORKON_HOME` is not set](https://bitbucket.org/dhellmann/virtualenvwrapper/src/67108f0e2abdda349cb22997612b3e22a9178ab3/virtualenvwrapper.sh#lines-300).

Somehow you've found the virtualenvwrapper script *and* sourced it, given that you don't get a `virtualenvwrapper not found` error, but don't have the `WORKON_HOME` variable set. If that's the case, can you `echo $virtualenvwrapper` to see what script it has loaded, and post it here so I can examine it?

**Comment by beruic** [comment]
Here it is:

    % echo $virtualenvwrapper                                                                                     ~ jk-dev
    /etc/bash_completion.d/virtualenvwrapper

**Comment by mcornella** [comment]
Can you post the content of that file?

**Comment by beruic** [comment]
Yes, I'm on Ubuntu 18.04 LTS and here is the content of the file:

```bash
# bash completion snippet for virtualenvwrapper

USE_FULL=no

if [ "$USE_FULL" = "yes" ]; then
    . /usr/share/virtualenvwrapper/virtualenvwrapper.sh
else
    . /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh
fi
```

Well... It might as well have been just:
```bash
. /usr/share/virtualenvwrapper/virtualenvwrapper_lazy.sh
```

, and since it uses the full path, there has been no reason to put it in `$PATH`.

**Comment by mcornella** [comment]
The problem is it uses the lazy completion, so we can't do anything as a plugin to fix it. I suggest you define `WORKON_HOME` yourself, before OMZ is sourced.

**Comment by beruic** [comment]
That's what I did :)

i noticed that this was marked "not our issue". Why is that?
Shouldn't oh-my-zsh also support the lazy completion?

**Comment by mcornella** [comment]
Happy to explain: the way the plugin found the virtualenvwrapper source script was through: https://github.com/robbyrussell/oh-my-zsh/blob/5aa62461d91546ce1fd5dcc6531569d0e6e6f17f/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh#L25

At this point in the loading logic, we have discarded either sourcing the virtualenvwrapper.sh script or the lazy one, meaning that we don't know whether `/etc/bash_completion.d/virtualenvwrapper` is lazy or not. We would have to know that in all systems, that particular file is the same for us to know that for a particular USE_FULL value it sources the lazy script, and for another it uses the full one. But again, we don't know what's in that file (`/etc/bash_completion.d/virtualenvwrapper`) *for all systems that have it*. So we can't make a distinction and say definitively that it only sources the lazy script.
