### ISSUE TITLE
ddev plugin? 

### ISSUE THREAD

**Issue by tomasnorre** [robbyrussell/oh-my-zsh#7589]
How would you feel about a ddev plugin for oh-my-zsh? 

So that command auto-completion works? 

I would be happy to provide the plugin.

**Comment by KaffDaddy** [comment]
That would be great! Fantastic!

**Comment by kaystrobach** [comment]
There is already a bash autocomplete shipped with ddev, sadly it dies not work with ohmyzsh

**Comment by tomasnorre** [comment]
@rfay Already pointed me in that direction.. 
https://twitter.com/randyfay/status/1094948088941301761

**Comment by mcornella** [comment]
This is the issue to follow then: https://github.com/drud/ddev/issues/327.
