### ISSUE TITLE
Sublime plugin error

### ISSUE THREAD

**Issue by Natetronn** [robbyrussell/oh-my-zsh#7595]
I'm getting the following error after adding the Sublime Plugin in .zshrc and running `source ~/.zshrc `
```
/home/username/.oh-my-zsh/plugins/sublime/sublime.plugin.zsh:36: defining function based on alias `subl'
/home/username/.oh-my-zsh/plugins/sublime/sublime.plugin.zsh:39: parse error near `()'
```
I'm on Ubuntu 18.04.2.

**Comment by mcornella** [comment]
I think that means you have an alias named 'subl' yourself, so the function definition picks up on that alias instead of defining a function named `subl`. Look it up in your zshrc file.

**Comment by Natetronn** [comment]
@mcornella, thanks for the reply. 

I do have aliases in the .zshrc file. Is there not a way to use both the plugin and aliases? For example, `alias ohmyzsh="subl ~/.oh-my-zsh" `

Why is there a conflict if the plugin uses other aliases? https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/sublime#usage

**Comment by mcornella** [comment]
It's a conflict with how the function is defined. If there is an alias of the same name it will run that alias unless there is the `function` keyword before it. We'll fix that.

In the meantime, you can define the `subl` alias after sourcing OMZ. That way you won't trigger the error.

**Comment by mcornella** [comment]
#7715 will fix this.

**Comment by Natetronn** [comment]
Thanks mcornella! 

FYI, my aliases were after sourcing OMZ. However, I moved sourcing OMZ to the top and there was no change.

**Comment by mcornella** [comment]
Can you test my changes and see if everything works correctly?

**Comment by Natetronn** [comment]
I ran `upgrade_oh_my_zsh` again, added `sublime` to the list of plugins. Unfortunately I'm still getting the same errors.

**Comment by Natetronn** [comment]
Do I need to manually update the file?

**Comment by Natetronn** [comment]
Okay, yes, that seems to have fixed the above errors.
