### ISSUE TITLE
Completion with ". <TAB>" should work like with "source <TAB>"

### ISSUE THREAD

**Issue by RafalSkolasinski** [robbyrussell/oh-my-zsh#7596]
As it is not uncommon to use single dot instead of ``source`` it would be nice if completion for it would work the same. For example
```
source <TAB>
```
triggers completion with folders / files in current directory.
In bash the same goes for 
```
. <TAB>
```

However, it does not seem to work in ZSH with oh-my-zsh. 
Am I missing something?

**Comment by mcornella** [comment]
The `source` and `.` (dot) builtins work slightly differently. See the [documentation for `.`](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-_002e) and [for `source`](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-source).

If you want `.` to behave like `source`, _i.e._ to search in the current directory first, add `./` to the file argument.

Either way, this is a zsh issue, not an Oh My Zsh one. I hope that helped you understand it better.
