### ISSUE TITLE
After installing oh-my-zsh on the server, cannot connect to this server by the software such as transmit or fillzila (macOS)

### ISSUE THREAD

**Issue by zjgbz** [robbyrussell/oh-my-zsh#7598]
I just installed oh-my-zsh on the HPC of the university. But I found that my laptop with macOS sierra cannot login this server by the software such as fillzila or transmit while I can still login from terminal via ssh. On the other hand, my PC can still login this server via both gitbash or winscp. It is needed for me to work on both laptops, but also, I really do not want to uninstall oh-my-zsh. Has anyone met such kind of issue and may I have your suggestions? Thank you in advance.

Best regards,
zjgbz

**Comment by zjgbz** [comment]
one more issue: on my PC, I can login via ssh on gitbash, but I CANNOT login via winscp. So it looks like after installing on-my-zsh on the server, such kinds of software cannot login the corresponding server.

**Comment by jjangga0214** [comment]
Was you able to use ftp (filezilla is a program for ftp protocol) before installing oh-my-zsh?
If you haven't, the issue, at least to filezilla issue, might be merely due to lack of ftp program on the server.

**Comment by mcornella** [comment]
Comment the line that sources OMZ in the `.zshrc` file (right after the `plugins=()` definition) and try again. If it still doesn't work, it's a problem of having changed the shell to zsh. You can change back to whatever shell you were using before with `chsh -s $(which <the-shell-you-used>)`.
