### ISSUE TITLE
How to fix ohmyzsh startup error

### ISSUE THREAD

**Issue by delmarocks** [robbyrussell/oh-my-zsh#7602]
Here is the error when i open my console and oh-my-zsh as default shell
zsh: done       echo |
zsh: abort

**Comment by mcornella** [comment]
Can you post your .zshrc file?

**Comment by shuhaowu** [comment]
I see this while using termux.

**Comment by mcornella** [comment]
Without more information we can't do anything. Does this happen when running `zsh` manually as well or only when first opening the console? What are the contents of your `.zshrc` file?

**Comment by aprilahijriyan** [comment]
Hi, I am also experiencing the same thing. I experienced this in the termux application, first I installed zsh, this is fine. However, when I install oh-my-zsh, and then I change the default shell to zsh. And oh-my-zsh displays a message like:

```
zsh: done echo | zsh: abort
```

And then, I quit zsh, then I re-entered zsh, and zsh displays the message:
```
# zsh
zsh: done echo |
zsh: suspended (signal)
[6] + done echo | abort
```
Please help.

**Comment by mcornella** [comment]
How did you set zsh as the default shell?

**Comment by aprilahijriyan** [comment]
I only press "Y" when oh-my-zsh asks a question.

**Comment by mcornella** [comment]
In my tests the install script can't actually set zsh as the default shell, I can't really reproduce the error.
