### ISSUE TITLE
The aplay alias in ansible plugin overrides existing aplay command line sound recorder

### ISSUE THREAD

**Issue by dimisjim** [robbyrussell/oh-my-zsh#7604]
Basically what the title says.

@deepan10 

https://linux.die.net/man/1/aplay
https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/ansible#aliases

**Comment by deepan10** [comment]
@dimisjim this bug has been fixed with pull request https://github.com/robbyrussell/oh-my-zsh/pull/7617
