### ISSUE TITLE
_zsh_highlight_call_widget error after update

### ISSUE THREAD

**Issue by mjsteinbaugh** [robbyrussell/oh-my-zsh#7611]
I just ran an update on oh-my-zsh, and now I'm seeing this error pop up in the terminal:

```
_zsh_highlight_call_widget:2: _main_complete: function definition file not found
```

Any advice on how to track this down? I'm not seeing anything obvious in my `.oh-my-zsh` directory.

**Comment by mjsteinbaugh** [comment]
This issue seems to be related to the `zsh-syntax-highlighting`plugin.

**Comment by turkeyphant** [comment]
Same issue here, do we have a fix?
