### ISSUE TITLE
tab completes moves to wrong line

### ISSUE THREAD

**Issue by gwoplock** [robbyrussell/oh-my-zsh#7618]
I've only got this issue on my MacBook pro. On my arch linux box with basically the same rc it works perfectly.  Here is the prompt pre-tab complete: 
```
#( 02/24/19@12:24PM )( garrettbattaglia@Garretts-MacBook-Pro ):~ 
   nano 
```

after: 
```
#( 02/24~/.oh-my-zshloadrcrettbattaglia@Garretts-MacBook-Pro ):~ 
   nano
```

as you can see the completion  is on the line above. 

[zshrc](https://gist.github.com/gwoplock/4d4869cf64268b43cd951543237d4eec)

**Comment by mcornella** [comment]
This is very possibly already documented in [issues about multiline prompts](https://github.com/robbyrussell/oh-my-zsh/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+multiline). It might be related to `COMPLETION_WAITING_DOTS` even. Please confirm.

**Comment by gwoplock** [comment]
commenting out COMPLETION_WAITING_DOTS seems to have fixed it. Thanks.
