### ISSUE TITLE
What is the correct way to show some env var in PROMPT?

### ISSUE THREAD

**Issue by andyzasl** [robbyrussell/oh-my-zsh#7627]
Hi!
In my work I need to fast switch KUBECONFIG variable, and I'd like to have it as a part of my PROMPT.
My current PROMPT looks like:
```
local⎈ az@host ~/projects$
```
The local - is the name of file-profile and it's the value of KUBECONFIG env var.
everything looks like fine, until I try to do some tab-autocompletions.
For example, when I type 'ls' and press 'tab' I see:
```local⎈ az@host /tmp$ ls        ls
ssh-sx6ma6bEUvfn
```

```
precmd() {
  kubecfg=$(echo "$KUBECONFIG" | cut -d '/' -f 5)
}

img=$(echo "\u2388")
kube="$fg[red]"'${kubecfg}'"$fg[blue]${img}"

PROMPT="${kube} ${user} ${pwd}$ "
```

I know that I have to use %{ %} , but I failed to modify my there for this :( 
Could you help me?

**Comment by mcornella** [comment]
You don't need the `precmd` function, you can define a prompt function that computes what you now have in the `$kube` variable, and put the call to that prompt function in your `$PROMPT` variable, in single quotes, like so:

```
your_prompt_function() {
  kubecfg=$(echo "$KUBECONFIG" | cut -d '/' -f 5)
  img=$(echo "\u2388")
  echo "%{$fg[red]%}${kubecfg}%{$fg[blue]%}${img}"
}
PROMPT='$(your_prompt_function) ${user} ${pwd}$ "
```

The `%{%}` escaping sequences are needed for characters that don't occupy screen space, like color sequences.

**Comment by andyzasl** [comment]
The final solution. 
Note, that value of KUBECONFIG might be changed while shell is alive.
`prompt_kubecfg() {
  kubecfg=$(echo "$KUBECONFIG" | cut -d '/' -f 5)
  img=$(echo "\u2388")
  echo "%{$fg[red]%}${kubecfg}%{$fg[blue]%}${img}"
}
PROMPT='$(prompt_kubecfg)'" ${user} ${pwd}$ "`
