### ISSUE TITLE
yarn completion invalid

### ISSUE THREAD

**Issue by dc3671** [robbyrussell/oh-my-zsh#7628]
1a657c6c4d44dbfcffb4c633a58e623f4d692706 add a split file containing completion scripts. But it's invalid for me. And if I combine this file into the original `.zsh` file, everything works fine. Should I commit a fix to do that?

**Comment by mcornella** [comment]
If it only works if you put it in the `plugin.zsh` file, just run `rm ~/.zcompdump*` and restart the shell to reset the completion cache.
