### ISSUE TITLE
Disable url escaping in quotes strings

### ISSUE THREAD

**Issue by madcapnmckay** [robbyrussell/oh-my-zsh#7632]
Version: `zsh 5.3 (x86_64-apple-darwin18.0)`

When I paste `http://foo.com?bar=baz` into the shell I instead get `http://foo.com\?bar\=baz`.

This happens even if am pasting into a quoted string. This is breaking some utils I use that expect an unescaped string url as a param.

I've tried commenting out the lines in `~/.oh-my-zsh/lib/misc.zsh` that run `bracketed-paste-magic` and `url-quote-magic` plugins, even after a restart I still see the issue.

I use antigen for loading OMZ and can confirm that it is indeed OMZ that causes the issue by simply commenting out the load of that bundle in `.zshrc`.

Has anyone else experienced this problem?

Below is my `.zshrc`

```
ANTIGEN_MUTEX=false

source /Users/imckay/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles

antigen bundle lukechilds/zsh-better-npm-completion
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle smallhadroncollider/antigen-git-rebase

# Load the theme.
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  dir
  virtualenv
  rust
  git
  cmd_exec_time
)

# Tell Antigen that you're done.
antigen apply

# User configuration

# SSH
export SSH_KEY_PATH="~/.ssh/id_rsa"
export EDITOR='subl -w'

# N Configuration

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
```

**Comment by mcornella** [comment]
After the latest update (run `upgrade_oh_my_zsh`), you can add `DISABLE_MAGIC_FUNCTIONS=true` to your zshrc (before OMZ is sourced) to bypass the loading of the magic functions.

**Comment by Shaked** [comment]
Hey, 

I have the latest oh-my-zsh installed (4e45e12d) using macos latest version, iTerm latest version. 

My `.zshrc` contains 

```
....
DISABLE_MAGIC_FUNCTIONS=true
source $ZSH/oh-my-zsh.sh
....
```

After running `source ~/.zshrc` I still can't paste URLs normally as they are being escaped same as in the original example 

> When I paste http://foo.com?bar=baz into the shell I instead get http://foo.com\?bar\=baz.

Any idea what am I missing? 

Thank you! 
Shaked

**Comment by mcornella** [comment]
Did you try restarting the terminal (or the zsh session with `exec zsh`)?

**Comment by Shaked** [comment]
`exec zsh` worked! thank you and sorry for the mess :)

**Comment by devnoname120** [comment]
> This happens even if am pasting into a quoted string.

Anyone found a way to fix this issue?
