### ISSUE TITLE
wsimport does not work 

### ISSUE THREAD

**Issue by vihanga-liyanage** [robbyrussell/oh-my-zsh#7636]
Not sure if this was already addressed. If yes please close this.
### Steps to reproduce
- When I try to execute the below command, following error logs by the zsh.
- Command:
  ```wsimport https://www.w3schools.com/xml/tempconvert.asmx?WSDL```
- Output
  ```zsh: no matches found: https://www.w3schools.com/xml/tempconvert.asmx?WSDL```

I was able to execute the same command in regular bash without any errors.

**Comment by mcornella** [comment]
You need to quote the URL because the question mark is interpreted as a glob character:
```
wsimport "https://www.w3schools.com/xml/tempconvert.asmx?WSDL"
```
