### ISSUE TITLE
Weird website completion

### ISSUE THREAD

**Issue by fengwang** [robbyrussell/oh-my-zsh#7640]
Under my terminal, the tab completion for `cp fig` is

```
fighly.com                   fightguard.net               fightperfect.net             figlobal.112.2o7.net         figurequarter.net                                       
fightagent.ru                fighting-poverty.org         fightpower.net               figurative.flowtemp.ro                                                             
fightanger.net               fightline.us.intellitxt.com  fightreport.net              figurefamous.net  
```

Is this intended behavior or something wrong with the configuration? I have `archlinux`, `git` and `python` plugin enabled.

**Comment by mcornella** [comment]
This looks like it's using the entries in `/etc/hosts` to suggest hosts, but it shouldn't do that for the `cp` command... What do `which -a cp` and `echo $_comps[cp]` show?

**Comment by fengwang** [comment]
My `cp` is an alias to `/usr/bin/rsync -a --stats --progress` and I have more than 100K blacklisted ads website (see https://github.com/fengwang/hosts-100k/blob/master/hosts) in my `/etc/hosts`. Could this be the reason? I noticed the completion works well when explicitly calling `/bin/cp`. And, is there any solution for `rsync`?

> This looks like it's using the entries in `/etc/hosts` to suggest hosts, but it shouldn't do that for the `cp` command... What do `which -a cp` and `echo $_comps[cp]` show?

**Comment by fengwang** [comment]
fixed by appending 
```
zstyle ':completion:*' hosts off
```
to my `~/.zshrc`
