### ISSUE TITLE
idea for colored-man-pages

### ISSUE THREAD

**Issue by robgal519** [robbyrussell/oh-my-zsh#7648]
Hi, 
I use colored-man-pages, and I recently installed man pages for cppreferance.com [pages](https://github.com/jeaye/stdman). In those pages there is section called "Example". It would be nice if this section would have syntax highlight.

**Comment by mcornella** [comment]
`colored-man-pages` should pick up the header correctly as long as the man page is formatted correctly. There may be some man pages incorrectly formatted (see https://github.com/jeaye/stdman/issues/2), but that's not an issue with `colored-man-pages`. Here's a sample from looking at `std::string::empty`:

![screenshot](https://user-images.githubusercontent.com/1441704/55836679-82ea0780-5b1f-11e9-9ce8-659bfdb824a6.png)
