### ISSUE TITLE
Bira theme curved character issue

### ISSUE THREAD

**Issue by rapsaGnauJ** [robbyrussell/oh-my-zsh#7651]
I don't know if this is the right place to post this issue. Forgive me if it's not.

The character(s) on the left side aren't aligned on my desktop computer. Maybe the cause of the problem is a 4k display or a non integer kde interface scale as this is the cause to some other issues with konsole.
I attach two images of the issue, one with the font size that I usually use and the other with a ver big font size.
![Screenshot_20190312_203811](https://user-images.githubusercontent.com/24842781/54230821-8631a980-4507-11e9-8a51-db5d626b0967.png)
![Screenshot_20190312_203754](https://user-images.githubusercontent.com/24842781/54230903-b416ee00-4507-11e9-977e-550551b874f8.png)

Edit: I uploaded the same image twice by mistake.

**Comment by mcornella** [comment]
Try to change the font or try different terminal emulators to see if the issue is still there, then submit the bug wherever it's appropriate (if this only happens with a specific font, or if it happens only with a specific terminal emulator, find the website where to submit an issue).
