### ISSUE TITLE
Maximized terminal window height shrinks on tab close on mac

### ISSUE THREAD

**Issue by talsaiag** [robbyrussell/oh-my-zsh#7652]
On mac, when maximized: Closing a tab (out of two), returning down to a single tab shrinks the height of the terminal window by the size of the (no-longer visible) tab strip height.
Expected: window height should remain the same - maximized.
Note: this also happens when the terminal window is not maximized but the issue is noticeable mostly when it is maximized.

**Comment by mcornella** [comment]
This is not an issue with OMZ but with your terminal emulator.
