### ISSUE TITLE
[New theme] Bundle Powerlevel10k?

### ISSUE THREAD

**Issue by romkatv** [robbyrussell/oh-my-zsh#7654]
Would you be interested in bundling [Powerlevel10k](https://github.com/romkatv/powerlevel10k) theme? It's a reimplementation of the popular Powerlevel9k theme -- a drop-in replacement that renders the same prompt given the same configuration options. It's 10-100 times faster though. Powerlevel10k has carefully optimized formatting code but its biggest advantage is a novel approach to querying status of git repositories--[gitstatus](https://github.com/romkatv/gitstatus)--which is also available as a standalone plugin. This makes Powerlevel10k much faster than any other theme that shows git information. Give it a try to see for yourself.

**Comment by romkatv** [comment]
I guess that's a no.

**Comment by OvermindDL1** [comment]
I'd personally find this quite nice!

**Comment by mcornella** [comment]
[We can't accept more themes](https://github.com/robbyrussell/oh-my-zsh#do-not-send-us-themes). Please make a separate repo with your theme and link to it from the [external themes](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) wiki page.

You can also add your theme as a custom theme. See [customization](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes) for instructions.

**Comment by romkatv** [comment]
@mcornella Thank you for taking the time to reply.
