### ISSUE TITLE
keybinding ESC-l overwrites word downcase

### ISSUE THREAD

**Issue by XL64** [robbyrussell/oh-my-zsh#7658]
This commit https://github.com/robbyrussell/oh-my-zsh/commit/55a9d685fd960390a4f400ac461d901049a78beb breaks the ESC-l keybinding to downcase word.

**Comment by tkstorm** [comment]
I have the same problem!!

vim ~/.zshrc

# bindkey
bindkey "^U"    backward-kill-line
bindkey "^u"    backward-kill-line
bindkey "^[l"   down-case-word
bindkey "^[L"   down-case-word

**Comment by mcornella** [comment]
This has been there for years (https://github.com/robbyrussell/oh-my-zsh/commit/f7708d4181374cfbd223e071f7253018f28e5509) so I don't think we can get rid of it without breaking backwards-compatibility. You can just redefine it yourself in your zshrc file.
