### ISSUE TITLE
Parse error when trying to configure themes

### ISSUE THREAD

**Issue by tlillenuit** [robbyrussell/oh-my-zsh#7661]
I am trying to customize my .zshrc. I am getting this error when trying to source .zshrc

```
/home/tlil/.oh-my-zsh/oh-my-zsh.sh:34: parse error near `${ZSH_CUSTOM}/lib/*z...'
```

Line 34 of ~/.oh-my-zshrc and surrounding lines:

```
for config_file ${ZSH_CUSTOM}/lib/*zsh; do        # (My comment): This is line 34
  custom_config_file="${ZSH_CUSTOM}/lib/${config_file:t}"
  [ -f "${custom_config_file}" ] && config_file=${custom_config_file}
  source $config_file
done
```

My .zshrc

```
export ZSH=$HOME/.oh-my-zsh
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git zsh-syntax-highlighting zsh-auto-completion colored-man-pages)

export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
source /home/tlil/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /home/tlil/.oh-my-zsh/oh-my-zsh.sh
```

**Comment by mcornella** [comment]
This is probably an issue with line endings, see https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351.

**Comment by tlillenuit** [comment]
Hm... I applied suggested fix but the issue seems to continue its stubborness, although I am able to change between various themes this time.

`autoload: command not found
bash: /home/tlil/.oh-my-zsh/oh-my-zsh.sh: line 34: syntax error near unexpected token `('
bash: /home/tlil/.oh-my-zsh/oh-my-zsh.sh: line 34: `for config_file ($ZSH/lib/*.zsh); do'

BTW i am not using cywin or anything like that, just pure UNIX :)`

**Comment by mcornella** [comment]
You're using bash I think

**Comment by tlillenuit** [comment]
You were right. I switch over to bash ( only temporarily though ;-) ) while trying to fix this issue. Swinging back and rebooting seems to have done the trick. Thank you mcornella!
