### ISSUE TITLE
Error updating with index

### ISSUE THREAD

**Issue by obelix1502** [robbyrussell/oh-my-zsh#7666]
When open a terminal I've this oh-my-zsh's error : 
`   upgrade_oh_my_my_zsh
Updating Oh My Zsh
error: shoot with an impossible reline: your index contains unconfirmed changes.
error: please validate or store them. 
(it's a translation)
`
So, what can I do to resolve it ?

**Comment by mcornella** [comment]
You have made changes to the OMZ repository. Either commit them with `git add -A; git commit` or delete them with `git reset --hard HEAD`, then attempt to upgrade again. You can view the changes you've made with `git status`.
