### ISSUE TITLE
cd history broken

### ISSUE THREAD

**Issue by magnus-gross** [robbyrussell/oh-my-zsh#7667]
Usually, I can use `cd -NUMBER` to navigate to one of the last directories.
For some time now, the autocompletion when pressing Tab after - seems to be broken, see the following example, where I choose to `cd` back to the home directory, but it actually goes back to `/etc`.

https://asciinema.org/a/7Y8tZEsa6IjDWU02B5KmiEZOL

Happening on latest oh-my-zsh with zsh 5.7.1

**Comment by roel0** [comment]
I have a sort like issue since a few weeks, when multiple history entries are present, zsh will always pick the first one ( so cd -4 == cd -1)

**Comment by magnus-gross** [comment]
Is it maybe a zsh bug and not a oh-my-zsh bug?

**Comment by mcornella** [comment]
Can you both post the output of `setopt`?

**Comment by magnus-gross** [comment]
@mcornella 

```bash
alwaystoend
autocd
autopushd
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
longlistjobs
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
```

**Comment by mcornella** [comment]
I can't reproduce your issue, but seeing your asciinema recording, it's as if `pushdminus` is set but the completion doesn't know it. Are you sure you're using zsh 5.7.1? I can't reproduce it on the docker image.

**Comment by magnus-gross** [comment]
Yes, I am sure about the version, maybe I have got the order that I load the plugins in wrong?

You can see my configuration here: https://github.com/magnus-gross/dotfiles/blob/master/zsh/.zshplug

**Comment by mcornella** [comment]
This happens to me too with your zshrc file. If I comment out zsh-autosuggestions it stops happening, so that has to be the culprit.

I also verified that having that enabled and OMZ disabled it still happens, so it isn't OMZ at fault.
