### ISSUE TITLE
how do I see glyphs on console only Linux (example: Ubuntu server edition)?

### ISSUE THREAD

**Issue by mrjayviper** [robbyrussell/oh-my-zsh#7668]
So I have installed ZSH + oh-my-zsh + powerlevel9k on my Ubuntu server edition.

While it's working including the colors (I used darkorange background to display current user), I cannot get the glyphs to work. In place of the home folder icon (enter image description here) when I'm on the user home folder, all I see is a triangle.

I'm guessing this problem is not specific to powerlevel9k but any theme that uses glyphs?

Can someone please advice how this can be fixed?

Thanks

**Comment by AlexeyDemidov** [comment]
You probably want to use Powerline font for linux console https://github.com/powerline/fonts/tree/master/Terminus/PSF

**Comment by mcornella** [comment]
See https://github.com/bhilburn/powerlevel9k#installation
This is not a OMZ issue.
