### ISSUE TITLE
Allow configuring/disabling default key bindings

### ISSUE THREAD

**Issue by yevgenyz** [robbyrussell/oh-my-zsh#7669]
Allow configuring and/or disabling default key bindings that are defined in key-bindings.zsh.

For example the default behavior of [Esc-L] => convert the word to lower case (like [Esc-U] => upper case]) is being overwritten to ls command unconditionally, which leaves to upper case conversion as is, but disables its sibling.

**Comment by mcornella** [comment]
You can just redefine the key bindings you want in your zshrc file. See https://github.com/robbyrussell/oh-my-zsh/issues/7658#issuecomment-476305197
