### ISSUE TITLE
compdef: unknown command or service: rails 

### ISSUE THREAD

**Issue by denisoster** [robbyrussell/oh-my-zsh#7672]
I use [asdf](https://github.com/asdf-vm/asdf)
`compdef: unknown command or service: rails`

**Comment by mcornella** [comment]
Post your zshrc file.

**Comment by denisoster** [comment]
@mcornella [.zsh](https://gist.github.com/denisoster/d4524eac85b8654ce8cd901a6388cc94)

**Comment by mcornella** [comment]
You shouldn't call compinit again, ohmyzsh does it for you. But I don't think that's the issue. Try `rm ~/.zcomdpump*` and restart the terminal, see if that helps.

**Comment by denisoster** [comment]
@mcornella  thx
