### ISSUE TITLE
[Plugin] Terraform not working after migration to new pc

### ISSUE THREAD

**Issue by nlarzon** [robbyrussell/oh-my-zsh#7683]
I have updated from Ubuntu 16.04 to 18.04 and after the fresh install the terraform plugin stopped working.

terraform version 0.11.13
I have the same .zshrc file all other plugin are working fine, how do I trace the error?

nothing in /.oh-my-zsh/log

**Comment by nlarzon** [comment]
Solved by removing zshdump.

**Comment by 255255255225** [comment]
Terraform plugin does not work for me on a 18.04 fresh install. (Also some other plugins like scw do not work)
What's the zshdump thing? (can't find it -- not sure what to remove)
