### ISSUE TITLE
Warning: plugin cargo not found

### ISSUE THREAD

**Issue by Avi-D-coder** [robbyrussell/oh-my-zsh#7685]
I belive it caused by https://github.com/robbyrussell/oh-my-zsh/pull/7679. Completions still work, but both `rust` and `cargo` trigger the error.

**Comment by joeky888** [comment]
`Warning: plugin docker not found`

Same here.

**Comment by shirishkz** [comment]
```
Warning: plugin celery not found
Warning: plugin docker not found
Warning: plugin redis-cli not found
Warning: plugin rust not found
Warning: plugin scala not found
Warning: plugin terminator not found
Warning: plugin ufw not found
Warning: plugin vagrant not found
```
Same problem here

**Comment by Avi-D-coder** [comment]
I found the issue will send a pr.

**Comment by sfpmld** [comment]
Same for me : warning on docker plugin not found. Seems like those plugins have lost the .plugin.zsh file

**Comment by davibusanello** [comment]
Same here for:
```
Warning: plugin completion not found
Warning: plugin docker not found
Warning: plugin nodejs not found
Warning: plugin wakatime not found
Warning: plugin mix not found
```

**Comment by pfdiy** [comment]
Same here for:
>Warning: plugin zsh-syntax-highlighting not found
>Warning: plugin zsh-autosuggestions not found

**Comment by chuckstar76** [comment]
For:

- Warning: plugin zsh-autosuggestions not found
- Warning: plugin zsh-completions not found
- Warning: plugin zsh-syntax-highlighting not found

[There may be more...]

Think the use of Homebrew as a plugin source should also be taken into account.

See - [brew.plugin.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh)

> With the advent of their 1.0 release, Homebrew has decided to bundle
> the zsh completion as part of the brew installation, so we no longer
> ship it with the brew plugin; now it only has brew aliases.

````
/usr/local/cellar/zsh-*
````

**Comment by pfdiy** [comment]
> For:
> 
> * Warning: plugin zsh-autosuggestions not found
> * Warning: plugin zsh-completions not found
> * Warning: plugin zsh-syntax-highlighting not found
> 
> [There may be more...]
> 
> Think the use of Homebrew as a plugin source should also be taken into account.
> 
> See - [brew.plugin.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh)
> 
> > With the advent of their 1.0 release, Homebrew has decided to bundle
> > the zsh completion as part of the brew installation, so we no longer
> > ship it with the brew plugin; now it only has brew aliases.
> 
> ```
> /usr/local/cellar/zsh-*
> ```

What we said is not a problem?

**Comment by Avi-D-coder** [comment]
@chuckstar76 I'm on Linux without a way of testing #7686 with brew. if you or someone else is still getting erroneous warnings with #7686 please send a PR to  https://github.com/Avi-D-coder/oh-my-zsh/tree/plug-not-found-fix or add suggestion to #7686

**Comment by chuckstar76** [comment]
@Avi-D-coder - yup OK - will give a go.

**Comment by jedipunkz** [comment]
same here for:

```
Warning: plugin vagrant not found
```

**Comment by Avi-D-coder** [comment]
@jedipunkz Are you upto date?
`upgrade_oh_my_zsh`
#7686 should have fixed it.

**Comment by Alienover** [comment]
```bash
Warning: plugin git, not found
```
Actually, run `upgrade_oh_my_zsh` 2 hours ago. The warning is still here.

**Comment by mcornella** [comment]
Zsh arrays use spaces to separate entries, the comma isn't necessary.

**Comment by vkaracic** [comment]
Removing the comma at the end of `git` solved it for me, thank you @mcornella !
Went from:
```

**Comment by Alienover** [comment]
@vkaracic Really!! That works!!Thanks a lot, and also @mcornella !!

**Comment by thomasbisignani** [comment]
GG @vkaracic :+1:

**Comment by luismilanese** [comment]
Just in case you don't know the file you're supposed to edit in order to make it work: it's the .zshrc file, usually located in your home directory.

**Comment by ThomasJunk** [comment]
> Zsh arrays use spaces to separate entries, the comma isn't necessary.
Thanks @mcornella - works fine!

But why did it work until now in the first place?
Until today's update zsh never complained?

**Comment by mcornella** [comment]
It didn't work, you just didn't know it.

**Comment by ThomasJunk** [comment]
> Until today's update zsh never complained?
Ah, I see ... that's the problem :]
