### ISSUE TITLE
Warning: plugin docker not found

### ISSUE THREAD

**Issue by kleinjm** [robbyrussell/oh-my-zsh#7687]
Just updated to the latest oh-my-zsh by pulling master and am getting the following warning  now when starting a new shell.
```
Warning: plugin docker not found
```
Here's my list of plugins inside my `.zshrc` as well as the entire file.
https://github.com/kleinjm/dotfiles/blob/9bef8f127ac41adf9959d9d2af53f5547a0600a1/shared/.zshrc#L63

I've made no other changes and can see the plugin in the right dir.
```
➜  .oh-my-zsh master > ls plugins/docker
total 256
drwxr-xr-x    4 jamesklein  staff   128B Mar 22 08:54 ./
drwxr-xr-x  262 jamesklein  staff   8.2K Mar 22 08:54 ../
-rw-r--r--    1 jamesklein  staff   169B Mar 22 08:53 README.md
-rw-r--r--    1 jamesklein  staff   123K Mar 22 08:54 _docker
```

**Comment by dhohengassner** [comment]
facing this issue as well - docker plugin is working anyway

looks like this is a bit too sensitive https://github.com/robbyrussell/oh-my-zsh/commit/779ff24c2d0091ebbddae938d12b3f117123fc29
