### ISSUE TITLE
Warning: plugin zsh-syntax-highlighting not found

### ISSUE THREAD

**Issue by pfdiy** [robbyrussell/oh-my-zsh#7688]
### mac 10.14.3

Just updated to the latest oh-my-zsh by pulling master and am getting the following warning now when starting a new shell.
```
     Warning: plugin zsh-syntax-highlighting not found
     Warning: plugin zsh-autosuggestions not found

**Comment by chuckstar76** [comment]
As described in #7690 user may have ZSH plugins installed by other tools (e.g. Homebrew) and are not sourced in $ZSH/plugins.
These should not be referenced inside plugins=(...) within the .zshrc

**Comment by XiangNanLi** [comment]
I solve it by the command :

'''
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
'''

on-my-zsh check if the plugin is exit at '$base_dir/plugins/$name/$name.plugin.zsh'  or '$base_dir/plugins/$name/_$name' , so the plugin should be at this path .

**Comment by pfdiy** [comment]
> autosuggestions

我在插件列表中 去掉 autosuggestions和zsh-syntax-highlighting,但是结果也是可以使用的.不解~~~

**Comment by chuckstar76** [comment]
To be fair [zsh-users](https://github.com/zsh-users)
has proper installation instructions depending on OS for each of those plugins...

- https://github.com/zsh-users/zsh-syntax-highlighting - [install.md](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)
- https://github.com/zsh-users/zsh-completions - [readme.md](https://github.com/zsh-users/zsh-completions/blob/master/README.md)
- https://github.com/zsh-users/zsh-autosuggestions - [install.md](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md)
- https://github.com/zsh-users/zsh-history-substring-search - [readme.md](https://github.com/zsh-users/zsh-history-substring-search/blob/master/README.md)

You need to follow your preferred options for your OS / package manager etc.

**Comment by mimoo** [comment]
I followed the `oh-my-zsh` instructions to install it and same thing, a few days ago I started having this warning.

**Comment by ujuc** [comment]
Later, I guess I'll come back and watch this eagle.

You can remove the plugin from the `oh-my-zsh` plugin.

In case of me, I installed the plugins using `zplug`, but in `oh-my-zsh`, I could not find the plugins installed with `zplug` and I got an error.

So I removed the `oh-my-zsh` plugin entry from `.zsh`.

https://github.com/ujuc/dotrc/commit/e2537072f7ee3fec4cd3c49afc3a06f0c60a3be1

**Comment by newtorob** [comment]
I am still having this issue, I followed the install instructions but currently getting plugin not found prompt.

**Comment by mcornella** [comment]
Where did you install it, where's the zsh-syntax-highlighting directory? Did you spell correctly the plugin name?

**Comment by metawops** [comment]
Having the same problem here on my Raspberry Pi 4.
After `sudo apt-get install zsh-syntax-highlighting` I found that the package was not installed in my `.oh-my-zsh/custom/plugins` folder but instead here:
```
pi@raspberrypi  ~  dpkg -L zsh-syntax-highlighting
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/zsh-syntax-highlighting
/usr/share/doc/zsh-syntax-highlighting/README.Debian
/usr/share/doc/zsh-syntax-highlighting/README.md
/usr/share/doc/zsh-syntax-highlighting/all.md.gz
/usr/share/doc/zsh-syntax-highlighting/changelog.Debian.gz
/usr/share/doc/zsh-syntax-highlighting/changelog.gz
/usr/share/doc/zsh-syntax-highlighting/copyright
/usr/share/doc/zsh-syntax-highlighting/highlighters
/usr/share/doc/zsh-syntax-highlighting/highlighters/brackets.md
/usr/share/doc/zsh-syntax-highlighting/highlighters/cursor.md
/usr/share/doc/zsh-syntax-highlighting/highlighters/line.md
/usr/share/doc/zsh-syntax-highlighting/highlighters/main.md
/usr/share/doc/zsh-syntax-highlighting/highlighters/pattern.md
/usr/share/doc/zsh-syntax-highlighting/highlighters/root.md
/usr/share/doc/zsh-syntax-highlighting/highlighters.md
/usr/share/zsh-syntax-highlighting
/usr/share/zsh-syntax-highlighting/.revision-hash
/usr/share/zsh-syntax-highlighting/.version
/usr/share/zsh-syntax-highlighting/highlighters
/usr/share/zsh-syntax-highlighting/highlighters/brackets
/usr/share/zsh-syntax-highlighting/highlighters/brackets/brackets-highlighter.zsh
/usr/share/zsh-syntax-highlighting/highlighters/cursor
/usr/share/zsh-syntax-highlighting/highlighters/cursor/cursor-highlighter.zsh
/usr/share/zsh-syntax-highlighting/highlighters/line
/usr/share/zsh-syntax-highlighting/highlighters/line/line-highlighter.zsh
/usr/share/zsh-syntax-highlighting/highlighters/main
/usr/share/zsh-syntax-highlighting/highlighters/main/main-highlighter.zsh
/usr/share/zsh-syntax-highlighting/highlighters/pattern
/usr/share/zsh-syntax-highlighting/highlighters/pattern/pattern-highlighter.zsh
/usr/share/zsh-syntax-highlighting/highlighters/root
/usr/share/zsh-syntax-highlighting/highlighters/root/root-highlighter.zsh
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

Now, should I manually move/copy that over to the correct location in my `~/.oh-my-zsh` folder or is there a *correct* way to install such a plugin?

**Comment by mcornella** [comment]
I think as long as you add
```zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
somewhere in your zshrc file you'll be good to go. [The INSTALL doc should cover that](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md). Better ask over there next time though.

**Comment by metawops** [comment]
> I think as long as you add
> 
> ```shell
> source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> ```
> 
> somewhere in your zshrc file you'll be good to go. [The INSTALL doc should cover that](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md). Better ask over there next time though.

Thanks & yes, this works. But being able to just include this with the other plugins and thus using the normal syntax would be nice. 🤷‍♂️

**Comment by mcornella** [comment]
[There's a separate section for including it with OMZ without having to install it with `apt`](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh).

**Comment by metawops** [comment]
> [There's a separate section for including it with OMZ without having to install it with `apt`](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh).

Awesome! Don’t know how I missed this!

**Comment by liuyaox** [comment]
For me, 

Reason: 

1. `zsh-syntax-highlighting` was installed by other tools (for me, homebrew), so there is not 'zsh-syntax-highlighting' folder in path '~/.oh-my-zsh/custom/plugins/' or other path like that. 

2. There is a line `plugins=(git zsh-syntax-highlighting)` in ~/.zshrc, so when terminal starts, it searches for 'zsh-syntax-highlighting' in path as described above.

Solution: 

As I have tested, both are OK, and you can choose one of them

1. `git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting`

2. Remove the line `plugins=(git zsh-syntax-highlighting)` in ~/.zshrc

Notes: 

Solution 2 is elegant and recommended, because solution 1 means that you install the plugin twice, one by homebrew, and one by manually

**Comment by katiechina** [comment]
I use the second method mentioned above, and it solve my issue.
             **Remove the line plugins=(git zsh-syntax-highlighting) in ~/.zshrc**
The only difference is that there are several plugins inside the (), I only remove zsh-syntax-highlighting, but keep the other plugins. 
Here is the detailed step in the terminal in case anyone want to know how to do:
1. vim ~/.zshrc
2. inside vim, press i , enter insert mode
3. remove zsh-syntax-highlighting from the plugins
4. enter Esc
5. enter :wq  to save and escape from vim
Now you can open a new terminal use command + T, and the annoying warning is not showing anymore.

**Comment by gerald0x01** [comment]
> I solve it by the command :
> 
> '''
> git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
> git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
> '''
> 
> on-my-zsh check if the plugin is exit at '$base_dir/plugins/$name/$name.plugin.zsh' or '$base_dir/plugins/$name/_$name' , so the plugin should be at this path .

Thanks! It's working.

**Comment by imajinyun** [comment]
If you used `brew` to install `zsh-syntax-highlighting`, you need to open the `$HOME/.zshenv` file, remove the lines related to `zsh-syntax-highlighting`, and then restart your terminal, which can be configured in `$HOME/.zshrc` file 😭

**Comment by pelmered** [comment]
> > I solve it by the command :
> > '''
> > git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
> > git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
> > '''
> > on-my-zsh check if the plugin is exit at '$base_dir/plugins/$name/$name.plugin.zsh' or '$base_dir/plugins/$name/_$name' , so the plugin should be at this path .
> 
> Thanks! It's working.

This is working for me, but every time I update Oh My ZSH the `~/.oh-my-zsh/custom` folder is cleared and I have to do that again. Pretty annoying. 
What should I do?

**Comment by mcornella** [comment]
How do you update OMZ? The built-in updater works for me, are you using a custom command? `$ZSH/custom` is gitignored: https://github.com/ohmyzsh/ohmyzsh/blob/90903779b942a12d273e8d158ad97b252dc74360/.gitignore#L1-L2.

**Comment by pelmered** [comment]
> How do you update OMZ? The built-in updater works for me, are you using a custom command? `$ZSH/custom` is gitignored:
> 
> https://github.com/ohmyzsh/ohmyzsh/blob/90903779b942a12d273e8d158ad97b252dc74360/.gitignore#L1-L2
> 
> .

I'm not really sure. I get a promt if I want to update sometimes when I start a new session in the terminal. Then I just press "y" and then i looks like a `git pull` is performed in `~/.oh-my-zsh/`. 

I tried reinstalling OMZ earlier today. Maybe that solves this problem the next time I update.

**Comment by XinyiXiang** [comment]
> I solve it by the command :
> 
> ''' git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting '''
> 
> on-my-zsh check if the plugin is exit at '$base_dir/plugins/$name/$name.plugin.zsh' or '$base_dir/plugins/$name/_$name' , so the plugin should be at this path .

This worked perfectly for me to get rid of the 'Not found' error(s), if you use a package manager on Mac try using this instead

**Comment by blackboldse** [comment]
> 

Thanks. I resolve with: `brew install zsh-fast-syntax-highlighting` command line.

**Comment by kingmob23** [comment]
> To be fair [zsh-users](https://github.com/zsh-users) has proper installation instructions depending on OS for each of those plugins...
> 
> * https://github.com/zsh-users/zsh-syntax-highlighting - [install.md](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)
> * https://github.com/zsh-users/zsh-completions - [readme.md](https://github.com/zsh-users/zsh-completions/blob/master/README.md)
> * https://github.com/zsh-users/zsh-autosuggestions - [install.md](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md)
> * https://github.com/zsh-users/zsh-history-substring-search - [readme.md](https://github.com/zsh-users/zsh-history-substring-search/blob/master/README.md)
> 
> You need to follow your preferred options for your OS / package manager etc.

Initially ran into same problem as topic starter with "Warning: plugin zsh-syntax-highlighting not found".

Did all exactly as in installation documentation. But nothing changed. No wonder, because i already had it installed with brew and needed line added to .zshrc.

And `git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting` indeed solved problem for me. Because `~/.oh-my-zsh/custom/plugins/` is the directory where zsh looks for plugins.

**Comment by elvisisvan** [comment]
i have the same error on feodra linux:
```shell
[oh-my-zsh] plugin 'zsh-autosuggestions' not found
[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found
```

i checked the official plugins list at https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins and `zsh-autosuggestions` and `zsh-syntax-highlighting` doesn't exist anymore, why is that?

**Comment by jesse-atomic** [comment]
Follow the official doc instructions here: 
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh

In your `.zshrc`, do not include commas.

I ran into a not found issue myself. I removed the plug in, redownloaded it from git (using the above instructions) and moved it to the end of the list in my `plugins=()` in zshrc. Then I quit and reopened my terminal. Worked for me.

**Comment by OliverGrimsley** [comment]
Not sure if this will help anyone . . . on MAC (m4) with Docker Desktop installed, Docker added a source line and a few others, and failed to add a space between the extension and the comment. So, in my .zshrc file it looked like this:

`source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh# The following lines have been added by Docker Desktop to enable Docker CLI completions.`

I just moved the comment to its own line (you could also add a space) and then it worked - note this was affecting only the Docker CLI, and not VSCode
