### ISSUE TITLE
Tab Completion after change of packages needs a restart of zsh

### ISSUE THREAD

**Issue by yuyueshihaoren** [robbyrussell/oh-my-zsh#7689]
I am running ohmyzsh on my linux machine, macbookpro and android termux.

After I install a new package/software via brew / apt / pacman / pip / npm, I have to restart zsh before I get the tab completion of that newly installed software. If I remove the package, I also have to restart zsh to not having that newly deleted package in my tab completion.

Is there a way to update the package information without restarting zsh? I've searched for google and looked through the .zshrc and found nothing.

**Comment by mcornella** [comment]
Once a completion is loaded it's difficult to unload it completely. The best solution is restarting zsh with `exec zsh`.
