### ISSUE TITLE
A prefix icon appeared after switching back to `robyrussell.zsh-theme`. How do I delete it?

### ISSUE THREAD

**Issue by metebyte** [robbyrussell/oh-my-zsh#7691]
I was using a **custom** theme which is known as [Powerlevel9k](https://github.com/bhilburn/powerlevel9k) and for a moment wanted to switch back the default theme which is `robbyrussell.zsh-theme`. Then an unknown **prefix icon** appeared at the start of line.

<img width="352" alt="Screen Shot 2019-03-23 at 06 53 57" src="https://user-images.githubusercontent.com/47678095/54861404-4d7ca600-4d39-11e9-9e56-311c08fd670f.png">

As it shows in the screenshot, Hyper Terminal **does not have** that prefix but when I open iTerm2 it's there.

Here's my configuration files.

`.zshrc` file

```
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"

plugins=(
  git
  docker
  docker-compose
  osx
  node
  npm
  brew
  ng
  yo
  xcode
  urltools
  vscode
  battery
  chucknorris
  colorize
  command-not-found
  copydir
  copyfile
  colored-man-pages
  dircycle
  yarn-completion
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
  history-substring-search
)

source $ZSH/oh-my-zsh.sh
autoload -U +X bashcompinit && bashcompinit
source /usr/local/etc/bash_completion.d/az

export LANG=en_US.UTF-8

alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias shopt="/usr/bin/shopt"
alias vsclist="code --list-extensions"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```
**Output** of `~/.oh-my-zsh/custom/themes`

```
➜  themes git:(master) ✗ ls -la
total 8
drwxr-xr-x   4 metebyte  staff  128 Mar 23 06:50 .
drwxr-xr-x   5 metebyte  staff  160 Mar 17 02:35 ..
-rw-r--r--   1 metebyte  staff  147 Mar 17 02:35 example.zsh-theme
drwxr-xr-x  23 metebyte  staff  736 Mar 17 20:54 powerlevel9k
```

**Comment by mcornella** [comment]
Restarting the shell should fix it. Run `exec zsh`.

**Comment by metebyte** [comment]
> Restarting the shell should fix it. Run `exec zsh`.

Sorry, didn't work..

**Comment by mcornella** [comment]
Oh right, that's an iTerm2 setting, see https://stackoverflow.com/questions/38136244/iterm2-how-to-remove-the-right-arrow-before-the-cursor-line.

**Comment by metebyte** [comment]
@mcornella Ohh 🤦‍♂️Thank you! And I'm really sorry I've never thought that's because of the iTerm2's settings. Anyway thanks again 🙏
