### ISSUE TITLE
common-aliases: alias conflict with fd

### ISSUE THREAD

**Issue by Arlon1** [robbyrussell/oh-my-zsh#7692]
The Alias `fd` in [plugins/common-aliases/common-aliases.plugin.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/729c2f796d4945dfa2bcff144fea84afe5c4b0cb/plugins/common-aliases/common-aliases.plugin.zsh#L37) conflicts with the program `fd`.

**Comment by mcornella** [comment]
Just `unalias fd` if you want to use the program (I think you mean [this one](https://github.com/sharkdp/fd)?).
