### ISSUE TITLE
An update broke a couple of plugins

### ISSUE THREAD

**Issue by d33tah** [robbyrussell/oh-my-zsh#7693]
I just got the regular update prompt and after entering the shell, I saw the following:

```
Warning: plugin colorized not found
Warning: plugin colored-man not found
Warning: plugin copyfiles not found
Warning: plugin zsh-syntax-highlighting not found
```

Are there any additional steps I should take after updating to the latest version?

**Comment by mcornella** [comment]
- `Warning: plugin colorized not found` → it's called `colorize`
- `Warning: plugin colored-man not found` → it's now `colored-man-pages`
- `Warning: plugin copyfiles not found` → it's `copyfile`
- `Warning: plugin zsh-syntax-highlighting not found` → we don't have it as a plugin

**Comment by d33tah** [comment]
@mcornella thanks!
