### ISSUE TITLE
[Ask] How to remove AWS plugin?

### ISSUE THREAD

**Issue by kimthangatm** [robbyrussell/oh-my-zsh#7695]

**Comment by mcornella** [comment]
Just remove it from the plugins array in your zshrc file.

**Comment by ksmithut** [comment]
I never had it in my plugins, but it started showing up today

```sh
> echo "${plugins[@]}" # This is before I source "$ZSH/oh-my-zsh.sh"
git node nvm yarn docker vscode tmux gpg-agent ssh-agent osx
```

I also tried setting `SHOW_AWS_PROMPT=false` in my zshrc file, but that didn't do anything either

**Comment by ksmithut** [comment]
@mcornella Maybe this should be a separate issue? I assume that the question was asked because it started showing up unprompted after updating oh-my-zsh today/yesterday

**Comment by mcornella** [comment]
How is that even possible? What do mean by showing up? Can you post your zshrc file as well?

**Comment by ksmithut** [comment]
Sure thing. I stripped it down to the most minimal config possible, removing all mention of plugins:

```sh
export ZSH="${HOME}/.oh-my-zsh"
export ZSH_THEME="agnoster"
export DEFAULT_USER=${USER}

export AWS_PROFILE=[redacted]
SHOW_AWS_PROMPT=false

source "$ZSH/oh-my-zsh.sh"
```

It seems to be triggered with the `export AWS_PROFILE=[redacted]`. Once I remove that, the prefix goes away. This also only started after the update I did to oh-my-zsh this morning, if that helps.

**Comment by mcornella** [comment]
Oh right, you're using agnoster. This was introduced in #6621. If you don't want it to be shown you can redefine the `prompt_aws` function to be empty:
```
prompt_aws(){}
```

**Comment by ksmithut** [comment]
@mcornella Thanks!

**Comment by kimthangatm** [comment]
@mcornella Thanks!

**Comment by QuentinVigand** [comment]
> Oh right, you're using agnoster. This was introduced in #6621. If you don't want it to be shown you can redefine the `prompt_aws` function to be empty:
> 
> ```
> prompt_aws(){}
> ```
> 
> Put this in your zshrc file after sourcing OMZ. In the future we might make this customizable but in the meantime that's the best we can do.

I am having the same issue after updating oh-my-zsh today. It seems the function name changed in the plugin. Fixed it with:
```bash
aws_prompt_info(){}                                                                                                                                                                      
```
