### ISSUE TITLE
Plugin Not Found

### ISSUE THREAD

**Issue by Gerst20051** [robbyrussell/oh-my-zsh#7699]
I must be missing something about how `zsh` plugins work.

I have the following plugins enabled:

`plugins=(aws, git, gradle, npm, pip, yarn)`

All of them show up in the `~/.oh-my-zsh/plugins` folder.

All of them are part of the bundled plugins except `yarn` which isn't throwing a not found warning.

https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins

This is what I see when I open up the terminal:

```
Warning: plugin aws, not found
Warning: plugin git, not found
Warning: plugin gradle, not found
Warning: plugin npm, not found
Warning: plugin pip, not found
```

Any insight would be great! Thanks!

**Comment by mcornella** [comment]
The zsh arrays aren't use commas to separate entries, just use spaces.

**Comment by Gerst20051** [comment]
Thanks, @mcornella I see what's happening now!

**Comment by betzerra** [comment]
That worked! Thanks @mcornella 
That being said, this is quite strange... my `~/.zshrc` was working perfectly until last update. 😱

**Comment by mcornella** [comment]
It wasn't working correctly, you just didn't know it. We only added the warning so that you can know it from now on.
