### ISSUE TITLE
Buggy Characters in shell

### ISSUE THREAD

**Issue by MattixNow** [robbyrussell/oh-my-zsh#7708]
![](https://i.imgur.com/dadfxDr.png)
What can i do ?

**Comment by mcornella** [comment]
You need a Powerline font: see the [Agnoster theme instructions](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster).

**Comment by MattixNow** [comment]
I have already installed this package

**Comment by mcornella** [comment]
You need to set up your terminal emulator to use one of these fonts. It looks like you're using Windows' default terminal, which at this point I think only supports `DejaVu Sans Mono for Powerline`.
