### ISSUE TITLE
Warning: plugins not found!

### ISSUE THREAD

**Issue by johannydls** [robbyrussell/oh-my-zsh#7709]
After last update, i receive the following messages after start my terminal: 

* Warning: plugin node_modules not found
* Warning: plugin apt not found
* Warning: plugin deb not found

**Comment by mcornella** [comment]
Those are not Oh My Zsh plugins. Remove them from the plugins array in your zshrc file.

**Comment by ughitsaaron** [comment]
I'm getting the same warnings about zsh plugins, e.g.,

```
Warning: plugin zsh-autosuggestions not found
Warning: plugin zsh-syntax-highlighting not found
```
