### ISSUE TITLE
Illegal variable name

### ISSUE THREAD

**Issue by chucklor** [robbyrussell/oh-my-zsh#7710]
Trying to install on a Mac via sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" and I got an error "Illegal variable name".

**Comment by chucklor** [comment]
Got it resolved.

**Comment by mcornella** [comment]
Was it a problem of the download not finishing properly?

**Comment by jacobgoldfarb** [comment]
Having this error on Ubuntu

**Comment by mcornella** [comment]
Does it happen if you first download and save the install script, and then run it? If so, can you run it like `sh -x install.sh` and post the output?
