### ISSUE TITLE
Most of the zsh themes did not work in xshell

### ISSUE THREAD

**Issue by MK0820** [robbyrussell/oh-my-zsh#7712]
Hi. I have set `ZSH_THEME="random"` in `.zshrc` file, but only several of them work well. What could be the problem?
![20190329100732](https://user-images.githubusercontent.com/27913271/55205317-4d831700-520d-11e9-8ef7-bbda4ff6e44d.png)
![20190329100753](https://user-images.githubusercontent.com/27913271/55205318-5247cb00-520d-11e9-9196-ac3e008ec065.png)

**Comment by mcornella** [comment]
You have to restart zsh for some of the theme changes to apply; some themes make changes that aren't overwritten by other themes, so restarting zsh with `exec zsh` should make the trick.
