### ISSUE TITLE
Newlines seem to be getting printed out after command

### ISSUE THREAD

**Issue by miguelsaldivar** [robbyrussell/oh-my-zsh#7713]
![empty_lines](https://user-images.githubusercontent.com/5522618/55216095-184cd980-51b9-11e9-8733-80c476d57178.png)

**Comment by mcornella** [comment]
Can you post your zshrc file?

**Comment by miguelsaldivar** [comment]
This happens as soon as I run the install script, so the zshrc should be the default one. My main [zshrc](https://github.com/miguelsaldivar/.dot_files/blob/master/.zshrc) is here though.

**Comment by mcornella** [comment]
I can't reproduce that with the fishy theme. What theme were you using in that screenshot?

**Comment by miguelsaldivar** [comment]
I believe it was `robbyrussell`, whatever comes by default. Is there any other data/log I can give you, that would be of use?

**Comment by mcornella** [comment]
Can you reliably reproduce this?

**Comment by miguelsaldivar** [comment]
Yeah it happens every time I get an error, specifically this one.

**Comment by miguelsaldivar** [comment]
Nevermind, I believe it was an issue with my terminal emulator. Thanks for trying to help though, and thanks for working on `oh-my-zsh`; you're work is very much appreciated :smile:

**Comment by mcornella** [comment]
If this only happened after a `command not found` error it might have also been due to [`command_not_found_handler`](http://zsh.sourceforge.net/Doc/Release/Command-Execution.html#index-command-not-found_002c-handling-of).

**Comment by miguelsaldivar** [comment]
If it occurs again, I'll look into; thanks again for trying to diagnosis the problem!
