### ISSUE TITLE
Docker complite does not work.

### ISSUE THREAD

**Issue by ShepardEG** [robbyrussell/oh-my-zsh#7714]
Nice to meet you guys. Installed fresh Ubuntu 18.04, add old-creepy Unity. 

Install last ZSH from APT
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

Install docker and docker-compose
Docker version 18.09.4, build d14af54266
docker-compose version 1.23.2, build 1110ad01

Installed last Oh My Zsh from master branch

commit b7b40b0b68c791d57d91c7f4e17ed681d01d5c75 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Jakub Łuczyński <doubleloop@users.noreply.github.com>
Date:   Tue Mar 26 14:44:58 2019 +0100

Add wanted plugins in .zshrc
plugins=(docker docker-compose git)
After restart shell and try autocomplite

![Broken](https://user-images.githubusercontent.com/40993787/55242793-03228a00-524f-11e9-94f4-4eec95282ca0.jpg)

I tried to find a solution on the Internet, but after 4-5 attempts, I decided to create an issue.
I tried source .zshrc
I changed the name of the plugins to the wrong ones (the file loads and says that it cannot find the wrong plugin)
Tried to download _docker from the docker / cli repository

Same problem with docker-compose. 
Tried docker-compose kill -s -> output list of files and dirs.

**Comment by hitalos** [comment]
Try:
```
rm ~/.zcompdump
```

**Comment by Denis-Sidorov** [comment]
I have the same issue but only for docker-compose.
Tried rm .zcompdump and zsh_reload - didn't help.
By the way, I don't see docker-compose in .zcompdump.

**Comment by ShepardEG** [comment]
@hitalos it's works! Thx for help. closing issue.

**Comment by mansurali901** [comment]
for me installation of bash-completion did the trick 
`yum install bash-completion -y`
