### ISSUE TITLE
zsh-completions not found

### ISSUE THREAD

**Issue by The33Coder** [robbyrussell/oh-my-zsh#7718]
For the last two days I've had a problem with the plugin zsh-completions. It is well installed and I reinstalled it with brew but the error persists! 

I have `Warning: plugin zsh-completions not found`

**Comment by mcornella** [comment]
If you haven't installed it as a zsh plugin, like [it's specified in their documentation](https://github.com/zsh-users/zsh-completions/#oh-my-zsh), you don't need to put it in the `plugins` array.

My guess is that you're probably sourcing it somewhere else in your zshrc file.
