### ISSUE TITLE
Warning: plugin history, not found

### ISSUE THREAD

**Issue by E1k3** [robbyrussell/oh-my-zsh#7722]
Since an OMZ update, every time I open a new teminal, I am greeted by this message "Warning: plugin history, not found".

I have read the other issues regarding this, but I cannot find the solution to this problem.
history/history.plugin.zsh exists inside my ~/.oh-my-zsh directory and the git plugin, which is located there as well (git/git.plugin.zsh), loads without problem.

**Comment by SantiMA10** [comment]
Same problem here but with *git* and *zsh-autosuggestions* plugins. Both appear on their respective folders.

**Comment by mcornella** [comment]
No commas after array entries:
do
```zsh
plugins=(... history ...)
```
not
```zsh
plugins=(... history, ...)
```

**Comment by SantiMA10** [comment]
Works for me! Thanks, @mcornella!

**Comment by E1k3** [comment]
Works. Has the behaviour regarding commas changed or did I forget changing the array entries?

**Comment by mcornella** [comment]
We started giving warnings just days ago, that's only what changed.
