### ISSUE TITLE
gbda alias is broken on MacOS 

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [robbyrussell/oh-my-zsh#7723]
Since last update `gbda` throws `xargs: illegal option -- r` error.
`-r` is a GNU extension (see [doc](http://man7.org/linux/man-pages/man1/xargs.1.html)) and is not available across all platforms.
Introduced in #6079

**Comment by mcornella** [comment]
Thanks for the heads up, I've decided to revert that change.

**Comment by ivanvoznyakovsky** [comment]
Thnx for quick fix
