### ISSUE TITLE
Plugins not found after updating

### ISSUE THREAD

**Issue by ktherage** [robbyrussell/oh-my-zsh#7728]
Hello,

I've updated my OhMyZsh yesterday (i did it because it told me there is an update on terminal boot up). And today after rebooting and starting a terminal i get the two following warnings.

```
Warning: plugin autosuggestions not found
Warning: plugin completions not found
```

Then i saw that those plugins where not anymore on https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins and i saw at https://github.com/robbyrussell/oh-my-zsh/issues/7685#issuecomment-477072354 and one of my colleague uses `zsh-autosuggestions` and `zsh-completions` so i tried them and i get the same problem.

Any fix ?

**Comment by robcresswell** [comment]
I've got the same issue with the `git` plugin, though that looks like its still in the tree? What's going on?

**Comment by chuckstar76** [comment]
@ktherage - you may be helped by this [comment](https://github.com/robbyrussell/oh-my-zsh/issues/7688#issuecomment-477340254)

General comments:

- External (non-OMZ) plugins do document how to install - follow them
- Do not use "," commas as delimiter in the ```plugins=()``` array

**Comment by SaltyCucumber** [comment]
Can confirm, fixed my problem by removing commas from plugins=() in .zshrc

**Comment by mcornella** [comment]
There are many other issues like this one, please use the search before opening an issue.

**Comment by cuthbeorht** [comment]
> @ktherage - you may be helped by this [comment](https://github.com/robbyrussell/oh-my-zsh/issues/7688#issuecomment-477340254)
> 
> General comments:
> 
>     * External (non-OMZ) plugins do document how to install - follow them
> 
>     * Do not use "," commas as delimiter in the `plugins=()` array

I was using commas in the plugins array.  I removed them and that solved it.
