### ISSUE TITLE
Disable kube Prompt

### ISSUE THREAD

**Issue by yyl719133368** [robbyrussell/oh-my-zsh#7730]
![1554329055532](https://user-images.githubusercontent.com/4263420/55516346-dca48a80-5664-11e9-88cf-f32a8aa78182.jpg)

Anyone know Where is this come from ? I want to remove it ...
**`[kube(n/a) git(e465b3b) branch(intl-1150)]`**

**Comment by mcornella** [comment]
What plugins and theme are you using?

**Comment by yyl719133368** [comment]
@mcornella It's not `oh my zsh` 's issue.
