### ISSUE TITLE
 Fedora29 / adding rpmfusion  -  zsh: parse error near `)'

### ISSUE THREAD

**Issue by Space-Amoeba** [robbyrussell/oh-my-zsh#7732]
# On Fedora 29 when trying to add rpmfustion repos i get this error:

-------------------------------------------------

sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \ https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$\(rpm -E %fedora).noarch.rpm
zsh: parse error near `)'

-------------------------------------------------

I ran the same command in bash. Worked flawlessly.

# Here is my .zshrc:

export ZSH="/home/myself/.oh-my-zsh"

ZSH_THEME="powerlevel9k/powerlevel9k"

ZSH_DISABLE_COMPFIX=true

plugins=(git git-extras pip python)

source $ZSH/oh-my-zsh.sh

# User settings:
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
POWERLEVEL9K_CONTEXT_TEMPLATE="%n|`hostname -f`"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="002"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="236"
POWERLEVEL9K_DIR_HOME_BACKGROUND="002"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_RIGHT_PROMPT_DEFAULT_BACKGROUND="236"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1

# User specific alias:
alias update='sudo dnf update -x '\''kernel*'\'''
alias glances="glances -1 -4 -t 1 --process-short-name -3 --hide-kernel-threads --disable-process"
alias nvidia="nvidia-smi -l 1"
alias python="python3"
alias syncOne='onedrive --synchronize --verbose --confdir="~/.config/onedriveOne"'
alias monOne='onedrive --monitor --verbose --confdir="~/.config/onedriveOne"'
alias syncTwo='onedrive --synchronize --verbose --confdir="~/.config/onedriveTwo"'
alias monTwo='onedrive --monitor --verbose --confdir="~/.config/onedriveTwo"'

# User specific functions:
if [ -f $HOME/.bash-insulter/src/bash.command-not-found ]; then
   source $HOME/.bash-insulter/src/bash.command-not-found
fi

**Comment by mcornella** [comment]
I think you need to get rid of the backslash in the second $(), it should be `...release-$(rpm...` instead of `...release-$\(rpm...`.
