### ISSUE TITLE
zsh: can't open input file: ~/.oh-my-zsh/tools/check_for_upgrade.sh

### ISSUE THREAD

**Issue by haboutnnah** [robbyrussell/oh-my-zsh#7735]
```sh
kodi-htpc$ zsh
zsh
zsh: can't open input file: ~/.oh-my-zsh/tools/check_for_upgrade.sh
/home/hannah/.oh-my-zsh/oh-my-zsh.sh:34: no matches found: ~/.oh-my-zsh/lib/*.zsh
```

Similar to #1245 but does not get fixed through what is listed, and a second error.

**Comment by mcornella** [comment]
Make sure you have a working Oh My Zsh repository. Try:
```zsh
cd ~/.oh-my-zsh
git reset --hard HEAD
```
It can also be a problem with your permissions, so make sure that all the files and directories under the ohmyzsh folder are owned by you.

**Comment by haboutnnah** [comment]
I deleted the directory and reinstalled and it works every time  I do that for a few days.
