### ISSUE TITLE
AWS plugin needs more flexibility with hiding "prefix" prompt or "suffix" prompt

### ISSUE THREAD

**Issue by ffxsam** [robbyrussell/oh-my-zsh#7737]
On the prefix (left) side, I have "AWS: default" prepended to my prompt, and on the suffix (right) side, I have `<aws:default>`. If I specify `SHOW_AWS_PROMPT=false`, it only gets rid of the suffix, which I actually want. I _don't_ want the prefix prompt.

There should be two options to cover this, e.g. `SHOW_AWS_PREFIX_PROMPT` and `SHOW_AWS_SUFFIX_PROMPT`.

**Comment by mcornella** [comment]
There are two variables to that effect, see [aws README](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/aws/README.md#theme).

**Comment by ffxsam** [comment]
@mcornella I think you misunderstood my post. I'm talking about a way to hide the add-on to my prompt, but keep the `<aws:profile>` tag on the right. The two variables you're referring to are only involved in formatting that `<aws:profile>` tag.

**Comment by ffxsam** [comment]
I'm talking about a way to remove the green prompt bit on the left, but keep the tag on the right.

![image](https://user-images.githubusercontent.com/12532733/55686683-d5fa6980-5929-11e9-9a71-e51a1b2ef5ce.png)

**Comment by mcornella** [comment]
Oh that's an agnoster function. You can override it by redefining it with an empty body:
```
prompt_aws(){}
```

**Comment by ffxsam** [comment]
@mcornella Ahh, great! Thank you.
