### ISSUE TITLE
Tab completion isn't working for wd or nvm plugin

### ISSUE THREAD

**Issue by asamolion** [robbyrussell/oh-my-zsh#7741]
I've installed a fresh copy of zsh and oh-my-zsh on Elementary OS Juno.

```
ZSH: 5.4.2
```

and I've enabled the following plugins

```
plugins=(
  extract
  git
  nvm
  wd
  virtualenvwrapper
)
```

autocomplete isn't working for wd and nvm. The rest are fine.

Can someone please point me on how to debug this issue?

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` after enabling the plugins and then restart the shell.

**Comment by asamolion** [comment]
@mcornella Thanks.

**Comment by Haixiang6123** [comment]
Thanks, it's really helpful!
