### ISSUE TITLE
Need some help in theme creation

### ISSUE THREAD

**Issue by chinanoahli** [robbyrussell/oh-my-zsh#7756]
I was working in a new theme
```
FG_COLOR_RED=%{$fg[red]%}
FG_COLOR_CYAN=%{$fg[cyan]%}
FG_COLOR_YELLOW=%{$fg[yellow]%}
FG_COLOR_BLACK=%{$fg[black]%}

BG_COLOR_BLACK=%{$bg[black]%}
BG_COLOR_BLUE=%{$bg[blue]%}
BG_COLOR_WHITE=%{$bg[white]%}

RESET_COLOR=%{$reset_color%}

PROMPT_NEWLINE='%{'$'\n''%}'
RPROMPT_PREFIX='%{'$'\e[1A''%}' # one line up
RPROMPT_SUFFIX='%{'$'\e[1B''%}' # one line down

if [ $(whoami) = "root" ]; then
  USERCOLOR=$FG_COLOR_RED
else
  USERCOLOR=$FG_COLOR_CYAN
fi

PROMPT='$USERCOLOR$BG_COLOR_BLACK [ %n >$RESET_COLOR$FG_COLOR_YELLOW$BG_COLOR_BLACK [ %m >$RESET_COLOR$FG_COLOR_BLACK$BG_COLOR_BLUE [ %~ >$RESET_COLOR$PROMPT_NEWLINE$USERCOLOR$BG_COLOR_BLACK [ %# > $RESET_COLOR'

RPROMPT='$RPROMPT_PREFIX$(git_prompt_info)$BG_COLOR_WHITE $FG_COLOR_BLACK<! %!$RESET_COLOR$FG_COLOR_BLACK$BG_COLOR_BLUE <%*$RESET_COLOR$RPROMPT_SUFFIX'

ZSH_THEME_GIT_PROMPT_PREFIX="$BG_COLOR_BLACK<git: $FG_COLOR_YELLOW"
ZSH_THEME_GIT_PROMPT_SUFFIX="$RESET_COLOR"
ZSH_THEME_GIT_PROMPT_DIRTY="$FG_COLOR_RED"
ZSH_THEME_GIT_PROMPT_CLEAN="$FG_COLOR_CYAN~"
```

But the `RPROMPT` seems to had some issues.
First, `RPROMPT` can not showed in the right edge on the shell.
Second, it can change the place itself, just like this
Third, when I using the tab key to auto completion the command, some time,  it will going crazy...

![Untitled](https://user-images.githubusercontent.com/10005128/55893359-0f192f00-5bf3-11e9-908d-acf08936cf3e.gif)

I was working this theme base on an old one, the old one can works normally.
```
CURRENTUSER=$(whoami)
if [ "$CURRENTUSER" = "root" ]; then USERCOLOR="red"; else USERCOLOR="cyan"; fi

PROMPT='⎡\
%{$fg[$USERCOLOR]%}%{$bg[black]%} [%n> %{$reset_color%}\
%{$fg[yellow]%}%{$bg[black]%}[%m> %{$reset_color%}\
%{$fg[black]%}%{$bg[blue]%}[%~> %{$reset_color%}
⎣\
%(?,%{$fg[green]%}%{$bg[black]%} [%?> %{$reset_color%},%{$fg[red]%}%{$bg[black]%} [%?> %{$reset_color%})%{$fg[$USERCOLOR]%}%# > %{$reset_color%}\
'

RPROMPT='$(git_prompt_info)%{$bg[white]%} %{$fg[black]%}<! %!%{$reset_color%}%{$fg[black]%}%{$bg[blue]%} <%*%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$bg[black]%}<git: %{$fg[yellow]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}*"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[cyan]%}~"
```

So, what is going on here?

**Comment by mcornella** [comment]
Try changing `PROMPT_NEWLINE='%{'$'\n''%}'` with `PROMPT_NEWLINE=$'\n'`, without the `%{%}` sequences (which tell zsh that the characters inside it don't take up space in the prompt line).

I have to say though, the way you're trying to reposition the right prompt to the line above is something I've never seen before, and it might cause problems when completing stuff.

With my suggestion above this worked in my system, hope this helps.

**Comment by chinanoahli** [comment]
Emmm, I was trying to put the `RPROMPT` in the first line as same as the `PROMPT`'s first line. After search, I got this way can actually work. Is there any better way to get this done?
