### ISSUE TITLE
Prompt text overwritten on error in the previous command

### ISSUE THREAD

**Issue by lgp171188** [robbyrussell/oh-my-zsh#7761]
I use the latest `oh-my-zsh` with the `bira` theme on `zsh 5.7.1` installed using `antigen`. 

```
antigen use oh-my-zsh
antigen theme robbyrussell/oh-my-zsh themes/bira
antigen apply
COMPLETION_WAITING_DOTS=false
```

When I run a command which returns an error, the cursor on the next prompt line gets moved to the `$` character in the prompt causing it to be overwritten when a command is typed. There was also an issue with the cursor getting pushed a bit to the right and the backspace not working in some cases, but disabling `COMPLETION_WAITING_DOTS` seems to have fixed it. Example illustrating the issue below:

```
─ guruprasad@precious ~  
╰─$ date
Thu Apr 11 23:48:03 IST 2019
╭─ guruprasad@precious ~  
╰─$ lll
zsh: correct 'lll' to 'll' [nyae]? n
zsh: command not found: lll
╭─ guruprasad@precious ~  
╰─$
╭─ guruprasad@precious ~  
╰─ls 
```

**Comment by mcornella** [comment]
Make sure you have a `locale` that supports `UTF-8`. See `locale -a` for options, then set `LANG` to one of them.

**Comment by lgp171188** [comment]
@mcornella, thanks that was the issue on my computer :+1:
