### ISSUE TITLE
ls command run when sourcing .zshrc

### ISSUE THREAD

**Issue by scottidler** [robbyrussell/oh-my-zsh#7772]
https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/theme-and-appearance.zsh#L35

I have tracked down an 'ls' command(above) that runs every time I source the ~/.zshrc file.  Is this supposed to happen?  If so, for what purpose?

**Comment by mcornella** [comment]
It's purpose is to check the color parameter it accepts. All output is silenced so it shouldn't be a problem.

**Comment by scottidler** [comment]
This happens every time I source the ~/.zshrc file.  It is not silenced.

**Comment by mcornella** [comment]
If you get ls output it's not from those lines because they explicitly redirect both stdout and stderr to /dev/null.
