### ISSUE TITLE
why my prompt is not in UTF-8?

### ISSUE THREAD

**Issue by kw-andy** [robbyrussell/oh-my-zsh#7773]
I have this error as you can see (see screenshot below)

[https://gifyu.com/image/923z](https://gifyu.com/image/923z)

My parameter has been set as UTF-8 so I'm not sure of what is going on.

Cheers.

**Comment by mcornella** [comment]
This is a font issue, you need a [powerline font](https://github.com/powerline/fonts). There are many closed issues in OMZ about this if you need further assistance. 

And for future reference, to check if you're using utf8 run `locale`, `LC_ALL` is not always defined.
