### ISSUE TITLE
[oh-my-zsh] plugin 'd' not found

### ISSUE THREAD

**Issue by kchen0x** [robbyrussell/oh-my-zsh#7779]
I found this error recently.

Did you remove this plugin? or it just changes name?

**Comment by krizss** [comment]
I got this

[oh-my-zsh] plugin 'source' not found
[oh-my-zsh] plugin '/dev/fd/12' not found

**Comment by mcornella** [comment]
> I found this error recently.
> 
> Did you remove this plugin? or it just changes name?

There has never been a plugin named `d`, I just checked. Where did you find that?

-----
> I got this
> 
> [oh-my-zsh] plugin 'source' not found
> [oh-my-zsh] plugin '/dev/fd/12' not found

You have broken syntax in your plugins array. Check for a line saying something like
```
plugins=(
   ...
   source <(....)
   ...
)
```
That source line shouldn't be there.

**Comment by kchen0x** [comment]
I can still use it:

```
╭─ kchen@KChens-MacBook-Pro ~/Projects/bin_asset_android.wiki  ‹master›
╰─$ d
0       ~/Projects/bin_asset_android.wiki
1       ~/.config/karabiner/assets/complex_modifications
2       ~/Projects/bin_account_android.wiki
3       ~/Projects/bin_account_ios.wiki
4       ~/Projects
5       /
6       ~/Projects/bin_facebookclient_android.wiki
```

and that's it:

```
$ which d
d: aliased to dirs -v | head -10
```

And check this post:
https://cnu.name/d-command-in-oh-my-zsh/

**Comment by mcornella** [comment]
Oh right, that's an alias provided by default by OMZ, see: https://github.com/robbyrussell/oh-my-zsh/blob/9b2410fbcfa21d6115219fe626a6f422b578d3ac/lib/directories.zsh#L24

You don't need to add that as a plugin (there is no d plugin), it just comes by default within the OMZ core.
