### ISSUE TITLE
vi-mode doesn't update

### ISSUE THREAD

**Issue by theonlygusti** [robbyrussell/oh-my-zsh#7797]
if I press enter while in normal mode the `<<<` remains on the next command line even though I have been put back into insert mode

**Comment by mcornella** [comment]
This is a side-effect of #7753. I've submitted #7818 which should fix it for you. +1 that if it works.

**Comment by mcornella** [comment]
Ping @theonlygusti

**Comment by theonlygusti** [comment]
Sorry I personally won't have time to test it for a while.

**Comment by shawn-ogg** [comment]
Just tested it on my computer. Works now!

**Comment by mcornella** [comment]
Thanks!

**Comment by AndreGeng** [comment]
I have a similar problem, if I press Ctrl-c while in normal mode the '<<<' remains on the next command line even though I have been put back into insert mode

**Comment by zArubaru** [comment]
[This](https://github.com/ohmyzsh/ohmyzsh/pull/7978) pull request resolves the issue.
