### ISSUE TITLE
Font broken after today's kernel update on Mint 19 system

### ISSUE THREAD

**Issue by mirkow** [robbyrussell/oh-my-zsh#7799]
Hello,

today I got the following updates on my Mint 19 system:

> Start-Date: 2019-04-24  11:13:09
> Commandline: packagekit role='update-packages'
> Requested-By: user (1000)
> Install: linux-image-4.15.0-48-generic:amd64 (4.15.0-48.51, automatic), linux-headers-4.15.0-48:amd64 (4.15.0-48.51, automatic), linux-headers-4.15.0-48-generic:amd64 (4.15.0-48.51, automatic), linux-modules-extra-4.15.0-48-generic:amd64 (4.15.0-48.51, automatic), linux-modules-4.15.0-48-generic:amd64 (4.15.0-48.51, automatic)
> Upgrade: linux-headers-generic:amd64 (4.15.0.47.49, 4.15.0.48.50), linux-libc-dev:amd64 (4.15.0-47.50, 4.15.0-48.51), linux-image-generic:amd64 (4.15.0.47.49, 4.15.0.48.50), google-chrome-stable:amd64 (73.0.3683.103-1, 74.0.3729.108-1), linux-generic:amd64 (4.15.0.47.49, 4.15.0.48.50)
> End-Date: 2019-04-24  11:14:16

Afterwards, my zsh shell with agnoster theme displayed a lot of ???:

`user@host ��� ~ ���` 

Somebody else got this problem and an idea how to fix this?

**Comment by abdl-dev** [comment]
I can confirm the same issue with Ubuntu 19.04, on all three on my machines that I've upgraded with various settings. No combination of tinkering with the font settings resolves this. Special glyphs and ligatures display correctly elsewhere (vim, tmux, etc.), but does not for zsh/omz. 

![Screenshot from 2019-04-25 06-13-51](https://user-images.githubusercontent.com/1343016/56728793-a1582180-6721-11e9-8d9a-450af8a49b9c.png)

**Comment by mirkow** [comment]
I saw now that it works on the cinnamon desktop but not on KDE plasma.

**Comment by mcornella** [comment]
Make sure your `locale` is also correct (i.e. using a UTF-8 one).

**Comment by mirkow** [comment]
Thanks, I changed it to Locale_C yesterday, which coincided with the update reboot.
Putting it back to en_US fixed it.
