### ISSUE TITLE
frontend-search: add Angular 2

### ISSUE THREAD

**Issue by DantonGodoy** [robbyrussell/oh-my-zsh#7802]
Hi. Can you guys add the Angular2+ in the search lsit context?
AngularJS is practically deprecated lol

**Comment by mcornella** [comment]
The URL for searching is `https://angular.io/?search=`, would you be interested in adding a PR for it?

**Comment by DantonGodoy** [comment]
I would love to, but I don´t even know how to start implementing this, build up the project, etc.

**Comment by divbhasin** [comment]
@mcornella I have opened a PR to fix the issue.
