### ISSUE TITLE
can't change theme in manjaro

### ISSUE THREAD

**Issue by jskcnsl** [robbyrussell/oh-my-zsh#7806]
I use oh-my-zsh in my new manjaro environment, and it autoset to a default theme (maybe agnoster, I think). I have checked ZSH_THEME after open a new terminal, and it's correctly equal to 'bullet-train'. 

After some experiments I find 
1. `source ~/.zshrc` not work
2. change to other theme not work
3. `source ~/.oh-my-zsh/theme/bullet-train.zsh-theme` work
4. `source ~/.oh-my-zsh/oh-my-zsh.sh` work

And the result of `zsh -xvic 'exit' &> ~/omz-debug.log` is [here](https://gist.github.com/jskcnsl/3b63053975e18c1364b859eac5acaab9). It looks all right ?

So, what can I try next ?

**Comment by jskcnsl** [comment]
I found the reason... the script add for powerline fonts after `source $ZSH/oh-my-zsh.sh` maybe do something... so, move `source $ZSH/oh-my-zsh.sh` to the end of .zshrc can fix this.

**Comment by mcornella** [comment]
You have a bullet-train theme in the custom folder (`$ZSH_CUSTOM`). Delete that one and it'll load the main one.
