### ISSUE TITLE
Square character in agnoster theme

### ISSUE THREAD

**Issue by KrisTomura** [robbyrussell/oh-my-zsh#7810]
OS:Arch linux
WM:i3
Terminal:Urxvt
zsh Theme: Agnoster
How to fix this square?
![2019-04-29-105845_1366x768_scrot](https://user-images.githubusercontent.com/45327204/56877238-60884180-6a6e-11e9-849e-da283beed3b7.png)

**Comment by mcornella** [comment]
You need to install a [Powerline font](https://github.com/powerline/fonts) and set up your terminal to use one. Also [documented in the wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster).
