### ISSUE TITLE
aws plugin does not work due to wrong path resolution of aws_zsh_completer.sh

### ISSUE THREAD

**Issue by dorons** [robbyrussell/oh-my-zsh#7811]
* aws --version
aws-cli/1.16.147 Python/3.7.3 Linux/5.0.0-13-generic botocore/1.12.137
* os: Ubuntu 19.04

How to reproduce: press tab after the 'aws' command 
Expected behavior: command completion
Actual behavior: no completion

The issue is due to improper path resolution of the aws_zsh_completion.sh in the latest awscli version

**Comment by mcornella** [comment]
Do you know what's the correct path?
