### ISSUE TITLE
Found Windows line endings in .oh-my-zsh/lib/theme-and-appearance.zsh

### ISSUE THREAD

**Issue by mehemken** [robbyrussell/oh-my-zsh#7819]
This morning I answered Y to the biweekly update and my theme broke. I don't use anything fancy, I use all the defaults from Oh My ZSH.

The error code was nice, it said there were some `^M` characters in the theme-and-appearance file. So I got in there with a `sed $'s/\r//g'` and then a `source ~/.zshrc`. Now my theme is back to normal.

So the bug is that there are Windows line endings in the most recent update that should probably not be there.

**Comment by mcornella** [comment]
See #4069.
