### ISSUE TITLE
After `Brew Upgrade` now getting error.

### ISSUE THREAD

**Issue by AdamGEmerson** [robbyrussell/oh-my-zsh#7825]
After running `brew upgrade` I am now getting the following lines after every command:

```
omz_urlencode:42: failed to load module `zsh/regex': dlopen(/usr/local/Cellar/zsh/5.7/lib/zsh/regex.bundle, 9): image not found
omz_urlencode:42: -regex-match not available for regex
```

Can someone help?

**Comment by AdamGEmerson** [comment]
So I've determined that the issue is the zsh has been updated to version 5.7.1 and the path in the above script is still calling for version 5.7... 

I just can't find the script `omz_urlencode`.  Anyone know where this is located?

**Comment by mcornella** [comment]
Try restarting zsh: `exec zsh`. [`omz_urlencode` is a function](https://github.com/robbyrussell/oh-my-zsh/blob/8113ed065d5bead01430e393bd33d6e32a597471/lib/functions.zsh#L128) set by OMZ to encode a string to URI specification. It is used for Terminal.app to encode the current working directory: https://github.com/robbyrussell/oh-my-zsh/blob/8113ed065d5bead01430e393bd33d6e32a597471/lib/termsupport.zsh#L90-L99

What happened is that you updated the zsh version while running the old one, and the old modules disappeared but your current zsh session doesn't know it.

**Comment by mcornella** [comment]
Relevant issue: https://github.com/robbyrussell/oh-my-zsh/issues/4669.

**Comment by AdamGEmerson** [comment]
@mcornella 

Thanks!  So simple. Not sure why I didn't think of it.  I was over here digging in `functions.zsh` about to make my problem worse.

Cheers! 🍻
