### ISSUE TITLE
Tab completion doesn't work on apt but on apt-get

### ISSUE THREAD

**Issue by SneakyTurt1e** [robbyrussell/oh-my-zsh#7829]
` apt-get -y ` and Tab, I can get a lot of options, it works perfectly. But `apt -y `
Nothing output here.
How can I solve this problem?
What information should I provide?

**Comment by mcornella** [comment]
`apt -y` is a weird order and is very possible that the completion apt completion doesn't account for it. Try another way, like `apt install -y` or `apt <command> -y`. This is provided by zsh itself though.
