### ISSUE TITLE
Strange % character on startup (MacOS Hyper terminal)

### ISSUE THREAD

**Issue by linonetwo** [robbyrussell/oh-my-zsh#7832]
<img width="944" alt="屏幕快照 2019-05-05 下午8 08 44" src="https://user-images.githubusercontent.com/3746270/57193795-dbbb8d00-6f71-11e9-9754-bd1cc1d23a39.png">

Try copy all texts resulted in:

```
%                                       

                                        


~                                                                                                             
▶ 
```

Even if I change to another theme:
<img width="938" alt="屏幕快照 2019-05-05 下午8 15 14" src="https://user-images.githubusercontent.com/3746270/57193873-9481cc00-6f72-11e9-89e1-32d5571a9050.png">

**Comment by mcornella** [comment]
The percent symbol is displayed by zsh when the last line before the prompt doesn't end with a newline. For example, you'll see it if you run `echo -n hello world`. This means that there has to be a command in your zsh init scripts that outputs a line with no newline.

**Comment by linonetwo** [comment]
I see no `echo` executed in `$ZSH/oh-my-zsh.sh`.

How can I further debug this?

**Comment by reneroth** [comment]
You could provide us with your oh-my-zsh.sh as well as your .zshrc (omit private details if necessary)

**Comment by linonetwo** [comment]
Hi, here are my [.zshrc](https://pastebin.com/kHSgk38v) and [$ZSH/oh-my-zsh.sh](https://pastebin.com/1PLEYyVa).

Actually, I've just installed it yesterday and this occurs just after installation.

**Comment by reneroth** [comment]
You have multiple plugins running, my first guess would be disabling all of them and then re-enabling them one by one to see if one of them is the culprit :)

**Comment by linonetwo** [comment]
Actually, it occurs with minimal config:
<img width="1030" alt="屏幕快照 2019-05-06 下午7 31 19" src="https://user-images.githubusercontent.com/3746270/57222613-c6a83200-7035-11e9-8e3d-d705617ef717.png">

**Comment by mcornella** [comment]
This is a regression introduced in Hyper v3, see https://github.com/zeit/hyper/issues/3586 and https://github.com/zeit/hyper/issues/2144.
