### ISSUE TITLE
lowdash completion and then: "can only be called from completion function"

### ISSUE THREAD

**Issue by nmaxcom** [robbyrussell/oh-my-zsh#7833]
I needed imagemagick for a gulp thing. According to their docs I used brew to install it. Brew auto updated, installed all the dependencies and finally the app, all with no errors or warnings.

Now when from the console I try to run it I type "image" and hit tab, the terminal shows me these options:

`_genisoimage  _imagemagick  _xloadimage   jimage`

I add an 'm' and tab again and now I'm ready to run `_imagemagick`. But what's with that prefix? Anyways:

```
Δ merl /Users/merl $ _imagemagick
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
```

I've lost an hour of searching and trying stuff like deleting the .zcompdump* file and resetting zsh (but the file and all its contents appears right back with some " _imagemagick" inside... I don't know.

This is not the first time something like this happens (autocomplete giving me a `_whatever` command)
Those _tags errors are absolutely cryptic, I don't know what else to do.

PS: also, gulp complains as expected "Error: Cannot find module 'imagemagick'"

**Comment by mcornella** [comment]
`_imagemagick` is the name of the completion function for imagemagick, that's why you get that error. You have to run an imagemagick command, which are varied and [none of them are called `imagemagick`](https://imagemagick.org/script/command-line-tools.php). As per the gulp error, I think you just need to `npm install` the `imagemagick` package.

Not an OMZ issue.

**Comment by nmaxcom** [comment]
Thank you for the imagemagick commands, they could have mentioned somewhere when you install it...
