### ISSUE TITLE
unstoppable autojump complaint(Please install autojump first (https://github.com/wting/autojump)

### ISSUE THREAD

**Issue by Nimrod0901** [robbyrussell/oh-my-zsh#7835]
Hi,
I remove `autojump` from `plugins` in my `.zshrc` and source it.
However, whenever I open a new terminal, it shows **Please install autojump first (https://github.com/wting/autojump)** which is annoying.
I have no idea about how to fix it.
I have installed and uninstalled `autojump` both locally and globally again and again.

**Comment by Nimrod0901** [comment]
Please feel free to let me provide more information. Thanks a lot.

**Comment by mcornella** [comment]
The `autojump` command needs to be available before the plugin is sourced. If the plugin doesn't find it, perhaps you have an issue with your `$PATH`.

**Comment by Nimrod0901** [comment]
> The `autojump` command needs to be available before the plugin is sourced. If the plugin doesn't find it, perhaps you have an issue with your `$PATH`.

Thanks, issue fixed. I copied .zshrc to .zshenv mistakenly.
