### ISSUE TITLE
alien_async_prompt:1: command not found: async_init

### ISSUE THREAD

**Issue by patisun** [robbyrussell/oh-my-zsh#7837]
Hi there, I get a issue:

When I start zsh then it does start, but shows the following:
```
alien_venv:1: command not found: plib_venv                                      
alien_async_prompt:1: command not found: async_init
alien_async_prompt:2: command not found: async_start_worker
alien_async_prompt:3: command not found: async_register_callback
alien_async_prompt:4: command not found: async_job

```
What can I do to get rid of the opening warnings?

**Comment by mcornella** [comment]
OMZ doesn't have an `alien` theme, ask wherever you got it from (possibly [this one?](https://github.com/eendroroy/alien)).

**Comment by mcornella** [comment]
Looks like this is what you want: https://github.com/eendroroy/alien/issues/6.
