### ISSUE TITLE
Chinnese simbols in zsh bar

### ISSUE THREAD

**Issue by alberpilot** [robbyrussell/oh-my-zsh#7840]
Hello

  I've recently installed zsh and all the stuff (I think), but the zsh bar is not shown correctly as you can see in the image below: 

![image](https://user-images.githubusercontent.com/3830293/57567762-4b040780-73de-11e9-8b58-d16db3e97203.png)

Thanks for your help.

PS: I tried this solution: https://github.com/robbyrussell/oh-my-zsh/issues/5709#issuecomment-267086715

**Comment by mcornella** [comment]
If you really have installed a Powerline font *and* set up your terminal emulator to use it, then another possibility might be that you're not using a UTF-8 locale. Run `locale` to be sure.

**Comment by alberpilot** [comment]
Hello 

 Thanks for your quick response. This is the locale ouput and powerline check: 

``` 
~  locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
 ~  sudo dpkg -l | grep powerline 
ii  fonts-powerline                                  2.6-2                                                  all          prompt and statusline utility (symbols font)
ii  powerline                                        2.6-2                                                  amd64        prompt and statusline utility
ii  python3-powerline                                2.6-2                                                  all          prompt and statusline utility (Python 3.x module)
 ~  


```

Any more ideas? I'm using Pop_OS! (Ubuntu based): https://system76.com/pop.

**Comment by mcornella** [comment]
What about the terminal emulator settings, is there a Powerline font set up?

**Comment by alberpilot** [comment]
Oh, really interesting question. I try to select them and: 

![image](https://user-images.githubusercontent.com/3830293/57569400-dd170a80-73f4-11e9-8384-342c45e51dd2.png)

Looks like I have a problem with the fonts, right? I tried to reinstalled them without success.

**Comment by alberpilot** [comment]
ok, fixed:

![image](https://user-images.githubusercontent.com/3830293/57569423-29fae100-73f5-11e9-94b1-656b388a347f.png)

What did I do? I unselected the use of system font.I think, not sure if that was the point that solved the problem. Thanks a lot @mcornella !!
