### ISSUE TITLE
cannot use |

### ISSUE THREAD

**Issue by felixbello** [robbyrussell/oh-my-zsh#7842]
the Pipe (alt + 7) ist not available any ideas?

I'm using the font: "Meslo LG S Regular for Powerline"

**Comment by mcornella** [comment]
You're probably using another keyboard character set. Not OMZ related.

**Comment by felixbello** [comment]
> You're probably using another keyboard character set. Not OMZ related.

the pipe was available in the terminal before I installed the fonts, right now I need to create the Pipe outside of terminal and then copy paste..

**Comment by mcornella** [comment]
If it's not a character set issue it might be an issue with your terminal emulator. Check if there were any other settings changed.
