### ISSUE TITLE
After updating "command not found: compdef"

### ISSUE THREAD

**Issue by krisavi** [robbyrussell/oh-my-zsh#7846]
https://github.com/robbyrussell/oh-my-zsh/blob/486fa1010df847bfd8823b4492623afc7c935709/lib/directories.zsh#L32

Seems that after the update I keep getting:
~/.oh-my-zsh/lib/directories.zsh:32: command not found: compdef

**Comment by 0vidiu** [comment]
Same for me.

**Comment by lhorace** [comment]
Same, oddly enough, I had assume it was misconfiguration somewhere.

**Comment by mcornella** [comment]
Try upgrading again, this was fixed hours after: `upgrade_oh_my_zsh`.

**Comment by maxcr** [comment]
still not fixed for me

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` as well.

**Comment by kalbert312** [comment]
Getting this as well after `rm` ing the zcompdump files, upgradeing ohmyzsh, and restarting the shell.
```# complete is a bash builtin, but recent versions of ZSH come with a function
# called bashcompinit that will create a complete in ZSH. If the user is in
# ZSH, load and run bashcompinit before calling the complete function.
if [[ -n ${ZSH_VERSION-} ]]; then
  autoload -U +X bashcompinit && bashcompinit
fi
+/Users/kylealbert/.nvm/bash_completion:92> [[ -n 5.7.1 ]]
+/Users/kylealbert/.nvm/bash_completion:93> autoload -U +X bashcompinit
+/Users/kylealbert/.nvm/bash_completion:93> bashcompinit
+bashcompinit:177> unfunction bashcompinit
+bashcompinit:178> autoload -Uz bashcompinit
+bashcompinit:179> return 0

complete -o default -F __nvm nvm
+/Users/kylealbert/.nvm/bash_completion:96> complete -o default -F __nvm nvm
+complete:1> emulate -L zsh
+complete:2> local args void cmd print remove
+complete:3> args=( -o default -F __nvm nvm ) 
+complete:4> zparseopts -D -a void o: A: G: W: C: F: P: S: X: a b c d e f g j k u v 'p=print' 'r=remove'
+complete:6> [[ -n '' ]]
+complete:8> [[ -n '' ]]
+complete:13> compdef '_bash_complete -o default -F __nvm' nvm
complete:13: command not found: compdef```

**Comment by mcornella** [comment]
Ok, then it is definite that if an upgrade doesn't fix it, it must be some other problem. In other words, if the message isn't
```
~/.oh-my-zsh/lib/directories.zsh:32: command not found: compdef
```
then there has to be some other culprit.

**Comment by slaterx** [comment]
In my case, I do not have NVM, but at the beginning of .zshrc I was setting my $PATH variable. 

I've moved that statement to the end of file and that fixed the issue.

**Comment by maxcr** [comment]
For me it was simply corruption of my default definition files. By reinstalling zsh, bash, and oh-my-zsh compdef began to create auto complete definition files correctly again. Don't force poweroff when using LVM on an SSD. If using LVM and an SSD, skip LVM and use ZFS. Checksumming filesystems go a lot farther than fsck.ext4.

**Comment by LLLY1025** [comment]
> In my case, I do not have NVM, but at the beginning of .zshrc I was setting my $PATH variable.
> 
> I've moved that statement to the end of file and that fixed the issue.

it works!I have NVM ,fixed the "command not found:compdef" by this method,thx!

**Comment by marcelodevops** [comment]
autoload -Uz compinit
compinit

**Comment by mruffieux** [comment]
Don't mean to open it again but in my case, I need both, as in

```shell
autoload -Uz bashcompinit
autoload -Uz compinit
bashcompinit
compinit
```

- `bashcompinit` seems throw `complete` not found away
- & `compinit` seems to take `compdef` error out

Cheers!

**Comment by sanriqing** [comment]
i fixed this problem by move `[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; # This loads nvm` under `[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion";  # This loads nvm bash_completion` . i do not understand why does help.
