### ISSUE TITLE
Git branch command will display into more mode

### ISSUE THREAD

**Issue by fireantzhang** [robbyrussell/oh-my-zsh#7847]
When using git branch command to see the branch of a warehouse, will enter more mode, the experience is not feeling very well.

As shown in the picture：
![git_branch_more](https://user-images.githubusercontent.com/5302051/57613353-39229000-75a9-11e9-9ef6-8ae0f0554288.gif)

Whether can adjust the other display mode.

**Comment by mcornella** [comment]
This is because by default git uses `less` as a pager. See https://stackoverflow.com/questions/48341920/git-branch-command-behaves-like-less/48342309
