### ISSUE TITLE
Remove support for yaourt for yay in archlinux plugin

### ISSUE THREAD

**Issue by TheKarlo95** [robbyrussell/oh-my-zsh#7848]
Since development of yaourt is stalled and will no longer be developed I suggest plugin should now use yay(anothe aur helper) for ya* aliases or at least should be supported alongside yaourt.

@seriousben

**Comment by mcornella** [comment]
It does support yay, and it will default to it if it's installed. See https://github.com/robbyrussell/oh-my-zsh/blob/f960e2be6f01abe5f185d668be661b57051322ac/plugins/archlinux/archlinux.plugin.zsh#L59-L86
