### ISSUE TITLE
Kitty breaks zsh tabcomplete/autocomplete

### ISSUE THREAD

**Issue by nicentra** [robbyrussell/oh-my-zsh#7852]
I'm assuming this is a font issue or rather an issue with how kitty handles fonts but just to be safe I'm asking here if it's a bug with omz or with my config:
When I start a command and tabcomplete this happens:
![image](https://user-images.githubusercontent.com/20487548/57833695-e8828100-77ba-11e9-87ae-90f24a69b067.png)
The first `cd` in the screenshot doesn't exist and it's just a display bug but still a bit annoying.

Does anyone know how to resolve if possible at all?

**Comment by mcornella** [comment]
This is normally an issue with `locale` not being set to a UTF-8 one. Try running `locale` and see available locales with `locale -a`.

**Comment by nicentra** [comment]
Hey @mcornella , that indeed fixed the issue, thank you very much! :)
