### ISSUE TITLE
zsh: command not found: z

### ISSUE THREAD

**Issue by AleksanderPopov** [robbyrussell/oh-my-zsh#7855]
Hello! I've used Z from homebrew, but recently found that there is actually built-in plugin in oh-my-zsh, so i tried to add it as follows:

```
plugins=(
  git
  z
  vi-mode
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)
```
running fresh terminal with zsh ( iterm2 ) and when I'm trying to use 'z' i see following error:

```
z project
zsh: command not found: z
```

while f.e. git plugin (and all the others) seems to work correctly.

Also if I manually source it via `source .oh-my-zsh/plugins/z/z.sh` it works as expected.

**Comment by mcornella** [comment]
Did you uninstall Homebrew's z?

**Comment by AleksanderPopov** [comment]
Yes

**Comment by mcornella** [comment]
Can I see your zshrc file?

**Comment by mcornella** [comment]
You're redefining the plugins array in [`.zsh_prompt`](https://github.com/AleksanderPopov/.dotfiles/blob/master/zshell/.zsh_prompt), which doesn't contain `z`.

**Comment by AleksanderPopov** [comment]
Yes, sorry.
