### ISSUE TITLE
Locally built zsh not showing a prompt

### ISSUE THREAD

**Issue by chuckisbusy** [robbyrussell/oh-my-zsh#7857]
I do not have access to root on this machine running CentOS 6.2. I run uname -a which yields:
`Linux dlxlogin.local 2.6.32-220.el6.x86_64 #1 SMP Wed Nov 9 08:03:13 EST 2011 x86_64 x86_64 x86_64 GNU/Linux` 
I have recently compiled zsh 5.7.1 from source to my ~/share/ directory. Zsh was tested with "make test" and had no failures. Running the zsh executable gives me my prompt: "dlxlogin%". I installed onhmyzsh using the curl command. Running zsh after installing .ohmyzsh then gave me errors:

```
/home/cad234/.oh-my-zsh/oh-my-zsh.sh:69: compinit: function definition file not found
/home/cad234/.oh-my-zsh/lib/directories.zsh:32: command not found: compdef
/home/cad234/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/home/cad234/.oh-my-zsh/plugins/git/git.plugin.zsh:83: command not found: compdef
```
I solved this problem as others have by setting the $FPATH and alternatively by adding ZSH_DISABLE_COMPFIX=true to my.zshrc. NOW, my problem is that after switching shells to zsh, I have no prompt. There is no error message and I'm not sure how to troubleshoot it. The only possible way for me to get back to my shell is to close the terminal or to keep pressing "ctrl + D" to kill zsh. Any ideas on why my prompt has disappeared?

**Comment by mcornella** [comment]
If this is an OMZ problem, `zsh -f` should still give you the `dlxlogin% ` prompt. If that's the case, you can run zsh in tracing mode and look at where it hangs: `zsh -xv`.

The `FPATH` thing shouldn't happen though if you've compiled zsh correctly, setting the appropriate arguments when running `./configure`. It's been a long time since I last compiled it from source so I can't tell you what the arguments are.

**Comment by chuckisbusy** [comment]
Thanks for the `zsh -xv` command. I did not know about that. It appears ohmyzsh was getting hung up on `+git_prompt_info:2> [[+git_prompt_info:2> git config --get oh-my-zsh.hide-status` and taking a really really long time. I fixed it by disabling `git_prompt_info` in my ~/.zshrc. Solution here: https://github.com/robbyrussell/oh-my-zsh/issues/5327#issuecomment-356883326

**Comment by mcornella** [comment]
Ok, then this is just the `git config` call taking too long? Can you reproduce that outside OMZ, with `zsh -f`?

**Comment by chuckisbusy** [comment]
Correct, I only had an issue when using OMZ. Otherwise, `zsh` and `zsh -f` worked fine. I disabled the git config for now and I have my prompt and everything else working.

**Comment by mcornella** [comment]
> Can you reproduce that outside OMZ, with `zsh -f`?

Does running `git config --get oh-my-zsh.hide-status` in `zsh -f` also take too long?

**Comment by chuckisbusy** [comment]
Yes, it hangs. It took about 4-5 minutes before I got my prompt back.

**Comment by mcornella** [comment]
Then the problem is with git, not OMZ. I don't really know how to fix the git config call though.
