### ISSUE TITLE
I see the default prompt after installing zsh

### ISSUE THREAD

**Issue by santosh9991** [robbyrussell/oh-my-zsh#7859]
I cannot see the theme getting reflected on my terminal even after installing zsh on mac. 
I have also added ZSH_THEME to ~/.zshrc file. I see % symbol on terminal. Below is the screen shot. I have followed the document and followed the procedure. 
![image](https://user-images.githubusercontent.com/16803672/57963616-6e521980-78ec-11e9-8750-a42b889ab4c0.png)

**Comment by mcornella** [comment]
It's probable ZSH_THEME is defined after OMZ sourced. Post your zshrc file please.

**Comment by santosh9991** [comment]
![image](https://user-images.githubusercontent.com/16803672/57971578-988bf180-7955-11e9-982c-3bdc8b90cb2b.png)

**Comment by mcornella** [comment]
You didn't install ohmyzsh or you're not using it in your zshrc file. Read the installation guide from the README.
