### ISSUE TITLE
cd and autojump failed reporting /usr/bin/env error

### ISSUE THREAD

**Issue by JackieLam** [robbyrussell/oh-my-zsh#7862]
**Describe the bug**

**To Reproduce**
1. Enable plugin '...'
2. Run command '...', _or_ try to complete command '...', _etc._
3. See error

**Expected behavior**

**Screenshots or recordings**
If applicable, add screenshots or record an [asciinema session](https://asciinema.org/) to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Zsh version [e.g. 5.6]
 - Terminal emulator [e.g. iTerm2]

**Additional context**

**Comment by mcornella** [comment]
You didn't fill out the questions? What does `which -a cd` show? Also post your zshrc file.
