### ISSUE TITLE
pass auto completion

### ISSUE THREAD

**Issue by Musikermomo** [robbyrussell/oh-my-zsh#7864]
Pass auto-completion isn’t working in zsh, instead it’s completing to whatever folder I’m currently in.
I added "pass" to the plugins array in my ~/.zshrc.
OMZ and zsh are up-to-date.

 - OS: Arch linux
 - Zsh version: 5.7.1
 - Terminal emulator: termite

Completion works fine in bash...

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` and restart zsh with `exec zsh`. When enabling plugins that add autocompletion a manual reset is currently needed (https://github.com/robbyrussell/oh-my-zsh/issues/7642).

**Comment by Musikermomo** [comment]
That worked perfectly, although I have no idea what I just did... Thank you very much!!

**Comment by adrienafl** [comment]
Also, update your FPATH for : FPATH=$(brew --prefix)/share/zsh-completions:$(brew --prefix)/share/zsh/site-functions:$FPATH

In the doc, site-functions aren't added which breaks pass autocomplete
