### ISSUE TITLE
aws: Getting grep error when using aws_profiles, etc

### ISSUE THREAD

**Issue by drummerjoe** [robbyrussell/oh-my-zsh#7872]
Newly installed aws plugin gives the following error on running aws_profiles:

`grep: ~/.aws/config: No such file or directory`

None of the other commands work as well.  I also had to add..

`export AWS_CONFIG_FILE="~/.aws/config"`

..to my .zshrc file as well b/c that doesn't seem to exist in real life?

**Comment by mcornella** [comment]
`aws_profiles` is currently not meant to be manually called, but only as part of completion of `asp` and `aws_change_access_key`. That said, there should be a check for the existence of that file in the completion function, I'm gonna add that.
