### ISSUE TITLE
I had installed oh-my-zsh success in root acount, but i can't use it on my new account of admin

### ISSUE THREAD

**Issue by scott8013** [robbyrussell/oh-my-zsh#7878]
centOS 7  useradd newaccount can not use oh-my-zsh

**Comment by mcornella** [comment]
Oh My Zsh is installed per-user, meaning if you installed it with root, it will only be set up to be used by root. You can change that by installing it in a location accessible by all users (see [custom directory instructions](https://github.com/robbyrussell/oh-my-zsh#custom-directory) in the README). Then, you need to copy the zshrc template (located in `$ZSH/templates/zshrc.zsh-template`), and fix the `ZSH=` line to point to the directory where you've installed OMZ. Auto-update will probably be affected though.

This is a bit hard to explain so feel free to ask about any doubts you have.
