### ISSUE TITLE
terraform state show item fails 

### ISSUE THREAD

**Issue by Nacer-BKRM** [robbyrussell/oh-my-zsh#7894]
Hi, 

I got a problem when i want to display a state item which contains brackets : 

terraform state show module.EC2_MyAPP_3.aws_instance.myapp[0]
zsh: no matches found: module.EC2_MyAPP_3.aws_instance.myapp[0]

same command tunning well on another shell. 

Nas.

**Comment by JSchwerberg** [comment]
Use quotes to wrap the string, like `terraform state show "module.EC2_MyAPP_3.aws_instance.myapp[0]"`.  Besides the fact that this is not a bug in the first place, this wouldn't be an Oh-my-zsh bug if it were -- it would be a ZSH bug.

**Comment by mcornella** [comment]
That's right, the square brackets `[` and `]` are used to match file names when not quoted. Using quotes fixes it, as Jason perfectly said.

**Comment by tarunlohumi** [comment]
> Use quotes to wrap the string, like `terraform state show "module.EC2_MyAPP_3.aws_instance.myapp[0]"`. Besides the fact that this is not a bug in the first place, this wouldn't be an Oh-my-zsh bug if it were -- it would be a ZSH bug.

I can't express how much this simple comment helped me. Thanks thanks thanks!

**Comment by ibottamike** [comment]
Thanks, I had a similar issue but with maps.  I'm adding comment as the syntax was slightly different referencing modules with a map of resources.  
I left the quotes in the map and wrapped the  state resource in single quotes.
 'module.module_name.aws_resource.resource_name["mapkey"]' resourceid

**Comment by gpgupta7891** [comment]
> Thanks, I had a similar issue but with maps. I'm adding comment as the syntax was slightly different referencing modules with a map of resources. I left the quotes in the map and wrapped the state resource in single quotes. 'module.module_name.aws_resource.resource_name["mapkey"]' resourceid

this one worked for me. thank you.

**Comment by minhvu178** [comment]
My god, this comment is such a lifesaver, thank you so much sir!

**Comment by m1n9o** [comment]
My god, this comment is such a lifesaver, thank you so much sir!
Much appreciated my brothers. 😉

**Comment by Aym3nTN** [comment]
> Use quotes to wrap the string, like `terraform state show "module.EC2_MyAPP_3.aws_instance.myapp[0]"`. Besides the fact that this is not a bug in the first place, this wouldn't be an Oh-my-zsh bug if it were -- it would be a ZSH bug.

This also was the solution when I only wanted to `terraform apply -target` a specific resource, thanks!
