### ISSUE TITLE
RubyMine Run Configuration Issues with Zsh

### ISSUE THREAD

**Issue by george-ma** [robbyrussell/oh-my-zsh#7895]
Hi, I tried zsh out yesterday but ended up deciding to switch back to regular bash. I ran the `uninstall_oh_my_zsh` script as well as ran `chsh -s /bin/bash` and `rm -rf .zsch` to get my shell defaulted to bash with my terminal. The issue comes up when I tried running programs in RubyMine, as it tries to execute the commands using /bin/zsh. I've tried setting the terminal setting in RubyMine's preferences to /bin/bash as well as ran a complete clean reinstall of the Application. One thing I noticed was odd though was after completely clean reinstalling RubyMine, /bin/zsh continues to be the default in RubyMine's terminal shell path, making me think this is a problem with my environment variables? Any help would be appreciated. Thanks.

![image](https://user-images.githubusercontent.com/20158582/58651658-d686ff00-82df-11e9-895a-eba2f901a27c.png)

This is what it looks like when I try running a program on RubyMine. I've also checked all the run configuration settings and nothing seems out of the ordinary / references zsh directly

**Comment by mcornella** [comment]
After you run `chsh` you need to quit your user session and log back in, maybe that's the solution.

**Comment by mcornella** [comment]
Also check that you haven't changed the shell parameter for the RubyMine's Terminal: https://www.jetbrains.com/help/ruby/settings-tools-terminal.html

**Comment by george-ma** [comment]
oops forgot to update this, ended up fixing this problem with an actual clean uninstall of RubyMine (deleting all the RubyMine/Jetbrains related folders in /Library) thanks for the help though Marc!
