### ISSUE TITLE
Plugin not found even though not specified anywhere

### ISSUE THREAD

**Issue by doronkatz** [robbyrussell/oh-my-zsh#7911]
Hi folks,

So I just moved to iTerm2 and zsh, along with OMZ. I am getting this error constantly when opening up a new terminal session:
```
[oh-my-zsh] plugin 'hub' not found
[oh-my-zsh] plugin 'colored-man-page' not found
```

Now, even uninstalling and installing OMZ I get this. I am not sure where this plugin is called but my `zshrc` file contains:
```
plugins=(git wd last-working-dir)
export ZSH=/Users/doron.katz/.local/share/oh-my-zsh
source $ZSH/oh-my-zsh.sh
source /Users/doron.katz/.local/share/oh-my-zsh/plugins/colored-man-page/colored-man-pages.plugin.zsh
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"export PATH="/usr/local/sbin:$PATH"
POWERLEVEL9K_MODE='nerdfont-complete'
source  ~/powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh dir vcs newline status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
```

I have even added `source /Users/doron.katz/.local/share/oh-my-zsh/plugins/colored-man-pages/colored-man-pages.plugin.zsh`. 

The folder exists, but not sure who is calling that plugin anyway.. THe same for HUB.

Please help!

**Comment by mcornella** [comment]
Make a debug log of the initialization with the command
```zsh
zsh -xvic exit &> ~/omz-debug.log
```
and post the resulting file so I can take a look.

**Comment by doronkatz** [comment]
OK thanks. Solved it!

The log file tells me which `.zshrc` its using, and its there.

**Comment by doronkatz** [comment]
And attached!

[omz-debug.log](https://github.com/robbyrussell/oh-my-zsh/files/3258840/omz-debug.log)

**Comment by mcornella** [comment]
Yes, there is another zshrc file at `/Users/doron.katz/.config/zsh/.zshrc` which has those plugins enabled.
