### ISSUE TITLE
Django tab completion does not work on cloned projects

### ISSUE THREAD

**Issue by HymanZHAN** [robbyrussell/oh-my-zsh#7927]
**Describe the bug**

The Django plugin does not work on a cloned project but works on projects created locally.

**To Reproduce**

Enable plugin `django`.

Say I have a project `profile_project_remote` on GitHub that's created on another machine and I have django installed on my local machine.

If I clone the remote project **that's not created locally by myself**:

```
git clone git@github.com:HymanZHAN/profile_project_remote.git
cd profile_project_remote
python manage.py <Hit Tab>
// A list of local files shows up.
manage.py         Pipfile           Pipfile.lock      profile_project/  profiles_api/
```

If I start a new project locally:

```
django-admin startproject profile_project_local
cd profile_project_local
python manage.py <Hit Tab>
// Django commands show up.
cleanup                    -- remove old data from the database
compilemessages            -- compile .po files to .mo for use with gettext
createcachetable           -- creates table for SQL cache backend
createsuperuser            -- create a superuser
dbshell                    -- run command-line client for the current database
diffsettings               -- display differences between the current settings and Django defaults
dumpdata                   -- output contents of database as a fixture
flush                      -- execute 'sqlflush' on the current database
inspectdb                  -- output Django model module for tables in database
loaddata                   -- install the named fixture(s) in the database
makemessages               -- pull out all strings marked for translation
reset                      -- executes 'sqlreset' for the given app(s)
runfcgi                    -- run this project as a fastcgi
runserver                  -- start a lightweight web server for development
```

**Expected behavior**

The autocompletion should also work on the cloned project.

**Screenshots or recordings**

![cloned_project](https://user-images.githubusercontent.com/26806995/59456452-56cf5900-8de4-11e9-82e5-58e8f2d8307c.png)

![local_project](https://user-images.githubusercontent.com/26806995/59456456-5a62e000-8de4-11e9-927d-51923d52d3c1.png)

**System:**
 - OS: PopOS 19.04
 - Zsh version: zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: Tilix & Gnome Terminal

**Additional context**

**Comment by mcornella** [comment]
Have you tried resetting the completion cache (`rm ~/.zcompdump*`) after enabling the plugin? See https://github.com/robbyrussell/oh-my-zsh/issues/7642

**Comment by HymanZHAN** [comment]
@mcornella I just tried but it did not help. I am still unable to get tab completion for my cloned project. It continues to work on the local project though.

**Comment by mcornella** [comment]
Can you capture a trace of the completion? To do so, type in `python manage.py` in one of the cloned repositories where completion fails and then press `CTRL`+`X` followed by `?`. It should capture a trace and tell you to press up-arrow, which will tell you in which file the trace was saved (it will be something like `/tmp/zsh5python1`).

**Comment by HymanZHAN** [comment]
![Screenshot from 2019-06-14 12-49-16](https://user-images.githubusercontent.com/26806995/59524835-d885bc00-8ea2-11e9-93da-15631b94fdcb.png)

The trace file is here:

[zsh17766python2.txt](https://github.com/robbyrussell/oh-my-zsh/files/3291493/zsh17766python2.txt)

**Comment by mcornella** [comment]
For some reason it's using zsh's official django completion instead of the one provided by the plugin. Is it possible the problem happens after you activate the virtualenv?

**Comment by HymanZHAN** [comment]
The behavior is the same before and after I activate virtualenv via pipenv.

![Screenshot from 2019-06-15 15-25-08](https://user-images.githubusercontent.com/26806995/59555529-f413c400-8f81-11e9-8358-e5172c4b154f.png)

**Comment by mcornella** [comment]
That's weird... Can you also trace the correct completion of the one generated with startproject?

**Comment by HymanZHAN** [comment]
![success_completion](https://user-images.githubusercontent.com/26806995/59628616-138c2780-910f-11e9-9634-09bd599810ed.png)

Trace file:

[zsh32566python2.txt](https://github.com/robbyrussell/oh-my-zsh/files/3298405/zsh32566python2.txt)

**Comment by mcornella** [comment]
Oh I can see why that is, it's a simple executable permission bit problem. Here's where the `_django` completion forks: https://github.com/zsh-users/zsh/blob/fd4056f4edb12000ac5b0181aef8bb741e60801c/Completion/Unix/Command/_django#L5-L8

The ultimate culprit is that the `manage.py` file isn't executable, therefore the completion script enters the if, calls `_default` (which is responsible for delivering the default completion, i.e. file entries) and it exits.

When the completion works it's because manage.py has the executable bit set. So just `chmod +x` the manage.py file and it should all work fine.

I'm not sure why your system uses zsh's default completion of django instead of the one provided by the django plugin, but that's something else entirely.

**Comment by HymanZHAN** [comment]
That works! Thank you very much for your help!
