### ISSUE TITLE
Autocomplete for custom function?

### ISSUE THREAD

**Issue by Luc45** [robbyrussell/oh-my-zsh#7930]
Considering that I have this function in `~/.zshrc`:

```
function work() {
    cd /home/lucas/work/$1
}
```

And these folders:

```
/home/lucas/work/foo
/home/lucas/work/bar
```

How can I type `work f` and press "tab" to get `work foo`?

**Comment by mcornella** [comment]
See https://unix.stackexchange.com/a/65071. You'd make a function `_work` and link it to the work function you've made with `compdef _work work`. Full thing:
```zsh
function work() {
    cd /home/lucas/work/$1
}
_work() {
    _files -W /home/lucas/work
}
compdef _work work
```
