### ISSUE TITLE
Uninstall script syntax error

### ISSUE THREAD

**Issue by ShlomoRosenheimer** [robbyrussell/oh-my-zsh#7932]
**Describe the bug**
```
machine% sh ~/.oh-my-zsh/tools/uninstall.sh
Are you sure you want to remove Oh My Zsh? [y/N] y
': not a valid identifiers/uninstall.sh: line 1: read: `confirmation
/Users/ph/.oh-my-zsh/tools/uninstall.sh: line 45: syntax error: unexpected end of file
machine%
```

**To Reproduce**
just run the uninstall

**Expected behavior**
to work

**System:**
 - OS: mojave
 - Zsh version 5.7.1
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
Can you cat `~/.oh-my-zsh/tools/uninstall.sh` and post it here?

**Comment by ShlomoRosenheimer** [comment]
somehow my installation folder was named ".oh-my-zsh^M" after renaming, the uninstall worked.

**Comment by mcornella** [comment]
In macOS `/bin/zsh` is provided by the operating system itself, if that's the one you see.
