### ISSUE TITLE
Support line number when using suffix alias

### ISSUE THREAD

**Issue by victorliun** [robbyrussell/oh-my-zsh#7938]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

No

**Is your feature request related to a problem? Please describe.**

I often uses suffix alias to edit files. e.g. type in `example.py` will open my favourite editor.
But if I type `example.py:100` and want the cursor be on the 100 line of `example.py`, it will complain file `example.py:100` not found. I have tried a few attempts to config this. but it doesn't work.

**Describe the solution you'd like**

My current config is 
`alias -s py=te`
I have tried below but it doesn't work.
1. `alias -s py*=te`
2. `alias -s py(*)=te`
3. `alias -s py(:*)=te`
If any of this works, it will be really handy to open a file on a certain line.

**Describe alternatives you've considered**

No
**Additional context**

If anyone can point to me how to archieve this. then I can possibly do a PR

**Comment by mcornella** [comment]
This isn't possible because a colon is a valid filename character, and zsh isn't programmed to allow this.
