### ISSUE TITLE
Cannot activate brew plugin to work

### ISSUE THREAD

**Issue by HaoyangFan** [robbyrussell/oh-my-zsh#7941]
Hi, even if I've already enabled the `brew` plugin in `~/.zshrc`, and then source the file using `source ~/.zshrc`, finally restart the terminal, the `brews` command is still not found

part of my `.zhsrc`:
```sh
# plugins
plugins=(
  git
  autojump
)

# set autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# set zsh syntax highlighting
source /Users/haoyangfan/Documents/settings/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

What I got after restarting the terminal
```
❯ brews
zsh: command not found: brews
```

I think `brew` plugin is already bundled with `oh-my-zsh` so that I don't need to install it again by myself? 

Any help will be appreciated!

**Comment by mcornella** [comment]
The command is `brew`, not `brews`. You do need to enable the brew plugin if you want to use the `brews` **alias** though, see [the README](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/README.md).

**Comment by HaoyangFan** [comment]
@mcornella Unfortunately it still doesn't work, now I've enabled the `brew` plugin in my `~/.zshrc`:
```sh
# plugins
plugins=(
  git
  brew
  autojump
)

# set autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# set zsh syntax highlighting
source /Users/haoyangfan/Documents/settings/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
Then I do `source ~/.zshrc` and relaunch the terminal app. Then whenever I try to run `brews`, as you mentioned, a alias defined by `brew plugin`, I still get the following error
```sh
❯ brews
zsh: command not found: brews
```
Any idea?

**Comment by mcornella** [comment]
Is this the only thing in your zshrc file? You're lacking the Oh My Zsh settings, like the ZSH variable definition and the line sourcing OMZ. Have you installed Oh My Zsh like it says in the README?

**Comment by HaoyangFan** [comment]
Sorry, I made a horrible noob mistake: I just realize that the `~/.zshrc` already comes with 
```sh
plugins = (
   git
)
....
````
in the middle of file. However, I am actually repeating that again by the end of the file
```
plugins = (
    git
    brew
    autojump
)
```
Apparently this won't override the previous setting of plugins so it won't work. I've fixed this error already. Thank you so much for your help!
