### ISSUE TITLE
Foreign language WINE applications break with oh-my-zsh active due to locale

### ISSUE THREAD

**Issue by alecschule** [robbyrussell/oh-my-zsh#7942]
Hello,

The high level issue I'm having is that I regularly run several Windows applications from the command line using WINE, and some of these programs do not work anymore after installing oh-my-zsh.

I am using Arch Linux. I used the oh-my-zsh installation script from this repo. I confirmed this behavior with no oh-my-zsh plugins or themes active.

I restored my old `.zshrc` to test, and I confirmed that the applications do run in vanilla zsh, but do not run in oh-my-zsh with no other changes.

One thing all the broken applications have in common is that they are expected to only work when run in a Japanese locale. I usually do this with a terminal command of the form `LANG=ja_JP.UTF-8 wine ...`

Is there an expected change of behavior when using the LANG variable in oh-my-zsh compared to vanilla zsh?

I am not positive that the problem is related to the foreign language, but it is my best guess at the moment. 

These WINE applications are an important part of my workflow, so I would greatly appreciate any help you can give in overcoming this issue. I am happy to do anything I can on my end to provide more information.

**Comment by mcornella** [comment]
If you think this is related to locale post the output of `locale` both with OMZ and without it. It would be helpful as well to know what you mean specifically by "broken applications" and "do not work anymore".

**Comment by alecschule** [comment]
Thank you for your reply.

vanilla zsh:  
```
$ locale

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
```
$ LANG=ja_JP.UTF-8 locale

LANG=ja_JP.UTF-8
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=
```
**with oh-my-zsh:**
```
$ LANG=ja_JP.UTF-8 locale
LANG=ja_JP.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=
```
Please note that `LC_CTYPE` is not updated by the `LANG` variable, which I believe is a problematic bug. 

I can now use a shell command of the form `LANG=ja_JP.UTF-8 LC_CTYPE=ja_JP.UTF-8 wine ...`, and my WINE applications work again.

FYI a "broken" WINE application in this case simply crashes on startup.

Thank you for pushing me to look at the `locale` output. I now have a usable workaround, but I hope you consider treating this behavior of `LC_CTYPE` as a bug, because I believe it will cause issues in many cases where the `LANG` variable is used.

**Comment by mcornella** [comment]
It's possible that this happens because of these lines https://github.com/robbyrussell/oh-my-zsh/blob/7b2c4327e7d40ec17b72fe7fce3031dfc92fb165/lib/misc.zsh#L34-L37
but I don't see why given that `LC_CTYPE` isn't empty before sourcing OMZ, which is one of the conditions.

> Please note that `LC_CTYPE` is not updated by the `LANG` variable, which I believe is a problematic bug.

This is by design. If you want to override `LC_CTYPE` you can use `LC_ALL` instead of `LANG`, which sets all `LC_*` locale env variables.

**Comment by alecschule** [comment]
> but I don't see why given that LC_CTYPE isn't empty before sourcing OMZ, which is one of the conditions.

I do not intentionally set `LC_CTYPE`, but it appears to have been explicitly defined nonetheless.
```
➜  ~ locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
➜  ~ unset LANG
➜  ~ locale
LANG=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
Once again, I disable oh-my-zsh:
```
mv .zshrc .zshrc.oh-my-zsh
mv .zshrc.pre-oh-my-zsh .zshrc
```
Opening a new terminal window shows that `LC_CTYPE` is not explicitly set.
```
% locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
% unset LANG
% locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
My conclusion is that something related to oh-my-zsh sets `LC_CTYPE` explicitly. This behavior is present with no plugins and the default theme. Of course, I've only tested on my computer, so I am curious if this is reproducible. 

> This is by design. If you want to override LC_CTYPE you can use LC_ALL instead of LANG, which sets all LC_* locale env variables.

I accept that this is the correct behavior for when `LC_CTYPE` is explicitly defined. I am still not sure *why* `LC_TYPE` is explicitly defined with oh-my-zsh.

**Comment by mcornella** [comment]
Can you check if commenting out the lines in https://github.com/robbyrussell/oh-my-zsh/issues/7942#issuecomment-506684475 the problem disappears?

**Comment by alecschule** [comment]
Yes, with those lines commented, the problem disappears.
```
➜  ~ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
➜  ~ unset LANG
➜  ~ locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
