### ISSUE TITLE
Git prompt not documented

### ISSUE THREAD

**Issue by timkingman** [robbyrussell/oh-my-zsh#7944]
**Describe the bug**
I can't find any documentation on the git prompt.

**To Reproduce**
Docs -> Plugins
Try to click https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#git-prompt

**Expected behavior**
Documentation on git prompt. What is +/-? What is the lightning bolt?

**Comment by mcornella** [comment]
I've fixed the link to point to the [plugin README](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git-prompt/README.md). Thanks for the heads up.
