### ISSUE TITLE
Git Prompt 

### ISSUE THREAD

**Issue by zhao-li** [robbyrussell/oh-my-zsh#7945]
Hi Oh-My-Zsh Team,

Thank you for making such a wonderful product.  I am trying to create a custom theme and for the most part got it working.

The only quirk that I cannot figure out is why when I press tab to autocomplete/autosuggest, the prompt gets munched up.

I tried removing the emoji's and special characters, but the only time this issue does not happen is when the git information is not displayed at all.

Attached are some screenshots of what’s happening.

This is my prompt configuration:
https://github.com/zhao-li/dots/blob/master/custom/themes/zhaoli.zsh-theme

Any ideas, how I can fix my prompt so tabbing out doesn’t munch the prompt?

Thank you for your time
<img width="720" alt="NoGit_NoMunching" src="https://user-images.githubusercontent.com/2177879/59956574-d2f11e80-942c-11e9-9286-ccc023517fa0.png">
<img width="717" alt="WithGit_HasMunching" src="https://user-images.githubusercontent.com/2177879/59956577-d8e6ff80-942c-11e9-98d1-1dec7319270b.png">

**Comment by mcornella** [comment]
Multiline prompts tend to have this problem. Make sure you don't have `COMPLETION_WAITING_DOTS=true` enabled in your zshrc file.

**Comment by zhao-li** [comment]
@mcornella thank you for the suggestions.  The problem still exists when I made the prompt into a single line and when `COMPLETION_WAITING_DOTS=true` was commented out.  I also tried setting it to `COMPLETION_WAITING_DOTS=false`

Thank you for taking the time to offer the suggestions.  Would you happen to know where else I might be able to go for guidance on this issue?  Is there a user community forum somewhere?

Thanks again and have a great day 🙂

**Comment by mcornella** [comment]
If this still happens then I'm out of ideas, try asking on the [users mailing list](http://zsh.org/mla).

**Comment by zhao-li** [comment]
@mcornella thank you for linking me to the mailing list.  It's going to be the first time I attempt to use a mailing list.  Thank you again for all of your help and guidance. :)

**Comment by romkatv** [comment]
This is the problem:

```zsh
PROMPT+='%{$(git_info)%}'
```

Fix:

```zsh
PROMPT+='$(git_info)'
```

`%{...%}` is telling ZSH that `...` does not move the cursor. `$(git_info)` does move cursor, hence `%{$(git_info)%}` is misleading ZSH.

P.S.

If you want a fast Git prompt (10+ times faster than in any theme bundled with Oh-My-Zsh), use [gitstatus](https://github.com/romkatv/gitstatus/) plugin.

1. Install:

```zsh
git clone https://github.com/romkatv/gitstatus.git $ZSH_CUSTOM/plugins/gitstatus
```

2. Add `gitstatus` to [`plugins`](https://github.com/zhao-li/dots/blob/6945dddbe820673c71529df0ef985e710f0b604e/custom/oh-my-zsh.sh#L74).

3. Replace `zhaoli.zsh-theme` with this:

```zsh
function zhaoli-set-prompt() {
  emulate -L zsh

  RPROMPT=''
  PROMPT="%F{237}${(pl.$((COLUMNS-1))..─.)}%f"$'\n' # horizontal line
  PROMPT+='%F{cyan}%n%f '                           # user
  PROMPT+='%F{green}%~%f '                          # current directory

  if gitstatus_query zhaoli && [[ $VCS_STATUS_RESULT == ok-sync ]]; then
    PROMPT+='%F{magenta}'
    PROMPT+=${${VCS_STATUS_LOCAL_BRANCH:-@${VCS_STATUS_COMMIT}}//\%/%%}  # escape %
    if (( VCS_STATUS_COMMITS_BEHIND )) PROMPT+=↓
    if (( VCS_STATUS_COMMITS_AHEAD )) PROMPT+=↑
    if (( VCS_STATUS_HAS_UNSTAGED || VCS_STATUS_HAS_UNTRACKED )); then
      PROMPT+=💩
    elif (( ! VCS_STATUS_HAS_STAGED )); then
      PROMPT+=🦄
    fi
    PROMPT+='%f '
  fi

  # '#' if root, '%' otherwise; green on success, red on error.
  PROMPT+='%F{%(?.green.red)}%#%f '

  # Enable/disable correct prompt expansions.
  setopt noprompt{bang,subst} promptpercent
}

(( $+functions[gitstatus_start] )) || {
  print -P '%F{red}[ERROR]%f zhaoli theme requires gitstatus plugin' >&2
  return 1
}

gitstatus_stop zhaoli && gitstatus_start zhaoli
autoload -Uz add-zsh-hook
add-zsh-hook precmd zhaoli-set-prompt
```

4. Customize to your liking. See [gitstatus docs](https://github.com/romkatv/gitstatus/blob/master/README.md).

**Comment by zhao-li** [comment]
@romkatv wow thank you so much for taking the time to write your post.  Your example code to fix the problem along with explanation helps tremendously.  I can understand why `%{...%}` is helpful [here](https://github.com/robbyrussell/oh-my-zsh/issues/2314#issuecomment-32155974), but not where I was using it in my prompt.

Thank you also for pointing me to gitstatus and your detailed example code for that as well.

I think I'm finally at a good place with my prompt and using zsh with oh-my-zsh.

My last remaining issue is with [hyper.js not properly handling emoji's and causing the prompt to be off by one character](https://github.com/zeit/hyper/issues/3516).  Unless you know of some easy fix for that as well, I'm going to just wait for hyper.js to fix that issue ticket.

Thanks again for your time and effort.

**Comment by romkatv** [comment]
> My last remaining issue is with hyper.js not properly handling emoji's and causing the prompt to be off by one character. Unless you know of some easy fix for that as well, I'm going to just wait for hyper.js to fix that issue ticket.

The problem is that ZSH thinks that some emoji in your prompt is a wide character (takes as much space as `xx`) but Hyper renders it as a narrow character (as much space as `x`). To work around this problem, you can tell ZSH that the emoji is indeed narrow.

Instead of this:

```zsh
PROMPT='🦀'
```

Do this:

```zsh
PROMPT='%{%G🦀%}'
```

`'%{%G...%}'` tells ZSH that `...` takes one character on the screen.

**Comment by zhao-li** [comment]
@romkatv amaze-balls!  It worked 💯 Thank you so much for sharing all of your knowledge.

Sorry for continuing to add more...😅

Is there an easy way to figure out if the shell is inside hyper or another terminal app?  So something like this?:
```
if [ #using hyper# ]
then
   PROMPT='%{%G🦀%}'
else
   PROMPT='🦀'
fi
```

Thank you again for your time and patience.  I'm good with where you've taken me to, but just thought I'd ask in case you know some easy way of doing it.  I would have never figured out what to Google to get to `%{%G🦀%}`.

**Comment by romkatv** [comment]
@zhao-li 

> Is there an easy way to figure out if the shell is inside hyper or another terminal app?

```zsh
if [[ $TERM_PROGRAM == 'Hyper' ]]; then
   PROMPT='%{%G🦀%}'
else
   PROMPT='🦀'
fi
```

**Comment by zhao-li** [comment]
@romkatv that did it!  Thanks for helping me transition to zsh and oh-my-zsh. 🍾🏁
