### ISSUE TITLE
Fix bad colors on Mac Terminal

### ISSUE THREAD

**Issue by ridhwaans** [robbyrussell/oh-my-zsh#7949]
**Describe the bug**

Currently on Mac Mojave 10.14, the CLI prompt in Terminal is unsightly. Power line bar is almost blacked out with very dark colors making the text unreadable. Using the default theme agnoster that came with installing oh-my-zsh. No issues with iTerm2

**To Reproduce**

Set zsh as the default,  
The few following settings in .zshrc sourced at time of events  
```  
...
 source $HOME/.zsh/bundle/bin/antigen.zsh
 antigen use oh-my-zsh
 antigen bundle git
antigen theme agnoster
```  
Launch Terminal,   
Use default preferences and Basic profile, set Font to Roboto Mono for Powerline    
Observe appearance  

**Expected behavior**

On default Terminal, while on zsh and using agnoster theme, I expect a clear cli prompt with light colors, readable text on a white background.

**Screenshots or recordings**

![image](https://user-images.githubusercontent.com/1103336/59986245-e99d9e00-9603-11e9-8b6c-a8a17531bd8c.png)

**System:**
 - OS: Mac Mojave 10.14
 - Zsh version: latest
 - Terminal emulator: Mac default Terminal 

**Additional context**
  
Do I need to change color bit depth

**Comment by mcornella** [comment]
The agnoster theme is configured to be used on a dark terminal by default, you can choose the light version by setting `SOLARIZED_THEME=light` before OMZ is sourced. See https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme#L37-L40

You could also change the appearance of Terminal.app to choose a dark color scheme.
