### ISSUE TITLE
Multiple users will use original install

### ISSUE THREAD

**Issue by alexa-v2** [robbyrussell/oh-my-zsh#7953]
**Describe the bug**

When I install oh-my-zsh on one user, installing on another user fails. It says it's already installed, citing the other user's folder. Also everything links back to the original users home folder
**To Reproduce**

1. Install for user1
2. Switch to user2
3. Oh-my-zsh refused to install, and if I manually set up ,zshrc it says that I need to take ownership of user1's home directory
**Expected behavior**

Oh-my-zsh to allow each user to install and have their own settings
**Screenshots or recordings**

**System:**
 - OS: Ubuntu 18.04
 - Zsh version: 5.4.2
 - Terminal emulator [e.g. iTerm2]: none, using SSH session

**Additional context**

**Comment by mcornella** [comment]
This is because the $ZSH variable is exported, so it lives through to the other user session. As a temporary workaround run `unset ZSH` and it'll work again.

We should change that to be a normal variable though, but there are many parts of the codebase that need changing.

**Comment by alexa-v2** [comment]
Didn't help

Still getting:

    [oh-my-zsh] Insecure completion-dependent directories detected:

And directory listed are from user1. To be clear I'm logging directly in from user2

**Comment by mcornella** [comment]
I should clarify that you should remove the .zshrc file from user2 and install OMZ again, *after* having executed `unset ZSH`.

**Comment by grimaldodev** [comment]
@mcornella Hi, Im using a mac, I follow your steps to use the oh-my-zsh in multiple users but is not working, I follow other solutions but is not working. Exist a guide to install in 2 users/sessions in Mac?

```bash
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 root  admin   96 Nov 17 14:28 /usr/local/share/zsh
drwxrwxr-x  5 root  admin  160 May  7  2019 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```
Thanks!

**Comment by mcornella** [comment]
> ```shell
> [oh-my-zsh] If the above didn't help or you want to skip the verification of
> [oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
> [oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
> ```

If you're running a multiple-user setup use these instructions to bypass the completion directories verification. `ZSH_DISABLE_COMPFIX=true` before OMZ is sourced in every user's zshrc file.

**Comment by grimaldodev** [comment]
was my first solution but it doesn't work, I still have the same issue with the folder permissions, the issue here is every time I made some change into a session the other session break even if the fix is made in both.

**Comment by mcornella** [comment]
You need to set up a user and group that allows all users to read it, and you need to probably redefine the `$ZSH_CACHE_DIR` variable to a directory that each user controls, like `$HOME/.cache/ohmyzsh`.

For example, user `root` and group `users` (sometimes that's a valid group, you need to find one where your users belong). Then, `chmod -R g+r /path/to/ohmyzsh`. Then, in the zshrc of each user put these before OMZ is sourced:
```zsh
ZSH_DISABLE_COMPFIX=true
ZSH_CACHE_DIR="$HOME/.cache/ohmyzsh"
mkdir -p "$ZSH_CACHE_DIR"
```
