### ISSUE TITLE
Zsh does not work like bash

### ISSUE THREAD

**Issue by gabrielgambarra** [robbyrussell/oh-my-zsh#7954]
I followed step by step of installation guide but zsh does not find some components for example `npm`.

If I run `npm version` in zsh, it says: `comand not found: npm`

But I go to bash and run the same command, it works. And then in the same window if I go back to zsh and run `npm version`, it works normally.

I wonder if it's happening with other things and I didn't try yet.

My question is: how do I turn all the bash commands to zsh?

**Comment by OvermindDL1** [comment]
You don't have anything in one of the bash-only files that is adding things to your bash path?  `whereis npm` and is that path in your global `$PATH`?

**Comment by mcornella** [comment]
This is due to some directories missing from the `$PATH` variable in zsh, but not in bash. Look at the `~/.bashrc` and `~/.bash_profile` files for a line exporting `$PATH` and add that to the `~/.zshrc` file (there's a line at the top you can modify).

**Comment by gabrielgambarra** [comment]
I've just solved this.

I switch to bash and then I used the commands bellow

`curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | zsh`

`source ~/.profile`

`nvm ls-remote`

`nvm install v10.16.0`

After this I turn back to zsh and it was working.

**Comment by shaztri** [comment]
> This is due to some directories missing from the `$PATH` variable in zsh, but not in bash. Look at the `~/.bashrc` and `~/.bash_profile` files for a line exporting `$PATH` and add that to the `~/.zshrc` file (there's a line at the top you can modify).

Checked my .bashrc file and saw some export parth related to npm .added those toh .zshrc and it is fixed now. :D Thanks
