### ISSUE TITLE
`/bin/zsh -c nvm` results in cmd not found, but running `nvm` works fine

### ISSUE THREAD

**Issue by MattIPv4** [robbyrussell/oh-my-zsh#7957]
**Describe the bug**

If I run `nvm` direct from terminal, which is using zsh, it works fine.
If however, I run `/bin/zsh -c nvm` in that same terminal, I get a command not found error.

**To Reproduce**

1. Have zsh installed and as the default terminal
2. Have nvm installed correctly and setup in ~./zshrc
3. Run `nvm` in terminal - should work
4. Run `/bin/zsh -c nvm` - should fail

**Expected behavior**

I would expect `/bin/zsh -c nvm` to work correctly unless I've missed something?

**Screenshots or recordings**

![image](https://user-images.githubusercontent.com/12371363/60101903-82433380-9754-11e9-845b-341c7b0950e3.png)

**System:**
 - OS: macOS 10.14.4
 - Zsh version 5.3
 - Terminal emulator ?? Default macOS terminal

**Additional context**

Discovered this whilst configuring custom bash run scripts in RubyMine.

**Comment by mcornella** [comment]
Running `nvm` requires loading it. Since you're running zsh with `-c`, zsh doesn't read the rc files (mainly, `.zshrc`) which is where I believe you're sourcing nvm. If you want it to do that, you should pass also the `-i` flag to zsh, for `interactive`.

**Comment by MattIPv4** [comment]
@mcornella Ah, I had missed something, `-i`. Thank you!
