### ISSUE TITLE
Unable to create file filename*.txt using vim on terminal

### ISSUE THREAD

**Issue by akashgudadhe1** [robbyrussell/oh-my-zsh#7963]
I want to create a file(filename*.txt) using Vim editor on Terminal.But I am unable to create it.It is possible to create such file using bash shell.

**Describe the bug**
          I want to create a file(filename*.txt) using Vim editor on Terminal.As I have to use filename like file*1.txt but zsh is giving me error. 

**To Reproduce**
1. Open Terminal
2. zsh (Enter) Entering into zsh
3. Run command 'vi file*1.txt '
4. See error 'zsh: no matches found: file*1.txt'

**Expected behavior**
          I want to create a file named 'file*1.txt' using vim editor on zsh.I am able to create this file successfully using bash shell.

**Screenshots or recordings**
https://imgur.com/uGJtgDA

**System:**
 - OS: Ubuntu 18.04.2 LTS
 - Zsh version zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator xterm-256color

**Comment by lhorace** [comment]
Hello there,

ZSH is interpreting that file name as a glob, to avoid situations like this, wrap it in quotes!

Best Regards.

**Comment by mcornella** [comment]
As Horace said: `vi "file*1.txt"`.

Note that stars (`*`) are invalid filename characters under Windows, just in case you ever use it.

**Comment by akashgudadhe1** [comment]
> As Horace said: `vi "file*1.txt"`.
> 
> Note that stars (`*`) are invalid filename characters under Windows, just in case you ever use it.

No I'am using Linux.* is completely valid in bash.I have first examined that and then posted here.

**Comment by mcornella** [comment]
I know that. I'm telling you just in case those files ever have to be used under Windows.
