### ISSUE TITLE
⚙️[wiki]: why wiki editing is public.

### ISSUE THREAD

**Issue by pranshuchittora** [robbyrussell/oh-my-zsh#7965]
Check this wiki page =>  https://github.com/robbyrussell/oh-my-zsh/wiki/This-seems-to-be-public

**Describe the bug**
access rights

**To Reproduce**

**Expected behavior**
Only maintainers can edit this.

**Fix**

![Screenshot from 2019-06-28 17-27-54](https://user-images.githubusercontent.com/32242596/60340948-a6a84580-99ca-11e9-9686-7c218e1d5a99.png)

**Comment by mcornella** [comment]
The wiki is public so that people outside the project can add information in the External plugins / themes sections, as well as make adjustments to the documentation. So far it's worked great, by relying on people's good faith.
