### ISSUE TITLE
Tab complete moves the cursor to a new upper line

### ISSUE THREAD

**Issue by saifrim** [robbyrussell/oh-my-zsh#7968]
**Describe the bug**

Each time I autocomplete on a prefix search matching multiple entries the cursor will go up 2 lines

**To Reproduce**

1. Apply the config
```
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"

SPACESHIP_PROMPT_ORDER=(dir git venv exec_time line_sep battery jobs char)
SPACESHIP_VENV_SYMBOL=🐍·
SPACESHIP_VENV_COLOR=yellow
SPACESHIP_PROMPT_SEPARATE_LINE=true

plugins=(
    git sudo colorize zsh-autosuggestions zsh-syntax-highlighting
    git-extras virtualenvwrapper django heroku jira
)

source $ZSH/oh-my-zsh.sh
```
2. `cd <some_chars_to_match_multiple_folders>`
3.  Press `Tab`

**Expected behavior**

The cursor should remain on the same line

**Screenshots or recordings**

![multi_line_zsh_problem](https://user-images.githubusercontent.com/11786642/60390106-5ec31480-9ad7-11e9-952a-c2511406a777.gif)

**System:**
 - OS: macOS 10.13.6
 - Zsh version: 5.7.1
 - Terminal emulator: iTerm2

**Comment by CaderHancock** [comment]
I am having a similar but slightly different problem. 

➜  ~ cd Dow <tab>   Expands normally 
➜  ~ cd Downloads/

A successive tab expands into

➜  ~ cdcd Downloads/
connman-ncurses-git/      dotfiles-arch-master/  yay/  

the first 2 letters of the line are duplicated and remain until a newline. This also occurs on history scrollback. I used a fresh install of ohmyzsh. None of this behavior exists after uninstalled. 

OS: Arch
ZSH 5.7.1
Term: terminator 1.91 && konsole 19.04.2 && termite v15

**Comment by saifrim** [comment]
> None of this behavior exists after uninstalled.

Indeed I've done a fresh install using `brew` and all works fine.

**Comment by CaderHancock** [comment]
A fresh install of zsh or oh-my-zsh?

**Comment by mcornella** [comment]
@CaderHancock your problem is usually due to not having a locale that can handle UTF-8. This is covered in the wiki FAQ.
