### ISSUE TITLE
schrodingers VIRTUAL_ENV_DISABLE_PROMPT 

### ISSUE THREAD

**Issue by thenoid** [robbyrussell/oh-my-zsh#7985]
**Describe the bug**
the `virtualenv` command generates a `bin/activate` script that modifies `$PS1` to include the virtual environment name.

oh-my-zsh does something similar with `prompt_virtualenv`

each script decides whether to display virtualenv information based on the `VIRTUAL_ENV_DISABLE_PROMPT` variable. 

the virtualenv's activate script uses the `-z` test (string is null, that is, has zero length).  oh-my-zsh uses the `-n` (string is not null)....  not sure how to craft a variable that is both null and not null.

```
prompt_virtualenv () {
    local virtualenv_path="$VIRTUAL_ENV"
    if [[ -n $virtualenv_path && -n $VIRTUAL_ENV_DISABLE_PROMPT ]]
    then
        prompt_segment blue black "(`basename $virtualenv_path`)"
    fi
}
```

```
if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1-}"
    if [ "x" != x ] ; then
        PS1="${PS1-}"
    else
        PS1="(`basename \"$VIRTUAL_ENV\"`) ${PS1-}"
    fi
    export PS1
fi
```
**To Reproduce**
1. Install oh-my-zsh
2. Install python2's virtualenv
3. create a virtual env `virtualenv test`
4. activate virtualenv `source test/bin/activate`
5. No matter what value you put for `VIRTUAL_ENV_DISABLE_PROMPT` always end up with a munged prompt

**Expected behavior**
When VIRTUAL_ENV_DISABLE_PROMPT is set, don't display the virtual env in PS1

**System:**
 - OS: OSX 10.14.5
 - Zsh version zsh 5.3 (x86_64-apple-darwin18.0)
 - Terminal emulator: iterm2
 - Virtualenv version: /usr/local/bin/virtualenv --version 16.6.1
 - Python version: Python 2.7.16

**Comment by mcornella** [comment]
You're right, we need to change the flag in agnoster to `-z`. Can you put together a PR?

**Comment by thenoid** [comment]
Sure!  Sorry for the delay - really need to figure out where my GitHub notifications are getting filtered to.
