### ISSUE TITLE
parse errors for functions in debian.plugin.zsh

### ISSUE THREAD

**Issue by shortspecialbus** [robbyrussell/oh-my-zsh#7986]
**Describe the bug**
In Debian Buster, zsh 5.7.1 (x86_64-debian-linux-gnu), the debian plugin in OMZ gives parse errors:

```
/home/username/.oh-my-zsh/plugins/debian/debian.plugin.zsh:75: defining function based on alias `abd'  
/home/username/.oh-my-zsh/plugins/debian/debian.plugin.zsh:75: parse error near `()' 
```

It appears that it doesn't like the functions being defined here without the "function" keyword.  This appears to be able to be fixed by adding "function" to all the functions defined in that section, namely:

line 75: "function abd() {"
line 86: "function ai() {"
line 91: "function ap() {"
line 96: "function ar() {"

I'm not sure how to file a pull request or I'd just do so myself, sorry.

**To Reproduce**
1.) Enable "debian" plugin in zshrc
2.) source ~/.zshrc
3.) Receive parse error

**Expected behavior**
Plugin should load without issue rather than parse errors

**System:**
 - OS: Debian Buster
 - Zsh version: 5.7.1 (x86_64-debian-linux-gnu)
 - Terminal emulator: urxvt (rxvt-unicode 9.22-6) with tmux 2.8-3

**Comment by shortspecialbus** [comment]
On reading things more closely while fixing some code tags in my post, I'm less confident that my "fix" is correct.  While it gets rid of the errors, I'm not sure it has the desired behavior.

**Comment by mcornella** [comment]
That is exactly the fix. It will get rid of the parse errors and define the functions correctly. Just know that aliases have priority and will get called even if there are functions or commands named the same.
