### ISSUE TITLE
Readme of sfdx plugin 

### ISSUE THREAD

**Issue by kvor** [robbyrussell/oh-my-zsh#7990]
Hi,

is there any recent  documentation for sfdx plugin? 
I ve added in my plugins but it does not work. Should I follow https://github.com/wadewegner/salesforce-cli-zsh-completion guide?

**Comment by mcornella** [comment]
The README is at https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/sfdx/README.md. Your problem is probably the same as https://github.com/robbyrussell/oh-my-zsh/issues/7642, you have to `rm ~/.zcompdump*` after you enable the plugin and restart the zsh session with `exec zsh`.
