### ISSUE TITLE
How can i change theme in mac OS catalina

### ISSUE THREAD

**Issue by janardhan1212** [robbyrussell/oh-my-zsh#8013]
Hey, I just updated my os to Catalina beta. I just search ~/zshrc file to change the theme but I find it empty. Can anyone help me  how to change the theme .

**Comment by TheSecEng** [comment]
I'd suggest you double check your syntax

`file ~/.zshrc`

If the file truly doesn't exist, try and `upgrade_oh_my_zsh` or reinstall oh-my-zsh. As it hasn't changed on MacOS Catalina

**Comment by theskillwithin** [comment]
same thing happened to me after upgrading to catalina

**Comment by mcornella** [comment]
Note: macOS Catalina uses zsh by default, **not Oh My Zsh**.

**Comment by gondo** [comment]
> Note: macOS Catalina uses zsh by default, **not Oh My Zsh**.

What is the difference? It seems like everywhere online ZSH is equal to "Oh My Zsh"

**Comment by TheSecEng** [comment]
Also, zsh is the shell, Oh My Zsh is just a configuration manager. Oh My Zsh just uses Zsh underneath.
