### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Machine-Maker** [robbyrussell/oh-my-zsh#8024]
**Describe the bug**
When I try to update Oh My Zsh (either manually or when prompted), I get an error.
![image](https://user-images.githubusercontent.com/15055071/61600539-ffdc5100-abe5-11e9-82f0-6d43481975d5.png)

If I try to run git status in the .oh-my-zsh directory, I get a similar error. I'm guessing something is corrupted in the .oh-my-zsh local repo on my machine.
![image](https://user-images.githubusercontent.com/15055071/61600557-1d111f80-abe6-11e9-9b29-7e98845c8628.png)

**To Reproduce**
Not really sure? It just started happening.

**Expected behavior**
I expect the update to proceed smoothly

**System:**
 - OS: Windows 10 (WSL)
 - Zsh version: 5.4.2
 - Terminal emulator: Hyper

**Comment by mcornella** [comment]
If you don't have commits you wish to save I'd recommend cloning the repository again. Make sure to back up any files you have modified inside `custom/` if you have any.

Please copy the errors instead of making a screenshot so that people having the same errors can find this by searching them.
