### ISSUE TITLE
how to forbidden change directory by directory name

### ISSUE THREAD

**Issue by GreedyPirate** [robbyrussell/oh-my-zsh#8025]
As known oh-my-zsh have a Intelligent way to change directory by directory name instead of 
`cd name`, but sometimes It bothered me to execute some command，assume that there is a directory named **gradle**， and I want to execute command **gradle** to build my project，but oh-my-zsh lead this command to  `change directory`

**Comment by mcornella** [comment]
What you're looking for is the [`autocd` option](http://zsh.sourceforge.net/Doc/Release/Options.html#index-AUTOCD). If you want to disable this behavior, run `unsetopt autocd` or `setopt noautocd`:
```
# With autocd
~$ ls
code
~$ code
~/code$

# Without autocd
~$ setopt noautocd
~$ code
zsh: permission denied: code
```

**Comment by jiyolla** [comment]
Is there a way to bypass/escape autocd?

I mean autocd is good for most of the time, what we want is probably to use disable it for exceptional cases.
Toggling via setopt autocd/noautocd is kind of tedious.
Though I can't think of easy solution to escaping, maybe it's possible and there is one already?

**Comment by mcornella** [comment]
`autocd` isn't triggered if the name corresponds to a command. In what other case would you want to bypass it?

**Comment by jiyolla** [comment]
> `autocd` isn't triggered if the name corresponds to a command. In what other case would you want to bypass it?

It's working the opposite when I post that comment 2 days ago...

It's now working as intended(prioritize cmd over dir), but I have no idea what fix that. 
Maybe it's a configuration bug and explicitly turning it off and on again fix that.
