### ISSUE TITLE
command-not-found plugin has strange behavior with unrecognized commands

### ISSUE THREAD

**Issue by nicolas-van** [robbyrussell/oh-my-zsh#8026]
**Describe the bug**
I'm on Ubuntu 18.04 freshly installed with zsh and latest version of oh-my-zsh. I activated the command-not-found plugin.

When I type a command for a program that is not installed everything performs normally:

```
 ✘ xxx  ~  ksh

Command 'ksh' not found, but can be installed with:

sudo apt install ksh 
sudo apt install mksh
```

Same thing if I type a command that *looks* like a known command:

```
 ✘ xxx  ~  ksb

Command 'ksb' not found, did you mean:

  command 'k3b' from deb k3b
  command 'sb' from deb lrzsz
  command 'kgb' from deb kgb
  command 'kdb' from deb elektra-bin
  command 'ksu' from deb heimdal-clients
  command 'ksu' from deb krb5-user
  command 'msb' from deb mysql-sandbox
  command 'ksh' from deb ksh
  command 'ksh' from deb mksh

Try: sudo apt install <deb name>
```

But when I type something totally unrelated to a known command it displays nothing at all:

```
 ✘ xxx  ~  hahahaha
 ✘ xxx  ~  
```

**To Reproduce**
On ubuntu, try to activate the command-not-found plugin and type an unknown command (like `hahahaha` in my example).

**Expected behavior**
Something more similar to a vanilla bash on ubuntu:

```
xxx:~$ hahahaha
hahahaha: command not found
xxx:~$
```

**Screenshots or recordings**

**System:**
 - OS: Ubuntu 18.04
 - Zsh version 5.4.2
 - Terminal emulator 'Terminal' application on Ubuntu

**Additional context**

**Comment by redtux** [comment]
I can confirm this. If I type oc for the Openshift CLI e.g. (which has no deb or snap package), I get no info at all… (I have always considered this to be a "feature" or rather an intended behavior. 😃)

**Comment by nicolas-van** [comment]
I doubt it was intended. If it's the case it's totally not ergonomic as it makes you think that the command was executed properly (and that it produced no output).

**Comment by mcornella** [comment]
This is an old bug in the ubuntu package. Track it here https://bugs.launchpad.net/ubuntu/+source/command-not-found/+bug/1766068
