### ISSUE TITLE
PS1 PS2 Merged with ZSH Autocomplete Menu

### ISSUE THREAD

**Issue by WillGreen98** [robbyrussell/oh-my-zsh#8031]
**Describe the bug**
Autocomplete (TAB TAB) with new-line enabled causes PS1 and PS2 to merge, resulting in PS2 being on PS1 and becoming unresponsive to the exit key. Can press enter to clear the current command

**To Reproduce**
1. Enable plugin "powerlevel10k/powerlevel10k"
2. Set POWERLEVEL9K_PROMPT_ON_NEWLINE=true
3. Type a command, 
4. Press TAB TAB to autocomplete command/ autocompletion menu
5. See error

**Expected behavior**
Autocomplete (TAB TAB) then exit should result going back to the current command line without UI bug.

**Screenshots or recordings**
<img width="493" alt="image" src="https://user-images.githubusercontent.com/19418225/61701474-23aeac80-ad36-11e9-8e70-e56db8cd974f.png">

<img width="413" alt="image" src="https://user-images.githubusercontent.com/19418225/61701521-34f7b900-ad36-11e9-8742-ed3d09717ed4.png">

<img width="425" alt="image" src="https://user-images.githubusercontent.com/19418225/61701986-f31b4280-ad36-11e9-8451-e519ac5538c4.png">

**System:**
OS: macOS
Zsh version - 5.7.1
Terminal emulator - iTerm2

**Comment by mcornella** [comment]
Issues with `PowerlevelXk` themes don't belong here, please post in the appropriate repository.
