### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by qazip** [robbyrussell/oh-my-zsh#8036]
I need some help debugging an issue I am having. So, I have several aliases defined in my zshrc. An example of that is "c" for clear. The aliases are recognized:

```
 ~ which c   
c: aliased to clear
```

However, doing "c" gives me:
```
 ~ c
zsh: command not found: c
```

This is true for all other aliases. Functions are working correctly though. Any idea what might be causing this?

I am using antergos and oh-my-zsh-git from the AUR. I should mention that the aliases worked absolutely fine until 2 or so days ago.

**Comment by mcornella** [comment]
Maybe run [`setopt aliases`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-ALIASES)?

**Comment by qazip** [comment]
> Maybe run [`setopt aliases`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-ALIASES)?

That fixed it! Thanks!
