### ISSUE TITLE
Autocompletion fails to retrieve all matching parameters

### ISSUE THREAD

**Issue by igorwojda** [robbyrussell/oh-my-zsh#8037]
**Describe the bug**
Missing code completion for git aliases

**To Reproduce**
1. Add an alias to `~/.gitconfig` file
```
[alias]
   clean-local-branches = "!git branch | egrep -v '(master|\\*)' | xargs git branch -D"
```

2. Open terminal and type `git cl`
3. Press Tab key

**behavior**
`git clone` is autocompleted

**Expected behavior**
Display all matching parameters starting with `cl`

**System:**
 - OS: macOS 10.14.5
 - Zsh version 5.7.1
 - Terminal emulator iTerm2 3.2.9

**Additional context**
This seems to fail partially as here is a similar path but working fine when typing more characters:
1. Open terminal and type `git cle` 
2. press Tab key -> autocompletes to `git clean` (OK) 
3. press Tab key -> displays all matches (OK)
![image](https://user-images.githubusercontent.com/530122/61864695-c9deeb80-aec9-11e9-976c-9d23286dab02.png)
^ These are the matches that should be also displayed previously

**Comment by mcornella** [comment]
I can't reproduce this, are you perchance using the gitfast plugin?

**Comment by igorwojda** [comment]
Not sure. 
How can i check this?

**Comment by mcornella** [comment]
See [Plugins](https://github.com/robbyrussell/oh-my-zsh#plugins).

**Comment by igorwojda** [comment]
My `.zshrc`

```
plugins=(
  git
  gradle
  zsh-syntax-highlighting
)
```

**Comment by mcornella** [comment]
Did you install git via Homebrew? It pulls in git completion as well. What do you get with `which _git` after trying to complete a git command?

**Comment by igorwojda** [comment]
I am pretty sure I have installed `git` via `brew install git`, however I remember I had some conflicts where this version was conflicting with other installed version (I was long time ago so don't remember exact details)

1. `which git` result:
`/usr/local/bin/git`


2. `which _git` result:

```
_git () {
	local _ret=1
	local cur cword prev
	cur=${words[CURRENT]}
	prev=${words[CURRENT-1]}
	let cword=CURRENT-1
	if (( $+functions[__${service}_zsh_main] ))
	then
		__${service}_zsh_main
	else
		emulate ksh -c __${service}_main
	fi
	let _ret && _default && _ret=0
	return _ret
}
```

**Comment by mcornella** [comment]
I didn't explain myself correctly, what I need is the output of running `which _git`, but only run it after trying to complete a git command (`git [TAB]` will do).

In any case, this seems to be a case of git's official completion hitting us in the rear. Follow https://github.com/robbyrussell/oh-my-zsh/issues/7062#issuecomment-449946676 to see how to disable that.

**Comment by igorwojda** [comment]
Yes this was the issue indeed. Running this command that prevents file to be loaded and solves the problem
`chmod 0 /usr/local/share/zsh/site-functions/_git`

**Comment by mcornella** [comment]
@felipec can we do something here to fix git's completion?

**Comment by felipec** [comment]
@mcornella I wrote that code, I think this is the expected behavior. The reason why the aliases don't show first is that the default configuration is like this:

    zstyle ':completion:*:*:git:*' tag-order 'common-commands'

So only the common commands are shown first. If you want common commands and aliases to show in the first go, then simply add this to your `.zshrc`:

    zstyle ':completion:*:complete:git:*:*' tag-order 'common-commands alias-commands'

Then `git cl<tab>` will show 'clean-local-branches'.
