### ISSUE TITLE
source ~/.zshrc  error

### ISSUE THREAD

**Issue by huangjihua** [robbyrussell/oh-my-zsh#8038]
```
hank@AT9474-DLP:~$ --> source ~/.zshrc
-bash: autoload: command not found
-bash: /Users/hank/.oh-my-zsh/oh-my-zsh.sh: line 41: syntax error near unexpected token `('
-bash: /Users/hank/.oh-my-zsh/oh-my-zsh.sh: line 41: `for plugin($plugins); do'
```

**Comment by mcornella** [comment]
You should be running zsh instead of bash. Run `zsh`, and `chsh -s $(which zsh)` if you want to have zsh as the default shell.

**Comment by akabuda050** [comment]
The same issue. @mcornella your comment didn't help.

**Comment by akabuda050** [comment]
@huangjihua, @mcornella
There are steps which helped me:
- `zsh`
- `chsh -s $(which zsh)`
- `Logout and Login from the system`
- `Run terminal`
It works for me now.

**Comment by isabelec** [comment]
@akabuda050 Thank you!!!

**Comment by athoug** [comment]
@akabuda050 Thank you mate!

**Comment by NizarETH** [comment]
not working :/

**Comment by mcornella** [comment]
You need to be running zsh. If you run `echo $ZSH_VERSION` and you don't see anything you're not running zsh.

**Comment by VeggieOrz** [comment]
> @huangjihua, @mcornella
> There are steps which helped me:
> 
> * `zsh`
> * `chsh -s $(which zsh)`
> * `Logout from the system and login`
> * `Run terminal`
>   It works for me now.
It works. Thank you!!

**Comment by rockie-yang** [comment]
Mac terminal has an option to use other shell rather than default shell. It will cause the same behavior. 

Change it from Terminal -> Preference -> General -> Shell open with (Default login shell)

**Comment by carolinesalib** [comment]
This worked for me. I was having problem with `source ~/.zshrc` before adding `zsh` to my installation script.

```
zsh
source ~/.zshrc
```

**Comment by yuhao3570** [comment]
Just encountered this problem today, solutions mentioned above do not work.

```
$ echo $ZSH_VERSION
5.7.1
$ echo $SHELL                                
/bin/zsh
```

**Comment by lordsolomon** [comment]
Running zsh v5.8 and having this issue. Have followed all steps listed and can confirm am running zsh. Oh-My-Zsh is not running, and running oh-my-zsh.sh exits with:

```
/home/ghost/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'
/home/ghost/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: `() {'
./oh-my-zsh.sh: line 21: autoload: command not found
./oh-my-zsh.sh: line 39: syntax error near unexpected token `('
./oh-my-zsh.sh: line 39: `for plugin ($plugins); do'
```

Seems to be the same issue, have been unable to troubleshoot. Thoughts?

**Comment by gzausmer** [comment]
> Running zsh v5.8 and having this issue. Have followed all steps listed and can confirm am running zsh. Oh-My-Zsh is not running, and running oh-my-zsh.sh exits with:
> 
> ```
> /home/ghost/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'
> /home/ghost/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: `() {'
> ./oh-my-zsh.sh: line 21: autoload: command not found
> ./oh-my-zsh.sh: line 39: syntax error near unexpected token `('
> ./oh-my-zsh.sh: line 39: `for plugin ($plugins); do'
> ```
> 
> Seems to be the same issue, have been unable to troubleshoot. Thoughts?

zsh v5.8  too. Showing exact same syntax errors on same lines.

**Comment by mcornella** [comment]
Are you sure you're using zsh? Zsh already sources the `.zshrc` file, you shouldn't need to do it. One surefire way to check that you're running zsh is to `echo $ZSH_VERSION`. If that shows nothing you're not running zsh.

**Comment by gzausmer** [comment]
> Are you sure you're using zsh? Zsh already sources the `.zshrc` file, you shouldn't need to do it. One surefire way to check that you're running zsh is to `echo $ZSH_VERSION`. If that shows nothing you're not running zsh.

![Screen Shot 2021-04-08 at 12 13 01](https://user-images.githubusercontent.com/18642340/114000933-216ee780-9864-11eb-98a5-0300168c2f84.png)

**Comment by mcornella** [comment]
Running 5.8 as well and this doesn't happen. When do you do `source ~/.zshrc`? It may happen while not running zsh.

**Comment by gzausmer** [comment]
> source ~/.zshrc

Not sure I understand :/ I tried ```source ~/.zshrc```, still getting all those errors.
Do you use git aliases - if you run those do you get any errors?

**Comment by mcornella** [comment]
> `790f185 [archlinux] Refactor: Fix name & scripts; reorder aliases (#9546)`

This didn't touch anything related to the errors you're seeing.

Can you post the sequence of events where you get the errors? Preferably in text form, just copy the terminal contents and put it inside triple backticks (<code>```</code>).

**Comment by gzausmer** [comment]
Sure:
```git checkout -b test-zsh-error```
then I get this:
```Switched to a new branch 'test-zsh-error'
../.zshrc: line 4: ${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh: bad substitution
../.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'
../.oh-my-zsh/tools/check_for_upgrade.sh: line 32: `() {'
../.oh-my-zsh/oh-my-zsh.sh: line 21: autoload: command not found
../.oh-my-zsh/oh-my-zsh.sh: line 39: syntax error near unexpected token `('
../.oh-my-zsh/oh-my-zsh.sh: line 39: `for plugin ($plugins); do'
../.p10k.zsh: line 16: local: can only be used in a function
../.p10k.zsh: line 20: builtin: setopt: not a shell builtin
../.p10k.zsh: line 22: syntax error near unexpected token `)'
../.p10k.zsh: line 22: `() {'
/usr/local/opt/fzf/shell/key-bindings.zsh: line 22: syntax error near unexpected token `)'
/usr/local/opt/fzf/shell/key-bindings.zsh: line 22: `  () {'
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 31: alias: -L: invalid option
alias: usage: alias [-p] [name[=value] ... ]
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 36: unalias: -m: invalid option
unalias: usage: unalias [-a] name [name ...]
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 39: 0=${(%):-%N}: bad substitution
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 42: /.version: No such file or directory
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 42: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 43: /.revision-hash: No such file or directory
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 43: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 58: autoload: command not found
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 59: is-at-least: command not found
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 62: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 66: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 81: syntax error near unexpected token `}'
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 81: `  if [[ $WIDGET == zle-isearch-update ]] && { $zsh_highlight__pat_static_bug || ! (( $+ISEARCHMATCH_ACTIVE )) }; then'

**Comment by mcornella** [comment]
That's using bash, please verify that you have a proper setup ([see this for example](https://github.com/ohmyzsh/ohmyzsh#4-change-your-default-shell)).

Example of error messages you got when running in bash:
![image](https://user-images.githubusercontent.com/1441704/114070429-4aad6900-98a0-11eb-830b-15a26fd377ee.png)

**Comment by gzausmer** [comment]
> That's using bash, please verify that you have a proper setup ([see this for example](https://github.com/ohmyzsh/ohmyzsh#4-change-your-default-shell)).
> 
> Example of error messages you got when running in bash:
> ![image](https://user-images.githubusercontent.com/1441704/114070429-4aad6900-98a0-11eb-830b-15a26fd377ee.png)

Thanks @mcornella, I think it was related this:
[weird-things-happen-after-typing-source-zshrc](https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc)
Had a script on my project that ran this on startup

**Comment by Ichimikichiki** [comment]
I fixed this by simply putting "zsh" at the top of my .bashrc and .profile

**Comment by azeemchauhan** [comment]
When you try  `chsh -s $(which zsh)` and you might get following text.
> chsh: no changes made

use default login shell instead of `/bin/bash` manually and its always pick you the default one

![image](https://user-images.githubusercontent.com/33758493/130044106-2d8f4d01-90df-43ab-9cab-38db34615bca.png)
