### ISSUE TITLE
Can not show all chinese of input. 

### ISSUE THREAD

**Issue by endingman** [robbyrussell/oh-my-zsh#8045]
when I input chinese like this: '测试测试'
it only show '测'.
![image](https://user-images.githubusercontent.com/16915802/62025871-ee113400-b20b-11e9-8cce-eb25fed414d9.png)

**Comment by mcornella** [comment]
Does this happen in all terminal emulators that you've tested? What's the output of running `locale`?

**Comment by endingman** [comment]
Sorry, I forget to close this.It is terminal cmder's  bug not oh my zsh.
