### ISSUE TITLE
autoload: command not found

### ISSUE THREAD

**Issue by SeonhoBan** [robbyrussell/oh-my-zsh#8057]
![image](https://user-images.githubusercontent.com/42695497/62420632-a6d5e800-b6d0-11e9-8a2f-3d6d1114014c.png)
![image](https://user-images.githubusercontent.com/42695497/62420639-b2c1aa00-b6d0-11e9-8c1d-7deb66185a2c.png)

If I run `test.sh`,
Printed `autoload: command not found`.

Is there a problem with my `test script`?
Or is there a problem with `oh-my-zsh`?

**Comment by mcornella** [comment]
You're running it with sh instead of zsh.
