### ISSUE TITLE
pressing tab key make broken line

### ISSUE THREAD

**Issue by LOGANLEEE** [robbyrussell/oh-my-zsh#8058]
<-- 
Fill this out before posting. You can delete irrelevant sections, but
an issue where no sections have been filled will be deleted without comment.
-->

**Describe the bug**

tab break cli 

**To Reproduce**

1. type any letter
2. press 'tab' key

**Expected behavior**

I expect the line don't break.

**Screenshots or recordings**

**System:**
 - OS: 10.15 Beta (19A526h
 - Zsh version : zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator : Version 2.10 (431)

**Additional context**

**Comment by LOGANLEEE** [comment]
![tab matter](https://user-images.githubusercontent.com/26853553/62420906-fdddbc00-b6d4-11e9-8746-78412b8bcc08.gif)

**Comment by mcornella** [comment]
This is normally a locale issue given you're using utf8 characters, see https://github.com/robbyrussell/oh-my-zsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command

**Comment by LOGANLEEE** [comment]
Thank you it worked!
