### ISSUE TITLE
git-auto-fetch plugin broken?

### ISSUE THREAD

**Issue by lucascosti** [robbyrussell/oh-my-zsh#8075]
**Describe the bug**
 👋  New zsh user here!

When I enable the `git-auto-fetch` plugin, I get errors on my shell. I'm not sure whether any fetching is occurring either.

**To Reproduce**

1. Enable plugin 'git-auto-fetch'
1. Open a new shell.
1. `cd` anywhere; either in or out of a repo directory.
1. See errors, e.g.:
    ```
    ➜ (eval):1: command not found: override-git-auto-fetch-
    ➜ zle-line-init:2: command not found: override-git-auto-fetch-zle-line-init
    ```

**Expected behavior**
No errors, and when in a git directory, for a fetch to occur.

**System:**
 - OS: macOS Mojave 10.14.6
 - Zsh version: 5.7.1
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
This means there is no `zle-line-init` function defined, which is weird since it should be defined in [`lib/key-bindings.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh). Are you perhaps overriding that file?

Another possibility is that `$terminfo` doesn't have `smkx`/`rmkx`, what's your `$TERM` value?

**Comment by mcornella** [comment]
@slavaGanzin we should add a check to see if `zle-line-init` is defined.

**Comment by slavaGanzin** [comment]
@mcornella Marc, I'm not longer user of zsh and so not following changes in zsh internals: don't even remember what zle-line-init is. So with all due respect, I can't help you.

**Comment by mcornella** [comment]
Fixed in https://github.com/robbyrussell/oh-my-zsh/commit/28232904bec1e8e15da52ae048a8a31ef7fac67b.

**Comment by lucascosti** [comment]
Thanks a lot for the quick fix, @mcornella!

I had a look at my `$term`, and you were right that there was something weird with it: for some reason it was set to `linux`. I changed it to `xterm-256color` and it seemed to restore the `zle-line-init` command.

btw, that also helped me solve why I couldn't get proper colors configured in my prompt! :D
