### ISSUE TITLE
Countdown Timer and/or Stopwatch plugin or function?

### ISSUE THREAD

**Issue by MBB417** [robbyrussell/oh-my-zsh#8080]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
 Yes, in a way. It is a request for help to create a new custom plugin or function that would create a countdown/up timer and/or a stopwatch. 

**Is your feature request related to a problem? Please describe.**
The only problem is that I've been spending too much time at my computer and would like a way to see the time spent in a more interactive way than just a small clock in the status bar. These plugins/functions would have myriad use in other contexts as well. 

**Describe the solution you'd like**
I am somewhat new to coding and command-line usage so I would like to know how to go about formatting the syntax for a custom plugin or function that could be placed in my ~.zshrc

**Describe alternatives you've considered**
There are many stopwatches and timers I could download from Apple's app store on my Macbook but I'd prefer to have something that shows up directly in the terminal I'm using. I also tried using a couple of commands that did not work out too well...see screenshots.

**Additional context**
Here are two screenshots of solutions I attempted on my own. As you can see, from the second photo, ZSH attempted to run the function for quite a long time before I cancelled it. Any help would be appreciated. 

![Screen Shot 2019-08-14 at 4 51 23 PM](https://user-images.githubusercontent.com/53518799/63064395-7bb87900-bec6-11e9-96fd-8063e5e29fbc.jpg)

<img width="1280" alt="Screen Shot 2019-08-14 at 4 52 23 PM" src="https://user-images.githubusercontent.com/53518799/63064402-807d2d00-bec6-11e9-8fa9-9d193f09cc6f.png">

**Comment by mcornella** [comment]
There are many resources available on a quick search for "terminal timer", have a look at some of the results for inspiration:
- https://superuser.com/questions/611538/is-there-a-way-to-display-a-countdown-or-stopwatch-timer-in-a-terminal
- https://github.com/trehn/termdown
- https://github.com/drgrib/ttimer
