### ISSUE TITLE
No ./zshrc or ./.oh-my-zsh file

### ISSUE THREAD

**Issue by Kyle-Ye** [robbyrussell/oh-my-zsh#8084]
I installed zsh and oh-my-zsh using yay in Arch.
But I didn't see any profile of setting about it.
Even I manually nano ~/.zshrc and write something like this
```
plugins=(vim
         git 
        sudo 
        extract 
        z 
        wd 
        archlinux 
        zsh-autosuggestions 
        zsh-syntax-highlighting)
```
and use `source ~/.zshrc` it still didn't work

**Comment by mcornella** [comment]
You have to install OMZ via the install script, which automatically generates a valid zshrc file. If you don't want to do that, have a look at the [template zshrc](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template) and copy the relevant parts:
- `export ZSH` line
- `ZSH_THEME` definition
- `plugins` definition (you already have that)
- `source oh-my-zsh script`
