### ISSUE TITLE
SSL certificate problem when installing

### ISSUE THREAD

**Issue by careyjames** [robbyrussell/oh-my-zsh#8086]
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"         
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by careyjames** [comment]
sh -c "$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
--2019-08-16 20:41:43--  https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 146.112.43.204, 146.112.43.142, 146.112.43.157, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|146.112.43.204|:443... connected.
ERROR: The certificate of ‘raw.githubusercontent.com’ is not trusted.
ERROR: The certificate of ‘raw.githubusercontent.com’ doesn't have a known issuer.

**Comment by mcornella** [comment]
This is actually a GitHub issue. [Check that you have ca-certificates installed](https://stackoverflow.com/questions/27144426/error-the-certificate-of-raw-githubusercontent-com-is-not-trusted) if on Linux. If on another system, ask GitHub support but the main issue is probably that you don't have enabled the trust in root certificate authorities.
