### ISSUE TITLE
How to log custom message on the terminal

### ISSUE THREAD

**Issue by kevinmamaqi** [robbyrussell/oh-my-zsh#8090]
Hi,

I've created an alias in the .zshrc file to launch mailhog, but I would like to print a custom message with the localhost address after it, therefore I used the following code.

`
alias start-mailhog="sudo brew services start mailhog && echo 'visit http://127.0.0.1:8025 to check emails"
`

Then I source the file, but it doesn't work as it only prompts the following: `cmdand quote>`

How can I get it to execute the command and then print the message on the terminal?

**Comment by mcornella** [comment]
You've missed closing the single quote in the echo command.
