### ISSUE TITLE
mark with number

### ISSUE THREAD

**Issue by jhuang71** [robbyrussell/oh-my-zsh#8092]
<img width="436" alt="Screen Shot 2019-08-20 at 4 47 23 PM" src="https://user-images.githubusercontent.com/40007806/63387169-616d1800-c36a-11e9-83f5-9acfc3740dec.png">

Hi, I am having this issue with the tail having these mark with numbers follow them. May I ask how to fix that so that it displays the correct symbol?

**Comment by mcornella** [comment]
What theme are you using?

**Comment by jhuang71** [comment]
> What theme are you using?

I am currently using: 

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=("agnoster" )

**Comment by jhuang71** [comment]
<img width="508" alt="Screen Shot 2019-08-21 at 2 05 09 PM" src="https://user-images.githubusercontent.com/40007806/63460794-d1d47180-c41c-11e9-8f32-77d84231f05e.png">

**Comment by mcornella** [comment]
Ask over at the powerlevel10k project, it's probable there's already an issue like yours.
