### ISSUE TITLE
SCP command not found

### ISSUE THREAD

**Issue by chewnglow** [robbyrussell/oh-my-zsh#8094]
Hi! When I use scp on a server with oh-my-zsh it returns `zsh:1: command not found: scp`. But the server indeed installs scp and is accessible on the local zsh shell. Coz the zsh shell has deeply configured so solutions without reinstallation would be better. Any help is thankful!

**Comment by mcornella** [comment]
Look at your `$PATH` variable. Sometimes when switching to zsh it's missing directories.

**Comment by chewnglow** [comment]
I've checked `$PATH` both in zsh and bash and they turned out to be the same. May any problem in value itself?
`/home/user/.autojump/bin:/opt/fsl/bin:/home/user/bin/ants/bin/:${FSLDIR}/bin:${PATH}:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/fsl/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

**Comment by mcornella** [comment]
Then scp might be a function defined only in bash.

**Comment by chewnglow** [comment]
How can I transfer this to zsh? I haven't seen pattern like `scp` in `.bashrc`. BTW the zsh was installed via arch's repository. Thx!

**Comment by mcornella** [comment]
Nevermind, scp *is* a binary. According to [the `openssh` package from Arch Linux](https://www.archlinux.org/packages/core/x86_64/openssh/), it should be in `/usr/bin/scp`, so if `/usr/bin` is in the `$PATH` it should be found by zsh. You do have it in there, so make sure that it is there with an `ls /usr/bin/scp`.

**Comment by chewnglow** [comment]
Sorry 4 late responce... The scp path is indeed `/usr/bin/scp`. May other things go wrong?

**Comment by mcornella** [comment]
Are you sure you check the `$PATH` on the server instead of the client? They don't need to be the same, each host has its particular configuration.

**Comment by chewnglow** [comment]
Yep I'm operating on the server currently. The prob is the scp works when
setting remote as another server but when the remote is this server, it
goes wrong.

Assuming the following operations are taken on this problem server.
`scp prob.local remote`(works)
`scp remote prob.local`(not works)
The same as connecting to this problem server on other devices.

**Comment by mcornella** [comment]
I didn't quite get that. What is prob.local and what is remote, and in which computer are you running the scp command when it fails? It should be easy: it needs to be installed anywhere you run the scp command, and its folder be in the `$PATH`.

**Comment by chewnglow** [comment]
To make it ez, let me show the screenshot:
[image: Screenshot_20190829_092433.png]
The su***6.62 is the problem server, and he***9.50 is the normal server.
I'm operating on the su***6.62. If I use scp with setting either local or
remote parameters as the su***6.62, it fails. But the su***6.62 has scp
installed and can normally share files with other servers(like he***9.50).
A little bit hard to describe, sorry 4 the inconvenience x_x

Marc Cornellà <notifications@github.com> 于2019年8月29日周四 上午3:18写道：

**Comment by mcornella** [comment]
GitHub left out the screenshot.

**Comment by chewnglow** [comment]
Sorry, here's the screenshot:
![Screenshot_20190829_092433](https://user-images.githubusercontent.com/22649869/63988027-df6cb400-cb0c-11e9-957e-0293feb51f97.png)

**Comment by mcornella** [comment]
It looks like the `command not found: scp` error is coming from the su***6.62 server. See [this stackoverflow question](https://stackoverflow.com/questions/17131048/error-when-using-scp-command-bash-scp-command-not-found/17131068) for example. Log in on that server and make sure that `$PATH` is correct and the proper scp package is installed.
