### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by sukai-cheng** [robbyrussell/oh-my-zsh#8095]
I have tried to solve this problem,but it make no sense.....i'm losing.....
![image](https://user-images.githubusercontent.com/35868545/63431711-0adb0900-c452-11e9-9ef7-d4ab8620afca.png)

![image](https://user-images.githubusercontent.com/35868545/63431593-c485aa00-c451-11e9-84e3-c508f0aaab4a.png)

**Comment by Ralithune** [comment]
It looks like you're missing the powerline fonts?

But I'm just as new to zsh as you are, so take that for what it's worth.

**Comment by sukai-cheng** [comment]
> It looks like you're missing the powerline fonts?
> 
> But I'm just as new to zsh as you are, so take that for what it's worth.

i have solved it . if you want to use 'agnoster',You must change the fonts
![Uploading image.png…]()

**Comment by sukai-cheng** [comment]
yet, you get it，I have solved it, the reason is that system miss some font.
, you can downland it form website, and then reload it, it will work...

[image: image.png]

Michael <notifications@github.com> 于2019年8月22日周四 上午12:07写道：
