### ISSUE TITLE
Prompt cursor bug made me uninstall

### ISSUE THREAD

**Issue by Ralithune** [robbyrussell/oh-my-zsh#8097]
**Describe the bug**
When the prompt is very long and close to the width of the terminal and when up arrowing through previous commands, the cursor will jump up another line above if the command is 2 lines long.  See video I made.

**To Reproduce**
1. Set this prompt:
`PROMPT='%{$fg[cyan]%}[-%{$reset_color%}%D{%F %T} %/ %{$fg[cyan]%}->${reset_color%} '`
2. Go to a really deep directory, something that takes up most of your terminal width
3. Type out a long command that wraps to a lower line and run it
4. Up arrow to the previous command and then use left arrow until it jumps to the next line
5. Continue to left arrow until it jumps another line

**Expected behavior**
Cursor to stay on the line I'm editing

**Screenshots or recordings**
https://www.youtube.com/watch?v=xAtogSdaONs

**System:**
MacOS
Zsh version latest as of yesterday
iTerm2 version 3

**Additional context**
I originally uninstalled zsh because of this bug, but came back for the history management stuff thinking I could just resize my window to clear this issue when I ran in to it, but that doesn't work.

I suspect this might be the cursor failing to deal with zshell color codes properly?

**Comment by mcornella** [comment]
Can you check if that happens as well with another terminal emulator, like Terminal.app?

**Comment by Ralithune** [comment]
It looks like it's the color codes in my prompt that are doing it.  When I remove them, the problem goes away - it might be iterm2 that's doing this, but they don't appear to have an obvious support link on their site.

**Comment by Ralithune** [comment]
I found it, and filed https://gitlab.com/gnachman/iterm2/issues/8161

**Comment by mcornella** [comment]
Thanks for replying with more information, hopefully this will be seen by people having the same problem.

**Comment by mcornella** [comment]
zsh doesn't need escaped prompt sequences... maybe try with [`%F{color}`/`%f`](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Visual-effects) instead of `$fg[color]`/`$reset_color`?
