### ISSUE TITLE
git branch completion not working for git switch

### ISSUE THREAD

**Issue by kleinfreund** [robbyrussell/oh-my-zsh#8105]
**Describe the bug**
When typing `git switch ` and pressing <kbd>Tab</kbd> after the space, the tab completion produces a list of file system objects of the current working directory rather than a list of git branch names (i.e. what happens when pressing <kbd>Tab</kbd> after typing `git checkout `).

**To Reproduce**

1. Enable plugin gitfast
2. Go to a directory that is a git repository with more than one local branch
3. Type `git switch ` (including the space at the end) and press <kbd>Tab</kbd>

**Expected behavior**

It shows a list of local branch names

**Actual behavior**

It shows a list of file system objects

**System:**
 - OS: Ubuntu
 - Zsh version 5.5.1
 - Terminal emulator gnome-terminal

**Additional context**

Requires git version 2.23.

It looks like the the git completion files need to updated (e.g. the gitfast plugin’s completion files are not up to date).

**Workaround**

Run the following commands. They place the completion files from the git repository into the `.zsh` directory.

```sh
mkdir -p ~/.zsh
curl -o ~/.zsh/git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
curl -o ~/.zsh/_git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
```

Add the following lines to your `.zshrc` file.

```
# Load completion files from the ~/.zsh directory.
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)

autoload -Uz compinit && compinit
```

**Comment by felipec** [comment]
The proper way to fix this is to backport the changes from v2.23. The pull request introduced more issues.

**Comment by kleinfreund** [comment]
This has stopped working for me at some point in the last days. The behavior is now back to how it was initially reported.

**Comment by edrpls** [comment]
Latest version also broke this for me, I am using the git and gitfast plugins, now none work.

**Comment by citosid** [comment]
@felipec do you know the status of this issue? It seems to still be broken, however the bug is closed.

**Comment by mcornella** [comment]
The gitfast plugin was updated to support oficial git completion. Make sure you have the latest OMZ version and open a new issue with details if you're still having issues.

**Comment by felipec** [comment]
> @felipec do you know the status of this issue? It seems to still be broken, however the bug is closed.

Should be fixed since December 2020.

**Comment by jaklan** [comment]
@felipec actually it isn't - there are no completions for `git switch`
