### ISSUE TITLE
zsh: command not found: help

### ISSUE THREAD

**Issue by Wonderful99668** [robbyrussell/oh-my-zsh#8120]
Hi, when I was trying to use "help" command to get to know the function of shell builtin, for example: `help let`, I ended up with `zsh: command not found: help`.

I tried adding a line:`source ~/.bash_profile` in my .zshrc, but it doesn't work.
However, other commands like: `vim`, `vi` do work, but I can only use "help" command in bash environment.

**Comment by mcornella** [comment]
zsh doesn't have a builtin help command. If you want information about it you'll have to read the man pages. Built-ins are documented in zshbuiltins and the rest of man pages all start with zsh (use tab to complete).

**Comment by ivancarrancho** [comment]
> source ~/.bash_profile 
 works for me 😊

**Comment by amarkoe2018** [comment]
But I was successfully using \? and \h before, and now today, I'm getting "zsh: command not found: h". How do I get back to what I had?

**Comment by nnajiabraham** [comment]
@amarkoe2018 any luck with this???

**Comment by amarkoe2018** [comment]
I don't know how, but it just works again. Wish I could be more help. I did a lot of installing Airflow over and over, I was having trouble getting it right.

**Comment by YourSouLi5Mine** [comment]
In the meanwhile, you could use this function https://gist.github.com/emreberge/1424710

**Comment by guiji56** [comment]
> 同时，您可以使用此功能https://gist.github.com/emreberge/1424710

thanks for  your help

**Comment by alifiroozi80** [comment]
> In the meanwhile, you could use this function https://gist.github.com/emreberge/1424710

Thank you so much bro, this actually helps!

**Comment by mcornella** [comment]
You can also use Zsh's official `run-help`:
```zsh
# put this in your zshrc file
autoload -Uz run-help
alias help='run-help'
```
```console
$ help echo
ZSHBUILTINS(1)                                   General Commands Manual                                   ZSHBUILTINS(1)

NAME
       zshbuiltins - zsh built-in commands

SHELL BUILTIN COMMANDS
       Some  shell  builtin  commands take options as described in individual entries; these are often referred to in the
       list below as `flags' to avoid confusion with shell options, which may also have an effect  on  the  behaviour  of
       builtin  commands.   In  this introductory section, `option' always has the meaning of an option to a command that
       should be familiar to most command line users.

       Typically, options are single letters preceded by a hyphen (-).  Options that take an argument  accept  it  either
       immediately  following  the  option  letter  or  after  white space, for example `print -C3 {1..9}' or `print -C 3
...
```
