### ISSUE TITLE
oh-my-zsh error source:118 no such file or directory

### ISSUE THREAD

**Issue by medev21** [robbyrussell/oh-my-zsh#8121]
I have installed oh-my-zsh along with spaceship theme in the past but recently I change the username folder in mac users which affected the theme.

When I open iterm, the theme is not there and I get this error:

`/Users/someuser/.oh-my-zsh/oh-my-zsh.sh:source:118: no such file or directory: /Users/someuser/.oh-my-zsh/themes/spaceship.zsh-theme`
I went into .zshrc, to change the the `export ZSH=..`, but it's still not fixing the problem.

It's complaining it can find the spaceship theme but it looks like theme is in another folder, `/Users/someuser/.oh-my-zsh/custom/theme`.

Not sure, how to let `oh-my-zsh` know to look in the custom folder. Has anyone encountered this issue? your help will be appreciated

**Comment by mcornella** [comment]
You should put the them in `$ZSH_CUSTOM/themes`, note the extra s at the end of the directory.
