### ISSUE TITLE
I just wanna know what's `ret_status` mean in robbyrussell.zsh-theme

### ISSUE THREAD

**Issue by nanxiaobei** [robbyrussell/oh-my-zsh#8124]
```
local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
```
Can anyone tell me what's `%(?` mean in shell? just curious.

**Comment by mcornella** [comment]
That's a conditional substring. See [Prompt Expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts).
