### ISSUE TITLE
How to change the background of "pasted text"?

### ISSUE THREAD

**Issue by nanxiaobei** [robbyrussell/oh-my-zsh#8125]
![nkAVuF.png](https://s2.ax1x.com/2019/09/03/nkAVuF.png)

When copy and paste some text to the terminal, it has background.
I change to `bash` and there is no background, where can I change or disable the background of "pasted text"?

**Comment by mcornella** [comment]
Duplicate of #5459. See [solution](https://github.com/robbyrussell/oh-my-zsh/issues/5459#issuecomment-250207759).
