### ISSUE TITLE
After using the latest OhMyZsh, the terminal username is lost.

### ISSUE THREAD

**Issue by KingsInnovate** [robbyrussell/oh-my-zsh#8133]
![image](https://user-images.githubusercontent.com/29455550/64420380-c0a08b80-d0d1-11e9-84c8-45cf70bf83ca.png)
What should i do?
Thanks

**Comment by mcornella** [comment]
That is the default theme, robbyrussell. Have a look at the [Themes wiki section](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes) for alternatives that do display the username.

**Comment by KingsInnovate** [comment]
Thanks
