### ISSUE TITLE
yarn plugin add yarn version

### ISSUE THREAD

**Issue by frani** [robbyrussell/oh-my-zsh#8137]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

is for Yarn Plugin

**Is your feature request related to a problem? Please describe.**

There is no alias for yarn version

**Describe the solution you'd like**

add an alias for yarn version

**Describe alternatives you've considered**

**Additional context**

**Comment by mcornella** [comment]
Closing, please do not open an issue if you have a PR ready.
