### ISSUE TITLE
[dnote] Command not found.

### ISSUE THREAD

**Issue by silvioprog** [robbyrussell/oh-my-zsh#8140]
Hi.

I have been trying to use dnote inside zsh, but it raises a `command not found`.

My steps was:

```bash
$ vi ~/.zshrc`
```

and enabled the plugin:

```bash
...
plugins=(git dnote)
...
```

After restarting the zsh/terminal, I've tried:

```bash
➜ ~ dnote
zsh: command not found: dnote
```

I have the oh-my-zsh installed on Linux (openSUSE Tumbleweed) and Windows (MinGW-w64).

Are there any additional steps I'm forgetting to do?

Thank you!

**Comment by mcornella** [comment]
The dnote plugin only adds completion for dnote, you still need to [install it separately](https://github.com/dnote/dnote#quick-install).
