### ISSUE TITLE
Can I use the oh-my-zsh when I ssh to a remote server?

### ISSUE THREAD

**Issue by zzkyeee** [robbyrussell/oh-my-zsh#8146]
When I ssh to a remote server, I found that terminal can't use oh-my-zsh, is there a mapping?

**Comment by mcornella** [comment]
You have to install zsh and OMZ in that remote server as @OpenWaygate said.

**Comment by zzkyeee** [comment]
But actually, we don't have permission to install zsh and OMZ in remote server.

**Comment by zzkyeee** [comment]
Because in general, we only ssh to the company's server.Is there are any mapping between OMZ and ssh bash terminal.

**Comment by mcornella** [comment]
There isn't no, sorry. You could locally install zsh to a folder writable by your user. Homebrew for Linux is a good way to do that.

**Comment by pnodet** [comment]
Just stumble on this issue. @zzkyeee You might wanna have a look at xxh.

https://github.com/xxh/xxh

**Comment by eagleonefight** [comment]
> Just stumble on this issue. @zzkyeee You might wanna have a look at xxh.
> 
> https://github.com/xxh/xxh

It supports x86, but does not support arm, which is sad. Are there other tools?

**Comment by dpthegrey** [comment]
I'd like to see oh my zsh work on our main machine to just change the look and feel of remote shell. After all we use the same terminal as our local machine to access remote.

**Comment by mcornella** [comment]
If Zsh is installed in the remote machine you can install OMZ in it. What you say about using the same terminal makes no sense. The shell environment is not running in the terminal, so it makes no difference if you use the same terminal. You need to change the shell environment, which runs on the server.

It seems the tool suggested above supports Oh My Zsh out of the box: https://github.com/xxh/xxh#seamless-oh-my-zsh-demo.
