### ISSUE TITLE
Global "d" path history?

### ISSUE THREAD

**Issue by Mebus** [robbyrussell/oh-my-zsh#8152]
Hallo,

when I press "d" I get the recently visited path of the current zsh instance. Is it possible to modify this shortcut in a way that I can get the path history for old shells and other shell instances, too? Is there probably a plugin for this?

Thanks

Mebus

**Comment by mcornella** [comment]
There's the [dirpersist plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/dirpersist) which tracks the 20 most recent unique directories (you can configure the number of tracked directories with the `DIRSTACKSIZE` variable), and there are other plugins which also allow you to jump to recent directories, see [Plugins Overview](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins-Overview#fs-jumping).
