### ISSUE TITLE
Windows line endings in latest update break $PS1 variable

### ISSUE THREAD

**Issue by mhemken-nyt** [robbyrussell/oh-my-zsh#8153]
**Describe the bug**
I said yes to the regular update. Now my `$PS1` is messed up. My shell prompt is blank and there are errors.

**To Reproduce**
1. Be on a Mac (or probably any *nix)
1. Say yes to today's updates

**Expected behavior**
Life as usual.

**Screenshots or recordings**
```
Last login: Tue Sep 17 09:26:04 on ttys000
/Users/123456/.oh-my-zsh/plugins/git/git.plugin.zsh:4: command not found: ^M
/Users/123456/.oh-my-zsh/plugins/git/git.plugin.zsh:230: parse error near `&&'
/Users/123456/.oh-my-zsh/themes/robbyrussell.zsh-theme:3: command not found: ^M

bash
bash-3.2$ zsh
/Users/123456/.oh-my-zsh/plugins/git/git.plugin.zsh:4: command not found: ^M
/Users/123456/.oh-my-zsh/plugins/git/git.plugin.zsh:230: parse error near `&&'
/Users/123456/.oh-my-zsh/themes/robbyrussell.zsh-theme:3: command not found: ^M
ls
Desktop    Downloads  Music     Public
Documents  Library    Movies   Pictures  
```

**System:**
 - OS: Mac
 - Zsh version 5.3
 - Terminal emulator "Terminal" aka the default one on a Mac

**Additional context**
Ok so I just fixed this...

Opened up the three files there in neovim and said `set ff=unix` and saved. Then I did a `source ~/.zshrc` and boom. Back to normal.

# Moral of the story:
Can we not leave in Windows line endings in updates? This is the second time this year.

**Comment by mhemken-nyt** [comment]
I'd love to help with this. Is there any kind of CI system that I can contribute to?

I could just submit a PR for those files, but that would be a band aid. Better to add a step in the CI to detect Windows line endings and fix the issue once and for all.

**Comment by mcornella** [comment]
This is a known issue with a workaround (see https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351). There were attempts at fixing this but nothing satisfying yet.
