### ISSUE TITLE
when typing history -w backup.txt the result is ➜ ~ omz_history:fc:13: bad option: -w

### ISSUE THREAD

**Issue by Kr4v3N** [robbyrussell/oh-my-zsh#8166]
when typing history -w backup.txt the result is
➜ ~ omz_history:fc:13: bad option: -w
I don't understand the result . Is my oh-my-zsh setting wrong?

**Comment by mcornella** [comment]
history is an almost exact alias of fc, if you want to copy the history to backup.txt you need -W. See http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-fc
