### ISSUE TITLE
 parse_git_dirty error

### ISSUE THREAD

**Issue by yossepbb** [robbyrussell/oh-my-zsh#8168]
Hi everyone,

Since yesterday I have this error message "  parse_git_dirty:4: command not found: git   " after removing git for a new installation.
Now it is totally impossible to update, upgrade my system. I am using Ubuntu 18.04.3 LTS.

Someone can at least explainme what does it means ?

Thank you for your support.

**Comment by msafadieh** [comment]
Git is part of the [prerequisites](https://github.com/robbyrussell/oh-my-zsh#prerequisites). You need to reinstall it. 

If you can't use your shell for now, rename your `.zshrc` file temporarily, re-install git, and then rename `.zshrc` back to its original name.

**Comment by mcornella** [comment]
You can hack it to not get that error by redefining the function with an empty body, like so:
```
parse_git_dirty() {}
```
But yeah, git is a prerequisite and thus we don't check for its existence in pretty much anywhere. If you have OMZ autoupdate enabled (it is by default) you'll also get errors once in a while.
