### ISSUE TITLE
print -z "foo" doesn't work from script or via command

### ISSUE THREAD

**Issue by skamsie** [robbyrussell/oh-my-zsh#8175]
**Describe the bug**

I am not sure if this is a bug or I am missing something, but I would like to use the `print` function with `-z` flag from a script and it is not working.

**To Reproduce**

1. Run the command `print -z "foo"` and observe the result
2. The command above will inject "foo" on a new line, leaving the cursor at the end, which is the expected behavior
3. Try to run the same command like `/bin/zsh -c 'print -z "foo"' ` -> nothing happens (it is the equivalent of pressing enter on an empty line)
4. Try to run the same command `print -z "foo"` from within a script file like:

```
#!/bin/zsh

print -z "foo"
```

Same as nr 3... nothing happens

**Expected behavior**
I would like the `print -z $COMMAND` to behave exactly the same from a script as it does when doing it directly in the command line

**System:**
 - OS: macOS Mojave
 - Zsh version: zsh 5.3 (x86_64-apple-darwin18.0)
 - terminal.app

**Additional context**
This used to work fine at some point (lower OS version and zsh different version)

**Comment by sparcbr** [comment]
I don't think that's supposed to work from a subshell. Only from the "editing" or "calling" shell.
You can make a function which is called from within the calling shell.
Edit file "foo" and put this:
```
z(){
   print -z 'testing'
}
```
Now source the file with this function, which you can do in ~/.zshrc (another alternative would be to define an autoload function)
```
❯ source foo
❯ z
❯ testing
```

**Comment by skamsie** [comment]
@sparcbr thank you, I guess it is a nice workaround, but I could swear this was working at some point...

**Comment by skamsie** [comment]
EDIT: my mistake, this is not a bug. I will close now.
