### ISSUE TITLE
zsh not loading theme after last update

### ISSUE THREAD

**Issue by nautilor** [robbyrussell/oh-my-zsh#8180]
Yesterday oh-my-zsh asked me if I wanted to check for updates and so I did, I don't remember if he updated or not but now everytime I start a terminal I have to do `source ~/.zshrc` to get the right prompt to load.

My guess is that is not parsing the `.zshrc` file

**Comment by nautilor** [comment]
Ok, by doing some testing with alias and others config in the ~/.zshrc I can tell that only the prompt does not get loaded

**Comment by jsumners** [comment]
Thank you. This solved my own issue of a new theme not loading. It seems setting a theme as early as possible is the best course of action.
