### ISSUE TITLE
Git Command Print

### ISSUE THREAD

**Issue by stephencweiss** [robbyrussell/oh-my-zsh#8192]
I switched from `zsh` to `oh-my-zsh` this morning (using the `agnoster` theme with a slight modification to the `PROMPT`).

I noticed that when I use a git command like `git branch`, instead of printing the results like my shell does for `ls -a` (see below)...
![image (2)](https://user-images.githubusercontent.com/39878535/66011307-33f6ac80-e488-11e9-9c86-2a47ffa2185f.png)

It opens a new view:
![image (3)](https://user-images.githubusercontent.com/39878535/66011308-33f6ac80-e488-11e9-8b7b-92ee6a845594.png)

The concern I have is that this makes it more difficult to _use_ the `git` command because I now have to remember the results instead of being able to reference them. This is because in order to write another command, I have to exit the view:
![image (4)](https://user-images.githubusercontent.com/39878535/66011309-33f6ac80-e488-11e9-843a-1f2e571e26bb.png)

Is there a setting somewhere that controls this behavior? I did try to comment out the `git` plugin within `.zshrc`, but that did not seem to fix it.

Thanks!

**Comment by mcornella** [comment]
I don't think there's a setting in OMZ that does this, this is just the default I think. Maybe you had a different `$LESS` value? Anyhow, you can disable that behavior with [git's `pager.branch`](https://stackoverflow.com/a/48370253/5798232).
