### ISSUE TITLE
Insecure completion-dependent directories detected on macOS Catalina

### ISSUE THREAD

**Issue by lucasjohnston** [robbyrussell/oh-my-zsh#8205]
**Describe the bug**
Just completed a clean install of macOS Catalina Beta 10 - it looks like a new insecure directory is now created in the process - `/usr/local/share`.
This causes a `Insecure completion-dependent directories detected` error from oh-my-zsh when sourcing my `~.zshrc`

**To Reproduce**
1. Install macOS Catalina
2. Install oh-my-zsh
3. Edit and `source` your .zshrc

**System:**
 - OS: macOS Catalina Beta 10 (19A578c)
 - Zsh v5.7.1
 - Terminal: Hyper

**Comment by mcornella** [comment]
Zsh detects it's insecure if the user and group owning the directory aren't the same as the current user and group, unless the current user is root (I think that's how it was). You can either change that (not recommended if it's a system folder) or ignore it, by setting `ZSH_DISABLE_COMPFIX=true` at the start of your zshrc file, before ohmyzsh is sourced.

**Comment by lucasjohnston** [comment]
I understand that, but my point was that this error is happening on a fresh install of Catalina, meaning every new install of oh-my-zsh on Catalina will surely run into this issue? If so, is it not worth adding some explainer text to the error for new users who might run into this error?

**Comment by mcornella** [comment]
Didn't you get this explanation? https://github.com/robbyrussell/oh-my-zsh/blob/40df67bc3b9b51caa24df5d220487043040d1f9a/lib/compfix.zsh#L29-L41

**Comment by victor-bonsai-labs** [comment]
Put `ZSH_DISABLE_COMPFIX="true"` in your `~/.zshrc`. Before `source $ZSH/oh-my-zsh.sh`

**~/.zshrc**

```bash
ZSH_DISABLE_COMPFIX="true"

source $ZSH/oh-my-zsh.sh
```

**Comment by dcsan** [comment]
i got this and came here too. this warning happens for any brew installed commands.
given it's a pretty frequent setup, is there a less jarring way to handle it? Otherwise users are basically caught in the crossfire between ohmyzsh and brew maintainer philosophies.

**Comment by Wiggriz** [comment]
Just happened with me too using a fresh Catalina install. 

I ran `compaudit | xargs chmod g-w,o-w` and there were insecure directories. 

I restarted my computer to make sure my user login shell profile was defaulting to zsh. I reran that command it appears to have fixed the problem.

**Comment by Droberts359** [comment]
I also ran into this issue. Just got a new Macbook and have been going through the Laracasts tutorials to learn Laravel and have begun running into this issue as well. Appears that doing the 

ZSH_DISABLE_COMPFIX="true" in the file did help.

**Comment by jcconnell** [comment]
@danwigrizer The same worked for me. Thank you!

**Comment by innosbill201** [comment]
this worked for me:

**sudo chmod -R  g-w,o-w /usr/local/share/zsh**

**Comment by valeriafuziySH** [comment]
@danwigrizer worked for me too. Thanks.

**Comment by thomas6g** [comment]
I wonder if that solution is really a solution...

I have two users on my Mac one  administrator (admin) which I use to install software or change the system configuration. The second user (tom) I use for my daily work surfing, programming etc.

I use brew with the admin user. I don't need root access rights for that purpose. My default user (tom) can't use brew because of missing permissions (default configuration of brew). I think this is fine for security reason. 

1. If I change the user of the complained folders to root or my default user (tom). I may satisfy compaudit of Zsh but brew won't be able to run with the admin user anymore, because it can't access the complained folders.
 
2. Disabling the security audit by ZSH_DISABLE_COMPFIX=true does not work for me, too. Because I don't want to disable the security checks entirely.  

Any ideas how to fix that problem considering these constraints? Maybe a whitelist?

**Comment by Aisuko** [comment]
> I wonder if that solution is really a solution...
> 
> I have two users on my Mac one administrator (admin) which I use to install software or change the system configuration. The second user (tom) I use for my daily work surfing, programming etc.
> 
> I use brew with the admin user. I don't need root access rights for that purpose. My default user (tom) can't use brew because of missing permissions (default configuration of brew). I think this is fine for security reason.
> 
> 1. If I change the user of the complained folders to root or my default user (tom). I may satisfy compaudit of Zsh but brew won't be able to run with the admin user anymore, because it can't access the complained folders.
> 2. Disabling the security audit by ZSH_DISABLE_COMPFIX=true does not work for me, too. Because I don't want to disable the security checks entirely.
> 
> Any ideas how to fix that problem considering these constraints? Maybe a whitelist?

You are right, I hit this issue with macOS big Sur 11.2 with my standard user account. And I switch account between administrators and standard user. We should not change the permission of the folder under the `/usr/share` folder and I believe that the security check is useful for us. So, there is not a real solution.

**Comment by shovon** [comment]
I'm on macOS Big Sur. Revoking writes from groups and others does not work.

Instead, my solution was to recursively change the owner to myself, and the group to admin, by invoking:

```shell
sudo chown -R $(whoami):admin /usr/local/share/zsh
```

I hope this helps.

**Comment by alextechtai** [comment]
I'm wondering do we have an unanimous "correct" way to fix this? I'm currently on macOS Monterey. It seems like it's still an issue and I just am curious is it because this was installed via Homebrew?
