### ISSUE TITLE
Key Fn Problem

### ISSUE THREAD

**Issue by GSilva18** [robbyrussell/oh-my-zsh#8211]
Hi,

I installed oh-my-zsh on Linux Mint 19.1 and one key isn't working correctly only on zsh. FN + 0 ... is the combination to / on my Notebook and it's not working...

What should I do? I really want to use oh-my-zsh on Linux too.

**Comment by mcornella** [comment]
I think you need to enable NumLock to use that? But there should be some other key with `/` so that you don't have to use Fn. If this is a Spanish keyboard that key is Shift+7.
