### ISSUE TITLE
How to highlighting stderr after entry command?

### ISSUE THREAD

**Issue by deweiwork** [robbyrussell/oh-my-zsh#8228]
I Know some themes which provide stderr highlighting, 
as red circle shown of following picture:

https://imgur.com/rubXSGJ

(Retrieved from: https://github.com/viasite-ansible/ansible-role-zsh)

Is there a zsh-plugin support like this?

I use bureau theme now, but it does not support this function,
https://imgur.com/n44g8uN

I want to use(extend) this function with zsh-plugin.

How do I do?

**Comment by mcornella** [comment]
This indicator means the executed command finished with a non-zero exit code, not that there is stderr output. It's a small difference, but it's worth pointing out. For example, running `false` (which exits with code 1) would also show that indicator but not output anything to stderr.

The exit code of the last command can be accessed with the variable `$?`. The `robbyrussell` theme shows a red arrow if the exit code was non-zero, for example: https://github.com/robbyrussell/oh-my-zsh/blob/3848102a5ec8534cef935d594c6abcbfc0f419c8/themes/robbyrussell.zsh-theme#L1
with a conditional substring, see [Conditional substrings in prompts](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Conditional-Substrings-in-Prompts).
