### ISSUE TITLE
Robbyrussel theme now very tiny

### ISSUE THREAD

**Issue by 9mm** [robbyrussell/oh-my-zsh#8235]
**Describe the bug**

The `robbyrussel` theme looks strange on the new Catalina OSX using iTerm 3

More specifically, the arrow is very tiny, but the font for the text seems to be identical and looking good... so that is strange.

![image](https://user-images.githubusercontent.com/1386207/66364963-3ea9b980-e940-11e9-8c5a-4621c785d7f1.png)

**System:**
 - OS: latest
 - Zsh version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator latest iTerm

**Comment by 9mm** [comment]
Now that I look at it, the tilde is also smaller I think.

ALso.. if I change it to "bold oblique" it actually looks ALMOST normal, but obviously bolder a little.. and oblique.. but at least the size is right. When I put it back to "roman" it looks super tiny again.

Here is bold oblique

![image](https://user-images.githubusercontent.com/1386207/66365132-cf809500-e940-11e9-8688-54ab1876f814.png)


The font im using is Bitstream Vera Sans Mono

**Comment by lty96117** [comment]
Same here...

**Comment by mcornella** [comment]
This has to be a font/terminal emulator/Catalina issue. Try with a different terminal and/or a different font; if nothing works it an Apple problem.

**Comment by xi-guan** [comment]
Change [Non-ASCII Font -> Arial, size -> 11 ] solved this problem for me.

**Comment by hologerry** [comment]
> Change [Non-ASCII Font -> Arial, size -> 11 ] solved this problem for me.

Thanks so much, this issue bother  me a long time.

**Comment by sakoula** [comment]
Hi everyone. Just if someone cares: I wanted to use [lsd](https://github.com/ryanoasis/nerd-fonts) and Arial does not have all the necessary icons etc. I end up using [Arimo Nerd Font](https://github.com/ryanoasis/nerd-fonts) for `Non-ASCII Font`. In all the others the icon was too small.

**Comment by shiva-kumarj** [comment]
@hologerry @xi-guan I am using the windows terminal and i too feel that the size of the arrow is small.. Can you instruct how to increase the "non-ascii font size" or where I can find it ? I can increase the font size from the settings but that makes everything big.
