### ISSUE TITLE
A list of everything that oh-my-zsh modifies in the computer

### ISSUE THREAD

**Issue by FemtoEmacs** [robbyrussell/oh-my-zsh#8245]
My computer is a Mac Mini with MacOS Catalina, Version 10.15. I installed oh-my-zsh, because I thought it would accelerate zsh, which was very slow. Immediately everything stopped working. Not even the ls command produced the message **zsh: command not found: ls**. The lem text editor, roswell, nvim, ghc, everything produced the message of command not found. Then, I tried to remove oh-my-zsh immediately. Fortunately, only the terminal was not working. Then I found that I just needed to run uninstall_oh_my_zsh, but again I got the message: command not found. I read the section about hiccups that suggest checking the .zshrc configuration file. I used the gui version of emacs to verify that .zshrc was setting the PATH correctly. I tried to find someone with the same problem. Finally, I found a woman who  guided me in removing oh-my-zsh by hand, without entering the terminal. I removed everything she told me that I should remove, and the terminal started working again, except roswell and lem. I reinstalled these tools again.

However, the woman who helped me confessed that she fixed her computer blindly, after examining the uninstall.sh file. Then she told me no rename ~/.zshrc.pre-oh-my-zsh to .zshrc, or something like that.  I am not sure whether I removed everything, and renamed what should be renamed. The terminal looks normal. When I installed oh-my-zsh, I saw the path in one line, and the Greek lambda letter playing the role of prompt in the other line. I suggest that you publish a list of steps for removing completely oh-my-zsh by hand, without entering the terminal.

**Comment by mcornella** [comment]
If you haven't changed any of the defaults, remove the `$ZSH` directory and the .zshrc file. Optionally:
- rename `~/.zshrc.pre-oh-my-zsh` to `~/.zshrc`, but that is only applicable if there was a zshrc file before installing ohmyzsh.
- go back to the previous shell if it wasn't zsh. This is achieved with `chsh -s $(which PREVIOUS_SHELL)`, where PREVIOUS_SHELL is the previous shell name (bash is the most common).
