### ISSUE TITLE
zsh doesn't show username and hostname

### ISSUE THREAD

**Issue by DrDinosaur** [robbyrussell/oh-my-zsh#8246]
I installed zsh and oh-my-zsh on Ubuntu on WSL 2. When I try to start the zsh, however, it doesn't show the username and hostname like it does with bash.

![image](https://user-images.githubusercontent.com/4646697/66624354-69507800-ebb5-11e9-9708-0e443ca1333a.png)

``` 
uname -a
Linux Summit 4.19.57-microsoft-standard #1 SMP Wed Jul 3 20:47:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mcornella** [comment]
This is the default theme, [robbyrussell](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes). You can browse that page for other themes that do have username and hostname, or look at the [External themes](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) for others that aren't included with ohmyzsh.

**Comment by DrDinosaur** [comment]
Changing theme did not fix the issue.

![image](https://user-images.githubusercontent.com/4646697/67138687-d47cf880-f20c-11e9-9032-1137cb8c4eb8.png)

Looks like maybe some data isn't getting processed correctly?

**Comment by DrDinosaur** [comment]
Ok, I needed to install the Powerline font using the install.ps1 script on the Powerline fonts repo, leave the default mode in the .zshrc file on Ubuntu for WSL, and enable a Powerline font in the application hosting the terminal (like Windows Terminal Preview or Visual Studio Code). Now it works and it looks amazing :)
