### ISSUE TITLE
Cask Plugin: Command Not Found

### ISSUE THREAD

**Issue by DarrenMack-OD** [robbyrussell/oh-my-zsh#8247]
**Describe the bug**

When using the CASK plugin I get command not found. I have the /usr/local/Cellar and usr/local/bin in my path. Not really sure what the cask plugin is looking for as cask is now baked into brew isn't it?

**To Reproduce**
1. Enable plugin 'oh-my-zsh/cask'
2. Start iTerm2
3. See error

**Expected behavior**

Not to see an error, more detail as to the cause?

**System:**
 - OS: macOS Catalina
 - Zsh version: 5.7.1
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
Note the cask plugin refers to the Emacs tool, not `brew cask`. [See the README](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/cask/README.md).
