### ISSUE TITLE
oh-my-zsh.sh tries to install dpkg into Fedora

### ISSUE THREAD

**Issue by KSonny4** [robbyrussell/oh-my-zsh#8253]
**Describe the bug**
Oh my zsh wants to install dpkg. Getting this message `Install package 'dpkg' to provide command 'dpkg'? [N/y]`.

**To Reproduce**
Simply turn on terminal, the problem is coming from .zshrc from `source $ZSH/oh-my-zsh.sh` (no problem when commented).

**Expected behavior**
None

**System:**
 - OS: Fedora 30
 - Zsh version: zsh 5.7.1 (x86_64-redhat-linux-gnu)
 - Terminal emulator: All terminals affected

**Comment by mgeeky** [comment]
Following patch resolved issue for my (Fedora):

```
diff --git a/plugins/fzf/fzf.plugin.zsh b/plugins/fzf/fzf.plugin.zsh
index 64614829..f5b09dc8 100644
--- a/plugins/fzf/fzf.plugin.zsh
+++ b/plugins/fzf/fzf.plugin.zsh
@@ -58,6 +58,7 @@ function setup_using_base_dir() {
 
 
 function setup_using_debian_package() {
+    command -v dpkg || return 1
     dpkg -s fzf &> /dev/null
     if (( $? )); then
         # Either not a debian based distro, or no fzf installed. In any case skip ahead
```

**Comment by mcornella** [comment]
Can you submit that in PR form?
