### ISSUE TITLE
It's extremely slow

### ISSUE THREAD

**Issue by piesoftdev** [robbyrussell/oh-my-zsh#8258]
Hi,

I am using iterm2 and installed this using:
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

Every time I enter a command the loading time is very very slow, i could be anything from ls in a small directory it really takes long time till I can see the files.

Thank you

**Comment by mcornella** [comment]
Can you run `set -xv` to enable trace mode and tell me if it's stuck in a particular command? Did you modify your zshrc file?

**Comment by piesoftdev** [comment]
This is the only thing I changed however it was slow before I changed
`ZSH_THEME="powerlevel9k/powerlevel9k"`

it got stuck at this part: _++vi-git-untracked:8> git ls-files --others --exclude-standard /Users/....._

**Comment by mcornella** [comment]
This is a powerlevel9k function, browse their issues for one that matches your case or submit a new one on their [repository](https://github.com/Powerlevel9k/powerlevel9k/).

**Comment by romkatv** [comment]
@piesoftdev You've installed the wrong theme. See https://github.com/romkatv/powerlevel10k/.
