### ISSUE TITLE
Cloud symbol not work

### ISSUE THREAD

**Issue by yuswift** [robbyrussell/oh-my-zsh#8261]
**Describe the bug**

after I update my OSX version to 10.15，I found that Cloud symbol not work properly. Here is the screenshot. 
![image](https://user-images.githubusercontent.com/37265389/66793958-39e19880-ef32-11e9-93df-ce257845f0d3.png)

**System:**
 - OS: macOS 10.15
 - Zsh version zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator  iTerm2

**Comment by mcornella** [comment]
If by "not work" you mean it's now small, this is the same as https://github.com/robbyrussell/oh-my-zsh/issues/8235 and it isn't an OMZ bug. See https://github.com/robbyrussell/oh-my-zsh/issues/8235#issuecomment-539521463.
