### ISSUE TITLE
ssh-agent plugin - issue loading identities

### ISSUE THREAD

**Issue by billyschmidt** [robbyrussell/oh-my-zsh#8264]
Seems like the plugin is adding an extra `/` for some reason, as I'm getting the following each time I open a new terminal:

`ssh-keygen: /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work: No such file or directory
ssh-keygen: /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github: No such file or directory
/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work: No such file or directory
/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github: No such file or directory`

My `.zshrc` contains the following:

`plugins=(
  zsh-completions
  git
  colored-man-pages
  colorize
  history
  sbt
  bundler
  rake
  rbenv
  ssh-agent
)

zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities ~/.ssh/id_rsa_work ~/.ssh/id_rsa_work_github

source $ZSH/oh-my-zsh.sh`

Relevant part of debug logs:

`_add_identities
+/Users/bschmidt/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh:78> _add_identities
+_add_identities:1> local id line sig lines
+_add_identities:2> local -a identities loaded_sigs loaded_ids not_loaded
+_add_identities:3> zstyle -a :omz:plugins:ssh-agent identities identities
+_add_identities:6> [[ ! -d /Users/bschmidt/.ssh ]]
+_add_identities:12> [[ 2 -eq 0 ]]
+_add_identities:21> lines=+_add_identities:21> ssh-add -l
+_add_identities:21> lines=$'4096 SHA256:ppIhNeqcn7s8dTFQ6uqILwbje/duuuKLcPHBYilVFUo /Users/bschmidt/.ssh/id_rsa_work (RSA)\n4096 SHA256:TdTOo+x7KWJ8ciahJLZ99GoAc5TgNWmyP/OpbDoaEV4 /Users/bschmidt/.ssh/id_rsa_work_github (RSA)'
+_add_identities:22> line=4096 SHA256:ppIhNeqcn7s8dTFQ6uqILwbje/duuuKLcPHBYilVFUo /Users/bschmidt/.ssh/id_rsa_work (RSA)
+_add_identities:23> loaded_sigs+=SHA256:ppIhNeqcn7s8dTFQ6uqILwbje/duuuKLcPHBYilVFUo
+_add_identities:24> loaded_ids+=/Users/bschmidt/.ssh/id_rsa_work
+_add_identities:22> line=4096 SHA256:TdTOo+x7KWJ8ciahJLZ99GoAc5TgNWmyP/OpbDoaEV4 /Users/bschmidt/.ssh/id_rsa_work_github (RSA)
+_add_identities:23> loaded_sigs+=SHA256:TdTOo+x7KWJ8ciahJLZ99GoAc5TgNWmyP/OpbDoaEV4
+_add_identities:24> loaded_ids+=/Users/bschmidt/.ssh/id_rsa_work_github
+_add_identities:29> id=/Users/bschmidt/.ssh/id_rsa_work
+_add_identities:31> [[ 0 -le 0 ]]
+_add_identities:32> sig=+_add_identities:32> ssh-keygen -lf /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work
+_add_identities:32> sig=+_add_identities:32> awk '{print $2}'
ssh-keygen: /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work: No such file or directory
+_add_identities:32> sig=''
+_add_identities:33> [[ 0 -le 0 ]]
+_add_identities:33> not_loaded+=/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work
+_add_identities:29> id=/Users/bschmidt/.ssh/id_rsa_work_github
+_add_identities:31> [[ 0 -le 0 ]]
+_add_identities:32> sig=+_add_identities:32> ssh-keygen -lf /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github
+_add_identities:32> sig=+_add_identities:32> awk '{print $2}'
ssh-keygen: /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github: No such file or directory
+_add_identities:32> sig=''
+_add_identities:33> [[ 0 -le 0 ]]
+_add_identities:33> not_loaded+=/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github
+_add_identities:37> [[ -n '/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github' ]]
+_add_identities:37> ssh-add /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github
/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work: No such file or directory
/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work_github: No such file or directory

**Comment by mcornella** [comment]
Look at the logged errors:
```
ssh-keygen: /Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work: No such file or directory
```
The path it looks for is `/Users/bschmidt/.ssh//Users/bschmidt/.ssh/id_rsa_work`, and that's because you're not supposed to put the absolute path in the zstyle parameter setting, just the filenames.
```zsh
zstyle :omz:plugins:ssh-agent identities id_rsa_work id_rsa_work_github
```

**Comment by billyschmidt** [comment]
Oh duh, makes sense, thanks brother!
