### ISSUE TITLE
Terminal appends instead of updating individual lines

### ISSUE THREAD

**Issue by foundryspatial-duncan** [robbyrussell/oh-my-zsh#8270]
**Describe the bug**

Some commands that update a single line of output in bash (like a progress indicator, for example) end up appending new lines for every update in oh-my-zsh. This happen for *some*, but not all scripts.

`yarn install` is an example of a script that updates a line as expected.

`docker-compose up` is an example of a script that updates lines, but only the bottom line updates in the terminal. The output behaves like this:

```bash
Starting app-api ... 
Starting app-report ... 
Starting app-search ... 
Starting app-api # this line is duplicated?
Starting app-search api # this line is duplicated?
Starting app-elasticsearch ... 
Starting app-redis ... 
Starting app-report api # this line is duplicated?
Starting app-elasticsearch api # this line is duplicated?
Starting app-elasticsearch2 ... 
Starting app-elasticsearch2 api # this line is duplicated?
Starting app-search ... done api # this is the only line that actually changes in the terminal output
```

**To Reproduce**

**Expected behavior**

In the docker-compose example above, there should only be 5 lines:

```bash
Starting app-api ... 
Starting app-report ... 
Starting app-search ... 
Starting app-elasticsearch ... 
Starting app-redis ... 
Starting app-elasticsearch2 ... 
```
...and each line should be updated in place with "..." and "done"

**Screenshots or recordings**

Here's a snippet of output from a vue-cli webpack build, where every update printed a new line:

```bash
10% building 6/9 modules 3 active ...mmi/node_modules/webpack/hot/emitter.j
10% building 6/10 modules 4 active ...les/webpack-dev-server/client/socket.
10% building 6/11 modules 5 active ...es/webpack-dev-server/client/overlay.
10% building 6/12 modules 6 active .../webpack-dev-server/client/utils/log.
10% building 6/13 modules 7 active ...-dev-server/client/utils/sendMessage.
10% building 6/14 modules 8 active ...ck-dev-server/client/utils/reloadApp.
10% building 6/15 modules 9 active ...-server/client/utils/createSocketUrl.
10% building 7/15 modules 8 active ...-server/client/utils/createSocketUrl.
10% building 8/15 modules 7 active ...-server/client/utils/createSocketUrl. 
11% building 9/15 modules 6 active ...-server/client/utils/createSocketUrl.
11% building 10/15 modules 5 active ...-server/client/utils/createSocketUrl
11% building 11/15 modules 4 active ...-server/client/utils/createSocketUrl
11% building 12/15 modules 3 active ...-server/client/utils/createSocketUrl
11% building 13/15 modules 2 active ...-server/client/utils/createSocketUrl
11% building 14/15 modules 1 active ...-server/client/utils/createSocketUrl 
11% building 15/16 modules 1 active ...v-server/client/clients/SockJSClient
```

I've seen this work as expected in oh-my-zsh, but it usually looks like the example above. I don't know what makes it work or not work.

**System:**
 - OS: Ubuntu 18.04
 - Zsh version 5.4.2
 - Terminal emulator Tilix 1.1.7 - I've also seen this behavior in hyper.is, and on iterm2 on MacOS

**Additional context**

There's a pretty good chance this is a problem with zsh itself, and not specific to oh-my-zsh, but

**Comment by mcornella** [comment]
Check if running `zsh -f` to bypass ohmyzsh still manages to produce this. Also, check the value of `$TERM` when it happens and when it doesn't.

**Comment by foundryspatial-duncan** [comment]
Cheers, I didn't know about `zsh -f` - it does indeed happen the same way in plain zsh.
My `$TERM` value is `xterm-256color`, if that makes a difference. If this is just a zsh thing, we can close this issue and I'll try to _take it upstream_ :man_shrugging:

**Comment by mcornella** [comment]
From my experience, it could also be that there's not enough horizontal room to print all the message in one line. To "refresh" the line written, the trick is to print a special character sequence that tells the terminal to put the cursor at the beginning of the line. If there's not enough room, the line spans two or more lines, and the beginning of the line ends up being one line down. So try to play with the window width.
