### ISSUE TITLE
Get 'main "$@": Invalid host name.' when I install oh-my-zsh

### ISSUE THREAD

**Issue by 1lin24** [robbyrussell/oh-my-zsh#8274]
environment:
    centos7

I try install oh-my-zsh by:

`wget sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"`

but got an error: "$@": Invalid host name.' .

And I couldn't jump to first letter by `ctrl+a` after it.

I have changed my hostname by `hostnamectl set-hostname new_host_name` command.  Is that what caused this incident? But I forgot the host name before.

Need you help, thank you first.

**Comment by mcornella** [comment]
You're using wget twice? The command should read `sh -c "$(wget ...)"`, without the first wget.
