### ISSUE TITLE
Themes not working properly in iTerm2 on MacOS Catalina (10.15)

### ISSUE THREAD

**Issue by scporse** [robbyrussell/oh-my-zsh#8276]
I tried to switch theme to agnoster and it looks far from what I see on the wiki page:

![image](https://user-images.githubusercontent.com/30633152/66998574-c75cee00-f0d4-11e9-8d2b-814af9599120.png)

To remedy this, I tried reinstalling oh-my-zsh, installing powerline fonts (even manually adding the fontconfig, as per https://github.com/powerline/fonts#fontconfig) but these things have not done the trick.

What might be the problem here?

Bonus question: Is there any plugin for oh-my-zsh that supports changing themes on-the-fly when starting an ssh connection and again, when that session is exited?

Edit: Forgot to include my zsh version,so here it is: zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by scporse** [comment]
Update: 
It seems I have got the theme working now, by enabling "Use built-in Powerline glyphs" in iTerm preferences > Profiles > Text menu.

My other question still stands, however, but I'll create a new issue on that and close this one.

**Comment by mcornella** [comment]
When you start an ssh session you use the login shell and shell settings of the remote machine. Simply set up a theme on that remote machine and you'll have the change automatically.

**Comment by scporse** [comment]
Thanks for the suggestion but what you propose it's not quite what I'm
looking for.

What I need is for my local iterm theme to automatically change, anytime
the command "ssh" is issued, and then change back again upon exit of the
ssh session.
I know something like this is possible, because I had it working in the
native MacOS terminal.
So I'll just have to find the way to make it work with iterm zsh.

**Comment by mcornella** [comment]
You'll have more success asking in the iTerm2 issue tracker: https://gitlab.com/gnachman/iterm2/issues.
