### ISSUE TITLE
[cargo completion] __get_package_names not defined

### ISSUE THREAD

**Issue by bjorn3** [robbyrussell/oh-my-zsh#8283]
**To Reproduce**

1. Enable plugin `cargo`
2. Try to complete `cargo update -p`
3. See error: `_arguments:463: command not found: __get_package_names`

**Expected behavior**

It doesn't error. I am fine with this not completing at all, or with this completing without error.

**Comment by mcornella** [comment]
Try `rm $ZSH_COMPDUMP` and restart the terminal.

**Comment by mcornella** [comment]
Disregard my previous post. I've updated the completion file. Upgrade, `rm $ZSH_COMPDUMP` and restart and it should not error anymore.

**Comment by bjorn3** [comment]
Thanks for fixing this in 05dfd0ae8520e58e852c574f55c83fe6f49fb189.
