### ISSUE TITLE
cannot move '10-powerline-symbols.conf' How i can FIX it!!!

### ISSUE THREAD

**Issue by ReDCeNTipeDe** [robbyrussell/oh-my-zsh#8287]
I use on Termux in android i type a patch install and i stuck  at 10-powerline-symbols.conf file Help me plss!
![Screenshot_20191019_113155](https://user-images.githubusercontent.com/43487032/67137771-a4f9da80-f264-11e9-86c4-979404309d3e.png)

**Comment by mcornella** [comment]
You need to create that directory with `mkdir -p`, that's why you get a "no such file or directory" error.
