### ISSUE TITLE
pvogfddififiificid

### ISSUE THREAD

**Issue by philipnightwolf** [robbyrussell/oh-my-zsh#8288]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or recordings**

**System:**
 - OS: [e.g. macOS]
 - Zsh version [e.g. 5.6]
 - Terminal emulator [e.g. iTerm2]

**Additional context**

**Comment by mcornella** [comment]
![white guy blinking confused gif](https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif).
