### ISSUE TITLE
macOs Catalina

### ISSUE THREAD

**Issue by limahatzl** [robbyrussell/oh-my-zsh#8291]
I have installed oh-my-zsh.

When I open terminal is asking my zsh password since I updated to macOS Catalina and I receive an error because is su command and not sudo.

The main thing: i don't want to receive this msg all the time when I open the terminal.

option 1: i will need to remove oh-my-zsh
option 2: how do i fix that?

ps: before I had updated to macOS Catalina it was everything working fine...

#7956

**Comment by JonLittleIT** [comment]
same here.

**Comment by mcornella** [comment]
ohmyzsh doesn't run su I believe. Can you post your zshrc file?

**Comment by limahatzl** [comment]
> ohmyzsh doesn't run su I believe. Can you post your zshrc file?

thank you so much.

I have no idea how su command end up on my zshrc file after I updated the OS.
I removed it and I don't have the problem anymore.
