### ISSUE TITLE
WSL startup parsing errors

### ISSUE THREAD

**Issue by ErikBrendel** [robbyrussell/oh-my-zsh#8295]
**Describe the bug**
When opening a Terminal, some parsing errors appear:

`/home/erik/.oh-my-zsh/lib/misc.zsh:2: command not found: ^M`
`/home/erik/.oh-my-zsh/lib/misc.zsh:36: parse error near '\n'`

I cannot find any problems with my terminal, so this should just be considered as an annoying bug

**To Reproduce**
- open up a new terminal (in any folder, or even embedded into an IDE)

**Expected behavior**
- no parsing errors appear

**Screenshots or recordings**
![error](https://user-images.githubusercontent.com/11018565/67190942-21b9bf80-f3f1-11e9-880a-0a29fc304f94.PNG)

**System:**
 - OS: Windows 10 / WSL Ubuntu 18.04
 - Zsh version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
- oh-my-zsh version:  a7c740b1d7d0033c6de118439c7935962b2a5c2a (recent master at the time of writing this)

**Comment by mcornella** [comment]
See the workaround: https://github.com/robbyrussell/oh-my-zsh/issues/4069#issue-89607351
