### ISSUE TITLE
Custom path for a theme?

### ISSUE THREAD

**Issue by asc11cat** [robbyrussell/oh-my-zsh#8298]
Is there any way to do it?

for example:
`ZSH_THEME="~/dotfiles/zsh/themes/themenamehere"`

**Comment by VBelozyorov** [comment]
Why not to use symlink inside default path?

**Comment by mcornella** [comment]
You can override ZSH_CUSTOM to `~/dotfiles/zsh`, then use `ZSH_THEME="themenamehere"`. See [Customization](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization). Otherwise, you can just source the theme yourself after ohmyzsh is sourced.
