### ISSUE TITLE
How to start showing git branch only while in repository's root

### ISSUE THREAD

**Issue by VBelozyorov** [robbyrussell/oh-my-zsh#8300]
As far as I understand, it's core of `oh-my-zsh` (not `git` plugin) which showing current git branch as part of terminal prompt? 

I want to change this behavior and see branch in prompt only while current directory is repository's root (has `.git` folder). When I'll go deeper in folder structrure I want more shorter prompt.

How can I achieve this? Can I override something and not break oh-my-zsh update mechanism?

**Comment by VBelozyorov** [comment]
Ok, I realized that it's theme responsible for that prompt, so I can override it, I suppose.

**Comment by VBelozyorov** [comment]
Will leave it here just in case.

In my case it is `agnoster` theme. There is `prompt_git()` function in it. So to achieve what I want I've changed first condition inside this function to:
```
  if [ "$(find ./ -maxdepth 1 -name '.git' | wc -l)" = 0 ] || [ "$(git config --get oh-my-zsh.hide-status 2>/dev/null)" = 1 ] ; then
    return
  fi
```

**Comment by mcornella** [comment]
You can use `-d .git` which checks if there's a .git folder in the current directory. In your case, negated with `!`.
```zsh
  if [ ! -d .git ] || [ "$(git config --get oh-my-zsh.hide-status 2>/dev/null)" = 1 ] ; then
    return
  fi
```

**Comment by VBelozyorov** [comment]
Whoa! It's much simpler :)
