### ISSUE TITLE
SSL Certificate Problem

### ISSUE THREAD

**Issue by LORDTEK** [robbyrussell/oh-my-zsh#8321]
I am trying to install oh-my-zsh to my new NetBSD system after install git, zsh, curl and wget.
When I put `sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"` then error is: `curl: (60) SSL certificate problem: unable to get local issuer certificate More details here: https://curl.haxx.se/docs/sslcerts.html`
Then I put -k parameter to suppress ssl problem for curl but then the new error while cloning is: `fatal: unable to access 'https://github.com/robbyrussell/oh-my-zsh.git/' : SSL certificate problem: unable to get local issuer certificate `

**Comment by mcornella** [comment]
I think this is due to you not having root certs installed. I'm not familiar with NetBSD but maybe this helps: https://www.cambus.net/installing-ca-certificates-on-netbsd/

**Comment by LORDTEK** [comment]
for cURL the solution is: `-k` or `--insecure`
for git the solution is: `git config http.sslVerify false`

**Comment by mcornella** [comment]
This opens the door to Man in the Middle attacks. Try the link I posted before doing that.

**Comment by wowitsjack** [comment]
> This opens the door to Man in the Middle attacks. Try the link I posted before doing that.

The link you posted does not work.

Git still fails.

**Comment by lvcianob** [comment]
Or just "pkgin install mozilla-rootcerts-openssl" as an alternative. Works pretty well on my newly installed 9.2 machine.
