### ISSUE TITLE
cd + tab doesn't work

### ISSUE THREAD

**Issue by yongjin-shin** [robbyrussell/oh-my-zsh#8323]
I am using zsh under ubuntu 18.04 ( zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
After updating to the latest version, whenever using "cd + tab" i.e. cd Docu + tabl, 
I got this error

```
_tags:comptags:36: nesting level too deep
_tags:comptry:51: no tags registered
_tags:comptry:51: no tags registered
_tags:comptry:51: no tags registered
_tags:comptry:55: no tags registered
_tags:comptags:60: nesting level too deep
_tags:comptags:67: nesting level too deep
_tags:comptags:36: nesting level too deep
_tags:comptry:51: no tags registered
_tags:comptry:51: no tags registered
_tags:comptry:51: no tags registered
_tags:comptry:55: no tags registered
_tags:comptags:60: nesting level too deep
_tags:comptags:67: nesting level too deep
_tags:comptags:36: nesting level too deep
_tags:comptry:51: no tags registered
_tags:comptry:51: no tags registered
_tags:comptry:51: no tags registered
_tags:comptry:55: no tags registered
_tags:comptags:60: nesting level too deep
_tags:comptags:67: nesting level too deep
```

Checked that bash is okay. So I wonder whether the error comes from zsh.
Thanks!

**Comment by sanskar11** [comment]
Can you please attach a screenshot of the issue.

**Comment by mcornella** [comment]
You can record a trace of the completion script by trying to complete the cd command, but instead of pressing tab using `CTRL`+`X`, then `?`. It should say something like
```
$ cd
Trace output left in /tmp/zsh5853cd3 (up-history to view)
```
Post the trace file generated (`/tmp/....`).

**Comment by yongjin-shin** [comment]
Hi, Someway somehow after updating either ubuntu or zsh, Everything is okay now.
Thanks a lot!

**Comment by guilhermesam** [comment]
Hello, in my case, zsh-syntax-highlighting created a lot of lines at the end of .zshrc file, like:

<pre><code>
source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
...
</code></pre>

This was causing a slow opening of the file and probably overflow when using the Tab. Removing all these lines manually worked for me.

**Comment by gregWierzba** [comment]
I think 
`echo "source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$HOME/.zshrc"`
in .zshrc might be the reason.

**Comment by DaywisonSilva** [comment]
> Hello, in my case, zsh-syntax-highlighting created a lot of lines at the end of .zshrc file, like:
> 
> ```
> 
> source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> source /home/wabbajack/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
> ...
> ```
> 
> This was causing a slow opening of the file and probably overflow when using the Tab. Removing all these lines manually worked for me.

How can i stop it?

**Comment by rwmitchell** [comment]
You were only supposed to do the echo once in your present shell, not every time  in a startup script
