### ISSUE TITLE
Permission denied when accessing .zshrc

### ISSUE THREAD

**Issue by tripol** [robbyrussell/oh-my-zsh#8324]
I saw a similar [issue](https://github.com/robbyrussell/oh-my-zsh/issues/3291) closed but he complainant got a different result from mine when he entered the `ls -l $HOME/.zshrc` command.

This is the message I got when I entered that command:
`-rw-r--r--@ 1 ekanemeno  staff  3571 Oct 26 09:50 /Users/ekanemeno/.zshrc`

What is `staff`? and can that be the issue why I'm getting my permission denied?

My specs:
Laptop: Macbook Pro
Terminal: Hyper.is

**Comment by Hero9909** [comment]
the unix permission system contains uses 3*3bytes to save permissions. All three parts are ordered by **r** ead **w** rite e**x**ecute. At the beginning is a underscore or an d. Which says whats the type of this entry. Either file or **d** irectory. 

The first part is for the owner , the second shows the permissions for the users which not owning the file but are in the same group as the file and the last is for anyone else. 

as ekanemeno is owning the file l, hes abled to read or write in the file. The users of the staff group are abled to read it , the same goes for anyone else.

So i think ekanemeno is your user. so you should be abled to change this file. 

Are you trying to change some options? Like "$ vim .zshrc "
Or "$ nano .zshrc"

If you want to refresh your shell options you should do "$ source .zshrc".

**Comment by tripol** [comment]
Thanks @Hero9909, your explanation was useful. I also got more information here:
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzahz/rzahzchmod.htm
