### ISSUE TITLE
error occure while using command read -p:read: -p: no coprocess

### ISSUE THREAD

**Issue by blueboz** [robbyrussell/oh-my-zsh#8330]
**Describe the bug**
error occure while input shell commands below:
➜ read -p "test "
![截屏2019-10-29上午10 40 05](https://user-images.githubusercontent.com/12193140/67733162-7a640a80-fa38-11e9-9b44-52185601be14.png)

**To Reproduce**
1. zsh
2. Run command read -p "test"
3. See error

**Expected behavior**
no error

**Screenshots or recordings**

![Jietu20191029-105028](https://user-images.githubusercontent.com/12193140/67733993-db8cdd80-fa3a-11e9-9229-aa029d8be72f.gif)

**System:**
 - OS: macOS
 - Zsh version :zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator [e.g. iTerm2]

**Additional context**

**Comment by mcornella** [comment]
zsh's read is a builtin that has different options than the bash one. Specifically, `-p` tells read to read the input from a coprocess. See https://superuser.com/a/556006/545959
