### ISSUE TITLE
Fabric: Autocompletion no longer working

### ISSUE THREAD

**Issue by amrishparmar** [robbyrussell/oh-my-zsh#8337]
**Describe the bug**
Looks like [recent changes to Fabric have broken autocompletion](https://github.com/robbyrussell/oh-my-zsh/commit/9d790ea60ce1d3af265dfc05b77d77bd94b801d7).

When pressing TAB to complete a line it gives an error from `awk` that `return` is not in a function.

**To Reproduce**
Type `fab ` followed by the prefix of any fab command and press TAB

**Expected behavior**
The command is successfully autocompleted, e.g. in the example below the command should complete to `fab helpers.check_warnings`

**Screenshots or recordings**
```
(ukf) ➜  deploy hg:(default) ✗ fab helpers.chawk: return not in function at source line 2
 context is
	    if (NF == 0 || NR == 1) >>>  return <<< 
awk: syntax error at source line 3
awk: illegal statement at source line 3
awk: return not in function at source line 2
 context is
	    if (NF == 0 || NR == 1) >>>  return <<< 
awk: syntax error at source line 3
awk: illegal statement at source line 3
awk: return not in function at source line 2
 context is
	    if (NF == 0 || NR == 1) >>>  return <<< 
awk: syntax error at source line 3
awk: illegal statement at source line 3        
```

**System:**
 - OS: macOS 10.14.6
 - Zsh version: 5.7.1
 - Terminal emulator: Terminal
 - Fabric: 1.14

**Additional context**
Worked fine prior to recent oh-my-zsh update

**Comment by mcornella** [comment]
That's my fault, it should be an `exit` instead of a return. It worked in GNU's version of awk.

Can you go to the file `$ZSH/plugins/fabric/_fab` and change the return in line 9 for an exit? Then, to test it, run `unfunction _fab; autoload -Uz _fab` and try again to complete fab.

**Comment by mcornella** [comment]
Scratch that, the keyword I was looking for is `next`. Try this command in a directory with a `fabfile.py`:
```zsh
fab -l 2>/dev/null | awk '{
    if (NF == 0 || NR == 1) next
    if (NF < 2) print $1
    else {
        docstring=substr($0, index($0,$2))
        gsub(":", "\\:", docstring)
        print $1":"docstring
    }
}'
```
