### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by sharon-yi** [robbyrussell/oh-my-zsh#8340]
I keep getting the error:
zsh: permission denied: /Users/**myname**/.zshrc

when i try to use ~/.zshrc

**Comment by sharon-yi** [comment]
I already have zsh and oh-my-zsh installed so i’m not sure what the actual problem is. I also have home brew installed? If that would do anything

**Comment by Peterkmoss** [comment]
Are you trying to open the config file? If so you have to specify an editor to do so in. E.g. `nano ~/.zshrc`.

**Comment by sharon-yi** [comment]
Yep just had to specify an editor haha .. thank you!
