### ISSUE TITLE
Allow for global oh-my-zsh installation

### ISSUE THREAD

**Issue by ElSamhaa** [robbyrussell/oh-my-zsh#8343]
**Describe the solution you'd like**

I'd like to see an option for global installation of `oh-my-zsh`, i.e to install to a local system directory, and inject `.zshrc` with a `custom` directory to every user with a home directory.

**Comment by mcornella** [comment]
This is already possible if you set the `ZSH` variable before calling the script. Then, on each user you want them to use it, change the zshrc file to point to the `$ZSH` folder you installed it on.

You might have troubles with `$ZSH_CACHE_DIR`, which needs to be writable by the user running OMZ. You can either make it world-writable or set it to a folder controlled by each user, like `$HOME/.cache/ohmyzsh` or something like that.

**Comment by DamianRivas** [comment]
Correct me if I'm wrong, but as long as we set `$ZSH_CACHE_DIR` before the `source $ZSH/oh-my-zsh.sh` command it should be fine, correct?

**Comment by carlosala** [comment]
Exactly!
