### ISSUE TITLE
odd characters after prompt with iterm2 + powerlevel10k theme

### ISSUE THREAD

**Issue by squarewave24** [robbyrussell/oh-my-zsh#8349]
i've setup powerline fonts with powerline10k theme. 

i seem these chars on dirty git branches: 

```
~/dev/my_folder  my_branch_name ⇡23 *1 
```

not sure if this is an issue with config, wrong font version, wrong theme or something else. 

`.zshrc`:
```
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="awesome-patched"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

i tried a few powerline fonts.. including MesloGS NF, and SourcePro for PowerLine but no luck 

![image](https://user-images.githubusercontent.com/843437/68088489-cb577280-fe2d-11e9-9a4d-ac8f8b373c27.png)

![image](https://user-images.githubusercontent.com/843437/68088527-1a050c80-fe2e-11e9-82ff-9e9c0423636e.png)

**Comment by mcornella** [comment]
Issues with powerlevel10k go to the powerlevel10k repository. But you might find similar issues with iTerm2 and powerline in this repository if you search for them.
