### ISSUE TITLE
How to disable fuzzy tab completion?

### ISSUE THREAD

**Issue by littlesandra88** [robbyrussell/oh-my-zsh#8355]
If I do this

    mkdir /tmp/test
    cd /tmp/test
    touch config
    ls on[tab]

then Oh My ZSH will replace `on` with `config` which I don't want.

I have tried to `rm $ZSH/plugins/fzf` which didn't work, and it seams wrong to edit the source for OhMyZSH, which also would result in I having to redo it when updating OhMyZSH.

**Question**

How can I disable this fuzzy file completion?

**Comment by mcornella** [comment]
There isn't an option in ohmyzsh but you can set this on your zshrc after OMZ is sourced:
```zsh
zstyle ":completion:*" matcher-list 'r:|=*' 'r:|=*'
```
