### ISSUE TITLE
[OSX plugin] Lyrics for Spotify song being currently played

### ISSUE THREAD

**Issue by bartekpacia** [robbyrussell/oh-my-zsh#8359]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
My feature is related to the `osx` plugin, particularly `spotify` part of that plugin. Basically, I created a small utility that displays the lirycs of song being currently played on Spotify.

**What am I asking for?**
I'm not asking for the merge of my plugin with the repo - it requires `NodeJS` and its `node_modules` is quite heavy, and it seems to me that it doesn't fit well with the overall philisophy of oh-my-zsh plugins . I just think it'd be cool and useful for other people to know that such a "lyrics plugin exists" – link placed [here](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/osx) pointing to [my lyrics plugin repo](https://github.com/bartekpacia/lyrics-buddy) would be enough.

If you agree to do this, I'll submit a PR.

:)

**Comment by mcornella** [comment]
There's a special place in the wiki for that: https://github.com/robbyrussell/oh-my-zsh/wiki/External-plugins.
