### ISSUE TITLE
I get this error: omz_history:fc:13: no such event: 1

### ISSUE THREAD

**Issue by thomasd3** [robbyrussell/oh-my-zsh#8360]
This is a new install on a brand new AWS CentOS.

Upon logging in to the system, I get this error.

I have done a search and there are a few posts and some old bugs dating a few years back but I can't find anything 'modern' about it. There were some discussions about fc being an alias, but again, these are old discussions, so I would assume whatever the problem was, it must have been sorted out.

I have no clue where this comes from.

How can I troubleshoot this?

**Comment by mcornella** [comment]
You could [capture a trace of the zsh initialization](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#other-problems) (the command that runs exit) and grep the error there to see where it was called. I can help you with that if you post the trace file.

**Comment by thomasd3** [comment]
I just did:
    zsh -xvic exit &> ~/omz-debug.log

and put the result here: https://pastebin.com/VDWPF5sU

**Comment by mcornella** [comment]
The call comes from `/etc/bashrc`:
```
+/etc/bashrc:38> omz_history -a
+omz_history:1> local clear list
+omz_history:2> zparseopts -E 'c=clear' 'l=list'
+omz_history:4> [[ -n '' ]]
+omz_history:8> [[ -n '' ]]
+omz_history:13> [[ -a = *[0-9]* ]]
+omz_history:13> fc -l -a 1
omz_history:fc:13: no such event: 1
```
which is sourced from `/root/.bashrc`:
```
# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
+/root/.bashrc:10> [ -f /etc/bashrc ']'
+/root/.bashrc:11> . /etc/bashrc
```
which is sourced in `.zshrc`:
```
source ~/.bashrc
+/root/.zshrc:101> source /root/.bashrc
```

There is something wrong about your loading process. `/etc/*` files should be sourced before user rc files, and bashrc shouldn't be sourced in zshrc. If you want to share settings between bash and zsh, put it in a separate file and source it from bashrc and zshrc.

**Comment by ehyyoj** [comment]
> The call comes from `/etc/bashrc`:
> 
> ```
> +/etc/bashrc:38> omz_history -a
> +omz_history:1> local clear list
> +omz_history:2> zparseopts -E 'c=clear' 'l=list'
> +omz_history:4> [[ -n '' ]]
> +omz_history:8> [[ -n '' ]]
> +omz_history:13> [[ -a = *[0-9]* ]]
> +omz_history:13> fc -l -a 1
> omz_history:fc:13: no such event: 1
> ```
> 
> which is sourced from `/root/.bashrc`:
> 
> ```
> # Source global definitions
> if [ -f /etc/bashrc ]; then
>     . /etc/bashrc
> fi
> +/root/.bashrc:10> [ -f /etc/bashrc ']'
> +/root/.bashrc:11> . /etc/bashrc
> ```
> 
> which is sourced in `.zshrc`:
> 
> ```
> source ~/.bashrc
> +/root/.zshrc:101> source /root/.bashrc
> ```
> 
> There is something wrong about your loading process. `/etc/*` files should be sourced before user rc files, and bashrc shouldn't be sourced in zshrc. If you want to share settings between bash and zsh, put it in a separate file and source it from bashrc and zshrc.

Great! I solved  this annoying problem by remove `source ~/.bash_profile` in `~/.zshrc`
