### ISSUE TITLE
Add alias for git merge --no-edit to git plugin

### ISSUE THREAD

**Issue by lgedeon** [robbyrussell/oh-my-zsh#8362]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Yes, the plugin simply named "git"

**Describe the solution you'd like**
I frequently type "git merge --no-edit". I saw many other aliases, but did not see this specific one. It would be great to add that.

**Comment by larson-carter** [comment]
@lgedeon I don't think that this is necessary to add to the code of oh-my-zsh simply due to the specifics of your request.. You can look into the link that I have attached below to see if that fixes your problem.

https://githowto.com/aliases

**Comment by lgedeon** [comment]
It is true that I could add my own, but the point of the git plugin for omz is to add aliases for git commands and this is one I use a lot. It would be nice to have.

**Comment by larson-carter** [comment]
@lgedeon Do you have any suggestions on what a solution could possibly look like? It would obviously need to be customizable for all users because they would not want an alias to do the exact same thing that you would want.

**Comment by lgedeon** [comment]
Here is a list of all the alias that are already in the plugin: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git. I was thinking that `gmn` could be used for `git merge --no-edit`

**Comment by mcornella** [comment]
[We already have many aliases](https://github.com/robbyrussell/oh-my-zsh/issues/5721), which means we have to be careful when adding one. In this instance, I think your particular workflow isn't that similar to the general userbase. I advise you to have a section in your zshrc file where you define aliases specifically useful to you.
