### ISSUE TITLE
Not able to install ohmyzsh as urls return 404 Not Found

### ISSUE THREAD

**Issue by ferdef** [robbyrussell/oh-my-zsh#8382]
No matter if I execute 

```sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"```

or 

```sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"``` 

I will receive a certification error. If I bypass certificates using:

```sh -c "$(curl -k -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"```

I receive a `404 NOT FOUND

Using this other url:

```sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"```

gives the same result.

**Comment by mcornella** [comment]
Are you using perhaps a proxy that redirects github.com? That sounds like a MitM in action... Try using a different Internet connection?

**Comment by ferdef** [comment]
Just tested on 2 different OS (Linux and Windows) and also used 2 different networks (Home Wifi and Phone Connection)

Not able to connect on any of them

**Comment by teclaelvis01** [comment]
the same happens to me.

Help !!!

**Comment by teclaelvis01** [comment]
> Just tested on 2 different OS (Linux and Windows) and also used 2 different networks (Home Wifi and Phone Connection)
> 
> Not able to connect on any of them

The solution for now is execute the nexts steps:

1.- git clone https://github.com/robbyrussell/oh-my-zsh.git
2.  cd oh-my-zsh/tools
3.- sh install.sh


And ready !!!

**Comment by mcornella** [comment]
This is something to be reported to GitHub support, I can't really help you there.

**Comment by mcornella** [comment]
If you're doing this from Pepephone (Spain) there seems to be an [issue with their DNS records](https://twitter.com/gonzaloserrano/status/1194983239708004352).
