### ISSUE TITLE
After update message "tput: unknown terminal "true" and tmux not work

### ISSUE THREAD

**Issue by Dmitryi** [robbyrussell/oh-my-zsh#8389]
Received the update and immediately installed it. I use xterm
Fedora 31, tmux. Tmux is no longer able to create splits and windows.

When launching terminals, this message "tput: unknown terminal "true"

**System:**
 - OS: Fedora 31 x64
 - Zsh version 5.7.1 (x86_64-redhat-linux-gnu)
 - Terminal emulator xterm

**Comment by mcornella** [comment]
This sounds like you ran `TERM=true` somewhere. Try looking at your zshrc file.

**Comment by Dmitryi** [comment]
You're right. 
I changed in .zshrc  from ZSH_TMUX_FIXTERM="true" to "false" and everything works.
Thank you.

**Comment by mcornella** [comment]
That shouldn't be the problem. The tmux plugin uses the `$ZSH_TMUX_TERM` variable to set `$TERM`, maybe you're overriding that? Can you post your zshrc file?
