### ISSUE TITLE
How to change order options of auto correction prompt?

### ISSUE THREAD

**Issue by thamaraiselvam** [robbyrussell/oh-my-zsh#8398]
Currently zsh prompt as follows when typo in  command

```
zsh: correct 'sl' to 'ls' [nyae]?
```

is that possible to change the order to `[ynae]` so when I press enter it will be executed.

**Comment by mcornella** [comment]
The prompt can be changed by tweaking the `$SPROMPT` variable (see [docs](http://zsh.sourceforge.net/releases.html), search for `SPROMPT`). Unfortunately, the behavior is baked in the zsh binary itself. As it says in the docs, previously `SPACE` or `TAB` where accepted as yes; now, they are invalid choices. [See also: Parameters](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-SPROMPT).
