### ISSUE TITLE
Possible to not expand wild card matches?

### ISSUE THREAD

**Issue by littlesandra88** [robbyrussell/oh-my-zsh#8404]
OMZ expands wild card matches like so:

```
➜  /tmp touch a aa aaa
➜  /tmp ls a* [TAB]
➜  /tmp ls a aa aaa
```

**Question**

Is it possible to disable this expansion, so it acts like Bash, where tabbing would list the files that match?

**Comment by mcornella** [comment]
If you leave out the star (`*`) you'll get the same thing. The default Zsh tab behavior is to try to expand the parameter so if it's a wildcard, a variable or a bang-expression (i.e. `!$`) it will expand them.

**Comment by littlesandra88** [comment]
Yes, that is a good point. I have been using Bash for +10 years, so I constantly make that mistake, now that I moved to OMZ. So I'd really like if it could be disabled.

Is that difficult to accomplish?

**Comment by mcornella** [comment]
You could bind `complete-word` to the tab key instead, but you still won't get the completion menu that bash provides. Instead, zsh won't do anything (unless there are files starting with the literal `a*`). If you still want to do this, here's the command:
```zsh
bindkey '^I' complete-word
```
