### ISSUE TITLE
Errors while executing /.zshrc

### ISSUE THREAD

**Issue by jiangbryn** [robbyrussell/oh-my-zsh#8412]
I have the same problem with this issue https://github.com/robbyrussell/oh-my-zsh/issues/6092
I have follow all the step in it, but still
/Users/xx/.oh-my-zsh/oh-my-zsh.sh: line 23: autoload: command not found
/Users/xx/.oh-my-zsh/oh-my-zsh.sh: line 41: syntax error near unexpected token `('
/Users/xx/.oh-my-zsh/oh-my-zsh.sh: line 41: `for plugin ($plugins); do'

**Comment by mcornella** [comment]
See https://github.com/robbyrussell/oh-my-zsh/issues/6092#issuecomment-457270449. You're running bash instead of `zsh`.
